### ISSUE TITLE
Account 结构体重构

### ISSUE THREAD

**Issue by Xhofe** [alist-org/alist#1024]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

- 现有的Account一个struct中字段过多，重用行较差，大部分网盘只需要少量字段，造成了存储冗余；
- 添加新字段时需要修改Account结构体，拓展性较差；

### Suggested solution / 实现思路

- 将Account改为Interface，在基本账户中抽象相同信息
- 其它各个网盘需要的字段在driver中定义
- driver返回字段列表时直接从结构体中反射得到，不必再手动返回

**Comment by foxxorcat** [comment]
很有必要，要不然每次都很纠结是增加新字段还是复用字段

**一点小建议**
- 可以使用结构体中的Tag来定义其他属性（列如默认值，是否必须）
- 直接通过反射得到数据类型，而不是手动指定
- 接口可以参考gorm中的自定义类型，要求实现Value()和Scan()

**Comment by Xhofe** [comment]
> 很有必要，要不然每次都很纠结是增加新字段还是复用字段
> 
> **一点小建议**
> 
> * 可以使用结构体中的Tag来定义其他属性（列如默认值，是否必须）
> * 直接通过反射得到数据类型，而不是手动指定
> * 接口可以参考gorm中的自定义类型，要求实现Value()和Scan()

感觉要放弃了 越改越乱了😫 太菜了

**Comment by foxxorcat** [comment]
的确,这工作量和重构项目差不多了
而且直接改数据库结构不太友好,或许可以考虑在v3版本重新设计一下程序结构
