### ISSUE TITLE
希望增加对 SMB 的支持

### ISSUE THREAD

**Issue by RebornQ** [alist-org/alist#1038]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

内网有个 SMB 文件共享，我想转为 Alist 的 API 接口进行访问，希望能支持~

**Comment by freefly22** [comment]
我也遇到了同样的需求，本地插USB的硬盘是不是只能SMB访问？
