### ISSUE TITLE
希望增加对jottacloud.com的支持

### ISSUE THREAD

**Issue by fantastlcok** [alist-org/alist#1070]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

这是一家挪威公司的云存储服务提供商。
这个网盘国内访问速度不错，可以生成直连，价格也便宜。

### Suggested solution / 实现思路

Rclone已实现部分，并在代码内标注了API。

https://github.com/rclone/rclone/tree/9e2fbe0f1a9314e1330b4adc9d69de137be12ee6/backend/jottacloud

通过获取刷新token，就能生成直链。

**Comment by dmlt** [comment]
59挪威克朗=40.8457人民币
不便宜呀 老兄。哈哈哈哈
