### ISSUE TITLE
self-hosted onlyoffice support

### ISSUE THREAD

**Issue by SINOPW** [alist-org/alist#1075]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

office documentation preview/edit

### Suggested solution / 实现思路

self-hosted onlyoffice

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
