### ISSUE TITLE
希望支持华为云盘和小米云盘

### ISSUE THREAD

**Issue by wh1235** [alist-org/alist#1121]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

华为云盘链接：https://cloud.huawei.com/
小米云盘链接：https://i.mi.com/
这两个我都有使用过，还是可以的，也有许多我曾经备份过得数据，并且不容易倒闭。

**Comment by geeklihui** [comment]
+1 华为云盘对于华为手机用户来说很有必要，照片备份、手机备份、微信备份都靠这个，但给的套餐又太不合适，50G太小200G太贵不如加一点上2T，但2T又完全用不到，就很浪费
已经在2T档位上花了468*3接近1500块钱了，但实际根本只能用到500G左右，很心痛......要是能通过Alist挂载，然后备份NAS数据过去就很香了
