### ISSUE TITLE
请求添加自定义前端入口

### ISSUE THREAD

**Issue by 253551464** [alist-org/alist#1129]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我现在使用nginx反代alist直接占用一个域名，希望可以和网站共存。例如我的网址是abc.com是一个博客，而abc.com/alist是alist前端入口，abc.com/alist/dav是alist的webdav入口，，，是我记错了吗，我好像记得以前的版本有自定义入口这个功能的

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
