### ISSUE TITLE
Visitor WebDAV问题

### ISSUE THREAD

**Issue by anwen-anyi** [alist-org/alist#1143]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.2

### Describe the bug / 问题描述

Alist  `Visitor WebDAV username/password`  都是默认的虽然是游客账号,但是没权限删除文件 不过还是可以看到`加密`的文件,文件夹,  **`在元信息设置了隐藏的文件/文件夹`**  倒是看不到  也是可以复制走的~建议给密码也设置成随机的

### Reproduction / 复现链接

null url

### Logs / 日志

```shell
null log
```

**Comment by Xhofe** [comment]
已随机
