### ISSUE TITLE
音频播放LRC歌词支持

### ISSUE THREAD

**Issue by haoduck** [alist-org/alist#1145]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

不知道音频播放器能不能支持LRC歌词，是一个很棒的功能。

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
