### ISSUE TITLE
迅雷网盘已失效

### ISSUE THREAD

**Issue by CatCars** [alist-org/alist#1154]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.2

### Describe the bug / 问题描述

挂载迅雷网盘，已获取captcha token
文件可以正常显示出来.但是无法下

### Reproduction / 复现链接

![This is an image](https://i.ibb.co/xsHSXy6/image.png)

### Logs / 日志

[GIN] 2022/05/25 - 13:23:24 | 500 |    164.2808ms |       127.0.0.1 | GET      "/d/迅雷网盘/共享文件夹/Top Gun _ Maverick (2022) 1080p HDCAM x264 AAC - QRips.mkv"
ERRO[2022-05-25 13:23:24]

2022/05/25 13:23:24 [Recovery] 2022/05/25 - 13:23:24 panic recovered:
http: wrote more than the declared Content-Length
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/json.go:56 (0x115c45e)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:913 (0x11615b7)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:956 (0x117282f)
/source/server/common/common.go:49 (0x11727b2)
/source/server/controllers/proxy.go:66 (0x11782be)
/source/server/controllers/down.go:22 (0x1175824)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x117b212)
/source/server/middlewares/down.go:26 (0x117b12e)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x1169d81)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99 (0x1169d6c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x1168ea6)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241 (0x1168e89)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x1167f9d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489 (0x1167c25)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445 (0x1167784)
/usr/local/go/src/net/http/server.go:2916 (0x933dfa)
/usr/local/go/src/net/http/server.go:1966 (0x92edf6)
/usr/local/go/src/runtime/asm_amd64.s:1571 (0x6bb9c0)

**Comment by WangEdward** [comment]
需要在下载请求加入客户端的 UA 头

**Comment by zpljd258** [comment]
> 需要在下载请求加入客户端的 UA 头

请问如何添加呢？

**Comment by WangEdward** [comment]
不是，自己抓，下载的时候填下载客户端里

**Comment by Tomlin5537** [comment]
infuse也已经无法加载迅雷里面的内容

**Comment by zpljd258** [comment]
> infuse也已经无法加载迅雷里面的内容

我的还能加载

**Comment by karma-sun** [comment]
> > 需要在下载请求加入客户端的 UA 头
> 
> 请问如何添加呢？是将以下信息（信息来源于alist自带的迅雷网盘UA）添加到down_proxy_url吗？还是有什么特别的写法？
> 
> ANDROID-com.xunlei.downloadprovider/7.43.0.7998 netWorkType/WIFI appid/40 deviceName/Samsung_Sm-g9810 deviceModel/SM-G9810 OSVersion/7.1.2 protocolVersion/301 platformVersion/10 sdkVersion/220200 Oauth2Client/0.9 (Linux 4_0_9+) (JAVA 0)

这个UA，试了一下貌似依旧403 Forbidden啊

**Comment by foxxorcat** [comment]
可以下载器手动指定 ua AndroidDownloadManager/11 (Linux; U; Android 11; M2004J7AC)(链接不限速)
或者后台设置ua为  AndroidDownloadManager/11 (Linux; U; Android 11; M2004J7AC) 开代理,需要重启alist(链接限速)
最近没时间修复这个问题,这是临时解决方法

**Comment by michealhansun** [comment]
迅雷网盘，挂载后在线看视频提示“重新连接”

**Comment by zpljd258** [comment]
感谢开发者的努力，迅雷云盘在v2.6.1-0-geb15bce已经可以正常透过webdav使用！

但是看起来似乎需要打开webdav direct开关。这似乎会导致所有的流量通过部署alist的服务器进行转发。是否有任何一种可能在未来的更新中实现原生转发？

顺便一提，在v2.6.1-0-geb15bce中，**迅雷云盘透过webdav使用时，无法进行编辑文件名/上传类型的操作。仅能进行下载**。

**Comment by acegao9527** [comment]
> 感谢开发者的努力，迅雷云盘在v2.6.1-0-geb15bce已经可以正常透过webdav使用！
> 
> 但是看起来似乎需要打开webdav direct开关。这似乎会导致所有的流量通过部署alist的服务器进行转发。是否有任何一种可能在未来的更新中实现原生转发？
> 
> 顺便一提，在v2.6.1-0-geb15bce中，**迅雷云盘透过webdav使用时，无法进行编辑文件名/上传类型的操作。仅能进行下载**。

没解决的，还是老问题
