### ISSUE TITLE
对联想乐云的支持

### ISSUE THREAD

**Issue by wh1235** [alist-org/alist#1156]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

网盘链接:https://lecloud.lenovo.com/index
描述:一个出道不久的网盘，并且还在赠送会员，有许多空间可以有效利用和不限速，希望支持挂载。

**Comment by wh1235** [comment]
打算在哪个版本实现该功能呢?

**Comment by Xhofe** [comment]
> 打算在哪个版本实现该功能呢?

无计划

**Comment by wh1235** [comment]
那之后会有网盘增加吗？



---原始邮件---
发件人: "Noah ***@***.***&gt;
发送时间: 2022年6月2日(周四) 晚上10:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xhofe/alist] 对联想乐云的支持 (Issue #1156)




  
打算在哪个版本实现该功能呢?
  
无计划

**Comment by chenchen100** [comment]
出道不久？，很久了好吧，官方不支持webdav
