### ISSUE TITLE
天翼云盘已经失效

### ISSUE THREAD

**Issue by alechy** [alist-org/alist#1182]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

Docker

### Describe the bug / 问题描述

天翼云盘已经失效
报 get:错误

### Reproduction / 复现链接

request url: https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https%3A%2F%2Fcloud.189.cn%2Fmain.action 
[GIN] 2022/05/31 - 02:51:09 | 200 |  3.267020153s |  182.86.131.246 | POST     "/api/public/path"
[GIN] 2022/05/31 - 03:56:55 | 200 |      252.66µs |  123.14.248.156 | GET      "/1"
[GIN] 2022/05/31 - 03:57:02 | 200 |     196.872µs |    14.204.44.85 | GET      "/"
[GIN] 2022/05/31 - 03:57:27 | 200 |     588.564µs | 182.138.158.213 | GET      "/"
[GIN] 2022/05/31 - 03:57:37 | 200 |     245.424µs |  112.66.102.107 | GET      "/"
[GIN] 2022/05/31 - 03:57:38 | 200 |       185.7µs |   112.66.111.98 | GET      "/conf.js"
[GIN] 2022/05/31 - 04:48:02 | 200 |       1.916ms |  182.86.131.246 | GET      "/api/public/settings"
ERRO[2022-05-31 04:48:02] Invalid token                                
[GIN] 2022/05/31 - 04:48:02 | 200 |     213.013µs |  182.86.131.246 | GET      "/api/admin/settings?group=1"
[GIN] 2022/05/31 - 04:48:02 | 200 |     860.187µs |  182.86.131.246 | POST     "/api/public/path"
ERRO[2022-05-31 04:48:05] Invalid token                                
[GIN] 2022/05/31 - 04:48:05 | 200 |     182.076µs |  182.86.131.246 | GET      "/api/admin/settings?group=1"
[GIN] 2022/05/31 - 04:48:05 | 200 |    2.178777ms |  182.86.131.246 | GET      "/api/public/settings"
ERRO[2022-05-31 04:48:09] get page:  
status: 403 

### Logs / 日志

```shell
request url: https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https%3A%2F%2Fcloud.189.cn%2Fmain.action 
[GIN] 2022/05/31 - 02:51:09 | 200 |  3.267020153s |  182.86.131.246 | POST     "/api/public/path"
[GIN] 2022/05/31 - 03:56:55 | 200 |      252.66µs |  123.14.248.156 | GET      "/1"
[GIN] 2022/05/31 - 03:57:02 | 200 |     196.872µs |    14.204.44.85 | GET      "/"
[GIN] 2022/05/31 - 03:57:27 | 200 |     588.564µs | 182.138.158.213 | GET      "/"
[GIN] 2022/05/31 - 03:57:37 | 200 |     245.424µs |  112.66.102.107 | GET      "/"
[GIN] 2022/05/31 - 03:57:38 | 200 |       185.7µs |   112.66.111.98 | GET      "/conf.js"
[GIN] 2022/05/31 - 04:48:02 | 200 |       1.916ms |  182.86.131.246 | GET      "/api/public/settings"
ERRO[2022-05-31 04:48:02] Invalid token                                
[GIN] 2022/05/31 - 04:48:02 | 200 |     213.013µs |  182.86.131.246 | GET      "/api/admin/settings?group=1"
[GIN] 2022/05/31 - 04:48:02 | 200 |     860.187µs |  182.86.131.246 | POST     "/api/public/path"
ERRO[2022-05-31 04:48:05] Invalid token                                
[GIN] 2022/05/31 - 04:48:05 | 200 |     182.076µs |  182.86.131.246 | GET      "/api/admin/settings?group=1"
[GIN] 2022/05/31 - 04:48:05 | 200 |    2.178777ms |  182.86.131.246 | GET      "/api/public/settings"
ERRO[2022-05-31 04:48:09] get page:  
status: 403
```

**Comment by Xhofe** [comment]
duplicate with #1180

**Comment by jackcsq** [comment]
附议，天翼云盘已失效。我也进入不了。
状态提示：get page: status: 403 request url: https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https%3A%2F%2Fcloud.189.cn%2Fmain.action

**Comment by fmbfmbhh** [comment]
附议，我也有两天登不了了。
`get page: status: 403 request url: https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https%3A%2F%2Fcloud.189.cn%2Fmain.action redirect url:`

**Comment by Bobxyo** [comment]
天翼云盘改成Cloud189PC就可以了

**Comment by GoogleSuper** [comment]
我的改成Cloud189PC会弹图形验证码错误提示，无法登录

**Comment by michealhansun** [comment]
我改用189CloudPC 可以正常使用了
