### ISSUE TITLE
分秒帧Token时效

### ISSUE THREAD

**Issue by xlc520** [alist-org/alist#1192]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

分秒帧文档中说[​Token](https://alist-doc.nn.ci/docs/driver/mediatrack#token)有效期七天，通过抓包发现一个`tenant_access_token`
，不知道能不能增加有效期.
还有一个`x-sensors-anonymous-id`，不是知道可不可以，测试发现没啥卵用

>[​Token](https://alist-doc.nn.ci/docs/driver/mediatrack#token)
>有效期仅七天，登陆后获取

### Suggested solution / 实现思路

1.抓包任意一个`https://jayce.api.mediatrack.cn/v4/auth/tenant_access_token`请求之前的`Authorization: Bearer`字段token，一般是`u-`开头
2.在`https://jayce.api.mediatrack.cn/v4/auth/tenant_access_token`请求头携带上面抓到的token，请求体是`member_id`，发post，会返回一个`t-`开头的token，就是需要的获取资源文件token。

API-POST生成的Go代码，请求体在哪我也不知道，没学过Go：
```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

func main() {
	client := &http.Client{}
	req, err := http.NewRequest("POST", "https://jayce.api.mediatrack.cn/v4/auth/tenant_access_token", nil)
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("accept", "application/json, text/plain, */*")
	req.Header.Set("accept-encoding", "gzip, deflate, br")
	req.Header.Set("accept-language", "zh-CN,zh;q=0.9")
	req.Header.Set("authorization", "Bearer u-xxxxxxxxxxxxxxxxxxxxxx")
	req.Header.Set("content-length", "35")
	req.Header.Set("content-type", "application/json;charset=UTF-8")
	req.Header.Set("origin", "https://app.mediatrack.cn")
	req.Header.Set("referer", "https://app.mediatrack.cn/")
	req.Header.Set("sec-ch-ua", ""Chromium";v="21", " Not;A Brand";v="99"")
	req.Header.Set("sec-ch-ua-mobile", "?0")
	req.Header.Set("sec-ch-ua-platform", ""Windows"")
	req.Header.Set("sec-fetch-dest", "empty")
	req.Header.Set("sec-fetch-mode", "cors")
	req.Header.Set("sec-fetch-site", "same-site")
	req.Header.Set("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36")
	req.Header.Set("x-plat", "sona")
	req.Header.Set("x-sensors-referer", "https%3A%2F%2Fapp.mediatrack.cn%2Fwelcome%2FpasswordLogin%3Fcallback%3D%252F")
	req.Header.Set("x-sensors-utm", "%7B%7D")
	resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	bodyText, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s\n", bodyText)
}

```

### Additional context / 附件

![20220603100405454](https://user-images.githubusercontent.com/56480807/171773425-9c109345-5aaa-4e0f-81d9-00a8fd248884.jpg)

![20220603100527303](https://user-images.githubusercontent.com/56480807/171773433-d2517b31-1890-4d32-beb1-103acd01c7d4.jpg)

![20220603100937574](https://user-images.githubusercontent.com/56480807/171773439-02fccdca-94c9-4a79-b089-c6353cf8ecca.jpg)

**Comment by Xhofe** [comment]
现在似乎已经不会失效了，demo已经超过一个月仍然有效
