### ISSUE TITLE
upload access dose not work recursively

### ISSUE THREAD

**Issue by SINOPW** [alist-org/alist#1194]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

every single version

### Describe the bug / 问题描述

upload access works for the very current directory, there is no upload access for the subfolders.

### Reproduction / 复现链接

local deployment

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
