### ISSUE TITLE
菜单栏显示不全

### ISSUE THREAD

**Issue by airchaoz** [alist-org/alist#1195]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.0-0-gc35d54d-dirty

### Describe the bug / 问题描述

在对列表较底层的文件进行操作时，操作子菜单会被挡住，如图所示。网页已经拉到最底下了，无法再拉动了。可以考虑在页面下方添加空白解决这个问题。
![image](https://user-images.githubusercontent.com/32660335/171881096-08c1f4d8-6ad5-4d67-b581-33b48eba9a25.png)

### Reproduction / 复现链接

无

### Logs / 日志

```shell
浏览器：Microsoft Edge 版本 102.0.1245.30 (正式版本) (64 位)
```

**Comment by ampcr** [comment]
目前我是点击右上角"切换网络布局"按钮或者点击显示方式可以解决.

**Comment by Xhofe** [comment]
可以通过自定义内容自己添加。
