### ISSUE TITLE
希望可以支持在线播放wmv格式的视频

### ISSUE THREAD

**Issue by suyin-long** [alist-org/alist#1201]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望可以在线播放wmv格式的视频，现在不支持在线播放wmv格式的视频，只支持通过调用外部播放器的方式来播放wmv格式的视频。

**Comment by Xhofe** [comment]
You cannot play WMV files in HTML5 video. This has been answered [here](https://stackoverflow.com/questions/4459891/how-to-play-wmv-files-in-html5-video-player).

If you want to play video cross browser with HTML5 video you have to transcode your WMV file (currently to MP4 and WebM). Have a look here for a take on [HTML5 video](http://diveintohtml5.info/video.html).

To embed WMV videos in a web page you have to use an object/embed tag that calls the windows media player plugin (if it is installed - ie it will not work in platforms where the plugin is not available like iOS). Have a look here for a [working example](https://stackoverflow.com/questions/2538724/how-to-embed-wmv-files-in-my-html-file).
(from https://stackoverflow.com/questions/23260092/how-can-i-play-wmv-video-in-html-player)

**Comment by sonichy** [comment]
复制网址到外部播放器也不行，奇怪。
