### ISSUE TITLE
希望可以对后端隐藏支持通配符或者正则

### ISSUE THREAD

**Issue by ihipop** [alist-org/alist#1202]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://alist-doc.nn.ci/docs/features/hide 前端隐藏是支持正则的，但是后端隐藏不支持
这样如果有一个目录下要只展示/只隐藏某些文件名的文件就只能枚举，没办法和前端隐藏一样使用正则。而前端隐藏对会翻API的人来说没啥用。

### Suggested solution / 实现思路

和前端隐藏一样在后端api隐藏通配符或者正则匹配/未匹配的文件

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
