### ISSUE TITLE
希望能够添加沃云盘

### ISSUE THREAD

**Issue by wh1235** [alist-org/alist#1209]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

网盘网站：http://pan.wo.cn/
描述：一个中国联通旗下的网盘，去年因故障网盘暂时关闭，今年又回来了，与天翼云盘和彩云都差不多，算是弥补一下三大运营空缺。

### Suggested solution / 实现思路

网盘api文件地址：https://toscode.gitee.com/didili/wopan-api#%E6%B2%83%E7%9B%98api

**Comment by whws** [comment]
> ### 请确认以下事项
> * [x] 我已经读过了[文件](https://alist-doc.nn.ci)。
> * [ ] 我确信没有重复的问题或讨论。
> * [x] 我确定这个功能没有实现。
> * [x] 我相信这是一个合理且受欢迎的要求。
> 
> ### 功能描述/需求描述
> 网盘网站：http://pan.wo.cn/描述：一个中国联通旗下的网盘,去年因故障网盘暂时关闭,今年又回来了,与天翼云盘和彩云都差不多,算是弥补一下三大运营空缺。
> 
> ### 建议的解决方案/实现思路
> 网盘美国石油学会(American Petroleum Institute)文件地址：[https://toscode . gitee . com/didili/wopan-API # % E6 % B2 % 83% E7 % 9B % 98 API](https://toscode.gitee.com/didili/wopan-api#%E6%B2%83%E7%9B%98api)
> 
> ### 附加上下文/附件
> _不响应_
网盘网站：https://pan.wo.cn/

**Comment by whws** [comment]
网盘网站：https://pan.wo.cn/
这个是正确的
