### ISSUE TITLE
Feature：是否有增加不同账户之间的文件操作的计划

### ISSUE THREAD

**Issue by GoodBoyCoder** [alist-org/alist#1212]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

比如将阿里云盘的文件复制到Onedrive，通过本地流量转移，请问是否有相关的支持计划

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
