### ISSUE TITLE
Cloudflare R2 下载文件显示未授权

### ISSUE THREAD

**Issue by hmsjy2017** [alist-org/alist#1214]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.4.3

### Describe the bug / 问题描述

对接 Cloudflare R2 对象存储（兼容 S3 协议），列目录正常：
![Screenshot_20220610_233249](https://user-images.githubusercontent.com/42692274/173100640-a53219f2-e077-4081-8465-2169c3d3d833.jpg)
上传文件正常：
![Screenshot_20220610_233644](https://user-images.githubusercontent.com/42692274/173101346-0319e5d5-2e45-4e9e-bc71-23d118f279f2.jpg)
下载文件时却出现未授权错误：
![Screenshot_20220610_233207](https://user-images.githubusercontent.com/42692274/173100630-40e069d2-4d60-472e-b003-87ebe7570b79.jpg)
开启 `S3ForcePathStyle` 后仍然会报相同的错误。

### Reproduction / 复现链接

https://alist.iamsjy.com/R2
下载其中任意一个文件，都会出现未授权错误

### Logs / 日志

```shell
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>Unauthorized</Code>
<Message>Unauthorized</Message>
</Error>
```

**Comment by Xhofe** [comment]
https://community.cloudflare.com/t/connecting-to-r2-using-rust-s3-package/385312
