### ISSUE TITLE
希望添加一个新功能：阿里云盘他人的分享也可以添加到alist里

### ISSUE THREAD

**Issue by AlexWanghh2022** [alist-org/alist#1215]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist-doc.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

将阿里云盘他人的分享直接添加到alist里，方式为只读，这样当我们云盘空间不足时，不用转存，就可以打开，预览，下载文件

### Suggested solution / 实现思路

目前，阿里云盘在分享界面不能直接下载，只能转存后在下载等。实现比较简单，一个油猴插件，源码在https://www.baiduyun.wiki/panlinker.user.js ，实现了在网页端提取直链并下载，希望融合到alist里。

**Comment by yzqiang666** [comment]
本人在sharelist中实现(http://smccb.tk:33001)，也想移植到alist中。

**Comment by yzqiang666** [comment]
看看我扩展的本机存储。扩展了阿里的分享链接，实现无限容量。我的网盘链接是http://smccb.tk:33001。收集了数不尽的电影和连续剧资源以及软件、电子书等。在PC端用完美解码播放直链阿里云盘，不限速。

发自我的 iPad
