### ISSUE TITLE
windows版 输出密码乱码

### ISSUE THREAD

**Issue by sw586** [alist-org/alist#1219]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

2.6.1

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/24788222/173185631-b94b6909-2769-4b50-969f-6d3c7eaf29d5.png)
![image](https://user-images.githubusercontent.com/24788222/173185676-c60adea5-ee19-4e50-846e-c4166c3315c7.png)

这种 密码是多少  第一次安装使用

### Reproduction / 复现链接

111

**Comment by Xhofe** [comment]
#876
