### ISSUE TITLE
部分手机浏览器无法下载文件

### ISSUE THREAD

**Issue by liuyunfei666** [alist-org/alist#1220]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist-doc.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

最新版

### Describe the bug / 问题描述
部分手机浏览器下载文件的时候会下载2-3kb的文件,无法解析正确的下载地址,例如小米手机浏览器等

![Screenshot_2022-06-11-19-46-58-539_com android br](https://user-images.githubusercontent.com/57814936/173186595-d02179e0-b9d5-425d-9b1d-34dcb7ec71a4.jpg)

### Reproduction / 复现链接

http://1.14.92.218:5244/%E9%BB%91%E6%9C%88%7C%E6%96%B0%E5%89%91%E4%BE%A0%E6%83%85%E7%BC%98

**Comment by Aixzk** [comment]
小米浏览器设置里关闭 `使用迅雷下载引擎` 试试

**Comment by lalasou** [comment]
alook浏览器 武无法下载阿里云 文件不知道为什么
