### ISSUE TITLE
[bug] 在视频预览页面刷新后字幕消失

### ISSUE THREAD

**Issue by 123485k** [alist-org/alist#1221]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1-0-geb15bce

### Describe the bug / 问题描述

第一次点进去页面可以正常加载字幕，刷新后字幕消失

### Reproduction / 复现链接

[链接](https://rec.nana7mi.123485k.ltd:444/testass/%E5%BD%95%E5%88%B6-21452505-20220611-024530-142-%E7%AC%AC%E4%B8%80%E6%AC%A1%E7%8E%A9%E7%B3%96%E8%B1%86%E4%BA%BA%E4%B9%8B%E5%90%8E%E7%9A%84%E4%B8%89%E5%9B%BD%E6%9D%80.flv)
need ipv6

**Comment by Xhofe** [comment]
正常现象 字幕依赖于程序中父级目录的缓存，所以只有从父目录进入才有字幕。

**Comment by 123485k** [comment]
> 正常现象 字幕依赖于程序中父级目录的缓存，所以只有从父目录进入才有字幕。

有办法改进吗

**Comment by Xhofe** [comment]
> > 正常现象 字幕依赖于程序中父级目录的缓存，所以只有从父目录进入才有字幕。
> 
> 有办法改进吗

暂时不会

**Comment by Xhofe** [comment]
Fixed at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
