### ISSUE TITLE
删除文件或移动文件时出现了没有权限的问题

### ISSUE THREAD

**Issue by chenchen100** [alist-org/alist#1223]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.0

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/95748110/173212530-e968c464-8a6a-4630-a372-aad7d36a825b.png)
**我在删除文件或移动文件时出现了没有权限的问题**

### Reproduction / 复现链接

还有就是夸克网盘的x文件在网盘中显示的是在a文件夹下（假如），但是在alist中查看却在b文件夹下，x文件之前在b中，后来使用网盘移动到a中，结果就使得x文件显示错位（实际路径是在a，但是这个问题实际上应该是延迟，过一会就好了)，而且在alist中无法移动，报错没有权限S-1-1-0

**Comment by Xhofe** [comment]
夸克本来就是只能中转，建议打开webdav_direct，兼容性会好一些。
