### ISSUE TITLE
希望能支持Cloudflare Tunnel 的反向代理

### ISSUE THREAD

**Issue by wensley** [alist-org/alist#1225]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用Cloudflare Tunnel进行反代，在后台设置 Cloudflare Tunnel 令牌，类似[Uptime Kuma项目反代](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy-with-Cloudflare-Tunnel)

### Additional context / 附件

![cloudflare tunnel](https://user-images.githubusercontent.com/4245450/173267388-2707d535-3a48-4b23-b27e-53beefd43687.png)

**Comment by Skimige** [comment]
关联 feature request: 希望能识别 Cloudflare 代理之后的额外 Header（`CF-Connecting-IP` 等），目前使用 `cloudflared` 会显示 IP 为 `::1`
