### ISSUE TITLE
支持github 作为存储后端

### ISSUE THREAD

**Issue by hyhy01** [alist-org/alist#1228]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

类似于图床的形式。
不过实时读取github的目录结构，并且支持通过`curl`命令上传文件。

**Comment by rywbl** [comment]
#实现思路

实现思路应该比较简单吧，调用本地的Git就可以了啊 
支持将github当做个人网盘使用
