### ISSUE TITLE
customize header&body wound not be loaded when back to home page from manage pages

### ISSUE THREAD

**Issue by memset0** [alist-org/alist#1231]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1-0-geb15bce

### Describe the bug / 问题描述

从任一管理页面 `/@manage/*` 点击右下角 `返回主页` 按钮后，新页面不会加载前段配置文件中的自定义 header 和自定义 body。

看起来 customize header & body 是在后端做替换的，跳转时 header 和 body 并没有被刷新。

### Reproduction / 复现链接

https://ftp.memset0.cn/

**Comment by Xhofe** [comment]
这是预期行为 因为是spa应用，路由跳转不会重新加载html。

**Comment by memset0** [comment]
或许可以考虑在跳转时将两端html插入 或这个情况下用浏览器默认跳转行为代替react的路由

**Comment by Xhofe** [comment]
fixed in https://github.com/alist-org/alist-web/commit/a32449d886393062d1fc3eed98068594a1450d68
