### ISSUE TITLE
后台安全

### ISSUE THREAD

**Issue by vk-kai** [alist-org/alist#1238]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能不能在管理界面登录时加点限制啊，既没有频率限制又没有验证码和裸奔一样，试多少次密码都可以很不安全

**Comment by Cai-Tang** [comment]
最好可以双因素验证

**Comment by sudehao** [comment]
确实是，最好能加个双重验证，或者Google什么的第三方验证也好。

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
