### ISSUE TITLE
Pikpak使用aira推送下载的文件为index.html

### ISSUE THREAD

**Issue by u93724** [alist-org/alist#1241]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1-0-geb15bce-dirty

### Driver used / 使用的存储驱动

pikpak

### Describe the bug / 问题描述

挂载pikpak网盘后右键推送到aira中，下载的为index.html文件，经测试我alist挂载的阿里云盘无此问题，使用第三方pikpak客户端推送aira无此问题
![chrome_4VOXOMhNSz](https://user-images.githubusercontent.com/57604382/174262615-9bb9aa96-e972-42c9-85d2-0cb33e16685f.png)

### Reproduction / 复现链接

![chrome_4VOXOMhNSz](https://user-images.githubusercontent.com/57604382/174262790-190c03fc-fc5d-418b-9c19-22084ee6a62d.png)

**Comment by u93724** [comment]
好像aira推送有些问题，无法下载整个整个文件夹

**Comment by Windman1320** [comment]
> 好像aira推送有些问题，无法下载整个整个文件夹

目前的实现不支持下载文件夹，控制台可以看到400的报错，下载uri没有获取到；另外题主应该不是下载文件夹，看文件大小可能是命名有问题，文件是正确下载的，可以尝试更改文件名和后缀看看是否是正确的问题件，这一点可能与aria2的功能无关

**Comment by SemiZhang** [comment]
aria2的http下载需要服务器请求文件名，但pikpak的直链经常不返回文件名，用其他下载器也是一样的

**Comment by u93724** [comment]
使用这个客户端实测可以返回文件名并可以正常推送下载https://qianye520.notion.site/qianye520/PikPak-Win-Mac_By_Shimily-a5201f193f1949be821579abdf096e09

**Comment by UbiquityTony** [comment]
另外，浏览器流式下载也可以实现文件名
<img width="553" alt="image" src="https://user-images.githubusercontent.com/107668802/175818875-75bd7545-449f-4988-8bef-c8448f3eb35e.png">

**Comment by geeklihui** [comment]
歪个楼，为啥我这边右键没有发送到 aria2 选项，版本如图：
![image](https://user-images.githubusercontent.com/28993319/178958315-9b8c5fa5-05c2-4c2d-a82b-f0d74c9412e5.png)
![image](https://user-images.githubusercontent.com/28993319/178958367-6137fc43-3747-47df-a144-fbe7c0323c0e.png)

**Comment by Xhofe** [comment]
fixed in https://github.com/alist-org/web-v2/pull/48
