### ISSUE TITLE
proxy开了之后Onedrive只有30kb/s

### ISSUE THREAD

**Issue by hushanjushi** [alist-org/alist#1243]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

没开proxy，Onedrive下载有500\~1000Kb/s,开了只有30\~50kb/s，服务器之前rclone访问OneDrive速度应在3Mb以上，这个。。。我想可能和这个[issue](https://github.com/alist-org/alist/issues/975#issue-1209105864)比较像，但是它duplicate了哪个啊，我花了半小时还没找到。。。。

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
#971

**Comment by hushanjushi** [comment]
> #971

我试了一下ip+端口直接访问没有问题，但是通过ngnix反代至域名就会出现我和这几名用户出现的情况，应该是中间可能有哪里卡住了速度，虽然可能和alist没有直接关系，但是就是向您表述一下这个现象是可复现的，您似乎也是ip+端口吧，试一下转发到443上试试，有可能是ngnix同时有多个网站导致的

**Comment by Xhofe** [comment]
> > #971
> 
> 我试了一下ip+端口直接访问没有问题，但是通过ngnix反代至域名就会出现我和这几名用户出现的情况，应该是中间可能有哪里卡住了速度，虽然可能和alist没有直接关系，但是就是向您表述一下这个现象是可复现的，您似乎也是ip+端口吧，试一下转发到443上试试，有可能是ngnix同时有多个网站导致的

nginx反代：
<img width="842" alt="image" src="https://user-images.githubusercontent.com/36558727/174449149-63432ace-daca-4eb1-825e-a789d30b904d.png">
带宽只有100M，跑满了

**Comment by hushanjushi** [comment]
> 

我再看看，应该是我们这几个哪里设置的和您不一样

**Comment by hushanjushi** [comment]
补充，这个现象的全过程是开始满速几秒，后面会掉速，原因暂时不明，应该是与ngnix宝塔默认配置或者别的哪里缓存满了就掉速了，但是由于目前遇到的问题的人不够多，无法确定问题到底在哪
