### ISSUE TITLE
增加文件共享链接功能

### ISSUE THREAD

**Issue by fl0w1nd** [alist-org/alist#1244]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我希望增加文件分享功能，将文件原本的直链转化成一个共享链接。

### Suggested solution / 实现思路

由于有部分网盘没有文件共享功能，比如pikpak，如果能添加文件共享功能，就能间接利用alist对这些网盘进行文件共享。
最好加入一个分享管理的页面，就能统一对这些网盘的文件分享进行管理。

**Comment by Xhofe** [comment]
希望你能明白“列表程序”本来就是用来分享的 
整个网站就是一个大的分享链接
