### ISSUE TITLE
Google Drive 快捷方式显示为文件夹

### ISSUE THREAD

**Issue by ddaodan** [alist-org/alist#1249]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1-0-geb15bce-dirty

### Driver used / 使用的存储驱动

Google Drive

### Describe the bug / 问题描述

盘内添加的快捷方式显示为文件夹，打开后里面没有东西

### Reproduction / 复现链接

https://pan.ddaodan.club/%E8%B0%B7%E6%AD%8C%E7%9B%98/aospa-sapphire-1-equuleus-alpha-20220224.zip

![G)YZ4`0_1Z23@XE`FRW@34F](https://user-images.githubusercontent.com/40017293/174511951-5f5c7e7d-d6bf-4584-ac2c-2ebfba789e84.png)

![image](https://user-images.githubusercontent.com/40017293/174512315-e8bddcf0-7950-40dd-85fa-5f11342a1893.png)

**Comment by Xhofe** [comment]
预期行为。
