### ISSUE TITLE
上传文件能否保留文件的时间戳呢？

### ISSUE THREAD

**Issue by as564335sa** [alist-org/alist#1251]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前很多web的文件管理器上传文件都不能保留文件时间戳，即文件修改时间会变成上传时的时间，能否保留源文件的时间戳呢？

**Comment by Xhofe** [comment]
NO
