### ISSUE TITLE
macos support ?

### ISSUE THREAD

**Issue by 906675869** [alist-org/alist#1252]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

macos support ?

**Comment by Xhofe** [comment]
what is [darwin](https://en.wikipedia.org/wiki/Darwin_(operating_system))

**Comment by 906675869** [comment]
ok,but if possible ,any introduction could support? For after runing the app, I don't what's I do next and what's should I config, if template config could generate will be thankful

**Comment by Xhofe** [comment]
Nothing need to configure
