### ISSUE TITLE
win直接运行版本希望加上启动后自动最小化的功能

### ISSUE THREAD

**Issue by githubhc20** [alist-org/alist#1254]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

windows直接运行版本，平时程序偶尔会因为各种原因停止运行，利用系统自带的计划任务自动重启后，新运行的程序会遮挡住荧屏，给电脑日常使用带来不便，希望能加上启动EXE文件后自动最小化到任务栏的功能，或者最好能在运行时就以最小化、后台进行。

**Comment by anwen-anyi** [comment]
用脚本启动咯~

**启动.vbs**

Set ws = CreateObject("Wscript.Shell")  
ws.run "alist-windows-4.0-amd64.exe",vbhide

**停止.vbs**

Dim Wsh
Set Wsh = WScript.CreateObject("WScript.Shell")
Wsh.Run "taskkill /f /im alist-windows-4.0-amd64.exe",0
Set Wsh=NoThing
WScript.quit

**Comment by szhangcn** [comment]
你既然会使用计划任务，不如在计划任务中直接启动这个程序？用system账户运行计划任务，启动时间选系统启动时（而不是登录时）

**Comment by icepole-jon** [comment]
> 你既然会使用计划任务，不如在计划任务中直接启动这个程序？用system账户运行计划任务，启动时间选系统启动时（而不是登录时）

实测可以的，不会弹出运行界面
