### ISSUE TITLE
sso 或者 ldap 支持

### ISSUE THREAD

**Issue by KaptinLin** [alist-org/alist#1256]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否支持 ldap 或者 oauth2，openid 的方式登录

**Comment by Xhofe** [comment]
不能
