### ISSUE TITLE
使用百度网盘Webdav服务时报错

### ISSUE THREAD

**Issue by wangty163** [alist-org/alist#1258]
【使用背景】
使用alist挂载了自己的百度网盘，同时打开了webdav服务，正常的上传、下载等操作均可以实现。
所以本人尝试使用群晖的Hyper Backup套件，将数据备份到百度网盘上（通过Alist的WebDav），但是发现会报错。我自己通过调用Alist的WebDav接口，发现是当上传一个空文件时候会报错，这个应该是百度网盘的上传接口的限制导致的。

【诉求】
能不能实现，过滤掉这些空文件，以防止百度网盘的接口报错呢？或者提供回调接口之类的，可以方便二次开发

**Comment by Xhofe** [comment]
WebDAV空文件本来就是忽略的。

**Comment by wangty163** [comment]
但是现在实际情况，是通过Alist的WebDav上传文件时候，如果上传了空文件会报错

**Comment by Xhofe** [comment]
log

**Comment by wangty163** [comment]
> log

我找了半天。。。没看到alist的日志在哪儿

**Comment by Xhofe** [comment]
无法复现。
![image](https://user-images.githubusercontent.com/36558727/174790444-38198d16-79da-4745-884a-538987b23868.png)

**Comment by wangty163** [comment]
这个出错的原因，是不是就是群晖备份文件中有大小为0的文件，然后webdav服务自动忽略了这些文件，群晖在check时候发现文件没有成功创建，所以报告失败了？

**Comment by Xhofe** [comment]
没有群晖 不知道。

**Comment by wangty163** [comment]
> 无法复现。 ![image](https://user-images.githubusercontent.com/36558727/174790444-38198d16-79da-4745-884a-538987b23868.png)

我后来确认了，python3的requests库在调用上传方法时候，data如果传入的时候文件对象，而且文件为空时候，尝试上传就会报错
