### ISSUE TITLE
ftP中文乱码

### ISSUE THREAD

**Issue by xf110** [alist-org/alist#1260]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

最新版

### Driver used / 使用的存储驱动

FTP

### Describe the bug / 问题描述

FTP文件名为中文时乱码，希望可以加入选字符集encoding的选项

### Reproduction / 复现链接

无

**Comment by Toby-Shi-cloud** [comment]
太对了，希望能加入编码方式（我甚至打算自己改了）
