### ISSUE TITLE
文件夹密码在mac下访问失效

### ISSUE THREAD

**Issue by bystart** [alist-org/alist#1261]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1-0-geb15bce

### Driver used / 使用的存储驱动

默认

### Describe the bug / 问题描述

在mac M1 safari 浏览器下 且 未登录 alist后台 点击受密码保护的目录会直接进入跳过了密码校验
在相同的环境下谷歌浏览器中点击受密码保护的文件目录会弹出密码提示框

### Reproduction / 复现链接

http://alist.bystart.cn/%E5%B7%B2%E7%AD%BE%E5%90%8DIPA

**Comment by Xhofe** [comment]
Have you tried InPrivate mode?

**Comment by bystart** [comment]
> 您是否尝试过 InPrivate 模式？

How should I open it?

**Comment by Xhofe** [comment]
https://support.apple.com/guide/safari/browse-privately-ibrw1069/mac

**Comment by bystart** [comment]
InPrivate mode，it is working fine。 thanks～

**Comment by bystart** [comment]
thanks
