### ISSUE TITLE
当上传大小为0的文件时候报错

### ISSUE THREAD

**Issue by wangty163** [alist-org/alist#1264]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist-doc.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

最新版的docker

### Driver used / 使用的存储驱动

百度网盘

#### 问题描述
本地尝试上传大小为0的文件时候，会导致WebDav服务报错：
本地报错信息：
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/16515347/175308185-ee5558e4-5e1e-4b98-93fe-edfff0a0bda2.png">
alist报错日志：
![image](https://user-images.githubusercontent.com/16515347/175311601-03be73ae-89e0-468d-a916-40abfc31a626.png)

#### 问题结论（如何复现）
当使用python3的requests工具上传空文件时候，调用requests提供的request函数，data参数为文件对象，此时上传alist的webdav服务会报错；而当data改成空二进制数据时，上传成功不报错，这里说明alist对这种情况处理一定是有问题的。（另外，在[该问题](https://github.com/alist-org/alist/issues/1258)中，开发者用自己的工具尝试上传空文件是成功的，所以猜测应该是alist在接受空请求时候的处理逻辑漏了一些情况）
虽然我只是发现了某种情况下alist处理逻辑不符合预期的情况，但是该问题应该在client为非python程序时也可能出现
注：[工具上传代码逻辑（调用python3的requests库逻辑）](https://github.com/ezhov-evgeny/webdav-client-python-3/blob/develop/webdav3/client.py#L221)

#### 其他
怀疑该问题也是导致类似提问的根源所在：
- https://github.com/alist-org/alist/issues/701
- https://github.com/alist-org/alist/issues/974
- https://github.com/alist-org/alist/issues/1258
- https://github.com/alist-org/alist/issues/1095

### Reproduction / 复现链接

使用python3安装[webdavclient3](https://github.com/ezhov-evgeny/webdav-client-python-3)后，使用该工具提供的upload接口进行文件上传

示例代码：
``` python
from webdav3.client import Client
options = {
    'webdav_hostname': "<hostname>",
    'webdav_login': "<username>",
    'webdav_password': "<password>",
    'disable_check': True,
}
return Client(options)
client.upload(local_path="<local emtpy file>", remote_path="<remote path>")
```

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/175314045-c62aabc6-3ed9-48ed-9f25-d68115ffed0c.png)
unable to reproduce

**Comment by wangty163** [comment]
我想想，那是因为我alist是挂在群晖上的docker服务么

**Comment by wangty163** [comment]
> 我想想，那是因为我alist是挂在群晖上的docker服务么

奇怪了，我本地（mac）起了个alist服务，尝试上传空文件时依然是报错的。。。

**Comment by Xhofe** [comment]
不知道你是什么问题 

另：除了有密钥信息的部分，不要给我发邮件，直接在issue中发就行

**Comment by wangty163** [comment]
我用群晖的docker版的alist，尝试了下通过webdav备份到本地，这时候尝试上传空文件是没问题的，所以感觉是docker版的alist + 百度网盘会出现这个问题
client.upload(local_path="/Users/wty/tmp/empty_test/lock", remote_path="/dav/本地/temp/test.remote/lock")


你测试没问题的版本号是多少，我本地是用的最新的，docker用的是lastest

**Comment by wangty163** [comment]
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/16515347/175490421-42dab92f-5c0f-4b40-b7a0-09c91e420c76.png">
会不会是我配置有啥问题？我网盘是这样配置的，alist设置没有改什么地方

**Comment by wangty163** [comment]
我看了下，docker版本和mac版本的我都试了，都是会有这个报错。会不会是win上正常，linux和mac有问题？

**Comment by wangty163** [comment]
我测试了下，用win客户端，尝试上传大小为0的文件，依然是报错。。。我有点迷茫了

**Comment by lkxlzx** [comment]
我是天翼云盘，还是一样有问题

**Comment by wangty163** [comment]
> 我是天翼云盘，还是一样有问题

我试了我这里已有的百度和阿里的网盘，好像都会这样

**Comment by Xhofe** [comment]
> 调用requests提供的request函数，data参数为文件对象，此时上传alist的webdav服务会报错；而当data改成空二进制数据时，上传成功不报错

本来就是这样的，建议你看一下webdav协议的规范。webdav 上传的文件只能放在body里面，data参数为空文件对象时body并不是空的， 而且可能导致EOF。

**Comment by wangty163** [comment]
> > 调用requests提供的request函数，data参数为文件对象，此时上传alist的webdav服务会报错；而当data改成空二进制数据时，上传成功不报错
> 
> 本来就是这样的，建议你看一下webdav协议的规范。webdav 上传的文件只能放在body里面，data参数为空文件对象时body并不是空的， 而且可能导致EOF。

我测试alist+本地是没问题，但是alist+网盘有问题，是不是alist在调用网盘的api的处理逻辑导致的？

**Comment by wangty163** [comment]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/16515347/177263767-6c7158fa-c462-48d8-984b-140fc3a6bf63.png">
我用群晖自带的挂载dav的服务，将alist的webdav挂载上了，然后直接用文件系统尝试上传大小为0的文件，也是会报这个错误
