### ISSUE TITLE
alicdn 分发的 aliyun-web-office-sdk 加载过慢

### ISSUE THREAD

**Issue by SemiZhang** [alist-org/alist#1267]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1

### Driver used / 使用的存储驱动

Onedrive, 123Pan, FTP

### Describe the bug / 问题描述

aliyun-web-office-sdk.min.js 建立连接用时7-9秒
![image](https://user-images.githubusercontent.com/26916265/175545027-534921b5-4390-4998-b3d0-8eb3c62efe14.png)
![image](https://user-images.githubusercontent.com/26916265/175552470-6785ba72-e44c-4aaf-956e-b2304f04dc57.png)

### Reproduction / 复现链接

所有Alist站点

**Comment by Xhofe** [comment]
http://www.17ce.com/site/http/20220624_57ce23f0f3cf11ecaf650f1f5da96149:1.html
> <img width="1292" alt="image" src="https://user-images.githubusercontent.com/36558727/175563982-c579f8b5-2a6b-4134-b4b8-1cceed6f154a.png">
