### ISSUE TITLE
document preview in local network environment

### ISSUE THREAD

**Issue by SINOPW** [alist-org/alist#1277]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

document preview in pure local network environment

### Suggested solution / 实现思路

self-hosted third-party document preview service or integrated document preview service

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
