### ISSUE TITLE
音频播放移动端网页音量调节

### ISSUE THREAD

**Issue by haoduck** [alist-org/alist#1278]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前似乎只有PC端的页面可以调节音量，不知道能否给移动端页面也添加上？  

因为默认的音量比较小，页面上又不能调节的话，只能把系统音量调到非常高，少数情况甚至最高都还是不够大声。  
这样的话，如果没注意一切换到其他应用就会“震耳欲聋”，体验不是很好。  

另外的话我有尝试过编译alist-web，把音频播放的“0.5”预设音量提高了一些，不过有时候会莫名回到0.5，但是用无痕浏览重新打开页面又是修改后的值。挺奇怪的，不知道为啥。

**Comment by Xhofe** [comment]
Dependency repo: https://github.com/lijinke666/react-music-player

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
