### ISSUE TITLE
Type in ENV variable name `DB_SLL_MODE`

### ISSUE THREAD

**Issue by Plausible0Bug** [alist-org/alist#1280]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1

### Driver used / 使用的存储驱动

N/A

### Describe the bug / 问题描述

There is a typo in ENV varialbe name `DB_SLL_MODE`, I think it should be `DB_SSL_MODE` instead.

### Reproduction / 复现链接

https://github.com/alist-org/alist/blob/c67f128f15eb026f363ca1165f43d02f9db4d0a7/internal/conf/config.go#L16

**Comment by Xhofe** [comment]
Thanks for the report.
