### ISSUE TITLE
“本地”类存储 中 webdav下载文件异常

### ISSUE THREAD

**Issue by lemonchu** [alist-org/alist#1288]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

使用webdav连接时，文件夹能以及文件裂变正常显示，但是无法下载。
此问题仅在“本地”存储中出现

### Reproduction / 复现链接

I believe that it will make no difference. So here are two screenshots.
![attach_01](https://user-images.githubusercontent.com/44695478/176360555-48704dec-3273-4361-8648-4e6a6046f47d.JPG)
![attach_02](https://user-images.githubusercontent.com/44695478/176360563-20ec654c-d69a-4f27-9e97-92bb7145f29a.JPG)

**Comment by Xhofe** [comment]
请使用raidrive等第三方程序。
