### ISSUE TITLE
夸克网盘在修改文件后不会进行同步，而是重新生成一个带序号的文件

### ISSUE THREAD

**Issue by ziboh** [alist-org/alist#1291]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.61

### Driver used / 使用的存储驱动

Quark

### Describe the bug / 问题描述

夸克网盘在修改文件后不会进行同步，而是重新生成一个带序号的文件

### Reproduction / 复现链接

![GIF 2022-6-29 19-28-51](https://user-images.githubusercontent.com/42881496/176426438-44d9805f-5a6d-4864-9acb-17c6b686f0bf.gif)

### Logs / 日志

```shell
No response
```

**Comment by Xhofe** [comment]
web端抓包上传api中并没有覆盖上传参数，可能是不支持也可能是我不知道。如果你知道覆盖上传参数，可以在这里提供。否则此issue将因为无法修复被关闭。

**Comment by Goooooooooood** [comment]
我也遇到了同样的问题,而且I/O错误频发
![Snipaste_2022-07-17_20-32-29](https://user-images.githubusercontent.com/90984890/179399656-08272542-732d-4963-8c54-b1f81d23805c.png)
![Snipaste_2022-07-17_20-41-10](https://user-images.githubusercontent.com/90984890/179399660-cada2dc3-3e91-4540-a993-1622ada92223.png)
.
