### ISSUE TITLE
加密功能在知道文件夹名的情况下是无效的

### ISSUE THREAD

**Issue by yzbleaf** [alist-org/alist#1294]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1-0-geb15bce

### Driver used / 使用的存储驱动

阿里云盘/百度云盘

### Describe the bug / 问题描述

仅使用了阿里云盘/百度云盘，在对根目录加密后，直接输入ip:5524,会要求输入密码，但如果知道虚拟路径，比如在账号中设置的虚拟路径为aliyun，在浏览器输入ip:5524/aliyun，刚可以绕过加密要求，直接可看到文件内容并播放视频文件。多次测试出现同样情况，包括注销账号，清空浏览器以及另换浏览器，都会出现同样的问题。

### Reproduction / 复现链接

我没有敢放外链，在局域网测试的

**Comment by yzbleaf** [comment]
为什么 issue 无效被关闭？

**Comment by tlze** [comment]
文档，https://alist-doc.nn.ci/docs/setting/backend
 检查父文件夹密码。
我看很明显你没看文档，违反第一条，所以被关了。
________________________________
