### ISSUE TITLE
Worker threw exception Error 1101

### ISSUE THREAD

**Issue by imgblz** [alist-org/alist#1295]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1-0-geb15bce-dirty

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

Worker threw exception Error 1101
这个是alist的
https://pan.imgblz.cn/onedrive-cloud1
下面复现是代理
代理使用国内中转服务器

### Reproduction / 复现链接

https://onedrive.imgblz.cn/onedrive-cloud1/[Snow-Raws]%20%e4%b8%ad%e4%ba%8c%e7%97%85%e3%81%a7%e3%82%82%e6%81%8b%e3%81%8c%e3%81%97%e3%81%9f%e3%81%84!%20%e6%88%80/[Snow-Raws]%20%e4%b8%ad%e4%ba%8c%e7%97%85%e3%81%a7%e3%82%82%e6%81%8b%e3%81%8c%e3%81%97%e3%81%9f%e3%81%84!%20%e6%88%80%20%e7%ac%ac01%e8%a9%b1%20(BD%201920x1080%20HEVC-YUV420P10%20FLACx3).mkv?sign=c241883bf0964454

### Logs / 日志

```shell
文件夹正常显示，文件都无法预览或者下载
```

**Comment by Xhofe** [comment]
you should login to Cloudflare and check the error logs for onedrive.imgblz.cn
