### ISSUE TITLE
希望增加安卓端视频播放器KMPlayer的跳转

### ISSUE THREAD

**Issue by zzy-ac** [alist-org/alist#1296]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加安卓端视频播放器KMPlayer的跳转

**Comment by Xhofe** [comment]
KMPlayer doesn't even have a simple url scheme to open the app, so having extended functionality seems unlikely.

> https://www.reddit.com/r/shortcuts/comments/lya549/how_to_open_kmplayer_with_a_url/

So, if KMPlayer now has a URI scheme, please provide it, otherwise the issue will be closed.
