### ISSUE TITLE
百度网盘大文件总是上传失败？

### ISSUE THREAD

**Issue by luyer919** [alist-org/alist#1309]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1-x86_64

### Driver used / 使用的存储驱动

Baidu disk

### Describe the bug / 问题描述

威联通通过Webdav链接，用HBS3做文件备份的时候，百度网盘一直报错，发现同一个文件一直过不去，文件大概有2.9G的样子。不知是什么问题呢？

### Reproduction / 复现链接

没有

**Comment by Misaka-Mikoto-Tech** [comment]
你这个问题跟alist无关吧，我刚设置了qnap的百度网盘同步，8G的视频文件HBS3都可以上传成功

**Comment by luyer919** [comment]
> 

Qnap HBS3直接百度网盘同步没问题，但是速度慢。但通过webdev alist挂载就会报错。我不太懂哈。

**Comment by Misaka-Mikoto-Tech** [comment]
> > 
> 
> Qnap HBS3直接百度网盘同步没问题，但是速度慢。但通过webdev alist挂载就会报错。我不太懂哈。

我测试HBS3上传速度还可以

**Comment by seifer08ms** [comment]
我也是一直上传不成功大文件，总提示没有空间

**Comment by bytepoem** [comment]
> 你这个问题跟alist无关吧，我刚设置了qnap的百度网盘同步，8G的视频文件HBS3都可以上传成功

您好，请问百度网盘需要开会员吗，用HBS3上传的话？
