### ISSUE TITLE
您好 像这种复制直链 文件名字是中文的   复制出来的链接是乱码  有办法解决吗

### ISSUE THREAD

**Issue by xingleiwu** [alist-org/alist#1311]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

2.61

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

对了  就像这种复制直链 文件名字是中文的   复制出来的链接是乱码  有办法解决吗

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/13015600/177575238-a1ccca18-dcf0-485b-b88e-ca60200a8fa3.png)

文件名字:麻衣高清a.json
乱码链接:http://192.168.123.1:5244/d/ali72/TVBox/MaooXB/%E9%BA%BB%E8%A1%A3%E9%AB%98%E6%B8%85a.json

**Comment by Xhofe** [comment]
首先这不是乱码 只是urlencode 其次 你没看见下面还有个复制decode的直链吗

**Comment by xingleiwu** [comment]
> 首先这不是乱码 只是urlencode 其次 你没看见下面还有个复制decode的直链吗
不好意思 解决了  之前没用过下面那个链接  麻烦您了

**Comment by summer0607** [comment]
你好，请问你为什么有操作和排序按钮，我只有复制链接和下载按钮
