### ISSUE TITLE
使用网格布局时无法多选

### ISSUE THREAD

**Issue by CuteCatXiao** [alist-org/alist#1312]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

使用网格布局时无法多选

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
设计如此。

**Comment by CuteCatXiao** [comment]
> 设计如此。

为什么这样设计？如果多选时需要使用缩略图帮助选择呢
