### ISSUE TITLE
Windows注册为服务项

### ISSUE THREAD

**Issue by wqcblog** [alist-org/alist#1320]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

作者您好，alist现在大多部署在服务器上，能否支持以windows服务的形式部署在windows上(我知道alist目前可以在windows上运行)，这样开机自启，占据一个固定的端口，可以方便的管理个人的多种网盘，将登录直接展现在前端，面向个人使用。

**Comment by anwen-anyi** [comment]
自己照猫画虎看吧.....挺方便的
https://www.bilibili.com/video/BV1DG411s7j5?t=266.8

**Comment by abiglee** [comment]
我用的NSSM，挺方便的，自己搜一下教程吧
