### ISSUE TITLE
支持Data URI作为Logo图片数据

### ISSUE THREAD

**Issue by SemiZhang** [alist-org/alist#1321]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在前端中支持Logo使用"data:image/png;base64"形式的URI作为图片数据，减少外部图床需求，提高页面加载效率。
目前在favicon填入data URI可正常显示图案，logo填入后会变为Text。

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
