### ISSUE TITLE
Ipv6不能访问时使用ipv4重试

### ISSUE THREAD

**Issue by pengweiqhca** [alist-org/alist#1322]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

`Post "https://www.googleapis.com/oauth2/v4/token": dial tcp [2607:f8b0:4005:801::200a]:443: connect: connection timed out`
Google ipv6不能访问，ipv4可以，因此需要使用ipv4重试

**Comment by Xhofe** [comment]
可以自己在hosts文件中指定。
