### ISSUE TITLE
自定义认证header

### ISSUE THREAD

**Issue by f1ashine** [alist-org/alist#1326]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在配置完Nginx的basic认证后，输入配置好的密码，然后访问admin目录无问题，访问api目录会无限弹出basic认证的输入框，因为alist和Nginx同时使用了Authorization header的值进行认证，在从前端传递该header的值时就会造成前后端认证内容不一致，从而导致无法访问应用。
参考https://cloud.tencent.com/developer/article/1885300 配置api目录不需要basic认证，根目录需要basic认证：
<img width="956" alt="image" src="https://user-images.githubusercontent.com/26664765/178414821-7e8c947f-a90e-48ae-8289-02dac81a01b1.png">
但实测直接访问api目录也可以直接访问web，实际上是可以绕过basic认证访问后台的
<img width="993" alt="image" src="https://user-images.githubusercontent.com/26664765/178414904-5f88e3dc-7792-4d54-a04a-5e47515dc3d1.png">
<img width="929" alt="image" src="https://user-images.githubusercontent.com/26664765/178414959-c9328b62-caaa-4e2d-9dfc-677204e97971.png">

### Suggested solution / 实现思路

建议alist配置文件设置自定义Authorization的header头，或直接将该header名称修改为非Authorization的其他值。

**Comment by Xhofe** [comment]
网页内的请求是xmlhttprequest 浏览器不会给xmlhttprequest自动加上basic auth。所以你应该考虑放行api目录而不是修改header名，即使修改了也没用。
