### ISSUE TITLE
不同网盘相同密码可以不用重复输入是bug还是专门设计？

### ISSUE THREAD

**Issue by Cyiming** [alist-org/alist#1328]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

最新

### Driver used / 使用的存储驱动

和彩云等

### Describe the bug / 问题描述

比如我本地网盘的一个文件夹A密码设置的是123

和彩云的一个文件夹B密码也是123

那么游客输入一次A文件夹密码后 再点击B文件夹 没有任何提示 直接可以访问

我觉得这个设计有点问题 不同文件夹应该重新输入一次密码 即使是密码相同的

### Reproduction / 复现链接

无

### Logs / 日志

```shell
无
```

**Comment by Xhofe** [comment]
就是这样的设计。
