### ISSUE TITLE
坚果云

### ISSUE THREAD

**Issue by zlx021120** [alist-org/alist#1341]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

<a href="jianguoyun.com" target="_blank">坚果云官网</a>:jianguoyun.com

推荐理由:坚果云可以后台自动备份(用户电脑)需要备份的文件夹，记录每个文件删除修改的记录(可以随时恢复删除/修改的文件)，每月1G上行 3G下行免费流量

### Suggested solution / 实现思路

实现思路:我不知道如何实现，仅仅提一个小小的建议，个人使用坚果云云盘备份一些学习的PDF Word md txt 等小文件还是挺不错的。

**Comment by chaofanlin** [comment]
坚果云支持webdav的，直接开webdav就行了

**Comment by zlx021120** [comment]
> 坚果云支持webdav的，直接开webdav就行了

我电脑不是一直开机，我想离线也能访问电脑文件夹(虽然我可以直接在坚果云APP中访问 哈哈哈)

**Comment by liyehuicn** [comment]
无语

**Comment by zlx021120** [comment]
我不是很懂webdav，只停留在那种阿里云盘挂载为本地云盘，如果引起了笑话 还望见谅

**Comment by zlx021120** [comment]
> 坚果云支持webdav的，直接开webdav就行了

谢谢我成功了
