### ISSUE TITLE
宝塔使用apache反向代理如果添加二级目录，api还是会访问根目录

### ISSUE THREAD

**Issue by mikulo** [alist-org/alist#1346]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1

### Driver used / 使用的存储驱动

aliyun

### Describe the bug / 问题描述

假设我的域名是www.baidu.com,alist程序端口是5244，alist的二进制文件放在www.baidu.com/alist/文件夹下，现在我的需求是将www.baidu.com/alist/这个二级目录设置为网站首页，我使用bt面板设置反代，添加了代理目录，如图:

![image](https://user-images.githubusercontent.com/46894621/179339890-f7177002-1d9c-4ce4-94b5-8f7adedad582.png)
但是我访问www.baidu.com/alist/ 时，会出现如下报错;

![image](https://user-images.githubusercontent.com/46894621/179339952-7a36b2ce-b312-4852-906d-81da28905377.png)
浏览器F12调试发现：访问的api地址应该为www.baidu.com/alist/api/public/settings，但是实际如图访问的是:www.baidu.com/api/public/settings

![image](https://user-images.githubusercontent.com/46894621/179340014-dac5ae48-4d2f-49cd-ae87-cba89fe0a560.png)

请问下这个是我操作有误，还是什么问题

### Reproduction / 复现链接

开启bt面板的代理目录后，然后访问域名即可复现

**Comment by Xhofe** [comment]
duplicate with #370

**Comment by lingyuanzhicheng** [comment]
二级目录可以这样解决，修改config.json文件。
将
`"sub_folder": "",`
改为
`"sub_folder": "/alist/",`
然后Nginx正常反向代理即可。
```
location ^~ /alist/
{
    proxy_pass http://127.0.0.1:5244/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    add_header X-Cache $upstream_cache_status;
}
```
