### ISSUE TITLE
手机浏览器无法使用右键菜单

### ISSUE THREAD

**Issue by suandqf** [alist-org/alist#1347]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

手机上使用浏览器时无法调出鼠标右键的功能。主要需要一个重命名功能，手机相册上传文件后名字需要更改。

**Comment by rakaki** [comment]
长按还是可以打开菜单的吧

**Comment by suandqf** [comment]
你是怎么长按能出菜单的？我长按出的是系统的菜单。

**Comment by Aixzk** [comment]
换个浏览器

**Comment by KleinerSource** [comment]
IOS 设备  Safari Chrome Edge 都不支持右键

**Comment by 253551464** [comment]
yandex浏览器可以

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)

**Comment by hipudding** [comment]
同IOS，最新版本，右键无法使用
