### ISSUE TITLE
斐讯k3 A1 OpenWrt 运行失败

### ISSUE THREAD

**Issue by hwlon** [alist-org/alist#1350]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1

### Driver used / 使用的存储驱动

OpenWrt 

### Describe the bug / 问题描述

alist-linux-musl-arm64.tar.gz 运行错误
alist-linux-arm64.tar.gz 运行错误
alist-linux-musl-arm.tar.gz 不能运行

### Reproduction / 复现链接

alist-linux-musl-arm64.tar.gz 运行错误
alist-linux-arm64.tar.gz  运行错误
![2f08d337628ecb52](https://user-images.githubusercontent.com/2849273/179383273-fe3945ce-31ae-4001-b397-71b9db1303fb.jpg)

![4dc66781b2dc3a39](https://user-images.githubusercontent.com/2849273/179383261-5978152e-f540-4913-964f-596a5a6c212c.jpg)

### Logs / 日志

```shell
主机名	OpenWrt
型号	Phicomm K3 (CpuMark : 9986.892204 Scores)
架构	ARMv7 Processor rev 0 (v7l) x 2
固件版本	OpenWrt R22.4.1 / LuCI Master (git-22.095.24346-72703c8)
内核版本	5.4.188
```

**Comment by Xhofe** [comment]
仅保证常见prebuilt可用，其他不可用请在目标target自行编译。
