### ISSUE TITLE
部分js无法加载

### ISSUE THREAD

**Issue by 12189108** [alist-org/alist#1358]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.2

### Driver used / 使用的存储驱动

无关存储驱动

### Describe the bug / 问题描述

https://npm.elemecdn.com/alist-web@2.6.2/dist/assets/vendor.dd75dc04.js
https://npm.elemecdn.com/alist-web@2.6.2/dist/assets/index.98f0b294.js
显示403错误

### Reproduction / 复现链接

![截图 2022-07-22 09-01-33](https://user-images.githubusercontent.com/24732116/180339642-807ff393-8440-4b42-86d6-7add6ee5d68c.png)

**Comment by Dawnnnnnn** [comment]
修改`config.json`

```json
"assets": "https://jsd.nn.ci/npm/alist-web@$version/dist",
```

**Comment by in-out** [comment]
看看文档 
https://alist-doc.nn.ci/docs/setting/config/#assets

**Comment by 12189108** [comment]
> 修改`config.json`
> 
> ```json
> "assets": "https://jsd.nn.ci/npm/alist-web@$version/dist",
> ```

感谢，已经解决

**Comment by 12189108** [comment]
> 看看文档 https://alist-doc.nn.ci/docs/setting/config/#assets

感谢，发现jsdelivr可用，腾讯等不可用
