### ISSUE TITLE
最新版本更新后首页和管理页面都白屏

### ISSUE THREAD

**Issue by lsyyktv** [alist-org/alist#1362]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.2

### Driver used / 使用的存储驱动

阿里云

### Describe the bug / 问题描述

最新版本更新后首页和管理页面都白屏,windows和linux版本都试过,一样白屏,数据库和config文件全部删除后重新运行还是白屏,但是之前版本的直链还是可用,回退2.6.1之后,立马正常

**Comment by JerryHM11** [comment]
使用docker的情况也是如此，F12报错情况如下：
![image](https://user-images.githubusercontent.com/44153776/180362891-46612071-d685-4806-b47d-01d26867ae09.png)

**Comment by abiglee** [comment]
windows运行alist-windows-4.0-amd64.exe，打开127.0.0.1:5244，同样白屏

**Comment by Cyiming** [comment]
同样问题 关注

**Comment by Cyiming** [comment]
We're sorry but alist doesn't work properly without JavaScript enabled. Please enable it to continue.

**Comment by geeklihui** [comment]
能搜到的所有相关 issue 都被标记了重复，就是不说到底跟哪个 issue 重了，唯一一个有信息的 https://github.com/alist-org/alist/issues/557 也是过期的没啥用。后来在讨论区找到了，为了方便以后其它人搜 issue，放个链接在这里吧：https://github.com/alist-org/alist/discussions/1357 
另外我新服务器全新安装的 2.6.4 没问题，旧服务器从 2.6.0 升级到 2.6.4 反而出问题了，真奇怪。都没有动过配置文件。
