### ISSUE TITLE
能不能给个内网服务端api接口?直接用管理密码换token

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#1365]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

http://0.0.0.0:5244/api/admin/login接口看了源码 注释了账号密码，直接走header取Authorization...
应用场景是 内网服务app做审计, 定时删掉临时存储文件夹。换言之，就是想单纯post来操作，不用浏览器。
所以，http://0.0.0.0:5244/api/admin/login 这个接口有没有办法做个IP白名单用后端控制台管理登录的密码直接换Authorization，剩下的我们自由post来操作?

### Suggested solution / 实现思路

携带管理登录密码 post 一个接口直接拿到Authorization,该接口可以在配置文件里面加入ip白名单，

或者这个Authorization到底怎么计算的，抓包看了下，http://0.0.0.0:5244/api/admin/login 前端页面弹窗填写密码，提交，直接就是前端生成的token？没有提交任何body... 那岂不是要去翻js源码...

**Comment by Xhofe** [comment]
v2版本`Authorization`是固定的，计算方式是：
```
md5(`https://github.com/Xhofe/alist-${YOUR_PASSWORD}`)
```

**Comment by gowy222** [comment]
> v2版本`Authorization`是固定的，计算方式是：
> 
> ```
> md5(`https://github.com/Xhofe/alist-${YOUR_PASSWORD}`)
> ```

收到！
