### ISSUE TITLE
pikpak挂载限速

### ISSUE THREAD

**Issue by spirytuslove** [alist-org/alist#1372]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

pikpak分播放和下载两种接口，挂载使用的是下载接口。下载接口限速6M/s，播放接口限速10M/s，能否实现alist挂载pikpak让我选用播放接口播放

### Suggested solution / 实现思路

能否实现alist挂载pikpak让我选用播放接口播放 实现挂载可以和客户端速度一样

**Comment by Xhofe** [comment]
提供接口文档。

**Comment by spirytuslove** [comment]
> 提供接口文档。

没文档。。。第三方开源客户端好像用的就是播放接口 https://www.tjsky.net/?p=277
