### ISSUE TITLE
189能不能加个手机app的协议? 只有手机app会员多了两个功能: 在线解压+同步盘内部迅雷离线下载

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#1376]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

会员账号手机端在线解压: https://cloud.189.cn/web/vip/#/privilegeIntroduce/4

同步盘内部迅雷离线下载，目前安卓手机app里面 同步盘支持加入url离线下载(和迅雷合作的), web版本同步盘页面不支持此功能，pc版没安装具体未知...

### Suggested solution / 实现思路

看大佬如何操作...

**Comment by Xhofe** [comment]
不是网盘有的功能就会被添加到alist中，即使使用app协议也不会添加网盘独有的功能。
本程序中只支持所有网盘共有的功能（列表、查看、删除、新建文件夹等）
