### ISSUE TITLE
能否在前端管理设置新增自定义用XX软件打开链接地址

### ISSUE THREAD

**Issue by Leoin1** [alist-org/alist#1377]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

通过前端管理设置，自定义软件的URL Schemes来打开链接，电脑端很全了，但是想自定义添加些其他的IOS端。如infuse、Zfuse等。这样自定义程度更高些。感谢作者。

### Suggested solution / 实现思路

alist-管理-前端-new feature-自定义打开视频链接url Schemes前部链接

在点击*mp4等格式视频文件时生效

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
