### ISSUE TITLE
Windows访问localhost:5244，无法显示页面且报错

### ISSUE THREAD

**Issue by mcube-12139** [alist-org/alist#1387]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

alist-windows-4.0-386

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

http://localhost:5244 不显示任何东西，且控制台输出错误信息
![IE7MOS)2SNJQ@B_{PA_~CYN](https://user-images.githubusercontent.com/73683960/180652039-c8bf84cb-24f7-45ee-ae7e-056aa125a118.png)

### Reproduction / 复现链接

无

### Logs / 日志

```shell
:5244/assets/index.98f0b294.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
:5244/assets/vendor.dd75dc04.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by fkxiaoyu** [comment]
duplicate to which? Searched by "Failed to load module script:" find nothing only two duplicate issue

**Comment by xhofe** [comment]
#184
