### ISSUE TITLE
阿里云盘不会自动刷新

### ISSUE THREAD

**Issue by panxinkai** [alist-org/alist#1388]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

V2.6.3

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

阿里云盘添加新文件后 必须重启程序才会看到，不会自动刷新

### Reproduction / 复现链接

http://192.168.3.33:5244

**Comment by jiemo9527** [comment]
+1复议，更新阿里盘内容后，不会自动刷新，重新挂载会被阿里api丢包处理，只能重启alist

**Comment by beierweiwei** [comment]
onedrive有同样的问题
