### ISSUE TITLE
Apache2 反向代理致非根目录时连接地址错误

### ISSUE THREAD

**Issue by bifenggang98** [alist-org/alist#1399]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.3-0-g1d3b869-dirty

### Driver used / 使用的存储驱动

ubuntu 22.04

### Describe the bug / 问题描述

Apache2 反向代理致非根目录时连接地址错误

Apache2 代理配置如下

```
        <IfModule mod_proxy.c>
                ProxyStatus On
                SSLProxyEngine On
                SSLProxyCheckPeerCN Off
                SSLProxyCheckPeerName Off
                ProxyRequests Off
                ProxyPreserveHost On
                ProxyPass /qbittorrent/ https://localhost:8443/
                ProxyPassReverse /qbittorrent/ https://localhost:8443/
                ProxyPass /aria2:6800 https://localhost:6800
                ProxyPassReverse /aria2:6800 https://localhost:6800
                ProxyPass /emby/ http://localhost:8096/
                ProxyPassReverse /emby/ http://localhost:8096/

                ProxyPass /alist/ http://localhost:5244/
                ProxyPassReverse /alist/ http://localhost:5244/
        </IfModule>
```

重启apache2后地址无变化，其他代理的服务均正常运行

更换静态资源，重定向api地址后显示错误，控制台无错误输出 

### Reproduction / 复现链接

https://haven98.top:21443/alist/

**Comment by Xhofe** [comment]
修改配置文件 sub_folder

**Comment by bifenggang98** [comment]
> 修改配置文件 sub_folder

修改后正常使用，感谢。
