### ISSUE TITLE
希望添加“新建文件”的功能

### ISSUE THREAD

**Issue by fwder** [alist-org/alist#1422]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

支持新建文件.

**Comment by lovezm** [comment]
同样需要 要是有文件后面加上描述的功能就更好了

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
