### ISSUE TITLE
迅雷上传文件报错

### ISSUE THREAD

**Issue by Cyiming** [alist-org/alist#1426]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist-doc.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

2.6.3

### Driver used / 使用的存储驱动

迅雷

### Describe the bug / 问题描述

迅雷可以正常加载和查看删除，但无法上传文件

上传后红色弹窗链接 链接打开是滑块 滑动滑块填入token不解决 上传依然滑块

见：https://i2.100024.xyz/2022/07/29/12dxlyf.webp

经测试 用迅雷本身上传也有滑块 这块alst还不能很好处理这一问题 希望下一版本修复 手动滑动可以上传
 

已经后台设置ua为 AndroidDownloadManager/11 (Linux; U; Android 11; M2004J7AC) 开代理

### Reproduction / 复现链接

无

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/discussions/1436
