### ISSUE TITLE
迅雷文件显示不全

### ISSUE THREAD

**Issue by Cyiming** [alist-org/alist#1427]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

2.6.3

### Driver used / 使用的存储驱动

迅雷

### Describe the bug / 问题描述

迅雷部分文件不加载显示（不是无法播放 是压根不显示）

已刷新还是不显示

经测试一个是wmv格式 一个mp4 一个mgp

### Reproduction / 复现链接

无

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/discussions/1436
