### ISSUE TITLE
移动端支持打开列表项目

### ISSUE THREAD

**Issue by ShinChven** [alist-org/alist#1433]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

移动端支持打开列表项目

我在iPad上想推送aria任务，发现没法使用右键菜单。

### Suggested solution / 实现思路

列表右侧放置一个按钮打开条目菜单。

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
