### ISSUE TITLE
希望可以添加对城通网盘的支持

### ISSUE THREAD

**Issue by X7A600** [alist-org/alist#1434]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

添加对城通网盘的支持
网盘[官网](https://ctfile.com/)

### Suggested solution / 实现思路

官方接口文档
[城通网盘用户侧接口文档](https://openapi.ctfile.com/docs/ctfile-user-api/ctfile-user-api-1cglhkmunab04)
[城通网盘开放接口文档](https://openapi.ctfile.com/docs/ctfile-open-api/ctfile-open-api-1c9js163vqces)

**Comment by anwen-anyi** [comment]
呃呃呃....话说城通真的有速度吗..感觉比115和百度还慢......

**Comment by X7A600** [comment]
> 

虽然是这样说 但是感觉比百度云限速50KB/s好多了

**Comment by anwen-anyi** [comment]
> > 
> 
> 虽然是这样说 但是感觉比百度云限速50KB/s好多了

QAQ要是和百度比起来感觉还是百度快...

**Comment by Ch3n4y** [comment]
> 

城通网盘需要会员充值，如有需要可以提供账号我来开发。

**Comment by Laine127** [comment]
城通本身支持webdav，直接挂上去不行么

**Comment by peerless2012** [comment]
> 城通本身支持webdav，直接挂上去不行么

非会员想白嫖啊，主要是有少量资源是成功分享的，开会员又没必要，PC挂机又太浪费了。
