### ISSUE TITLE
我用fileball添加迅雷,满速

### ISSUE THREAD

**Issue by sunzhe1234** [alist-org/alist#1437]
我用fileball添加迅雷,满速
![98C35627-7271-4B08-8C71-CC456F1FDE5F](https://user-images.githubusercontent.com/100278321/182120636-9c7daae4-7cb1-4e27-a352-9e3172d28b55.png)
![4DD2613B-1ACC-441E-A189-4F97EDF90CCE](https://user-images.githubusercontent.com/100278321/182120665-a47c93bb-60d0-4c80-89b8-153ce744c004.png)

**Comment by cky8264** [comment]
新版的怎么添加迅雷，我看只有百度云了啊。。。
