### ISSUE TITLE
夸克网盘挂载后不显示文件夹下的内容

### ISSUE THREAD

**Issue by pkr5277** [alist-org/alist#1438]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6

### Driver used / 使用的存储驱动

Quark

### Describe the bug / 问题描述

夸克网盘挂载后不显示文件夹下的内容，cookie和目录id都设置了，重启或者清除缓存都无效
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/38154917/182123921-1c8338c0-7d55-4b38-b1d7-39b61281f472.png">
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/38154917/182124013-3f26a880-c856-4b9f-823c-e293ca7bf66d.png">
![Uploading image.png…]()

### Reproduction / 复现链接

夸克网盘挂载后不显示文件夹下的内容，cookie和目录id都设置了，重启或者清除缓存都无效
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/38154917/182123921-1c8338c0-7d55-4b38-b1d7-39b61281f472.png">
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/38154917/182124013-3f26a880-c856-4b9f-823c-e293ca7bf66d.png">
![Uploading image.png…]()

**Comment by pkr5277** [comment]
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/38154917/182124288-60a3390b-8333-4480-b4d9-53f6a0582d6f.png">

**Comment by raygzcn** [comment]
同样遇到这个问题，是了pikpak正常，就是夸克不正常

**Comment by 2822132073** [comment]
我也不正常,希望可以使用之后踢我一下

**Comment by jungeee** [comment]
我也遇到了这种情况。可能是ip被禁止访问，pan.quark.cn网页也打不开，ping不通。更换ip或者使用夸克浏览器内置云盘可以访问。

**Comment by 2822132073** [comment]
> 

我可以访问pan.quark.cn,但是没办法看文件

**Comment by Xhofe** [comment]
id不带后面的目录名称

**Comment by shaojs321** [comment]
我第一次也这样，删了数据重新部署又好了

**Comment by xian54966** [comment]
V2同样的问题，不显示部分目录。更换V3版本，问题依旧
