### ISSUE TITLE
希望增加pCloud网盘的接入

### ISSUE THREAD

**Issue by chung1912** [alist-org/alist#1443]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加pCloud网盘的接入。
主要是当前webdav挂载效果不佳，无法获取到直链

**Comment by woshichenghaibo** [comment]
最近刚发现了这个网盘，希望接入，这个网盘有中文界面，网速也还行，4GB但是可以扩展到10GB。

目前alist所有支持的网盘里面，能免梯子访问的国外网盘只有yandex，但是yandex不能看文件，只能列目录，也被墙了

用国外网盘存储点私密资料的话，还是可以的，相信很多人不想被网信办一览无余吧？

**Comment by chung1912** [comment]
> 最近刚发现了这个网盘，希望接入，这个网盘有中文界面，网速也还行，4GB但是可以扩展到10GB。
> 
> 目前alist所有支持的网盘里面，能免梯子访问的国外网盘只有yandex，但是yandex不能看文件，只能列目录，也被墙了
> 
> 用国外网盘存储点私密资料的话，还是可以的，相信很多人不想被网信办一览无余吧？

这个需求等了一年多了，希望可以加入啊

**Comment by kzssc** [comment]
+1 pcloud 🚀
