### ISSUE TITLE
readme文件添加评论系统无法显示

### ISSUE THREAD

**Issue by coolarec** [alist-org/alist#1447]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.1-0-geb15bce

### Driver used / 使用的存储驱动

123网盘

### Describe the bug / 问题描述

我想在readme.md中添加waline或者artitalk评论系统，测试在系统后台的body处添加显示正常
![image](https://user-images.githubusercontent.com/46271219/182595513-b754313f-839d-4708-bfd1-9b430c5d1c37.png)
![image](https://user-images.githubusercontent.com/46271219/182595520-90d9b1f4-cc89-4dfb-830f-dca7eb19bc91.png)

但是当我把以下代码写入readme时就不能正常显示
  <div id="waline"></div>
  <script>
    Waline.init({
      el: '#waline',
      serverURL: 'https://xxxx.vercel.app/',
    });
  </script>

![image](https://user-images.githubusercontent.com/46271219/182596105-36d801eb-9133-453f-a196-18af2c2e2b65.png)

### Reproduction / 复现链接

http://coolarec.live/%E9%A9%AC%E4%BA%91%E7%BB%99%E7%9A%84

**Comment by Xhofe** [comment]
How should script tags work in react? That's a massive security vulnerability

> https://github.com/remarkjs/react-markdown/issues/562
