### ISSUE TITLE
加载动画建议

### ISSUE THREAD

**Issue by TTomDuan** [alist-org/alist#1448]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能不能多加一些动画，例如顶部加载条之类的  转圈的动画总感觉看着心慌😂

**Comment by anwen-anyi** [comment]
顶部加载条 ~ 可以自行引入CSS JS实现 哈哈这个随便百度就能找到

**Comment by TTomDuan** [comment]
好的 谢谢啦
