### ISSUE TITLE
pikpak上传失败 --2 validation error(s) found. 

### ISSUE THREAD

**Issue by ika166** [alist-org/alist#1452]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.3

### Driver used / 使用的存储驱动

pikpak

### Describe the bug / 问题描述

2 validation error(s) found. - minimum field size of 1, CreateMultipartUploadInput.Bucket. - minimum field size of 1, CreateMultipartUploadInput.Key.

### Reproduction / 复现链接

2 validation error(s) found. - minimum field size of 1, CreateMultipartUploadInput.Bucket. - minimum field size of 1, CreateMultipartUploadInput.Key.

**Comment by paowan2** [comment]
![image](https://user-images.githubusercontent.com/30073279/184117850-a8d42dce-fdfb-49d6-b819-68f342c3682a.png)

**Comment by zl70971** [comment]
我也出现了同样的问题
