### ISSUE TITLE
关于README文件无法读取的相关问题

### ISSUE THREAD

**Issue by CuteCatXiao** [alist-org/alist#1456]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.3-0-g1d3b869

### Driver used / 使用的存储驱动

OneDrive E5

### Describe the bug / 问题描述

无论是否自动读取或手动访问均无法读取内容
经测试，重命名"readme.md"为"readme1.md"可以解决
最近操作:新增文件".password" 更改logo

相关截图:
![image](https://user-images.githubusercontent.com/62191675/182992811-c3b72757-28bd-44f6-9f72-ccce5ed240cf.png)
![image](https://user-images.githubusercontent.com/62191675/182993030-2ba6768b-996b-44de-a640-c63f35cfcdaf.png)
文件列表:
![image](https://user-images.githubusercontent.com/62191675/182993784-028bad9f-6f21-4583-b111-42840f924335.png)
![image](https://user-images.githubusercontent.com/62191675/182993817-315dd0fb-52ec-4690-8933-1442cce6eedd.png)

相关错误日志：
![image](https://user-images.githubusercontent.com/62191675/182992891-b2550240-0d2a-451f-b2cb-b80548a3386d.png)
![image](https://user-images.githubusercontent.com/62191675/182993423-60fb3eee-c8c1-4bfa-95fa-f85a4b01f760.png)

相关配置：
![image](https://user-images.githubusercontent.com/62191675/182992988-47362cb8-644c-4d5a-bd9a-3abe97d5472e.png)

### Reproduction / 复现链接

https://drive.nekoluna.ga/

**Comment by CuteCatXiao** [comment]
@Xhofe 所以是什么问题😥

**Comment by Xhofe** [comment]
> @Xhofe 所以是什么问题😥

目测网络

**Comment by CuteCatXiao** [comment]
> > @Xhofe 所以是什么问题😥
> 
> 目测网络

我本地网炸了? 你那里可以访问是吧

**Comment by Xhofe** [comment]
不知道 你加了密码 我看不见

**Comment by CuteCatXiao** [comment]
> 不知道 你加了密码 我看不见

应该的是cloudflare出了点小问题,改成仅dns模式就好了
