### ISSUE TITLE
使用potplayer唤起功能不能播放，提示不存在该文件，经测试是Unicode编码导致的问题

### ISSUE THREAD

**Issue by hdm9527** [alist-org/alist#1464]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.3-0-g1d3b869-dirty

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

在win10上经测试是potplayer唤起后端会把url中的中文转换成Unicode字符，导致找不到该文件，最后播放失败。复制链接使用potplayer播放正常，编码的url和解码的url都可以正常播放。

### Reproduction / 复现链接

[复现链接](https://rn.37373.xyz/d/admin/%E7%8B%82%E8%B5%8C%E4%B9%8B%E6%B8%8A%E5%8F%8C/%5BNekomoe%20kissaten%5D%5BKakegurui%20Twin%5D%5B01%5D%5B1080p%5D%5BCHS%5D.mp4?sign=16c07d4d64788a16)
alist的demo站也存在这个问题，url中有中文唤起potplayer提示找不到该文件[demo视频](https://alist.nn.ci/d/China/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/%E8%A7%86%E9%A2%91/%E9%A9%AC%E4%BF%9D%E5%9B%BD%20TOP10%E5%8D%81%E5%A4%A7%E9%AC%BC%E7%95%9C%E6%94%B9%E7%BC%96(%E6%95%85%E4%BA%8B%E7%AF%87)%20%E7%AC%AC%E4%B8%80%E5%90%8D%E6%B0%B8%E8%BF%9C%E6%97%A0%E6%B3%95%E8%B6%85%E8%B6%8A%20%E7%A9%B6%E7%AB%9F%E5%8F%91%E7%94%9F%E7%94%9A%E4%B9%88%E4%BA%8B%E4%BA%86%EF%BC%9F%20-%20YouTube.mkv)

### Logs / 日志

```shell
potplayer手动播放正常
[GIN] 2022/08/07 - 11:10:24 | 302 |  257.694396ms | 240e:3b3:9234:xxx:xxxx:c3e6:xxxx:5fd6 | GET      "/d/admin/狂赌之渊双/[Nekomoe kissaten][Kakegurui Twin][01][1080p][CHS].mp4?sign=16c07d4d64788a16"

potplayer唤起播放失败
ERRO[2022-08-07 11:10:34] not file                                     
[GIN] 2022/08/07 - 11:10:34 | 200 |   11.879503ms | 240e:3b3:9234:xxx:xxxx:c3e6:xxxx:5fd6 | GET      "/d/admin/ç\u008b\u0082èµ\u008cä¹\u008bæ¸\u008aå\u008f\u008c/[Nekomoe kissaten][Kakegurui Twin][01][1080p][CHS].mp4?sign=16c07d4d64788a16"
ERRO[2022-08-07 11:10:35] not file
```

**Comment by lonzoen** [comment]
出现相同问题
![image](https://user-images.githubusercontent.com/22364270/183291123-270cfa5d-29a9-4171-9a70-964ac77c3f64.png)

**Comment by chuest** [comment]
出现相同问题。

**Comment by JokerZhang66** [comment]
我也遇到了

**Comment by balh55y** [comment]
![image](https://user-images.githubusercontent.com/85926883/188651343-5a58fd49-0cf0-4a64-9d3b-169d1197b8ba.png)
同样

**Comment by hdm9527** [comment]
> ![image](https://user-images.githubusercontent.com/85926883/188651343-5a58fd49-0cf0-4a64-9d3b-169d1197b8ba.png) 同样

临时解决方法，把路径的中文用字母或字符代替

**Comment by shiji5824666** [comment]
[potplayer调用.zip](https://github.com/alist-org/alist/files/9504459/potplayer.zip)
把压缩包里的两个文件拷贝到potplayer安装根目录(目录路径不能含中文)，然后把两个文件里的potplayer.exe和potplayer.bat的路径换成你的，最后以管理员身份双击运行potplayer.reg添加进注册表

**Comment by hdm9527** [comment]
> 

你先看清楚，是路径中不能有中文或文件名有中文，改成英文或其他字符就可以正常使用

**Comment by shiji5824666** [comment]
> > 
> 
> 你先看清楚，是路径中不能有中文或文件名有中文，改成英文或其他字符就可以正常使用

老哥，能有点常识吗，我能发出解决方案，自然是亲测的了，算了，信不信随你，溜了溜了

**Comment by hdm9527** [comment]
> > > 
> > 
> > 
> > 你先看清楚，是路径中不能有中文或文件名有中文，改成英文或其他字符就可以正常使用
> 
> 老哥，能有点常识吗，我能发出解决方案，自然是亲测的了，算了，信不信随你，溜了溜了

不好意思，不会bat命令，百度了下原来是利用bat进行字符替换

**Comment by hdm9527** [comment]
potplayer的原因，中文解码时被当成utf8字符转gbk了，找错方向了，先关闭了。解决方法参照[这里](https://github.com/alist-org/alist/issues/1464#issuecomment-1239115518)，思路是注册表调用bat脚本替换字符，本来想用一条命令解决的，但是变量的值不知道怎么传过去，都是空

**Comment by Think2twice** [comment]
> [potplayer调用.zip](https://github.com/alist-org/alist/files/9504459/potplayer.zip) 把压缩包里的两个文件拷贝到potplayer安装根目录(目录路径不能含中文)，然后把两个文件里的potplayer.exe和potplayer.bat的路径换成你的，最后以管理员身份双击运行potplayer.reg添加进注册表

厉害啊，老哥。解决了

**Comment by Namialways** [comment]
> [potplayer调用.zip](https://github.com/alist-org/alist/files/9504459/potplayer.zip) 把压缩包里的两个文件拷贝到potplayer安装根目录（目录路径不能含中文），然后把两个文件里的potplayer.exe和potplayer.bat的路径换成你的，最后以管理员身份双击运行potplayer.reg添加进注册表

我的是跳转链接potplayer://http//127.0.0.1。。。。其中http后面没有冒号，有办法解决吗

**Comment by bswc000** [comment]
> > [potplayer调用.zip](https://github.com/alist-org/alist/files/9504459/potplayer.zip) 把压缩包里的两个文件拷贝到potplayer安装根目录（目录路径不能含中文），然后把两个文件里的potplayer.exe和potplayer.bat的路径换成你的，最后以管理员身份双击运行potplayer.reg添加进注册表
> 
> 我的是跳转链接potplayer://http//127.0.0.1。。。。其中http后面没有冒号，有办法解决吗

我也是，蹲
