### ISSUE TITLE
Googledrive显示不全

### ISSUE THREAD

**Issue by bian2022** [alist-org/alist#1467]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

alist-windows-4.0-386.exe

### Driver used / 使用的存储驱动

Googledrive

### Describe the bug / 问题描述

Googledrive在不设置目录的情况下，无法显示“共享云端硬盘”

### Reproduction / 复现链接

*

**Comment by Xhofe** [comment]
单次只能显示一个盘。
