### ISSUE TITLE
阿里云盘报错 The resource drive has exceeded the limit. File size exceeded drive capacity

### ISSUE THREAD

**Issue by geeklihui** [alist-org/alist#1479]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.3-0-g1d3b869-dirty

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

通过在服务器上 Rclone 挂载 Alist 的 Webdav，Alist 里配置了 Onedrive 和阿里云盘，使用 Aria2 下载后执行脚本，把下好的文件上传到 Alist 里的阿里云盘里。
过了几个小时发现小文件传上去了，大文件没传上去（5.9G），看了下 Rclone 日志是上传失败了。
后来再用 Rclone 不管上传什么到阿里云盘都会报错，但上传到 Onedrive 就没问题，**遂排除 Rclone 的问题。Rclone 这边详细报错是 rate limited**
之后怀疑可能是服务器公网 IP 被 ban，也怀疑可能是 webdav 接口被 ban，于是尝试直接在 Alist 网页版上传文件到阿里云盘，随便选了个几十 M 的文件，同样无法上传，报错为 The resource drive has exceeded the limit. File size exceeded drive capacity

### Reproduction / 复现链接

不知道该怎么复现，所有的操作步骤已在上面详述。

**Comment by geeklihui** [comment]
注：阿里云盘网页版、客户端上传均正常，排除账号被 ban 的可能性

**Comment by Xhofe** [comment]
无法复现。

**Comment by geeklihui** [comment]
> 无法复现。

没事了，自己恢复了，可能阿里云盘在我这边有波动，后来我同事也跟我说登不上去阿里云盘，下载东西没反应啥的。现在都好了。

**Comment by wakaka123wakaka** [comment]
我也遇到这个问题了

**Comment by anysoft** [comment]
包括应该是阿里云盘限时容量到期了，可用容量不足导致的。
