### ISSUE TITLE
是否可以在后台增加允许“全选打包下载”“目录打包下载”开关呢？

### ISSUE THREAD

**Issue by xxika** [alist-org/alist#1483]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

一旦下载人数多起来的时候，大量游客会全选打包下载，系统IO受不了。

**Comment by Xhofe** [comment]
纯前端调用，不会走服务器。
