### ISSUE TITLE
希望能增加小龙云

### ISSUE THREAD

**Issue by 3242692624** [alist-org/alist#1484]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

小龙云盘是四川星河飞天科技有限公司打造的一款安全可靠的存储工具，它是一个基于区块链理念、依托IPFS（InterPlanetary File System）的去中心化分布式存储应用；提供无限存储空间、海量资源共享、跨界极速传输等功能，实现自由分享的同时充分保护用户的隐私
https://www.stariverpan.com/download.html

**Comment by whws** [comment]
https://wx.stariverpan.com/web/home，这个是该网盘的链接，希望能够支持挂载。

**Comment by whws** [comment]
https://wx.stariverpan.com/web/home
这个是该网盘的链接，希望能够支持挂载。

**Comment by whws** [comment]
@vanplus 意思是可以实现挂载!

**Comment by Xhofe** [comment]
> 我发现他家的电脑客户端可以开启 DevTools 调试模式抓包。
> 
> ![开启 DevTools](https://camo.githubusercontent.com/674abc92e9300d531bb95c4e20b64362008ba1c3a4e7f163c04edd09750fb037/68747470733a2f2f692e696d6775722e636f6d2f754d64734561532e706e67)
> 
> `Ctrl+I`
> 
> ![debug](https://camo.githubusercontent.com/8158dd50df0e3a82a3d7a93b32b89aeb9a1a9a8527224a3ab4c6e8af9c2dc575/68747470733a2f2f692e696d6775722e636f6d2f766f514d636c532e706e67)

试了一下 打不开了 点`切换到开发者模式`没有反应
