### ISSUE TITLE
有没有可能引入百度云盘SDK的API

### ISSUE THREAD

**Issue by howie-wu** [alist-org/alist#1488]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

有没有可能引入百度云盘SDK的API
https://pan.baidu.com/union/doc

### Suggested solution / 实现思路

用户自行创建应用然后使用API

**Comment by Xhofe** [comment]
本来就是使用的这个API。

**Comment by howie-wu** [comment]
感谢回复是我唐突了> 本来就是使用的这个API。
