### ISSUE TITLE
v2.6.4 升级失败

### ISSUE THREAD

**Issue by zhucaidan** [alist-org/alist#1489]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4

### Driver used / 使用的存储驱动

alist

### Describe the bug / 问题描述

使用 curl -fsSL "https://nn.ci/alist.sh" | bash -s update 命令升级提示失败，
两台机器（amd64 和 arm）都测试过都一样无法解压安装

```
停止 Alist 进程

下载 Alist  ...
######################################################################## 100.0%

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
下载 alist-linux-musl-arm64.tar.gz 出错，更新失败！
回退所有更改 ...
```

### Reproduction / 复现链接

curl -fsSL "https://nn.ci/alist.sh" | bash -s update

**Comment by Huadao1108** [comment]
![image](https://user-images.githubusercontent.com/83736338/184480837-ff142787-7da7-44be-91bd-b01f01cf9981.png)
me too

**Comment by Huadao1108** [comment]
curl -fsSL "https://nn.ci/alist.sh" | bash -s install > error

**Comment by Xhofe** [comment]
请尝试手动安装。
