### ISSUE TITLE
希望加入kkfileviw和onlyoffice的本地调用

### ISSUE THREAD

**Issue by softwareygr** [alist-org/alist#1494]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望加入kkfileviw 和onlyoffcie 的本地的调用

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
