### ISSUE TITLE
天翼云盘账号状态 ocr error

### ISSUE THREAD

**Issue by kzhuang91** [alist-org/alist#1501]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.3-0-g1d3b869

### Driver used / 使用的存储驱动

天翼云盘

### Describe the bug / 问题描述

<img width="996" alt="WX20220815-112720@2x" src="https://user-images.githubusercontent.com/30922566/184572243-9b8e9ba4-02d4-4ea6-a937-fb9e5d4709ab.png">
<img width="1193" alt="WX20220815-112817@2x" src="https://user-images.githubusercontent.com/30922566/184572329-f9c2d20b-6d04-40b2-9f0d-273f1bffd2a0.png">

如上图所示。

### Reproduction / 复现链接

<img width="911" alt="WX20220815-112914@2x" src="https://user-images.githubusercontent.com/30922566/184572465-903dc049-25bd-4444-a425-f21727ccef25.png">

**Comment by c939984606** [comment]
https://api.nn.ci/ocr/file/json

OCR API  404打不开了

**Comment by mtn888** [comment]
the same problem!

**Comment by qkmy** [comment]
the same problem!

**Comment by c939984606** [comment]
https://api.xhofe.top/ocr/file/json
先用这个ocr吧，设置-后端- ocr api

**Comment by THINK37** [comment]
> [https://api.hofe.top/ocrfile/json](https://api.xhofe.top/ocr/file/json) 先用ocr吧，设置-xr-这个api/ocr ac
好像这个也不行了

**Comment by Xhofe** [comment]
如无法访问公共ocr api，请考虑自部署：https://alist.nn.ci/config/global.html#ocr-api

**Comment by myselfghost** [comment]
https://api.xhofe.top/ocr/file/json  这个可用

**Comment by michealhansun** [comment]
> 如无法访问公共ocr api，请考虑自部署：https://alist.nn.ci/config/global.html#ocr-api

![image_2023-05-25_08-32-53](https://github.com/alist-org/alist/assets/9845710/c0e552f9-9a52-4173-b2b2-2aa5aca8b56b)
这种是搭建成功了吗，请问如何使用的
