### ISSUE TITLE
能否增加个端口号修改,由于本人技术不足,没法逆向

### ISSUE THREAD

**Issue by tangjin2580** [alist-org/alist#1513]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增加个修改端口号的功能

**Comment by cyrxdzj** [comment]
@tangjin2580 请打开alist同一目录下的config.json

**Comment by cyrxdzj** [comment]
可能不在alist同一目录。
![image](https://user-images.githubusercontent.com/63708985/185899711-88555c4a-1e61-4a10-9992-491aa03afe9e.png)

**Comment by tangjin2580** [comment]
好的找到了,非常感谢
