### ISSUE TITLE
2.6.4版本下载代理失效，显示http/1.1 500 internal server error或SSL connection_error 5

### ISSUE THREAD

**Issue by fl0w1nd** [alist-org/alist#1522]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

* 之前2.6.3版本时使用cloudflare workers的下载中转正常，然后今天升级了2.6.4版本后文件无法正常下载显示http/1.1 500 internal server error或SSL connection_error 5，退回2.6.3时正常。觉得应该是需要修改代理js代码了。

### Reproduction / 复现链接

https://github.com/alist-org/alist-proxy/blob/main/alist-proxy.js

**Comment by yubanmeiqin9048** [comment]
是不是用了非标准端口的原因
