### ISSUE TITLE
在线xlsx报错

### ISSUE THREAD

**Issue by Clove-MJC** [alist-org/alist#1524]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

V2.0

### Driver used / 使用的存储驱动

本地服务器

### Describe the bug / 问题描述

An error occurred
We're sorry, but for some reason we can't open this for you.
[Learn more](https://r.office.microsoft.com/r/rlidowaviewhelp)

### Reproduction / 复现链接

An error occurred
We're sorry, but for some reason we can't open this for you.
[Learn more](https://r.office.microsoft.com/r/rlidowaviewhelp)

### Logs / 日志

```shell
An error occurred
We're sorry, but for some reason we can't open this for you.
Learn more
```

**Comment by Clove-MJC** [comment]
v2.6.4-0-gbd52df1-dirty 版本号

**Comment by Xhofe** [comment]
https://antfu.me/posts/why-reproductions-are-required

**Comment by woshichenghaibo** [comment]
我的也是这样，从来没有成功过。
