### ISSUE TITLE
希望可以后退后回到之前的浏览位置

### ISSUE THREAD

**Issue by zzh4n** [alist-org/alist#1527]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

每次后退上一级目录都会回到列表顶部，在文件夹较多、需要经常前进后退浏览文件列表时非常不方便

### Suggested solution / 实现思路

后退后回到之前的浏览位置，并框选标记上一次打开的子文件夹以方便定位

**Comment by ShinChven** [comment]
`cmd/ctrl`+`左键` 点击链接可以解决你这个问题。
