### ISSUE TITLE
123盘挂载报错

### ISSUE THREAD

**Issue by aotuitx** [alist-org/alist#1528]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4-0-gbd52df1

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

打开挂载目录后提示：123pan rate limit type min

### Reproduction / 复现链接

https://tool.icafe8.top/1

### Logs / 日志

```shell
[GIN] 2022/08/19 - 10:17:16 | 200 |     220.944µs | *.*.*.* | POST     "/api/public/path"
[GIN] 2022/08/19 - 10:17:18 | 200 |       58.81µs | *.*.*.* | GET      "/"
[GIN] 2022/08/19 - 10:17:19 | 200 |     420.728µs | *.*.*.* | GET      "/api/admin/settings?group=1"
[GIN] 2022/08/19 - 10:17:19 | 200 |     296.185µs | *.*.*.* | GET      "/api/public/settings"
[GIN] 2022/08/19 - 10:17:19 | 200 |      15.298µs | *.*.*.* | GET      "/api/admin/verify"
[GIN] 2022/08/19 - 10:17:19 | 200 |     205.103µs | *.*.*.* | POST     "/api/public/path"
ERRO[2022-08-19 10:17:20] 123pan rate limit type min                   
[GIN] 2022/08/19 - 10:17:20 | 200 |   80.220763ms | *.*.*.* | POST     "/api/public/path"
```

**Comment by Xhofe** [comment]
超出请求限制，非bug。

**Comment by aotuitx** [comment]
> 请求超出限制，非bug。

那，无解？只能换帐号了？
