### ISSUE TITLE
S3 的 custom_host  配置项，对 host 含义的理解有误

### ISSUE THREAD

**Issue by baobao1270** [alist-org/alist#1531]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4-0-gbd52df1-dirty

### Driver used / 使用的存储驱动

S3

### Describe the bug / 问题描述

对于 S3 Driver，当配置 Custom Host 为不带 schema 的地址（如 `cdn.example.com`）时，将导致 404 错误。只有当配置为带 schema 的地址（如 `https://cdn.example.com`）时，才能够正常访问。

根据 [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.2) 的定义，host 应当为 IP 地址或域名，并不带有协议名称。自定义 Custom Domain 的协议，也可能导致 mixed content 问题。

在 https://github.com/alist-org/alist/blob/v2/drivers/s3/s3.go#L41 中，代码使用了解析 URL 的方式解析 host，然后将 custom_host 的 schema 和 host 都用于替换重定向的链接。

```go
cURL, err := url.Parse(account.CustomHost)
if err != nil {
	return nil, err
}
client.Handlers.Build.PushBack(func(r *request.Request) {
	if r.HTTPRequest.Method != http.MethodGet {
		return
	}
	r.HTTPRequest.URL.Scheme = cURL.Scheme
	r.HTTPRequest.URL.Host = cURL.Host
})
```

个人认为，预期的行为应当是只替换 host，而不替换 schema。

---

可选的解决方法有以下几种，也可以组合使用：

1. 直接用 custom host 替换 host，不解析为 URL：
   ```go
   client.Handlers.Build.PushBack(func(r *request.Request) {
	if r.HTTPRequest.Method != http.MethodGet {
		return
	}
	r.HTTPRequest.URL.Host = account.CustomHost
   })
   ```
2. 增加判断逻辑，如果 custom host 的 schema 为空，则默认为 HTTPS；如果 custom host 的 schema 不为空，则使用之。同时增加对 schema 的判断，仅允许 HTTP、HTTPS 及 FTP 协议，防止潜在的安全问题（如通过自定义 schema 唤起本地程序）。
3. 在文档中加入相关说明。

### Reproduction / 复现链接

https://github.com/alist-org/alist/blob/v2/drivers/s3/s3.go#L41

**Comment by Xhofe** [comment]
Fixed at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
