### ISSUE TITLE
保存Casdoor Jwt Public Key配置项时会导致格式错误

### ISSUE THREAD

**Issue by wenxuan70** [alist-org/alist#1538]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4

### Driver used / 使用的存储驱动

none

### Describe the bug / 问题描述

在配置后端的Casdoor Jwt Public Key选项时，input标签会把移除换行符，导致在经过casdoor sdk验证code时会报无效的证书格式异常。

### Reproduction / 复现链接

![6d0225a033cffd9411cdab9ea18de17](https://user-images.githubusercontent.com/55948263/185751513-9c6b4f32-de31-4f70-ae3a-c1e3540af3d4.jpg)
![image](https://user-images.githubusercontent.com/55948263/185751697-6bd3a7b9-7585-4250-9d2e-d1d97cdf28ce.png)

**Comment by NoverNobida** [comment]
但是最新版本 ( xhofe/alist:latest 即 xhofe/alist:v2.6.4 ) 还是有这个问题，无论是全选复制，还是点击casdoor自带的复制按钮复制，最终都会有 `invalid key` 这个错误。最终还是通过用数据库工具（DBeaver)，在软件里面粘贴，才没有出现错误。

**Comment by wenxuan70** [comment]
> 但是最新版本 ( xhofe/alist:latest 即 xhofe/alist:v2.6.4 ) 还是有这个问题，无论是全选复制，还是点击casdoor自带的复制按钮复制，最终都会有 `invalid key` 这个错误。最终还是通过用数据库工具（DBeaver)，在软件里面粘贴，才没有出现错误。

最新版的alist还没有包含修复这个bug的代码。

**Comment by wenxuan70** [comment]
可以采用源码的方式运行alist，https://alist-doc.nn.ci/docs/install/source-code
