### ISSUE TITLE
Onedrive E5账户报错

### ISSUE THREAD

**Issue by PeakGymnast** [alist-org/alist#1540]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4

### Driver used / 使用的存储驱动

Onedrive E5

### Describe the bug / 问题描述

Onedrive E5账户出现这种情况，报错，**Onemanager**没出现这种情况
![photo_2022-08-20_23-31-31](https://user-images.githubusercontent.com/85560713/185755509-d35392bf-d674-4942-8a19-562fda5894c7.jpg)
![image](https://user-images.githubusercontent.com/85560713/185755547-c4bfdd2e-11ca-4209-81bd-d0c4e7cc54dc.png)

### Reproduction / 复现链接

不明

**Comment by Xhofe** [comment]
找不到填写的根路径。
