### ISSUE TITLE
首次访问报 unexpected EOF

### ISSUE THREAD

**Issue by sxjeru** [alist-org/alist#1548]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4

### Driver used / 使用的存储驱动

无关

### Describe the bug / 问题描述

新用户访问，或隔一段时间后访问网站，第一次必报 unexpected EOF，并且无法进入。（停留在加载动画）
尽快刷新后可进入，若拖延了一会，则刷新后依旧报错 unexpected EOF.

后台日志：
```
ERRO[2022-08-21 23:55:31] unexpected EOF
[GIN] 2022/08/21 - 23:55:31 | 200 | 1.254321ms | ip | GET "/api/public/settings"
[GIN] 2022/08/21 - 23:55:32 | 200 | 22.82µs | ip | GET "/api/admin/verify"
[GIN] 2022/08/21 - 23:55:33 | 200 | 1.683567805s | ip | GET "/api/admin/settings?group=1"
```
尽快刷新后正常进入，输出以下内容：
```
[GIN] 2022/08/21 - 23:57:31 | 200 | 83.11µs | ip | GET "/"
[GIN] 2022/08/21 - 23:57:32 | 200 | 115.731607ms | ip | GET "/api/admin/settings?group=1"
[GIN] 2022/08/21 - 23:57:33 | 200 | 120.181µs | ip | GET "/api/admin/verify"
[GIN] 2022/08/21 - 23:57:33 | 200 | 209.832295ms | ip | GET "/api/public/settings"
[GIN] 2022/08/21 - 23:57:34 | 200 | 220.660714ms | ip | POST "/api/public/path"
```
正在使用 bit.io 提供的远程数据库。

### Reproduction / 复现链接

https://eru-alist-sxjeru.koyeb.app/

若无法复现，请稍后再试。

**Comment by Xhofe** [comment]
网络问题自行解决。

**Comment by sxjeru** [comment]
基本确认是数据库服务的问题，更换后解决。
