### ISSUE TITLE
invalid auth config

### ISSUE THREAD

**Issue by PeakGymnast** [alist-org/alist#1551]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4

### Driver used / 使用的存储驱动

Onedrive E5

### Describe the bug / 问题描述

Ubuntu无法启动./alist-linux-amd64，显示**invalid auth config**，只是在后端添加了个OneDrive e5账户，使用窗口**screen ./alist-linux-amd64**就启动失败，未修改过密码

![image](https://user-images.githubusercontent.com/85560713/186032287-406ea81b-bbb9-4394-be0f-d36833f70fb9.png)

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
删除重装，不要再打开enable casdoor。
或者手动在数据库中禁用casdoor。

**Comment by PeakGymnast** [comment]
> 删除重装，不要再打开enable casdoor。 或者手动在数据库中禁用casdoor。

好的，感谢大佬
