### ISSUE TITLE
Hope to add MEGA drive support

### ISSUE THREAD

**Issue by TankTim68** [alist-org/alist#1553]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Hope to add MEGA drive support
web url: https://mega.nz/

**Comment by Xhofe** [comment]
dcaaae366bff2b37e2c14915b7f32405729d3fe0
