### ISSUE TITLE
腾讯云对象存储多一个不存在的文件

### ISSUE THREAD

**Issue by yoval** [alist-org/alist#1561]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4-0-gbd52df1-dirty

### Driver used / 使用的存储驱动

COS

### Describe the bug / 问题描述

![](https://yun.bizha.top/d/Google/Img/BaiduShurufa_2022-8-24_16-41-58.png)

### Reproduction / 复现链接

https://yun.bizha.top/COS

**Comment by Xhofe** [comment]
占位文件 将placeholder filename设置为空即可消除。
