### ISSUE TITLE
求不同云盘间通过webdav复制文件的shell脚本

### ISSUE THREAD

**Issue by dycfan** [alist-org/alist#1564]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

您好！能不能提供一个 linux shell脚本：将百度云盘上的指定文件夹或者文件稳定复制到阿里云盘或者天翼云盘上的指定文件夹。
目前我的做法：
1、将百度云盘和阿里云盘的webdav挂载到本地。
2、用cp命令复制百度云盘上的文件到阿里云盘。
后果：小文件没问题。大文件出错（百度云盘的webdav设置开启了代理，不开启代理根本就无法复制）。

**Comment by xuan-git** [comment]
让我想到我的产品

**Comment by Xhofe** [comment]
v3中将内置。

**Comment by 1-1-2** [comment]
> v3中将内置。

跨存储复制，遇到了以下情况：
1. 页面提示成功，但没有在新路径下发现文件。
2. 复制文件夹A到阿里云根目录，阿里云根目录下生成了一堆A目录下文件的同名文件夹但没有成功拷贝文件

请问跨存储间是有限条件使用吗？ @Xhofe

**Comment by Xhofe** [comment]
> > v3中将内置。
> 
> 跨存储复制，遇到了以下情况：
> 1. 页面提示成功，但没有在新路径下发现文件。
> 2. 复制文件夹A到阿里云根目录，阿里云根目录下生成了一堆A目录下文件的同名文件夹但没有成功拷贝文件
> 
> 请问跨存储间是有限条件使用吗？ @Xhofe 

后台tasks查看具体信息。

**Comment by 1-1-2** [comment]
> 后台tasks查看具体信息。

![image](https://user-images.githubusercontent.com/50569812/189901199-5ba546f4-28d4-43c4-932c-190ece03bd5e.png)

感谢回复，v3一时还不太习惯。第一条确认了是进度条没走完，第二条问题还是存在的。如图复制文件夹，提示包含文件，复制完后是文件夹

![image](https://user-images.githubusercontent.com/50569812/189901968-267baf6c-32d0-4145-b5da-4d9d55a2a7bc.png)
