### ISSUE TITLE
Add Custom Host option to SFTP storage type.

### ISSUE THREAD

**Issue by yntzes** [alist-org/alist#1574]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

This is a small feature request as the title is.

### Suggested solution / 实现思路

As how S3 do,it'll be simple to realize.Thanks to develpers of Alist!

**Comment by Xhofe** [comment]
Sorry i don't quite understand. Does SFTP have this parameter?

**Comment by yntzes** [comment]
I think I'm a little bit more strict.Because I found that if use SFTP,downloading will be proxyed by alist.Thank you all the same.
