### ISSUE TITLE
增加对telegram的支持

### ISSUE THREAD

**Issue by shaojs321** [alist-org/alist#1575]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

作者能否增加对telegram的支持，telegram个人账户能够当做云盘使用，并且官方不对存储空间，下载上传速度做限制，比谷歌云盘好用多了，目前看起来没有封号的风险

**Comment by Xhofe** [comment]
duplicate with #696

**Comment by suykjay** [comment]
用“T-Drive”当过网盘，被封了一个号，建议不要专门用做网盘。
