### ISSUE TITLE
阿里云封号严重，可否添加禁用下载功能

### ISSUE THREAD

**Issue by 676407926** [alist-org/alist#1576]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

针对封号问题，元信息添加“下载权限管理”

### Suggested solution / 实现思路

相应路径下载功能仅限于管理员，访客禁用。
期待！！！

**Comment by geeklihui** [comment]
给特定路径加访问密码不就行了

**Comment by 676407926** [comment]
> 给特定路径加访问密码不就行了


> 给特定路径加访问密码不就行了

那样访客可就无法访问了呀。我只想禁访客下载而已。

**Comment by geeklihui** [comment]
> > 给特定路径加访问密码不就行了
> 
> > 给特定路径加访问密码不就行了
> 
> 那样访客可就无法访问了呀。我只想禁访客下载而已。

没太明白能访问但不能下载的意义在哪里......

**Comment by Xhofe** [comment]
> > > 给特定路径加访问密码不就行了
> > 
> > 
> > > 给特定路径加访问密码不就行了
> > 
> > 
> > 那样访客可就无法访问了呀。我只想禁访客下载而已。
> 
> 没太明白能访问但不能下载的意义在哪里......

同问。

**Comment by SOVLOOKUP** [comment]
流量代理

**Comment by flower-elf** [comment]
这本身是一个文件目录列表程序
你说的这个需求只需简单的设置访问密码即可
目前此类文件列表程序对于可预览文件是“访问即下载”
而对于不可预览文件，本身就是要下载才能浏览的
所以这个问题没有什么意义
