### ISSUE TITLE
建议修改分享时的页页信息

### ISSUE THREAD

**Issue by vbskycn** [alist-org/alist#1588]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在浏览器上查看网站内容，进入二级目录，或是三级目录
想要分享给好友，比如分享到微信
![](https://img.zhoujie218.top/piggo/202209022036482.png)
它只会显示网站名称
这样的话，网站内容有很多个，那分享任何一个内容都是相同的
可否在分享的页面上直接显示目录名字  一级目录名/二级目录名/分享的内容

**Comment by vbskycn** [comment]
**比如"学习资料'  能否显示网盘内所在的目录名**

**Comment by Xhofe** [comment]
fixed in v3.
