### ISSUE TITLE
Onedrive不支持在线预览PDF和打包下载

### ISSUE THREAD

**Issue by Edge-coordinates** [alist-org/alist#1595]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4-0-gbd52df1-dirty

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

我使用ALIST链接了Onedrive gobal，网盘，但是我无法预览PDF文档，如下图，但是如.doc之类的文件是可以预览的。
![image](https://user-images.githubusercontent.com/68896486/188265945-516a2627-85ca-4869-ad74-2c07a6631f55.png)

同时，打包下载功能也不是很好，它一直在加载，没有报错，但也不会开始下载。

我的服务器使用的是Caddy,配置如下：
```
alist.ics.ink {
	reverse_proxy 127.0.0.1:5244
}
```
我使用了Https,同时有开启证书。

### Reproduction / 复现链接

https://alist.ics.ink/Edge01/%E6%8A%80%E6%9C%AF%E4%B9%A6%E7%B1%8D/Python%E6%A0%B8%E5%BF%83%E7%BC%96%E7%A8%8B%EF%BC%88%E4%B8%AD%E6%96%87%E7%AC%AC%E4%BA%8C%E7%89%88%EF%BC%89%E5%B8%A6%E7%9B%AE%E5%BD%95.pdf

### Logs / 日志

```shell
PDF.js v2.12.305 (build: d3e1d7090)
信息：Failed to fetch
```

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/188266225-986f7845-c4c3-4a7a-972c-266652656202.png)

![image](https://user-images.githubusercontent.com/36558727/188266271-136bced4-7adf-4919-bef2-28de72ecbb29.png)

**Comment by Edge-coordinates** [comment]
> ![image](https://user-images.githubusercontent.com/36558727/188266225-986f7845-c4c3-4a7a-972c-266652656202.png)
> 
> ![image](https://user-images.githubusercontent.com/36558727/188266271-136bced4-7adf-4919-bef2-28de72ecbb29.png)

![image](https://user-images.githubusercontent.com/68896486/188266817-927496ac-1725-4879-8ba4-0b9b1bf275aa.png)
然而我这边显然还是不行，请问到底是怎样的情况，谢谢，新的图片挂载的是CloudFlare的S3。

**Comment by Edge-coordinates** [comment]
> ![image](https://user-images.githubusercontent.com/36558727/188266225-986f7845-c4c3-4a7a-972c-266652656202.png)
> 
> ![image](https://user-images.githubusercontent.com/36558727/188266271-136bced4-7adf-4919-bef2-28de72ecbb29.png)

我知道原因了。。。谢谢
