### ISSUE TITLE
强烈建议大佬增加支持115网盘挂载

### ISSUE THREAD

**Issue by ahuaiph** [alist-org/alist#1598]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

115网盘作为一个使用度也很高的网盘，内存空间也比某度大多了，很适合用来搭建家庭媒体库，但需要有一个挂在工具，目前能用的挂在工具是clouddrive，但是它有一个很严重的问题，就是挂载后显示的文件内容不全，导致一些原盘高清的电影找不到，没法看。希望大佬能增加支持115网盘的挂载，感激不尽~~~

**Comment by Xhofe** [comment]
duplicate with #894
