### ISSUE TITLE
阿里云盘内有些视频文件打开出错

### ISSUE THREAD

**Issue by vbskycn** [alist-org/alist#1599]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

2.6.4

### Driver used / 使用的存储驱动

阿里云

### Describe the bug / 问题描述

![mmexport1662295790501](https://user-images.githubusercontent.com/34542650/188314303-791dd87e-aeaa-43d8-8830-2738c0cceea1.jpg)
![mmexport1662295857694](https://user-images.githubusercontent.com/34542650/188314355-51411e2c-13db-422f-a00d-09f4f2481b00.jpg)

比如这个目录下的视频，用电脑 安卓手机打开就正常，ios就报错
还有一些目录下的文件不管什么设备访问都是出错的，只有用阿里云盘官方程序才能打开

### Reproduction / 复现链接

https://xue.zhoujie218.top/%E6%AD%A3%E5%9C%A8%E4%BD%BF%E7%94%A8/%E5%9B%9B%E5%B9%B4%E7%BA%A7%E4%B8%8A/%E8%8B%B1%E8%AF%AD/%E8%8B%B1%E8%AF%AD%E5%9B%9B%E5%B9%B4%E7%BA%A7%E4%B8%8A%E5%86%8C%E4%BA%BA%E6%95%99PEP%E7%89%88%E5%90%8C%E6%AD%A5%E7%B2%BE%E8%AE%B2%E5%90%88%E9%9B%86

**Comment by vbskycn** [comment]
https://xue.zhoujie218.top/%E6%A8%8A%E7%99%BB%E8%AF%BB%E4%B9%A6%E4%BC%9A/%E6%96%B0%E7%88%B6%E6%AF%8D%E4%BA%94%E9%97%A8%E5%BF%85%E4%BF%AE%E5%A4%A7%E8%AF%BE
这个目录下的视频  安卓  ios 电脑  都打不开

**Comment by vbskycn** [comment]
？？？这个是我的个人原因吗？

**Comment by tlze** [comment]
用播放器，有很多编码浏览器不支持，详细看文档说明。

**Comment by vbskycn** [comment]
好的，非常感谢，一时没有想到
