### ISSUE TITLE
能否在native(本地)驱动中增加对.strm文件（emby中的strm）的支持

### ISSUE THREAD

**Issue by yzqiang666** [alist-org/alist#1602]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

http://smccb.tk:901/video/Videos/TV/鱿鱼游戏/鱿鱼游戏.S01E01.mkv?size=2917815589&ct=1654310945&mt=1654310945

**Comment by Xhofe** [comment]
请描述详细。

**Comment by yzqiang666** [comment]
在strm文件中保存如下内容：
http://smccb.tk:901/video/Videos/TV/鱿鱼游戏/鱿鱼游戏.S01E01.mkv?size=2917815589&ct=1654310945&mt=1654310945
size为文件大小
ct为文件创建时间
mt为文件修改时间

要求在界面中正确显示文件信息，下载或播放时自动链接到实际的http链接中。
