### ISSUE TITLE
添加静态文件服务的站点功能

### ISSUE THREAD

**Issue by SOVLOOKUP** [alist-org/alist#1607]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

设置一个目录为站点目录，供上传前端文件，部署网站使用。

**Comment by Xhofe** [comment]
Out of scope
