### ISSUE TITLE
希望添加个 直接连接阿里云盘分享连接的功能！实现无限空间的功能！

### ISSUE THREAD

**Issue by 56965779** [alist-org/alist#1608]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist的开发者你好！
希望添加个 直接连接阿里云盘分享连接的功能！实现无限空间的功能！
阿里云盘的分享连接登录后是可以直接不用保存可以直接获取到下载地址的！
这样的话就可以实现只需要收集分享连接就可以得到无限多的资源！不用保存到空间里！

### Suggested solution / 实现思路

只需要收集分享连接 如：Z 再造战士4K REMUX (1992)【0678】  https://www.aliyundrive.com/s/FCVDNBZA1i9
即可解析出下载地址：
https://api.aliyundrive.com/v2/file/get_share_link_download_url

**Comment by Xhofe** [comment]
duplicate with #1215
