### ISSUE TITLE
希望增加转存功能，实现不同网盘间文件传输

### ISSUE THREAD

**Issue by Timor88** [alist-org/alist#1618]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

举例：百度网盘不能在线查看视频文件，而阿里云盘可以，将百度盘的文件转存至阿里云盘，实现在线播放。

### Suggested solution / 实现思路

以服务器为中介，将百度云盘的文件下载至服务器，再上传至阿里云盘。

**Comment by Xhofe** [comment]
duplicate with #1212
