### ISSUE TITLE
希望增加谷歌云盘的共享盘支持

### ISSUE THREAD

**Issue by JoyeChen-Got** [alist-org/alist#1630]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

![image](https://user-images.githubusercontent.com/105471886/189485899-95abb2d1-8c8c-4d60-879a-1b5b2193ae1a.png)
V2版本可以把共享盘添加快捷方式到自己的云端硬盘然后设置alist根目录形式，V3版本不行了

**Comment by Xhofe** [comment]
根目录设置为共享盘id即可。
