### ISSUE TITLE
open page error error when docker deploy in Raspbian

### ISSUE THREAD

**Issue by muzhi1991** [alist-org/alist#1631]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist-doc.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

 v3.0.0-beta.1

### Driver used / 使用的存储驱动

none

### Describe the bug / 问题描述

open web show error:
failed get storage: can't find storage with rawPath: /

exec container can't find 6800 process running.

os version:
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

docker version:
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:51 2022
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

docker cmd: 

### Reproduction / 复现链接

docker run -d --restart=always -v /etc/alist:/opt/alist/data -p 5244:5244 --name="alist" xhofe/alist:latest

### Logs / 日志

```shell
docker logs show:

ERRO[2022-09-10 15:49:54] failed to init aria2 client: Post "http://localhost:6800/jsonrpc": dial tcp 127.0.0.1:6800: connect: connection refused
failed get aria2 version
github.com/alist-org/alist/v3/internal/aria2.InitAria2Client
	/app/internal/aria2/aria2.go:33
github.com/alist-org/alist/v3/internal/aria2.InitClient
	/app/internal/aria2/aria2.go:23
github.com/alist-org/alist/v3/internal/bootstrap.InitAria2.func1
	/app/internal/bootstrap/aria2.go:10
runtime.goexit
	/usr/lib/go/src/runtime/asm_arm.s:831
```

**Comment by gongzhaoxi** [comment]
这个不是报错，是找不能储存，
在页面右下“管理”里重建“储存”就可以了
