### ISSUE TITLE
启动动画在下个版本可否增加个开关功能

### ISSUE THREAD

**Issue by mnwgkj** [alist-org/alist#1632]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

去除不了 启动的时候占用过多时间

**Comment by Xhofe** [comment]
不认为白屏比动画的体验好。
