### ISSUE TITLE
添加天翼云盘报错

### ISSUE THREAD

**Issue by cnfug** [alist-org/alist#1638]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6

### Driver used / 使用的存储驱动

天翼云盘

### Describe the bug / 问题描述

添加天翼云盘报错

### Reproduction / 复现链接

添加天翼云盘报错

### Logs / 日志

```shell
2022/09/11 08:07:01.270999 ERROR RESTY Post "https://api.nn.ci/ocr/file/json": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
```

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/config/global.html#ocr-api

**Comment by mffan0922** [comment]
> https://alist.nn.ci/zh/config/global.html#ocr-api

请问这个的意思是ocr有时候会不准吗，我这边偶尔会有alist主页目录结构不显示，failed报错
