### ISSUE TITLE
打开首页后不出目录，提示 date/signature is null

### ISSUE THREAD

**Issue by qingee** [alist-org/alist#1640]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.4

### Driver used / 使用的存储驱动

百度和天翼

### Describe the bug / 问题描述

打开首页后不出目录，提示 date/signature is null

### Reproduction / 复现链接

https://www.vmpan.com/

**Comment by Xhofe** [comment]
No longer maintained
