### ISSUE TITLE
Aria2无法正常下载

### ISSUE THREAD

**Issue by sunnynctu** [alist-org/alist#1650]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-beta.2

### Driver used / 使用的存储驱动

Onedrive、AliDrive、Local

### Describe the bug / 问题描述

Alist最新beta版本，挂载了Onedrive、阿里云盘和服务器本地存储都能正常上传下载，但无法使用Aria2离线下载，添加任务时提示：
Failed to add uri https://***.**/***.exe: context deadline exceeded
这个时候Aria2里面会添加任务并完成下载，下载完后会自动删除文件

如果单独使用aria2可以正常下载到服务器本地存储

烦请大佬指教一下

### Reproduction / 复现链接

从略

### Logs / 日志

```shell
从略
```

**Comment by sunnynctu** [comment]
再补充一下，aria2采用的是ws协议

**Comment by sunnynctu** [comment]
从Aria2里面看到的任务下载路径: /opt/alist/data/temp/aria2/1249ec4b-b9f9-49df-9a48-a2afb1e758d4
这个路径下面有历次尝试添加任务下载好的文件，说明Aria2是正常运作的
但不知为何添加任务会出现“Failed to add uri https://./**.exe: context deadline exceeded”错误提示，也没推送到指定存储驱动下的路径

**Comment by Xhofe** [comment]
使用http协议呢？

**Comment by lowking** [comment]
> 使用http协议呢？

希望支持ws协议，我也是无法下载，提示：Failed to send to aria2: AxiosError: Unsupported protocol ws:
