### ISSUE TITLE
大量文件上传夸克内存泄漏

### ISSUE THREAD

**Issue by zxcvbnmzsedr** [alist-org/alist#1661]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-beta.2

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

大量文件通过rclone sync的方式同步到alist 的webdav接口，会导致服务异常退出

刚开始的内存占用：
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/14026790/189862827-9b65af8c-0f2b-4ccb-a1a9-40731d5cb5d4.png">

开启上传之后，内存猛增最后被系统杀掉：
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/14026790/189863146-4a8158dd-ba2c-48bc-bd85-d6eac91d2b05.png">

### Reproduction / 复现链接

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/14026790/189864341-2c5e2f5b-786d-4897-af48-16a2d6b82c25.png">

**Comment by Xhofe** [comment]
journalctl -u alist
与log/log.log
完整日志

**Comment by zxcvbnmzsedr** [comment]
[alist.log](https:/
[log.log](https://github.com/alist-org/alist/files/9555695/log.log)
/github.com/alist-org/alist/files/9555692/alist.log)

**Comment by zxcvbnmzsedr** [comment]
[journalctl -u alist](https://github.com/alist-org/alist/files/9555700/alist.log)

[log.log](https://github.com/alist-org/alist/files/9555702/log.log)

**Comment by zxcvbnmzsedr** [comment]
看日志应该是出现在 fs.go: 180
