### ISSUE TITLE
阿里云盘+RaiDrive，提示wsasend: An existing connection was forcibly closed by the remote host.有什么办法解决

### ISSUE THREAD

**Issue by caodaye** [alist-org/alist#1666]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V2.6.4

### Driver used / 使用的存储驱动

AliyunDirve	

### Describe the bug / 问题描述

我用阿里云盘+RaiDrive，文件会有
ERRO[2022-09-13 20:17:09] write tcp 127.0.0.1:5244->127.0.0.1:65053: wsasend: An existing connection was forcibly closed by the remote host.
[GIN] 2022/09/13 - 20:17:09 | 500 |    786.4838ms |       127.0.0.1 | GET      
这个的提示，有啥办法解决么，还是需要修改什么。

### Reproduction / 复现链接

从略

### Logs / 日志

```shell
无
```

**Comment by Xhofe** [comment]
无视即可。
