### ISSUE TITLE
希望增加iOS16在线安装IPA的协议

### ISSUE THREAD

**Issue by jinchunyou** [alist-org/alist#1677]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加iOS16在线安装IPA的协议

**Comment by Xhofe** [comment]
Provide the details of the protocol, please

**Comment by Netskao** [comment]
itms-services:// 在线安装协议iOS16严格了

简单来说就是安装协议plist文件中的bundle-identifier字段内容必须和iPA包中info.plist的CFBundleIdentifier内容相同

位于此处https://github.com/alist-org/alist/blob/main/server/handles/helper.go#L55

**Comment by xiaowang7212** [comment]
> 

意思是不是，alist这种分发永远不可能支持ios16了，那有没有办法绕过呢

**Comment by Netskao** [comment]
那就看作者怎么实现了

最无脑的就是直接解压iPA提取info.plist中CFBundleIdentifier字段内容来填充

不清楚go是否有不需要解压就可以提取zip内文件流的，如果有那实现就更加方便了

或者开放后端可设置不同iPA的bundle-identifier字符串自定义(对于双方都麻烦

具体看作者如何解决吧

**Comment by xiaowang7212** [comment]
> 那就看作者怎么实现了
> 
> 最无脑的就是直接解压iPA提取info.plist中CFBundleIdentifier字段内容来填充
> 
> 不清楚go是否有不需要解压就可以提取zip内文件流的，如果有那实现就更加方便了
> 
> 或者开放后端可设置不同iPA的bundle-identifier字符串自定义(对于双方都麻烦
> 
> 具体看作者如何解决吧

基本上解决起来很麻烦，例如蓝奏云也都不行了。

**Comment by Xhofe** [comment]
> itms-services:// 在线安装协议iOS16严格了
> 
> 简单来说就是安装协议plist文件中的bundle-identifier字段内容必须和iPA包中info.plist的CFBundleIdentifier内容相同
> 
> 位于此处https://github.com/alist-org/alist/blob/main/server/handles/helper.go#L55

我尝试了使用iPA包中info.plist的CFBundleIdentifier作为plist文件中的bundle-identifier，似乎仍然无法正常安装。你可以提供一个可以工作的ipa和plist文件吗？

**Comment by Netskao** [comment]
尝试安装的IPA文件签名是否正常？

**Comment by Xhofe** [comment]
> 尝试安装的IPA文件签名是否正常？

我不是很懂ipa签名这方面的信息，只是网上随便找的。

**Comment by Netskao** [comment]
那就直接使用爱思助手的IPA给你测试

itms-services://?action=download-manifest&url=https://initnil.com/installApp.plist

只要iPA签名正常和bundle-identifier符合iPA内CFBundleIdentifier的内容，iOS16肯定是正常的

下次发行Beta时可更新出来让大家试试即可

**Comment by Xhofe** [comment]
> 那就直接使用爱思助手的IPA给你测试
> 
> itms-services://?action=download-manifest&url=https://initnil.com/installApp.plist
> 
> 只要iPA签名正常和bundle-identifier符合iPA内CFBundleIdentifier的内容，iOS16肯定是正常的
> 
> 下次发行Beta时可更新出来让大家试试即可

确实可以安装了 但是我无法打开这个应用 这是正常的吗

**Comment by Netskao** [comment]
爱思助手的包是这样的，如果手机没有连接过电脑使用过爱思助手就无法正常打开，因为没有同步他的ID数据(这就是题外话了

能正常安装就代表正常！

**Comment by Xhofe** [comment]
那么现在可以使用 https://github.com/alist-org/alist/actions/runs/3073536693 此版本测试
文件名规则为：`原文件名_bundle-identifier.ipa`

**Comment by Netskao** [comment]
本来想试试的，发现v3版本IPA点击安装按钮无反应

似乎其他用户的v3版本也如此

**Comment by xiaowang7212** [comment]
> 本来想试试的，发现v3版本IPA点击安装按钮无反应
> 
> 似乎其他用户的v3版本也如此

V3 目前所以系统都不能在线安装ipa  点了没反应了·

**Comment by ying-zi** [comment]
这里有一个样例，也是上传ipa后支持正常安装，不知道对你有没有帮助

> Provide the details of the protocol, please

这里有一个样例，也是上传ipa后支持正常安装，不知道对你有没有帮助

https://ipasd.herokuapp.com/

**Comment by Netskao** [comment]
> 那么现在可以使用 https://github.com/alist-org/alist/actions/runs/3073536693 此版本测试
> 文件名规则为：`原文件名_bundle-identifier.ipa`

使用目前的最新构建，并且按照你新更改的 `原文件名@bundle-identifier.ipa` 已经可以正常支持iOS16安装了

新问题，如果文件名称中包含中文点击预览页面会出现:
System error: InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**Comment by Xhofe** [comment]
> > 那么现在可以使用 https://github.com/alist-org/alist/actions/runs/3073536693 此版本测试
> > 文件名规则为：`原文件名_bundle-identifier.ipa`
> 
> 使用目前的最新构建，并且按照你新更改的 `原文件名@bundle-identifier.ipa` 已经可以正常支持iOS16安装了
> 
> 新问题，如果文件名称中包含中文点击预览页面会出现: System error: InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

新问题请重新打开一个issue，此issue将被标记为已解决。
