### ISSUE TITLE
升级了V3，Raidrive挂载后不能写入！！

### ISSUE THREAD

**Issue by kitkw** [alist-org/alist#1678]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-beta.2

### Driver used / 使用的存储驱动

ali

### Describe the bug / 问题描述

升级了V3，Raidrive挂载后不能写入（用于TMM搜刮）！！ v2版时没有这个问题   Raidrive 挂载另一个插件aliyundrive-webdav  也能正常写入

### Reproduction / 复现链接

以上

**Comment by zzwsfnas** [comment]
也不能删除文件了

**Comment by zzwsfnas** [comment]
也不能删除文件了

**Comment by kitkw** [comment]
> 也不能删除文件了

文件可以删，也能创建文件夹。但几K的东西也传不上.....

**Comment by Xhofe** [comment]
unable to reproduce, log please

**Comment by zxcvbnmzsedr** [comment]
V3版本 webdav策略默认是302跳转，检查一下是不是这边设置有问题。改为本地代理就好了

**Comment by wonb168** [comment]
> V3版本 webdav策略默认是302跳转，检查一下是不是这边设置有问题。改为本地代理就好了

改为本地代理就好了？改哪里，咋改？
