### ISSUE TITLE
Docker版添加aria2提示x509:certificate signed by unknown authority

### ISSUE THREAD

**Issue by lm317379829** [alist-org/alist#1679]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-beta.2

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

Docker版，设置Aria2提示x509:certificate signed by unknown authority。
Aria2RPC采取HTTPS协议token验证
建议docker添加ca-certificates以便于解决证书验证的问题。

### Reproduction / 复现链接

无

**Comment by UnicornUnderMoon** [comment]
有相似问题。
ubuntu22.04，一键脚本安装的alist，版本3.29.1；域名使用certbot的证书，aria2采用https协议。
alist和aria2在同一台电脑上，在alist的设置-->其他项目下，设置aria2，用本机对外的https域名。反馈`Failed get aria2 version: Post "https://*****/jsonrpc": tls: failed to verify certificate: x509: certificate signed by unknown authority`
有怎么解决问题的思路吗？
