### ISSUE TITLE
正则匹配貌似有问题

### ISSUE THREAD

**Issue by airdreamn** [alist-org/alist#1680]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-beta.2

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

我想隐藏某个文件夹下所有目录，正则正确的是`.*`

`.$` `$` 也能隐藏文件夹下所有目录，按道理来说.$应该是匹配只有一个字符的字符串

### Reproduction / 复现链接

元信息，隐藏

**Comment by airdreamn** [comment]
怎么还吃了个字符。。
$和.$也能隐藏文件夹下所有目录

**Comment by airdreamn** [comment]
.$和
$
怎么还被吃了个字符。。

**Comment by Xhofe** [comment]
只有一个字符的字符串：`^.$`

请先学习如何写正则表达式
