### ISSUE TITLE
Unable to preview PDF file

### ISSUE THREAD

**Issue by wengtad** [alist-org/alist#1681]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

main

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

Unable to preview PDF file after upload.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/12437747/190352485-63024a74-9d55-463c-95a1-34005fd96a2c.png">

Steps to reproduce:
1. Upload a PDF file.
2. Click on the uploaded PDF file to preview.
3. Failed to fetch.

I'm think the issue is the incorrect URL.

The URL for the PDF.js preview be like:
`http://example.domain.local/p/folder/filename.pdf?sign=QRxxxxxxx-Xxxxxxxxx=:0`

But if using the "Copy link" function, the URL be like:
`https://example.domain.com/d/folder/filename.pdf`

If change 
`https://alist-org.github.io/pdf.js/web/viewer.html?file=http://example.domain.local/p/folder/filename.pdf?sign=QRxxxxxxx-Xxxxxxxxx=:0`

to
`https://alist-org.github.io/pdf.js/web/viewer.html?file=http://example.domain.local/d/folder/filename.pdf`
the file will preview successfully.

Is there any meaning for 'd', 'p' or 'sign' in the URL?

I guess most of the issue reported in GitHub that have closed automatically could be the same issue with me.

### Reproduction / 复现链接

Hope your demo link is back online so that I'm able to reproduce and provide the link.

**Comment by Kenny0521** [comment]
https://alist-org.github.io/pdf.js/web/viewer.html?file=$e_url

**Comment by Xhofe** [comment]
You need to set `Api url` to your real address so that the backend can provide the correct link of file.

**Comment by wengtad** [comment]
Thanks!

Manage to get it work.

For those who facing this issue, just add the address in `Api url` as mention by @Xhofe . 
Provided an image with the example address match with the issue about.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/12437747/190361760-ab078bc9-5f21-4536-9f51-4489a4e72b2e.png">

**Comment by werner-balonius** [comment]
> 

There is a problem that there is no api url now in AList

**Comment by zerofo** [comment]
The page at 'https://alist-org.github.io/pdf.js/web/viewer.html?file=httpxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxsignxxxxxxxxxxxxxxxxxxxxxxxxxx' was loaded over HTTPS, but requested an insecure resource 'http://192.168.xxxxxxxxx/p/xxxxxxxxxxxx.pdf?sign=xxxxxxxxxxxxxxxxxxxxxxxxxxxx'. This request has been blocked; the content must be served over HTTPS.
