### ISSUE TITLE
请求增加打开/关闭2FA的开关

### ISSUE THREAD

**Issue by yyn-777** [alist-org/alist#1692]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

上次打开2FA后感觉比较麻烦，请求增加打开/关闭2FA的开关。

**Comment by Xhofe** [comment]
```
cd path_of_alist
./alist cancel2fa
```

**Comment by Kenny0521** [comment]
那Windows的呢

> ```
> cd path_of_alist
> ./alist cancel2fa
> ```

**Comment by anwen-anyi** [comment]
> 

直接去你Windows的Alist目录下
alist.exe cancel2fa
