### ISSUE TITLE
v3.0.0-rc0 使用本地存储时，上传大文件时提示权限问题

### ISSUE THREAD

**Issue by taurusxin** [alist-org/alist#1693]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-rc0

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

上传时提示：The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.

### Reproduction / 复现链接

无

**Comment by wengtad** [comment]
上传小文件就没问题？你的文件多大？

**Comment by taurusxin** [comment]
> 上传小文件就没问题？你的文件多大？

似乎是大于2G就报错了，小文件就没问题

**Comment by foxxorcat** [comment]
浏览器的限制,因为前端上传不是采用分片上传而是整个读取上传
