### ISSUE TITLE
Feature request：建议使用react-h5-audio-player替换jinke-music-player

### ISSUE THREAD

**Issue by dpy013** [alist-org/alist#1694]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

## 前言
经过调查，当前[jinke-music-player](https://github.com/lijinke666/react-music-player)已停止维护，为了模块的可用和安全性，建议使用其他的music播放器替换[jinke-music-player](https://github.com/lijinke666/react-music-player)
## 更换原因
在就是[jinke-music-player](https://github.com/lijinke666/react-music-player)对[accessibility](https://en.wikipedia.org/wiki/Accessibility)并不是很友好，基于以上原因就有了以上的issue了。
## react-h5-audio-player 优势
* 可以在不同的浏览器上提供一致的UI/UX
& 支持i18n和a11y
& 支持键盘事件
最后也是最重要的一点就是[react-h5-audio-player](https://github.com/lhz516/react-h5-audio-player)是在维护的。
### 部署信息
操作系统： ubuntu22.04 lts
alist版本：3.0.0latest beta 使用docker创建
nginx：1.22.0
[audio demo](https://files.imydd.top/demo.mp3)
## 问题重现步骤
首先打开以上[地址](https://files.imydd.top/demo.mp3)
然后使用[屏幕阅读器](https://en.wikipedia.org/wiki/Screen_reader)浏览到音乐播放器的控制界面。
这时候可以发现[jinke-music-player](https://github.com/lijinke666/react-music-player)播放器的控件按钮是没有标题的，[屏幕阅读器](https://en.wikipedia.org/wiki/Screen_reader)会使用语音报告按钮、按钮的提示。
并且，使用shift+五位导航键也不能快进退，和增检音量。
## 获取屏幕阅读器为了更好的测试
[下载NVDA](https://www.nvaccess.org/download)
[NonVisual Desktop Access - Wikipedia](https://en.wikipedia.org/wiki/NonVisual_Desktop_Access)
## 写在最后
* 感谢作者可以写出这么好用的网盘管理程序

**Comment by Xhofe** [comment]
v2不再更新。

**Comment by dpy013** [comment]
> v2不再更新。
测试是基于
v3进行测试的

**Comment by dpy013** [comment]
以下是使用的pull代码
` docker run -d --restart=always -v /etc/alist:/opt/alist/data --network=host -p 5244:5244 --name="alist" xhofe/alist:latest`

**Comment by Xhofe** [comment]
v3未使用react框架。。。

**Comment by dpy013** [comment]
> v3未使用react框架。。。

感谢提醒。
