### ISSUE TITLE
游客浏览时文本文件使用文本编辑器查看时不应该有保存按钮

### ISSUE THREAD

**Issue by kilvn** [alist-org/alist#1697]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-rc.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

如题，游客浏览时文本文件，使用文本编辑器查看时不应该有保存按钮。
虽然提交按钮会返回403，没有权限，但是也应该判断当前用户是游客还是管理员来决定是否显示保存按钮。

一键升级至 v3.0.0-rc.0 后问题依旧。

### Reproduction / 复现链接

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/16423601/190850702-03d9c59e-a3d5-4db6-9edf-ec31e62bfe46.png">

### Logs / 日志

```shell
请看界面截图
```

**Comment by Kenny0521** [comment]
同求，加上最好把管理员首页的“WEBDAV 读取”改成“WEBDAV 读**写**”，然后如果关闭了读写权限，就隐藏保存按钮
