### ISSUE TITLE
webdav https连不上

### ISSUE THREAD

**Issue by nuoooo** [alist-org/alist#1700]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.0

### Driver used / 使用的存储驱动

aliyun

### Describe the bug / 问题描述

网页打开正常，用kodi挂载不行
日志：http: TLS handshake error from 10.0.0.143:8684: local error: tls: bad record MAC

### Reproduction / 复现链接

/

**Comment by Xhofe** [comment]
Did you enable https?

**Comment by nuoooo** [comment]
> Did you enable https?

config里已经打开了，web管理https是生效的

**Comment by Xhofe** [comment]
https://stackoverflow.com/questions/8154617/how-to-troubleshoot-ssl-bad-record-mac-exception

**Comment by Xhofe** [comment]
This may be due to a problem with kodi/network/ssl, `alist` has nothing to do

**Comment by ideascf** [comment]
可以尝试在 kodi 添加视频源的时候禁用 ssl 验证，在"远程路径"输入框输入的 path 最后添加 `|verifypeer=false`。
