### ISSUE TITLE
Docker部署V3版本,调用Aria2下载并上传到网盘出错

### ISSUE THREAD

**Issue by MIKU-N** [alist-org/alist#1706]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.0.0-rc.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

我使用Docker部署了V3版本的Alist，下面是我的部署配置：
```
docker run -d \
--restart=always \
-v /home/alist:/opt/alist/data \
-p 5244:5244 \
--name="alist" \
xhofe/alist:latest
```
然后，我同样使用Docker配置Aria2,此处使用了p3terx的镜像
```
docker run -d \
--name aria2-pro \
--restart unless-stopped \
-log-opt max-size=1m \
--network host \
-e IPV6_MODE=true \
-e PUID=$UID \
-e PGID=$GID \
-e RPC_SECRET=<Token> \
-e RPC_PORT=6800 \
-e LISTEN_PORT=6888 \
-v /home/aria2/:/config \
-v  /home/aria2/downloads:/downloads \
-v /home/alist:/opt/alist/ \
p3terx/aria2-pro
```
然后在Alist后台添加Aria2配置，此处使用本地回环,正常验证通过。
但是，在我添加任务后，Alist可以正常向Aria2添加任务，且Aria2可以正常的下载完成任务，唯独上传无法进行，且Alist无任何错误日志，仅在后台的已完成提示错误。
Aria2与Alist的日志如下
![image](https://user-images.githubusercontent.com/61493780/190858758-38c5e9d7-7719-44c0-9cb9-e112e5a52c76.png)
本地目录也可以找到Aria所下载完成的文件，位置于``/home/alist/data/temp/...``

现在的问题就是Alist无法正常进行上传，即使文件已经下载完成，且Alist日志并无报错信息，仅在后台提示错误，我也看不到究竟是什么原因的错误。在Alist目录内也没有看到log生成。

### Reproduction / 复现链接

NO URL

**Comment by Xhofe** [comment]
```docker
docker run -d \
--name aria2-pro \
--restart unless-stopped \
-log-opt max-size=1m \
--network host \
-e IPV6_MODE=true \
-e PUID=$UID \
-e PGID=$GID \
-e RPC_SECRET=<Token> \
-e RPC_PORT=6800 \
-e LISTEN_PORT=6888 \
-v /home/aria2/:/config \
-v  /home/aria2/downloads:/downloads \
-v /home/alist:/opt/alist/ \ <---与alist目录映射保持一致
p3terx/aria2-pro
```
另：日志位于可执行文件同级目录log/log.log.

**Comment by MIKU-N** [comment]
> 

我刚刚按你所说已修正aria2配置为
```
docker run -d \
--name aria2-pro \
--restart unless-stopped \
 --log-opt max-size=1m \
--network host \
-e IPV6_MODE=true \
-e PUID=$UID \
-e PGID=$GID \
-e RPC_SECRET=sakura54356854 \
-e RPC_PORT=6800 \
-e LISTEN_PORT=6888 \
-v /home/aria2/:/config \
-v  /home/aria2/downloads:/downloads \
-v /home/alist:/opt/alist/data \
p3terx/aria2-pro
```
错误仍在，没有任何变化，至于log，我知道它在同级目录，但看起来Alist确实没有生成它
![image](https://user-images.githubusercontent.com/61493780/190860622-2afb0b1a-ca94-4c25-9d76-7acd5bfb41a8.png)

**Comment by MIKU-N** [comment]
另外，此错误似乎导致我无法在Alist任务后台清除任务，当我点击删除按钮时，它提示”Task not found“，也就是说，看起来Alist找不到任务了。

**Comment by Xhofe** [comment]
是否下载磁力链接

**Comment by MIKU-N** [comment]
> 

是的，下载内容为磁力链接

**Comment by Xhofe** [comment]
duplicate with #1665
