### ISSUE TITLE
元信息设置bug

### ISSUE THREAD

**Issue by ying-zi** [alist-org/alist#1711]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.0

### Driver used / 使用的存储驱动

aliyun

### Describe the bug / 问题描述

元信息设置添加一个路径后，比如“/”根目录，设置隐藏某一目录无效。
元信息设置允许某一路径写入，比如/公共目录，如果不应用到子文件夹，则该目录无法写入。

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
描述不清

**Comment by ying-zi** [comment]
> 描述不清

比如我的根目路径“/”下有“私人”,“公共”,“上传”这三个目录。

我在元信息设置路径“/”的时候，我要隐藏“/私人”这个目录，但设置无法生效。

我在元信息设置路径“/上传”的时候，如果要允许游客在该目录上传文件，我不仅要勾先允许上传，还必须勾选“应用到子目录”，写入设置才能生效，如果不勾选应用到子目录，则游客在“/上传”目录仍无法上传文件。

**Comment by Xhofe** [comment]
最基础的版本都没说清楚。

**Comment by ying-zi** [comment]
> 最基础的版本都没说清楚。

v3.0.0-rc.0
v3.0.0-rc.1
都是如此。

版本在提交issue的时候就有注明3.0

**Comment by Xhofe** [comment]
3.0目前有五个版本。

**Comment by Xhofe** [comment]
rc1无法复现。

**Comment by ying-zi** [comment]
> rc1无法复现。

我在元信息设置里允许“/公共空间”的写入权限，但没有点击“应用到子目录”，就是说我只允许“/公共空间”这个目录游客能上传，但我并不想游客上传文件到“/公共空间/iPAs”目录，不知道这样说算不算解释清楚了。下图是我设置的界面
![2BC54495-499F-4BAF-83C3-A954CBA4E9C3](https://user-images.githubusercontent.com/36904833/190918458-c9e4f1e0-7224-4ae4-abbf-3ddc49334f54.png)

但目前的问题是如果不勾选“应用到子文件夹”的话，游客在“/公共空间”目录内，显示能上传文件，但上传完成后会提示permission denied，如下图
![Uploading BE1EAD69-09AC-4764-AB8B-60FDDCFB0B9F.jpeg…]()

**Comment by ying-zi** [comment]
> rc1无法复现。

bug复现地址

https://pan.ioser.ltd/公共空间

你处于该目录时，右下角菜单显示可以上传，但实际上当你上传完成后会提示你“ permission denied ”

**Comment by anwen-anyi** [comment]
> > 描述不清
> 
> 比如我的根目路径“/”下有“私人”,“公共”,“上传”这三个目录。
> 
> 我在元信息设置路径“/”的时候，我要隐藏“/私人”这个目录，但设置无法生效。
> 
> 我在元信息设置路径“/上传”的时候，如果要允许游客在该目录上传文件，我不仅要勾先允许上传，还必须勾选“应用到子目录”，写入设置才能生效，如果不勾选应用到子目录，则游客在“/上传”目录仍无法上传文件。



## **rc.1 修复了 如下问题....亲测**
>我在元信息设置路径“/”的时候，我要隐藏“/私人”这个目录，但设置无法生效。

**Comment by zhuziyi1989** [comment]
讲真我设置了密码，隐身窗口依然可以访问
