### ISSUE TITLE
ipa文件名包含中文时提示无效字符

### ISSUE THREAD

**Issue by ying-zi** [alist-org/alist#1712]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-rc.1

### Driver used / 使用的存储驱动

aliyundrive

### Describe the bug / 问题描述

当iPA文件名包含中文时，会提示“ System error: InvalidCharacterError: The string contains invalid characters. ”

若暂时无法解决，建议新增一个设置项来关闭ipa的在线安装功能。

### Reproduction / 复现链接

该目录下有分别以中英文命名的同一个文件的两份副本，以英文命名的一切正常，但以中文命名的则提示无效字符

https://pan.ioser.ltd/公共空间/iPAs

**Comment by Ssiswent** [comment]
> ### Please make sure of the following things
> * [ ]  I have read the [documentation](https://alist.nn.ci).
> * [ ]  I'm sure there are no duplicate issues or discussions.
> * [ ]  I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
> * [ ]  I'm sure I'm using the latest version
> 
> ### Alist Version / Alist 版本
> v3.0.0-rc.1
> 
> ### Driver used / 使用的存储驱动
> aliyundrive
> 
> ### Describe the bug / 问题描述
> 当iPA文件名包含中文时，会提示“ System error: InvalidCharacterError: The string contains invalid characters. ”
> 
> 若暂时无法解决，建议新增一个设置项来关闭ipa的在线安装功能。
> 
> ### Reproduction / 复现链接
> 该目录下有分别以中英文命名的同一个文件的两份副本，以英文命名的一切正常，但以中文命名的则提示无效字符
> 
> [https://pan.ioser.ltd/公共空间/iPAs](https://pan.ioser.ltd/%E5%85%AC%E5%85%B1%E7%A9%BA%E9%97%B4/iPAs)
> 
> ### Logs / 日志
> _No response_

老哥，你好，我也是alist挂载的阿里云盘，但是我的下载直链是这种格式，和你的不一样，请问是我哪里没设置对吗
`http://pan.happaa.com/p/%E6%89%98%E7%AE%A1/Ssiswent/Mac%E5%A4%87%E4%BB%BD/Ssiswent%E7%9A%84%E8%AF%8D%E5%BA%93.scel?sign=8SZbvTMQCblsZdB-CwNrrIT-5HjueeF3GHQ7pLflzxg=:0`
<img width="322" alt="image" src="https://user-images.githubusercontent.com/37449310/206721616-34a84a79-6332-41fc-a8ad-9f04536e3129.png">
