### ISSUE TITLE
苹果手机safari浏览器无法正常显示

### ISSUE THREAD

**Issue by TT-IPIP** [alist-org/alist#1716]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

天翼云

### Describe the bug / 问题描述

苹果手机safari浏览器无法正常显示

System error: TypeError: n.replaceAll is not a function. (In 'n.replaceAll("%","%25")', 'n.replaceAll' is undefined)

### Reproduction / 复现链接

http://localhost:5244/

### Logs / 日志

```shell
INFO[2022-09-19 03:53:54] Shutdown Server ...                          
INFO[2022-09-19 03:53:57] timeout of 3 seconds.                        
INFO[2022-09-19 03:53:57] Server exiting                               
INFO[2022-09-19 03:53:57] reading config file: data/config.json        
INFO[2022-09-19 03:53:57] load config from env with prefix:            
INFO[2022-09-19 03:53:57] init logrus...                               
INFO[2022-09-19 03:53:57] start server @ 0.0.0.0:5244                  
ERRO[2022-09-19 03:53:57] failed to init aria2 client: Post "http://localhost:6800/jsonrpc": dial tcp 127.0.0.1:6800: connect: connection refused
failed get aria2 version
github.com/alist-org/alist/v3/internal/aria2.InitAria2Client
	/app/internal/aria2/aria2.go:33
github.com/alist-org/alist/v3/internal/aria2.InitClient
	/app/internal/aria2/aria2.go:23
github.com/alist-org/alist/v3/internal/bootstrap.InitAria2.func1
	/app/internal/bootstrap/aria2.go:10
runtime.goexit
	/usr/lib/go/src/runtime/asm_arm64.s:1172
```

**Comment by Xhofe** [comment]
duplicate with #1662
