### ISSUE TITLE
登录时无法使用密码管理器插件填充OTP代码

### ISSUE THREAD

**Issue by Ruikoto** [alist-org/alist#1726]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-rc.0 （Docker-latest）

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

在登录后台管理时，账户名和密码可以使用密码管理器填充（我使用的1Password），但是OTP代码无法填充，其他支持OTP的网站都是可以使用密码管理器填充的，推测是文本框少写了一些属性导致的，这样每次都需要打开密码管理器把OTP复制出来粘贴进去，非常麻烦，希望可以优化一下。（同时可以考虑增加一个一段时间内不再需要使用OTP验证登录的选项）

![image](https://user-images.githubusercontent.com/30781137/191157099-64828ab6-f3fd-4046-94d5-c7a9a8b46fcd.png)
![image](https://user-images.githubusercontent.com/30781137/191157132-dbf2c552-a455-4a77-bb96-54c8397cde57.png)

### Reproduction / 复现链接

https://example.com/@login

**Comment by Xhofe** [comment]
什么属性 可以说清楚一点

**Comment by Ruikoto** [comment]
不好意思，我不太熟悉前端方面的机制，少了属性只是我基于问题现象的一种猜想 ，之前问题描述确实写得少了些，我补充下。

我观察了一下Google，Github和群晖DSM的OTP验证页面，推测只需要文本框有一个值为opt的任意属性就可以，比如`name="otp"`，我摘录几段过来

## Github
![image](https://user-images.githubusercontent.com/30781137/191269681-874d656f-6c15-45f2-9e4e-f1a49f303dbb.png)
```
<input type="text" name="otp" id="totp" value="" autocomplete="off" autofocus="autofocus" class="form-control input-block js-verification-code-input-auto-submit mb-2" inputmode="numeric" pattern="([0-9]{6})|([0-9a-fA-F]{5}-?[0-9a-fA-F]{5})" placeholder="XXXXXX">
```

## 群晖DSM
应该是`one-time-code`值触发了管理器的自动填充
![image](https://user-images.githubusercontent.com/30781137/191269555-34c98c0c-9678-464d-8377-8e272a0ad4fe.png)
```
<input syno-id="" type="text" placeholder="验证代码" name="one-time-code" autocomplete="one-time-code" tabindex="1" class="" data-com-onepassword-filled="light">
```

## Google
甚至用Google搜索框搜索一下otp都能触发自动填充机制，应该是因为搜索完后属性`value`的值为`otp`
![image](https://user-images.githubusercontent.com/30781137/191269825-6aa08932-dbc6-40e3-bee6-1ba839b16476.png)
```
<input class="gLFyf gsfi" jsaction="paste:puy29d; mouseenter:MJEKMe; mouseleave:iFHZnf;" maxlength="2048" name="q" type="text" aria-autocomplete="both" aria-haspopup="false" autocapitalize="off" autocomplete="off" autocorrect="off" role="combobox" spellcheck="false" value="otp" aria-label="搜索" data-ved="0ahUKEwjywLTVuqP6AhXNplYBHVsPDzUQ39UDCAs">
```

## AList
AList的则是被密码管理器判断为了一个普通文本框，因此没有触发自动填充
![image](https://user-images.githubusercontent.com/30781137/191270169-c2775976-1afb-4bcc-ab49-566368d3e8cc.png)
```
<input class="hope-input hope-c-kvTTWD hope-c-PJLV hope-c-kvTTWD-hYRNAb-variant-filled hope-c-kvTTWD-gfwxhr-size-md hope-c-PJLV-hbsPHc-cv hope-c-PJLV hope-c-PJLV-ibtHApG-css" type="text" placeholder="输入您的 OTP 代码">
```

**Comment by Xhofe** [comment]
你可以在https://github.com/alist-org/alist/actions/runs/3090913408 结束后尝试是否可以正常工作
