### ISSUE TITLE
夸克网盘目录显示不全。

### ISSUE THREAD

**Issue by xian54966** [alist-org/alist#1729]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V2.0 and V3.0

### Driver used / 使用的存储驱动

Docker

### Describe the bug / 问题描述

之前发现夸克网盘目录不更新，刚下载的电影不显示。现用V2版本，更换V3最新版也不行。今天使用浏览器开发调试工具发现，返回的目录列表JSON文件中文件夹更新时间是5天前，我并不清楚Alist的工作流程，由此简单的推断文件不更新的问题在这里，特提交Issue供查看。
![微信截图_20220920184502](https://user-images.githubusercontent.com/48814371/191239908-a72b71f5-4d84-4b00-93f8-5daedd1a76c9.png)

### Reproduction / 复现链接

![微信截图_20220920184502](https://user-images.githubusercontent.com/48814371/191240285-039fa66b-9043-410f-8c0b-23887185c486.png)

**Comment by Xhofe** [comment]
https://alist.nn.ci/faq/why.html#why-is-the-uploaded-file-not-displayed-deleted-file-still-modified-in-the-root-directory-does-not-take-effect-%E2%80%8B

**Comment by xian54966** [comment]
> https://alist.nn.ci/faq/why.html#why-is-the-uploaded-file-not-displayed-deleted-file-still-modified-in-the-root-directory-does-not-take-effect-%E2%80%8B

感谢您的回复。
在V2版本内没有设置缓存的有效时间的地方，但是在右上角有刷新的按钮。测试无效。还是刷不出今天下午4点离线下载成功的电影。重新启动V3版本Docker，重新添加Cookies，发现有设置缓存有效时间的选项，由原来30设置为1，经测试多次，同样没法显示之前下载的目录。
在Alist下，修改文件名称可以同步到网盘；在网页版夸克网盘下新建文件夹，刷新Alist目录，也可以正常显示。
但是为什么就是显示不出离线下载的目录呢。在网页端网盘里操作这个离线下载的电影文件夹，移动到任意文件夹，重命名，在Alist下都不能显示。太奇怪了。期待您的回复

**Comment by Xhofe** [comment]
无法复现 给个离线下载的链接

**Comment by xian54966** [comment]
> 无法复现 给个离线下载的链接

https://pan.quark.cn/s/b2bb56a5df17
或者您试下离线下载一个种子试试

**Comment by Xhofe** [comment]
空文件夹。。。

**Comment by xian54966** [comment]
> 空文件夹。。。
![image](https://user-images.githubusercontent.com/48814371/191251509-60fcff9d-c749-4914-88e9-46a628908d11.png)
原来是资源违规的原因。会导致Alist不显示吗？

**Comment by Xhofe** [comment]
是的 违规的文件也无法预览和下载。
