### ISSUE TITLE
希望能加入搜索功能

### ISSUE THREAD

**Issue by Winspain** [alist-org/alist#1740]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

搜索功能

### Suggested solution / 实现思路

引入es

**Comment by StudentWeis** [comment]
同求

**Comment by qq2246367036** [comment]
同求

**Comment by yzqiang666** [comment]
同求，原v2.6.4已有这功能。

**Comment by mnixry** [comment]
或许ElasticSearch在这个场景下有些重, 感觉[MeiliSearch](https://github.com/meilisearch/meilisearch-go)会是一个更好的选择
如果有go语言原生实现的全文搜索引擎, 似乎可以考虑[Bleve](https://blevesearch.com/), 但是引入它需要额外考虑对CJK的索引分析问题

**Comment by isChengshi** [comment]
搜索功能多好啊 求出！

**Comment by swRains** [comment]
同求

**Comment by power721** [comment]
vote

**Comment by steinvenic** [comment]
+1
