### ISSUE TITLE
3.0版本谷歌网盘如果设置了下载代理URL,就无法网页播放,下载也会报错

### ISSUE THREAD

**Issue by lsyyktv** [alist-org/alist#1743]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-rc.1

### Driver used / 使用的存储驱动

谷歌网盘

### Describe the bug / 问题描述

如果设置了下载代理URL,就无法网页播放,下载也会报错

![image](https://user-images.githubusercontent.com/39065858/191504690-0e53e71b-e8ad-4581-b567-02d3ea518b24.png)

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
Reproduction is required.
