### ISSUE TITLE
希望v3能挂载电脑共享smb

### ISSUE THREAD

**Issue by softwareygr** [alist-org/alist#1746]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望v3能挂载电脑共享smb

**Comment by temurlee** [comment]
支持，非常需要！

**Comment by Looong01** [comment]
这个指的是可以直接在Windows文件资源管理器里添加映射网络驱动器吗？

**Comment by temurlee** [comment]
> 这个指的是可以直接在Windows文件资源管理器里添加映射网络驱动器吗？

不。希望Alist可以增加局域网内SMB映射，来访问SMB里内容，特殊场景有需要，比如emby
