### ISSUE TITLE
希望能增加挂载网盘到本地

### ISSUE THREAD

**Issue by VisualSinger** [alist-org/alist#1747]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

通过alist把各种网盘挂载到本地

### Suggested solution / 实现思路

![image](https://user-images.githubusercontent.com/24698959/191653498-d8fd102d-27f3-4e18-bad5-7357557bdfe5.png)

### Additional context / 附件

![Uploading image.png…]()

**Comment by VisualSinger** [comment]
> ### 看
> 1. 50%[的能力希望挂载钉盘](https://github.com/alist-org/alist/issues/1627)[ #1627](https://github.com/alist-org/alist/issues/1627)[](https://github.com/alist-org/alist/issues/1627)

这个不是通过WebDav挂载，是通过CloudDrive直接挂载到映射的文件夹，通过运行alist直接把网盘挂载到alist服务器上

通过WebDav，需要单独运行一项 服务，这样可以更方便
在alist管理网盘，也可以通过alist服务器上相关的服务访问到网盘内容 

主要是想通过alist 挂载网盘后，通过服务器上其他的软件访问网盘内容，例如jellyfin等。

**Comment by luckyreny** [comment]
同需求

**Comment by HelloMusician** [comment]
大佬没时间的话，大家还是把文件放NAS再扫描吧

**Comment by Sdator** [comment]
+1

**Comment by xz950211** [comment]
同需求，希望可以和aliyundrive-fuse这个项目一样，可以供jellyfin快速读取。

**Comment by ocean521** [comment]
同需求,不知道有没有开发者跟进这个项目。

**Comment by jonntd** [comment]
可以用rclone 临时解决 win 用RaiDrive

ocean521 ***@***.***> 于2022年11月1日周二 21:49写道：

**Comment by bootli** [comment]
同需求

**Comment by goldsoft8888** [comment]
> 同需求，现在这种，我通过webdav-client 挂载到服务器上，再通过jellyfin添加的媒体库，扫描太卡太慢。 希望可以和 aliyundrive-fuse 这个项目一样，能供jellyfin快速读取。

太需要这个功能了，用RCLONE转发到alist太浪费资源了，CPU内存磁盘都吃不消

**Comment by IAALAI** [comment]
主要是这个挂载功能非常非常的复杂，参考实现了相同功能的rclone，它的代码量可是远比alist高！

**Comment by HelloMusician** [comment]
> 主要是这个挂载功能非常非常的复杂，参考实现了相同功能的rclone，它的代码量可是远比alist高！

对啊，定位不一样啊

**Comment by s949492225** [comment]
> 主要是这个挂载功能非常非常的复杂，参考实现了相同功能的rclone，它的代码量可是远比alist高！

那是否考虑直接把rclone集成到镜像内部，直接调用rclone,不直接去实现rclone.
提供一些简单的界面搞定rclone挂载，这样实现成本相对就比较低，也能满足大部分人的需求了，毕竟rclone和开机自启动很多人还是玩不明白的.

**Comment by IAALAI** [comment]
> > 主要是这个挂载功能非常非常的复杂，参考实现了相同功能的rclone，它的代码量可是远比alist高！
> 
> 那是否考虑直接把rclone集成到镜像内部，直接调用rclone,不直接去实现rclone. 提供一些简单的界面搞定rclone挂载，这样实现成本相对就比较低，也能满足大部分人的需求了，毕竟rclone和开机自启动很多人还是玩不明白的. 如果能实现那么alist这个就无敌了，云盘挂载无敌手，唯一选择了

我认为意义不大，而且你说rclone的界面，rclone已经提供了一个了webui了
