### ISSUE TITLE
使用 v3 版本进行反向代理到子目录时 /assets 路径无法访问

### ISSUE THREAD

**Issue by chuest** [alist-org/alist#1748]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-rc.1

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

使用 v3 版本进行反向代理到子目录时 /assets 路径仍然是在根目录请求。

### Reproduction / 复现链接

https://blog.chuest.com/cloud

![20220922162341](https://user-images.githubusercontent.com/61411821/191696726-e729e212-3a32-45fc-b3b1-a07842bfea3b.png)

### Logs / 日志

```shell
https://user-images.githubusercontent.com/61411821/191696726-e729e212-3a32-45fc-b3b1-a07842bfea3b.png
```

**Comment by Xhofe** [comment]
需要在配置文件中指明cdn路径，`/cloud`或者使用外部cdn，如`https://cdn1.tianli0.top/npm/alist-web@$version/dist/`

**Comment by Xhofe** [comment]
下个版本优化。

**Comment by chuest** [comment]
> 需要在配置文件中指明cdn路径，`/cloud`或者使用外部cdn，如`https://cdn1.tianli0.top/npm/alist-web@$version/dist/`

好的，更改之后可以正常使用了，感谢解答。

**Comment by chuest** [comment]
反代之后出现一个新的问题，在主页面如果要打开某个文件的话，若本来该文件路径为 `/index.md` 的话，则反代到子目录后，要打开他的链接应为`https://blog.chuest.com/cloud/index.md` ，但从主页面 `https://blog.chuest.com/cloud/` 进入后，点击该文件的话会显示这个文件的链接为 `https://blog.chuest.com/cloud/cloud/index.md` 。

**Comment by Xhofe** [comment]
fixed in [v3.0.1](https://github.com/alist-org/alist/releases/tag/v3.0.1)

**Comment by wimotek** [comment]
同样问题.  反代到子目录 页面显示不出来

**Comment by Mai0313** [comment]
> 同样问题. 反代到子目录 页面显示不出来

湊巧看到你也有相同問題，我剛好瞎改找到方法解決 跟你分享一下
假設你設定的反向代理是 `location /alist/`
那你應該要這樣設置，將 `/alist` 加到 `site_url` 才對
![image](https://github.com/alist-org/alist/assets/21039366/efcbab71-6645-4a43-bf34-cb87a532cc21)
而不是開發者說的cdn，無意冒犯 還請開發者理解下
