### ISSUE TITLE
3.0.1 的新功能 阿里共享盘无法播放，显示没有权限

### ISSUE THREAD

**Issue by paowan2** [alist-org/alist#1753]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

ailyundriveshare

### Describe the bug / 问题描述

新增的时候使用自己的token，能够正常浏览目录，但是播放的时候会出现

failed get link: No Permission to access resource File

### Reproduction / 复现链接

https://www.aliyundrive.com/s/TvsfrqkTBYh/folder/628339f999df231409164a809c98d874fdcfb540

**Comment by foxxorcat** [comment]
意料之中，阿里云盘做了限制，大文件必须保存到自己网盘里看，小文件没问题。

**Comment by wowo14735** [comment]
> 意料之中，阿里云盘做了限制，大文件必须保存到自己网盘里看，小文件没问题。
多大算大？多小算小？
