### ISSUE TITLE
新版的 阿里云token保存后又为什么会变？

### ISSUE THREAD

**Issue by paowan2** [alist-org/alist#1754]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

ailyundrive

### Describe the bug / 问题描述

比如我填入A，保存，然后再编辑会显示B，但是自己的阿里云盘又能正常浏览和播放，这是一种安全机制还是bug？

### Reproduction / 复现链接

没有

**Comment by Xhofe** [comment]
**refresh** token
