### ISSUE TITLE
使用 v3.0.1 版本进行反向代理到子目录后所有页面均空白

### ISSUE THREAD

**Issue by o0HalfLife0o** [alist-org/alist#1755]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

阿里云

### Describe the bug / 问题描述

反向代理到子目录/pan后页面显示空白

### Reproduction / 复现链接

https://gcp-argo.ming92.tk/pan

### Logs / 日志

```shell
[GIN] 2022/09/23 - 00:19:58 | 200 |      75.283µs |       127.0.0.1 | GET      "/pan"
[GIN] 2022/09/23 - 00:19:59 | 200 |      71.113µs |       127.0.0.1 | GET      "/pan/assets/index.d90e2c50.js"
[GIN] 2022/09/23 - 00:19:59 | 200 |      51.706µs |       127.0.0.1 | GET      "/pan/assets/index.659f4289.css"
```
```

**Comment by qq2246367036** [comment]
![image](https://user-images.githubusercontent.com/29965958/191806830-cf474e2a-4858-4fdb-95d5-d909141425cb.png)
http://tva1.sinaimg.cn/large/005In4Hggy1h6fvcebtqyj30qz0mwk2r.jpg

我这边可以看
