### ISSUE TITLE
中文alist页面浏览器提示从英语翻译到中文

### ISSUE THREAD

**Issue by mengguyi** [alist-org/alist#1761]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

一个无伤大雅的小bug。我注意到当我打开alist页面时浏览器会弹出翻译页面的选项，我的alist页面设置为中文正常不应该出现翻译才对
![无标题](https://user-images.githubusercontent.com/73788063/191880350-dbfff823-4f8c-4fc5-950d-e212d908efe3.png)
这个是因为`<html lang="en">`导致的，我查看cn.bing.com它的html lang是zh
![C9M9RC Q@ OQV)J`@` ~`~H](https://user-images.githubusercontent.com/73788063/191880499-79203b0d-f2a6-41f8-be11-3ef2cd278d58.png)

而alist的html lang是en

![%AV6~NRZC6QSTKN{FVK2)VI](https://user-images.githubusercontent.com/73788063/191881428-1fee14c4-be68-418a-af35-6576f3802468.png)

### Reproduction / 复现链接

https://driver.mengguyi.com/

### Logs / 日志

![无标题](https://user-images.githubusercontent.com/73788063/191880350-dbfff823-4f8c-4fc5-950d-e212d908efe3.png)

**Comment by mengguyi** [comment]
浏览器是ms edge

**Comment by dpy013** [comment]
> 浏览器是ms edge

Microsoft Edge
版本 105.0.1343.50 (正式版本) (64 位)的路过
好像是html的lang不对，默认是en的，实际上应该是zh_CN

**Comment by dpy013** [comment]
另外我clone了alist-web的仓库，发现/Source\Repos/alist-web/src/lang 目录里只有一个en的语言目录，大佬是不是可以合并一下[New Crowdin updates](https://github.com/alist-org/alist-web/pull/2)这样可能就可以解决问题了。
