### ISSUE TITLE
V3.0.1编译前端报错

### ISSUE THREAD

**Issue by ticifer** [alist-org/alist#1763]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

环境信息：
nodejs:v16.15.0 gcc:9.3.1 git:1.8.3.1 go: 1.19.1 pnpm:7.12.1 yarn: 8.5.5 npm:1.22.19
编译前端报错如下：
vite v3.1.3 building for production...
✓ 5 modules transformed.
[vite:load-fallback] Could not load /root/alist/alist-web/solid-router/src (imported by src/main.tsx): ENOENT: no such file or directory, open '/root/alist/alist-web/solid-router/src'
error during build:
Error: Could not load /root/alist/alist-web/solid-router/src (imported by src/main.tsx): ENOENT: no such file or directory, open '/root/alist/alist-web/solid-router/src'
把solid-router拉下来放进去也是报错这样，npm、yarn、pnpm都是这样报错,请指导；谢谢

### Reproduction / 复现链接

git clone https://github.com/alist-org/alist
git clone https://github.com/Xhofe/alist-web

**Comment by Linya-IronMan** [comment]
> 

兄弟，怎么解决的？

**Comment by mengguyi** [comment]
> > 
> 
> 兄弟，怎么解决的？版本问题么？

你看看现在的release是哪个版本

**Comment by Linya-IronMan** [comment]
> > > 
> > 
> > 
> > 兄弟，怎么解决的？版本问题么？
> 
> 你看看现在的release是哪个版本

3.17.0 啊，这个问题在说 3.10 之后存在的某个问题。怎么了？

我切了alist-web 的好几个版本，都没办法 build
