### ISSUE TITLE
谷歌网盘无法上传文件

### ISSUE THREAD

**Issue by Smart-zsw** [alist-org/alist#1765]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1-aarch64

### Driver used / 使用的存储驱动

谷歌云盘

### Describe the bug / 问题描述

目前只可以上传几十M的文件
上传大于1G的文件都会产生报错
大于5G的一个文件会直接不会上载而报错

### Reproduction / 复现链接

无，内网使用

### Logs / 日志

```shell
错误：http: invalid Read on closed Body
错误：The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.
```

**Comment by Xhofe** [comment]
日志过短。
