### ISSUE TITLE
请求添加缓存位置设置选项，目前位置在opt/alist/data/temp

### ISSUE THREAD

**Issue by yyysuo** [alist-org/alist#1767]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

从web端在不同网盘间转移文件，临时文件目录在opt/alist/data/temp，如果是安装在ssd上的openwrt，一般是小容量ssd甚至是u盘，几十T文件的转移很可能直接把ssd或者u盘寿命耗尽。

### Suggested solution / 实现思路

希望默认把临时文件目录设置到主机的/tmp/alist位置，文件上传有可能需要单个文件下载完成后再上传，意味着文件不能分割，那么当下载的文件存在超过/tmp容量时，应该提醒或者自动忽略此大文件。

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/configuration.html#database
