### ISSUE TITLE
alist_v3latest:后台配置了ba号后，前台页面底部无法显示

### ISSUE THREAD

**Issue by dpy013** [alist-org/alist#1768]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3dev

### Driver used / 使用的存储驱动

123pan_driver

## 前提
已在后台配置了ba号

## 重现步骤
首先打开[测试链接](https://files.imydd.top)
然后鼠标啦到底，假如是正常的话，是可以看到后台配置的ba号的，
后面还测试了v2的alist，v2的alist可正常显示后台配置的ba号。

### Logs / 日志

```shell
none
```

**Comment by Xhofe** [comment]
已删除备案设置。自行在customize body添加。
