### ISSUE TITLE
potplayer播放视频提示“无法找到该文件”

### ISSUE THREAD

**Issue by elunlun** [alist-org/alist#1769]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

应该是生成的potplayer的链接不对，用vlc的链接把vlc改成potplayer就能用potplayer播放

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
更新。

**Comment by StellarisW** [comment]
对的，我也遇到了这个问题
[前端代码](https://github.com/alist-org/alist-web/blob/main/src/pages/home/previews/video.tsx#L17)
正常的url是这样的（v2版本）
![image](https://user-images.githubusercontent.com/46246823/192088964-00238972-971a-4bd2-9d4f-8ab934a3df07.png)
现在v3版本的url是这样的
![image](https://user-images.githubusercontent.com/46246823/192089007-880e12b1-33ee-4051-8440-4b70ee9692d3.png)

**Comment by tyhunter** [comment]
Docker更新到3.0.2版本，这个问题依然存在

**Comment by StellarisW** [comment]
@tyhunter @elunlun 
问题好像解决了，
Potplayer 升级到最新版本 1.7.21801就可以了，
最新版本会把 encoded url 解码

**Comment by Diskland** [comment]
> @tyhunter @elunlun 问题好像解决了， Potplayer 升级到最新版本 1.7.21801就可以了， 最新版本会把 encoded url 解码

升级到最新版1.7.21859了  依旧没用。

**Comment by Diskland** [comment]
> @tyhunter @elunlun 问题好像解决了， Potplayer 升级到最新版本 1.7.21801就可以了， 最新版本会把 encoded url 解码

但是VLC的url是正确的  把抬头vlc换成potplayer就能播放了！ 应该还是有问题。

**Comment by commandoccz** [comment]
新版本尚未解决该问题

**Comment by auflute** [comment]
最近更新到potpalyer到1.7.21861，出现这个问题，之前是能正常调用的

**Comment by commandoccz** [comment]
作者已经更新了前端代码，问题已经解决，可以按教程自行编译，或等待作者更新 [#2782](https://github.com/alist-org/alist/issues/2782) as completed via [alist-org/alist-web@d95c5d5](https://github.com/alist-org/alist-web/commit/d95c5d526bb43496e1664eca74c13df4489486ce).
