### ISSUE TITLE
希望给管理后台中的任务队列增加手动暂停按钮

### ISSUE THREAD

**Issue by mengguyi** [alist-org/alist#1771]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

给alist管理后台中任务队列（Aria2，上传，复制）增加手动暂停按钮和控制同时进行的队列数量

很多人的vps硬盘不是很大，只能一次进行一个到两个任务，在使用alist+rclone从百度网盘等网盘向OneDrive同步文件

遇到大文件（80G+）传输时一个任务完成了，但是rclone需要时间向OneDrive上传。此时硬盘已经没有空间进行下一个任务了

这时alist还会进行下一个下载任务，就会把vps的硬盘爆满，影响vps使用

所以希望增加一个手动控制任务启动/暂停的按钮和控制同时进行的队列数量的选项

而且vps上一般不会只运行alist，如果alist把磁盘占满，大概率会影响其他服务的运行

### Suggested solution / 实现思路

参考百度网盘下载设置里的上传/下载并行任务数
![U%JMUG8M@OINQ)2FJUL@YR3](https://user-images.githubusercontent.com/73788063/191916876-ba6f2b7c-61c3-41a2-b787-2d2421f36ceb.png)
![LXZ }P273EQ}BRW$HO$C}L](https://user-images.githubusercontent.com/73788063/191916990-cb5c2287-38c1-4497-8dfd-374213908c8d.png)

**Comment by xxssww0258** [comment]
是的，我也有同样问题，我有一个2mb云服务器，我在其中复制1t文件到另一个云盘，到现在2个星期都没复制完，导致这台服务器我都没法用
