### ISSUE TITLE
修复后时间排序依然错序

### ISSUE THREAD

**Issue by Lumilk233** [alist-org/alist#1776]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

b6d9018

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

最新Dev版本没有修复该问题
![图片](https://user-images.githubusercontent.com/110418934/191894950-af7b59b7-ba47-48bd-b09b-2469acf4ba74.png)
![图片](https://user-images.githubusercontent.com/110418934/191895076-c9deeadb-20db-4606-9267-249421cc5453.png)

### Reproduction / 复现链接

略

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/191960567-96c7ec27-ce4b-4783-99a1-1b6b6189cfa3.png)
unable to reproduce.

**Comment by Lumilk233** [comment]
> ![image](https://user-images.githubusercontent.com/36558727/191960567-96c7ec27-ce4b-4783-99a1-1b6b6189cfa3.png) unable to reproduce.

重新搭建alist后排序回复正常

**Comment by Lumilk233** [comment]
![图片](https://user-images.githubusercontent.com/110418934/191994739-3ac6934c-2ed7-40a7-bba6-eab199a95be4.png)
![图片](https://user-images.githubusercontent.com/110418934/191994746-1d279b6d-6301-48ff-a37d-cc2422020460.png)
![图片](https://user-images.githubusercontent.com/110418934/191994860-87e19581-a371-4567-acf3-644a55f75be1.png)
![图片](https://user-images.githubusercontent.com/110418934/191994885-d7f49c08-13e5-4757-8d03-7ffd0ab8523f.png)

**Comment by Lumilk233** [comment]
储存设置设置按照修改时间排序后再次调整时间排序依然错序

**Comment by Xhofe** [comment]
没看出来你想表达什么 你按名称排序 时间肯定是错序

**Comment by Lumilk233** [comment]
> 没看出来你想表达什么 你按名称排序 时间肯定是错序

![gif](https://autopatchcn.mihomo.tk/Img/2022/09/23/2db4ccabc020826b40f4ab9285852946.gif)

**Comment by Lumilk233** [comment]
或许文件更多给您展示的应该更清楚
![gif](https://autopatchcn.mihomo.tk/Img/2022/09/23/2d7f75aa882ecbbf1c70edf1e8d329aa.gif)

**Comment by Xhofe** [comment]
到底是什么问题 说清楚 不要发动图给复现链接 。

**Comment by Lumilk233** [comment]
> 到底是什么问题 说清楚 不要发动图给复现链接 。

复现链接: https://pan.lumine233.ml/main/microG
问题：修改时间按钮无作用
复现过程：点击修改时间按键导致顺序错乱
