### ISSUE TITLE
请问网页视频倍速播放可以具体细化吗？

### ISSUE THREAD

**Issue by China-Huanghe** [alist-org/alist#1781]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

看一些教学视频的时候，1.5倍速太慢，2.0倍速又听不清。安装了一个支持HTML5网页视频的油猴脚本，对这个也不起作用。

### Suggested solution / 实现思路

所采用的artplayer播放器是否支持其他倍速？网页播放时是否是HTML5格式呢？

**Comment by Xhofe** [comment]
不支持 如有更高的要求使用播放器播放。
