### ISSUE TITLE
无法发送到Aria2进行下载

### ISSUE THREAD

**Issue by VectorZhao** [alist-org/alist#1782]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

pikpak

### Describe the bug / 问题描述

后台已配置好Aria2并且可以识别到版本，前台从pikpak推送下载到Aria2报错！

**Comment by VectorZhao** [comment]
![Screenshot_2022-09-24-09-01-06-98_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/16644993/192073887-c361c10b-7d7a-44ec-826c-6249260ee7aa.jpg)
![Screenshot_2022-09-24-08-59-24-30_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/16644993/192073891-a51a68c1-acd1-43ff-a78a-80507c56e34f.jpg)

**Comment by VectorZhao** [comment]
![IMG_20220924_091601](https://user-images.githubusercontent.com/16644993/192074016-3016626c-0991-43b7-86aa-d40d3785f0ff.jpg)
![Screenshot_2022-09-24-08-59-24-30_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/16644993/192074023-57f411e1-999b-420c-9e89-83a0340fe4d1.jpg)

**Comment by Xhofe** [comment]
后台配置的是用于离线下载的aria2，前台发送到aria2下载需要在本地设置中配置。

**Comment by VectorZhao** [comment]
> 后台配置的是用于离线下载的aria2，前台发送到aria2下载需要在本地设置中配置。
![Snipaste_2022-09-24_11-01-52](https://user-images.githubusercontent.com/16644993/192077350-cde1bbaf-eb13-4176-9358-2ca8a97df0cb.png)

同样的错误

**Comment by Xhofe** [comment]
不能在https页面中发送http请求。

**Comment by VectorZhao** [comment]
> 不能在https页面中发送http请求。

好的，我去试试https

**Comment by VectorZhao** [comment]
> 不能在https页面中发送http请求。

搞定了，感谢感谢👻

**Comment by huomqh** [comment]
> > 不能在https页面中发送http请求。
> 
> 搞定了，感谢感谢👻
怎么搞定的，求指导
