### ISSUE TITLE
开启Web 代理后出现PDF/Office文件预览不可使用的问题

### ISSUE THREAD

**Issue by Edge-coordinates** [alist-org/alist#1789]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/68896486/191986366-0d80a11e-4002-42c3-a3e9-4eba85ee11d3.png)
这是配置，就是普通的打开了Web代理，但是这样显然是无法使用的，首先这样的情况下，
![image](https://user-images.githubusercontent.com/68896486/191986685-7205d69b-7f88-425b-adde-5c4bb6c60988.png)
这是Office的表现，
![image](https://user-images.githubusercontent.com/68896486/191987056-2def08a8-2ad2-4835-9506-2ceda9a35e98.png)
着是PDF的表现，这个我倒是知道是因为使用了Http协议的问题，但是我任然不知道怎么解决它，请问有什么方案吗？谢谢！

**注：** 我尝试了在`下载代理URL`中填写`https://alist.xf-yun.cn`,然而获得的只是这样的报错：
![image](https://user-images.githubusercontent.com/68896486/191987705-481b16d3-46b8-4915-a3fa-204630b9f853.png)

### Reproduction / 复现链接
[PDF](https://alist.xf-yun.cn/Hello_world/Node%E4%B8%8EExpress%E5%BC%80%E5%8F%91_Ethan%20Brown_%20%E5%90%B4%E6%B5%B7%E6%98%9F_%E8%8B%8F%E6%96%87%E8%AF%91_%E4%BA%BA%E6%B0%91%E9%82%AE%E7%94%B5%E5%87%BA%E7%89%88%E7%A4%BE.pdf)
[PPT](https://alist.xf-yun.cn/Hello_world/Office/PPT%E6%A8%A1%E6%9D%BF/ppt%E6%A8%A1%E6%9D%BF2000%E4%B8%AA/[001]%E4%B8%BB%E9%A2%98%E7%B2%BE%E9%80%89PPT%E6%A8%A1%E6%9D%BF[%20%20%20%20%20].ppt)
同一个网盘，没有开代理的同一个文件[PPT](https://alist.ics.ink/Edge01/Office/PPT%E6%A8%A1%E6%9D%BF/ppt%E6%A8%A1%E6%9D%BF2000%E4%B8%AA/[001]%E4%B8%BB%E9%A2%98%E7%B2%BE%E9%80%89PPT%E6%A8%A1%E6%9D%BF[%20%20%20%20%20].ppt),它是可用的。

**Comment by Xhofe** [comment]
首先下载代理URL不懂不要乱填，其次提供复现链接。

**Comment by Xhofe** [comment]
与#1802 一样的问题。
