### ISSUE TITLE
预览GB2312编码的纯文本会乱码

### ISSUE THREAD

**Issue by kbj** [alist-org/alist#1791]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

在预览Windows系统自带的记事本创建的txt纯文本时会乱码无法显示，经过测试发现是中文Windows系统默认使用的GB2312(GBK)编码，如果手动通过编辑器转成UTF8后才正常显示。

所以，想请问下作者是否有计划兼容下GB2312(GBK)编码的纯文本预览？我测试了下v2版本的alist预览同一个GB2312编码的纯文本没出现乱码情况

谢谢

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
无计划。
