### ISSUE TITLE
使用frp进行https反向代理，下载协议为http

### ISSUE THREAD

**Issue by huangzulin** [alist-org/alist#1797]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

在预览下载页面，点击下载为http协议，复制链接则正常，文件列表右键下载也正常
![image](https://user-images.githubusercontent.com/9855749/192124079-0f2a22ad-3e81-4d93-861e-0f3a69741a56.png)

### Reproduction / 复现链接

https://alist.z00z.cf/public.txt

**Comment by Xhofe** [comment]
填写此字段 https://alist.nn.ci/zh/config/site.html#api%E5%9C%B0%E5%9D%80

**Comment by huangzulin** [comment]
谢谢，已正常使用
