### ISSUE TITLE
开启Web代理播放视频时浏览器显示 不安全

### ISSUE THREAD

**Issue by skyrim663** [alist-org/alist#1802]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

开启Web代理播放视频时浏览器显示 不安全

The page at 'url' was loaded over HTTPS, but requested an insecure video 'url'. This content should also be served over HTTPS.

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/site.html#api-url
设置此字段。

**Comment by skyrim663** [comment]
感谢 已解决
