### ISSUE TITLE
[3.x] 在部分 2021 年之前的浏览器中，会报错 n.replaceAll() is not a function

### ISSUE THREAD

**Issue by YidaozhanYa** [alist-org/alist#1803]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.1

### Driver used / 使用的存储驱动

任意

### Describe the bug / 问题描述

2021 年之前的 Chromium 内核浏览器在 AList v3 首页就会报错，无法浏览任何内容

### Reproduction / 复现链接

任何使用 AList v3 的站点

**Comment by YidaozhanYa** [comment]
建议在浏览器不支持 String.prototype.replaceAll() 时，让程序用 JS 平替函数替换之。

**Comment by Xhofe** [comment]
b71ecc8e89258e0fc83913606cc019facade3a2b
