### ISSUE TITLE
alist网盘用户在iOS16新系统里无法安装ipa 其他系统都没问题

### ISSUE THREAD

**Issue by Kieratseng** [alist-org/alist#1806]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.0

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

其他iOS系统都可以直接安装ipa，网盘会自动分发下载安装。但是iOS16系统访问alist网盘里面的苹果软件下载安装会显示绿色图标。网盘无法正常分发，和蓝奏云一样 目前都存在这个问题。希望作者能够针对苹果新系统iOS16分发更新一下规则适配iOS16下载ipa。

### Reproduction / 复现链接

https://43.143.76.180/苹果软件/BM.ipa

### Logs / 日志

```shell
直接显示绿色图标。
```

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/guide/advanced/ipa.html
