### ISSUE TITLE
markdown 文件无法渲染字体颜色

### ISSUE THREAD

**Issue by StudenGit** [alist-org/alist#1807]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

markdown 文件无法渲染字体颜色
![image](https://user-images.githubusercontent.com/33886886/192152488-ceba59ef-db26-425d-be52-0e1edd1b7dc8.png)
在vscode中正常显示为
![image](https://user-images.githubusercontent.com/33886886/192152531-c57b6638-158c-4db4-a113-3a03a3271096.png)
但是alist渲染为
![image](https://user-images.githubusercontent.com/33886886/192152601-d42a8320-c683-444b-acb5-a28bfa28927e.png)
求解决办法

**Comment by Xhofe** [comment]
```html
<span style="color:blue;">blue</span>
```
