### ISSUE TITLE
希望可以恢复decode直链复制

### ISSUE THREAD

**Issue by DreamLumine** [alist-org/alist#1810]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

未decode直链太长不利于查看 遇到中文可能乱码 希望可以重新添加decode直链复制

### Suggested solution / 实现思路

该功能在2.x版本已经实现 希望可以移植到3.0上

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/192208472-00384f3a-ac0b-48c3-8da3-1ffe9735bf0a.png)
