### ISSUE TITLE
temp文件夹root权限导致群晖Aria2下载失败

### ISSUE THREAD

**Issue by loryncien** [alist-org/alist#1813]
### Please make sure of the following things

- [X] #1815
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Alist 创建的temp文件夹为root权限，映射到宿主机群晖NAS，Aria2挂载该目录，因Aria2没有root权限，Alist离线下载错误。
要手动修改temp文件夹权限为当前用户才能正确离线下载。

Alist v3.0.2     
p3terx/aria2-pro:latest   PUID=1026  PGID=100 （非root权限）

**Comment by Xhofe** [comment]
只能手动修改，谁能预知到aria2是什么权限。

**Comment by loryncien** [comment]
> 只能手动修改，谁能预知到aria2是什么权限。

确实，不知能否权限设置everybody或puid pgid，不方便实现的话，只能手动修改了。

**Comment by SourceOnce** [comment]
PUID  PGID我全设置的0，一般都是root吧
