### ISSUE TITLE
建议添加一个分组

### ISSUE THREAD

**Issue by vsuyvkpzica46088** [alist-org/alist#1816]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

添加了大量阿里云分享连接以后，需要对相同类型进行分组。

**Comment by Xhofe** [comment]
挂载路径：
- /阿里云盘分享/分享1
- /阿里云盘分享/分享2
- /阿里云盘分享/分享3

**Comment by nuoooo** [comment]
> 使用虚拟路径方式..你随便折腾..开发者已经给出案例
> 
> 甚至你还可以这样
> - /阿里云盘分享/电视剧/二十不惑
> -  /阿里云盘分享/电视剧/昆仑神宫
> - /阿里云盘分享/电影/大鱼海棠
> - /阿里云盘分享/电影/疯狂的石头
> - /阿里云盘分享/动漫/斗罗大陆
> - /阿里云盘分享/动漫/斗破苍穹
> - /阿里云盘分享/美剧/越狱
> - /阿里云盘分享/美剧/越狱2
> 
> 

这个指的是虚拟存储那个吗，那个老报错不知道咋用
