### ISSUE TITLE
V3 版本iOS 16 安装 IPA 的优化建议方案

### ISSUE THREAD

**Issue by bigsen** [alist-org/alist#1824]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前V3 版本iOS 16 安装 IPA 需要把文件名修改为：原文件名@bundle-identifier.ipa 
然儿非常不方便。有个建议：

其他类似蒲公英等分发网站应该是已经做到了， 可以不解压IPA然后读取ipa里面的info.plist里面的包名的。

### Suggested solution / 实现思路

可以参考下这个技术方案https://blog.csdn.net/lqlqlq007/article/details/121242545。

建议在点安装的时候，先读取ipa里面的plist文件，然后动态生成plist文件包含正确的bundleid。不需要人工取命名带上包名，这样会非常方便。

**Comment by xiaowang7212** [comment]
两种不同的类型，没必要考虑了。
