### ISSUE TITLE
设置 site_url 之后 base_path 同时指向了 site_url 导致访问不正常

### ISSUE THREAD

**Issue by EndCredits** [alist-org/alist#1830]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.2

### Driver used / 使用的存储驱动

local

### 注: 由于文件服务器已切换至 alist v3.0.1 ，故下文中原本的 ```问题链接``` 与 ```正常访问链接``` 互换

我正在试图搭建一个文件下载站，本地运行 alist 守护进程并使用 ```caddy``` 进行反向代理，由于原本的 ```api_url``` 字段已被弃用，所以我按照文档设定了 ```site_url``` 为 https://mirrors.lewa-revived.work 

在设置之后执行 ```sudo systemctl restart alist``` 重启了 alist，发现网页 ( https://mirrors.lewa-revived.work )  无法正常访问，显示为空

![image](https://user-images.githubusercontent.com/64133324/192416892-f6c28dbd-4900-4566-91ed-da0a18a63056.png)

排查页面源代码之后发现 ```base_path``` 字段同时也指向了 ```/mirrors.lewa-revived.work```

这时访问 https://mirrors.lewa-revived.work/mirrors.lewa-revived.work , 发现恢复正常

![image](https://user-images.githubusercontent.com/64133324/192417288-c6ff70d1-e9e2-4bf4-887f-9c159103f01b.png)

建议: 重新加入 ```base_path``` 字段避免类似的情况发生，同时方便子目录反向代理的设置

临时解决方案: 回退至版本 v3.0.1 或 revert commit https://github.com/alist-org/alist/commit/7c32af4649909dd7ebcafe2b58ed44c311223759 并重新编译

### Reproduction / 复现链接

问题链接: https://mirrors.lewa-revived.work

正常访问链接: https://mirrors.lewa-revived.work/mirrors.lewa-revived.work/

### Logs / 日志

```shell
见上方
```

**Comment by crazy0x70** [comment]
谢谢，我也遇到了一样的问题，希望作者尽快出一个修复版本吧

**Comment by crazy0x70** [comment]
> 楼主好，请问您是怎么​​弄域名挂载的呢，也想弄一个，谢谢啦

反代端口就好了...
