### ISSUE TITLE
建议本机存储的符号链接文件大小显示为目标文件大小

### ISSUE THREAD

**Issue by wolonggl** [alist-org/alist#1832]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

系统： Linux Ubuntu 22.04
本地的视频文件因为PT保种需要，建立软链接方式到一个专门的/MediaLibrary 目录下，用于 emby/jellyfin媒体服务器用；
在Alist添加本机存储，根文件夹路径为/MediaLibrary，挂载到/NAS存储目录下，挂载后，可以正常浏览该目录下的图片文件，但是所有的视频文件(软连接)都显示为100左右字节大小的文件，而不是实际的视频文件大小；

![QQ图片20220928143623](https://user-images.githubusercontent.com/17318615/192705740-b56fb4ac-bc33-484d-a190-05125d6d06c8.png)

user111@nas:/MediaLibrary/华语电影/颐和园$ ls -ls
total 452
136 -rw-r--r-- 1 emby   emby   137291  9月 10 02:30 fanart1.jpg
 68 -rw-rw-r-- 1 user111 user111  69058  9月  9 21:54 颐和园.Summer.Palace.2006.HD.1080P.x264-fanart.jpg
  4 lrwxrwxrwx 1 user111 user111     79  9月  9 10:44 **_颐和园.Summer.Palace.2006.HD.1080P.x264.mkv -> /mnt/zh华语电影/华语电影/颐和园.Summer.Palace.2006.HD.1080P.x264.mkv_**
  8 -rw-rw-r-- 1 user111 user111   7430  9月 10 07:17 颐和园.Summer.Palace.2006.HD.1080P.x264.nfo
236 -rw-rw-r-- 1 user111 user111 238130  9月  9 21:54 颐和园.Summer.Palace.2006.HD.1080P.x264-poster.jpg

### Reproduction / 复现链接

无

**Comment by nidbCN** [comment]
我也有这个需求
