### ISSUE TITLE
v3版本增加添加其他Alist支持

### ISSUE THREAD

**Issue by lixplus0** [alist-org/alist#1833]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

v2版本（2.6.4）是支持添加另一个alist地址的，不过v3似乎找不到添加其他alist的选项，希望可以添加回来。

**Comment by DreamOfIce** [comment]
也许可以考虑通过WebDAV挂载别的alist？

**Comment by vpei** [comment]
> 也许可以考虑通过WebDAV挂载别的alist？
只要对方支持就可以挂载，不过挂载后不稳定。

**Comment by vpei** [comment]
😁
