### ISSUE TITLE
挂载本机存储，并启用缩略图情况下，快速浏览大量图片，主进程被OOM-Killer退出

### ISSUE THREAD

**Issue by wolonggl** [alist-org/alist#1837]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

系统：Ubuntu 22.04 i3-10100t 32G 
挂载本机存储，并启用缩略图情况下，快速浏览大量图片，从htop观察来看，alist创建大量线程用于生成缩略图，内存占用和cpu占用暴涨，浏览一段时间后，alist主进程由于内存暴涨原因和占满系统内存和swap内存，触发系统内核oom-killer机制造成主进程被kill；

PS： 建议，增加缩略图缓存机制，来回切换浏览不同目录的图片时，不会重复生成缩略图，减少cpu和内存占用；

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
duplicate with #1784
