### ISSUE TITLE
dev版本上传大文件超时

### ISSUE THREAD

**Issue by hdm9527** [alist-org/alist#1842]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

dev

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

手动上传大文件显示504超时，上传失败，离线下载上传onedrive是正常的，测了好几次。因为dev版本的onedrive分块大小为100m，后面把分块大小改成50m、20m、10m编译测试，然后手动上传大文件测试，50m的有概率上传成功，20m和10m都失败了。找了下原因，文件上传到服务器之后，再到服务器上传到onedrive这段时间中，前端会一直轮询请求上传进度状态，但是因为onedrive分块大小的原因，onedrive上传一部分文件会等待几秒到十几秒之后才会继续上传，导致前端请求超时，关闭上传通道，离线下载的文件不受影响。
>解决方法

把onedrive分块大小改回4m或修改前端代码

![image](https://user-images.githubusercontent.com/39702328/192694102-afa57a24-3de7-47d2-ace2-044de31a33e9.png)
![image](https://user-images.githubusercontent.com/39702328/192694257-f64addbf-7d62-40ce-a2ab-00c0ef1ad563.png)

### Reproduction / 复现链接

无

### Logs / 日志

无

**Comment by kilvn** [comment]
轮训方法不可靠，建议使用websocket通道。
