### ISSUE TITLE
分页类型不为全部时，如果显示内容多于一页时，切换页面或者加载更多后，返回上级目录时显示空白

### ISSUE THREAD

**Issue by wolonggl** [alist-org/alist#1849]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

分页类型不为全部时，如果显示内容多于一页时，切换页面或者加载更多后，返回上级目录时显示空白，如下图
![QQ图片20220928212241](https://user-images.githubusercontent.com/17318615/192791682-668904ef-d9bd-47f8-9cc4-0aa4371206ec.png)
点击上级目录后，页面显示空白
![QQ图片20220928212900](https://user-images.githubusercontent.com/17318615/192791709-18e08eab-9e91-4bb5-bcc4-2b0ea8468efb.png)

出现空白后，点击任务目录按钮无变化，需要F5刷新页面才恢复正常。

### Reproduction / 复现链接

无

### Logs / 日志
F12开发工具查看点击上级目录后，响应信息如下：

{"code":200,"message":"success","data":{"content":null,"total":11,"readme":"","write":true,"provider":"Local"}}

_No response_

**Comment by zp96324511** [comment]
猜测bug是切换目录时，页码没有自动重置为1
