### ISSUE TITLE
lrc等文本文件乱码

### ISSUE THREAD

**Issue by 12189108** [alist-org/alist#1850]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

无关存储驱动

### Describe the bug / 问题描述

当文本为GB2312等非UTF-8编码时，显示乱码，编辑功能不可用

### Reproduction / 复现链接

本地部署

**Comment by Xhofe** [comment]
仅支持utf8
