### ISSUE TITLE
server 后自动唤醒浏览器打开网址

### ISSUE THREAD

**Issue by Hunlongyu** [alist-org/alist#1854]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在 cmd 里执行 alist.exe server ，等服务启动后，并不能自动打开网址。

至少 log 里的 0.0.0.0 写成 http://0.0.0.0， 这样部分终端在能识别出 链接时，按住 `ctrl` 点击链接还可以打开网址。

### Suggested solution / 实现思路

```cpp
#include <stdlib.h>

int main()
{
  system("start http://0.0.0.0:5244")
}
```
主要不熟悉 `go` 但应该是可以实现的吧。

**Comment by Xhofe** [comment]
我想不到这样做的必要 不是所有人都在本地使用。
