### ISSUE TITLE
Aria2下载文件失败

### ISSUE THREAD

**Issue by TwooSix** [alist-org/alist#1857]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

阿里云盘，onedrive

### Describe the bug / 问题描述

在使用aria2下载文件并上传到云盘时发生错误，但文件可以正常下载到本机。实测阿里云盘和onedrive都不行。
环境是oracle的arm服务器，ubuntu 20.04，不知道是不是arm的问题？在其他amd服务器里也确实没出现这种情况。

### Reproduction / 复现链接

https://releases.ubuntu.com/22.04.1/ubuntu-22.04.1-live-server-amd64.iso

### Logs / 日志

```shell
[31mERRO[0m[2022-09-29 13:00:58] error [failed to download ffbd602ec37a9444, unknown status 
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Update
	/home/runner/work/alist/alist/internal/aria2/monitor.go:112
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Loop
	/home/runner/work/alist/alist/internal/aria2/monitor.go:54
github.com/alist-org/alist/v3/internal/aria2.AddURI.func1
	/home/runner/work/alist/alist/internal/aria2/add.go:57
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:75
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/asm_arm64.s:1270] while run task [download https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh to [/Aliyun](/)]
```

**Comment by Xhofe** [comment]
日志过少。

**Comment by TwooSix** [comment]
> 日志过少。
清空日志重跑了一遍，也还是这些日志。具体需要的是什么日志？
```
[GIN] 2022/09/30 - 02:06:09 | 200 |       68.68µs |  183.236.83.125 | GET      "/api/public/settings"
[GIN] 2022/09/30 - 02:06:09 | 200 |       77.68µs |  183.236.83.125 | GET      "/api/me"
[GIN] 2022/09/30 - 02:06:10 | 200 |         394µs |  183.236.83.125 | POST     "/api/fs/get"
[GIN] 2022/09/30 - 02:06:10 | 200 |      322.28µs |  183.236.83.125 | POST     "/api/fs/list"
[GIN] 2022/09/30 - 02:06:21 | 200 |      185.88µs |  183.236.83.125 | POST     "/api/fs/add_aria2"
[GIN] 2022/09/30 - 02:06:25 | 200 |      400.88µs |  183.236.83.125 | POST     "/api/fs/list"
[GIN] 2022/09/30 - 02:07:28 | 200 |    85.31952ms |  183.236.83.125 | POST     "/api/fs/add_aria2"
[31mERRO[0m[2022-09-30 02:07:44] error [failed to download 414837c718406c9e, unknown status 
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Update
	/home/runner/work/alist/alist/internal/aria2/monitor.go:112
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Loop
	/home/runner/work/alist/alist/internal/aria2/monitor.go:54
github.com/alist-org/alist/v3/internal/aria2.AddURI.func1
	/home/runner/work/alist/alist/internal/aria2/add.go:57
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:75
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/asm_arm64.s:1270] while run task [download https://releases.ubuntu.com/22.04.1/ubuntu-22.04.1-live-server-amd64.iso to [/Aliyun](/)] 
```

**Comment by Xhofe** [comment]
这看起来是由于aria2返回来未知的状态。无法复现

**Comment by Triwind** [comment]
遇到同样的错误，unkonwn status
添加离线任务后可以在Alist管理--》任务--》Aria2看到任务进度
一段时间后Alist前端检测不到任务状态，后台aria2还在继续下载
alist服务部署在n1-armbian上

`ERRO[2022-09-30 10:23:38] error [failed to download eee6f1ef98097b56, unknown status 
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Update
        /app/internal/aria2/monitor.go:112
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Loop
        /app/internal/aria2/monitor.go:54
github.com/alist-org/alist/v3/internal/aria2.AddURI.func1
        /app/internal/aria2/add.go:57
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
        /app/pkg/task/task.go:75
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
        /app/pkg/task/manager.go:33
runtime.goexit
        /usr/lib/go/src/runtime/asm_arm64.s:1172] while run task [download magnet:?xt=urn:btih:4b254c0ac901b3419b9f5659a1f6a41e99235df2&dn=Dead.for.a.Dollar.2022.1080p.WEBRip.x265-RARBG&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2720&tr=udp%3A%2F%2F9.rarbg.to%3A2950&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14780&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15770 to [/aliyun](/aria2)]`

**Comment by Triwind** [comment]
> 遇到同样的错误，unkonwn status 添加离线任务后可以在Alist管理--》任务--》Aria2看到任务进度 一段时间后Alist前端检测不到任务状态，后台aria2还在继续下载 alist服务部署在n1-armbian上
> 
> `ERRO[2022-09-30 10:23:38] error [failed to download eee6f1ef98097b56, unknown status github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Update /app/internal/aria2/monitor.go:112 github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Loop /app/internal/aria2/monitor.go:54 github.com/alist-org/alist/v3/internal/aria2.AddURI.func1 /app/internal/aria2/add.go:57 github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run /app/pkg/task/task.go:75 github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1 /app/pkg/task/manager.go:33 runtime.goexit /usr/lib/go/src/runtime/asm_arm64.s:1172] while run task [download magnet:?xt=urn:btih:4b254c0ac901b3419b9f5659a1f6a41e99235df2&dn=Dead.for.a.Dollar.2022.1080p.WEBRip.x265-RARBG&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2720&tr=udp%3A%2F%2F9.rarbg.to%3A2950&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14780&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15770 to [/aliyun](/aria2)]`

刚刚在windows 10 amd64上试了一下
一样的错误

**Comment by shirakun** [comment]
同样的问题
```
ERRO[2022-10-02 21:18:24] error [failed to download 0dadf8a6c8710323, unknown status
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Update
        /home/runner/work/alist/alist/internal/aria2/monitor.go:112
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Loop
        /home/runner/work/alist/alist/internal/aria2/monitor.go:54
github.com/alist-org/alist/v3/internal/aria2.AddURI.func1
        /home/runner/work/alist/alist/internal/aria2/add.go:57
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
        /home/runner/work/alist/alist/pkg/task/task.go:75
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
        /home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
        /opt/hostedtoolcache/go/1.18.6/x64/src/runtime/asm_arm64.s:1270] while run task [download magnet:?xt=urn:btih:e5b5512d3b91e708ea13840fc012d8b0efa22207 to [/189](/anime/[c.c動漫][7月新番][異世界迷宮裡的後宮生活][01-12][合集][BIG5][1080P][MP4][AT-X])]
```

**Comment by shirakun** [comment]
> 同样的问题
> 
> ```
> ERRO[2022-10-02 21:18:24] error [failed to download 0dadf8a6c8710323, unknown status
> github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Update
>         /home/runner/work/alist/alist/internal/aria2/monitor.go:112
> github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Loop
>         /home/runner/work/alist/alist/internal/aria2/monitor.go:54
> github.com/alist-org/alist/v3/internal/aria2.AddURI.func1
>         /home/runner/work/alist/alist/internal/aria2/add.go:57
> github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
>         /home/runner/work/alist/alist/pkg/task/task.go:75
> github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
>         /home/runner/work/alist/alist/pkg/task/manager.go:33
> runtime.goexit
>         /opt/hostedtoolcache/go/1.18.6/x64/src/runtime/asm_arm64.s:1270] while run task [download magnet:?xt=urn:btih:e5b5512d3b91e708ea13840fc012d8b0efa22207 to [/189](/anime/[c.c動漫][7月新番][異世界迷宮裡的後宮生活][01-12][合集][BIG5][1080P][MP4][AT-X])]
> ```

目前摸索的解决办法:删除aria2的任务,然后重启alist,然后重新添加可能会正常下载,如果不行则重复此操作

**Comment by shirakun** [comment]
> 这看起来是由于aria2返回来未知的状态。无法复现

https://github.com/alist-org/alist/blob/6c89c6c8ae13c615fc13b811edc5b715bd302039/internal/aria2/monitor.go#L111

根据@Triwind和我的情况来看这个问题应该是出现在低配置或者高负载的情况下
我觉得获取到未知状态后应该跳过或增加重试次数并且将aria2返回内容记录到日志以便排查

**Comment by shirakun** [comment]
不正经的解决办法:
clone此仓库代码
修改`/internal/aria2/monitor.go`的112行,将内容替换为`case "active", "waiting", "paused":`的内容
到alist-web下载releases的dist.zip解压到`/public`
然后按照官方文档编译
```
appName="alist"
builtAt="$(date +'%F %T %z')"
goVersion=$(go version | sed 's/go version //')
gitAuthor=$(git show -s --format='format:%aN <%ae>' HEAD)
gitCommit=$(git log --pretty=format:"%h" -1)
version=$(git describe --long --tags --dirty --always)
webVersion=$(wget -qO- -t1 -T2 "https://api.github.com/repos/alist-org/alist-web/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
ldflags="\
-w -s \
-X 'github.com/alist-org/alist/v3/internal/conf.BuiltAt=$builtAt' \
-X 'github.com/alist-org/alist/v3/internal/conf.GoVersion=$goVersion' \
-X 'github.com/alist-org/alist/v3/internal/conf.GitAuthor=$gitAuthor' \
-X 'github.com/alist-org/alist/v3/internal/conf.GitCommit=$gitCommit' \
-X 'github.com/alist-org/alist/v3/internal/conf.Version=$version' \
-X 'github.com/alist-org/alist/v3/internal/conf.WebVersion=$webVersion' \
"
go build -ldflags="$ldflags" .
```

然后将生成的alist替换即可,这样做出现的已知问题是当aria2无法访问的时候不显示进度,直到再次可以访问

相关文档和代码
https://alist.nn.ci/zh/guide/install/source.html#%E6%9E%84%E5%BB%BA%E5%90%8E%E7%AB%AF
https://github.com/alist-org/alist/blob/6c89c6c8ae13c615fc13b811edc5b715bd302039/internal/aria2/monitor.go#L112
https://github.com/alist-org/alist/blob/6c89c6c8ae13c615fc13b811edc5b715bd302039/internal/aria2/monitor.go#L107
https://github.com/alist-org/alist/blob/6c89c6c8ae13c615fc13b811edc5b715bd302039/internal/aria2/monitor.go#L108

**Comment by gaofashao** [comment]
> > 这看起来是由于aria2返回来未知的状态。无法复现
> 
> https://github.com/alist-org/alist/blob/6c89c6c8ae13c615fc13b811edc5b715bd302039/internal/aria2/monitor.go#L111
> 
> 根据@Triwind和我的情况来看这个问题应该是出现在低配置或者高负载的情况下 我觉得获取到未知状态后应该跳过或增加重试次数并且将aria2返回内容记录到日志以便排查

同样的问题，一样是乌龟壳4c24g，实测速度超过10m/s alist就会报错，实际aria2后台仍在下载
