### ISSUE TITLE
希望播放器增加VR模式选项(LR, TM等)

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [alist-org/alist#1859]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我本地存了很多VR视频，大部分都是 左右180度的格式，少部分上下180度的，能否像 PotPlayer 一样 增加切换3D模式的选项？让没有VR设备的用户也可以正常查看视频

**Comment by itsHenry35** [comment]
你这个是不是应该去Artplayer里面提个issue https://github.com/zhw2590582/ArtPlayer alist目前使用的前端播放器是artplayer

**Comment by Misaka-Mikoto-Tech** [comment]
好的

**Comment by nini22P** [comment]
我尝试添加了个VR播放器，不过 WebGL 有 CORS 限制，必须开启 Web 代理才能播放，且只支持左右的视频[https://github.com/nini22P/alist-web/tree/video360-player](https://github.com/nini22P/alist-web/tree/video360-player)
