### ISSUE TITLE
安卓上运行服务端无法添加云储存

### ISSUE THREAD

**Issue by aiselp** [alist-org/alist#1863]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.0.3

### Driver used / 使用的存储驱动

阿里云

### Describe the bug / 问题描述

![Screenshot_20220930184305](https://user-images.githubusercontent.com/76829457/193253347-5a5b80b7-b7eb-4084-8abb-0c5eb6f8425b.jpg)

看错误信息就知道是由于进行dns查询时访问的是本地53端口出错了，可能是安卓上的53端口并没有dns服务

### Reproduction / 复现链接

无

### Logs / 日志

```shell
ERRO[2022-09-30 10:33:26] failed get enabled storages: Post "https://auth.aliyundrive.com/v2/account/token": dial tcp: lookup auth.aliyundrive.com on [::1]:53: read udp [::1]:43450->[::1]:53: read: connection refused
failed init storage
```

**Comment by XiaoXin1640** [comment]
这是go linux dns的问题，手机有root：在手机上根目录etc文件夹下创建resolv.conf文件，内容写下面的就行了
nameserver 223.5.5.5
nameserver 119.29.29.29
无root：使用Termux在proot的环境里安装Linux系统，在proot环境的Linux系统中运行alist即可。
有root的方法我并未尝试，我自己使用的无root方法，请自测。

**Comment by aiselp** [comment]
感谢解答，无root方法成功解决
