### ISSUE TITLE
负载均衡下进行文件操作的问题

### ISSUE THREAD

**Issue by DreamOfIce** [alist-org/alist#1865]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

Aliyundrive,123pan,189Cloud

### Describe the bug / 问题描述

在开启负载均衡的情况下，使用alist对文件进行操作（上传/新建/修改/删除等），只会按照轮询顺序对其中一个存储进行修改，例如：
某目录由存储1和存储2组成负载均衡。
在此目录下新建文件test，后端只会在存储1中创建此文件，从而导致两个存储之间文件结构不一致。

### Reproduction / 复现链接

[cloud.dreamofice.cn](https://cloud.dreamofice.cn/)
此站在根目录下挂载了三个存储组成负载均衡，按照上面的例子新建文件test。
观察发现每刷新3次文件列表，就会有一次出现文件test。

**Comment by Xhofe** [comment]
网盘文件结构自己保持，本程序不提供。

**Comment by DreamOfIce** [comment]
> 网盘文件结构自己保持，本程序不提供。

那就是说开启负载均衡的情况下无法正常使用alist上传/修改文件的功能了吗？

**Comment by DreamOfIce** [comment]
建议至少加一个提示，或者在开启负载均衡的情况下禁用文件修改相关功能
