### ISSUE TITLE
存在负载均衡且包含阿里云盘时，将Safari端的视频在线预览请求全部交由阿里云盘处理

### ISSUE THREAD

**Issue by DreamOfIce** [alist-org/alist#1866]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

参考文档中[为什么我不能预览视频或音频文件](https://alist.nn.ci/zh/faq/why.html#为什么我不能预览视频或音频文件)
开启负载均衡时，能否将safari浏览器的视频预览请求尽可能使用阿里云盘？

（考虑到此功能可能导致负载不均，建议加一个开关）

### Suggested solution / 实现思路

后端根据UA判断Safari浏览器，返回阿里云盘的结果

**Comment by Xhofe** [comment]
Not a popular requirement.
