### ISSUE TITLE
任务列表希望能增加一键取消所有任务的功能

### ISSUE THREAD

**Issue by 12189108** [alist-org/alist#1870]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

当复制别的网盘的文件夹时，可能会不小心点多一个，文件夹内文件过多的话，一个一个取消过于折磨

**Comment by whl9701125** [comment]
可以通过停止alist 再启动，任务便会清除
