### ISSUE TITLE
关于V3版本无法部署至Render的相关问题

### ISSUE THREAD

**Issue by MiaoLuoNa** [alist-org/alist#1871]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.0.3

### Driver used / 使用的存储驱动

OneDrive E5

### Describe the bug / 问题描述

![192287549-d23ed145-b0ba-4da5-9364-5e4906e748bd](https://user-images.githubusercontent.com/62191675/193402453-f42801f1-1e17-4b6b-97eb-b15ac21c6c0c.png)
使用一键部署 ↑
![192294601-5af671e0-e7eb-4d6e-b792-76939006163e](https://user-images.githubusercontent.com/62191675/193402463-764bfb3b-6ff2-45c0-b8fa-899ab605dfc8.png)
自行部署 ↑
![image](https://user-images.githubusercontent.com/62191675/193402491-947070de-4836-4c06-953d-da3a3444df55.png)
环境变量 ↑
使用alist-render commit：4d8e55a

### Reproduction / 复现链接

无

**Comment by shirakun** [comment]
仓库已被render列入黑名单,需要自行fork和修改之后才可以部署

**Comment by MiaoLuoNa** [comment]
> 仓库已被render列入黑名单,需要自行fork和修改之后才可以部署

那也用不了

**Comment by taylormao** [comment]
> > 仓库已被render列入黑名单,需要自行fork和修改之后才可以部署
> 
> 那也用不了

我也遇到你的问题。我也是自己fork，并且修改了。依旧不能使用。我还把配置的内容天灾render.yml里面中，也无济于事。

估计是docker.io的镜像地址失效。

• http://docker.io/xhofe/alist:latest
• http://docker.io/xhofe/alist:latest@sha256:39e84ef7da0e99b54d5b273407e16cf71842888c616b96cd45ed38cb4ebbaa55
• http://registry-1.docker.io/

就是这三个。我不知道哪里可以修改这三个

**Comment by mengguyi** [comment]
自己build一个传到docker

**Comment by LSQ-Code** [comment]
> > > 仓库已被render列入黑名单，需要自行fork和修改之后才可以部署
> > 
> > 
> > 那也用不了
> 
> 我也遇到你的问题。我也是自己fork，并且修改了。依旧不能使用。我还把配置的内容天灾render.yml里面中，也无济于事。
> 
> 估计是 docker.io 的镜像地址失效。
> 
> • http://docker.io/xhofe/alist:latest • http://docker.io/xhofe/alist:latest@sha256:39e84ef7da0e99b54d5b273407e16cf71842888c616b96cd45ed38cb4ebbaa55 • http://registry-1.docker.io/
> 
> 就是这三个。我不知道哪里可以修改这三个

你好 有解决方法了吗
