### ISSUE TITLE
编码下载链接功能无效

### ISSUE THREAD

**Issue by Lumilk233** [alist-org/alist#1872]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

最新DEV版本

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

![图片](https://user-images.githubusercontent.com/110418934/193409837-ccea9f89-f3b6-43f1-ac61-af3ce41b1408.png)
使用该功能复制下载链接依然为未编码直链

### Reproduction / 复现链接

https://pan.lumine233.ml/Lumine/ESET%20Offline-Update

**Comment by Xhofe** [comment]
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/36558727/193415610-14cd79db-4cd5-4df3-a27f-53e6920ce6a8.png">
