### ISSUE TITLE
希望能恢复V2版本一直用着很好的复制黏贴路径功能

### ISSUE THREAD

**Issue by zhanglinku** [alist-org/alist#1874]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Alist Version / Alist 版本
v3.0.3
Driver used / 使用的存储驱动
阿里云盘

经常要分发IPA，V2可以直接复制黏贴修改目录ID就好。
现在需要每个都手动添加，有些繁琐。希望能增加这个功能。

**Comment by llyang1** [comment]
我刚升级到v3.2.1, 以前一直使用v2.6.1
v3功能确实强大，特别是网盘之间复制非常实用等。同时，也发现楼主这个同样的问题。
如果作者感觉每个网盘都统一支持copy/paste有困难，可以对常用网盘支持，特别是onedrive，参数实在有点多。
为了保留目前v3美观的界面。可以在Edit界面添加copy/paste按钮。

另外，以前的管理界面和浏览界面，都是在同一个窗口；v3会跳转新开窗口，感觉不跳转更好。这个是小问题，可以忽略。
