### ISSUE TITLE
建议把log.log改成每次缓冲区满了重新打开文件写入的模式

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [alist-org/alist#1875]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前日志文件 log.log 被 alist独占打开，中途不能修改，一旦修改alist就不会再继续写入，建议改成内部设置个buffer，buffer满了或者缓冲区不为空且时间超过一定长度就重新打开此文件，定位到文件末尾，写入。这样这个文件就可以被外部修改了（比如日志太多想清空时）。很多其它项目的日志类型文件都是这样操作的

**Comment by Xhofe** [comment]
日志是自动轮转的。
