### ISSUE TITLE
Text Editor saving would duplicate file

### ISSUE THREAD

**Issue by 66Leo66** [alist-org/alist#1880]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

Google Drive

### Describe the bug / 问题描述

1. Use Text Editor to edit a file
2. save
3. refresh and see duplicated file

not sure if this is a Gdrive-only problem.

### Reproduction / 复现链接

Try editing `test.md` at:
https://alist.6leo6.com/GDrive/PublicUpload/Testing

**Comment by Xhofe** [comment]
> https://support.tmssoftware.com/t/uploading-same-file-to-google-drive-creates-a-duplicate/12386

Does googledrive supoort overwrite upload?

**Comment by 66Leo66** [comment]
Not sure but inferring from the official gdrive client, it should be somehow avaliable.And no matter what we can delete-reupload to update (text) files.alist-org/alist 写道:
Hello @66Leo66, please input issue by template and add detail. Issues labeled by question will be closed if no activities in 7 days.
你好 @66Leo66，请按照issue模板填写, 并详细说明问题/复现步骤/复现链接/实现思路或提供更多信息等, 7天内未回复issue自动关闭。

**Comment by Xhofe** [comment]
File may loss as re-upload cannot be guaranteed to be 100% successful.
