### ISSUE TITLE
手机chrome浏览器使用mxplayer播放mp4文件会跳转到谷歌应用商店

### ISSUE THREAD

**Issue by Monster-DP** [alist-org/alist#1881]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

本地储存

### Describe the bug / 问题描述

手机chrome浏览器使用mxplayer播放mp4文件会跳转到谷歌应用商店，播放mkv视频mxplayer可以直接打开

### Reproduction / 复现链接

无

**Comment by Monster-DP** [comment]
> 
我用的是去广告版，这个也有影响吗，我看他们的包名是一样的的唉

**Comment by Xhofe** [comment]
检查 `关联URI协议`
