### ISSUE TITLE
对接aria2离线下载出错

### ISSUE THREAD

**Issue by kuake0** [alist-org/alist#1887]
Please make sure of the following things
 I have read the documentation.
 I'm sure there are no duplicate issues or discussions.
 I'm sure it's due to alist and not something else(such as Dependencies or Operational).
 I'm sure I'm using the latest version
Alist Version / Alist 版本
v3.0.3

Driver used / 使用的存储驱动
Aliyun, PikPak or any driver

Describe the bug / 问题描述
aria2一直说无法创建指定目录，文件夹权限明明都已经开放了
https://s1.xptou.com/2022/10/05/633d105f26137.jpg
https://s1.xptou.com/2022/10/05/633d10b4174cd.jpg

**Comment by THU-Pieris** [comment]
> 这个问题我也遇到了，解决办法就是因为aria2是docker部署的，我是群晖，加个映射的路径即可，

我也是docker部署。请问具体怎么映射路径？谢谢
