### ISSUE TITLE
webdav的代理模式似乎有问题

### ISSUE THREAD

**Issue by 1621391916** [alist-org/alist#1891]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

全部

### Describe the bug / 问题描述

使用了自建的Worker 代理，“Web 代理”模式打开是能够正常调用的；然而webdav策略切换到”使用代理地址“模式后，webdav就无法使用了。在worker的实时日志中看到“Web 代理”模式打开时通过网页下载是有日志产生的，但是用webdav时就没有

### Reproduction / 复现链接

http://cloud.wangyuye.cc/d/OneDrive/test.bin
网页下载：
![image](https://user-images.githubusercontent.com/42343279/194049248-bc31fb18-7c6e-4edc-9235-84040bb0e060.png)
webdav就一直卡住：
![image](https://user-images.githubusercontent.com/42343279/194049451-a234bb78-7e1d-476e-a892-e2fa70bbd410.png)

**Comment by paowan2** [comment]
> 使用代理地址也是302 并不是webdav标准协议 client可能不适配，使用本机代理。

如果alist接入webdav的网盘，放在公网公开分享，别人播放此webdav网盘上的视频是不是要耗损alist所在服务器的流量，因为本机做了代理？

**Comment by paowan2** [comment]
如果放在公网（假设只挂载了阿里盘）通过webdav接口分享给别人，用户播放视频的时候会不会耗损alist所在机器的流量？

**Comment by Humetea** [comment]
用cloudflare代理同样出现该问题，网页端能正常传输文件，但是webdav传输文件会报错

**Comment by 1621391916** [comment]
> 

在2.0版本中webdav代理是能正常使用的，我是在刚刚升级了3.0后才发现的问题，感觉可能是bug导致的

**Comment by 1621391916** [comment]
> 使用代理地址也是302 并不是webdav标准协议 client可能不适配，使用本机代理。

在2.0版本中webdav代理是能正常使用的，我是在刚刚升级了3.0后才发现的问题，感觉可能是bug导致的

**Comment by Xhofe** [comment]
> > 使用代理地址也是302 并不是webdav标准协议 client可能不适配，使用本机代理。
> 
> 在2.0版本中webdav代理是能正常使用的，我是在刚刚升级了3.0后才发现的问题，感觉可能是bug导致的

不是
