### ISSUE TITLE
failed get storage: can't find storage with rawPath: /

### ISSUE THREAD

**Issue by fengUi** [alist-org/alist#1902]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

failed get storage: can't find storage with rawPath: /
打开提示这个错误是什么问题导致的呢？

**Comment by arbaleast** [comment]
可能得到，网盘里面才能上传哦，aria上传的应该是当前你看到的页面

**Comment by qixianchuan** [comment]
![image](https://user-images.githubusercontent.com/11327411/199383229-cced3f9e-4e67-44f6-9105-4371f24f0445.png)

![image](https://user-images.githubusercontent.com/11327411/199383279-da10caf1-2716-4aca-80e9-360e5b914db4.png)

**Comment by aogg** [comment]
到底为什么，我刚安装，登录上去就显示这个

**Comment by arbaleast** [comment]
没挂载网盘

**Comment by ponponon** [comment]
> 没挂载网盘

怎么挂载?在哪挂载？
