### ISSUE TITLE
本地路径挂载问题

### ISSUE THREAD

**Issue by Cyiming** [alist-org/alist#1905]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.03

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

路径命名存在 挂载说不存在

![image](https://user-images.githubusercontent.com/45073586/194499926-1e58d6d6-711c-4956-b1c3-3f6e3219730a.png)

![}} U6O3$)AM{@N(ZL}MH6VT](https://user-images.githubusercontent.com/45073586/194499997-52fe24ee-cb73-4a88-9462-ce68ff6f37b2.png)

### Reproduction / 复现链接

![}} U6O3$)AM{@N(ZL}MH6VT](https://user-images.githubusercontent.com/45073586/194499997-52fe24ee-cb73-4a88-9462-ce68ff6f37b2.png)

**Comment by Xhofe** [comment]
docker?

**Comment by Xhofe** [comment]
> > docker?
> 
> 是的

先查查docker怎么用的，容器路径与宿主机路径什么关系。

**Comment by Cyiming** [comment]
> > > docker?
> > 
> > 
> > 是的
> 
> 先查查docker怎么用的，容器路径与宿主机路径什么关系。

问题是我放在容器目录外也不行啊
![image](https://user-images.githubusercontent.com/45073586/194572632-3c50c2a9-9f50-4c61-925d-26a64dd1449d.png)
![image](https://user-images.githubusercontent.com/45073586/194572657-42914bcb-77ac-4c25-9f42-2bb7efb1991e.png)

**Comment by Xhofe** [comment]
所以让你先查查docker怎么用的，不了解的话就直接在宿主机安装，不要使用docker。
