### ISSUE TITLE
升级出错

### ISSUE THREAD

**Issue by Kenny0521** [alist-org/alist#1910]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

Update

### Describe the bug / 问题描述

curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s update
使用一键升级命令升级，发现错误
“
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
”
发现会下载->https://ghproxy.com/https://github.com/alist-org/alist/releases/download/v3.1.0/alist-linux-musl-amd64.tar.gz
目前的latest releases中没有带**musl**包的
望添加

### Reproduction / 复现链接

https://ghproxy.com/https://github.com/alist-org/alist/releases/download/v3.1.0/alist-linux-musl-amd64.tar.gz

**Comment by Kenny0521** [comment]
> ### See
> 1. 50% [运行出错 #573](https://github.com/alist-org/alist/issues/573)

oh not that

**Comment by Xhofe** [comment]
这么着急？？？？
GitHub actions 没编译完

**Comment by Kenny0521** [comment]
> 这么着急？？？？ GitHub actions 没编译完

确实着急

**Comment by Xhofe** [comment]
着急也不要什么问题都提issue
> **issues are for bug reports and feature request only**
