### ISSUE TITLE
V3没有api_proxy_url

### ISSUE THREAD

**Issue by shelken** [alist-org/alist#1913]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用google drive时发现没有这个api_proxy_url了，访问api一直超时，能否加上？或者有哪里可以配置http_proxy的地方。

### Suggested solution / 实现思路

v2有这个选项

### Additional context / 附件

无

**Comment by Xhofe** [comment]
https://askubuntu.com/questions/583797/how-to-set-a-proxy-for-terminal

**Comment by shelken** [comment]
我知道终端的这个export,但是我这个是在docker中运行，尝试过加上环境变量HTTP_PROXY。还是超时
