### ISSUE TITLE
视频调用potplay时提示解码失败

### ISSUE THREAD

**Issue by fcwys** [alist-org/alist#1920]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.1.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

视频调用potplay时提示解码失败，查看日志信息是由于URL被编码导致potplayer不能解析，另外希望播放器图标加上title说明更清晰一些(如下图)，谢谢！
![image](https://user-images.githubusercontent.com/28641034/194682176-0eb94d77-42fc-4d37-9a9f-7dc5595dd5d6.png)

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/28641034/194681533-1664e0f7-2fe5-4404-8091-294e1c55c3ec.png)
v3版本链接异常：
![image](https://user-images.githubusercontent.com/28641034/194681558-82048bf8-7f25-48ed-a702-bdc7a0a2b8d2.png)
v2版本链接正常：
![image](https://user-images.githubusercontent.com/28641034/194681604-c0b87ec3-83b4-41fe-980a-119aa0aa356d.png)

**Comment by RiddlerM** [comment]
可以尝试更新potplayer到最新版本 220914(1.7.21801)
