### ISSUE TITLE
无法挂载Google photos

### ISSUE THREAD

**Issue by qinfengge** [alist-org/alist#1925]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.1.0

### Driver used / 使用的存储驱动

google photos

### Describe the bug / 问题描述

无论是使用默认凭证还是自己手动申请凭证（已开启Photos Library API）均无法使用

### Reproduction / 复现链接

无

### Logs / 日志

```shell
版本为docker，docker日志无异常
failed get objs: failed to list objs: Request had insufficient authentication scopes.: []
```

**Comment by Xhofe** [comment]
@LittleJake

**Comment by LittleJake** [comment]
进行oauth时需要选中scope，具体参考rclone获取。
`rclone authorize "Google Photo"`

**Comment by LittleJake** [comment]
Btw，当时用rclone的OAuth接口调用超限，最好用自己的client id。

**Comment by LittleJake** [comment]
> 用rclone的OAuth应用演示一下

详细步骤：
1. 打开alist提供的 [谷歌网盘令牌获取](https://tool.nn.ci/google/request)，填入自己应用的`client_id`、`client_secret`；
2. 访问url：`https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?client_id={client_id}&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=openid%20profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary&access_type=offline&approval_prompt=auto&flowName=GeneralOAuthFlow`
 **（其中的`{client_id}`更换为自己应用的`client_id`）**；
 ![20221008223710](https://user-images.githubusercontent.com/13583702/194712984-73d90631-8921-4f18-97fb-fcf1b3f545b6.png)
3. 登录后授权，得到`code`填入 步骤1中`code`编辑框；
4. 点击获取刷新令牌即可。
 ![image](https://user-images.githubusercontent.com/13583702/194713045-53824577-e0f2-43a4-bca1-5143b8dcb5c8.png)

**Comment by qinfengge** [comment]
我查看了Google的[文档](https://support.google.com/cloud/answer/6158849#authorized-domains&zippy=%2Cauthorized-domains%2Cpublic-and-internal-applications%2Cuser-consent)
似乎可以指定范围
![1665279460935.png](https://pic.jitudisk.com/public/2022/10/08/64ee746b5f14c.png)
但又有新的问题，Google不支持使用urn:ietf:wg:oauth:2.0:oob这种格式作为重定向URI
![1665279591308.png](https://pic.jitudisk.com/public/2022/10/08/2ce20321d2a33.png)
为什么上面的可以使用那种方式呢，还有别的方法吗？
另外，非常感谢您抽空回复我

**Comment by LittleJake** [comment]
可以尝试创建OAuth桌面应用，桌面应用无回调URI。

**Comment by qinfengge** [comment]
感谢，此方法有效
![1665281064930.png](https://pic.jitudisk.com/public/2022/10/08/224995d29203d.png)

**Comment by eattrenclenhard** [comment]
You may deploy your own app from my [repository ](https://github.com/eattrenclenhard/Sho-Time/) to generate access token to Google Token if you prefer your own client credentials over Rclone's and have security concerns over public access token generator.

[preview URL](https://shotime.streamlit.app)
<details>
    <summary>Demo screen capture</summary>
    ![shotime](https://github.com/user-attachments/assets/5f13cd2a-68e0-4b7c-8b3f-802c404060b7)
</details>

**Comment by eattrenclenhard** [comment]
You may deploy your own app from my [repository ](https://github.com/eattrenclenhard/Sho-Time/) to generate access token to Google Token if you prefer your own client credentials over any public's client id-secret pair and have security concerns over public access token generator.

[preview URL](https://shotime.streamlit.app)
![Image](https://github.com/user-attachments/assets/c9553f02-9683-4460-a7c7-87821f2ec845)
