### ISSUE TITLE
无法删除禁用状态下的存储

### ISSUE THREAD

**Issue by DreamOfIce** [alist-org/alist#1942]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.1.0

### Driver used / 使用的存储驱动

本地存储,189云盘

### Describe the bug / 问题描述

无法删除已经禁用的存储，会提示`Failed get storage driver: no mount path for an storage is: /path/to/storage`(见图1)
必须将存储启用后再删除(图2)
![图1](https://user-images.githubusercontent.com/80821706/194754167-5a2d6b11-fee0-4a13-9a13-6ed95f72fbd5.jpeg)
![图2](https://user-images.githubusercontent.com/80821706/194754266-1c0ef917-2b64-46a1-a509-36d894357b85.jpeg)

### Reproduction / 复现链接

见上

**Comment by zcluo** [comment]
阿里云盘OPEN又出现该问题

**Comment by londbell** [comment]
尝试挂载windows smb，遇到一样的问题。这个smb挂载不成功，且无法删除，报错一致，即使修改挂载路径也一样。
最后是备份，然后把docker-compose里的映射/etc/alist删除，重新up，把备份json里的新增挂载项移除，问题解决
