### ISSUE TITLE
是否能提供通过命令行的方式挂载网盘的功能，以便通过脚本的方式批量添加资源

### ISSUE THREAD

**Issue by dl280** [alist-org/alist#1950]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

是否能提供通过命令行的方式挂载网盘的功能，以便通过脚本的方式批量添加资源。

**Comment by Xhofe** [comment]
没懂你说的什么意思

**Comment by shirakun** [comment]
可以开f12看看网页添加时传的参数,然后自己通过curl实现

**Comment by HelloMusician** [comment]
V2版本里有个备份和导入功能，可以把添加的网盘信息批量导出再导入新的服务器的alist里面，V3支持吗大佬？@Xhofe

**Comment by dl280** [comment]
> 
![image](https://user-images.githubusercontent.com/63228072/195812477-d2d815c8-6a01-4a17-9e6d-fbec2b774ac9.png)
![image](https://user-images.githubusercontent.com/63228072/195813443-9241f6d0-d356-48dd-a3e0-7fa99c07eefc.png)
就是希望通过命令行的方式挂载阿里云盘中的资源，或者可以提供对应的api，方便二次开发。
