### ISSUE TITLE
功能需求:下载链接地址不失效，可以增加一个失效的时间吗？

### ISSUE THREAD

**Issue by 331969102** [alist-org/alist#1952]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

昨天给我朋友下载链接，然后今天那个链接依旧可以使用，可以增加一个失效时间的选择吗？
昨天那个链接是阿里云，还没什么，但是我想用Alist使用本机存储，如果链接一直有效，然后下载地址暴露在公网，会增加服务器压力，可以单独为本机存储增加一个分享系统吗，让下载链接可以选择定时失效或者长期有效！

**Comment by jj225511** [comment]
给目录加密，然后全局设置里设置直链有效期

**Comment by 331969102** [comment]
> 给目录加密，然后全局设置里设置直链有效期

谢谢！请问全局里直链有效期默认为"0",是不是如果我设置为"1"，是不是链接1天后失效，因为设置那里没有单位！

**Comment by jj225511** [comment]
> 
小时

**Comment by zuilintan** [comment]
单独设置直链有效期：0.1，
等待超过6分钟，链接依然可以下载，

不确定加上目录加密后是否可行
