### ISSUE TITLE
alist挂载出错 Failed create storage in database: disk I/O error

### ISSUE THREAD

**Issue by kany2000** [alist-org/alist#1953]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

baidu&tianyi

### Describe the bug / 问题描述

alist挂载出错 Failed create storage in database: disk I/O error
root@docker-lxc:~/alist# systemctl status alist
* alist.service - Alist service
     Loaded: loaded (/etc/systemd/system/alist.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-10-10 04:55:04 UTC; 3s ago
    Process: 20951 ExecStart=/root/alist/alist server (code=exited, status=1/FAILURE)
   Main PID: 20951 (code=exited, status=1/FAILURE)
        CPU: 69ms

Oct 10 04:55:04 docker-lxc systemd[1]: Started Alist service.
Oct 10 04:55:04 docker-lxc alist[20951]: INFO[2022-10-10 04:55:04] reading config file: data/config.json
Oct 10 04:55:04 docker-lxc alist[20951]: INFO[2022-10-10 04:55:04] load config from env with prefix: ALIST_
Oct 10 04:55:04 docker-lxc alist[20951]: INFO[2022-10-10 04:55:04] init logrus...
Oct 10 04:55:04 docker-lxc alist[20951]: 2022/10/10 04:55:04 failed migrate database: disk I/O error
Oct 10 04:55:04 docker-lxc systemd[1]: alist.service: Main process exited, code=exited, status=1/FAILURE
Oct 10 04:55:04 docker-lxc systemd[1]: alist.service: Failed with result 'exit-code'.

### Reproduction / 复现链接

内网构建alist

**Comment by Nu-Exception** [comment]
运行alist 时提示:load config error: readObjectStart: expect { or n, but found , error found in #1 byte of ...||..., bigger context ...||... 怎么处理啊，在哪改？
