### ISSUE TITLE
希望可以自定义aria2的离线下载路径

### ISSUE THREAD

**Issue by JsonSong89** [alist-org/alist#1957]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

当alist添加aira2的下载任务时
下载路径为
/opt/alist/data/temp/aria2/{uuid} 
然而我希望可以把/opt/alist路径留在主硬盘,把下载的临时文件保存在另外一个挂载盘(30块钱的傲腾m10,可劲造)
但是没有找到配置aria2下载路径的地方

### Suggested solution / 实现思路

可以在管理后台配置aria2的下载路径

**Comment by anwen-anyi** [comment]
1. 哪你把alist安装的时候安装到你哪个 30块钱的m10硬盘上面就行呗~  **ヾ§ ￣▽)ゞ2333333**

 2. 或者把临时目录路径改到哪个硬盘也行
data/config.json
```json
  "temp_dir": "data/temp",
```

**Comment by JsonSong89** [comment]
好的 我试试改下配置
