### ISSUE TITLE
[Feature request] 开放运行状态接口用于个人仪表盘应用

### ISSUE THREAD

**Issue by tom8zds** [alist-org/alist#1964]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

为heimdal或[homepage](https://github.com/benphelps/homepage)等个人仪表盘提供软件的状态查看接口，如复制、aria任务个数和完成状态，上传/下载速率等

### Suggested solution / 实现思路

添加管理页面仪表盘页面，收集相关数据，开放接口，开放用户token

### Additional context / 附件

![截图 2022-10-11 08-14-41](https://user-images.githubusercontent.com/20534594/194970933-b17bbf6e-82ef-4373-8838-c865042007ec.png)

**Comment by Xhofe** [comment]
所有接口定义在 https://github.com/alist-org/alist/blob/main/server/router.go 可自行查看 不会适配特定接口 需要请pr。

token 后台自取。
