### ISSUE TITLE
建议能够禁用webdav的缓存

### ISSUE THREAD

**Issue by aiselp** [alist-org/alist#1967]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用webdav配合其他同步软件使用时，由于缓存原因经常出现上传了文件却找不到文件而引发各种错误。

### Additional context / 附件

截图虽然使用的是2.6版本，但最新的3.1版本也有同样问题
![Screenshot_20221005211601](https://user-images.githubusercontent.com/76829457/194982292-d9a45952-970a-47de-93c9-c44161efbfc1.jpg)

**Comment by findyy99** [comment]
我这不知道算不算是同样的问题，文件事实上已经上传成功了，但是`Zotero`经常提示上传失败，`nginx`已经设置了`405`到`200`的转发
```
[JavaScript Error: "Upload request 1/KKHFAPLK failed"]

[JavaScript Error: "您的 WebDAV 服务器对 PUT 请求返回了 HTTP 405 错误。

如果您频繁收到此消息，请检查您的 WebDAV 服务器设置，或联系 WebDAV 服务器的管理员。

URL：https://findyy:********@xxx25.xyz/dav/zotero/KKHFAPLK.zip" {file: "chrome://zotero/content/xpcom/storage/webdav.js" line: 1496}]

[JavaScript Error: "Upload request 1/C8T4CJ3T failed"]

[JavaScript Error: "您的 WebDAV 服务器对 PUT 请求返回了 HTTP 405 错误。

如果您频繁收到此消息，请检查您的 WebDAV 服务器设置，或联系 WebDAV 服务器的管理员。
```

**Comment by 354770288** [comment]
+1 使用网盘做图床，图床通过alist上传后，必须等待缓存刷新后才可访问。

**Comment by JsonSong89** [comment]
有个手动刷新的按钮 
这个可以强刷文件目录吗?

**Comment by evlic** [comment]
感觉像是文件上传 / 删除一类的操作没有触发缓存更新（可能需要 RWMutex）导致的，我对这个问题同样关心。

**Comment by aiselp** [comment]
之后发现这个问题不是缓存的原因，而是一刻相册会把上传的图片全部重命名，就造成上传成功却找不到图片

**Comment by refined-fish** [comment]
> 把缓存过期时间改成-1

没法输入-符号，只能输入数字吧

**Comment by refined-fish** [comment]
> webdav除非上传到没有秒传的网盘，否则都得走缓存。 另外用rclone，webdav可以走相同的名称复制，也不用缓存。 比如 rclone --timeout 0 --retries 10 --transfers 1 --tpslimit 0.5 copy -P alist:本机存储路径 alist:网盘路径 这样也不用走缓存

感谢您的解答，我是想用群晖cloudSync来同步备份，大量的文件需要消耗太多的空间和磁盘寿命，我才想到能不能关闭这个缓存。
我对技术细节了解不多，按照您的意思是说，这是WebDAV的特性，并不是一个Bug。🥲如果可能的话，不知道您有没有什么好的想法？

**Comment by cyay10** [comment]
> > > webdav除非上传到没有秒传的网盘，否则都得走缓存。 另外用rclone，webdav可以走相同的名称复制，也不用缓存。 比如 rclone --timeout 0 --retries 10 --transfers 1 --tpslimit 0.5 copy -P alist:本机存储路径 alist:网盘路径 这样也不用走缓存
> > 
> > 
> > 感谢您的解答，我是想用群晖cloudSync来同步备份，大量的文件需要消耗太多的空间和磁盘寿命，我才想到能不能关闭这个缓存。 我对技术细节了解不多，按照您的意思是说，这是WebDAV的特性，并不是一个Bug。🥲如果可能的话，不知道您有没有什么好的想法？
> 
> 用啥套件，你是白群晖就咸鱼出掉，黑群晖就刷linux发行版，来用命令行rclone不吊打群晖

rclone 不能实时同步吧。

**Comment by cyay10** [comment]
> > > > > > > webdav除非上传到没有秒传的网盘，否则都得走缓存。 另外用rclone，webdav可以走相同的名称复制，也不用缓存。 比如 rclone --timeout 0 --retries 10 --transfers 1 --tpslimit 0.5 copy -P alist:本机存储路径 alist:网盘路径 这样也不用走缓存
> > > > > > 
> > > > > > 
> > > > > > 感谢您的解答，我是想用群晖cloudSync来同步备份，大量的文件需要消耗太多的空间和磁盘寿命，我才想到能不能关闭这个缓存。 我对技术细节了解不多，按照您的意思是说，这是WebDAV的特性，并不是一个Bug。🥲如果可能的话，不知道您有没有什么好的想法？
> > > > > 
> > > > > 
> > > > > 用啥套件，你是白群晖就咸鱼出掉，黑群晖就刷linux发行版，来用命令行rclone不吊打群晖
> > > > 
> > > > 
> > > > rclone 不能实时同步吧。
> > > 
> > > 
> > > 可以定时
> > 
> > 
> > rclone mount 到本地 在用 那些同步工具 同步 这样能行吗 大佬。
> 
> rclone建议只复制，挂载推荐用隔壁的clouddrive

我用 cd2 挂载alist webdav ， 然后 用cd2 同步  。  视频文件 3-4G就 复制不过去了。。。。
