### ISSUE TITLE
doc xls等文件无法正常预览

### ISSUE THREAD

**Issue by flywalt** [alist-org/alist#1970]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.1.0

### Driver used / 使用的存储驱动

onedrive、百度云

### Describe the bug / 问题描述

预览doc xls等文件时出现错误
![d16740b08aac4fb3fc528cd138a30cd](https://user-images.githubusercontent.com/56569425/195000246-2e559389-d7b9-4361-8540-a4272b94f45f.jpg)
System error: InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### Reproduction / 复现链接

http://ddns.dafeis.com:5244/

**Comment by flywalt** [comment]
顺便这个bug我查询到了其他的issue提到过，但是是预览ipa文件之类的，并且也没看到具体的问题解决方案

**Comment by Xhofe** [comment]
Reproduction is required.

**Comment by Xhofe** [comment]
打不开。

**Comment by flywalt** [comment]
我试了下可以打开，是不是因为我这是ipv6的ddns，需要V6环境才能打开……
那我研究下能不能4穿6弄个别的复现地址
