### ISSUE TITLE
AList v3.1.0，元信息设置了文件夹密码，但是实际无效仍可以查看（无论是用户还是游客）

### ISSUE THREAD

**Issue by Zacharry** [alist-org/alist#1977]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.1.0

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

AList v3.1.0，元信息设置了文件夹密码，但是实际无效仍可以查看（无论是用户还是游客）

### Reproduction / 复现链接

/

### Logs / 日志

```shell
[GIN] 2022/10/11 - 22:15:48 | 200 |   876.33567ms |    | GET      "/d/🐢Allen🐢/2a02b3f9e8f7e672c83065959e5dc34a.png?sign=C32cSQJB0ZbF-9wNHvFqnBw4gxjKZxlI75YkQrENlRQ=:0"

排查了日记输出没有问题是正常进入
```

**Comment by Zacharry** [comment]
> ### 看
> 1. 59% [AList v3.1.0部署到域名下的子目录时，登陆成功与游客访问会跳转至域名根目录](https://github.com/alist-org/alist/issues/1966)[ #1966](https://github.com/alist-org/alist/issues/1966)[](https://github.com/alist-org/alist/issues/1966)
> 2. 56% [Alist白屏 #1550](https://github.com/alist-org/alist/issues/1550)

并非以上问题，请排查

**Comment by Zacharry** [comment]
更正：元信息设置的文件夹密码不能作用于游客用户，游客用户可以查看所有，用户登录后反而需要填写密码后才能进入文件夹

**Comment by ynyyn** [comment]
看起来是因为有程序缓存，导致新设置的访问密码并不立刻生效。我这边试着重启服务，行为就符合预期了。

**Comment by ynyyn** [comment]
我发现触发这一问题的场景似乎是编辑一个已有的元信息，只原信息的路径，它的元信息密码失效，除非将「应用到子文件夹」来回切换保存，或者重启程序，才会符合预期。

**Comment by zerofo** [comment]
> 我发现触发这一问题的场景似乎是编辑一个已有的元信息。编辑元信息的路径，提交保存后元信息密码彻底失效，除非将「应用到子文件夹」来回切换保存，或者重启程序，密码才会生效。
> 
> 无论是旧路径还是新路径，无论原本状态是否应用到子文件夹，都需要来回切换一下「应用到子文件夹」开关，密码功能才恢复正常。

然而 知道 路径 加个 /p/ 还可以不用密码。。。
例如 http://ip/test/ 元信息加密  test下有test.zip
直接访问 http://ip/p/test/test.zip 还是能正常下载

**Comment by xhofe** [comment]
> > 我发现触发这一问题的场景似乎是编辑一个已有的元信息。编辑元信息的路径，提交保存后元信息密码彻底失效，除非将「应用到子文件夹」来回切换保存，或者重启程序，密码才会生效。
> > 无论是旧路径还是新路径，无论原本状态是否应用到子文件夹，都需要来回切换一下「应用到子文件夹」开关，密码功能才恢复正常。
> 
> 然而 知道 路径 加个 /p/ 还可以不用密码。。。 例如 [http://ip/test](http://ip/test/) 元信息加密 test下有test.zip 直接访问 http://ip/p/test/test.zip 还是能正常下载无需密码

https://alist.nn.ci/guide/drivers/common.html#enable-signing

**Comment by zerofo** [comment]
> 知道 路径 加个 /p/ 还可以不用密码。。。
> 例如 http://ip/test/ 元信息加密 test下有test.zip
> 直接访问 http://ip/p/test/test.zip 还是能正常下载无需密码

感谢

**Comment by zerofo** [comment]
> > > 我发现触发这一问题的场景似乎是编辑一个已有的元信息。编辑元信息的路径，提交保存后元信息密码彻底失效，除非将「应用到子文件夹」来回切换保存，或者重启程序，密码才会生效。
> > > 无论是旧路径还是新路径，无论原本状态是否应用到子文件夹，都需要来回切换一下「应用到子文件夹」开关，密码功能才恢复正常。
> > 
> > 
> > 然而 知道 路径 加个 /p/ 还可以不用密码。。。 例如 [http://ip/test](http://ip/test/) 元信息加密 test下有test.zip 直接访问 http://ip/p/test/test.zip 还是能正常下载无需密码
> 
> https://alist.nn.ci/guide/drivers/common.html#enable-signing

大佬, 请问一下,, 这么设置以后, 访客 http://ip/test/test.zip  需要密码.. 但是 密码怎么输入都不对= = 这个怎么解?

**Comment by zerofo** [comment]
> zerofo


在 master 中 重新编译 release 版本也一样。 
```
Built At: 2023-08-16 14:32:12 +0800
Go Version: go1.20.3 linux/amd64
Author: Xhofe <i@nn.ci>
Commit ID: e9bdb91
Version: 
WebVersion: 3.25.1
```
似乎是这里提示的 密码错误。https://github.com/alist-org/alist/blob/e9bdb91e014decdc238363460e1424548aaab267/server/handles/fsread.go#L247

**Comment by zerofo** [comment]
> > zerofo
> 
> 在 master 中 重新编译 release 版本也一样。
> 
> ```
> Built At: 2023-08-16 14:32:12 +0800
> Go Version: go1.20.3 linux/amd64
> Author: Xhofe <i@nn.ci>
> Commit ID: e9bdb91
> Version: 
> WebVersion: 3.25.1
> ```
> 
> 似乎是这里提示的 密码错误。
> 
> https://github.com/alist-org/alist/blob/e9bdb91e014decdc238363460e1424548aaab267/server/handles/fsread.go#L247
在这里返回了。
https://github.com/alist-org/alist/blob/e9bdb91e014decdc238363460e1424548aaab267/server/common/check.go#L41

**Comment by zerofo** [comment]
> > > zerofo
> > 
> > 
> > 在 master 中 重新编译 release 版本也一样。
> > ```
> > Built At: 2023-08-16 14:32:12 +0800
> > Go Version: go1.20.3 linux/amd64
> > Author: Xhofe <i@nn.ci>
> > Commit ID: e9bdb91
> > Version: 
> > WebVersion: 3.25.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 似乎是这里提示的 密码错误。
> > https://github.com/alist-org/alist/blob/e9bdb91e014decdc238363460e1424548aaab267/server/handles/fsread.go#L247
> 
> 在这里返回了。
> 
> https://github.com/alist-org/alist/blob/e9bdb91e014decdc238363460e1424548aaab267/server/common/check.go#L41

至少在这里 
https://github.com/alist-org/alist/blob/e9bdb91e014decdc238363460e1424548aaab267/server/common/check.go#L37
```
        IsApply(meta.Path, path.Dir(reqPath), meta.HSub) && !(meta.Password == password)){ // the meta should apply to the parent of current path
```
不然密码怎么打都提示不对，不符合逻辑。

**Comment by tomatocuke** [comment]
也可能是： 用户 - 游客 - 无需密码访问
