### ISSUE TITLE
阿里云盘突然挂载不了了context deadline exceeded (Client.Timeout exceeded while awaiting headers)报错

### ISSUE THREAD

**Issue by z953218350** [alist-org/alist#1978]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.3

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

阿里云盘突然挂载不了了，报错：Post "https://api.aliyundrive.com/v2/user/get": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### Reproduction / 复现链接

内网链接

### Logs / 日志

```shell
Post "https://api.aliyundrive.com/v2/user/get": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by z953218350** [comment]
我通过禁用和解除禁用又恢复了，不知道是什么原因

**Comment by Xhofe** [comment]
https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers

**Comment by iris0329** [comment]
> 禁用和解除禁用

@z953218350  可以请问一下 禁用和解除禁用 是什么操作吗

**Comment by WRXinYue** [comment]
关于服务器网络连接问题解决:

* 服务器: 阿里云VPS - 北京
* 部署方式: Docker

## 我的Logs日志如下:
```
2023/06/14 06:28:26.071831 ERROR RESTY Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
2023/06/14 06:28:56.192345 ERROR RESTY Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
2023/06/14 06:29:26.297739 ERROR RESTY Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
2023/06/14 06:29:56.658813 ERROR RESTY Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 4
```

我尝试将Oauth令牌链接替换为`https://api-cf.nn.ci/alist/ali_open/token`成功解决
![image](https://github.com/alist-org/alist/assets/94453358/a5c79317-a9b7-4e7b-94a9-92e585ce6cb8)

**Comment by 1273082756** [comment]
我来补充一下楼上的做法
1.将Oauth改成 "https://api-cf.nn.ci/alist/ali_open/token"
2.打开如下网站, 并选中 "https://api-cf.nn.ci (cf)", 进行扫码获取 "刷新令牌" 
https://alist.nn.ci/tool/aliyundrive/request.html
3.保存即可变正常

**Comment by zhuziyi1989** [comment]
升级v3.18.0 后，这个 api.nn.ci 挂了

阿里云盘OPEN 报错如下：
`状态: Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

1、将原来使用的Oauth令牌链接:
`https://api.nn.ci/alist/ali_open/token`
改成
`https://api-cf.nn.ci/alist/ali_open/token`

2、重新获取令牌

https://alist.nn.ci/tool/aliyundrive/request.html

选域名`api-cf.nn.ci`

进入扫描码获取 "刷新令牌"

恢复正常。
