### ISSUE TITLE
文件夹名称中有符号/ 点开后无法显示文件夹下的文件

### ISSUE THREAD

**Issue by Pmc8090** [alist-org/alist#1979]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.0.2

### Driver used / 使用的存储驱动

阿里云盘分享

### Describe the bug / 问题描述

挂载了阿里云盘分享，发现如果文件夹名称中有斜杠符号/，点开后就无法显示文件夹下的文件，报错failed get objs: failed get dir: failed get parent list: failed get dir: object not found

### Reproduction / 复现链接

阿里云盘分享链接  https://www.aliyundrive.com/s/shog4UJgM2T

**Comment by Pmc8090** [comment]
看了下根本原因还是阿里云盘的问题，在云盘里面新建文件夹的时候，如果名字里面有/，会提示文件夹名称包含不支持的字符，但已建好的文件夹重命名的时候，如果带/，是可以重命名成功的，感觉有点矛盾了，按理说/符号不能用于文件夹名称的，去找阿里云盘反馈了

**Comment by yzqiang666** [comment]
修改 相应的types.go文件：
func fileToObj(f File) *model.ObjThumb {
	return &model.ObjThumb{
		Object: model.Object{
			ID:       f.FileId,
			### **Name:     strings.Replace(f.Name, "/", "♣", -1),**
			Size:     f.Size,
			Modified: f.UpdatedAt,
			IsFolder: f.Type == "folder",
		},
		Thumbnail: model.Thumbnail{Thumbnail: f.Thumbnail},
	}
}

**Comment by Pmc8090** [comment]
> 修改 相应的types.go文件： func fileToObj(f File) *model.ObjThumb { return &model.ObjThumb{ Object: model.Object{ ID: f.FileId, ### **Name: strings.Replace(f.Name, "/", "♣", -1),** Size: f.Size, Modified: f.UpdatedAt, IsFolder: f.Type == "folder", }, Thumbnail: model.Thumbnail{Thumbnail: f.Thumbnail}, } }

请问如果是docker部署的，怎么修改这个文件，谢谢

**Comment by yzqiang666** [comment]
如您已重新编译后，可以用docker exec -it xxxx sh，进入后用编译后的alist覆盖。况且可以用Go交叉编译生成各种平台环境下的版本,何必用docker。

**Comment by mymine** [comment]
> 如您已重新编译后，可以用docker exec -it xxxx sh，进入后用编译后的alist覆盖。况且可以用Go交叉编译生成各种平台环境下的版本,何必用docker。
> […](#)
> 在 2022年10月17日，09:43，Pmc8090 ***@***.***> 写道： 修改 相应的types.go文件： func fileToObj(f File) *model.ObjThumb { return &model.ObjThumb{ Object: model.Object{ ID: f.FileId, ### Name: strings.Replace(f.Name, "/", "♣", -1), Size: f.Size, Modified: f.UpdatedAt, IsFolder: f.Type == "folder", }, Thumbnail: model.Thumbnail{Thumbnail: f.Thumbnail}, } } 请问如果是docker部署的，怎么修改这个文件，谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

修改后编译失败。

**Comment by kettly1260** [comment]
> 修改 相应的types.go文件： func fileToObj(f File) *model.ObjThumb { return &model.ObjThumb{ Object: model.Object{ ID: f.FileId, ### **Name: strings.Replace(f.Name, "/", "♣", -1),** Size: f.Size, Modified: f.UpdatedAt, IsFolder: f.Type == "folder", }, Thumbnail: model.Thumbnail{Thumbnail: f.Thumbnail}, } }

修改后无法正常编译，提示drivers/aliyundrive_share/types.go:44:10: undefined: strings
go version：1.19.3


func fileToObj(f File) *model.ObjThumb {
	return &model.ObjThumb{
		Object: model.Object{
			ID:       f.FileId,
			Name: strings.Replace(f.Name, "/", "♣", -1),
			Size:     f.Size,
			Modified: f.UpdatedAt,
			IsFolder: f.Type == "folder",
		},
		Thumbnail: model.Thumbnail{Thumbnail: f.Thumbnail},
	}
}

**Comment by Pmc8090** [comment]
> > 修改 相应的types.go文件： func fileToObj(f File) *model.ObjThumb { return &model.ObjThumb{ Object: model.Object{ ID: f.FileId, ### **Name: strings.Replace(f.Name, "/", "♣", -1),** Size: f.Size, Modified: f.UpdatedAt, IsFolder: f.Type == "folder", }, Thumbnail: model.Thumbnail{Thumbnail: f.Thumbnail}, } }
> 
> **修改后无法正常编译，提示drivers/aliyundrive_share/types.go:44:10: undefined: strings go version：1.19.3**
> 
> func fileToObj(f File) *model.ObjThumb { return &model.ObjThumb{ Object: model.Object{ ID: f.FileId, Name: strings.Replace(f.Name, "/", "♣", -1), Size: f.Size, Modified: f.UpdatedAt, IsFolder: f.Type == "folder", }, Thumbnail: model.Thumbnail{Thumbnail: f.Thumbnail}, } }

最新版本已经修复了文件夹带斜杠的问题，可以试试
