### ISSUE TITLE
polyfill.io 国内访问速率问题

### ISSUE THREAD

**Issue by Wittoy** [alist-org/alist#1980]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

阿里云提供了polyfill的国内代理，其cdn地址为 [polyfill.alicdn.com](https://polyfill.alicdn.com/polyfill.min.js)

**Comment by zhangnew** [comment]
`后台管理 -> 设置 -> 全局 ->自定义头部` 可以修改
