### ISSUE TITLE
使用官方代理代码设置代理后，百度网盘PDF文件进入不到详情页面

### ISSUE THREAD

**Issue by soultt** [alist-org/alist#1986]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.1.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/13159846/195269782-1bd8330a-5cfb-4d5e-bd6f-2a1dbe5f0029.png)

如图。使用官方代理代理设置代理后，百度网盘PDF文件进入不到详情页面。直接报错：
Fig. After using the official proxy to set up the proxy, the PDF file of Baidu Internet Disk cannot enter the details page. Direct error:

System error: InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### Reproduction / 复现链接

[百度云盘_pdf_Url](https://cloud.yhbsoul.com/%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98/2022%E9%9D%A2%E8%AF%95%E5%A4%A7%E5%85%A8/Java%20%E5%B7%A5%E7%A8%8B%E5%B8%88%E8%BF%9B%E9%98%B6%E7%9F%A5%E8%AF%86%E5%AE%8C%E5%85%A8%E6%89%AB%E7%9B%B2.pdf)

**Comment by Xhofe** [comment]
Reproduction is required.

**Comment by soultt** [comment]
> Reproduction is required.

https://cloud.yhbsoul.com/%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98/2022%E9%9D%A2%E8%AF%95%E5%A4%A7%E5%85%A8/Java%20%E5%B7%A5%E7%A8%8B%E5%B8%88%E8%BF%9B%E9%98%B6%E7%9F%A5%E8%AF%86%E5%AE%8C%E5%85%A8%E6%89%AB%E7%9B%B2.pdf
