### ISSUE TITLE
V3 天翼云盘PC 家庭失效

### ISSUE THREAD

**Issue by dmlt** [alist-org/alist#1987]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.1.0

### Driver used / 使用的存储驱动

天翼云盘PC

### Describe the bug / 问题描述

就是天翼云盘PC 设置家庭后 还是个人盘

![WX20221012-162320@2x](https://user-images.githubusercontent.com/26223986/195290687-3dee3c4b-934c-46bf-b66d-d3ed10365c2d.png)

![WX20221012-162349@2x](https://user-images.githubusercontent.com/26223986/195290668-af5601fc-02b3-43e3-bb9d-0c49a075171d.png)

### Reproduction / 复现链接
无

**Comment by anwen-anyi** [comment]
Family id 吃啦~~(´◔‸◔')”

**Comment by dmlt** [comment]
> 请刷新缓存。。。

ok 刷新缓存 太隐蔽了。。。。
