### ISSUE TITLE
3.0版本可以恢复一键复制全部直链吗？

### ISSUE THREAD

**Issue by zhujitop** [alist-org/alist#2014]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

今天安装好3.0就把2.0版本删了。

然后才发现3.0版本，没有一键复制直链的功能了。

就是一键复制整个文件夹里面全部文件的直链。

网站图片外链非常实用。

### Suggested solution / 实现思路

2.0版本就有这个功能

**Comment by Xhofe** [comment]
右下角更多 -> 开关复选框  -> 全选 -> 中间下部工具栏复制链接

**Comment by zhujitop** [comment]
> 右下角更多 -> 开关复选框 -> 全选 -> 中间下部工具栏复制链接

这个我看了，就是也没有全选的功能啊。

打开这个功能下面出来的功能分别是：
重命名 移动 复制 删除 复制链接(预览页面/下载链接/编码下载链接) 下载(批量下载/打包下载/发送到Aria2)  取消选择

3.2.0版本

https://pic.iqy.ink/i/2022/10/14/634972975ddb1.jpg
