### ISSUE TITLE
有些浏览器js报错

### ISSUE THREAD

**Issue by tsymq-live** [alist-org/alist#2015]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2

### Driver used / 使用的存储驱动

天翼云客户端

### Describe the bug / 问题描述

js错误，用2345浏览器

index.cf9e8205.js:1 Uncaught ReferenceError: globalThis is not defined
    at r (index.cf9e8205.js:1)
    at Go.r (index.cf9e8205.js:1)
    at ip (index.cf9e8205.js:1)
    at index.cf9e8205.js:17
r @ index.cf9e8205.js:1
Go.r @ index.cf9e8205.js:1
ip @ index.cf9e8205.js:1
(anonymous) @ index.cf9e8205.js:17

### Reproduction / 复现链接

可能和chrome版本有关系？

**Comment by Xhofe** [comment]
https://caniuse.com/?search=globalThis

不支持远古浏览器。

**Comment by tsymq-live** [comment]
> https://caniuse.com/?search=globalThis
> 
> 不支持远古浏览器。

好吧 最低支持到71版本，2345浏览器chrome内核是： 69.0.3947.100

**Comment by steinvenic** [comment]
> > https://caniuse.com/?search=globalThis
> > 不支持远古浏览器。
> 
> 好吧 最低支持到71版本，2345浏览器chrome内核是： 69.0.3947.100

幸会遇到了2345勇士，别人跑都来不及
