### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by MicroNeutron** [alist-org/alist#2017]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能够支持城通网盘

**Comment by x4455** [comment]
城通网盘**支持WebDAV**，不需要额外支持。
