### ISSUE TITLE
经过https反代后无法预览视频

### ISSUE THREAD

**Issue by 123485k** [alist-org/alist#2023]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

使用nginx 加上https反代时，视频无法预览
F12发现视频播放器请求的链接协议为http而非https,出现mixed-content错误

### Reproduction / 复现链接

[需要ipv6](https://rec.nana7mi.123485k.ltd:444/21452505-%E4%B8%83%E6%B5%B7Nana7mi/%E5%BD%95%E5%88%B6-21452505-20221001-003015-758-hey.flv)

**Comment by Xhofe** [comment]
It seems to you didn't read the documentation.
> https://alist.nn.ci/config/configuration.html#site-url
