### ISSUE TITLE
希望增加缓存请求限制

### ISSUE THREAD

**Issue by cqash** [alist-org/alist#2025]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我的OneDrive网盘有个文件夹里面有5w张图片，可能是拉缓存时请求太频繁了或者其他原因，被微软封控了的样子
错误代码
failed get objs: failed to list objs: Get "https://graph.microsoft.com/v1.0/me/drive/root:/Pixiv:/children?$expand=thumbnails": read tcp **********:57822->************72:443: read: connection reset by peer

**Comment by cqash** [comment]
这个也是其中一个错误代码
failed get objs: failed to list objs: The request has been throttled

**Comment by Xhofe** [comment]
不要在同一个文件夹下放置过多的文件，因为WebDAV没有分页概念只能一次性请求所有。
