### ISSUE TITLE
期望能添加token管理

### ISSUE THREAD

**Issue by swRains** [alist-org/alist#2026]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

可否添加一个token管理功能，批量更新token，将不同token的链接分组。而不是一个个点开去更新，这种挺麻烦的。
或者加个账号密码登陆。并且将存储管理界面改成表，失效的链接能加个状态灯或归为一组，而非卡片显示或许对于管理者会更加一目了然。
毕竟单个账号的存储空间有限，很有可能存几下就满了。
alist非常好用，是我用过的最好颜值最高的网盘聚合工具，作者辛苦了，期望开发者大大能实现以上功能，非常感谢！

**Comment by Xhofe** [comment]
说实话 我没看懂你在说什么。

**Comment by swRains** [comment]
> 说实话 我没看懂你在说什么。
开发者您好，费了点时间做了个后台管理存储页面的简陋的构想图。
我的设想是能够只修改图中**红框**内的token，即可更新下列使用该token的挂载
做成图示的列表的形式相较于目前的卡片形式或许会更直观些
![image](https://user-images.githubusercontent.com/96161478/196037533-f3a70279-fb3e-4f5c-993e-30a0fb362a03.png)
[构想.xlsx](https://github.com/alist-org/alist/files/9794607/default.xlsx)
