### ISSUE TITLE
建议：设置游客访问网站显示的默认语言

### ISSUE THREAD

**Issue by SerendipityR-2022** [alist-org/alist#2030]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能够在后端设置游客访问网站显示的默认语言，而不是直接默认为英语。

**Comment by Xhofe** [comment]
并没有默认为英语，默认是检测浏览器设置的语言，我觉得这是合理的。

**Comment by SerendipityR-2022** [comment]
> 并没有默认为英语，默认是检测浏览器设置的语言，我觉得这是合理的。

好的，感谢答复。
刚刚测试了一下，发现浏览器的语言为中文，而不是中文（简体），可能因此并没有检测到所设置的语言。
