### ISSUE TITLE
123盘挂赞失败

### ISSUE THREAD

**Issue by laoqijun** [alist-org/alist#2032]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.0

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

挂载后提示failed get objs: failed to list objs: json: cannot unmarshal string into Go struct field Files.code of type int

### Reproduction / 复现链接

https://alist.xn--vzyr4p.top/123%E7%9B%98

**Comment by Xhofe** [comment]
123限制了请求频率 无解。
