### ISSUE TITLE
成功设置aria2后，aria2下载仍使用默认配置

### ISSUE THREAD

**Issue by john5du** [alist-org/alist#2041]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.2.0

### Driver used / 使用的存储驱动

阿里云盘，夸克网盘

### Describe the bug / 问题描述

在设置页面成功配置aira2
![屏幕截图 2022-10-17 103907](https://user-images.githubusercontent.com/45614150/196077591-4f272814-3f5b-4467-af19-74e543203bf4.png)
在文件列表中选择发送到aira2，未使用已经配置的设置。
![image](https://user-images.githubusercontent.com/45614150/196077725-ed3bf47e-9f7c-4839-9910-35f56e6f1e1e.png)
![image](https://user-images.githubusercontent.com/45614150/196077682-ae2aed0c-cb4d-44e4-80f7-92d28d592a37.png)

### Reproduction / 复现链接

http://localhost:6800/jsonrpc

**Comment by Xhofe** [comment]
你设置的是用于离线下载的aria2，发送到aria2处的aria2设置位于本地设置中。

**Comment by john5du** [comment]
我也看了配置文件啊 没有相关的配置啊 
![image](https://user-images.githubusercontent.com/45614150/196099888-26c4031c-428b-4546-b45a-f19dc6aceb9a.png)

所以以为是这个

**Comment by john5du** [comment]
![image](https://user-images.githubusercontent.com/45614150/196102087-6fc03799-d762-4203-a9fa-82580c6ae871.png)
找到入口了 感谢解答
