### ISSUE TITLE
希望能新增时光相册

### ISSUE THREAD

**Issue by Meteorsss** [alist-org/alist#2042]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能新增时光相册

**Comment by mohui1999** [comment]
支持支持
