### ISSUE TITLE
开启了双从认证，无法关闭，手机丢了，无法登录了

### ISSUE THREAD

**Issue by non-trace** [alist-org/alist#2051]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

开启了双从认证，无法关闭，手机丢了，无法登录了

### Reproduction / 复现链接

本地环境部署

**Comment by Xhofe** [comment]
duplicate with #1795
