### ISSUE TITLE
在设置下载代理后，批量选择发送到aria还是源地址，而不是代理后的地址

### ISSUE THREAD

**Issue by invoker-kael** [alist-org/alist#2059]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3

### Driver used / 使用的存储驱动

All

### Describe the bug / 问题描述

在设置下载代理后，批量选择发送到aria还是源地址，而不是代理后的地址

### Reproduction / 复现链接

比如
挂载了google，设置了下载代理url
https://download.qq.com

使用idm下载会显示从https://download.qq.com
下载，但是发送到aria，aria的下载地址还是https://alist.qq.com/d/path/file.ext

**Comment by invoker-kael** [comment]
比如
alist地址是https://alist.qq.com

挂载了google，设置了下载代理url
https://download.qq.com

使用idm下载会显示从https://download.qq.com/path/file.ext
下载
但是发送到aria，aria的下载地址还是https://alist.qq.com/d/path/file.ext

**Comment by Xhofe** [comment]
302
