### ISSUE TITLE
v3版本手机访问时readme.md显示报错failed to fetch

### ISSUE THREAD

**Issue by qq80284445** [alist-org/alist#2081]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

Failed to fetch http://xxx.com/readme.md: TypeError: s.data.text is not a function. (In 's.data.text()', 's.data.text' is undefined)

### Reproduction / 复现链接

用手机浏览器访问 https://pan.sztcrs.com/index 下面本该显示的readme.md 会出现错误 
Failed to fetch http://xxx.com/readme.md: TypeError: s.data.text is not a function. (In 's.data.text()', 's.data.text' is undefined)

**Comment by Xhofe** [comment]
![Screenshot_20221022_144706](https://user-images.githubusercontent.com/36558727/197324811-2ce44a34-3863-4855-aff6-2510a5e52804.jpg)
