### ISSUE TITLE
Unable to preview PDF file

### ISSUE THREAD

**Issue by flashliao** [alist-org/alist#2082]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.1.0

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

Unable to preview PDF file.
v3.1.0 has no API adress setting. 
please tell me how to do.

### Reproduction / 复现链接

Hope your demo link is back online so that I'm able to reproduce and provide the link.

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/preview.html#iframe-previews
