### ISSUE TITLE
新增readme在文件栏上方或下方按钮

### ISSUE THREAD

**Issue by HuYihe2008** [alist-org/alist#2090]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

想在样式管理中添加README显示在文件栏上方或在下方的功能按钮

### Suggested solution / 实现思路

管理=》设置=》样式=》README显示位置：上方  ：下方

**Comment by drw2005** [comment]
支持这个建议。。。
