### ISSUE TITLE
希望能夠增加禁止遊客訪問功能

### ISSUE THREAD

**Issue by kasnre** [alist-org/alist#2091]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

guest能夠指定根目錄，但目前v3無法設置遊客目錄
使得有時個人文件共享管理較為不便

隱藏文件夾也是只要知道正確名稱就能用網址訪問
使得權限管理不足

### Suggested solution / 实现思路

增加禁止遊客訪問的選項，強制登入使用
或是在用戶設定中添加訪客的基本路徑設置

**Comment by Xhofe** [comment]
guest不就是访客 你在说什么

**Comment by kasnre** [comment]
> guest不就是访客 你在说什么
我原本也是這樣理解，但目前3.2.1編輯guest基本路徑
只有在登入頁面使用guest登入才會在設定後的路徑
可新開無痕頁面直接遊客訪問一樣會在根目錄(root)

但剛剛重啟後，卻重現不了BUG
待我重現後再截圖補充

**Comment by anwen-anyi** [comment]
尝试把访客登录的按钮直接干掉呢?
没有了按钮就点不进来了吧?
