### ISSUE TITLE
没有ipv6网络下报错

### ISSUE THREAD

**Issue by ta1994** [alist-org/alist#2092]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1

### Driver used / 使用的存储驱动

所有

### Describe the bug / 问题描述

在只有ipv4没有ipv6的网络下，报错

### Reproduction / 复现链接

no

### Logs / 日志

```shell
2022/10/22 08:57:46.902539 ERROR RESTY Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2408:4001:1000::4]:443: connect: network is unreachable, Attempt 2
2022/10/22 08:57:47.068708 ERROR RESTY Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2408:4001:1000::4]:443: connect: network is unreachable, Attempt 3
2022/10/22 08:57:47.372123 ERROR RESTY Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2408:4001:1000::4]:443: connect: network is unreachable, Attempt 4
```

**Comment by Xhofe** [comment]
This is due to the issue of you network instead of alist. Check your dns config.
