### ISSUE TITLE
非常希望对SMB协议的支持

### ISSUE THREAD

**Issue by temurlee** [alist-org/alist#2093]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

除了可通过网盘资源做影音库，同时希望也将SMB协议的内容一起导入

**Comment by BoYanZh** [comment]
现在可以考虑通过`mount -t cifs`来先把smb mount到local然后用local storage，但我现在mount后无法在alist里看到local storage里mount的smb路径内的内容

**Comment by temurlee** [comment]
> 

感谢提供思路

**Comment by Looong01** [comment]
这个指的是可以直接在Windows文件资源管理器里添加映射网络驱动器吗？
