### ISSUE TITLE
V3 aria2 离线下载 + 自动转储 能不能加2个功能? 【预设重命名】【转储成功后删除本地文件】

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#2094]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

实验了下 aria2 离线下载，其实docker部署aria2，本地部署alist，只要目录映射+权限正确，是可以工作的，并不需要2个都安装在同一docker...主要alist装在docker 定时更新 咱不会啊... 每次还要重新配置挂载网盘账号这些 写sh感觉好难...

正题: 
浏览器F12 发现 web api 只是提交了 远程需要下载的url给后端alist, 然后alist 调用 aria2 ，

1. 成功转储了文件之后，本地文件是保留的，可惜服务器就20G空间, 不够用啊。所以 => 能不能加个 【转储成功后删除本地文件】true/false

2: api 提供远程下载url的时候可否加一个功能【预设重命名】比如下载的文件是ABC.zip, 而我想转储蓄的时候 自定义一个新的名字 如 2022-BBC.zip。=> 【预设重命名】

### Suggested solution / 实现思路

看大神如何操作... 前端提交的 urls 是个array.. 能不能改成
jobs: [ 
 { 
  download_url: https://XXX.zip, 
  re_name:'BBB.ZIP',  //下载成功后，转储网盘的时候 重命名  "" -> 空 str 则=不重命名
  auto_del_localfile:true/false //自动删除本地文件
}
]

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/blob/a2c808c8ce4360e4050a9a2ceddf2ed8c8fd14d1/internal/aria2/monitor.go#L139

上传完是自动删除的啊

**Comment by gowy222** [comment]
docker run -d \
    --name aria2-pro \
    --privileged=true \ # 关闭安全权限，否则你容器操作文件夹没有权限
    中间配置忽略...
    -v /opt/alist/data/temp/aria2:/opt/alist/data/temp/aria2 \  #目录映射
    p3terx/aria2-pro 

以上aria2 装在docker，可以工作。权限我直接给的755..结果转储完成 本地文件都还在..

**Comment by gowy222** [comment]
> https://github.com/alist-org/alist/blob/a2c808c8ce4360e4050a9a2ceddf2ed8c8fd14d1/internal/aria2/monitor.go#L139
> 
> 上传完是自动删除的啊

是我看错了... 残留的文件是 aria2那边之前下载失败的，重启服务之后，又自动下载下来了...罪过

**Comment by gowy222** [comment]
【预设重命名】 这个有没有机会实现呢?

**Comment by monsterxcn** [comment]
预设重命名是什么？你是否在找 Aria2 的 [`--out=<FILE>`](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-o)
