### ISSUE TITLE
预览文件给定参数中增加由Alist代理的预览参数

### ISSUE THREAD

**Issue by liheji** [alist-org/alist#2095]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

预览参数中的 **$url: the file url** 仅为由Alist转化为网盘直链之后的 URL，而不是由Alist代理的URL
大部分云盘的直链预览会由于 cross-origin 被浏览器终止
因此希望增加由Alist代理的预览参数（即下图2中点击复制的，由Alist代理的链接）

### Suggested solution / 实现思路

暂无

### Additional context / 附件

![image](https://user-images.githubusercontent.com/56494145/197401948-6db1a58f-9ddb-47f2-9903-59f4e8e1105a.png)
![image](https://user-images.githubusercontent.com/56494145/197402075-a693b617-8456-42e7-be84-30b5a0e52921.png)

**Comment by Xhofe** [comment]
你可以打开web proxy使得$url为代理链接。

**Comment by liheji** [comment]
感谢

> 你可以打开web proxy$url为代理链接。
