### ISSUE TITLE
阿里云盘文件下载失败

### ISSUE THREAD

**Issue by NianBroken** [alist-org/alist#2096]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

阿里云盘文件下载失败

能上传，能查看，能删除，但就是无法下载
![Screenshot_2022-10-24-08-48-05-259_mark via](https://user-images.githubusercontent.com/57057288/197427386-229bc6dc-4ea1-4f12-8cd0-60a3dee8be21.jpg)

### Reproduction / 复现链接

无

### Logs / 日志

```shell
无
```

**Comment by Xhofe** [comment]
it's due to your browser. some browser auto add referer header while download.

**Comment by Ssiswent** [comment]
老哥，你好，我也是alist挂载的阿里云盘，但是我的下载直链是这种格式，和你的不一样，请问是我哪里没设置对吗
`http://pan.happaa.com/p/%E6%89%98%E7%AE%A1/Ssiswent/Mac%E5%A4%87%E4%BB%BD/Ssiswent%E7%9A%84%E8%AF%8D%E5%BA%93.scel?sign=8SZbvTMQCblsZdB-CwNrrIT-5HjueeF3GHQ7pLflzxg=:0`
<img width="322" alt="image" src="https://user-images.githubusercontent.com/37449310/206721616-34a84a79-6332-41fc-a8ad-9f04536e3129.png">

**Comment by muziyinlee** [comment]
请问，所以最后怎么解决的啊？同样的情况，困扰我很久了！！这提问全是bot自动关闭！

**Comment by londbell** [comment]
你使用的是VIA浏览器吧？
