### ISSUE TITLE
开通夸克会员下载速度没有提升

### ISSUE THREAD

**Issue by gmshiwoge** [alist-org/alist#2097]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

夸克开了会员，webdav下载，仍旧限速2M

**Comment by youtehub** [comment]
尝试过，似乎夸克云盘本身限速

**Comment by Xhofe** [comment]
the download speed of quark depends on your server.
