### ISSUE TITLE
 V3 版本 err: [Error: ENAMETOOLONG: name too long, 文件名太长? 上传遇到一个文件名全中文40个文字的.pdf

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#2098]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

189

### Describe the bug / 问题描述

err: [Error: ENAMETOOLONG: name too long, open '/node/app/Alist/tmp/***
上传遇到一个文件名全中文40个文字的.pdf (我也是第一次遇到...真有人给文件这么起名...醉了)
所以: 请问 Alist 内部 逻辑 文件名 最长是多长 .length? 我这边配合 修改下我自己业务逻辑代码..来阶段文件名

### Reproduction / 复现链接

暂时不提供

### Logs / 日志

```shell
err: [Error: ENAMETOOLONG: name too long, open '/node/app/Alist/tmp/***
```

**Comment by Xhofe** [comment]
这是你使用的存储的限制 alist并没有限制文件名长度。

**Comment by gowy222** [comment]
> 这是你使用的存储的限制 alist并没有限制文件名长度。

好的，谢谢
