### ISSUE TITLE
正则表达式中的 `^` 不工作

### ISSUE THREAD

**Issue by Clansty** [alist-org/alist#2101]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.2.1

### Driver used / 使用的存储驱动

任意

### Describe the bug / 问题描述

正则表达式中的 `^` 无法工作，即匹配文件名的开头

### Reproduction / 复现链接

在全局设置的隐藏文件中添加 `/^\./` 来隐藏 `.` 开头的文件，不工作

若使用 `/\..*`，则所有带 `.` 的文件全都会隐藏

### Logs / 日志

```shell
无
```

**Comment by Xhofe** [comment]
全局设置的隐藏文件中的正则表达式test的是文件的全部路径，要隐藏所有.开头的文件：
```typescript
/\/\./i
```

**Comment by Clansty** [comment]
哦这样啊，谢谢

**Comment by paowan2** [comment]
> 全局设置的隐藏文件中的正则表达式test的是文件的全部路径，要隐藏所有.开头的文件：
> 
> ```ts
> /\/\./i
> ```

这样写有没有问题
