### ISSUE TITLE
SMB共享功能，可将alist 映射为windows的驱动器使用

### ISSUE THREAD

**Issue by nokaka** [alist-org/alist#2106]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

![image](https://user-images.githubusercontent.com/101942715/197659014-48a6290b-6381-4a50-b249-0047733a7053.png)
类似于nas 的smb共享功能，可将alist 映射为windows的驱动器使用。
![image](https://user-images.githubusercontent.com/101942715/197659152-aaade828-ec3a-42d5-98d5-3418d4ba82e1.png)
emby、jellyfin也支持smb协议，这样无需rclone就可直接挂载。

**Comment by temurlee** [comment]
强烈支持

**Comment by BoYanZh** [comment]
go上没有现成的smb server，估计非常难做，如果只要挂载成网络磁盘那可以从rclone那里把这个功能抄过来

**Comment by msycn** [comment]
强烈支持,愿意捐助 @Xhofe

**Comment by youtehub** [comment]
我现在就是使用rclone挂载成为网络硬盘的很方便，如果大佬能够直接在程序中实现就更好了，这个rclone软件非常好用，平时都是命令行启动自动挂载，后期也会补上捐赠 @Xhofe

**Comment by 12189108** [comment]
其实windows可以直接挂WebDav的

**Comment by 12189108** [comment]
其实windows可以直接挂WebDav的，不需要任何第三方软件

**Comment by youtehub** [comment]
Windows原生的资源管理器对Webdav支持残缺不全，甚至不支持显示容量，对文件大小也有极大限制。如果常用建议换别的软件替代。

**Comment by nokaka** [comment]
> 其实windows可以直接挂WebDav的，不需要任何第三方软件

webdav会把数据从c盘过一遍，固态硬盘小命呜呼。smb可以直接走

**Comment by sunny-00001** [comment]
3.3版本增加的SMB怎么用啊，希望更新一下说明文档。地址里面要求必须填写端口号，填写之后就报错，在资源管理器中可以读取的地址在alist中就报错。原谅我不会用。

**Comment by iancsy** [comment]
很需要这个功能…有些坑爹播放器只能识别smb共享，不支持webdav

**Comment by lp1018** [comment]
> 3.3版本增加的SMB怎么用啊，希望更新一下说明文档。地址里面要求必须填写端口号，填写之后就报错，在资源管理器中可以读取的地址在alist中就报错。原谅我不会用。

我也是提示缺少端口号,但是不知道怎么填,有结果了希望同步下

**Comment by leungzw** [comment]
Raidrive可以曲线救国

**Comment by simon-ding** [comment]
提供fuse挂载我感觉更好一些。像rclone那边一样

**Comment by holger2138** [comment]
确实，Windows 原生资源处理器 I/O 爆卡，会把整个视频 down 下来

**Comment by wowdd1** [comment]
+1

**Comment by corvofeng** [comment]
希望支持~

**Comment by bootli** [comment]
可以加nfs/samba，像Rclone那种挂载， 然后加上用量/容量显示，更完美了

**Comment by shadowofgost** [comment]
+1 可以加nfs/samba，像Rclone那种挂载， 然后加上用量/容量显示，更完美了

**Comment by zhi42live** [comment]
bug , smb 用户域不能指定。用 域\用户名 或 用户名@域 都不成功。

**Comment by StartMoney** [comment]
希望支持。有旧设备电视不支持webdav只支持smb的非常需要。

**Comment by verydemo** [comment]
我现在就是先rclone 挂载成本地磁盘， 然后再共享出smb 服务，曲线救国，   很多软件不支持webdav,  绝大多数设备都是支持smb的， 希望支持smb 共享出来

**Comment by christan-duplicate** [comment]
> 我现在就是先rclone 挂载成本地磁盘， 然后再共享出smb 服务，曲线救国， 很多软件不支持webdav, 绝大多数设备都是支持smb的， 希望支持smb 共享出来

为什么我用rclone挂载成本地磁盘后，不能共享smb呢？提示不能共享，找不到
![image](https://github.com/user-attachments/assets/82a737a6-e589-46f1-b4fb-da55d8319283)

**Comment by oldsento** [comment]
现在支持了没有？或者有没有其他方法？主要是想手机上用
