### ISSUE TITLE
能否支持便携版本？

### ISSUE THREAD

**Issue by niheaven** [alist-org/alist#2108]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在Windows上安装时，数据目录和日志目录默认到了`$env:USERPROFILE`，能否考虑首先检查应用程序本地目录，如果在本地有data目录的话把所有文件都放在本地以便完全便携？

主要是我在给Scoop写Manifest的时候，希望能够persist所有程序数据，而不是管理到目录外面。

或者能提供一个portable的开关也行。

**Comment by Xhofe** [comment]
默认的数据和日志目录都在执行文件同级目录下。
`$env:USERPROFILE`是哪里得出的？？

**Comment by niheaven** [comment]
在Windows环境下，运行`alist admin`会自动生成配置文件，放在了用户主目录下面，也就是`C:\Users\xxx`.

**Comment by Xhofe** [comment]
这只是取决于你在那个目录运行程序。

**Comment by niheaven** [comment]
OK，也即是我必须在alist.exe的目录运行，才会生成在当前目录是吧？这一特征能否通过开关控制？就是强制读取alist.exe目录的配置文件。

**Comment by Xhofe** [comment]
不能。

**Comment by niheaven** [comment]
呃，所以我才提Feature request而不是Bug……

**Comment by Xhofe** [comment]
cd到程序所在目录并不困难

**Comment by Xhofe** [comment]
或者你也可以通过`--conf path`指定要加载的配置路径，其他使用到的路径都定义在指定的配置文件中。

默认值都为执行程序时的路径的相对路径。

**Comment by niheaven** [comment]
要不我先介绍下背景。Scoop上有人提[Request](https://github.com/ScoopInstaller/Main/issues/4059)加入alist，但是Scoop的app启动方式（通过shim代理）把启动目录放在了用户目录，就导致data没办法被永久保留，只能通过指定conf文件并事先修改的方式强制alist数据放在保留目录。这样也不是不能实现，我已经写了[manifest](https://github.com/ScoopInstaller/Main/pull/4060)，但感觉不是很方便，尤其是如果用户需要指定其他的配置文件时。

当然，如果用了开关控制便携版，在参数这边也会有冲突……

**Comment by Xhofe** [comment]
所以还是需要加入一个arg强制使用程序所在的目录作为数据目录？

**Comment by niheaven** [comment]
非常感谢！另外，现在已经可以通过 Scoop 来安装 alist 了，`scoop install alist`，待 https://github.com/alist-org/alist/commit/1c212f6c304769fd7407b94cd1ea64797c6d5a14 发布后会更改 Manifest。

**Comment by Xhofe** [comment]
不客气 已发布[v3.3.0](https://github.com/alist-org/alist/releases/tag/v3.3.0)，可通过`--force-bin-dir`参数强制使用二进制文件所在文件夹作为数据目录，同时日志目录也移至data文件夹内部。
