### ISSUE TITLE
强烈建议大佬增添对115网盘的支持，cookies登录模式也可

### ISSUE THREAD

**Issue by isChengshi** [alist-org/alist#2112]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

强烈建议大佬增添对115网盘的支持，cookies登录模式也可

空间大，速度快，是存储的不二之选了，翻了好久的帖子，发现不少重复115诉求的帖子，看到去年大佬回复的暂无计划支持，心拔凉拔凉的，但还是想再请求一下，Alist太好使了，希望能做到只用这一款工具，不用多工具协同，那样出的问题太多了。

**Comment by SheltonZhu** [comment]
我在搞，但是现在不支持200MB以上大文件上传

**Comment by isChengshi** [comment]
> 我在搞，但是现在不支持200MB以上大文件上传

强烈支持，包括sha1的上传机制，可以参考

**Comment by SheltonZhu** [comment]
感觉115的api很容易变动 并且只能用代理模式 
有点不适合合并进来，等大文件上传实现了，看看大佬到时候怎么说吧

今天刚找到一个大文件上传的实现，需要花点时间读源码。如果想先体验下可以用我那个分支试一试

**Comment by stb1238921** [comment]
200M这个问题是不是跟浏览器登录的有关？我用Chrome浏览器登录115网盘，提示上传文件不能大于200M。用客户端APP就没问题
![mmexport1666778824937](https://user-images.githubusercontent.com/8872664/197999012-6f22a399-d524-4e69-a5a3-65ef7c9c693c.png)

**Comment by SheltonZhu** [comment]
是的，并且115自家的app对请求体和响应响应体进行了加密

**Comment by isChengshi** [comment]
> 

抓包 APP的cookies，有效期一年，网页版的太容易失效了，或者用115浏览器导出的cookies替换三值就可以，很稳定

**Comment by ueser1-bit** [comment]
怎么抓包APP的cookies啊？

**Comment by SheltonZhu** [comment]
需要格外的软件，我是用的QuantumultX抓的ios 115

**Comment by SheltonZhu** [comment]
> 不好用 会提示重复登录 115-webdav那个库就没这个问题

建议等更新，万一修复了呢？115-webdav不能上传呀。XD

**Comment by brucmao** [comment]
> 需要格外的软件，我是用的QuantumultX抓的ios 115

怎么用quanx抓115的cookie呢，找到一个[quanx获取cookie](https://raw.githubusercontent.com/w37fhy/QuantumultX/master/js_cookie.conf)的订阅都失效了

**Comment by brucmao** [comment]
ios 换 stream抓到了
