### ISSUE TITLE
网页错误，无法播放百度网盘里面的视频

### ISSUE THREAD

**Issue by shadowofgost** [alist-org/alist#2125]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.2.1

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

在网页上无法播放百度网盘的视频

### Reproduction / 复现链接

http://101.132.135.180:5244/
账户：test
密码：1234

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E8%83%BD%E9%A2%84%E8%A7%88%E8%A7%86%E9%A2%91%E6%88%96%E9%9F%B3%E9%A2%91%E6%96%87%E4%BB%B6

**Comment by shadowofgost** [comment]
> 提醒一下，你的网盘个人资料要被看光了，建议设置游客权限

?不是设置了 权限嘛，只能看到那个主页的文件，那个文件就是美剧啊

**Comment by Beurling** [comment]
> > 提醒一下，你的网盘个人资料要被看光了，建议设置游客权限
> 
> ?不是设置了 权限嘛，只能看到那个主页的文件，那个文件就是美剧啊

可以看到，你快点重新设置！

**Comment by asong2022** [comment]
http://101.132.135.180:5244/
账户：test
密码：1234
这个是怎么设置的呀，为什么我也可以浏览
