### ISSUE TITLE
点击下载出现错误  failed get link

### ISSUE THREAD

**Issue by lumineyuri** [alist-org/alist#2133]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

最新DEV

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

无法下载 点进文件预览提示
failed get link: json: cannot unmarshal string into Go struct field DownResp.code of type int

### Reproduction / 复现链接

https://minas.mihoyo.today/Lumine/%E5%8D%A1%E5%B7%B4%E6%96%AF%E5%9F%BA%E8%87%AA%E5%AE%9A%E4%B9%89%E8%83%8C%E6%99%AF/%E9%87%91%E5%B1%B1%E5%A8%98NTR%E5%8D%A1%E5%B7%B4%E6%96%AF%E5%9F%BA%EF%BC%88Q%E7%89%88%EF%BC%89.zip
https://minas.mihoyo.today/Lumine/%E5%8D%A1%E5%B7%B4%E6%96%AF%E5%9F%BA%E8%87%AA%E5%AE%9A%E4%B9%89%E8%83%8C%E6%99%AF

### Logs / 日志

```shell
ERROR RESTY json: cannot unmarshal string into Go struct field DownResp.code of type int, Attempt 1
```

**Comment by Xhofe** [comment]
请求超限了
