### ISSUE TITLE
非标准端口的Alist服务器无法通过CF worker进行下载

### ISSUE THREAD

**Issue by foxdodo** [alist-org/alist#2136]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

使用非标准端口搭建的Alist服务器`https://example.com:6666`, 在通过CF worker下载代理访问时CF会返回prohibit ip错误. 
另外一台有开放80端口的Alist服务器则可正常使用下载代理, 请问有可能让 https://github.com/alist-org/alist-proxy/blob/main/alist-proxy.js 也支持非标准端口的服务器吗?

### Reproduction / 复现链接

https://example.com:6666

**Comment by Xhofe** [comment]
这是cf的限制 你可以问问他们的客服
