### ISSUE TITLE
aria2离线下载文件变小了

### ISSUE THREAD

**Issue by whistle003** [alist-org/alist#2137]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

aria2离线下载文件变小了，从阿里云推送的一季电视剧，视频文件3G左右的会变成一百多k这样。

### Reproduction / 复现链接

<img width="995" alt="image" src="https://user-images.githubusercontent.com/64147479/198269538-f9775862-0a94-44bc-8baa-9c955f9955bf.png">
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/64147479/198269604-f2b69838-1fd3-453a-a7b2-141bf5083d67.png">

### Logs / 日志
[31mERRO[0m[2022-10-27 10:16:12] failed link /root/电影/追更/追更美剧/闪电侠 (2014)/The.Flash.2014.S05.1080p.BluRay.x264-ROVERS/The.Flash.2014.S05E09.1080p.BluRay.x264-ROVERS.mkv: Post "https://api.aliyundrive.com/v2/file/get_download_url": read tcp 10.182.0.3:54534->47.92.21.245:443: read: connection reset by peer
failed get link

**Comment by whistle003** [comment]
> ### See
> 1. 64% [Aria2下载文件失败 #1857](https://github.com/alist-org/alist/issues/1857)
> 2. 50% [对接aria2离线下载出错 #1887](https://github.com/alist-org/alist/issues/1887)

已补充日志

**Comment by Xhofe** [comment]
its due to network
