### ISSUE TITLE
挂载路径设置为 /dav 会和webDAV 路由冲突

### ISSUE THREAD

**Issue by SheltonZhu** [alist-org/alist#2139]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1

### Driver used / 使用的存储驱动

any

### Describe the bug / 问题描述

挂载路径设置为 /dav 会和 webDAV 路由冲突

在 `http://ip:port/dav` 页面刷新会进入到webDAV 的认证

建议：限制挂载路径不能为冲突的路由？

![企业微信截图_16669344378022](https://user-images.githubusercontent.com/26734784/198509117-42e86c90-c26c-4f60-9bfa-da6906d5e094.png)

### Reproduction / 复现链接

1.配置任意存储
2.挂载路径填写 `/dav`
3.访问 `http://ip:port/dav `

**Comment by Xhofe** [comment]
保留路径：
- /dav
- /d
- /d
- /api

不要使用这谢作为挂载路径。
