### ISSUE TITLE
Aria2添加下载总是失败

### ISSUE THREAD

**Issue by iceman0142** [alist-org/alist#2141]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1

### Driver used / 使用的存储驱动

本地磁盘

### Describe the bug / 问题描述

我是在路由器上部署的alist，padavan系统安装了opt环境，磁盘用的是ext4格式，aria2之前可以正常工作。
在用aria2添加下载的时候出现错误"下载出错 Aria2 无法创建文件夹"，我在windows系统上安装了aria2连接后就可以正常下载，不知道是对系统环境还是文件格式的支持有问题。

### Reproduction / 复现链接

无

### Logs / 日志

```shell
[31mERRO[0m[2022-10-28 07:04:14] error [failed to download e21451e8e07992ce, error: Download aborted.
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Update
	/home/runner/work/alist/alist/internal/aria2/monitor.go:107
github.com/alist-org/alist/v3/internal/aria2.(*Monitor).Loop
	/home/runner/work/alist/alist/internal/aria2/monitor.go:49
github.com/alist-org/alist/v3/internal/aria2.AddURI.func1
	/home/runner/work/alist/alist/internal/aria2/add.go:57
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:75
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/asm_mipsx.s:617] while run task [download https://down.360safe.com/setupbeta_jisu.exe to [/本地存储](/media/AiDisk_a1/Share/Downloads)]
```

**Comment by Xhofe** [comment]
it's due to aria2
