### ISSUE TITLE
安装后openwrt路由器丢失终端命令菜单，重启功能失效

### ISSUE THREAD

**Issue by master-yun-yun** [alist-org/alist#2157]
![alist-3 2 1png](https://user-images.githubusercontent.com/79097488/198886421-9b0dddbf-8161-46b4-8ec0-264480b4296d.png)
手动安装的， glibc 版本太低，下载 的musl 版本。能正常运行
但是导致路由器里自带的终端（就是自带的类似putty的工具）菜单丢失
另外，重启命令也失效了，点重启不再重启
不知道什么情况
请达人看看
谢谢

**Comment by master-yun-yun** [comment]
![固件版本](https://user-images.githubusercontent.com/79097488/198886758-a7184175-ed6f-4070-89e0-9fb61d21619a.png)

**Comment by Becods** [comment]
![CM6PHS7AGGJPN31Y2DI83MS](https://user-images.githubusercontent.com/35525491/201261596-4bb2d949-57c2-4054-90fa-5905874e079e.png)

**Comment by leungzw** [comment]
让它好好当个路由吧。随便换个x86性能都比它强

**Comment by chengnan049** [comment]
https://supes.top/ 尝试在此处编译新固件
