### ISSUE TITLE
在安卓系统下无法运行,提示找不到文件或目录

### ISSUE THREAD

**Issue by flytkgl** [alist-org/alist#2161]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3

### Driver used / 使用的存储驱动

不适用

### Describe the bug / 问题描述

在安卓系统下无法运行,提示找不到文件或目录

# ./alist server
/system/bin/sh: ./alist: No such file or directory

### Reproduction / 复现链接

不适用

**Comment by 12189108** [comment]
可以尝试用Termux的proot-distro安装ubuntu或其他系统后运行

**Comment by flytkgl** [comment]
> 请给出更多的日志，还有，alist好像不能在Android下直接运行请用linuxdeploy或Termux 或者你尝试一下 `chmod +x alist`

没有更多日志,一运行就直接提示`/system/bin/sh: ./alist: No such file or directory`  然后就没了,就类似sh脚本用了Windows的换行符的情况

**Comment by flytkgl** [comment]
> 可以尝试用Termux的proot-distro安装ubuntu或其他系统后运行

我尝试了复制到Termux下运行(没有安装Ubuntu或其他系统)也是提示`/system/bin/sh: ./alist: No such file or directory`,感觉真的很像是用了Windows的换行符

**Comment by Xhofe** [comment]
仅保证在通用Linux系统上（不包含Android）可用，且prebuilt也都是在桌面端Linux编译。

Android请自行编译/研究。

**Comment by Triwind** [comment]
termux下直接pkg i alist就可以安装使用了啊
