### ISSUE TITLE
配置文件能否支持导入导出

### ISSUE THREAD

**Issue by gzxiexl** [alist-org/alist#2165]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

最近我把docker版本alist迁移到群晖app版了，存储重新一个一个添加实在痛苦了，如可以支持导出再导入就方便多了

**Comment by Xhofe** [comment]
直接复制data文件即可。

**Comment by horse-world** [comment]
ok, i will try

**Comment by horse-world** [comment]
> ok, i will try

i copy the dir 'alist-windows-4.0-amd64', it doesn't work

**Comment by horse-world** [comment]
> > ok, i will try
> 
> i copy the dir 'alist-windows-4.0-amd64', it doesn't work

well, i think i know someething, if create shortcut, it will find data file in the cmd-dir not in where alist put.

**Comment by BoYanZh** [comment]
> Maybe this commit have done. [alist-org/alist-web@3ba8fe1](https://github.com/alist-org/alist-web/commit/3ba8fe1f96e03bcc5bcc1d25ac2a09d2190d967e)

The issues can be closed.
