### ISSUE TITLE
不同网盘之间使用rclone 复制时多一层目录

### ISSUE THREAD

**Issue by 9k001** [alist-org/alist#2171]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v2 v3版本均有

### Driver used / 使用的存储驱动

centos

### Describe the bug / 问题描述

version: v3.2.1
问题:
使用alist挂载网盘,不同网盘之间使用 rclone 进行同步,对应文件在同步时，会多创建一层 以文件名为名的 文件夹。不知道这个问题怎么解决。
即
a挂载 (源数据)
目录下有 aa.txt ab.txt ac.txt 。
b挂载 (备份)
rclone 设置 webdav config 文件
使用
rclone copy webdav:a webdav:b 或 rclone sync webdav:a webdav:b 进行同步时
会报错 ，但是查看 b挂载中 复制已经完成，但是多了一层 以 文件名 命名的文件夹。
同步后 文件完整路径如下 b/aa/aa.txt b/ab/ab.txt b/ac/ac.txt
求问这个问题怎么解决

### Reproduction / 复现链接

无

### Logs / 日志
![image](https://user-images.githubusercontent.com/63529476/199161214-a8ed6aa0-4e5b-4835-913a-57912fd8f13c.png)

**Comment by anzhiyu-c** [comment]
我也遇到了这个问题。

**Comment by furacas** [comment]
同样遇到了
