### ISSUE TITLE
文件夹加密情况分享链接能进去上层文件夹

### ISSUE THREAD

**Issue by jonntd** [alist-org/alist#2182]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

文件夹加密情况分享链接能进去上层文件夹，加密子文件话文件访问不到，希望能访问到分享的文件同时不希望能进去上层文件夹，要么就干脆做一个分享的功能只能看到分享的内容

### Additional context / 附件

![screenshot-20221102-163448](https://user-images.githubusercontent.com/7754100/199441655-b2cf5a5a-fb31-401e-8367-ec6724466963.png)

**Comment by anwen-anyi** [comment]
有没有可能有个叫  `应用到子文件夹` 的选项？

**Comment by jonntd** [comment]
应用到子文件夹 你这个文件都访问不了

安稳 ***@***.***> 于2022年11月3日周四 09:19写道：

**Comment by liugensite** [comment]
同样的问题，能不能生成token，用来做校验，保证子文件的安全

**Comment by ylsy2002** [comment]
同样的问题，Alist要挨个做文件夹加密的话太累赘了，不做的话又很容易被爬虫，尤其影响onedrive。我的看法是可以在配置文件里面配置好seed，分享时可以选择将url中的路径用seed加密。
