### ISSUE TITLE
挂载阿里云盘分享的文件无法下载

### ISSUE THREAD

**Issue by Qiaoidea** [alist-org/alist#2183]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.3.0

### Driver used / 使用的存储驱动

阿里云盘分享

### Describe the bug / 问题描述

能正确加载文件列表，但是无法访问和查看下载

`
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>636241D452799A353512A9E6</RequestId>
<HostId>cn-beijing-data.aliyundrive.net</HostId>
</Error>
`

### Reproduction / 复现链接

存储管理，加载阿里云盘分享，
链接 alishare/xxx/share.file

非视频和图文出现
复制 ｜ 下载
点击下载出现上述错误

视频和图文也无法查看，但是目录和文件名显示正确。

补充信息：
修改refresh_token 也是一样

### Logs / 日志

```shell
链接：
https://cn-beijing-data.aliyundrive.net/wvTdtfa4%2F1167465%2F609b4429fc3d0b5d8836477d8b5a915ece4d2330%2F609b44297f138ee44e4c4f1a8145c111b529625b?di=bj29&dr=84144657&f=62404068aead002026274a55af343a00c15a88b7&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E8%25BE%25B9%25E8%258D%2592%25E4%25BC%25A0%25E8%25AF%25B4%25281%2529.epub&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5eDPM2Bu5xl8qeEcRDVgDQ6Rsh%2BorfY0Tz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVGnKAv8qVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABCvRPZMSSaqtm%2Fo4s%2Bt%2B3CKT0vgcLkVwJuH%2BAz4hJ3K8TV7PXf72ieWvf%2BkIocxf5ncQHEvlcWj4dgRk7Mg7iy7395DdRhrpZ%2FSTOrnrByFi2nXGxVn8HvP0ynauo0UMZ9UH6YLMK02bmhj6MPxlqnyzO5%2FJg6y9IsLi9ccAsJtY%3D&sl=sXFzGzKSdJt&u=87c7d32d3f7746ad96dd946718746710&x-oss-access-key-id=STS.NT6ww5VCDEeos6dd4oJGRMrs3&x-oss-additional-headers=referer&x-oss-expires=1667383542&x-oss-signature=Ht8nLGPlq0mbeBx5rM%2BPsMs9oJ%2FwzDk3kSu%2BgGIvuO4%3D&x-oss-signature-version=OSS2

网页内容：

<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>636241D452799A353512A9E6</RequestId>
<HostId>cn-beijing-data.aliyundrive.net</HostId>
</Error>
```

**Comment by Ssiswent** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
> * [x]  I'm sure I'm using the latest version
> 
> ### Alist Version / Alist 版本
> v3.3.0
> 
> ### Driver used / 使用的存储驱动
> 阿里云盘分享
> 
> ### Describe the bug / 问题描述
> 能正确加载文件列表，但是无法访问和查看下载
> 
> `<Error> <Code>InvalidArgument</Code> <Message>At least one of AdditionalHeaders is not in request headers.</Message> <RequestId>636241D452799A353512A9E6</RequestId> <HostId>cn-beijing-data.aliyundrive.net</HostId> </Error>`
> 
> ### Reproduction / 复现链接
> 存储管理，加载阿里云盘分享， 链接 alishare/xxx/share.file
> 
> 非视频和图文出现 复制 ｜ 下载 点击下载出现上述错误
> 
> 视频和图文也无法查看，但是目录和文件名显示正确。
> 
> 补充信息： 修改refresh_token 也是一样
> 
> ### Logs / 日志
> ```shell
> 链接：
> https://cn-beijing-data.aliyundrive.net/wvTdtfa4%2F1167465%2F609b4429fc3d0b5d8836477d8b5a915ece4d2330%2F609b44297f138ee44e4c4f1a8145c111b529625b?di=bj29&dr=84144657&f=62404068aead002026274a55af343a00c15a88b7&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E8%25BE%25B9%25E8%258D%2592%25E4%25BC%25A0%25E8%25AF%25B4%25281%2529.epub&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5eDPM2Bu5xl8qeEcRDVgDQ6Rsh%2BorfY0Tz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNVGnKAv8qVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABCvRPZMSSaqtm%2Fo4s%2Bt%2B3CKT0vgcLkVwJuH%2BAz4hJ3K8TV7PXf72ieWvf%2BkIocxf5ncQHEvlcWj4dgRk7Mg7iy7395DdRhrpZ%2FSTOrnrByFi2nXGxVn8HvP0ynauo0UMZ9UH6YLMK02bmhj6MPxlqnyzO5%2FJg6y9IsLi9ccAsJtY%3D&sl=sXFzGzKSdJt&u=87c7d32d3f7746ad96dd946718746710&x-oss-access-key-id=STS.NT6ww5VCDEeos6dd4oJGRMrs3&x-oss-additional-headers=referer&x-oss-expires=1667383542&x-oss-signature=Ht8nLGPlq0mbeBx5rM%2BPsMs9oJ%2FwzDk3kSu%2BgGIvuO4%3D&x-oss-signature-version=OSS2
> 
> 网页内容：
> 
> <Error>
> <Code>InvalidArgument</Code>
> <Message>At least one of AdditionalHeaders is not in request headers.</Message>
> <RequestId>636241D452799A353512A9E6</RequestId>
> <HostId>cn-beijing-data.aliyundrive.net</HostId>
> </Error>
> ```

老哥，你好，我也是alist挂载的阿里云盘，但是我的下载直链是这种格式，和你的不一样，请问是我哪里没设置对吗
`http://pan.happaa.com/p/%E6%89%98%E7%AE%A1/Ssiswent/Mac%E5%A4%87%E4%BB%BD/Ssiswent%E7%9A%84%E8%AF%8D%E5%BA%93.scel?sign=8SZbvTMQCblsZdB-CwNrrIT-5HjueeF3GHQ7pLflzxg=:0`
<img width="322" alt="image" src="https://user-images.githubusercontent.com/37449310/206721616-34a84a79-6332-41fc-a8ad-9f04536e3129.png">

**Comment by xiaoyaoz1** [comment]
怎么解决的这个问题呢？

**Comment by hellojukay** [comment]
我也遇到了这样的问题，大家是如何解决的
