### ISSUE TITLE
阿里云分享链接能刷出目录，但浏览器和播放器均无法播放

### ISSUE THREAD

**Issue by snoopytl** [alist-org/alist#2185]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.3

### Driver used / 使用的存储驱动

阿里云盘分享

### Describe the bug / 问题描述

通过阿里云盘分享链接添加了文件，在主页可以显示，通过webdav在potplayer中也能显示，但无法播放，3种webdav策略都不行，好像和文件大小也没有关系，我查看1个70多k的图片也打不开，而且我发现我添加的刷新令牌在每次保存后重新进去查看，它是自动变化的

### Reproduction / 复现链接

阿里云分享id：cr21ayNfjkS

### Logs / 日志

```shell
runtime/asm_amd64.s:1594 (0x4756a0)
[0m
[GIN] 2022/11/02 - 13:11:08 | 500 |  218.392955ms | 192.168.195.100 | GET      "/p/周星驰/周星驰 电影合集 蓝光 REMUX/大话西游之仙履奇缘 (1995)/西遊記大結局之仙履奇緣).mkv?sign=_4awkPLVaPU3mwMbn4IMNplu7OLlQ_5u8wzEKfe0tV0=:0"
[GIN] 2022/11/02 - 13:11:08 | 401 |      52.258µs | 192.168.195.100 | GET      "/dav/周星驰/周星驰 电影合集 蓝光 REMUX/大话西游之仙履奇缘 (1995)/西遊記大結局之仙履奇緣).mkv"
[GIN] 2022/11/02 - 13:11:08 | 302 |     214.157µs | 192.168.195.100 | GET      "/dav/周星驰/周星驰 电影合集 蓝光 REMUX/大话西游之仙履奇缘 (1995)/西遊記大結局之仙履奇緣).mkv"
[31mERRO[0m[2022-11-02 13:11:08] <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
  <RequestId>63626C6C5FB8153537C27B3C</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <OSSAccessKeyId>STS.NUQEXFAnNzNJwrMTKv6yq9xoC</OSSAccessKeyId>
  <SignatureProvided>0nB+wSgCht8eavqnqoXeCx5W692Na2950zhM9CkCb5s=</SignatureProvided>
  <StringToSign>GET
```

**Comment by alan21j** [comment]
百度也出現類似情況，播放不了

**Comment by gitcook** [comment]
前几天更新了alist 然后今天就G了

**Comment by cbnui** [comment]
目前版本v3.3.0，也碰到类似的问题，挂载好后文件打不开播放不了，但把alist服务重启又可以重新打开及播放了。应该是BUG

**Comment by 0302-Darren** [comment]
分享链接有密码的下载提示没权限

**Comment by Qiaoidea** [comment]
同样的阿里云分享，从网盘网页点击可以正常播放，挂载到Alist上就不能了

**Comment by denda188** [comment]
3.4也依然播放不了

**Comment by YCIrving** [comment]
我也遇到了类似的问题，主页可以显示文件列表，但是播放不了。

后来打开设置中的“Web代理”后可以正常播放了
![image](https://user-images.githubusercontent.com/19617566/202857408-dda84f17-9773-4c2a-976d-14f15384ebb6.png)

**Comment by cxyzzz** [comment]
这是你用了桌面的token，换成手机端的token就行了
