### ISSUE TITLE
中国移动网盘同步大文件无法成功，比如一步4G左右的视频文件，没有成功过。

### ISSUE THREAD

**Issue by torgelee** [alist-org/alist#2195]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1

### Driver used / 使用的存储驱动

139yun

### Describe the bug / 问题描述

中国移动网盘同步大文件无法成功，也就是无法从本地上传到云端，比如一步4G左右的视频文件，没有成功过。一百多M的视频文件到时同步成功了。

### Reproduction / 复现链接

使用群晖NAS，打开webDAV，利用群晖的Cloud Sync连接，同步网盘的内容，将本地的视频文件同步到云端。

**Comment by nuan1989** [comment]
移动对文件大小本身有没做限制?

**Comment by Jiayou-Chao** [comment]
我遇到同样的问题，不限于移动云盘，阿里和天翼也有同样的问题，很可能所有网盘都无法上传大文件。直接使用webdav会出现405 method not allowed报错，mount以后会有0x80070021进程被锁定，无法访问报错，mount后台有405 method not allowed报错。

猜测是webdav协议对大文件支持有问题导致。

**Comment by nuan1989** [comment]
> 我遇到同样的问题，不限于移动云盘，阿里和天翼也有同样的问题，很可能所有网盘都无法上传大文件。直接使用webdav会出现405 method not allowed报错，mount以后会有0x80070021进程被锁定，无法访问报错，mount后台有405 method not allowed报错。
> 
> 猜测是webdav协议对大文件支持有问题导致。

123pan, 我30G都上传成功, 直接网页上传的. 理论上不存在这个说法.

**Comment by Jiayou-Chao** [comment]
> > 我遇到同样的问题，不限于移动云盘，阿里和天翼也有同样的问题，很可能所有网盘都无法上传大文件。直接使用webdav会出现405 method not allowed报错，mount以后会有0x80070021进程被锁定，无法访问报错，mount后台有405 method not allowed报错。
> > 猜测是webdav协议对大文件支持有问题导致。
> 
> 123pan, 我30G都上传成功, 直接网页上传的. 理论上不存在这个说法.

直接网页上传是指什么，这不是在讨论用webdav上传吗？

**Comment by albertwind** [comment]
这个我在用rclone webdav同步alist挂载的onedrive也遇到过大文件上传会出现405 method not allowed

**Comment by Austinwenyz** [comment]
这个可能是nginx的设置问题，默认nginx上传设置是50m，如需要可以自行扩大。另外，默认的nginx上传超时是60s，如果带宽不够也可能导致断开。
