### ISSUE TITLE
Alist无法在我的BCM4709C和MT7621构架路由上运行

### ISSUE THREAD

**Issue by cjchome** [alist-org/alist#2196]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v2.x v3.x

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

试了两台路由，斐讯K3（CPU是arm BCM4709C，梅林固件）和极路由B70（CPU是MT7621，Padavan固件)，下载了各arm和mipsle的版本，均无法在路由上运行

### Reproduction / 复现链接

![Alist](https://user-images.githubusercontent.com/30073216/199669905-0cf3492e-41b0-4e43-a83a-7773e3f13875.jpg)

**Comment by Xhofe** [comment]
Not all versions of prebuilt are available, please compile it yourself.

**Comment by arrio464** [comment]
MT7621 为 MIPS 架构，且内部没有 FPU 单元，因此需要采用`mipsel-linux-musln32sf-cross`自行编译。
```shell
wget https://musl.cc/mipsel-linux-musln32sf-cross.tgz
tar -xvf mipsel-linux-musln32sf-cross.tgz
export CC=~/mipsel-linux-musln32sf-cross/bin/mipsel-linux-musln32sf-gcc
export CXX=~/mipsel-linux-musln32sf-cross/bin/mipsel-linux-musln32sf-g++ 
export AR=~/mipsel-linux-musln32sf-cross/bin/mipsel-linux-musln32sf-ar
export LD=~/mipsel-linux-musln32sf-cross/
export GOOS=linux
export GOARCH=mipsle
export GOMIPS=softfloat
export CGO_ENABLED=1
```
其余部分参考[构建后端](https://alist.nn.ci/zh/guide/install/source.html#%E6%9E%84%E5%BB%BA%E5%90%8E%E7%AB%AF)即可。
```shell
go build -a -ldflags "-s -w -L /arrio/mipsel-linux-musln32sf-cross/ '-extldflags=-v -static'"
```
