### ISSUE TITLE
麻烦做一个默认dark的功能

### ISSUE THREAD

**Issue by ihuanx** [alist-org/alist#2202]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

其实也不影响切换 ..  就在于首次打开是黑色的还是白色的.  不按照浏览器决定.

**Comment by ihuanx** [comment]
或者可以实现一个  `https://example.com/?dark=1` 这样子

**Comment by Xhofe** [comment]
```html
<script>
localStorage.setItem("hope-ui-color-mode", "dark")
</script>
```

**Comment by ihuanx** [comment]
> ```
> <script>
> localStorage.setItem("hope-ui-color-mode", "dark")
> </script>
> ```

谢谢!!!

**Comment by YosenFree** [comment]
感谢
