### ISSUE TITLE
文件名称若含有 `#` 且使用cf worker时，无法预览且下载

### ISSUE THREAD

**Issue by MOOnLyer** [alist-org/alist#2208]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.3.0

### Driver used / 使用的存储驱动

GoogleDrive

### Describe the bug / 问题描述

当文件名称含有特殊字符 `#` 且使用cf worker作为代理时，文件无法预览也无法下载。预览时提示video load fail，点击下载会提示 

`{"code":401,"message":"expire missing"}`。

当取消使用下载代理时，一切正常。

该情况可能与 #1351 等issue 相关联，可能是只处理了本地端特殊字符问题，但没有解决远程通讯时文件名存在特殊字符的情况。

### Reproduction / 复现链接

当文件名称含有特殊字符 `#` 且使用cf worker作为代理时都会出现上述情况。

**Comment by Xhofe** [comment]
Provide a reproduction link, please.

**Comment by MOOnLyer** [comment]
> Provide a reproduction link, please.

[# 分享.MP4](https://alist.moont.cf/Quark/Share/#%20%E5%88%86%E4%BA%AB.MP4?sign=nnqkneLCuKufjJ5CUwsw65O50TuSFU9AgT_Ji_zqeXM=:0) Hope this will help.

**Comment by Xhofe** [comment]
> 

Give the original URL instead of redirect URL please.

**Comment by MOOnLyer** [comment]
> > > Provide a reproduction link, please.
> > 
> > 
> > [# 分享.MP4](https://alist.moont.cf/Quark/Share/#%20%E5%88%86%E4%BA%AB.MP4?sign=nnqkneLCuKufjJ5CUwsw65O50TuSFU9AgT_Ji_zqeXM=:0) Hope this will help.
> 
> Give the original URL instead of redirect URL please.

Following are two identical files with different filenames. As suggested, the one with special character `#` is not working properly.
[# 分享.MP4](https://index.moont.cf/%23%20%E5%88%86%E4%BA%AB.MP4) 
[分享.MP4](https://index.moont.cf/%E5%88%86%E4%BA%AB.MP4)

**Comment by MOOnLyer** [comment]
@Xhofe With the latest commit, the error message now becomes `{"code":401,"message":"sign mismatch"}`. I try to rebuild everything from scratch in case it is a cache issue. And it turns out that it is irrelevant.
