### ISSUE TITLE
威联通使用HBS同步失败。failed get storage 

### ISSUE THREAD

**Issue by fallenyy** [alist-org/alist#2209]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.3.0

### Driver used / 使用的存储驱动

所有

### Describe the bug / 问题描述

docker部署的V3版本 ，在威联通中能狗挂载到本地，但是使用HBS3创建同步空间时发生错误。而这在V2的版本中没有问题。
V3下报错 ：
![tmp2B4D](https://user-images.githubusercontent.com/70746058/199948723-01c0adde-eb9e-497f-adf2-67ad484437e8.png)

V2正常

### Reproduction / 复现链接

无

### Logs / 日志

```shell
相关日志 ：
failed get storage 
[GIN] 2022/11/04 - 10:00:47 | 405 |    4.618056ms |  192.168.31.151 | PROPFIND  "/dav/@QCloudSync/syncinfo"
```

**Comment by Xhofe** [comment]
A storage with name `@QCloudSync` is required.

**Comment by vision57** [comment]
我alist升级到v3.4.0后也遇到了这个问题。

威联通hbs3添加alist根路径（`/dav`）的时候，会自动尝试访问 `PROPFIND  "/dav/@QCloudSync/syncinfo"`。新版alist直接返回405，导致威联通认为webdav不可用。

但是如果在hbs3中直接添加alist某个已存在的具体存储路径的时候，比如`/dav/quark`，威联通同样会尝试访问`PROPFIND  "/dav/quark/@QCloudSync/syncinfo"`。此时alist会返回404，那么威联通不会认为webdav不可用。
