### ISSUE TITLE
似乎找到在Alist在某些路由系统运行时出现not found的原因了

### ISSUE THREAD

**Issue by cjchome** [alist-org/alist#2213]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V2.x V3.x

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

以斐讯K3为例（CPU是arm5 BCM4709C，梅林固件），运行alist-linux-arm-5时出现not found错误无法运行，经查可能是缺少动态链接库文件的问题，用readelf -l alist查看必需的库有/lib/ld-linux.so.3，绝大多数路由系统中lib目录中没有这个文件（固件中该目录只读，不能增改文件），通过安装entware可以得到这个库文件，不过entware的库是保存在/opt/lib/的 ，alist并没有识别到，所以还是会提示not found。
我也在其它的设备上做了一些测试，其中musl版的不需要动态链接库，所以可以在相应CPU构架环境下正常运行，其它需要动态链接的版本在路由系统中运行又缺少相应库文件的话就会提示not found，不同的系统环境需要的链接库文件不一样，不一定是/lib/ld-linux.so.3。
为了让更多轻型Linux系统设备的用户能用上Alist，能否将这个动态链接库的链接改为通过$PATH搜寻，而不指定绝对路径/lib/，或采用静态编译，非常感谢~

alist-linux-arm-5的动态链接信息，在K3缺少库文件不能运行
![alist-linux-arm-5](https://user-images.githubusercontent.com/30073216/199985812-b196ddac-f263-42d2-a38d-346c9a3fba64.jpg)

/lib/目录下没有相应库文件
![lib目录](https://user-images.githubusercontent.com/30073216/199985850-42f7c76f-2e7c-418a-8f99-50638584b019.jpg)

/opt/lib/目录有相应的库文件的软链接
![entware的lib](https://user-images.githubusercontent.com/30073216/199985868-0151d547-ecbd-4236-9c06-4325ab0948b1.jpg)

alist-linux-mipsle版的动态链接信息，在B70缺少库文件不能运行
![alist-linux-mipsle](https://user-images.githubusercontent.com/30073216/200008014-5d8f5c18-ea4b-42d8-b024-130f9580343c.jpg)

alist-linux-musl-mipsle版不需要动态链接库，在B70可以正常运行
![musl版](https://user-images.githubusercontent.com/30073216/199998202-55007178-27bb-4b87-8548-e4bf15ba3ecb.jpg)

### Reproduction / 复现链接

alist-linux-arm-5在K3找不到相应动态链接库文件，提示not found。
![not found](https://user-images.githubusercontent.com/30073216/199986551-39b2ec93-7279-4245-9f3c-4061ca9c3887.jpg)

**Comment by Xhofe** [comment]
Sorry -- not sure how this is related to AList.

- glibc does not support static linking, hence the musl version;
- Dynamically linking libraries is compiler behavior
- prebuilt arm versions use cross-compilation, so we recommend binaries are compiled for your native target yourself for performance and compatibility reasons.
