### ISSUE TITLE
在前台添加Aria2进度显示

### ISSUE THREAD

**Issue by KarlcxChina** [alist-org/alist#2229]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在调用Aria2下载时，在前台（文件列表界面）展示下载进度及下载速度。目前只能在提交任务后切换到第三方Aria2前端或者进入后台查看进度（且后台无法查看下载速度等详细数据）

**Comment by yws112358** [comment]
可能得考虑异步同步进度条的问题  读取速度应该可以 毕竟可以连rpc了
