### ISSUE TITLE
建议增加个前端css js缓存配置的控制.  

### ISSUE THREAD

**Issue by nuan1989** [alist-org/alist#2230]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

通过反向代理/cdn能实现js/css/jpg的缓存. 
不过对于大部分人来说,  需求可能只是简单的网盘,  这么折腾太麻烦了.   
---------------
希望增加一个http协议头的缓存时间的配置.  

### Suggested solution / 实现思路

建议做成设置或者配置. 而不是一刀切, 否则会一些诡异的想象,  特别对新手来说, 有时候明明后台改了代码, 前台刷新就是不变更. 会摸不着头脑.

**Comment by nuan1989** [comment]
好奇怪, 我今天加了cdn后, 同样是无缓存的情况下, 速度能快了2倍.  想不通, golang处理静态内容真的这么烂?  没道理啊.

**Comment by Xhofe** [comment]
后端并没有做静态资源缓存 属于浏览器默认行为 强制刷新即可
