### ISSUE TITLE
alist被反向代理后内网设备通过外网地址访问时，logo与标签logo一直转圈无法显示，非内网设备访问正常

### ISSUE THREAD

**Issue by Vincistudio** [alist-org/alist#2238]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

2.64

### Driver used / 使用的存储驱动

本地nas

### Describe the bug / 问题描述

alist被反向代理后内网设备通过外网地址访问时，logo与标签logo一直转圈无法显示，非内网设备访问正常。

### Reproduction / 复现链接

alist被反向代理后内网设备通过外网地址访问时，logo与标签logo一直转圈无法显示，非内网设备访问正常。

**Comment by Xhofe** [comment]
该版本不再维护。
