### ISSUE TITLE
希望添加不同网盘文件夹实时同步的功能

### ISSUE THREAD

**Issue by albertwind** [alist-org/alist#2246]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望添加不同网盘文件夹实时同步的功能，比如OneDrive可以实时同步阿里云盘的文件夹，方便不同网盘之间实现数据同步

**Comment by Sliots-dump** [comment]
同样希望有这个功能，这样可以实现由一个主要的网盘负责更新，然后同步到其他网盘作为备份/分流

**Comment by BurtSweet** [comment]
这是个很有价值的功能希望大佬们考虑下☕️

**Comment by takchichan** [comment]
can't agree more

**Comment by takchichan** [comment]
附议

**Comment by GengGode** [comment]
附议

**Comment by Peooop** [comment]
附议，很有价值

**Comment by wejudging** [comment]
附议，很有价值

**Comment by Jue-Xu** [comment]
alist配合rclone可以实现吧

**Comment by ypq123456789** [comment]
附议！请求考虑！

**Comment by nexx5** [comment]
> alist配合rclone可以实现吧

rclone sync 本地:/data1 远程:/data1
阿里等云盘都会报错。多数时405错误

**Comment by myselfghost** [comment]
我也觉得这个功能很有必要，谢谢。

**Comment by Asakushen** [comment]
附议，谢谢！

**Comment by Katou-Kouseki** [comment]
是有必要的功能，附议
