### ISSUE TITLE
SFTP挂载报错

### ISSUE THREAD

**Issue by A-xianchu** [alist-org/alist#2267]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1 windows amd64

### Driver used / 使用的存储驱动

SFTP

### Describe the bug / 问题描述

SFTP挂载时报错
确认SSH密码无错误
确认地址无错误
确认SSH本身可连接

![](https://s1.ax1x.com/2022/11/09/xzoOPS.png)

### Reproduction / 复现链接

内网未开放公网

### Logs / 日志

```shell
Failed create storage in database: UNIQUE constraint failed: x_storages.mount_path
```

**Comment by A-xianchu** [comment]
已解决，没加端口号

**Comment by RalstonLiu** [comment]
> 已解决，没加端口号

你好，请教一下端口号加在哪里？我在地址栏直接写成`201.9.39.100 -P 2213`这种形式，似乎还是不行

**Comment by RalstonLiu** [comment]
> 已解决，没加端口号

搞定了 ip:端口
