### ISSUE TITLE
所有密码都是明文显示或存储，有没有考虑修饰一下？

### ISSUE THREAD

**Issue by cjchome** [alist-org/alist#2269]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

发现Alist所有密码都是明文显示或存储，特别是在半开放的场合，如公司台式电脑、疏于管理的服务器，很容易通过肩窥或不小心本地文件泄漏等原因导致非法登录，是不是考虑加密一下？
用户
![用户](https://user-images.githubusercontent.com/30073216/200727211-1ce307a7-a3b4-4832-940f-0c7a1c58ccfe.jpg)
元信息
![元信息](https://user-images.githubusercontent.com/30073216/200727303-4098c4f6-a27c-4651-9f84-1b88db4bd7df.jpg)
数据库mate
![数据库1](https://user-images.githubusercontent.com/30073216/200727331-6d99c0cc-11c8-4580-bc07-73211b9ad755.jpg)
数据库users
![数据库2](https://user-images.githubusercontent.com/30073216/200727351-86a97b81-788f-47ac-b0d7-9e2f6bb2865d.jpg)

### Suggested solution / 实现思路

Web端强烈建议统一显示星号，如有需要在旁边加上“显示密码”按钮，数据库保存的密码加密存储，哪怕稍稍掩饰一下也好呀

**Comment by cjchome** [comment]
使用下来，让我个人感觉filebrowser的安全性会比alist强一些，可能各自的侧重点不同吧。
比如我如果在公用电脑上远程访问自己构建的云盘后，filebrowser我只要退出登录我就可以放心的走了，但是alist我真不知道我走后文件会不会被后面几个使用者轮J，因为主页只要登录过一次，下次打开就再也不用密码了。

**Comment by anwen-anyi** [comment]
> 使用下来，让我个人感觉filebrowser的安全性会比alist强一些，可能各自的侧重点不同吧，还是我的配置方法不对？ 比如我如果在公用电脑上远程访问自己构建的云盘后，filebrowser我只要退出登录我就可以放心的走了，但是alist我真不知道我走后文件会不会被后面几个使用者轮J，因为主页只要登录过一次，下次打开就再也不用密码了。

自己设置登录失效呗...默认48小时失效

**Comment by Becods** [comment]
> 使用下来，让我个人感觉filebrowser的安全性会比alist强一些，可能各自的侧重点不同吧，还是我的配置方法不对？ 比如我如果在公用电脑上远程访问自己构建的云盘后，filebrowser我只要退出登录我就可以放心的走了，但是alist我真不知道我走后文件会不会被后面几个使用者轮J，因为主页只要登录过一次，下次打开就再也不用密码了。

manage界面，右上角有退出按钮

或者直接清理cookie
