### ISSUE TITLE
raidrive挂载后不能写入

### ISSUE THREAD

**Issue by wonb168** [alist-org/alist#2270]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v4.0

### Driver used / 使用的存储驱动

天翼云

### Describe the bug / 问题描述

可以浏览，但不能写入文件。
![image](https://user-images.githubusercontent.com/25274931/200730602-5525c541-9d5e-478e-9eea-58b6b9f610b8.png)

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/25274931/200730798-f8283639-2a39-4309-9d01-8fd7bae324ce.png)

### Logs / 日志

```shell
无
```

**Comment by wonb168** [comment]
> ### See
> 1. 65% [升级了V3，Raidrive挂载后不能写入！！ #1678](https://github.com/alist-org/alist/issues/1678)

调为了本地代理，还是不能写入

**Comment by luxiyourbro** [comment]
![image](https://user-images.githubusercontent.com/32382388/206890652-87844991-6369-4389-9ea4-2e59ea312f22.png)
