### ISSUE TITLE
Raidrive挂载天翼云不能写入

### ISSUE THREAD

**Issue by wonb168** [alist-org/alist#2292]
> ### See
> 1. 65% [升级了V3，Raidrive挂载后不能写入！！ #1678](https://github.com/alist-org/alist/issues/1678)

调为了本地代理，还是不能写入

_Originally posted by @wonb168 in https://github.com/alist-org/alist/issues/2270#issuecomment-1309839055_

**Comment by luxiyourbro** [comment]
![image](https://user-images.githubusercontent.com/32382388/206890667-d790f174-e53c-4ee3-90b9-1241e1eb0482.png)
不能写入
