### ISSUE TITLE
元信息隐藏功能有问题（正则表达式测试无问题）

### ISSUE THREAD

**Issue by rockxsj** [alist-org/alist#2293]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.3.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/3021207/201255944-f46b20d0-9df1-4ca8-bfbb-ac9d3188062a.png)
按照上图配置后图片还是会显示在列表中
![image](https://user-images.githubusercontent.com/3021207/201255990-9d5bcc07-2b30-4fbb-be96-9908f42dcb5a.png)

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/3021207/201256035-807ac30a-fd5c-45b5-b8bb-44e1828b9973.png)
正则表达式测试应该是通过的

**Comment by rockxsj** [comment]
经过测试，设置到子目录，则则目录的文件隐藏是生效的。   但是上图我配置到根目录，已经勾选了应用到子目录了呀。

**Comment by Xhofe** [comment]
不需要使用`。

**Comment by rockxsj** [comment]
> 1. 不需要使用`；
> 2. 只会使用最近的元信息。

问题解决  就是因为忘记去掉`了   
其实最开始就配置好了，只是我是登录的admin看的，所以还能看到我以为是bug，刚debug了一下代码发现admin永远能看到隐藏的内容。。。
谢谢dalao
