### ISSUE TITLE
v3.3.0，迅雷专家版方式添加网盘后播放的视频为720p

### ISSUE THREAD

**Issue by LGuangming** [alist-org/alist#2297]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.3

### Driver used / 使用的存储驱动

ThunderExpert

### Describe the bug / 问题描述

v3.3.0版本中，以迅雷专家版方式添加迅雷网盘后，不管是在IOS 下的Nplayer还是android TV的KODI，播放的视频均为720p

### Reproduction / 复现链接

。

**Comment by foxxorcat** [comment]
使用迅雷官方的app能看高于720p的吗

**Comment by foxxorcat** [comment]
如果没开使用视频Url的话是使用下载链接,除非视频本身是720p,不然不可能低于720p.
启用的话也是优先返回最清晰的链接,除非不是vip看不了原画.

**Comment by LGuangming** [comment]
> 使用迅雷官方的app能看高于720p的吗

也只能看720p的视频，我又看了一下，我的确是打开了使用视频url。但是从我设置xunlei expert后一直没动过，但视频变为720p是最近才有的事情，之前一直都是原分辨率播放。

**Comment by foxxorcat** [comment]
那就不是alist的问题了,调用的是迅雷官方接口,所以只能按官方的来
