### ISSUE TITLE
[增强建议] 1. 希望给一组任务 增加大概的总进度条(数量) 2. 可以筛选 成功/错误 的任务 3. 失败的任务希望可以retry

### ISSUE THREAD

**Issue by tanpengsccd** [alist-org/alist#2300]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

[增强建议] 
1. 希望给一组任务 增加大概的总进度条
    - 一组任务是指的一次性添加的多个任务为一组
    - 组进度条 是显示该组的完成数量百分比进度
2. 可以筛选 成功/错误 的任务 
    - 希望可以有可筛选的复选框  进行中/完成/错误  来筛选任务.
3. 失败的任务希望可以retry 
    - 失败的任务可能是网络波动造成 所以希望可以自动重试 或者  手动 点击重试.

### Suggested solution / 实现思路

rt

**Comment by ma3252788** [comment]
+1 目前确实没有重试的选项

**Comment by makergit365** [comment]
+1 上传这块希望能再改进改进，现在总是稀里糊涂失败，开了秒传，有的失败了，我拉出来单独重试成功了，有的死活不成功，我用pc客户端秒传成功，确定不能秒传的，我关闭秒传有的能上传有的又不能。

**Comment by zx2587232768** [comment]
+1 任务列表若能得到增强将会极大的增加可用性，在一个存储将一个文件夹内非常多的文件复制到其他存储时，总是会有很多文件出错，没有筛选和重试导致使用体验非常糟糕

**Comment by LuGHuaaa** [comment]
+1 复制了 200G, 有几十个错误,  没有重试已经没办法处理了

**Comment by tanpengsccd** [comment]
+1 一键重试确实是个刚需了.115复制到本地总会有不少失败的.

**Comment by Jonathan523** [comment]
+1 重试确实是刚需了

**Comment by pipinian** [comment]
+1 如果能实现重试，也不用费自己硬盘来上传了，岂不美哉

**Comment by pockegar** [comment]
+1
