### ISSUE TITLE
加入aira2修改下载保存地址，不然docker安装的alist没法用aria2

### ISSUE THREAD

**Issue by laowangdegit** [alist-org/alist#2308]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用docker安装的alist发送给aira2的下载保存地址是docker内部地址，宿主机的aira2根本没法创建这个地址，就会任务失败，按理应该提交到bug区，但没看明白bug提交要求，提交过一个说提交的不对

### Suggested solution / 实现思路

只需要给个修改传递地址的选项就行了，修改成宿主机aira2可以创建的地址

**Comment by vjjj4688** [comment]
对，3.3.0可以用，3.4.0就挂了，发送到aria2用不了

**Comment by Xhofe** [comment]
https://docs.docker.com/storage/bind-mounts/

**Comment by laowangdegit** [comment]
> Hello @laowangdegit, this issue will not be worked on and will be closed. 你好 @laowangdegit，这不会被处理，将被关闭。



> https://docs.docker.com/storage/bind-mounts/

给我看这有啥用啊，事实就是docker的alist没法用aira2，难不成就这玩意还要自己去搞操作？

**Comment by Febtw** [comment]
> > Hello @laowangdegit, this issue will not be worked on and will be closed. 你好 @laowangdegit，这不会被处理，将被关闭。
> 
> > https://docs.docker.com/storage/bind-mounts/
> 
> 给我看这有啥用啊，事实就是docker的alist没法用aira2，难不成就这玩意还要自己去搞操作？

临时解决方法
宿主机创建 mkdir -p /opt/alist/data/temp/aria2
alist容器进行同名挂载 -v /opt/alist/data/temp/aria2:/opt/alist/data/temp/aria2
