### ISSUE TITLE
PDF.js 加载缓慢，建议直接内置

### ISSUE THREAD

**Issue by hihuangwei** [alist-org/alist#2309]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0

### Driver used / 使用的存储驱动

smb

### Describe the bug / 问题描述

PDF预览缓慢

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
You can deploy it yourself and replace the default in https://alist.nn.ci/config/preview.html#iframe-previews.
