### ISSUE TITLE
路径带有X (2022)下载会500报错,在线播放正常

### ISSUE THREAD

**Issue by msycn** [alist-org/alist#2317]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

感谢大佬 @Xhofe 开发这么强大的系统路径带有X (2022)下载就会500报错, 修改为X档案 (2022)可以正常下载
在线播放正常

### Reproduction / 复现链接

https://cdn1.naifeis.com/d/cn/Netflix/Movie/1080/X/X%20(2022)/X%20(2022)%20-%201080p.h265.mkv

### Logs / 日志

```shell
{"code":500,"message":"failed to get file: failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed get dir: failed get parent list: failed to list objs: Post \"https://api.aliyundrive.com/v2/file/list\": net/http: TLS handshake timeout","data":null}
```

**Comment by anwen-anyi** [comment]
我这里点这个复现链接能下载啊
![](http://pic.rmb.bdstatic.com/bjh/aa267590e5ed7feedfa5911e63f7df60.png)
