### ISSUE TITLE
只能挂载一个类型的盘一个？

### ISSUE THREAD

**Issue by 91jetbrain** [alist-org/alist#2320]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

你好，我已经挂了一个oneDrive，但是当我开始挂第二个onedrive之后 一直报错：
【Failed create storage in database: UNIQUE constraint failed: x_storages.mount_path】
我已经按了ctrl F5 刷新页面了， 但是一直是这个提示。
我想请问下， 是不是 只支持一个类型的盘，只能挂一个？
比如不能同时挂两个onedrive?

### Reproduction / 复现链接

...不知道这个链接是指？

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/guide/drivers/common.html#%E6%8C%82%E8%BD%BD%E8%B7%AF%E5%BE%84
