### ISSUE TITLE
v3.4.0本地存储下载的内链是http导致chorme和edge无法下载

### ISSUE THREAD

**Issue by simplove** [alist-org/alist#2326]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

url地址是 https://pan.xxx.me/loc/file/BCompare-zh-4.1.3.20814.rar
下载的地址是http://pan.xxx.me/p/loc/file/BCompare-zh-4.1.3.20814.rar?sign=npGvmhgI5lB44Dyr7TgCWBNaVRsRRxbQtakduHvCP-k=:0
导致新版本的chrome和edge无法下载![](https://s3.bmp.ovh/imgs/2022/11/14/88865a7e59512448.png)
chrome是一闪就没了，edge报错：无法安全下载
![](https://s3.bmp.ovh/imgs/2022/11/14/954b322cd6e7240c.png)
原因是因为chrome新版本不允许https嵌套http的下载链接。
旧版本可以通过修改![](https://s3.bmp.ovh/imgs/2022/11/14/ad10cee69d714697.png)

### Logs / 日志
即使我做了301跳转，也不会影响到内链仍然是http的状态。所以看能不能加个功能
_No response_

**Comment by 12189108** [comment]
https://alist.nn.ci/config/configuration.html#site-url
