### ISSUE TITLE
群晖映射的WEBDAV里的视频播放时音频与视频不同步，音频慢一拍。快进一下又好了，播一会儿又慢了

### ISSUE THREAD

**Issue by yefenghu** [alist-org/alist#2328]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0

### Driver used / 使用的存储驱动

群晖webdav

### Describe the bug / 问题描述

群晖映射的WEBDAV里的视频播放时音频与视频不同步，音频慢一拍。快进一下又好了，播一会儿又慢了

### Reproduction / 复现链接

https://yefenghu.top:5244/%E5%BD%B1%E8%A7%86%E5%A4%A7%E5%8E%85/%E7%94%B5%E8%A7%86%E5%89%A7/q%E5%8D%BFr%E5%B8%B8.EP12.HD1080p.mp4

**Comment by Xhofe** [comment]
Alist use artplayer as default web video player. If you have any issues about it, please go to https://github.com/zhw2590582/ArtPlayer to solve it.
