### ISSUE TITLE
希望添加aria2远程离线下载功能

### ISSUE THREAD

**Issue by Austinwenyz** [alist-org/alist#2330]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望添加aria2远程添加下载到云储存对象功能。

aria2现在已经实现离线下载了，但是需要通过网页端来添加离线下载任务，并且无法实时观看下载进度，最重要的是通过aria2 NG等web ui无法直接离线下载到储存对象中，只能下载到本地。因此希望可以通过aria2 ng等web ui来远程添加离线下载任务到云端储存对象中。

### Suggested solution / 实现思路

不知道aria2和NG之间的通讯协议是什么，但是他们可以通过http通讯，可能也就可以通过中间人攻击的方式截取他们的通讯，然后解码并且添加到Alist离线任务。

### Additional context / 附件

无

**Comment by Xhofe** [comment]
1. 后台可以看到下载与中转进度
2. 要通过aria2 ng等web ui添加你应该给aria2 ng提issue而不是这里。
