### ISSUE TITLE
安卓手机刷入后，重启手机📱 出错

### ISSUE THREAD

**Issue by Discover623** [alist-org/alist#2339]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.4

### Driver used / 使用的存储驱动

阿里云

### Describe the bug / 问题描述

之前好好的，，最近更新完 每次重启都这样  ，咋回事呦[疑问]        点击状态异常的 “编辑”按钮 后 进去不动任何地方 直接点保存 保存后才可以用 重启又要弄一次才正常

### Reproduction / 复现链接

![Uploading 12.png…]()

### Logs / 日志

```shell
https://imgse.com/i/zAhoLD
```

**Comment by Discover623** [comment]
https://s1.ax1x.com/2022/11/14/zAhoLD.png

**Comment by Xhofe** [comment]
https://www.google.com/search?q=android+no+address+associated+with+hostname
