### ISSUE TITLE
能否让本地上传onedrive时不经过服务器代理

### ISSUE THREAD

**Issue by 1219099256** [alist-org/alist#2364]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

因为需要使用cf的证书，就需要打开cf的代理，但是cf有上传大小限制，请问能否实现

**Comment by fl0w1nd** [comment]
`Cloudreve`的Onedrive上传文件就不需要经过服务器代理，我觉得应该可以实现吧

**Comment by YangDunYu** [comment]
目前貌似所有本地上传的文件都要过一遍Alist服务器才行，因为用户认证的关系

**Comment by sakuraes** [comment]
+1，cf有上传大小限制，配置了nginx没有效果，原来是CF的问题
