### ISSUE TITLE
V3 全局 设置->站点 ->默认每页数量30 不起作用, list刷新 per_page 还是= 0, 近1W子文件夹 载入直接卡崩 

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#2380]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

189

### Describe the bug / 问题描述

189 排序 修改时间 降序 + 文件夹 提到最前，
全局 设置->站点 ->默认每页数量30 不起作用。 per_page 还是0

http://192.168.0.1:5244/api/fs/list
{"path":"/","password":"","page":1,"per_page":0,"refresh":true}

per_page 怎么设置 默认都是0, 然而我目录里面 近1W个子项目...悲催了

### Reproduction / 复现链接

per_page 默认设置30-50 默认强制分页!

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/site.html#pagination-type
