### ISSUE TITLE
上传已存在文件完成后，会同时存在两个同名文件

### ISSUE THREAD

**Issue by devioa** [alist-org/alist#2390]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

之前open过这个issue #2324 
拉了最新源码编译出来后测试还是一样复现
运行环境：
![QQ截图20221116234456](https://user-images.githubusercontent.com/38558065/202226701-cc747cad-f1be-40ba-9cf3-4534671fd4e0.png)

### Reproduction / 复现链接

![QQ截图20221116233800](https://user-images.githubusercontent.com/38558065/202225336-110fce01-1b6f-4a80-ae89-14ae594cb888.png)

**Comment by Xhofe** [comment]
unable to reproduce.

**Comment by devioa** [comment]
我重新编译在`Linux arm64`运行的二进制文件没有复现出来，今天晚些时候我重推docker镜像再pull试试

**Comment by devioa** [comment]
> 我重新编译在`Linux arm64`运行的二进制文件没有复现出来，今天晚些时候我重推docker镜像再pull试试

我`rm -rf`再重新pull编译出来运行就不会再复现了，已解决
