### ISSUE TITLE
阿里云盘分享挂载到其他目录下导致目录最后一项文件无法读取

### ISSUE THREAD

**Issue by LikeQFXY** [alist-org/alist#2391]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

当我把一个阿里云盘分享挂载到我的阿里云盘目录下面，此时我自己阿里云盘目录里面的最后一个文件就会在点击后消失且无法读取显示object not found，刷新列表可以重新加载出来但依然会在点击后消失。禁用分享存储后恢复正常文件可读可显示，但是只要打开分享存储，最后一项文件就会无法读取。

### Reproduction / 复现链接

https://likeqfxy-my.sharepoint.com/:v:/g/personal/likeqfxy_ms_likeqfxy_top/Ef4_l-9K4OFAlTsCnanudL4Bj5ObmY7Np7tb9w8UbePEcw?e=DKcvL4

**Comment by LikeQFXY** [comment]
和哪一个重复了？

**Comment by LikeQFXY** [comment]
https://likeqfxy-my.sharepoint.com/:v:/g/personal/likeqfxy_ms_likeqfxy_top/EbJS4PeKv0VOpgr0jfFungMBBceA2XdFzLv-OzBvNPpiQw?e=w6aWxx

**Comment by LikeQFXY** [comment]
@Xhofe 我真找不到相同的，我看到了许多分享资源目录不能访问或者子目录无法访问等很多由于“/”引起的问题，但我这个是分享资源保存到其他目录后导致其他目录中的某个文件无法访问，而那个文件名中并不包含“/”。这里还有一个演示视频。[https://likeqfxy-my.sharepoint.com/:v:/g/personal/likeqfxy_ms_likeqfxy_top/Edllty-y2PtDgjbwgmusAQMBM3MbxVY6R_F8Vt6RpZ9c7g?e=JcN9Df](url)

**Comment by Xhofe** [comment]
#2340

**Comment by LikeQFXY** [comment]
确实相似，但他那个是两个onedrive挂载到相同存储出现的无法访问文件**夹**的问题，我这个是阿里云盘分享挂载到阿里云盘（视频一）、阿里OSS（视频二）、onedrive个人版（视频三）无法访问挂载目录下文件的问题。并且我尝试过挂载到只有文件夹的目录，不会出现任何问题，文件夹都可以访问。最为奇怪的是onedrive工作版并不受此影响，不管是只有文件夹的目录，还是混合目录，所有文件夹及文件都能访问。

**Comment by Xhofe** [comment]
此问题与使用的存储无关，只与是否挂载了存储到另一个存储内部并且开启了排序有关，且具有随机性。在主分支中已经修复，可以在actions中下载试用。

**Comment by LikeQFXY** [comment]
okk，感谢解答
