### ISSUE TITLE
更新官方文档中 v3 token 的获取方法

### ISSUE THREAD

**Issue by Ton-yi** [alist-org/alist#2393]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

[alist文档](https://alist-doc.nn.ci/docs/driver/alist/#token) 中获取 token 的方式是v2的 希望更新v3 的 token 获取方式

### Reproduction / 复现链接

我想要使用 [## picgo-plugin-alist](https://github.com/jinzhi0123/picgo-plugin-alist) 时参照 [alist文档](https://alist-doc.nn.ci/docs/driver/alist/#token) 获取token 失败
，之后是在这个 [issue](https://github.com/jinzhi0123/picgo-plugin-alist/issues/3) 找到获取方式，

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/other.html#token
