### ISSUE TITLE
文件夹中带有/字符会被认为是路径分隔符

### ISSUE THREAD

**Issue by rockxsj** [alist-org/alist#2409]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0

### Driver used / 使用的存储驱动

阿里云分享

### Describe the bug / 问题描述

路径名中带有/会被认为是路径分隔符，从而报错
![image](https://user-images.githubusercontent.com/3021207/202641156-fca0caef-3cbd-4259-803b-ce530d82423c.png)

### Reproduction / 复现链接

随便一个带有/的路径即可
![image](https://user-images.githubusercontent.com/3021207/202641201-279e99a1-af53-4a4a-817c-516bae78be7d.png)

**Comment by Xhofe** [comment]
duplicate with #2006 #1979 #1507 #324 #691
