### ISSUE TITLE
Text Editor修改文本文件的内容后，返回目录刷新再进入Markdown预览报错

### ISSUE THREAD

**Issue by devioa** [alist-org/alist#2418]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

Text Editor修改文本文件的内容后，返回目录刷新再进入Markdown预览报错，同时Text Editor也是编辑的报错的文本

### Reproduction / 复现链接

本来是想测试之前open的issue #2396 。刚开始在文本首行随便只输了个`1`，返回刷新预览都正常。后面具体忘了是什么步骤了，好像是我把那个`1`删掉再保存，然后按相同的步骤返回目录刷新再进入Markdown预览就这样了。我把此文件下载下来看内容是正常无误的，但是Markdown和Text Editor会显示这样：
![1](https://user-images.githubusercontent.com/38558065/202845183-20a3470e-9fc5-49de-83ce-51ecff2762ee.png)
![2](https://user-images.githubusercontent.com/38558065/202845193-178c4529-37f0-469b-9d92-97f8cdee07db.png)
尝试`docker restart alist`无效
尝试在后台禁用该存储挂载然后再启用也无效
最后清除浏览器缓存并删除cookies以及本地会话存储后恢复正常了

**Comment by devioa** [comment]
后续变成这样了：
![1](https://user-images.githubusercontent.com/38558065/202845476-4b72ad62-d3ed-4227-8102-8efced55cf33.png)

**Comment by devioa** [comment]
和上个comment相关的log：
![2](https://user-images.githubusercontent.com/38558065/202845570-960da1e3-1261-45ba-96f7-5491d55c08c9.png)

**Comment by Xhofe** [comment]
Reproduction Link please.

**Comment by devioa** [comment]
> Reproduction Link please.

http://mosol.oicp.net:88/Public/just_for_test.txt

**Comment by Xhofe** [comment]
duplicate with #2415
