### ISSUE TITLE
大文件上传到100%时报错 Request failed with status code 504

### ISSUE THREAD

**Issue by lingan1996** [alist-org/alist#2419]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.4.0

### Driver used / 使用的存储驱动

Onedrive 和 本地存储

### Describe the bug / 问题描述

选择form方式上传4GB的mov视频，上传到100%后报错：Request failed with status code 504。试过分别上传到Onedrive 和 本地存储，都是报相同的错。
上传到本地存储报错后，但可以在本地和网页上看到上传的文件，并且文件也没损坏。
而上传Onedrive报错后，在文件列表看不到文件，大概是上传到服务器上中专时报错了。

### Reproduction / 复现链接

无

### Logs / 日志

```shell
Request failed with status code 504
```

**Comment by Xhofe** [comment]
https://www.google.com/search?q=nginx+reverse+proxy+timeout
