### ISSUE TITLE
arm-5 版本的包无法使用报错

### ISSUE THREAD

**Issue by qigj** [alist-org/alist#2420]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0

### Driver used / 使用的存储驱动

启动

### Describe the bug / 问题描述

arm-5 版本的包无法使用报错

### Reproduction / 复现链接

arm-5 版本的包无法使用报错，
咱们是这样build吗？
GOARM=5 GOARCH=arm GOOS=linux go build

### Logs / 日志

```shell
INFO[2022-11-18 10:49:58]/home/qijia14/alist/internal/bootstrap/log.go:49 github.com/alist-org/alist/v3/internal/bootstrap.Log() init logrus...
```

**Comment by Xhofe** [comment]
prebuilt 除musl版本外均使用https://github.com/techknowlogick/xgo 交叉编译，若不能使用请自行编译。
