### ISSUE TITLE
本地挂载，点击下载，链接没有带上端口，而复制链接有端口。

### ISSUE THREAD

**Issue by aday1986** [alist-org/alist#2429]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3

### Driver used / 使用的存储驱动

本地挂载

### Describe the bug / 问题描述

例如：
点击下载时，访问的链接是不带端口的：http://www.pan.com/p/Local/Router/log/log.log?sign=viSwtuh45Z7foIu2P0o9CDKE-DRT7YG-zEaGZC4QUcU=:0
点击复制链接，链接则为正常可使用的：https://www.pan.com:5001/d/Local/Router/log/log.log

### Reproduction / 复现链接

https://www.pan.com:5001/d/Local/Router/log/log.log

**Comment by uvwvu** [comment]
docker，v2.6.4版本，本地存储下载按键正常。最新版下载按键无法下载，
?sign=IvFzPpfSwqGWCSruuk0wRIJKXZ5Yyts2EurRH3TwdMk=:0
复制粘贴链接下载正常

**Comment by aday1986** [comment]
> docker，v2.6.4版本，本地存储下载按键正常。最新版下载按键无法下载， ?sign=IvFzPpfSwqGWCSruuk0wRIJKXZ5Yyts2EurRH3TwdMk=:0 复制粘贴链接下载正常

是的，我和你一摸一样的情况。

**Comment by aday1986** [comment]
![image](https://user-images.githubusercontent.com/35755382/203055516-404ac6e0-fc0e-4e56-8cab-749acf479819.png)
点击复制链接，得到的链接是：https://pan.zkbar.cn:5001/d/Local/Synology/share/%E5%AD%A6%E7%94%9F%E5%90%8D%E5%8D%95.xlsx

**Comment by 12189108** [comment]
> ![image](https://user-images.githubusercontent.com/35755382/203055516-404ac6e0-fc0e-4e56-8cab-749acf479819.png) 点击复制链接，得到的链接是：https://pan.zkbar.cn:5001/d/Local/Synology/share/%E5%AD%A6%E7%94%9F%E5%90%8D%E5%8D%95.xlsx

你这数据保真吗🌝

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/configuration.html#site-url

**Comment by aday1986** [comment]
> https://alist.nn.ci/config/configuration.html#site-url

解决了，非常感谢。

**Comment by Winyer** [comment]
> > * [使用非标准端口反代后夸克网盘的文件请求错误 #726](https://github.com/alist-org/alist/issues/726)
> > * [当网址带端口时,播放视频存在问题 #1159](https://github.com/alist-org/alist/issues/1159)
> > * [反向代理后  下载按钮的链接不正确 #3644](https://github.com/alist-org/alist/issues/3644)
> 
> 解决了，非常感谢。

请问是怎么解决的😥没看懂

**Comment by mygit20230606** [comment]
现在2023年12月19日 还有这问题
