### ISSUE TITLE
文件夹名称中包含“/”符号会被识别成路径中包含子目录，导致无法正常浏览

### ISSUE THREAD

**Issue by 849506054** [alist-org/alist#2440]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.4.0

### Driver used / 使用的存储驱动

阿里云盘/阿里云盘分享

### Describe the bug / 问题描述

文件夹名称中包含“/”符号会被识别成路径中包含子目录，导致无法正常浏览。

例图，文件夹名称中包含“/”符号，
![image](https://user-images.githubusercontent.com/25845909/203049806-a856674b-962c-4767-b74c-c9d2d66feb02.png)
alist将文件夹名称中的“/”识别为下级路径分割符号
![image](https://user-images.githubusercontent.com/25845909/203050437-a59904ed-53b9-4a04-8978-b87f24447bb1.png)

### Reproduction / 复现链接

https://www.aliyundrive.com/s/53VdBr6hK9B/folder/635151fc53641440ad95492c8174c57584c56f68

**Comment by shuoshuo1234** [comment]
确实有这个问题
