### ISSUE TITLE
Can not load PDF via HTTP - site_url

### ISSUE THREAD

**Issue by drewbitt** [alist-org/alist#2442]
### Please make sure of the following things

- [ x] I have read the [documentation](https://alist.nn.ci).
- [ x] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.4.0

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

Relates to #1681 

![image](https://user-images.githubusercontent.com/26885897/203176424-ad4b1cf2-0e40-4ec5-9a7a-4f890c9874d2.png)

This is because of mixed content 

```
fetch_stream.js:123 Mixed Content: The page at 'https://alist-org.github.io/pdf.js/web/viewer.html?file=http%3A%2F%2F192.168.1.237%3A5244%2Fp%2Fmnt%2Fdata%2FDocuments%2FBooks%2FTest.pdf%3Fsign%3DHAhGEE9t2Ctw-MW9IFuyBw34Kfa3G7QF2LxL6pLLLXk%3D%3A0' was loaded over HTTPS, but requested an insecure resource 'http://192.168.1.237:5244/p/mnt/data/Documents/Books/Dating/Online%20Dating%20for%20Men.pdf?sign=HAhGEE9t2Ctw-MW9IFuyBw34Kfa3G7QF2LxL6pLLLXk=:0'. This request has been blocked; the content must be served over HTTPS.
```

I am running alist over HTTP with `schema: { "https": "false"`

The solution, `You need to set Api url in Site settings to your real address so that the backend can provide the correct link of file.`, has the setting in https://github.com/alist-org/alist/commit/7c32af4649909dd7ebcafe2b58ed44c311223759 moved to `site_url`

I have set `site_url` in `config.json` to `http://myip:5244` but it does not solve the pdf problem. 

Other settings:
```
{
  "force": false,
  "address": "0.0.0.0",
  "port": 5244,
  "site_url": "http://192.168.1.237:5244",
  "cdn": "",
```

### Reproduction / 复现链接

None

**Comment by Xhofe** [comment]
https is required.

**Comment by drewbitt** [comment]
Yes. That is undocumented as far as I can see.

**Comment by drewbitt** [comment]
OK, missed that documentation.
