### ISSUE TITLE
Storage XSS vulnerability

### ISSUE THREAD

**Issue by Shydlock** [alist-org/alist#2457]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

**A storage xss vulnerability exists at the site's bulletin board**

- Enter the malicious xss payload here
![image](https://user-images.githubusercontent.com/52377340/203464066-7d01c0f7-4b43-4f20-9375-d9fee7e8955d.png)

- Visit the website homepage, and will find the payload  has been executed
![image](https://user-images.githubusercontent.com/52377340/203464157-40ce0bb0-1f9f-43ee-860a-dc4c306c93d1.png)

### Reproduction / 复现链接

<script>alert(111);</script>

**Comment by Xhofe** [comment]
This can only be modified by the admin user. But you can do anything if you are admin user.
