### ISSUE TITLE
离线下载功能可以添加torrent文件

### ISSUE THREAD

**Issue by karma-sun** [alist-org/alist#2459]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

离线下载功能可以添加torrent文件,并可以选择只下载torrent中选定的文件

### Suggested solution / 实现思路

类似迅雷和百度云提供的离线下载

**Comment by mengguyi** [comment]
其实有一个曲线救国的办法，离线下载支持torrent的链接（不是磁力链）只需把torrent上传到alist再添加到离线下载里

https://user-images.githubusercontent.com/73788063/208114988-a3e04dbd-35e8-42d7-aa9d-4f2681f319e9.mp4

**Comment by kimycai** [comment]
> 其实有一个曲线救国的办法，离线下载支持torrent的链接（不是磁力链）只需把torrent上传到alist再添加到离线下载里

此方法可行，**但**有个问题，就是下载完后，种子没有在qbittorrent队列中做种，既没有下载记录，也没有做种记录，这个能不能修正？

**Comment by m0ch3** [comment]
> > 其实有一个曲线救国的办法，离线下载支持torrent的链接（不是磁力链）只需把torrent上传到alist再添加到离线下载里
> 
> 此方法可行，**但**有个问题，就是下载完后，种子没有在qbittorrent队列中做种，既没有下载记录，也没有做种记录，这个能不能修正？

#3588
