### ISSUE TITLE
威联通提示libc.so.6版本过低不可运行

### ISSUE THREAD

**Issue by iranee** [alist-org/alist#2463]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.5.1

### Driver used / 使用的存储驱动

webdav

### Describe the bug / 问题描述

一直用的QNAP的NAS运行打包好的x86_64二进制
一直到3.4.0版本都没有问题，最新版3.5.1提示NAS的依赖包过旧不可运行
alist-3.5.1: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /alist/alist-3.5.1)

NAS的libc.so版本：
 strings /lib64/libc.so.6 | grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_PRIVATE

### Reproduction / 复现链接

alist-3.5.1: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /alist/alist-3.5.1)

### Logs / 日志

```shell
alist-3.5.1: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /alist/alist-3.5.1)
```

**Comment by Xhofe** [comment]
use musl version please.
