### ISSUE TITLE
备份恢复功能支持导入从V2版备份的json数据

### ISSUE THREAD

**Issue by karma-sun** [alist-org/alist#2468]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

备份恢复功支持导入从V2版备份的json数据
可以仅恢复存储相关的数据，这部分数据太多了

**Comment by Xhofe** [comment]
不考虑支持。
