### ISSUE TITLE
failed get link: ForbiddenNoPermission.File:No Permission to access resource File

### ISSUE THREAD

**Issue by youyifentian** [alist-org/alist#2472]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.5.1

### Driver used / 使用的存储驱动

阿里云盘分享

### Describe the bug / 问题描述

阿里云盘分享挂载成功，目录可以正常访问，但是文件无法访问，提示failed get link: ForbiddenNoPermission.File:No Permission to access resource File

### Reproduction / 复现链接

https://cloud.xday.icu:5244/at/B%20%E8%9D%99%E8%9D%A0%E4%BE%A0%E7%B3%BB%E5%88%974K%20REMUX%204%E9%83%A8%E5%85%A8/B%20%E8%9D%99%E8%9D%A0%E4%BE%A01%204K%20REMUX%20%EF%BC%881989%EF%BC%89%E3%80%900568%E3%80%91

打开链接后，点击任意文件访问即报错

**Comment by NovaShen0724** [comment]
我也遇到此问题，希望解决
