### ISSUE TITLE
alist.nn.ci/v3.sh脚本在debian 11上运行会导致curl无法使用

### ISSUE THREAD

**Issue by YIKE2020** [alist-org/alist#2478]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

在运行
`curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s install`
之后，发现再次调用curl指令之后会报错：
`curl: command not found`
但是在运行
`apt-get update -y && apt-get install curl -y`
之后，显示
`0 upgraded, 0 newly installed, 0 to remove and 69 not upgraded.`
通过重装curl可以解决这个问题,但reboot没有效果
之后经过对sh文件的逐行执行，发现在执行类似
`INSTALL_PATH=xxx`
的指令后就会产生此问题
阿里云的机，系统为 Debian 11.3
怀疑这个叫做"INSTALL_PATH"的变量可能和Debian中的系统环境变量冲突，导致出现问题

### Reproduction / 复现链接

`curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s install`

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/203901909-e01604f3-eafe-48db-9982-9f0bb6dcaaf5.png)
无法复现

**Comment by YIKE2020** [comment]
在其他服务器上确实没有这个问题，可能是阿里云的特色吗2333
先docker部署着用吧
