### ISSUE TITLE
增加后台网盘缓存更新按钮

### ISSUE THREAD

**Issue by yale8888** [alist-org/alist#2479]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增加后台网盘缓存更新按钮
有时上传了新的文件，好久前端不显示。建议能手动更新缓存的功能。
达到上传文件以后更新文件缓存能马上在前端就能显示。

**Comment by yale8888** [comment]
期待更新

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/203901566-f3edd871-4933-4a82-a8fb-13cf5097ce79.png)
