### ISSUE TITLE
增加网盘内的搜索功能

### ISSUE THREAD

**Issue by tushanxing** [alist-org/alist#2481]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

对各个网盘内的文件增加搜索功能

**Comment by fish2018** [comment]
+1
