### ISSUE TITLE
作者你好 我想问下Alist挂载本地存储的webdav为什么图片预览全是碎的 但我上传到网盘后 再挂载网盘图片就有预览图了

### ISSUE THREAD

**Issue by cuixuhong123** [alist-org/alist#2483]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

WEBDAV

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/50816484/203911429-38b921b4-0512-48e8-8593-a61cd67c5ff7.png)

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
thumbnail由对应存储提供。

**Comment by cuixuhong123** [comment]
thumbnail 格式什么
