### ISSUE TITLE
aria2错误

### ISSUE THREAD

**Issue by Gumingjie0312** [alist-org/alist#2496]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

服务器上有aria2，但是alist却提示Aria2 not ready

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/other.html#aria2
