### ISSUE TITLE
改进上传部分的设计

### ISSUE THREAD

**Issue by makergit365** [alist-org/alist#2497]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在总是稀里糊涂上传失败，开了秒传，有的失败了，我拉出来单独重试成功了，有的死活不成功，我用pc客户端秒传成功，确定不能秒传的，我关闭秒传有的能上传有的又不能。我是真想找出来一些规律给你反馈，但我折腾了几次实在找不来，所以只能在这给你提，我只能确定的是秒传时失败，日志里都是一样的，不管我后来拉出来单试成功没成功，所以也没什么报错日志给你。我关闭秒传时，上传失败的哪些在web里明显的特征就是精度条走的很快，走完就失败，我上行小水管，正常跑满上行精度条也是龟速才对。
我弄了几天但是真没啥报错日志给你，因为日志里没法分辨错误，所以还是麻烦你手动排查吧。我希望的理想状态是达到pc客户端的水平，秒传不成功就自动转普通上传，或者给个按钮手动开启这个任务的普通上传，最后还不成功只能是文件违规，然后给个标签就行。

**Comment by Xhofe** [comment]
无法做到，上传本来就是一个很复杂的设计，大部分存储都做了各种加密。除非是有公开api，否则这种抓包出来的接口都无法做到像官方客户端一样的稳定性。

**Comment by makergit365** [comment]
> 无法做到，上传本来就是一个很复杂的设计，大部分存储都做了各种加密。除非是有公开api，否则抓包出来的接口都无法做到像官方客户端一样的稳定性。

我忘记说我是在不通的网盘里复制，不过也算是一种上传吧。对失败的能否加个重试选项呢，还有秒传失败的能不能自动或者手动去普通上传，现在批量上传有部分失败后，还得自己记下哪些失败了，然后去存储设置里取消秒传，再一个个找出来重新上传。这样的话即使没有客户端的稳定性也能很大程度上改变上传的体验。
