### ISSUE TITLE
Ubuntu挂载webdav api 出现无法读取文件里面的内容

### ISSUE THREAD

**Issue by hyh1750522171** [alist-org/alist#2499]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

docker   xhofe/alist:latest  id: 3ce2152396a5

### Driver used / 使用的存储驱动

阿里云盘    ubuntu使用  davfs2  挂载  

### 服务器系统 centos 7.9
当时使用这个命令下载启动容器的
```bash
  56  2022-11-25 10:16:49 docker run -d --restart=always -v /opt/alist:/opt/alist/data -p 5244:5244 --name="alist" xhofe/alist:latest
```

### 使用系统
挂载操作系统：ubuntu 20.04 lts 
挂载软件 ：  apt install davfs2
挂载方式： mount -t davfs http://x.x.x.x:5244/dav/  /webdav/

### Reproduction / 复现链接

```bash
root@MAC:/webdav/阿里网盘/贺/code/shell# cat admin-react.js
cat: admin-react.js: 输入/输出错误
```
出现上面问题
拷贝复制都出错。

**Comment by Xhofe** [comment]
set `native proxy` for https://alist.nn.ci/guide/drivers/common.html#webdav-policy to improve compatibility
