### ISSUE TITLE
v3 一键升级后 出错

### ISSUE THREAD

**Issue by qian9008** [alist-org/alist#2500]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3最新

### Driver used / 使用的存储驱动

多个

### Describe the bug / 问题描述

 alist.service - Alist service
   Loaded: loaded (/etc/systemd/system/alist.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2022-11-26 19:35:07 CST; 1s ago
  Process: 4257 ExecStart=/opt/alist/alist server (code=exited, status=1/FAILURE)
 Main PID: 4257 (code=exited, status=1/FAILURE)

Nov 26 19:35:06 DSM systemd[1]: Started Alist service.
Nov 26 19:35:06 DSM systemd[1]: Starting Alist service...
Nov 26 19:35:07 DSM alist[4257]: INFO[2022-11-26 19:35:07] reading config file: data/config.json
Nov 26 19:35:07 DSM alist[4257]: INFO[2022-11-26 19:35:07] load config from env with prefix: ALIST_
Nov 26 19:35:07 DSM alist[4257]: INFO[2022-11-26 19:35:07] init logrus...
Nov 26 19:35:07 DSM alist[4257]: 2022/11/26 19:35:07 failed migrate database: table x_storages__temp has no column named UNIQUE
Nov 26 19:35:07 DSM systemd[1]: alist.service: main process exited, code=exited, status=1/FAILURE
Nov 26 19:35:07 DSM systemd[1]: Unit alist.service entered failed state.
Nov 26 19:35:07 DSM systemd[1]: alist.service failed.

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
check your database yourslef otherwise reinstall plaese.

**Comment by qian9008** [comment]
数据库 之前用的正常，怎么升级后就错了呢？ 数据库多了字段没成功升级？

**Comment by qian9008** [comment]
> check your database yourslef otherwise reinstall plaese.

把老库的  x_storages 替换 到新的，仍然出错。

**Comment by laoqijun** [comment]
> 

把name这个项目的主键和索引删了，类型改成lognext即可解决。
