### ISSUE TITLE
上传大文件时出错

### ISSUE THREAD

**Issue by NianBroken** [alist-org/alist#2502]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.5.1

### Driver used / 使用的存储驱动

全部储存

### Describe the bug / 问题描述

上传大文件时提示
Cannot read properties of undefined (reading 'status')
![image](https://user-images.githubusercontent.com/57057288/204096785-a803edbb-e5ed-48ab-a0cc-4b056c65dfba.png)

### Reproduction / 复现链接

none

### Logs / 日志

```shell
none
```

**Comment by shenuadm** [comment]
我也有这个问题，请问解决了吗

**Comment by wujianzhijing** [comment]
我也有这个问题，经过多次试验，发现是alist会优先将文件放入缓存目录导致的，硬盘份额并没有文件那么大，所以会报错。

**Comment by loong22** [comment]
使用http方式上传没问题，但是切换到https就会遇到你这个问题。目前没有解决，上传大文件直接用http就行，日常使用还是https
