### ISSUE TITLE
建议：阿里云分享自动识别链接

### ISSUE THREAD

**Issue by qianku** [alist-org/alist#2506]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议自动识别分享链接的分享ID和根文件夹ID，这样可以加添加的时候更加快速填写

### Suggested solution / 实现思路

如粘贴链接：https://www.aliyundrive.com/s/W45tEztzdsq/folder/637cef5009badf8322bf4649a79595cb116c60ff
可以自动识别
shareID=W45tEztzdsq
Root folder id=637cef5009badf8322bf4649a79595cb116c60ff

**Comment by Bennie-CHEN** [comment]
up

**Comment by swRains** [comment]
复议，其他的分享链接也可以识别就好了
以下项目油猴脚本“网盘智能识别助手”有该功能
https://github.com/syhyz1990/panAI

**Comment by swRains** [comment]
如果可以混合批量添加就更好了，但那种工程量可能会有点大。我还是觉得把储存页做成列表的形式会好一点，可以批量管理和修改

**Comment by fcwys** [comment]
附议

**Comment by BoYanZh** [comment]
实现这个功能不该在alist里，应该也是别的油猴脚本识别到这些信息然后调用alist的API帮你自动挂载

**Comment by karma-sun** [comment]
> 实现这个功能不该在alist里，应该也是别的油猴脚本识别到这些信息然后调用alist的API帮你自动挂载

现在有没有脚本能实现一键自动挂载？

**Comment by BoYanZh** [comment]
> > 实现这个功能不该在alist里，应该也是别的油猴脚本识别到这些信息然后调用alist的API帮你自动挂载
> 
> 现在有没有脚本能实现一键自动挂载？

自己动手丰衣足食

**Comment by chengnan049** [comment]
> > > > 实现这个功能不该在alist里，应该也是别的油猴脚本识别到这些信息然后调用alist的API帮你自动挂载
> > > 
> > > 
> > > 现在有没有脚本能实现一键自动挂载？
> > 
> > 自己动手丰衣足食
> 
> 
> 
> 有的，github上有一个，不记得名字了，搜关键词 添加 alist

似乎是 [alist_batch_add](https://github.com/yzbtdiy/alist_batch_add) 项目 ？

**Comment by HughRyu** [comment]
> 实现这个功能不该在alist里，应该也是别的油猴脚本识别到这些信息然后调用alist的API帮你自动挂载

没理解lz的意思吧.就是在alist创建阿里云盘分享的时候,直接粘进去完成阿里云盘分享地址,自动可以识别分享ID和目录,无需手动拆分.

lz提议的很好,而且还有一个就是阿里云盘的Cookie直接保存好,添加分享链接时候,没必要每次都要填cookie啊,自动调用更简便.
