### ISSUE TITLE
开启完毕访问网盘时出现故障

### ISSUE THREAD

**Issue by lumineyuri** [alist-org/alist#2511]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

最新DEV

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

开启完毕访问网盘时出现该故障
Releases 版本无该故障

### Reproduction / 复现链接

无

### Logs / 日志

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x1d082b7]

goroutine 157 [running]:
github.com/alist-org/alist/v3/internal/search.Update({0xc00089f710, 0x6}, {0xc0001a8e00, 0x8, 0xc00045c050?})
        /source/internal/search/update.go:14 +0x57
github.com/alist-org/alist/v3/internal/op.List.func1.1()
        /source/internal/op/fs.go:65 +0x74
created by github.com/alist-org/alist/v3/internal/op.List.func1
        /source/internal/op/fs.go:63 +0x118
```

**Comment by Xhofe** [comment]
wip 不保证可用
