### ISSUE TITLE
Embed pdf.js/web/viewer.html in AList binary

### ISSUE THREAD

**Issue by BoYanZh** [alist-org/alist#2530]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

It is unstable for users from Mainland China to access github.io, may be it is better to embed that HTML file in the program and let user to set the js file links from a cdn site?
Not sure whether it is a good idea.

**Comment by mengguyi** [comment]
部分中国大陆地区会对*.github.io进行封锁但是大部分地区并不会这样做。
而且PDF.js的url可以在`Iframe 预览`中进行修改，用户可以自行决定它的位置

**Comment by BoYanZh** [comment]
问题就在于部分地区会封锁，而现在最好的办法是找到一个架设在国内的能提供viewer.html的源或者直接内嵌，但cdn站点只提供js

**Comment by BoYanZh** [comment]
得看看有没有好心人搞一套备案好的gitee pages

**Comment by mengguyi** [comment]
据我观察，某些地区会对*.github.io进行sni阻断，所以域名别用github.io就行

**Comment by BoYanZh** [comment]
> 问题就在于部分地区会封锁，而现在最好的办法是找到一个架设在国内的能提供viewer.html的源或者直接内嵌，但cdn站点只提供js

cdn站点还不提供locale文件以及svg 需要打包的内容更多了 alist-org/alist-web#39 已经嵌入epub.js
