### ISSUE TITLE
PDF.js 无法预览 PDF 文件

### ISSUE THREAD

**Issue by xlenco** [alist-org/alist#2538]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.5

### Driver used / 使用的存储驱动

所有存储驱动

### Describe the bug / 问题描述

PDF.js 无法
![Uploading Screenshot_2022-11-30-17-55-04-39.jpg…]()
预览 PDF 文件

### Reproduction / 复现链接

https://solitude.eu.org/AliDrive/%E5%AD%A6%E4%B9%A0%E7%9B%B8%E5%85%B3/%E5%88%9D%E4%B8%AD%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%96%99/%E7%9F%A5%E8%AF%86%E6%B1%87%E6%80%BB/%E5%88%9D%E4%B8%AD%E8%8B%B1%E8%AF%AD%E7%9F%A5%E8%AF%86%E5%9B%BE%E8%B0%B1.pdf

**Comment by without-yy** [comment]
可以在设置->Iframe 预览中的pdf里添加一项iframe直接调用浏览器本地的解析
```
"pdf": {
		 "iframe":"$url",
		 "PDF.js":"https://alist-org.github.io/pdf.js/web/viewer.html?file=$e_url"
},
```

**Comment by woshichenghaibo** [comment]
> 可以在设置->Iframe 预览中的pdf里添加一项iframe直接调用浏览器本地的解析
> 
> ```
> "pdf": {
> 		 "iframe":"$url",
> 		 "PDF.js":"https://alist-org.github.io/pdf.js/web/viewer.html?file=$e_url"
> },
> ```

默认就是有这个的，但是还是不行

**Comment by songxingguo** [comment]
> "pdf": {
> 		 "iframe":"$url",
> 		 "PDF.js":"https://alist-org.github.io/pdf.js/web/viewer.html?file=$e_url"
> },
会自动下载，而不是预览
