### ISSUE TITLE
Param --data dosen't work correctly

### ISSUE THREAD

**Issue by qq57240** [alist-org/alist#2542]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

115 189 aliyundrive onedrive

### Describe the bug / 问题描述

When using the cmd "alist --data /etc/alist server" in ubuntu 22.04 the param "--data" dosen't work correctly. It spawns all data files in the home directory even the console shows 'reading /etc/alsit/config.json'. 

### Reproduction / 复现链接

None

### Logs / 日志

```shell
root@CloudCone:~# rm  -rf /root/data
root@CloudCone:~# ./alist version
Built At: 2022-11-22 13:22:07 +0000
Go Version: go1.19.2 linux/amd64
Author: Noah Hsu <i@nn.ci>
Commit ID: 2b902de
Version: v3.5.1
WebVersion: 3.5.0
root@CloudCone:~# ll /etc/alist/
total 64
drwxr-xr-x   4 root root  4096 Dec  1 08:46 ./
drwxr-xr-x 110 root root  4096 Dec  1 08:40 ../
-rw-r--r--   1 root root   613 Dec  1 09:03 config.json
-rw-r--r--   1 root root 45056 Dec  1 08:44 data.db
drwxr-xr-x   2 root root  4096 Dec  1 08:46 log/
drwxr-xr-x   2 root root  4096 Dec  1 08:46 temp/
root@CloudCone:~# ./alist --data /etc/alist/ server
INFO[2022-12-01 09:19:51] reading config file: /etc/alist/config.json
INFO[2022-12-01 09:19:51] load config from env with prefix: ALIST_
INFO[2022-12-01 09:19:51] init logrus...
INFO[2022-12-01 09:19:51] Successfully created the admin user and the initial password is: tkxj5ovM
INFO[2022-12-01 09:19:51] Aria2 not ready.
INFO[2022-12-01 09:19:51] start server @ 0.0.0.0:5244
^CINFO[2022-12-01 09:19:57] Shutdown Server ...
INFO[2022-12-01 09:19:58] timeout of 1 seconds.
INFO[2022-12-01 09:19:58] Server exiting
root@CloudCone:~# ll /root/data
total 48
drwxr-xr-x 3 root root  4096 Dec  1 09:19 ./
drwx------ 9 root root  4096 Dec  1 09:19 ../
-rw-r--r-- 1 root root 36864 Dec  1 09:19 data.db
drwxr-xr-x 2 root root  4096 Dec  1 09:19 temp/
```

**Comment by Xhofe** [comment]
I don't know what's wrong with this, you already have config.json under '/etc/alist' and the program will only read the configuration in it by default instead of using the command-line arguments. Command line arguments will only be written to the configuration if 'config.json' is not available

**Comment by qq57240** [comment]
> I don't know what's wrong with this, you already have `config.json` under `/etc/alist` and the program will only read the configuration in it by default instead of using the command-line arguments. Command line arguments will only be written to the configuration if `config.json` doesn't exist.

I copied the data directory from another server. I hope the alist binary to use this configuration, but it dosen't work. The binary ignores /etc/data/config.json and spawns new files in home directory. 

INFO[2022-12-01 09:19:51] reading config file: /etc/alist/config.json （There has password in.）
INFO[2022-12-01 09:19:51] load config from env with prefix: ALIST_
INFO[2022-12-01 09:19:51] init logrus...
INFO[2022-12-01 09:19:51] Successfully created the admin user and the initial password is: tkxj5ovM （and here is a new password spawned）

**Comment by Xhofe** [comment]
You can read the content of `/etc/alist/config.json`. The program would follow the configuration in it. If the path  in it is relative path, it will use current dir (the dir of binary) as prefix.
