### ISSUE TITLE
今天突然出现Token is expired，使用账户登录也是Token is expired

### ISSUE THREAD

**Issue by superdobo** [alist-org/alist#2554]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.4.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

使用反向代理的域名直接进不去，跳转到登录界面，显示Token is expired，使用账户进行登录，显示弹出登录成功界面，然后又弹出Token is expired
在本地访问不会出现此状况，Nginx缓存已关闭，询问是什么状况

### Reproduction / 复现链接

https://tva3.sinaimg.cn/large/008w1auWly8h8pe90b853j31400nw0v7.jpg

**Comment by starsflows666** [comment]
一样的问题，请问解决了吗

**Comment by wanshanhong11** [comment]
我也遇到了，不过呢，我什么都没做，等了一会儿，大概1-3分钟吧，我浏览了一个网页回来，就没有token is expired的提示了

**Comment by IhaveBB** [comment]
![image](https://github.com/alist-org/alist/assets/115210411/03beda75-1c55-416c-96a2-2206b31f2038) 我关闭这里就好了
