### ISSUE TITLE
115文件列表显示重复/不完整

### ISSUE THREAD

**Issue by andyai1992** [alist-org/alist#2564]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

在群晖DS920+上以docker方式安装后，网页和WebDAV都只能显示目录内部分文件，并且还出现了一个文件夹重复显示多次的情况
<img width="925" alt="image" src="https://user-images.githubusercontent.com/13974663/205433794-215d91e0-3e27-4310-beb3-ef6397b363b9.png">

### Reproduction / 复现链接

none

**Comment by Xhofe** [comment]
dependence: https://github.com/SheltonZhu/115driver
