### ISSUE TITLE
用https://xxxx.con:1234/d/可以不用密码下载任何文件

### ISSUE THREAD

**Issue by AaronHzy** [alist-org/alist#2568]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

用https://xxxx.con:1234/d/可以不用密码下载任何文件
如果知道了目录结构，就可以下载任何文件，元信息加密无效
希望可以修复这个漏洞

### Reproduction / 复现链接

xxx

**Comment by BoYanZh** [comment]
Done in ff0bcfef8ac0516640099276c748758f55020aeb.
