### ISSUE TITLE
支援命令列模式進行設定?

### ISSUE THREAD

**Issue by changchichung** [alist-org/alist#2579]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在命令模式下，直接對alist 進行操作，例如新增/刪除使用者、新增/修改/刪除 storage 等等設定

### Suggested solution / 实现思路

我想要讓使用者(約100+ accounts) 能夠透過 alist 去存取 webdav
現在的設定方式，是我需要手動建立這些webdav sotage 以及使用者帳號，然後指定使用者的HomeDIR
如果可以在命列模式操作，那就可以很簡單的用script 來執行，效率會快很多！

**Comment by Xhofe** [comment]
其实你可以通过api去建立账户。也可以很簡單的用script 來執行
