### ISSUE TITLE
alist指定--data运行不起作用

### ISSUE THREAD

**Issue by rockxsj** [alist-org/alist#2580]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

none

### Describe the bug / 问题描述

``` powershell
PS C:\Users\xxx\.config\alist> alist server --data C:\Users\xxx\.config\alist --no-prefix
INFO[2022-12-05 11:32:04] reading config file: C:\Users\xxx\scoop\apps\alist\current\data\config.json
INFO[2022-12-05 11:32:04] load config from env with prefix:
INFO[2022-12-05 11:32:04] init logrus...
INFO[2022-12-05 11:32:07] Aria2 not ready.
INFO[2022-12-05 11:32:07] start server @ 0.0.0.0:5244
```
指定了`--data` flag，还是从默认位置启动

### Reproduction / 复现链接

直接看描述

**Comment by Xhofe** [comment]
你这里使用的似乎是通过scoop安装的alist，它默认会添加--force-bin-dir参数以强制使用二进制所在文件夹作为数据目录。

**Comment by rockxsj** [comment]
``` powershell
PS C:\Users\xxx> scoop cat dev-tools/alist
{
    "version": "3.5.1",
    "description": "A file list program that supports multiple storage, powered by Gin and Solidjs.",
    "homepage": "https://alist.nn.ci",
    "license": "AGPL-3.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/alist-org/alist/releases/download/v3.5.1/alist-windows-amd64.zip",
            "hash": "md5:0c45b568946c2e11f06301b420cbe418"
        },
        "32bit": {
            "url": "https://github.com/alist-org/alist/releases/download/v3.5.1/alist-windows-386.zip",
            "hash": "md5:ad5fc7244cfa2e4fada18b6d196a3638"
        }
    },
    "bin": [
        [
            "alist.exe",
            "alist",
            "--force-bin-dir"
        ]
    ],
    "persist": [
        "data",
        "log"
    ],
    "checkver": {
        "github": "https://github.com/alist-org/alist"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/alist-org/alist/releases/download/v$version/alist-windows-amd64.zip"
            },
            "32bit": {
                "url": "https://github.com/alist-org/alist/releases/download/v$version/alist-windows-386.zip"
            }
        },
        "hash": {
            "url": "$baseurl/md5.txt"
        }
    }
}
```
还真是这样。。   离谱   为啥要修改默认行为啊   不理解

**Comment by chengnan049** [comment]
> ``` powershell
> PS C:\Users\xxx> scoop cat dev-tools/alist
> {
>     "version": "3.5.1",
>     "description": "A file list program that supports multiple storage, powered by Gin and Solidjs.",
>     "homepage": "https://alist.nn.ci",
>     "license": "AGPL-3.0-or-later",
>     "architecture": {
>         "64bit": {
>             "url": "https://github.com/alist-org/alist/releases/download/v3.5.1/alist-windows-amd64.zip",
>             "hash": "md5:0c45b568946c2e11f06301b420cbe418"
>         },
>         "32bit": {
>             "url": "https://github.com/alist-org/alist/releases/download/v3.5.1/alist-windows-386.zip",
>             "hash": "md5:ad5fc7244cfa2e4fada18b6d196a3638"
>         }
>     },
>     "bin": [
>         [
>             "alist.exe",
>             "alist",
>             "--force-bin-dir"
>         ]
>     ],
>     "persist": [
>         "data",
>         "log"
>     ],
>     "checkver": {
>         "github": "https://github.com/alist-org/alist"
>     },
>     "autoupdate": {
>         "architecture": {
>             "64bit": {
>                 "url": "https://github.com/alist-org/alist/releases/download/v$version/alist-windows-amd64.zip"
>             },
>             "32bit": {
>                 "url": "https://github.com/alist-org/alist/releases/download/v$version/alist-windows-386.zip"
>             }
>         },
>         "hash": {
>             "url": "$baseurl/md5.txt"
>         }
>     }
> }
> ```
> 还真是这样。。   离谱   为啥要修改默认行为啊   不理解

一直都是的，软件的数据放在统一目录
