### ISSUE TITLE
希望支持配置samba共享

### ISSUE THREAD

**Issue by stevenliuit** [alist-org/alist#2590]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望支持配置samba共享，发现里面支持sftp但是不支持samba局域网内的东西链接，求支持

**Comment by BoYanZh** [comment]
https://github.com/alist-org/alist/releases/tag/v3.3.0 不是有了么
