### ISSUE TITLE
titen

### ISSUE THREAD

**Issue by mj5219054** [alist-org/alist#2591]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.1

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

挂载OneDri成功无法获取对象失败：无法列出对象：未找到段的子项的资源

### Reproduction / 复现链接

![图片](https://user-images.githubusercontent.com/79394963/205646536-a1a9f2f4-1c1b-4bb8-94a6-ea08f8004411.png)

**Comment by Xhofe** [comment]
Check your storage config yourself.
