### ISSUE TITLE
 failed to open start log file:open /home/kk/bin/alist/daemon/start.log: no such file or directory

### ISSUE THREAD

**Issue by vipzrx** [alist-org/alist#2594]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

1

### Driver used / 使用的存储驱动

1

### Describe the bug / 问题描述

我的环境 debian x64 

 curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s install /home/kk/bin/

> 出错了，请使用 root 权限重试！
> 
> 
> 
> (23) Failed writing body

添加sudo

curl -fsSL "https://alist.nn.ci/v3.sh" |sudo  bash -s install /home/kk/bin/

```
Alist 安装成功！

访问地址：http://YOUR_IP:5244/

配置文件路径：/home/kk/bin/alist/data/config.json
$查看管理员信息，请执行
cd /home/kk/bin/alist
./alist admin

查看状态：systemctl status alist
启动服务：systemctl start alist
重启服务：systemctl restart alist
停止服务：systemctl stop alist

```
是最新版本

kk@H7 ~/bin/alist ❯ ./alist version
```
Built At: 2022-12-05 13:55:03 +0000
Go Version: go1.19.3 linux/amd64
Author: Noah Hsu <i@nn.ci>
Commit ID: f1a9b68
Version: v3.6.0

```

启动报错

kk@H7 ~ ❯ alist start
`FATA[2022-12-06 00:04:06] 86362: failed to open start log file:open /home/kk/bin/alist/daemon/start.log: no such file or directory
`

这是我自己的home目录,应该有写权限.可能问题出在安装的时候用了sudo 

### Reproduction / 复现链接

1

**Comment by Xhofe** [comment]
使用脚本安装请使用root用户启动，普通用户请手动安装。
