### ISSUE TITLE
docker 桥接网络模式下无法正常访问

### ISSUE THREAD

**Issue by CN-traveler** [alist-org/alist#2596]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

docker 创建了一个自定义桥接网络，网关 10.0.0.1 子网 10.0.0.0/8。
在此网络下有两个容器 nginx alist，其中 nginx 容器绑定宿主机 80 、 443 端口，nginx 通过反向代理将 alist 绑定到域名 xxx.com 。
在访问 xxx.com 时，发现视频无法加载，通过开发者调试工具发现前端网络请求为 alist:5244 此地址为 docker 内部地址，故无法访问。于是我尝试配置下载代理URL为 xxx.com/p | xxx.com | xxx.com/d，后发现会导致死循环重定向。

### Reproduction / 复现链接

无法提供。
![image](https://user-images.githubusercontent.com/55753029/205768204-b3eb1df1-b9d8-4678-b6f9-62b7bb1ea2e7.png)

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/configuration.html#site-url
