### ISSUE TITLE
在文件夹是空的情况下切换成列表模式会变成白条

### ISSUE THREAD

**Issue by happytbs** [alist-org/alist#2605]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/74001578/205802214-41678da9-7b83-4783-ba6a-10700e564dcb.png)
在文件夹是空的情况下切换成列表模式会变成白条，看着很别扭

### Reproduction / 复现链接

http://dl.star-fish.top/%E6%B5%8B%E8%AF%95/%E5%85%B6%E4%BB%96

**Comment by Xhofe** [comment]
所以？你觉得这是个bug吗

**Comment by happytbs** [comment]
> 所以？你觉得这是个bug吗

哪怕加个文件夹是空的也行a……
