### ISSUE TITLE
不支持中文搜索

### ISSUE THREAD

**Issue by steinvenic** [alist-org/alist#2606]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

- 索引类型：Bleve
- 搜索关键字`exe`，有搜索结果
- 搜索`反编译`，无结果
- 对应关键字路径：`https://alist.00123.fun/tank/%E9%80%86%E5%90%91`

### Reproduction / 复现链接

https://alist.00123.fun/tank/%E9%80%86%E5%90%91

**Comment by Xhofe** [comment]
bleve的分词很奇怪 不一定会得到你想要的结果，如果你想完全匹配关键字可以选择使用数据库索引。

如果想要改进bleve，可以去bleve的仓库提issue。
