### ISSUE TITLE
模态框关闭按钮建议放到右上角

### ISSUE THREAD

**Issue by fcwys** [alist-org/alist#2607]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

模态框关闭按钮建议放到右上角，最新3.6.0版本的关闭按钮有点错乱

### Suggested solution / 实现思路

建议如图：
![image](https://user-images.githubusercontent.com/28641034/205818245-340e8a7d-4e08-45d9-ad97-a4c4743d6f75.png)

**Comment by ma3252788** [comment]
请问搜索框怎么调出来呀？

**Comment by BoYanZh** [comment]
我这看到的关闭按钮确实就在右上角

**Comment by fcwys** [comment]
> 

最新版本的
