### ISSUE TITLE
挂载阿里云盘分享时，大于25G的视频资源无法播放

### ISSUE THREAD

**Issue by bigbigking** [alist-org/alist#2609]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

阿里云盘分享

### Describe the bug / 问题描述
阿里云盘分享的情况：
在AList中的存储添加「阿里云盘分享」驱动的存储，如这个https://www.aliyundrive.com/s/xeUqbtve9Pi/folder/637575062723d704a9e44fbabb905db3763ed31a
用「A账号」登录阿里云盘取得refresh_token，添加存储正常，可以正常浏览以上分享里的目录和文件。但是用AList直接播放分享文件夹下的视频的时候出现问题，小于25G的可以直接播放，最大的那个25.55G的文件无法播放，重新连接5次后页面停止。
![image](https://user-images.githubusercontent.com/21093049/205836181-014c0abd-e97f-4426-841e-72519363e55b.png)

### Reproduction / 复现链接

[某阿里云盘分享：黑亚当](https://www.aliyundrive.com/s/xeUqbtve9Pi/folder/637575062723d704a9e44fbabb905db3763ed31a)

**Comment by Xhofe** [comment]
https://alist.nn.ci/faq/why.html#why-can-t-i-preview-the-video-or-audio-file

**Comment by bigbigking** [comment]
> https://alist.nn.ci/faq/why.html#why-can-t-i-preview-the-video-or-audio-file

感谢大佬的答复，才明白是因为大文件视频的编码原因导致的浏览器无法播放，使用推荐的播放器播放就搞定了。
