### ISSUE TITLE
搜索和索引不可用

### ISSUE THREAD

**Issue by nxjonson** [alist-org/alist#2610]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.6

### Driver used / 使用的存储驱动

所有

### Describe the bug / 问题描述

点击搜索框和管理的索引，都会出现提示：Search not available

### Reproduction / 复现链接

http://127.0.0.1:5244

**Comment by nxjonson** [comment]
![IMG_20221206_142249](https://user-images.githubusercontent.com/109280467/205838201-1a06f485-6b2d-43d5-a095-749aba538770.jpg)

**Comment by Xhofe** [comment]
选择一个索引保存。
