### ISSUE TITLE
在非alist网站根目录搜索得不到结果

### ISSUE THREAD

**Issue by mengguyi** [alist-org/alist#2611]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

在非alist网站根目录搜索得不到结果
比如在https://drive.mengguyi.com 里搜索 library 会得到 来自z-library。
在https://drive.mengguyi.com/图书 里搜索 library 没有结果

索引用的数据库，数据库为mysql

### Reproduction / 复现链接

https://drive.mengguyi.com
https://drive.mengguyi.com/图书

### Logs / 日志

ERRO[2022-12-05 15:10:02] init index error: readObjectStart: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...
WARN[2022-12-05 15:10:02] not enable search

**Comment by mengguyi** [comment]
索引状态
![image](https://user-images.githubusercontent.com/73788063/205846518-5e32dffb-b0de-48d4-87a4-b9ed507c1338.png)
bug视频

https://user-images.githubusercontent.com/73788063/205847647-4448daa6-b673-4e96-8845-e6fef5c8cd41.mp4

**Comment by Xhofe** [comment]
使用mysql5.7 无法复现
![image](https://user-images.githubusercontent.com/36558727/205850964-a2fdfe6c-22c0-4cd0-82cb-89aebd93938e.png)

**Comment by mengguyi** [comment]
好吧，我再试试看

**Comment by mengguyi** [comment]
用admin账户搜索没有问题但使用guest会触发

**Comment by mengguyi** [comment]
https://user-images.githubusercontent.com/73788063/205853403-67886728-854b-44cc-bf1b-80a7b9449ff3.mp4
