### ISSUE TITLE
重建索引文件出现502 bad gateway nginx

### ISSUE THREAD

**Issue by llyang1** [alist-org/alist#2616]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

onedrive googledrive ali

### Describe the bug / 问题描述

重建索引，大致5-8万条，就会出现502，重建就无法继续了。
nginx错误主要内容是：connect() failed (111: Connection refused) while connecting to upstream, client: 
restart nginx仍然502
安装php 7.4也不能改变
核实nginx status, php status正常
location直接从这里复制过来，简单修改端口 https://alist.nn.ci/faq/howto.html#how-to-reverse-proxy-with-sub-directory

reboot vps马上就可以访问了

个人建议: 设置暂停, 或者追加. 否则,永远都无法获得几十万条的索引

### Reproduction / 复现链接

更换一个VPS,仍然如此

### Logs / 日志

nginx error log

2022/12/06 08:59:33 [error] 1229#1229: *382 connect() failed (111: Connection refused) while connecting to upstream, client: 25.25.25.25, server: aaa.abc.com, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:5244/", host: "aaa.abc.com"

alist log, 这里罗列的最后几行

INFO[2022-12-06 11:49:08] index obj count: 72856                       
[GIN] 2022/12/06 - 11:49:08 | 200 |     834.906µs |    20.245.81.29 | POST     "/api/fs/get"
[GIN] 2022/12/06 - 11:49:08 | 200 |     931.407µs |    20.245.81.29 | POST     "/api/fs/list"
[GIN] 2022/12/06 - 11:49:08 | 200 |      80.901µs |    20.245.81.29 | GET      "/assets/icon.6bb85728.js"
[GIN] 2022/12/06 - 11:49:08 | 200 |     790.206µs |    20.245.81.29 | GET      "/assets/Folder.2e68dbc2.js"
[GIN] 2022/12/06 - 11:49:08 | 200 |     392.003µs |    20.245.81.29 | GET      "/assets/Folder.b511ba9e.css"
[GIN] 2022/12/06 - 11:49:08 | 200 |      82.801µs |    20.245.81.29 | GET      "/assets/List.a42ca9c9.js"
INFO[2022-12-06 11:49:13] index obj count: 72856                       
[GIN] 2022/12/06 - 11:49:14 | 200 |    1.868215ms |    20.245.81.29 | GET      "/api/admin/index/progress"

**Comment by Xhofe** [comment]
测试 100万+正常构建。

nginx无意义，请检查alist的日志和运行状态。

**Comment by llyang1** [comment]
找到问题的根源了

我手动下载这个覆盖升级或者安装
https://github.com/alist-org/alist/releases/download/v3.6.0/alist-linux-amd64.tar.gz
解压缩得到13475064字节
这样,就会出现我描述的问题

如果采用v3.sh全新安装或者升级
下载的文件是
https://github.com/Xhofe/alist/releases/latest/download/alist-linux-musl-amd64.tar.gz
解压缩得到40867944字节
这个重建索引没问题

在我这里使用,发现:
有问题的那个文件,创建索引速度比较快,也许这就是引起502的原因

请作者核实并更新第一个文件

**Comment by MrOldsix6** [comment]
![上传DAF9F019-95CE-481E-8360-656225235B66.jpeg...]()我没创建索引也会出现这样，几乎每天都会出现502 Bad Gateway，我每次都是重启服务器才能正常打开。请问我这怎么解决呀

**Comment by zhlx2835** [comment]
我也遇到了，你的怎么解决的？我之前从没有遇到过，最近升级到最新版v3.28.0频繁出现502 Bad Gateway
