### ISSUE TITLE
对大量文件建立索引时内存占用不断飙升

### ISSUE THREAD

**Issue by ma3252788** [alist-org/alist#2619]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.6.0

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

对大量的文件进行索引时 ，内存占用会不断增加，直到占满，然后服务器死机。
![image](https://user-images.githubusercontent.com/22229456/205935663-b2f22bc4-a9e2-4812-90d7-847a210dcbb7.png)
![](https://ypyssl.machunjie.com/machunjie/20221206221724-e58.png)

![image](https://user-images.githubusercontent.com/22229456/205935370-92947643-01f2-4730-9c64-9bedde553866.png)

### Reproduction / 复现链接

阿里云服务器

**Comment by ma3252788** [comment]
等死机我关闭的时候，大概索引了78万条数据。

**Comment by mengguyi** [comment]
我也用的mysql，在第一次建立索引时mysql+alist占用内存最高时5.7G但是没爆内存。总共建立了80万+的索引
如果你的服务器内存太小可以考虑在有足够内存的电脑上连接服务器的mysql建立索引。这样可能会缓解一下
或者考虑忽略一些不常用的路径来减少内存占用
毕竟80万的索引不好维护，建立一次要10多小时

**Comment by ma3252788** [comment]
> 我草，你们哪来搞的这么多，我觉得我四十万条已经够离谱的了

😸，主要是挂载的磁盘比较多，包括照片、文件啥的~~三十多T的空间，几百万文件应该还算正常吧😋

**Comment by ma3252788** [comment]
> 这无法fix 对于庞大的数据量，更好的机器是必要的 你只能通过降低缓存时间/增加内存 来保证不发生 out of memory

好吧，谢谢大佬~
