### ISSUE TITLE
希望增加一个"自动索引功能"

### ISSUE THREAD

**Issue by mengguyi** [alist-org/alist#2620]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist现在已经支持了文件搜索，这非常棒。但网盘每天都有新的文件放入，如果每次网盘同步文件后还需要点一下构建索引就有点麻烦，希望能弄一个每天定时执行的索引功能比如在 每天/每周/每月 的特定时间执行构建索引

### Suggested solution / 实现思路

alist现在已经支持了文件搜索，这非常棒。但网盘每天都有新的文件放入，如果每次网盘同步文件后还需要点一下构建索引就有点麻烦，希望能弄一个每隔一段时间执行的索引功能比如在 每天/每周/每月 的特定时间执行构建索引

### Additional context / 附件

草草地画了张示意图
![_WFOD1W9WI~N85{R3~KQEWL](https://user-images.githubusercontent.com/73788063/205945522-0aeb672e-0983-480f-8ab3-1d65adbb55ae.png)

**Comment by mengguyi** [comment]
对于录播站，rclone会自动上传录制完成的视频，而很多用户会在主播下播几小时内访问这些回放。所以如果可以希望弄一个循环索引，在索引完成后立刻开始下一次索引

**Comment by swRains** [comment]
看文档，数据库索引有该功能，另一个嘛，没有

**Comment by Xhofe** [comment]
1. 循环索引不现实 重建索引前会清除之前的所有数据，循环构建会导致大部分时间索引都是不完整的
2. 对于定时重建索引 目前不会考虑 你可以自行通过创建定时任务访问API实现
3. 更好的建议是使用database索引 只要用户访问了变动的目录 索引会自动更新，且为增量更新不需要完全重新构建。
