### ISSUE TITLE
能否增加指定路径索引？

### ISSUE THREAD

**Issue by ma3252788** [alist-org/alist#2621]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前的索引貌似只能全盘索引，即使某个盘某个路径只增删了一个文件。

请问能否增加对指定路径的索引？感觉这样可以大幅增加效率。

### Suggested solution / 实现思路

在一次全盘索引结束后，下次更新可以选择全盘或者指定路径索引。

不知道这种增量索引好不好实现。

**Comment by mengguyi** [comment]
是的，现在索引只能写黑名单，不索引那些目录。希望能增加白名单模式可以只针对某些路径进行索引

**Comment by BoYanZh** [comment]
我估计这个是 duplicate of #2593.

**Comment by ma3252788** [comment]
> 我估计这个是 duplicate of #2593.

是挺类似的

**Comment by ma3252788** [comment]
> bleve无法实现。database目前版本已经支持自动增量更新，当你访问有变动的目录，索引会自动更新。
> 
> 具体参见文档

谢谢
