### ISSUE TITLE
无法索引挂载目录

### ISSUE THREAD

**Issue by swRains** [alist-org/alist#2622]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

在索引时无法索引挂载目录：
如：
将多个阿里云盘分享资源（其他资源没试过）分别挂载在 /1           /2              /2/3   挂载路径时，无法检索1、2、3文件夹，但是1、2、3文件夹下文件可以检索到。
就是直接搜索挂载路径的名称无法检索到，但是资源下的内容还是能搜到。
产生一个问题就是有些资源比如说动漫，它文件名称不包含关键字或者是其他语言，只能通过文件夹检索，就有可能找不到资源。

### Reproduction / 复现链接

https://wegame.store/%E6%9C%8D%E5%8A%A1%E7%AB%AF%E3%80%81%E7%9F%A5%E4%B9%8E%E7%AD%89%E6%9D%82%E9%A1%B9%E8%B5%84%E6%BA%90/%E7%81%AB%E7%BB%92

主目录搜火绒搜不到该文件夹，但是能搜到该文件夹下的资源。其他主页的文件夹也搜不到。

**Comment by Xhofe** [comment]
你使用的是bleve索引 他的搜索结果无法控制、不可靠的，即使是完全匹配、它也可能搜索不到。

具体参见文档。

**Comment by swRains** [comment]
> 你使用的是bleve索引 他的搜索结果无法控制、不可靠的，即使是完全匹配、它也可能搜索不到。
> 
> 具体参见文档。

并不是，我用的是数据库索引，bleve构建索引太慢我就没用。

**Comment by swRains** [comment]
数据库索引依旧搜索不到，说明在构建索引时没有将其加入索引，期望开发者能将其加入索引目录，谢谢

**Comment by swRains** [comment]
储存目录如下
<img width="1280" alt="chrome_54C1iQ7smz" src="https://user-images.githubusercontent.com/96161478/206115995-b9860ed7-4c6d-49cf-803d-d75d160019ec.png">
