### ISSUE TITLE
添加存储alist v3 无法写入，删除文件

### ISSUE THREAD

**Issue by planxx** [alist-org/alist#2626]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

AList V3

### Describe the bug / 问题描述

添加存储alist v3 无法写入，删除文件

### Reproduction / 复现链接

随便添加一个alist v3存储就能复现了

### Logs / 日志

[GIN] 2022/12/07 - 04:50:36 | 200 |     904.302µs |   216.250.97.49 | GET      "/"
[GIN] 2022/12/07 - 04:50:36 | 200 |     909.992µs |   216.250.97.49 | GET      "/assets/index.659f4289.css"
[GIN] 2022/12/07 - 04:50:36 | 200 |    2.735044ms |   216.250.97.49 | GET      "/assets/index.3a80bc76.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |    1.007684ms |   216.250.97.49 | GET      "/assets/entry.56788660.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |    3.618686ms |   216.250.97.49 | GET      "/api/public/settings"
[GIN] 2022/12/07 - 04:50:37 | 200 |    2.032054ms |   216.250.97.49 | GET      "/api/me"
[GIN] 2022/12/07 - 04:50:37 | 200 |     152.379µs |   216.250.97.49 | GET      "/assets/useTitle.27a08ba5.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     334.375µs |   216.250.97.49 | GET      "/assets/Layout.6526da94.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |      45.838µs |   216.250.97.49 | GET      "/assets/useT.f153f830.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |    1.094216ms |   216.250.97.49 | GET      "/assets/Markdown.ab2170d8.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     302.956µs |   216.250.97.49 | GET      "/assets/api.7f233fde.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |      209.72µs |   216.250.97.49 | GET      "/assets/Layout.6526da94.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     112.044µs |   216.250.97.49 | GET      "/assets/FolderTree.5443c115.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     116.832µs |   216.250.97.49 | GET      "/assets/useUtil.a5be35bc.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     232.544µs |   216.250.97.49 | GET      "/assets/index.68d10b5a.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |      67.451µs |   216.250.97.49 | GET      "/assets/index.6289ff4c.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     143.148µs |   216.250.97.49 | GET      "/assets/useTitle.27a08ba5.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     141.907µs |   216.250.97.49 | GET      "/assets/useT.f153f830.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     551.753µs |   216.250.97.49 | GET      "/assets/Markdown.ab2170d8.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     158.884µs |   216.250.97.49 | GET      "/assets/api.7f233fde.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |      77.774µs |   216.250.97.49 | GET      "/assets/useUtil.a5be35bc.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |       53.13µs |   216.250.97.49 | GET      "/assets/index.6289ff4c.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |        73.3µs |   216.250.97.49 | GET      "/assets/FolderTree.5443c115.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     316.339µs |   216.250.97.49 | GET      "/assets/index.68d10b5a.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |    5.011812ms |   216.250.97.49 | POST     "/api/fs/get"
[GIN] 2022/12/07 - 04:50:37 | 200 |     2.54119ms |   216.250.97.49 | POST     "/api/fs/list"
[GIN] 2022/12/07 - 04:50:37 | 200 |     487.185µs |   216.250.97.49 | GET      "/assets/Folder.b511ba9e.css"
[GIN] 2022/12/07 - 04:50:37 | 200 |      72.838µs |   216.250.97.49 | GET      "/assets/icon.6bb85728.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     560.649µs |   216.250.97.49 | GET      "/assets/Folder.2e68dbc2.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     1.67899ms |   216.250.97.49 | GET      "/assets/index.3a80bc76.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     556.371µs |   216.250.97.49 | GET      "/assets/Folder.2e68dbc2.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     135.487µs |   216.250.97.49 | GET      "/assets/icon.6bb85728.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     323.786µs |   216.250.97.49 | GET      "/assets/List.a42ca9c9.js"
[GIN] 2022/12/07 - 04:50:37 | 200 |     133.577µs |   216.250.97.49 | GET      "/assets/List.a42ca9c9.js"
[GIN] 2022/12/07 - 04:50:46 | 200 |  965.825285ms |   216.250.97.49 | POST     "/api/fs/list"
[31mERRO[0m[2022-12-07 04:50:50] failed put /瑞典/: upload not supported
github.com/alist-org/alist/v3/internal/fs.putDirectly
	/home/runner/work/alist/alist/internal/fs/put.go:52
github.com/alist-org/alist/v3/internal/fs.PutDirectly
	/home/runner/work/alist/alist/internal/fs/fs.go:84
github.com/alist-org/alist/v3/server/handles.FsStream
	/home/runner/work/alist/alist/server/handles/fsup.go:49
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/alist-org/alist/v3/server/middlewares.FsUp
	/home/runner/work/alist/alist/server/middlewares/fsup.go:43
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/runner/work/alist/alist/server/middlewares/auth.go:55
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:11
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2947
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:1991
runtime.goexit
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/asm_amd64.s:1594 
[GIN] 2022/12/07 - 04:50:50 | 200 |   17.950804ms |   216.250.97.49 | PUT      "/api/fs/put"

**Comment by BoYanZh** [comment]
预期行为，要是登录的账号对该alist有修改权限那就直接去那个站上操作

**Comment by planxx** [comment]
> 预期行为，要是登录的账号对该alist有修改权限那就直接去那个站上操作

啊？不是吧？如果按照这个逻辑，那其他网盘，也可以直接到站上去操作。。。全部挂在一个alist中，不就是图方便吗？

**Comment by BoYanZh** [comment]
你要图方便为什么不把那个alist站的挂载直接放到单一的alist里

**Comment by planxx** [comment]
> 你要图方便为什么不把那个alist站的挂载直接放到单一的alist里

老哥，你把我弄糊涂了，我现在就是希望全部集中到一个alist来管理。
4台大盘VPS，都装了Alist，把VPS-B、C、D这三台，全部通过alist v3驱动挂到了VPS-A，现在的情况是VPS-A的Alist能读取挂过来的三台，但是从A无法向这三台写入文件。

**Comment by BoYanZh** [comment]
那你为什么不直接把VPS B C D的所有挂载放到VPS-A里而要绕一圈

**Comment by planxx** [comment]
> 那你为什么不直接把VPS B C D的所有挂载放到VPS-A里而要绕一圈

老哥理解错了，BCD中我都只挂本地存储，没挂其他网盘。然后通过Alist V3驱动，把BCD挂到了VPS-A，目前是可以读取，不能写入

**Comment by BoYanZh** [comment]
我突然意识到事情不对 为什么不用webdav挂载

**Comment by planxx** [comment]
> 我突然意识到事情不对 为什么不用webdav挂载
哈哈哈，因为我以为用alist v3有特殊加成。。。。

**Comment by planxx** [comment]
> 我突然意识到事情不对 为什么不用webdav挂载

好吧，其实还是有特殊加成的。。。因为我测试发现，WebDav都得通过代理，而Alist V3驱动，可以直接301到真实地址。。。

**Comment by BoYanZh** [comment]
现在挂载alist上传没有302

**Comment by planxx** [comment]
> 现在挂载alist上传没有302

好的吧，反正目前读取是有的，上传有没有，没那么重要了，昨天同步了最新的，还是不能写入。。。是我姿势不对吗？
