### ISSUE TITLE
123网盘无法读取

### ISSUE THREAD

**Issue by Fromduststar** [alist-org/alist#2628]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.6.0

### Driver used / 使用的存储驱动

123网盘

### Describe the bug / 问题描述

页面显示
failed get objs: failed to list objs: json: cannot unmarshal string into Go struct field Files.data of type struct { InfoList []_123.File "json:\"InfoList\""; Next string "json:\"Next\"" }

### Reproduction / 复现链接

http://101.42.242.251:5244/%E5%8E%9F%E7%A5%9E/%E7%81%AB/%E8%83%A1%E6%A1%83
密码yuanshen

**Comment by Xhofe** [comment]
123 api 有 rate limit，请自行拆分文件夹
