### ISSUE TITLE
关闭索引后自动清理索引文件

### ISSUE THREAD

**Issue by caixiaohaier** [alist-org/alist#2632]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在发现打开索引功能后建立了索引文件，当关闭后相关的数据库表项不会清除，会一直残留在数据表中。建议打开索引后，关闭索引（搜索）功能时，能把打开索引产生的数据库表或者索引文件删除，减少资源占用。

**Comment by mengguyi** [comment]
可以手动连接数据库删除
![image](https://user-images.githubusercontent.com/73788063/206126928-edb91dd7-5b0e-4101-96a0-04e6e3ea913c.png)
