### ISSUE TITLE
使用安卓foldersync 软件无法连接alist webdav

### ISSUE THREAD

**Issue by lbgws2** [alist-org/alist#2643]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.5.0

### Driver used / 使用的存储驱动

aliyun

### Describe the bug / 问题描述

配置如下,提示 handshake failed

![image](https://user-images.githubusercontent.com/3014778/206281494-4e1845bb-8b3f-493d-a089-f041c95b2f56.png)
![image](https://user-images.githubusercontent.com/3014778/206281546-1eb065de-aa6a-4da1-8c37-509278d4293b.png)

### Reproduction / 复现链接

已上传图片

**Comment by Xhofe** [comment]
https://www.google.com/search?q=handshake+failed

**Comment by C63H88CoN14O14P** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
> * [x]  I'm sure I'm using the latest version
> 
> ### Alist Version / Alist 版本
> v3.5.0
> 
> ### Driver used / 使用的存储驱动
> aliyun
> 
> ### Describe the bug / 问题描述
> 配置如下,提示 handshake failed
> 
> ![image](https://user-images.githubusercontent.com/3014778/206281494-4e1845bb-8b3f-493d-a089-f041c95b2f56.png) ![image](https://user-images.githubusercontent.com/3014778/206281546-1eb065de-aa6a-4da1-8c37-509278d4293b.png)
> 
> ### Reproduction / 复现链接
> 已上传图片
> 
> ### Logs / 日志
> _No response_

请问您最后是如何解决的?

**Comment by wangzhilin777** [comment]
> 我也是遇到这种情况，foldersync好像是不支持http协议的webdav，我改成https,端口443,身份验证类型改成Basic(UTF8)就好了

我试了还是不行，报这个错：
org.xmlpull.v1.XmlPullParserException: Attr.value missing f. async (position:START_TAG <script src='https://g.alicdn.com/IMM/office-js/1.1.5/aliyun-web-office-sdk.min.js' async='https://jsd.nn.ci/gh/alist-org/logo@main/logo.png'>@19:5 in cq.v1@2581693) 

java.lang.RuntimeException: org.xmlpull.v1.XmlPullParserException: Attr.value missing f. async (position:START_TAG <script src='https://g.alicdn.com/IMM/office-js/1.1.5/aliyun-web-office-sdk.min.js' async='https://jsd.nn.ci/gh/alist-org/logo@main/logo.png'>@19:5 in cq.v1@2581693)
