### ISSUE TITLE
SyntaxError: Invalid regular expression: /?/: Nothing to repeat报错

### ISSUE THREAD

**Issue by DUNKILL** [alist-org/alist#2645]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

非驱动问题

### Describe the bug / 问题描述

今天打开alist突然报错以下内容：
System error: SyntaxError: Invalid regular expression: /?/: Nothing to repeat
查看日志发现每当试图 GET      "/assets/index.6289ff4c.js"的时候卡住
![image](https://user-images.githubusercontent.com/91525837/206355833-045cbe92-587d-4fac-adc0-97a8a8d1cce6.png)
![image](https://user-images.githubusercontent.com/91525837/206355938-14db10b8-ed1d-4ba1-996b-a8f284a93697.png)

### Reproduction / 复现链接

https://res.czqblog.vip/

### Logs / 日志

详见问题描述，感谢开发者！

**Comment by DUNKILL** [comment]
补充说明：访问管理后台是正常的

**Comment by DUNKILL** [comment]
问题已解决，谢谢

**Comment by it985** [comment]
> 问题已解决，谢谢

可以说下怎么解决的吗

**Comment by anwen-anyi** [comment]
> > 问题已解决，谢谢
> 
> 可以说下怎么解决的吗

https://github.com/alist-org/alist/discussions/2399

**Comment by 5615hasdj** [comment]
怎么解决？

**Comment by anwen-anyi** [comment]
> 怎么解决？

https://github.com/alist-org/alist/discussions/2399

**Comment by gangtieya233** [comment]
咋解决的啊，电脑访问就这样，手机访问没事

**Comment by gangtieya233** [comment]
油猴脚本的问题
