### ISSUE TITLE
链接中接入了 sign  就不能引用了. 

### ISSUE THREAD

**Issue by ihuanx** [alist-org/alist#2648]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

比如说 本来可以用 `https://pan.nn.ci/d/Google/Five%20minutes%20of%20silence.jpeg` 来调用素材的 
现在必须要 `https://pan.nn.ci/d/Google/Five%20minutes%20of%20silence.jpeg?sign=K1CytXijk1oSjqTzeXDjtq6wWMIfnu3Ugs8YIwjl19k=:0`

我记得 V.3.5.1 打开`https://pan.nn.ci/d/Google/Five%20minutes%20of%20silence.jpeg` 还会自动跳转  `https://pan.nn.ci/d/Google/Five%20minutes%20of%20silence.jpeg?sign=K1CytXijk1oSjqTzeXDjtq6wWMIfnu3Ugs8YIwjl19k=:0` 的  

现在彻底不能用了. 

### Reproduction / 复现链接

https://pan.nn.ci/Google/Five%20minutes%20of%20silence.jpeg

**Comment by ihuanx** [comment]
本来新建一个本地存储还可以引用资源 . 现在彻底失效了..

**Comment by mengguyi** [comment]
关闭签名所有

**Comment by ihuanx** [comment]
我关闭了签名所有  状态码还是401啊  我已经删除缓存了
