### ISSUE TITLE
iOS 16 突然不能在线安装 ipa（无法安装“xxx”）

### ISSUE THREAD

**Issue by Ssiswent** [alist-org/alist#2667]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.4

### Driver used / 使用的存储驱动

阿里云

### Describe the bug / 问题描述

iOS 16 突然不能在线安装 ipa（无法安装“xxx”）
以前是能在 iOS 16 正常安装的，不知为何突然不行了
经测试，同一个已经确认签名正常的 ipa 使用以下的方法都能成功安装：
1. 轻松签签名后直接安装
2. 上传到蓝奏云在线安装
3. 参照 `https://blog.csdn.net/qunwuhui/article/details/110874942` 的方法，在线安装

注：
已经按照 iOS 16 要求设置好文件名的 bundle id
<img width="534" alt="image" src="https://user-images.githubusercontent.com/37449310/206714254-4b248ca3-851e-4a6a-94c5-187dff744438.png">

### Reproduction / 复现链接

https://pan.happaa.com/%E6%89%98%E7%AE%A1/Ssiswent/ipa/%E5%B7%B2%E7%AD%BE/%E5%B0%8F%E6%98%8E%E8%AE%A1%E7%AE%97%E5%99%A8@com.differ.xiaoming.ipa

### Logs / 日志

查看指向 `安装` 按钮的 plist 文件：
<img width="1804" alt="image" src="https://user-images.githubusercontent.com/37449310/206720050-68e6b19d-9ff2-4e4d-9f68-b3881e3555ef.png">

出错提示：
<img width="444" alt="image" src="https://user-images.githubusercontent.com/37449310/206714567-2e138824-6c05-446d-b23f-db482df5076a.png">

**Comment by Xhofe** [comment]
测试 上传到蓝奏云在线安装  无法安装

**Comment by Dashan-IZ** [comment]
我的也是这个问题

**Comment by Ssiswent** [comment]
> 测试 上传到蓝奏云在线安装 无法安装

我找到问题了，是因为在Alist后台管理勾选了Web代理，取消勾选就好了
<img width="1880" alt="image" src="https://user-images.githubusercontent.com/37449310/207602893-32f3f573-6706-47c0-b3cd-347d3470f4cb.png">

**Comment by asoncqt** [comment]
您好大大  我也遇到同样的问题了 ，我怎么没看到我后台有web代理这个功能啊

**Comment by shadowrocket-id** [comment]
真正的原因是，ipa的下载址一定要是https开头，本地存储没有302重定向，无法解决，只能挂载网盘才有302重定向，这样下载的ipa文件才是https开头，才能正常安装
