### ISSUE TITLE
 将权限「可以看到隐藏」权限拆分成, 可见隐藏 与 可访问隐藏

### ISSUE THREAD

**Issue by balh55y** [alist-org/alist#2668]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

# 将权限「可以看到隐藏：可以看到隐藏的文件和文件夹」权限拆分成, 可见隐藏 与 可访问隐藏
使用场景(本人刚遇到的):我想把一些家庭图片放到网站上并将链接分享给家人,此时长辈只需要点击链接就可访问.同时(在之前的版本)文件夹是隐藏的,其他不知道链接的游客不会有常规手段访问到这个文件夹.
### 现状: 游客账户权限
![image](https://user-images.githubusercontent.com/85926883/206723787-3241a694-f529-4dc8-be97-03efc5e0375e.png)
### 访问隐藏文件夹(未设置密码)会没权限
![image](https://user-images.githubusercontent.com/85926883/206725489-a03879aa-94ec-4e54-8c0b-2e7a63d292cc.png)
现在如果想通过链接直接访问隐藏文件/文件夹 就需要给游客开放 「可以看到隐藏」权限,这样游客能看见东西实在是太多了

## 上述需求在之前的版本都是可以实现的,只需要在元信息里将文件夹隐藏即可.现版本怎么做都无法实现了

ps:有能回退版本的一键脚本也行~~

### Additional context / 附件

例子:
https://517474.xyz/18+/%E8%8E%89%E5%8F%AF%E8%8E%89%E4%B8%9Dcos_%E5%AF%86%E7%A0%81123.zip
这个文件及上层文件夹想直接访问,但是网页目录不可见 (游客权限只开 无密码访问)

**Comment by Zacharry** [comment]
保存好data，直接去releases下载重新部署不就好了？

**Comment by BoYanZh** [comment]
去全局设置隐藏

**Comment by balh55y** [comment]
> 去全部设置隐藏

谢谢,解决了

**Comment by asong2022** [comment]
请问下，您发的链接里面，在网盘目录下放图片或者文字说明这个是如何做到的呀

**Comment by Zacharry** [comment]
> 请问下，您发的链接里面，在网盘目录下放图片或者文字说明这个是如何做到的呀

在目录下创建/上传一个README.md文件，markdown格式即可，或者在元信息那里选择目录后填写说明

**Comment by asong2022** [comment]
> > 请问下，您发的链接里面，在网盘目录下放图片或者文字说明这个是如何做到的呀
> 
> 在目录下创建/上传一个README.md文件，markdown格式即可，或者在元信息那里选择目录后填写说明

谢谢！！太感谢您了！

**Comment by asong2022** [comment]
还有想问下无密码访问这个功能是什么作用呀，我看游客没勾选无密码访问这个权限，他还是可以不登录访问呀？

**Comment by Zacharry** [comment]
> 还有想问下无密码访问这个功能是什么作用呀，我看游客没勾选无密码访问这个权限，他还是可以不登录访问呀？

无需密码访问就是对你已经设置过密码的目录，他可以不需要密码就能直接访问

**Comment by asong2022** [comment]
> > 还有想问下无密码访问这个功能是什么作用呀，我看游客没勾选无密码访问这个权限，他还是可以不登录访问呀？
> 
> 无需密码访问就是对你已经设置过密码的目录，他可以不需要密码就能直接访问

谢谢！！刚刚看您提到的元信息的那里看到这个了，想到原来这个无密码访问是指文件夹密码！感谢！
