### ISSUE TITLE
预览程序请求

### ISSUE THREAD

**Issue by chengzixqq** [alist-org/alist#2670]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

AList中的视频预览ArtPlayer停留在4.5.4版本
目前ArtPlayer已经更新到了4.5.11版本，请求更新最新版本
![image](https://user-images.githubusercontent.com/104790283/206784341-f320d2f0-3214-479c-b76d-68b6cca8869e.png)
![image](https://user-images.githubusercontent.com/104790283/206784444-b8cdb1c4-71d8-4ea7-96e5-45ff009aa144.png)

**Comment by InitialXKO** [comment]
新版主要是后台功能的改变，Alist本身没有去调用这些功能，前端没有区别。
