### ISSUE TITLE
MySQL数据库search_nodes表parent字段的varchar(191)类型长度不够用

### ISSUE THREAD

**Issue by xiwangly2** [alist-org/alist#2674]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我使用MySQL作为Alist的数据库，我的网盘有时后文件夹路径很深，这导致了这个字段varchar(191)类型的长度不够用，导致了超出了这个长度的部分没有被索引进去，我尝试过手动修改这个值，但是Alist重启后字段类型自动更新成varchar(191)，我希望进一步放宽这个限制

**Comment by BoYanZh** [comment]
https://www.grouparoo.com/blog/varchar-191

**Comment by xiwangly2** [comment]
> https://www.grouparoo.com/blog/varchar-191

是的，由于一些历史原因，不得不使用varchar(191)，并且这样做能提高索引的效率，但是能不能放弃这个索引来提高存储parent字段的长度呢？

**Comment by BoYanZh** [comment]
> > https://www.grouparoo.com/blog/varchar-191
> 
> 是的，由于一些历史原因，不得不使用varchar(191)，并且这样做能提高索引的效率，但是能不能放弃这个索引来提高存储parent字段的长度呢？

那要么砍掉在某个路径下搜索的功能，要么要用复杂的方法来存parent字段。

**Comment by xiwangly2** [comment]
> 那要么砍掉在某个路径下搜索的功能，要么要用复杂的方法来存parent字段。

如果要提高可用性，选择后者会是更好的方案；或者说用某种id去代替表示很长的路径，倘若要支持某些网盘带有特殊字符（`/`，`"`,`'`等）的目录显示，这或许会是一个选择。

**Comment by xiwangly2** [comment]
我注意到新的版本已经把字段改成了longtext类型，这解决了此问题
