### ISSUE TITLE
文件删除后索引还在

### ISSUE THREAD

**Issue by ssln5014** [alist-org/alist#2675]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

索引类型为数据库

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
https://alist.nn.ci/guide/advanced/search.html
