### ISSUE TITLE
支持terabox网盘存储

### ISSUE THREAD

**Issue by karma-sun** [alist-org/alist#2678]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

支持terabox网盘存储https://www.terabox.com/

### Suggested solution / 实现思路

API类似百度盘,用cookie登录，如列表接口是https://www.terabox.com/api/list

**Comment by wowo14735** [comment]
牛逼网盘

**Comment by yangchaobalck** [comment]
希望支持terabox
