### ISSUE TITLE
希望能增加一个文件夹密码功能

### ISSUE THREAD

**Issue by Dashan-IZ** [alist-org/alist#2688]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加一个文件夹密码功能，把不想公开的或者持有访问密码的·人才能访问某个文件夹，

**Comment by BoYanZh** [comment]
已有功能，你真的看了文档了吗？
