### ISSUE TITLE
如何设置防盗链(白名单)

### ISSUE THREAD

**Issue by Tinaliasd** [alist-org/alist#2689]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如何设置防盗链,alist 应该是有防盗链的,但是我希望可以设置白名单,因为我希望使用alist 搭配网盘来做一部分图床,方便发博客的时候可以直接使用那些链接

**Comment by Xhofe** [comment]
无防盗链。
