### ISSUE TITLE
百度网盘离线上传失败，提示error2

### ISSUE THREAD

**Issue by wizardmanxxx** [alist-org/alist#2690]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述
使用alist离线下载功能。
添加磁力后，能成功下载，但是无法上传中会报错
e.g. failed to make dir [/我的资源/电影/Inception.2010.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.5.1-RARBG]: errno: 2, refer to https://pan.baidu.com/union/doc/
提示error 2；查了下百度api文档，差了下是接口参数错误。目前发现的规律是小文件<10G的可以成功上传，已是百度svip（或百度服务器已有副本秒传的资源）怀疑是否api用错了？
<img width="568" alt="image" src="https://user-images.githubusercontent.com/36092385/207082775-3798281e-a109-456a-a707-d631d66787fd.png">
选择添加的磁力是
magnet:?xt=urn:btih:6D7687DF8762263BB8CF1CE28E4754966FE95347&dn=Inception.2010.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.5.1-RARBG

### Reproduction / 复现链接

内网ip暂无可用链接

### Logs / 日志

![image](https://user-images.githubusercontent.com/36092385/207083950-e51e6e13-964b-44ca-af74-1d8c6d12a821.png)

**Comment by mnpq-top** [comment]
我的是复制任务，到百度云盘。复制剧集其中会有好几集失败的，得挑出来再加一次复制任务，可以成功上传。

**Comment by Xhofe** [comment]
此处是创建文件夹`Inception.2010.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.5.1-RARBG`失败，尝试了一下 这可能是百度的问题，会随机创建失败，有时候又可以创建成功。
