### ISSUE TITLE
联通云盘支持

### ISSUE THREAD

**Issue by wzwzx** [alist-org/alist#2698]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

支持联通云盘 pan.wo.cn

**Comment by Noahsarker** [comment]
同求，免费送了2T

**Comment by wxyShine** [comment]
8T

**Comment by nancheung** [comment]
同求联通云盘

**Comment by v1006945671** [comment]
同求

**Comment by flacce** [comment]
+1

**Comment by zzsrv** [comment]
附议
