### ISSUE TITLE
希望添加功能“用户-编辑-基本路径可设置同层级多个文件夹”

### ISSUE THREAD

**Issue by may1051** [alist-org/alist#2699]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望添加功能“用户-编辑-基本路径可设置同层级多个文件夹”

**Comment by KyonCN** [comment]
赞同
