### ISSUE TITLE
Support FULLTEXT index for file field in `search_node`

### ISSUE THREAD

**Issue by BoYanZh** [alist-org/alist#2716]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

FULLTEXT index is supported in SQLite with fts5, late version of MySQL and pgSQL. Now it is too slow to search on large amount of files with O(n) complexity.

### Suggested solution / 实现思路

Modify declaration of gorm model and use MATCH statement in query.

**Comment by BoYanZh** [comment]
no idea on how to let https://github.com/mattn/go-sqlite3 used by gorm imported with build tag `fts5` to enable full text index.
It will raise `failed migrate database: near "FULLTEXT": syntax error` on sqlite, and work well on the others.

**Comment by BoYanZh** [comment]
So the problem is that FTS5 needs the following syntax to create the index
```
CREATE VIRTUAL TABLE email USING fts5(sender, title, body);
```
but gorm will run
```
CREATE FULLTEXT INDEX `idx_x_search_nodes_name` ON `x_search_nodes`(`name`)
```

**Comment by Xhofe** [comment]
Perhaps we could use `db.Exec`  to run raw sql to create the index manually instead of the automated `db.AutoMigrate` for sqlite3.
Is this okay?

**Comment by BoYanZh** [comment]
> Perhaps we could use `db.Exec` to run raw sql to create the index manually instead of the automated `db.AutoMigrate` for sqlite3. Is this okay?

According to the doc of FTS5, sqlite can only create a table that builds a full text index on all the columns. So in order to support sqlite, we need a separate table, connected to `search_node` table with a foreign key, which will be different than other two tables. (I think sqlite can not use normal B-tree index for searching prefix https://www.sqlite.org/fts5.html#prefix_indexes)

Any way, fulltext search support for sqlite should be in low priority. The primary goal is to make full text search work for other db and will not raise an error on sqlite. I think `db.Exec` is a good way. Just do not use `json:"name" gorm:"index:,class:FULLTEXT"` in struct definition, use `db.Exec` to create full text index on 2 dbs is enough.

**Comment by BoYanZh** [comment]
FULLTEXT index on postgresql does not work well.
