### ISSUE TITLE
Google 驱动令牌过期问题

### ISSUE THREAD

**Issue by hexin-lin-1024** [alist-org/alist#2719]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

谷歌硬盘的刷新令牌会过期，而AList无法自动获取新的令牌；建议将填写刷新令牌一栏换成填写 `Code` ，当检测到发生 `invalid_grant` 错误的时候自动发送 `Post` 请求获取新令牌。

### Suggested solution / 实现思路

根据目前网页端获取刷新令牌的思路，检测到 `invalid_grant` 错误的时候自动发送 `Post` 请求获取新令牌。

**Comment by hexin-lin-1024** [comment]
> ### See
> 1. 50% [Google Drive不能移动文件了 #620](https://github.com/alist-org/alist/issues/620)

问题并未重复

**Comment by Muggles001** [comment]
大佬是否解决令牌经常过期问题

**Comment by UFervor** [comment]
> 大佬是否解决令牌经常过期问题

这个令牌似乎是间歇性失效的，令人疑惑。

**Comment by Muggles001** [comment]
> > 大佬是否解决令牌经常过期问题
> 
> 这个令牌似乎是间歇性失效的，令人疑惑。

没办法，测试版7天一过期，正式版又获取不了，貌似只能电脑本地获取，然后config里面有令牌

**Comment by LevineWoo** [comment]
> > > 大佬是否解决令牌经常过期问题
> > 
> > 
> > 这个令牌似乎是间歇性失效的，令人疑惑。
> 
> 没办法，测试版7天一过期，正式版又获取不了，貌似只能电脑本地获取，然后config里面有令牌

请问电脑本地获取的这个google什么关键字可以找到教程嘛？

**Comment by Muggles001** [comment]
先在测试版获取令牌，然后点升级正式版如果7天后没有过过期就是成功了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月23日(周五) 中午11:11
收件人: ***@***.***&gt;;
抄送: "Clifford ***@***.******@***.***&gt;;
主题: Re: [alist-org/alist] Google 驱动令牌过期问题 (Issue #2719)




    
大佬是否解决令牌经常过期问题
  
这个令牌似乎是间歇性失效的，令人疑惑。
  
没办法，测试版7天一过期，正式版又获取不了，貌似只能电脑本地获取，然后config里面有令牌
  
请问电脑本地获取的这个google什么关键字可以找到教程嘛？
