### ISSUE TITLE
使用webdav上传大量小文件到被索引忽略的文件夹时触发Error 1040: Too many connections

### ISSUE THREAD

**Issue by mengguyi** [alist-org/alist#2732]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

在使用rclone向webdav上传大量小文件到被索引忽略的文件夹时触发MySQL Error 1040: Too many connections
下图为netdata的监控
![图片](https://user-images.githubusercontent.com/73788063/208054935-7a78c071-2429-403e-a696-9922ef18d869.png)
![图片](https://user-images.githubusercontent.com/73788063/208054993-f271a8a2-b08e-4093-aa07-daf37e902d18.png)
alist的管理后台
![图片](https://user-images.githubusercontent.com/73788063/208055213-d78af46f-f48f-4b91-9440-480f65d40926.png)

### Reproduction / 复现链接

这个东西不好在 drive.mengguyi.com 上复现，在这里写一下复现步骤
1. 准备很多的5m左右的小文件（照片）总大小11G左右
2. 在rclone中添加alist的admin账户的webdav
3. 启用alist的索引，使用数据库，数据库为MySQL
4. 在索引完成后使用rclone通过webdav向alist的一个被忽略索引的文件夹上传这些文件
5. 很快就会触发Error 1040: Too many connections

另外说一下，本人服务器放在内网，上传速率约等于1000Mbps。如果是公网服务器可能没有如此大的上传带宽可能无法复现。MySQL上只链接了alist，基本排除其他业务导致Error 1040: Too many connections的可能

推测bug出现的原因：在上传到被忽略索引的文件夹时alist还是把索引数据写入到了数据库

期望的情况：在向被忽略索引的文件夹上传文件时不向数据库写入索引数据

### Logs / 日志

[log.log](https://github.com/alist-org/alist/files/10244035/log.log)

**Comment by BoYanZh** [comment]
还没看log，但我猜是因为hook里update index被webdav的list触发后会反复对那些文件去执行查询是否在忽略的索引目录下，这部分没被塞进memcache里所以连接过多了。

**Comment by Xhofe** [comment]
This should have been fixed in 62ea93837c546133dd67d99108719f94aff2624c
