### ISSUE TITLE
莫名生成了大量嵌套空文件夹

### ISSUE THREAD

**Issue by ywxksjhx** [alist-org/alist#2760]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.6.0

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

系统：win10

测试 **用户-编辑-权限** 里 **复制** 权限有什么用的时候 给我生成了无数个嵌套空文件夹

当时情况：用edge浏览器登录admin账号把游客账号的**复制**权限打开，之后用火狐浏览器（没有登录）发现**右键单击**文件时多出了**复制**选项，但是点击之后跳出弹框让选择文件夹，于是我新建了一个文件夹（没有改名，文件夹名：**新建文件夹**）然后复制选中此文件夹后发现什么也没复制到，于是我多试了几次发现剪切板上还是什么都没有，但是文件夹内多了一堆嵌套的文件夹（即 新建文件夹/新建文件夹/新建文件夹/新建文件夹/新建文件夹/...... 这种样子）且此时电脑风扇声音突然增大，任务管理器发现alist占用很高，猜测还在生成，于是直接结束进程，风扇声音恢复；之后使用win自带资源管理器删除（**右键-删除**）已无法删除，一点删除出现**下图**

![image](https://user-images.githubusercontent.com/75521805/208434118-a288f63b-fde4-4e2e-b8ff-a2e76b7dce0d.png)

点击重试之后资源管理器就崩溃闪退（重启也没用）幸好本人懂一点java代码，使用java递归删除（java只能删除文件和空文件夹，所以要删除非空文件夹需要递归）运行了有大概20秒才删除

### Reproduction / 复现链接

怕损坏电脑没有复现；当时怕电脑出问题有点慌，所以执行代码时没计数也没计时，但之后测试创建了1000个嵌套文件夹，用同样的代码，删除时只用了2.4秒，所以保守估计当时有3000个左右的嵌套文件夹

**Comment by BoYanZh** [comment]
日志呢
