### ISSUE TITLE
文件列表显示错误

### ISSUE THREAD

**Issue by Clown1i** [alist-org/alist#2764]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.60

### Driver used / 使用的存储驱动

WebDav

### Describe the bug / 问题描述

WebDav挂载，供应商Sharepoint，上传文件不会立刻刷新缓存显示新文件，在缓存刷新时间之前无法看到新上传的文件或文件夹，全选进行操作时会连同隐藏的文件或文件夹一起操作

### Reproduction / 复现链接

任意链接

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8A%E4%BC%A0%E7%9A%84%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA-%E5%88%A0%E9%99%A4%E7%9A%84%E6%96%87%E4%BB%B6%E8%BF%98%E5%9C%A8-%E4%BF%AE%E6%94%B9%E6%A0%B9%E7%9B%AE%E5%BD%95%E4%B8%8D%E7%94%9F%E6%95%88

**Comment by Peooop** [comment]
你这是从来没看过文档吧
