### ISSUE TITLE
视频播放页面，Potplayer调用链接无法播放

### ISSUE THREAD

**Issue by commandoccz** [alist-org/alist#2782]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.6.0

### Driver used / 使用的存储驱动

阿里云/和彩云

### Describe the bug / 问题描述

        alist列出网盘视频文件并展开播放界面后，网页端可正常播放，点击视频窗口下方PotPlayer按钮成功调出播放器后显示“无法找到该文件”，查看Potplayer链接为potplayer://https%3A%2F%2...，似乎链接生成有问题。
        其余播放器按钮例如VLC 显示为：vlc://https://....调用正常.
        该问题已有多人反馈，其中 #1769 issue说更新potplayer到最新版可解决，经过尝试，bug依然存在，麻烦作者提供一个解决方案，谢谢啦

### Reproduction / 复现链接

无

**Comment by anwen-anyi** [comment]
原因貌似就是把 //转义了 %3A%2F%2...

**Comment by devefx** [comment]
问题依然存在，但是issue已经被close了，作者认为问题已经修复了

**Comment by anwen-anyi** [comment]
这都能挖坟？2年哩，这次是浏览器的锅好像，就`Chrome` 这样 Edge 火狐都没事儿
- https://github.com/AlistGo/alist/issues/7360#issuecomment-2425268737
- https://github.com/AlistGo/alist/issues/7360#issuecomment-2439544206
------
- https://github.com/AlistGo/alist/issues/7471
