### ISSUE TITLE
请求增加 3D 模型预览/展示功能

### ISSUE THREAD

**Issue by Febtw** [alist-org/alist#2788]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

1、Alist 已经支持了文本和多媒体的众多格式的预览，如果可以支持3D模型的展示，那么会使Alist变得更酷；
2、已有 [kovacsv/Online3DViewer](https://github.com/kovacsv/Online3DViewer) [https://3dviewer.net/](https://3dviewer.net/)、[google/model-viewer](https://github.com/google/model-viewer/tree/master/packages/model-viewer)   [https://modelviewer.dev/](https://modelviewer.dev/) 等方案便于开发，用 Alist 提供文件列表相得益彰。

### Suggested solution / 实现思路

与  [kovacsv/Online3DViewer](https://github.com/kovacsv/Online3DViewer) [https://3dviewer.net/](https://3dviewer.net/) 或 [google/model-viewer](https://github.com/google/model-viewer/tree/master/packages/model-viewer)   [https://modelviewer.dev/](https://modelviewer.dev/) 结合

**Comment by Xhofe** [comment]
You can add it yourself by editing [iframe-previews](https://alist.nn.ci/config/preview.html#iframe-previews) like:
```json
        "glb": {
                "3dviewer": "https://3dviewer.net/#model=$url"
        }
```
demo: https://al.nn.ci/local/DamagedHelmet.glb

**Comment by Febtw** [comment]
> You can add it yourself by editing [iframe-previews](https://alist.nn.ci/config/preview.html#iframe-previews) like:
> 
> ```json
>         "glb": {
>                 "3dviewer": "https://3dviewer.net/#model=$url"
>         }
> ```
> 
> demo: https://al.nn.ci/local/DamagedHelmet.glb

This is my [iframe-previews](https://alist.nn.ci/config/preview.html#iframe-previews) setting
'''
{
	"doc,docx,xls,xlsx,ppt,pptx": {
		"Microsoft":"https://view.officeapps.live.com/op/view.aspx?src=$e_url",
		"Google":"https://docs.google.com/gview?url=$e_url&embedded=true"
	},
	"pdf": {
		"PDF.js":"https://alist-org.github.io/pdf.js/web/viewer.html?file=$e_url"
	},
	"obj,3ds,stl,ply,gltf,glb,off,3dm,fbx,dae,wrl,3mf,ifc,brep,step,iges,fcstd,bim": {
		"3Dviewer":"https://3dviewer.net/#model=$e_url"
	}
}
'''
There's still something wrong.
![image](https://user-images.githubusercontent.com/96163355/209358836-32a588d6-00f5-4b32-aa53-1076b308fdbc.png)

**Comment by Febtw** [comment]
Should I start a new issue？I also want to have GeoGebra Apps embeded. [Reference:GeoGebra Apps Embedding](https://wiki.geogebra.org/en/Reference:GeoGebra_Apps_Embedding)

**Comment by Xhofe** [comment]
No we will no longer add previews for new file types. Embed iframe for preview by editing iframe_previews yourself please.

**Comment by Febtw** [comment]
> No we will no longer add previews for new file types. Embed iframe for preview by editing iframe_previews yourself please.

Please, I have the last question, which parameter represents Alist file url
I have tried $url and $e_url , it gets url like https://xxx.sharepoint.com/personal/xxx_onmicrosoft_com/_layouts/15/download.aspx?loooooong_string. 
And 3dviewer can't read the url.
But It works, when I replace $url with Alist file url like https://my.site/d/Alist/DamagedHelmet.glb?sign=long_string=:0

My drive is Onedrive
And  ./alist version
Built At: 2022-12-05 13:55:03 +0000
Go Version: go1.19.3 linux/amd64    （but my system is ubuntu 20.04 arm64）
Author: Noah Hsu <i@nn.ci>
Commit ID: f1a9b68
Version: v3.6.0
WebVersion: 3.6.0
