### ISSUE TITLE
针对本机存储增加下载速度限制

### ISSUE THREAD

**Issue by earthjasonlin** [alist-org/alist#2789]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

针对本机存储增加下载速度限制

### Suggested solution / 实现思路

在“本机存储”的编辑界面中增加一个多行文本框让管理员撰写规则，格式大概可以按照``用户名,路径,速度限制（KB/s）``之类的来
或者是在元信息的编辑内增加一个速度限制的选项

**Comment by flymin** [comment]
请问这个功能实现了吗？目前怎么设置限速？
