### ISSUE TITLE
网页的静态资源使用相对路径

### ISSUE THREAD

**Issue by ain-soph** [alist-org/alist#2790]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我知道AList可以设置`site_url`来实现二级目录反代，但是还是不太方便，尤其需要同时使用多种server_name的情况（如使用IP和网址）。

网页端部署在5244端口后，我通过nginx转发到二级目录`https://192.168.1.2/alist/`。访问端口`https://192.168.1.2:5244`可以正常使用，但是访问`https://192.168.1.2/alist/`打开的是空白网页。

原因是html里面的静态文件链接错误（详情看最后的截图）。因为使用了绝对路径，导致二级目录被无视了。

例如，`<link href="/css/chunk-21dfbee4.7c372010.css" rel="prefetch">`
    - **实际：**`https://192.168.1.2/assets/index-legacy.0367ebcb.js`。
    - **期望：**`https://192.168.1.2/`**`alist/`**`assets/index-legacy.0367ebcb.js`。

### Suggested solution / 实现思路

我希望既能通过端口访问也能通过二级目录访问，所以只需要把最前面的斜杠去掉变成相对路径即可。这样二级目录反代就不需要添加任何额外设置了。
- **当前：**`"/assets/index-legacy.0367ebcb.js"`
- **修改：**`"assets/index-legacy.0367ebcb.js"`
（只是个例子，需要修改html里的所有绝对路径，和用到的JS里面也可能出现的绝对路径）

### Additional context / 附件

<img width="642" alt="image" src="https://user-images.githubusercontent.com/13214530/209273990-ed490628-fd94-49f4-a1e6-633f33e71668.png">

**Comment by Xhofe** [comment]
spa使用相对路径只能访问首页，所以不支持。

你可以使用公共cdn：https://alist.nn.ci/zh/config/configuration.html#cdn

**Comment by ain-soph** [comment]
Thanks for your quick response. I'll check if CDN works.

**Comment by ain-soph** [comment]
还是读取不了，因为api没有被重定向，访问的是192.168.1.2/api而不是192.168.1.2/alist/api。
不过看来没什么好办法了，就这样吧。
