### ISSUE TITLE
Is there a parameter represents Alist file url ？

### ISSUE THREAD

**Issue by Febtw** [alist-org/alist#2805]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

I‘m trying to add [https://3dviewer.net/](https://3dviewer.net/) on [iframe-previews](https://alist.nn.ci/config/preview.html). 
I have tried parameter with $url and $e_url , it gets url like https://xxx.sharepoint.com/personal/xxx_onmicrosoft_com/_layouts/15/download.aspx?loooooong_string.
And 3dviewer can't read the url like that.
But It works, when I replace $url with Alist file url like https://my.site/d/Alist/DamagedHelmet.glb?sign=long_string=:0

Is there a parameter represents Alist file url ？

### Suggested solution / 实现思路

Could Alist reserve a parameter that represents Alist file url ？

### Additional context / 附件

My drive is Onedrive
And ./alist version
Built At: 2022-12-05 13:55:03 +0000
Go Version: go1.19.3 linux/amd64    【It's strange, but my system is ubuntu 20.04 arm64】
Author: Noah Hsu [i@nn.ci](mailto:i@nn.ci)
Commit ID: https://github.com/alist-org/alist/commit/f1a9b680223c9215931012e1af67dd75b4ee586b
Version: v3.6.0
WebVersion: 3.6.0

**Comment by anwen-anyi** [comment]
Does this help you? https://alist.nn.ci/config/preview.html#external-previews

**Comment by Febtw** [comment]
> Does this help you? https://alist.nn.ci/config/preview.html#external-previews
I have tried parameters $url, $e_url, $b_url and $eb_url. 
$url and $e_url give http url form, but are onedrive's url;
$b_url and $eb_url don't give http url form.
None of them could be read by 3dviewer.

**Comment by anwen-anyi** [comment]
No problem according to the commit demo test
![3D](https://down.onmicrosoft.cn/oss/u2021090299b56677_1671951827514_15992911_image.png)

**Comment by Febtw** [comment]
> 根据[评论](https://github.com/alist-org/alist/issues/2788#issuecomment-1363678994)演示测试没有问题 ![.3D](https://camo.githubusercontent.com/1044a41017d821436660c31bc86686726625917a681576282595ac1c52ed0fc6/68747470733a2f2f646f776e2e6f6e6d6963726f736f66742e636e2f6f73732f75323032313039303239396235363637375f313637313935313832373531345f31353939323931315f696d6167652e706e67)

Yes, it gives Alist file url when using local drive, but gives onedrive url when using onedrive.

**Comment by Febtw** [comment]
@Xhofe Please, orz , It's not the same question as #2788, and I'm not asking for adding previews for new file types.

**Comment by Xhofe** [comment]
> 

As you can see in https://github.com/alist-org/alist-web/commit/a83b08e09b62b56e59373f4f24e68ef44b8fad0c, I have add a new variable for scheme which named `$durl`.

**Comment by anwen-anyi** [comment]
> > 根据[评论](https://github.com/alist-org/alist/issues/2788#issuecomment-1363678994)演示测试没有问题 ![.3D](https://camo.githubusercontent.com/1044a41017d821436660c31bc86686726625917a681576282595ac1c52ed0fc6/68747470733a2f2f646f776e2e6f6e6d6963726f736f66742e636e2f6f73732f75323032313039303239396235363637375f313637313935313832373531345f31353939323931315f696d6167652e706e67)
> 
> Yes, it gives Alist file url when using local drive, but gives onedrive url when using onedrive.
> 
> ![image](https://user-images.githubusercontent.com/96163355/209460065-50c95f8f-f9de-4365-8380-47f76688c796.png)

好吧，onedrive确实是这样的(我去onedrive复现也是这样的)，不过看到 Xhofe 新加了一个选项，等下个版本再试试看呢

**Comment by Febtw** [comment]
> > @Xhofe Please, orz , It's not the same question as #2788, and I'm not asking for adding previews for new file types.
> 
> As you can see in [alist-org/alist-web@a83b08e](https://github.com/alist-org/alist-web/commit/a83b08e09b62b56e59373f4f24e68ef44b8fad0c), I have added a new variable for scheme which named `$durl`.

Sorry, misunderstanding [😅](https://cn.emojiguide.com/%E7%AC%91%E8%84%B8%E4%B8%8E%E6%83%85%E6%84%9F/grinning-face-with-sweat/)... Thank you for your work!!!
