### ISSUE TITLE
提交e118f4a的代码出现大量的sql"DELETE FROM `x_search_nodes`"

### ISSUE THREAD

**Issue by 17ce** [alist-org/alist#2810]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

commit-c00dcc8

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

昨晚编译了最新的commit，使用mysql做数据库，mysql做索引，mysql的总连接数配置为500。  

在后台构建了索引(一开始是bleve,再切换到了mysql)，运行一段时间后，前台页面提示”failed select meta: Error 1040: Too many connections“，无法正常加载目录。文件比较多，索引数量有12万。  

起初以为是搜索量大导致的，关闭索引后的确正常了，但看nginx的日志搜索的请求很少。  

之后mysql配置了更高的连接数，后台再打开了索引，alist开启debug后重新运行，看日志有大量的DELETE FROM `x_search_nodes`，数量是SELECT * FROM `x_meta`是几倍乃至十几倍，感觉不太正常。  

尝试过重启alist，重启后日志依旧有大量的DELETE FROM `x_search_nodes`记录。  

在后台索引页面中的索引数量没有变，网盘文件也没有变动。 

后面重新编译了https://github.com/alist-org/alist/tree/3af23f6792c37d013850bb5bcea193e2dc1c6c67，也就是commit-e118f4a3b9051cec772876621932b8b6cecbfcd1之前的代码。  
日志就没有再出现”DELETE FROM `x_search_nodes`“，负载也正常了。  

### Reproduction / 复现链接

无

### Logs / 日志

![image](https://user-images.githubusercontent.com/56804964/209529834-f29a48e6-28a1-40cd-9216-5f351a68951b.png)

**Comment by Xhofe** [comment]
日志贴全 不要截一半

**Comment by roderick6668** [comment]
![image](https://user-images.githubusercontent.com/69986428/211114977-33fa118a-cbbe-4c05-824d-e65b3db386f9.png)
我和他出现了一样的问题，如果有需要我可以把我完全的log发给你 @Xhofe
