### ISSUE TITLE
macOS连接WebDav到alist添加文件失败

### ISSUE THREAD

**Issue by chenshd** [alist-org/alist#2812]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

last

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

环境: 
- alist : centos下 docker安装
- 系统 : macOS Ventura
存储: 
-  阿里云盘
问题：
    macOS下webdav连接alist的阿里云盘,显示查看一切正常，但是往目录中添加文件后不显示新增的文件，比如新增abc.txt在阿里云盘中显示._abc.txt没有新上传的文件
 

### Reproduction / 复现链接

无

**Comment by chenshd** [comment]
在web端新增和删除一切都正常

**Comment by vipheyue** [comment]
@chenshd   你把远程路径加上不要忘了   /dav



http[s]://domain:port/dav/
domian填写公网 ip 或者局域网 ip  
或者 127.0.0.1    或者  localhost

**Comment by jzxkkk** [comment]
macos自带文件添加的话有很多问题  不建议使用

**Comment by vipheyue** [comment]
您好，您发送的邮件我已经收到。我查阅后,会尽快回复您！

**Comment by likeman66** [comment]
> macos自带文件添加的话有很多问题 不建议使用

请问有什么软件推荐嘛，我访达连接alist dav确实问题很多，文件传不上去，也经常不能重命名东西。。

**Comment by vipheyue** [comment]
您好，您发送的邮件我已经收到。我查阅后,会尽快回复您！
