### ISSUE TITLE
挂载Onedrive后读取，alist崩溃

### ISSUE THREAD

**Issue by lizihan12138** [alist-org/alist#2817]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

通过webdiv方式挂载onedrive，打开后一直转圈alist应用占用升高
![image](https://user-images.githubusercontent.com/51503607/209743473-0d51b844-34bd-4b46-ae28-a45deb358902.png)

### Reproduction / 复现链接

无

### Logs / 日志

![image](https://user-images.githubusercontent.com/51503607/209743566-62266fcb-c551-4d15-a9f5-c853023d74f2.png)

**Comment by chengnan049** [comment]
通过何种方式挂载？是 Windows 自带还是 CloudDrive Rclone 等，同时你的 `WebDav` 打成了 `webdiv` ，并且没有大写

**Comment by lizihan12138** [comment]
> 通过何种方式挂载？是 Windows 自带还是 CloudDrive Rclone 等，同时你的 `WebDav` 打成了 `webdiv` ，并且没有大写
raidrive，问题在于我在alist的网页端打开onedrive的文件夹就会这样

**Comment by chengnan049** [comment]
先尝试最新版本，并不要使用 RaiDrive ，随后打开 AList

**Comment by chengnan049** [comment]
Build版本下未发现异常![image](https://user-images.githubusercontent.com/46060083/210130007-c339dd71-3cee-4912-8da4-9682e1f19ecb.png)

**Comment by lizihan12138** [comment]
> Build版本下未发现异常![image](https://user-images.githubusercontent.com/46060083/210130007-c339dd71-3cee-4912-8da4-9682e1f19ecb.png)

估计可能是我系统版本问题或者挂载的不大对吧，我换了别的挂载方式还是有问题

**Comment by chengnan049** [comment]
来群里问吧
