### ISSUE TITLE
增加dubox/terrabox支持

### ISSUE THREAD

**Issue by LzwCracker** [alist-org/alist#2825]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增加dubox/terrabox支持

**Comment by BoYanZh** [comment]
Duplicate of #2678.
