### ISSUE TITLE
建议增加小龙云盘支持

### ISSUE THREAD

**Issue by hyhwl** [alist-org/alist#2827]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

小龙云盘 无限存储云盘没有大小限制 比较好用来存文件比较好

### Suggested solution / 实现思路

可以和其他云盘互通

**Comment by BoYanZh** [comment]
Duplicate of #1484, 2105.

**Comment by foxxorcat** [comment]
我抽空看了一下，发现小龙云盘和公共ipfs数据是连通的，应该是没有设置私有化，只是文件传播速度非常慢，你或许可以直接用ipfs官方客户端挂成本地磁盘，也算是支持一下ipfs发展。
当然也欢迎有人pr。

**Comment by whws** [comment]
> 我抽空看了一下，发现小龙云盘和公共ipfs数据是连通的，应该是没有设置私有化，只是文件传播速度非常慢，你或许可以直接用ipfs官方客户端挂成本地磁盘，也算是支持一下ipfs发展.当然也欢迎有人pr.

该网盘链接:https://wx.stariverpan.com/web/home
