### ISSUE TITLE
3.7.1版本对象存储bug

### ISSUE THREAD

**Issue by Gumingjie0312** [alist-org/alist#2834]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.7.1

### Driver used / 使用的存储驱动

对象存储

### Describe the bug / 问题描述

在更新完V3.7.1版本后，出现了以下问题：
切换目录时，对象存储会一直停留在根目录上
![问题复现](http://joegu.tk/d/Screenshot_20221230_083424.jpg?sign=-R437bwBRnhFiOLaz4s91bvowwaB80oHgm_bjLPLnYo=:0)

### Reproduction / 复现链接

![问题复现](http://joegu.tk/d/Screenshot_20221230_083424.jpg?sign=-R437bwBRnhFiOLaz4s91bvowwaB80oHgm_bjLPLnYo=:0)

**Comment by Xhofe** [comment]
你需要填写一下根文件夹路径这一项 比如`/`
