### ISSUE TITLE
3.7.1版本调用potplayer失败

### ISSUE THREAD

**Issue by fcwys** [alist-org/alist#2838]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.7.1

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

文件路径包含中文时调用potplay失败，另外看了下前端代码链接替换部分的uri编码似乎没有起作用

### Reproduction / 复现链接

调用potplayer显示中文乱码

**Comment by Xhofe** [comment]
更新potplayer
