### ISSUE TITLE
3.7.2版本在个人资料里无法变更账户名/密码的问题

### ISSUE THREAD

**Issue by SoDaSheep** [alist-org/alist#2852]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.7.2

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

在AList的3.7.2版本中，无论是何种权限的账户，均无法在“管理”-“个人资料”中变更自己的账户和密码。
详细情况为：在此页面对账户名/密码进行变更后点击"保存",变更后的账户名/密码不会被提交，也不会跳转到登录界面。

本地搭建/云端搭建此问题均会出现

### Reproduction / 复现链接

[本地搭建，无链接，任意3.7.2版本的AList均可复现](https://github.com/alist-org/alist/)

**Comment by SoDaSheep** [comment]
补充一点，此版本仍旧可在admin账户的“管理”-“用户”中对账户名和密码进行更改。

**Comment by crosspacific** [comment]
我也遇到了

**Comment by jzxkkk** [comment]
我也遇到了
