### ISSUE TITLE
下载问题?

### ISSUE THREAD

**Issue by zzj2039** [alist-org/alist#2857]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.6.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

我的网站使用的是非标端口 在下载文件时 点击下载按钮无法下载（没有指定端口） 当我点击复制链接按钮进行下载时又可以正常下载

### Reproduction / 复现链接

https://wdsj.pro:55/%E8%BF%9C%E7%A8%8B%E5%B7%A5%E5%85%B7%EF%BC%88%E4%B8%8B%E8%BD%BD%E8%AF%B7%E4%BD%BF%E7%94%A8%E5%A4%8D%E5%88%B6%E9%93%BE%E6%8E%A5%E6%8C%89%E9%92%AE%E4%B8%8B%E8%BD%BD%EF%BC%89/ToDesk_Lite.exe

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/configuration.html#site-url
