### ISSUE TITLE
Linux下以.开头的隐藏文件夹不在web端列表中

### ISSUE THREAD

**Issue by earthjasonlin** [alist-org/alist#2858]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.7.2

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

在操作系统中mkdir一个.开头的文件夹，它在alist里面不会出现，用webdav啥的也不好使，有些App的同步功能（比如Joplin）会报错：
PUT .sync/version.txt: Unknown error 2 (405): Method Not Allowed

### Reproduction / 复现链接

在操作系统中mkdir一个.开头的文件夹，然后去web端或者是webdav里面试着上传或者新建文件

### Logs / 日志

failed to get dir [/joplin/.sync] 
[GIN] 2023/01/01 - 12:13:21 | 405 |     532.709µs | XXX.XXX.XXX.XXX | PUT      "/dav/joplin/.sync/version.txt"

**Comment by earthjasonlin** [comment]
linux系统

**Comment by xclidongbo** [comment]
一样的错误。
