### ISSUE TITLE
onedrive 

### ISSUE THREAD

**Issue by qingshanshi** [alist-org/alist#2862]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.7.2

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

failed get objs: failed to list objs: Resource not found for the segment 'children'.

how to solve

### Reproduction / 复现链接

no ip

**Comment by zhaobudaomingzi** [comment]
请问你解决这个问题了吗
