### ISSUE TITLE
希望在cookie内加入浏览锚点记录功能。

### ISSUE THREAD

**Issue by Paper-Dragon** [alist-org/alist#2863]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

# 问题
在浏览比较长的页面的时候，点击子目录，如果再次返回父目录，显示页面的位置将会更新。找不到浏览的位置，
例子：https://alist.todesk.top/%E5%AF%B9%E5%A4%96%E5%88%86%E4%BA%AB

![alist-load-problem](https://user-images.githubusercontent.com/49874457/210163325-c0f8e94f-1c47-45e3-b0a0-c69b172f135a.gif)

# 建议
在页面内加入cookie锚点功能，返回上一页能够记录位置，有助于浏览，更加人性化。

### Suggested solution / 实现思路

- 页面内生成锚点
- 在cookie或其他浏览器存储内进行位置保存
- 缓存生命周期和清理操作

**Comment by hyh1750522171** [comment]
@Paper-Dragon

**Comment by hyh1750522171** [comment]
是这个页面设置的
<img width="503" alt="微信图片_20230101151539" src="https://user-images.githubusercontent.com/35066516/210163549-388748f4-30b6-4287-885d-1fab6bbe0312.png">

**Comment by haoduck** [comment]
这个确实是挺有用

**Comment by Xhofe** [comment]
duplicate of #2327
