### ISSUE TITLE
V3版本"Database is Locked"错误

### ISSUE THREAD

**Issue by erbanku** [alist-org/alist#2873]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.7.2

### Driver used / 使用的存储驱动

OneDrive和其他（下面区域提供截图）

## Describe the bug / 问题描述
在V3版本后台试图修改某些设置时出现"Database is Locked"错误，重启无效。 
## Driver used / 使用的存储驱动：
![ShareX_2023-01-02_09-22-40_Monday_Window](https://user-images.githubusercontent.com/79493862/210189710-44fc9744-bd3e-4d9f-84fe-af1a558580a0.png)

### Reproduction / 复现链接

不知道如何复现，但是我在进入`@manage`页面，试图修改一些配置（不管是什么配置），显示`Database is Locked`错误，重启无效。

## Update search index error while index new node: database is locked.
![image](https://user-images.githubusercontent.com/79493862/210189617-b0080ba2-9d43-4b87-83af-5e20cfe1ecaf.png)

**Comment by anwen-anyi** [comment]
你在构建索引吧？

**Comment by erbanku** [comment]
> 你在构建索引吧？

是的，构建索引Database不应该Locked呀。
这导致索引无法更新、设置无法修改。

**Comment by anwen-anyi** [comment]
> > 你在构建索引吧？
> 
> 是的，构建索引Database不应该Locked呀。 这导致索引无法更新、设置无法修改。

你等索引构建完毕了在修改试试呢，貌似就是这么设置的构建期间锁数据库

**Comment by Xhofe** [comment]
https://alist.nn.ci/guide/advanced/search.html#search-tips

**Comment by erbanku** [comment]
Many Thanks to all.
