### ISSUE TITLE
115 some videos load failed

### ISSUE THREAD

**Issue by liuhangbin** [alist-org/alist#2874]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.7.2

### Driver used / 使用的存储驱动

一键安装，不清楚驱动

### Describe the bug / 问题描述

115网盘部分视频打开后显示 Reconnect, 尝试5次之后报 Video load failed.
失败的视频大部分都是2G以上的美剧。国产电视剧貌似没问题...我用手机和电脑客户端
都可以正常打开。

### Reproduction / 复现链接

暂时没有。

### Logs / 日志

![1](https://user-images.githubusercontent.com/1594572/210191514-c2312716-fd7d-43cc-803b-8cb70ceff2cf.png)

**Comment by anwen-anyi** [comment]
大大的 H.265 写着呢 QAQ

**Comment by liuhangbin** [comment]
> 大大的 H.265 写着呢 QAQ

不好意思，我不太清楚，是不支持 H.265 格式吗？ 没看到 doc 里面有这个说明。搜索issue 也没搜到

**Comment by anwen-anyi** [comment]
> > 大大的 H.265 写着呢 QAQ
> 
> 不好意思，我不太清楚，是不支持 H.265 格式吗？ 没看到 doc 里面有这个说明。搜索issue 也没搜到

https://alist.nn.ci/zh/faq/why.html#为什么我不能预览视频或音频文件

**Comment by liuhangbin** [comment]
> > 不好意思，我不太清楚，是不支持 H.265 格式吗？ 没看到 doc 里面有这个说明。搜索issue 也没搜到
> 
> [https://alist.nn.ci/zh/faq/why.html#为什么我不能预览视频或音频文件](https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E8%83%BD%E9%A2%84%E8%A7%88%E8%A7%86%E9%A2%91%E6%88%96%E9%9F%B3%E9%A2%91%E6%96%87%E4%BB%B6)

感谢！读文档的时候就看到安装配置，没注意还有`常见问题` 页。建议把这个页面链接也加入到 [在提交新的issue之前你需要知道的](https://github.com/alist-org/alist/issues/1393)
