### ISSUE TITLE
访客绑定Github

### ISSUE THREAD

**Issue by 12189108** [alist-org/alist#2888]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.7.2

### Driver used / 使用的存储驱动

*

### Describe the bug / 问题描述

以访客登陆身份登录，进入后台界面，有绑定Github的选项，访客应不允许此操作

### Reproduction / 复现链接

*

**Comment by taozhiyu** [comment]
不过好在未登录没有权限修改

此外，在未授权的用户请求github登录时，会显示
```json
{"code":400,"message":"The Github ID is not associated with a user: record not found","data":null}
```
最好应该返回登录页，并且弹窗提醒授权失败（类似于portainer）

![image](https://user-images.githubusercontent.com/49258735/210525991-a074f6cc-d287-4fb9-b943-e32af7bf4341.png)

最好可以删除账号密码登录的按钮，只留一个github登录按钮，如果无法登录，需要使用cli 命令 清除github信息
