### ISSUE TITLE
功能请求：在http页面将选中下载直链批量导出为m3u文件

### ISSUE THREAD

**Issue by waeshang** [alist-org/alist#2902]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

选中链接导出为m3u，好处是方便手机可以通过第三方播放器比如mpv播放。
特别是追剧用于连续播放多个mkv文件，如果能实现好处是很大的。

### Suggested solution / 实现思路

功能请求：在http页面将选中下载直链批量导出为m3u文件
选中链接导出为m3u，好处是方便手机可以通过第三方播放器比如mpv播放。
特别是追剧用于连续播放多个mkv文件，如果能实现，好处是很大的。

**Comment by BoYanZh** [comment]
没看懂 什么是批量导出 在哪一页操作

**Comment by mengguyi** [comment]
不懂，m3u不是直播用的吗。alist想把mkv转m3u还要依赖ffmpeg

**Comment by waeshang** [comment]
在页面加一段JavaScript也能实现这个功能，greasyfork有针对aliyundriver网页端的js的实现。

> 不懂，m3u不是直播用的吗。alist想把mkv转m3u还要依赖ffmpeg
