### ISSUE TITLE
一刻相册无法正常上传&创建文件夹

### ISSUE THREAD

**Issue by Mcayear** [alist-org/alist#2911]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.7.2

### Driver used / 使用的存储驱动

一刻相册

### Describe the bug / 问题描述

在上传照片或者创建文件夹时提示错误
```
Errno: 2, refer to https://photo.baidu.com/union/doc
```
![屏幕截图(376)](https://user-images.githubusercontent.com/48203962/210685540-22341422-84e2-4292-b6fe-8c13ecc6e581.png)

### Reproduction / 复现链接

http://159.75.109.43:5244/BaiduPhoto

### Logs / 日志

```
[GIN] 2023/01/05 - 10:29:32 | 200 |    301.7697ms |  223.146.153.92 | POST     "/api/fs/list"
[31mERRO[0m[2023-01-05 10:29:46] failed put /BaiduPhoto/: errno: 2, refer to https://photo.baidu.com/union/doc
github.com/alist-org/alist/v3/internal/op.Put
	/source/internal/op/fs.go:516
github.com/alist-org/alist/v3/internal/fs.putDirectly
	/source/internal/fs/put.go:54
github.com/alist-org/alist/v3/internal/fs.PutDirectly
	/source/internal/fs/fs.go:84
github.com/alist-org/alist/v3/server/handles.FsStream
	/source/server/handles/fsup.go:49
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.FsUp
	/source/server/middlewares/fsup.go:43
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:55
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1991
runtime.goexit
	/usr/local/go/src/runtime/asm_386.s:1326 
[GIN] 2023/01/05 - 10:29:46 | 200 |    1.3672017s |  223.146.153.92 | PUT      "/api/fs/put"
```

**Comment by Mcayear** [comment]
在 [Tool ](https://openapi.baidu.com/oauth/2.0/authorize?response_type=code&client_id=iYCeC9g08h5vuP9UqvPHKKSVrKFXGa1v&redirect_uri=https://tool.nn.ci/baidu/callback&scope=basic,netdisk&qrcode=1)更新token后问题没有解决。
更新前：
![屏幕截图(378)_LI](https://user-images.githubusercontent.com/48203962/210724046-292b88ab-6068-4f3c-a95e-0147a45c4acd.jpg)
更新后：
![屏幕截图(379)_LI](https://user-images.githubusercontent.com/48203962/210724077-03f15495-b019-4e64-8c99-ba2bdcd1c93f.jpg)

**Comment by 1649508134** [comment]
官网可以上传不

**Comment by Mcayear** [comment]
[官网](https://photo.baidu.com/) 可以上传。
我发现了新线索：
- 上传没有失败，它在`全部相册`是可见的
![屏幕截图(383)](https://user-images.githubusercontent.com/48203962/210725366-aa767710-7445-4060-b527-016580d89cc3.png)
- 但是在`对应的相册`不可见
![屏幕截图(384)](https://user-images.githubusercontent.com/48203962/210725478-f9a398fc-3846-4633-96a9-637d26cdcd10.png)

**Comment by zxdstyle** [comment]
复现了，把你的相册ID去掉就可以上传成功了，具体原因还在排查

**Comment by foxxorcat** [comment]
我还是改进一下把,这样写的确反人类了点

**Comment by zxdstyle** [comment]
@foxxorcat 可以在placeholder里提醒一下或者拆成两个配置

**Comment by foxxorcat** [comment]
直接代码里自动识别算了,文档写了都没看的

**Comment by Mcayear** [comment]
实在是抱歉。确实是我文档没看仔细。
在id中加上 “|{tid}”就可以正常工作了。

**Comment by xxnuo** [comment]
同样的问题，token和tid重新填写后仍未解决

**Comment by hejingjun** [comment]
> 同样的问题，token和tid重新填写后仍未解决 ![图片](https://private-user-images.githubusercontent.com/54252779/282240314-bb689493-e80d-4421-aa4f-bf9493b5d041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTM0ODQsIm5iZiI6MTcwOTA5MzE4NCwicGF0aCI6Ii81NDI1Mjc3OS8yODIyNDAzMTQtYmI2ODk0OTMtZTgwZC00NDIxLWFhNGYtYmY5NDkzYjVkMDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA0MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNDYyOWZkMmJlMWQ2Y2IxMGQ2MGE3YjRhNzQ2MjUxNDNjNTllNzk2YWQxOTVmZTA3MTkxZDUyODdhZDA2NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Or54_QQ80mmTVpy4NzsNAIYqfJqIHuB3z1e21RW7aOQ) 操作是从本地存储的目录复制到一刻相册的目录，文件是一个155Mb的flv文件

一刻相册非会员好像不能上传大视频，不知道基于Alist能否突破这个限制
