### ISSUE TITLE
建议：访客身份登录无需验证Token是否过期

### ISSUE THREAD

**Issue by SerendipityR-2022** [alist-org/alist#2914]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题，现在隔登录几天就会提示Token is expired.

### Suggested solution / 实现思路

访客身份登录时无需验证Token是否过期

**Comment by Xhofe** [comment]
只在你登录过才会提示。
