### ISSUE TITLE
功能请求：索引构建使用线程池并暴露相关线程参数可供调整

### ISSUE THREAD

**Issue by ZJUCJH** [alist-org/alist#2915]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现状：
挂载资源量较多的时候，索引构建很慢
120w+对象的索引构建大概需要6小时+

另外似乎增量更新索引没有起效，只能重构

**Comment by BoYanZh** [comment]
目录爬的快被封的也快，估计要完美的解决方案得在每个挂载下加个限速器的配置
