### ISSUE TITLE
希望增加MPC-BE播放器的调用支持

### ISSUE THREAD

**Issue by ArriettyQAQ** [alist-org/alist#2917]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题，希望增加MPC-BE播放器的调用支持

该播放器项目地址 https://sourceforge.net/projects/mpcbe/

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/preview.html#external-previews
