### ISSUE TITLE
初次加载很慢，L2Dwidget.js文件加载失败

### ISSUE THREAD

**Issue by archervanderwaal** [alist-org/alist#2921]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v2.0.0

### Driver used / 使用的存储驱动

BAIDU

### Describe the bug / 问题描述

第一次打开加载很慢，L2Dwidget.js文件加载失败

### Reproduction / 复现链接

https://pan.archervanderwaal.com/

### Logs / 日志

<img width="1832" alt="image" src="https://user-images.githubusercontent.com/18182408/210922020-172a2e88-d734-4816-8908-ba6c52a7d3cd.png">

**Comment by itsHenry35** [comment]
这不是因为你自己引入js添加了看板娘么...这又不是alist的bug，自己给这个文件找个快点的cdn吧

**Comment by archervanderwaal** [comment]
> 这不是因为你自己引入js添加了看板娘么...这又不是alist的bug，自己给这个文件找个快点的cdn吧

明白了，多谢
