### ISSUE TITLE
挂载的阿里云盘MKV视频没有声音

### ISSUE THREAD

**Issue by luiguangguan** [alist-org/alist#2932]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.7.2

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

[https://www.aliyundrive.com/s/npFnMCLN5LU](https://www.aliyundrive.com/s/npFnMCLN5LU)
这里面的MKV文件播放没有声音

### Reproduction / 复现链接

无

**Comment by lingim** [comment]
这是无法解析DTS音频编码的问题，跟Alist本身无关，需要用能硬件解码的设备或者软解的播放软件打开，浏览器是不支持这种需要交专利费的音频编码的。

**Comment by anwen-anyi** [comment]
差不多跟这个一样的道理吧QAQ....... 调用下面的播放器观看吧 嘿嘿
https://alist.nn.ci/zh/faq/why.html#为什么我不能预览视频或音频文件
