### ISSUE TITLE
本地存储某些路径无法显式

### ISSUE THREAD

**Issue by juhuan** [alist-org/alist#2941]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

环境：Ubuntu 和 群晖 都试过

按照官方文档部署，新建本地存储，发现有些路径无法挂载或显示

比如在群晖挂载这个路径 /volume3，会报错说不存在
<img width="510" alt="image" src="https://user-images.githubusercontent.com/46651841/211134256-1d0070bf-9670-43da-b4a2-680425e52ca9.png">
实际在系统中是有的
<img width="225" alt="image" src="https://user-images.githubusercontent.com/46651841/211134296-4dcc6c76-2fef-4f6b-b724-495e33aedff5.png">

在Ubuntu上挂载根目录/，但是这里像boot、data都没法显示
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/46651841/211134415-f78af11f-7d9f-4c4c-a5b8-16c3fefa091d.png">

### Reproduction / 复现链接

内网验证，暂无公网上的复现链接。重现部署命令

ubuntu：
sudo docker run -d --restart=always -v /data/app/alist/data:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest

synology:
sudo docker run -d --restart=always -v /volume3/docker/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest

**Comment by juhuan** [comment]
sorry, 原来默认是容器路径啊，已经解决了，加了一行-v /data:/data ，把需要管理的宿主路径挂载到容器里

帮忙关掉问题吧

**Comment by anwen-anyi** [comment]
> sorry, 原来默认是容器路径啊，已经解决了，加了一行-v /data:/data ，把需要管理的宿主路径挂载到容器里
> 
> 帮忙关掉问题吧

可以自行关闭的
