### ISSUE TITLE
能否将“阿里云盘分享”里的“刷新令牌”改为全局设置，而不必每个“阿里云分享”都单独设置？

### ISSUE THREAD

**Issue by xiamiwolf** [alist-org/alist#2948]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否将“阿里云盘分享”里的“刷新令牌”改为全局设置，而不必每个“阿里云分享”都单独设置？或者增加一个从全局获取和单独获取的选项？

**Comment by anwen-anyi** [comment]
用这个呗现在，第三方做的批量添加的可以阿里云盘分享的
https://github.com/yzbtdiy/alist_batch_add

**Comment by InitialXKO** [comment]
> 用这个呗现在，第三方做的批量添加的可以阿里云盘分享的 https://github.com/yzbtdiy/alist_batch_add

这个需要填folder，反而更麻烦

**Comment by waeshang** [comment]
> > 用这个呗现在，第三方做的批量添加的可以阿里云盘分享的 https://github.com/yzbtdiy/alist_batch_add
> 
> 这个需要填folder，反而更麻烦

简单写了个bash函数，能批量导入阿里分享链接。把这个函数复制添加到你的.bashrc文件里就能用了。

先在网页后台备份json文件，然后运行这个函数
运行格式
aliadd json 你备份json文件 <<< '名字+空格+分享ur l的列表'
或者
aliadd json 你备份json文件 < '包含名字+空格+分享的url的文件'
最后从你的后台恢复这个json文件
希望能帮到你
`aliadd () 
{ 
    [[ -f $1 ]] || { 
        echo "用法: $FUNCTION alist备份文件 <<< 'string'";
        return 1
    };
    lines=$(wc -l "$1" | cut -d " " -f1);
    ((lines < 1)) && { 
        echo file is empty !;
        return 2
    };
    sed $((lines-1)),\$d -i "$1";
    sed \$s/}/},/ -i "$1";
    while read url; do
        [[ -z $url ]] && continue;
        mount_patch=${url% *};
        root_folder_id=${url##*/};
        share_id=${url#*/s/};
        share_id=${share_id%/folder*};
        cat <<eof
  {
      "id": 3,
      "mount_path": "/$mount_patch",
      "order": 1,
      "driver": "AliyundriveShare",
      "cache_expiration": 30,
      "status": "work",
      "addition": "{\"refresh_token\":\"填写你的刷新令牌\",\"share_id\":\"${share_id}\",\"share_pwd\":\"\",\"root_folder_id\":\"${root_folder_id}\",\"order_by\":\"name\",\"order_direction\":\"ASC\"}",
      "remark": "/$mount_patch",
      "modified": "2023-01-11T11:36:36.794104022Z",
      "disabled": false,
      "order_by": "",
      "order_direction": "",
      "extract_folder": "front",
      "web_proxy": true,
      "webdav_policy": "native_proxy",
      "down_proxy_url": ""
      },
eof
    done >> "$1";
    sed \$s/},/}/ -i "$1";
    cat >> "$1" <<-eof
],
  "metas": []
}
eof
}
`
注意替换你的refresh_token

**Comment by oneisall8955** [comment]
非常强烈希望能实现这个功能。
这个功能建议拆分成管理阿里云盘的账户，以云盘的账号作为区分。
在创建存储时，由填入刷新令牌，替换成选择账号，每个云盘账号单独置顶refresh token即可。

至于为什么不做成全局的呢而是账号区分呢？
我的思考是：例如我有好几个阿里云盘账号，或者给朋友挂载他的阿里云，这样就很容易区分了。

**Comment by drw2005** [comment]
> 做一个token管理功能就可以了，所有网盘的token统一管理，网盘添加时由现在的填写token变成选择token。考虑到各网盘需要的信息不同，token管理模块，使用对应的json或者多行key value就可以。

支持这个建议，希望大佬考虑。

**Comment by InitialXKO** [comment]
Xiaoya的docker镜像已经支持，使用token.txt即可

**Comment by seerking** [comment]
确实，经常性出现有的存储token会丢失的现象，少量还可以手动，如果有几百个，那简直就是灾难

**Comment by elevenface** [comment]
确实，每次都手工拷贝，很是麻烦

**Comment by xzxiaoshan** [comment]
这个需求没有人讨论了？
