### ISSUE TITLE
ERROR CODE

### ISSUE THREAD

**Issue by kweefc** [alist-org/alist#2954]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0 Latest

### Driver used / 使用的存储驱动

百度云盘

### Describe the bug / 问题描述

下载百度资料出现了这个

{"error_code":31329,"error_msg":"hit black userlist , hit illeage dlna","request_id":178815420351913354}

**Comment by kweefc** [comment]
马来西亚不能下载百度网盘吗？

**Comment by sonichy** [comment]
我也出现了  
hit black userlist , hit illeage dlna
