### ISSUE TITLE
【群晖】temp目录中的文件，在创建并使用完成后删除失败，导致不能回收磁盘占用

### ISSUE THREAD

**Issue by xzxiaoshan** [alist-org/alist#2961]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

【群晖】temp目录中的文件，在创建并使用完成后删除失败，导致不能回收磁盘占用

错误日志如下：

```
^[[31mERRO^[[0m[2023-01-08 22:07:10] failed to remove file [/var/packages/alist3/target/bin/data/temp/aria2/2ebde8fb-a697-403a-a4bd-e0563b1cc54d/041002200111_38656162.pdf]
^[[31mERRO^[[0m[2023-01-08 22:07:10] failed to remove aria2 temp dir: unlinkat /var/packages/alist3/target/bin/data/temp/aria2/2ebde8fb-a697-403a-a4bd-e0563b1cc54d/041002200111_38656162.pdf: permission denied
```

经判断，原因为：
1、temp 目录的所有者为 alist3
2、在temp目录中创建的临时有 aria2 创建，所有者为 aria2
3、alist3 没有权限删除 aria2 的目录，故定义为bug

### Suggested solution / 实现思路

建议 temp 目录在使用后自动删除临时文件，并在管理台中提供自动或手动清理缓存的功能。

**Comment by BoYanZh** [comment]
给个文件的例子，正常退出应该会删

**Comment by foxxorcat** [comment]
重新启动会删除的
https://github.com/alist-org/alist/blob/9398cdaac1c1a55f4a9ec4f7d169e7d957f74e81/internal/bootstrap/config.go#L68
所以只能是使用时产生的

**Comment by xzxiaoshan** [comment]
> 给个文件的例子，正常退出应该会删

扒了错误日志，因为文件夹的所有者不同导致的删除失败。
temp 所有者为 alist3 ，uuid 的临时文件所有者为 aria2

**Comment by xzxiaoshan** [comment]
```
DSM920:/var/packages/alist3/target/bin/data$ ll
total 48
drwxrwxrwx 1 alist3 alist3    44 Jan  8 23:26 .
drwxr-xr-x 1 alist3 alist3    26 Jan  8 22:04 ..
-rwxrwxrwx 1 alist3 alist3   661 Jan  8 22:04 config.json
-rwxrwxrwx 1 alist3 alist3 45056 Jan  8 23:26 data.db
drwxrwxrwx 1 alist3 alist3    10 Jan  8 22:07 temp
DSM920:/var/packages/alist3/target/bin/data$ cd temp/
DSM920:/var/packages/alist3/target/bin/data/temp$ ll
total 0
drwxrwxrwx 1 alist3 alist3 10 Jan  8 22:07 .
drwxrwxrwx 1 alist3 alist3 44 Jan  8 23:26 ..
drwxr-xr-x 1 aria2  aria2   0 Jan  8 22:08 aria2
DSM920:/var/packages/alist3/target/bin/data/temp$ 
```

**Comment by xzxiaoshan** [comment]
功能测试场景：将A网盘的文件，复制到B网盘。A网盘的文件被 aria2 下载到temp目录中（文件夹所有者为 aria2），然后将下载的临时文件上传到网盘B后。 alist3 执行删除代码时出现权限问题。

**Comment by BoYanZh** [comment]
那就和alist没关系了，纯属自己没设置好权限

**Comment by xzxiaoshan** [comment]
> 那就和alist没关系了，纯属自己没设置好权限

alist 没有内置 aria2，在群晖中 alist 是一个独立的应用，aria2 也是一个独立的应用，分别安装后一定是2个不同的用户，这个temp的问题也就一定会发生，从纯程序猿角度来讲确实可以 alist 无关，但是这个问题也不加以提醒和说明也是100%必出现的问题。

但是如果作者能在文档或者其他相关地方给出提示和说明可能会更好一些。

> 从代码来说与 alist 无关，从应用角度来讲这就是一个必现的 bug，普通用户没有加一关注的话，是发现不了 temp 膨胀问题的。所以建议在相关地方给用户一个提醒。

**Comment by BoYanZh** [comment]
> 分别安装后一定是2个不同的用户

该命题为假
