### ISSUE TITLE
增加百度分享挂载功能

### ISSUE THREAD

**Issue by wowdd1** [alist-org/alist#2967]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增加百度分享链接的挂载功能  参考阿里云盘分享挂载

**Comment by Xhofe** [comment]
根据百度网盘官方文档，未提供获取分享文件链接接口，无法实现。

**Comment by laoqijun** [comment]
> 根据百度网盘官方文档，未提供获取分享文件链接接口，无法实现。

能否根据
https://github.com/yuantuo666/baiduwp-php
这个实现？
