### ISSUE TITLE
增加夸克分享挂载功能

### ISSUE THREAD

**Issue by wowdd1** [alist-org/alist#2968]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增加夸克分享链接的挂载功能 参考阿里云盘分享挂载

**Comment by Xhofe** [comment]
未发现通过分享链接获取文件直链的接口，无法实现。

**Comment by xiaoyaliu00** [comment]
> 未发现通过分享链接获取文件直链的接口，无法实现。

可以转存到自己夸克盘，获取新fid再播放，举例

请求：
https://drive-pc.quark.cn/1/clouddrive/share/sharepage/save?pr=ucpro&fr=pc&uc_param_str=&__dt=29418&__t=1716817707174
POST内容：
 {"fid_list":["92b53f8a670243628f8aa2fd94c9af6d"],"fid_token_list":["9a1601abf70a916b194163b501cbc41c"],"to_pdir_fid":"4e51a4bf74d84d6d82e8a9eda3f5372f","pwd_id":"3d0adc9f7429","stoken":"eXOtPYMDWe3oCPJiryOYoDhPwb+3HemggLfqrKGja8M=","pdir_fid":"0","scene":"link"}
返回：
{
    "status": 200,
    "code": 0,
    "message": "ok",
    "timestamp": 1716817708,
    "data": {
        "task_id": "e12eef9bc9c042d9891e89e0881e632f"
    },
    "metadata": {
        "tq_gap": 500
    }
}

获取任务编号 e12eef9bc9c042d9891e89e0881e632f ，然后请求任务编号获取结果，也就是新的file id

请求：
https://drive-pc.quark.cn/1/clouddrive/task?pr=ucpro&fr=pc&uc_param_str=&task_id=e12eef9bc9c042d9891e89e0881e632f&retry_index=2&__dt=31269&__t=1716817709025
返回：
{
    "status": 200,
    "code": 0,
    "message": "ok",
    "timestamp": 1716817710,
    "data": {
        "task_id": "e12eef9bc9c042d9891e89e0881e632f",
        "event_id": "99fk42-228c9e052978bb",
        "task_type": 17,
        "task_title": "分享-转存",
        "status": 2,
        "created_at": 1716817708654,
        "finished_at": 1716817710050,
        "share": {},
        "save_as": {
            "search_exit": true,
            "to_pdir_fid": "4e51a4bf74d84d6d82e8a9eda3f5372f",
            "is_pack": "0",
            "save_as_top_fids": [
                "**13d4fad2bcb143ad8add01a8019c6fa6**"
            ],
            "to_pdir_name": "来自：分享"
        }
    },
    "metadata": {
        "tq_gap": 1500
    }
}

13d4fad2bcb143ad8add01a8019c6fa6 应该就是新的 file id
