### ISSUE TITLE
本地存储启用缩略图和数据库搜索，显示一堆的报错信息： update search index error while del old node: database is lock

### ISSUE THREAD

**Issue by iesv** [alist-org/alist#2971]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.7.2

### Driver used / 使用的存储驱动

本地驱动

### Describe the bug / 问题描述

本地存储启用缩略图和数据库搜索，显示一堆的报错信息：
update search index error while del old node: database is lock

### Reproduction / 复现链接

无

### Logs / 日志

ERRO[2023-01-09 14:42:39] update search index error while del old node: database is lock[10/1806]│n.be61f06a.js"
INFO[2023-01-09 14:42:39] index obj count: 3585                                                  │[GIN] 2023/01/08 - 08:08:06 | 200 |     174.721µs |  87.236.176.223 | GET      "/"
ERRO[2023-01-09 14:42:40] update search index error while del old node: database is locked       │[GIN] 2023/01/08 - 16:50:57 | 200 |     171.697µs |   89.248.165.52 | CONNECT  ""
INFO[2023-01-09 14:42:40] index obj count: 123                                                   │[GIN] 2023/01/08 - 17:32:59 | 200 |     141.177µs |   89.248.165.52 | CONNECT  ""
ERRO[2023-01-09 14:42:40] update search index error while del old node: database is locked       │[GIN] 2023/01/08 - 17:32:59 | 200 |      99.197µs |   89.248.165.52 | GET      "/"
INFO[2023-01-09 14:42:41] index obj count: 868                                                   │[GIN] 2023/01/09 - 05:15:08 | 200 |     142.123µs | 156.251.172.207 | GET      "/"
ERRO[2023-01-09 14:42:41] update search index error while del old node: database is locked       │[GIN] 2023/01/09 - 05:15:26 | 200 |     138.217µs | 156.251.172.207 | GET      "/robots.txt"
ERRO[2023-01-09 14:42:42] update search index error while del old node: database is locked       │[GIN] 2023/01/09 - 05:15:26 | 200 |     128.287µs | 156.251.172.207 | GET      "/sitemap.xml"
INFO[2023-01-09 14:42:42] index obj count: 17993

**Comment by Xhofe** [comment]
sqlite3不支持并发写 如果你要启用自动更新索引 请考虑使用其他数据库。
