### ISSUE TITLE
百度云下载大文件报错

### ISSUE THREAD

**Issue by xiaoxintang** [alist-org/alist#2973]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

使用docker镜像，右键下载大文件的时候无法下载

### 使用官方接口下载报错
```
{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":1589273305709486850}
```

### 使用非官方接口报错
```
{"error_code":31329,"error_msg":"hit black userlist , hit illeage dlna","request_id":200530104803184948}
```

### 使用curl 添加请求头的方式报错
```
{"code":401,"message":"expire missing","data":null}%
```

### Reproduction / 复现链接

无

### Logs / 日志

无

**Comment by coderZoe** [comment]
同样的问题，不知道这个issue为什么关了，也没写解决方案或者建议

**Comment by kuanos** [comment]
同样的问题，{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":2090082498753930192}

**Comment by junchao98** [comment]
存储设置里启用Web 代理

**Comment by zfx-t** [comment]
> 同样的问题，{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":2090082498753930192}

你复制的下载连接会讲过302重定向变成一个新的百度网盘直链，解决方法就是：先在浏览器打开复制的连接，经过302后再用新的链接重新下载

**Comment by qllokirin** [comment]
1 使用302重定向策略需要设置ua才能下载大文件
2 勾选Web 代理 使用本地代理，Alist会下载之后再传给你就不用设置ua了
3 非官方接口非会员下载大文件大概率提示31119，是限制 很正常
