### ISSUE TITLE
蓝奏云“请忽使用第三方工具”

### ISSUE THREAD

**Issue by yoval** [alist-org/alist#2974]
### Please make sure of the following things

- [X] I'm sure there are no duplicate issues or discussions.
- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v2.6.4-0-gbd52df1-dirty

### Driver used / 使用的存储驱动

lanzou

### Describe the bug / 问题描述

![](https://pan.bizha.top/view.php/e95b4c30188e815307337a21f5443855.png)

### Reproduction / 复现链接

https://yun.bizha.top/Lanzou/MagiskModels

**Comment by wangwuxuan2011** [comment]
请先尝试把AList升级到最新版本，复现链接的版本号为v3.6.0，最新版本为v3.8.0
