### ISSUE TITLE
Mysql做数据库时的搜索结果不全

### ISSUE THREAD

**Issue by haoduck** [alist-org/alist#2975]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

mysql只能搜索到从开头截断的关键词，搜不到从中间截断的关键词。  

例如文件夹“ABCD1234”，mysql作为数据库时，可以用"ABC"搜到，也可以用"ABCD12"搜到（关键词需要从最开头的A开始）  
用"BC"或者"CD123"、"1234"这些从中间截断的字符就搜不到结果。  

用sqlite3作为数据库时上述的关键词都能搜到结果，如图所示。  

### Additional context / 附件

![image](https://user-images.githubusercontent.com/56804964/211285669-4a7ac861-546d-41f2-9b3f-0f66d639fe9e.png)
![image](https://user-images.githubusercontent.com/56804964/211285747-8c9c64ac-9d9b-4a05-90c6-98fceb2ebd53.png)
![image](https://user-images.githubusercontent.com/56804964/211286798-e6868315-5287-4962-b795-ca0af2dce924.png)
以上为mysql截图  
——————————————————————  
以下为sqlite3截图  
![image](https://user-images.githubusercontent.com/56804964/211286091-42a92bf2-ddc2-4d84-86c9-79b59c21b439.png)
![image](https://user-images.githubusercontent.com/56804964/211286156-5788e387-3e5a-4398-a11a-08a6fe5a12b1.png)
![image](https://user-images.githubusercontent.com/56804964/211286658-4e10b1ad-afd4-416d-ab72-bc98f6c38d34.png)

**Comment by anwen-anyi** [comment]
3.7.x 
3.8.x 
以上两个版本 MySQL暂时还是有一些问题的 已知问题在修复中....

**Comment by foxxorcat** [comment]
mysql 全文索引在布尔模式下*只能模糊匹配右值,真让人头大的

**Comment by BoYanZh** [comment]
下个版本可以让mysql不用全文搜索，用LIKE慢慢搜

**Comment by BoYanZh** [comment]
这个issue应该可以关掉，sqlite3就是现在只会用LIKE搜，下个版本mysql也可以这样了

**Comment by snailwind** [comment]
postgres好像就没有模糊查询，开头就没法匹配
