### ISSUE TITLE
onedrive根据文档挂载报错，无法使用自己获取的密钥

### ISSUE THREAD

**Issue by ULeeBu** [alist-org/alist#2980]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v2.0/3.0

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/40551517/211453875-bdad4282-4b95-46eb-8db0-8307c42125c0.png)
![image](https://user-images.githubusercontent.com/40551517/211454331-dee3c8e3-669b-4f1f-8bb0-1259ab20982d.png)

onedrive的密钥和id使用微软官方注册的会在获取刷新令牌的时候报错，只能使用打开获取网址默认的进行获取

### Reproduction / 复现链接

https://tool.nn.ci/onedrive/request

### Logs / 日志

![image](https://user-images.githubusercontent.com/40551517/211454344-4124e317-4dc8-4593-88de-72919fbbeaf1.png)

**Comment by mengguyi** [comment]
![RQ4HU)7B_4SKCXK3IXYYV](https://user-images.githubusercontent.com/73788063/211465377-36f45d09-c0bc-4ebd-9cd9-b84a71b7ef34.png)
我这里是好使的，你的可能是教育版账户。只能用webdav方式挂载
