### ISSUE TITLE
`can't find storage with rawPath: /xxx` in log

### ISSUE THREAD

**Issue by BoYanZh** [alist-org/alist#2984]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

-

### Describe the bug / 问题描述

Just as a reminder for myself.
According to my observation, /xxx is always a path in the root, but the corresponding directory does not always exist. Even if /xxx exists, the error will occur as before.

### Reproduction / 复现链接

-

### Logs / 日志

[31mERRO[0m[2023-01-06 18:57:07] failed get All - DailyCheckIn - 云函数: can't find storage with rawPath: /All - DailyCheckIn - 云函数
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/source/internal/op/path.go:18
github.com/alist-org/alist/v3/internal/fs.get
	/source/internal/fs/get.go:25
github.com/alist-org/alist/v3/internal/fs.Get
	/source/internal/fs/fs.go:26
github.com/alist-org/alist/v3/internal/search.BuildIndex
	/source/internal/search/build.go:141
github.com/alist-org/alist/v3/internal/search.Update
	/source/internal/search/build.go:219
github.com/alist-org/alist/v3/internal/op.List.func1.1
	/source/internal/op/fs.go:113
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
failed get storage

**Comment by InitialXKO** [comment]
Did you add any storage? Alist will always report error until first storage is added.

**Comment by BoYanZh** [comment]
> Did you add any storage? Alist will always report error until first storage is added.

Yes. I will fix this error later by myself I think.

**Comment by chengnan049** [comment]
> Did you add any storage? Alist will always report error until first storage is added.

Hey bro, he is Dev

**Comment by www963257827** [comment]
![image](https://user-images.githubusercontent.com/49772139/219293162-9273c407-44e4-4928-8b31-ea879af0f3fc.png)
点击这个地方，添加第一个存储，或者可以参考这个使用教程
https://zhuanlan.zhihu.com/p/572827191
