### ISSUE TITLE
aria2 上传报错

### ISSUE THREAD

**Issue by wxyhgk** [alist-org/alist#2985]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8

### Driver used / 使用的存储驱动

Onedrive 123网盘

### Describe the bug / 问题描述

已经部署好了 aria2 ，可以下载，但是上传报错，不知道为什么，看了所有的issue都没人指出这个问题
![image](https://user-images.githubusercontent.com/37659181/211522610-52d93e2a-59ba-4b3d-94c2-c852b428174d.png)

### Reproduction / 复现链接

failed to open file /opt/alist/data/temp/aria2/ff4fb32a-f8ba-4467-969d-84639755b9da/aria2.sh: open /opt/alist/data/temp/aria2/ff4fb32a-f8ba-4467-969d-84639755b9da/aria2.sh: no such file or directory

### Logs / 日志

failed to open file /opt/alist/data/temp/aria2/ff4fb32a-f8ba-4467-969d-84639755b9da/aria2.sh: open /opt/alist/data/temp/aria2/ff4fb32a-f8ba-4467-969d-84639755b9da/aria2.sh: no such file or directory

**Comment by Xhofe** [comment]
docker?

**Comment by wxyhgk** [comment]
> 

是的，一个是docker部署的，一个不是，我看看这个

**Comment by Xhofe** [comment]
docker 请自行处理路径问题

**Comment by lentikr** [comment]
这个问题解决了吗？

**Comment by wxyhgk** [comment]
不行啊，我这个不是docker部署的，有问题
