### ISSUE TITLE
安全性建议

### ISSUE THREAD

**Issue by ZimJames** [alist-org/alist#2989]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

进入网页就是主页内容，且不用登录就能够看见挂载的网盘里的文件，感觉十分不安全。希望能改成必须登录才能进入主页，并查看和下载相关内容。

### Suggested solution / 实现思路

希望能改成必须登录才能进入主页，并查看和下载相关内容。

**Comment by panziqiang007** [comment]
添加个元信息，路径为/，设置密码并应用到子文件夹，下面根据需要设置是否写入。这样一打开主页就会提示输密码了。
