### ISSUE TITLE
让文件夹隐藏，不被看到但可以被存取

### ISSUE THREAD

**Issue by kugimiya530** [alist-org/alist#2993]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在的功能可以让文件夹隐藏
但是权限的部份一定要给"可以看隐藏文件"才能存取
但是我只想要隐藏，不想要被游客直接看到

但是如果他知道网址的话可以存取
有办法这样做吗

### Suggested solution / 实现思路

新版的隐藏就真的是隐藏，一定要开权限给使用者才能看到 与存取

有没有办法只存取 而不被看到?

不知道能不能把隐藏的 "存取" "看见" 细分成两个权限

**Comment by wangwuxuan2011** [comment]
加一层密码就可以了 #534

**Comment by kugimiya530** [comment]
试了一下 全局隐藏了以后，完全读取不到资料夹下面的东西...

**Comment by kugimiya530** [comment]
查了一下 
想要像这样的
https://github.com/alist-org/alist/discussions/2523#discussioncomment-4284805

**Comment by wangwuxuan2011** [comment]
> 试了一下 全局隐藏了以后，完全读取不到资料夹下面的东西...

我的理解是：你希望在隐藏的同时不通过URL进行访问文件的列表，但是希望通过wget类似的工具进行下载文件。

全局设置中的隐藏文件只是前端页面的判断，即：后端会返回所有的文件参数但是前端页面不显示出来，并不是真的在隐藏。它仍然存在于 api 返回的列表中，只是没有出现在前端列表中。

如果希望后端隐藏指定的文件或者文件夹，接口不返回该文件或文件夹的数据，可以编辑对应的元信息。

如不希望通过路径直接访问可以进行设置密码。如果你有wget的需求可以尝试使用直链，即输入密码后文件页面的**复制链接**

![image](https://user-images.githubusercontent.com/101337393/211707709-6aed9417-029f-4692-9b4e-1a8f0c9d557e.png)

请多查阅一下相关issue和文档，文档介绍的很详细。

**Comment by kugimiya530** [comment]
> > 试了一下 全局隐藏了以后，完全读取不到资料夹下面的东西...
> 
> 我的理解是：你希望在隐藏的同时不通过URL进行访问文件的列表，但是希望通过wget类似的工具进行下载文件。
> 
> 全局设置中的隐藏文件只是前端页面的判断，即：后端会返回所有的文件参数但是前端页面不显示出来，并不是真的在隐藏。它仍然存在于 api 返回的列表中，只是没有出现在前端列表中。
> 
> 如果希望后端隐藏指定的文件或者文件夹，接口不返回该文件或文件夹的数据，可以编辑对应的元信息。
> 
> 如不希望通过路径直接访问可以进行设置密码。如果你有wget的需求可以尝试使用直链，即输入密码后文件页面的**复制链接**
> 
> ![image](https://user-images.githubusercontent.com/101337393/211707709-6aed9417-029f-4692-9b4e-1a8f0c9d557e.png)
> 
> 请多查阅一下相关issue和文档，文档介绍的很详细。

感谢回复

其实我想要的是可以直接存取URL  但前端看不到

这样是不是就只有设置密码使用复制连接的选项了?

**Comment by wangwuxuan2011** [comment]
我或许不太理解你的意思，那你的需求是不是：在列表页面不显示文件夹，但是可以通过明确的链接进入页面并允许进行存取（即读取和写入）？

那可以直接打开对应目录元信息的写入功能即可允许未登录状态存取文件了。同时可以搭配隐藏功能就可以实现不显示文件夹的效果。

**Comment by kugimiya530** [comment]
> 我或许不太理解你的意思，那你的需求是不是：在列表页面不显示文件夹，但是可以通过明确的链接进入页面并允许进行存取（即读取和写入）？
> 
> 那可以直接打开对应目录元信息的写入功能即可允许未登录状态存取文件了。同时可以搭配隐藏功能就可以实现不显示文件夹的效果。

真的不行....

我把所有设置打出来好了

首先 游客权限 全无  

然后
测试1.
全局隐藏资料夹
然后元信息可以写入 包括子资料夹

结果:存取结果为 object not found

测试2.
全局不隐藏  
元信息把资料夹隐藏 并且打开写入
结果: 存取结果为需要密码
然而 我并没有设置密码...

**Comment by wangwuxuan2011** [comment]
那可能是你的配置问题，你可以试着按下面的方法操作：

例如需要隐藏/file/hide文件夹，

你需要在/file文件夹中按照下图进行设置：

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/101337393/211716493-984207de-be8a-40b9-bd5c-48531397b07f.png">

然后在/file/hide文件夹中按照下图进行设置：

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/101337393/211716567-ca284ba7-33ce-41e3-b027-a0172d39a7a5.png">


> 测试2.
全局不隐藏
元信息把资料夹隐藏 并且打开写入
结果: 存取结果为需要密码
然而 我并没有设置密码...

密码可能是因为其他元信息影响，你可以逐一排查一下。

**Comment by kugimiya530** [comment]
> 那可能是你的配置问题，你可以试着按下面的方法操作：
> 
> 例如需要隐藏和允许写入/file/hide文件夹，
> 
> 你需要在/file文件夹中按照下图进行设置：
> 
> <img alt="image" width="1222" src="https://user-images.githubusercontent.com/101337393/211716493-984207de-be8a-40b9-bd5c-48531397b07f.png">
> 
> 然后在/file/hide文件夹中按照下图进行设置：
> 
> <img alt="image" width="1236" src="https://user-images.githubusercontent.com/101337393/211716567-ca284ba7-33ce-41e3-b027-a0172d39a7a5.png">
> 
> > 测试2.
> > 全局不隐藏
> > 元信息把资料夹隐藏 并且打开写入
> > 结果: 存取结果为需要密码
> > 然而 我并没有设置密码...
> 
> 密码可能是因为其他元信息影响，你可以逐一排查一下。

照你这样就可以了!!!!

感谢  所以这个下载东西都得透过跳出来的那个复制链接下载是吗

不能用原始的准确URL直连下载  例如 网址/file/hide/123.zip

**Comment by wangwuxuan2011** [comment]
页面上有两种链接，

`复制链接`提供的是包含alist签名的直链，如果不设置过期时间将不会过期 。访问直链alist将获取最新的原始下载链接进行下载。

`下载`是根据存储方式得到的原始下载链接。原始下载链接大多数包含时效性的、由存储提供方定义的签名信息，所以并不能持久化，会在一定时间后失效，并且链接大多数也没有规律。

如果你想使用准确并可预测的url链接下载，并可以不受链接签名信息影响随时进行下载访问，你可以尝试使用例如**S3协议**（也就是Alist存储选项的**对象存储**）的存储桶，并且可绑定**自定义域名**的**公开**式存储策略。

例如我使用Cloudflare R2的公开存储桶进行存储，并绑定了自定义域名dl.website.com。而我的alist域名是website.com，当我访问website.com/file/hide/123.zip即是alist的文件页面，访问dl.website.com/file/hide/123.zip即可直接进行下载。

**Comment by kugimiya530** [comment]
好的 谢谢你的回答!!!

wangwuxuan2011 ***@***.***> 於 2023年1月11日 週三 下午12:53寫道：

**Comment by pipixia244** [comment]
同问一下，我现在使用如下配置隐藏文件夹下所有内容后，游客进入该文件夹必须输入密码，而我只进行隐藏未设置密码。
![image](https://user-images.githubusercontent.com/56287117/212749529-08d1ac4c-902b-4895-b772-5e4066fd0ff4.png)
我的目标是：目标文件夹在上层目录显示，但点开该文件夹后不显示文件夹内的任何文件，同时通过url仍能访问该文件夹内的文件。请问该如何设置呢？

**Comment by pipixia244** [comment]
@wangwuxuan2011 
同问一下，我现在使用如下配置隐藏文件夹下所有内容后，游客进入该文件夹必须输入密码，而我只进行隐藏未设置密码。而在v3.5.1及以前的版本中，该配置能正确实现我的目标。
![image](https://user-images.githubusercontent.com/56287117/212749529-08d1ac4c-902b-4895-b772-5e4066fd0ff4.png)
我的目标是：游客访问时，目标文件夹在上层目录显示，但点开该文件夹后不显示文件夹内的任何文件，同时通过url仍能访问该文件夹内的文件。请问该如何设置呢？
alist版本v3.8.0

**Comment by wangwuxuan2011** [comment]
@pipixia244 
我注意到了这个问题，这个需求我现在还没想到解决的办法。作者在v3.5.1后的版本中修改了访问判断的逻辑，目前我不确定是作者有意为之还是出现了bug。我先试着修改一下代码看一下能不能按预期运行，有需要的话我再提交一个issue
#2532

**Comment by kugimiya530** [comment]
你的这个要求挺有趣的，感觉我也适用我的场景  hh

等待大佬更新



wangwuxuan2011 ***@***.***> 於 2023年1月17日 週二 下午4:49寫道：

**Comment by wangwuxuan2011** [comment]
@pipixia244 对于

> 游客进入该文件夹必须输入密码

对于输入密码的问题 可能是正则意外匹配到目录本级导致目录隐藏而触发了密码 我提交了PR等待作者合并

> 通过url仍能访问该文件夹内的文件

此问题参考 #2532 的安全性描述作者在后续的版本中似乎不希望将隐藏的文件进行公开

所以对此特性我没有做此方面的任何修改 所以在隐藏状态下再进行访问的需求可能需要其他解决办法 我试试看能不能加上个选项

**Comment by pipixia244** [comment]
@wangwuxuan2011 

> 此问题参考 #2532 的安全性描述作者在后续的版本中似乎不希望将隐藏的文件进行公开

作者的想法似乎是只要文件隐藏，则无权限账号就不应该能够访问任何内容。（无权访问隐藏文件的用户在访问到隐藏文件夹时，无论输入的url是否指向一个真正存在的文件，作者都加了一个永远不可能输入正确的密码输入提示框，以保护文件和文件列表不会泄露。）

但这里可能会存在“外链“的需求，需要在隐藏目录的同时允许游客url访问，并且此类需求并不需要很高的安全性保证。我所想的需求也是针对外链而言的，我觉得这种功能应该加入，毕竟用alist实现外链也是一种很好的选择。

> 所以对此特性我没有做此方面的任何修改 所以在隐藏状态下再进行访问的需求可能需要其他解决办法 我试试看能不能加上个选项

针对这个问题，确实是如果能加上一个选项控制是否进行url保护就好了，感谢大佬！

（另外小声吐槽一下，元数据部分隐藏文件可以靠正则匹配很多文件/文件夹，但加密文件似乎只能加密path一个文件/文件夹，导致加密多个文件要手动一个一个加）

**Comment by wangwuxuan2011** [comment]
@pipixia244 哈哈哈感觉你的需求有点有趣 
（我也小声问一句 为啥不直接调整一下目录结构 让分散的文件放在一个加密或隐藏的文件夹🤣

**Comment by pipixia244** [comment]
@wangwuxuan2011 
外链感觉还是挺常见的，类似图床功能的文件床（
（关于调整目录结构 有一说一有道理，我傻了😂😂）

**Comment by wangwuxuan2011** [comment]
@pipixia244 
外链功能也有啊 下载页面的复制链接不就是外链么 上面也讲到了呀
alist生成的只不过是sign无规律且不可推测罢了 这也是有意设计成这样的
如果是不希望经过alist的签名验证 那也可以用我上面说到的挂载s3公共存储桶的办法 这样所有文件都会不加密码的暴露在外 并且链接无签名并可推测
如果文件夹需要公开访问你放在一个不被隐藏且没有加密的目录里不就好了 允许游客编辑的话可以直接打开写入的开关就完事

原文：
复制链接提供的是包含alist签名的直链，如果不设置过期时间将不会过期 。访问直链alist将获取最新的原始下载链接进行下载，直链就是在站点host后跟随/d/加上文件路径加上签名信息，如https://website.com/file.doc的直链为https://website.com/d/file.doc?sign=xxxxx。

**Comment by pipixia244** [comment]
@wangwuxuan2011 
我的需求是对于一个Onedrive类型的storage，对游客隐藏文件夹内的所有文件/文件夹，但仍然可以被通过url不加签名直接访问，并且游客可以以看不到任何文件/文件夹的前提下往这个文件夹内上传文件，并获取链接。其实就是一个完全公开的存储但隐藏掉文件目录，确实相当于S3的特性，但S3的话就用不了OneDrive了吧，我主要还是利用OneDrive的空间。

看上去是个挺小众的需求，要不我就继续用旧版本或者看看能不能自己改一下代码吧，谢谢大佬！

**Comment by wangwuxuan2011** [comment]
@pipixia244 哦哦了解了，那我先尝试修改一下代码吧，如果你先改好了代码也可以PR🤣

**Comment by A1A2B3X** [comment]
确实是非常有必要的一个功能，因为我个人的一个一个应用场景就是：
希望收到共享的人能够无密码（设置Meta比较麻烦）的读取某个目录，但是不希望他到处乱翻，翻到我给其他人的东西（
