### ISSUE TITLE
V3.8百度网盘看不到图片，视频可以

### ISSUE THREAD

**Issue by fordiy** [alist-org/alist#2994]
**发现问题是由于Crack API导致的，用Offical API就可以!**

### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8

### Driver used / 使用的存储驱动

baidu

### Describe the bug / 问题描述

连接到的百度网盘里看图片一直提示：Failed to load image
视频可以
![image](https://user-images.githubusercontent.com/2220214/211704168-fbbed3bd-2128-4e0e-a0c3-dec0ce872ffa.png)

设置：
无论是否打开web proxy
无论WebDAV policy是什么

### Logs / 日志

![image](https://user-images.githubusercontent.com/2220214/211704687-6a71bc92-a01d-4ade-a6a3-9e5088ef676f.png)

**Comment by Xhofe** [comment]
文档中已经说明crack api并不是官方提供的api，它不一定可用
