### ISSUE TITLE
重大BUG;登过一次后在任何电脑打开都不需要登录了

### ISSUE THREAD

**Issue by dotanero9** [alist-org/alist#2995]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

阿里云

### Describe the bug / 问题描述

登过一次后在任何电脑打开都不需要登录了,可随意查看、下载等操作文件

### Reproduction / 复现链接

http://wsd.hnyygroup.com:5244/aliyun

**Comment by wangwuxuan2011** [comment]
> 可随意查看、下载等操作文件
设计就是如此，如有需要可以通过元信息设置隐藏或密码的方式进行权限控制。

我打开复现链接就是未登录状态，你可以进入站点[manage](http://wsd.hnyygroup.com:5244/@manage)页面查看现在是以游客还是已登录用户的身份访问。

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/101337393/211714030-7d81f7c0-07cb-4a5f-9efa-1390b4b22b2d.png">
