### ISSUE TITLE
Environment (Docker) UMASK is not valid for folders

### ISSUE THREAD

**Issue by Suyknow** [alist-org/alist#2996]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.8.0

### Driver used / 使用的存储驱动

Local storage

### Describe the bug / 问题描述

在Umask设置022后，文件的权限正常，为644，但是文件夹的权限不正常，依然是700。
After the Umask is set to 022, the permission of **FILE** is ok (**644**), but the permission of **FOLDER** is abnormal, which is still **700**

PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-- | --
PGID | 100
PUID | 1000
UMASK | 022

> [SuyMyAdmin@TS-264C Temp]$ ls -l
total 36
-rw-r--r-- 1 MyUsername everyone 31043 2023-01-11 10:58 test_file.png
drwx------ 2 MyUsername everyone  4096 2023-01-11 11:00 test_folder/
[SuyMyAdmin@TS-264C Temp]$ 

附：测试平台服务器端为Docker/X86，威联通Container Station，客户端Finder @ MacOS 13.2
PS: The server side of the test platform is Docker/X86, QNAP Container Station, and the client side is Finder @ MacOS 13.2

### Reproduction / 复现链接

NONE

### Logs / 日志

![DGFdRz6lNxbSkL2](https://s2.loli.net/2023/01/11/DGFdRz6lNxbSkL2.png)
![um9QLW2xUEJMXjR](https://s2.loli.net/2023/01/11/um9QLW2xUEJMXjR.png)

**Comment by DDSDerek** [comment]
这个文件是alist生成的吗？如果是alist生成的文件，`umask=022`的情况下，权限掩码应该是755，而不是上面所说的644

**Comment by Suyknow** [comment]
> 这个文件是alist生成的吗？如果是alist生成的文件，`umask=022`的情况下，权限掩码应该是755，而不是上面所说的644，文件夹也是755。如果文件不是alist生成的，那么alist不会更改文件权限。

@DDSDerek 文件和目录都是通过alist创建的，以及[据我了解](https://www.cyberciti.biz/tips/understanding-linux-unix-umask-value-usage.html)，umask022对应file和folder是不同的效果，文件默认舍弃X权限。

引用：The default umask for the root user is 022 result into default directory permissions are 755 and default file permissions are 644.

**Comment by DDSDerek** [comment]
> > 这个文件是alist生成的吗？如果是alist生成的文件，`umask=022`的情况下，权限掩码应该是755，而不是上面所说的644，文件夹也是755。如果文件不是alist生成的，那么alist不会更改文件权限。
> 
> @DDSDerek 文件和目录都是通过alist创建的，以及[据我了解](https://www.cyberciti.biz/tips/understanding-linux-unix-umask-value-usage.html)，umask022对应file和folder是不同的效果，文件默认舍弃X权限。
> 
> 引用：The default umask for the root user is 022 result into default directory permissions are 755 and default file permissions are 644.

@Suyknow  是的，你理解是正确的，是我理解错误了。并且经过测试，无论umask怎么设置，文件夹权限都是700，而文件权限会随之改变。说明文件夹创建时alist会重新设置权限，这需要改动程序，并不是镜像制作的错误。

**Comment by Suyknow** [comment]
> > > 这个文件是alist生成的吗？如果是alist生成的文件，`umask=022`的情况下，权限掩码应该是755，而不是上面所说的644，文件夹也是755。如果文件不是alist生成的，那么alist不会更改文件权限。
> > 
> > 
> > @DDSDerek 文件和目录都是通过alist创建的，以及[据我了解](https://www.cyberciti.biz/tips/understanding-linux-unix-umask-value-usage.html)，umask022对应file和folder是不同的效果，文件默认舍弃X权限。
> > 引用：The default umask for the root user is 022 result into default directory permissions are 755 and default file permissions are 644.
> 
> @Suyknow 是的，你理解是正确的，是我理解错误了。并且经过测试，无论umask怎么设置，文件夹权限都是700，而文件权限会随之改变。说明文件夹创建时alist会重新设置权限，这需要改动程序，并不是镜像制作的错误。

@DDSDerek 只能等作者更新了……

**Comment by Suyknow** [comment]
@Xhofe hello, 这个BUG又出现了……文件权限还是正常，但是文件夹权限不正常，无论umask设置什么值，文件夹权限都会变成411
