### ISSUE TITLE
建议解决跨盘转移后文件同步懒加载的问题，以及文件夹和文件的数量统计功能和多选功能

### ISSUE THREAD

**Issue by STEVENTAN100** [alist-org/alist#3003]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我在同步OneDrive和别的网盘（如阿里云、123云盘）的文件时，如果是拷贝到OneDrive的，那么在OneDrive目录下就可以及时看到结果，可是把文件反向拷贝到别的网盘时，却不能及时刷新，点击存储的**重新加载**功能也没有用，必须要采用systemctl restart alist的方式。

建议增加文件夹和文件的数量统计功能，方便对文件夹进行管理。

建议增加文件多选功能，批量下载、移动、复制文件。

希望复制文件操作能个性化，能选择同时传输多少文件（好像默认是3），加快速度。

**Comment by foxxorcat** [comment]
1.懒加载是有接口的,因为是可选实现所以大部份存储都没实现
2.文件信息不是一次性读取到缓存的,这样网盘api容易炸.没有完全获取,统计的数量也没有意义

**Comment by STEVENTAN100** [comment]
谢谢，已找到！
