### ISSUE TITLE
华硕路由器AC68U ARMV7架构，安装几个arm版本的都不能运行

### ISSUE THREAD

**Issue by inspurhua** [alist-org/alist#3005]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8

### Driver used / 使用的存储驱动

None

### Describe the bug / 问题描述

华硕路由器AC68U ARMV7架构，安装几个arm版本的都不能运行

### Reproduction / 复现链接

华硕路由器AC68U ARMV7架构，安装几个arm版本的都不能运行

### Logs / 日志

华硕路由器AC68U ARMV7架构，安装几个arm版本的都不能运行

**Comment by BoYanZh** [comment]
这就是你的日志？

**Comment by Xhofe** [comment]
若prebuilt不可用请自行在目标机器编译，这通常比交叉编译具有更好的兼容性。
