### ISSUE TITLE
123云盘在webdav中无法下载或读取文件

### ISSUE THREAD

**Issue by MichaelChao02** [alist-org/alist#3006]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.2.1

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

我在使用rclone挂载webdav后，发现`123云盘`中的文件无法下载或读取。即使不挂载直接用rclone(webdav协议)下载也不行。在`Windows` 和 `Linux`上都尝试了存在相同的问题。

alist显示错误信息` ERROR RESTY json: cannot unmarshal string into Go struct field DownResp.code of type int, Attempt 1`，有很多行一样的重复信息。rclone挂载后显示错误`Internal Server Error: 500 Internal Server Error`。用rclone直接下载会出现`corrupted on transfer: sizes differ`

其它网盘的下载是正常的！不使用webdav而是直接使用alist的网页端下载也是正常的！

log文件在下方

### Reproduction / 复现链接

`rclone copy webdav:123pan/cmder_mini.zip local/path/ --size-only -P`

### Logs / 日志

[GIN] 2023/01/11 - 08:13:13 | 207 |    314.5425ms |       127.0.0.1 | PROPFIND  "/dav/123pan/cmder_mini.zip"
[GIN] 2023/01/11 - 08:13:13 | 207 |       136.7µs |       127.0.0.1 | PROPFIND  "/dav/123pan/cmder_mini.zip"
[GIN] 2023/01/11 - 08:13:13 | 302 |    216.7365ms |       127.0.0.1 | GET      "/dav/123pan/cmder_mini.zip"
[GIN] 2023/01/11 - 08:13:13 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/123pan/cmder_mini.zip"
[GIN] 2023/01/11 - 08:13:13 | 302 |    138.6973ms |       127.0.0.1 | GET      "/dav/123pan/cmder_mini.zip"
[GIN] 2023/01/11 - 08:13:14 | 207 |       334.1µs |       127.0.0.1 | PROPFIND  "/dav/123pan/cmder_mini.zip"
[GIN] 2023/01/11 - 08:13:14 | 302 |    146.6684ms |       127.0.0.1 | GET      "/dav/123pan/cmder_mini.zip"
[GIN] 2023/01/11 - 08:14:03 | 207 |      1.7169ms |       127.0.0.1 | PROPFIND  "/dav/123pan"
[GIN] 2023/01/11 - 08:14:03 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/"
[GIN] 2023/01/11 - 08:14:13 | 207 |      2.8497ms |       127.0.0.1 | PROPFIND  "/dav/123pan/"
[31mERRO[0m[2023-01-11 08:14:13] failed link /123pan/电脑安装这个.exe: json: cannot unmarshal string into Go struct field DownResp.code of type int
failed get link
github.com/alist-org/alist/v3/internal/op.Link.func1
	/source/internal/op/fs.go:156
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.Link
	/source/internal/op/fs.go:163
github.com/alist-org/alist/v3/internal/fs.link
	/source/internal/fs/link.go:16
github.com/alist-org/alist/v3/internal/fs.Link
	/source/internal/fs/fs.go:35
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleGetHeadPost
	/source/server/webdav/webdav.go:237
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/source/server/webdav/webdav.go:55
github.com/alist-org/alist/v3/server.ServeWebDAV
	/source/server/webdav.go:44
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/alist-org/alist/v3/server.WebDAVAuth
	/source/server/webdav.go:93
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:11
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/gin.go:613
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/gin.go:569
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1991
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594 
[31mERRO[0m[2023-01-11 08:14:13] GET /dav/123pan/电脑安装这个.exe json: cannot unmarshal string into Go struct field DownResp.code of type int
failed get link
github.com/alist-org/alist/v3/internal/op.Link.func1
	/source/internal/op/fs.go:156
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.Link
	/source/internal/op/fs.go:163
github.com/alist-org/alist/v3/internal/fs.link
	/source/internal/fs/link.go:16
github.com/alist-org/alist/v3/internal/fs.Link
	/source/internal/fs/fs.go:35
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleGetHeadPost
	/source/server/webdav/webdav.go:237
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/source/server/webdav/webdav.go:55
github.com/alist-org/alist/v3/server.ServeWebDAV
	/source/server/webdav.go:44
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/alist-org/alist/v3/server.WebDAVAuth
	/source/server/webdav.go:93
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:11
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/gin.go:613
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/gin.go:569
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1991
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594

**Comment by MichaelChao02** [comment]
为什么给关闭了？

**Comment by Xhofe** [comment]
勾选与所述不符

**Comment by MichaelChao02** [comment]
> 勾选与所述不符

能不能具体一点？

**Comment by Xhofe** [comment]
**I'm sure I'm using the latest version**

**Comment by mengguyi** [comment]
> > 勾选与所述不符
> 
> 能不能具体一点？
 I'm sure I'm using the latest version
