### ISSUE TITLE
380+372被ESET报Win32/Kryptik.BD

### ISSUE THREAD

**Issue by DuangXT** [alist-org/alist#3009]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.8.0

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

如题，解压后被秒，尝试老版371正常，其它没测试。
请问是否是因为372开始32位更换了什么内容导致的呢？
是否可以忽略此查杀呢？

### Reproduction / 复现链接

non

### Logs / 日志

![a](https://user-images.githubusercontent.com/15960478/211889102-2240d3e2-2548-4881-9c20-728b3afc0d6e.png)

**Comment by mengguyi** [comment]
如果不放心请自行编译
https://alist.nn.ci/zh/guide/install/source.html
windows defender未报毒

**Comment by Xhofe** [comment]
prebuilt 均由github actions自动编译 中间过程完全透明。

另对于Windows版本 我们使用了upx压缩，一些防病毒软件供应商误将 upx 压缩的二进制文件标记为病毒，请查看[相关问题](https://github.com/upx/upx/issues/437)。

**Comment by DuangXT** [comment]
> 

了解了，谢谢
