### ISSUE TITLE
配置环境变量后启动 alist，start 提示错误

### ISSUE THREAD

**Issue by xzxiaoshan** [alist-org/alist#3012]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

Windows 配置环境变量 `Path` 后，在cmd命令行启动服务，`server` 、`version` 参数均正常，`start` 出现错误，如下截图所示：

```
C:\Users\Administrator>alist start
FATA[2023-01-12 08:53:14] failed to start children process: exec: ".\\alist": file does not exist
```

### Reproduction / 复现链接

https://user-images.githubusercontent.com/16459864/211950258-c59f0593-5d22-443b-9162-fbc9480829d0.png

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/212057292-6bd5b966-2c26-44a4-a49d-44f909bf69b3.png)
无法复现此问题。

**Comment by xzxiaoshan** [comment]
使用 PowerShell 不报错，使用 cmd 报错，另外

![image](https://user-images.githubusercontent.com/16459864/212540714-5aa90edb-3e3f-48fe-9c55-0e0f7801dd86.png)

![image](https://user-images.githubusercontent.com/16459864/212540747-c790aade-306d-49ed-9429-c35b52c36b50.png)

cmd 使用 `alist start` 报错，但是使用 `alist server` 输出正常，初步判断是因为 cmd fork 子进程的时候默认目录读取的是当前窗口默认目录 `C:\Users\Administrator>`，这个是否应该做个处理？应该读取 alist 所在目录。

![image](https://user-images.githubusercontent.com/16459864/212541077-db5512c0-28fd-4120-aa0e-8082883ee799.png)

**Comment by Xhofe** [comment]
cmd：
![image](https://user-images.githubusercontent.com/36558727/212543394-b4704be5-898f-495a-9ed6-eba86f66dd87.png)

**Comment by xzxiaoshan** [comment]
我明天用同事电脑试一下，我AList 放在 `D:\Program Files\AList` 中的。
看你的没问题，我就很纳闷了。我的那个错误提示，看起来是指 fork 进程找不到 alist，明天换个电脑试试。

**Comment by xzxiaoshan** [comment]
作者你好，这块可能确实需要检查一下代码，我用了公司同事的电脑，是一个没有相关配置的相对比较干净的电脑。

按照如下图所示配置环境变量，完成后运行 cmd，alist start 启动服务，错误确实是存在的。

看错误的提示，应该就是把 cmd 当前窗口的路径当做 fork 子进程的目录路径了，实际上应该以 alist.exe 应用程序本身的所在目录为基准。

![image](https://user-images.githubusercontent.com/16459864/212582484-1f036c70-674b-4c40-adb7-3ceb6c7784f0.png)

![image](https://user-images.githubusercontent.com/16459864/212582731-6949ac72-782c-4f80-8bba-6db067760947.png)

**Comment by xzxiaoshan** [comment]
你 Win+R 快捷键，运行 `cmd`，这样打开窗口

**Comment by xzxiaoshan** [comment]
如有需要的话，可以通过 微信、钉钉、QQ、Tg 等方式协助测试。
