### ISSUE TITLE
增量更新的索引，在管理中心的索引界面，不会增加数量、时间也不会变

### ISSUE THREAD

**Issue by xzxiaoshan** [alist-org/alist#3019]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增量更新的索引，在管理中心的索引界面，不会增加数量、时间也不会变。
不知道是bug，还是存在这个问题。
建议索引管理页看到的数量是从数据库获取的实时数据，对应的更新时间也应该是只要触发了索引更新就对应改变。

**Comment by xzxiaoshan** [comment]
该字段的数值 和 对应的最后更新时间，应从数据库中读取，保持一致。

![image](https://user-images.githubusercontent.com/16459864/212011328-dd7a4396-0e0f-4890-84ea-a700c31e77c0.png)

**Comment by KNaiFen** [comment]
原来是这样吗？我看他数字没变我一直以为自动更新是坏的，不会更新，搞得我每次都去重新构建
