### ISSUE TITLE
全局隐藏后还会计入分页统计中

### ISSUE THREAD

**Issue by Tasle** [alist-org/alist#3020]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

Google

### Describe the bug / 问题描述

全局中隐藏文件后，前端展示还会把隐藏的文件计入分页统计中，导致前面几页都是空白的

### Reproduction / 复现链接

![](https://img.urlnode.com/file/7e9280206b41455ee3594.png)

**Comment by Xhofe** [comment]
全局中的隐藏对API无效，仅在前端展示时不显示，要对分页生效 请在meta中添加隐藏
