### ISSUE TITLE
webdav 驱动不应该是通用的吗?为什么只支持OneDrive/SharePoint?

### ISSUE THREAD

**Issue by zhugunzi** [alist-org/alist#3021]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

webdav 难道不是一种国际标准吗?配置地址 端口 用户名 密码应该就足够了啊!为什么只支持OneDrive/SharePoint,
windows搭建的webdav 为什么连接不上呢!!!!

**Comment by Xhofe** [comment]
我不知道你在哪里看的只支持OneDrive/SharePoint。

**Comment by zhugunzi** [comment]
> 我不知道你在哪里看的只支持OneDrive/SharePoint。

我用win 10搭建的webdav服务 用alist 连接不上啊
