### ISSUE TITLE
OneDrive 无法重命名文件夹

### ISSUE THREAD

**Issue by 12189108** [alist-org/alist#3028]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

日志如下
 ``` 
[ERRO][2023-01-12 22:37:02] failed rename /OneDrive_5G/图片 to Pic: Either id or path in parentReference must be specified
github.com/alist-org/alist/v3/internal/op.Rename
	/source/internal/op/fs.go:378
github.com/alist-org/alist/v3/internal/fs.rename
	/source/internal/fs/other.go:40
github.com/alist-org/alist/v3/internal/fs.Rename
	/source/internal/fs/fs.go:68
github.com/alist-org/alist/v3/server/handles.FsRename
	/source/server/handles/fsmanage.go:159
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:55
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1991
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594 
[GIN] 2023/01/12 - 22:37:02 | 200 |  217.810719ms |    20.78.82.234 | POST     "/api/fs/rename"
 ```

### Reproduction / 复现链接

*

**Comment by Xhofe** [comment]
未能复现此问题 
![image](https://user-images.githubusercontent.com/36558727/212219831-2bd9f6e6-34e6-423b-a44b-36356eedc0d0.png)
![image](https://user-images.githubusercontent.com/36558727/212219857-c4fec0a4-ee4d-4504-aeff-09fae0448c90.png)

**Comment by 12189108** [comment]
网站地址:yundisk.cf
用户名:test
密码:test
如果还有其他信息需要提供，请说明

**Comment by 12189108** [comment]
> 未能复现此问题 ![image](https://user-images.githubusercontent.com/36558727/212219831-2bd9f6e6-34e6-423b-a44b-36356eedc0d0.png) ![image](https://user-images.githubusercontent.com/36558727/212219857-c4fec0a4-ee4d-4504-aeff-09fae0448c90.png)

网站地址:yundisk.cf
用户名:test
密码:test
如果还有其他信息需要提供，请说明

**Comment by 12189108** [comment]
> 未能复现此问题 ![image](https://user-images.githubusercontent.com/36558727/212219831-2bd9f6e6-34e6-423b-a44b-36356eedc0d0.png) ![image](https://user-images.githubusercontent.com/36558727/212219857-c4fec0a4-ee4d-4504-aeff-09fae0448c90.png)

如暂时不能解决问题，我将删除测试账号
