### ISSUE TITLE
建议Alist下方的视频播放器可以链接到网盘正确的地址，而不是Alist网页本身的地址

### ISSUE THREAD

**Issue by STEVENTAN100** [alist-org/alist#3030]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Alist挂载在VPS上，如果视频播放器链接指向的是Alist网页的地址，就会出现下图的问题：
![2](https://user-images.githubusercontent.com/93769514/212226586-7677333e-0008-4ac2-9ec0-73baa5bf563f.png)

如果用PotPlayer添加下图的网址时，就可以正常播放：
![1](https://user-images.githubusercontent.com/93769514/212226748-127687f8-e08f-45d7-9642-8b0065bf5b5b.png)

提这个issue同时也是想问为什么网页上播放视频会导致黑屏（有声音，但本地可以正常播放），会不会是ArtPlayer不支持某种MP4视频的h264编码？

### Suggested solution / 实现思路

把potplayer的a元素href到视频正确的地址

**Comment by Xhofe** [comment]
请更新PotPlayer。
