### ISSUE TITLE
openwrt环境安装的alist，新上传文件不能正常显示

### ISSUE THREAD

**Issue by jickylong** [alist-org/alist#3032]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

openwrt环境安装的alist，存储为阿里云盘，通过alist新上传文件正常，通过阿里云盘客户端亦可正常查看到，但alist页面不能正常显示。重启alist服务后可正常显示新上传的文件

### Reproduction / 复现链接

http://lsp.banlangen.top

**Comment by STEVENTAN100** [comment]
alist右下角三个点展开，刷新一下
