### ISSUE TITLE
利用RaiDrive 将Alist 映射到电脑上，百度网盘可以下载文件，但是不能上传文件

### ISSUE THREAD

**Issue by lijoe123** [alist-org/alist#3033]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.8.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

利用RaiDrive 将Alist 放到我的电脑上之后，可以从百度网盘下载文件，但是无法上传文件
![image](https://user-images.githubusercontent.com/86214036/212249387-a09fe86b-f603-4deb-b2a0-936fdbaaac7d.png)

### Reproduction / 复现链接

no

### Logs / 日志

![image](https://user-images.githubusercontent.com/86214036/212249408-ea473e10-d4a7-4f7f-af8f-ceee68ab293b.png)

**Comment by anwen-anyi** [comment]
https://alist.nn.ci/zh/faq/why.html#raidrive挂载百度网盘-可以下载文件-不能上传文件。往挂载目录丢文件提示-提示-你需要权限来执行此操作-。这个怎么解决

**Comment by OXERIS** [comment]
> [https://alist.nn.ci/zh/faq/why.html#raidrive挂载百度网盘-可以下载文件-不能上传文件。往挂载目录丢文件提示-提示-你需要权限来执行此操作-。这个怎么解决](https://alist.nn.ci/zh/faq/why.html#raidrive%E6%8C%82%E8%BD%BD%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98-%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6-%E4%B8%8D%E8%83%BD%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E3%80%82%E5%BE%80%E6%8C%82%E8%BD%BD%E7%9B%AE%E5%BD%95%E4%B8%A2%E6%96%87%E4%BB%B6%E6%8F%90%E7%A4%BA-%E6%8F%90%E7%A4%BA-%E4%BD%A0%E9%9C%80%E8%A6%81%E6%9D%83%E9%99%90%E6%9D%A5%E6%89%A7%E8%A1%8C%E6%AD%A4%E6%93%8D%E4%BD%9C-%E3%80%82%E8%BF%99%E4%B8%AA%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3)

按照文章的说法我只能用回V2版本的alist吗？还是说V3可以配置忽略空文件？

**Comment by anwen-anyi** [comment]
> > [https://alist.nn.ci/zh/faq/why.html#raidrive挂载百度网盘-可以下载文件-不能上传文件。往挂载目录丢文件提示-提示-你需要权限来执行此操作-。这个怎么解决](https://alist.nn.ci/zh/faq/why.html#raidrive%E6%8C%82%E8%BD%BD%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98-%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6-%E4%B8%8D%E8%83%BD%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E3%80%82%E5%BE%80%E6%8C%82%E8%BD%BD%E7%9B%AE%E5%BD%95%E4%B8%A2%E6%96%87%E4%BB%B6%E6%8F%90%E7%A4%BA-%E6%8F%90%E7%A4%BA-%E4%BD%A0%E9%9C%80%E8%A6%81%E6%9D%83%E9%99%90%E6%9D%A5%E6%89%A7%E8%A1%8C%E6%AD%A4%E6%93%8D%E4%BD%9C-%E3%80%82%E8%BF%99%E4%B8%AA%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3)
> 
> 按照文章的说法我只能用回V2版本的alist吗？还是说V3可以配置忽略空文件？

理论上是这样的，反正目前不能配置忽略空文件.

**Comment by Holiday2019** [comment]
我配置v2.6.4的alist，在raidrive配置相应参数时，显示401错误，请问该如何解决呢？
