### ISSUE TITLE
ADGUARD对Alist出现误拦截

### ISSUE THREAD

**Issue by ShiroSekai** [alist-org/alist#3034]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

123云盘

## 浏览环境
浏览器：Firefox （Mozilla国际版）
浏览器版本: 108.0.2 (64 位) 

AdGuard 浏览器扩展版本： 4.1.53
拦截规则：过滤器AdBlockID

## 具体问题
~~在FF国际版上点击文件无法正常显示复制链接和下载按钮，在Chrome访问则无此问题，使用此FF版本访问Alist v2版本无此问题。~~

ADGUARD出现了能够拦截Alist下载界面的规则，或许讨论下如何解决这个问题？因为好多拦截器都有使用ADGUARD的规则，这将影响所有正在使用拦截器的用户访问Alist。

### Reproduction / 复现链接

[复现地址](https://share.moeblog.vip/%E8%BD%AF%E4%BB%B6%E9%9B%86/Antivirus_Removal_Tool_2022_12%23%E5%8D%B8%E8%BD%BD%E5%AE%89%E5%85%A8%E8%BD%AF%E4%BB%B6%E5%B7%A5%E5%85%B7.zip)

### Logs / 日志

![出现问题的图片](https://user-images.githubusercontent.com/52284665/212257394-08bec0ee-ef08-4e07-ad22-540940badc33.png)

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/212267905-5b800594-0588-4721-899c-4fc3c1297a94.png)

**Comment by ShiroSekai** [comment]
Sorry，我重新测试了一下，是ADGUARD给屏蔽了，但我觉得这里不是广告而被屏蔽感到奇怪。
下面是拦截规则。我会在稍后关闭issue。
![拦截规则](https://user-images.githubusercontent.com/52284665/212268946-0666554c-9640-4e7d-867e-bbbda9b90da3.png)
