### ISSUE TITLE
UC浏览器打开视频详情，V2的下载按钮没有了，并且点击video切换download按钮没反应

### ISSUE THREAD

**Issue by 454592673** [alist-org/alist#3037]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

阿里云盘/移动云盘个人

### Describe the bug / 问题描述

用UC浏览器打开视频详情，V2的下载按钮没有了，而且点击video下拉切换download，没反应
![7b3517e995e7e2172c43c1ea818e1de](https://user-images.githubusercontent.com/22283930/212285933-c5ef9cec-7f42-4aa1-acd8-65641bdc9c55.jpg)

### Reproduction / 复现链接

用UC浏览器随意打开一个视频都能复现

### Logs / 日志

这个应该和日志没关系，只是页面样式兼容的问题

**Comment by Xhofe** [comment]
UC浏览器接管了视频播放并强制将播放窗口指定导致页面选择器被遮挡，这是UC的问题，请向UC反馈而不是这里。
