### ISSUE TITLE
元信息隐藏 直接在当前行回车进行换行 会将整个根目录隐藏

### ISSUE THREAD

**Issue by anwen-anyi** [alist-org/alist#3039]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.8.0 和 Commit ID: 2dc5dec

### Driver used / 使用的存储驱动

All

### Describe the bug / 问题描述

元信息隐藏 直接在当前行回车进行换行 会将整个根目录隐藏（也就是说回车换行的空白变成了 * 的意思差不多）

### Reproduction / 复现链接

 - 元信息
   - 路径选择：root
   - 密码 写入 不需要管
   - 隐藏 直接摁回车进行换行
   - 保存 用无痕模式打开首页  会发现被加密
   - ![Log](https://down.onmicrosoft.cn/qiniu/u20221021b3a89013_1673617048663_10319549_image.png)

### Logs / 日志

No

**Comment by Xhofe** [comment]
空白本来就会匹配任何字符串，我不认为这是什么bug
