### ISSUE TITLE
增加功能：根据http头X-Real-IP对本地直链请求不做sign验证

### ISSUE THREAD

**Issue by qbisi** [alist-org/alist#3045]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我使用alist项目有两个功能：
1. 用nginx反代alist做共享网盘
2. 服务器本地用alist的直链api替换到emby的媒体请求

对于1，为了保证文件贡献不被滥用需要加sign，对于2, 要使用直链api必须不加sign，

目前临时解决方案是在服务本地另外开启一个alist进程，对所有直链请求不做sign验证；
用于nginx反代的alist进程做sign验证，但是这样使用分开的database不利于系统维护，也不优雅。

### Suggested solution / 实现思路

增加一个选项，根据http头X-Real-IP对本地直链请求不做sign验证

**Comment by qbisi** [comment]
似乎可以通过 Host/api/fs/link 或者token计算sign实现，作者认为如有必有可关闭此issue。

**Comment by zanderzhng** [comment]
@qbisi 请问怎么实现的不验证sign允许直链的。
