### ISSUE TITLE
在readme.md中不能在新窗口打开链接

### ISSUE THREAD

**Issue by zxxhz** [alist-org/alist#3048]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

通过md语法，或者直接用 加target="_blank"属性，都没法让链接在新窗口中打开。在查看网页源代码后发现_blank被替换成了_self

### Reproduction / 复现链接

https://emoing.cc/Docker/README.md

**Comment by Xhofe** [comment]
This may depend on our dependencies: [solid-markdown](https://github.com/andi23rosca/solid-markdown)
