### ISSUE TITLE
支持添加另一个alist站点作为源

### ISSUE THREAD

**Issue by yhcharles** [alist-org/alist#3054]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

支持把其他alist站点作为存储源（等同于OneDrive, GoogleDrive）添加到存储列表中

**Comment by snailwind** [comment]
原本就支持啊
