### ISSUE TITLE
能不能增加一个云函数serverless部署方式

### ISSUE THREAD

**Issue by sikros** [alist-org/alist#3070]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

服务器快到期了，不想买服务器了，有没有办法把alist部署到云函数或heroku上

**Comment by Xhofe** [comment]
https://alist.nn.ci/guide/install/paas.html#koyeb
