### ISSUE TITLE
在windows服务控制管理器中注册成服务无法启动 

### ISSUE THREAD

**Issue by dragonandy** [alist-org/alist#3071]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在Windows的Service Control Manager中注册alist作为系统服务后，无法使用服务管理启动alist守护进程服
```cmd
D:\alist>sc create alist start=auto binPath="D:\alist\alist.exe"
[SC] CreateService 成功
D:\alist>sc start alist
[SC] StartService 失败 1053:
```

**Comment by xzxiaoshan** [comment]
同问，遇到相同的问题。能提供一个直接安装和卸载服务的脚本就更好了。

**Comment by Xhofe** [comment]
我不了解Windows 但是启动alist服务是`./alist server`，你这肯定不对。请理解issue仅作为bug report与feature request。
