### ISSUE TITLE
谁能开发一个阿里云分享页面一键添加到AList的chrome插件

### ISSUE THREAD

**Issue by xzxiaoshan** [alist-org/alist#3083]
谁能开发一个阿里云分享页面一键添加到AList的chrome插件，只要打开的是阿里云分享页面。就自动出现一个添加到AList的按钮，点击后选择挂载路径保存即可。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by loveveryday** [comment]
GreasyFork脚本[一键添加阿里云共享到AList](https://gist.github.com/loveveryday/0967dabf20709de81d0cfd6cdcb8a0e1)

> 谁能开发一个阿里云分享页面一键添加到AList的chrome插件，只要打开的是阿里云分享页面。就自动出现一个添加到AList的按钮，点击后选择挂载路径保存即可。
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

GreasyFork脚本[一键添加阿里云共享到AList](https://gist.github.com/loveveryday/0967dabf20709de81d0cfd6cdcb8a0e1)

**Comment by loveveryday** [comment]
> 谁能开发一个阿里云分享页面一键添加到AList的chrome插件，只要打开的是阿里云分享页面。就自动出现一个添加到AList的按钮，点击后选择挂载路径保存即可。
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

GreasyFork脚本[一键添加阿里云共享到AList](https://gist.github.com/loveveryday/0967dabf20709de81d0cfd6cdcb8a0e1)

**Comment by loveveryday** [comment]
[Greasy脚本](https://greasyfork.org/en/scripts/460279-%E4%B8%80%E9%94%AE%E6%B7%BB%E5%8A%A0%E9%98%BF%E9%87%8C%E4%BA%91%E5%85%B1%E4%BA%AB%E5%88%B0alist)
