### ISSUE TITLE
请求添加qBittorrent远程下载支持

### ISSUE THREAD

**Issue by Qs315490** [alist-org/alist#3087]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我目前使用过的类似程序都只有aria2支持，aria2在下载 bt 或磁链存在兼容问题。
比如，下载的文件每个文件都多出一个对应叫 `如果你看到这个文件请升级bt客户端` 的文件。
而使用qBittorrent或其他bt客户端没有这个问题。

### Suggested solution / 实现思路

官方API写的比较详细，且市面上有相关其他编程语言实现
 qBittorrent的远程下载是基于http的api调用
qBittorrent添加下载流程如下
通过API登录 -> 通过POST /api/v2/torrents/add携带的数据添加链接
通过/api/v2/torrents/获取所有连接，与aria2的json-rpc和xml-rpc不同。

### Additional context / 附件

[qBittorrent Web-API官方文档](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1))

**Comment by mengguyi** [comment]
赞同，aria2好像不支持utp，导致一些做种少的种子下不来/不完整
