### ISSUE TITLE
Docker detection then keep aria2 download path in default

### ISSUE THREAD

**Issue by jyxjjj** [alist-org/alist#3089]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

Tag:v3.8.0 Podman:6ddc826003ac9d63e9b7e5b813218390f721f957de2c72731ef01deb86930d97 Docker:7ef0ec22bc4f1022f92129035ddf67d64a053ed8c047a98fe6e7ee30a386dd4f

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

aria2 download path will be set to `/opt/alist/data/temp/aria2/`,
Or something like `/media` which is not exists in physical machine.

To detect if running with docker/podman, if so, do not pass the param about any path.

### Reproduction / 复现链接

N/A

**Comment by Xhofe** [comment]
We have to specify a specific path so that we can visit it.
