### ISSUE TITLE
谁能开发一个阿里云分享页面一键添加到AList的chrome插件

### ISSUE THREAD

**Issue by xzxiaoshan** [alist-org/alist#3091]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Chrome 插件安装后，打开分享的阿里云链接，就会自行显示“添加到AList” 按钮，点击后，自动添加到 AList 挂载管理中。

如果能结合 #3090 实现了驱动默认 Token，则就可以自动使用默认Token。

**Comment by loveveryday** [comment]
GreasyFork脚本[一键添加阿里云共享到AList](https://gist.github.com/loveveryday/0967dabf20709de81d0cfd6cdcb8a0e1)

**Comment by loveveryday** [comment]
[Greasy脚本](https://greasyfork.org/en/scripts/460279-%E4%B8%80%E9%94%AE%E6%B7%BB%E5%8A%A0%E9%98%BF%E9%87%8C%E4%BA%91%E5%85%B1%E4%BA%AB%E5%88%B0alist)
