### ISSUE TITLE
默认密码无法登录

### ISSUE THREAD

**Issue by aizigun** [alist-org/alist#3094]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.0

### Driver used / 使用的存储驱动

..

### Describe the bug / 问题描述

无法登录

### Reproduction / 复现链接

http://127.0.0.1:5244/@login

### Logs / 日志

![Snipaste_2023-01-18_15-16-25](https://user-images.githubusercontent.com/23473720/213107906-371a4682-0f06-407c-83cf-d18aa0f1a186.png)
![Snipaste_2023-01-18_15-17-07](https://user-images.githubusercontent.com/23473720/213107905-86114ea0-006a-41a8-a862-4bc191608dd6.png)

**Comment by Xhofe** [comment]
你的错误次数过多 请稍后再试。

**Comment by zjy2931** [comment]
同样默认密码无法登录

**Comment by hua345** [comment]
> 同样默认密码无法登录

+1

**Comment by hua345** [comment]
> 



> 你的错误次数过多 请稍后再试。 重启可重置

删除data目录和重启服务，
 alist.exe admin返回的admin 密码还是错误
