### ISSUE TITLE
alist部署后怎么使用本地文件自定义网站logo

### ISSUE THREAD

**Issue by 3177854** [alist-org/alist#3100]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist部署后怎么使用本地文件自定义网站logo？或者后台要怎么引用本地路径？

**Comment by Xhofe** [comment]
不支持直接引用。你可以创建本地存储然后复制链接
