### ISSUE TITLE
data目录里多出两个文件

### ISSUE THREAD

**Issue by nxjonson** [alist-org/alist#3104]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.9.0

### Driver used / 使用的存储驱动

全部

### Describe the bug / 问题描述

3.8.0之前版本data目录下有config.json和data.db两个文件，升级到最新3.9.0版本之后，发现data目录多出两个文件分别是：data.db-shm、data.db-wal其中data.db-wal会随着每一次启动alist，体积不断变大…

### Reproduction / 复现链接

http://127.0.0.1:5244

**Comment by Xhofe** [comment]
https://stackoverflow.com/questions/7778723/what-are-the-db-shm-and-db-wal-extensions-in-sqlite-databases

**Comment by KinShin** [comment]
> https://stackoverflow.com/questions/7778723/what-are-the-db-shm-and-db-wal-extensions-in-sqlite-databases

> The only safe way to remove a WAL file is to open the database file using one of the [sqlite3_open()](https://www.sqlite.org/c3ref/open.html) interfaces then immediately close the database using [sqlite3_close()](https://www.sqlite.org/c3ref/close.html).

@xhofe 大佬，data.db-shm、data.db-wal 两个文件的残留应该是在退出 AList 时没有关闭数据库造成的。每次打开数据库的时候会出现这两个文件，写入更改时会将新内容保存在这两个文件里，在关闭数据库的时候才会将 data.db-wal 的内容提交到 data.db 中，并自动删除这两个文件。
