### ISSUE TITLE
尊敬的alist作者，想请教您是否可以开启https。

### ISSUE THREAD

**Issue by itaustin** [alist-org/alist#3110]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

尊敬的alist作者，想请教您是否可以开启https。

**Comment by Xhofe** [comment]
Follow our issue guidelines, please.

**Comment by snailwind** [comment]
可以开，配置文件中，建议通过反向代理开。
