### ISSUE TITLE
OneDrive m3u8 播放问题

### ISSUE THREAD

**Issue by srcenchen** [alist-org/alist#3111]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.1

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

近日，注意到开发者大大修复了m3u8在ios的播放问题，我也是迫不及待地更新了新的版本，但是在 OneDrive iOS 上直接播放视频，直接提示无法播放，是一个播放图标被砍了一刀那样，我debug了一下，发现好像是重定向到Onedrive 服务时候被拦截了。
我便打开了 Alist的 Web 代理， iOS问题解决了，但是新的问题又来了，在windows mac android 上又无法播放了，通过日志可以看到这个
![image](https://user-images.githubusercontent.com/48435089/213637312-d9bd35a6-456a-4fe3-8763-b287a9d413d4.png)
我认为和这个有关，应该是http与https的服务交接没做好

### Reproduction / 复现链接

https://sancloud.luckysan.top/OneDriveE5/%E6%B4%8B%E8%91%B1%E5%AD%A6%E9%99%A2/HLS/%E9%AB%98%E4%B8%AD/%E6%95%B0%E5%AD%A6/%E5%BF%85%E4%BF%AE%E4%BA%8C/9.%E5%B9%B3%E9%9D%A2%E5%90%91%E9%87%8F/9.1%E5%90%91%E9%87%8F%E6%A6%82%E5%BF%B5/9.1.1%E5%90%91%E9%87%8F%E6%A6%82%E5%BF%B5/1.%E6%A6%82%E5%BF%B5%E8%AF%BE/1.%E4%BB%80%E4%B9%88%E6%98%AF%E5%90%91%E9%87%8F.m3u8

### Logs / 日志

![image](https://user-images.githubusercontent.com/48435089/213637387-e42682c0-3e94-4d5f-86c7-dbf49b598294.png)

**Comment by srcenchen** [comment]
![image](https://user-images.githubusercontent.com/48435089/213638816-5dd3b701-b889-4849-bd7b-9d513460e9c5.png)

**Comment by srcenchen** [comment]
没有重复吧 我翻了issue 没找到相关解决方案呀

**Comment by Xhofe** [comment]
> 没有重复吧 我翻了issue 没找到相关解决方案呀

#1797 #2235

**Comment by srcenchen** [comment]
感谢开发大大

**Comment by LuckyTain** [comment]
v3.35.0
m3u8在线播放播放，在启用签名后无法在线播放，因为在线播放请求ts文件时不会带sign参数
{"code":401,"message":"expire missing","data":null}
关闭签名后则正常播放，希望有空可以开发一下这个功能

**Comment by ulifuqiang** [comment]
> v3.35.0 m3u8在线播放播放，在启用签名后无法在线播放，因为在线播放请求ts文件时不会带sign参数 {"code":401,"message":"expire missing","data":null} 关闭签名后则正常播放，希望有空可以开发一下这个功能

复议
