### ISSUE TITLE
能否实现仿raid

### ISSUE THREAD

**Issue by Kenny0521666** [alist-org/alist#3113]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

找了几个123云盘，能否实现将几个123云盘账号像raid那样直接合并成一个大的并通过raidrive挂载呢
（毕竟2T很爽)

**Comment by anwen-anyi** [comment]
123盘算啦，123的脆弱的很 你速度快了 或者一加载大文件API直接爆表GG........

**Comment by Kenny0521666** [comment]
> 123盘算啦，123的脆弱的很 你速度快了 或者一加载大文件API直接爆表GG........

没事我就号多想弄个大的raid
