### ISSUE TITLE
删除存储的同时删除存储的索引

### ISSUE THREAD

**Issue by likecreep** [alist-org/alist#3116]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

删除存储的同时删除存储的索引。 否则之后搜索到时候会搜索出大量无效的索引。

### Suggested solution / 实现思路

删除数据库里已该存储路径开头的索引

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/guide/advanced/search.html#%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E7%B4%A2%E5%BC%95
