### ISSUE TITLE
请适配下载的后缀(可选)

### ISSUE THREAD

**Issue by Faryi** [alist-org/alist#3123]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在有些网盘会提供图片云裁剪的功能,或者其他在线功能.
例如:onedrive,you提供图片云裁剪的功能.
https://127.0.01/1.jpg?width=117&height=176&cropmode=none
在实际跳转loction的url 后面增加?width=117&height=176&cropmode=none

### Suggested solution / 实现思路

作者可以开启一个按钮,高级功能,开启可以适配?后面的后缀,自动添加到实际loction的url后面即可.

**Comment by Winyer** [comment]
实测OneDrive加了参数也不会裁剪图片，一开始我以为是Alist的问题，已经开启了转发直链，然后又去找了onmicrosoft的链接加上?width=117&height=176&cropmode=none这个参数，但是图片还是没被裁剪，综上，得出结论，OneDrive无云裁剪功能或参数出错
