### ISSUE TITLE
txt文件预览自动换行

### ISSUE THREAD

**Issue by Seele0oO** [alist-org/alist#3125]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

txt文件在预览时无法开启自动换行，在预览文件的需求情况下不是很方便。

### Suggested solution / 实现思路

增加一个支持换行功能的查看器。

**Comment by Huelse** [comment]
Seems to add an option and put the content in the <p> tag will work.
