### ISSUE TITLE
苹果手机播放视频显示加载失败，安卓和电脑我尝试都没问题。

### ISSUE THREAD

**Issue by HankMo** [alist-org/alist#3131]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

网盘是阿里云盘，浏览视频，苹果手机播放视频显示加载失败，安卓和电脑我尝试都没问题。

### Reproduction / 复现链接

由于网盘私用涉及隐私暂无法提供公开链接

**Comment by evlic** [comment]
是的这个问题我同样遇到了，我查看了页面播放组件 ArtPlayer  4.5.4 相关的说明，iOS 应该是支持的，不过可能需要特别的设置（safari 解码器好像不太通用），但是该组件是支持 iOS 浏览器播放视频的。

正好手头有设备，后续我可以跟进一下问题（不过 ios 比较难 debug
