### ISSUE TITLE
希望能像RClone一样 支持google的 service account(sa) 

### ISSUE THREAD

**Issue by tanpengsccd** [alist-org/alist#3132]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能像RClone一样 支持google的 service account(sa) ,获取的刷新token容易失效

### Suggested solution / 实现思路

希望能像RClone一样 支持google的 service account(sa)

**Comment by orangejx** [comment]
已经支持 SA 啦, 只需要将 SA 文件所在位置或者所在文件夹的路径填入 `Refresh Token` 字段即可使用, 原本填入的 `Refresh Token` 也可以继续使用.

**Comment by tanpengsccd** [comment]
nice，感谢。另外问问 是不是随机选择 sa？ 比如有100个sa 是不是随机选择使用？

**Comment by orangejx** [comment]
> nice，感谢。另外问问 是不是随机选择 sa？ 比如有100个sa 是不是随机选择使用？

原则上来说是**顺序读取**的, 
例如所填文件夹内有 `000.json, 001.json, 002.json ... 099.json` . 第一次会读取 `000.json`, 第二次会读取 `001.json`, 以此类推. 

此外, 由于通过 SA 获取的 `Access Token` 有效期最大为 1 小时, 所以每隔 1 个小时都会切换到新的 SA. 当所有的 SA 使用完毕之后, 则重新使用第一个 SA.
