### ISSUE TITLE
Failed to restart alist.service: Unit is not loaded properly: Invalid argument. See system logs and 'systemctl status alist.service' for details.

### ISSUE THREAD

**Issue by ailachan** [alist-org/alist#3135]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

Jan 23 11:22:34 aila systemd[1]: [/etc/systemd/system/alist.service:8] Not an absolute path, ...list
Jan 23 11:22:34 aila systemd[1]: [/etc/systemd/system/alist.service:9] Executable path is not...rver
Jan 23 11:22:34 aila systemd[1]: alist.service lacks both ExecStart= and ExecStop= setting. R...ing.
Jan 23 11:22:34 aila systemd[1]: [/etc/systemd/system/alist.service:8] Not an absolute path, ...list
Jan 23 11:22:34 aila systemd[1]: [/etc/systemd/system/alist.service:9] Executable path is not...rver
Jan 23 11:22:34 aila systemd[1]: alist.service lacks both ExecStart= and ExecStop= setting. R...ing.
Hint: Some lines were ellipsized, use -l to show in full.

这是alist.service服务状态
请问一下这个怎么解决啊

### Reproduction / 复现链接

j

**Comment by anwen-anyi** [comment]
**`alist.service`** 这个里面写的啥你去看看呗

**Comment by ailachan** [comment]
> **`alist.service`** 这个里面写的啥你去看看呗

Jan 23 11:22:34 aila systemd[1]: [/etc/systemd/system/alist.service:8] Not an absolute path, ...list
Jan 23 11:22:34 aila systemd[1]: [/etc/systemd/system/alist.service:9] Executable path is not...rver
Jan 23 11:22:34 aila systemd[1]: alist.service lacks both ExecStart= and ExecStop= setting. R...ing.
Jan 23 11:22:34 aila systemd[1]: [/etc/systemd/system/alist.service:8] Not an absolute path, ...list
Jan 23 11:22:34 aila systemd[1]: [/etc/systemd/system/alist.service:9] Executable path is not...rver
Jan 23 11:22:34 aila systemd[1]: alist.service lacks both ExecStart= and ExecStop= setting. R...ing.
Hint: Some lines were ellipsized, use -l to show in full.

看不明白

**Comment by ailachan** [comment]
> **`alist.service`** 这个里面写的啥你去看看呗

难道是路径问题？我也看不太明白

**Comment by anwen-anyi** [comment]
> > **`alist.service`** 这个里面写的啥你去看看呗
> 
> 难道是路径问题？我也看不太明白

```bash
WorkingDirectory=path_alist
ExecStart=path_alist/alist server
```

很明显你写的路径不对吧.....

**Comment by ailachan** [comment]
> > > **`alist.service`** 这个里面写的啥你去看看呗
> > 
> > 
> > 难道是路径问题？我也看不太明白
> 
> ```shell
> WorkingDirectory=path_alist
> ExecStart=path_alist/alist server
> ```
> 
> 很明显你写的路径不对吧.....（应该是这样）

！！！！好了,谢谢大佬

**Comment by anwen-anyi** [comment]
> > > > **`alist.service`** 这个里面写的啥你去看看呗
> > > 
> > > 
> > > 难道是路径问题？我也看不太明白
> > 
> > 
> > ```shell
> > WorkingDirectory=path_alist
> > ExecStart=path_alist/alist server
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 很明显你写的路径不对吧.....（应该是这样）
> 
> ！！！！好了,谢谢大佬

手动关闭issue吧
