### ISSUE TITLE
添加腾讯云COS，访问二级目录出现占位文件

### ISSUE THREAD

**Issue by skyle1995** [alist-org/alist#3137]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.9.1

### Driver used / 使用的存储驱动

对象储存

### Describe the bug / 问题描述

运行环境Docker，添加腾讯云COS，访问二级路径（COS）会出现同目录名占位文件（无效文件）

![123](https://user-images.githubusercontent.com/39904228/214237770-c80a36b8-eaba-4bba-86af-016772986116.png)

### Reproduction / 复现链接

http://skyle.wicp.vip:8205/%E5%AF%B9%E8%B1%A1%E5%82%A8%E5%AD%98/TX-COS

### Logs / 日志

{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:53] Shutdown Server ...                          \n","stream":"stderr","time":"2023-01-24T07:51:53.944078627Z"}
{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:55] timeout of 1 seconds.                        \n","stream":"stderr","time":"2023-01-24T07:51:55.024631353Z"}
{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:55] Server exiting                               \n","stream":"stderr","time":"2023-01-24T07:51:55.024655684Z"}
{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:58] reading config file: data/config.json        \n","stream":"stderr","time":"2023-01-24T07:51:58.639067105Z"}
{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:58] load config from env with prefix:            \n","stream":"stderr","time":"2023-01-24T07:51:58.639087921Z"}
{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:58] init logrus...                               \n","stream":"stderr","time":"2023-01-24T07:51:58.639091144Z"}
{"log":"\u001b[33mWARN\u001b[0m[2023-01-24 07:51:58] not enable search                            \n","stream":"stdout","time":"2023-01-24T07:51:58.65618739Z"}
{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:58] start server @ 0.0.0.0:5244                  \n","stream":"stderr","time":"2023-01-24T07:51:58.656209174Z"}
{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:58] success load storage: [/网盘主题], driver: [Local] \n","stream":"stderr","time":"2023-01-24T07:51:58.663432926Z"}
{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:58] Aria2 not ready.                             \n","stream":"stderr","time":"2023-01-24T07:51:58.674415323Z"}
{"log":"\u001b[36mINFO\u001b[0m[2023-01-24 07:51:59] success load storage: [/对象储存/TX-COS], driver: [S3] \n","stream":"stderr","time":"2023-01-24T07:51:59.975254339Z"}
{"log":"[GIN] 2023/01/24 - 07:52:25 | 200 |   29.084186ms |     192.168.0.1 | POST     \"/api/fs/list\"\n","stream":"stdout","time":"2023-01-24T07:52:25.464594824Z"}
{"log":"[GIN] 2023/01/24 - 07:52:26 | 200 |  258.874765ms |     192.168.0.1 | POST     \"/api/fs/list\"\n","stream":"stdout","time":"2023-01-24T07:52:26.752899676Z"}
{"log":"[GIN] 2023/01/24 - 07:52:28 | 200 |   53.955081ms |     192.168.0.1 | POST     \"/api/fs/list\"\n","stream":"stdout","time":"2023-01-24T07:52:28.246971529Z"}

**Comment by anwen-anyi** [comment]
补充：已测试 阿里 腾讯 都会这样其他的存储桶暂未测试.

**Comment by Xhofe** [comment]
请提供一个测试账户以供测试

mailto: i@nn.ci

**Comment by anwen-anyi** [comment]
> 请提供一个测试账户以供测试
> 
> mailto: [i@nn.ci](mailto:i@nn.ci)

发了一个七牛的 查收

**Comment by shpdnkti** [comment]
请问这个问题最后是怎么解决的？

**Comment by Sakura-zyu** [comment]
@skyle1995 您可以试试使用 “隐藏文件功能”来进行隐藏无效文件，在“设置-全局-隐藏文件”内用正则表达式来进行填写。例如 //二级文件夹名字/i 亲测有效！！！
![Snipaste_2023-09-11_23-56-24](https://github.com/alist-org/alist/assets/38059916/1b327bce-cead-44e8-9fa2-b560a1735aaf)

**Comment by jochne** [comment]
请问v3.29.1版本腾讯云COS还是会有这个问题，会有版本修复吗？还是智能用上面的临时方案解决呢～？
