### ISSUE TITLE
使用/d作为挂载目录，刷新2次后会有401报错

### ISSUE THREAD

**Issue by immoke** [alist-org/alist#3138]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.1

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

环境描述如下：
1）使用群辉docker、CentOS 7 执行官方一键命令，均出现此情况；
2）后端是阿里云盘，
3）只要使用/d作为挂载目录，进入第二级目录刷新2次页面就会出现报错，错误信息如下：
{"code":401,"message":"expire missing","data":null}

例如挂载目录为/d，文件夹目录为1，那么进入 192.168.168.100:5244/d/1，在此目录下刷新两次即可复现问题。

使用/a /c /d /e 均无此问题，使用其他名称也没有问题。

因为/d在我这是比较常用的，所以想反馈一下，并想咨询一下，是哪里出现了问题呢？

### Reproduction / 复现链接

alist.mmoke.com/dd
这个为目前没有问题的链接。如果将/dd改为/d，就会出现此问题。

### Logs / 日志

不清楚哪里有错误日志。
{"code":401,"message":"expire missing","data":null}，这个算吗？

**Comment by anwen-anyi** [comment]
呃呃呃...建议换一个...因为   `/d/` 是用来当下载用的....明知道`/d/` 还用这个名字来挂载. 还有 `/p/`也是（这个是用于中转的似乎）

**Comment by immoke** [comment]
> 呃呃呃...建议换一个...因为 `/d/` 是用来当下载用的....明知道`/d/` 还用这个名字来挂载. 还有 `/p/`也是（这个是用于中转的似乎）

因为……我也是用来当下载的……所以用d是最短的……
了解了，请问有能共存的方法吗?我现在用/dd

**Comment by anwen-anyi** [comment]
> 

如果你也用来当下载的话那没招了估计..冲突了吧？
`127.0.0.1:/d/dd/xxxxx`
只能这样了哪你用/d /p 这俩除外的呗

**Comment by Xhofe** [comment]
不要使用 https://github.com/alist-org/alist/blob/6a90b1d40aae342440614d1543790b2ee2d327f7/server/router.go#L15 中定义的路由

**Comment by immoke** [comment]
@Xhofe @anwen-anyi 两位老大好，我参考https://www.yuque.com/anwenya/alist/glqlhu 这个文档，已经实现了编译官方版。然后我尝试修改 alist/server/router.go 文件，希望能将默认路径调整，但是编译后，似乎没有作用。还希望两位大神可以指导一下，谢谢。

我的操作笔记，请帮忙看一下哪里有问题：https://wiki.imoke.org/Github/alist(%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98%E4%BB%A3%E7%90%86)/CentOS%207%20%E7%BC%96%E8%AF%91AlistV3.html
