### ISSUE TITLE
希望能在複製任務裡加上一個按鈕只清除已成功的任務，並保留失敗的任務，這樣容易辨別哪些失敗了要重新複製。

### ISSUE THREAD

**Issue by ITtest1** [alist-org/alist#3140]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望在複製任務頁裡加上只清除成功的任務按鈕和為已失敗任務按鈕添加上重試按鈕。

**Comment by mengguyi** [comment]
别mark成stable
这个issue挺好
顶一下
