### ISSUE TITLE
Form上传进度条满了也不成功

### ISSUE THREAD

**Issue by ysj6** [alist-org/alist#3142]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.1

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

使用Form上传时进度条读完一直不成功，设置界面的上传目录也是空的

### Reproduction / 复现链接

https://user-images.githubusercontent.com/94835973/214492888-b5e2df11-c9b0-4853-85ba-15ec5e3c5862.png
https://user-images.githubusercontent.com/94835973/214493071-6bf2663f-3be7-484d-b957-b13d9d4b895e.png

**Comment by anwen-anyi** [comment]
1. 图一：不是提示在后台上传吗？
 2. 图二：你没有勾选 **`添加为任务`** 选项，后台自然看不到
