### ISSUE TITLE
v3.9.1 docker-compose 部署，备份和恢复有点坑... 全新安装,Alist自己的备份自己恢复报错...

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#3143]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.1

### Driver used / 使用的存储驱动

189

### Describe the bug / 问题描述

服务器迁移，换docker跑，全部重新 手动配置 - 备份 -> 测试恢复 结果失败...
关键挂载网盘信息都报错..

![image](https://user-images.githubusercontent.com/52201479/214500946-b39cc81d-14a7-42fc-bbe8-91ffe0cb1c10.png)

### Reproduction / 复现链接

nop

### Logs / 日志

ℹ️

开始备份

✅

[ 设置 ] 备份成功

✅

[ 用户 ] 备份成功

✅

[ 存储 ] 备份成功

✅

[ 元信息 ] 备份成功

ℹ️

备份完成

ℹ️

开始恢复

✅

[ 设置 ] 恢复成功

❌

[ 用户 ] 恢复失败 [ admin ] :admin or guest user can not be created

❌

[ 用户 ] 恢复失败 [ guest ] :admin or guest user can not be created

❌

[ 存储 ] 恢复失败 [ /189 ] :failed create storage in database: UNIQUE constraint failed: x_storages.mount_path

ℹ️

恢复完成

**Comment by gowy222** [comment]
另外 提个建议:

ocr 和 alist 都是 docker-compose 批量部署的, 
Alist 启动测试ocr 接口的时候，适当给个延迟几秒(10秒吧..)... 
【万能的 docker-compose 一直缺失delay功能!!!igit请愿那么多，官方就是不鸟...】

虽然设置了 depends_on
但是
导致ocr 接口 内部 上线 可能 还需要几秒，alist这边已经开始ping ocr接口了...

--------------
`2023/01/25 15:08:06.167955 ERROR RESTY Post "http://192.168.0.1:9898/ocr/file/json": read tcp 192.168.0.3:55006->192.168.0.1:9898: read: connection reset by peer, Attempt 1
2023/01/25 15:08:06.269069 ERROR RESTY Post "http://192.168.0.1:9898/ocr/file/json": read tcp 192.168.0.3:55010->192.168.0.1:9898: read: connection reset by peer, Attempt 2`

**Comment by gowy222** [comment]
另外 提个建议:

ocr 和 alist 都是 docker-compose 批量部署的, 
Alist 启动测试ocr 接口的时候，适当给个延迟几秒(10秒吧..)... 
【万能的 docker-compose 一直缺失delay功能!!!igit请愿那么多，官方就是不鸟...】

虽然设置了 depends_on
但是
导致ocr 接口 内部 上线 可能 还需要几秒，alist这边已经开始ping ocr接口了...

--------------
`2023/01/25 15:08:06.167955 ERROR RESTY Post "http://192.168.0.1:9898/ocr/file/json": read tcp 192.168.0.3:55006->192.168.0.1:9898: read: connection reset by peer, Attempt 1
2023/01/25 15:08:06.269069 ERROR RESTY Post "http://192.168.0.1:9898/ocr/file/json": read tcp 192.168.0.3:55010->192.168.0.1:9898: read: connection reset by peer, Attempt 2`

**Comment by gowy222** [comment]
而且 alist ping ocr接口失败了，貌似不会后续 继续尝试... 导致挂载网盘一直离线

**Comment by Xhofe** [comment]
对于冲突数据请自行手动处理。
