### ISSUE TITLE
音乐播放预加载下一曲

### ISSUE THREAD

**Issue by haoduck** [alist-org/alist#3144]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否在音乐播放的时候，预加载下一曲。这样播放完毕切下一曲的时候不会停顿，感觉挺不错的。

**Comment by Xhofe** [comment]
dependency:
- https://github.com/MoePlayer/APlayer
