### ISSUE TITLE
希望加入流量控制/限流等功能，能针对单IP或者单文件的请求频率进行限制！

### ISSUE THREAD

**Issue by KNaiFen** [alist-org/alist#3145]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

要不然开个站点很容易被别人爬爆

### Suggested solution / 实现思路

思路的话，我觉得最好是可以针对限制某个文件夹、某个储存点，在一分钟内最多支持几次请求
若能拿到体积参数，针对文件大小总量来限制那就更好了
如100G限制，这个储存点一分钟内被请求了10次10G大小的文件，超出限制了，那就启动流控，限制访问XX分钟

**Comment by anwen-anyi** [comment]
这个恐怕没办法限制的把 好多302重定向的你怎么统计流量？

如果单纯的限制的话可以自行用  nginx 或者 apache 自行设置呗..
