### ISSUE TITLE
复制文件有时候会出现错误，希望能增加重试功能

### ISSUE THREAD

**Issue by 7ongOrz** [alist-org/alist#3151]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

有时候复制文件多了之后会出现错误，希望能增加像rclone一样的自动重试功能，不然还得一个一个找错误重新复制

**Comment by hsxnet** [comment]
请问，通过文件夹对比工具BCompare，把本机硬盘上的文件，上传至阿里云盘的相同目录下，为何在阿里云盘的回收站里有自动删除的同名文件，且文件大小是0K？要手工在阿里云盘APP里手工删除。这是不是影响上传速度的原因，上传好慢好慢。
谢谢老大的软件！！

**Comment by EchoGroot** [comment]
希望增加重试功能，从阿里云盘复制多个文件到本地时，出现“错误 unexpected EOF”
![image](https://user-images.githubusercontent.com/44628981/222112926-af56ac50-ccbb-4d1d-b5cb-cf597ff9f404.png)

**Comment by liuhangbin** [comment]
+1， 网盘之间复制东西的时候也是经常出现失败，之前没注意，结果源文件都删了...希望加入重试功能，谢谢

**Comment by mengguyi** [comment]
+1，尤其是网络不好的时候

**Comment by BurtSweet** [comment]
希望能出一个一键批量重试....E5挂了整盘复制到另外一个盘失败了7页.一个一个点重试太费手了,希望大佬们能支持一键全部重试功能

**Comment by endercatone** [comment]
+1，网络不好一整页都是失败的

**Comment by Winyer** [comment]
补充一下，哪怕是手动点击了重试，它依然有可能直接失败进入已完成列表中，所以希望重试功能改进一下，以及，能够把需要重试的单独列出来，已完成列表只显示真正完成了的

**Comment by Winyer** [comment]
> 希望能出一个一键批量重试....E5挂了整盘复制到另外一个盘失败了7页.一个一个点重试太费手了,希望大佬们能支持一键全部重试功能

一键重试+1

**Comment by koinouta1** [comment]
+1

**Comment by SuNine520** [comment]
我也希望有这个功能，添加一个定时重试也不错

**Comment by seanhe26** [comment]
由于目前alist的代码没有做流操作的size判断，很容易产生不完整文件。
我后面会给task加入 自动重试，断点续传，完整性判断。
新功能会展示在https://github.com/seanhe26/alist-private-cloud

**Comment by ohmyarch** [comment]
希望增加定时重试或全部重试功能，目前这个单次重试基本没用。
