### ISSUE TITLE
Linux Arm64版本挂载阿里云盘出错，failed get objs: failed to list objs: Post "https://api.aliyundrive.com/v2/file/list": EOF

### ISSUE THREAD

**Issue by sechina** [alist-org/alist#3164]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

alist-linux-arm64 v3.9.2

### Driver used / 使用的存储驱动

Aliyun

### Describe the bug / 问题描述

系统；N1刷的Armbian
用Alist挂载Pikpak和本地存储正常。但挂载阿里云盘出错。
我以为是我的token有问题，但我用同样的token和设置在WIN64版本在电脑上却可以挂载，所以可能是ARM64版本的BUG。
难道是我用的版本不对吗？
有没有相同问题的朋友 请指教一下，谢谢！

### Reproduction / 复现链接

1月 27 19:03:26 aml alist[392375]: 2023/01/27 19:03:26.977883 ERROR RESTY Post "https://auth.aliyundrive.com/v2/account/token": EOF, Attempt 1

### Logs / 日志

![image](https://user-images.githubusercontent.com/121702670/215072083-f9aa03e8-2ed0-4416-bfc4-99c1f0dfb765.png)
![image](https://user-images.githubusercontent.com/121702670/215072652-f3af9d01-812b-44dd-8c4a-686b53dc9d34.png)

**Comment by mengguyi** [comment]
![image](https://user-images.githubusercontent.com/73788063/215075480-a8ac332e-0d83-4dda-9552-5e821fd82d98.png)
好像是有问题
不过不排除网络问题

**Comment by mengguyi** [comment]
![image](https://user-images.githubusercontent.com/73788063/215075978-2caa933b-9c8d-40c9-abe5-f5e0f492e07c.png)
![image](https://user-images.githubusercontent.com/73788063/215075991-40a92306-f18a-4655-b48a-3933c3c65665.png)
树莓派4 Ubuntu22.04 没有问题

**Comment by mengguyi** [comment]
![image](https://user-images.githubusercontent.com/73788063/215076266-0561a8ad-25f3-4147-b1e4-7fc6a275bfcd.png)

**Comment by veryflying** [comment]
遇到同样的问题， Macos

**Comment by sechina** [comment]
兄弟们，我的问题解决了， 在主路由关闭IPV6功能，只用IPV4就可以挂载了

**Comment by cmal** [comment]
同样问题
