### ISSUE TITLE
请求百度网盘支持文档在线预览

### ISSUE THREAD

**Issue by xiaozhou26** [alist-org/alist#3165]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

请求百度网盘支持文档在线预览
因为百度网盘不能使用Microsoft和Google的在线文档功能，不支持访问，所以希望添加百度网盘在线查看文档功能，感谢！

**Comment by anwen-anyi** [comment]
没有你说的哪个无法打开的问题，再加上百度本就需要UA请求头
Microsoft和Google看不了是因为网络问题导致的和Alist无关，也可以自行搭建office服务
![](http://pic.rmb.bdstatic.com/bjh/c4fb8bc02f42daefe959410b1f5b8546.png)

**Comment by wowo14735** [comment]
> 没有你说的哪个无法打开的问题，再上百度本就需要UA请求头（文档这种几百万的倒是不需要的）微软件和谷歌看不了主要是因为网络网络问题导向致连接不上的和Alist 无关，也可以自行搭建办公室办公室服务 ![](https://camo.githubusercontent.com/4fe40b1e8f9dcffad5166e9af8edaaf543280a99e19792870fbf8f2b8cf8a4f4/687474703a2f2f7069632e726d622e62647374617469632e636f6d2f626a682f63346662386263303266343264616566653935393431306231663562383534362e706e67)
> 
> ### 下图为自动搭建办公服务
> 个人使用不对外开放 ![](https://camo.githubusercontent.com/f808f730c35a3c696e840f0e4d4d421455b6d73ef212290d93e8084e163eab51/687474703a2f2f7069632e726d622e62647374617469632e636f6d2f626a682f39323936616239376431626438653333653861326337383362326138663731622e706e67)

咋整
