### ISSUE TITLE
能否给一个是否开启log日志的按钮,日志把我docker空间都沾满了导致无法启动

### ISSUE THREAD

**Issue by aTenb** [alist-org/alist#3170]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否给一个是否开启log日志的按钮,日志把我docker空间都沾满了导致无法启动

### Suggested solution / 实现思路

给一个log日志关闭的按钮

我看了一下日志 我是削刮了本地的,导致alist每次都云端都检测不到文件生成一推日志,3个多G 把我空间沾满了,算一个bug吧

**Comment by Xhofe** [comment]
请查阅配置文件
