### ISSUE TITLE
目录结构已知时网址后面输入对应目录结构可绕过密码直接进入目标目录

### ISSUE THREAD

**Issue by zytk100** [alist-org/alist#3172]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.2

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

目录结构已知时网址后面输入对应目录结构可绕过密码直接进入目标目录

https://user-images.githubusercontent.com/65448374/215249775-10fdb584-9add-4662-9340-ccfaa298550d.mp4

### Reproduction / 复现链接

https://github.com/everstu/Koolcenter_alist

**Comment by anwen-anyi** [comment]
请把后面应用到子文件 勾上谢谢

**Comment by zytk100** [comment]
好了，谢谢

**Comment by anwen-anyi** [comment]
> 好了，谢谢

自行关闭issue即可
