### ISSUE TITLE
The problem of excessive load pressure on public welfare stations

### ISSUE THREAD

**Issue by xiaohuang-01** [alist-org/alist#3176]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Hello author, alist seems to be a very perfect network disk directory program
But now many public welfare sites suffer from the problem of malicious API brushing or overdrawn downloads
I have the following two suggestions
1. For the v3 v2 web page mount, add a switch to allow or not to be mounted by a third-party alist, which is the same as the index, or the white list specifies that some alliances formed by webmasters mount each other
2. Add a switch for the download function. The site owner can decide when to open the download and close the download function appropriately.
Sincerely, salute
A non-profit webmaster

**Comment by BoYanZh** [comment]
Mounted by other alist program is identical to be browsed through web page.
