### ISSUE TITLE
Nginx反代alist到二级目录会影响Webdav

### ISSUE THREAD

**Issue by gkl1368** [alist-org/alist#3182]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.2

### Driver used / 使用的存储驱动

dav

### Describe the bug / 问题描述

Nginx反代alist到二级目录使用Howto里面的教程https://alist.nn.ci/zh/faq/howto.html#%E5%A6%82%E4%BD%95%E5%AF%B9%E5%AD%90%E7%9B%AE%E5%BD%95%E8%BF%9B%E8%A1%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86 会导致目录列出不正确

每个文件夹会多出当前文件夹的名称 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/12904884/215304115-a2da5687-e9e9-430e-8407-b802167a6f43.png">
<img width="287" alt="image" src="https://user-images.githubusercontent.com/12904884/215304121-0cf73926-1aaa-4a71-8422-1512bcc5df9a.png">
<img width="441" alt="image" src="https://user-images.githubusercontent.com/12904884/215304150-485c42d0-aad6-42c4-8c47-fb8b3795f992.png">

查看日志发现查找了 /dav/dav,/dav,/alist/dav 

### Reproduction / 复现链接

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/12904884/215303812-6ac03938-e402-4843-b149-5d41172595e2.png">

### Logs / 日志

Alist  | [GIN] 2023/01/29 - 10:01:56 | 401 |    1.821252ms |     172.27.3.33 | PROPFIND  "/dav"
Alist  | [GIN] 2023/01/29 - 10:01:56 | 207 |   17.509769ms |     172.27.3.33 | PROPFIND  "/dav"
Alist  | ERRO[2023-01-29 10:01:59] failed get /Kelly/dav: can't find storage with rawPath: /Kelly/dav
Alist  | github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
Alist  |        /app/internal/op/path.go:18
Alist  | github.com/alist-org/alist/v3/internal/fs.get
Alist  |        /app/internal/fs/get.go:25
Alist  | github.com/alist-org/alist/v3/internal/fs.Get
Alist  |        /app/internal/fs/fs.go:26
Alist  | github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
Alist  |        /app/server/webdav/webdav.go:591
Alist  | github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
Alist  |        /app/server/webdav/webdav.go:72
Alist  | github.com/alist-org/alist/v3/server.ServeWebDAV
Alist  |        /app/server/webdav.go:44
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/alist-org/alist/v3/server.WebDAVAuth
Alist  |        /app/server/webdav.go:93
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
Alist  |        /app/server/middlewares/check.go:14
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.LoggerWithConfig.func1
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616
Alist  | github.com/gin-gonic/gin.(*Engine).ServeHTTP
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572
Alist  | net/http.serverHandler.ServeHTTP
Alist  |        /usr/lib/go/src/net/http/server.go:2947
Alist  | net/http.(*conn).serve
Alist  |        /usr/lib/go/src/net/http/server.go:1991
Alist  | runtime.goexit
Alist  |        /usr/lib/go/src/runtime/asm_amd64.s:1594
Alist  | failed get storage 
Alist  | ERRO[2023-01-29 10:01:59] PROPFIND /dav/dav can't find storage with rawPath: /Kelly/dav
Alist  | github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
Alist  |        /app/internal/op/path.go:18
Alist  | github.com/alist-org/alist/v3/internal/fs.get
Alist  |        /app/internal/fs/get.go:25
Alist  | github.com/alist-org/alist/v3/internal/fs.Get
Alist  |        /app/internal/fs/fs.go:26
Alist  | github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
Alist  |        /app/server/webdav/webdav.go:591
Alist  | github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
Alist  |        /app/server/webdav/webdav.go:72
Alist  | github.com/alist-org/alist/v3/server.ServeWebDAV
Alist  |        /app/server/webdav.go:44
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/alist-org/alist/v3/server.WebDAVAuth
Alist  |        /app/server/webdav.go:93
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
Alist  |        /app/server/middlewares/check.go:14
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.LoggerWithConfig.func1
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616
Alist  | github.com/gin-gonic/gin.(*Engine).ServeHTTP
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572
Alist  | net/http.serverHandler.ServeHTTP
Alist  |        /usr/lib/go/src/net/http/server.go:2947
Alist  | net/http.(*conn).serve
Alist  |        /usr/lib/go/src/net/http/server.go:1991
Alist  | runtime.goexit
Alist  |        /usr/lib/go/src/runtime/asm_amd64.s:1594
Alist  | failed get storage 
Alist  | [GIN] 2023/01/29 - 10:01:59 | 405 |     469.822µs |     172.27.3.33 | PROPFIND  "/dav/dav"
Alist  | ERRO[2023-01-29 10:02:00] failed get /Kelly/dav: can't find storage with rawPath: /Kelly/dav
Alist  | github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
Alist  |        /app/internal/op/path.go:18
Alist  | github.com/alist-org/alist/v3/internal/fs.get
Alist  |        /app/internal/fs/get.go:25
Alist  | github.com/alist-org/alist/v3/internal/fs.Get
Alist  |        /app/internal/fs/fs.go:26
Alist  | github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
Alist  |        /app/server/webdav/webdav.go:591
Alist  | github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
Alist  |        /app/server/webdav/webdav.go:72
Alist  | github.com/alist-org/alist/v3/server.ServeWebDAV
Alist  |        /app/server/webdav.go:44
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/alist-org/alist/v3/server.WebDAVAuth
Alist  |        /app/server/webdav.go:93
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
Alist  |        /app/server/middlewares/check.go:14
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.LoggerWithConfig.func1
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616
Alist  | github.com/gin-gonic/gin.(*Engine).ServeHTTP
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572
Alist  | net/http.serverHandler.ServeHTTP
Alist  |        /usr/lib/go/src/net/http/server.go:2947
Alist  | net/http.(*conn).serve
Alist  |        /usr/lib/go/src/net/http/server.go:1991
Alist  | runtime.goexit
Alist  |        /usr/lib/go/src/runtime/asm_amd64.s:1594
Alist  | failed get storage 
Alist  | ERRO[2023-01-29 10:02:00] PROPFIND /dav/dav can't find storage with rawPath: /Kelly/dav
Alist  | github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
Alist  |        /app/internal/op/path.go:18
Alist  | github.com/alist-org/alist/v3/internal/fs.get
Alist  |        /app/internal/fs/get.go:25
Alist  | github.com/alist-org/alist/v3/internal/fs.Get
Alist  |        /app/internal/fs/fs.go:26
Alist  | github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
Alist  |        /app/server/webdav/webdav.go:591
Alist  | github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
Alist  |        /app/server/webdav/webdav.go:72
Alist  | github.com/alist-org/alist/v3/server.ServeWebDAV
Alist  |        /app/server/webdav.go:44
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/alist-org/alist/v3/server.WebDAVAuth
Alist  |        /app/server/webdav.go:93
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
Alist  |        /app/server/middlewares/check.go:14
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.LoggerWithConfig.func1
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240
Alist  | github.com/gin-gonic/gin.(*Context).Next
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
Alist  | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616
Alist  | github.com/gin-gonic/gin.(*Engine).ServeHTTP
Alist  |        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572
Alist  | net/http.serverHandler.ServeHTTP
Alist  |        /usr/lib/go/src/net/http/server.go:2947
Alist  | net/http.(*conn).serve
Alist  |        /usr/lib/go/src/net/http/server.go:1991
Alist  | runtime.goexit
Alist  |        /usr/lib/go/src/runtime/asm_amd64.s:1594
Alist  | failed get storage 
Alist  | [GIN] 2023/01/29 - 10:02:00 | 405 |      501.74µs |     172.27.3.33 | PROPFIND  "/dav/dav"
Alist  | [GIN] 2023/01/29 - 11:42:05 | 200 |     701.137µs |     172.27.3.33 | PROPFIND  "/"
Alist  | [GIN] 2023/01/29 - 11:42:21 | 200 |     198.489µs |     172.27.3.33 | PROPFIND  "/alist/dav"
Alist  | [GIN] 2023/01/29 - 11:42:31 | 401 |      20.743µs |     172.27.3.33 | PROPFIND  "/dav"
Alist  | [GIN] 2023/01/29 - 11:42:31 | 207 |    1.023734ms |     172.27.3.33 | PROPFIND  "/dav"
Alist  | [GIN] 2023/01/29 - 11:44:38 | 401 |      24.514µs |     172.27.3.21 | PROPFIND  "/dav/"
Alist  | [GIN] 2023/01/29 - 11:44:38 | 207 |      475.48µs |     172.27.3.21 | PROPFIND  "/dav/"
Alist  | [GIN] 2023/01/29 - 11:44:38 | 200 |     6.06523ms |     172.27.3.21 | OPTIONS  "/dav/"
Alist  | [GIN] 2023/01/29 - 11:44:38 | 207 |     390.203µs |     172.27.3.21 | PROPFIND  "/dav/"
Alist  | [GIN] 2023/01/29 - 11:44:40 | 207 |  703.352883ms |     172.27.3.21 | PROPFIND  "/dav/"
Alist  | [GIN] 2023/01/29 - 11:44:44 | 207 |  1.266556149s |     172.27.3.21 | PROPFIND  "/dav/Media Center/"
Alist  | [GIN] 2023/01/29 - 11:44:45 | 207 |  1.248961233s |     172.27.3.21 | PROPFIND  "/dav/Buacg 盘/"

**Comment by gkl1368** [comment]
目前有能力测试了4个客户端: win: raidrive:正确,  macos: forklift:不正确，ios: infuse:不正确， ios: Documents 正确

**Comment by Xhofe** [comment]
This should have been fixed in https://github.com/alist-org/alist/commit/6c2f3486fc155e795026d08cf55d559f3e63595a
