### ISSUE TITLE
更新v3.9.2后上传1.8GB文件OOM

### ISSUE THREAD

**Issue by godlikeanyone** [alist-org/alist#3184]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.2

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

我用fly.io部署的alist，更新v3.9.2后用chrome上传一个1.8GB的ipa文件到任意云盘（OD, GD, 天翼等）后提示out of memory。
这是Windows任务管理器查看内存占用情况，我尝试了两次所以有两个峰值。每当内存占满时chrome会提示out of memory。v3.9.1没有这个bug。
![](https://m.360buyimg.com/babel/jfs/t1/1075/8/18354/20318/63d616b2F0c6a6e33/c3b8a1ebe9e91301.png)

### Reproduction / 复现链接

fly.io部署v3.9.2 alist之后上传超过1.8G的文件至任意云盘

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/faq/why.html#%E4%B8%A4%E4%B8%AA%E4%B8%8A%E4%BC%A0%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB

**Comment by iKangnakamuyi** [comment]
你好，能否请教一下 Fly.io 部署方式如何更新 Alist？谢谢！
