### ISSUE TITLE
能否更新一下pdf.js，目前手机端无法观看，电脑端可以

### ISSUE THREAD

**Issue by liuke0538** [alist-org/alist#3190]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前pdf只能在电脑端查看，手机端查看不了，希望作者可以修复下，感激不尽

**Comment by BoYanZh** [comment]
无法复现

**Comment by ClockworkChen** [comment]
在微信里面用微信内置浏览器打开，无法观看。

**Comment by liuke0538** [comment]
> 在微信里面用微信内置浏览器打开，无法观看。

普通手机浏览器也看不了

**Comment by BoYanZh** [comment]
使用microsoft edge 109.0.1518.53无法复现
