### ISSUE TITLE
chrome109.0.5414.120浏览器访问播放音乐中文歌词一律乱码+播放视频音乐无法拖放进度条

### ISSUE THREAD

**Issue by heygo1345678** [alist-org/alist#3192]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v 3.9.2

### Driver used / 使用的存储驱动

smb

### Describe the bug / 问题描述

浏览器访问alist web网页播放中文音乐歌词全部乱码，英文歌词正常， 播放视频或者音乐拖动进度条会重新播放，无法实现到拖放的时间轴播放

### Reproduction / 复现链接

没有

### Logs / 日志

[GIN] 2023/01/30 - 01:10:46 | 200 |  103.987778ms |   192.168.111.4 | GET      "/d/D/Music/爱的供养-杨幂.mp3?sign=g=:0"

![捕获](https://user-images.githubusercontent.com/79509309/215368051-416287d0-eea4-4f81-8f14-f5dc570b733e.JPG)

**Comment by Xhofe** [comment]
- 对于歌词我们只支持utf8，如果乱码请手动转码

**Comment by heygo1345678** [comment]
> * 对于歌词我们只支持utf8，如果乱码请手动转码

好的，多谢大佬，刚刚用notepad++查看lrc文件确实都是gb2312,另存为转换为utf8测试正常了

**Comment by heygo1345678** [comment]
> * 对于歌词我们只支持utf8，如果乱码请手动转码

我测试了/etc/fstab挂载cifs，然后映射到docker alist，然后alist容器挂载本地存储目录，而这个目录是/etc/fstab挂载cifs目录，这个情况下是播放视频音乐可可用拖动进度条时间轴的，说明这个bug还是和alist smb功能相关的，目前就这样使用了，之前玩emby jellyfin filebrowser也是这么套娃
