### ISSUE TITLE
希望添加本地存储的权限设置

### ISSUE THREAD

**Issue by Qs315490** [alist-org/alist#3196]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我在使用 `alist3.9.2` 和 `samba` 配合使用，为了安全 `samba` 没有 `root` 登录。
`alist` 默认创建的文件夹所有者是 `root` 且所有组没有读取和写入权限，导致 `samba` 无权限访问文件夹。
`samba` 配置为用户各 `home` 文件夹对应 `/pan` 目录下的用户同名文件夹。
比如 `qs315490` 的用户文件夹为 `/pan/qs315490` ，`test` 的用户文件夹为 `/pan/test`

建议添加本地目录时可以 `指定 Linux 用户` 

### Suggested solution / 实现思路

使用指定用户运行 `alist` 是行不通的，本地挂载了不同用户的文件夹。
因为服务是 `root` 权限运行，网页也不会有权限问题。
只是 `samba`不同用户对应文件夹不同，无法通过添加 `root` 用户解决。

在新建文件时使用指定用户创建

**Comment by BoYanZh** [comment]
也许可以通过 https://github.com/alist-org/alist/blob/main/entrypoint.sh 解决，否则就是 #2996

**Comment by Qs315490** [comment]
> 也许可以通过 https://github.com/alist-org/alist/blob/main/entrypoint.sh 解决，否则就是 #2996

这并不能解决问题，我使用脚本部署不是Docker。需要的功能是网页创建文件是指定Linux用户和组以及目前版本umask不生效。

**Comment by DDSDerek** [comment]
> > 也许可以通过 https://github.com/alist-org/alist/blob/main/entrypoint.sh 解决，否则就是 #2996
> 
> 这并不能解决问题，我使用脚本部署不是Docker。需要的功能是网页创建文件是指定Linux用户和组以及目前版本umask不生效。

脚步部署也是可以更改启动程序的用户的，但是目前Umask设置还是有问题，得等作者修复

**Comment by DDSDerek** [comment]
最好的方法还是程序能提供启动用户和用户组设置，这样使用更方便，兼容性更强

**Comment by Qs315490** [comment]
> 最好的方法还是程序能提供启动用户和用户组设置，这样使用更方便，兼容性更强

我就是这个意思，对每个本地存储都可以自定义用户和组

**Comment by Xhofe** [comment]
我想这个[commit](https://github.com/alist-org/alist/commit/51f5d1b3c4e38c4acc3a5268cefe369d12de712e)可以解决此问题。

**Comment by DDSDerek** [comment]
> 我想这个[commit](https://github.com/alist-org/alist/commit/51f5d1b3c4e38c4acc3a5268cefe369d12de712e)可以解决此问题。

我认为这个 commit 并没有完全解决这个问题，因为这个 commit 只是将文件夹的权限设置为了777，而文件的权限还是归属于root用户，权限掩码为644，最终还是会导致权限问题

**Comment by Xhofe** [comment]
你可以将umask 改为0，而不是一定要使用022

**Comment by DDSDerek** [comment]
> 你可以将umask 改为0，而不是一定要使用022

但是我认为使用777权限是一件危险的事情。并且通过脚本安装的alist，好像是不支持umask设置的吧？

**Comment by Xhofe** [comment]
可用直接修改系统的umask。
```bash
umask 0
```

**Comment by DDSDerek** [comment]
> 可用直接修改系统的umask。
> 
> ```shell
> umask 0
> ```

不会修改到系统的umask的，系统默认umask是不会变的，每个shell都是022，这个命令只能更改当前shell的umask

**Comment by Xhofe** [comment]
```bash
umask 0 && alist server
```

**Comment by DDSDerek** [comment]
> ```shell
> umask 0 && alist server
> ```

是的，这样确实可以解决

但是我有一点想请教，程序创建文件夹的权限掩码只能在程序源码中修改吗？是否可以根据环境的umask变化而变化
