### ISSUE TITLE
如何添加谷歌相册

### ISSUE THREAD

**Issue by zhumimi520** [alist-org/alist#3208]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我看到有支持google相册，但是没有google相册添加的相关教程，安装google云端网盘步骤添加后，无法访问到google相册。烦请更新下如果添加google相册的教程，非常感激。

**Comment by LittleJake** [comment]
可以参考 #1925

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/guide/drivers/googlephotos.html
