### ISSUE TITLE
启动时提示 “WARN[2023-01-31 22:05:51] not enable search” 求大佬解决

### ISSUE THREAD

**Issue by BuyDew** [alist-org/alist#3210]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.92

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

启动时提示  “WARN[2023-01-31 22:05:51] not enable search” 
求大佬解决

### Reproduction / 复现链接

![屏幕截图 2023-01-31 221427](https://user-images.githubusercontent.com/64422189/215785883-49962204-71c4-471b-8d8e-76bc280f4e26.png)

### Logs / 日志

[log.log](https://github.com/alist-org/alist/files/10547229/log.log)

**Comment by mengguyi** [comment]
https://alist.nn.ci/zh/guide/advanced/search.html#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8
