### ISSUE TITLE
EOF occurs when SFTP to mac book .

### ISSUE THREAD

**Issue by leaf918** [alist-org/alist#3213]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.2

### Driver used / 使用的存储驱动

SFTP

### Describe the bug / 问题描述

通过SFTP挂载局域网下的磁盘到alist.一共挂载了两个，分别是
nas:
挂载成功，
mac book:
不成功，配置与nas相同，ip地址不同，但是报错 EOF。如下图
![image](https://user-images.githubusercontent.com/170311/215938436-87a9970c-006f-4a64-b7de-4512025cf3c6.png)

查看log显示如下：
![image](https://user-images.githubusercontent.com/170311/215938526-5c21bf9e-6167-4aaa-bcf1-57a1df05becb.png)

推测是代码逻辑中没有很好的处理异常，没有经过mac 端为目标的测试。

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/170311/215938727-41da45d3-96cc-4692-a800-bbd87da4195e.png)

### Logs / 日志

![image](https://user-images.githubusercontent.com/170311/215938720-80be1257-f91c-45ef-9097-9862500c256a.png)
![image](https://user-images.githubusercontent.com/170311/215938739-4a2b023c-bf1b-4264-93d2-eb89fbaea666.png)

**Comment by Xhofe** [comment]
please check your network.

**Comment by leaf918** [comment]
网络当然是没有问题。检查过。
