### ISSUE TITLE
阿里云盘分享bug

### ISSUE THREAD

**Issue by leon1509** [alist-org/alist#3215]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.2

### Driver used / 使用的存储驱动

阿里云盘分享

### Describe the bug / 问题描述

[https://www.aliyundrive.com/s/Dz5KUjNgnPV](https://www.aliyundrive.com/s/Dz5KUjNgnPV)

这个分享链接无法读取其中的【500多部港剧大合集 15T】文件列表，其它目录都可以，直接打开分享链接也可以读取！

请参见下面的图片

### Reproduction / 复现链接

<img width="958" alt="image" src="https://user-images.githubusercontent.com/4725850/215973624-bf35f86d-6355-4cf7-a2e1-8e475429d067.png">

<img width="978" alt="image" src="https://user-images.githubusercontent.com/4725850/215973941-b1c17e72-566f-4ea4-af94-b24aea9d11d8.png">

**Comment by leon1509** [comment]
路径中没有/

![image](https://user-images.githubusercontent.com/4725850/215982166-43a98d7a-0548-4a75-9144-8bcc1b79b563.png)

**Comment by anwen-anyi** [comment]
难道是因为目录太多了？
直接单独将这个目录`635fb9326c5a195866db4d20b75cbe73a78c027a`挂载倒是可以添加上去

**Comment by Xhofe** [comment]
1. 我不是很理解为什么要在目录名称后面加个`\n`导致歧义。
![image](https://user-images.githubusercontent.com/36558727/216037813-eda2e480-4579-49b9-9705-b194a014312e.png)
2. 你可以通过在`文件名字符映射`中添加`\n`->空字符串的映射解决此问题。
