### ISSUE TITLE
搜索会展示加密文件夹下的内容，并且可以直接点击进去

### ISSUE THREAD

**Issue by z953218350** [alist-org/alist#3218]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.2

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

搜索功能匹配到加密问价夹下的内容会展示出来，并且可以不需要密码直接点进去

### Reproduction / 复现链接

1.访问加密的问价夹
![1675241785104](https://user-images.githubusercontent.com/20390760/215996691-de8016b7-fa0b-45b8-b375-2f272bc81830.jpg)
2.搜索
![1675241849110](https://user-images.githubusercontent.com/20390760/215996864-67fc0b4c-0a30-483e-9ef9-ccd5b794d019.jpg)
3.点击直接进去
![1675241942162](https://user-images.githubusercontent.com/20390760/215997285-fbcd32db-dc3f-460d-8389-da77dbe8cc85.jpg)

### Logs / 日志

No response

**Comment by Xhofe** [comment]
https://alist.nn.ci/guide/advanced/meta.html#hide
