### ISSUE TITLE
使用右下角工具新建文件夹时提示“Not implement”，上传本地文件提示“upload not supported”，求大佬解决！

### ISSUE THREAD

**Issue by BuyDew** [alist-org/alist#3220]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.92

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

使用右下角工具新建文件夹时提示“Not implement”，上传本地文件提示“upload not supported”，求大佬解决！

### Reproduction / 复现链接

![屏幕截图 2023-02-01 182505](https://user-images.githubusercontent.com/64422189/216017654-f4445fe0-d270-4b96-a201-95f48d3ac40b.png)
![屏幕截图 2023-02-01 182331](https://user-images.githubusercontent.com/64422189/216017669-eaa3230f-117b-4d6b-9d73-ae30b9938d03.png)

### Logs / 日志

[log.log](https://github.com/alist-org/alist/files/10555945/log.log)

**Comment by Xhofe** [comment]
请提供一个可供复现的链接。

**Comment by BuyDew** [comment]
> 请提供一个可供复现的链接。

纯小白，在本机里整的，请问一下咋提供复现链接

**Comment by BuyDew** [comment]
> 请提供一个可供复现的链接。

纯小白，在windows上整的，请问怎么提供复现链接

**Comment by Xhofe** [comment]
> > 请提供一个可供复现的链接。
> 
> 纯小白，在windows上整的，请问怎么提供复现链接

你可以使用内网穿透或在带有公网IP的服务器上部署。

**Comment by BuyDew** [comment]
> > > 请提供一个可供复现的链接。
> > 
> > 
> > 纯小白，在windows上整的，请问怎么提供复现链接
> 
> 你可以使用内网穿透或在带有公网IP的服务器上部署。

http://6g864268y1.yicp.fun:5244/
账号：tset
密码：test

**Comment by Xhofe** [comment]
> > > > 请提供一个可供复现的链接。
> > > 
> > > 
> > > 纯小白，在windows上整的，请问怎么提供复现链接
> > 
> > 你可以使用内网穿透或在带有公网IP的服务器上部署。
> 
> http://6g864268y1.yicp.fun:5244/
> 账号：test
> 密码：test

打不开

**Comment by BuyDew** [comment]
> > > > > 请提供一个可供复现的链接。
> > > > 
> > > > 
> > > > 纯小白，在windows上整的，请问怎么提供复现链接
> > > 
> > > 
> > > 你可以使用内网穿透或在带有公网IP的服务器上部署。
> > 
> > 
> > http://6g864268y1.yicp.fun:5244/
> > 账号：test
> > 密码：test
> 
> 打不开

这会不在家，晚上八点左右再试试

**Comment by AYOMITA** [comment]
您好，我也遇到了相同问题，这是网址：https://necs.work，账号：alist_test，密码：test，您可以在初始目录下的任何地方上传，都会复现该问题。
