### ISSUE TITLE
无法访问SMB文件夹

### ISSUE THREAD

**Issue by Sostay** [alist-org/alist#3228]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.2

### Driver used / 使用的存储驱动

smb

### Describe the bug / 问题描述

3.8版本之后访问SMB都出现以下提示：
failed get objs: failed to list objs: open \: leading '\' is not allowed in this operation
![image](https://user-images.githubusercontent.com/6897274/216253934-7578e460-0df9-4b47-8846-f8a737577c45.png)
同一个文件夹，3.8及之前的版本都能正常访问

### Reproduction / 复现链接

挂载在本地电脑上的
http://192.168.210.139:5244/192.168.210.6

**Comment by BoYanZh** [comment]
请提供具体配置和log

**Comment by Sostay** [comment]
> 请提供具体配置和log

是直接上传config和log文件吗请问？

**Comment by BoYanZh** [comment]
> > 请提供具体配置和log
> 
> 是直接上传config和log文件吗请问？

smb挂载配置截图和log文件

**Comment by Sostay** [comment]
[log.log](https://github.com/alist-org/alist/files/10680897/log.log)
![image](https://user-images.githubusercontent.com/6897274/217408443-6169ca2d-d77b-4cbb-ba34-63bdcb705a09.png)
![image](https://user-images.githubusercontent.com/6897274/217408450-5ddcddc7-b0d6-4afa-a487-737abbade389.png)
错误提示第一张是smb根目录，第二张是子目录

**Comment by Sostay** [comment]
> [log.log](https://github.com/alist-org/alist/files/10680897/log.log) ![image](https://user-images.githubusercontent.com/6897274/217408443-6169ca2d-d77b-4cbb-ba34-63bdcb705a09.png) ![image](https://user-images.githubusercontent.com/6897274/217408450-5ddcddc7-b0d6-4afa-a487-737abbade389.png) 错误提示第一张是smb根目录，第二张是子目录
> 
@BoYanZh

**Comment by Sostay** [comment]
。。。。。

**Comment by shinobi9** [comment]
根据 #2634 我猜应该是路径处理改了，我把根文件夹路径改成  `.\` 就可以了 @Sostay

**Comment by Sostay** [comment]
> 根据 #2634 我猜应该是路径处理改了，我把根文件夹路径改成 `.\` 就可以了 @Sostay
牛哇 这么久终于有人解决我的问题了~ 😂😂😂
