### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by sakaman** [alist-org/alist#3229]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

For list content pages, adding PWA support is more suitable for fast and easy access on mobile and desktop to improve the operating experience; additionally, the web app can be launched in full screen or standalone mode for a more native experience.

### Suggested solution / 实现思路

Refer to [Mozilla development documentation](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs), just add `<head>` block to `index.html`, and you need to configure the *`.webmanifest` file to personalize the PWA.

```html
<link rel="manifest" href="alistpwa.webmanifest" />
```
```json
{
  "name": "Alist Progressive Web App",
  "short_name": "AlistPWA",
  "description": "Progressive Web App for alist.",
  "icons": [
    {
      "src": "icons/icon-32.png",
      "sizes": "32x32",
      "type": "image/png"
    },
    // ...
    {
      "src": "icons/icon-512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "start_url": "/index.html",
  "display": "fullscreen",
  "theme_color": "#B12A34",
  "background_color": "#B12A34"
}
```

**Comment by Meuko** [comment]
So all you want is the app to be installable on your mobile (allowing you to add alist to your homescreen?) This is just a partial implementation of PWA.

**Comment by sakaman** [comment]
> So all you want is the app to be installable on your mobile (allowing you to add alist to your homescreen?) This is just a partial implementation of PWA.

Yep, don't need many development resources to get mobile experience enhancements; maybe PWA has more aspects, I'm not sure.
