### ISSUE TITLE
PC端播放器连接WebDav报错

### ISSUE THREAD

**Issue by liangrj914** [alist-org/alist#3233]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.2

### Driver used / 使用的存储驱动

GOM player plus和恒星播放器

### Describe the bug / 问题描述

使用播放器连接webdav报错，个人感觉跟/dav这个路径有关，因为恒星播放器我使用nginx代理后去掉/dav后连接正常，但是另外一个播放器不可以。所以请大佬看看。

### Reproduction / 复现链接

播放器地址：https://www.ghxi.com/gomplayer.html

### Logs / 日志

![image](https://user-images.githubusercontent.com/101916802/216342737-c7b5efc5-7c97-4eb7-8cfd-4a2027fa9eb8.png)

**Comment by liangrj914** [comment]
这个也支持啊，但是他连接失败呀。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Andy ***@***.***> |
| 日期 | 2023年02月02日 21:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alist-org/alist] PC端播放器连接WebDav报错 (Issue #3233) |

请使用支持webdav路径的播放器。

**Comment by Xhofe** [comment]
> 这个也支持啊，但是他连接失败呀。 | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Andy ***@***.***> | | 日期 | 2023年02月02日 21:55 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [alist-org/alist] PC端播放器连接WebDav报错 (Issue #3233) | 请使用支持webdav路径的播放器。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

那你应该找软件的开发者
