### ISSUE TITLE
webdav服务对文件目录未实现HTTP HEAD方法

### ISSUE THREAD

**Issue by karma-sun** [alist-org/alist#3236]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8

### Driver used / 使用的存储驱动

任意

### Describe the bug / 问题描述

webdav服务对文件目录未实现HTTP HEAD方法，造成部分客户端请求时报405错误，按照webdav协议HEAD方法应当被实现

### Reproduction / 复现链接

部署一个本地alist，然后
curl -I http://guest:guest@127.0.0.1:5244/dav/test/

**Comment by Xhofe** [comment]
> The semantics of GET are unchanged when applied to a collection, since GET is defined as, "retrieve whatever information (in the form of an entity) is identified by the Request-URI" [[RFC2616]](http://www.webdav.org/specs/rfc4918.html#RFC2616). GET, when applied to a collection, may return the contents of an "index.html" resource, a human-readable view of the contents of the collection, or something else altogether. Hence, it is possible that the result of a GET on a collection will bear no correlation to the membership of the collection.

> 
> Similarly, since the definition of HEAD is a GET without a response message body, the semantics of HEAD are unmodified when applied to collection resources.

This suggests that HEAD should only be supported on a resource if GET is supported.

Many servers won't implement GET on folders, so it would be reasonable to not implement HEAD. Our WebDav server doesn't support Get method for folder, so to me this sounds like a client-side bug.

Clients should instead do OPTIONS for capability discovery.
