### ISSUE TITLE
默认强制设置密码需求(发现隐私泄露问题)

### ISSUE THREAD

**Issue by UoUoio** [alist-org/alist#3241]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用网站  https://www.zoomeye.org/
搜索:title:"alist" +country:"CN"
会发现泄露了大量含有隐私内容的网盘,
强制设置密码1. 有助于作者规避相关法律风险,开源不易,2.有效防止小白的隐私内容遭到泄露

### Suggested solution / 实现思路

在安装部署时强制用户设置访问密码或随机生成访问密码

**Comment by BoYanZh** [comment]
这不是搜到的都是公开分享的alist么

**Comment by UoUoio** [comment]
> 这不是搜到的都是公开分享的alist么

是的，但是现在很多人在利用这个方式下载小白的网盘内容。其中有很多是私人照片、有一定的安全隐患，希望作者评估一下，是否有必要增加默认密码功能、
