### ISSUE TITLE
仅作展示的路径合并(内容聚合)

### ISSUE THREAD

**Issue by xsdcz** [alist-org/alist#3248]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望可以有一个路径合并的功能。
例： 
云盘账号1、云盘账号2 里面均有电影这个文件夹，但内容未必重合。
现在似乎只能分别挂载到两个不同的路径上（云盘1/电影  ，云盘2/电影）或者（电影\云盘1，电影\云盘2）。
可不可以提供一个聚合的文件夹 （电影）里面可以同时包含云盘1和云盘2的内容。

### Suggested solution / 实现思路

可以在“元信息 ”或者 “存储”里面添加一个聚合文件夹选项。
聚合文件夹作为只读目录，不可对文件夹进行修改。
在聚合文件夹内可以添加多个现有盘的路径地址，功能上，仅仅是作为路径转发，对现有功能基本不做修改。
展示时文件夹内容可以选择 
1、同名合并：参考负载均衡的思路。 
2、同名优先：自定义某个盘内容优先，比如某个盘速度更快，如果这个盘内有资源就默认选择这个盘内容。
3、自动前缀：为资源添加盘名前缀，如 “盘1泰坦尼克号 ，盘2泰坦尼克号” 。

**Comment by Bris4e** [comment]
这个功能类似于rclone的[union](https://rclone.org/union/)，我也挺想alist能够实现这个功能，这样就不必先把union挂载到服务器，再在alist上挂载了。
