### ISSUE TITLE
手动安装输入./alist server后提示-ash: ./alist: not found 如何解决？

### ISSUE THREAD

**Issue by cjyy46** [alist-org/alist#3249]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

1.Linux arm64平台，一键安装后`curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s install`，提示`出错了，无法确定你当前的 Linux 发行版。建议手动安装：https://alist.nn.ci`，然后改手动装。

2.按照手动安装教程，到了第三步输入`./alist server`后 提示`-ash: ./alist: not found` 请问如何解决？

**Comment by 1476523** [comment]
你這是開錯Labels吧...

**Comment by yzqiang666** [comment]
没有下载对应平台的版本。如linux试一试musl平台的版本。
