### ISSUE TITLE
建议文件预览能识别双后缀扩展名

### ISSUE THREAD

**Issue by Febtw** [alist-org/alist#3254]
### Please make sure of the following things

* [x]  I have read the [documentation](https://alist.nn.ci).
* [x]  I'm sure there are no duplicate issues or discussions.
* [x]  I'm sure this feature is not implemented.
* [x]  I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我有一些文件是zip打包的3d文件，可以用[3dviewer](https://3dviewer.net/)预览#2788，但并不是所有的zip文件都可以用3dviewer进行预览的，因此想通过双后缀扩展名进行区分。但在预览中添加双后缀扩展名并不能被识别。

### Suggested solution / 实现思路

预览的配置中增加双后缀扩展名的配置项，或者程序自动区分单、双后缀扩展名。然后文件的与预览预设的单、双后缀扩展名分别匹配。

**Comment by anwen-anyi** [comment]
没问题啊,可以的啊~
```
{
	"doc,docx,xls,xlsx,ppt,pptx": {
		"Microsoft":"https://view.officeapps.live.com/op/view.aspx?src=$e_url",
		"Google":"https://docs.google.com/gview?url=$e_url&embedded=true"
	},
	"pdf": {
		"PDF.js":"https://cdn.xxxxxxxxx.com/pdf.js-2.16.105/web/viewer.html?file=$e_url"
	},
	"epub": {
		"EPUB.js":"/static/epub.js/viewer.html?url=$e_url"
	},
	"glb,zip": {
                "3dviewer": "https://3dviewer.net/#model=$durl"
	}
}
```
![OK](https://i.wpic.cc/g/2023/03/15/6411c4619ff3d.png)

**Comment by Febtw** [comment]
> 没问题的,可以预览的吖~
> 
> ```
> {
> 	"doc,docx,xls,xlsx,ppt,pptx": {
> 		"Microsoft":"https://view.officeapps.live.com/op/view.aspx?src=$e_url",
> 		"Google":"https://docs.google.com/gview?url=$e_url&embedded=true"
> 	},
> 	"pdf": {
> 		"PDF.js":"https://cdn.xxxxxxxxx.com/pdf.js-2.16.105/web/viewer.html?file=$e_url"
> 	},
> 	"epub": {
> 		"EPUB.js":"/static/epub.js/viewer.html?url=$e_url"
> 	},
> 	"glb,zip": {
>                 "3dviewer": "https://3dviewer.net/#model=$durl"
> 	}
> }
> ```
> 
> ![OK](https://camo.githubusercontent.com/e033e017e78c9a548999723031b2e9b562d1b5b80d8cf8f2435ea6d42f3311b8/68747470733a2f2f692e777069632e63632f672f323032332f30332f31352f363431316334363139666633642e706e67)

你似乎误解了，以3dviewer预览zip为例，我没有否定能预览，但是我不希望所有的zip都被预览，也没必要
