### ISSUE TITLE
手动安装报错-ash: ./alist: not found

### ISSUE THREAD

**Issue by cjyy46** [alist-org/alist#3256]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.9.2

### Driver used / 使用的存储驱动

Aliyun

### Describe the bug / 问题描述

1.Linux arm64平台，一键安装后`curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s install`，提示`出错了，无法确定你当前的 Linux 发行版。建议手动安装：https://alist.nn.ci`，然后改手动装。

2.按照手动安装教程，到了第三步输入`./alist server`后 提示`-ash: ./alist: not found` ，换路径也试过问题依旧，谷歌也搜不到答案，也问过程序员朋友都没解决，求解决方案。

### Reproduction / 复现链接

官方手动安装链接：
https://alist.nn.ci/zh/guide/install/manual.html

### Logs / 日志

![微信图片_20230204190806](https://user-images.githubusercontent.com/25416040/216763976-2a3207ee-4306-4d5d-a58c-5cdcc376b883.png)

**Comment by ayanami-desu** [comment]
![image](https://user-images.githubusercontent.com/105108444/216764196-b234b6e9-e988-48ae-adf3-f439850d8581.png)
ui'ys使用更新脚本提示如上

**Comment by Xhofe** [comment]
你可以尝试使用 arm64-musl版本，若仍不可用，则可能是交叉编译的兼容性问题，请自行在宿主机编译

**Comment by CCKNBC** [comment]
![image](https://user-images.githubusercontent.com/62093618/216765370-60ef1671-fffd-4b85-8b08-004fe624c8cb.png)
