### ISSUE TITLE
谷歌硬盘授权报错

### ISSUE THREAD

**Issue by chunzhimoe** [alist-org/alist#3259]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.2

### Driver used / 使用的存储驱动

google drive

### Describe the bug / 问题描述

google drive无法授权

### Reproduction / 复现链接

使用工具授权谷歌云盘时报错
https://accounts.google.com/signin/oauth/error/v2?authError=Cg9pbnZhbGlkX3JlcXVlc3QS3gEK5oKo5peg5rOV55m75b2V5q2k5bqU55So77yM5Zug5Li65a6D5LiN56ym5ZCIIEdvb2dsZSDkuLrkv53pmpzlupTnlKjlronlhajogIzliLblrprnmoQgT0F1dGggMi4wIOaUv-etlueahOinhOWumuOAggoK5oKo5Y-v5Lul6YCa55-l5bqU55So5byA5Y-R6ICF77yM6K6p5YW25LqG6Kej6K-l5bqU55So5LiN56ym5ZCI5LiA6aG55oiW5aSa6aG5IEdvb2dsZSDpqozor4Hop4TliJnjgIIKICAaM2h0dHBzOi8vc3VwcG9ydC5nb29nbGUuY29tL2FjY291bnRzL2Fuc3dlci8xMjM3OTM4NCCQAyopCgxyZWRpcmVjdF91cmkSGXVybjppZXRmOndnOm9hdXRoOjIuMDpvb2IyowIIARLNAVRoZSBvdXQtb2YtYmFuZCAoT09CKSBmbG93IGhhcyBiZWVuIGJsb2NrZWQgaW4gb3JkZXIgdG8ga2VlcCB1c2VycyBzZWN1cmUuIEZvbGxvdyB0aGUgT3V0LW9mLUJhbmQgKE9PQikgZmxvdyBtaWdyYXRpb24gZ3VpZGUgbGlua2VkIGluIHRoZSBkZXZlbG9wZXIgZG9jcyBiZWxvdyB0byBtaWdyYXRlIHlvdXIgYXBwIHRvIGFuIGFsdGVybmF0aXZlIG1ldGhvZC4aT2h0dHBzOi8vZGV2ZWxvcGVycy5nb29nbGUuY29tL2lkZW50aXR5L3Byb3RvY29scy9vYXV0aDIvcmVzb3VyY2VzL29vYi1taWdyYXRpb24%3D&client_id=202264815644.apps.googleusercontent.com

### Logs / 日志

![image](https://user-images.githubusercontent.com/60135925/216770608-126beed9-8432-4fc1-b41b-faaad56f05a7.png)

**Comment by chunzhimoe** [comment]
这篇文档可能会有帮助，希望大佬修复！大佬辛苦了
https://developers.google.com/identity/protocols/oauth2/resources/oob-migration?hl=zh-cn#what-is-oob

**Comment by eattrenclenhard** [comment]
You may deploy your own app from my [repository ](https://github.com/eattrenclenhard/Sho-Time/) to generate access token to Google Token if you prefer your own client credentials over any public's client id-secret pair and have security concerns over public access token generator.

[preview URL](https://shotime.streamlit.app)
![Image](https://github.com/user-attachments/assets/c9553f02-9683-4460-a7c7-87821f2ec845)
