### ISSUE TITLE
Alist挂载中的索引问题

### ISSUE THREAD

**Issue by ErDongChen1973** [alist-org/alist#3260]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望支持在挂载别人的alist后，能继续使用原alist中提供的索引功能。目前的问题是将别人的alist挂载到自己alist后，似乎原有的搜索会被本地的搜索覆盖，如果自己再重新建立索引就太复杂了。

**Comment by BoYanZh** [comment]
我猜你想要的是用别人的搜索结果，直接拿别人的索引数据塞你数据库来又大又不安全还没法同步

**Comment by ErDongChen1973** [comment]
> 我猜你想要的是用别人的搜索结果，直接拿别人的索引数据塞你数据库来又大又不安全还没法同步

我就想能直接用别人搜索框，不需要添加到我自己的索引数据库中

**Comment by wudiming** [comment]
挂在上不能用，搜索框还占地方，搞成能直接用就好了

**Comment by WPF0414** [comment]
自己建立索引好大啊，搜索起来比较慢。如果能直接使用别人的当然是最好的了

**Comment by xuegao456** [comment]
我是直接导入别人的数据库，比如小雅，就是比较慢。
如果想直接调用别人的搜索API，我猜想可以用反向代理实现，就是转发HTTP请求到别人的alist上去
