### ISSUE TITLE
能不能支持挂载telegram（

### ISSUE THREAD

**Issue by nimade2333** [alist-org/alist#3261]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如标题

### Suggested solution / 实现思路

我是笨蛋😭

**Comment by BoYanZh** [comment]
曾经考虑过，但是在不在db中缓存的情况下列出所有文件太慢
也许需要先套一层 https://teledriveapp.com/ 再挂载这个
