### ISSUE TITLE
能否支持阿里云盘的【相册】访问和管理？目前仅可以访问管理【文件】类型。

### ISSUE THREAD

**Issue by hsxnet** [alist-org/alist#3262]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否支持阿里云盘的【相册】访问和管理？目前仅可以访问管理【文件】类型。
从阿里云盘的桌面客户端"D:\Program Files\Aliyunpan\aDrive\aDrive.exe"，是可以访问【相册】的。

另外，通过文件夹对比工具BCompare，把本机硬盘上的文件，上传至阿里云盘上的相同目录下，为何在阿里云盘的回收站里有自动删除的同名文件，且文件大小是0K？要手工在阿里云盘APP或者桌面客户端里手工删除。
是不是这个原因，影响了上传速度？
上传好慢好慢啊。
谢谢老大的软件！！

### Suggested solution / 实现思路

把阿里云盘的【相册】也加入访问和管理。

### Additional context / 附件

无

**Comment by hsxnet** [comment]
关于通过【复制】本地电脑目录文件，在RaiDrive列举中的远程阿里云目录【粘贴】的方式。还是通过文件夹对比工具BCompare，把本机硬盘上的文件，上传至阿里云盘上的相同目录下，速度都奇慢！
我有2000个图片，昨晚电脑开一夜，才上传成功800多个。
现在在阿里云盘的桌面客户端里操作上传，1分钟搞定。
希望AList也能这么快！

**Comment by anwen-anyi** [comment]
首先你要先知道 Alist上传是怎么运作的QAQ.......

**Comment by leic4u** [comment]
+1，阿里云盘的相册和文件不互通，想管理起来太麻烦了

**Comment by hyw520sj** [comment]
顶上去让，有需求的请评论

**Comment by DemonGao** [comment]
同意，望支持

**Comment by BurningUDream** [comment]
顶顶

**Comment by SouperGeng** [comment]
同意，望支持

**Comment by SouperGeng** [comment]
同意，望支持

**Comment by vveijue** [comment]
同意，望支持

**Comment by deardeer7** [comment]
希望支持一下啊作者大大，手机备份相册到了阿里云盘，alist挂载到电脑却看不到相册

**Comment by samhelper** [comment]
+1，特意登陆进来支持这个建议

**Comment by KaiWenRui** [comment]
估计这个需求得等阿里开放api，我看目前开放了album:shared:read
