### ISSUE TITLE
对于web管理页面和web文件列表页面的几个建议

### ISSUE THREAD

**Issue by fengchen-github** [alist-org/alist#3263]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

AList管理页面：
“个人资料”菜单能否理解成管理员修改密码相关，是否可以整合进“用户”菜单；
将”设置“-”站点“-版本，放置在管理页左下角（菜单列下方），直接显示版本号；
“存储”重命名为“挂载管理”
“主页“重命名为”文件列表“，将按钮放在页面顶部

文件列表页面（主页）：
右上角添加当前登陆用户显示，添加注销按钮，将”管理“按钮”移至此处（只有管理员显示）

**Comment by sunny-00001** [comment]
最好画个示意图直观一点，这样更容易让开发者理解

**Comment by V-arc** [comment]
第一个，非admin的管理面板没有“用户”选项。而且也可能是为了后续的功能拓展做铺垫。
其他几个支持👍

**Comment by fengchen-github** [comment]
> 最好画个示意图直观一点，这样更容易让开发者理解

我也不是专业的，权当抛砖引玉吧😊

**Comment by wpq111** [comment]
支持

**Comment by drw2005** [comment]
支持
