### ISSUE TITLE
对无扩展名的文件的右键菜单添加“用xx方式打开”

### ISSUE THREAD

**Issue by 2ej2o** [alist-org/alist#3265]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

版本 3.10.1
一些文件（如文本文件）没有后缀需要手动改名加后缀才能用网页编辑

### Suggested solution / 实现思路

对于无扩展名的文件右键菜单添加"用xx方式打开"

**Comment by Febtw** [comment]
可以对无扩展名文件进行预览。
“预览"中各类文件扩展名列表下每一项是用逗号,隔开的，因此可用`,a,b`或`a,,b`或`a,b,`格式添加无扩展名的预览。
根据你的需要，在文本类型中进行添加，将无扩展名文件都识别为文本类型
