### ISSUE TITLE
Linux arm64手动安装无法守护进程

### ISSUE THREAD

**Issue by cjyy46** [alist-org/alist#3266]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.10.1

### Driver used / 使用的存储驱动

Aliyun

### Describe the bug / 问题描述

1.Linux arm64 openwrt平台按官方教程手动安装，`./alist server`后显示正常，可访问web页面；
2.然后到守护进程这里，`/usr/lib/systemd/system/alist.service` ，用WinSCP找不到其中的`/systemd/system`这个路径及`alist.service`文件；
3.本人Linux小白，请问应该如何操作能顺利守护进程并保持开机自启动？麻烦尽量说得详细一些，多谢各位！

### Reproduction / 复现链接

https://alist.nn.ci/zh/guide/install/manual.html#%E5%AE%88%E6%8A%A4%E8%BF%9B%E7%A8%8B

**Comment by lj2333** [comment]
我有相同的问题，请问你解决了吗？

**Comment by chiming123** [comment]
> 我有相同的问题，请问您解决了吗？

不知道你有没有解决，如果没有alist.service文件自建一个即可，而且有教程视频，请认真观看一下
