### ISSUE TITLE
希望添加一个文件直链挂载

### ISSUE THREAD

**Issue by MoeCinnamo** [alist-org/alist#3268]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望添加一个文件直链挂载功能

比如，我有一张图片是 https://file.mojy.xyz/files/fileshare/music.webp ，我希望在不添加任何网盘的情况下挂载它。

### Suggested solution / 实现思路

添加一个新的存储驱动，可实现增加文件直链的效果

**Comment by mengguyi** [comment]
大概是在存储里添加一个HTTP链接存储，一个路径一个链接，可以302重定向或者代理

**Comment by MoeCinnamo** [comment]
> 大概是在存储里添加一个HTTP链接存储，一个路径一个链接，可以302重定向或者代理

是這樣

**Comment by mengguyi** [comment]
那就别光有HTTP链接了，FTP，SFTP也弄上吧

**Comment by phoon** [comment]
> 大概是在存储里添加一个HTTP链接存储，一个路径一个链接，可以302重定向或者代理

可能还得处理referer

**Comment by phoon** [comment]
> 大概是在存储里添加一个HTTP链接存储，一个路径一个链接，可以302重定向或者代理

可能还得处理referer

**Comment by SENyiAi** [comment]
不错的主意

**Comment by MoeCinnamo** [comment]
> 那就别光有HTTP链接了，FTP，SFTP也弄上吧

默認它是支援FTP，SFTP的
但是沒有HTTP連接
所以這個請求很合理

**Comment by MoeCinnamo** [comment]
> > 大概是在存储里添加一个HTTP链接存储，一个路径一个链接，可以302重定向或者代理
> 
> 可能还得处理referer

有幾種，比如通過FTP、SFTP、SMB等方式上載，或者通過API上載到GitHub倉庫，以及手動添加連結這幾種方法
我覺得應該是可行的

**Comment by MoeCinnamo** [comment]
> 不错的主意

因為，它導致了我出現了一些困擾

**Comment by MoeCinnamo** [comment]
> 修改drivers中local目录下文件很容易实现，已使用几个月了。对后缀名为strm的文件读取内容作为下载链接返回，同时修改目录显示的函数。基本上只需修改Link和List或Get函数。

我覺得，不應該修改這麼多
通過一建為目錄添加HTTP連結方式會更好一些
就像，永碩盤一樣

**Comment by maxadc** [comment]
在这个地址上增加一个需求，可不可以不是一个输入框，而是指定硬盘上的一个文件。这样便于修改。比如第三方工具自动增删改查
