### ISSUE TITLE
希望增加移动复制等操作的进度条展示

### ISSUE THREAD

**Issue by mapleafgo** [alist-org/alist#3272]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在移动复制文件的时候，无法判断是否操作完成。当前展示效果是操作立即提示成功，但无法知道是否完成。到目的文件夹查看文件未出现还以为未操作成功，导致有可能重复操作

**Comment by mapleafgo** [comment]
@Xhofe 可以说明下，为何无效吗？这个问题确实有点降低体验感呢

**Comment by mapleafgo** [comment]
我注意到在管理界面看得到复制的记录和进度，但在操作复制的主界面无法看到

**Comment by enochayy** [comment]
> 我注意到在管理界面看得到复制的记录和进度，但在操作复制的主界面无法看到

感谢，没看到你我都不知道这里能看。
