### ISSUE TITLE
又拍云存储挂载进不去

### ISSUE THREAD

**Issue by In2013** [alist-org/alist#3278]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0-1

### Driver used / 使用的存储驱动

又拍云存储

### Describe the bug / 问题描述

根文件夹路径 /
存储桶
Endpoint
操作员名称
操作员密码

Alist是软路由固件bleach plus 20230109 @ OpenWrt R23.1.1里的，这几项都填写正确了，访问时一直转圈进不去，尝试过根文件夹路径为.或者..或者存储桶的名称，也不行，设置为..时，会有提示存储桶名称不对，自定义HOST这一项为空，另外，用FTP方式可以正常挂载

### Reproduction / 复现链接

http://192.168.123.123:5244

### Logs / 日志

[GIN] 2023/02/06 - 19:22:07 | 200 |   19.225372ms |   192.168.123.5 | POST     "/api/admin/storage/disable?id=4"
[GIN] 2023/02/06 - 19:22:07 | 200 |     1.59401ms |   192.168.123.5 | GET      "/api/admin/storage/list"
[GIN] 2023/02/06 - 19:22:26 | 200 |   72.015778ms |   192.168.123.5 | POST     "/api/admin/storage/enable?id=4"
[GIN] 2023/02/06 - 19:22:26 | 200 |     1.59061ms |   192.168.123.5 | GET      "/api/admin/storage/list"
[GIN] 2023/02/06 - 19:22:26 | 200 |     802.609µs |   192.168.123.5 | GET      "/api/admin/storage/get?id=4"
[GIN] 2023/02/06 - 19:22:26 | 200 |     214.498µs |   192.168.123.5 | GET      "/api/admin/driver/info?driver=USS"
[GIN] 2023/02/06 - 19:23:00 | 200 |     170.261µs |   192.168.123.5 | GET      "/"
[GIN] 2023/02/06 - 19:23:00 | 200 |     154.897µs |   192.168.123.5 | GET      "/api/public/settings"
[GIN] 2023/02/06 - 19:23:00 | 200 |      67.762µs |   192.168.123.5 | GET      "/api/me"
[GIN] 2023/02/06 - 19:23:01 | 200 |     303.265µs |   192.168.123.5 | POST     "/api/fs/get"
[GIN] 2023/02/06 - 19:23:01 | 200 |     564.141µs |   192.168.123.5 | POST     "/api/fs/list"

**Comment by wangwuxuan2011** [comment]
麻烦先尝试用一下最新版本～
