### ISSUE TITLE
PDF Failed to Fetch

### ISSUE THREAD

**Issue by fame-odoo** [alist-org/alist#3280]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.10.1

### Driver used / 使用的存储驱动

Google Drive

### Describe the bug / 问题描述

Cannot preview the pdf file correctly, always display 

```bash
PDF.js v3.0.44 (build: 6852001b0)
Message: Failed to fetch
```

### Reproduction / 复现链接

https://mfy.gd/temp/testpdf.pdf

### Logs / 日志

<img width="936" alt="image" src="https://user-images.githubusercontent.com/107050396/217013059-be08d250-9238-4516-93f7-14a0db96cb80.png">

**Comment by Xhofe** [comment]
You need to pass `X-Forwarded-Proto` header on reverse proxy or set [site_url](https://alist.nn.ci/config/configuration.html#site-url)
