### ISSUE TITLE
希望增加前端批量导出 M3U8 播放列表功能

### ISSUE THREAD

**Issue by Yefori-Go** [alist-org/alist#3282]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加前端批量导出 M3U8 播放列表，自动导出选择的视频。 

### Suggested solution / 实现思路

M3U8 播放列表本质上是具有格式的纯文本文件。前端目前可以批量复制链接，加以改进便可以导出为 M3U8 格式

**Comment by Yefori-Go** [comment]
hello？

**Comment by ywzhaiqi** [comment]
> hello？

自己简单尝试了下 播放列表。https://github.com/ywzhaiqi/alist-web/commit/91c15086439371f41ace5867b3ed0ec4a993d30e
