### ISSUE TITLE
希望增加日志写入 ELK 的功能

### ISSUE THREAD

**Issue by LisonFan** [alist-org/alist#3284]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

把日志写入 ELK 方便查看

**Comment by JsonSong89** [comment]
这需求有点离谱,关别人应用方什么事?
你自己用logstash或filebeat取日志不就行了?
