### ISSUE TITLE
挂载Alist V3，链接临时失效的问题

### ISSUE THREAD

**Issue by koolca** [alist-org/alist#3287]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

某些Alist站点，偶尔失效，如果挂载后通过webdav访问，可以导致假死，能否直接返回空内容，而不是反复尝试连接
2023/02/07 08:56:31.702049 ERROR RESTY Post "https://pan.*.net/api/fs/list": dial tcp *:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond., Attempt 1
2023/02/07 08:56:52.876796 ERROR RESTY Post "https://pan.*.net/api/fs/list": dial tcp *:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond., Attempt 2
2023/02/07 08:57:14.048442 ERROR RESTY Post "https://pan.*.net/api/fs/list": dial tcp *:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond., Attempt 3
2023/02/07 08:57:35.317943 ERROR RESTY Post "https://pan.*.net/api/fs/list": dial tcp *:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond., Attempt 4

**Comment by Xhofe** [comment]
默认重试三次没有什么不合理 链接失效这应该是用户处理的

**Comment by koolca** [comment]
> 默认重试三次没有什么不合理 链接失效这应该是用户处理的

了解了，谢谢，有没有API方面的介绍，可以通过脚本临时禁用部分失效的挂载点
