### ISSUE TITLE
利用nginx反代，开启多个alist实例，连接同一个数据库配置，可以实现访问的负载均衡吗？

### ISSUE THREAD

**Issue by youyifentian** [alist-org/alist#3293]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

因为现在服务器上面一个alist实例挂载了很多网盘，访问起来有时候会有卡顿，因为用的是nginx的反代，配置的是mysql的数据库，现在想通过不同的端口，开启多个alist实例，连接的是同一个alist数据库，然后通过nginx反代实现负载均衡，因为现在数据比较多，我怕弄错了，自己没有尝试，想先来咨询一下，这样会不会导致数据相互覆盖出现什么问题啊，希望能有空解答一下，非常感谢

**Comment by shadowofgost** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure this feature is not implemented.
> * [x]  I'm sure it's a reasonable and popular requirement.
> 
> ### Description of the feature / 需求描述
> 因为现在服务器上面一个alist实例挂载了很多网盘，访问起来有时候会有卡顿，因为用的是nginx的反代，配置的是mysql的数据库，现在想通过不同的端口，开启多个alist实例，连接的是同一个alist数据库，然后通过nginx反代实现负载均衡，因为现在数据比较多，我怕弄错了，自己没有尝试，想先来咨询一下，这样会不会导致数据相互覆盖出现什么问题啊，希望能有空解答一下，非常感谢
> 
> ### Suggested solution / 实现思路
> _No response_
> 
> ### Additional context / 附件
> _No response_

会存在数据一致性问题，应该会导致你看到的数据和实际数据有误差，不过个人认为可以忽略不记，可以这样去做我是这样想的

**Comment by ZRHann** [comment]
@youyifentian 请问你部署过了吗，有没有遇到什么问题
