### ISSUE TITLE
增加TeraCLOUD网盘

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [alist-org/alist#3294]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

网站https://teracloud.jp/en/
分享链接测试：https://toi.teracloud.jp/share/11c1dcecd42a27b5
国内速度很快，有免费额度。

**Comment by xpremix** [comment]
你webdav挂载就可以了
