### ISSUE TITLE
文件挂载的阿里云盘，用微信内置浏览器打开pdf预览，使用pdf.js的方式，无法加载pdf文档

### ISSUE THREAD

**Issue by ClockworkChen** [alist-org/alist#3300]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.9.1

### Driver used / 使用的存储驱动

aliyundrive

### Describe the bug / 问题描述

文件挂载的阿里云盘，用微信内置浏览器打开pdf预览，使用pdf.js的方式，无法加载pdf文档

### Reproduction / 复现链接

下载链接会失效，可以用任意阿里云存储pdf文档进行测试。

### Logs / 日志

无错误日志。

**Comment by Xhofe** [comment]
找微信反馈它们的内核版本太低了
