### ISSUE TITLE
MarkDown 预览问题

### ISSUE THREAD

**Issue by yiguanxianyu** [alist-org/alist#3304]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.10.1

### Driver used / 使用的存储驱动

对象存储

### Describe the bug / 问题描述

我分别用对象存储以S3模式挂载了Backblaze和Scaleway，其中Backblaze添加了自定义HOST（格式类似：[https://cdn.custom.host]()）。在使用过程中发现，当使用自定义HOST时，B2的markdown文件无法正常预览，原因是请求的地址队后多了一个'\\'字符。切换成下载链接下载的时候是正常的。
<img width="972" alt="截屏2023-02-08 01 04 38" src="https://user-images.githubusercontent.com/11457822/217314367-dee984d8-4093-40f1-962f-a62537df1b0d.png">
与此同时，图片和视频的预览经测试是正常的。当关闭自定义HOST后MarkDown也可以正常预览了。但是，在没有
使用自定义HOST的情况下，Scaleway的对象存储同样出现了预览问题，并且目测也是因为链接最后多了一个'\\'
<img width="975" alt="截屏2023-02-08 01 09 41" src="https://user-images.githubusercontent.com/11457822/217315286-245ed4a7-5bce-4995-a586-2f4824aaceb9.png">

(补充：这种情况下似乎移动文件也会失败)

### Reproduction / 复现链接

按照问题描述操作可以复现，预览可以看 [这里](https://disk.yiguanxianyu.live)

### Logs / 日志

{"code":500,"message":"Get "https://cdn.custom.host/Mermaid%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E5%85%A5%E5%9C%9F.md\": http2: invalid Connection request header: ["upgrade"]","data":null}

{"code":500,"message":"Get "https://random-bucket.s3.nl-ams.scw.cloud/Mac%E5%BA%94%E7%94%A8.md?X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Credential=SCWEZ467M03V9EC5F892%2F20230207%2Fnl-ams%2Fs3%2Faws4_request\u0026X-Amz-Date=20230207T171244Z\u0026X-Amz-Expires=14400\u0026X-Amz-SignedHeaders=host\u0026response-content-disposition=attachment%3Bfilename%3D%22Mac%25E5%25BA%2594%25E7%2594%25A8.md%22\u0026X-Amz-Signature=c1c369e146c7ec9761643d8a046a37bd81d8a867a768aaf6e971d26bd7a840e0\": http2: invalid Connection request header: ["upgrade"]","data":null}

**Comment by Yefori-Go** [comment]
你指的是单引号还是双引号？

**Comment by yiguanxianyu** [comment]
> 你指的是单引号还是双引号？

抱歉抱歉，我忘了一个\\是转义符号，我指的是反斜杠\\。你看错误输出里链接的最后一个字符就好

**Comment by Xhofe** [comment]
这应该是你的反向代理配置有问题

反向代理：https://disk.yiguanxianyu.live/p/Scaleway/test/Mermaid%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E5%85%A5%E5%9C%9F.md?sign=MgSaUWQYrWzMjRiaZFX9z51pSUNJUlCh21EifK9tJJw=:0
未反向代理：http://disk.yiguanxianyu.live:5244/p/Scaleway/test/Mermaid%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E5%85%A5%E5%9C%9F.md?sign=MgSaUWQYrWzMjRiaZFX9z51pSUNJUlCh21EifK9tJJw=:0
