### ISSUE TITLE
跪求适配arm架构的windows

### ISSUE THREAD

**Issue by xiaohei1124** [alist-org/alist#3308]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题 现在arm架构的轻薄本是大势所趋 建议适配（关键是我买了用不了很难受 哈哈）

**Comment by Xhofe** [comment]
我尝试了使用交叉编译，但是得到了错误：
```bash
# runtime/cgo
/usr/local/bin/aarch64-w64-mingw32-gcc: 99: /usr/local/bin/clang: Exec format error
```
所以当前无法直接提供二进制prebuilt，欢迎熟悉交叉编译的人提供修复。

但是你可以：
- 直接在目标机器上自行编译
- 使用Docker

**Comment by mengguyi** [comment]
> 

直接在aarch64的Linux上编译呢

**Comment by mengguyi** [comment]
我编译了一个arm64的alist，可以试试
[alist.7z把扩展名改成7z.zip](https://github.com/alist-org/alist/files/10687124/alist.7z.7z.zip)

**Comment by mengguyi** [comment]
记录一下我的编译过程

```
docker run -i -t ubuntu:22.04 /bin/bash
apt update && apt upgrade
apt install golang #此处发现Ubuntu22.04的golang是1.18
apt install wget curl git
wget https://golang.google.cn/dl/go1.19.5.linux-arm64.tar.gz
tar -C /usr/local -xzf go1.19.5.linux-arm64.tar.gz
export PATH=$PATH:/usr/local/go/bin
go version #输出 go version go1.19.5 linux/arm64
go env -w GOPROXY=https://goproxy.io,direct
go install github.com/crazy-max/xgo@latest
git clone https://github.com/alist-org/alist.git
cd alist
git clone --recursive https://ghproxy.com/github.com/alist-org/alist-web.git
cd alist-web/public
mv * /alist/alist-web/dist/
cd /alist
export GOOS=windows
export GOARCH=arm64
go build -o "$1" -ldflags="$ldflags" -tags=jsoniter .
```

**Comment by xiaohei1124** [comment]
> 我编译了一个arm64的alist，可以试试 [alist.7z把扩展名改成7z.zip](https://github.com/alist-org/alist/files/10687124/alist.7z.7z.zip)

**failed to connect database:Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub** 
运行不了，log记载如上

**Comment by Xhofe** [comment]
我尝试使用zig作为c交叉编译器编译了一份，你可以尝试一下是否可用：
[alist-windows-arm64.zip](https://github.com/alist-org/alist/files/10696023/alist-windows-arm64.zip)
如果可用的话，之后可用尝试继承到GitHub actions中。

**Comment by xiaohei1124** [comment]
> 我尝试使用zig作为c交叉编译器编译了一份，你可以尝试一下是否可用： [alist-windows-arm64.zip](https://github.com/alist-org/alist/files/10696023/alist-windows-arm64.zip) 如果可用的话，之后可用尝试继承到GitHub actions中。
可以运行了 但是potplayer连接不上alist的webdav功能 log中有一段报错如下

[31mERRO[0m[2023-02-09 18:30:23] failed list /: can't find storage with rawPath: /
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/home/xhf/Downloads/alist-main/internal/op/path.go:18
github.com/alist-org/alist/v3/internal/fs.list
	/home/xhf/Downloads/alist-main/internal/fs/list.go:18
github.com/alist-org/alist/v3/internal/fs.List
	/home/xhf/Downloads/alist-main/internal/fs/fs.go:17
github.com/alist-org/alist/v3/server/handles.FsGet
	/home/xhf/Downloads/alist-main/server/handles/fsread.go:291
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/xhf/Downloads/alist-main/server/middlewares/auth.go:65
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/xhf/Downloads/alist-main/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1995
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1172
failed get storage 
[GIN] 2023/02/09 - 18:30:23 | 200 |            0s |       127.0.0.1 | POST     "/api/fs/get"
[31mERRO[0m[2023-02-09 18:30:23] failed list /: can't find storage with rawPath: /
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/home/xhf/Downloads/alist-main/internal/op/path.go:18
github.com/alist-org/alist/v3/internal/fs.list
	/home/xhf/Downloads/alist-main/internal/fs/list.go:18
github.com/alist-org/alist/v3/internal/fs.List
	/home/xhf/Downloads/alist-main/internal/fs/fs.go:17
github.com/alist-org/alist/v3/server/handles.FsList
	/home/xhf/Downloads/alist-main/server/handles/fsread.go:80
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/xhf/Downloads/alist-main/server/middlewares/auth.go:65
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/xhf/Downloads/alist-main/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/xhf/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1995
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1172
failed get storage
