### ISSUE TITLE
禁用guest账户后无法使用github登陆

### ISSUE THREAD

**Issue by 12189108** [alist-org/alist#3314]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.10.1

### Driver used / 使用的存储驱动

任何

### Describe the bug / 问题描述

禁用guest账户后，点击按钮，显示如下
```
{"code":401,"message":"Guest user is disabled, login please","data":null}
```
也无法在管理界面绑定github账号

### Reproduction / 复现链接

*

**Comment by anwen-anyi** [comment]
未修改前将访客打开启用，然后在后台绑定都就可以使用了，
https://github.com/alist-org/alist/commit/43a8ed472b44ff3bde2515b848d4c897d11d246f 重新修改后 直接导致无法绑定 白屏也看不到什么相关日志...

以下为测试复现视频：
视频OK 为 V3.10.1，但v3.11.0经测试和v3.10.1方法一样

视频NO 为新的Action build构建的版本 https://github.com/alist-org/alist/actions/runs/4230606094

### video
**https://www.aliyundrive.com/s/1TzmNSbzd1U**


Dev build version
```bash
$ /c/Users/Administrator/Desktop/3.11.0/alist-windows-amd64-0.exe version
Built At: 2023-02-21 08:22:19 +0000
Go Version: go1.19.5 linux/amd64
Author: Xhofe <i@nn.ci>
Commit ID: fd36ce5
Version: dev
```

**Comment by Xhofe** [comment]
> 未修改前将访客打开启用，然后在后台绑定都就可以使用了， [43a8ed4](https://github.com/alist-org/alist/commit/43a8ed472b44ff3bde2515b848d4c897d11d246f) 重新修改后 直接导致无法绑定 白屏也看不到什么相关日志...
> 
> 以下为测试复现视频： 视频OK 为 V3.10.1，但v3.11.0经测试和v3.10.1方法一样
> 
> 视频NO 为新的Action build构建的版本 https://github.com/alist-org/alist/actions/runs/4230606094 即使将游客账号打开，然后去后台绑定依然是白屏...
> 
> ### video
> **https://www.aliyundrive.com/s/1TzmNSbzd1U**
> 
> Dev build version
> 
> ```shell
> $ /c/Users/Administrator/Desktop/3.11.0/alist-windows-amd64-0.exe version
> Built At: 2023-02-21 08:22:19 +0000
> Go Version: go1.19.5 linux/amd64
> Author: Xhofe <i@nn.ci>
> Commit ID: fd36ce5
> Version: dev
> ```

redirect_uri 不匹配。

**Comment by anwen-anyi** [comment]
> > 未修改前将访客打开启用，然后在后台绑定都就可以使用了， [43a8ed4](https://github.com/alist-org/alist/commit/43a8ed472b44ff3bde2515b848d4c897d11d246f) 重新修改后 直接导致无法绑定 白屏也看不到什么相关日志...
> > 以下为测试复现视频： 视频OK 为 V3.10.1，但v3.11.0经测试和v3.10.1方法一样
> > 视频NO 为新的Action build构建的版本 https://github.com/alist-org/alist/actions/runs/4230606094 即使将游客账号打开，然后去后台绑定依然是白屏...
> > ### video
> > **https://www.aliyundrive.com/s/1TzmNSbzd1U**
> > Dev build version
> > ```shell
> > $ /c/Users/Administrator/Desktop/3.11.0/alist-windows-amd64-0.exe version
> > Built At: 2023-02-21 08:22:19 +0000
> > Go Version: go1.19.5 linux/amd64
> > Author: Xhofe <i@nn.ci>
> > Commit ID: fd36ce5
> > Version: dev
> > ```
> 
> redirect_uri 不匹配。

最新版的有什么需要修改的吗？还是说 本地的不可以了？

**Comment by Xhofe** [comment]
> > > 未修改前将访客打开启用，然后在后台绑定都就可以使用了， [43a8ed4](https://github.com/alist-org/alist/commit/43a8ed472b44ff3bde2515b848d4c897d11d246f) 重新修改后 直接导致无法绑定 白屏也看不到什么相关日志...
> > > 以下为测试复现视频： 视频OK 为 V3.10.1，但v3.11.0经测试和v3.10.1方法一样
> > > 视频NO 为新的Action build构建的版本 https://github.com/alist-org/alist/actions/runs/4230606094 即使将游客账号打开，然后去后台绑定依然是白屏...
> > > ### video
> > > **https://www.aliyundrive.com/s/1TzmNSbzd1U**
> > > Dev build version
> > > ```shell
> > > $ /c/Users/Administrator/Desktop/3.11.0/alist-windows-amd64-0.exe version
> > > Built At: 2023-02-21 08:22:19 +0000
> > > Go Version: go1.19.5 linux/amd64
> > > Author: Xhofe <i@nn.ci>
> > > Commit ID: fd36ce5
> > > Version: dev
> > > ```
> > 
> > 
> > redirect_uri 不匹配。
> 
> 最新版的有什么需要修改的吗？似乎没看到哪里修改吖 QAQ 还是说 本地的不可以了？ 或者说一下 现在新版本的这个怎么填写 回调URL~

理论上不可能出现你这个情况  我无法复现。

**Comment by anwen-anyi** [comment]
> > > > 未修改前将访客打开启用，然后在后台绑定都就可以使用了， [43a8ed4](https://github.com/alist-org/alist/commit/43a8ed472b44ff3bde2515b848d4c897d11d246f) 重新修改后 直接导致无法绑定 白屏也看不到什么相关日志...
> > > > 以下为测试复现视频： 视频OK 为 V3.10.1，但v3.11.0经测试和v3.10.1方法一样
> > > > 视频NO 为新的Action build构建的版本 https://github.com/alist-org/alist/actions/runs/4230606094 即使将游客账号打开，然后去后台绑定依然是白屏...
> > > > ### video
> > > > **https://www.aliyundrive.com/s/1TzmNSbzd1U**
> > > > Dev build version
> > > > ```shell
> > > > $ /c/Users/Administrator/Desktop/3.11.0/alist-windows-amd64-0.exe version
> > > > Built At: 2023-02-21 08:22:19 +0000
> > > > Go Version: go1.19.5 linux/amd64
> > > > Author: Xhofe <i@nn.ci>
> > > > Commit ID: fd36ce5
> > > > Version: dev
> > > > ```
> > > 
> > > 
> > > redirect_uri 不匹配。
> > 
> > 
> > 最新版的有什么需要修改的吗？似乎没看到哪里修改吖 QAQ 还是说 本地的不可以了？ 或者说一下 现在新版本的这个怎么填写 回调URL~
> 
> 理论上不可能出现你这个情况 我无法复现。

可以提供远程复现..  但是呢...不用https://github.com/alist-org/alist/commit/43a8ed472b44ff3bde2515b848d4c897d11d246f  修改后的就没问题...

**Comment by Xhofe** [comment]
发我 todesk
