### ISSUE TITLE
希望可以选择禁止用户修改用户名

### ISSUE THREAD

**Issue by juruoyyx** [alist-org/alist#3320]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望可以选择禁止用户修改用户名。

目前所有用户都可以自行修改用户名，这样可能会导致用户名格式混乱，不方便管理，还存在可能冒充他人的情况。

**Comment by bsdayo** [comment]
这个功能有什么问题吗？两个相关的 issue 都被打上了 wontfix 的标签

我认为这是一个挺需要的功能，例如公开分享时防止偷改用户名导致管理混乱，或者冒充其他用户的行为

如果实在无法实现这个功能，可否说明一下原因？谢谢
