### ISSUE TITLE
希望增加显示容量功能

### ISSUE THREAD

**Issue by Eternal-Future** [alist-org/alist#3324]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增加网盘显示容量功能（剩余容量/总容量）
在对于一下仅支持登录一个客户端的网盘相对比较方便一点（比如115网盘，挂载alist之后再次登录客户端会掉线）
对于挂载多个网盘的人会让容量情况一目了然
不需要一个个开客户端查看容量
该功能可由管理员自行选择是否开启
对于挂载本地存储/FTP等不显示总容量的由管理员手动设置总容量

**Comment by BoYanZh** [comment]
我猜，无此计划，不过欢迎pr。

**Comment by Xhofe** [comment]
> 我猜，无此计划，不过欢迎pr。

yep

**Comment by pipinian** [comment]
rclone size remote:

**Comment by oyjcmyn** [comment]
我也非常希望 增加显示容量功能,就是把网盘当前总容量和剩余容量显示出来,当挂载多个网盘后,时间久点不知道哪个网盘还剩下多少空间,就不太好传文件,还得去一个个登陆到网盘里查看
