### ISSUE TITLE
隐藏文件需要密码

### ISSUE THREAD

**Issue by yuehun** [alist-org/alist#3328]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

不想battle，可否加一个开关设置，不然也太不方便了，害怕被猜出来的文件就直接加密好了

**Comment by anwen-anyi** [comment]
和谁battle？用户还是谁呀~
嗷，刚刚复现了一下，你说的是现在隐藏文件 如果猜出来的需要密码是吧？

得了 众口难调....之前是隐藏的文件能直接猜出来并且能访问觉的不安全，现在是猜出来的需要密码 觉的麻烦 哈哈...

不过你可以考虑新加一用户 可以看到隐藏的文件权限...这样 曲折一些，但是也能解决一些问题QAQ

**Comment by yuehun** [comment]
> 和谁battle？用户还是谁呀~ 嗷，刚刚复现了一下，你说的是现在隐藏文件 如果猜出来的需要密码是吧？
> 
> 得了 众口难调....之前是隐藏的文件能直接猜出来并且能访问觉的不安全，现在是猜出来的需要密码 觉的麻烦 哈哈...
> 
> 不过你可以考虑新加一用户 可以看到隐藏的文件权限...这样 曲折一些，但是也能解决一些问题QAQ





我的意思如果害怕被猜出来，就不要用隐藏文件了吗
或者是否可以增加一个开关，隐藏文件是否需要密码才能访问

**Comment by youshang2580** [comment]
现在就是隐藏了知道文件夹名字还是可以访问（勾选了 应用到子文件夹），这隐藏功能有点鸡肋，隐藏文件需要密码不是更鸡肋，我设置密码我还隐藏干啥，隐藏就应该访问不到

**Comment by anwen-anyi** [comment]
> 现在就是隐藏了知道文件夹名字还是可以访问（勾选了 应用到子文件夹），这隐藏功能有点鸡肋，隐藏文件需要密码不是更鸡肋，我设置密码我还隐藏干啥，隐藏就应该访问不到

谁告诉你隐藏了还能访问？

**Comment by anwen-anyi** [comment]
> > 和谁battle？用户还是谁呀~ 嗷，刚刚复现了一下，你说的是现在隐藏文件 如果猜出来的需要密码是吧？
> > 得了 众口难调....之前是隐藏的文件能直接猜出来并且能访问觉的不安全，现在是猜出来的需要密码 觉的麻烦 哈哈...
> > 不过你可以考虑新加一用户 可以看到隐藏的文件权限...这样 曲折一些，但是也能解决一些问题QAQ
> 
> 我的意思如果害怕被猜出来，就不要用隐藏文件了吗 或者是否可以增加一个开关，隐藏文件是否需要密码才能访问

我记得现在隐藏文件隐藏后直接报错还是怎么了 反正访问不到

**Comment by youshang2580** [comment]
> > > 和谁battle？用户还是谁呀~ 嗷，刚刚复现了一下，你说的是现在隐藏文件 如果猜出来的需要密码是吧？
> > > 得了 众口难调....之前是隐藏的文件能直接猜出来并且能访问觉的不安全，现在是猜出来的需要密码 觉的麻烦 哈哈...
> > > 不过你可以考虑新加一用户 可以看到隐藏的文件权限...这样 曲折一些，但是也能解决一些问题QAQ
> > 
> > 
> > 我的意思如果害怕被猜出来，就不要用隐藏文件了吗 或者是否可以增加一个开关，隐藏文件是否需要密码才能访问
> 
> 我记得现在隐藏文件隐藏后直接报错还是怎么了 反正访问不到

能访问呀，只是主页隐藏这个文件夹了，地址输入隐藏的可以访问的

**Comment by BakaJzon** [comment]
要不就加个设置：
`前端隐藏` 只在api中隐藏，可输入路径访问
`后端隐藏` 就算访问了隐藏文件目录，也报404

**Comment by QiuYeDx** [comment]
请问有没有进度👀感觉这点挺需要改进的，就像楼上说的那样
