### ISSUE TITLE
视频播放集数选择器 Safari浏览器点击时字重叠

### ISSUE THREAD

**Issue by MindFollowing** [alist-org/alist#3332]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.10.1

### Driver used / 使用的存储驱动

Aliyundrive

### Describe the bug / 问题描述

文件夹下有多个视频时，任选一播放，视频下方出现集数（视频标题）选择器；
IOS Safari：字体显示重叠，页面刷新后仅当前集（只有一条记录了）
其他浏览器：字体显示正常，页面刷新后仅当前集（只有一条记录了）
![image](https://raw.githubusercontent.com/MindFollowing/doutu/3fe3ac806acedae5384d5e770653d81898f1ba13/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230210143452.jpg)

### Reproduction / 复现链接

[https://pan.lccyy.com](https://pan.lccyy.com/%E7%88%B1%E4%B8%BD%E4%B8%9D%E6%A2%A6%E6%B8%B8%E4%BB%99%E5%A2%83/%E7%88%B1%E4%B8%BD%E4%B8%9D%E6%A2%A6%E6%B8%B8%E4%BB%99%E5%A2%831.mp4)

**Comment by Xhofe** [comment]
什么叫字体显示重叠

**Comment by MindFollowing** [comment]
> 什么叫字体显示重叠

已更新问题描述

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/218125384-689f4600-a4f1-4820-adfd-6cfb25a5e076.png)

无法复现此问题。
