### ISSUE TITLE
瀏覽器標籤顯示方式

### ISSUE THREAD

**Issue by 1476523** [alist-org/alist#3336]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能夠自訂在瀏覽器的標籤上是否要顯示目錄名稱，又或者是更改顯示的方式。

### Suggested solution / 实现思路

在AList管理的站點位置新增一個下拉式的選項
名稱
目錄顯示方式
選項
目錄顯示在前(預設)
目錄顯示在後
無

目錄顯示在前(預設)就是目前的3.10.1以來的顯示方式
例如目前預設值為目錄在主頁；網站標題 CCC的站點
![image](https://user-images.githubusercontent.com/98206495/218038825-d7e9ae04-df01-4ec6-b80c-1d0e41466e77.png)
網頁標籤上顯示為 主頁 | TOC AList

![image](https://user-images.githubusercontent.com/98206495/218038447-8441434e-9b3c-494d-93c8-d260a8893610.png)
目錄顯示在後就是會變成 TOC AList | 主頁

![image](https://user-images.githubusercontent.com/98206495/218038721-7df477ec-ea85-406d-bb07-b1fab4124eba.png)
無則是只有單存的 TOC AList

當然AList管理可以不用或者一起更改顯示方式

**Comment by LowerAI** [comment]
主页在前看起来爹却有点别扭了，支持
