### ISSUE TITLE
现在阿里 token 经常失效，需要一个一个的更换，建议增加从外部文本导入token功能，也便于不带token的备份进行分享 

### ISSUE THREAD

**Issue by p00y** [alist-org/alist#3337]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在阿里 token 经常失效，需要一个一个的更换，建议增加从外部文本导入token功能，也便于不带token的备份进行分享

**Comment by Xhofe** [comment]
请理解本项目是一个通用的应用 而不是专门为阿里服务，故不考虑为某个存储添加专有的功能。专有的功能可以考虑通过外部程序调用本应用的API实现。

ps 正常使用阿里的token应该永远不会失效。
