### ISSUE TITLE
建议修改登录时触发密码错误次数过多的判断逻辑

### ISSUE THREAD

**Issue by juruoyyx** [alist-org/alist#3339]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

![HG39QBD Z({%J( U8P1_AP](https://user-images.githubusercontent.com/60863833/218078302-43669bf9-f3a1-4c1d-9739-bf545674f5a6.png)

建议修改登录时触发密码错误次数过多的判断逻辑（或者提供判断逻辑的切换选项），目前是以 IP 为标准进行统计的，但是对于学校、公司等场所很多人共用一个公网IP，这导致一人输错密码过多，整个场所都无法进行登录。

建议修改为以用户名为标准进行统计，判断一个用户名是否错误次数过多。

### Suggested solution / 实现思路

位于 `server\handles\auth.go` 文件的 `func Login(c *gin.Context)` 函数中。

将
```go
loginCache.Get(ip)
loginCache.Set(ip, count+1)
loginCache.Del(ip)
```
修改为
```go
loginCache.Get(req.Username)
loginCache.Set(req.Username, count+1)
loginCache.Del(req.Username)
```
或是同时保留两种判断逻辑，后台可进行切换

**Comment by anwen-anyi** [comment]
重启可以重置我记得

**Comment by juruoyyx** [comment]
> 重启可以重置我记得

我知道重启可以，但不可能每次出现都重启吧（（；´д｀）ゞ

**Comment by anwen-anyi** [comment]
> > 重启可以重置我记得
> 
> 我知道重启可以，但不可能每次出现都重启吧（（；´д｀）ゞ

嗯，我理解你的意思，不过正常情况下6次才会锁定，
自己的账号密码的话按理说设置了记住密码了 不会错才对....

（题外话QAQ）如果是自己用要是觉的48小时登录时间太短 可以尝试设置更久一些
