### ISSUE TITLE
圖片示圖模式下觀看圖片並不會換頁或自動加載

### ISSUE THREAD

**Issue by 1476523** [alist-org/alist#3341]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.10.1

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

例如目前設定為
分頁類型 分頁 或 加載更多 或 自動加載更多
默認每頁數量 10
當用戶觀看圖片至第10張圖時並點選下一張圖片時是顯示第1張圖片而不是第11張圖片
若這不是Bug的話請幫我改成enhancement

### Reproduction / 复现链接

這邊開了一個區域測試圖片的顯示
站點默認每頁數量是10；分頁類型是分頁 
https://alist.toc.icu/%E6%B8%AC%E8%A9%A6%E5%8D%80

**Comment by BoYanZh** [comment]
我觉得是预期行为，前端只能找到这页里那么多图

**Comment by Xhofe** [comment]
同预期行为，当前页只有这么多张图片啊
