### ISSUE TITLE
希望增加超星学习通网盘

### ISSUE THREAD

**Issue by wzwtt** [alist-org/alist#3347]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加超星学习通网盘，包括个人空间、小组空间和课程空间。学习通网盘不限速，其中小组空间和课程空间可以无限容量。

网盘地址：
http://i.chaoxing.com/

### Suggested solution / 实现思路

相关api介绍：
https://hbte.ch/1817.html

**Comment by anwen-anyi** [comment]
想用的话 可以用V2的 V2的有一个超星学习通网盘

**Comment by GitCourser** [comment]
> 希望增加超星学习通网盘，包括个人空间、小组空间和课程空间。学习通网盘不限速，其中小组空间和课程空间可以无限容量。

请问课程空间在哪里?

**Comment by wzwtt** [comment]
> > 希望增加超星学习通网盘，包括个人空间、小组空间和课程空间。学习通网盘不限速，其中小组空间和课程空间可以无限容量。
> 
> 
> 
> 请问课程空间在哪里?

![image](https://user-images.githubusercontent.com/21050445/219376758-8bdf2acc-fd3f-44b4-8189-debdb99c01c0.jpeg)

**Comment by GitCourser** [comment]
这个"测试"是自建的的班级还是自建的课程?

**Comment by wzwtt** [comment]
> 
> 
> 这个"测试"是自建的的班级还是自建的课程?

自己新建的课程，课程里面可以新建班级。

**Comment by GitCourser** [comment]
> > 这个"测试"是自建的的班级还是自建的课程?
> 
> 自己新建的课程，课程里面可以新建班级。

原来如此, 谢谢了
