### ISSUE TITLE
能否隐藏 .开头的隐藏文件

### ISSUE THREAD

**Issue by jch12138** [alist-org/alist#3349]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在mac下挂载了webdav，往里面添加文件的时候会生成 .开头的隐藏文件，在系统文件管理器里不显示，但在网页端会显示，尝试了管理功能中的隐藏功能，但无法实现对所有该类文件的匹配，因为这些隐藏文件的名字是不固定的。
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/30290347/218246892-e280c95d-7206-4fec-8361-2c1c9175a5d1.png">

### Additional context / 附件

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/30290347/218246889-13e34693-9f15-4e05-ab38-c3ae60773315.png">

**Comment by Xhofe** [comment]
```
^\.
```
