### ISSUE TITLE
希望元信息可以自定义某个文件夹的排序

### ISSUE THREAD

**Issue by kuilei0926** [alist-org/alist#3360]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望元信息可以自定义某个文件夹的排序

**Comment by anwen-anyi** [comment]
你添加存储的时候不是可以进行排序设置么~

**Comment by kuilei0926** [comment]
> 你添加存储的时候不是可以进行排序设置么~

有些文件夹我想让他按名称排序，有些我想按修改日期排序，添加存储的只能整个设置

**Comment by anwen-anyi** [comment]
> > 你添加存储的时候不是可以进行排序设置么~
> 
> 
> 
> 有些文件夹我想让他按名称排序(比如电影)，有些我想按修改日期排序(比如照片，我想看最新上传的照片)，添加存储的只能整个设置

😂挺麻烦的……够呛……

**Comment by testonlys** [comment]
中文排序好象不是按拼音排，是按笔划排的

**Comment by V-arc** [comment]
> 中文排序好象不是按拼音排，是按笔划排的

还有1、11，2这样的排序。。（不知道是叫自然排序还是什么
