### ISSUE TITLE
Cloudreve无法上传文件,下载是没问题,不知道为啥？

### ISSUE THREAD

**Issue by reyfull** [alist-org/alist#3361]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.10.1

### Driver used / 使用的存储驱动

Cloudreve

### Describe the bug / 问题描述

cloudreve本身的程序在网页上传和下载文件是正常的,alist挂载cloudreve之后也是可以下载,但上传会出现错误,不知道是啥原因
补充一下,cloudreve如果是绑本地存储是可以上传的,但如果是绑onedrive就无法上传文件了,会出现错误。。。
大佬可以帮解决一下吗,谢谢
![SharedScreenshot](https://user-images.githubusercontent.com/111069621/218276247-dca11323-a43c-4a76-ae43-6f08c387dde5.jpg)

### Logs / 日志
谢谢楼下的大佬提醒,补上log文件
![Cloudreve](https://user-images.githubusercontent.com/111069621/218294470-3981e3e6-4a7b-4aa5-a4e3-4f3082d89a50.jpg)

_No response_

**Comment by anwen-anyi** [comment]
建议再补充一下日志，可以去 data/log/log.log 打开找到日志

**Comment by mclk623** [comment]
问题仍然存在
