### ISSUE TITLE
关于添加插件功能来实现灵活扩展

### ISSUE THREAD

**Issue by wangdashuaihenshuai** [alist-org/alist#3369]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在挂载视频的时候，
有时候需要对视频文件名做些修改。
所以需要一个可以灵活修改的方式。
我觉得讲文件查询创建更新添加hook，
做成插件接口，然后其他开发者可以开发插件。来实现灵活修改的功能。

### Suggested solution / 实现思路

在
查询文件
更新文件
删除文件
事件前后添加一个hook接口，用go plugin来作为插件功能。

**Comment by swRains** [comment]
附议

**Comment by adogecheems** [comment]
附议

**Comment by aliuq** [comment]
+1 插件的灵活扩展可以让 alist 发展的更好，可以实现更多的需求

**Comment by CafeBabe202** [comment]
希望能够添加前端 插件/主题 功能，这样将有更好的布局，更灵活强大的前端功能
