### ISSUE TITLE
FR 增加后台home键

### ISSUE THREAD

**Issue by BakaJzon** [alist-org/alist#3372]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

进入后台管理后找不到返回根的链接。要手动重输链接，很麻烦。
希望在login 和 管理页 增加home键，指向 `https://alist.example.com/root/`

### Suggested solution / 实现思路

1. 往上方logo处加超链接
2. 在管理页注销按钮旁加一个
3. etc

**Comment by anwen-anyi** [comment]
后台左侧栏不是有个 主页按钮？
