### ISSUE TITLE
重启路由后报错

### ISSUE THREAD

**Issue by chris191110** [alist-org/alist#3374]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.10.1

### Driver used / 使用的存储驱动

aliyun共享

### Describe the bug / 问题描述

padavan 重启路由后，可以登录alist，但是打开里面之前添加的别人的共享链接，均出现下列报错提示：

failed get objs: failed to list objs: Post "https://api.aliyundrive.com/adrive/v3/file/list": x509: certificate signed by unknown authority

### Reproduction / 复现链接

failed get objs: failed to list objs: Post "https://api.aliyundrive.com/adrive/v3/file/list": x509: certificate signed by unknown authority

**Comment by anwen-anyi** [comment]
可能是他是HTTPS证书到期了 你去他的域名看看是不是  等后面版本可以跳过这个证书检测
