### ISSUE TITLE
Alist 下载无法多线程

### ISSUE THREAD

**Issue by kgggggb** [alist-org/alist#3382]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

当驱动为：
```
AList V2
AList V3
FTP
本机存储
SFTP
SMB
虚拟存储
WebDav
```
时，IDM无法多线程下载文件。

### Additional context / 附件

![image](https://user-images.githubusercontent.com/47137779/218389478-9b4d85b3-6a61-48b1-957f-cdd19f646aa4.png)

**Comment by kgggggb** [comment]
？？？？

**Comment by kgggggb** [comment]
@Xhofe 这个问题有效啊 确实同一条链接没法多线程

**Comment by Xhofe** [comment]
- AList V2 取决于源驱动
- AList V3 取决于源驱动
- FTP 不支持seek，无法支持
- 本机存储 ![image](https://user-images.githubusercontent.com/36558727/218390372-938b8f29-cd02-4cdb-a0bb-e7af77029f2b.png)
- SFTP 待添加seek
- SMB 待添加seek
- 虚拟存储 测试用 无实际意义
- WebDav 取决与源服务

**Comment by kgggggb** [comment]
> * AList V2 取决于源驱动
> * AList V3 取决于源驱动
> * FTP 不支持seek，无法支持
> * 本机存储 ![image](https://user-images.githubusercontent.com/36558727/218390372-938b8f29-cd02-4cdb-a0bb-e7af77029f2b.png)
> * SFTP 待添加seek
> * SMB 待添加seek
> * 虚拟存储 测试用 无实际意义
> * WebDav 取决与源服务

~~![image](https://user-images.githubusercontent.com/47137779/218395069-3358f714-5ed1-4c75-852b-e03fa9bd7843.png)

我这本地存储不仅不支持多线程，直接续传都不行了，宝塔默认Nginx反向代理~~

-----------------

我把官网的所有Nginx参数都一个一个加上去看看是哪个参数有问题。
如果反代参数中没有
`proxy_set_header Range $http_range;`
那就没办法多线程 我也不知道为什么。
