### ISSUE TITLE
WebDAV不能正常上传文件：Method Not Allowed

### ISSUE THREAD

**Issue by AkarinLiu** [alist-org/alist#3384]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.10.1

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/58081491/218456910-c6a988f4-de29-4c4b-bd25-ec8fa1e33f50.png)
我使用FreeFileSync进行同步，但是RaiDrive报错：Method Not Allowed

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/58081491/218457274-2a4dea34-4810-4b54-9616-2a5264c7509e.png)

**Comment by ddaodan** [comment]
#3375
