### ISSUE TITLE
123盘无法正常下载预览

### ISSUE THREAD

**Issue by guangguailulu** [alist-org/alist#3385]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.10.1

### Driver used / 使用的存储驱动

123Pan

### Describe the bug / 问题描述

能正常读取文件列表，甚至上传功能也是正常的，但是无法下载文件，点击下载会跳转到一个名为index的空白网站，复制下载链接到下载器也不能正常下载，预览视频也是失败，我尝试到官网下载是正常的，或许123盘添加了某个认证

### Reproduction / 复现链接

https://xdream.repl.co/p/123Pan/gmzz%252Caqsdwz.rar?sign=-oog16Np7R0DIHpjzXd8Ch1T4tUTFZ65EkpbGpA6FT4=:0

**Comment by likefresh** [comment]
问题描述补充：Edge跳转到index后可以自动下载；预览视频功能已失效，直接123网盘登录后观看正常。

**Comment by anzhiyu-c** [comment]
+1，会跳转到index空白网页。
