### ISSUE TITLE
希望在后台加一个sign可以不用加的开关，以前我用直链直接可以下软件，现在必须加sign我的东西根本用不了了

### ISSUE THREAD

**Issue by Xcker8** [alist-org/alist#3386]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望在后台加一个sign可以不用加的开关，以前我用直链直接可以下软件，现在必须加sign我的东西根本用不了了
以前我的都是  ip/d/aaa.res    直接下，现在必须加sign  很头疼啊

### Suggested solution / 实现思路

在后台添加开关 用户自行选择

**Comment by zanderzhng** [comment]
我也觉得可以加一个一直直链的开关，或者说针对某个共享，某个后缀，一直启用直链，不启用预览。
