### ISSUE TITLE
在一键安装脚本里面的 systemd 加入restart on failure？

### ISSUE THREAD

**Issue by acyanbird** [alist-org/alist#3389]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

因为在实际安装的时候，这个很有用所以自己加入了，我想应该可以让初始设置就是这样？
[Service]
Restart=on-failure

不清楚会不会有不好的影响，但是考虑一下？感谢各位~

### Suggested solution / 实现思路

修改 https://alist.nn.ci/v3.sh 处的 systemd 配置

**Comment by SkysCrystal** [comment]
我使用一键脚本升级到 v3.12.0 ，debian 重启后不会自动开启 alist 服务。
之前使用的版本是可以自重启的。而且新版本隔几个小时就会 exit
