### ISSUE TITLE
请求添加 pixeldrain 网盘储存

### ISSUE THREAD

**Issue by cgapk123** [alist-org/alist#3404]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

此网盘不限速不限制容量，在海外非常受欢迎

网盘地址：https://pixeldrain.com/

### Suggested solution / 实现思路

此网盘文档api 方法

以下是使用 curl 匿名上传文件的方法：

curl -T "file_name.txt" https://pixeldrain.com/api/file/
您还可以使用 curl 将文件上传到您的 pixeldrain 帐户。[从API 密钥页面](https://pixeldrain.com/user/api_keys)获取 API 密钥并在命令中输入它。将此处的示例 API 密钥替换为您自己的：

curl -T "file_name.txt" -u :5f45f184-64bb-4eaa-be19-4a5f0459db49 https://pixeldrain.com/api/file/

**Comment by The-GO** [comment]
这叫不限速？一周20GB能干嘛？
![Screenshot_2023-02-26-01-23-12-441-edit_com android chrome](https://user-images.githubusercontent.com/50163359/221370803-5897c669-e764-4740-a458-13560910a7c7.jpg)
