### ISSUE TITLE
请问能够同步安卓源吗？Termux只能安装3.10.1版本。

### ISSUE THREAD

**Issue by zym20192019** [alist-org/alist#3405]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

没有催的意思，安卓党感谢大佬！！

**Comment by zym20192019** [comment]
是我自己的问题，安卓端termux已安装并且能够流畅使用！！！alist永远的神！！！

**Comment by zym20192019** [comment]
是我自己的问题，安卓端termux已安装并且能够流畅使用！！！alist永远的神！！！

**Comment by manon2328** [comment]
友友你好，请问你的安卓端termux是怎么安装更新包的啊？（小白求教，非常感谢）

**Comment by zym20192019** [comment]
> 友友你好，请问你的安卓端termux是怎么安装更新包的啊？（小白求教，非常感谢）

先更新termux源，命令是pkg update,之后正常安装，命令是pkg install alist,如果老版本没卸载的话先pkg uninstall alist
