### ISSUE TITLE
请求增加连接aria2下载器时WebSocket协议的支持

### ISSUE THREAD

**Issue by w0ngzz** [alist-org/alist#3412]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

![image](https://user-images.githubusercontent.com/34603964/218854417-cf0ac802-e389-4776-9f6f-d8646892ff95.png)
现在的aria2填写rpc地址时仅支持http协议，本人使用的是websocket协议，故提出此需求

### Suggested solution / 实现思路

建议参考[AriaNg](https://github.com/mayswind/AriaNg)和[webui-aria2](https://github.com/ziahamza/webui-aria2)这两个项目。

### Additional context / 附件

这是我在AriaNg里面对aria2连接的设置，我觉得这个项目可以也设计成类似的布局
![image](https://user-images.githubusercontent.com/34603964/218856496-5784004b-e133-4dfa-be25-aa9332790795.png)

**Comment by Xhofe** [comment]
我不是很理解 aria2明明提供http RPC你为什么非得要使用websocket
