### ISSUE TITLE
qBittorrent离线下载无法使用

### ISSUE THREAD

**Issue by 12189108** [alist-org/alist#3413]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0

### Driver used / 使用的存储驱动

无关存储驱动

### Describe the bug / 问题描述

添加下载任务后，提示：
```
qbittorrent

there should be exactly one task with tag "alist-e83dde1f-e2d8-40e4-9f39-fa9d36881ca7"
```
还有qbittorrent的用户名、密码和端口是不是写死的，没有看到可以配置的地方

### Reproduction / 复现链接

*

### Logs / 日志

```
error [there should be exactly one task with tag "alist-e83dde1f-e2d8-40e4-9f39-fa9d36881ca7"] while run task [download 网页链接 to 对应存储]
```

**Comment by wxnode** [comment]
我看了下,好像有个预设值
http://admin:adminadmin@localhost:8080

你可以按照这个设置了试试.

**Comment by LowerAI** [comment]
> 我看了下,好像有个预设值 http://admin:adminadmin@localhost:8080
> 
> 你可以按照这个设置了试试.

请问这个预设值填在哪儿？

**Comment by CyberTNT** [comment]
> > 我看了下,好像有个预设值 http://admin:adminadmin@localhost:8080
> > 你可以按照这个设置了试试.
> 
> 请问这个预设值填在哪儿？

应该是在qb里设置，qb和alist在同一台机子上，qb里设置webUI，用户名admin，密码adminadmin

**Comment by anwen-anyi** [comment]
> > > 我看了下,好像有个预设值 http://admin:adminadmin@localhost:8080
> > > 你可以按照这个设置了试试.
> > 
> > 
> > 请问这个预设值填在哪儿？
> 
> 应该是在qb里设置，qb和alist在同一台机子上，qb里设置webUI，用户名admin，密码adminadmin，ip127.0.0.1，端口8080

这个倒是设置好了依然会出现楼主那样的问题QAQ..... 但是实际上也把种子离线文件推送到 `qBittorrent` 下载了
同时我也把`qBittorrent` 下载的路径改到了`data\temp\qbittorrent`这个也是不行..

@kdxcxs 大佬老看看啥情况呗~

**Comment by kdxcxs** [comment]
qb 在添加任务的时候会先解析种子再创建任务，我调试的时候用的种子解析的很快就没注意到这个问题，在修了

**Comment by anwen-anyi** [comment]
> qb 在添加任务的时候会先解析种子再创建任务，我调试的时候用的种子解析的很快就没注意到这个问题，在修了

辛苦大佬了 么么哒~

**Comment by 88pan** [comment]
同样出现问题，但是我的显示Qbittorrent not ready

**Comment by anwen-anyi** [comment]
机器人 构建 测试版的似乎失败了？手动停止了吗~

**Comment by kdxcxs** [comment]
> 机器人 构建 测试版的似乎失败了？手动停止了吗~

细说？

**Comment by anwen-anyi** [comment]
> > 同样出现问题，但是我的显示Qbittorrent not ready
> 
> 应该是 qb 的 url 没设置好，你看看 [上面](https://github.com/alist-org/alist/issues/3413#issuecomment-1430495203)

现在有新的问题  :  `torrent parse timeout`

**Comment by kdxcxs** [comment]
> > > 同样出现问题，但是我的显示Qbittorrent not ready
> > 
> > 
> > 应该是 qb 的 url 没设置好，你看看 [上面](https://github.com/alist-org/alist/issues/3413#issuecomment-1430495203)
> 
> 现在有新的问题 : `torrent parse timeout` 有一段视频你需要吗？我可以提供一下复现视频

这里是我设置了超时，如果等了 qb 一分钟都还没有创建任务的话就会报这个错

**Comment by anwen-anyi** [comment]
> > > > 同样出现问题，但是我的显示Qbittorrent not ready
> > > 
> > > 
> > > 应该是 qb 的 url 没设置好，你看看 [上面](https://github.com/alist-org/alist/issues/3413#issuecomment-1430495203)
> > 
> > 
> > 现在有新的问题 : `torrent parse timeout` 有一段视频你需要吗？我可以提供一下复现视频
> 
> 这里是我设置了超时，如果等了 qb 一分钟都还没有创建任务的话就会报这个错

我发你视频吧 你看下 就应该知道怎么回事啦~
https://www.aliyundrive.com/s/8D3ZH474ygM

兰奏上传不上去一直只能用阿里了

**Comment by kdxcxs** [comment]
> 
> 我发你视频吧 你看下 就应该知道怎么回事啦~ [aliyundrive.com/s/8D3ZH474ygM](https://www.aliyundrive.com/s/8D3ZH474ygM)
> 
> 兰奏上传不上去一直只能用阿里了

怪，一样的种子，一样的操作，我这边是正常的

![image.png](https://s2.loli.net/2023/02/15/dpV6hOo8XZENstf.png)

**Comment by anwen-anyi** [comment]
> > 我发你视频吧 你看下 就应该知道怎么回事啦~ [aliyundrive.com/s/8D3ZH474ygM](https://www.aliyundrive.com/s/8D3ZH474ygM)
> > 兰奏上传不上去一直只能用阿里了
> 
> 怪，一样的种子，一样的操作，我这边是正常的
> 
> ![image.png](https://camo.githubusercontent.com/e30af865268a357b5700b53aa7814a2c9b958dd2a71c871d8618f7f2d9e97a9e/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30322f31352f64705636684f6f38585a454e7374662e706e67)

我用刚build好的也一样.. 大佬你发下你用的哪个Alist呢 我试试看
https://github.com/alist-org/alist/actions/runs/4182139905

**Comment by kdxcxs** [comment]
> > > 我发你视频吧 你看下 就应该知道怎么回事啦~ [aliyundrive.com/s/8D3ZH474ygM](https://www.aliyundrive.com/s/8D3ZH474ygM)
> > > 兰奏上传不上去一直只能用阿里了
> > 
> > 
> > 怪，一样的种子，一样的操作，我这边是正常的
> > ![image.png](https://camo.githubusercontent.com/e30af865268a357b5700b53aa7814a2c9b958dd2a71c871d8618f7f2d9e97a9e/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30322f31352f64705636684f6f38585a454e7374662e706e67)
> 
> 我用刚build好的也一样.. 大佬你发下你用的哪个Alist呢 我试试看 [alist-org/alist/actions/runs/4182139905](https://github.com/alist-org/alist/actions/runs/4182139905)

https://github.com/kdxcxs/alist/releases/tag/v3-qbitorrent

**Comment by anwen-anyi** [comment]
> > > > 我发你视频吧 你看下 就应该知道怎么回事啦~ [aliyundrive.com/s/8D3ZH474ygM](https://www.aliyundrive.com/s/8D3ZH474ygM)
> > > > 兰奏上传不上去一直只能用阿里了
> > > 
> > > 
> > > 怪，一样的种子，一样的操作，我这边是正常的
> > 
> > 
> > 我用刚build好的也一样.. 大佬你发下你用的哪个Alist呢 我试试看 [alist-org/alist/actions/runs/4182139905](https://github.com/alist-org/alist/actions/runs/4182139905)
> 
> https://github.com/kdxcxs/alist/releases/tag/v3-qbitorrent

奇怪了...一样的问题...先吃饭了 吃完饭 我用Windows 10 笔记本试试看 麻烦大佬啦~

**Comment by anwen-anyi** [comment]
害.... 也不知道哪里问题了 可能 qBittorrent 和我无缘了

### Windows 7
依然是我录制的视频中那种情况

### Windows 10
虽然不像视频中那样了，但是又出现新的情况了 `qBittorrent `离线好后 进行上传的时候 提示如下
```log
[31mERRO[0m[2023-02-15 18:56:49] error [open C:\anwen\新建文件夹\data\temp\qbittorrent\0f63b922-2798-4456-9a88-427f2ddd8767\[SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 19 (1080p) [B6A57801].mkv: The system cannot find the path specified.
failed to open file C:\anwen\新建文件夹\data\temp\qbittorrent\0f63b922-2798-4456-9a88-427f2ddd8767\[SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 19 (1080p) [B6A57801].mkv
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	D:/Codes/alist/internal/qbittorrent/monitor.go:136
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	D:/Codes/alist/pkg/task/task.go:75
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	D:/Codes/alist/pkg/task/manager.go:33
runtime.goexit
	D:/Go/src/runtime/asm_amd64.s:1594] while run task [transfer C:\anwen\新建文件夹\data\temp\qbittorrent\0f63b922-2798-4456-9a88-427f2ddd8767\[SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 19 (1080p) [B6A57801].mkv to [/QB](/ceshi)]
```
图片中失败哪里虽然没有说上传到哪里，但是在日志里面倒是看到了 日志最后的 `to [/QB](/ceshi)]`就是我上传的位置 没有错 图片中也有记录
![img](https://img-blog.csdnimg.cn/0c6240abbcda48fa82718f7f103f9175.png)

然后我以为是我本地离线到本地然后打不开文件夹的权限问题呢 我就又随便挂载了一个网盘`Teambition` 提示一样
```log
[31mERRO[0m[2023-02-15 19:18:05] error [open C:\anwen\新建文件夹\data\temp\qbittorrent\c20cde51-9f4b-488e-827b-20bac8d25ad3\[SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 19 (1080p) [B6A57801].mkv: The system cannot find the path specified.
failed to open file C:\anwen\新建文件夹\data\temp\qbittorrent\c20cde51-9f4b-488e-827b-20bac8d25ad3\[SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 19 (1080p) [B6A57801].mkv
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	D:/Codes/alist/internal/qbittorrent/monitor.go:136
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	D:/Codes/alist/pkg/task/task.go:75
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	D:/Codes/alist/pkg/task/manager.go:33
runtime.goexit
	D:/Go/src/runtime/asm_amd64.s:1594] while run task [transfer C:\anwen\新建文件夹\data\temp\qbittorrent\c20cde51-9f4b-488e-827b-20bac8d25ad3\[SubsPlease] Kage no Jitsuryokusha ni Naritakute! - 19 (1080p) [B6A57801].mkv to [/tb](/视频)]
```
图片中失败哪里虽然没有说上传到哪里，但是在日志里面倒是看到了 日志最后的 `to [/tb](/视频)]`就是我上传的位置 没有错 图片中也有记录
![img](https://img-blog.csdnimg.cn/8d991d3834114968afd5ad3dc71b5fff.png)

到这里俺也不知道哪里错了 哈哈 `powershell` 也用了 也`右键获取管理员权限`了........可能真的就是和我无缘啦 就这样吧暂时 呜呜呜~~~

**Comment by QYQSDTC** [comment]
能下但是AList报错
![CleanShot-q7mWKbEV](https://user-images.githubusercontent.com/15608306/219029446-14ffdb5c-1ca9-40d3-8d62-e387090a0c7d.jpg)

**Comment by Jerry12228** [comment]
> qb 在添加任务的时候会先解析种子再创建任务，我调试的时候用的种子解析的很快就没注意到这个问题，在修了

aria2下载也存在这个问题，而且如果一直无法解析种子的话，其他已经完成的任务也不上传到对应存储status一直是active

**Comment by ZJUprince** [comment]
dfasdf
