### ISSUE TITLE
天翼云也挂载不上了

### ISSUE THREAD

**Issue by Lsuntiny** [alist-org/alist#3414]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.11.0

### Driver used / 使用的存储驱动

天翼云盘

### Describe the bug / 问题描述

No images in the current folder

### Reproduction / 复现链接

No images in the current folder

**Comment by anwen-anyi** [comment]
=,= 把右上角按钮从图片视图切换成列表视图或者网格视图 
自行关闭issues吧.....
