### ISSUE TITLE
阿里分享挂载状态不是work的自动处理

### ISSUE THREAD

**Issue by wowdd1** [alist-org/alist#3419]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist管理 ->  存储  下, 有些阿里云盘分享的状态显示 "状态: work", 有些则不是, 可能是下面几种显示

“share_link is cancelled by the creator”  这种显示失效, 可以自动移除

“Failed init storage: failed to refresh token: The input parameter refresh_token is not valid.” 这种显示token无效 用其他分享有效的token更新token

“share_link is forbidden”  可以自动移除

“The resource share_pwd is not valid. Please check.”  保留, 查询公共api获取密码更新?

**Comment by anwen-anyi** [comment]
可以套用一下开发者的话 https://github.com/alist-org/alist/issues/3337#issuecomment-1425547617
