### ISSUE TITLE
在文件列表下载显示signature not match,详情见描述

### ISSUE THREAD

**Issue by invoker-kael** [alist-org/alist#3423]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.11.0

### Driver used / 使用的存储驱动

Aliyun

### **在文件列表下载显示signature not match**
![image](https://user-images.githubusercontent.com/63380399/218939144-0122f0ef-8b39-4a89-9d57-e1bee765fca0.png)
![image](https://user-images.githubusercontent.com/63380399/218940477-4d08ac69-1258-484d-8aec-62d90025dc1a.png)

### **如果点入文件下载可以正常下载**
![image](https://user-images.githubusercontent.com/63380399/218939744-2ed1f4e7-2c1b-41f5-ae99-f41e7361a533.png)
![image](https://user-images.githubusercontent.com/63380399/218939616-a7610f91-2228-4b19-b884-300cd67c2628.png)

### Reproduction / 复现链接

https://alist.caibao.gq/The.Year.of.Jacky.Cheung.World.Tour.07'.HK.2007.BluRay.1080p.2Audio.DTS-HD.MA.5.1.x264-beAst.mkv

**Comment by anwen-anyi** [comment]
暂时无法复现诶~

**Comment by invoker-kael** [comment]
复现链接
https://alist.caibao.gq/The.Year.of.Jacky.Cheung.World.Tour.07'.HK.2007.BluRay.1080p.2Audio.DTS-HD.MA.5.1.x264-beAst.mkv

**Comment by anwen-anyi** [comment]
> 复现链接 https://alist.caibao.gq/The.Year.of.Jacky.Cheung.World.Tour.07'.HK.2007.BluRay.1080p.2Audio.DTS-HD.MA.5.1.x264-beAst.mkv

1. 更换token 试试看，更换之前先看看第二步
2. 打开阿里云盘手机端 我的  --- 设置  --- 账号与安全  --- 登录设备管理  看看是不超出你的设备上限了？
   - （普通3台设备限制   超级会员10台设备限制）
   - 可千万别把 三星 SM-G9810 设备删除
   - 如果不小心删除了上面哪个设备 现在似乎不知道怎么加上去了...
3. 然后重启Alist 试试呢？

我自己的网盘里面确实复现不出来.....

**Comment by anwen-anyi** [comment]
嗯？这个问题也是因为  转发直链参数导致的么~

**Comment by invoker-kael** [comment]
如果去除转发直链参数显示如下
AccessDenied You are denied by bucket referer policy. 63EC945E3FFCDB313823672A cn-beijing-data.aliyundrive.net ccp-bj29-bj-1592982087
分别重新获取过新的token以及数量没有超出3台（就2台）

**Comment by anwen-anyi** [comment]
> AccessDenied You are denied by bucket referer policy. 63EC945E3FFCDB313823672A cn-beijing-data.aliyundrive.net ccp-bj29-bj-1592982087

6 你这是属于token的问题 去用移动端token吧...

**Comment by invoker-kael** [comment]
可以确认是非token问题，因为我抓的就是手机上的token，甚至用网站的二维码都扫过了。。。

**Comment by anwen-anyi** [comment]
> 可以确认是非token问题，因为我抓的就是手机上的token，甚至用网站的二维码都扫过了。。。 如果是web端，那么应该根本无法预览和下载才对。。

https://github.com/alist-org/alist/actions/runs/4181910254 试试这个测试版咯

**Comment by invoker-kael** [comment]
找到了问题在哪里
是nginx的Referrer-Policy问题，这个安全选项要为不安全unfafe-url，而不能设置为no-referrer-when-downgrade

**Comment by licoba** [comment]
> 找到了问题在哪里 是nginx的Referrer-Policy问题，这个安全选项要为不安全unfafe-url，而不能设置为no-referrer-when-downgrade

能详细说一下吗？我没有找到nginx配置在哪里，不是直接一键部署和启动的吗？

**Comment by invoker-kael** [comment]
> 

这个是另外使用nginx反代设置的，通常默认没有开启，我这里是手动加固了一点安全权限，所以会有一点问题
一键应该是不会有这个问题的

**Comment by invoker-kael** [comment]
> > 找到了问题在哪里 是nginx的Referrer-Policy问题，这个安全选项要为不安全unfafe-url，而不能设置为no-referrer-when-downgrade
> 
> 能详细说一下吗？我没有找到nginx配置在哪里，不是直接一键部署和启动的吗？

这个是另外使用nginx反代设置的，通常默认没有开启，我这里是手动加固了一点安全权限，所以会有一点问题
一键应该是不会有这个问题的
