### ISSUE TITLE
文本文件无法预览

### ISSUE THREAD

**Issue by damahouH** [alist-org/alist#3429]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.11.0

### Driver used / 使用的存储驱动

天翼云盘

### Describe the bug / 问题描述

文本文件无法在线预览

### Reproduction / 复现链接

https://mynotes.world/%E8%B5%84%E6%BA%90/cf%E4%B8%AD%E8%BD%AC%E6%9C%BA%E6%89%AB%E6%8F%8F/ip_scanner.py

### Logs / 日志

"code":401,"message":"sign expired","data":null}

**Comment by Xhofe** [comment]
检查你的 https://alist.nn.ci/zh/config/global.html#%E9%93%BE%E6%8E%A5%E8%BF%87%E6%9C%9F%E6%97%B6%E9%97%B4 设置。
