### ISSUE TITLE
挂载 Terabox(海外百度) 出现无法写入和删除

### ISSUE THREAD

**Issue by cgapk123** [alist-org/alist#3431]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11

### Driver used / 使用的存储驱动

Terabox

### Describe the bug / 问题描述

按照教程添加 Terabox 后可以正常读取和下载，但是却没办法上传和删除，上传和删除操作后均提示完成，但刷新后还是没有变化，进入网盘官网里面查看文件也没有任何变化。

进入 Terabox 官网上传和删除都正常，然后我尝试删除驱动，并重新注册了一个新的账户登录并添加，但是新账户添加后还是这样没办法上传和删除操作。

根据两个账户测试以及都能正常刷新显示列表和下载，不确定是不是我在Cookie里面添加问题，我是把Cookie里面的所有都复制了，可以正常显示下载，然后我又测试复制Cookie里面 browserid=（这段里面的复制了）=== ，但也显示正常。

### Reproduction / 复现链接

没有

### Logs / 日志

因为没有任何报错，所以没有日志

**Comment by 7ongOrz** [comment]
我这里也是这样，3.15.0
