### ISSUE TITLE
docker alist v3.10.1更新v3.11.0失败的问题，请教如何解决。阿里嘎多!

### ISSUE THREAD

**Issue by yuhouyanran** [alist-org/alist#3434]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.10.1

### Driver used / 使用的存储驱动

软路由docker

### Describe the bug / 问题描述

首先我我使用了停止容器--删除旧镜像--运行拉取最新版alist镜像命令--建立新的alist容器并配置参数。
相关命令如下：
`docker stop alist`
`docker rm alist`
`docker pull xhofe/alist:latest`
`docker run -d --restart=always -v /etc/alist:/opt/alist/data -p 5244:5244 --name="alist" xhofe/alist:latest`
之后重新打开alist页面查看版本依然是3.10，且挂载的两个存储还在，遂以为有可能是没有重启软路由所致，所以又进行了以下一次步骤依：停止容器--删除旧镜像--重启软路由--运行拉取最新版alist镜像命令--建立新的alist容器并配置参数，再次进入网页查看版本依然是3.10且有两个已成功挂载的存储。
而后尝试了建立watchower来自动更新docker下所有容器并手动运行了一次watchower，显示以下代码
<a href="https://imgse.com/i/pS7dp2q"><img src="https://s1.ax1x.com/2023/02/15/pS7dp2q.png" alt="pS7dp2q.png" border="0" /></a>

### Reproduction / 复现链接

<a href="https://imgse.com/i/pS7dp2q"><img src="https://s1.ax1x.com/2023/02/15/pS7dp2q.png" alt="pS7dp2q.png" border="0" /></a>

### Logs / 日志

root@OpenWrt:~# docker run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower \
    --cleanup \
    --run-once
time="2023-02-15T07:54:32Z" level=info msg="Watchtower 1.5.3"
time="2023-02-15T07:54:32Z" level=info msg="Using no notifications"
time="2023-02-15T07:54:32Z" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2023-02-15T07:54:32Z" level=info msg="Running a one time update."
time="2023-02-15T07:54:42Z" level=warning msg="Could not do a head request for \"xhofe/alist:latest\", falling back to regular pull." container=/alist image="xhofe/alist:latest"
time="2023-02-15T07:54:42Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": read tcp 172.31.0.6:51854->198.18.27.221:443: read: connection reset by peer" container=/alist image="xhofe/alist:latest"
time="2023-02-15T07:57:25Z" level=info msg="Found new whyour/qinglong:latest image (3ce372d543a7)"
time="2023-02-15T07:57:25Z" level=info msg="Stopping /qinglong (9aa46fa69312) with SIGTERM"
time="2023-02-15T07:57:40Z" level=info msg="Creating /qinglong"
time="2023-02-15T07:57:42Z" level=info msg="Removing image 3a8aa6dfbabf"
time="2023-02-15T07:57:47Z" level=info msg="Session done" Failed=0 Scanned=5 Updated=1 notify=no
time="2023-02-15T07:57:47Z" level=info msg="Waiting for the notification goroutine to finish" notify=no

**Comment by Xhofe** [comment]
不要再在issue中提问题！！！
