### ISSUE TITLE
更新到3.11.0版本后，挂载自己的阿里云盘还是不能播放视频，显示 failed get link: Device offline 

### ISSUE THREAD

**Issue by wsfyhlo** [alist-org/alist#3438]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

更新到3.11.0版本后，挂载自己的阿里云盘还是不能播放视频，显示 failed get link: Device offline 不清楚什么原因啊，希望大佬帮看下

### Reproduction / 复现链接

no

### Logs / 日志

[31mERRO[0m[2023-02-15 21:09:32] GET /dav/个人网盘/阿里云盘/去有风的地方/1.mp4 Device offline
failed get link
github.com/alist-org/alist/v3/internal/op.Link.func1
	/source/internal/op/fs.go:253
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.Link
	/source/internal/op/fs.go:260
github.com/alist-org/alist/v3/internal/fs.link
	/source/internal/fs/link.go:16
github.com/alist-org/alist/v3/internal/fs.Link
	/source/internal/fs/fs.go:35
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleGetHeadPost
	/source/server/webdav/webdav.go:250
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/source/server/webdav/webdav.go:58
github.com/alist-org/alist/v3/server.ServeWebDAV
	/source/server/webdav.go:44
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server.WebDAVAuth
	/source/server/webdav.go:93
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1991
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594

**Comment by Ethan9424** [comment]
我今天下午还能用，几分钟之前就不行了

**Comment by iabbaa** [comment]
+1

**Comment by davidtwchn** [comment]
阿里云盘电脑版，登录设备管理中，删除一些设备，注意保留 samsung 帐号。

**Comment by wsfyhlo** [comment]
> 阿里云盘电脑版，登录设备管理中，删除一些设备，注意保留 Samsung 帐号。

试了一下，还是不行

**Comment by gstsc2** [comment]
同样问题，就是挂载后，播放一段时间，会卡死，一定要停掉进程，然后再启动，又才可以，是不是限制了！

**Comment by stevezhka** [comment]
老版本的2.26也不行了，前一天还正常，突然就不能播放，alist上显示500错误

**Comment by gstsc2** [comment]
基本用不了，我另一个帐号都封了，用了新版本的ALIST后，应该是他们后台监控了，新的API，转移数据出来，得想办法！还有2个帐号也是断断续续，隔一段时间要重启一下，才能下载文件，不然就是卡死！

**Comment by chikungfu** [comment]
我的是无法加载，alist打开阿里云盘一直转圈。

**Comment by wsfyhlo** [comment]
> > 
> 
> 我用的方法是更换手机号，更换为一个未注册的手机号，然后可以正常使用后换回原来手机号

有效，谢谢大佬

**Comment by Ccccx159** [comment]
> 我的是无法加载，alist打开阿里云盘一直转圈。

我在两个alist的docker实例中挂载同一个阿里云盘（非共享）也会出现这个情况。同一个阿里云盘仅挂载一次，能正常使用，版本3.11.0

**Comment by foxxorcat** [comment]
可以等待#3437的pr合并后尝试新的api

**Comment by ilonglong** [comment]
> 阿里云盘电脑版，登录设备管理中，删除一些设备，注意保留 samsung 帐号。

用这个方式搞定了。

**Comment by at2008** [comment]
> 阿里云盘电脑版，登录设备管理中，删除一些设备，注意保留 samsung 帐号。

请教一下，这个 samsung 设备是哪里来的？

**Comment by mugqsir** [comment]
这个 samsung 设备是哪里来的？

**Comment by mengguyi** [comment]
应该是作者开发alist抓包用的，你看到的 Samsung 设备是alist
