### ISSUE TITLE
markdown 相对路径会解析到上层路径

### ISSUE THREAD

**Issue by shoucandanghehe** [alist-org/alist#3444]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.10.1

### Driver used / 使用的存储驱动

Onedrive / 本地存储

### Describe the bug / 问题描述

markdown 使用相对路径链接会解析到上层路径
![image](https://user-images.githubusercontent.com/51957264/219094738-a8e3871e-f6ed-40d5-a376-fceffc15efa5.png)
![image](https://user-images.githubusercontent.com/51957264/219094855-3ce5ca47-7032-43c2-8372-b655c2389cf8.png)

### Reproduction / 复现链接

https://alist.呵呵.com/test

**Comment by Xhofe** [comment]
你当前的路径为 `/test` 而不是 `/test/`， 所以`./` 指向的就是 `/`，没有问题。

**Comment by tiankaima** [comment]
> 你当前的路径为 `/test` 而不是 `/test/`， 所以`./` 指向的就是 `/`，没有问题。

挖个坟, 不是很理解, 现在前端默认的 `href` 不也不包含这个结尾的 `/` 吗, 这真的算预期行为吗?

<img width="356" alt="图片" src="https://github.com/alist-org/alist/assets/91816094/13ff8eab-158e-4eea-b738-e88b98834036">

我的意思是, 在前端点击的所有链接, 最后都不会正确渲染这个链接/图片, 是否应该重新考虑一下这里的逻辑, 总不可能手动将所有链接设置成绝对地址吧.

考虑两方面的 fix:
1. 服务端所有目录返回地址 + `/`
2. 调整 markdown 渲染逻辑 所有 `<img>` `<a>` `src/href`

下面是个图片 & 相对路径的 temp fix:
```html
<script>
window.addEventListener('load', function() {
    function updatePaths() {
        var anchors = document.querySelectorAll('a[href], img[src]');
        var currentAddr = window.location.origin + window.location.pathname.replace(/\/$/, '');
        anchors.forEach(function(element) {
            var attr = element.tagName === 'A' ? 'href' : 'src';
            var path = element.getAttribute(attr);
            if (path && !path.includes('://') && !path.startsWith('//')) {
                element.setAttribute(attr, currentAddr + '/' + path);
            }
        });
    }

    updatePaths(); // Initial call to update existing elements
    
    var observer = new MutationObserver(updatePaths);
    observer.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['href', 'src'] });
});
</script>
```

如果需要的话我也可以帮忙 PR, 但是不清楚项目结构, 需要的话还请指出需要修改哪些代码.
