### ISSUE TITLE
mac守护进程（开机启动）文件夹路径到底怎么填写

### ISSUE THREAD

**Issue by Abinthur** [alist-org/alist#3446]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0

### Driver used / 使用的存储驱动

macos

### Describe the bug / 问题描述

path_alist 为 AList 所在的路径：/Applications/AAlist/data 和 /Applications/AAlist 均尝试过
path/to/working/dir 为 AList的工作路径：/Applications/AAlist/alist

执行 launchctl load ~/Library/LaunchAgents/ci.nn.alist 加载配置，会报错
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.

### Reproduction / 复现链接

![Snipaste_2023-02-16_09-55-56](https://user-images.githubusercontent.com/62495250/219248194-8123bd8d-6fa9-4e2c-af38-5589cc2e2fc0.jpg)

**Comment by jjm2473** [comment]
不是随便一个地方就行吗，跟workingdir完全没关系，用`--data`参数指定配置文件存放的路径
<img width="549" alt="image" src="https://user-images.githubusercontent.com/3896703/219269273-0596d017-94f3-4bb5-ab7d-6afcb1a3de2f.png">

**Comment by jjm2473** [comment]
不是因为没加--data参数吗

**Comment by hyb1041739742** [comment]
他这个报错好像是因为反复load了，执行这个launchctl load ~/Library/LaunchAgents/ci.nn.alist 之前可以先launchctl unload ~/Library/LaunchAgents/ci.nn.alist 就不会有这个报错

**Comment by hyb1041739742** [comment]
问了deepseek，稍微改了plist文件：

![Image](https://github.com/user-attachments/assets/8b497aae-877d-423d-9136-e17a8c16702b)

然后给各种文件加了权限（大概就是加执行权限，然后读写权限，归属）
chmod 644 ~/Library/LaunchAgents/ci.nn.alist.plist
chmod +x ~/Documents/Alist/alist
sudo chown $(whoami) ~/Library/LaunchAgents/ci.nn.alist.plist
sudo chown $(whoami) ~/Documents/Alist/alist
sudo chown $(whoami) ~/Documents/Alist

最后重新装载下
launchctl unload ~/Library/LaunchAgents/ci.nn.alist.plist
launchctl load ~/Library/LaunchAgents/ci.nn.alist.plist
成功
