### ISSUE TITLE
更新3.11还是不能访问阿里云盘

### ISSUE THREAD

**Issue by Easyzhan** [alist-org/alist#3449]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.11

### Driver used / 使用的存储驱动

aliyun

### Describe the bug / 问题描述

报错405，网页上报错：
failed get objs: failed to list objs: invalid X-Device-Id

### Reproduction / 复现链接

阿里云

**Comment by Guochengjie** [comment]
我也复现了这个问题，无论是用binary还是docker，但是zxcvbnmzsedr/alist:v3.10.1_fix没有这个问题

**Comment by hejiadong0608** [comment]
我用了 main 的 docker ，今天发现阿里云盘也不能用了，提示 failed get objs: failed to list objs: Device offline

**Comment by liuxin930** [comment]
我也出现了这个问题，提示：failed get objs: failed to list objs: Device offline

**Comment by Duke-li** [comment]
invalid X-Device-Id：error，这个报错。
update the alist, The problem has been solved.
问题已经解决了，更新一下alist

**Comment by keeYuc** [comment]
invalid X-Device-Id

**Comment by keeYuc** [comment]
docker pull xhofe/alist:latest arm64还是报错 4e6967bada99

**Comment by seryte** [comment]
xhofe/alist:latest
8b72eb2e3eea
`failed get objs: failed to list objs: Device offline
`

**Comment by liuxin930** [comment]
依旧报错



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月20日 12:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alist-org/alist] 更新3.11还是不能访问阿里云盘 (Issue #3449) |

invalid X-Device-Id：error，这个报错。
update the alist, The problem has been solved.
问题已经解决了，更新一下alist

**Comment by sanroot3** [comment]
同样还有failed get objs: failed to list objs: invalid X-Device-Id 这个问题
