### ISSUE TITLE
3.11.0  guest用户可以通过搜索或者地址栏输入地址访问隐藏文件

### ISSUE THREAD

**Issue by niylin** [alist-org/alist#3452]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.11

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

guest用户可以通过搜索或者地址栏输入地址访问隐藏文件,
尝试加密并应用到子文件夹后,依然可以通过上述方法访问文件,比如加密了a文件夹,无法直接访问a文件夹,但可以通过上述方法访问a文件夹之内子文件夹

### Reproduction / 复现链接

1

**Comment by anwen-anyi** [comment]
`可以通过上述方法访问a文件夹之内子文件夹` 是因为你没有勾选哪个后面应用到子文件夹
