### ISSUE TITLE
打开3.0及以后版本无法正常使用

### ISSUE THREAD

**Issue by bzhltl** [alist-org/alist#3453]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.0.0及以后版本

### Driver used / 使用的存储驱动

全部无法使用

### Describe the bug / 问题描述

打开v3.0.0以后版本alist.exe会显示
This is a command line tool.
You need to open cmd.exe and run it from there.
然后就无法使用了
https://smms.app/image/JNY1FADMHbzga7t

### Reproduction / 复现链接

无

### Logs / 日志

截图：https://smms.app/image/JNY1FADMHbzga7t

**Comment by anwen-anyi** [comment]
仔细阅读文档 https://alist.nn.ci/zh/
