### ISSUE TITLE
mac上使用挂载alist的百度云盘，上传文件的时候提示"不能完成此操作，因为你没有权限访问"

### ISSUE THREAD

**Issue by Jesn** [alist-org/alist#3458]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

image: 1cd44fabc26c

### Driver used / 使用的存储驱动

baidu

### Describe the bug / 问题描述

mac上使用挂载alist的百度云盘，上传文件的时候提示"不能完成此操作，因为你没有权限访问"，文件夹可以上传上去，但是所有文件类的都上传不了，提示这个，测试了下阿里云盘是可以上传的

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/5728274/219313575-3806f4d2-eed9-4b59-999f-14f866600fad.png)

**Comment by curryhendry** [comment]
请问解决了吗？我也是这个问题
