### ISSUE TITLE
3.11.0下，图片预览错误，直接提示code 401

### ISSUE THREAD

**Issue by OuOumm** [alist-org/alist#3469]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.11.0

### Driver used / 使用的存储驱动

阿里云，tb盘，夸克

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/43441064/219432199-a86d20b0-93a0-4fb8-9b49-990794f38044.png)
![image](https://user-images.githubusercontent.com/43441064/219432303-e2ed2df3-c7b7-46ff-b7b0-88e17ea386c8.png)
![image](https://user-images.githubusercontent.com/43441064/219432349-3cbed2c2-9c06-457c-b10a-970e0fc492ab.png)
![image](https://user-images.githubusercontent.com/43441064/219432477-9165adce-a6a1-4bd9-bffc-52b40a18015d.png)

在点开预览后点击下载图片提示401，或者直接下载一个图片文件名但是后缀名是xml的文件，0kb。

![image](https://user-images.githubusercontent.com/43441064/219433044-4c4775c7-eb2c-4a61-aad6-4f0f24af2d70.png)

![image](https://user-images.githubusercontent.com/43441064/219432932-06fa3014-a517-45d4-8e02-0d9221a702d4.png)

如果在这个界面点下载可以直接下载，但是如果点复制连接之后，在去浏览器粘贴地址后，跳转到401的那张图，code401
![image](https://user-images.githubusercontent.com/43441064/219434016-f741d1b6-af23-4f7e-845e-39634885fdb6.png)

### Reproduction / 复现链接

https://pan.warhut.cn/Al/Updata

### Logs / 日志

![image](https://user-images.githubusercontent.com/43441064/219434263-c73427a7-4184-4a7d-bb91-389c0c5a089a.png)

**Comment by Xhofe** [comment]
这看起来应该是你的中间某个步骤（反向代理/CDN）的问题丢失了sign，而不是alist的问题
