### ISSUE TITLE
百度网盘无法获取刷新令牌

### ISSUE THREAD

**Issue by zzx** [alist-org/alist#3475]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

百度网盘无法获取刷新令牌
错误代码：redirect_uri_mismatch
错误信息：Invalid redirect uri

### Reproduction / 复现链接

https://openapi.baidu.com/oauth/2.0/authorize?response_type=code&client_id=iYCeC9g08h5vuP9UqvPHKKSVrKFXGa1v&redirect_uri=https://tool.nn.ci/baidu/callback&scope=basic,netdisk&qrcode=1

**Comment by Xhofe** [comment]
我不知道你在哪里看的这个地址，文档中已经修改了

**Comment by Gokou-Ruri** [comment]
> 我不知道你在哪里看的这个地址，文档中已经修改了
https://alist-doc.nn.ci/docs/driver/baidu/
新的token获取链接似乎也过期了。
`您遇到了错误！
`错误代码：redirect_uri_mismatch
`错误信息：Invalid redirect uri
