### ISSUE TITLE
谷歌云盘的团队盘根目录ID如何填写

### ISSUE THREAD

**Issue by duansix** [alist-org/alist#3477]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如标题所说，目前版本的Alist只能填写团队盘的子文件夹的ID，无法填写或读取团队盘的根目录ID  个人盘是root 那团队盘是什么呢？

**Comment by hoey94** [comment]
遇到了相同的问题。
