### ISSUE TITLE
189CloudStrong Error 天翼云盘异常

### ISSUE THREAD

**Issue by Juhaoyang** [alist-org/alist#3478]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.10.1

### Driver used / 使用的存储驱动

189cloud个人版

### Describe the bug / 问题描述

Failed init storage: Post "https://api.nn.ci/ocr/file/json": x509: certificate signed by unknown authority
自己网站的证书是TrustAsia.Inc颁发的，不可能是未知机构。

### Reproduction / 复现链接

https://dl.juhaoyang.xyz

**Comment by Juhaoyang** [comment]
> ### See
> 1. 56% [天翼云盘账号状态 ocr error #1501](https://github.com/alist-org/alist/issues/1501)

but this error is different from your link

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/global.html#ocr-api
