### ISSUE TITLE
天翼云个人网盘登录报错

### ISSUE THREAD

**Issue by Jesn** [alist-org/alist#3481]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

latest

### Driver used / 使用的存储驱动

天翼云

### Describe the bug / 问题描述

错误信息
```
Failed init storage: Post "https://api.nn.ci/ocr/file/json": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/5728274/219598931-a3849416-a552-4e6a-b693-ad823f922304.png)

**Comment by cstxxr** [comment]
1、驱动：天翼云盘客户端
2、设置：关闭ocr
3、挂载：登录后可能需要进行一次验证码输入，手动输入下即可
over
天翼云盘使用有问题，因为没有关闭ocr的选项，也许是这个问题。

**Comment by love5241** [comment]
开启ocr选项
