### ISSUE TITLE
阿里云盘出现了： ailed to list objs: not found device info

### ISSUE THREAD

**Issue by Attiv** [alist-org/alist#3482]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0

### Driver used / 使用的存储驱动

阿里

### Describe the bug / 问题描述

ailed to list objs: not found device info

### Reproduction / 复现链接

http://107.173.144.111:5244/ali

### Logs / 日志

之前好好的，今天突然就不能访问了
![CleanShot 2023-02-17 at 17 04 07@2x](https://user-images.githubusercontent.com/15698129/219600710-485011b7-f973-4409-9c55-2047de7100c7.png)

**Comment by cs-star** [comment]
是好是坏 重启下又正常 有时候非常缓慢

**Comment by NeesonD** [comment]
老哥，咋解决的

**Comment by Attiv** [comment]
@NeesonD 更新了下

**Comment by ohmyarch** [comment]
建议再打开这个issue，最新版也时不时会出现，重启服务可能会暂时解决
