### ISSUE TITLE
Webdav 不支持子目录

### ISSUE THREAD

**Issue by BakaJzon** [alist-org/alist#3483]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.11.0

### Driver used / 使用的存储驱动

Local, Onedrive

### Describe the bug / 问题描述

webdav不支持子目录
路径设置为 `<domain>/alist` ,访问 `alist/dav` 出错,建议添加子目录支持

### Reproduction / 复现链接

请忽略证书错误，流量有限，请勿下载。

**Comment by BakaJzon** [comment]
另：`/dav` 有其它用途，不能修改反代配置

**Comment by BakaJzon** [comment]
@Xhofe 为什么标记无效呢？这个功能可以有吧？

**Comment by Xhofe** [comment]
之前提供的链接打不开。

**Comment by BakaJzon** [comment]
emmm，机子关了，明天下午试试？（只是笔记本，见谅
user upload
pwd xxx123456xxx
winscp上所有本地存储会多出一个同名文件夹，打开404，onedrive直接500

或者本地将alist配置
{"site_url" : "http://127.0.0.1:5245/alist" ...}
用caddy反代至5245
```caddyfile
http://127.0.0.1:5245

redir /alist /alist/
handle_path /alist/* http://127.0.0.1:5244
```
访问`/alist/dav`出问题，我机子上`/dav`已被占用，不能改

**Comment by pluto6496** [comment]
之前用nginx反代alist到一个子目录，网页端是正常的，webdav我没有测试。更新3.12.0之后网页端的反代打不开，浏览器提示重定向次数过多。webdab反代也无法正常打开。

**Comment by Xhofe** [comment]
> 之前用nginx反代alist到一个子目录，网页端是正常的，webdav我没有测试。更新3.12.0之后网页端的反代打不开，浏览器提示重定向次数过多。webdab反代也无法正常打开。

需要修改反代方式 具体见
https://github.com/alist-org/alist/commit/6c2f3486fc155e795026d08cf55d559f3e63595a

**Comment by pluto6496** [comment]
> 

按文档中的描述修改了nginx配置，首页加载的`index.5805ed79.js`文件和`index.659f4289.css`文件返回的`content-type`都是`application/json; charset=utf-8`，导致浏览器拒绝执行。首页显示空白，不知道是我配置的问题还是怎么样

**Comment by shenlijun** [comment]
> 

请问Apache需要怎么修改？
原本的3.11这样是可以的，新的版本就会提示重定向次数过多

<VirtualHost *:80>
    ServerName myapp.example.com
    ServerAdmin webmaster@example.com
    DocumentRoot /www/myapp/public

    AllowEncodedSlashes NoDecode
    ProxyPass "/" "http://127.0.0.1:5244/" nocanon
</VirtualHost>

**Comment by shenlijun** [comment]
> > 之前用nginx反代alist到一个子目录，网页端是正常的，webdav我没有测试。更新3.12.0之后网页端的反代打不开，浏览器提示重定向次数过多。webdab反代也无法正常打开。
> 
> 需要修改反代方式 具体见 [6c2f348](https://github.com/alist-org/alist/commit/6c2f3486fc155e795026d08cf55d559f3e63595a)

请问Apache需要怎么修改？
之前3.11的时候这样是可以的，新的版本会提示重定向次数过多

`<VirtualHost *:80>
    ServerName myapp.example.com
    ServerAdmin webmaster@example.com
    DocumentRoot /www/myapp/public

    AllowEncodedSlashes NoDecode
    ProxyPass "/" "http://127.0.0.1:5244/" nocanon
</VirtualHost>`

**Comment by shenlijun** [comment]
> > 之前用nginx反代alist到一个子目录，网页端是正常的，webdav我没有测试。更新3.12.0之后网页端的反代打不开，浏览器提示重定向次数过多。webdab反代也无法正常打开。
> 
> 需要修改反代方式 具体见 [6c2f348](https://github.com/alist-org/alist/commit/6c2f3486fc155e795026d08cf55d559f3e63595a)

请问Apache需要怎么修改？
之前3.11的时候这样是可以的，新的版本会提示重定向次数过多
```
<VirtualHost *:80>
    ServerName myapp.example.com
    ServerAdmin webmaster@example.com
    DocumentRoot /www/myapp/public

    AllowEncodedSlashes NoDecode
    ProxyPass "/alist" "http://127.0.0.1:5244/alist" nocanon
</VirtualHost>
```

**Comment by shenlijun** [comment]
> > 之前用nginx反代alist到一个子目录，网页端是正常的，webdav我没有测试。更新3.12.0之后网页端的反代打不开，浏览器提示重定向次数过多。webdab反代也无法正常打开。
> 
> 需要修改反代方式 具体见 [6c2f348](https://github.com/alist-org/alist/commit/6c2f3486fc155e795026d08cf55d559f3e63595a)

请问Apache需要怎么修改？
之前3.11的时候这样是可以的，新的版本会提示重定向次数过多

```
<VirtualHost *:80>
    ServerName myapp.example.com
    ServerAdmin webmaster@example.com
    DocumentRoot /www/myapp/public

    AllowEncodedSlashes NoDecode
    ProxyPass "/alist" "http://127.0.0.1:5244" nocanon
</VirtualHost>
```

**Comment by shenlijun** [comment]
> > 之前用nginx反代alist到一个子目录，网页端是正常的，webdav我没有测试。更新3.12.0之后网页端的反代打不开，浏览器提示重定向次数过多。webdab反代也无法正常打开。
> 
> 需要修改反代方式 具体见 [6c2f348](https://github.com/alist-org/alist/commit/6c2f3486fc155e795026d08cf55d559f3e63595a)

请问Apache需要怎么修改？
之前3.11的时候这样是可以的，新的版本会提示重定向次数过多

```
<VirtualHost *:80>
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>

<VirtualHost *:443>
    ServerName myapp.example.com
    DocumentRoot /www/myapp/public
    Protocols h2 h2c http/1.1
    SSLEngine on
    SSLCertificateFile ccc.fu
    SSLCertificateKeyFile ccc.key
    ProxyPreserveHost On
    ProxyRequests off
    AllowEncodedSlashes NoDecode
    ProxyPass "/alist" "http://127.0.0.1:5244/alist" nocanon
</VirtualHost>
```
