### ISSUE TITLE
KODI客户端不能应用阿里云盘里的同人图和海报图片

### ISSUE THREAD

**Issue by sunxiaochuan2506** [alist-org/alist#3492]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v.3.11.0

### Driver used / 使用的存储驱动

Kodi

### Describe the bug / 问题描述

![QQ图片20230218055747](https://user-images.githubusercontent.com/125409799/219802053-3a447b2e-4893-4873-80bf-2d2a97c1144c.png)

原来是可以的。并且阿里云盘里有的电影，在Alist上却没有。

### Reproduction / 复现链接

别的网盘没问题

**Comment by sunxiaochuan2506** [comment]
我运用的是阿里云盘/分享的方式挂载到KODI上，Alist里用网页可以打开预览图片也能下载，但挂到KODI上确没有任何显示。
【以前可以刮削显示出海报，网盘里的文件我没有动，这次事件后就不显示了】

**Comment by tanghongxin** [comment]
@sunxiaochuan2506 
我遇到与你相同的问题，经实验得出的解决方案：
1. 目录下含有 nfo 等刮削文件时，KODI 将优先进行读取。此时要求 alist 分配的用户具有写入权限；这也意味着存储类型需要是「阿里云盘」而非「阿里云盘分享」
2. 挂载目录下只有单个视频文件时，KODI 将通过网络进行刮削（需确保网络通畅），此时对 alist 分配的用户权限没有要求

有关 KODI 写入权限的相关帖子：
- https://forum.kodi.tv/showthread.php?tid=352642
- https://forum.kodi.tv/showthread.php?tid=371418
