### ISSUE TITLE
百度网盘 refresh token 刷新不出来

### ISSUE THREAD

**Issue by TTtrace** [alist-org/alist#3493]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

点击[文档](https://alist.nn.ci/zh/guide/drivers/baidu.html#%E5%88%B7%E6%96%B0%E4%BB%A4%E7%89%8C)中的刷新令牌的链接后，通过百度登录确认，可是 refresh token 始终刷新不出来。

### Reproduction / 复现链接

https://openapi.baidu.com/oauth/2.0/authorize?response_type=code&client_id=iYCeC9g08h5vuP9UqvPHKKSVrKFXGa1v&redirect_uri=https://alist.nn.ci/tool/baidu/callback&scope=basic,netdisk&qrcode=1

### Logs / 日志

<img width="634" alt="image" src="https://user-images.githubusercontent.com/39454079/219824737-f0a34daa-af6f-4d6d-b7f2-2a2f237351c6.png">

**Comment by Xhofe** [comment]
若无法访问https://api.nn.ci/
请挂代理
