### ISSUE TITLE
阿里云盘挂载后可以浏览并播放视频，但无法下载文件

### ISSUE THREAD

**Issue by xxxzsgxxx** [alist-org/alist#3509]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

之前旧版有失败问题，升级到最新版后从装并配置阿里云盘后，浏览文件及文件夹都正常，甚至播放云盘里面的视频也正常，但就是无法下载。

### Reproduction / 复现链接

http://192.168.50.18:5244/d/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/ebook-1/Screenshot_20230123_102138_com.jingdong.app.mall.jpg

### Logs / 日志

INFO   2023-02-18 22:35:52 ( 1676730952 )   Opening LogFile...
INFO   2023-02-18 22:35:52 ( 1676730952 )   DownloadEngine State Changed : Unkown -> Starting...
DEBUG  2023-02-18 22:35:52 ( 1676730952 )   DownloadEngine is Starting...
INFO   2023-02-18 22:35:52 ( 1676730952 )   Trying to Start Download for -> https://cn-beijing-data.aliyundrive.net/bk88FP8a/65669770/63ce16a04aff85371a344a2694279e90fa4197e6/63ce16a087d84a4fd8fb4efeacf02e8cf3b5176d?di=bj29&dr=65669770&f=63ce16a04aff85371a344a2694279e90fa4197e6&response-content-disposition=attachment; filename*=UTF-8''Screenshot_20230123_102138_com.jingdong.app.mall.jpg&security-token=Xy5TYO27uz2prOegno=&u=26a7bc67a00c4d1698f15e7accd3f9ce&x-oss-access-key-id=STS.NTWLaiGt3cw16rbQKv8J3JvUV&x-oss-expires=1676745352&x-oss-signature=3ocbmxT97hJkTkN87qf3knlA4kNobMygXEAI5jywEv0=&x-oss-signature-version=OSS2
INFO   2023-02-18 22:35:52 ( 1676730952 )   DownloadID = 839 , Protocol = HTTPS
INFO   2023-02-18 22:35:52 ( 1676730952 )   New Socket(s) Created. MaxAllowedConnection = 8 And ActiveSockets = 1
DEBUG  2023-02-18 22:35:52 ( 1676730952 )   Socket ( 1 )  Connecting to  211.154.222.74:443 ...
INFO   2023-02-18 22:35:52 ( 1676730952 )   Initializing SslHandShake for Socket (1 )
INFO   2023-02-18 22:35:52 ( 1676730952 )   SslHandShake OK for Socket ( 1 )
DEBUG  2023-02-18 22:35:52 ( 1676730952 )   SegmentManager Created a New Segment and now has 1 Segments.
DEBUG  2023-02-18 22:35:52 ( 1676730952 )   Socket ( 1 ) HttpStatus =  HTTP_STATE_VOID  RoundNumberServer = 0 and RoundNumberProxy = 0
INFO   2023-02-18 22:35:52 ( 1676730952 )   Sending Http-GET  for Socket ( 1 )  Range = 0-
DEBUG  2023-02-18 22:35:52 ( 1676730952 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_VOID  ->  HTTP_STATE_GET_SENT 
INFO   2023-02-18 22:35:52 ( 1676730952 )   GET Sent : 
<< GET /bk88FP8a/65669770/63ce16a04aff85371a344a2694279e90fa4197e6/63ce16a087d84a4fd8fb4efeacf02e8cf3b5176d?di=bj29&dr=65669770&f=63ce16a04aff85371a344a2694279e90fa4197e6&response-content-disposition=attachment; filename*=UTF-8''Screenshot_20230123_102138_com.jingdong.app.mall.jpg&security-token=Xy5TYO27uz2prOegno=&u=26a7bc67a00c4d1698f15e7accd3f9ce&x-oss-access-key-id=STS.NTWLaiGt3cw16rbQKv8J3JvUV&x-oss-expires=1676745352&x-oss-signature=3ocbmxT97hJkTkN87qf3knlA4kNobMygXEAI5jywEv0=&x-oss-signature-version=OSS2 HTTP/1.1
Host: cn-beijing-data.aliyundrive.net
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.49
Accept: */*
Accept-Encoding: identity
Accept-Language: en-US,en;q=0.9
Accept-Charset: *
Origin: https://cn-beijing-data.aliyundrive.net/
Referer: https://cn-beijing-data.aliyundrive.net/bk88FP8a/65669770/63ce16a04aff85371a344a2694279e90fa4197e6/63ce16a087d84a4fd8fb4efeacf02e8cf3b5176d?di=bj29&dr=65669770&f=63ce16a04aff85371a344a2694279e90fa4197e6&response-content-disposition=attachment; filename*=UTF-8''Screenshot_20230123_102138_com.jingdong.app.mall.jpg&security-token=CAIS+gF1q6Ft5B2yfSjIr5fiB9vdqqsS1LXaNFTTtUsjNMUfpbP+tDz2IHFPeHJrBeAYt/oxmW1X5vwSlq5rR4QAXlDfNX+qRh7ZqVHPWZHInuDox55m4cTXNAr+Ihr/29CoEIedZdjBe/CrRknZnytou9XTfimjWFrXWv/gy+QQDLItUxK/cCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF+97DRbG/dNRpMZtFVNO44fd7bKKp0lQLukMWr/wq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J+q/zxhTPrMnpkSlacGoABD+bbUGQMlMFwDUm8wUPmZXgV1fPK7vGjIfZIsy/g1DwP4V5pSr5bc14RpFc22UHjLeDet57EGjoPmqonZsPxN7nFCGiYYOOX/tuslijaWOAVphSSAWNIzVzgHZSMpsmjjtHIWSRSi4PIhWej1a+y3bi2eXy5TYO27uz2prOegno=&u=26a7bc67a00c4d1698f15e7accd3f9ce&x-oss-access-key-id=STS.NTWLaiGt3cw16rbQKv8J3JvUV&x-oss-expires=1676745352&x-oss-signature=3ocbmxT97hJkTkN87qf3knlA4kNobMygXEAI5jywEv0=&x-oss-signature-version=OSS2
Range: bytes=0-

>>
INFO   2023-02-18 22:35:52 ( 1676730952 )   All Response Headers For Socket ( 1 ) :
INFO   2023-02-18 22:35:52 ( 1676730952 )   
<<HTTP/1.1 403 Forbidden
Server: AliyunOSS
Date: Sat, 18 Feb 2023 14:35:52 GMT
Content-Type: application/xml
Content-Length: 297
Connection: keep-alive
x-oss-request-id: 63F0E24868127D3031E14A7E
Vary: Origin
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, HEAD
Access-Control-Expose-Headers: ETag
Access-Control-Max-Age: 0
x-oss-server-time: 4>>

DEBUG  2023-02-18 22:35:52 ( 1676730952 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_GET_SENT  ->  HTTP_STATE_PARSING_HTTP_HEADER 
DEBUG  2023-02-18 22:35:52 ( 1676730952 )   Status Code For Socket (1 ) = 403
ERROR  2023-02-18 22:35:52 ( 1676730952 )   Handling Error - Socket ( 1 ) - SocketState =  HTTP_STATE_PARSING_HTTP_HEADER  ErrorText = HTTP/1.1 403 Forbidden
ERROR  2023-02-18 22:35:52 ( 1676730952 )   HTTP/1.1 403 Forbidden
INFO   2023-02-18 22:35:52 ( 1676730952 )   DownloadEngine State Changed : Starting... ( 4 ) -> Error
DEBUG  2023-02-18 22:35:52 ( 1676730952 )   Socket ( 1 ) All Headers have been Parsed. Now HttpStatus =  HTTP_STATE_PARSING_HTTP_HEADER  And StatusCode = 403
ERROR  2023-02-18 22:35:52 ( 1676730952 )   Error Occurred. HTTP/1.1 403 Forbidden
DEBUG  2023-02-18 22:35:53 ( 1676730953 )   DownloadEngine Is Terminating. EngineState = Error.
DEBUG  2023-02-18 22:35:53 ( 1676730953 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_PARSING_HTTP_HEADER  ->  HTTP_STATE_VOID 
INFO   2023-02-18 22:35:53 ( 1676730953 )   Closing LogFile.

**Comment by JayHawSG** [comment]
一样

**Comment by Xhofe** [comment]
duplicate with #3423
