### ISSUE TITLE
FR 添加WebDAV对site_url的支持

### ISSUE THREAD

**Issue by BakaJzon** [alist-org/alist#3510]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

代码中 webdav 的路径是硬编码到`/dav`的，使用子目录反代时虽然能用，但有各种问题：
1. 仅本地存储能用，其他的报 500 错误
2. 本地存储出现幽灵目录，如`/video/anime`下会有一个同名文件夹`/video/anime/anime`，点进去报404（winscp）

应该是硬编码的锅。

*另：添加存储页中Onedrive默认fallback已经挪了，这里也请改一下*

### Suggested solution / 实现思路

将源码里的`/dav`替换成类似`<site_url>/dav`的代码。
或者提取 site_url 的子目录（如果有），然后用`/<subdir>/dav`
由于 alist 本来就支持子目录反代，只要修改输出部分应该就够了。（ handle 部分不用管）

## Alist config.json
``` json
{...
  "site_url" : "/alist"
...}
```

## 反代
Caddy (Recommended)
``` Caddyfile
http://127.0.0.1:10086

redir /alist /aliat/
handle_path /alist/* {
  reverse_proxy http://127.0.0.1:5244
}
```
**请勿反代`/dav`路径，以还原问题。**

nginx
```
location /alist/ {
  reverse_proxy http://127.0.0.1:5244
  ...
}
```

## 测试
使用`http://127.0.0.1:10086/alist/dav`访问
~~*而不是`/dav`*~~

**Comment by Xhofe** [comment]
This has been done in 6c2f3486fc155e795026d08cf55d559f3e63595a
