### ISSUE TITLE
有没有可能支持MAC系统？

### ISSUE THREAD

**Issue by JXA-a** [alist-org/alist#3516]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

有没有可能支持MAC系统？
目前都没有制作MAC系统的挂载

**Comment by wangwuxuan2011** [comment]
darwin即macos系统
amd64对应Intel型号芯片
arm64对应Apple M系列芯片

**Comment by JXA-a** [comment]
> darwin即macos系统 amd64对应Intel型号芯片 arm64对应Apple M系列芯片

原来如此 感谢感谢 有安装教程吗
