### ISSUE TITLE
在子目录反代下的epub.js路径问题

### ISSUE THREAD

**Issue by notch1p** [alist-org/alist#3519]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.11.0

### Driver used / 使用的存储驱动

does not matter

### Describe the bug / 问题描述

根据[Documentation](https://alist.nn.ci/zh/faq/howto.html#%E6%80%8E%E4%B9%88%E6%B7%BB%E5%8A%A0epub%E9%98%85%E8%AF%BB): 3.7及之后版本默认添加
> "EPUB.js":"/static/epub.js/viewer.html?url=$e_url"

**对于设置了nginx二级目录反代的情况，如此设置会造成epub.js路径错误返回404的情况。**
应该改为<code>/<b>{site_url}</b>/static/epub.js/viewer.html?url=$e_url</code>, 其中`site_url`为`data/config.json`的值(不带域名也可)，个人测试正常。

个人建议顺便修正说明文档，小坑

### Reproduction / 复现链接

上述条件下预览epub即可复现

### Logs / 日志

Chrome console log:
`viewer.html:1          Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by BakaJzon** [comment]
alist 好多子目录反代问题啊
😕

**Comment by BoYanZh** [comment]
真的有必要让前端去获取`data/config.json`的值么

**Comment by notch1p** [comment]
只是说这两个值应该是一样的。我觉得在文档里特别说明一下就行，或者干脆不要设置epubjs的默认值

**Comment by BoYanZh** [comment]
https://github.com/alist-org/docs/pull/153
