### ISSUE TITLE
提示failed get objs: failed to list objs: not found device info

### ISSUE THREAD

**Issue by cjy2812163** [alist-org/alist#3521]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.1.1

### Driver used / 使用的存储驱动

docker

### Describe the bug / 问题描述

x86软路由运行的docker环境下，使用的是阿里云盘，部署完成后打开文件夹直接提示failed get objs: failed to list objs: not found device info，百度查说是没有实名的原因导致，但确实已经实名了。

### Reproduction / 复现链接

https://github.com/alist-org/alist

### Logs / 日志

failed get objs: failed to list objs: not found device info

**Comment by ohmyarch** [comment]
一样的问题，重启服务可能会暂时解决

**Comment by make145** [comment]
同样的问题，发现刷新令牌，填入后，点保存，然后再次打开查看，发现已经变了

**Comment by dfvips** [comment]
一样的问题，按上面的解决方案，解决不了。

**Comment by lixh00** [comment]
俺也一样，如图所示
![image](https://user-images.githubusercontent.com/72033265/220507423-4fbf99d9-c8d2-47db-902c-e7509b0b2815.png)

**Comment by cjy2812163** [comment]
> 一样的问题，重启服务可能会暂时解决

暂时是多久？目前我已成功使用3天了。

**Comment by ChiehJang** [comment]
docker restart [你的docker服务名称]  
临时解决问题。

**Comment by hjkltop** [comment]
使用新的驱动 阿里云盘open 解决。

**Comment by timorpic** [comment]
failed get objs: failed to list objs: User not found
