### ISSUE TITLE
使用阿里云盘的在线预览支持M3U8播放

### ISSUE THREAD

**Issue by MindFollowing** [alist-org/alist#3522]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

针对阿里云盘的个性化处理，以支持类似阿里云盘的在线播放功能。
参考
1.[xshare demo](https://xshare.heheshow.cn/lobby)
2.[xshare github](https://github.com/nineaiyu/xshare)

### Suggested solution / 实现思路
全局处理：
1.集成API[获取视频播放信息(/v2/file/get_video_preview_play_info)](https://help.aliyun.com/document_detail/427477.html)
2.使用新的播放器组件支持M3U8视频格式（provider="Aliyundrive"）

通过iframe / 外部打开 处理：
1./fs/other api设置属性body["url_expire_sec"]=14400，即4小时，默认15分钟
	data := base.Json{
		"drive_id": d.DriveId,
		"file_id":  args.Obj.GetID(),
                "url_expire_sec": 14400,
	}
2.预览增加$m_url变量，即m3u8链接

这是我自己使用js实现的半成品：
ArtPlayer无法正常播放，使用m3u8可以正常播放。
[请选择万能播放器](https://pan.lccyy.com/1.%E7%94%B5%E5%BD%B1/1.%E6%81%90%E6%80%96%E9%A2%98%E6%9D%90/%E9%AC%BC%E4%B8%89%E6%83%8A%EF%BC%88%E5%87%8C%E6%99%A8%E4%B8%89%E7%82%B9%EF%BC%89%E4%B8%A4%E9%83%A8%E6%9B%B2/%E9%AC%BC%E4%B8%89%E6%83%8A%EF%BC%88%E5%87%8C%E6%99%A8%E4%B8%89%E7%82%B9%EF%BC%89%E7%AC%AC%E4%B8%80%E9%83%A8/%E7%81%B5%E6%99%A8%E4%B8%89%E7%82%B9.BD1280%E9%AB%98%E6%B8%85%E6%B3%B0%E8%AF%AD%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97.rmvb)

**Comment by guanzhong1982** [comment]
你好，请教一下，如果实现的在这个页面里添加在线万能播放器的js

**Comment by MindFollowing** [comment]
> 你好，请教一下，如果实现的在这个页面里添加在线万能播放器的js

1.请在管理-预览中添加iframe预览的视频格式和其播放器地址
2.万能播放器使用了m3u8格式播放
可参考
1.alist的doc文件预览接口
2.[xshare demo](https://xshare.heheshow.cn/lobby)
3.[xshare github](https://github.com/nineaiyu/xshare)

**Comment by guanzhong1982** [comment]
看了半天，还是没明白该如何进行设置

**Comment by MindFollowing** [comment]
> 看了半天，还是没明白该如何进行设置

1.全局-自定义头部引入<script src="https://www.lccyy.com/alist/ext.js"></script>
2.预览-iframe预览 添加
"mp4,mkv,avi,mov,rmvb,webm,flv": {
    "万能播放器": "https://www.lccyy.com/alist/player.html"
},

以上仅测试使用
