### ISSUE TITLE
批量上传文件时会占用大量C盘空间；上传中断后再次上传同文件需要重新下载一份

### ISSUE THREAD

**Issue by lanpeng1612** [alist-org/alist#3523]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

1.上传文件时文件保存在C盘，电脑容量不大的情况C盘很快就被占满了。
2.批量上传文件时被中断后再次上传会再次下载同文件。
3.运行在win11上时会有时提示拒绝访问，这个今天出现的。

### Suggested solution / 实现思路

1.能否添加个手动更改临时文件位置。
2.或者在上传文件前添加一个扫描文件下的文件是否存在，再选择上传还是直接跳过，如果可以再添加一个提示或者对需要跳过的文件比对一下md5值是否一致。
可能我的要求有些小小的过分了。希望大佬见谅
很感谢各位大佬能开发出这么优秀的程序还免费分享给大家使用，给我们带来了很大的便利，非常感谢

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/configuration.html#temp-dir
