### ISSUE TITLE
使用docker部署时，Alist存储间的临时缓存文件夹映射

### ISSUE THREAD

**Issue by chung1912** [alist-org/alist#3526]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我用的docker部署，从一个网盘复制到另一个网盘的行为中，缓存路径在哪里？我想把这个缓存路径映射到一个空间比较大的其他盘，系统盘太小了，不够用

### Suggested solution / 实现思路

我用的docker部署，从一个网盘复制到另一个网盘的行为中，缓存路径在哪里？我想把这个缓存路径映射到一个空间比较大的其他盘，系统盘太小了，不够用

**Comment by chung1912** [comment]
我发现离线下载时，缓存位置是在temp文件夹，但是复制的时候，temp文件夹并没有出现任何缓存文件，所以复制的时候应该缓存在了其他位置，我想找到这个文件夹，将其映射出来

**Comment by BoYanZh** [comment]
就是在`config.json`的`temp_dir`里，和离线下载一样。

**Comment by chung1912** [comment]
> 

"temp_dir": "data/temp"，我正在复制过程当中，一直观察这个文件夹，没有发现有任何“临时文件”出现，但是如果是离线下载，立即能看到会产生一个aria2文件夹，并且里面能看到临时文件
