### ISSUE TITLE
多选或一键删除任务

### ISSUE THREAD

**Issue by sakura776** [alist-org/alist#3528]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

当不小心复制错一个文件夹，而里面文件特别多的话，慢慢删除简直痛苦。所以能不能增加一个快速删除任务的选项

**Comment by ilihu** [comment]
不如搞个一键清空所有正在复制中任务比较简单
