### ISSUE TITLE
希望能在alistV3后台管理-任务里加一个分页查询信息的功能

### ISSUE THREAD

**Issue by aHr1i9** [alist-org/alist#3537]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

当我们在用到前台的复制，上传之类的功能。一旦信息过多，后台查找文件操作失败或者成功就会很麻烦，导致页面加载起来就会有一点点卡。虽然有一个清除功能。不过还是希望老哥能加一个。

### Suggested solution / 实现思路

在后台-任务功能-小模块里加一个分页查询功能，并且可以根据文件操作失败或者成功状态进行查询即可

**Comment by rwshui** [comment]
我也提一个吧，建议除了可以将 复制任务 里面失败错误的筛选出来之外，可以增加一键全部重试，或者单个重试的功能，而不是只有清除，这样可以方便将跨盘复制失败的重传。

**Comment by lanpeng1612** [comment]
我最近上传一文件夹里面有600个个文件，然后经常性的失败或者是被中断了都不知道那些没有成功，又只好重新再来结果还是失败打断了；现在不知道哪些成功了哪些没成功，只好又重来

**Comment by 1298345095** [comment]
me too
