### ISSUE TITLE
打开提示System error: SyntaxError: Invalid regular expression: /?/: Nothing to repeat

### ISSUE THREAD

**Issue by chikungfu** [alist-org/alist#3541]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11 docker或套件

### Driver used / 使用的存储驱动

群晖

### Describe the bug / 问题描述

打开显示System error: SyntaxError: Invalid regular expression: /?/: Nothing to repeat

### Reproduction / 复现链接

 打开显示System error: SyntaxError: Invalid regular expression: /?/: Nothing to repeat

### Logs / 日志

![alist](https://user-images.githubusercontent.com/51909833/220221881-001516cb-7130-4f0c-9483-bdba6ae47823.png)

**Comment by chikungfu** [comment]
> ### See
> 1. 66% [SyntaxError: Invalid regular expression: /?/: Nothing to repeat报错 #2645](https://github.com/alist-org/alist/issues/2645)

你给的链接现在也是提示这个错误。

**Comment by BoYanZh** [comment]
所以你试过那里的解决方案了吗
