### ISSUE TITLE
可否解决下ARM7的`GLIBC_2.28' not found的问题。 我使用的是QNAP的TS-420

### ISSUE THREAD

**Issue by babylife** [alist-org/alist#3542]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://github.com/iranee/qnap-alist-webdav
使用该作者的作品，3.4的版本没有问题，之后的版本无法运行，直接执行二进制后出现了下面的问题：
/share/HDA_DATA/.qpkg/alist/alist: /lib/libc.so.6: version `GLIBC_2.28' not found

arm-x19 | linux-arm-7 的版本， 处理器 | Marvell 1.6GHz

**Comment by BoYanZh** [comment]
musl版本，请

**Comment by babylife** [comment]
> musl版本，请问是哪个，我刚才测试了下面几个，都不行
![image](https://user-images.githubusercontent.com/31977161/220236221-43afdc86-eac1-4d98-b1e4-ec39219f09b9.png)


![image](https://user-images.githubusercontent.com/31977161/220235927-f51e214e-dba6-49ff-b974-00476c20e02f.png)


![image](https://user-images.githubusercontent.com/31977161/220235769-447bcd5a-5c85-4027-8620-ecaf1033b5c4.png)

**Comment by babylife** [comment]
https://github.com/iranee/qnap-alist-webdav/issues/23
这是在QNAP项目地址提交的问题

**Comment by babylife** [comment]
使用MUSL-ARM报错如下
[~] # /share/HDA_DATA/.qpkg/alist/alist
Illegal instruction
使用MUSL-ARM64报错如下：
[~] # /share/HDA_DATA/.qpkg/alist/alist
-sh: /share/HDA_DATA/.qpkg/alist/alist: cannot execute binary file

**Comment by anwen-anyi** [comment]
是否有 `chmod +x alist` 进行授权？

**Comment by Xhofe** [comment]
对不起， 你的glibc版本过低。请尝试自行在目标target编译。

**Comment by BoYanZh** [comment]
估计是现在那个用了musl的版本带了点armv7里没有的，armv8才有的指令所以寄了。
你倒是可以按照 https://github.com/alist-org/alist/blob/d1ab2443f18eecc28515578b0460c23e904d19a7/build.sh#L76 附近的搞法提个pr把armv5 v6 v7的编译命令全塞进去，我看 https://musl.nn.ci/ 还是有那些musl libc的。

**Comment by babylife** [comment]
> 是否有 `chmod +x alist` 进行授权？

已经授权了

**Comment by babylife** [comment]
> 估计是现在那个用了musl的版本带了点armv7里没有的，armv8才有的指令所以寄了。 你倒是可以按照
> 
> https://github.com/alist-org/alist/blob/d1ab2443f18eecc28515578b0460c23e904d19a7/build.sh#L76
> 
> 附近的搞法提个pr把armv5 v6 v7的编译命令全塞进去，我看 https://musl.nn.ci/ 还是有那些musl libc的。

大佬，我是真不会。。。。
