### ISSUE TITLE
索引无法创建，自动把存储加入忽略列表。

### ISSUE THREAD

**Issue by sclodestar** [alist-org/alist#3549]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.11

### Driver used / 使用的存储驱动

alistv3

### Describe the bug / 问题描述

重新拉镜像，删除挂载点，重新建立容器，里面只有小雅一个盘。

创建索引按教程创建，选数据库，点保存，忽略里面空

点重新构建后有如下log：

INFO[2023-02-21 16:06:15] build index for: [/]
INFO[2023-02-21 16:06:15] ignore paths: [/Y仙女]
INFO[2023-02-21 16:06:15] success build index, count: 0

如果我把忽略列表加上/Y仙女，还得得到这样的日志，假如我把/Y仙女删除点保存，并点重新构建，会有如下日志：
INFO[2023-02-21 16:11:16] build index for: [/]
INFO[2023-02-21 16:11:16] ignore paths: [/Y仙女 /Y仙女]
INFO[2023-02-21 16:11:16] success build index, count: 0

这是怎么肥事？

### Reproduction / 复现链接

木有

### Logs / 日志

见上面

**Comment by anwen-anyi** [comment]
小雅也没开启允许索引，自己看文档吧..... 默认是自动跳过索引 他人Alist的
https://alist.nn.ci/zh/config/site.html#允许索引

**Comment by sclodestar** [comment]
> 小雅也没开启允许索引，自己看文档吧..... 默认是自动跳过索引 他人Alist的 [https://alist.nn.ci/zh/config/site.html#允许索引](https://alist.nn.ci/zh/config/site.html#%E5%85%81%E8%AE%B8%E7%B4%A2%E5%BC%95)

我在3.10的时候确实能构建索引，并搜索到小雅的东西

**Comment by sclodestar** [comment]
这么急的关issue。。。

**Comment by anwen-anyi** [comment]
> > 小雅也没开启允许索引，自己看文档吧..... 默认是自动跳过索引 他人Alist的 [https://alist.nn.ci/zh/config/site.html#允许索引](https://alist.nn.ci/zh/config/site.html#%E5%85%81%E8%AE%B8%E7%B4%A2%E5%BC%95)
> 
> 我在3.10的时候确实能构建索引，并搜索到小雅的东西

那是BUG..
