### ISSUE TITLE
谷歌云盘刷新码页面有问题

### ISSUE THREAD

**Issue by kugimiya530** [alist-org/alist#3550]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0 

### Driver used / 使用的存储驱动

nvme ssd

### Describe the bug / 问题描述

Google刷新代码的页面有问题

用自己的api 资讯都跟之前一样 不过之前的都可以

网页改版了以后 就会显示这个

錯誤代碼 400： redirect_uri_mismatch

### Reproduction / 复现链接

https://alist.nn.ci/tool/google/request.html

**Comment by anwen-anyi** [comment]
在创建OA客户端的时候填写重定向URL 你没写仔细看文档~
