### ISSUE TITLE
密码加密/ encrypting data, especially password

### ISSUE THREAD

**Issue by liumingedwin** [alist-org/alist#3552]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

密码在Alist数据库以明文形式出现，有点危险。
希望加密储存。
推荐直接变成SHA256
-----  
To encrypt password in the database

### Suggested solution / 实现思路

储存和读取密码时加密即可

**Comment by zhuangzi926** [comment]
我想使用[bcrypt](https://gowebexamples.com/password-hashing/)来实现数据库内密码的加密处理，但是我不明白这样的更新操作之后是否会导致旧数据库和新的密码存储方式不兼容。

**Comment by XZB-1248** [comment]
> 我想使用[bcrypt](https://gowebexamples.com/password-hashing/)来实现数据库内密码的加密处理，但是我不明白这样的更新操作之后是否会导致旧数据库和新的密码存储方式不兼容。

可以修改一下更新机制，比如在配置文件里写上当前的版本，然后更新之后判断一下，如果是从特定版本更新的，则对数据库进行调整
