### ISSUE TITLE
请求增加软连接功能

### ISSUE THREAD

**Issue by koolca** [alist-org/alist#3553]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

若具备类似linux 的link功能，可以方便分类整合各种资源，以前也有人提出相同需求，请大佬关注一下，谢谢！

**Comment by playingapi365one** [comment]
这个需求以前也提过 被关了   这个问题大概率也会被关掉

**Comment by mengguyi** [comment]
https://github.com/alist-org/alist/issues/1741

**Comment by Xhofe** [comment]
这应该已经在 https://alist.nn.ci/guide/drivers/alias.html 被实现
