### ISSUE TITLE
每天alist 服务都需要重启一次

### ISSUE THREAD

**Issue by dukoalad** [alist-org/alist#3555]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11

### Driver used / 使用的存储驱动

aliyundrive

### Describe the bug / 问题描述

alist.service - Alist service
Loaded: loaded (/etc/system/system/alist.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Tue 2023-02-21 19:58:27 CST; 2h 16min ago
Process: 7936 ExecStart=/opt/alist/alist server (code=exited, status=2)
Main PID: 7936 (code=exited, status=2)
[](url)

### Reproduction / 复现链接

alist.service - Alist service
Loaded: loaded (/etc/system/system/alist.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Tue 2023-02-21 19:58:27 CST; 2h 16min ago
Process: 7936 ExecStart=/opt/alist/alist server (code=exited, status=2)
Main PID: 7936 (code=exited, status=2)

### Logs / 日志

alist.service - Alist service
Loaded: loaded (/etc/system/system/alist.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Tue 2023-02-21 19:58:27 CST; 2h 16min ago
Process: 7936 ExecStart=/opt/alist/alist server (code=exited, status=2)
Main PID: 7936 (code=exited, status=2)
Feb 21 19:58:27 : net/http. (*conn).serve (0xc0208aed20, {0x21ba680, 0xc000a0a180})
Feb 21 19:58:27 :
/opt/hostedtoolcache/go/1.19.5/×64/src/net/http/server.go:19
Feb 21 19:58:27 : net/http.(*Server).Serve.func3 ()
| Feb 21 19:58:27 :
/opt/hostedtoolcache/go/1.19.5/X64/src/net/http/server.go:31
• Feb 21 19:58:27 : runtime.goexit ()
Feb 21 19:58:27 :
/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/asm_amd64.s:1
Feb 21 19:58:27 : created by net/http.(*Server). Serve Feb 21 19:58:27 :
/opt/hostedtoolcache/go/1.19.5/X64/src/net/http/server.go:31

- Feb 21 19:58:27 VM-12-11-debian systemd[1]: alist.service: Main process exited, code=exited, status=2/INVALIDARGU Feb 21 19:58:27 VM-12-11-debian systemd[1]: alist.service: Failed with result 'exit-code'

**Comment by cy726** [comment]
我设成2小时重启一次了。。。不然没法用

**Comment by Xhofe** [comment]
我相信这应该在v3.12.0中被修复

**Comment by SkysCrystal** [comment]
我使用的一键脚本更新 AList 到最新版 v3.12.0 （系统 debian）。但是仍然出现过一段时间自动关闭的现象。此外，重启系统，alist 服务不会开机自启。请问要如何解决或是提供更多信息？谢谢
```
● alist.service - Alist service
     Loaded: loaded (/etc/systemd/system/alist.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-02-25 09:29:56 CST; 11min ago
   Main PID: 518 (code=exited, status=1/FAILURE)
        CPU: 147ms

Feb 25 09:29:55 xxxx systemd[1]: Started Alist service.
Feb 25 09:29:56 xxxx alist[518]: INFO[2023-02-25 09:29:56] reading config file: data/config.json
Feb 25 09:29:56 xxxx alist[518]: INFO[2023-02-25 09:29:56] load config from env with prefix: ALIST_
Feb 25 09:29:56 xxxx alist[518]: INFO[2023-02-25 09:29:56] init logrus...
Feb 25 09:29:56 xxxx systemd[1]: alist.service: Main process exited, code=exited, status=1/FAILURE
Feb 25 09:29:56 xxxx systemd[1]: alist.service: Failed with result 'exit-code'.
```
