### ISSUE TITLE
能否将“签名所有”和“转发直链参数”迁移至元信息

### ISSUE THREAD

**Issue by xhwsd** [alist-org/alist#3558]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

**能否将“签名所有”和“转发直链参数”迁移至元信息**

### 签名所有
实现对指定文件夹下文件进行签名

### 转发直链参数
- 并不是所有网盘都兼容转发参数的（如开启签名和转发参数，阿里README.md将报错）
- 或者过滤掉alist的签名参数

**Comment by anwen-anyi** [comment]
签名所有加密不就是吗？

转发直链参数暂时不做评价

**Comment by xhwsd** [comment]
实现对**指定文件夹**下文件进行签名

**Comment by xhwsd** [comment]
这和元信息"密码"一个意思，按你这逻辑是不是不要"密码"不就是吗？

**Comment by xhwsd** [comment]
**和元信息中“密码”一个逻辑，实现多指定文件夹进行签名~**

**Comment by stkroot** [comment]
确实，如果把Alist作为图床就必须关闭签名所有。但关闭后又有安全问题，如果可以对某个文件夹单独设置关闭签名就好了
