### ISSUE TITLE
能不能提供在配置里卸载某个网盘（当前后台UI因某网盘出问题无法加载时）？

### ISSUE THREAD

**Issue by ilihu** [alist-org/alist#3564]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

#### 起因
之前提过一个issue https://github.com/alist-org/alist/issues/3529 。这个issue的大概意思是阿里云盘的ocr宕机导致alist挂载的所有网盘都无法正常使用（主要问题是当时前后台的UI都加载不了，进不去后台，能进后台我也就不来开这个issue了）。

#### 需求
如果我可以在服务器里通过日志判断出是哪个网盘出了问题，我只需要在配置里取消该网盘挂载到alist上，即可正常使用其他没出问题的alist前后台UI和功能。

**Comment by anwen-anyi** [comment]
? 后台不是给你禁用和删除了？还不够用嘛？ 哈哈

**Comment by ilihu** [comment]
> ? 后台不是给你禁用和删除了？还不够用嘛？ 哈哈

问题是 一旦出现上述问题，我后台都进不去啊。无论前台后台的UI都进不去

**Comment by gowy222** [comment]
昨天K8S部署的时候就发现这个问题，拷贝的原来的 data文件夹 直接映射部署的，结果因为前置ocr接口再 K8S 内部 pod ip解析不一样，造成后台一直卡死在验证 ocr接口去登录网盘。 前端UI 就一直显示: 正在设置挂载对象啥的。。。连登录窗口都没有。 后来没办法，去后台把所有data文件夹清空，重新部署新的alist。 另外 发现Alist docker镜像，在K8S 配置了 本地储蓄pv+pvc的时候，./alist admin 无法读取env... 各种报错，拿不到密码... 又全部清空部署了一个新的alist.... 换言之，alist目前作为容器镜像，想高可用+易迁移 还是有点麻烦...

**Comment by Xhofe** [comment]
理论上即使有网盘网络不可达，但是都设置了超时时间，过了超时时间会直接返回错误记录在status中不会一直`Loading Storage`才对。你使用的是什么存储错误时会一直加载？

**Comment by ilihu** [comment]
> 理论上即使有网盘网络不可达，但是都设置了超时时间，过了超时时间会直接返回错误记录在status中不会一直`Loading Storage`才对。你使用的是什么存储错误时会一直加载？

用的阿里云盘，整整一个小时无法正常使用。希望发生超时等问题，可以将有问题的存储立刻卸载掉，不用等待就能进后台调试的功能

**Comment by xialei123456** [comment]
出现了一样的问题，我是123网盘挂载出了问题，UI里禁用和删除都报错找不到目录，然后就重启了alist, 之后打开UI就一直报错：获取设置失败： 请稍候，正在加载储存
