### ISSUE TITLE
下载失败Sorry, something went wrong

### ISSUE THREAD

**Issue by sizxiwu** [alist-org/alist#3565]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

下载不了跳转软件也不能播放
![Screenshot_20230222-221452](https://user-images.githubusercontent.com/121373708/220816425-eab2b97e-37b3-480f-a570-74f8231d4305.png)

### Reproduction / 复现链接

https://xn--5mq36gt1npvq.xyz/d/%E5%BE%AE%E8%BD%AF%E4%BA%91%E7%9B%98/%E5%8A%A8%E6%BC%AB%E7%95%AA%E5%89%A7/%5BANi%5D%20%E8%BD%89%E7%94%9F%E5%85%AC%E4%B8%BB%E8%88%87%E5%A4%A9%E6%89%8D%E5%8D%83%E9%87%91%E7%9A%84%E9%AD%94%E6%B3%95%E9%9D%A9%E5%91%BD%20-%2008%20%5B1080P%5D%5BBaha%5D%5BWEB-DL%5D%5BAAC%20AVC%5D%5BCHT%5D.mp4?sign=ghr0SuXR0lLV5x1hEkv11zJQLj8PzCGzdFmcxP50OVQ=:0

### Logs / 日志

![Screenshot_20230223-113635](https://user-images.githubusercontent.com/121373708/220816259-583e94aa-94d3-422f-b573-fb7e7b709440.png)

**Comment by anwen-anyi** [comment]
你是在目录**右键下载**的吧？ 去后台看看 转发直链参数你关一下试试看？


在文件进去然后选择下载倒是没问题
