### ISSUE TITLE
Alist版本3.11，迅雷已挂载成功，驱动为迅雷（非专家版），infuse连接alist也能看，但alist迅雷云盘经常性挂载失灵。状态显示为：Post "https://xluser-ssl.xunlei.com/v1/shield/captcha/init": dial tcp: lookup xluser-ssl.xunlei.com on 127.0.0.1:53: no such host

### ISSUE THREAD

**Issue by KennyZKY** [alist-org/alist#3566]
Alist版本3.11，迅雷已挂载成功，驱动为迅雷（非专家版），infuse连接alist也能看，但alist迅雷云盘经常性挂载失灵。状态显示为：Post "https://xluser-ssl.xunlei.com/v1/shield/captcha/init": dial tcp: lookup xluser-ssl.xunlei.com on 127.0.0.1:53: no such host
有时迅雷云盘会自己恢复正常，周而复始。阿里云盘挂载正常。
update：已尝试专家版，挂载成功，一开始正常使用，后面问题依旧。。可能是网络问题？
_Originally posted by @KennyZKY in https://github.com/alist-org/alist/discussions/3560_

**Comment by 12189108** [comment]
dns解析的问题，可以尝试更改服务器为223.5.5.5（没有国外网盘的挂载需求），或8.8.8.8
