### ISSUE TITLE
希望增加对百度网盘群组文件库的支持

### ISSUE THREAD

**Issue by Frogsita** [alist-org/alist#3570]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能够挂载百度网盘账号下群组内已共享的文件库

### Additional context / 附件

![Snipaste_2023-02-23_19-41-08](https://user-images.githubusercontent.com/117974612/220896165-5afc6cc6-6f3c-4da8-be51-1d51b6837c28.png)

**Comment by jewein** [comment]
+1

**Comment by Xhofe** [comment]
暂未发现百度未开放此API。

**Comment by 12189108** [comment]
> 暂未发现百度未开放此API。如有请提供并reopen。

https://github.com/PeterDing/BaiduPCS-Py/issues/73

大部分api已在此issues中提供，但大文件的dlink和list还是加密的
