### ISSUE TITLE
天翼云客户端无法访问 证书错误

### ISSUE THREAD

**Issue by barton0426** [alist-org/alist#3572]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

docker latest

### Driver used / 使用的存储驱动

天翼云客户端

### Describe the bug / 问题描述

天翼云都不可用 证书问题

Post "https://api.nn.ci/ocr/file/json": tls: failed to verify certificate: x509: certificate signed by unknown authority

### Reproduction / 复现链接

新建一个天翼云就能复现
Post "https://api.nn.ci/ocr/file/json": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by jetsung** [comment]
我刚刚添加了，也是这个问题。具体原因我刚刚有回别的的贴。

https://github.com/alist-org/alist/discussions/3335#discussioncomment-5088547

别人也说了解决方法：https://github.com/alist-org/alist/discussions/3473

可以参与下我写的 docker-compose.yml
https://github.com/jetsung/docker-compose/tree/main/alist
