### ISSUE TITLE
ubuntu使用普通用户启动后不久就无法访问了

### ISSUE THREAD

**Issue by 4860575** [alist-org/alist#3574]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0

### Driver used / 使用的存储驱动

aliyun

### Describe the bug / 问题描述

系统：ubuntu22.04
使用“https://alist.nn.ci/zh/guide/install/manual.html#守护进程”以普通用户启动。当退出登陆过会在访问就无法访问了，日志如下：
WARN[2023-02-23 22:43:06] not enable search                            
如果再次登陆服务器查看日志，就又能访问了

### Reproduction / 复现链接

无

### Logs / 日志

WARN[2023-02-23 22:43:06] not enable search

**Comment by Xhofe** [comment]
抱歉 这可能属于alist的范畴。
