### ISSUE TITLE
拉取v3.10.1以上版本报错

### ISSUE THREAD

**Issue by TingTing1990** [alist-org/alist#3578]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.0

### Driver used / 使用的存储驱动

PikPak

### Describe the bug / 问题描述

按照使用手册想从v3.10.1更新到最新版本，无论使用 xhofe/alist:latest还是 xhofe/alist:v3.12.0都提示

“mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'.
See 'docker run --help'.”

指定v3.10.1正常

### Reproduction / 复现链接

按照问题描述复现

**Comment by jjm2473** [comment]
dockerd版本太老？

**Comment by TingTing1990** [comment]
> dockerd版本太老？

Community 19.03.4
