### ISSUE TITLE
阿里云盘分享 Aliyun Video Previewer - UserDeviceIllegality: invalid X-Device-Id

### ISSUE THREAD

**Issue by MindFollowing** [alist-org/alist#3582]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.0

### Driver used / 使用的存储驱动

Aliyundrive

### Describe the bug / 问题描述

使用阿里云盘分享的，访问API [/api/fs/other]，出现UserDeviceIllegality: invalid X-Device-Id问题。

### Reproduction / 复现链接

[阿里云盘分享 - 复现链接](https://pan.lccyy.com/3.%E5%A4%96%E9%83%A8%E5%88%86%E4%BA%AB%EF%BC%88%E8%B5%84%E6%BA%90%E5%90%88%E9%9B%86%EF%BC%89/2.%E8%B1%86%E7%93%A3%20Top250%20%E7%94%B5%E5%BD%B1/%E8%B1%86%E7%93%A3%20Top250%20%E7%94%B5%E5%BD%B1/Top046.%E6%95%99%E7%88%B62.The.Godfather.Part.%E2%85%A1.1974.Bluray.1080p.x265.AAC(5.1).2Audios.GREENOTEA.mkv)

### Logs / 日志

{"code":500,"message":"UserDeviceIllegality: invalid X-Device-Id","data":null}

**Comment by lsh8848** [comment]
一样的问题，用旧的播放器就没问题。还有epub电子书加载不出书，预览不了。

**Comment by anwen-anyi** [comment]
分享的方式挂载 不可以使用 open方式获取的token

**Comment by lsh8848** [comment]
> 分享的方式挂载 不可以使用 open方式获取的token

https://alist.nn.ci/zh/guide/drivers/aliyundrive.html 扫码获取的不行，请赐教。

**Comment by Xhofe** [comment]
阿里云盘分享不支持Aliyun Video Previewer，将在下个版本对阿里云盘分享删除Aliyun Video Previewer

**Comment by gmdig** [comment]
有禁用的设置吗？
