### ISSUE TITLE
3.12 阿里Open 驱动问题

### ISSUE THREAD

**Issue by imkratos** [alist-org/alist#3583]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.12.0 docker版

### Driver used / 使用的存储驱动

Open阿里

### Describe the bug / 问题描述

挂载一段时间后，日志会显示TooManyRequest问题，目前不知道自动刷新机制是什么。

### Reproduction / 复现链接

内网

### Logs / 日志

![image](https://user-images.githubusercontent.com/3302461/221090428-3df13b13-264a-4023-814f-a9a7a29cf764.png)
<img width="344" alt="image" src="https://user-images.githubusercontent.com/3302461/221090457-8fdd8196-0c9d-4460-93c4-145d3cb7a6cd.png">

**Comment by everstu** [comment]
![1677212343398](https://user-images.githubusercontent.com/19686947/221090763-65bc267a-e7a8-4628-bbc5-459624a72268.png)


同样的问题，挂载成功后并无其他任何操作，自动成了TooManyRequests。

**Comment by 12189108** [comment]
希望能给一个适合自建api的版本，参数留空就行

**Comment by Xhofe** [comment]
已更新limiter策略。

**Comment by zoujingli** [comment]
Alist  v3.15.0 ，刷新时偶尔出现以下问题：

failed link: failed get link: TooManyRequests:76917ccccd4441c39457a04f6084fb2f

![image](https://user-images.githubusercontent.com/4349951/230269146-9f8e7b84-c4a4-44a3-92ad-5a270be91605.png)
