### ISSUE TITLE
api自建

### ISSUE THREAD

**Issue by 12189108** [alist-org/alist#3586]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

类似于alist-org下的ddddocr,将其他api的后端开源，便于自建，可将关键参数留空，留给我自己填，更加稳定，比如阿里云盘open的api经常报Too many requests

**Comment by Xhofe** [comment]
如果你申请了官方client 你可以直接填在阿里云盘open的配置里而不使用alist提供的API，如果你没有那么你也建不了这个API后端。
