### ISSUE TITLE
站点公告文字重叠

### ISSUE THREAD

**Issue by catchfishday** [alist-org/alist#3589]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.0-x86_64

### Driver used / 使用的存储驱动

baidu

### Describe the bug / 问题描述

站点公告文字重叠，见附件截图

![WX20230224-141653@2x](https://user-images.githubusercontent.com/12185015/221107369-8f8b257f-eae9-4c0b-9d5c-6660c9922b34.png)

### Reproduction / 复现链接

http://127.0.0.1:5244/

**Comment by ronnie9211** [comment]
https://alist.nn.ci/zh/config/site.html#%E5%85%AC%E5%91%8A

**Comment by catchfishday** [comment]
> https://alist.nn.ci/zh/config/site.html#%E5%85%AC%E5%91%8A
按照上面的方法加上去好像不太行😄
<img width="351" alt="image" src="https://user-images.githubusercontent.com/12185015/221182190-6bbd6bee-0ebf-4933-9c3c-5dcb20a35148.png">

**Comment by Xhofe** [comment]
> > https://alist.nn.ci/zh/config/site.html#%E5%85%AC%E5%91%8A
> > 按照上面的方法加上去好像不太行😄
> 
> <img alt="image" width="351" src="https://user-images.githubusercontent.com/12185015/221182190-6bbd6bee-0ebf-4933-9c3c-5dcb20a35148.png">

此处`\n`指换行，并不是让你真的输入`\n`

**Comment by catchfishday** [comment]
> > > https://alist.nn.ci/zh/config/site.html#%E5%85%AC%E5%91%8A
> > > 按照上面的方法加上去好像不太行😄
> > 
> > 
> > <img alt="image" width="351" src="https://user-images.githubusercontent.com/12185015/221182190-6bbd6bee-0ebf-4933-9c3c-5dcb20a35148.png">
> 
> 此处`\n`指换行，并不是让你真的输入`\n`

搞好了，用br才可以正常换行
Hello<br/>Welcome to use Alist
