### ISSUE TITLE
更新3.12.0版本后出现：UserDeviceIllegality: invalid X-Device-Id

### ISSUE THREAD

**Issue by Bssn520** [alist-org/alist#3590]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.0

### Driver used / 使用的存储驱动

阿里云盘分享

### Describe the bug / 问题描述

中午更新到3.12.0版本后出现UserDeviceIllegality: invalid X-Device-Id错误：
<img width="472" alt="image" src="https://user-images.githubusercontent.com/96654048/221111629-70c068fc-61d3-4078-b09a-b4aa4005417d.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/96654048/221111390-2861c49f-52b9-40db-9fae-0266c6346695.png">
无法在线播放视频，但是用webdav方式挂载后可以正常观看。

### Reproduction / 复现链接

http://81.70.1.225:5244/%E5%91%A8%E4%B8%80-%E6%98%9F%E8%BE%B0%E5%8F%98/%E6%98%9F%E8%BE%B0%E5%8F%98%20%E7%AC%AC%E4%BA%94%E5%AD%A3_09_1080P.mp4

**Comment by CCraftY** [comment]
不使用aliyun video previewer可以正常播放

**Comment by Bssn520** [comment]
> 不使用aliyun video previewer可以正常播放

好的👌🏻，感谢回答。

网页播放，默认是使用aliyun video previewer，更新完没注意看😅

不过，既然添加了该播放方式，为何报了个之前已经解决过的error呢？

**Comment by MindFollowing** [comment]
> > 不使用aliyun video previewer可以正常播放
> 
> 好的👌🏻，感谢回答。
> 
> 网页播放，默认是使用aliyun video previewer，更新完没注意看😅
> 
> 不过，既然添加了该播放方式，为何报了个之前已经解决过的error呢？

不是同一个error，应该是阿里云分享不支持在线预览（强行支持也只能播放2分钟）

**Comment by Bssn520** [comment]
> > > 不使用aliyun video previewer可以正常播放
> > 
> > 
> > 好的👌🏻，感谢回答。
> > 网页播放，默认是使用aliyun video previewer，更新完没注意看😅
> > 不过，既然添加了该播放方式，为何报了个之前已经解决过的error呢？
> 
> 不是同一个error，应该是阿里云分享不支持在线预览（强行支持也只能播放2分钟）

那有办法使网页默认以Video方式播放吗？
除了退回之前的版本外。
