### ISSUE TITLE
希望网页端增加对ape格式音频和wmv格式视频的支持

### ISSUE THREAD

**Issue by x2287711259** [alist-org/alist#3592]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望网页端增加对ape格式音频和wmv格式视频的支持

**Comment by anwen-anyi** [comment]
后台设置 预览选项里面有个音频选项 你自己增加试试看
