### ISSUE TITLE
隐藏某特定类型后除admin用户以外将无法上传

### ISSUE THREAD

**Issue by anwen-anyi** [alist-org/alist#3593]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.12.0

### Driver used / 使用的存储驱动

All

### Describe the bug / 问题描述

隐藏某一类型文件后，就无法上传，以下两种方式都不可以
1. 给予某文件夹写入权限
2. 创建一个用户 给予上传权限

若通过全局-->隐藏文件方式可以，例如隐藏readme那样
不知这是否是预期行为还是其他。

### Reproduction / 复现链接

No URL

### Logs / 日志

上传对话框内显示
```log
logpermission denied
```

**Comment by Xhofe** [comment]
上传自己看不见的文件并没有什么意义

**Comment by anwen-anyi** [comment]
特定场景下可能用得到 ，那还是使用 `全局-->隐藏文件` 的方式吧~

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/pull/3612
