### ISSUE TITLE
WEBDAV挂载阿里云盘视频播放黑屏，只有声音

### ISSUE THREAD

**Issue by icexk** [alist-org/alist#3594]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.0

### Driver used / 使用的存储驱动

WEBDAV

### Describe the bug / 问题描述

你好，我用WEBDAV挂载阿里云盘的视频，播放只有声音，没有画面，黑屏

### Reproduction / 复现链接

<img width="981" alt="image" src="https://user-images.githubusercontent.com/43198678/221151911-a52ac9db-ff22-4e2a-b619-40846db55938.png">

**Comment by mengguyi** [comment]
检查你视频的编码，确保你的浏览器支持
