### ISSUE TITLE
Aliyun Video Previewer

### ISSUE THREAD

**Issue by HaanJam** [alist-org/alist#3616]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

阿里云盘OPEN

### Describe the bug / 问题描述

我打开视频文件以后（默认是Aliyun Video Previewer打开），有的视频文件拖动进度条以后一直转圈圈然后卡住了，一直等待一直没有反应的。选择之前的Viedeo来播放就很流畅，拖到哪里就从哪里播放，所以我排除了我的网络慢的问题。
建议：在添加阿里云盘OPEN的选项中能够设置默认播放器

### Reproduction / 复现链接

http://20.187.82.54:5244/2019%E6%9C%80%E6%96%B0%20SSM%E6%A1%86%E6%9E%B6%E9%85%92%E5%BA%97%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F%E5%AE%9E%E6%88%98%E5%BC%80%E5%8F%91%E6%95%99%E7%A8%8B%EF%BC%88%E7%AC%94%E8%AE%B0%E3%80%81%E6%BA%90%E7%A0%81%E3%80%81%E7%B4%A0%E6%9D%90%E3%80%81%E6%95%B0%E6%8D%AE%EF%BC%89/%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B/%E7%AC%AC%E5%85%AD%E8%AE%B2%E6%88%BF%E9%97%B4%E7%B1%BB%E5%9E%8B%E6%8E%A7%E5%88%B6%E5%99%A8%E8%AE%BE%E8%AE%A1%E5%8F%8A%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AE%BE%E8%AE%A1%E5%AE%9E%E7%8E%B0%E3%80%90%E7%91%9E%E5%AE%A2%E8%AE%BA%E5%9D%9B%20www.ruike1.com%E3%80%91.mp4

### Logs / 日志

![image](https://user-images.githubusercontent.com/35722236/221366287-bdfe4755-3e41-41ef-a330-47cf495a1a68.png)
![image](https://user-images.githubusercontent.com/35722236/221366472-7c8f491b-c1b2-4e2e-beb9-ea356fbd4260.png)

**Comment by Xhofe** [comment]
getVideoPreviewPlayInfo接口返回的播放url，大部分情况下可以在直接主流播放器进行播放。
上传到云盘的视频，会经过转码服务转成 H.264 编码的视频流。
- 新上传到云盘的视频，默认只预转码视频的前30s。第一次播放(访问oss/media-0.ts)时会触发完整的视频转码。转码后的视频会缓存，之后再次触发播放不需要重新转码。
-  不足30s的视频不会触发预转码，只会在第一次播放时开始转码。
-  实时转码需要一定时间。新上传的视频立即播放，或者新上传的视频seek到靠后的时刻播放，可能遇到media-x.ts 缺失。
