### ISSUE TITLE
AliyundriveOpen 接口导致 AList 进程意外退出

### ISSUE THREAD

**Issue by KaminoDice** [alist-org/alist#3617]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.0

### Driver used / 使用的存储驱动

AliyundriveOpen

### Describe the bug / 问题描述

添加 AliyundriveOpen 储存后，会时不时出错导致整个 AList 进程意外退出

并且无法自动重启服务，需要手动重新启动 AList

alist 日志一切正常
systemd 日志如下

### Reproduction / 复现链接

和这个discussions https://github.com/alist-org/alist/discussions/3605 相同的问题

### Logs / 日志

 ```shell
alist[6750]: panic: runtime error: invalid memory address or nil pointer dereference
alist[6750]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12a6990]
alist[6750]: goroutine 89 [running]:
alist[6750]: github.com/alist-org/alist/v3/drivers/aliyundrive_open.(*AliyundriveOpen).Init.func1()
alist[6750]:         /home/runner/work/alist/alist/drivers/aliyundrive_open/driver.go:52 +0x30
alist[6750]: github.com/alist-org/alist/v3/pkg/cron.(*Cron).Do.func1()
alist[6750]:         /home/runner/work/alist/alist/pkg/cron/cron.go:24 +0x8e
alist[6750]: created by github.com/alist-org/alist/v3/pkg/cron.(*Cron).Do
alist[6750]:         /home/runner/work/alist/alist/pkg/cron/cron.go:18 +0x72
systemd[1]: alist.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: alist.service: Unit entered failed state.
systemd[1]: alist.service: Failed with result 'exit-code'.
```

**Comment by KaminoDice** [comment]
Duplicate #3591 
fixed [ec5483](https://github.com/alist-org/alist/commit/ec548311622805ca5bc84b845128ec166ddb8c12)

**Comment by anwen-anyi** [comment]
v3.12.2？ 这个试过了吗 我现在更新到 v3.12.2了暂时没问题等一两个小时没回就是没问题
