### ISSUE TITLE
挂载Alist上传大文件报Method Not Allowed: 405 错误

### ISSUE THREAD

**Issue by lcvy** [alist-org/alist#3621]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.0

### Driver used / 使用的存储驱动

webdav

### Describe the bug / 问题描述

情况：rclone挂载alist的webdav，其中webdav设置了sharepoint（世纪互联版）。可正常通过rclone命令行方式列出对应文件列表。
问题：上传大文件（>=4G）报 Method Not Allowed: 405 Method Not Allowed，上传小文件无此问题。

### Reproduction / 复现链接

见日志。

### Logs / 日志

##Alist's log

[31mERRO[0m[2023-02-26 10:25:37] PROPFIND /dav/sharepoint/test.zip object not found
github.com/alist-org/alist/v3/internal/op.Get
	/home/runner/work/alist/alist/internal/op/fs.go:220
github.com/alist-org/alist/v3/internal/fs.get
	/home/runner/work/alist/alist/internal/fs/get.go:38
github.com/alist-org/alist/v3/internal/fs.Get
	/home/runner/work/alist/alist/internal/fs/fs.go:26
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
	/home/runner/work/alist/alist/server/webdav/webdav.go:594
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/home/runner/work/alist/alist/server/webdav/webdav.go:72
github.com/alist-org/alist/v3/server.ServeWebDAV
	/home/runner/work/alist/alist/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/home/runner/work/alist/alist/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.19.6/x64/src/net/http/server.go:2947
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.19.6/x64/src/net/http/server.go:1991
runtime.goexit
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/asm_arm64.s:1172 
[GIN] 2023/02/26 - 10:25:37 | 404 |     233.841µs |       127.0.0.1 | PROPFIND  "/dav/sharepoint/test.zip"
[GIN] 2023/02/26 - 10:25:37 | 201 |      28.881µs |       127.0.0.1 | MKCOL    "/dav/sharepoint/"
[31mERRO[0m[2023-02-26 10:25:38] failed put /sharepoint: WriteStream /test.zip: 400
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:550
github.com/alist-org/alist/v3/internal/fs.putDirectly
	/home/runner/work/alist/alist/internal/fs/put.go:54
github.com/alist-org/alist/v3/internal/fs.PutDirectly
	/home/runner/work/alist/alist/internal/fs/fs.go:84
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePut
	/home/runner/work/alist/alist/server/webdav/webdav.go:328
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/home/runner/work/alist/alist/server/webdav/webdav.go:62
github.com/alist-org/alist/v3/server.ServeWebDAV
	/home/runner/work/alist/alist/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/home/runner/work/alist/alist/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.19.6/x64/src/net/http/server.go:2947
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.19.6/x64/src/net/http/server.go:1991
runtime.goexit
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/asm_arm64.s:1172 
[31mERRO[0m[2023-02-26 10:25:38] PUT /dav/sharepoint/test.zip WriteStream /test.zip: 400
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:550
github.com/alist-org/alist/v3/internal/fs.putDirectly
	/home/runner/work/alist/alist/internal/fs/put.go:54
github.com/alist-org/alist/v3/internal/fs.PutDirectly
	/home/runner/work/alist/alist/internal/fs/fs.go:84
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePut
	/home/runner/work/alist/alist/server/webdav/webdav.go:328
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/home/runner/work/alist/alist/server/webdav/webdav.go:62
github.com/alist-org/alist/v3/server.ServeWebDAV
	/home/runner/work/alist/alist/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/home/runner/work/alist/alist/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.19.6/x64/src/net/http/server.go:2947
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.19.6/x64/src/net/http/server.go:1991
runtime.goexit
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/asm_arm64.s:1172 
[GIN] 2023/02/26 - 10:25:38 | 405 |   260.56308ms |       127.0.0.1 | PUT      "/dav/sharepoint/test.zip"

##rclone's return
![image](https://user-images.githubusercontent.com/54807723/221388172-970edde2-e7a1-44d8-b5c5-367521c344c9.png)

**Comment by Xhofe** [comment]
这是onedrive/sharepoint WebDAV的限制，非alist问题。

**Comment by bibichuan** [comment]
我挂载百度网盘也是出现了这个问题，该如何解决呢？

**Comment by 54145a** [comment]
> 我挂载百度网盘也是出现了这个问题，该如何解决呢？

+1
