### ISSUE TITLE
非admin用户添加编辑元信息说明的权限

### ISSUE THREAD

**Issue by Masterlovsky** [alist-org/alist#3623]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

企业内部搭建alist进行资源共享时，希望多人合作，每个人都能对目录做Markdown的说明。
现在只有admin用户可以编辑元信息，希望可以吧密码、隐藏的权限只给admin，说明的权限开放给所有用户，便于合作资源共享。

**Comment by adogecheems** [comment]
我喜欢这个功能
