### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shzxm** [alist-org/alist#3627]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.12.2

### Driver used / 使用的存储驱动

openaliyun

### Describe the bug / 问题描述

 alist[2970829]: panic: runtime error: invalid memory address or nil pointer dereference
alist[2970829]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12a6990]
 alist[2970829]: goroutine 61 [running]:
 alist[2970829]: github.com/alist-org/alist/v3/drivers/aliyundrive_open.(*AliyundriveOpen).Init.func1()
alist[2970829]:         /home/runner/work/alist/alist/drivers/aliyundrive_open/driver.go:52 +0x30
alist[2970829]: github.com/alist-org/alist/v3/pkg/cron.(*Cron).Do.func1()
 alist[2970829]:         /home/runner/work/alist/alist/pkg/cron/cron.go:24 +0x8e
 alist[2970829]: created by github.com/alist-org/alist/v3/pkg/cron.(*Cron).Do
 alist[2970829]:         /home/runner/work/alist/alist/pkg/cron/cron.go:18 +0x72

### Reproduction / 复现链接

github.com/alist-org/alist/v3/drivers/aliyundrive_open.(*AliyundriveOpen).Init.func1()

**Comment by Xhofe** [comment]
We have removed the use of cron, so this cannot happen with v3.12.2, please check your version.
