### ISSUE TITLE
对于阿里云盘这种根据md5之类的信息秒传文件的功能，我有个大胆的想法，希望大佬们能看到

### ISSUE THREAD

**Issue by 643104191** [alist-org/alist#3631]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

网盘软件应该都是在本地读取完文件，生成一个md5/sha之类的唯一校验码到服务器上去对比，
如果有匹配到的文件，就直接在网盘生成一个文件，
那这时候，如果alist这边，跳过文件读取&生成唯一校验码的步骤，
直接把md5/sha之类的唯一校验码上传到服务器，
那是不是就简化了大家下载/上传电影或其他热门资源的流程？

### Suggested solution / 实现思路

见需求描述

**Comment by Xhofe** [comment]
无法实现：
1. 阿里暂未开放秒传API
2. 阿里的秒传与需要提供proof_code，它的计算逻辑为
```
1.计算出文件的size
2.获取本地的access_token，计算出md5值，比如"468740f5b1629aa305db99e56e15cd88"
3.截取前16位，"468740f5b1629aa3"
4.转换成unsigned int64，比如：5082102128498088611
5.获取文件的size，如果size为0，直接返回
6.对文件大小取模，r1=5082102128498088611%23512=17579
7.得出range:[r, r+8)
8.如果r+8>=size，调整为[r, size)
  
2.读取本地文件的range值的byte，计算proof_code
    base64(filedata[r,r+8))
  
  这里不传入时间戳来防重放，因为accesstoken有过期时间，且重放也只是该用户的重放，不会有安全问题。

计算 proof range 示例代码
type ProofRange struct {
    Start int64
    End   int64
}

func getProofRange(input string, size int64) (*commonmodel.ProofRange, error) {
    if size == 0 {
    return &commonmodel.ProofRange{}, nil
    }

    // 参考：https://yuque.antfin-inc.com/mdm/agncs6/ibgc7a
    tmpStr := utils.MD5Str(input)[0:16]

    tmpInt, err := strconv.ParseUint(tmpStr, 16, 64)
    if err != nil {
    return nil, err
    }

    index := tmpInt % uint64(size)
    pr := &commonmodel.ProofRange{
    Start: int64(index),
    End:   int64(index) + 8,
    }
    if pr.End >= size {
    pr.End = size
    }

    return pr, nil
}
```

它并不固定 需要根据每个人的token读取文件的不同部分。

**Comment by chunfengyao** [comment]
@Xhofe 不知道阿里云盘的接口和阿里提供的企业云盘服务接口是不是通用的。企业的云盘与相册服务是有秒传功能的，而且，只需要一个sha1值。

https://help.aliyun.com/document_detail/175888.html#zSgCe

**Comment by JsonSong89** [comment]
> 
阿里云盘之前是支持,后来发现有人通过秒传分享颜色,才加了随机proof_code校验
