### ISSUE TITLE
更新3.12.2之后出现重定向次数过多

### ISSUE THREAD

**Issue by shenlijun** [alist-org/alist#3632]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

百度网盘、webdav、smb

### Describe the bug / 问题描述

在ubuntu22.04上用apache2反向代理到alist子文件夹（实际上的alist是安装在另外一台局域网服务器上）。
之前一直使用没有问题，上一个版本应该是3.11.0。
今天更新3.12.2之后就出现无法访问的问题，显示重定向次数过多，ERR_TOO_MANY_REDIRECTS；内网访问ip:port正常。

因为同时反代了nextcloud和alist，而nextcloud没有问题，只是alist不行

### Reproduction / 复现链接

暂时改回3.11.0了，链接现在是可用的

**Comment by li-jun** [comment]
出现同样的问题了，也是设置了反向代理 。
