### ISSUE TITLE
Bug - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jerryluo71** [alist-org/alist#3637]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

Synology NAS (DSM7.1.1)  docker alist:lastest

### Describe the bug / 问题描述

alist升级到v3.12.2版本后，固定每2小时重启一次，查看日志，报错原因为：panic: runtime error: invalid memory address or nil pointer dereference。

### Reproduction / 复现链接

从下面csv文件中可以看到，2:01:13重启一次，到4:01:49又重启一次。这里只提供了两个时间节点的错误以及docker报错信息的截图，后面有详细的日期文件，请查阅。
![docker info](https://user-images.githubusercontent.com/42297312/221452284-f31128de-368b-4887-ad05-17d6b90439a8.png)
![error - time020131](https://user-images.githubusercontent.com/42297312/221452287-6a0f1582-aa11-44c0-aeb7-cf3c39df7d9e.png)
![error - time040149](https://user-images.githubusercontent.com/42297312/221452289-668821c6-eb2d-4c39-96b5-296e98c8f7fc.png)

### Logs / 日志

[Alist bug.csv](https://github.com/alist-org/alist/files/10835362/Alist.bug.csv)

**Comment by Xhofe** [comment]
According to your log, you are still using v3.12.0 instead of the latest v3.12.2. Please check your version
