### ISSUE TITLE
账号二级验证会报错

### ISSUE THREAD

**Issue by kimycai** [alist-org/alist#3640]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.12.2

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

启动账号二级验证后登陆账号时，第一次输入二级验证码会提示验证码无效错误，第二次输入则会正常登陆，第二次输入的验证码同第一次，且间隔为未刷新验证码之前输入

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/17998728/221463955-080414cb-592d-40b7-80a0-799d615b924a.png)

**Comment by Xhofe** [comment]
For 2FA, we use the lib https://github.com/pquerna/otp, If there are any issues, please report it to upstream repo directly.
