### ISSUE TITLE
反向代理后  下载按钮的链接不正确

### ISSUE THREAD

**Issue by wudiming** [alist-org/alist#3644]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

通过ipv6端口转发的方式连接外网，为能使ipv4端也可以访问，采用了双栈服务器反向代理了一下，可以正常访问。
在下载本机存储的文件时，点击下载，网站是原ipv6的地址，导致无法下载文件，但是点击复制链接 ，通过该连接能正确下载文件。
希望可以调整下下载按钮的链接策略

### Reproduction / 复现链接

下载按钮的直链链接：http://v6.deamonwu.icu/p/nas/volume1/%E4%B8%B4%E6%97%B6%E5%B7%A5%E4%BD%9C/%E6%9D%83%E5%8A%9B%E7%9A%84%E6%B8%B8%E6%88%8F%E9%93%BE%E6%8E%A5.txt?sign=W-2RvjveorqV6viDYUw2S8oGVhgIy4BtvXArXfHK_BI=:0
复制链接按钮的直链链接：
https://pan.deamonwu.icu/d/nas/volume1/%E4%B8%B4%E6%97%B6%E5%B7%A5%E4%BD%9C/%E6%9D%83%E5%8A%9B%E7%9A%84%E6%B8%B8%E6%88%8F%E9%93%BE%E6%8E%A5.txt?sign=W-2RvjveorqV6viDYUw2S8oGVhgIy4BtvXArXfHK_BI=:0

复制的能自动识别反代后的域名，下载的还是原来的域名

**Comment by Xhofe** [comment]
you need to pass your host while do reverse proxy, such as: 
```nginx
location / {
    proxy_set_header Host $http_host;
}
```

**Comment by jyjxqy** [comment]
proxy_set_header X-Forwarded-Host $http_host; # 添加这一行楼上的添加Host是错的，耽误我半小时

**Comment by Huayuluoshi** [comment]
> proxy_set_header X-Forwarded-Host $http_host; # 添加这一行楼上的添加Host是错的，耽误我半小时

确实应该填写这个

**Comment by Jreffreywanttogetmarried** [comment]
确实应该填写这个。我的场景是宝塔站点反代+https域名+本地存储。发现非admin角色都不能查看图片，链接是错的。
