### ISSUE TITLE
网页白屏

### ISSUE THREAD

**Issue by qusim** [alist-org/alist#3653]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

网页白屏

### Describe the bug / 问题描述

网页白屏,打开后就白屏什么也不能看

### Reproduction / 复现链接

https://pan.lunglung.top/

### Logs / 日志

![QQ截图20230228011840](https://user-images.githubusercontent.com/118922339/221634147-7ef9f0a3-b9c9-4385-bc2e-e32220c39ea2.png)

**Comment by anwen-anyi** [comment]
复现链接 403

**Comment by 12189108** [comment]
你把配置里的cdn里的/@login去了就行，哪有这么配置的

**Comment by qusim** [comment]
> 你把config.json配置在cdn裡的/@login去了就行，哪有這個配置的

好的好的感謝

**Comment by qusim** [comment]
> 

但我这边也是一样,也是白屏

**Comment by qusim** [comment]
> /@login

"force": false,
  "address": "0.0.0.0",
  "port": 5244,
  "site_url": "https://pan.lunglung.top/",
  "cdn": "",

**Comment by qusim** [comment]
有了感謝
