### ISSUE TITLE
支持播放器读取内置、外置字幕功能

### ISSUE THREAD

**Issue by MindFollowing** [alist-org/alist#3655]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Aliyun Video Previewer 支持读取内置、外置字幕
Video支持读取目录结构获取外置字幕文件并挂载

### Suggested solution / 实现思路

*********Aliyun Video Previewer 原生获取视频信息接口中返回了字幕的数据*********
{
	"domain_id": "bj29",
	"drive_id": "369641930",
	"file_id": "63fd5c3a00f8552bc7694adab4585740cbf8c8bf",
	"category": "live_transcoding",
	"video_preview_play_info": {
		"category": "live_transcoding",
		"meta": {
			"duration": 8529.432,
			"width": 1920,
			"height": 816
		},
		"live_transcoding_task_list": [Object object],
		"*********live_transcoding_subtitle_task_list": [{
			"language": "chi",
			"status": "finished",
			"url": "https://ccp-bj29-video-preview.oss-enet.aliyuncs.com/lt/D8FD2361753581E0E54DE9F54E76203690F87D24_3572904023__sha1_bj29/subtitle/chi_0.vtt"
		}, {
			"language": "eng",
			"status": "finished",
			"url": "https://ccp-bj29-video-preview.oss-enet.aliyuncs.com/lt/D8FD2361753581E0E54DE9F54E76203690F87D24_3572904023__sha1_bj29/subtitle/eng_0.vtt?*********"
		}]
	}
}

Video 需要考虑将srt, ssa, ass 等文件转换成vtt格式后进行挂载

**Comment by shadowofgost** [comment]
+1 特别希望提供读取外置字幕功能

**Comment by DawnElixir** [comment]
+1 希望Aliyun Video Previewer 支持读取内置字幕

**Comment by quanrennsxsb** [comment]
+1 特别希望提供读取外置字幕功能

**Comment by sonichy** [comment]
内置字幕不支持
