### ISSUE TITLE
支持torrent形式BT下载

### ISSUE THREAD

**Issue by ll789899** [alist-org/alist#3656]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能够上传torrent文件 然后交给qb下载最后自动上传的功能 。目前只支持磁力链接 希望可以加上这个功能。

**Comment by mengguyi** [comment]
https://github.com/alist-org/alist/issues/2459#issuecomment-1354870010

**Comment by kimycai** [comment]
或者将 https://nutbread.github.io/t2m/ 转换的js集成到alist里面的qbittorrent的下载页面上
