### ISSUE TITLE
阿里云盘分享速度慢，200K/s不到

### ISSUE THREAD

**Issue by snoopytl** [alist-org/alist#3663]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12

### Driver used / 使用的存储驱动

阿里云盘分享

### Describe the bug / 问题描述

目前挂载了别人的分享，通过potplayer或者电视去观看的时候，速度不到200k，这是否和阿里云open有关系，因为之前我没用阿里云open，我看我自己的盘里的内容也不到200k，换了阿里云open速度上去了，如果和阿里云open有关系，那以后的版本更新是否会解决这一问题，还是以后阿里云盘分享就只能是个摆设了

### Reproduction / 复现链接

/d4BGHcF7Pw8 共享id

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/issues/3613#issuecomment-1445152780

**Comment by peterwan1989** [comment]
遇到完全一样的问题

**Comment by Xiaosade** [comment]
遇到同样的问题，一直缓存，无法正常播放。
