### ISSUE TITLE
Alist启动后无法登录，提示密码错误

### ISSUE THREAD

**Issue by zgxhmj** [alist-org/alist#3672]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.12.2

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

Alist服务手动启动后，可以打开后登录页面，输入用户名和密码后，可以正常登录，如果用脚本自动启动后，打开后登录页面后，输入用户名和密码后，提示用户名和密码错误，一直不知道什么原因

### Reproduction / 复现链接

![172427grvisvevihsr1ceh](https://user-images.githubusercontent.com/126656544/222095831-c3f373f1-03f1-4d0b-9919-164bbcd2aa4d.jpg)
![172522zdpjkjcf6q0ucq0i](https://user-images.githubusercontent.com/126656544/222095859-67411fc2-2e69-41f6-ba5c-845a2c809a2e.jpg)

**Comment by anwen-anyi** [comment]
建议你去看文档 常见问题 为什么密码不对的哪一个说明~
