### ISSUE TITLE
webdav挂载打不开,

### ISSUE THREAD

**Issue by iso-lib** [alist-org/alist#3677]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.12.2

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

使用的docker安装在aws的vps上,网页端打开正常,网页端观看正常.
webdav挂载到nplayer或者cx浏览器上打不开
nplayer点击后 premature end of data in tag html line 2 (77)

我知道只有我一个人遇到这个问题,因为我用了这软件从v2用到v3都没遇到过
等新版我再重新安装试试.

### Reproduction / 复现链接

无

### Logs / 日志

![Screenshot_20230302-121144](https://user-images.githubusercontent.com/77186879/222329529-47f72e0a-7bfb-421b-92ce-9fb45a92f2f4.jpg)

**Comment by iso-lib** [comment]
找到原因了,是因为config.json文件中配置了site_url: www.xxxx.xyz

解决办法:
webdav挂载时,挂载路径需要写成https://www.xxxx.xyz/www.xxxx.xyz/dav

去掉site_url配置,就不需要多写一次url.

**Comment by reminx** [comment]
> 找到原因了,是因为config.json文件中配置了site_url: [www.xxxx.xyz](http://www.xxxx.xyz)
> 
> 解决办法: webdav挂载时,挂载路径需要写成https://www.xxxx.xyz/www.xxxx.xyz/dav
> 
> 去掉site_url配置,就不需要多写一次url.

没理解你说的解决方案，我webDAV挂载的是xiaoya。也是使用nplayer，也是相同的报错。你说的那个挂载路径要如何设置？
