### ISSUE TITLE
rclone挂载alist的webdav读取阿里云盘Open挂载的文件出现I/O error (403 Forbidden)

### ISSUE THREAD

**Issue by JingenChen** [alist-org/alist#3678]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

alist分别通过阿里云盘Open和阿里云盘共享挂载两个目录，再通过rclone去挂载webdav，其中阿里云盘Open挂载的路径下读取文件会出现I/O error，而阿里云盘共享则可以正常读取。

### Reproduction / 复现链接

N/A

### Logs / 日志

root@iStoreOS:/mnt/data_sda4/data/netdisk/Aliyun/xyz# cat DSC_0301.JPG 
cat: read error: I/O error
root@iStoreOS:/mnt/data_sda4/data/netdisk/Aliyun/xyz# cat /tmp/rclone_netdisk.log
2023/03/02 04:59:12 ERROR : IO error: 403 Forbidden
2023/03/02 04:59:12 ERROR : IO error: 403 Forbidden

**Comment by JingenChen** [comment]
我的rclone挂载参数如下：
/usr/bin/rclone mount Aliyun:/ /mnt/data_sda4/data/netdisk  --config /root/.config/rclone/rclone.conf --cache-dir /mnt/data_sda4/tmp/netdisk/ --allow-other --vfs-cache-mode writes --allow-non-empty &> /tmp/rclone_netdisk.log &

**Comment by sjtuross** [comment]
遇到一样的问题，这是跟哪个issue重复了？没找到

**Comment by ericma15** [comment]
是不是webdav策略，没有配成本地代理

**Comment by XG-China** [comment]
我也是这情况！真奇怪！挂载成功的也能给文件改名字 但是就是不能播放不能下载

**Comment by diduweiwu** [comment]
> 我也是这情况！真奇怪！挂载成功的也能给文件改名字 但是就是不能播放不能下载

老哥,我也是一样的情况,请问下你这边解决了吗?

**Comment by NibbinNone** [comment]
rclone加上这个参数 --header "Referer:https://www.aliyundrive.com/"

**Comment by bsdayo** [comment]
> rclone加上这个参数 --header "Referer:https://www.aliyundrive.com/"

问题解决，感谢

**Comment by best-cloud** [comment]
> rclone加上这个参数 --header "Referer:https://www.aliyundrive.com/"

太感谢了，你是怎么知道这个的，在哪里有文档吗？

**Comment by NibbinNone** [comment]
别用了，这个项目都卖了
> > rclone加上这个参数 --header "Referer:https://www.aliyundrive.com/"
> 
> 太感谢了，你是怎么知道这个的，在哪里有文档吗？
