### ISSUE TITLE
Aria2 not ready

### ISSUE THREAD

**Issue by AspirantH** [alist-org/alist#3679]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

Any

### Describe the bug / 问题描述

在x86软路由下安装的Alist最新版，之前离线下载好好的，Alist最新版提示Aria2 not ready，实际aria2的设置都是正常的，Aria2Ng里手工新增链接可以正常下载

### Reproduction / 复现链接

https://www.ukey.tax:8888/

### Logs / 日志

[36mINFO[0m[2023-03-02 07:25:55] index obj count: 875                         
[36mINFO[0m[2023-03-02 07:25:55] index obj count: 1713                        
[36mINFO[0m[2023-03-02 07:25:55] index obj count: 120                         
[36mINFO[0m[2023-03-02 07:25:55] index obj count: 1614                        
[36mINFO[0m[2023-03-02 07:25:56] index obj count: 122                         
[36mINFO[0m[2023-03-02 07:25:57] index obj count: 43366                       
[36mINFO[0m[2023-03-02 07:25:57] index obj count: 101                         
[36mINFO[0m[2023-03-02 07:25:57] index obj count: 373                         
[36mINFO[0m[2023-03-02 07:25:57] index obj count: 138                         
[36mINFO[0m[2023-03-02 07:25:58] index obj count: 270                         
[36mINFO[0m[2023-03-02 07:25:58] index obj count: 61                          
[36mINFO[0m[2023-03-02 07:25:58] index obj count: 75                          
[36mINFO[0m[2023-03-02 07:25:58] index obj count: 10777                       
[36mINFO[0m[2023-03-02 07:25:58] index obj count: 2846                        
[36mINFO[0m[2023-03-02 07:25:59] index obj count: 82                          
[36mINFO[0m[2023-03-02 07:25:59] index obj count: 681                         
[GIN] 2023/03/02 - 07:25:59 | 200 |     216.216µs |   221.229.73.24 | POST     "/api/fs/add_aria2"
[36mINFO[0m[2023-03-02 07:25:59] index obj count: 1025                        
[36mINFO[0m[2023-03-02 07:26:00] index obj count: 34                          
[36mINFO[0m[2023-03-02 07:26:00] index obj count: 875                         
[36mINFO[0m[2023-03-02 07:26:00] index obj count: 1713                        
[36mINFO[0m[2023-03-02 07:26:00] index obj count: 120                         
[36mINFO[0m[2023-03-02 07:26:00] index obj count: 1614                        
[36mINFO[0m[2023-03-02 07:26:01] index obj count: 122

**Comment by ooingram** [comment]
确实我，也是这样的问题。
非要在后台 其它 里面 点一下设置才能正常使用，很奇怪。
其实参数什么的都是正确的，非要点一下 设置Aria2 才能正常使用。很奇怪。
