### ISSUE TITLE
后台显示下载记录

### ISSUE THREAD

**Issue by GengGode** [alist-org/alist#3696]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

想要后台能够看到某些文件的下载历史或者下载次数

### Suggested solution / 实现思路

获取可以直接将下载文件和次数直接存到sqlite数据表里，然后后台显示直方图，几个简单的筛选

**Comment by BoYanZh** [comment]
也许你可以分析日志得到这个数据
