### ISSUE TITLE
K8S 本地持久卷 pv+pvc 映射 /opt/alist/data  导致 ./alist admin 报错..无法读取env..

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#3701]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3最新

### Driver used / 使用的存储驱动

暂不涉及

### Describe the bug / 问题描述

在pod执行shell...

alist-5fd9b5c4c5-jp9v4:/opt/alist# ./alist admin
INFO[2023-03-04 01:19:47] reading config file: data/config.json        
INFO[2023-03-04 01:19:47] load config from env with prefix: ALIST_     
FATA[2023-03-04 01:19:47] load config from env error: env: parse error on field "Port" of type "int": strconv.ParseInt: parsing "tcp://10.43.127.164:5244": invalid syntax 
alist-5fd9b5c4c5-jp9v4:/opt/alist# 

### Reproduction / 复现链接

K8S 本地储蓄 创建pv + pvc 然后pod 和 alist 容器 挂载到对应pvc 启动容器....

**Comment by gowy222** [comment]
本来是打算 直接 复制原来另一个服务器的/opt/alist/data 数据，之前迁移alist的... 一时间忘了密码..想去拿密码..结果悲剧了..

**Comment by Xhofe** [comment]
请自行处理环境变量相关问题。
