### ISSUE TITLE
v3.12.2 自定义body问题

### ISSUE THREAD

**Issue by imkratos** [alist-org/alist#3706]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2 Docker 版

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

在自定义 内容内 加入  `<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.3/jquery.slim.min.js"></script>`  

默认进入主页时，此引用是存在于页面的 如下：
<img width="964" alt="image" src="https://user-images.githubusercontent.com/3302461/222885828-58540949-eb26-4e83-926f-ec03f5371907.png">

默认进入主面时截图  
<img width="773" alt="image" src="https://user-images.githubusercontent.com/3302461/222886464-275153ad-044d-44f4-8e68-23a2f0f8dc37.png">

点击管理进入管理页面后，手动刷新管理页面后 引用丢失。

<img width="955" alt="image" src="https://user-images.githubusercontent.com/3302461/222885866-9f126f4a-4af8-41cc-9d2c-a93eef33459c.png">

### Reproduction / 复现链接

内网

### Logs / 日志

截图如上图

**Comment by Xhofe** [comment]
后台管理页面不支持自定义body。
