### ISSUE TITLE
使用docker报错”failed delete temp file: unlinkat /opt/alist/data/temp/qbittorrent: device or resource busy“

### ISSUE THREAD

**Issue by Jingye-Xia** [alist-org/alist#3708]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

不涉及

### Describe the bug / 问题描述

使用docker运行，已经映射了下面两个目录：
/opt/alist/data/temp/aria2
/opt/alist/data/temp/qbittorrent

环境变量：
PUID=0
PGID=0
UMASK=022

启动docker以后查看日志，会有一条报错”failed delete temp file: unlinkat /opt/alist/data/temp/qbittorrent: device or resource busy“，请问这是什么原因呢？

### Reproduction / 复现链接

不涉及

### Logs / 日志

[36mINFO[0m[2023-03-04 09:53:44] reading config file: data/config.json
[36mINFO[0m[2023-03-04 09:53:44] config file not exists, creating default config file
[36mINFO[0m[2023-03-04 09:53:44] load config from env with prefix:
[31mERRO[0m[2023-03-04 09:53:44] failed delete temp file: unlinkat /opt/alist/data/temp/qbittorrent: device or resource busy
[36mINFO[0m[2023-03-04 09:53:44] init logrus...
[36mINFO[0m[2023-03-04 09:53:44] Successfully created the admin user and the initial password is: 91A993G8
[36mINFO[0m[2023-03-04 09:53:44] start server @ 0.0.0.0:5244
[36mINFO[0m[2023-03-04 09:53:44] qbittorrent not ready.
[36mINFO[0m[2023-03-04 09:53:44] Aria2 not ready.

**Comment by Xhofe** [comment]
https://unix.stackexchange.com/questions/11238/how-to-get-over-device-or-resource-busy
