### ISSUE TITLE
隐藏目录问题（隐藏后大小不一致）

### ISSUE THREAD

**Issue by xing-yv** [alist-org/alist#3712]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

在元信息中将一个目录中部分目录隐藏后，该目录的父目录和该目录显示大小不一致

### Reproduction / 复现链接

http://49.235.159.169/OneDrive
好像无法直接访问，可以在浏览器手动输入

### Logs / 日志

![Screenshot_2023-03-05-10-17-27-856_com tencent mm](https://user-images.githubusercontent.com/109603760/222938555-0661a0d6-e021-4cd1-80f9-00661fea1932.png)
![Screenshot_2023-03-05-10-17-34-758_com tencent mm](https://user-images.githubusercontent.com/109603760/222938557-70f36a48-8c63-4d1d-8010-926650b89cc6.png)

**Comment by Xhofe** [comment]
这是onedrive API给出的大小，非程序计算。
