### ISSUE TITLE
“名称-降序”排列，是否有点小问题？

### ISSUE THREAD

**Issue by Bssn520** [alist-org/alist#3719]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

阿里云盘Open

#### 如图所示，后台存储设置里的顺序设置为“名称-降序”：
<img width="248" alt="image" src="https://user-images.githubusercontent.com/96654048/222949604-f1fce70e-01ec-49c3-bef6-e0b00dbea36f.png">    
结果如下图：
<img width="971" alt="image" src="https://user-images.githubusercontent.com/96654048/222949609-7a7b8fa8-4fe2-4fec-919a-87a7b312d748.png">    
99、98没问题，但是到了100，顺序就变得奇怪。点击左上角的名称之后可以正常排序，但一刷新又变得错误了。

### Reproduction / 复现链接

sorry

**Comment by Xhofe** [comment]
后台排序由阿里云盘提供，请向官方反馈。
![image](https://user-images.githubusercontent.com/36558727/222950071-05646e7d-fd4c-48d6-8bea-363cd70e7172.png)
