### ISSUE TITLE
MP3音乐播放器能否增加单曲播放完毕后停止的功能？

### ISSUE THREAD

**Issue by jxjxjhjh** [alist-org/alist#3725]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

一个文件夹中有多个MP3文件，播放时可以设置随机、单曲循环、列表循环和不循环，但无法在播放完一首歌曲后停止。
按照其他播放器的理解，在循环设定中如果时不循环，应该就会在播放完一首歌曲后停止，可是ALIST不是。

**Comment by elonshen** [comment]
将音频格式配置为视频播放器打开.
在管理页-设置-预览中,将‘音频类型’中格式剪切到‘视频类型’就行了.注意是剪切而不是复制.
<img width="789" alt="Screenshot 2024-10-10 at 20 06 12" src="https://github.com/user-attachments/assets/5714d3c4-334a-4d6d-adb2-33165bbd0382">
