### ISSUE TITLE
ALIST 312.2

### ISSUE THREAD

**Issue by zq500480** [alist-org/alist#3728]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

aliyundrive openai

### Describe the bug / 问题描述

<img width="652" alt="image" src="https://user-images.githubusercontent.com/34306818/223014214-5c2bbf83-0b8d-4343-94a0-b377c7a56f74.png">
用aria2离线下载，这样设置后就先清空下载目录，导致原来文件丢失

### Reproduction / 复现链接

<img width="652" alt="image" src="https://user-images.githubusercontent.com/34306818/223014323-9a43a94b-fbe9-4afe-85af-c80d520c00a4.png">

### Logs / 日志

<img width="652" alt="image" src="https://user-images.githubusercontent.com/34306818/223014306-c8a1b8c1-af7e-4cdc-8a08-b9f8159529e9.png">

**Comment by Xhofe** [comment]
不要将别的目录与alist目录混用。
