### ISSUE TITLE
请问怎样获取文件原始后缀的直链？

### ISSUE THREAD

**Issue by ma3252788** [alist-org/alist#3730]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.10.1

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

想用alist搭建轻松签源，但是添加需要.ipa结尾的直链，通过alist获取的直链后面有token，所以不行

请问有没有办法或者.ipa格式的直链呀？

### Reproduction / 复现链接

无

**Comment by MindFollowing** [comment]
管理 - 设置 -全局 - 签名所有（关闭） 

向所有文件的直接链接添加签名(无论是否有密码) 即https://xxxx.com/d/xx? sign=vUQ5KFXnwMseKnIUXGRcfoG3cEHzKFBiPGp1NriMDXA=:0
若需要关闭自行关闭即可，但需要注意安全问题，关闭签名后若站点能被公网访问，可能会被绕过密码访问私人文件。

**Comment by ma3252788** [comment]
> 管理 - 设置 -全局 - 签名所有（关闭）
> 
> 向所有文件的直接链接添加签名(无论是否有密码) 即https://xxxx.com/d/xx? sign=vUQ5KFXnwMseKnIUXGRcfoG3cEHzKFBiPGp1NriMDXA=:0 若需要关闭自行关闭即可，但需要注意安全问题，关闭签名后若站点能被公网访问，可能会被绕过密码访问私人文件。

明白了，太感谢了！！
