### ISSUE TITLE
alist 和 openclash 共存问题

### ISSUE THREAD

**Issue by zyu0090** [alist-org/alist#3731]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

alist 挂阿里云盘 open 模式，openclash 用 fake-ip 并开启绕开国内 ip ，一开始访问 alist 挂载的内容没问题，过了一会儿 alist 就读不了目录了，这是哪里的问题呢？

### Reproduction / 复现链接

试过openclash绕开5244端口及alist的webdav策略改为本地

**Comment by Xhofe** [comment]
out of scope

**Comment by kSirZX** [comment]
我也是这样的问题不知道如何解决······
