### ISSUE TITLE
Old Frontend at latest version

### ISSUE THREAD

**Issue by itsHenry35** [alist-org/alist#3736]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.13.0

### Driver used / 使用的存储驱动

/

### Describe the bug / 问题描述

Old frontend... Seems like you forgot to release the frontend so that the latest version is using the 3.12.1 frontend
![image](https://user-images.githubusercontent.com/58730749/223114764-e737f611-9c93-439b-a3af-1ce946ac09b3.png)

### Reproduction / 复现链接

/

**Comment by Xhofe** [comment]
My fault, I forgot to publish the web tag

**Comment by FW27623** [comment]
I guess that's why the third-party login button doesn't appear

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/releases/tag/v3.13.1
