### ISSUE TITLE
OneDrive 游客上传报错

### ISSUE THREAD

**Issue by 3152598423** [alist-org/alist#3741]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.1

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

Microsoft 365 OneDrive E5账号 游客上传报错
需勾上"应用到子文件夹"才可以上传
Cannot read properties of undefined (reading 'status')

### Reproduction / 复现链接

不明

### Logs / 日志

![image](https://user-images.githubusercontent.com/52593036/223186295-eb5e79cf-d7c0-4588-bc1f-a6f446ffe3e6.png)

<img width="1280" alt="20d673c37a3a5d28be05632a525b8e3" src="https://user-images.githubusercontent.com/52593036/223175921-60ab28a0-148e-48c4-adb1-6f9d4d819ff1.png">

**Comment by Xhofe** [comment]
请打开开发者工具提供一下网络请求信息。

**Comment by 3152598423** [comment]
<img width="1280" alt="1678168664580" src="https://user-images.githubusercontent.com/52593036/223333426-40d9b0c2-0941-464d-8598-314a76332abe.png">

**Comment by Xhofe** [comment]
控制台报什么错

**Comment by 3152598423** [comment]
![image](https://user-images.githubusercontent.com/52593036/223333928-b6d5e962-2edc-4891-b292-b43d30d4e623.png)

**Comment by 3152598423** [comment]
aliyun-web-office-sdk.min.js:1 aliyun JS-SDK V1.1.5
index.f670c9cc.js:21  AList  v3.13.1  https://github.com/Xhofe/alist
Folder.2ccd557a.js:1 solid-contextmenu-scale
Folder.2ccd557a.js:42 
        
       lightGallery: 0000-0000-000-0000 license key is not valid for production use
s.validateLicense @ Folder.2ccd557a.js:42
s @ Folder.2ccd557a.js:42
Ke @ Folder.2ccd557a.js:71
(匿名) @ Folder.2ccd557a.js:174
Fs @ index.f670c9cc.js:1
ao @ index.f670c9cc.js:1
Po @ index.f670c9cc.js:1
ng @ index.f670c9cc.js:1
(匿名) @ index.f670c9cc.js:1
Dr @ index.f670c9cc.js:1
tg @ index.f670c9cc.js:1
io @ index.f670c9cc.js:1
Dr @ index.f670c9cc.js:1
B @ index.f670c9cc.js:1
L @ index.f670c9cc.js:1
(匿名) @ index.f670c9cc.js:1
Upload.27f0cee7.js:1 undefined
index.f670c9cc.js:21 
        
       Ge {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
(匿名) @ index.f670c9cc.js:21
Promise.then(异步)
request @ index.f670c9cc.js:21
(匿名) @ index.f670c9cc.js:21
(匿名) @ index.f670c9cc.js:20
me @ Upload.27f0cee7.js:1
V @ Upload.27f0cee7.js:1
(匿名) @ Upload.27f0cee7.js:1
ce @ Upload.27f0cee7.js:1
k @ Upload.27f0cee7.js:1
onChange @ Upload.27f0cee7.js:1
Upload.27f0cee7.js:1 
        
       TypeError: Cannot read properties of undefined (reading 'status')
    at index.f670c9cc.js:21:14318
    at async Object.me [as upload] (Upload.27f0cee7.js:1:1763)
    at async V (Upload.27f0cee7.js:1:3528)
    at async Upload.27f0cee7.js:1:449
    at async u (Upload.27f0cee7.js:1:370)
    at async ce (Upload.27f0cee7.js:1:537)
    at async k (Upload.27f0cee7.js:1:3306)
V @ Upload.27f0cee7.js:1
await in V(异步)
(匿名) @ Upload.27f0cee7.js:1
ce @ Upload.27f0cee7.js:1
k @ Upload.27f0cee7.js:1
onChange @ Upload.27f0cee7.js:1
Upload.27f0cee7.js:1 undefined
index.f670c9cc.js:21 
        
      
        
        
      
        
      
       
        
       PUT https://68m72g5779.imdo.co/api/fs/put net::ERR_CONNECTION_RESET
(匿名) @ index.f670c9cc.js:21
Ll @ index.f670c9cc.js:21
Dl @ index.f670c9cc.js:21
Promise.then(异步)
request @ index.f670c9cc.js:21
(匿名) @ index.f670c9cc.js:21
(匿名) @ index.f670c9cc.js:20
me @ Upload.27f0cee7.js:1
V @ Upload.27f0cee7.js:1
(匿名) @ Upload.27f0cee7.js:1
ce @ Upload.27f0cee7.js:1
k @ Upload.27f0cee7.js:1
onChange @ Upload.27f0cee7.js:1

**Comment by Xhofe** [comment]
这应该是个bug

目前的解决方法可能是打开上传时 你需要勾选应用到子文件夹

**Comment by 3152598423** [comment]
好的好的，谢谢😀
