### ISSUE TITLE
3.11之后的版本，Apache反向代理到子目录出现重定向次数过多

### ISSUE THREAD

**Issue by shenlijun** [alist-org/alist#3742]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.1

### Driver used / 使用的存储驱动

百度网盘、webdav、smb

### Describe the bug / 问题描述

在ubuntu22.04上用apache2反向代理到alist子文件夹（实际上的alist是安装在另外一台局域网服务器上）。
3.11一直使用没有问题
新的版本会出现无法访问的问题，显示重定向次数过多，ERR_TOO_MANY_REDIRECTS；内网访问ip:port正常。

因为同时反代了gitea和alist，而gitea没有问题，只是alist不行

```
<VirtualHost *:80>
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>

<VirtualHost *:443>
    ServerName myapp.example.com
    DocumentRoot /www/myapp/public
    Protocols h2 h2c http/1.1
    SSLEngine on
    SSLCertificateFile ccc.fu
    SSLCertificateKeyFile ccc.key
    SSLUseStapling on
    AllowEncodedSlashes NoDecode
    ProxyPass "/alist" "http://10.9.0.21:5244" nocanon
</VirtualHost>
```

### Reproduction / 复现链接

[https://www.grandview.site/alist](https://www.grandview.site/alist)

### Logs / 日志

日志翻了下好像和3.11没有区别

**Comment by Xhofe** [comment]
链接后加 /alist

**Comment by shenlijun** [comment]
> 链接后加 /alist

这样还是重定向次数过多
```
<VirtualHost *:80>
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>

<VirtualHost *:443>
    ServerName myapp.example.com
    DocumentRoot /www/myapp/public
    Protocols h2 h2c http/1.1
    SSLEngine on
    SSLCertificateFile ccc.fu
    SSLCertificateKeyFile ccc.key
    SSLUseStapling on
    AllowEncodedSlashes NoDecode
    ProxyPass "/alist" "http://10.9.0.21:5244**/alist**" nocanon
</VirtualHost>
```

配置里的site_url是“/alist”

**Comment by Xhofe** [comment]
你提供的链接已经可以正常打开，你可以需要清除浏览器缓存。

**Comment by shenlijun** [comment]
> 链接后加 /alist



> 以正常打开，你可以需要清除浏览器缓存。

果然，感谢感谢
