### ISSUE TITLE
对单个文件添加markdown说明

### ISSUE THREAD

**Issue by ilihu** [alist-org/alist#3744]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

1. 对单个文件，例如视频，图片等文件的下方（文本文件就不需要了）添加markdown文字描述
2. 添加的 **markdown文字描述** 可以被索引
3. **markdown文字描述** 功能可以在后台关闭

**Comment by Xhofe** [comment]
可以自行在meta中添加。
