### ISSUE TITLE
开了2FA的账户无法通过API接口获取token

### ISSUE THREAD

**Issue by chung1912** [alist-org/alist#3748]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0

### Driver used / 使用的存储驱动

所有

### Describe the bug / 问题描述

https://github.com/alist-org/alist/discussions/2501
通过以上这个方式获取token，但是开了2FA的账号应该增加什么参数才能传递2FA Code？
报错如下

{
    "code": 402,
    "message": "Invalid 2FA code",
    "data": null
}

### Reproduction / 复现链接

同上

**Comment by Xhofe** [comment]
增加你的2fa验证码。

**Comment by Kuingsmile** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
> * [x]  I'm sure I'm using the latest version
> 
> ### Alist Version / Alist 版本
> v3.11.0
> 
> ### Driver used / 使用的存储驱动
> 所有
> 
> ### Describe the bug / 问题描述
> #2501 通过以上这个方式获取token，但是开了2FA的账号应该增加什么参数才能传递2FA Code？ 报错如下
> 
> { "code": 402, "message": "Invalid 2FA code", "data": null }
> 
> ### Reproduction / 复现链接
> 同上
> 
> ### Logs / 日志
> _No response_

![image](https://user-images.githubusercontent.com/96409857/223303461-e9773215-ffd7-47f6-8db5-b9e2458d621d.png)
根据源代码，请增加`OtpCode`参数
