### ISSUE TITLE
发现几个BUG，查找问题也有人提到过。

### ISSUE THREAD

**Issue by alimalls** [alist-org/alist#3751]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.1

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

我的问题是这样的，
我部署onedrive，设置了某个目录需要密码访问，在元信息里也把应用到子目录勾上了，但是却不生效，只有进入一级目录的时候提示输入密码，再进入二级目录后，不需要密码。，而且我也发现我部署的，在首页通过搜索某个我已知的文件名，可以直接访问不需要密码【这个文件存放的目录，事实我已经设置了元信息，需要密码访问的。】不知道是哪里的问题引起的。

### Reproduction / 复现链接

无

### Logs / 日志

无

**Comment by anwen-anyi** [comment]
说一下你的AList版本号，截图你元信息的所有配置，相关信息打码，发一下试试看
