### ISSUE TITLE
能不能加一个 alist 的ping接口? 容器健康检查 => 单纯验证alist服务 是否 成功启动 和链路检验 ? 不涉及挂载网盘那些..

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#3752]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

容器内做健康检查，一般1分钟ping一次，
本来使用默认的:5244/来验证，但是发现每次都返回html.. 
每分钟要处理一个html模板/静态文件传输, 感觉有点消耗/浪费资源...

参考ocr接口那种 /ping返回 pong 就挺好... 不过alist这边考虑下用一个特殊接口不和挂载盘路径冲突=> 比如 /ping.do? 返回pong来验证?

为何要这个接口: 
K8S 避免宕机 少数情况 pod重启分配新节点(没内部负载)，alist虽然启动成了，但是node port服务不会重新启动导致节点内部cdn没有刷新新pod分配的ip，最终导致访问不到alist...
有了健康检查 ping接口，可以设置ping3次失败，容器和backend node port全部自动重启 来保证服务全部重新上线。

**Comment by Xhofe** [comment]
你可以把 https://al.nn.ci/api/public/settings 当作是ping接口。
