### ISSUE TITLE
115网盘上传出错

### ISSUE THREAD

**Issue by szshaojiang** [alist-org/alist#3753]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.1

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

115网盘上传出错
打开 删除 下载都正常

### Reproduction / 复现链接

上传
result.txt

错误
-/s

请升级到最新版本: unexpected error
![屏幕截图 2023-03-07 130118](https://user-images.githubusercontent.com/23231380/223325113-029cef67-4c10-4663-b723-b60706018949.jpg)

**Comment by Yejia995** [comment]
相同错误

**Comment by Xhofe** [comment]
对不起 这是上级依赖的问题 请向上级仓库反馈：https://github.com/sheltonzhu/115driver

**Comment by Yejia995** [comment]
已经提交了Pull request给上级了，稍微等一下吧

**Comment by god2456** [comment]
一样有问题，求解决

**Comment by smarxtboy** [comment]
115上传错误，这个bug 开发什么时候可以解决。目前最新版本3.13.2 问题依然存在。请尽快解决谢谢！
