### ISSUE TITLE
failed to verify certificate: x509

### ISSUE THREAD

**Issue by guinanlin** [alist-org/alist#3755]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.11.0

### Driver used / 使用的存储驱动

seafile

### Describe the bug / 问题描述

1, 安装seafile, 且正常配置基于ip的ssl. 属于自签名证书.  意思是用户需要本地浏览器需要自己导入CA证书才能正常访问seafile.
seafile 访问地址: https://192.168.8.189:8443/, 同时针对 http 80 端口做了重定向到 https 443端口.

2, 配置alist seafile
![image](https://user-images.githubusercontent.com/44794953/223349754-fd8823e0-3c32-4494-b9f2-5e0e33126bc4.png)

显示报错信息:
Failed init storage: Post "https://***********89:8443/api2/auth-token/": tls: failed to verify certificate: x509: certificate signed by unknown authority

### Reproduction / 复现链接

参照如上的问题描述.

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/config/configuration.html#tls-insecure-skip-verify

**Comment by guinanlin** [comment]
果真可以了, 感谢, 感谢.
