### ISSUE TITLE
Baidu网盘获取token失败

### ISSUE THREAD

**Issue by chenbojian** [alist-org/alist#3757]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.12.2

### Driver used / 使用的存储驱动

BaiduNetDisk

### Describe the bug / 问题描述

获取刷新令牌失败

<img width="611" alt="image" src="https://user-images.githubusercontent.com/4935201/223364840-83ab8b02-c3a4-4906-9481-89c407edd8ab.png">

### Reproduction / 复现链接

https://alist-doc.nn.ci/docs/driver/baidu/

https://openapi.baidu.com/oauth/2.0/authorize?response_type=code&client_id=iYCeC9g08h5vuP9UqvPHKKSVrKFXGa1v&redirect_uri=https://tool.nn.ci/baidu/callback&scope=basic,netdisk&qrcode=1

**Comment by chenbojian** [comment]
相关issue 
https://github.com/alist-org/alist/issues/3475

**Comment by Xhofe** [comment]
https://alist.nn.ci/
