### ISSUE TITLE
希望能更新内置的artplayer到目前的最新版本。

### ISSUE THREAD

**Issue by kimycai** [alist-org/alist#3762]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

当前内置版本为4.5.4，最新的artplayer版本为4.6.2，不知可否将内置播放器升级至功能更多的最新版

**Comment by Bssn520** [comment]
+1

**Comment by mengguyi** [comment]
+1
