### ISSUE TITLE
按照数值对文件进行排序

### ISSUE THREAD

**Issue by renbaoshuo** [alist-org/alist#3764]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在一些情况下会遇到文件夹内文件是按照 `1.` `2.` `3.` ... 等规律进行命名的。然而当前 Alist 的排序行为似乎是逐字符比较，这会导致出现 `1.` `10.` `11.` `12.` ... `19.` `2.` `20.` ... 的情况。因此请求增加按照数值对文件进行排序的功能。

### Suggested solution / 实现思路

https://stackoverflow.com/a/73073707/14109955

有一个 C# 的比较器实现 —— AlphanumComparator，可以作为参考。

### Additional context / 附件

![Snipaste_2023-03-08_06-25-36](https://user-images.githubusercontent.com/47095648/223567798-ff8c8e59-a98c-4c5a-9af6-af1cb9c652a4.png)

在 Windows 系统中该选项可以通过组策略来进行开启/关闭。

**Comment by Xhofe** [comment]
我们已经做了`natural sort`，具体见#2612，部分没有`natural sort`的是因为网盘的API提供了排序选项，所以提供的就直接使用了，其中的体验应该是与网盘一致的。

**Comment by renbaoshuo** [comment]
好的，感谢您的解答。
