### ISSUE TITLE
qbittorrent下载完成后无法做种。

### ISSUE THREAD

**Issue by kimycai** [alist-org/alist#3765]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在qbittorrent本体程序中看不到下载的种子信息，且无法做种，这对于某些有做种要求的站点来说是不利的，不知能否修正？

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/issues/3588
