### ISSUE TITLE
百度网盘令牌获取失败

### ISSUE THREAD

**Issue by Wuxiaolong962464** [alist-org/alist#3768]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.1

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

您遇到了错误！
错误代码：redirect_uri_mismatch
错误信息：Invalid redirect uri
详细描述：授权回调页地址错误，具体内容请开发者参考[“redirect uri”验证方](http://developer.baidu.com/wiki/index.php?title=docs/oauth/redirect)

### Reproduction / 复现链接

https://openapi.baidu.com/oauth/2.0/authorize?response_type=code&client_id=iYCeC9g08h5vuP9UqvPHKKSVrKFXGa1v&redirect_uri=https://tool.nn.ci/baidu/callback&scope=basic,netdisk&qrcode=1

### Logs / 日志

[https://imgse.com/i/ppmEong](url)

**Comment by Rektyfikowany** [comment]
有效获取链接：[https://openapi.baidu.com/oauth/2.0/authorize?response_type=code&client_id=iYCeC9g08h5vuP9UqvPHKKSVrKFXGa1v&redirect_uri=https://alist.nn.ci/tool/baidu/callback&scope=basic,netdisk&qrcode=1](https://openapi.baidu.com/oauth/2.0/authorize?response_type=code&client_id=iYCeC9g08h5vuP9UqvPHKKSVrKFXGa1v&redirect_uri=https://alist.nn.ci/tool/baidu/callback&scope=basic,netdisk&qrcode=1)
文档地址：[https://alist.nn.ci/zh/guide/drivers/baidu.html](https://alist.nn.ci/zh/guide/drivers/baidu.html)

**Comment by anwen-anyi** [comment]
盲猜楼主用的V2获取刷新令牌，哪个早换了 不能用了，用V3的文档
