### ISSUE TITLE
阿里云盘 Open 无法获取refresh_token，页面报错，无返回

### ISSUE THREAD

**Issue by xujipm** [alist-org/alist#3770]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.1

### Driver used / 使用的存储驱动

阿里云盘 Open

### Describe the bug / 问题描述

两种方式均无法获取
![image](https://user-images.githubusercontent.com/3202911/223695197-1f4859da-5098-4fa9-aff5-2682df914e9a.png)
![image](https://user-images.githubusercontent.com/3202911/223695494-de591643-5bd8-49fd-ab92-f6b17a77d4b5.png)

### Reproduction / 复现链接

https://alist.nn.ci/tool/aliyundrive/request.html

**Comment by Xhofe** [comment]
一切正常 无法复现。

我们的API部署在国外，请检查与 https://api.nn.ci/ 的通信情况。

**Comment by xujipm** [comment]
> 一切正常 无法复现。
> 
> 我们的API部署在国外，请检查与 https://api.nn.ci/ 的通信情况。

我尝试过使用美国的代理，也是相同的状况呢，晚点我再试试其他地区的代理吧
