### ISSUE TITLE
是否可以间接实现在线看共享盘

### ISSUE THREAD

**Issue by nbtianyige** [alist-org/alist#3777]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

自打阿里open接口推出来，阿里共享驱动没法看共享盘了

### Suggested solution / 实现思路

1、自定义自己的阿里云盘某个目录为缓存目录
2、通过alist挂载别人的阿里共享盘
3、在alist看某个共享盘上的资源的时候，alist将这个资源另存到自己阿里云盘上的缓存目录，然后实际在线看的是缓存目录上的
4、设置缓存目录的策略，比如超过多少空间占比，自动清理，或者缓存时间

**Comment by Xhofe** [comment]
阿里云盘开放平台暂不提供转存API，故无法实现。请关注：https://www.yuque.com/aliyundrive/zpfszx

**Comment by anwen-anyi** [comment]
> > 阿里云盘开放平台暂不提供转存API，故无法实现。请关注：https://www.yuque.com/aliyundrive/zpfszx
> 
> 可否用老接口。下面这个项目的issue里也有提到转存用老接口 git项目https://github.com/adminpass/aliyundrive-subscribe
> 
> 我的意思是挂共享和转存用老的接口，播放的时候用open接口

这样做不符合 使用阿里云盘开放平台开发者 `TOS` 条款吧...:sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile:

**Comment by playingapi365one** [comment]
+1   

就是实现转存自动播放  自动清理功能, 之前pikpak分享挂掉的时候 也提过这样的需求, 后来被关了, 说不实现

考虑阿里云盘的资源太多,  实现这个功能十分必要,  而且理论上应该是可以实现的

另外 识别如果挂载的分享目录  在网页上显示一个按钮 可以复制当前挂载的分享的链接  方便用户手动转存

**Comment by Xhofe** [comment]
为避免client被封禁 我们不会这样做。

**Comment by anwen-anyi** [comment]
> +1
> 
> 就是实现转存自动播放 自动清理功能, 之前pikpak分享挂掉的时候 也提过这样的需求, 后来被关了, 说不实现
> 
> 考虑阿里云盘的资源太多, 实现这个功能十分必要, 而且理论上应该是可以实现的
> 
> 另外 识别如果挂载的分享目录 在网页上显示一个按钮 可以复制当前挂载的分享的链接 方便用户手动转存

这样是爽了，那到时候开发者授权也别要了.. :sweat_smile:

**Comment by playingapi365one** [comment]
可以fork一个版本出去    就说跟alist 没关系

**Comment by playingapi365one** [comment]
网上大量的共享盘都是挂阿里分享实现的   不能看共享实在是太可惜了

**Comment by playingapi365one** [comment]
估计大部分alist用户都是挂阿里资源的  说不维护这个接口了  影响面太大了

**Comment by nbtianyige** [comment]
或许以后还有其他方案，要么这个case关了吧

**Comment by linkq** [comment]
请求添加功能：右键菜单增加查看阿里云分享的原始链接

**Comment by playingapi365one** [comment]
在阿里open 中看到:
"
二、

默认使用的是阿里云盘自带播放器 - Aliyun Video Previewer

上传到云盘的视频，会经过转码服务转成 H.264 编码的视频流。（好处是 IOS 可以播放了...嗯 应该是这样）

新上传到云盘的视频，默认只预转码视频的前 30s。第一次播放时会触发完整的视频转码。转码后的视频会缓存，之后再次触发播放不需要重新转码。
不足 30s 的视频不会触发预转码，只会在第一次播放时开始转码。
实时转码需要一定时间。
画质分别为：LD|SD|HD|FHD|QHD
"


看阿里分享是不是也可以用Aliyun Video Previewer， 然后选择hd画质, 实现流畅播放,   在alist哪里设置？？

**Comment by anwen-anyi** [comment]
> 在阿里open 中看到: " 二、
> 
> 默认使用的是阿里云盘自带播放器 - Aliyun Video Previewer
> 
> 上传到云盘的视频，会经过转码服务转成 H.264 编码的视频流。（好处是 IOS 可以播放了...嗯 应该是这样）
> 
> 新上传到云盘的视频，默认只预转码视频的前 30s。第一次播放时会触发完整的视频转码。转码后的视频会缓存，之后再次触发播放不需要重新转码。 不足 30s 的视频不会触发预转码，只会在第一次播放时开始转码。 实时转码需要一定时间。 画质分别为：LD|SD|HD|FHD|QHD "
> 
> 看阿里分享是不是也可以用Aliyun Video Previewer， 然后选择hd画质, 实现流畅播放, 在alist哪里设置？？

不可以 别想着分享了

**Comment by playingapi365one** [comment]
测试过其他软件  都可以实现转码流畅播放  

alist不方便实现分享链接转存  那能否把分享链接的转码播放做进去实现流畅播放

**Comment by anwen-anyi** [comment]
> 测试过其他软件 都可以实现转码流畅播放
> 
> alist不方便实现分享链接转存 那能否把分享链接的转码播放做进去实现流畅播放
> 
> “上传到云盘的视频，会经过转码服务转成 H.264 编码的视频流”
> 
> 那能能否加个选项直接请求转码后的数据？

最开始是有这个选项的，无法播放的哦~  你可以倒退到 3.12.0试试就知道啦 https://github.com/alist-org/alist/issues/3582

**Comment by playingapi365one** [comment]
> 那能能否加个选项直接请求转码后的数据？

海阔视界的云盘汇影小程序视实现了转码播放

我看到代码里面有这句代码

                        playLink = 'http://113.107.160.110:3000/apis/yun-play/'+share_id+'/'+file_id+'/'+access_token+'/'+share_token+'/'+value+'/'+drive_id+'/'+user_id+'/'+device_id+'/index.m3u8';


它调用了一个api去实现了转码播放

https://github.com/alist-org/alist/issues/3582#issuecomment-1442837778   这里说阿里分享不支持Aliyun Video Previewer，
是否可以用上面说的方法实现？

**Comment by yzqiang666** [comment]
自改自用吧。

**Comment by playingapi365one** [comment]
自动转存被小雅实现了 

curl -s http://docker.xiaoya.pro/update_xiaoya_test.sh | bash


./alist version
Built At: 2023-03-13 [15:25:04](https://web.telegram.org/k/#) +0000
Go Version: go1.20.2 linux/amd64
Author: Xhofe <[i@nn.ci](mailto:i@nn.ci)>
Commit ID: 3d3f23e
Version: v3.13.1
WebVersion: xiaoya-2023-03-13 [15:25:04](https://web.telegram.org/k/#) +0000

**Comment by nbtianyige** [comment]
> 自动转存被[小雅](https://t.me/xiaoyaliu)实现了
> 
> curl -s http://docker.xiaoya.pro/update_xiaoya_test.sh | bash
> 
> ./alist version Built At: 2023-03-13 [15:25:04](https://web.telegram.org/k/#) +0000 Go Version: go1.20.2 linux/amd64 Author: Xhofe <[i@nn.ci](mailto:i@nn.ci)> Commit ID: [3d3f23e](https://github.com/alist-org/alist/commit/3d3f23ec9e6b763101906459eea40b0475f46e49) Version: v3.13.1 WebVersion: xiaoya-2023-03-13 [15:25:04](https://web.telegram.org/k/#) +0000
> 
> api/fs/get
> 
> { "code":200, "message":"success", "data":{ "name":"Downfall.The.Case.Against.Boeing.2022.2160p.NF.WEB-DL.DDP5.1.DV.HDR10.H.265-SMURF.mkv", "size":10237743260, "is_dir":false, "modified":"2023-01-08T10:31:48.477Z", "sign":"", "thumb":"", "type":2, "raw_url":"[https://cn-beijing-data.aliyundrive.net/A8F5QPYW%2F607180%2F63ba8e33798afe77665a47c18f837b86652bc146%2F63ba8e337e897caab4b64af991600513fa0bb6e7?di=bj29\u0026dr=412102150\u0026f=64117f94d84803918eb04f0995fb03ae4379bdf5\u0026response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27Downfall.The.Case.Against.Boeing.2022.2160p.NF.WEB-DL.DDP5.1.DV.HDR10.H.265-SMURF.mkv\u0026security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bnEu7tnetOzaeMVR6GljQfOsJch5ffujz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNTjdTCHRqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABDzZTmGjKO0ObIxmXqO9zIoGXfecv%2B2gAvzp2mb8R1Z9SwiIFmKn7NSC6Z1TP9tTulbTpvKMqCh%2BorLRQ65%2FWf29s2Qo%2BjcR4YIRgsQArBX0Fo8sQ4j4PrI09zqgwfy%2FP91b8oPRtoJP8aLDw%2FNjLZ6ua2pSGG%2Fgfh8463H506VA%3D\u0026u=254808010963075794\u0026x-oss-access-key-id=STS.NURYTYp4ozegW87r4J6MphRtX\u0026x-oss-expires=1678882775\u0026x-oss-signature=EoWPsYarXVoJd3eyXZrCBS3LAJ0z1Gd4Pp%2B7FVyIGVM%3D\u0026x-oss-signature-version=OSS2](https://cn-beijing-data.aliyundrive.net/A8F5QPYW%2F607180%2F63ba8e33798afe77665a47c18f837b86652bc146%2F63ba8e337e897caab4b64af991600513fa0bb6e7?di=bj29%5Cu0026dr=412102150%5Cu0026f=64117f94d84803918eb04f0995fb03ae4379bdf5%5Cu0026response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27Downfall.The.Case.Against.Boeing.2022.2160p.NF.WEB-DL.DDP5.1.DV.HDR10.H.265-SMURF.mkv%5Cu0026security-token=CAIS%2BgF1q6Ft5B2yfSjIr5bnEu7tnetOzaeMVR6GljQfOsJch5ffujz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNTjdTCHRqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABDzZTmGjKO0ObIxmXqO9zIoGXfecv%2B2gAvzp2mb8R1Z9SwiIFmKn7NSC6Z1TP9tTulbTpvKMqCh%2BorLRQ65%2FWf29s2Qo%2BjcR4YIRgsQArBX0Fo8sQ4j4PrI09zqgwfy%2FP91b8oPRtoJP8aLDw%2FNjLZ6ua2pSGG%2Fgfh8463H506VA%3D%5Cu0026u=254808010963075794%5Cu0026x-oss-access-key-id=STS.NURYTYp4ozegW87r4J6MphRtX%5Cu0026x-oss-expires=1678882775%5Cu0026x-oss-signature=EoWPsYarXVoJd3eyXZrCBS3LAJ0z1Gd4Pp%2B7FVyIGVM%3D%5Cu0026x-oss-signature-version=OSS2)", "readme":"\u003cFORM METHOD=GET ACTION=/search id="searchform"\u003e \n\u003cinput class="search__input" type="text" name="box" placeholder=" 输入搜索关键词" \u003e \n\u003cinput type="hidden" name="url"\u003e \n\u003cinput type="hidden" name="type" value="video"\u003e \n\u003c/FORM\u003e \n\n\u003ca href=https://t.me/xiaoyaliu target=_blank\u003e\u003ch3 align=right\u003e订阅小雅的tg频道\u003c/h3\u003e\u003c/a\u003e\n\u003ch2\u003e热搜\u003c/h2\u003e\u003cbr\u003e\n\u003ca href=[http://img.xiaoya.pro/dashan.png\u003e\u003cimg](http://img.xiaoya.pro/dashan.png%5Cu003e%5Cu003cimg) src='https://s2.loli.net/2023/02/19/JKsEuWwYLTNfme8.png' width='30%' align=right valign=top\u003e\u003c/a\u003e\n\u003ca href=/每日更新/电视剧/国产剧/少年歌行\u003e少年歌行\u003c/a\u003e\u0026emsp;\n\u003ca href=/每日更新/电视剧/国产剧/风吹半夏\u003e风吹半夏\u003c/a\u003e\u0026emsp;\n\u003ca href=/每日更新/电视剧/国产剧/打开生活的正确方式\u003e打开生活的正确方式\u003c/a\u003e\u0026emsp;\n\u003ca href=/每日更新/电视剧/国产剧/回来的女儿\u003e回来的女儿\u003c/a\u003e\u0026emsp;\n\u003ca href=/每日更新/电视剧/日剧/重启人生\u003e重启人生（日剧）\u003c/a\u003e\u0026emsp;\u003cp\u003e\n\n\u003ca href=/每日更新/电视剧/韩剧/黑暗荣耀\u003e黑暗荣耀（韩剧）\u003c/a\u003e\u0026emsp;\n\u003ca href=/电视剧/韩国/C%20%7C%20财阀家的小儿子\u003e财阀家的小儿子（韩剧）\u003c/a\u003e\u0026emsp;\n\u003ca href=/每日更新/电视剧/韩剧/赌命为王\u003e赌命为王（韩剧）\u003c/a\u003e\u0026emsp;\n\u003ca href=/电视剧/中国/未分类-1/天下长河（40集全）\u003e天下长河\u003c/a\u003e\u0026emsp;\u003cp\u003e\n\n\u003ca href=/每日更新/电视剧/TVB%20Viu/傲娇与章经\u003e傲娇与章经（TVB）\u003c/a\u003e\u0026emsp;\n\u003ca href=/每日更新/电视剧/国产剧/狂飙\u003e狂飙\u003c/a\u003e\u0026emsp;\n\u003ca href=/每日更新/电视剧/美剧/最后生还者\u003e最后生还者（美剧）\u003c/a\u003e\u0026emsp;\n\u003ca href=/每日更新/电视剧/国产剧/三体\u003e三体\u003c/a\u003e\u0026emsp;\n\u003chr width=60% style="border:0; border-width:0; color:gray; background-color:gray"\u003e\u003cp\u003e\n小雅的近期推荐：\n\u003ca href=http://recommend.xiaoya.pro/xiaoya/1.html target=_blank\u003e一期\u003c/a\u003e\u0026emsp;\n\u003ca href=http://recommend.xiaoya.pro/xiaoya/2.html target=_blank\u003e二期\u003c/a\u003e\u0026emsp;\n\u003ca href=http://recommend.xiaoya.pro/xiaoya/3.html target=_blank\u003e三期\u003c/a\u003e\u0026emsp;\n\u003ca href=http://recommend.xiaoya.pro/xiaoya/4.html target=_blank\u003e四期\u003c/a\u003e\u0026emsp;\n\u003ca href=http://recommend.xiaoya.pro/xiaoya/5.html target=_blank\u003e五期\u003c/a\u003e\u0026emsp;\n\u003ca href=http://recommend.xiaoya.pro/xiaoya/6.html target=_blank\u003e六期\u003c/a\u003e\u003cbr\u003e\n\u003cb style="color:Red;"\u003e最新：\u003c/b\u003e\u003ca href=/每日更新/电视剧/英剧/网络暗战%20The%20Undeclared%20War%20第一季\u003e网络暗战\u003c/a\u003e\u0026emsp;\n\u003cb style="color:Red;"\u003e宝藏：\u003c/b\u003e\u003ca href=/每日更新/电视剧/台湾/斯卡罗\u003e斯卡罗\u003c/a\u003e\n\u003chr width=60% style="border:0; border-width:0; color:gray; background-color:gray"\u003e\n\n\u003cp\u003e\n\u003ch3 style="color: #CC3333;"\u003e测试目录下的内容不限速，但只有在安装docker的环境下才能观看，请及早下载安装\u003c/h3\u003e\n\u003cp\u003e\n\u003cb\u003e小雅的alist 的docker镜像\u003c/b\u003e\u003cbr\u003e\n1. 内容一样\n\u003ch4 style="color: #CC3333;"\u003e2. 因为阿里风控的原因，一定要自己搭建并替换自己的token，不然无法提供在线播放。如果没有docker环境，或者不愿意折腾的，可以联系我 \u003ca href=[https://t.me/liuxiaoya00\u003et.me/liuxiaoya00\u003c/a\u003e](https://t.me/liuxiaoya00%5Cu003et.me/liuxiaoya00%5Cu003c/a%5Cu003e) 代建托管，18元/月\u003c/h4\u003e\n3. 本服务器在海外，你连接你本地服务器肯定更快更稳\u003cbr\u003e\n4. 对于用webdav方式挂载的内容，是要通过本机代理，受制于本服务器网络的延迟和带宽，而你本地没有这个问题\n\u003cp\u003e\n\u003cb\u003e一键安装和更新容器\u003c/b\u003e\u003cbr\u003e\ncurl -s http://docker.xiaoya.pro/update_xiaoya.sh | bash\n\u003cp\u003e\n端口：5678\u003cbr\u003e\n访问： http://xxxxx:5678/ （xxxx 为你alist所在设备的 IP）\n\u003cp\u003e\nwebdav 账号密码\u003cbr\u003e\n用户: guest\n密码: guest_Api789\n\u003cp\u003e\n\u003cb\u003e重启就会自动更新数据库及搜索索引文件\u003c/b\u003e\u003cbr\u003e\ndocker restart xiaoya\n\u003cp\u003e\n\u003ca href="[https://www.notion.so/xiaoyaliu/xiaoya-docker-69404af849504fa5bcf9f2dd5ecaa75f\](https://www.notion.so/xiaoyaliu/xiaoya-docker-69404af849504fa5bcf9f2dd5ecaa75f%5C)" target=_blank style="color:black;"\u003e\u003ch1 style="color:black;"\u003e详细的配置指南请点击打开\u003c/h1\u003e\u003c/a\u003e\n\n\u003cscript\u003e\nfunction addsearch() {\n let searchObj = document.querySelector(".markdown-body form");\n if(searchObj){\n let headRight = document.querySelector(".header-right");\n headRight.prepend(searchObj);\n searchObj.querySelector('input').style.width="90%";\n }\n else{\n setTimeout(()=\u003e{\n addsearch();\n },333);\n }\n }\n addsearch();\n\u003c/script\u003e", "provider":"AliyundriveShare2Open", "related":null } }

xiaoya的docker我部署了，admin密码也拿到了，但是@manage链接被改了，没时间仔细研究，无法自己加资源
