### ISSUE TITLE
能否让元信息关联单个用户

### ISSUE THREAD

**Issue by aliuq** [alist-org/alist#3789]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在元信息对应的是文件夹的权限，而一条元信息针对的是所有用户，比如，我隐藏了`阿里云盘1`，那只要拥有查看隐藏内容的权限，都能看到这个文件夹，这样感觉不是很友好，如果能在添加元信息的时候，根据路径，指定用户权限，那么就避免了让用户A和B能看到所有隐藏的内容，可以达到针对用户A，隐藏阿里云盘1，针对用户B，隐藏阿里云盘2

### Suggested solution / 实现思路

在添加元信息里面，增加一个用户对应密码、写入、隐藏的关系

**Comment by Flover-am** [comment]
臣附议！！
alist现在的访问权限控制功能很不完善，元信息和用户是控制权限的两种方式，但是会有很多情况，是搭配使用这两者也无法达成的。希望能够像 aliuq 说的那样，起码这是一个不需要添加新功能就可以实现的简单思路

**Comment by 13860605362** [comment]
同样希望拥有这个功能，如果元信息可以选择一个或多个受影响的用户，这样可以对文件权限有更细致的划分。
比如同一层级下有ABC三个文件夹，此时有两个用户。当我希望用户1可以浏览AC文件夹，用户2可以浏览BC文件夹，目前没有很方便的解决办法。
