### ISSUE TITLE
S3对象存储是否可以关闭证书验证

### ISSUE THREAD

**Issue by 1314mjf521** [alist-org/alist#3794]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.13.2

### Driver used / 使用的存储驱动

华为的S3对象存储

### Describe the bug / 问题描述

failed get objs: failed to list objs: RequestError: send request failed caused by: Get "https://iso.obs.cidc-rp-2063.jsszkszwyhlwq1.joint.cmecloud.cn/?delimiter=%2F&list-type=2&prefix=": tls: failed to verify certificate: x509: certificate signed by unknown authority

在特殊对象存储桶中由于证书为自签证书，在获取远端的S3协议版本时出现证书验证错误无法使用，在使用时是否可以关闭存储桶的证书验证避免此类问题的出现？

### Reproduction / 复现链接

http://gt.majunfei.club:5244/HCSO%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8

**Comment by 1314mjf521** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
> * [x]  I'm sure I'm using the latest version
> 
> ### Alist Version / Alist 版本
> V3.13.2
> 
> ### Driver used / 使用的存储驱动
> 华为的S3对象存储
> 
> ### Describe the bug / 问题描述
> failed get objs: failed to list objs: RequestError: send request failed caused by: Get "https://iso.obs.cidc-rp-2063.jsszkszwyhlwq1.joint.cmecloud.cn/?delimiter=%2F&list-type=2&prefix=": tls: failed to verify certificate: x509: certificate signed by unknown authority
> 
> 在特殊对象存储桶中由于证书为自签证书，在获取远端的S3协议版本时出现证书验证错误无法使用，在使用时是否可以关闭存储桶的证书验证避免此类问题的出现？
> 
> ### Reproduction / 复现链接
> http://gt.majunfei.club:5244/HCSO%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8
> 
> ### Logs / 日志
> _No response_
刚看到处理方案我测试下

**Comment by qia0756** [comment]
同样有此需求，比如自建的s3（minio），不一定会有证书，这个时候就没法用了，可以参考rclone，他有一个--no-check-certificate选项，这边在配置对象存储的时候也做一个不验证证书的选项，谢谢。

**Comment by 1314mjf521** [comment]
> 同样有此需求，比如自建的s3（minio），不一定会有证书，这个时候就没法用了，可以参考rclone，他有一个--no-check-certificate选项，这边能否在配置对象存储的时候也做一个不验证证书的选项，谢谢。

我当时直接把证书在服务器上做了下信任，然后就能直接使用了，换句话说我尝试过直接给他套个壳简单省事
