### ISSUE TITLE
Rclone挂载alist阿里云open可浏览目录，但无法读取和下载

### ISSUE THREAD

**Issue by commandoccz** [alist-org/alist#3802]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.2

### Driver used / 使用的存储驱动

阿里云/和彩云

### Describe the bug / 问题描述

Rclone挂载alist阿里云open可浏览目录，但无法读取和下载，显示403Forbidden，和彩云正常读取和下载
![image](https://user-images.githubusercontent.com/76011848/224465851-4c1703a2-3f97-48da-81fb-015e58dd67ca.png)

### Reproduction / 复现链接

无

### Logs / 日志

2023/03/11 12:59:42 ERROR : aliyundriver/共享文件夹/IMG_8831.JPG/IMG_8831.JPG: vfs cache: failed to download: vfs reader: failed to write to cache file: 403 Forbidden
2023/03/11 12:59:42 ERROR : aliyundriver/共享文件夹/IMG_8831.JPG/IMG_8831.JPG: vfs cache: too many errors 34/10: last error: vfs reader: failed to write to cache file: 403 Forbidden
2023/03/11 12:59:42 ERROR : aliyundriver/共享文件夹/IMG_8831.JPG/IMG_8831.JPG: vfs cache: failed to kick waiters: vfs reader: failed to write to cache file: 403 Forbidden
2023/03/11 12:59:42 ERROR : aliyundriver/共享文件夹/IMG_8831.JPG/IMG_8831.JPG: vfs cache: failed to _ensure cache vfs reader: failed to write to cache file: 403 Forbidden
2023/03/11 12:59:42 ERROR : IO error: vfs reader: failed to write to cache file: 403 Forbidden
2023/03/11 12:59:42 ERROR : aliyundriver/共享文件夹/IMG_8831.JPG/IMG_8831.JPG: vfs cache: failed to download: vfs reader: failed to write to cache file: 403 Forbidden
2023/03/11 12:59:42 ERROR : aliyundriver/共享文件夹/IMG_8831.JPG/IMG_8831.JPG: vfs cache: too many errors 35/10: last error: vfs reader: failed to write to cache file: 403 Forbidden
2023/03/11 12:59:42 ERROR : aliyundriver/共享文件夹/IMG_8831.JPG/IMG_8831.JPG: vfs cache: failed to kick waiters: vfs reader: failed to write to cache file: 403 Forbidden
2023/03/11 12:59:42 ERROR : aliyundriver/共享文件夹/IMG_8831.JPG/IMG_8831.JPG: vfs cache: failed to _ensure cache vfs reader: failed to write to cache file: 403 Forbidden
2023/03/11 12:59:42 ERROR : IO error: vfs reader: failed to write to cache file: 403 Forbidden

**Comment by commandoccz** [comment]
和彩印一切正常
![image](https://user-images.githubusercontent.com/76011848/224466066-ba55c209-028f-4517-97f6-9902b2a754e0.png)

**Comment by simon-ding** [comment]
同样的问题，和哪个issue重复了？

**Comment by commandoccz** [comment]
没有啊，啥情况？

**Comment by commandoccz** [comment]
哈，我在文档评论区说了那么一句，我去，这也算重复。。。。 #161

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/discussions/630

**Comment by commandoccz** [comment]
@Xhofe 大大抱歉，因为之前都用的好好的，升级了才出现的问题，我以为是新问题，忘了搜索一下issue

**Comment by simon-ding** [comment]
大佬，我加了Referer也不行。我的alist部署在vps上的，不能改成本地代理，问题中的两种方法对我都无效。

之前一直都可以的，最近这几个版本更新就不行了，挂载的方式一直没变过。

帮忙看一下，感谢！

**Comment by commandoccz** [comment]
@simon-ding webdav不支持重定向，要不就弄个cdn搞个worker 下载代理 URL[https://alist.nn.ci/zh/guide/drivers/common.html#webdav-策略](url)

**Comment by simon-ding** [comment]
> 

cloudflare速度也太慢了。

我研究了个下，这个问题好像和golang的http库有关，golang不会转发http referer导致的referer的host是原来的host，阿里云认为是跨域访问，大概率就给禁了，见 [issues 44160](https://github.com/golang/go/issues/44160)

目前看来只能寄希望于这个bug修复，不过看这个bug挂的时间估计还要等好久
