### ISSUE TITLE
网页播放器点击网页全屏版式错乱

### ISSUE THREAD

**Issue by fcwys** [alist-org/alist#3804]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.2

### Driver used / 使用的存储驱动

阿里云盘 Open

### Describe the bug / 问题描述

网页播放器点击网页全屏版式错乱，当点击网页全屏时会往右下角延申

### Reproduction / 复现链接

![微信截图_20230311141730](https://user-images.githubusercontent.com/28641034/224468772-19727e43-aa1a-4709-95ab-7542f6851e72.png)
![微信截图_20230311141801](https://user-images.githubusercontent.com/28641034/224468782-bca3d531-f82c-40df-a26c-459cb66eab61.png)

### Logs / 日志

![微信截图_20230311141801](https://user-images.githubusercontent.com/28641034/224468790-022feba3-1880-4877-85ec-6e0c7f6aa969.png)

**Comment by Hipponensis** [comment]
更新新版本，同样遇到了这个问题，投屏做不到满屏显示了，退回老版本token又无法刷新
