### ISSUE TITLE
权限控制对下载链接不起作用

### ISSUE THREAD

**Issue by linkq** [alist-org/alist#3807]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.13.2

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

不需要进行权限校验，只要知道下载链接，就能直接下载文件。
经过测试，阿里云open、百度云、OneDrive都存在该问题。

### Reproduction / 复现链接

https://alist.linkq.fun/d/%E6%B5%8B%E8%AF%95/test.md

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/global.html#sign-all

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/global.html#sign-all
