### ISSUE TITLE
win版 V3  使用alist server和alist start不同命令启动AList 各自会生成独立的配置及数据文件导致alist start启动时输入初始密码一直显示密码不正确

### ISSUE THREAD

**Issue by UareoVo** [alist-org/alist#3808]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.2

### Driver used / 使用的存储驱动

本地存储  天翼云盘  移动云盘（这部分不重要）

### Describe the bug / 问题描述

**操作系统** ：win11
**软件版本**：v3.13.2
![image](https://user-images.githubusercontent.com/102874761/224471320-173da52b-7a4c-4ae9-b390-f2fd880998ee.png)
**问题描述**：
①使用alist server命令启动AList时生成的配置及数据文件存放在 C:\Users\用户名\data 目录下 
②使用alist start 命令启动AList时会生成新的配置及数据文件并存放在.\AList安装目录\data  目录下
③在方式②下使用alist admin 获取的账号密码是 C:\Users\用户名\data\data.db 中存储的账号密码而不是.\AList安装目录\data\data.db 中的账号密码 ，但是登录时验证的是.\AList安装目录\data\data.db 中的账号密码 所以会一直提示密码不正确

### Reproduction / 复现链接

**1.卸载并重装alist**
![image](https://user-images.githubusercontent.com/102874761/224473002-405c0b1d-2201-408a-a3f6-2d61170032b9.png)
**2. 此时两个目录都没有配置及数据文件**
![image](https://user-images.githubusercontent.com/102874761/224473429-ba647233-642c-442a-a8fc-adfb68ead69f.png)
**3. 使用alist server 启动AList**
![image](https://user-images.githubusercontent.com/102874761/224473499-1a4be547-e896-4b24-9383-b5356571a196.png)
**4.此时 C:\Users\用户名\data 目录下生成了配置及数据文件 安装目录依旧为空**
![image](https://user-images.githubusercontent.com/102874761/224473575-380b7f3f-7d2b-4e80-a7b5-31cac907a4e0.png)
**5.使用alist admin获取初始账号密码并登录，登录成功**
![image](https://user-images.githubusercontent.com/102874761/224473771-86ef7afd-45ae-4a6a-a708-fcc592c9b0ee.png)
![image](https://user-images.githubusercontent.com/102874761/224473852-30f7f12c-37f3-4306-b1be-724b654def33.png)
**6.使用SQLiteStudio看下 C:\Users\用户名\data\data.db中的账号密码，和命令获取的一致（到目前为止没有任何问题）**
![image](https://user-images.githubusercontent.com/102874761/224473994-aa26c2b5-240d-4b92-89c2-00f6c85ce0e7.png)
**7.Ctrl+C终止服务，使用alist start启动AList**
![image](https://user-images.githubusercontent.com/102874761/224474113-fef3c315-53b5-47a6-b448-955edbcc869e.png)
**8.此时 C:\Users\用户名\data 目录没有变化，但是在安装目录生成了一个daemon和一个data文件夹，而data目录中有着新的配置和数据文件**
![image](https://user-images.githubusercontent.com/102874761/224474220-095a4115-1393-4beb-95cb-8e2741ef3638.png)
![image](https://user-images.githubusercontent.com/102874761/224474374-b40f1b56-3ca1-4cc0-a141-5c40cc88b0b2.png)
**9.使用alist admin获取用户名和密码，得到的和步骤5中相同的账号密码**
![image](https://user-images.githubusercontent.com/102874761/224474563-1792ca94-1f8f-4a14-a087-c79521cf72f6.png)
**10.此时用获取的账号密码登录 AList 提示密码不正确**
![image](https://user-images.githubusercontent.com/102874761/224474643-34868478-9e89-46d3-a3e2-82834f406bfe.png)
**11.使用SQLiteStudio查看.\AList安装目录\data\data.db中账号密码，发现里面是新的账号和密码。且与获取到的不一致**
![image](https://user-images.githubusercontent.com/102874761/224474802-9234de89-8186-4ac9-9067-54a933218c6f.png)
**12.使用步骤11中SQLiteStudio查看到的账号密码登录AList,登录成功**
![image](https://user-images.githubusercontent.com/102874761/224474920-03ca5174-b083-42ee-8c53-c18ab009a490.png)
**13.综上所述.：alist server 和alist admin 两个命令下读取的是C:\Users\用户名\data\data.db中的账号密码，alist start 命令下登录验证的是.\AList安装目录\data\data.db中账号密码，命令获取的账号密码和验证的账号密码不一致导致登录报错**

### Logs / 日志

**1.C:\Users\用户名\data\log\log.log**
[33mWARN[0m[2023-03-11 16:18:54] not enable search                            
[GIN] 2023/03/11 - 16:25:47 | 200 |       632.2µs |             ::1 | POST     "/api/auth/login"
[GIN] 2023/03/11 - 16:25:47 | 200 |       327.4µs |             ::1 | GET      "/api/me"
[31mERRO[0m[2023-03-11 16:25:47] failed list /: please add a storage first.
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/source/internal/op/path.go:19
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:18
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:17
github.com/alist-org/alist/v3/server/handles.FsGet
	/source/server/handles/fsread.go:291
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1995
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
failed get storage 
[GIN] 2023/03/11 - 16:25:47 | 200 |       1.452ms |             ::1 | POST     "/api/fs/get"
[31mERRO[0m[2023-03-11 16:25:47] failed list /: please add a storage first.
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/source/internal/op/path.go:19
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:18
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:17
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:80
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1995
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
failed get storage 
[GIN] 2023/03/11 - 16:25:47 | 200 |       768.3µs |             ::1 | POST     "/api/fs/list"
[33mWARN[0m[2023-03-11 16:40:04] not enable search                            

**2..\AList安装目录\data\log\log.log**
[33mWARN[0m[2023-03-11 16:31:51] not enable search                            
[GIN] 2023/03/11 - 16:33:33 | 200 |         287µs |             ::1 | GET      "/"
[GIN] 2023/03/11 - 16:33:33 | 200 |       111.7µs |             ::1 | GET      "/api/public/settings"
[GIN] 2023/03/11 - 16:33:33 | 200 |       863.8µs |             ::1 | GET      "/api/me"
[GIN] 2023/03/11 - 16:43:44 | 200 |       624.6µs |             ::1 | POST     "/api/auth/login"
[GIN] 2023/03/11 - 16:43:56 | 200 |            0s |             ::1 | POST     "/api/auth/login"
[GIN] 2023/03/11 - 16:43:56 | 200 |            0s |             ::1 | POST     "/api/auth/login"
[GIN] 2023/03/11 - 16:43:57 | 200 |            0s |             ::1 | POST     "/api/auth/login"
[GIN] 2023/03/11 - 16:49:51 | 200 |       509.2µs |             ::1 | POST     "/api/auth/login"
[GIN] 2023/03/11 - 16:49:51 | 200 |       474.3µs |             ::1 | GET      "/api/me"
[31mERRO[0m[2023-03-11 16:49:51] failed list /: please add a storage first.
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/source/internal/op/path.go:19
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:18
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:17
github.com/alist-org/alist/v3/server/handles.FsGet
	/source/server/handles/fsread.go:291
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1995
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
failed get storage 
[GIN] 2023/03/11 - 16:49:51 | 200 |       694.9µs |             ::1 | POST     "/api/fs/get"
[31mERRO[0m[2023-03-11 16:49:51] failed list /: please add a storage first.
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/source/internal/op/path.go:19
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:18
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:17
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:80
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1995
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
failed get storage 
[GIN] 2023/03/11 - 16:49:51 | 200 |       291.3µs |             ::1 | POST     "/api/fs/list"

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/224480016-d3fb03dc-6a36-4525-9b26-a46c852b6178.png)
