### ISSUE TITLE
挂载百度云报错

### ISSUE THREAD

**Issue by sdw81219** [alist-org/alist#3815]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.2

### Driver used / 使用的存储驱动

百度云

### Describe the bug / 问题描述

添加储存后，点进去给出提示：failed get objs: failed to list objs: errno: 2, refer to https://pan.baidu.com/union/doc/

### Reproduction / 复现链接

http://127.0.0.1:5244/%E7%99%BE%E5%BA%A6%E4%BA%91

**Comment by anwen-anyi** [comment]
1. 检查必选参数是否都已填写；
  2. 检查每个参数的值是否正确。
自行排查自己的配置是否正确，或者把你添加挂载的配置截图发出来看看

**Comment by sdw81219** [comment]
成功修复了 多谢

**Comment by zhengshengxi** [comment]
你好，怎么解决的
