### ISSUE TITLE
新增vercel或者railway一键部署

### ISSUE THREAD

**Issue by fangyuan99** [alist-org/alist#3816]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

新增`vercel`或者`railway`**一键部署**,可以~~白嫖~~免费部署在云端，比较方便。

## 文档
- [Introduction to Vercel | Vercel Docs](https://vercel.com/)
- [Railway Docs](https://docs.railway.app/)

**Comment by Xhofe** [comment]
vercel: 只支持serverless，故不支持；
railway：https://github.com/alist-org/alist-railway/issues/7
