### ISSUE TITLE
One-click Script of mac m1

### ISSUE THREAD

**Issue by Oscaner** [alist-org/alist#3819]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

latest

### Driver used / 使用的存储驱动

None

### Describe the bug / 问题描述

提示 `出错了，一键安装目前仅支持 x86_64 和 arm64 平台`

### Reproduction / 复现链接

使用 mac m1 pro 电脑

### Logs / 日志

<img width="519" alt="image" src="https://user-images.githubusercontent.com/26829325/224528325-39dce889-fcc3-4ce9-adbb-522e62e5e7aa.png">

**Comment by Xhofe** [comment]
# **Only for Linux-x86_64/arm64 platform.**
