### ISSUE TITLE
Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by cjj619** [alist-org/alist#3821]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v2.0

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

上传文件报错Cannot read properties of undefined (reading 'status')

### Reproduction / 复现链接

jiguang.zj.cn:5244

### Logs / 日志

Cannot read properties of undefined (reading 'status')

**Comment by Mooling0602** [comment]
为啥无效啊

**Comment by CYscared** [comment]
我也碰到这个bug，文件上传报错Cannot read properties of undefined (reading 'status')

**Comment by Cathgao** [comment]
传一半就报这个错误白传了，然后看issue直接就无效？
