### ISSUE TITLE
webdav / sharepoint 挂载问题

### ISSUE THREAD

**Issue by Aigio1064** [alist-org/alist#3824]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.2

### Driver used / 使用的存储驱动

webdav / sharepoint

### Describe the bug / 问题描述

可以显示文件列表，但是无法显示内容以及下载文件，  
我不知道是什么原因导致的，它能给到我的只有一段错误：
```json
{"code":500,"message":"Get "https://nenueducn-my.sharepoint.com/personal/huyf345_nenu_edu_cn/Documents/share/readme.md\": http2: invalid Connection request header: ["upgrade"]","data":null}
```
我尝试获取了官方的下载链接，它给的是：
```
https://nenueducn-my.sharepoint.com/personal/huyf345_nenu_edu_cn/_layouts/15/download.aspx?SourceUrl=/personal/huyf345_nenu_edu_cn/Documents/share/readme.md
```

### Reproduction / 复现链接

<https://alist.aigio1064.top/>

### Logs / 日志

[log.log](https://github.com/alist-org/alist/files/10950659/log.log)
![image](https://user-images.githubusercontent.com/97342833/224540967-dacc2b3b-d1e0-43f1-856b-5a89eef1beee.png)

**Comment by Xhofe** [comment]
这通常由不正确的反向代理所致，你可以检查原始链接是否存在此错误。

**Comment by Aigio1064** [comment]
> 这通常由不正确的反向代理所致，你可以检查原始链接是否存在此错误。

点击链接可以访问下载，但是我不知道配置哪里有错，
教程里只是一笔带过，没有任何关于这方面的问题  

我的存储配置：
![image](https://user-images.githubusercontent.com/97342833/224542165-fe4a60cf-4e39-46d1-86c4-a332db3a4da8.png)

**Comment by Xhofe** [comment]
反向代理，反向代理，反向代理。

**Comment by Aigio1064** [comment]
好吧

**Comment by Aigio1064** [comment]
> 反向代理，反向代理，反向代理。

试了，问题依旧...

**Comment by Aigio1064** [comment]
我设置site_url配置项，无论是使用最后访问的https://alist.aigio1064.top/，还是内网的http://0.0.0.0:5244/，都没有任何效果...

**Comment by Xhofe** [comment]
你直接访问5244端口那个链接。

**Comment by Aigio1064** [comment]
是只要 0.0.0.0:5244就行了吗？

**Comment by Xhofe** [comment]
你打开5244端口 然后直接访问你的ip:5244 链接

看看有没有问题

**Comment by Aigio1064** [comment]
本地的正常，就远端的美国服务器不行...

**Comment by Aigio1064** [comment]
🤣

**Comment by Xhofe** [comment]
所以说这是你反向代理的问题，这不符号issue的的第三条：
`I'm sure it's due to alist and not something else(such as Dependencies or Operational).`
这并不是alist的问题，而是nginx的问题。

**Comment by Aigio1064** [comment]
好吧，麻烦你了，我是真的不知道问题出在哪，本地的alist挂载同样的配置在修改前一直显示403，也就没再试了

**Comment by Aigio1064** [comment]
大无语事件发生....当我把alist的配置文件恢复原样，然后新建一个站点再反代，它就能用了。。。  
![image](https://user-images.githubusercontent.com/97342833/224552402-7b9ebf9a-67b2-424b-800f-0a72b18dc5ca.png)
难道nginx还分proxy_pass的？
