### ISSUE TITLE
对象存储文件夹获取bug

### ISSUE THREAD

**Issue by Kuingsmile** [alist-org/alist#3828]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.2

### Driver used / 使用的存储驱动

对象存储

### Describe the bug / 问题描述

使用对象存储挂载cloudflare R2，当把挂载路径的最后一级目录设置为和存储桶相同的名字时，点击文件夹，会循环进入点击的文件夹，当最后一级目录改成其它名字时正常

### Reproduction / 复现链接

随意对象存储挂载可稳定复现

### Logs / 日志

我挂载的存储桶名为obsidian

如图，挂载路径设置为`/R2/obs`时，文件夹正常
![image](https://user-images.githubusercontent.com/96409857/224547841-731de5d7-5b27-48b9-9e0f-e8fa7a7ff0cc.png)
设置为`/R2/obsidian`时出现异常
![image](https://user-images.githubusercontent.com/96409857/224547845-477ce22d-8854-4d49-91b7-541ac38996a4.png)

**Comment by anwen-anyi** [comment]
这个之前出现过一次 但是修过我记得  但是没完全修好QAQ

**Comment by Kuingsmile** [comment]
试了下好像是升级前没有填根目录导致的 删除了新添加的又好了 先关了
