### ISSUE TITLE
为Aria2赋予$temp_dir/aria2的访问权限

### ISSUE THREAD

**Issue by ttxs25830** [alist-org/alist#3833]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前，当Alist创建aria2的临时目录（`$temp_dir/aria2`）时，目录会被赋予`755 *alist user*:*alist group*`的权限，而当服务器管理员为aria2使用较严格的安全设置时，这会导致aria2没有权限访问该目录，从而导致下载失败。

### Suggested solution / 实现思路

将目录的权限更改为`775`，如此服务器管理员可以将aria2的用户加入alist所属组中以允许其访问该目录。

**Comment by QYQSDTC** [comment]
我用[Aria2完美配置](https://github.com/P3TERX/aria2.conf)Docker部署的Aria2在用Alist下载的时候就是这样，无法创建tmp文件夹

**Comment by bilibili2077** [comment]
Docker部署的Aria2和Alist的下载可以，但是无法上传，无法打开tmp文件夹，导致无法上传，不知道什么问题，

**Comment by wangzhehan84** [comment]
> 我用[Aria2完美配置](https://github.com/P3TERX/aria2.conf)Docker部署的Aria2在用Alist下载的时候就是这样，无法创建tmp文件夹
我也和你用的一样的配置 ，先替换一下下载路径 。
`    -v $PWD/aria2-downloads:/downloads \ 
`
替换成
`   -v /etc/alist/temp/aria2:/opt/alist/data/temp/aria2 \
` 
再把本地路径/etc/alist/temp/ 新建aria2文件夹并把权限设为777

**Comment by QYQSDTC** [comment]
> > 我用[Aria2完美配置](https://github.com/P3TERX/aria2.conf)Docker部署的Aria2在用Alist下载的时候就是这样，无法创建tmp文件夹
> 
> 我也和你用的一样的配置 ，把文件夹权限设置正确，还是能正常运行的。 先替换一下下载路径 。 ` -v $PWD/aria2-downloads:/downloads \ ` 替换成 ` -v /etc/alist/temp/aria2:/opt/alist/data/temp/aria2 \` 再把本地路径/etc/alist/temp/ 新建aria2文件夹并把权限设为777 突然发现了作者也考虑到更改临时文件夹的情况，也可以把临时文件夹设置$PWD/aria2-downloads，应该也可以运行吧 https://alist.nn.ci/zh/config/configuration.html#temp-dir

我两种都试了都是failed to make the directory; permission denied，但是qbit又是好的
![CleanShot-Hu6t6aaA](https://user-images.githubusercontent.com/15608306/225076760-e7aab20a-a6fd-46e0-8f63-f51581291185.png)
![CleanShot-xHKiAfM1](https://user-images.githubusercontent.com/15608306/225077036-433a631e-eec6-4f1e-93b1-d222e6bc7a66.png)

**Comment by ifangyong** [comment]
我在群晖docker下把pud和gud都设置成0解决了，用户和用户组都为root
