### ISSUE TITLE
支持discord作为存储

### ISSUE THREAD

**Issue by lonelil** [alist-org/alist#3836]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

您可以通过将每个文件拆分为8MB，将discord webhook用作“无限”文件存储。

### Additional context / 附件

https://github.com/forscht/ddrive

**Comment by anwen-anyi** [comment]
啊这...8M比兰奏还狠 哈哈
