### ISSUE TITLE
Teambition网盘能挂载，但是不能上传文件，出现`参数有误`

### ISSUE THREAD

**Issue by royccg** [alist-org/alist#3854]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.1

### Driver used / 使用的存储驱动

Teambition网盘

### Describe the bug / 问题描述

填写了 `Cookie`、`项目ID`、`根文件夹ID`之后，能正常挂载上。
+ 能播放文佳夹内的媒体
+ 能下载图片

但是不能上传文件，会显示 参数有误。
<img width="281" alt="Snipaste_2023-03-15_11-26-08" src="https://user-images.githubusercontent.com/44716144/225198852-f4eb620e-11ff-42da-a5bd-c34ef7fa6d80.png">

### Reproduction / 复现链接

<img width="281" alt="Snipaste_2023-03-15_11-26-08" src="https://user-images.githubusercontent.com/44716144/225198992-69c029ee-9a90-4527-a833-b60307e01109.png">

**Comment by anwen-anyi** [comment]
日志补充    暂时 v3.13.1 到目前构建测试版都这样（测试`alias`时也遇到了）
```log
[GIN] 2023/03/15 - 12:25:50 | 200 |    133.0076ms |       127.0.0.1 | PUT      "/api/fs/put"
[31mERRO[0m[2023-03-15 12:25:50] error [参数有误
github.com/alist-org/alist/v3/internal/op.Put
	/source/internal/op/fs.go:569
github.com/alist-org/alist/v3/internal/fs.putAsTask.func1
	/source/internal/fs/put.go:39
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/source/pkg/task/task.go:75
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/source/pkg/task/manager.go:33
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598] while run task [upload alist-windows-amd64-1.exe to [/1Teambition](/Video)] 
```
