### ISSUE TITLE
补充日语和繁体中文

### ISSUE THREAD

**Issue by StarGolx** [alist-org/alist#3857]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

补充**日语**和**繁体中文**：日语显示的就是英语了；繁体中文有一些没翻译
版本3.13.2

### Suggested solution / 实现思路

补充完整日语和繁体中文的翻译

### Additional context / 附件

日语：
![image](https://user-images.githubusercontent.com/62445523/225372486-4d4691fb-028a-4f5e-a10f-8519711e7d5f.png)

繁体中文：
![image](https://user-images.githubusercontent.com/62445523/225373738-650d0221-95bb-40f7-a5bb-0eca90471e57.png)
![image](https://user-images.githubusercontent.com/62445523/225373671-1babccf4-1abf-4926-8c95-6fcaa8dc5977.png)

**Comment by mengguyi** [comment]
日语其实我很早就给翻译了
只是作者没给合并
不过现在日语应该不全

**Comment by anwen-anyi** [comment]
https://crowdin.com/project/alist

**Comment by Xhofe** [comment]
欢迎有能力的朋友添加翻译
https://crwd.in/alist

**Comment by mengguyi** [comment]
![image](https://user-images.githubusercontent.com/73788063/225808323-90c254d5-3bff-444b-8e6f-0019ecf35e46.png)
日语翻译大部分已经完成，请作者查看
如果没问题记得批准

**Comment by uu-xixi** [comment]
> ![image](https://user-images.githubusercontent.com/73788063/225808323-90c254d5-3bff-444b-8e6f-0019ecf35e46.png) 日语翻译大部分已经完成，请作者查看 如果没问题记得批准
为了引起不必要争议和麻烦，尊重一个中国原则。还是把繁体字上中华民国国旗去掉吧

**Comment by uu-xixi** [comment]
> ![图像](https://user-images.githubusercontent.com/73788063/225808323-90c254d5-3bff-444b-8e6f-0019ecf35e46.png) 日语翻译大部分已经完成，请作者查看 如果没问题记得批准

为了引起不必要争议和麻烦，尊重一个中国原则。还是把繁体字上中华民国国旗去掉吧
