### ISSUE TITLE
增加DLNA(UPNP)媒体服务

### ISSUE THREAD

**Issue by kimycai** [alist-org/alist#3861]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

可否增加DLNA（UPNP)媒体服务，并支持wav和flac无损音频编码传输

**Comment by TomIsFat** [comment]
这功能在哪里？没见到

**Comment by SheltonZhu** [comment]
https://github.com/alexballas/go2tv
