### ISSUE TITLE
挂载夸克网盘失败

### ISSUE THREAD

**Issue by KafCoppelia** [alist-org/alist#3869]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

挂载夸克网盘多次失败，确认Cookie以及文件夹ID获取无误

### Reproduction / 复现链接

参照文档挂载夸克网盘的方式

### Logs / 日志

报错：Failed init storage: Get "https://drive.quark.cn/1/clouddrive/config?fr=pc&pr=ucpro": dial tcp: lookup drive.quark.cn: Try again

**Comment by wizll7865** [comment]
你解决了么

**Comment by dfvips** [comment]
解决了吗？我也遇到了。

**Comment by KafCoppelia** [comment]
是不是最近又不行了？是不是夸克的问题？
