### ISSUE TITLE
元信息隐藏问题，隐藏当前目录OK，但还是可以访问隐藏目录下的子文件夹下的内容。

### ISSUE THREAD

**Issue by wgf520** [alist-org/alist#3878]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

N/A

### Describe the bug / 问题描述

元信息隐藏问题，隐藏当前目录OK，应用到子文件夹有勾选，但还是可以访问隐藏目录下的子文件夹下的内容。

### Reproduction / 复现链接

N/A

### Logs / 日志

![image](https://user-images.githubusercontent.com/128127036/226075289-dd0e583a-db6b-4677-8914-5e2cb07b6ac7.png)
![image](https://user-images.githubusercontent.com/128127036/226075351-da09d516-3a48-4ef3-b21c-7c02481409d5.png)
![image](https://user-images.githubusercontent.com/128127036/226075382-008f7a13-d9ea-4c2c-a122-ccba298d1928.png)

**Comment by wgf520** [comment]
好像上个版本反馈过，没有修复吗？[#3784](https://github.com/alist-org/alist/issues/3784)

**Comment by anwen-anyi** [comment]
我记得上次https://github.com/alist-org/alist/issues/3784 commit之后修好了不过现在确实又双叒叕出现了

**Comment by anwen-anyi** [comment]
好吧，上次的是修复的是另一个.....是写根目录里面的二级文件夹
这次的是根目录QAQ...........

**Comment by Xhofe** [comment]
目前隐藏只会在名称匹配时生效。
