### ISSUE TITLE
索引不可用

### ISSUE THREAD

**Issue by xiangchu95** [alist-org/alist#3880]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

no

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/110237853/226085236-e3f72638-2213-43ab-942d-ff66419b8bfe.png)

### Reproduction / 复现链接

无

**Comment by anwen-anyi** [comment]
仔细看文档好吧~
![image](https://user-images.githubusercontent.com/56105412/226085887-8731ed80-19ce-40be-88fc-c3916100154e.png)
