### ISSUE TITLE
希望增加复制任务的重试功能

### ISSUE THREAD

**Issue by liooge** [alist-org/alist#3884]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用pikpak复制大批量文件到本地时，经常会因为网络原因失败。
希望增加一种重试机制。

**Comment by mengguyi** [comment]
目前已经有重试功能了但是是针对每个任务的，当复制大量文件（夹）时可能会产生大量失败的任务，一个一个点重试有点费劲。希望加入一个“全部重试”按钮来解决该问题
