### ISSUE TITLE
苹果设备查看epub格式显示object not found

### ISSUE THREAD

**Issue by StarGolx** [alist-org/alist#3892]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.14.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

苹果设备查看epub格式显示object not found，在安卓和Windows上可正常显示。

### Reproduction / 复现链接

https://pan.zer0ne1.repl.co/小説%20すずめの戸締まり%20(角川文庫).epub
用户名和密码均为tmp

### Logs / 日志

![da3935b28c07465205e10278da94365](https://user-images.githubusercontent.com/62445523/226173981-f4955a18-e945-49b8-9f7c-13a636401558.jpg)

**Comment by StarGolx** [comment]
上个版本我装的是1.13.2也是一样的

**Comment by Panici4** [comment]
应该是safari url encode不一样的原因。

**Comment by StarGolx** [comment]
我试了其它浏览器，也是不行的

**Comment by Panici4** [comment]
> 我试了其它浏览器，也是不行的

我mac在chrome是可以的，不要直接打开链接，从文件列表点进去。

**Comment by StarGolx** [comment]
> @Panici4 我mac在chrome是可以的，不要直接打开链接，从文件列表点进去。

我就是在文件列表里点进去的

**Comment by StarGolx** [comment]
> 我就是在文件列表里点进去的
> 我试试看chrome

还是不行

**Comment by Panici4** [comment]
> > 我就是在文件列表里点进去的
> > 我试试看chrome
> 
> 还是不行

<img width="752" alt="image" src="https://user-images.githubusercontent.com/35474709/226179010-8e7acba5-8d01-4708-a912-d76993d96668.png">

**Comment by Panici4** [comment]
我是可以的，看了下safari请求的path是不对，导致文件名匹配不上。去掉文件名里面的   ゙ 这个可能就可以了

**Comment by StarGolx** [comment]
> @Panici4 我是可以的，看了下safari请求的path是不对，导致文件名匹配不上。去掉文件名里面的 ゙ 这个可能就可以了

改下文件名就可以了，感谢
