### ISSUE TITLE
我希望为Alist贡献新的onedrive驱动

### ISSUE THREAD

**Issue by linshuboy** [alist-org/alist#3901]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

你好,我希望为Alist贡献新的onedrive驱动,虽然我不是go开发者,根据原有的onedrive修改一个版本的能力还是有的,但是因为这个原因,我对于一开始如何在本地跑起来代码有些疑问,希望能得到你的帮助
我做过以下尝试,通过golang初始化了本地代码,配置了goproxy,也安装了gcc,然后运行 go run main.go.提示
![image](https://user-images.githubusercontent.com/20389206/226257521-1971b206-a10f-4c82-a5ba-b46d83f2c7fe.png)
但是并没有这个进程.所以需要作者的帮助.

**Comment by anwen-anyi** [comment]
这不是启动吗了？ 如果你想要看带日志的那种可以使用  `server` 参数来当做启动

**Comment by linshuboy** [comment]
@anwen-anyi 是的,我又换了server方式,已经启动了,现在遇到了一个新的问题,我怎么获取admin用户呢,我运行go run main.go admin 获取的用户不能登录,感觉每次运行go run main.go 都会产生一个新的程序,并且互不干扰的感觉.

**Comment by anwen-anyi** [comment]
没问题啊
```go
PS C:\Users\安稳\Desktop\git\Alist-3.1.0\alist> go run .\main.go admin 
INFO[2023-03-20 14:10:18] reading config file: data\config.json        
INFO[2023-03-20 14:10:18] load config from env with prefix: ALIST_     
INFO[2023-03-20 14:10:18] init logrus...
INFO[2023-03-20 14:10:18] admin user's info: 
username: admin
password: w30OHV7r
```
