### ISSUE TITLE
关于游客访问上传

### ISSUE THREAD

**Issue by Oliyrs** [alist-org/alist#3907]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

请问能不能把用户权限设置地再细一点，游客只能在哪个文件夹创建上传及其他任务。

**Comment by Xhofe** [comment]
元信息本身就是按文件夹设置的。

**Comment by Oliyrs** [comment]
好的，没仔细看，谢谢

**Comment by bootli** [comment]
可以设置限制访客上传大小就好了
