### ISSUE TITLE
能否添加 挂载Dropbox呢?

### ISSUE THREAD

**Issue by crazy0x70** [alist-org/alist#3913]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否添加挂载Dropbox功能呢?目前兼容了多款热门网盘,但是像Dropbox、box尚未支持,未来的版本中是否会加上呢?

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/issues/3873
