### ISSUE TITLE
希望能增加自定义OAuth单点登录

### ISSUE THREAD

**Issue by WuxidiKang** [alist-org/alist#3914]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能增加自定义OAuth单点登录

**Comment by anwen-anyi** [comment]
例如你要对接那个厂商OA单点登录系统

**Comment by Xhofe** [comment]
OAuth 只是一种协议，各家实现都有区别 只能单独实现。另：alist从来没有过所谓的通用OAuth。

**Comment by anwen-anyi** [comment]
> > 比如你要对接那个厂家OA单点登录系统（就是好奇）
> 
> 有留意到群晖7.2版本SSO支持 OAuth，希望能支持通用的OAuth吧，以前老版本是有的

你指的是 V2 版本末期的那个SSO吗？
这个么？https://alist-doc.nn.ci/docs/setting/casdoor

**Comment by manduted** [comment]
附议！！！或者能LDAP验证也行。这样一个账号就可以打通。Jellyfin.群晖.alist那些。。nextcloud可以但是那速度简直了。稀碎

**Comment by xzzpig** [comment]
> OAuth 只是一种协议，各家实现都有区别 最好的做法还是单独实现。要兼容所有需要自己写很多配置。 另：alist从来没有过所谓的通用OAuth。

能否考虑支持 OpenID Connect (OIDC) 协议？OIDC是基于OAuth协议的，而且许多OAuth协议提供商已经支持OIDC。鉴于alist现在已经支持了OAuth协议，额外支持OIDC协议应该不会太困难。

**Comment by manduted** [comment]
emmm。。好像没有反应。要是能支持。就不用有authentik keycloak之类的还要去挂个微软AD那些咯

**Comment by gucong3000** [comment]
在群辉中试用了一小段日子了，这几天发现 AList 完全可以替代群晖官方的`WebDAV Server`，但代价是账号系统与群晖不通用，如果能支持群晖内已经创建的账号那就太方便了。

通过 Alist 一个服务，电脑上映射一个网络驱动器，就能同时访问自己的N多个网盘账号和群晖，真的是太方便了。

**Comment by kaaass** [comment]
同希望增加 OpenID Connect (OIDC) ！现在常见的开源 SSO 实现都是支持 OIDC 的，如 authelia、authentik、keycloak。而且其中部分实现还支持多种 2FA 方式，比如 WebAuthn。

**Comment by hsluoyz** [comment]
现在alist V3版本也支持Casdoor单点登录了，支持OIDC, OAuth 2.0, SAML, CAS, LDAP, WebAuthn, 2FA等等

alist V3文档：

- https://alist.nn.ci/zh/guide/advanced/sso.html
- https://anwen-anyi.github.io/index/09-ssologin.html

alist V2文档：

- https://alist-doc.nn.ci/docs/setting/casdoor

**Comment by kaaass** [comment]
通过 Casdoor 接入 OIDC 确实理论上可行，但是这种接入方式下，

1. 需要再为 AList 单独起一个 Casdoor。否则文档中也提到了，Casdoor 本身是收费的。此外如果 IdP 在内网之类的情况也需要自建。
2. 登录过程需要两次甚至更多跳转。

如果能原生支持 OIDC 的话应该能改善不少可用性。

**Comment by hsluoyz** [comment]
@kaaass 

> 需要再为 AList 单独起一个 Casdoor。此外如果 IdP 在内网之类的情况也需要自建。

你前面一个回复里提到的`现在常见的开源 SSO 实现都是支持 OIDC 的，如 authelia、authentik、keycloak`，这些都需要单独起一个服务，都需要自建，与Casdoor没什么分别。

一般上SSO的，都不止alist一个应用。所以需要一个集中式的SSO服务，各个应用都可以集成到里面去。

> 登录过程需要两次甚至更多跳转。

用户如果跳到SSO后，直接密码登录，那就只有一次跳转。如果在SSO里再跳到微信去登录，那就两次了。也就是说跳转几次取决于你采用什么方式去登录。所有的SSO都是这样工作的，这没什么问题。

> Casdoor 本身是收费的。

Casdoor是基于Apache 2.0协议下完全开源免费的：https://github.com/casdoor/casdoor ，Apache 2.0是目前商用最友好的开源协议之一。收费的是云服务托管，绝大部分个人用户是不需要使用的。

> 如果能原生支持 OIDC 的话应该能改善不少可用性。

如果说只支持一个OIDC还好，其他的功能，如OAuth 2.0, SAML, CAS, LDAP, WebAuthn, 2FA、邮箱验证码、短信验证码，都自己开发难度就太大了。例如，仅仅是OAuth 2.0，各家的实现都不太一样的。如果全部在alist里都实现了，相当于alist里面自己开发了一整套单点登录，这个是没有必要的。

**Comment by kaaass** [comment]
> 这些都需要单独起一个服务，都需要自建，与Casdoor没什么分别

我这里指的是为 AList 适配 OIDC。以我自己为例，我目前已经有 Authelia 并接入了一系列服务。Authelia 支持 OIDC，但为了接入 AList，我需要自建一个 Casdoor 接入 Authelia，然后再在 AList 接入 Casdoor。我认为这个是完全没有必要的。

> 也就是说跳转几次取决于你采用什么方式去登录。所有的SSO都是这样工作的，这没什么问题。

此处同上。登录时需要 AList 跳 Casdoor 跳 Authelia，过程中会看到三个登录框。如果原生支持 OIDC 则可以简化为正常的一跳。

> Casdoor 本身是收费的。

替我挽一下尊，这里指的是 Casdoor 官方的托管，也就是不自建 Casdoor 的情况。

> 如果说只支持一个OIDC还好，其他的功能，如OAuth 2.0, SAML, CAS, LDAP, WebAuthn, 2FA、邮箱验证码、短信验证码，都自己开发难度就太大了。

除却 OAuth 2.0，其余功能应该是交给 SSO 实现，AList 并不需要操心。如果指的是我之前提到的 WebAuthn 的话，我的意思是 Authelia 等已经支持了 WebAuthn，只需要支持 OIDC 接入，AList 就自动有这些功能了。

**Comment by thomasdba** [comment]
建议支持oidc

**Comment by manduted** [comment]
> @hsluoyz
> 
> > 这些都需要单独起一个服务，都需要自建，与Casdoor没什么分别
> 
> 我这里指的是为 AList 适配 OIDC。以我自己为例，我目前已经有 Authelia 并接入了一系列服务。Authelia 支持 OIDC，但为了接入 AList，我需要自建一个 Casdoor 接入 Authelia，然后再在 AList 接入 Casdoor。我认为这个是完全没有必要的。
> 
> > 也就是说跳转几次取决于你采用什么方式去登录。所有的SSO都是这样工作的，这没什么问题。
> 
> 此处同上。登录时需要 AList 跳 Casdoor 跳 Authelia，过程中会看到三个登录框。如果原生支持 OIDC 则可以简化为正常的一跳。
> 
> > Casdoor 本身是收费的。
> 
> 替我挽一下尊，这里指的是 Casdoor 官方的托管，也就是不自建 Casdoor 的情况。
> 
> > 如果说只支持一个OIDC还好，其他的功能，如OAuth 2.0, SAML, CAS, LDAP, WebAuthn, 2FA、邮箱验证码、短信验证码，都自己开发难度就太大了。
> 
> 除却 OAuth 2.0，其余功能应该是交给 SSO 实现，AList 并不需要操心。如果指的是我之前提到的 WebAuthn 的话，我的意思是 Authelia 等已经支持了 WebAuthn，只需要支持 OIDC 接入，AList 就自动有这些功能了。而至于 OAuth 2.0，据我观察大部分开源的 SSO 都支持了 OIDC，而至于各大社交网站的登录则确实可以交给 Casdoor。

+1，我用的Authentik。所有单点登录都经过它。像其他的Authelia、Keycloak，本来就支持OIDC那些。结果还要新部署个Casdoor.。先跳Casdoor再跳Authentik....我现在就是直接Fowardauth了，，打开Alist先Authentik认证。但是坏处就是要打开游客访问。。而且。Casdoor不算好用。

**Comment by ForsakenRei** [comment]
> > @hsluoyz
> > > 这些都需要单独起一个服务，都需要自建，与Casdoor没什么分别
> > 
> > 
> > 我这里指的是为 AList 适配 OIDC。以我自己为例，我目前已经有 Authelia 并接入了一系列服务。Authelia 支持 OIDC，但为了接入 AList，我需要自建一个 Casdoor 接入 Authelia，然后再在 AList 接入 Casdoor。我认为这个是完全没有必要的。
> > > 也就是说跳转几次取决于你采用什么方式去登录。所有的SSO都是这样工作的，这没什么问题。
> > 
> > 
> > 此处同上。登录时需要 AList 跳 Casdoor 跳 Authelia，过程中会看到三个登录框。如果原生支持 OIDC 则可以简化为正常的一跳。
> > > Casdoor 本身是收费的。
> > 
> > 
> > 替我挽一下尊，这里指的是 Casdoor 官方的托管，也就是不自建 Casdoor 的情况。
> > > 如果说只支持一个OIDC还好，其他的功能，如OAuth 2.0, SAML, CAS, LDAP, WebAuthn, 2FA、邮箱验证码、短信验证码，都自己开发难度就太大了。
> > 
> > 
> > 除却 OAuth 2.0，其余功能应该是交给 SSO 实现，AList 并不需要操心。如果指的是我之前提到的 WebAuthn 的话，我的意思是 Authelia 等已经支持了 WebAuthn，只需要支持 OIDC 接入，AList 就自动有这些功能了。而至于 OAuth 2.0，据我观察大部分开源的 SSO 都支持了 OIDC，而至于各大社交网站的登录则确实可以交给 Casdoor。
> 
> +1，我用的Authentik。所有单点登录都经过它。像其他的Authelia、Keycloak，本来就支持OIDC那些。结果还要新部署个Casdoor.。先跳Casdoor再跳Authentik....我现在就是直接Fowardauth了，，打开Alist先Authentik认证。但是坏处就是要打开游客访问。。而且。Casdoor不算好用。

虽然这个issue已经closed as completed，但我也是Authentik，用Casdoor跳实在是难受，真希望能原生支持一下OAuth 2.0

**Comment by 1298345095** [comment]
> > > @hsluoyz
> > > > 这些都需要单独起一个服务，都需要自建，与Casdoor没什么分别
> > > 
> > > 
> > > 我这里指的是为 AList 适配 OIDC。以我自己为例，我目前已经有 Authelia 并接入了一系列服务。Authelia 支持 OIDC，但为了接入 AList，我需要自建一个 Casdoor 接入 Authelia，然后再在 AList 接入 Casdoor。我认为这个是完全没有必要的。
> > > > 也就是说跳转几次取决于你采用什么方式去登录。所有的SSO都是这样工作的，这没什么问题。
> > > 
> > > 
> > > 此处同上。登录时需要 AList 跳 Casdoor 跳 Authelia，过程中会看到三个登录框。如果原生支持 OIDC 则可以简化为正常的一跳。
> > > > Casdoor 本身是收费的。
> > > 
> > > 
> > > 替我挽一下尊，这里指的是 Casdoor 官方的托管，也就是不自建 Casdoor 的情况。
> > > > 如果说只支持一个OIDC还好，其他的功能，如OAuth 2.0, SAML, CAS, LDAP, WebAuthn, 2FA、邮箱验证码、短信验证码，都自己开发难度就太大了。
> > > 
> > > 
> > > 除却 OAuth 2.0，其余功能应该是交给 SSO 实现，AList 并不需要操心。如果指的是我之前提到的 WebAuthn 的话，我的意思是 Authelia 等已经支持了 WebAuthn，只需要支持 OIDC 接入，AList 就自动有这些功能了。而至于 OAuth 2.0，据我观察大部分开源的 SSO 都支持了 OIDC，而至于各大社交网站的登录则确实可以交给 Casdoor。
> > 
> > 
> > +1，我用的Authentik。所有单点登录都经过它。像其他的Authelia、Keycloak，本来就支持OIDC那些。结果还要新部署个Casdoor.。先跳Casdoor再跳Authentik....我现在就是直接Fowardauth了，，打开Alist先Authentik认证。但是坏处就是要打开游客访问。。而且。Casdoor不算好用。
> 
> 虽然这个issue已经关了，但我也是Authentik，用Casdoor跳实在是难受，真希望能原生支持一下OAuth 2.0

现在还是不能authentik吗？

**Comment by ForsakenRei** [comment]
> > 虽然这个issue已经关了，但我也是Authentik，用Casdoor跳实在是难受，真希望能原生支持一下OAuth 2.0
> 
> 现在还是不能authentik吗？

不能，现在支持的SSO是GitHub，Dingtalk，Microsoft，Google和Casdoor

**Comment by 1298345095** [comment]
> > > 虽然这个issue已经关了，但我也是Authentik，用Casdoor跳实在是难受，真希望能原生支持一下OAuth 2.0
> > 
> > 
> > 现在还是不能authentik吗？
> 
> 不能，现在支持的SSO是GitHub，Dingtalk，Microsoft，Google和Casdoor

单点登录里单独有个OIDC。。那个能用吗

**Comment by ForsakenRei** [comment]
> > > > 虽然这个issue已经关了，但我也是Authentik，用Casdoor跳实在是难受，真希望能原生支持一下OAuth 2.0
> > > 
> > > 
> > > 现在还是不能authentik吗？
> > 
> > 
> > 不能，现在支持的SSO是GitHub，Dingtalk，Microsoft，Google和Casdoor
> 
> 单点登录里单独有个OIDC。。那个能用吗

看起来是能的，但我可能有什么没填对吧，返回的页面是这样的
```
{
  "code": 400,
  "message": "404 Not Found: \n\n\n\n\u003C!DOCTYPE html\u003E\n\n\u003Chtml\u003E\n    \u003Chead\u003E\n        \u003Cmeta charset=\"UTF-8\"\u003E\n        \u003Cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\"\u003E\n        \u003Ctitle\u003E\nAuthentik\n\u003C/title\u003E\n        \u003Clink rel=\"icon\" href=\"/media/favicon.ico\"\u003E\n        \u003Clink rel=\"shortcut icon\" href=\"/media/favicon.ico\"\u003E\n        \n\u003Clink rel=\"prefetch\" href=\"/static/dist/assets/images/flow_background.jpg\" /\u003E\n\u003Clink rel=\"stylesheet\" type=\"text/css\" href=\"/static/dist/patternfly.min.css\"\u003E\n\u003Clink rel=\"stylesheet\" type=\"text/css\" href=\"/static/dist/theme-dark.css\" media=\"(prefers-color-scheme: dark)\"\u003E\n\n\n\n\u003Cscript\u003E\n    window.authentik = {\n        locale: \"en-us\",\n        config: JSON.parse(''),\n        brand: JSON.parse(''),\n        versionFamily: \"\",\n        versionSubdomain: \"\",\n        build: \"\",\n    };\n    window.addEventListener(\"DOMContentLoaded\", function () {\n        \n    });\n\u003C/script\u003E\n\n\n        \u003Clink rel=\"stylesheet\" type=\"text/css\" href=\"/static/dist/authentik.css\"\u003E\n        \u003Clink rel=\"stylesheet\" type=\"text/css\" href=\"/static/dist/custom.css\" data-inject\u003E\n        \u003Cscript src=\"/static/dist/poly-2024.6.3.js\" type=\"module\"\u003E\u003C/script\u003E\n        \u003Cscript src=\"/static/dist/standalone/loading/index-2024.6.3.js\" type=\"module\"\u003E\u003C/script\u003E\n        \n\u003Cstyle\u003E\n:root {\n    --ak-flow-background: url(\"/static/dist/assets/images/flow_background.jpg\");\n    --pf-c-background-image--BackgroundImage: var(--ak-flow-background);\n    --pf-c-background-image--BackgroundImage-2x: var(--ak-flow-background);\n    --pf-c-background-image--BackgroundImage--sm: var(--ak-flow-background);\n    --pf-c-background-image--BackgroundImage--sm-2x: var(--ak-flow-background);\n    --pf-c-background-image--BackgroundImage--lg: var(--ak-flow-background);\n}\n/* Form with user */\n.form-control-static {\n    margin-top: var(--pf-global--spacer--sm);\n    display: flex;\n    align-items: center;\n    justify-content: space-between;\n}\n.form-control-static .avatar {\n    display: flex;\n    align-items: center;\n}\n.form-control-static img {\n    margin-right: var(--pf-global--spacer--xs);\n}\n.form-control-static a {\n    padding-top: var(--pf-global--spacer--xs);\n    padding-bottom: var(--pf-global--spacer--xs);\n    line-height: var(--pf-global--spacer--xl);\n}\n\u003C/style\u003E\n\n        \u003Cmeta name=\"sentry-trace\" content=\"\" /\u003E\n    \u003C/head\u003E\n    \u003Cbody\u003E\n        \n\u003Cdiv class=\"pf-c-background-image\"\u003E\n\u003C/div\u003E\n\u003Cak-message-container\u003E\u003C/ak-message-container\u003E\n\u003Cdiv class=\"pf-c-login stacked\"\u003E\n    \u003Cdiv class=\"ak-login-container\"\u003E\n        \u003Cmain class=\"pf-c-login__main\"\u003E\n            \u003Cdiv class=\"pf-c-login__main-header pf-c-brand ak-brand\"\u003E\n                \u003Cimg src=\"/media/ba_logo.png\" alt=\"authentik Logo\" /\u003E\n            \u003C/div\u003E\n            \u003Cheader class=\"pf-c-login__main-header\"\u003E\n                \u003Ch1 class=\"pf-c-title pf-m-3xl\"\u003E\n                    \nNot Found\n\n                \u003C/h1\u003E\n            \u003C/header\u003E\n            \u003Cdiv class=\"pf-c-login__main-body\"\u003E\n                \n\u003Cform method=\"POST\" class=\"pf-c-form\"\u003E\n    \u003Cp\u003E\u003C/p\u003E\n    \u003Ca id=\"ak-back-home\" href=\"/\" class=\"pf-c-button pf-m-primary\"\u003E\n        Go home\n    \u003C/a\u003E\n\u003C/form\u003E\n\n            \u003C/div\u003E\n        \u003C/main\u003E\n        \u003Cfooter class=\"pf-c-login__footer\"\u003E\n            \u003Cul class=\"pf-c-list pf-m-inline\"\u003E\n                \n                \u003Cli\u003E\n                    \u003Cspan\u003E\n                        Powered by authentik\n                    \u003C/span\u003E\n                \u003C/li\u003E\n            \u003C/ul\u003E\n        \u003C/footer\u003E\n    \u003C/div\u003E\n\u003C/div\u003E\n\n        \n        \n    \u003C/body\u003E\n\u003C/html\u003E\n",
  "data": null
}
```

**Comment by MemoryShadow** [comment]
> 看起来是能的，但我可能有什么没填对吧，返回的页面是这样的
> ...
> 刚才重新建了一个app+provider重新试了一下，现在提示no method provided，所以应该还是什么地方我填的有问题……

您好, 很高兴这个 issue 以及 #7599 的帮助, 您还在为这个问题困惑吗? 我在经过多次尝试后成功接入了标准 OIDC, 您要注意的地方为回调 URL 需要携带参数, 例如:
`http://127.0.0.1:5244/api/auth/sso_callback?method=sso_get_token` 而不是 `http://127.0.0.1:5244/api/auth/sso_callback`.

此外您需要注意 oidc 用户名键 是否正确, Alist 提供的默认值是错误的, 对于我使用的 `keycloak`, 此处的值应当为 `preferred_username`.

还有, 官方给出的 `casdoor` 中使用了 `casdoor` 服务的根目录作为 "单点登录端点名称", 这是因为 `.well-known/openid-configuration` 文件在那里, 如果你正在使用非默认的组织, 需要将其定位过去, 但在 `casdoor` 中应该是存在问题导致证书必须在默认组中才能被使用. 对于我使用的 `keycloak`, 对应的值应该是 `http://keycloak.service.host/realms/realm_name`. 需要额外注意的是末尾没有 `/`, 这是由于在 `http://keycloak.service.host/realms/realm_name/.well-known/openid-configuration` 的 `issuer` 字段中进行了强制声明.

我进行修改后的字段仅有以下几个:
- 启用单点登录: 修改为 On
- 单点登录平台: 修改为 OIDC
- 单点登录客户端ID: 修改为对应的客户端 ID
- 单点登录客户端机密: 修改为对应的客户端机密
- Sso oidc 用户名键: 修改为 `preferred_username`
- 单点登录组织名称: 用于显示, 请自便
- 单点登录应用名称: 用于显示, 请自便
- 单点登录端点名称: 详见上文

如果您遇到了类似如下的报错:

```json
{"code":400,"message":"404 Not Found: {\"error\":\"HTTP 404 Not Found\"}","data":null}
```

请记住, 这些错误有可能来自于您的 SSO 提供商而非 Alist, 我被这个误导排查了一段时间的日志.

祝您有一个良好的使用体验. ^^

**Comment by dalamudx** [comment]
同authentik，现在开不开兼容模式登录之后跳转都报
```
{"code":400,"message":"oidc: malformed jwt: square/go-jose: compact JWS format must have three parts","data":null}
```

**Comment by catfishlty** [comment]
> > 看起来是能的，但我可能有什么没填对吧，返回的页面是这样的
> > ...
> > 刚才重新建了一个app+provider重新试了一下，现在提示no method provided，所以应该还是什么地方我填的有问题……
> 
> 您好, 很高兴这个 issue 以及 [#7599](https://github.com/AlistGo/alist/issues/7599) 的帮助, 您还在为这个问题困惑吗? 我在经过多次尝试后成功接入了标准 OIDC, 您要注意的地方为在客户端中设置的允许回调 URL 需要携带参数, 例如: `http://127.0.0.1:5244/api/auth/sso_callback?method=sso_get_token` 而不是 `http://127.0.0.1:5244/api/auth/sso_callback`.
> 
> 此外您需要注意 oidc 用户名键 是否正确, Alist 提供的默认值是错误的, 对于我使用的 `keycloak`, 此处的值应当为 `preferred_username`.
> 
> 还有, 官方给出的 `casdoor` 文档中使用了 `casdoor` 服务的根目录作为 "单点登录端点名称", 这是因为 `.well-known/openid-configuration` 文件在那里, 如果你正在使用非默认的组织, 需要将其定位过去, 但在 `casdoor` 中应该是存在问题导致证书必须在默认组中才能被使用. 对于我使用的 `keycloak`, 对应的值应该是 `http://keycloak.service.host/realms/realm_name`. 需要额外注意的是末尾没有 `/`, 这是由于在 `http://keycloak.service.host/realms/realm_name/.well-known/openid-configuration` 的 `issuer` 字段中进行了强制声明.
> 
> 我进行修改后的字段仅有以下几个:
> 
> * 启用单点登录: 修改为 On
> * 单点登录平台: 修改为 OIDC
> * 单点登录客户端ID: 修改为对应的客户端 ID
> * 单点登录客户端机密: 修改为对应的客户端机密
> * Sso oidc 用户名键: 修改为 `preferred_username`
> * 单点登录组织名称: 用于显示, 请自便
> * 单点登录应用名称: 用于显示, 请自便
> * 单点登录端点名称: 详见上文
> 
> 如果您遇到了类似如下的报错:
> 
> {"code":400,"message":"404 Not Found: {\"error\":\"HTTP 404 Not Found\"}","data":null}
> 请记住, 这些错误有可能来自于您的 SSO 提供商而非 Alist, 我被这个误导排查了一段时间的日志.
> 
> 祝您有一个良好的使用体验. ^^

感谢您的方案
通过参考您的配置方式，我也将Authelia接入到Alist中作为OIDC的提供商。

配置如下：

#### Authelia 配置
```
      - id: alist
        description: AList
        secret: 'your-oidc-secret'
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://alist.example.com/api/auth/sso_get_token
          - https://alist.example.com/api/auth/get_sso_id
        scopes:
          - openid
          - email
          - profile
        userinfo_signing_algorithm: none
```

#### Alist 配置
* 启用单点登录: 修改为 On
* 单点登录平台: 修改为 OIDC
* 单点登录客户端ID: 修改为对应的客户端 ID，如示例中的`alist`
* 单点登录客户端机密: 修改为对应的客户端机密，如示例中的`your-oidc-secret`
* Sso oidc 用户名键: 修改为 `preferred_username`
* 单点登录应用名称: Authelia
* 单点登录端点名称: https://auth.example.com
* Sso兼容模式: 修改为 On
