### ISSUE TITLE
建议添加 pan.wo.cn

### ISSUE THREAD

**Issue by cyclestudy** [alist-org/alist#3917]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

pan.wo.cn

### Suggested solution / 实现思路

pan.wo.cn

**Comment by nancheung** [comment]
附议

**Comment by nexx5** [comment]
附议。

**Comment by xiaoxiaoxiaodeseyixia** [comment]
附议

**Comment by vicdorke** [comment]
附议

**Comment by youtehub** [comment]
支持一下，希望集成

**Comment by dhfsqxz** [comment]
附议
