### ISSUE TITLE
阿里云盘open提示请求太多

### ISSUE THREAD

**Issue by yb1229998088** [alist-org/alist#3918]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.14.0

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

添加储存就提示Failed init storage: failed to refresh token: Too Many Requests
已经添加过的储存暂时还能用，但是如果取编辑储存内容就立马出这个报错了。

### Reproduction / 复现链接

https://api.nn.ci/alist/ali_open/token

### Logs / 日志

Failed init storage: failed to refresh token: Too Many Requests

**Comment by xiaogui2011** [comment]
这问题开始困扰这我

**Comment by xialei123456** [comment]
我也遇到了qaq  怎么解决呀

**Comment by baballuo** [comment]
同样的问题

**Comment by xd19861224** [comment]
有解决方案了吗？
