### ISSUE TITLE
阿里云盘上传文件时一直卡在“正在后台上传”，随后提示返回504错误。

### ISSUE THREAD

**Issue by NianBroken** [alist-org/alist#3919]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

阿里云盘OPEN

### Describe the bug / 问题描述

在“阿里云盘OPEN”驱动内上传文件会一直卡在“正在后台上传”，随后提示返回504错误。
其他驱动则不会出现这个问题

### Reproduction / 复现链接

https://pan.nianbroken.top/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/Bandicam

### Logs / 日志

![image](https://user-images.githubusercontent.com/57057288/226811531-c797a0f8-7ae2-4fe2-8204-698da1c53031.png)
![image](https://user-images.githubusercontent.com/57057288/226811640-51a1be58-5f87-4871-8c5a-845eab5f24af.png)
![image](https://user-images.githubusercontent.com/57057288/226811669-cd57375b-a5c1-47e6-999b-a61831242ba7.png)

**Comment by Xhofe** [comment]
你没有提供任何有用的信息，我无法复现你的问题

**Comment by Xhofe** [comment]
> Put "https://cn-beijing-data.aliyundrive.net/Z1bzjCws%2F40430%2F641a9ddb061cf11b38954d689e926566d9da038d%2F641a9ddb62b97a4879cb4d44b4115d45ff5ce13d?partNumber=1&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5baJd3mgJNp9LKvaWXaoWQ2Nb5CuKHRoTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNQmoBQvPqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABdd0yfro0xyS0octJPnlQ3AiT9nkOe21WLqw0MhIHJM5OEvMCcHe8rLry4cQqPatUx65cs%2FphTO7npXW4Gw6yEhAoAIYI6orbKOvzx3U2v8qlL0IOnKW6XVnyhCIWAxfX3EiqFfYiiwTsfjcYKzbIaxfLkgJBIE%2BVn3XbwQPn6gQ%3D&uploadId=FB27C5D547DA4C3BAC00E92C2906C911&x-oss-access-key-id=STS.NUongRmLHCpDkCkEdc91nWdzC&x-oss-expires=1679469547&x-oss-signature=H9k1LreI6nthbZw0LpEEIpXP2oLJGVLr4rvj0R6KGAc%3D&x-oss-signature-version=OSS2": write tcp ********:33118->***********8:443: use of closed network connection

抱歉你的服务器与阿里云盘的上传节点通信有问题，与alist无关。
