### ISSUE TITLE
迅雷云盘上传图片（视频）会变成别的（他人的）图片（视频）（疑似网盘BUG？安全性问题？）

### ISSUE THREAD

**Issue by ptbsare** [alist-org/alist#3920]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

迅雷云盘

### Describe the bug / 问题描述

复现步骤：
1、打开alist网页端迅雷云盘文件夹
2、向 我的资源 文件夹上传一张图片
3、待上传成功后预览该图片
4、图片变为他人图片。
![Screen-Recording-2023-03-22-at-18 21 05](https://user-images.githubusercontent.com/3147576/226875982-eddb6256-626e-46b7-8dfe-9b392c92c999.gif)

### Reproduction / 复现链接

见复现步骤视频：
![Screen-Recording-2023-03-22-at-18 21 05](https://user-images.githubusercontent.com/3147576/226876030-f3e81d60-8e31-4de4-8804-2075ed036771.gif)

**Comment by Rektyfikowany** [comment]
这个问题你有通过迅雷官方的客户端重试过吗，如果官方上传结果相同那么alist无法解决

**Comment by ptbsare** [comment]
![迅雷](https://user-images.githubusercontent.com/3147576/226898547-2ea0659a-657e-42c0-ac91-f4afc808f898.gif)
尝试用尝试用官方的客户端，无此问题。

**Comment by foxxorcat** [comment]
![image](https://user-images.githubusercontent.com/95907542/226917465-165d6597-87cf-4fc3-a577-dda98f91eb92.png)
无法复现，有概率是迅雷服务器那边的问题。程序上传逻辑中只省略了hash计算部分以达到以流的形式上传。

**Comment by foxxorcat** [comment]
好吧后缀名改了以后就有问题了，而且出现的图片很随机，甚至出现视频，这算不算攻击了迅雷云盘🤔

**Comment by ptbsare** [comment]
是的，图片很随机，每次都不一样，建议报给迅雷官方了，隐私泄露风险。😃😅😅😅

**Comment by Rektyfikowany** [comment]
确实没想明白，就算hash碰撞了每次出错的内容应该会相同吧🤔，坐等大佬解答

**Comment by foxxorcat** [comment]
加上hash计算果然就好了，应该是迅雷那边策略有问题

**Comment by foxxorcat** [comment]
迅雷本身就不支持秒传之类的hash对迅雷应该不重要才对，更何况上传后服务器会重新计算hash，不大可能是hash碰撞。想不明白

**Comment by ptbsare** [comment]
这其实是一个安全性问题。是不是意味着如果我有一个迅雷的账号，通过构建精巧的上传文件的网络请求就可以看到别人在迅雷里面的随机照片？

**Comment by foxxorcat** [comment]
对的，这是一个安全问题，而且得尽快解决，就看迅雷官方如何解决了

**Comment by Rektyfikowany** [comment]
况且我们构造的这个请求倒也没有多"精巧"纯属意外😂，也无从了解hash是怎么引起这种随机的问题的了

**Comment by Rektyfikowany** [comment]
况且我们构造的这个请求倒也没有多"精巧"纯属意外😂，也无从了解hash是怎么引起这种随机问题的了

**Comment by foxxorcat** [comment]
精巧的是这图片和名字好吧，名字或图不同都不会有问题

**Comment by ptbsare** [comment]
这个图片一点也不特殊的，触发那个bug以后。把他展示那个图片下载下来再上传上去，会触发同样的bug。也会变成另外一张图片，所以图片一点也不特殊。或者你随便上传一张别的图片，也会触发这个bug。

**Comment by Xhofe** [comment]
一点猜想：或许是迅雷中间改过逻辑，某个时间点之前它不支持hash秒传而现在支持了，导致之前使用alist上传的很多文件hash值一样，所以现在上传会导致会随机在有同样hash的文件中选取一个。

**Comment by ptbsare** [comment]
猜想比较合理，但是目前我这边只能复现图片和视频的情况，有没有其他人复现上传其他类型文件也会出现变成其它文件的情况？

**Comment by foxxorcat** [comment]
大概找到原因了，就是迅雷那边有问题，如果上传后马上刷新就会获取到别人的文件，但等一下或多刷一次就没问题

**Comment by Rektyfikowany** [comment]
> 但等一下或多刷一次就没问题

这么看来服务器或许上传完后某个时间重新计算了hash？这样处理倒也解释的通

**Comment by Panici4** [comment]
> 大概找到原因了，就是迅雷那边有问题，如果上传后马上刷新就会获取到别人的文件，但等一下或多刷一次就没问题

我刚开始出现了，过了几分钟就正常了。

**Comment by foxxorcat** [comment]
估计是迅雷服务器上文件对应的ID在刚上传的那段时间是空的，在数据库里找其他文件身上去了。迅雷在没有上传文件就生成了文件ID
