### ISSUE TITLE
OneDrive无法挂载

### ISSUE THREAD

**Issue by MoeCinnamo** [alist-org/alist#3921]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

在正确填写所有链接后，点击挂载会直接转圈，不关掉会一直转下去，关掉再打开会出现一个状态为空，同时不能禁用、启用和删除的存储。

### Recurrence steps / 复现步骤

根据教程依次填写挂载

### Reproduction / 复现链接

https://fileshare.mojy.xyz/

**Comment by JeamUmika** [comment]
估计是网络问题
