### ISSUE TITLE
初代V3.0版本升级到V3.14后，威联通(QNAP)NAS的HybridMount无法挂载

### ISSUE THREAD

**Issue by G22DER** [alist-org/alist#3923]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

百度网盘、阿里云盘

### Describe the bug / 问题描述

从docker，初代V3.0版本升级到V3.14.0后，在威联通(QNAP)NAS的HybridMount应用中变得无法挂载了，一直提示“正在挂载”。试了两台不同型号威联通都是一样。使用/dav、/dav/ali路径都是一样。我应该如何解决。
![08f0d7045530a43c377443adb7b4b1a](https://user-images.githubusercontent.com/104652125/226974123-3eb88e8e-3517-43d2-b0a7-cfc51eb8697e.png)

### Reproduction / 复现链接

1

**Comment by G22DER** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by G22DER** [comment]
在更新HybridMount后，在远程挂载中选择云服务的webdav可以挂载成功
![image](https://user-images.githubusercontent.com/104652125/227066155-3444ea6c-3cf0-49ab-a6aa-a56da38394c6.png)

**Comment by markhomanho** [comment]
請問你是填了什麼才用HYBRIDMOUNT 連上的
我的INFUSE 能掛載上WEBDAV 但是我用HYBRIDMOUNT 就無法連接上

**Comment by G22DER** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by G22DER** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月9日(周日) 中午11:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [alist-org/alist] 初代V3.0版本升级到V3.14后，威联通(QNAP)NAS的HybridMount无法挂载 (Issue #3923)




 
請問你是填了什麼才用HYBRIDMOUNT 連上的
 我的INFUSE 能掛載上WEBDAV 但是我用HYBRIDMOUNT 就無法連接上

**Comment by G22DER** [comment]
> 請問你是填了什麼才用HYBRIDMOUNT 連上的 我的INFUSE 能掛載上WEBDAV 但是我用HYBRIDMOUNT 就無法連接上

![Uploading Screenshot_20230410224957.jpg…]()

**Comment by G22DER** [comment]
> 請問你是填了什麼才用HYBRIDMOUNT 連上的 我的INFUSE 能掛載上WEBDAV 但是我用HYBRIDMOUNT 就無法連接上

服务器url填: http://192.168.31.26:5244/dav
