### ISSUE TITLE
希望增加alist看视频的播放记录

### ISSUE THREAD

**Issue by qinghena** [alist-org/alist#3930]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加alist看视频的播放记录，断点播放要是能播放记录里面显示进度和检测有没有下一集就更好了。类似追番的这种功能

**Comment by youtehub** [comment]
这可以使用 **Rclone** 挂载出来以后，用其他软件播放就可以直接解决了呗，例如 **emby** ，开源免费
