### ISSUE TITLE
115网盘突然无法加载播放文件

### ISSUE THREAD

**Issue by shaopak** [alist-org/alist#3931]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

115 Cloud

### Describe the bug / 问题描述

之前一直正常使用，今天白天发现115网盘虽可以正常挂载目录，但是实际无法加载播放内容。

pdf、mp4、mkv等文件格式尝试了全部无法加载。

### Reproduction / 复现链接

目前报错环境是：mac arm64版 v3.14.0

**Comment by kingicer** [comment]
今天上午也遇到同样的问题，但是国外的小鸡挂载的115网盘一直正常，没有问题

**Comment by smarxtboy** [comment]
回退alist版本到v3.12.2  可以解决问题，刚刚已经解决了

**Comment by shaopak** [comment]
> 回退alist版本到v3.12.2 可以解决问题，刚刚已经解决了

但是我回退到v3.12.2后发现只有部分文件恢复正常，很多依旧是播放不了的，而且还是随机恢复正常

**Comment by We1eVen** [comment]
> 退alist版本到v3.12.2 可以解决问题，刚刚已经解决了

实测有效，感谢
