### ISSUE TITLE
游客通过url无需密码访问元信息目录

### ISSUE THREAD

**Issue by adorabled4** [alist-org/alist#3938]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

阿里云盘OPEN

### Describe the bug / 问题描述

我通过管理页面添加了元信息目录并且设置了需要密码访问  ,  对于正常的游客, 如果通过主页的目录逐层点击是需要密码的(正常执行)  ,  但是如果直接在浏览器输入对应目录的url , 也可以访问到需要密码的目录
![image](https://user-images.githubusercontent.com/96526641/227444801-f054ef61-fc2d-4b77-815c-aeee34e81bfc.png)

### Reproduction / 复现链接

元信息目录 https://alist.dhx.icu/tmpFiles
文件目录 https://alist.dhx.icu/tmpFiles/sofeware
tmpFiles目录需要输入密码访问

**Comment by ronnie9211** [comment]
有打开应用到子目录开关吗

**Comment by zerofo** [comment]
知道 路径 加个 /p/ 还可以不用密码。。。
例如 http://ip/test/ 元信息加密 test下有test.zip
直接访问 http://ip/p/test/test.zip 还是能正常下载无需密码
