### ISSUE TITLE
配置文件开了https并配置证书后，http则不能连接，是否可以分开端口？

### ISSUE THREAD

**Issue by chung1912** [alist-org/alist#3943]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.14.0

### Driver used / 使用的存储驱动

所有

### Describe the bug / 问题描述

配置文件开了https并配置证书后，http则不能连接，是否可以分开配置端口？

### Reproduction / 复现链接

无

**Comment by Rektyfikowany** [comment]
好奇开了https为什么有必要保留http端口，哪一个客户端不支持ssl吗

**Comment by 12189108** [comment]
你用nginx反代呗，直接解决问题

**Comment by chung1912** [comment]
> 好奇开了https为什么有必要保留http端口，哪一个客户端不支持ssl吗

这里配置后，内网环境用ip时不能连接了，只能域名使用。其实很多docker服务都有http和https两个端口，可以同时使用

**Comment by chengnan049** [comment]
> > 好奇开了 https 为什么有必要保留 http 端口，哪一个客户端不支持 ssl 吗
> 
> 这里配置后，内网环境用 ip 时不能连接了，只能域名使用。其实很多 docker 服务都有 http 和 https 两个端口，可以同时使用

同求

**Comment by Rektyfikowany** [comment]
> 这里配置后，内网环境用ip时不能连接了，只能域名使用。其实很多docker服务都有http和https两个端口，可以同时使用

分开配置两组`Address`&`Port`容易实现，不过分开两组`SiteURL`影响面比较大，看看作者@Xhofe对这种域名和IP混用需求的态度了

**Comment by ronnie9211** [comment]
> > 好奇开了https为什么有必要保留http端口，哪一个客户端不支持ssl吗
> 
> 这里配置后，内网环境用ip时不能连接了，只能域名使用。其实很多docker服务都有http和https两个端口，可以同时使用

使用nginx反向代理

**Comment by chengnan049** [comment]
我个人是使用 `IPv6 + DDNS` 的方式实现外网访问的，所以查询域名 IP 时会解析到 公网 V6，我个人家庭中需要使用 [WebDAV 播放器](https://github.com/nova-video-player/aos-AVP) 进行媒体访问，现提供一种曲线救国的方法，方案如下

1. 使用 `OpenWrt` 将公网域名劫持到 路由器内网IP（**`Luci --> 网络 --> DHCP/DNS --> 自定义域名劫持`**） 如 **`home.xxx.com --> 192.168.2.1`**（该方案似乎需要将内网设备 DNS 设置为 OpenWrt 主机）
![image](https://user-images.githubusercontent.com/46060083/235393125-f9387857-9af5-4225-a741-ce663aaca342.png)
2. 使用 `OpenWrt` 内 `Host` 文件进行指定 IP，Passwall 用户可以在（**`Luci --> 服务 --> Passwall --> 规则列表 --> 路由 Hosts 文件`**）中进行设置
![image](https://user-images.githubusercontent.com/46060083/235393441-4354b8f1-9c86-40b8-9d45-941415202cee.png)
3. 使用 `Clash` 等插件进行分流，Clash 实现代理本身就需要 `劫持 DNS` 理论上不需要手动设置内网设备 DNS（瞎猜的，未测试，可作为参考，具体不再赘述请自行摸索）

P.S.使用以上方案时可能需要关闭 `私人DNS` ，`AdGuard` ,  `Intra` 等用户请自行摸索，例如在 `MIUI14` 中 就提示 手动指定 `Wi-Fi` 的 DNS 服务器会被 `私人DNS` 覆盖

**Comment by Xhofe** [comment]
- #4536
