### ISSUE TITLE
path: /d/* 这个路径没有做权限验证，是否要考虑下载的安全？

### ISSUE THREAD

**Issue by traceless** [alist-org/alist#3944]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0 +

### Driver used / 使用的存储驱动

all drive

### Describe the bug / 问题描述

1. 这个路径下的文件理论上会被 访客访问到，不知道为何设计不添加这个权限的验证。如果跳转不方便携带token，那么可以应该添加一个签名来防止访问吧？

### Reproduction / 复现链接

/d/* 的路径都不用授权即可访问

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/config/global.html#%E7%AD%BE%E5%90%8D%E6%89%80%E6%9C%89

**Comment by traceless** [comment]
> https://alist.nn.ci/zh/config/global.html#%E7%AD%BE%E5%90%8D%E6%89%80%E6%9C%89

好的，多谢
