### ISSUE TITLE
是否会考虑海报墙功能

### ISSUE THREAD

**Issue by wisinfun** [alist-org/alist#3945]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

海报墙有更好的观影体验，类似于低配版Emby、Plex
并且Alist有重定向功能，相对于Emby这是很大的优势，易于分享和异地播放

### Suggested solution / 实现思路

初期可以考虑直接适配刮削好的影视库（[TMM](https://www.tinymediamanager.org/download/)刮削），由用户自己手动刮削，实现成本会相对较低
后期可以考虑直接适配[TMDB](https://www.themoviedb.org/)刮削平台，自动刮削

**Comment by wisinfun** [comment]
迅雷NAS也退出了简易海报墙功能，功能还比较简单，但是效果已经挺好的了
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/41355260/227691242-72c7155a-2710-4dae-b9e8-a0e681d2eff9.png">

**Comment by jinchunyou** [comment]
有个第三方的开源项目叫onelist 就是实现这个功能的

**Comment by wisinfun** [comment]
> 有个第三方的开源项目叫onelist 就是实现这个功能的

感谢分享，我去体验下

**Comment by mondayice** [comment]
轻量化
