### ISSUE TITLE
手机/手机UI  观看视频时会有两个进度条

### ISSUE THREAD

**Issue by anwen-anyi** [alist-org/alist#3954]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

All

### Describe the bug / 问题描述

手机观看/手机UI观看 视频时会有两个进度条

### Reproduction / 复现链接

如果是手机可以直接看能看到，如果是浏览器切换成手机的UA刷新网页即可复现
![image](https://user-images.githubusercontent.com/56105412/227752118-f71a1a0f-b9ef-469b-83b5-433aed48fd57.png)

### Logs / 日志

No log

**Comment by Rektyfikowany** [comment]
测试发现`artplayer@4.5.10`及更早版本没这个问题，`4.5.11`开始有新的进度条以及上次观看进度记录等新功能，
还没仔细看`artplayer`文档这个是feature还是bug

**Comment by anwen-anyi** [comment]
> 测试发现`artplayer@4.5.10`及更早版本没这个问题，`4.5.11`开始有新的进度条以及上次观看进度记录等新功能， 还没仔细看`artplayer`文档这个是feature还是bug

我拿我本地的  `v3.13.1的AList` 看也是这样 ，artplayer版本是 `4.5.4`

**Comment by Rektyfikowany** [comment]
> 我拿我本地的 `v3.13.1的AList` 看也是这样 ，artplayer版本是 `4.5.4` 

我电脑上`alist@3.14.0`和之前的版本没有问题
![屏幕截图](https://user-images.githubusercontent.com/126593039/227755560-28784fcc-c79c-4a0e-a302-2c3adab74612.png)

**Comment by anwen-anyi** [comment]
> > 我拿我本地的 `v3.13.1的AList` 看也是这样 ，artplayer版本是 `4.5.4`
> 
> 我电脑上`alist@3.14.0`和之前的版本没有问题

你把大小切换成 手机的那种 iPhone x，Pixel 这种呢  虽然你切换成手机UI了 哈哈~

**Comment by Rektyfikowany** [comment]
> 你把大小切换成 手机的那种 iPhone x，Pixel 这种呢 虽然你切换成手机UI了 哈哈~

切换`iPhone XR`效果一样，`artplayer`好像是按UA区分桌面端和移动端的显示

**Comment by anwen-anyi** [comment]
哈哈 上面提到的哪个版本确实是我自己的锅，不过v3.15.0确实是有的

### 没问题的版本
- [x] alist-windows-amd64-3.12.2@ArtPlayer  4.5.4
- [x] alist-windows-amd64-3.13.1@ArtPlayer  4.5.4
- [x] alist-windows-amd64-3.13.2@ArtPlayer  4.5.4
- [x] alist-windows-amd64-3.14.0@ArtPlayer  4.5.4
-----
### 出现的
- [x] alist-windows-amd64-3.15.0@ArtPlayer  4.6.2

**Comment by Syt100** [comment]
我手机电脑不管哪个版本都没这个问题，要不试试清理下浏览器缓存
