### ISSUE TITLE
阿里云open平台 挂载提示  failed to refresh token: Too Many Requests

### ISSUE THREAD

**Issue by tohsakarinww** [alist-org/alist#3955]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v2.0.0

### Driver used / 使用的存储驱动

阿里云盘开放平台

### Describe the bug / 问题描述

阿里云open平台 挂载提示  failed to refresh token: Too Many Requests

### Reproduction / 复现链接

https://alist.nn.ci/tool/aliyundrive/callback.html?code=6763326fda214b00aa5726e7217607fc

### Logs / 日志

![image](https://user-images.githubusercontent.com/123134759/227753102-3dae28d6-4dcc-4beb-9f4b-6a1a8a16ec8e.png

**Comment by tohsakarinww** [comment]
更新到最新版本还是不行

**Comment by vampire624** [comment]
Same problem here and why this issue is invalid?
