### ISSUE TITLE
服务器迁移时恢复出错

### ISSUE THREAD

**Issue by swRains** [alist-org/alist#3956]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.13.1

### Driver used / 使用的存储驱动

aliyun_open

### Describe the bug / 问题描述

站点备份后下载备份文件到本地，阿里云盘open的储存无法恢复，日志如下。新添加也无法添加，复制原始docker卷文件也一样，不知道是不是我的设置问题？
docker是bridge网络，可能docker自身的ip地址不一样导致的？期望有大佬能解答下。

### Reproduction / 复现链接

无

### Logs / 日志

Post "https://api.nn.ci/alist/ali_open/token": read tcp 192.168.48.2:43860->45.66.130.152:443: read: connection reset by peer

docker compose文件如下
version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - '/disk/sdb/docker/alist.alist:/opt/alist/data'
        ports:
            - '5244:5244'
        container_name: alist.alist
        image: 'xhofe/alist:latest'

**Comment by mengguyi** [comment]
connection reset by peer
你应该检查docker的网络配置看看
curl https://api.nn.ci/alist/ali_open/token
输出什么

**Comment by swRains** [comment]
> connection reset by peer 你应该检查docker的网络配置看看 curl https://api.nn.ci/alist/ali_open/token 输出什么

{"code":"Invalid request","message":"Incorrect GrantType","error":"Incorrect GrantType"}
