### ISSUE TITLE
优化根目录的元信息readme和子文件夹已有的readme冲突

### ISSUE THREAD

**Issue by threerog** [alist-org/alist#3963]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前根目录的`元信息`>`说明` 开启`应用到子文件夹`后
如果子文件夹存在自己的readme文件时也会被强制覆盖或者忽略掉
只显示元信息的说明

希望能在`元信息`>`说明`处增加一个勾选框`强制覆盖显示`或者`同时显示`
从而实现子文件夹本来的readme和元信息的说明不冲突
实现更个人化的效果

**Comment by cancundeyingzi** [comment]
我的在根目录 开启应用到子文件夹后，，，别的写了元信息的目录全部不显示，，，
例如目录a，b，c，元信息写了根目录（写了说明病应用到子文件夹）和a（没写说明），结果a不显示说明，，其余目录显示说明
