### ISSUE TITLE
希望aliyunopen添加M2ST RM RMVB在线播放功能 并可以在线挂载字幕 2 hours ago

### ISSUE THREAD

**Issue by miaopasimiao** [alist-org/alist#3964]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望aliyunopen添加M2ST RM RMVB在线播放功能 并可以在线挂载字幕
阿里云盘是支持这几个格式的云转码的

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/preview.html#video-types
