### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by bzmshang** [alist-org/alist#3965]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

ONEDRIVE、123，阿里

### Describe the bug / 问题描述

在v3.14.0的时候，点击下载按钮，能正常下载
升级到v3.15.0后，下载按钮，点击就报错
{"code":401,"message":"expire missing","data":null}

之前版本都没有这个问题，就3.15.0才出现的

我可以【右键下载】，可以【复制链接下载】，就是【点击下载按钮】【不能下载】

### Reproduction / 复现链接

https://cloud.bzmshang.top/Software/Shizuku-Sui/Zygisk-Sui-v12.7.2.zip
任何一个点击下载按钮的，都报错

### Logs / 日志

![Uploading image.png…]()

**Comment by mengguyi** [comment]
https://github.com/alist-org/alist/issues/3957

**Comment by mengguyi** [comment]
https://github.com/alist-org/alist/commit/86beadc0ed902e89027ecb47d9fbd80d791ba426
这个PR修复了问题，你应该去actions里下载最新的构建

**Comment by anwen-anyi** [comment]
> > [86beadc](https://github.com/alist-org/alist/commit/86beadc0ed902e89027ecb47d9fbd80d791ba426) 这个PR修复了问题，你应该去actions里下载最新的构建
> 
> 能否请教，怎么从actions中下载最新

https://github.com/alist-org/alist/actions/runs/4523610315

**Comment by stevenliuit** [comment]
群晖里的插件 是不是只能等更新才行啊
