### ISSUE TITLE
115挂载视频不能播放

### ISSUE THREAD

**Issue by ivanterkai** [alist-org/alist#3967]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.0

### Driver used / 使用的存储驱动

115云盘

### Describe the bug / 问题描述

![微信图片_20230326211125](https://user-images.githubusercontent.com/33594133/227777961-c68f5e07-39c2-4a6d-873a-7f4d9a52bd01.png)

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/33594133/227778016-481c6295-bd8e-4f53-9857-e30e8b1420d1.png)

**Comment by 4free4ever** [comment]
我也是这样子。。。但是我是挂载在本地的有这个问题，分别试验了3条不同运营商的网络，几台不同的机子，不同的系统，都是如此。。。但是挂载在外网vps上的没有这个问题，一切正常。。。
