### ISSUE TITLE
手机移动端网页音频播放时，无法随着系统音量的改变而改变

### ISSUE THREAD

**Issue by 2389006038** [alist-org/alist#3975]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.15.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

手机移动端网页音频播放时，无法随着系统音量的改变而改变
PC端是正常的。
以下是手机信息
手机型号：Redmi Note11T Pro
处理器：联发科 天玑8100
系统版本：MIUI 14.0.3
Android版本：13
浏览器：Microsoft Edge 110.0.1587.66

### Reproduction / 复现链接

**Bug复现视频**

https://user-images.githubusercontent.com/41809763/227914176-6a096cb4-9ed6-4295-bcf7-d4513dabe8e1.mp4

**Comment by Xhofe** [comment]
安卓edge与iOS safari均无法复现，请向上级依赖反馈：https://github.com/DIYgod/APlayer

**Comment by 2389006038** [comment]
> 安卓edge与iOS safari均无法复现，请向上级依赖反馈：https://github.com/DIYgod/APlayer
十分不好意思，是我手机的问题，找到原因了😂，扬声器莫名其妙进入耳机模式了😂。
这是个很棒的项目！👍

**Comment by 2389006038** [comment]
> @Xhofe 安卓edge与iOS safari均无法复现，请向上级依赖反馈：https://github.com/DIYgod/APlayer
十分不好意思，是我手机的问题，找到原因了😂，扬声器莫名其妙进入耳机模式了😂。
这是个很棒的项目！👍
