### ISSUE TITLE
{"code":401,"message":"expire missing","data":null}

### ISSUE THREAD

**Issue by IceBingQI** [alist-org/alist#3979]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.15.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

从3.14版本升级至3.15版本后，下载文件提示{"code":401,"message":"expire missing","data":null}，视频和音频也无法正常播放，降级至3.14版本后恢复正常

### Reproduction / 复现链接

因为是内网使用，无法提供外网链接

### Logs / 日志

<img width="833" alt="image" src="https://user-images.githubusercontent.com/95079514/228154998-1d14e7dc-89a1-4e31-9785-275d0672c24f.png">

**Comment by Rektyfikowany** [comment]
参考#3957 #3965 处理
