### ISSUE TITLE
无法通过域名直接访问本机存储的非根目录

### ISSUE THREAD

**Issue by joeyzhou521** [alist-org/alist#3980]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

感谢大佬，我用alist仅挂载本地硬盘当nas用，用外部vps搭建了宝塔面版反代了域名访问https下的alist
目前配置为文件夹路径J:\MyDrive，访客权限路径/MyDrive/Share

现有问题是：
通过域名url访问MyDrive/Share/Download目录的时候显示ailed get parent list: failed get dir: object not found
手动点击到主页后可以正常显示/MyDrive/Share的内容
我发现https://github.com/alist-org/alist/issues/1732
这里有挂载网盘时相同问题的解决方法，但无法应用在本地存储上，请问是否有什么其他解决方案？

谢谢

**Comment by anwen-anyi** [comment]
`/Download` 有这个目录吗？
