### ISSUE TITLE
挂载百度网盘，视频无法播放

### ISSUE THREAD

**Issue by BytePrince** [alist-org/alist#3982]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

按照官方文档，尝试了三种WebDAV 策略，视频均无法调用本地播放器播放。

### Reproduction / 复现链接

视频请求返回403

**Comment by anwen-anyi** [comment]
三种模式的前提是你需要有`SVIP`，文档也写的很清楚
如果你使用302，哪你得设置UA头
如果你使用本地代理 你得有一个大宽带

**Comment by LordHumphrey** [comment]
> UA头

请问UA头设置成什么，谢谢

**Comment by Asukaaa648** [comment]
> > UA头
> 
> 请问UA头设置成什么，谢谢

设置成"pan.baidu.com"
