### ISSUE TITLE
123云盘下载频繁

### ISSUE THREAD

**Issue by ManjusakaY** [alist-org/alist#3986]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

![Screenshot_2023-03-29-04-58-39-271_mark via](https://user-images.githubusercontent.com/80582093/228365342-9364d9d9-9f52-40f3-9c57-4853da22875a.jpg)
如图所示
failed link: failed get link: 下载操作频繁，请稍后再试
已经更新alist到PR 86beadc 构建版本还是复现

### Reproduction / 复现链接

https://pan.qiule.top/ManjusakaToolbox/Q

### Logs / 日志

failed link: failed get link: 下载操作频繁，请稍后再试

**Comment by anwen-anyi** [comment]
这是123的问题  下载一多 列出文件一多 就会崩掉 QAQ

**Comment by ManjusakaY** [comment]
我直接换成onedrive😋
