### ISSUE TITLE
无法关闭搜索框

### ISSUE THREAD

**Issue by 3152598423** [alist-org/alist#3991]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

"允许索引"已关闭了已保存已刷新
搜索框仍然在显示

### Reproduction / 复现链接

无

### Logs / 日志

![A390HT$Y)XSY$MI)PYK _BT](https://user-images.githubusercontent.com/52593036/228626176-74f0c739-1ef2-4d81-af73-8fde4f0ce825.png)
![OH{F3 2$Z 5VPL@EIYE(PBB](https://user-images.githubusercontent.com/52593036/228626197-ba0411cb-1f50-49d1-a781-1a0738a8a496.png)

**Comment by Rektyfikowany** [comment]
根据[网站设置](https://alist.nn.ci/zh/config/site.html)和[搜索](https://alist.nn.ci/zh/guide/advanced/search.html)的文档进行设置，索引设置为无可关闭搜索框

**Comment by 3152598423** [comment]
### [已解决]把搜索索引改为无
![image](https://user-images.githubusercontent.com/52593036/228726454-6bac2157-d518-4ea5-a522-de0ba583df9f.png)

**Comment by 3152598423** [comment]
### [已解决]把搜索索引改为无
![image](https://user-images.githubusercontent.com/52593036/228726454-6bac2157-d518-4ea5-a522-de0ba583df9f.png)
