### ISSUE TITLE
在Windows7、10下挂载Webdav无法上传文件

### ISSUE THREAD

**Issue by zongceng** [alist-org/alist#3993]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

系统自带的Webdav

### Describe the bug / 问题描述

Alist新建的普通用户，在Windows7、10下，利用系统自带的功能挂载Webdav，无法复制、上传文件。但Alist的“admin”账户登录webdav后，上传功能正常。

### Reproduction / 复现链接

利用本地局域网测试

**Comment by zongceng** [comment]
> ### See
> 1. 59% [Windows下部分webdav软件上传 #376](https://github.com/alist-org/alist/issues/376)

仍存在此问题

**Comment by chengnan049** [comment]
实在不建议用系统自带的 WebDav ，如果你需要文件传输，那么我建议 FileZilla ，如果你需要挂载那么我建议 Rclone CloudDrive2

**Comment by prozyy** [comment]
希望大佬解决一下，win11、Mac下也遇到了同样的问题
