### ISSUE TITLE
关于V3模式的功能

### ISSUE THREAD

**Issue by 9E307** [alist-org/alist#3997]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

让V3模式可以挂载其它需要账号密码访问的alist网页

### Suggested solution / 实现思路

希望能够增加V3模式设置里的访问账号密码这个选项。以便对不开放游客访问的alist用v3进行挂载。

**Comment by chengnan049** [comment]
![image](https://user-images.githubusercontent.com/46060083/228815837-cb3252c6-cdcd-42c9-a42b-86751fa4a96f.png)
你想说的是这个吗？

**Comment by Xhofe** [comment]
你可以使用token挂载。

**Comment by 9E307** [comment]
后台只有填写密码的选项，没有填写账户的选项，另外token一般人也不会给你。token的权限比账号密码大多了。我只是想希望alist的V3支持填写账号密码访问对方的页面。

github-actions[bot] ***@***.***> 于2023年3月30日周四 19:53写道：
