### ISSUE TITLE
关于离线下载

### ISSUE THREAD

**Issue by xx6z8v** [alist-org/alist#4002]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否添加新的离线下载方式,不依赖任何第三方(比如Aria2),服务器因为特殊原因AList和Aria2不能共存

### Suggested solution / 实现思路

目前我可以用"地址树"挂载下载链接,任何复制文件到其它储存,所以AList应该是可以不依赖Aria2下载文件的,希望能单独设置此功能

**Comment by mengguyi** [comment]
go-torrent倒是可以，不过由于百度网盘多年的经营go-torrent已经进大多数BT软件使用者的黑名单了吧
