### ISSUE TITLE
建议支持小龙云盘，分布式存储，无限空间

### ISSUE THREAD

**Issue by egwang186** [alist-org/alist#4007]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议支持小龙云盘，分布式存储，无限空间

### Suggested solution / 实现思路

⭐小龙云盘〡基于IPFS技术无限空间免费不限速~
android：小龙云盘〡iOS：星河云盘
外链下载地址：https://wx.stariverpan.com/download/
(如若无法访问请自行复制链接移步到浏览器访问)

官方微信公众号：星河飞天

**Comment by Xhofe** [comment]
需要API文档。

**Comment by laopaoer-wallet** [comment]
这种小众的网盘......恐怕活不了多久...

**Comment by foxxorcat** [comment]
感觉可以再观望一下，感觉活不了多久了，客户端完全没有运用ipfs，全靠ipfs网关实现下载。
也就是说直接跑的是服务器流量，也就存储方面占了点边，用的是ipfs搭建的分布式存储。
并且在ipfs网络中文件扩散的还慢，直接把ipfs的优势全干没了，就是套了皮的网盘，在没有盈利能力之前完全是烧钱。😢

用本地的ipfs测试了一下，没办法访问小龙云的数据了，可能做了限制（这不等于是bt中的迅雷吗？）

小龙云ipfs的节点ID：
ip:182.139.36.103 id:12D3KooWBrKCoW6fjqGKi9iq7RZ79Mr8cEi7D86ZvzjYLDuCLFyh
ip:171.88.165.247 id:12D3KooWB8pRcKXnqy9v1cDnixcsvKQ3Xx6J9vze3nyfP9cfqgh8

**Comment by anwen-anyi** [comment]
> 这种小众的网盘......恐怕活不了多久...

被你真像了 哈哈
![C@D2}HKBGW)QU4XO`{~QNCS](https://user-images.githubusercontent.com/56105412/233535987-20188dca-54aa-40cf-8bf2-37c669127330.jpg)

**Comment by KarLYelin** [comment]
> 

买个破 U 盘还要付费买空间😳
直接攒钱买移动硬盘不好吗，而且区块链都东西上传了可能不能删除和修改💦💦💦

**Comment by eI91a1wT** [comment]
IPFS可以
