### ISSUE TITLE
OneDrive开启Web代理后支持多线程下载

### ISSUE THREAD

**Issue by KarlcxChina** [alist-org/alist#4014]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能够在开启Web代理的情况下多线程下载。
目前开启web代理选项后IDM只能单线程下载，对于底子不好的服务区来说甚至不如多线程直连

我使用Docker部署+直接宝塔反代方案，如有操作不当请大佬指出

**Comment by anwen-anyi** [comment]
多线程 单线程 似乎是和你服务器有关吧？ web代理了就看你自己搭建AList的机器了

**Comment by Xhofe** [comment]
本来就支持，自行检查反向代理配置。
