### ISSUE TITLE
挂在本地存储时图片和视频无法浏览

### ISSUE THREAD

**Issue by LovelyTitan** [alist-org/alist#4016]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

我使用的是群晖套件中心-社群的方式安装，已经是最新版本v3.15.0，同时群晖控制面板中文件夹的读写权限已给到。
使用Alist挂载本地目录后，目录结构可正常显示，直接右击下载文件也正常，
但是点击图片在线浏览时会显示“载入图像失败”。如果在该界面将Image模式改为Download会显示“{"code":401,"message":"expire missing","data":null}”
视频的话情况类似，会不断显示“重新连接”，最后“加载失败”

以上这些问题仅存在于本次存储中，在线存储的图片、视频在线浏览功能均正常
同时v3.14.0版本中好像没有该问题

### Reproduction / 复现链接

{"code":401,"message":"expire missing","data":null}

**Comment by gundamf6** [comment]
我也是同样的问题，你解决了没？

**Comment by BI1PBUTHU** [comment]
+1
