### ISSUE TITLE
太强了！

### ISSUE THREAD

**Issue by wdzhwsh4067** [alist-org/alist#4018]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

太强了

**Comment by anwen-anyi** [comment]
issue只适用于问题报告和功能请求 请勿乱使用~
