### ISSUE TITLE
[Driver Request] Google Drive Index

### ISSUE THREAD

**Issue by DarremMolko** [alist-org/alist#4020]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Repositories:
https://gitlab.com/GoogleDriveIndex/Google-Drive-Index
https://github.com/alx-xlx/goindex
https://github.com/menukaonline/goindex-extended

There are many of this indexes available on the web, it would be nice to mount them in Alist and access them through WebDAV.

### Suggested solution / 实现思路

Create a new storage driver for Google Drive Index.

### Additional context / 附件

-

**Comment by anwen-anyi** [comment]
It is recommended to read the documentation first ： https://alist.nn.ci/guide/drivers/googledrive.html

**Comment by DarremMolko** [comment]
> It is recommended to read the documentation first ： https://alist.nn.ci/guide/drivers/googledrive.html

I know about the Google Drive driver, I'm already using it. The Google Drive Index is a different thing, you wouldn't need any API credentials (client ID, client secret, etc) to mount other people's indexers in Alist, except maybe if they enabled the basic auth.
If you need an example of such indexers you can try searching this in Google "site:workers.dev/0:/".

**Comment by anwen-anyi** [comment]
> > It is recommended to read the documentation first ： https://alist.nn.ci/guide/drivers/googledrive.html
> 
> I know about the Google Drive driver, I'm already using it. The Google Drive Index is a different thing, you wouldn't need any API credentials (client ID, client secret, etc) to mount other people's indexers in Alist, except maybe if they enabled the basic auth. If you need an example of such indexers you can try searching this in Google "site:workers.dev/0:/".

Ok, sorry, first time seeing this `index` method :grin: :grin:
