### ISSUE TITLE
 connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by Tesla1983** [alist-org/alist#4028]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.15

### Driver used / 使用的存储驱动

pikpak

### Describe the bug / 问题描述

 connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

### Reproduction / 复现链接

 connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

### Logs / 日志

 connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by Xhofe** [comment]
https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers
