### ISSUE TITLE
登录就显示系统错误

### ISSUE THREAD

**Issue by redyellowred** [alist-org/alist#4029]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.1.5

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

每次登录就显示System error: TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:5244/assets/index.19879b92.js，但是我明明就挂载成功了网盘

### Reproduction / 复现链接

System error: TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:5244/assets/index.19879b92.js

**Comment by anwen-anyi** [comment]
检查你自己的网络问题

**Comment by redyellowred** [comment]
> 检查你自己的网络问题

我可以通过这个错误链接打开主页，挂载网盘也正常，只是不知道为什么每次登录就会弹出这个错误提示

**Comment by anwen-anyi** [comment]
你试试用 192.168.x.x的链接试试 你说的哪个问题我也遇到过但是一刷新就好了 就十天半月出现一次

**Comment by redyellowred** [comment]
> 你试试用 192.168.x.x的链接试试 你说的哪个问题我也遇到过但是一刷新就好了 就十天半月出现一次

非常感谢，我用本机ip还真正常了

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/issues/4030
