### ISSUE TITLE
我能正常登录，但是一点击主页就出现错误

### ISSUE THREAD

**Issue by redyellowred** [alist-org/alist#4030]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.1.5

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

System error: TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:5244/assets/Layout.dc0628db.js

### Reproduction / 复现链接

System error: TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:5244/assets/Layout.dc0628db.js

**Comment by Xhofe** [comment]
请检查你的环境。
