### ISSUE TITLE
移动把alist墙了，重置链接打不开，能不能本地化js？

### ISSUE THREAD

**Issue by 1265578519** [alist-org/alist#4049]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

?

### Describe the bug / 问题描述

访问 http://127.0.0.1:5244/ 页面，一直空白，F12抓包发现此url无法访问
![11](https://user-images.githubusercontent.com/6442439/230086983-e2160161-7dd7-4bae-adc2-564f144c37d3.png)

[?](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)

### Reproduction / 复现链接

？

**Comment by ilihu** [comment]
这么厉害？127.0.0.1 移动都能墙的吗？

**Comment by 1265578519** [comment]
> 这么厉害？127.0.0.1 移动都能墙的吗？

因为alist从外部引入了js文件，，，所以导致被墙了页面白屏。

**Comment by ilihu** [comment]
> > 这么厉害？127.0.0.1 移动都能墙的吗？
> 
> 因为alist从外部引入了js文件，，，所以导致被墙了页面白屏。

那只是polyfill被墙了，换个cdn就是了

**Comment by ilihu** [comment]
> > 那只是polyfill被墙了，换个cdn就是了
> 
> 自己换的话，直接删掉自定义头部会有其他影响吗？不知道那个js的作用

试试这个  
```
https://polyfill.alicdn.com/polyfill.min.js?features=String.prototype.replaceAll
```

**Comment by mengguyi** [comment]
进mysql里改
![image](https://user-images.githubusercontent.com/73788063/230105274-5691a4f7-6d88-43bd-aa03-c331414c744c.png)

**Comment by mengguyi** [comment]
或者你开个梯子进去再改

**Comment by 1265578519** [comment]
> 我忽然发现我忘加 v3 了，无所谓，反正里面就是注释

能不能让开发者提交个pr给本地化一下js，让用户自己改会有门槛

**Comment by 12189108** [comment]
> > 我忽然发现我忘加 v3 了，无所谓，反正里面就是注释
> 
> 能不能让开发者提交个pr给本地化一下js，让用户自己改会有门槛

你只要用的是现代浏览器（最新版kiwi 、chrome之类的），可以直接删掉这玩意

**Comment by ingxhe** [comment]
> 这么厉害？127.0.0.1 移动都能墙的吗？
> 
> 这么厉害？127.0.0.1 移动都能墙的吗？

你他妈就是纯种傻逼，秀什么？还127也能墙，是一个事吗
