### ISSUE TITLE
需要自定义3倍速功能

### ISSUE THREAD

**Issue by 1265578519** [alist-org/alist#4050]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

0.5, 1, 1.5, 2, 3, 4

**Comment by zhw2590582** [comment]
已经支持自定义倍速了：[demo](https://artplayer.org/?libs=&code=Artplayer.PLAYBACK_RATE%20%3D%20%5B0.5%2C%201%2C%201.5%2C%202%2C%203%2C%204%5D%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09playbackRate%3A%20true%2C%0A%7D)%3B%0A)

**Comment by Xhofe** [comment]
> 已经支持自定义倍速了：[demo](https://artplayer.org/?libs=&code=Artplayer.PLAYBACK_RATE%20%3D%20%5B0.5%2C%201%2C%201.5%2C%202%2C%203%2C%204%5D%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09playbackRate%3A%20true%2C%0A%7D)%3B%0A)

OK，感谢

**Comment by lovedva** [comment]
能保存倍速记录吗，就是自动播放到下一个视频的时候记忆倍速。
或者音频支不支持倍速。。。求。。。
