### ISSUE TITLE
google drive 302重定向

### ISSUE THREAD

**Issue by aprils148** [alist-org/alist#4052]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述
現在只能代理
google drive有辦法302重定向嗎?
不知道是不是無法實現。

**Comment by Xhofe** [comment]
Googledrive需要authorization，故无法实现。
