### ISSUE TITLE
build.sh cant download  release dependecy

### ISSUE THREAD

**Issue by neatlife** [alist-org/alist#4057]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

master

### Driver used / 使用的存储驱动

any

### Describe the bug / 问题描述

xx:~/go/src/alist$ wget https://musl.nn.ci/x86_64-linux-musl-cross
--2023-04-06 14:43:15--  https://musl.nn.ci/x86_64-linux-musl-cross
Resolving musl.nn.ci (musl.nn.ci)... 172.67.173.235, 104.21.30.209, 2606:4700:3033::6815:1ed1, ...
Connecting to musl.nn.ci (musl.nn.ci)|172.67.173.235|:443... connected.
HTTP request sent, awaiting response... 523 
2023-04-06 14:43:24 ERROR 523: (no description).

### Reproduction / 复现链接

https://github.com/alist-org/alist/blob/main/build.sh

### Logs / 日志

xx:~/go/src/alist$ wget https://musl.nn.ci/x86_64-linux-musl-cross
--2023-04-06 14:43:15--  https://musl.nn.ci/x86_64-linux-musl-cross
Resolving musl.nn.ci (musl.nn.ci)... 172.67.173.235, 104.21.30.209, 2606:4700:3033::6815:1ed1, ...
Connecting to musl.nn.ci (musl.nn.ci)|172.67.173.235|:443... connected.
HTTP request sent, awaiting response... 523 
2023-04-06 14:43:24 ERROR 523: (no description).

**Comment by mengguyi** [comment]
作者的服务器崩了而已，等等就好了
