### ISSUE TITLE
刷新导致管理页面自定义主题失效问题

### ISSUE THREAD

**Issue by yyccc-iu** [alist-org/alist#4058]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

Not mentioned

### Describe the bug / 问题描述

我在自定义区修改了一些颜色参数实现透明主题（其实就是在十六进制的颜色代码后面加了两位透明度参数），但是在管理页面下，只要浏览器刷新，自定义的颜色配置就会失效，回归默认设置。

翻看F12可以发现，使用的html源文件似乎甚至有差异(?)，我认为这应该算是一个BUG，修复后可以提高某些强迫症(just like me)享受到更好的使用体验......

plz  XD

### Reproduction / 复现链接

修改自定义主题后，在管理页面刷新浏览器

**Comment by imkratos** [comment]
作者回复过，，说后台管理，不支持自定义主题
