### ISSUE TITLE
希望能够提高调用频率，现在频繁出现toomanyrequest

### ISSUE THREAD

**Issue by ggfvictor** [alist-org/alist#4061]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能够提高调用频率，现在频繁出现toomanyrequest。
我有阅读wiki，但是我的访问频率真的没有很高，搭建完成后放了一个晚上，再去访问都会频繁出现toomanyrequest。需要刷新好几次才可以勉强成功一次。

### Additional context / 附件

![image](https://user-images.githubusercontent.com/27218364/230367120-71132b2d-4a32-44b2-a10e-c0acbce2cc2c.png)

**Comment by anwen-anyi** [comment]
耐心等待 这次似乎和 频率无关

**Comment by JingenChen** [comment]
是的，一上来就TooManyRequest，貌似和一个文件短时间内多次请求有关。

**Comment by ggfvictor** [comment]
但是事实上很多情况下我都是刚进去首页 随机访问一个网页都会出现这个问题，这种情况并不是短时间频繁访问

**Comment by mengguyi** [comment]
不行自己申请apikey吧

**Comment by 12189108** [comment]
> 不行自己申请apikey吧

咋申请，以前的填表填了半年没人理😅，阿里真的离谱

**Comment by Xhofe** [comment]
每次刷新token都有两个小时的有效期，所以理论上只要你不添加超过10个阿里云盘Open存储都不会触发toomanyrequest。

**Comment by mengguyi** [comment]
额...
![image](https://user-images.githubusercontent.com/73788063/230382898-3ab9ae3b-9302-447a-9c88-d761962a808e.png)
我就添加了一个，每分钟访问不超过40次。当我反复访问一个文件时（每分钟访问不超过40次）还是会触发

**Comment by mengguyi** [comment]
还是每个IP限制访问次数。我附近可能有人大量访问导致我被限制

**Comment by Xhofe** [comment]
> 额... ![image](https://user-images.githubusercontent.com/73788063/230382898-3ab9ae3b-9302-447a-9c88-d761962a808e.png) 我就添加了一个，每分钟访问不超过40次。当我反复访问一个文件时（每分钟访问不超过40次）还是会触发

这个是阿里的限制，并不是alist的限制：
https://www.yuque.com/aliyundrive/zpfszx/gogo34oi2gy98w5d#mN50J

**Comment by Stabrinai** [comment]
感觉这...像是阿里云把抽卡系统装到限制请求上了一样，有10%的几率成功访问，剩下的都是toomanyrequest

**Comment by mengguyi** [comment]
诶，还是用OneDrive吧

**Comment by Xhofe** [comment]
> 接口限制：单app 20qps, 单app单用户5s内调用1次。如要扩容，可找管理员申请。

这意味着同一秒内超过5个人使用AList 阿里云盘Open获取文件列表或或者下载文件就会触发toomanyrequest

**Comment by mondayice** [comment]
同样的情况，我在内网搭建的也出现`TooManyRequests`。可能是规则有变化

**Comment by mengguyi** [comment]
> > 接口限制：单app 20qps, 单app单用户5s内调用1次。如要扩容，可找管理员申请。
> 
> 这意味着同一秒内超过5个人使用AList 阿里云盘Open获取文件列表或或者下载文件就会触发toomanyrequest


作者的意思是全世界同一秒内超过5个人使用AList 阿里云盘Open
获取文件列表或或者下载文件就会触发toomanyrequest


> 同样的情况，我在内网搭建的也出现`TooManyRequests`。可能是规则有变化

**Comment by ggfvictor** [comment]
好了好了 大家请看这条回复，无论你的频率是多少，只要使用了作者的api，就会与所有alist用户共享这个rate limit 。这个不是alist限制的，是阿里云盘api的限制。如果要解除，只能自己申请api key  或者作者申请扩容，就酱。

**这个和你是否用新IP，是否在内网部署都没有任何关系！！！！！！**   最后 谢谢解答

接口限制：单app 20qps, 单app单用户5s内调用1次。如要扩容，可找管理员申请。

这意味着同一秒内超过5个人使用AList 阿里云盘Open获取文件列表或或者下载文件就会触发toomanyrequest

**Comment by xiaoyaliu00** [comment]
大家混为一谈了，虽然都是 “too many request”

**Comment by ihuge820920** [comment]
但是我没有nplayer也这样  用的potplayer和reex？也会吗

**Comment by Zason-Lee** [comment]
确实频繁出现，很影响用户体验！

**Comment by oyksoft** [comment]
昨天开始这样的吧，这么搞下去已经失去使用云盘的意义，而SVIP的官方客户端，下载速度也才100kb/s，阿里云啊，看来是不想玩这个云盘了

**Comment by zhi1ong** [comment]
> 大家混为一谈了，虽然都是 “too many request”，一个是请求 https://api.nn.ci/alist/ali_open/token 而截图的不是上述情况，而是昨天早上阿里新出的限制，是请求 https://open.aliyundrive.com/adrive/v1.0/openFile/getDownloadUrl
> 
> 如果是网页端那基本没问题，因为点击播放时，只请求一次文件，fileball也没什么问题，而其它的的播放器有预读功能，进入一个目录时会读取该目录下的其它文件，并且会对一个文件请求4-5次（nplayer），这就触发了这个 too many，昨天才出现的
> 
> 我的方法是把请求返回的url放入字典，以file_id做键，请求时先检查字典里该文件id的DownloadUrl是否存在，如存在则直接返回该值，如不存在则继续请求接口，那么多次请求可以大幅减少（不可能降为1次，因为不是按顺序请求，而是并发的），基本上解决这个问题

网页版本也随便点开几个图片也一样会出现这个问题。。

**Comment by wanglei-github** [comment]
我昨晚也是突然出现了，之前也没有遇到，现在基本无法通过kodi 挂载 alist使用。
老板们啊，帮忙想想解决办法，我也是转alist不久，感觉alist非常好用，我还捐献了一杯咖啡，老板们，加油啊

**Comment by seven3s** [comment]
看上去无解了，用nplayer魔改就是想要海报墙，还没玩到几个月，就不行了，阿里云盘有点小坑啊

**Comment by Malcolmwongzz** [comment]
> 每次刷新 token 都有两个小时的有效期，所以理论上只要你不添加超过 10 个阿里云盘 Open 存储都不会触发 toomanyrequest。

只有一个点进去就触发，并不是数量的问题

**Comment by Xhofe** [comment]
> > 每次刷新 token 都有两个小时的有效期，所以理论上只要你不添加超过 10 个阿里云盘 Open 存储都不会触发 toomanyrequest。
> 
> 只有一个点进去就触发，并不是数量的问题

麻烦看全。

**Comment by weicun581** [comment]
windows客户端非常容易出现too many request，
我的另外一台树莓派就没出现过这种情况呢

**Comment by KingDoum** [comment]
> windows客户端非常容易出现too many request， 我的另外一台树莓派就没出现过这种情况呢

你的树莓派 运行alist  风扇会突然 出现规则的声音么？ 像电锯一样 有点吵了
我关闭alist docker 就不响了

**Comment by weicun581** [comment]
> > windows客户端非常容易出现too many request， 我的另外一台树莓派就没出现过这种情况呢
> 
> 你的树莓派 运行alist 风扇会突然 出现规则的声音么？ 像电锯一样 有点吵了 我关闭alist docker 就不响了

没有哎，我没有发现散热风扇异响的情况，GPIO电压输出不稳定？可以找个示波器看下输出电压的曲线。

**Comment by KingDoum** [comment]
更新：现在搞定了
处理办法重新格式化，刷了系统，现在又稳定了

**Comment by weicun581** [comment]
> 更新：现在搞定了 处理办法重新格式化，刷了系统，现在又稳定了

棒，我现在都不敢轻易刷系统了，重新配置、安装软件太麻烦了。

**Comment by KingDoum** [comment]
及时备份，我买了个128G内存卡，然后用的一个脚本进行压缩备份。
把备份重新烧录进去，就ok啦

**Comment by KingDoum** [comment]
> > 更新：现在搞定了 处理办法重新格式化，刷了系统，现在又稳定了
> 
> 棒，我现在都不敢轻易刷系统了，重新配置、安装软件太麻烦了。

及时备份，我买了个128G内存卡，然后用的一个脚本进行压缩备份。
把备份重新烧录进去，就ok啦

**Comment by weicun581** [comment]
> > > 更新：现在搞定了 处理办法重新格式化，刷了系统，现在又稳定了
> > 
> > 
> > 棒，我现在都不敢轻易刷系统了，重新配置、安装软件太麻烦了。
> 
> 及时备份，我买了个128G内存卡，然后用的一个脚本进行压缩备份。 把备份重新烧录进去，就ok啦

机智如你，棒棒棒~

**Comment by KingDoum** [comment]
> > > > 更新：现在搞定了 处理办法重新格式化，刷了系统，现在又稳定了
> > > 
> > > 
> > > 棒，我现在都不敢轻易刷系统了，重新配置、安装软件太麻烦了。
> > 
> > 
> > 及时备份，我买了个128G内存卡，然后用的一个脚本进行压缩备份。 把备份重新烧录进去，就ok啦
> 
> 机智如你，棒棒棒~

哈哈，及时备份，方便折腾，老哥，你用树莓派，能做什么哇，最后

**Comment by weicun581** [comment]
> > > > > 更新：现在搞定了 处理办法重新格式化，刷了系统，现在又稳定了
> > > > 
> > > > 
> > > > 棒，我现在都不敢轻易刷系统了，重新配置、安装软件太麻烦了。
> > > 
> > > 
> > > 及时备份，我买了个128G内存卡，然后用的一个脚本进行压缩备份。 把备份重新烧录进去，就ok啦
> > 
> > 
> > 机智如你，棒棒棒~
> 
> 哈哈，及时备份，方便折腾，老哥，你用树莓派，能做什么哇，最后

基本上学习为主啦，其实就是瞎折腾，实际生活中也不怎么用的到，最近再玩homeassistant、motion。
你呢，用树莓派做产品吗？

**Comment by weicun581** [comment]
> > > 更新：现在搞定了 处理办法重新格式化，刷了系统，现在又稳定了
> > 
> > 
> > 棒，我现在都不敢轻易刷系统了，重新配置、安装软件太麻烦了。
> 
> 及时备份，我买了个128G内存卡，然后用的一个脚本进行压缩备份。 把备份重新烧录进去，就ok啦

你用的脚本是这个么？ [PiShrink](https://github.com/Drewsif/PiShrink)

**Comment by KingDoum** [comment]
> > > > > > 更新：现在搞定了 处理办法重新格式化，刷了系统，现在又稳定了
> > > > > 
> > > > > 
> > > > > 棒，我现在都不敢轻易刷系统了，重新配置、安装软件太麻烦了。
> > > > 
> > > > 
> > > > 及时备份，我买了个128G内存卡，然后用的一个脚本进行压缩备份。 把备份重新烧录进去，就ok啦
> > > 
> > > 
> > > 机智如你，棒棒棒~
> > 
> > 
> > 哈哈，及时备份，方便折腾，老哥，你用树莓派，能做什么哇，最后
> 
> 基本上学习为主啦，其实就是瞎折腾，实际生活中也不怎么用的到，最近再玩homeassistant、motion。 你呢，用树莓派做产品吗？

没，我跟你差不多，我当时买这个，就是为了跑跑日常跑跑脚本，现在就拿他来挂一下本地硬盘，可以自动下下番，离线下载视频，然后利用alist 访问。
后面暂时不打算折腾homeassistant，那个太费事了。

**Comment by weicun581** [comment]
> > > > > > > 更新：现在搞定了 处理办法重新格式化，刷了系统，现在又稳定了
> > > > > > 
> > > > > > 
> > > > > > 棒，我现在都不敢轻易刷系统了，重新配置、安装软件太麻烦了。
> > > > > 
> > > > > 
> > > > > 及时备份，我买了个128G内存卡，然后用的一个脚本进行压缩备份。 把备份重新烧录进去，就ok啦
> > > > 
> > > > 
> > > > 机智如你，棒棒棒~
> > > 
> > > 
> > > 哈哈，及时备份，方便折腾，老哥，你用树莓派，能做什么哇，最后
> > 
> > 
> > 基本上学习为主啦，其实就是瞎折腾，实际生活中也不怎么用的到，最近再玩homeassistant、motion。 你呢，用树莓派做产品吗？
> 
> 没，我跟你差不多，我当时买这个，就是为了跑跑日常跑跑脚本，现在就拿他来挂一下本地硬盘，可以自动下下番，离线下载视频，然后利用alist 访问。 后面暂时不打算折腾homeassistant，那个太费事了。

你用alist挂载阿里云盘吗？会遇到要经常更新token密码的情况吗？

**Comment by weicun581** [comment]
> > > > > > > > > 更新：现在搞定了 处理办法重新格式化，刷了系统，现在又稳定了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 棒，我现在都不敢轻易刷系统了，重新配置、安装软件太麻烦了。
> > > > > > > 
> > > > > > > 
> > > > > > > 及时备份，我买了个128G内存卡，然后用的一个脚本进行压缩备份。 把备份重新烧录进去，就ok啦
> > > > > > 
> > > > > > 
> > > > > > 机智如你，棒棒棒~
> > > > > 
> > > > > 
> > > > > 哈哈，及时备份，方便折腾，老哥，你用树莓派，能做什么哇，最后
> > > > 
> > > > 
> > > > 基本上学习为主啦，其实就是瞎折腾，实际生活中也不怎么用的到，最近再玩homeassistant、motion。 你呢，用树莓派做产品吗？
> > > 
> > > 
> > > 没，我跟你差不多，我当时买这个，就是为了跑跑日常跑跑脚本，现在就拿他来挂一下本地硬盘，可以自动下下番，离线下载视频，然后利用alist 访问。 后面暂时不打算折腾homeassistant，那个太费事了。
> > 
> > 
> > 你用alist挂载阿里云盘吗？会遇到要经常更新token密码的情况吗？
> 
> 我没用来挂 阿里云盘，我直接挂我本地的硬盘，以前的斐讯1T硬盘，最近又买了一个4T的机械硬盘 玩的。 另外 我是用的 [PiShrink](https://github.com/Drewsif/PiShrink) 可以参考这个教程 https://blog.csdn.net/m0_50679156/article/details/115431062

不太懂。你是用树莓派外接一个机械硬盘，然后用alist挂载，局域网其他电脑访问，是这样吗？

**Comment by KingDoum** [comment]
> 

对，就是这个意思，不仅仅是局域网访问，我还申请了公网ip ，然后直接公网ip访问，很舒服

**Comment by KingDoum** [comment]
> > 
> 
> 对，就是这个意思，不仅仅是局域网访问，我还申请了公网ip ，然后直接公网ip访问，很舒服

@weicun581

**Comment by weicun581** [comment]
> > 
> 
> 对，就是这个意思，不仅仅是局域网访问，我还申请了公网ip ，然后直接公网ip访问，很舒服

 机械硬盘长时间挂载在树莓派上，会不会造成损坏？
公网IP属实羡慕了，你家的网络是电信的？

**Comment by KingDoum** [comment]
> > > 
> > 
> > 
> > 对，就是这个意思，不仅仅是局域网访问，我还申请了公网ip ，然后直接公网ip访问，很舒服
> 
> 机械硬盘长时间挂载在树莓派上，会不会造成损坏？ 公网IP属实羡慕了，你家的网络是电信的？

应该不会吧，他本质上就是硬盘，电脑上弄个硬盘，怎么会损伤硬盘，除非，你玩的是pt 经常上传和下载。 我现在 就是用qb 下载点资源看看，不涉及到上传大量数据。
不是电信的，我是联通的。

**Comment by weicun581** [comment]
> > > > 
> > > 
> > > 
> > > 对，就是这个意思，不仅仅是局域网访问，我还申请了公网ip ，然后直接公网ip访问，很舒服
> > 
> > 
> > 机械硬盘长时间挂载在树莓派上，会不会造成损坏？ 公网IP属实羡慕了，你家的网络是电信的？
> 
> 应该不会吧，他本质上就是硬盘，电脑上弄个硬盘，怎么会损伤硬盘，除非，你玩的是pt 经常上传和下载。 我现在 就是用qb 下载点资源看看，不涉及到上传大量数据。 不是电信的，我是联通的。

你的树莓派是放在家里持续跑的吗？会定时重启吗？

**Comment by weicun581** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 对，就是这个意思，不仅仅是局域网访问，我还申请了公网ip ，然后直接公网ip访问，很舒服
> > > > 
> > > > 
> > > > 机械硬盘长时间挂载在树莓派上，会不会造成损坏？ 公网IP属实羡慕了，你家的网络是电信的？
> > > 
> > > 
> > > 应该不会吧，他本质上就是硬盘，电脑上弄个硬盘，怎么会损伤硬盘，除非，你玩的是pt 经常上传和下载。 我现在 就是用qb 下载点资源看看，不涉及到上传大量数据。 不是电信的，我是联通的。
> > 
> > 
> > 你的树莓派是放在家里持续跑的吗？会定时重启吗？
> 
> 对，持续跑，不定时重启哎，你的出现 定时重启的情况么？

没有，我再想持续跑会不会不太好，毕竟长时间运行，考虑定期重启下树莓派的。
不过话又说回来了，你的公网IP是怎么弄到的？
真实羡慕啊，我现在能通过云服务器做内网串通，但是小水管带宽也是小的可怜。

**Comment by KingDoum** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 对，就是这个意思，不仅仅是局域网访问，我还申请了公网ip ，然后直接公网ip访问，很舒服
> > > > > 
> > > > > 
> > > > > 机械硬盘长时间挂载在树莓派上，会不会造成损坏？ 公网IP属实羡慕了，你家的网络是电信的？
> > > > 
> > > > 
> > > > 应该不会吧，他本质上就是硬盘，电脑上弄个硬盘，怎么会损伤硬盘，除非，你玩的是pt 经常上传和下载。 我现在 就是用qb 下载点资源看看，不涉及到上传大量数据。 不是电信的，我是联通的。
> > > 
> > > 
> > > 你的树莓派是放在家里持续跑的吗？会定时重启吗？
> > 
> > 
> > 对，持续跑，不定时重启哎，你的出现 定时重启的情况么？
> 
> 没有，我再想持续跑会不会不太好，毕竟长时间运行，考虑定期重启下树莓派的。 不过话又说回来了，你的公网IP是怎么弄到的？ 真实羡慕啊，我现在能通过云服务器做内网串通，但是小水管带宽也是小的可怜。

不晓得， 树莓派 他是基于Linux的，大型服务器都是树莓派 一运行 运行一年多，也没啥问题。所以我就不考虑定时重启。

公网这个 确实是机缘巧合弄到的，没办法传授

树莓派是真的耐操，你日常跑起来 CPU温度应该也不高吧
