### ISSUE TITLE
希望可以添加短链接功能

### ISSUE THREAD

**Issue by floatanddream** [alist-org/alist#4063]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在某些情况分享带有中文的文件是连接会很长。
希望添加短链接功能以美化链接。

**Comment by mengguyi** [comment]
https://github.com/Xhofe/OEZ
