### ISSUE TITLE
alist data 路径

### ISSUE THREAD

**Issue by FxxKZhangYue** [alist-org/alist#4064]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v 3.15.0

### Driver used / 使用的存储驱动

none

### Describe the bug / 问题描述

在命令行启动alist的时候，加载的data总是当前工作路径的data（如果不存在它会新建，但是我已经在alist.exe所在的目录下有一个配置好的data文件夹，在其他目录使用alist start只是为了方便启动而已），--data 和 --force-bin-dir 都无效，希望能添加指定加载data路径或默认加载alist.exe目录下的data文件夹
补充：alist是使用winget下载的

### Reproduction / 复现链接

none

**Comment by Rektyfikowany** [comment]
--data和--force-bin-dir只设置了`config.json`的路径，而`config.json`中保存了`data.db`等配置文件所在路径，这些路径仍然是相对当前工作路径的（为了保持对现有配置文件的兼容也不方便轻易调整这一行为），用启动参数时需要注意检查`config.json`中的路径是否正确

**Comment by magicdawn** [comment]
感觉不是很直观, `--data` 应该被命名为 `--config /path/to/config.json`
然后在文档里注释下 config.json 里的路径是相对于程序启动 pwd, 而不是 config.json 的位置.
