### ISSUE TITLE
挂载阿里云盘后，kodi播放提示文件不可用

### ISSUE THREAD

**Issue by Zason-Lee** [alist-org/alist#4068]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.15.1

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

把阿里云盘挂载到alist以后，在kodi通过webdav协议添加完，刮削之后部分影片播放的时候会提示“此文件已不可用，要从资料库移除吗？”个别可以正常直接播放，有些就会出现这样的问题。

### Reproduction / 复现链接

只有挂载阿里云盘会出现这样的问题

**Comment by hetingrui** [comment]
一样
看之前重新扫描要看的剧/电影就能放了，但还是体验不佳
