### ISSUE TITLE
可否增加隐藏文件路径中储存桶名的选项

### ISSUE THREAD

**Issue by tjsky** [alist-org/alist#4069]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

设置CDN域名的一部分原因就是为了，隐藏对象储存域名和储存桶名，让别人无法获得文件真实链接，不能直接拉取从储存桶拉取文件。毕竟CDN的流量费用可比对象储存源站流量费用便宜的多。
但是目前的代码，会将文件链接拼接为
`CDN域名\储存桶名\文件在储存桶内的路径`

毕竟常见的对象储存就那几种，每家的访问域名也就那几个，
对方很容易就可以猜出来对象储存的实际访问域名（Endpoint）
又通过alist得到了，储存桶名
只要想搞事情，就可绕过CDN直接刷储存桶的流量，使用者很容易因此面对天价的流量账单。

原来在设置CDN加速域名后，可以通过CDN的路径重写功能，将文件访问链接设置为
`CDN域名\文件在储存桶内的路径`从而隐藏储存桶的名称。
将储存桶名称设置为超过16位的随机字符串，来防止被猜出来桶名称。

### Suggested solution / 实现思路

1. 建议方案一
在设置CDN加速域名后，将文件访问和下载链接设置为`CDN域名\文件在储存桶内的路径`从而隐藏储存桶的名称
因为如果想暴露储存桶名这个固定值，可在设置CDN加速域名时设置为`CDN域名\储存桶名`的格式。

2. 建议方案二
增加一个设置CDN后是否在路径中插入储存桶名的开关，默认状态为插入储存桶名来保证最大兼容性。

**Comment by Xhofe** [comment]
一般好像可以设置只允许cdn回源吧，直接endpoint+bucket+路径会需要签名。

**Comment by tjsky** [comment]
> 一般好像可以设置只允许cdn回源吧，直接endpoint+bucket+路径会需要签名。

有些没有这功能，比如b2，知道桶名可以直接去源拉取。
 
通过cf的路由规则可以直接实现
自定义域名+路径访问。
访问时是不需要签名的。

**Comment by Xhofe** [comment]
已经增加了 可以试一下： https://github.com/alist-org/alist/actions/runs/4650278347
