### ISSUE TITLE
rclone 挂载webdav 使用onedrive驱动,使用linux move 文件报错 

### ISSUE THREAD

**Issue by linshuboy** [alist-org/alist#4071]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

当前最新的docker

### Driver used / 使用的存储驱动

Onedrive 和 Onedrive APP

### Describe the bug / 问题描述

rclone 挂载webdav 使用onedrive驱动,使用linux move 文件报错,当前文件夹move是没有问题的,跨文件夹move 就会报
![image](https://user-images.githubusercontent.com/20389206/230567946-c006451d-ae6e-4669-8b7a-d5a3625daa9e.png)
这个错误,
../
./
aaaaa/
aaaaa/aaaa.zip
1.运行 move aaaaa/aaaa.zip ./
报错
本地无变化
远程无变化
2.运行 move aaaaa/aaaa.zip ./bbbb.zip
报错
本地变成
../
./
aaaaa/
aaaaa/bbbb.zip
远程无变化
此时数据已经错乱,不得不重新挂载

### Reproduction / 复现链接

无

### Logs / 日志

![image](https://user-images.githubusercontent.com/20389206/230568959-da8eb31b-b6e8-4480-a68d-10f9f7e7e9c6.png)

**Comment by linshuboy** [comment]
怀疑是因为webdav支持的内容不完整或者是因为驱动缺失部分功能,如果是后者可以尝试帮忙修复

**Comment by linshuboy** [comment]
重新测试了一下.好像只有在文件移动回根目录的时候会报错

**Comment by Xhofe** [comment]
请提供alist日志。

**Comment by mengguyi** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
> * [x]  I'm sure I'm using the latest version
> 
> ### Alist Version / Alist 版本
> 当前最新的docker
> 
> ### Driver used / 使用的存储驱动
> Onedrive 和 Onedrive APP
> 
> ### Describe the bug / 问题描述
> rclone 挂载webdav 使用onedrive驱动,使用linux move 文件报错,当前文件夹move是没有问题的,跨文件夹move 就会报

有没有可能alist不支持跨盘move

https://user-images.githubusercontent.com/73788063/230696098-b08a9526-2b5c-4f14-91ef-a2db3dc02eee.mp4



>![image](https://user-images.githubusercontent.com/20389206/230567946-c006451d-ae6e-4669-8b7a-d5a3625daa9e.png) 这个错误, ../ ./ aaaaa/ aaaaa/aaaa.zip 1.运行 move aaaaa/aaaa.zip ./ 报错 本地无变化 远程无变化 2.运行 move aaaaa/aaaa.zip ./bbbb.zip 报错 本地变成 ../ ./ aaaaa/ aaaaa/bbbb.zip 远程无变化 此时数据已经错乱,不得不重新挂载
> 
> ### Reproduction / 复现链接
> 无
> 
> ### Logs / 日志
> ![image](https://user-images.githubusercontent.com/20389206/230568959-da8eb31b-b6e8-4480-a68d-10f9f7e7e9c6.png)

**Comment by Xhofe** [comment]
> > ### Please make sure of the following things
> > * [x]  I have read the [documentation](https://alist.nn.ci).
> > * [x]  I'm sure there are no duplicate issues or discussions.
> > * [x]  I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
> > * [x]  I'm sure I'm using the latest version
> > 
> > ### Alist Version / Alist 版本
> > 当前最新的docker
> > 
> > ### Driver used / 使用的存储驱动
> > Onedrive 和 Onedrive APP
> > 
> > ### Describe the bug / 问题描述
> > rclone 挂载webdav 使用onedrive驱动,使用linux move 文件报错,当前文件夹move是没有问题的,跨文件夹move 就会报
> 
> 有没有可能alist不支持跨盘move
> 
> https://user-images.githubusercontent.com/73788063/230696098-b08a9526-2b5c-4f14-91ef-a2db3dc02eee.mp4
> 
> 
> 
> >![image](https://user-images.githubusercontent.com/20389206/230567946-c006451d-ae6e-4669-8b7a-d5a3625daa9e.png) 这个错误, ../ ./ aaaaa/ aaaaa/aaaa.zip 1.运行 move aaaaa/aaaa.zip ./ 报错 本地无变化 远程无变化 2.运行 move aaaaa/aaaa.zip ./bbbb.zip 报错 本地变成 ../ ./ aaaaa/ aaaaa/bbbb.zip 远程无变化 此时数据已经错乱,不得不重新挂载
> > 
> > ### Reproduction / 复现链接
> > 无
> > 
> > ### Logs / 日志
> > ![image](https://user-images.githubusercontent.com/20389206/230568959-da8eb31b-b6e8-4480-a68d-10f9f7e7e9c6.png)
> 
> 

是不支持的，为避免跨盘移动失败导致文件丢失，所以只支持跨盘复制。

**Comment by linshuboy** [comment]
好像是onedrive 驱动的问题，我尝试改一下
