### ISSUE TITLE
建议储存管理添加分组和导入导出功能

### ISSUE THREAD

**Issue by smanx** [alist-org/alist#4074]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

**Comment by Xhofe** [comment]
你可以使用备份/恢复 实现导入导出。
