### ISSUE TITLE
OneDrive开启Web代理后网页端无法播放的问题

### ISSUE THREAD

**Issue by Winyer** [alist-org/alist#4077]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.15.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

    关于Alist的Web代理，很奇怪的一点是，开始代理后网页端播放时服务器直接没流量走动，然后加载半天后直接加载失败，手机电脑测试都是一样的，然后电脑上点PotPlayer开始播放则会明显的出现流量波动，而手机上点mx player pro播放则会出现无响应也不会跳转到播放器，我尝试复制下载地址到mx去手动播放，也会出现加载失败且服务器无流量中转。

    再次总结下问题，网盘是OneDrive，启用了代理，web端播放视频失败，电脑端唤起PotPlayer播放速度很快很流畅，服务器也有流量通过，但是手机端mx player pro播放器播放时还是一样的加载不了，且服务器无流量通过。

### Reproduction / 复现链接

无

**Comment by Winyer** [comment]
> ### See
> 1. 62% [OneDrive开启Web代理后支持多线程下载 #4014](https://github.com/alist-org/alist/issues/4014)

看过了，不是一个类型，他是反代我是用的alist的代理

**Comment by Winyer** [comment]
补充一条，使用webdev的代理又是正常的

**Comment by Winyer** [comment]
> Hello @Winyer, please input issue by template and add detail. Issues labeled by `question` will be closed if no activities in 7 days. 你好 @Winyer，请按照issue模板填写, 并详细说明问题/日志记录/复现步骤/复现链接/实现思路或提供更多信息等, 7天内未回复issue自动关闭。

你好，我是按照模板写的，请问缺少了哪些东西未填写呢？
Hello, I wrote according to the template, what is missing and not filled in?

**Comment by mengguyi** [comment]
> > Hello @Winyer, please input issue by template and add detail. Issues labeled by `question` will be closed if no activities in 7 days. 你好 @Winyer，请按照issue模板填写, 并详细说明问题/日志记录/复现步骤/复现链接/实现思路或提供更多信息等, 7天内未回复issue自动关闭。
> 
> 你好，我是按照模板写的，请问缺少了哪些东西未填写呢？ Hello, I wrote according to the template, what is missing and not filled in?

问题描述不足以让开发者明白到底出什么问题了，你可以录屏你认为有问题的地方。
像这种不易发现问题的情况应该提供日志以便开发者更好地调试

**Comment by Rektyfikowany** [comment]
加载失败的响应内容是什么，
本地代理的地址是`你的域名/p/挂载路径`，下载页点击下载也会跳转到这个地址，F12网络中看一下请求代理链接时的响应代码（类似HTTP404）以及报错内容

**Comment by Xhofe** [comment]
提供一个复现链接是最好的。

**Comment by Winyer** [comment]
> 加载失败的响应内容是什么， 本地代理的地址是`你的域名/p/挂载路径`，下载页点击下载也会跳转到这个地址，F12网络中看一下请求代理链接时的响应代码（类似HTTP404）以及报错内容

![mmexport1681027081451](https://user-images.githubusercontent.com/19600350/230761275-d62a42ca-6717-4493-8109-c81c297d43d2.png)
![mmexport1681027084724](https://user-images.githubusercontent.com/19600350/230761278-33f1764d-eb9c-4309-a091-aeeb8626cab4.png)
![mmexport1681027098353](https://user-images.githubusercontent.com/19600350/230761281-6e99bec5-d461-444f-926d-35215bbc6e1a.png)
报错和状态码如上，状态码没有

**Comment by Winyer** [comment]
> > > Hello @Winyer, please input issue by template and add detail. Issues labeled by `question` will be closed if no activities in 7 days. 你好 @Winyer，请按照issue模板填写, 并详细说明问题/日志记录/复现步骤/复现链接/实现思路或提供更多信息等, 7天内未回复issue自动关闭。
> > 
> > 
> > 你好，我是按照模板写的，请问缺少了哪些东西未填写呢？ Hello, I wrote according to the template, what is missing and not filled in?
> 
> 问题描述不足以让开发者明白到底出什么问题了，你可以录屏你认为有问题的地方。 像这种不易发现问题的情况应该提供日志以便开发者更好地调试

录屏就是打开代理后手机网页端播放视频一直加载不出来，没多大意义，请问日志在哪个位置呢？我提供下吧

**Comment by Xhofe** [comment]
请提供复现链接。

**Comment by Winyer** [comment]
> 日志位置定义在config.json中，请提供复现链接。

我想重新搭建一个来复现，结果没出现这个问题，经过一晚上的排查，发现，原来是因为启用了宝塔反代5244端口引起的，直接访问5244端口的网站没有这个问题🥴

**Comment by Winyer** [comment]
> Hello @Winyer, your issue is invalid and will be closed. 你好 @Winyer，你的issue无效，将被关闭。

好的谢谢
