### ISSUE TITLE
建议添加多个管理账号

### ISSUE THREAD

**Issue by Dongyanmio** [alist-org/alist#4085]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

就比如说我们有个社区，社区里有多个管理，管理要不定期上线查看社区里其他人上传的文件是否合规
不可能就是每次都登同一个账号去管理，这样也可以提高一点点效率

**Comment by anwen-anyi** [comment]
如果不支持的话 你可以手动去数据库修改一下数据试试看

**Comment by youtehub** [comment]
直接用 Navicat 改数据库角色就可以了哈

**Comment by Dongyanmio** [comment]
> 直接用 Navicat 改数据库角色就可以了哈

看起来会报错，报错信息：Failed find user: record not found

**Comment by anwen-anyi** [comment]
> > 直接用 Navicat 改数据库角色就可以了哈
> 
> 看起来会报错，报错信息：Failed find user: record not found

`role` 改成 2 呢 我这里没问题~
