### ISSUE TITLE
增加视频/音频默认跳转功能

### ISSUE THREAD

**Issue by C63H88CoN14O14P** [alist-org/alist#4089]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

一个小小的建议, 实现打开文件默认跳转播放
非常感谢

### Suggested solution / 实现思路

在设置处增加 "是否默认跳转播放"的选项

**Comment by Xhofe** [comment]
描述不清

**Comment by C63H88CoN14O14P** [comment]
> 
  作者您好, 我的描述确实不太清晰, 我的意思是在使用网页版的alist时预览视频( 在网页版播放而非使用其他播放器webdav )时, 右下角会出现提示如 "上次看到XX:XX 跳转播放", alist已经可以实现记忆播放位置了, 我的请求就是默认实现这个跳转播放, 就像B站一样, 也会提示你上次观看到的位置. 但是B站默认是跳转到记忆的位置(我希望的就是这个效果), 所以我认为可以在alist的设置中加入一个选项让用户决定是否默认跳转.

**Comment by C63H88CoN14O14P** [comment]
> 描述不清

作者您好, 我的描述确实不太清晰, 我的意思是在使用网页版的alist时预览视频( 在网页版播放而非使用其他播放器webdav )时, 右下角会出现提示如 "上次看到XX:XX 跳转播放", alist已经可以实现记忆播放位置了, 我的请求就是默认实现这个跳转播放, 就像B站一样, 也会提示你上次观看到的位置. 但是B站默认是跳转到记忆的位置(我希望的就是这个效果), 所以我认为可以在alist的设置中加入一个选项让用户决定是否默认跳转.
