### ISSUE TITLE
增加外部预览的变量种类

### ISSUE THREAD

**Issue by IFxmp** [alist-org/alist#4090]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

近期使用kkfileview搭建在线预览，发现提供的变量$url: the file url，在挂载阿里网盘时$url地址是https://cn-beijing-data.aliyundrive.net/***的下载地址，导致kkfileview无法预览文档。在挂载本地存储时$url地址是访问的浏览器网址（中间添加/d路径），此时，kkfileview可以预览文档。
对此，建议是否能够新提供一个变量url和base64的url，变量url其值就是访问浏览器的网址（或者中间添加/d路径的地址）

**Comment by Xhofe** [comment]
参加 https://github.com/alist-org/alist-web/blob/cc9661fd0adc686c1678957f34b099eef5b16bdb/src/utils/str.ts#L58

基础变量为$url（https://cn-beijing-data.aliyundrive.net/*** 这种）和$durl（https://al.nn.ci/d/xxx.docx 这种），在基础变量前[eb]_，即是对基础变量做转换，e表示encodeURIComponent，b标识base64。如：
- $e_url: encodeURIComponent($url)
- $b_url: btoa($url)
- $eb_url: encodeURIComponent(btoa($url))
- $e_durl: encodeURIComponent($durl)
- $b_durl: btoa($durl)
- $eb_durl: encodeURIComponent(btoa($durl))

**Comment by AstbReal** [comment]
对接kkfileview时要使用$be_durl而不是$eb_durl
