### ISSUE TITLE
阿里云盘open用不了

### ISSUE THREAD

**Issue by write-live** [alist-org/alist#4092]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

failed get objs: failed to list objs: invalid character '<' looking for beginning of value

### Reproduction / 复现链接

http://127.0.0.1:5244/dav

### Logs / 日志

![image](https://user-images.githubusercontent.com/59868306/230728607-ab6c6fa0-fa4e-4396-aa6b-8768270a04ed.png)

**Comment by wejudging** [comment]
我也是！！！

**Comment by qcjackman** [comment]
+1

**Comment by Panlelaila** [comment]
我也遇到了，而且去获取新的token不能扫码，会直接ERROR，如果是直接登录就一直转圈

**Comment by Hehesheng** [comment]
+1

**Comment by decade20092009** [comment]
me too

**Comment by BetterWorld-Liuser** [comment]
same

**Comment by leebo** [comment]
+1

**Comment by wisinfun** [comment]
+1

**Comment by z-henry** [comment]
+1

**Comment by panghujiajia** [comment]
+1

**Comment by sheek-thrish** [comment]
+1

**Comment by qsxc369** [comment]
+1

**Comment by zhuguozheng** [comment]
+1

**Comment by licher-liu** [comment]
same issue, looking forward to the solution

**Comment by xuhuaq** [comment]
An error occurred: API rate limit exceeded for alist-org/docs. Sign in to increase the rate limit

**Comment by anwen-anyi** [comment]
点击这个围观即可，不用回复 不然所有人都会收到通知
![image](https://user-images.githubusercontent.com/56105412/230729831-252cc059-b544-4787-b846-bfa96ed30767.png)

**Comment by zzwm1396** [comment]
+1

**Comment by KevinAnYuan** [comment]
+1

**Comment by Xhofe** [comment]
由于请求过多，服务器过载导致进程被杀，已重启服务。
