### ISSUE TITLE
关于元信息中的正则表达式不支持断言/预查

### ISSUE THREAD

**Issue by TommyLeung-gj** [alist-org/alist#4094]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.1

### Driver used / 使用的存储驱动

本机硬盘

### Describe the bug / 问题描述

我尝试在某些目录下限定子目录的创建，便使用断言写入元信息对不含关键词语的目录进行了隐藏，然而提示我正则解析是啊比不支持`?!`,
我很确信这是golang的regexp造成的，希望可以将regexp转换为regexp2包的支持以支持复杂的正则。

### Reproduction / 复现链接

...私人连接就不放了吧

**Comment by sjtuross** [comment]
现在很难实现隐藏不包含某关键字的目录

或者能否提供白名单功能，就是指定哪些目录显示，其余都隐藏呢？
