### ISSUE TITLE
Microsoft SSO Redirect URL can't contain query info（microsoft）

### ISSUE THREAD

**Issue by Musicminion** [alist-org/alist#4095]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

单点登录中，回调URL现在微软不允许带有查询字符串(就是类似?aaa=xxx&bbb=yyy)之类的，所以建议修复用参数匹配的机制
例如api/xxx/callback/sso_get_xxx之类的

### Reproduction / 复现链接

回调URL现在微软不允许带有查询字符串(就是类似?aaa=xxx&bbb=yyy)之类的，所以建议修复用参数匹配的机制

**Comment by FW27623** [comment]
注意看官方文档，你选错了应用类型吧https://learn.microsoft.com/zh-cn/azure/active-directory/develop/reply-url
![image](https://user-images.githubusercontent.com/59783568/230852358-c3045be0-249e-46de-b732-1114cea3f410.png)

**Comment by itsHenry35** [comment]
> > 我打算弄个选项允许改回原来的重定向方式，为了更好的兼容性
> 
> 请问现在这个选项在哪，我这里3.42.0版本找不到

![Image](https://github.com/user-attachments/assets/499f9146-859c-411d-8bf0-25376af08912)

**Comment by itsHenry35** [comment]
> > > > 我打算弄个选项允许改回原来的重定向方式，为了更好的兼容性
> > > 
> > > 
> > > 请问现在这个选项在哪，我这里3.42.0版本找不到
> > 
> > 
> > ![Image](https://github.com/user-attachments/assets/499f9146-859c-411d-8bf0-25376af08912)
> 
> 开启兼容模式后登录会报错{"code":400,"message":"error occurred","data":null} 是有哪里没有配置到位吗？

https://alist.nn.ci/zh/guide/advanced/sso.html#%E5%9B%9E%E8%B0%83%E5%8F%82%E6%95%B0-%E9%87%8D%E5%AE%9A%E5%90%91%E9%93%BE%E6%8E%A5

**Comment by itsHenry35** [comment]
> > > > > > 我打算弄个选项允许改回原来的重定向方式，为了更好的兼容性
> > > > > 
> > > > > 
> > > > > 请问现在这个选项在哪，我这里3.42.0版本找不到
> > > > 
> > > > 
> > > > ![Image](https://github.com/user-attachments/assets/499f9146-859c-411d-8bf0-25376af08912)
> > > 
> > > 
> > > 开启兼容模式后登录会报错{"code":400,"message":"error occurred","data":null} 是有哪里没有配置到位吗？
> > 
> > 
> > https://alist.nn.ci/zh/guide/advanced/sso.html#%E5%9B%9E%E8%B0%83%E5%8F%82%E6%95%B0-%E9%87%8D%E5%AE%9A%E5%90%91%E9%93%BE%E6%8E%A5
> 
> 就是看这里的链接，难道需要保留旧的链接吗

你新开个issue吧，附上日志，我回头看看
