### ISSUE TITLE
链接指向错误?

### ISSUE THREAD

**Issue by liyanes** [alist-org/alist#4101]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/30283620/230776989-0c03db82-581c-4992-bfd3-11a0fa067b67.png)
不知道是写错的(以前版本)还是就是不对,链接可以导向该库
更改无异常
图为"由Alist驱动"指向的链接,目前应该是https://github.com/alist-org/alist
如果尊重原作者,建议不要更改,想问问你们(指开发者们)的看法

### Reproduction / 复现链接

如上图

### Logs / 日志

![image](https://user-images.githubusercontent.com/30283620/230777179-71600377-ece3-4092-9b39-4031d9f33856.png)

**Comment by anwen-anyi** [comment]
没问题以前的库就是这个链接

**Comment by mengguyi** [comment]
@Xhofe 不就是作者吗，alist一直是他主持开发的啊
