### ISSUE TITLE
能否支持transmission作为离线下载工具

### ISSUE THREAD

**Issue by skyflying1989** [alist-org/alist#4102]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议新增支持transmission作为离线下载工具，trasmission比qBittorent要稳定些

### Suggested solution / 实现思路

trasmission也有web端接口，实现起来应该和qBittorent差不多

**Comment by ZerOri** [comment]
要怎么设置啊，谁发个教程

**Comment by TPAXcc** [comment]
> 要怎么设置啊，谁发个教程

+1
```Windows
Failed get transmission version: can't get session values: 'session-get' rpc method failed: can't unmarshal request answer body: json: cannot unmarshal number 100.0 into Go struct field answerPayload.arguments.RawSessionArguments.speed-limit-down of type int64
```
