### ISSUE TITLE
建议添加uc网盘分享

### ISSUE THREAD

**Issue by njpengqc** [alist-org/alist#4104]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

uc网盘分享下载不限速
打开分享链接后高速下载

### Suggested solution / 实现思路

官方网站：
https://fast.uc.cn/

### Additional context / 附件

![image](https://user-images.githubusercontent.com/87556536/230836898-1cf0c9aa-af30-433e-9f61-e65fab68b261.png)

**Comment by kdaye** [comment]
Please support UC Drive with alist!

**Comment by Bashir-1** [comment]
强烈支持！！！

**Comment by zqxiaojin** [comment]
https://github.com/alist-org/alist/pull/4459

这个提交支持UC网盘

**Comment by ypq123456789** [comment]
> #4459
> 
> 这个提交支持UC网盘

大佬，这个只支持挂载自己的uc网盘，能否挂载别人的uc网盘分享啊？
