### ISSUE TITLE
启用/关闭签名错误

### ISSUE THREAD

**Issue by yys5014** [alist-org/alist#4107]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.1

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

添加存储，此处的“启用签名”并未打开
![QQ截图20230410145201](https://user-images.githubusercontent.com/104966479/230844854-f64bdb3f-17c3-4c6e-880d-e4f5e0380757.png)
在复制链接中，https://*?sign=mpXxBx8VlziHy5NgbelJqh06F5WaV6DDfqOl9h3nEu4=:0，仍然存在sign

### Reproduction / 复现链接

eg:
![QQ截图20230410145201](https://user-images.githubusercontent.com/104966479/230845275-d413ee43-6690-47fd-9b36-14b987d1d47b.png)
https://share.yyycontrol.top/d/%E5%93%95%E5%93%95%E5%90%96%E4%B8%93%E5%B1%9E/%E6%9D%8E%E8%B7%B3%E8%B7%B3%E4%BF%9D%E6%B4%BB%E6%A8%A1%E5%9D%97/%E6%9D%8E%E8%B7%B3%E8%B7%B32.2%E6%97%A0%E9%9A%9C%E7%A2%8D%E4%BF%9D%E6%B4%BBv2.5(230410).zip?sign=mpXxBx8VlziHy5NgbelJqh06F5WaV6DDfqOl9h3nEu4=:0

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/config/global.html#%E7%AD%BE%E5%90%8D%E6%89%80%E6%9C%89

**Comment by yys5014** [comment]
我已经关闭，且关闭无效

**Comment by lbg2008** [comment]
全局中关闭了签名所有，但是我依然也有这个问题。

**Comment by Everlasting16108** [comment]
同样出现该问题。关闭了全部的签名，在获取图片链接时还是会自带
