### ISSUE TITLE
在 Webdav 挂载 Sharepoint 时支持 Cookie 认证

### ISSUE THREAD

**Issue by lyc8503** [alist-org/alist#4111]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

某些组织的世纪互联 Onedrive 不仅没有 API 权限, 还使用了组织的 SSO 登录, 无法得到用户名和密码.

![image](https://user-images.githubusercontent.com/36782264/231069601-d14208e3-5726-4d18-be8f-c93f6456eadb.png)

如果 Webdav 挂载时可以添加一个可选的 Cookie 认证方式, 让用户自己填入抓包的 Cookie (主要是 `FedAuth` 和 `rtFA` 这两个值), 这种 Onedrive 也能被正确挂载. (尝试使用 Nginx 反向代理手动添加 Cookie, 发现是可行的.)

### Suggested solution / 实现思路

原本获取 Cookie 的代码在 https://github.com/alist-org/alist/blob/main/drivers/webdav/odrvcookie/cookie.go

在前端界面加入一个可选的 Cookie 输入框, 在后端如果读取到 Cookie 则跳过登录, 直接使用现有的 Cookie.

**Comment by zanilia1016** [comment]
填入抓包的 Cookie, 确实可以正确挂载世纪互联 OneDrive，但cookie容易过期失效吧

**Comment by lyc8503** [comment]
是的，我也发现了这个问题，我现在正在使用 rclone 挂载，使用 Python 脚本定期更新 Cookie，可以正常使用

**Comment by zanilia1016** [comment]
怎么更新cookie，是不是需要重新登录

**Comment by lyc8503** [comment]
重新访问一次 Onedrive 的登录页面，会自动跳转到组织 SSO，如果组织 SSO 能记住登录的话，就能自动跳转回 Onedrive，就刷新了 Onedrive 的 Cookie

**Comment by lyc8503** [comment]
使用 rclone 作为后端可配置 cookie 认证, 需要自己根据 SSO 登录逻辑写代码更新 cookie
