### ISSUE TITLE
实现类似OneDrive的拖拽移动

### ISSUE THREAD

**Issue by ZsOg** [alist-org/alist#4119]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

实现类似OneDrive的拖拽移动

**Comment by Masterlovsky** [comment]
同求，感觉现在的移动文件很不方便，希望能支持拖拽移动

**Comment by woshichenghaibo** [comment]
你还真把它当网盘用了

**Comment by ZsOg** [comment]
> 你还真把它当网盘用了

即使没，但现在移动文件很不方便

**Comment by Masterlovsky** [comment]
> 

举个例子，我想把这个文件移动到当前文件夹之外。现在点击移动之后我要从根目录开始一级一级找到当前的目录的上级目录才能移动。这个操作很费时间
