### ISSUE TITLE
alist添加存储webdav形式，策略能否添加302重定向

### ISSUE THREAD

**Issue by sglkmh** [alist-org/alist#4121]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我在alist中通过webdav形式挂载了小雅的alist，但是流量走的是我的服务器的带宽，我在nplayer、tvbox同样以webdav形式挂载小雅的alist，可以走阿里云的带宽，播放很流畅。

### Suggested solution / 实现思路

作者能否优化下webdav策略，使用302重定向一类的思路，使挂载不使用服务器的流量，万分感谢

**Comment by Xhofe** [comment]
不能。

**Comment by LeenHawk** [comment]
你直接ngnix挂小雅的不就行了吗。。。
