### ISSUE TITLE
调用/api/fs/form接口上传文件成功，进入阿里网盘看确实上传成功了，但是调用/api/fs/list返回的文件列表里却没有上传的这个文件

### ISSUE THREAD

**Issue by dary123** [alist-org/alist#4123]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.1

### Driver used / 使用的存储驱动

阿里云盘OPEN

### Describe the bug / 问题描述

调用/api/fs/form接口上传文件成功，进入阿里网盘看确实上传成功了，但是调用/api/fs/list返回的文件列表里却没有上传的这个文件，请问是因为缓存原因导致的么，那么如何刷新缓存

### Reproduction / 复现链接

我的域名/api/fs/list，域名不方便提供，还请谅解

### Logs / 日志

上传返回，{
	"code": 200,
	"message": "success",
	"data": null
}，
获取文件列表返回
{
	"code": 200,
	"message": "success",
	"data": {
		"content": null,
		"total": 0,
		"readme": "",
		"write": true,
		"provider": "Quark"
	}
}

**Comment by Xhofe** [comment]
Please go to our discussion forum for general questions, issues are for bug reports and feature request only.
