### ISSUE TITLE
webdav驱动挂载无法删除文件夹

### ISSUE THREAD

**Issue by guangguailulu** [alist-org/alist#4126]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.1

### Driver used / 使用的存储驱动

WebDav

### Describe the bug / 问题描述

使用webdav挂载的[某网盘](https://infini-cloud.net/)删除普通文件正常，但无法正常删除文件夹（提示success，点击刷新文件夹仍然在并没有被删除）。经测试坚果云未发现此问题，我起初怀疑是这个网盘的bug，可能删除文件夹的权限未给全，但是我更换webdav软件（es文件管理器）后发现可以正常删除文件夹。所以这大概是alist的bug。
！我是指webdav驱动，并非通过webdav访问alist这个功能！

### Reproduction / 复现链接

出现问题的网盘：https://infini-cloud.net/
它支持webdav，就用的webdav驱动直接挂载的

**Comment by internetic** [comment]
3.16.0复现,同一个网盘

**Comment by Xhofe** [comment]
这应该已经在https://github.com/alist-org/alist/commit/ee4ac81677b26d2b43e351476f14b1e630f47192 被修复。
