### ISSUE TITLE
建议增加linkbox网盘挂载和分享挂载

### ISSUE THREAD

**Issue by playingapi** [alist-org/alist#4130]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议增加对[linkbox](https://www.linkbox.to/)网盘的支持

**Comment by tuthanika** [comment]
建议增加linkbox
