### ISSUE TITLE
gb2312编码的txt预览时显示乱码

### ISSUE THREAD

**Issue by haoduck** [alist-org/alist#4131]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

markdown在线预览的功能好像默认用utf-8打开txt文件？就是gb2312编码的文件预览的时候是乱码的，有办法解决吗？

**Comment by Xhofe** [comment]
不支持 也不准备支持 但是如果有人愿意pr欢迎
