### ISSUE TITLE
夸克网盘频繁出现write: broken pipe 错误

### ISSUE THREAD

**Issue by JingenChen** [alist-org/alist#4135]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.1

### Driver used / 使用的存储驱动

夸克网盘

### Describe the bug / 问题描述

夸克网盘webdav访问频繁出现一下错误：
ERRO[2023-04-13 02:23:08] GET /dav/Quark149/电视/灌篮高手/灌篮高手.1080P.国粤日三语.软字幕.AVC.默认国语音频.083.mkv write tcp 172.17.0.3:5244->192.168.2.1:39908: write: broken pipe 

### Reproduction / 复现链接

N/A

### Logs / 日志

ERRO[2023-04-13 02:23:07] GET /dav/Quark149/电视/灌篮高手/灌篮高手.1080P.国粤日三语.软字幕.AVC.默认国语音频.083.mkv write tcp 172.17.0.3:5244->192.168.2.1:39892: write: broken pipe 
[GIN] 2023/04/13 - 02:23:07 | 206 |  682.864191ms |     192.168.2.1 | GET      "/dav/Quark149/电视/灌篮高手/灌篮高手.1080P.国粤日三语.软字幕.AVC.默认国语音频.083.mkv"
[GIN] 2023/04/13 - 02:23:07 | 206 |    163.9081ms |     192.168.2.1 | GET      "/dav/Quark149/电视/灌篮高手/灌篮高手.1080P.国粤日三语.软字幕.AVC.默认国语音频.083.mkv"
[GIN] 2023/04/13 - 02:23:08 | 206 |  112.102839ms |     192.168.2.1 | GET      "/dav/Quark149/电视/灌篮高手/灌篮高手.1080P.国粤日三语.软字幕.AVC.默认国语音频.083.mkv"
ERRO[2023-04-13 02:23:08] GET /dav/Quark149/电视/灌篮高手/灌篮高手.1080P.国粤日三语.软字幕.AVC.默认国语音频.083.mkv write tcp 172.17.0.3:5244->192.168.2.1:39908: write: broken pipe 
[GIN] 2023/04/13 - 02:23:08 | 206 |  334.951062ms |     192.168.2.1 | GET      "/dav/Quark149/电视/灌篮高手/灌篮高手.1080P.国粤日三语.软字幕.AVC.默认国语音频.083.mkv"
[GIN] 2023/04/13 - 02:23:08 | 207 |     880.274µs |     192.168.2.1 | PROPFIND  "/dav/"
ERRO[2023-04-13 02:23:09] GET /dav/Quark149/电视/灌篮高手/灌篮高手.1080P.国粤日三语.软字幕.AVC.默认国语音频.083.mkv write tcp 172.17.0.3:5244->192.168.2.1:39910: write: broken pipe 
[GIN] 2023/04/13 - 02:23:09 | 206 |  1.138675576s |     192.168.2.1 | GET      "/dav/Quark149/电视/灌篮高手/灌篮高手.1080P.国粤日三语.软字幕.AVC.默认国语音频.083.mkv"

**Comment by Xhofe** [comment]
https://juejin.cn/post/7114818240731152397
