### ISSUE TITLE
upload failed to WebDAV

### ISSUE THREAD

**Issue by dzz10** [alist-org/alist#4136]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.1

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

用RaiDrive挂载后，用golang写个程序往里面写数据，会报错。
upload failed to WebDAV
WinErrorCode:5
NotifyErrorCode:204

同理测试了阿里云盘open，可行。

测试代码如下：
err := os.WriteFile("Z:/qy/999.txt", []byte("中文咯"), os.ModePerm)
if err != nil {
    fmt.Println(err)
}

### Reproduction / 复现链接

http://nourl.com

### Logs / 日志

[2023-04-13 14:14:12] PUT /dav/qy/999.txt EmptyStaticCreds: static credentials are empty
github.com/alist-org/alist/v3/internal/op.Put
	/source/internal/op/fs.go:569
github.com/alist-org/alist/v3/internal/fs.putDirectly
	/source/internal/fs/put.go:54
github.com/alist-org/alist/v3/internal/fs.PutDirectly
	/source/internal/fs/fs.go:84
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePut
	/source/server/webdav/webdav.go:328
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/source/server/webdav/webdav.go:62
github.com/alist-org/alist/v3/server.ServeWebDAV
	/source/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/source/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1995
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598 
[GIN] 2023/04/13 - 14:14:12 | 405 |   11.3145095s |       127.0.0.1 | PUT      "/dav/qy/999.txt"

**Comment by dzz10** [comment]
我没找到和我一样错误的呢

**Comment by Xhofe** [comment]
- #4046 
- #4038
