### ISSUE TITLE
增加网盘各种文件类型的在线浏览

### ISSUE THREAD

**Issue by playingapi** [alist-org/alist#4137]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

对更多文件的在线预览  如对压缩文件在线浏览, 不用下载到本地

### Suggested solution / 实现思路

https://github.com/kekingcn/kkFileView

**Comment by Xhofe** [comment]
Implement it yourself by [iframe-previews](https://alist.nn.ci/config/preview.html#iframe-previews)
