### ISSUE TITLE
[夸克]挂载后无法播放视频，下午突然出现

### ISSUE THREAD

**Issue by Goooooooooood** [alist-org/alist#4140]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.1

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

夸克挂载后无法播放视频，无论是使用网页还是手机或电脑播放器。

可以正常浏览挂载的目录，网盘里的.txt ,.pdf均能正常浏览。

使用nplayer播放视频时，出现错误提示“Internal Server Error (500)”。

尝试在alist后台删除挂载的驱动，重新添加挂载，没有任何作用。

### Reproduction / 复现链接

![51C4DA71-3200-4583-9D17-4C2CED773BD1](https://user-images.githubusercontent.com/90984890/231751221-af883fe7-c0ec-4012-b350-9112da188db0.png)
![F99331EE-913B-4BB2-9E2C-B1D85BAA5ECF](https://user-images.githubusercontent.com/90984890/231751459-9e6a35f6-65ba-47c9-9a7a-84363808b512.jpeg)

**Comment by Bridge97** [comment]
刚刚遇到相同的问题，看来不是个例.

**Comment by Goooooooooood** [comment]
> 刚刚遇到相同的问题，看来不是个例.

我在电报群里问了，没人理我，才来这里提交问题的。🥹

**Comment by sammymsn** [comment]
同样的问题，希望得到解决，感谢。

**Comment by Xhofe** [comment]
Quark限制了web端文件下载的大小，强制使用客户端，因此此API目前对较大文件已无法下载 **download file size limit**。

需要抓包客户端的API，如果有人知道客户端的下载API可以在这里提供。

**Comment by foxxorcat** [comment]
验证了User-Agent ,请求时添上
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) quark-cloud-drive/2.5.20 Chrome/100.0.4896.160 Electron/18.3.5.4-b478491100 Safari/537.36 Channel/pckk_other_ch"
就行了

**Comment by ata5028** [comment]
> 验证了User-Agent ,请求时添上 "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) quark-cloud-drive/2.5.20 Chrome/100.0.4896.160 Electron/18.3.5.4-b478491100 Safari/537.36 Channel/pckk_other_ch" 就行了

不行

**Comment by llonline** [comment]
明显用夸克的人很少。上次阿里寄的时候，各个群呼天喊地。这次夸克出问题，基本没人关注。

**Comment by anwen-anyi** [comment]
> 明显用夸克的人很少。上次阿里寄的时候，各个群呼天喊地。这次夸克出问题，基本没人关注。

使用起来没那么方便（默认是本地代理 嘿嘿~这个限制就挺麻烦的），资源也就那样吧

**Comment by wolfit50** [comment]
> 

因为是本地代理，不是302，自己改浏览器UA显然没用

**Comment by Xhofe** [comment]
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) quark-cloud-drive/2.5.20 Chrome/100.0.4896.160 Electron/18.3.5.4-b478491100 Safari/537.36 Channel/pckk_other_ch

OK

**Comment by LuckyTain** [comment]
> Quark限制了web端文件下载的大小，强制使用客户端，因此此API目前对较大文件已无法下载 **download file size limit**。
> 
> 需要抓包客户端的API，如果有人知道客户端的下载API可以在这里提供。

Yes, I got this error.

```
{
  "code": 500,
  "message": "failed link: failed get link: download file size limit[558562d5fce54dfd***********]",
  "data": null
}
```

**Comment by sammymsn** [comment]
就关闭了么？解决了么？

**Comment by niubilityxiesong** [comment]
> 验证了User-Agent ,请求时添上 "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) quark-cloud-drive/2.5.20 Chrome/100.0.4896.160 Electron/18.3.5.4-b478491100 Safari/537.36 Channel/pckk_other_ch" 就行了

不行 我试了

**Comment by llonline** [comment]
> 

阿里和谐的夸克没问题。还能做下载器，唯一优点了。

**Comment by mashirozx** [comment]
> > 就关闭了么？解决了么？
> 
> 我看到作者已经修改了代码了，现目前的alist版本应该是无法解决了，要等最新的release包，更新一下版本应该就可以了

试了一下main分支的代码，还是一样的报错啊

**Comment by mashirozx** [comment]
> > > 就关闭了么？解决了么？
> > 
> > 
> > 我看到作者已经修改了代码了，现目前的alist版本应该是无法解决了，要等最新的release包，更新一下版本应该就可以了
> 
> 试了一下main分支的代码，还是一样的报错啊

啊，可以了，原来是要刷新一下，感谢作者大佬

**Comment by mashirozx** [comment]
但是这样处理大文件会因为超时被自动断开（大概一个小时），或许需要断点续传支持
![Screenshot_2023-04-14-19-15-06-968_com kiwibrowser browser](https://user-images.githubusercontent.com/16148054/232030156-480e9733-3da0-41aa-9204-8587a3513669.jpg)

**Comment by sammymsn** [comment]
已经安装了新版3.16.0,但播放视频仍然不行，5秒后就卡了。估计要等3.16.1了。

**Comment by Goooooooooood** [comment]
> 已经安装了新版3.16.0,但播放视频仍然不行，5秒后就卡了。估计要等3.16.1了。

我用nplayer连接alist的webdav播放时，会出现同样问题。

但如果将webdav挂载为本地磁盘，然后通过nplayer和emby播放，均正常。

**Comment by wales01** [comment]
我播放少于40分钟的视频可以，大于四十分钟就不行了
