### ISSUE TITLE
上传文件到 123盘  又炸了

### ISSUE THREAD

**Issue by hais1992** [alist-org/alist#4141]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

 46f9aef

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

上传文件提示：
`{"code":500,"message":"EmptyStaticCreds: static credentials are empty","data":null}`

经排查好像是跟下面这接口不返回key、token有关？

![PC0T 70 VXTXEL7S5T67WM](https://user-images.githubusercontent.com/91512491/231777718-fc751fcd-f193-41be-a459-fb73baf87894.png)

### Reproduction / 复现链接

。

**Comment by imshuai** [comment]
最新版本：`v1.15.1`  
`rclone move`在传输完成后报错`405 Method Not Allowed`  
curl调用api直接上传和alist目录间的复制都报错`{"code":500,"message":"EmptyStaticCreds: static credentials are empty","data":null}`
