### ISSUE TITLE
部分视频没有声音

### ISSUE THREAD

**Issue by tnnevol** [alist-org/alist#4142]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.1

### Driver used / 使用的存储驱动

smb、阿里云等

### Describe the bug / 问题描述

客户端： 浏览器环境 chrome 版本 112.0.5615.49（正式版本） (arm64)
操作系统：macos 13.3.1
现象
部分视频无法播放声音，mkv比较多，也存在mp4视频无法播放声音

### Reproduction / 复现链接

magnet:?xt=urn:btih:3349cd1f141b7f516c56bf9efd210c3d17693325&dn=Tetris.2023.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-DVSUX&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2820%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2830%2Fannounce

### Logs / 日志

![image](https://user-images.githubusercontent.com/28475939/231784175-a1c006c6-5b11-4760-8ef1-874af62bc247.png)

**Comment by seryte** [comment]
issue为啥无效，我也有同样的问题！

**Comment by mengguyi** [comment]
> 

这个问题与alist无关所以issue无效
