### ISSUE TITLE
本地文件夹无法打开  failed get objs: failed to list objs: open /mnt/data/downloads: no such file or directory

### ISSUE THREAD

**Issue by dcshow** [alist-org/alist#4144]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

我用的unraid装了alist，之前使用一直没问题，突然有一天本地文件夹就无法打开了，配置也没有去动过
![image](https://user-images.githubusercontent.com/53973596/231798123-3b4a9815-2d57-47c8-9799-ae50bca7c67b.png)

### Reproduction / 复现链接

 failed get objs: failed to list objs: open /mnt/data/downloads: no such file or directory

**Comment by Xhofe** [comment]
文件夹不存在。
