### ISSUE TITLE
webdav上传文件有内存泄漏

### ISSUE THREAD

**Issue by 91520** [alist-org/alist#4149]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.15.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

115 挂载后 使用webdav同步上传大量文件，内存会无限增加

### Reproduction / 复现链接

115 挂载后 使用webdav同步上传大量文件，内存会无限增加

**Comment by Xhofe** [comment]
deps: github.com/SheltonZhu/115driver

**Comment by sunzqe** [comment]
同样问题我也遇到，使用阿里云盘同步视频到webdav，docker容器内存飙升到8Gb，然后容器重启

**Comment by yurhett** [comment]
Same issue.
