### ISSUE TITLE
针对PDF、Word等主流文件格式的加密与在线查看支持

### ISSUE THREAD

**Issue by thinkmore123x** [alist-org/alist#4152]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

昨天在逛帖子的时候，翻到一个老的话题，才发现居然在线加密播放是大家不知道的，而且看样子还很需要，所以分享了一下，一个免费的小工具，用起来很爽。但分享完，在和原题主的交流中，经他指出只有视频加密在线播放，没有对其他文件的加密支持，是个短板。事实上，我的确也有很多小说和私人文件也想实现类似加密视频那样的阅读效果，那怕让我提前转格式为pdf或者Word什么的也可以，只要能实现在线加密阅读就行。以前，我有一套加密阅读的方法，是采用Joplin来实现的，这里我也顺便分享下，不过看起来太过繁琐，思路是：云盘——>Alist——>webdav——>joplin——>PC客户端+手机App，加密效果有了，但是Joplin的图片资源组织乱得一笔。所以萌生了一个念头，想问群里的高手们，是否有可能在没源码的情况下，给那小工具加上其他文件格式的加密支持？但后来自己也觉得不现实，所以，还不如作为Alist的一种功能特性提出，看看Alist的大神们是否可以加上，这对于注重云盘隐私的用户还是挺重要的。相关讨论地址：https://github.com/alist-org/alist/issues/3846#issuecomment-1506552132

### Suggested solution / 实现思路

我前面所描述的基于Jolin的流程思路，不知是否有用，感觉问题在于加密的时间点（上传时？）、解密的时间点（预览时？）和密钥的生成与存储上（同目录结构下？）

**Comment by traceless** [comment]
所以我建议你看看alist-encrypt 是否满足你的需求。有演示的效果，就是上传的时候进行加密，在线播放的时候就进行解密。不过PDF 和word都有问题，技术可以解决，需要点时间。其他的 图片，文本，视频都是可以在线播放和查看的。也支持文件名字加密。你可以尝试去了解下这个 应用插件，看看能否满足你的需求。

**Comment by thinkmore123x** [comment]
视频加密和在线播放，那款小工具已经满足我需求了，我现在希望能在pdf和word这类文件上，也可以有加密和在线支持，按你说的那个项目有望技术解决，暂时还有些问题，那我就保持关注，谢谢告知！

**Comment by traceless** [comment]
> 视频加密和在线播放，那款小工具已经满足我需求了，我现在希望能在pdf和word这类文件上，也可以有加密和在线支持，按你说的那个项目有望技术解决，暂时还有些问题，那我就保持关注，谢谢告知！

在网页无法在线观看PDF，word，需要你的部署的encrypt 服务支持域名访问 才可以观看。如果是webdav上看的话，就可以直接看到PDF，和word

**Comment by youtehub** [comment]
有一种间接的方法，还是使用 alist-encrypt,就是先使用 alist 挂载一个本地目录，然后  alist-encrypt 挂载这个本地目录，实现在本地加密文件，然后上传到网盘，应该就能实现加密访问了，这样做的好处就是可以直接使用网盘客户端上传文件

**Comment by traceless** [comment]
> 有一种间接的方法，还是使用 alist-encrypt,就是先使用 alist 挂载一个本地目录，然后 alist-encrypt 挂载这个本地目录，远程网盘也使用 alist-encrypt 加密，使用相同的密码，然后上传到这个目录下，实现在本地加密文件，然后上传到网盘，应该就能实现加密访问了，这样做的好处就是可以直接使用网盘客户端上传文件

额，这个encrypt本身就支持 使用命令方式 加密本地文件夹文件的。而且也可以在网页上进行对本地文件夹 进行加密的。适合前期批量的把文件一次性加密，然后通过  云盘客户端上传到云盘
