### ISSUE TITLE
qbittorrent非admin用户无法添加离线下载

### ISSUE THREAD

**Issue by QYQSDTC** [alist-org/alist#4153]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.15.1

### Driver used / 使用的存储驱动

AliyunOpen

### Describe the bug / 问题描述

创建一个General用户，给予添加离线下载权限，但是用该账户登陆后无法用qbittorrent添加离线任务，提示permission denied。
<img width="692" alt="CleanShot-CorBdKIB@2x" src="https://user-images.githubusercontent.com/15608306/231960545-ab3d46e7-1406-4188-bd71-b3fd649e73cf.png">
<img width="476" alt="CleanShot-qoaAtz6t@2x" src="https://user-images.githubusercontent.com/15608306/231960553-0b5eefe9-00a8-4da1-a5c3-94cca21ab746.png">
<img width="929" alt="CleanShot-LkZR9uuF@2x" src="https://user-images.githubusercontent.com/15608306/231960566-b4f8bdf2-ab43-46f9-a24c-20227fda1332.png">

### Reproduction / 复现链接

随便创建一个有离线下载权限的general用户，然后用其添加qbittorrent离线任务

**Comment by sigvoid** [comment]
看了下qb的permission denied，检查权限用CanAddQbittorrentTasks()
```
func AddQbittorrent(c *gin.Context) {
	user := c.MustGet("user").(*model.User)
	if !user.CanAddQbittorrentTasks() {
		common.ErrorStrResp(c, "permission denied", 403)
		return
	}
```
它查是权限值的第10位
```
func (u User) CanAddQbittorrentTasks() bool {
	return u.IsAdmin() || (u.Permission>>10)&1 == 1
}
```
而设置里勾上离线下载权限，实际上是第2位，aria2权限
![image](https://user-images.githubusercontent.com/19713973/232833640-caa49a38-3801-4f9d-8aba-e30c2512026c.png)
```
func (u User) CanAddAria2Tasks() bool {
	return u.IsAdmin() || (u.Permission>>2)&1 == 1
}
```

所以如果你急着用的话，要把第10位加上。
你可以用F12手动抓一个request改一下permission发过去，像这样
![image](https://user-images.githubusercontent.com/19713973/232834861-415835c5-27ca-40ce-9a7c-8d2b411c9c80.png)
这里是1028而不是1024，是因为第2位也是需要的，否则界面不会显示小磁铁图标

**Comment by QYQSDTC** [comment]
> 看了下qb的permission denied，检查权限用CanAddQbittorrentTasks()
> 
> ```
> func AddQbittorrent(c *gin.Context) {
> 	user := c.MustGet("user").(*model.User)
> 	if !user.CanAddQbittorrentTasks() {
> 		common.ErrorStrResp(c, "permission denied", 403)
> 		return
> 	}
> ```
> 
> 它查是权限值的第10位
> 
> ```
> func (u User) CanAddQbittorrentTasks() bool {
> 	return u.IsAdmin() || (u.Permission>>10)&1 == 1
> }
> ```
> 
> 而设置里勾上离线下载权限，实际上是第2位，aria2权限 ![image](https://user-images.githubusercontent.com/19713973/232833640-caa49a38-3801-4f9d-8aba-e30c2512026c.png)
> 
> ```
> func (u User) CanAddAria2Tasks() bool {
> 	return u.IsAdmin() || (u.Permission>>2)&1 == 1
> }
> ```
> 
> 所以如果你急着用的话，要把第10位加上。 你可以用F12手动抓一个request改一下permission发过去，像这样 ![image](https://user-images.githubusercontent.com/19713973/232834861-415835c5-27ca-40ce-9a7c-8d2b411c9c80.png) 这里是1028而不是1024，是因为第2位也是需要的，否则界面不会显示小磁铁图标
> 
> 然后就可以添加qbt任务了 ![image](https://user-images.githubusercontent.com/19713973/232835986-9d0ea001-205a-4994-81f4-0aed489906a1.png)

谢谢大佬
