### ISSUE TITLE
oid无端消耗

### ISSUE THREAD

**Issue by Mayuqi-crypto** [alist-org/alist#4157]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.6.0 desktop

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

什么东西，我的surface pro每换一次外接显示器就让我输入key, 50块钱白白浪费了

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
请通过面包多私信。
