### ISSUE TITLE
alist视频调用播放器时，个别文件名可能导致调用失败

### ISSUE THREAD

**Issue by SlackGPT** [alist-org/alist#4159]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.16.0

### Driver used / 使用的存储驱动

阿里云open

### Describe the bug / 问题描述

alist视频调用播放器时，个别文件名可能导致调用失败，目前测试过程中，文件名存在空格，日文，韩文时调用播放器都是失败的

### Reproduction / 复现链接

完美 世界.mp4，우주소녀 다원.mp4，まった私.mp4    请使用这些文件名进行测试

**Comment by SlackGPT** [comment]
https://user-images.githubusercontent.com/54522645/232182294-f594111d-6acf-4adf-b695-61f823085ff7.mp4

**Comment by SlackGPT** [comment]
文件名中含有空格，如视频中所示，外部播放器不能调用成功，去掉空格后可以调用

**Comment by Xhofe** [comment]
特定的链接变量只适用于特定的播放器，请自行查看提供的变量以适配。

**Comment by SlackGPT** [comment]
文件名包含日文，韩文，也是相同的情况，外部播放器不能成功打开
