### ISSUE TITLE
希望能够视频下方能够自定义外部播放器

### ISSUE THREAD

**Issue by SlackGPT** [alist-org/alist#4160]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我本地使用的播放器是mpv，希望能够加到视频下方进行外部调用

### Suggested solution / 实现思路

和其他播放器一样mpv://视频链接

**Comment by Xhofe** [comment]
https://alist.nn.ci/config/preview.html#external-previews

**Comment by Asukaaaaaa** [comment]
在视频的页面选择download，然后点复制链接，然后命令行输入 `mpv.exe <你复制的链接>` 就能播放了
