### ISSUE TITLE
从地址树中复制文件到ONEDRIVEAPP时应用退出

### ISSUE THREAD

**Issue by zunao1024** [alist-org/alist#4163]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.0

### Driver used / 使用的存储驱动

地址树、OnedriveAPP

### Describe the bug / 问题描述

当从地址树里复制文件到Onedrive存储时，应用会直接退出

### Reproduction / 复现链接

Onedrive账号类型：Microsoft365 E5
地址树目录结构:
Url:
  AndroidGSI:
    13:
      https://dl.google.com/developers/android/tm/images/gsi/gsi_gms_arm64-exp-T1B1.220819.006-9012527-0b3ddd9e.zip
      https://dl.google.com/developers/android/tm/images/gsi/aosp_arm64-exp-T1B1.220819.006-9012527-bb83c478.zip
      https://dl.google.com/developers/android/tm/images/gsi/gsi_gms_x86_64-exp-T1B1.220819.006-9012527-3899de5e.zip
      https://dl.google.com/developers/android/tm/images/gsi/aosp_x86_64-exp-T1B1.220819.006-9012527-3a7b91f3.zip

### Logs / 日志

github.com/alist-org/alist/v3/internal/op.Get
	/home/runner/work/alist/alist/internal/op/fs.go:220
github.com/alist-org/alist/v3/internal/op.GetUnwrap
	/home/runner/work/alist/alist/internal/op/fs.go:224
github.com/alist-org/alist/v3/internal/op.List
	/home/runner/work/alist/alist/internal/op/fs.go:109
github.com/alist-org/alist/v3/internal/op.Get
	/home/runner/work/alist/alist/internal/op/fs.go:210
github.com/alist-org/alist/v3/internal/fs.get
	/home/runner/work/alist/alist/internal/fs/get.go:38
github.com/alist-org/alist/v3/internal/fs.Get
	/home/runner/work/alist/alist/internal/fs/fs.go:37
github.com/alist-org/alist/v3/server/handles.FsGet
	/home/runner/work/alist/alist/server/handles/fsread.go:250
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/runner/work/alist/alist/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.20.3/x64/src/net/http/server.go:2936
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.20.3/x64/src/net/http/server.go:1995
runtime.goexit
	/opt/hostedtoolcache/go/1.20.3/x64/src/runtime/asm_amd64.s:1598
failed get dir
failed get parent list

**Comment by Xhofe** [comment]
请给出panic日志。带有结构的文本请使用```包裹
