### ISSUE TITLE
夸克网盘视频播放被限速

### ISSUE THREAD

**Issue by the-404** [alist-org/alist#4166]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.0

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

   基于昨天修复夸克问题后，昨天测试时候，发现夸克限制了速度。大小为100k/s。我尝试在macOS的夸克客户端抓包分析接口，无法分析出下载地址的请求，但是可以看到/1/clouddrive/file/download请求获取的下载路径。通过添加cookies信息，ua信息都被限制为100kb/s。
   通过分析手机客户端请求，发现其会携带的http头有'Range: bytes=41925931-62411691'信息。将请求转成curl执行下载可达到30m/s的速度。如果删除range头 速度为100k/s

### Reproduction / 复现链接

下图为使用curl方式通过alist下载夸克视频
<img width="800" alt="WechatIMG176" src="https://user-images.githubusercontent.com/5340063/232237601-fa6fd838-cbf9-439e-9675-f308816f21e1.png">

### Logs / 日志

下图分别为带range头和不带的下载速度区别
![WX20230416-003034@2x](https://user-images.githubusercontent.com/5340063/232238097-70ef0890-4020-48a0-bda6-cded014a3af3.png)

**Comment by sammymsn** [comment]
厉害，能提出这种问题的人，一定是可以给出解决方案的人。

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/232279123-400fc442-5b64-4776-876c-70d24d8b1394.png)
我这里测试似乎加了range也限速。

**Comment by wolfit50** [comment]
![image](https://user-images.githubusercontent.com/4847638/232289244-6dfb49ea-7a6a-4ae6-b7f3-438dad1e260e.png)
加了range确实有效

**Comment by ASQ301** [comment]
请问现在解决了嘛 群里有人说是因为受限打开方式的问题 如果挂载成本地磁盘就和以前一样的速度了  我现在是下载有速度 但是在线播放和webdav播放是完全没速度

**Comment by ASQ301** [comment]
非常感谢你能帮助大家用专业的语言描述出准确问题  夸克现在在线播放和webdav播放速度太慢了 虽然小更新后下载速度没问题 但是播放就很卡

**Comment by Xhofe** [comment]
如果添加range有用，可以试一下这个构建：https://github.com/alist-org/alist/actions/runs/4713028995

**Comment by chenyong0709** [comment]
> 
帮忙截图完整点可以吗，看看你的命令是怎么打的

**Comment by chenyong0709** [comment]
> ![image](https://user-images.githubusercontent.com/4847638/232289244-6dfb49ea-7a6a-4ae6-b7f3-438dad1e260e.png) 加了range确实有效

老哥，帮忙截图完整一点，看下你的命令可以吗

**Comment by zhendery** [comment]
> 如果添加range有用，可以试一下这个构建：https://github.com/alist-org/alist/actions/runs/4713028995

很不幸这个构建速度也是这样：
![速度](https://user-images.githubusercontent.com/13639590/232324529-d22938f2-d763-4790-a909-2908c05fccdc.jpg)

**Comment by zhendery** [comment]
> 如果添加range有用，可以试一下这个构建：https://github.com/alist-org/alist/actions/runs/4713028995

wget我测试不了，但直接使用的话速度仍然是：
![速度](https://user-images.githubusercontent.com/13639590/232327822-2b4f9b61-5902-42ab-af20-efa51d0724be.jpg)

**Comment by zhendery** [comment]
> > 如果添加range有用，可以试一下这个构建：https://github.com/alist-org/alist/actions/runs/4713028995
> 
> 直接使用的话速度仍然是： ![速度](https://user-images.githubusercontent.com/13639590/232327822-2b4f9b61-5902-42ab-af20-efa51d0724be.jpg) wget我测试不了，不知道为什么一直拉不到： ![wget](https://user-images.githubusercontent.com/13639590/232327919-6d3a3456-b89c-4541-be90-b367f09914ab.jpg)

https://github.com/alist-org/alist/actions/runs/4718633189  这个很可以

**Comment by sammymsn** [comment]
搞不懂github的机制，问题被关闭的标准不是解决了么？现在是这个问题已经被解决了么？

**Comment by zhendery** [comment]
> 搞不懂github的机制，问题被关闭的标准不是解决了么？现在是这个问题已经被解决了么？

对，已经解决了，不过是其他人提的相同问题里，详情见：https://github.com/alist-org/alist/issues/4175
