### ISSUE TITLE
宝塔反代127.0.0.1:5244如果使用了非标准接口的SSL会导致在线观看的地址不会加端口

### ISSUE THREAD

**Issue by Winyer** [alist-org/alist#4181]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.0

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

如题，宝塔反代127.0.0.1:5244如果使用了非标准接口的SSL会导致在线观看的地址不会加端口
主要表现为，我用的SSL端口为其他端口非443端口时，如https://abc.com:1564这样时，在线观看时获取到的视频的链接会变成https://abc.com/p/1.mp4，而不是https://abc.com:1564/p/1.mp4（链接带/p/是因为开启了代理），希望能够修复一下

另：获取到的文件下载链接则是正常的带了端口的

问题如图所示：
![bug1](https://user-images.githubusercontent.com/19600350/232551926-10e0af4b-9620-4160-b395-229b52dfed98.png)

### Reproduction / 复现链接

无

**Comment by Winyer** [comment]
补充说明下，没有获取到端口也就不能获取到文件地址导致了无法在线观看，还有不使用443端口是因为运营商没有给443端口开放的权限，所以只能用非标准端口了

**Comment by Winyer** [comment]
再补充一条，经测试，关闭代理后此问题消失，能够正常获取到端口

**Comment by Xhofe** [comment]
#726
#1159
#3644
#2429

**Comment by Winyer** [comment]
> * [使用非标准端口反代后夸克网盘的文件请求错误 #726](https://github.com/alist-org/alist/issues/726)
> * [当网址带端口时,播放视频存在问题 #1159](https://github.com/alist-org/alist/issues/1159)
> * [反向代理后  下载按钮的链接不正确 #3644](https://github.com/alist-org/alist/issues/3644)
> * [本地挂载，点击下载，链接没有带上端口，而复制链接有端口。 #2429](https://github.com/alist-org/alist/issues/2429)

请问能详细点吗？那几个issues看完了只看到说解决了没看到是怎么做的😥

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/issues/3644#issuecomment-1445999667

**Comment by Winyer** [comment]
> [#3644 (comment)](https://github.com/alist-org/alist/issues/3644#issuecomment-1445999667)

好的，我去试试，谢谢

**Comment by Winyer** [comment]
> > [#3644 (comment)](https://github.com/alist-org/alist/issues/3644#issuecomment-1445999667)
> 
> 好的，我去试试，谢谢

记录下我这42分钟的反复折腾，反复重建网站配置规则吧，如果能帮到后面的人就更好了可能因为自己没接触过相关的，所以很吃力，到现在我才明白是要在宝塔-网站设置-反向代理里面点击你配置的反代的配置文件然后把proxy_set_header Host $http_host;这个添加进去，看了看，我顺便删除了proxy_set_header Host $host;这句，因为感觉有点重复了，不知道应不应该删，反正我删了暂时好像没问题。

**Comment by Winyer** [comment]
> > 
> 
> 又去试了一次，如果不删除会出现400错误，访问失败，所以确实要删掉

再记录一个，这样反代后代理的速度会很慢，差不多只有直接访问5244端口时代理速度的三十分之一左右.....我也不知道是为什么，还是哪没做对？有知道的帮忙解答下吧

**Comment by shadowofgost** [comment]
> > > 
> > 
> > 
> > 又去试了一次，如果不删除会出现400错误，访问失败，所以确实要删掉
> 
> 再记录一个，这样反代后代理的速度会很慢，差不多只有直接访问5244端口时代理速度的三十分之一左右.....我也不知道是为什么，还是哪没做对？有知道的帮忙解答下吧

反代用的是什么？docker，nginx还是啥？还有反代的具体配置，nginx要开压缩，文件之类，去查看nginx配置的博客和论文，还有反代的通道大小等。并且你说的慢是什么慢呢？有没有使用中继

**Comment by Winyer** [comment]
> > > > 
> > > 
> > > 
> > > 又去试了一次，如果不删除会出现400错误，访问失败，所以确实要删掉
> > 
> > 
> > 再记录一个，这样反代后代理的速度会很慢，差不多只有直接访问5244端口时代理速度的三十分之一左右.....我也不知道是为什么，还是哪没做对？有知道的帮忙解答下吧
> 
> 反代用的是什么？docker，nginx还是啥？还有反代的具体配置，nginx要开压缩，文件之类，去查看nginx配置的博客和论文，还有反代的通道大小等。并且你说的慢是什么慢呢？有没有使用中继

用的是宝塔里面的，nginx的tengine版本，使用的是默认的配置，开了压缩，通道大小是什么呢，慢是网速的慢，无中继
