### ISSUE TITLE
希望新增huang1111网盘（pan.huang1111.cn）的挂载方式

### ISSUE THREAD

**Issue by k1195453766** [alist-org/alist#4185]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望新增huang1111网盘（pan.huang1111.cn）的挂载方式

**Comment by mengguyi** [comment]
> ### Please make sure of the following things
> * [ ]  I have read the [documentation](https://alist.nn.ci).
> * [ ]  I'm sure there are no duplicate issues or discussions.
> * [ ]  I'm sure this feature is not implemented.
> * [ ]  I'm sure it's a reasonable and popular requirement.
> 
> ### Description of the feature / 需求描述
> 希望新增huang1111网盘（pan.huang1111.cn）的挂载方式
> 
> ### Suggested solution / 实现思路
> _No response_
> 
> ### Additional context / 附件
> _No response_


它不是有webdav吗，而且是cloudreve，哪个不都可以吗
