### ISSUE TITLE
游客用户可通过索引搜索到向游客用户隐藏的文件并播放

### ISSUE THREAD

**Issue by li5243225** [alist-org/alist#4196]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.0

### Driver used / 使用的存储驱动

pikpakshare

### Describe the bug / 问题描述

已建立非全文索引的情况下，使用游客账户登录进行搜索时，能搜索到对游客账户隐藏（元信息设置）的文件夹内容并打开。

### Reproduction / 复现链接

 如下截图，游客账户开放pikpakshare文件，但通过搜索能搜到未对游客开放的其他盘内容。
![image](https://user-images.githubusercontent.com/42256397/233030708-efb5a420-6cc9-45e6-a1b7-3d0a96b877cc.png)

**Comment by Xhofe** [comment]
bleve吗

**Comment by li5243225** [comment]
> bleve吗

非全文搜索

**Comment by xing-yv** [comment]
隐藏文件夹时勾选“应用到子文件夹”或许会有帮助
在我的issue， #4494

**Comment by Xhofe** [comment]
duplicate with #4494
