### ISSUE TITLE
可以支持对外暴露一个oss服务吗?

### ISSUE THREAD

**Issue by shawn520** [alist-org/alist#4197]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

比如说挂载云盘之后,把云盘当作对象存储进行管理,然后对外暴露oss,这样通过sdk/api就能上传下载文件了

**Comment by zhucp** [comment]
有这个功能的话,就完全把各种网盘聚合起来当作oss服务器了.不用买服务商的oss服务了.爽

**Comment by jile1997** [comment]
alist提供的有webdav可以通过webdav的sdk来上传下载

**Comment by JsonSong89** [comment]
现在alist用的是openApi吧,这种有频率限制的,你能接受oss接口动不动限流?
