### ISSUE TITLE
linux的本机存储 中文文件排序错误（UTF-8）

### ISSUE THREAD

**Issue by zhendery** [alist-org/alist#4204]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.0

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

![wenjianming](https://user-images.githubusercontent.com/13639590/233394013-52099395-70c4-4411-97f3-b8c3487cd157.jpg)

如截图所示，因为是linux系统所以文件名是UTF-8编码，排序并不是按照拼音顺序排的。
而Windows系统是按拼音顺序排的GBK编码。

因此建议对于UTF-8的汉字进行转码然后再排序。

### Reproduction / 复现链接

无公网测试链接，请自行测试。
问题先挂在这，如果可以的话我有空也会尝试进行此问题的修改。

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/issues/4131

应该和这个类似吧🥲虽然他说的是编码 你说的是排序

不过咱们的排序应该用的是ASCLL码排序的吧? 应该不会修改了 不过欢迎pr😄

**Comment by zhendery** [comment]
> #4131
> 
> 应该和这个类似吧🥲虽然他说的是编码 你说的是排序
> 
> 不过咱们的排序应该用的是ASCLL码排序的吧（应该没记错）? 应该不会修改了 不过欢迎pr😄

 类似的地方只有编码吧，主要他的是文件在线预览，可以用浏览器直接改预览编码的。
而我这个排序是alist自己实现的，没办法通过外部修改，除非一开始就不要用utf-8的文件系统（也就是说不能用linux了），所以我三思后还是认为是一个bug因此当issue提了。

实现起来也不复杂，主要是我可能需要配下环境啥的。

**Comment by ZXiangQAQ** [comment]
把官方SortFiles的name字段的less方法换一下就行

```golang
import (
	"bytes"
	"golang.org/x/text/encoding/simplifiedchinese"
	"golang.org/x/text/transform"
	"io"
	"strings"
)

// UTF82GBK chars transform from utf8 to gb18030
func UTF82GBK(source string) ([]byte, error) {
	return io.ReadAll(transform.NewReader(strings.NewReader(source), simplifiedchinese.GB18030.NewEncoder()))
}

// GBK2UTF8 chars transform from gb18030 to utf8
func GBK2UTF8(source []byte) (string, error) {
	transformed, err := io.ReadAll(transform.NewReader(bytes.NewReader(source), simplifiedchinese.GB18030.NewDecoder()))
	if err != nil {
		return "", err
	}
	return string(transformed), nil
}

// CNLess use gbk implemented sort.Slice() less method
func CNLess(i string, j string) bool {
	a, _ := UTF82GBK(i)
	b, _ := UTF82GBK(j)
	bLen := len(b)
	for idx, chr := range a {
		if idx > (bLen - 1) {
			return false
		}
		if chr != b[idx] {
			return chr < b[idx]
		}
	}
	return true
}
```

**Comment by ZXiangQAQ** [comment]
> 把官方 `model.SortFiles` 的 `name` 字段的 `less` 方法换一下就行, 不过效率没 `natural.Less` 效率高
> 
> ```go
> import (
> 	"bytes"
> 	"golang.org/x/text/encoding/simplifiedchinese"
> 	"golang.org/x/text/transform"
> 	"io"
> 	"strings"
> )
> 
> // UTF82GBK chars transform from utf8 to gb18030
> func UTF82GBK(source string) ([]byte, error) {
> 	return io.ReadAll(transform.NewReader(strings.NewReader(source), simplifiedchinese.GB18030.NewEncoder()))
> }
> 
> // GBK2UTF8 chars transform from gb18030 to utf8
> func GBK2UTF8(source []byte) (string, error) {
> 	transformed, err := io.ReadAll(transform.NewReader(bytes.NewReader(source), simplifiedchinese.GB18030.NewDecoder()))
> 	if err != nil {
> 		return "", err
> 	}
> 	return string(transformed), nil
> }
> 
> // CNLess use gbk implemented sort.Slice() less method
> func CNLess(i string, j string) bool {
> 	a, _ := UTF82GBK(i)
> 	b, _ := UTF82GBK(j)
> 	bLen := len(b)
> 	for idx, chr := range a {
> 		if idx > (bLen - 1) {
> 			return false
> 		}
> 		if chr != b[idx] {
> 			return chr < b[idx]
> 		}
> 	}
> 	return true
> }
> ```
> 
> `Benckmark` 结果, 转码消耗太大了
> 
> ```shell
> goos: darwin
> goarch: arm64
> pkg: bestpay/less
> BenchmarkCNLess-8          99808             11704 ns/op
> BenchmarkNatural-8      10429744               115.4 ns/op
> PASS
> ok      bestpay/less    2.716s
> ```
喂给 `GPT`稍微优化了一下, 效率提高了一个数量级, `GPT` 比我强多了 =。=
```golang
var encoder = simplifiedchinese.GB18030.NewEncoder()
var decoder = simplifiedchinese.GB18030.NewDecoder()

func UTF82GBK(s string, buf []byte) ([]byte, error) {
	nDst, _, _ := encoder.Transform(buf, []byte(s), true)
	return buf[:nDst], nil
}

func GBK2UTF8(s []byte, buf []byte) (string, error) {
	nDst, _, _ := decoder.Transform(buf, s, true)
	return string(buf[:nDst]), nil
}

func CNLess(i string, j string) bool {
	var buf [1024]byte
	a, _ := UTF82GBK(i, buf[:0])
	b, _ := UTF82GBK(j, buf[:0])
	bLen := len(b)
	for idx, chr := range a {
		if idx > (bLen - 1) {
			return false
		}
		if chr != b[idx] {
			return chr < b[idx]
		}
	}
	return true
}
```
`Benchmark` 结果如下, 从 `11704 ns/op` 优化到 `4766 ns/op`
```shell
goos: darwin
goarch: arm64
pkg: bestpay/less
BenchmarkCNLess-8         218506              4766 ns/op
BenchmarkNatural-8      10436370               115.0 ns/op
PASS
ok      bestpay/less    2.517s
```

**Comment by LevineWoo** [comment]
这个排序确实对非英文字符的不友好。
