### ISSUE TITLE
建议增加复选框的鼠标点击感应范围，或增加鼠标框选

### ISSUE THREAD

**Issue by maimengmeng** [alist-org/alist#4206]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

1. 当我希望对批量文件进行操作时，需要点击复选框将其选中，但只要鼠标稍微点击小方块的周围一点点而没点在小方块上，就变成了进入文件夹的操作，这样在我希望用鼠标快速批量勾选时很容易误操作而导致需要后退重新勾选，是不是可以设计成复选框的那一整块全部可点击选择？
2. 能否增加鼠标框选快速选择文件或文件夹？
谢谢！

**Comment by ohmyarch** [comment]
是非常必要的功能，现在连ctrl/shift多选都不支持
