### ISSUE TITLE
[WebDAV] 能否增加diffuse webdav支持  （CORS限制）

### ISSUE THREAD

**Issue by euXnZv** [alist-org/alist#4208]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.0

### Driver used / 使用的存储驱动

ALIST V3

### Describe the bug / 问题描述

diffuse是一款网页音乐播放器，支持多种云存储链接。在链接alist挂载的webdav时受到CORS限制,不能读取内容。经了解个人无法更改CORS设置，所以希望由开发者来实现。

https://github.com/icidasset/diffuse

<img width="533" alt="image" src="https://user-images.githubusercontent.com/94121014/233562195-931969f8-f388-4ffb-8273-ffe3d83a3947.png">

diffuse提供的webdav设置示例：

<img width="734" alt="image" src="https://user-images.githubusercontent.com/94121014/233562561-15e8b777-368e-4194-bb34-a369644b4c2f.png">

cors:
  enabled: true
  credentials: true

  allowed_headers:
    - Authorization
    - Content-Type
    - Depth
    - Range
  allowed_methods:
    - GET
    - HEAD
    - PROPFIND
  allowed_hosts:
    - https://diffuse.sh
    - http://127.0.0.1:44999
  exposed_headers:
    - Content-Length
    - Content-Type

### Reproduction / 复现链接

没有链接

### Logs / 日志

No responsei

**Comment by Xhofe** [comment]
本来就是支持的 
![image](https://user-images.githubusercontent.com/36558727/233765153-31a180ce-2e37-4469-b916-774c6dc34a8f.png)
