### ISSUE TITLE
Owncloud挂载错误

### ISSUE THREAD

**Issue by liyanes** [alist-org/alist#4214]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.0

### Driver used / 使用的存储驱动

本地驱动(远程挂载Alist的Webdav)

### Describe the bug / 问题描述

在使用Owncloud挂载Alist的Webdav时报错
返回400/401,错误信息是 PROPFIND /dav/ prop must not be empty

对于坚果云等WebDav未发生该错误

请求头是:
PROPFIND /dav/ HTTP/1.1
Host: localhost:5244
Authorization: Basic .............
User-Agent: sabre-dav/4.4.0 (http://sabre.io/)
Accept: */*
Depth: 0
Content-Type: application/xml
Content-Length: 438

<?xml version="1.0" encoding="UTF-8"?>
<d:propfind xmlns:d="DAV:">
  <d:prop xmlns:x="http://owncloud.org/ns" xmlns:x1="http://open-collaboration-services.org/ns">
    <d:getlastmodified/>
    <d:getcontentlength/>
    <d:getcontenttype/>
    <x:permissions xmlns:x="http://owncloud.org/ns"/>
    <x1:share-permissions xmlns:x="http://open-collaboration-services.org/ns"/>
    <d:resourcetype/>
    <d:getetag/>
  </d:prop>
</d:propfind>

返回是:
HTTP/1.1 207 Multi-Status
Content-Type: text/xml; charset=utf-8
Date: Fri, 21 Apr 2023 12:07:56 GMT
Content-Length: 673

<?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>/dav/</D:href><D:propstat><D:prop><D:getlastmodified>Tue, 18 Apr 2023 14:10:20 GMT</D:getlastmodified><D:resourcetype><D:collection xmlns:D="DAV:"/></D:resourcetype></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat><D:propstat><D:prop><D:getcontentlength></D:getcontentlength><D:getcontenttype></D:getcontenttype><permissions xmlns="http://owncloud.org/ns"></permissions><share-permissions xmlns="http://open-collaboration-services.org/ns"></share-permissions><D:getetag></D:getetag></D:prop><D:status>HTTP/1.1 404 Not Found</D:status></D:propstat></D:response></D:multistatus>

### Reproduction / 复现链接

任意Alist Webdav服务

### Logs / 日志

以下是发生错误部分的日志

[GIN] 2023/04/21 - 19:49:13 | 207 |     607.513µs |       127.0.0.1 | PROPFIND  "/dav/"
[GIN] 2023/04/21 - 19:49:13 | 401 |       8.766µs |       127.0.0.1 | PROPFIND  "/dav/"
ERRO[2023-04-21 19:49:13] PROPFIND /dav/ prop must not be empty
[GIN] 2023/04/21 - 19:49:13 | 400 |      288.13µs |       127.0.0.1 | PROPFIND  "/dav/"
[GIN] 2023/04/21 - 19:49:14 | 401 |        43.1µs |       127.0.0.1 | PROPFIND  "/dav/"
[GIN] 2023/04/21 - 19:49:14 | 207 |     557.721µs |       127.0.0.1 | PROPFIND  "/dav/"
[GIN] 2023/04/21 - 19:49:14 | 401 |      47.103µs |       127.0.0.1 | PROPFIND  "/dav/"
[GIN] 2023/04/21 - 19:49:14 | 207 |     543.666µs |       127.0.0.1 | PROPFIND  "/dav/"

**Comment by liyanes** [comment]
上面的问题描述补充一下,好像自动截断了

返回的数据:

HTTP/1.1 207 Multi-Status
Content-Type: text/xml; charset=utf-8
Date: Fri, 21 Apr 2023 12:07:56 GMT
Content-Length: 673

<?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>/dav/</D:href><D:propstat><D:prop><D:getlastmodified>Tue, 18 Apr 2023 14:10:20 GMT</D:getlastmodified><D:resourcetype><D:collection xmlns:D="DAV:"/></D:resourcetype></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat><D:propstat><D:prop><D:getcontentlength></D:getcontentlength><D:getcontenttype></D:getcontenttype><permissions xmlns="http://owncloud.org/ns"></permissions><share-permissions xmlns="http://open-collaboration-services.org/ns"></share-permissions><D:getetag></D:getetag></D:prop><D:status>HTTP/1.1 404 Not Found</D:status></D:propstat></D:response></D:multistatus>

**Comment by liyanes** [comment]
上面返回的格式好像没法写出来:
下面是图片

![image](https://user-images.githubusercontent.com/30283620/233635229-ad81dbf6-7107-4e5c-97c0-d16cc6beac86.png)

**Comment by Xhofe** [comment]
207是正常的响应，请提供207之后的请求的请求内容。

**Comment by liyanes** [comment]
207指多个返回值
由于我是tcpdump抓包,所有看不到内部的逻辑处理,
这里应该主要是最后响应的404 NotFound
(代码可以粘贴显示)
```
<?xml version="1. 0" encoding="UTF-8"?>
  <D : multistatus xmLns : D="DAV:">
    <D:response>
      <D : href> /dav/</D: href>
      <D: propstat>
        <D: prop>
          <D:getlastmodified>Tue, 18 Apr 2023 14:10:20 GMT</D:getlastmodified>
          <D: resourcetype>
            <D: collection xmLns :D="DAV:"/>
          </D:resourcetype>
        </D: prop>
        <D: status>HTTP/1.1200 0K< /D: status>
      < /D: propstat>
      <D: propstat>
        <D : prop>
          <D: getcontentlength>
          </D: getcontentlength>
          <D: getcontenttype></D: getcontenttype>
          <permissions xmLns="http://ownc Loud.org/ns"></ permissions>
          <share -permissions xmLns="http://open-collaboration-services.org/ns ">
          </share-permissions>
          <D : getetag></D: getetag>
        < /D: prop>
        <D : status>HTTP/1.1 404 Not Found< /D: status>
      </D : propstat>
    < /D : response>
  < /D : multistatus>
```

![image](https://user-images.githubusercontent.com/30283620/233770977-2a7c0004-954c-499f-8d18-2cf479dc6632.png)


这里应该是getcontentlength和getcontenttype两个步骤出错了,发生在获取文件夹的过程中

这里用坚果云的WebDav是可以的

**Comment by Xhofe** [comment]
> 

在这之后还有个返回405的请求，那个请求才是报”prop must not be empty“的地方。

**Comment by liyanes** [comment]
应该是这一部分,只看Bad Requests的话

```
PROPFIND /dav/ HTTP/1.1
Host: localhost:5244
Authorization: Basic (账户:密码)
User-Agent: sabre-dav/4.4.0 (http://sabre.io/)
Accept: */*
Depth: 1
Content-Type: application/xml
Content-Length: 93

<?xml version="1.0" encoding="UTF-8"?>
<d:propfind xmlns:d="DAV:">
  <d:prop/>
</d:propfind>

16:47:09.554980 lo    In  IP 127.0.0.1.5244 > 127.0.0.1.47632: Flags [P.], seq 1048:1185, ack 1843, win 512, options [nop,nop,TS val 3243001316 ecr 3243001315], length 137
E...r.@.@..r.........|..M.41...............
.LE..LE.HTTP/1.1 400 Bad Request
Date: Sat, 22 Apr 2023 08:47:09 GMT
Content-Length: 11
Content-Type: text/plain; charset=utf-8

Bad Request
```

**Comment by Xhofe** [comment]
对于webdav，我们使用了https://github.com/golang/net/tree/master/webdav 作为基础。它暂不支持空prop请求，这里的owncloud可能是想请求所有的属性，根据[rfc4918](http://www.webdav.org/specs/rfc4918.html#rfc.section.9.1.5)，请求所有属性应该直接使用`allprop`或者空的请求体（目前也不支持）。所以目前只支持：
- allprop
- 在prop中包含要请求的属性

**Comment by liyanes** [comment]
我将会提Issue到那个项目, 目前等待项目修正

**Comment by liyanes** [comment]
将会尝试提交issue到指定项目, 目前等待修正

**Comment by liyanes** [comment]
将在Owncloud下一次发行版本修复
(go webdav就不知道了)
