### ISSUE TITLE
indexes 复数应该是 indices

### ISSUE THREAD

**Issue by hawktang** [alist-org/alist#4215]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.16

### Driver used / 使用的存储驱动

NA

### Describe the bug / 问题描述

indexes 复数应该是 indices

### Reproduction / 复现链接

indexes 复数应该是 indices
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/2004071/233657334-b1f84027-2ed7-4566-afcc-30a8396454ae.png">

### Logs / 日志

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/2004071/233657308-4cd639a2-c571-49ad-a46f-41256f8d558c.png">

**Comment by Xhofe** [comment]
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/index-indexes-indices
