### ISSUE TITLE
Support thumbnail cache

### ISSUE THREAD

**Issue by DuskXi** [alist-org/alist#4216]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

In process of using, I found that the loading speed of the thumbnails is very slow. (On international internet)
Even in the case of sufficient bandwidth, the loading speed of the thumbnail is even much lower than that of the original image. especially high resolution png.

### Suggested solution / 实现思路

Thumbnail cache generation should be passive. Thumbnails are calculated and cached only after the corresponding request is received. This means that the thumbnail of a picture will only be calculated once.
Create a cache directory directly on disk to store thumbnails of corresponding images.
If the file is deleted, delete the corresponding thumbnail.
At the same time, you can add a configuration string list to match which directories will enable caching.

**Comment by ty114514** [comment]
Good advice, I found the same thing when I tested on a Raspberry Pi
