### ISSUE TITLE
反代后无法在线播放，一直缓冲

### ISSUE THREAD

**Issue by coldnight9** [alist-org/alist#4220]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.16

### Driver used / 使用的存储驱动

gdrive

### Describe the bug / 问题描述

反代域名 开启了ssl，gdrive使用的本地代理，海外服务器
在使用ip：5244时可以正常播放，使用域名就不可以。需要缓冲非常久。
参阅了以下内容，也更改了proxy_set_header Host $http_host; 还是无法播放
#4181 
#3644 

### Reproduction / 复现链接

无

### Logs / 日志

![1](https://user-images.githubusercontent.com/80202197/233774106-f415a4af-6d92-4547-824d-13f5aa085fe1.png)
反代配置

![2](https://user-images.githubusercontent.com/80202197/233774127-dbbed404-7db1-4afd-accb-ea48e40a5b58.png)
视频统计信息

**Comment by coldnight9** [comment]
> https://alist.nn.ci/guide/install/reverse-proxy.html
> 
> 您好，请按模板输入问题并添加详细信息。如果 7 天内没有活动，则标记的问题将关闭。 你好 ，请按照issue模板填写， 并详细说明问题/日志记录/复现步骤/复现链接/实现思路或提供更多信息等， 7天内未回复issue自动关闭。`question`

感谢，已解决

**Comment by huangzlin9** [comment]
可以说下怎么解决的吗 我也遇到这样的问题了

**Comment by huangzlin9** [comment]
> > https://alist.nn.ci/guide/install/reverse-proxy.html
> > 您好，请按模板输入问题并添加详细信息。如果 7 天内没有活动，则标记的问题将关闭。 你好 ，请按照issue模板填写， 并详细说明问题/日志记录/复现步骤/复现链接/实现思路或提供更多信息等， 7天内未回复issue自动关闭。`question`
> 
> 感谢，已解决

老哥，怎么解决的 我也是挂载谷歌为本地
