### ISSUE TITLE
添加存储器时, 添加不了设置有密码的alist V3. 希望能增加此功能.

### ISSUE THREAD

**Issue by xioqing** [alist-org/alist#4226]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

添加存储器时, 添加不了设置有密码的alist V3. 希望能增加此功能.

**Comment by anwen-anyi** [comment]
你是不是在找这个？
![image](https://user-images.githubusercontent.com/56105412/233818082-14cb4094-d65a-4bea-96a7-fc2901f4db1e.png)
![image](https://user-images.githubusercontent.com/56105412/233818077-42231585-60b4-49d7-80f1-ee2f3edeb63a.png)

**Comment by xioqing** [comment]
> 你是不是在找这个？ ![image](https://user-images.githubusercontent.com/56105412/233818082-14cb4094-d65a-4bea-96a7-fc2901f4db1e.png) ![image](https://user-images.githubusercontent.com/56105412/233818077-42231585-60b4-49d7-80f1-ee2f3edeb63a.png)

不是, 我的意思是, 比方说, 我们登入自己的alist时, 有个用户名(admin), 还有个密码需要输入, 但是当我们添加存储alist v3时, 却没有用户名和密码的输入功能. 不知道我有没有表达清楚..

**Comment by anwen-anyi** [comment]
嗷 哪你和这个 https://github.com/alist-org/alist/issues/4218 类似了

**Comment by xioqing** [comment]
> 嗷 哪你和这个 #4218 类似了

嗯, 差不多, 他这个是不希望别人挂载,但是允许访问. 而我是不让别人访问, 但是可以挂载.
