### ISSUE TITLE
希望能自定义qbittorrent下载的文件是否自动上传

### ISSUE THREAD

**Issue by holzora** [alist-org/alist#4229]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我在/www/qbittorrent/download挂载的目录localstorge下载磁链，下载完成后，它给我cp了下qbittorrent里面的记录就没了(保种20小时)，alist中的qbittorrent配置里的做种时间我配置了1天，但是下载完成后也立即转移了文件，能否设置alist中qbittorrent离线下载的下载目录默认qbittorrent的就行了，不要下载在alist的temp目录再移(上传)过去的？

### Suggested solution / 实现思路

可否做两个选择，一个是勾选后遵循qbittorrent的默认下载路径，alist只做一个启动操作，另一个勾选后下载在alist的temp目录，下载完成后直接执行文件转移？

### Additional context / 附件

![Uploading IMG_20230423_170624_866.png…]()

**Comment by Xhofe** [comment]
alist 并不是一个qBittorrent管理面板，你可能需要的是[qbittorrent webui](https://www.google.com/search?q=qbittorrent+webui)。
