### ISSUE TITLE
兼容对象存储的缩略图功能

### ISSUE THREAD

**Issue by timi137137** [alist-org/alist#4232]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在现有对象存储中，通常都会自带一个功能`图片处理`
该功能可以将图片按照传入的请求参数进行处理并返回
为何需要该功能？
因为在网格视图中并没有缩略图显示
![image](https://user-images.githubusercontent.com/36812439/233854726-05c13cd4-3231-49c6-9a0b-3cdd5f141bc5.png)
在图片视图中并没有使用缩略图显示，而是完整加载
![image](https://user-images.githubusercontent.com/36812439/233854760-81dd7d2f-8fa8-4521-8367-005d5b5c734a.png)
在图片较大的情况下，此种行为会加速流量的使用
并且图片视图中如果没有放大是看不清细节的，并不需要如此
因此需要添加对象存储可选功能：缩略图显示

### Suggested solution / 实现思路

建议由设置中，按照存储分类，允许用户填写自定义请求参数
如OSS：
```
原图地址：https://oss-console-img-demo-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/example.jpg
图片处理参数： x-oss-process=image/resize,p_50
```
那么请求的地址便是
`https://oss-console-img-demo-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/example.jpg?x-oss-process=image/resize,p_50`
但由于每个厂商的方式都不同，因此需要用户填写自定义请求参数，或者默认给出单选框选择
如COS的压缩链接举例：`https://test-1250000000.cos.ap-beijing.myqcloud.com/sample.jpg?imageMogr2/thumbnail/!50p`

**Comment by imotosaiko** [comment]
支持。。。就因为不支持OSS的缩略图功能自己都开始物色其他替代软件了，希望能早日添加这个功能
