### ISSUE TITLE
建议首次启动Alist让用户自己设置用户名和密码

### ISSUE THREAD

**Issue by AkarinLiu** [alist-org/alist#4236]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

用户安装Alist后需要输入密码以便登录后台，建议首次运行Alist要求用户设置用户名和密码。

### Suggested solution / 实现思路

用户安装Alist后需要输入密码以便登录后台，但是输入生成的默认管理员密码会导致无法登录

### Additional context / 附件

当用户首次输入以下命令：
```
alist server
```
用户会被要求设置用户名和密码：
```
New Username:
New Password:
```
设置之后才能正常运行:
```
INFO[2023-04-24 19:54:31] success start pid: 3848
```

**Comment by anwen-anyi** [comment]
呃, 现在培养的`AList`用户习惯都得推翻重来 挺麻烦的 哈哈
而且现在的这样获取不也挺方便吗 第一次会输出密码  😂

**Comment by AkarinLiu** [comment]
就问用户是否设置密码就行

发自我的小米
在 安稳 ***@***.***>，2023年4月24日 20:23写道：

呃, 现在培养的AList用户习惯都得推翻重来 挺麻烦的 哈哈
而且现在的这样获取不也挺方便吗 第一次会输出密码 😂

**Comment by AkarinLiu** [comment]
否则是会自动生成密码的

发自我的小米
在 安稳 ***@***.***>，2023年4月24日 20:23写道：

呃, 现在培养的AList用户习惯都得推翻重来 挺麻烦的 哈哈
而且现在的这样获取不也挺方便吗 第一次会输出密码 😂
