### ISSUE TITLE
增加armv7l架构CPU的编译版本

### ISSUE THREAD

**Issue by XYUU** [alist-org/alist#4243]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否增加armv7l架构CPU的编译版本，目前有一些路由器和光猫设备用的是armv7l的架构指令。

同时，希望能完善一下文档，讲述一下不同版本的处理器选用的区别，比如：musl版本适用哪些cpu。

### Suggested solution / 实现思路

[armv7l 表示编译的软件是为小端模式（little-endian）的 armv7 硬件准备的，而 armv7h 表示编译的软件是为硬浮点 ABI（hard-float ABI）的 armv7 硬件准备的](https://stackoverflow.com/questions/29166619/differences-between-arm-versions-armv7-only)。[硬浮点 ABI 可以利用硬件 FPU（浮点运算单元）来加速浮点计算，而软浮点 ABI 则不依赖硬件 FPU](https://blog.hypriot.com/post/how-to-compile-go-on-arm/)。因此，在 Linux 环境使用 golang 编译 armv7l 架构和 armv7 架构的 Linux 系统二进制应用程序的不同之处在于：

需要设置不同的 GOARM 环境变量，例如 GOARM=7 表示 armv7l，GOARM=7h 表示 armv7h；
需要设置不同的 CC 和 CXX 环境变量，指定不同的交叉编译器，例如 CC="arm-linux-gnueabi-gcc" CXX="arm-linux-gnueabi-g++" 表示 armv7l，CC="arm-linux-gnueabihf-gcc" CXX="arm-linux-gnueabihf-g++" 表示 armv7h；
编译出来的二进制应用程序可能有不同的性能表现，取决于目标平台是否有硬件 FPU 支持。

我大致看了一下官方的build.sh
如果是musl则可能需要增加[arm-linux-musleabi-cross.tgz](http://musl.cc/arm-linux-musleabi-cross.tgz)和[armv7l-linux-musleabihf-cross.tgz](http://musl.cc/armv7l-linux-musleabihf-cross.tgz)的配置。

**Comment by anwen-anyi** [comment]
https://github.com/sbwml/luci-app-alist  这里看看有没有arm v7设备使用的？

**Comment by Winyer** [comment]
文档应该不会完善了，很多东西都没写详尽，只能自己摸索

**Comment by jackadam1981** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/28656671/234514050-9c9534e1-19b6-429d-b078-a84587b857b5.png">
这里有armv7

**Comment by jackadam1981** [comment]
https://hub.docker.com/r/xhofe/alist/tags

**Comment by XYUU** [comment]
> [<img alt="image" width="424" src="https://user-images.githubusercontent.com/28656671/234514050-9c9534e1-19b6-429d-b078-a84587b857b5.png">](https://hub.docker.com/r/xhofe/alist/tags) 这里有armv7

armv7在armv7l上是无法运行的，存在数据大小端的问题。

**Comment by XYUU** [comment]
> https://github.com/sbwml/luci-app-alist 这里看看有没有arm v7设备使用的？

没有的，armv7和armv7l的架构区别在于数据大小端的不同。比如中兴新出的小方糖路由器，以及新出的各种高性能双核CPU、ONU都是这个指令集。

**Comment by jackadam1981** [comment]
这就不清楚了，我是跑在玩客云和410wifi棒子上。

**Comment by XYUU** [comment]
> 这就不清楚了，我是跑在玩客云和410wifi棒子上。

额，我是跑在光猫上，但目前无法运行起来，仅是指令集的差异问题导致的。

**Comment by ty114514** [comment]
楼主你好，不是很熟悉硬件，引用了 NewBing 的回复

> 你好，这是Bing。我可以帮你查找一些big-endian的armv7处理器的信息。根据我的搜索结果[1](https://developer.arm.com/ip-products/processors/cortex-a.)，大多数armv7处理器都是little-endian的，但是有一些支持big-endian模式，比如armv7-R[2](https://developer.arm.com/documentation/ddi0406/c/Application-Level-Architecture/Application-Level-Memory-Model/Endian-support/Instruction-endianness)。另外，有一些指令可以在armv7处理器上实现字节序的转换，比如rev[3](https://stackoverflow.com/questions/4286671/endianness-conversion-in-arm)。如果你想了解更多关于armv7处理器的细节，你可以参考这个网站[4](https://developer.android.com/ndk/guides/abis)。

你的问题似乎与大小端序列无关，只是目标 glibc 版本低于构建平台，你的命令显示你的设备最高支持到 2.26，但报错丢出依赖 2.28 的库

另外，musl 同 glibc 一样也是 C 库，但不同的是，musl 更偏向于轻量，嵌入式，外部零依赖

musl 与 glibc 的硬件支持都是一样的，楼主可以尝试运行[alist-linux-musl-arm.tar.gz](https://github.com/alist-org/alist/releases/latest/download/alist-linux-musl-arm.tar.gz)

: )

**Comment by XYUU** [comment]
我尝试过了，提示非法指令。
我目前使用的是自己用交叉编译器编译的版本。

**Comment by henry19922** [comment]
> > 楼主你好，不是很熟悉硬件，引用了 NewBing 的回复
> > > 你好，这是Bing。我可以帮你查找一些big-endian的armv7处理器的信息。根据我的搜索结果[1](https://developer.arm.com/ip-products/processors/cortex-a.)，大多数armv7处理器都是little-endian的，但是有一些支持big-endian模式，比如armv7-R[2](https://developer.arm.com/documentation/ddi0406/c/Application-Level-Architecture/Application-Level-Memory-Model/Endian-support/Instruction-endianness)。另外，有一些指令可以在armv7处理器上实现字节序的转换，比如rev[3](https://stackoverflow.com/questions/4286671/endianness-conversion-in-arm)。如果你想了解更多关于armv7处理器的细节，你可以参考这个网站[4](https://developer.android.com/ndk/guides/abis)。
> > 
> > 
> > 你的问题似乎与大小端序列无关，只是目标 glibc 版本低于构建平台，你的命令显示你的设备最高支持到 2.26，但报错丢出依赖 2.28 的库
> > 另外，musl 同 glibc 一样也是 C 库，但不同的是，musl 更偏向于轻量，嵌入式，外部零依赖
> > musl 与 glibc 的硬件支持都是一样的，楼主可以尝试运行[alist-linux-musl-arm.tar.gz](https://github.com/alist-org/alist/releases/latest/download/alist-linux-musl-arm.tar.gz)
> > : )
> 
> 我尝试过了，提示非法指令。 我目前使用的是自己用交叉编译器编译的版本。

能分享下你编译的版本吗？

**Comment by showcy** [comment]
> > 楼主你好，不是很熟悉硬件，引用了 NewBing 的回复
> > > 你好，这是Bing。我可以帮你查找一些big-endian的armv7处理器的信息。根据我的搜索结果[1](https://developer.arm.com/ip-products/processors/cortex-a.)，大多数armv7处理器都是little-endian的，但是有一些支持big-endian模式，比如armv7-R[2](https://developer.arm.com/documentation/ddi0406/c/Application-Level-Architecture/Application-Level-Memory-Model/Endian-support/Instruction-endianness)。另外，有一些指令可以在armv7处理器上实现字节序的转换，比如rev[3](https://stackoverflow.com/questions/4286671/endianness-conversion-in-arm)。如果你想了解更多关于armv7处理器的细节，你可以参考这个网站[4](https://developer.android.com/ndk/guides/abis)。
> > 
> > 
> > 你的问题似乎与大小端序列无关，只是目标 glibc 版本低于构建平台，你的命令显示你的设备最高支持到 2.26，但报错丢出依赖 2.28 的库
> > 另外，musl 同 glibc 一样也是 C 库，但不同的是，musl 更偏向于轻量，嵌入式，外部零依赖
> > musl 与 glibc 的硬件支持都是一样的，楼主可以尝试运行[alist-linux-musl-arm.tar.gz](https://github.com/alist-org/alist/releases/latest/download/alist-linux-musl-arm.tar.gz)
> > : )
> 
> 我尝试过了，提示非法指令。 我目前使用的是自己用交叉编译器编译的版本。

你好，我也有相同的问题，可否分享一下您交叉编译的版本？谢谢

**Comment by stuzyz999** [comment]
> > 楼主你好，不是很熟悉硬件，引用了 NewBing 的回复
> > > 你好，这是Bing。我可以帮你查找一些big-endian的armv7处理器的信息。根据我的搜索结果[1](https://developer.arm.com/ip-products/processors/cortex-a.)，大多数armv7处理器都是little-endian的，但是有一些支持big-endian模式，比如armv7-R[2](https://developer.arm.com/documentation/ddi0406/c/Application-Level-Architecture/Application-Level-Memory-Model/Endian-support/Instruction-endianness)。另外，有一些指令可以在armv7处理器上实现字节序的转换，比如rev[3](https://stackoverflow.com/questions/4286671/endianness-conversion-in-arm)。如果你想了解更多关于armv7处理器的细节，你可以参考这个网站[4](https://developer.android.com/ndk/guides/abis)。
> > 
> > 
> > 你的问题似乎与大小端序列无关，只是目标 glibc 版本低于构建平台，你的命令显示你的设备最高支持到 2.26，但报错丢出依赖 2.28 的库
> > 另外，musl 同 glibc 一样也是 C 库，但不同的是，musl 更偏向于轻量，嵌入式，外部零依赖
> > musl 与 glibc 的硬件支持都是一样的，楼主可以尝试运行[alist-linux-musl-arm.tar.gz](https://github.com/alist-org/alist/releases/latest/download/alist-linux-musl-arm.tar.gz)
> > : )
> 
> 我尝试过了，提示非法指令。 我目前使用的是自己用交叉编译器编译的版本。

大佬你好,我是armv71版本的ac68u,同求您的alist版本.感谢

**Comment by Xhofe** [comment]
请测试：

https://github.com/alist-dev/alist/actions/runs/5716716642

**Comment by xiaodatao2007** [comment]
我的可以跑起来，谢了@Xhofe

`root权限下
$  adb push alist-linux-musleabihf-armv7l /data/local/tmp 
$  cd /data/local/tmp
$  chmod 777 alist-linux-musleabihf-armv7l
$ 
$  ./alist-linux-musleabihf-armv7l version
`

log :
`
                                    <
Built At: 2023-07-31 15:40:09 +0000
Go Version: go1.20.6 linux/amd64
Author: Xhofe <i@nn.ci>
Commit ID: a91d403
Version: dev
WebVersion: dev

`

**Comment by xiaodatao2007** [comment]
添加阿里云盘，报错，token是正常的，linux可以正常添加，反复试了3遍，都没有成功；
日志如下：
[36mINFO[0m[2023-08-05 09:17:11] reading config file: /data/local/tmp/alist2/data/config.json 
[36mINFO[0m[2023-08-05 09:17:11] load config from env with prefix: ALIST_     
[36mINFO[0m[2023-08-05 09:17:11] init logrus...                               
[36mINFO[0m[2023-08-05 09:17:11] start HTTP server @ 0.0.0.0:5244             
[36mINFO[0m[2023-08-05 09:17:11] qbittorrent not ready.                       
2023/08/05 09:17:11.956874 ERROR RESTY Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:42755->[::1]:53: read: connection refused, Attempt 1
2023/08/05 09:17:12.063689 ERROR RESTY Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:41067->[::1]:53: read: connection refused, Attempt 2
2023/08/05 09:17:12.222399 ERROR RESTY Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:60862->[::1]:53: read: connection refused, Attempt 3
2023/08/05 09:17:12.579162 ERROR RESTY Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:39693->[::1]:53: read: connection refused, Attempt 4
[31mERRO[0m[2023-08-05 09:17:12] failed get enabled storages: Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:39693->[::1]:53: read: connection refused
failed init storage
github.com/alist-org/alist/v3/internal/op.initStorage
	/home/runner/work/alist/alist/internal/op/storage.go:99
github.com/alist-org/alist/v3/internal/op.LoadStorage
	/home/runner/work/alist/alist/internal/op/storage.go:80
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
	/home/runner/work/alist/alist/internal/bootstrap/storage.go:20
runtime.goexit
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/asm_arm.s:831 
2023/08/05 09:18:50.875808 ERROR RESTY Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:34001->[::1]:53: read: connection refused, Attempt 1
2023/08/05 09:18:50.989126 ERROR RESTY Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:42900->[::1]:53: read: connection refused, Attempt 2
2023/08/05 09:18:51.188885 ERROR RESTY Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:59058->[::1]:53: read: connection refused, Attempt 3
2023/08/05 09:18:51.476437 ERROR RESTY Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:47243->[::1]:53: read: connection refused, Attempt 4

**Comment by HeLinSpace** [comment]
> > 楼主你好，不是很熟悉硬件，引用了 NewBing 的回复
> > > 你好，这是Bing。我可以帮你查找一些big-endian的armv7处理器的信息。根据我的搜索结果[1](https://developer.arm.com/ip-products/processors/cortex-a.)，大多数armv7处理器都是little-endian的，但是有一些支持big-endian模式，比如armv7-R[2](https://developer.arm.com/documentation/ddi0406/c/Application-Level-Architecture/Application-Level-Memory-Model/Endian-support/Instruction-endianness)。另外，有一些指令可以在armv7处理器上实现字节序的转换，比如rev[3](https://stackoverflow.com/questions/4286671/endianness-conversion-in-arm)。如果你想了解更多关于armv7处理器的细节，你可以参考这个网站[4](https://developer.android.com/ndk/guides/abis)。
> > 
> > 
> > 你的问题似乎与大小端序列无关，只是目标 glibc 版本低于构建平台，你的命令显示你的设备最高支持到 2.26，但报错丢出依赖 2.28 的库
> > 另外，musl 同 glibc 一样也是 C 库，但不同的是，musl 更偏向于轻量，嵌入式，外部零依赖
> > musl 与 glibc 的硬件支持都是一样的，楼主可以尝试运行[alist-linux-musl-arm.tar.gz](https://github.com/alist-org/alist/releases/latest/download/alist-linux-musl-arm.tar.gz)
> > : )
> 
> 我尝试过了，提示非法指令。 我目前使用的是自己用交叉编译器编译的版本。

大佬你好,我是armv71版本的ac68u,同求您的alist版本.感谢

**Comment by XYUU** [comment]
> > > 楼主你好，不是很熟悉硬件，引用了 NewBing 的回复
> > > > 你好，这是Bing。我可以帮你查找一些big-endian的armv7处理器的信息。根据我的搜索结果[1](https://developer.arm.com/ip-products/processors/cortex-a.)，大多数armv7处理器都是little-endian的，但是有一些支持big-endian模式，比如armv7-R[2](https://developer.arm.com/documentation/ddi0406/c/Application-Level-Architecture/Application-Level-Memory-Model/Endian-support/Instruction-endianness)。另外，有一些指令可以在armv7处理器上实现字节序的转换，比如rev[3](https://stackoverflow.com/questions/4286671/endianness-conversion-in-arm)。如果你想了解更多关于armv7处理器的细节，你可以参考这个网站[4](https://developer.android.com/ndk/guides/abis)。
> > > 
> > > 
> > > 你的问题似乎与大小端序列无关，只是目标 glibc 版本低于构建平台，你的命令显示你的设备最高支持到 2.26，但报错丢出依赖 2.28 的库
> > > 另外，musl 同 glibc 一样也是 C 库，但不同的是，musl 更偏向于轻量，嵌入式，外部零依赖
> > > musl 与 glibc 的硬件支持都是一样的，楼主可以尝试运行[alist-linux-musl-arm.tar.gz](https://github.com/alist-org/alist/releases/latest/download/alist-linux-musl-arm.tar.gz)
> > > : )
> > 
> > 
> > 我尝试过了，提示非法指令。 我目前使用的是自己用交叉编译器编译的版本。
> 
> 大佬你好,我是armv7l版本的ac68u,同求您的alist版本.感谢

我编译的不是armv7l的版本的，是armv5的版本的，我能力有限，搞不出armv7l的可运行的版本的，就不好意思发出来了。

**Comment by HeLinSpace** [comment]
> > > > 楼主你好，不是很熟悉硬件，引用了 NewBing 的回复
> > > > > 你好，这是Bing。我可以帮你查找一些big-endian的armv7处理器的信息。根据我的搜索结果[1](https://developer.arm.com/ip-products/processors/cortex-a.)，大多数armv7处理器都是little-endian的，但是有一些支持big-endian模式，比如armv7-R[2](https://developer.arm.com/documentation/ddi0406/c/Application-Level-Architecture/Application-Level-Memory-Model/Endian-support/Instruction-endianness)。另外，有一些指令可以在armv7处理器上实现字节序的转换，比如rev[3](https://stackoverflow.com/questions/4286671/endianness-conversion-in-arm)。如果你想了解更多关于armv7处理器的细节，你可以参考这个网站[4](https://developer.android.com/ndk/guides/abis)。
> > > > 
> > > > 
> > > > 你的问题似乎与大小端序列无关，只是目标 glibc 版本低于构建平台，你的命令显示你的设备最高支持到 2.26，但报错丢出依赖 2.28 的库
> > > > 另外，musl 同 glibc 一样也是 C 库，但不同的是，musl 更偏向于轻量，嵌入式，外部零依赖
> > > > musl 与 glibc 的硬件支持都是一样的，楼主可以尝试运行[alist-linux-musl-arm.tar.gz](https://github.com/alist-org/alist/releases/latest/download/alist-linux-musl-arm.tar.gz)
> > > > : )
> > > 
> > > 
> > > 我尝试过了，提示非法指令。 我目前使用的是自己用交叉编译器编译的版本。
> > 
> > 
> > 大佬你好,我是armv7l版本的ac68u,同求您的alist版本.感谢
> 
> 我编译的不是armv7l的版本的，是armv5的版本的，我能力有限，搞不出armv7l的可运行的版本的，就不好意思发出来了。

好的 还是 谢谢大佬回复了 我准备换个小米搞一搞  毕竟老机器就算能整 性能也会跟不上
