### ISSUE TITLE
挂载阿里云后上传不显示文件

### ISSUE THREAD

**Issue by KKISO574** [alist-org/alist#4245]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16

### Driver used / 使用的存储驱动

阿里云open

### Describe the bug / 问题描述

挂载后尝试上传小文件成功后阿里云客户端也有文件了，但是当第二次上传后，文章不在alist中显示，清除浏览器缓存无果，但是阿里云客户端中有改文件，且文件无损坏。

### Reproduction / 复现链接

https://cloud.7boe.top:13797/%E9%98%BF%E9%87%8C%E7%BD%91%E7%9B%98/%E7%BD%91%E7%9B%98%E4%B8%8A%E4%BC%A0
密码Wangwei
阿里云客服端文件页面：https://ali.7boe.top/2023/04/26/6448ccd56ad7f.png
我的alist中的文件截图：https://ali.7boe.top/2023/04/26/6448ccf1cb6e2.png

### Logs / 日志

阿里云客服端文件页面：https://ali.7boe.top/2023/04/26/6448ccd56ad7f.png
我的alist中的文件截图：https://ali.7boe.top/2023/04/26/6448ccf1cb6e2.png

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8A%E4%BC%A0%E7%9A%84%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA-%E5%88%A0%E9%99%A4%E7%9A%84%E6%96%87%E4%BB%B6%E8%BF%98%E5%9C%A8-%E4%BF%AE%E6%94%B9%E6%A0%B9%E7%9B%AE%E5%BD%95%E4%B8%8D%E7%94%9F%E6%95%88
