### ISSUE TITLE
更新3.16.1版本后，alist-proxy无法正常工作

### ISSUE THREAD

**Issue by Mcxunyun666** [alist-org/alist#4252]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.1

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

在使用AList的下载代理URL并配合[AList-Proxy](https://github.com/alist-org/alist-proxy)使用时出现
{"code":500,"msg":"unexpected end of JSON input"}
报错且无法完成下载。

经过测试，二进制文件部署和Cloudflare Workers部署均为同一报错提示信息

回退版本到v3.16.0后测试未发现任何问题

### Reproduction / 复现链接

[此目录](https://d.oxyxc.top/%E4%BA%A4%E4%BA%92%E5%BC%8F%E6%99%BA%E8%83%BD%E7%99%BD%E6%9D%BFPC%E6%A8%A1%E5%9D%97%E7%B3%BB%E7%BB%9F%E9%95%9C%E5%83%8F/Cloudflare%E8%8A%82%E7%82%B9)  下所有文件

**Comment by lin-cop** [comment]
alist-proxy 的确是好久没有更新了，该维护了

**Comment by coldnight9** [comment]
一样的问题，更新到3.16.1出现的

**Comment by Mcxunyun666** [comment]
[终端日志输出-4-27-23_9-59.log](https://github.com/alist-org/alist/files/11338872/-4-27-23_9-59.log)
[log.log](https://github.com/alist-org/alist/files/11338873/log.log)

**Comment by Mcxunyun666** [comment]
[终端日志输出-4-27-23_9-59.log](https://github.com/alist-org/alist/files/11338935/-4-27-23_9-59.log)
