### ISSUE TITLE
Only show the options of Casdoor while Casdoor is selected at frontend SSO settings

### ISSUE THREAD

**Issue by itsHenry35** [alist-org/alist#4254]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

As the title goes. When anything rather than casdoor is selected, only show client ID, and client secret placeholder. While casdoor is selected, only display org name, app name, endpoint name, and token

### Suggested solution / 实现思路

It seems like a special page for the SSO setting page need to be written in order to use show when, I wonder if there's a better way to implement this.

**Comment by anwen-anyi** [comment]
😄能这样最好不过了

**Comment by anwen-anyi** [comment]
It is also possible to separately require the parameters filled in by Casdoor plus prompts, for example, the following figure

![GPO9C6BL4W~$M66_%7FOTUX](https://user-images.githubusercontent.com/56105412/235342060-3eddd6fd-b842-4f8c-a77d-d2d47b373932.png)

Adding hints like this should be the simplest and crudest way :zany_face: 
but a little ugly :joy: :joy: :joy:

**Comment by itsHenry35** [comment]
unstale
