### ISSUE TITLE
希望能添加浏览器上拖拽文件自动上传

### ISSUE THREAD

**Issue by houshao666** [alist-org/alist#4258]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能添加浏览器上拖拽文件自动上传，就是不用点上传按钮，在文件夹界面拖拽文件到浏览器就可以上传

**Comment by hcaihao** [comment]
支持增加这个功能

**Comment by nadirvishun** [comment]
同支持，这个最符合常规

**Comment by aohanhongzhi** [comment]
非常需要，我第一次搭建，找了5244界面，找了官网，硬是没有找到上传。最后看b站视频，发现，竟然再右下角一个小按钮上传。这个设计不得不说，是个败笔。

![image](https://github.com/alist-org/alist/assets/37319319/ab605bab-ed10-4528-99aa-e8f88c7fc22f)
