### ISSUE TITLE
后台设置 预览 不支持 ape

### ISSUE THREAD

**Issue by ddatsh** [alist-org/alist#4268]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望支持 ape

**Comment by anwen-anyi** [comment]
`ape`是什么格式？音频吗

**Comment by ddatsh** [comment]
> 在 后台 --> 预览 --> 音频类型 里面添加`ape`格式 试试看

加了APE，没用

**Comment by anwen-anyi** [comment]
> > 在 后台 --> 预览 --> 音频类型 里面添加`ape`格式 试试看
> 
> 加了APE，没用

上游 https://github.com/DIYgod/APlayer 不支持 暂时木办法了~~
