### ISSUE TITLE
希望添加一个收藏功能，也就是路径的快捷链接

### ISSUE THREAD

**Issue by xiaoyaliu00** [alist-org/alist#4269]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望可以添加一个收藏的功能，就是把文件夹或者文件添加到指定的目录里，比如一个叫“收藏”的目录，近似alias，但是不用配置，可以直接右键操作

这样的好处，一来是收藏的功能，二来是各种播放器都能使用这个收藏夹

### Suggested solution / 实现思路

![image](https://user-images.githubusercontent.com/124729009/235224380-eb651817-1e3d-4008-a5d4-fb099a7550c5.png)

**Comment by huihui808** [comment]
支持，非常需要这个功能，要不然在不同设备上都要重新收藏
