### ISSUE TITLE
增加微软和谷歌的文档预览方式，优化PDF.js载入PDF 时发生错误的问题

### ISSUE THREAD

**Issue by wowo14735** [alist-org/alist#4270]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

演示站：https://mynotes.world/%E7%AC%94%E8%AE%B0/linux/raid/raid.docx

### Suggested solution / 实现思路

1.演示站用了微软和谷歌的文档预览，目前是否应该优化掉PDF.js载入 PDF 时发生错误的问题？增加这类套件的文档预览？

其他用户给出的第三方服务方案：https://github.com/alist-org/alist/discussions/3908

2.讨论区和电报很多人反映PDF载入 PDF 时发生错误。根据常见问题中，用户并没有得到有用的解决方案，希望后续能优化一下这个问题？
https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E8%83%BD%E9%A2%84%E8%A7%88%E8%A7%86%E9%A2%91%E6%88%96%E9%9F%B3%E9%A2%91%E6%96%87%E4%BB%B6

**Comment by anwen-anyi** [comment]
这种对外提供服务的, 怎么说呢 懂得都懂
不过可以自己自行搭建解决一些也是一样的。并非一定要使用这个自带的`PDF.js`
而且`PDF.js`服务 也可以自行搭建，这样使用起来更加的稳定~
应该是这个：https://github.com/mozilla/pdf.js

我也试过`kkfileview`,这个挺大的几百M，个人觉的适合用于本地使用，服务器的话感觉够呛..

**Comment by Xhofe** [comment]
你可以通过https://alist.nn.ci/zh/config/preview.html#iframe-%E9%A2%84%E8%A7%88 自定义预览程序。

**Comment by Rosewives** [comment]
用 Docker 安装部署的 alist-v3.16.3，

`阿里云盘 open` 方式下可以预览 pdf，但是其他office文档 (如 excel，word， ppt) 都无法预览 （提示：`File not found`
The URL of the original file is not valid or the document is not publicly accessible.）。

原来的`阿里云盘`方式下有自带的 aliyun office 预览插件，而 `阿里云盘 open` 方式下目前没有，希望可以把这个功能加进来🙏🏻

用的默认的 Iframe 预览 配置
```
{
	"doc,docx,xls,xlsx,ppt,pptx": {
		"Microsoft":"https://view.officeapps.live.com/op/view.aspx?src=$e_url",
		"Google":"https://docs.google.com/gview?url=$e_url&embedded=true"
	},
	"pdf": {
		"PDF.js":"https://alist-org.github.io/pdf.js/web/viewer.html?file=$e_url"
	},
	"epub": {
		"EPUB.js":"/static/epub.js/viewer.html?url=$e_url"
	}
}
```

**Comment by wangzichenglong** [comment]
同样是https://view.officeapps.live.com/op/view.aspx?src=$e_url"的调用
alist运行在局域网（有公网ip）的时候，micresoft插件不能预览天翼云盘、阿里云盘、onedrive盘、局域网本地服务器上的文件（192.168.1.10:5244形式），而Oneindex这个老牌的程序同样运行在局域网，micresoft插件却能浏览onedrive盘、局域网本地服务器上的文件。
想来脚本的运行逻辑是有一些出入的。而运行在局域网却能不受限的在线打开网盘或本地盘列表里的micresoft文件进行查看，是非常方便的功能。希望alist作者大佬能借鉴Oneindex的预览模式，改进功能。
![image](https://github.com/alist-org/alist/assets/101960731/e5dc0ac7-06f7-48ab-874d-ab250874c642)
