### ISSUE TITLE
WebDav 无法挂载

### ISSUE THREAD

**Issue by YangguangZhou** [alist-org/alist#4280]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

全部

### Describe the bug / 问题描述

无法挂载到 NPlayer 的 WebDav 上
![Screenshot_20230430-151725](https://user-images.githubusercontent.com/61733195/235340853-c1467cef-50d2-477e-88f3-1b02a51fc765.png)
![Screenshot_20230430-151400](https://user-images.githubusercontent.com/61733195/235340790-2957571f-4551-4447-a516-59bcdc5b5f00.png)

### Reproduction / 复现链接

http://cloud.jerryz.com.cn:443/dav

**Comment by YangguangZhou** [comment]
没有找到相似的问题@Xhofe

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/235341447-f471f2d7-78b7-4f68-9962-4c36b2e0be15.png)
使用上的问题请去discussion，不要提issue。

**Comment by YangguangZhou** [comment]
另外，pikpak 在 Android 上可以正常播放视频，而在 ios 上就不行
