### ISSUE TITLE
可以增加获取网盘hash值的功能吗？

### ISSUE THREAD

**Issue by Gokou-Ruri** [alist-org/alist#4282]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前还有办法获取网盘的hash值（例如百度网盘文件的md5）吗？
用alist下载百度网盘时经常会碰到文件损坏，损坏的文件往往都是10G以上的大文件（从概率上来说越大的文件越容易损坏），而且有时候无法确定到底是上传时损坏还是下载时损坏，如果能拿到md5的话，就能快速比对了，不需要反复重下了。
目前我为了验证文件是否损坏经常需要反复下载同一个20G的文件数次，alist可否增加hash值的获取功能？如果可以实现批量导出网盘文件的hash值或自动校验下载后的文件就更好了。

### Suggested solution / 实现思路

希望可以在网盘的文件列表界面右侧增加“显示hash值”的功能按钮，如果可以增加一个批量复制hash值到剪切板的按钮就更好了，这样就能更方便比对下载的文件了。

**Comment by Winyer** [comment]
同问，顺便问问能不能增加网页版的按时间排序功能，太需要这个了

**Comment by LJason77** [comment]
我用 alist 下载文件是必然损坏，经过测试阿里和百度的都会损坏。测试流程：
1. 打包一个压缩包，加密；
2. 上传到网盘（不使用 alist 上传）；
3. 用 alist 下载，文件哈希值必定改变，然后密码错误导致无法解压。
