### ISSUE TITLE
“发送到Aria2”可否支持文件夹批量下载？

### ISSUE THREAD

**Issue by Gokou-Ruri** [alist-org/alist#4283]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

不是打包成文件夹发送给aria2下载，而是保持网盘的相对目录结构发送给aria2进行下载。

### Suggested solution / 实现思路

将网盘的文件所在的目录发送给aria2进行下载，aria2会自动创建不存在的目录，所以这个功能是可行的。

**Comment by ypq123456789** [comment]
确实

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist-web/pull/88

**Comment by Gokou-Ruri** [comment]
> [alist-org/alist-web#88](https://github.com/alist-org/alist-web/pull/88) 经测试可以直接下载文件夹可以按照文件夹目录结构进行下载

这是个第三方alist的webui吗？

**Comment by anwen-anyi** [comment]
> > [alist-org/alist-web#88](https://github.com/alist-org/alist-web/pull/88) 经测试可以直接下载文件夹可以按照文件夹目录结构进行下载
> 
> 这是个第三方alist的webui吗？

新pr的（新贡献的代码）
