### ISSUE TITLE
夸克网盘无法使用 alist 复制/移动到其他网盘或者本地

### ISSUE THREAD

**Issue by bamboo512** [alist-org/alist#4291]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

Quark

### Describe the bug / 问题描述

Anything that stores on Quark Drive will not be able to copied or moved to other storage, but directly downloading files from alist (Quark Drive) is working well.
存储在夸克网盘的所有内容无法复制或者移动到其他存储，但是直接从夸克下载是正常工作的。

It warns:

> failed get [/夸克精选壁纸/壁纸_8.jpg] stream: failed to get response for : Get "": unsupported protocol scheme ""

<img width="1187" alt="截屏2023-05-01 14 33 06" src="https://user-images.githubusercontent.com/16702370/235417475-fd020057-3c35-4a6d-a068-d71f0782e6b8.png">

### Reproduction / 复现链接

This bug can be reproduced with 100% possibility when you copy or move a file or folder from Quark Drive into another storage.
当从夸克拷贝或者移动文件或文件夹到另一存储，此 Bug 有 100% 的可能性会被复现。

### Logs / 日志

> failed get [/夸克精选壁纸/壁纸_8.jpg] stream: failed to get response for : Get "": unsupported protocol scheme ""

<img width="1187" alt="截屏2023-05-01 14 33 06" src="https://user-images.githubusercontent.com/16702370/235417475-fd020057-3c35-4a6d-a068-d71f0782e6b8.png">

**Comment by thomasdba** [comment]
嗯，的确，遇到了同样的问题
