### ISSUE TITLE
浏览器直接打开共享的html文件的地址能不能直接浏览

### ISSUE THREAD

**Issue by changlehu** [alist-org/alist#4292]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在一打开，就会下载这个html文件，有没有办法做到让它在浏览器打开浏览而不是下载呢？

**Comment by Xhofe** [comment]
这并不是alist要做的事情，你可能需要[nginx](https://www.nginx.com/)
