### ISSUE TITLE
更换onedrive存储导致502

### ISSUE THREAD

**Issue by q246** [alist-org/alist#4294]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

最新

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

我以为更新会恢复 结果还是报错 该如何解决？

### Reproduction / 复现链接

https://alist.nn.ci/zh/guide/drivers/onedrive.html

### Logs / 日志

5月 01 20:09:34 VM-8-14-centos alist[11168]: ERRO[2023-05-01 20:09:34] failed get enabled storages: 鉴权失败
5月 01 20:09:34 VM-8-14-centos alist[11168]: failed init storage
5月 01 20:09:34 VM-8-14-centos alist[11168]: github.com/alist-org/alist/v3/internal/op.initStorage
5月 01 20:09:34 VM-8-14-centos alist[11168]: /home/runner/work/alist/alist/internal/op/storage.go:99
5月 01 20:09:34 VM-8-14-centos alist[11168]: github.com/alist-org/alist/v3/internal/op.LoadStorage
5月 01 20:09:34 VM-8-14-centos alist[11168]: /home/runner/work/alist/alist/internal/op/storage.go:80
5月 01 20:09:34 VM-8-14-centos alist[11168]: github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
5月 01 20:09:34 VM-8-14-centos alist[11168]: /home/runner/work/alist/alist/internal/bootstrap/storage.go:20
5月 01 20:09:34 VM-8-14-centos alist[11168]: runtime.goexit
5月 01 20:09:34 VM-8-14-centos alist[11168]: /opt/hostedtoolcache/go/1.20.3/x64/src/runtime/asm_amd64.s:1598

**Comment by Xhofe** [comment]
请给全日志。

**Comment by q246** [comment]
> * 版本请使用工具实体版号
> * 请给全日志。

v3.16.3 全日志在哪里看？

**Comment by q246** [comment]
算了不需要了 我直接重装了 我的评价是不如之前的V2版本
