### ISSUE TITLE
希望网页端增加win自带播放器“电影和电视”的调用

### ISSUE THREAD

**Issue by x2287711259** [alist-org/alist#4296]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望网页端本地播放器的调用，增加win自带播放器“电影和电视”，本人小白，不太清楚是否可行，win自带的“电影和电视”占用低，播放流畅，好多potplayer播放卡顿的视频都可以流畅播放

**Comment by Xhofe** [comment]
我未找到“电影和电视的”应用程序scheme，如果你知道你可以在https://alist.nn.ci/config/preview.html#external-previews 中自行添加新的应用程序scheme。
