### ISSUE TITLE
百度网盘报错：user not exists

### ISSUE THREAD

**Issue by imzlh** [alist-org/alist#4297]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

无论是下载还是预览报错：
`{"error_code":31045,"error_msg":"user not exists","request_id":512894431695382399}`
但是文件列举正常，在之前的版本里没遇到这个问题
试过重新加载存储，也没有用

### Reproduction / 复现链接

（目前只支持ipv6）
imzlh.top:88/资源/百度云/Chrome_v68.0.3440.70_20180730_for_Android%204.1+.apk

### Logs / 日志

![49F970AE-67B9-45A8-A20A-BAB8EC6ABA0E](https://user-images.githubusercontent.com/114276136/235583330-c6f6fcab-74ab-487e-9a0e-e0f1bb072f37.jpeg)

**Comment by jinenge** [comment]
挂载v3好像也挂载不上去了

**Comment by Xhofe** [comment]
请截图你的存储配置。

**Comment by imzlh** [comment]
好的，使用natmap搭了一个临时的
http://39.171.171.2:12480/资源/百度云/Chrome_v68.0.3440.70_20180730_for_Android%204.1+.apk

**Comment by imzlh** [comment]
抱歉，发现问题了。使用了非官方接口，不是alist的问题
