### ISSUE TITLE
【严重安全问题】关于加密

### ISSUE THREAD

**Issue by toyqiu** [alist-org/alist#4299]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

webdav

### Describe the bug / 问题描述

不论是挂载 webdav 还是阿里云，登陆后获取任意挂载的云空间里的文件的链接，用隐私模式或其他未登陆 AList 账户的浏览器访问该链接，可直接获得链接。

即，账户密码只是阻止了任意用户访问文件目录，只要知道具体的文件路径，整个挂载的目录等于是在裸奔。

### Reproduction / 复现链接

不论是挂载 webdav 还是阿里云，登陆后获取任意挂载的云空间里的文件的链接，用隐私模式或其他未登陆 AList 账户的浏览器访问该链接，可直接获得链接。

即，账户密码只是阻止了任意用户访问文件目录，只要知道具体的文件路径，整个挂载的目录等于是在裸奔。

**Comment by bamboo512** [comment]
每一个存储的配置都有一个 __启用签名__ 的选项，启用之后，请求链接必须带有 `sign` 请求参数才能成功请求到相应文件。
![Screenshot_2023-05-03-15-01-39-193_com android chrome-edit](https://user-images.githubusercontent.com/16702370/235851293-ada90100-6017-4103-9132-0d7bfc623a48.jpg)

**Comment by anwen-anyi** [comment]
开启`应用到子文件夹`了? 开启签名了?

**Comment by toyqiu** [comment]
解决了。
没有这个概念，在安装说明文档中没看到相关说明，希望能默认开启或者重点标注一下，谢谢！
