### ISSUE TITLE
希望添加robots.txt功能

### ISSUE THREAD

**Issue by uselibrary** [alist-org/alist#4303]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望添加`robots.txt`功能，比避免网站被全网搜索引擎收录。

**Comment by mengguyi** [comment]
你可能需要[nginx](http://www.nginx.org)

**Comment by m0ch3** [comment]
全局设置-自定义头部 新一行追加这个`<meta name="robots" content="noindex">`

参考[使用 noindex 阻止搜索引擎编入索引](https://developers.google.com/search/docs/crawling-indexing/block-indexing?rd=1&hl=zh-cn)
