### ISSUE TITLE
希望可以增加百度网盘自身的播放渠道，例如阿里云Aliyun Video Previewer。

### ISSUE THREAD

**Issue by SwePolice** [alist-org/alist#4305]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前百度网盘播放视频的时候很卡，使用本地代理也无法有效解决问题，增设百度自身视频播放接口，这样是否可以有效解决百度网盘视频播放问题。

**Comment by anwen-anyi** [comment]
就算是增设百度网盘的自身视频播放接口，该需要会员还是需要会员
而且现在百度的也没一定需要你使用`本地代理`播放
直接使用302播放（记得改UA头）在有会员的前提下速度也是直接拉满的
所以木有必要浪费精力去弄一个~

**Comment by SwePolice** [comment]
> 就算是增设百度网盘的自身视频播放接口，该需要会员还是需要会员 而且现在百度的也没一定需要你使用`本地代理`播放 直接使用302播放（记得改UA头）在有会员的前提下速度也是直接拉满的 所以木有必要浪费精力去弄一个~

我目前有用一个猫头鹰文件的文件管理器，挂载百度网盘能够正常播放视频，但是alist挂载百度网盘后，同样没有会员，就无法正常播放
