### ISSUE TITLE
如果能有个指纹识别就更好了

### ISSUE THREAD

**Issue by xioqing** [alist-org/alist#4311]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

其实不是必须的功能, 只是每次打密码或者二次验证输入验证码难免有点麻烦. 
谢谢.

**Comment by anwen-anyi** [comment]
确实不是必要的 二次验证的初衷就是安全一些🥲
意味着可能麻烦一点儿
鱼和熊掌不可兼得🤓

**Comment by KarLYelin** [comment]
还不如买个物理的 USB 安全密钥
集成 Windows Hello 没什么用

**Comment by Carlos920** [comment]
> 还不如买个物理的 USB 安全密钥 集成 Windows Hello 没什么用

他应该指的是[webauthn](https://webauthn.io/)

**Comment by xioqing** [comment]
我指的是 FIDO 或者 Security keys (GitHub里是这么写的)

**Comment by Carlos920** [comment]
> 我指的是 FIDO 或者 Security keys (GitHub里是这么写的)

webauthn就是调用设备的指纹识别等进行身份认证（如果浏览器支持的话，安卓的chrome,edge,firefox均支持，pc需要设备支持指纹或者winhello等）

**Comment by xioqing** [comment]
> > 我指的是 FIDO 或者 Security keys (GitHub里是这么写的)
> 
> webauthn就是调用设备的指纹识别等进行身份认证（如果浏览器支持的话，安卓的chrome,edge,firefox均支持，pc需要设备支持指纹或者winhello等）
> 
> 一些相关构建方式：
> 
> * https://developers.google.com/codelabs/webauthn-reauth
> * https://learn.microsoft.com/zh-cn/microsoft-edge/devtools-guide-chromium/webauthn/
> 
> 演示网站：
> 
> * https://try-webauthn.appspot.com/
> * https://webauthn.io/
嗯, 那就是你说的这个
