### ISSUE TITLE
希望单点登录开放标准的oidc协议

### ISSUE THREAD

**Issue by qxa792** [alist-org/alist#4315]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望单点登录开放标准的oidc协议
可以使用自己的oidc服务器进行登录，配置统一的路径就行了

**Comment by anwen-anyi** [comment]
`oidc`协议是什么协议，最近尝试了一下 `Casdoor` 这个感觉更方便 :joy_cat: :joy_cat:

**Comment by thomasdba** [comment]
支持，通用性更好

**Comment by ty114514** [comment]
+1，就跟 s3 一样，可以支持任意 endpoint

**Comment by qxa792** [comment]
> `oidc`协议是什么协议，最近尝试了一下 `Casdoor` 这个感觉更方便 😹 😹

openid connect

**Comment by itsdapi** [comment]
希望文档能更新一下oidc教程
