### ISSUE TITLE
夸克网盘使用cloudflare代理下载，流量还是会由本机代理

### ISSUE THREAD

**Issue by xiaqijun** [alist-org/alist#4318]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/130994988/236459539-d0d6173b-f6c1-499c-91f5-e5d36c5b439c.png)
这里已经跳转到了cloudflare,但是观察本机的流量和日志可以发现cloudflare，将请求又发到了本机，由本机进行代理。
![image](https://user-images.githubusercontent.com/130994988/236459796-d21200bd-7a86-46e9-b139-4dbd6d1f7d28.png)
以下是web日志信息
172.70.211.86 - - [05/May/2023:20:39:48 +0800] ＂GET /p/%E5%A4%B8%E5%85%8B/%E9%AC%BC%E7%81%AD%E4%B9%8B%E5%88%83%E7%AC%AC%E4%B8%80%E9%9B%86.mp4?d&amp;sign=b5BCsvD_LyDMlQzY1A9wKtqob_rpmwL89iPbEtk0gnA=:1683293848 HTTP/2.0＂ 200 311599329 ＂-＂ ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68＂
172.70.211.86是cloudflare的地址。

### Reproduction / 复现链接

https://cloudreve.dongling.xyz/%E5%A4%B8%E5%85%8B/%E9%AC%BC%E7%81%AD%E4%B9%8B%E5%88%83%E7%AC%AC%E4%B8%80%E9%9B%86.mp4

**Comment by xiaqijun** [comment]
天翼网盘客户端使用代理地址下载就没有问题

**Comment by Xhofe** [comment]
由于限速问题，夸克网盘现在必须走本机流量 
https://github.com/alist-org/alist/blob/ee6c31332d4e6ee2c1db187ce075d08f9780eacc/drivers/quark/meta.go#L17

**Comment by xiaqijun** [comment]
> 由于限速问题，夸克网盘现在必须走本机流量
> 
> https://github.com/alist-org/alist/blob/ee6c31332d4e6ee2c1db187ce075d08f9780eacc/drivers/quark/meta.go#L17

好的，感谢解答

**Comment by culilaren** [comment]
docker 版本怎么设置？能不能具体点？

**Comment by boobb** [comment]
> 由于限速问题，夸克网盘现在必须走本机流量
> 
> https://github.com/alist-org/alist/blob/ee6c31332d4e6ee2c1db187ce075d08f9780eacc/drivers/quark/meta.go#L17

不好意思才开始玩，能不能请教一下这个该如何修改

**Comment by acloudtwei** [comment]
如果夸克网盘是会员的话，能否不走本地代理？

**Comment by xiaqijun** [comment]
> 如果夸克网盘是会员的话，能否不走本地代理？

写死了，只能本地

**Comment by acloudtwei** [comment]
> > 如果夸克网盘是会员的话，能否不走本地代理？
> 
> 写死了，只能本地

那怎么办？我的是会员，服务器带宽很低，能否有办法选择走会员通道？

**Comment by xiaqijun** [comment]
> > > 如果夸克网盘是会员的话，能否不走本地代理？
> > 
> > 
> > 写死了，只能本地
> 
> 那怎么办？我的是会员，服务器带宽很低，能否有办法选择走会员通道？

没有办法

**Comment by acloudtwei** [comment]
> > > > 如果夸克网盘是会员的话，能否不走本地代理？
> > > 
> > > 
> > > 写死了，只能本地
> > 
> > 
> > 那怎么办？我的是会员，服务器带宽很低，能否有办法选择走会员通道？
> 
> 没有办法

哪个版本的docker还是支持走会员通道的夸克网盘？

**Comment by xiaqijun** [comment]
> 哪个版本的docker还是支持走会员通道的夸克网盘？
目前只能走本地代理

**Comment by Maxice** [comment]
现在夸克的Cookie 已经被藏起来来了吧, 怎么找到呢

**Comment by vbnm159** [comment]
请问使用本地代理会伤硬盘吗，是否有这种说法，纯小白，求解答

**Comment by vpei** [comment]
出错了，不能按文件名正常排序？

**Comment by ENIAC1729** [comment]
> 由于限速问题，夸克网盘现在必须走本机流量
> 
> https://github.com/alist-org/alist/blob/ee6c31332d4e6ee2c1db187ce075d08f9780eacc/drivers/quark/meta.go#L17

如果有会员可以走代理吗？

**Comment by dsc-bjmn** [comment]
夸克挂载之后，打开就是这样的：failed get objs: failed to list objs: query fail [61008]
有没有大佬现在能挂载成功的啊？求指点……

**Comment by Mosaic-c** [comment]
> 夸克挂载之后，打开就是这样的：failed get objs: failed to list objs: query fail [61008]
> 有没有大佬现在能挂载成功的啊？求指点……

配置储存界面的“排序”不要选择“文件排序”

**Comment by Vector-zip** [comment]
> > 夸克挂载之后，打开就是这样的：failed get objs: failed to list objs: query fail [61008]
> > 有没有大佬现在能挂载成功的啊？求指点……
> 
> 配置储存界面的“排序”不要选择“文件排序”

还是不行诶，还是访客模式

**Comment by Mosaic-c** [comment]
> > > 夸克挂载之后，打开就是这样的：failed get objs: failed to list objs: query fail [61008]
> > > 有没有大佬现在能挂载成功的啊？求指点……
> > 
> > 
> > 配置储存界面的“排序”不要选择“文件排序”
> 
> 还是不行诶，还是访客模式

你这个是用户权限管理的问题吧...

**Comment by Vector-zip** [comment]
> > > > 夸克挂载之后，打开就是这样的：failed get objs: failed to list objs: query fail [61008]
> > > > 有没有大佬现在能挂载成功的啊？求指点……
> > > 
> > > 
> > > 配置储存界面的“排序”不要选择“文件排序”
> > 
> > 
> > 还是不行诶，还是访客模式
> 
> 你这个是用户权限管理的问题吧...

我就是这样设置的是不是没问题，我用edge或者Chrome的cookie都一样，管理权限咋设置，没看见网盘有这个设置选项。
![存储-AList-管理](https://github.com/user-attachments/assets/0f06d62f-4458-4405-8c02-9359436420fb)

**Comment by Vector-zip** [comment]
> 你去alist的用户设置那里看看呗，是不是你的用户对网盘没有管理权限
> 
> > > > > > 夸克挂载之后，打开就是这样的：failed get objs: failed to list objs: query fail [61008]
> > > > > > 有没有大佬现在能挂载成功的啊？求指点……
> > > > > 
> > > > > 
> > > > > 配置储存界面的“排序”不要选择“文件排序”
> > > > 
> > > > 
> > > > 还是不行诶，还是访客模式
> > > 
> > > 
> > > 你这个是用户权限管理的问题吧...
> > 
> > 
> > 我就是这样设置的是不是没问题，我用edge或者Chrome的cookie都一样，管理权限咋设置，没看见网盘有这个设置选项。 ![存储-AList-管理](https://private-user-images.githubusercontent.com/63224094/359040756-0f06d62f-4458-4405-8c02-9359436420fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDk5NzgsIm5iZiI6MTcyNDI0OTY3OCwicGF0aCI6Ii82MzIyNDA5NC8zNTkwNDA3NTYtMGYwNmQ2MmYtNDQ1OC00NDA1LThjMDItOTM1OTQzNjQyMGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MzVlOTExNjJkYjk5YjM2MDc3ZTE1Yzg4MWY4ZmI2NWJmOTM1MzFkM2VmNDQzNGYxYTcyODM3NTNkMzYwYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._BluQK4kIZOUjMMT776UA6Ux5coeDyFNMibUTe8Y05o)
> 
> 你去alist的用户设置那里看看呗，是不是你的用户对网盘没有管理权限

可我用的是admin登录的都勾上了

**Comment by Mosaic-c** [comment]
> > 你去alist的用户设置那里看看呗，是不是你的用户对网盘没有管理权限
> > > > > > > 夸克挂载之后，打开就是这样的：failed get objs: failed to list objs: query fail [61008]
> > > > > > > 有没有大佬现在能挂载成功的啊？求指点……
> > > > > > 
> > > > > > 
> > > > > > 配置储存界面的“排序”不要选择“文件排序”
> > > > > 
> > > > > 
> > > > > 还是不行诶，还是访客模式
> > > > 
> > > > 
> > > > 你这个是用户权限管理的问题吧...
> > > 
> > > 
> > > 我就是这样设置的是不是没问题，我用edge或者Chrome的cookie都一样，管理权限咋设置，没看见网盘有这个设置选项。 ![存储-AList-管理](https://private-user-images.githubusercontent.com/63224094/359040756-0f06d62f-4458-4405-8c02-9359436420fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDk5NzgsIm5iZiI6MTcyNDI0OTY3OCwicGF0aCI6Ii82MzIyNDA5NC8zNTkwNDA3NTYtMGYwNmQ2MmYtNDQ1OC00NDA1LThjMDItOTM1OTQzNjQyMGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MzVlOTExNjJkYjk5YjM2MDc3ZTE1Yzg4MWY4ZmI2NWJmOTM1MzFkM2VmNDQzNGYxYTcyODM3NTNkMzYwYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._BluQK4kIZOUjMMT776UA6Ux5coeDyFNMibUTe8Y05o)
> > 
> > 
> > 你去alist的用户设置那里看看呗，是不是你的用户对网盘没有管理权限
> 
> 可我用的是admin登录的都勾上了

辣就不知道噜

**Comment by Vector-zip** [comment]
> > > 你去alist的用户设置那里看看呗，是不是你的用户对网盘没有管理权限
> > > > > > > > 夸克挂载之后，打开就是这样的：failed get objs: failed to list objs: query fail [61008]
> > > > > > > > 有没有大佬现在能挂载成功的啊？求指点……
> > > > > > > 
> > > > > > > 
> > > > > > > 配置储存界面的“排序”不要选择“文件排序”
> > > > > > 
> > > > > > 
> > > > > > 还是不行诶，还是访客模式
> > > > > 
> > > > > 
> > > > > 你这个是用户权限管理的问题吧...
> > > > 
> > > > 
> > > > 我就是这样设置的是不是没问题，我用edge或者Chrome的cookie都一样，管理权限咋设置，没看见网盘有这个设置选项。 ![存储-AList-管理](https://private-user-images.githubusercontent.com/63224094/359040756-0f06d62f-4458-4405-8c02-9359436420fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDk5NzgsIm5iZiI6MTcyNDI0OTY3OCwicGF0aCI6Ii82MzIyNDA5NC8zNTkwNDA3NTYtMGYwNmQ2MmYtNDQ1OC00NDA1LThjMDItOTM1OTQzNjQyMGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MzVlOTExNjJkYjk5YjM2MDc3ZTE1Yzg4MWY4ZmI2NWJmOTM1MzFkM2VmNDQzNGYxYTcyODM3NTNkMzYwYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._BluQK4kIZOUjMMT776UA6Ux5coeDyFNMibUTe8Y05o)
> > > 
> > > 
> > > 你去alist的用户设置那里看看呗，是不是你的用户对网盘没有管理权限
> > 
> > 
> > 可我用的是admin登录的都勾上了
> 
> 辣就不知道噜

https://alist.nn.ci/guide/drivers/quark.html
最新的教程有了，要从源cookie获取，终于解决了

**Comment by peng-yq** [comment]
> > 如果夸克网盘是会员的话，能否不走本地代理？
> 
> 写死了，只能本地

请问您后面是怎么优化的呀？还是换其他网盘了直接。

**Comment by wanghuayu666** [comment]
> 由于限速问题，夸克网盘现在必须走本机流量 https://github.com/alist-org/alist/blob/ee6c31332d4e6ee2c1db187ce075d08f9780eacc/drivers/quark/meta.go#L17

走本地流量是什么意思？是宽带的流量吗？还是局域网的带宽？

**Comment by typenoob** [comment]
> > 由于限速问题，夸克网盘现在必须走本机流量 https://github.com/alist-org/alist/blob/ee6c31332d4e6ee2c1db187ce075d08f9780eacc/drivers/quark/meta.go#L17
> 
> 走本地流量是什么意思？是宽带的流量吗？还是局域网的带宽？

即走搭建alist的机器的流量

**Comment by Daryl-Do** [comment]
88vip的夸克会员，家里的服务器，下载速度大概6mb/s。不知道svip会不会限速，官网说的是“最高”50mb/s。 我5个t的文件备份到nas里，这么下去要导半个月。

**Comment by yuyetao123** [comment]
现在夸克TV也超级慢，是需要会员了吗

**Comment by Daryl-Do** [comment]
> 88vip的夸克会员，家里的服务器，下载速度大概6mb/s。不知道svip会不会限速，官网说的是“最高”50mb/s。 我5个t的文件备份到nas里，这么下去要导半个月。

更新一下，不同时间段的限速似乎不同，夜里速度挺快的，5个t大概导了2天时间

**Comment by MemoryClear** [comment]
alist挂载夸克，每隔一段时间无法播放网盘中的视频。日志显示cookie过期。不手动重新更新cookie的情况下，过一段时间又能正常播放。

**Comment by viocha** [comment]
> alist挂载夸克，每隔一段时间无法播放网盘中的视频。日志显示cookie过期。不手动重新更新cookie的情况下，过一段时间又能正常播放。

cookie有效期是多久
