### ISSUE TITLE
alist上传文件成功后刷新文件不出现，需要修改文件目录下的文件名或者其他操作上传的图片才出现

### ISSUE THREAD

**Issue by it-chenliang** [alist-org/alist#4320]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

当使用alist集成了`阿里云盘-open`或者`百度网盘`时，当我进入alist首页具体的目录下，然后上传文件，提示上传成功，然后刷新页面上传的文件并不会出现，而是需要我手动去修改当前目录下的具体某个文件名称(或者其他操作)时，上传的文件才会出现，这个问题该如何解决？
具体效果如下图所示: 
![GIF 2023-05-05 21-32-20](https://user-images.githubusercontent.com/34783722/236471921-1a1220b7-9250-4c3c-8976-9db9d53c629c.gif)

### Reproduction / 复现链接

![GIF 2023-05-05 21-32-20](https://user-images.githubusercontent.com/34783722/236471921-1a1220b7-9250-4c3c-8976-9db9d53c629c.gif)

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/236473252-272ff826-0c57-494c-a910-3dac1a07a331.png)
