### ISSUE TITLE
用RaiDrive挂载天翼和百度的webdav，在资源管理器里只能新建目录，不能新建文件，也不能复制粘贴文件

### ISSUE THREAD

**Issue by inmost888** [alist-org/alist#4323]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3 desktop windows

### Driver used / 使用的存储驱动

天翼和百度

### Describe the bug / 问题描述

用RaiDrive挂载天翼和百度的webdav，在资源管理器里只能新建目录，不能新建文件，也不能复制粘贴文件，需要权限

### Reproduction / 复现链接

![2023-05-06](https://user-images.githubusercontent.com/72589045/236582933-739e72da-54bd-4b68-867b-d06294467b17.png)

### Logs / 日志

![2023-05-06](https://user-images.githubusercontent.com/72589045/236582933-739e72da-54bd-4b68-867b-d06294467b17.png)

**Comment by phoeni-x-man** [comment]
同样问题 补充一点 无论上传下载都提示需要权限 阿里云盘没有这样的问题

**Comment by hongwen000** [comment]
@Xhofe 请问duplicate的issue在哪里？

**Comment by Xhofe** [comment]
- https://alist.nn.ci/zh/faq/why.html#raidrive%E6%8C%82%E8%BD%BD%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98-%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6-%E4%B8%8D%E8%83%BD%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E3%80%82%E5%BE%80%E6%8C%82%E8%BD%BD%E7%9B%AE%E5%BD%95%E4%B8%A2%E6%96%87%E4%BB%B6%E6%8F%90%E7%A4%BA-%E6%8F%90%E7%A4%BA-%E4%BD%A0%E9%9C%80%E8%A6%81%E6%9D%83%E9%99%90%E6%9D%A5%E6%89%A7%E8%A1%8C%E6%AD%A4%E6%93%8D%E4%BD%9C-%E3%80%82%E8%BF%99%E4%B8%AA%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3
- #3825
- #1639
- #3128

**Comment by hongwen000** [comment]
收到！感谢，现已换到Rclone解决该问题。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
