### ISSUE TITLE
希望增加天翼魔盘的支持

### ISSUE THREAD

**Issue by Ren9527** [alist-org/alist#4325]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

    电天翼最近新推出了一个魔盘服务，每个电信用户都能有免费50g云空间，可接入诸多服务。
望请开发者大佬提供支持服务。

**Comment by Winyer** [comment]
50G....太小了吧

**Comment by sucooer** [comment]
> 50G....太小了吧

宽带免费送会员有4t😂

**Comment by JsonSong89** [comment]
> > 50G....太小了吧
> 
> 宽带免费送会员有4t😂

我也是电信宽带用户,请问怎么操作啊? 没看到有送会员的地方

**Comment by sucooer** [comment]
我是四川电信的，魔盘也是四川电信推出的，外地不知道送不送
