### ISSUE TITLE
支持一下inscode呗

### ISSUE THREAD

**Issue by zknb-666** [alist-org/alist#4326]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使alist在inscode上运行
[inscode](https://inscode.csdn.net/@zknb-666/alist-inscode)
[github](https://github.com/zknb-666/alist-inscode)

### Suggested solution / 实现思路

参考[alist-replit](https://github.com/alist-org/alist-replit)进行修改

**Comment by Xhofe** [comment]
你这不是已经有了吗，提issue是什么意思？
