### ISSUE TITLE
123盘下载链接返回json数据，而不是blod数据

### ISSUE THREAD

**Issue by moyanj** [alist-org/alist#4331]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

下载123云盘内文件时，下载链接，返回json数据。可以解析，其中redirect_url为真正的文件下载地址

### Reproduction / 复现链接

https://alist.moyanjdc.top/d/%E6%8A%95%E6%A0%87%E4%B9%A6.docx

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/236679328-c1abe99c-e322-43f8-8488-49f9efa1ac49.png)
