### ISSUE TITLE
下载123云盘内文件时，返回json数据

### ISSUE THREAD

**Issue by moyanj** [alist-org/alist#4332]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

下载123云盘内文件时，下载链接，返回json数据。可以解析，其中redirect_url为真正的文件下载地址,有clouflare缓存

### Reproduction / 复现链接

https://alist.moyanjdc.top/d/%E6%8A%95%E6%A0%87%E4%B9%A6.docx

### Logs / 日志

没有日志，但的确是3.16.3
<img src ='https://img1.imgtp.com/2023/05/07/Z1vTfUqs.jpg'>

**Comment by Xhofe** [comment]
你发的地址就是3.16.0，这个问题已经在https://github.com/alist-org/alist/commit/9d55ad3af61e379ea372084ed46076e73be454e6 这个提交中被修复。

未命中缓存，版本仍是3.16.0：
![image](https://user-images.githubusercontent.com/36558727/236680796-7982844f-eecd-4c15-bf43-c5b355823553.png)

**Comment by moyanj** [comment]
这真的是3.16.3,只是datas.db是3.16.0的

**Comment by Xhofe** [comment]
我可以有多种办法证明你这是3.16.0的版本：
- api中返回的版本号虽然在数据库中有存储，但是都是硬编码在代码中编译时注入的版本号，每次启动都会更新到数据库中；
- 使用的静态资源hash值也是3.16.0中的：https://unpkg.com/browse/alist-web@3.16.0/dist/assets/index.6067d580.js
![image](https://user-images.githubusercontent.com/36558727/236681108-b41c5748-a45d-438d-93f2-de7b197e44dc.png)
 在最新的版本号中，这个hash值不存在：https://unpkg.com/browse/alist-web@3.16.2/dist/assets/index.6067d580.js
