### ISSUE TITLE
WebDAV 经常性异常，可以读取目录但无法读取文件

### ISSUE THREAD

**Issue by BrandonStudio** [alist-org/alist#4335]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.16.3

### Driver used / 使用的存储驱动

irrelevant

### Describe the bug / 问题描述

无法使用WebDAV读取文件内容，但可以浏览目录。

重新启动alist服务可以解决此问题，但是有可能一段时间后重新出现此问题

此问题不是升级后出现的。2022年11月的版本就有此问题。

此问题与网盘驱动无关，与WebDAV客户端无关，因为多个网盘驱动和WebDAV客户端都遇到此问题。

### Reproduction / 复现链接

问题具有偶发性，不能稳定复现

### Logs / 日志

![image](https://user-images.githubusercontent.com/55647556/236733221-37da1537-1f86-4e42-b719-bd3fcacd8051.png)

**Comment by Xhofe** [comment]
最起码的日志。

**Comment by Xhofe** [comment]
你提供的内容中无有效信息，我们无法定位问题。
