### ISSUE TITLE
alist-web 应该同步 Crowdin 的 i18n 文件

### ISSUE THREAD

**Issue by ty114514** [alist-org/alist#4336]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题，alist-web 仓库中只存在英语，而 web-dist 是已经构建完成的产物，在修改前端时没法使用，无本地化的调试体验也不够友好
作为本项目的一部分，多国语言翻译应一并同步
猜测只有英语可能是防止通过 Github 进行贡献翻译导致 PR 页看上去很乱，但这不太利于二次开发，所以还请放行

**Comment by ty114514** [comment]
Sorry，发之前没检索，以为小众需求不会有人提
那就再补充一下，有没有考虑使用 Action 自动从 Crowdin 上同步翻译资源呢

**Comment by Xhofe** [comment]
- 如果你想二次开发自己用，你可以直接在Crowdin 中下载语言文件解压即可，它是开放的并不是私有；
- 如果你想贡献源项目，那么并不需要关注语言文件只用提交英文文件，其他翻译均在Crowdin 上完成。
所以，暂不考虑。
