### ISSUE TITLE
元信息中的写入权限不生效

### ISSUE THREAD

**Issue by gyf9835** [alist-org/alist#4337]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

想实现的功能：
让/media目录下变为只读

操作：
新增元信息，路径`/media`，写入关闭，打开`应用到子文件夹`，说明中填写'禁止写入'

结果：
以普通用户在无痕模式登录，可以看到说明，但是可以正常创建文件和文件夹，已尝试过重启容器和重新登录

补充：
docker部署，xhofe/alist-aria2:latest

### Reproduction / 复现链接

http://127.0.0.1:5244/@manage/metas/edit/1
因为还在试用阶段，没有映射到公网

**Comment by Xhofe** [comment]
meta仅对访客用户生效，登录用户仅受编辑用户编辑下面的权限设置影响。

**Comment by gyf9835** [comment]
我觉得有以下两点可以改进，可以的话我会提交PR
1. 文档中对于写入的说明是：`允许访客新建目录、新文件和上传文件`。`访客`和登录页面中的`游客`不对应，可否将文档中的`访客`改为`游客`消除歧义？
2. 设置页面上的`写入`文案可否更改为`游客写入`，因为`写入`的作用域为游客，而同页面下其他配置项的作用域为所有用户，容易产生误解

另外对于`写入`功能，我觉得有些不合理
3. 游客和普通用户一样有权限设置，为什么写入功能只针对游客呢？
4. 和 #3789 一样，写入权限能否覆盖更多用户？
