### ISSUE TITLE
readme说明无法覆盖子目录

### ISSUE THREAD

**Issue by cancundeyingzi** [alist-org/alist#4342]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.16

### Driver used / 使用的存储驱动

本地、阿里

### Describe the bug / 问题描述

举例：
有A,B两个目录
元信息根目录写了说明，开应用到子目录
元信息A目录加了密码，写入打开，没写说明
结果：
根目录和B目录有说明。A没有

### Reproduction / 复现链接

ipv6.cancundeyingzi.xyz:5244
里面有测试文件夹

**Comment by Xhofe** [comment]
只能获取最近的meta信息，你的A目录设置了自己的meta，那么肯定会以它自身的meta记录为准。

**Comment by cancundeyingzi** [comment]
经过测试，存储方式为本机目录时没有这个bug，其他情况有这个bug

**Comment by cancundeyingzi** [comment]
> 只能获取最近的meta信息，你的A目录设置了自己的meta，那么肯定会以它自身的meta记录为准。这是预期行为。

![image](https://user-images.githubusercontent.com/73635883/236787749-d8a95220-cac8-4c91-91a0-48c02ceeb7c1.png)
那这个路径下依旧有说明,,所以还是有bug
![image](https://user-images.githubusercontent.com/73635883/236788034-6d9e9662-b8e6-4c24-bd14-85af3238afcf.png)

**Comment by Xhofe** [comment]
> > 只能获取最近的meta信息，你的A目录设置了自己的meta，那么肯定会以它自身的meta记录为准。这是预期行为。
> 
> 那这个路径下依旧有说明,,所以还是有bug ![image](https://user-images.githubusercontent.com/73635883/236787749-d8a95220-cac8-4c91-91a0-48c02ceeb7c1.png) 那这个路径下依旧有说明,,所以还是有bug ![image](https://user-images.githubusercontent.com/73635883/236788034-6d9e9662-b8e6-4c24-bd14-85af3238afcf.png)

这是因为你这个路径下有个名为`README.md`的文件。
