### ISSUE TITLE
右键菜单和left-toolbar-box的位置

### ISSUE THREAD

**Issue by koolca** [alist-org/alist#4344]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

当页面高度超过一个屏幕，右键菜单的位置没有落在鼠标周围，同时希望三个圆点left-toolbar-box的位置能跟随页面滚动，或者能拖动，因为偶尔会挡住视频播放的菜单，谢谢！

**Comment by koolca** [comment]
就是当页面超过一个屏幕长度，出现了滚动条，此时将页面滚动到下面，在列表上点击右键，出现的右键菜单位置不对

**Comment by Xhofe** [comment]
![image](https://github.com/alist-org/alist/assets/36558727/f96443d8-2daf-492d-8975-c76da63624bf)

**Comment by koolca** [comment]
@Xhofe 不好意思，这个问题好像与我自己加入的javascript脚本有关，我再定位一下，再次感谢！
