### ISSUE TITLE
能否实现上传直传

### ISSUE THREAD

**Issue by GreenTeodoro839** [alist-org/alist#4348]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

下载现在是直链，但是上传会警告服务器，国外服务器传阿里云盘比较慢。有没有办法实现上传直传？

**Comment by anwen-anyi** [comment]
做不到 我记得之前哪里说过 但是找不到了

**Comment by swRains** [comment]
买北京的阿里云服务器有内部上传

**Comment by GreenTeodoro839** [comment]
> 做不到 我记得之前哪里说过 但是找不到了

但是cloudreve onemanager等都能做到

**Comment by anwen-anyi** [comment]
> > 做不到 我记得之前哪里说过 但是找不到了
> 
> 
> 
> 但是cloudreve onemanager等都能做到

…… 大概意思就是AList要照顾所有云盘的上传无法直接上传

Tips:不建议使用AList来上传大文件/多文件

**Comment by Winyer** [comment]
> > > 做不到 我记得之前哪里说过 但是找不到了
> > 
> > 
> > 但是cloudreve onemanager等都能做到
> 
> …… 大概意思就是AList要照顾所有云盘的上传无法直接上传
> 
> Tips:不建议使用AList来上传大文件/多文件

所以用webdav复制文件进网盘的时候也是走的服务器流量？
