### ISSUE TITLE
阿里云Open秒传

### ISSUE THREAD

**Issue by kunger97** [alist-org/alist#4352]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://www.yuque.com/aliyundrive/zpfszx/ezlzok 阿里云Open接口现在已经开放秒传相关的参数，希望可以支持秒传

### Suggested solution / 实现思路

逻辑应该和旧版类似吧

**Comment by anwen-anyi** [comment]
你小子可真快 :joy: :joy_cat: 今天才上线的
