### ISSUE TITLE
api链接访问不良

### ISSUE THREAD

**Issue by swRains** [alist-org/alist#4354]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://api.nn.ci/alist/ali_open/token
该链接api网络访问不良，我家里四播四公网ip，能有两个访问不了。在腾讯云服务器上也偶尔失效。但是都能ping通，curl无返回值。能否支持自建镜像服务器，用host重定向以减缓此网络问题。

如果带宽开销不大的话我可以提供一台腾讯云服务器。

**Comment by Xhofe** [comment]
你可以直接反代这个接口，然后将 OauthTokenURL 改为你反代后的链接即可。

**Comment by swRains** [comment]
反代的服务器有时候也有概率访问不了啊，而且不是人人都有云服务器。
即便说我共享我返代的链接，由于api请求限制，一个反代服务器也就只能支持七个alist服务

**Comment by wbc389561407** [comment]
我如果自己搞个接口是否就可以了&nbsp;有代码&nbsp;或者教程吗，期待大佬回复







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alist-org/alist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 中午1:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alist-org/alist] api链接访问不良 (Issue #4354)





 
反代的服务器有时候也有概率访问不了啊，而且不是人人都有云服务器。
 即便说我共享我返代的链接，由于api请求限制，一个反代服务器也就只能支持七个alist服务

**Comment by Xhofe** [comment]
这是交换token服务部分的代码，https://github.com/alist-org/auth/blob/main/ali_open.go

- 但是你需要去向官方申请client，我无法直接分享client，只能提供交换token的服务。
- 如果你有自己申请的client，那么你也不需要搭建后端服务，直接在https://alist.nn.ci/zh/guide/drivers/aliyundrive_open.html#%E5%AE%A2%E6%88%B7%E7%AB%AF-id-%E7%A7%98%E9%92%A5 填写client就行。

**Comment by swRains** [comment]
> 这是交换token服务部分的代码，https://github.com/alist-org/auth/blob/main/ali_open.go
> 
> * 但是你需要去向官方申请client，我无法直接分享client，只能提供交换token的服务。
> * 如果你有自己申请的client，那么你也不需要搭建后端服务，直接在https://alist.nn.ci/zh/guide/drivers/aliyundrive_open.html#%E5%AE%A2%E6%88%B7%E7%AB%AF-id-%E7%A7%98%E9%92%A5 填写client就行。

感谢

**Comment by wbc389561407** [comment]
感谢




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alist-org/alist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 中午1:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alist-org/alist] api链接访问不良 (Issue #4354)





  
这是交换token服务部分的代码，https://github.com/alist-org/auth/blob/main/ali_open.go
  
但是你需要去向官方申请client，我无法直接分享client，只能提供交换token的服务。
 
如果你有自己申请的client，那么你也不需要搭建后端服务，直接在https://alist.nn.ci/zh/guide/drivers/aliyundrive_open.html#%E5%AE%A2%E6%88%B7%E7%AB%AF-id-%E7%A7%98%E9%92%A5 填写client就行。
   
感谢

**Comment by anwen-anyi** [comment]
昨天开始。开发者上游服务器提供商被攻击了 然后被连带了(群友说的) 应该是因为这个吧🥲

**Comment by swRains** [comment]
> 昨天开始。开发者上游服务器提供商被攻击了 然后被连带了(群友说的) 应该是因为这个吧🥲

是的，运营商上游服务器被攻击了，然后国际线路还被切了，导致国内访问出现问题

**Comment by swRains** [comment]
阿里云盘开发者我之前申请了几次都没联系我，是有啥要求吗

**Comment by kilvn** [comment]
留个脚印

**Comment by leifeng-N** [comment]
Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by Xhofe** [comment]
已经将后端服务迁到香港服务器了 还不能用的话 我也没得办法了

**Comment by Xhofe** [comment]
源api：
- https://api.nn.ci/alist/ali_open/token

提供两个备用：
- https://api.xhofe.top/alist/ali_open/token (腾讯云上海，	2023-11-18 到期)
- https://api-cf.nn.ci/alist/ali_open/token (套了一层cloudflare)

若源api无法连接，可在备用中选择一个。

**Comment by swRains** [comment]
> 源api：
> 
> * https://api.nn.ci/alist/ali_open/token
> 
> 提供两个备用：
> 
> * https://api.xhofe.top/alist/ali_open/token (腾讯云上海，	2023-11-18 到期)
> * https://api-cf.nn.ci/alist/ali_open/token (套了一层cloudflare)
> 
> 若源api无法连接，可在备用中选择一个。

感谢！

**Comment by kilvn** [comment]
我有甲骨文首尔和春川闲置，如果需要可以发可执行文件，在我在我的服务器提供备用节点服务。
