### ISSUE TITLE
使用AList上传文件至Teambition无法使用阿里云张家口oss地址

### ISSUE THREAD

**Issue by Mcxunyun666** [alist-org/alist#4365]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

Teambition

### Describe the bug / 问题描述

在使用AList上传文件至Teambition存储时会发现调用的是 `https://tcs.teambition.net` 地址，并非通过teambition官方web端上传时所调用的阿里云张家口oss地址 `https://teambition-file.oss-cn-zhangjiakou.aliyuncs.com`。

经过测试，使用AList所调用的 `https://tcs.teambition.net` 地址上传的文件无论从AList还是官方Web客户端再次下载时依旧是`https://tcs.teambition.net` 地址，而且上传速度和连接质量不如阿里云张家口oss地址 `https://teambition-file.oss-cn-zhangjiakou.aliyuncs.com`。

![批注 2023-05-11 104754](https://github.com/alist-org/alist/assets/51842260/1ed4088b-b3f7-450e-8955-420ecb9703b6)

但是如果预先通过官方Web客户端上传文件，就会发现无论从AList还是官方Web客户端下载文件均调用的是阿里云张家口oss地址 `https://teambition-file.oss-cn-zhangjiakou.aliyuncs.com`，且速度和连接质量较为优良。

![浏览器上传](https://github.com/alist-org/alist/assets/51842260/e68a1bb1-7391-4732-954a-10a84e402e95)
![浏览器上传2](https://github.com/alist-org/alist/assets/51842260/cd6229d3-82cb-4c4f-8eae-3013b31bf0bd)

附上GIF：
使用AList下载：
![alist测试](https://github.com/alist-org/alist/assets/51842260/8b75af93-8998-47d2-bf97-69a25324c403)

使用官方Web客户端下载：
![官方web测试](https://github.com/alist-org/alist/assets/51842260/937c7dec-e743-490f-9c0b-d205615eb2f3)

### Reproduction / 复现链接

这里有我的测试文件，已经预先分别注明好了类型了：https://l.oxyxc.top/qa6cz

### Logs / 日志

none

**Comment by anwen-anyi** [comment]
标签应该是 `enhancement` 而不是`bug`

**Comment by Mcxunyun666** [comment]
> 标签应该是 `enhancement` 而不是`bug`

嗯。。。怎么说呢。。。我也是觉得很难确定是 `enhancement` 还是 `bug` 。因为alist调用api的方式（或者使用的API？）和官方不一致导致了部分影响？。。

很难决定。。。
