### ISSUE TITLE
天翼云盘提示「您的密码安全级别过低，请重置密码」

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [alist-org/alist#4368]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3 

### Driver used / 使用的存储驱动

天翼云盘／天翼云盘客户端

### Describe the bug / 问题描述

直接用网页浏览器是可以登录的
Alist 挂载时提示「obtained, msg: 您的密码安全级别过低，请重置密码 」

### Reproduction / 复现链接

http://localhost:5244

### Logs / 日志

![图片](https://github.com/alist-org/alist/assets/14090545/8dbcd7bd-79fa-4518-acda-5e9bcf7a75e6)

**Comment by Xhofe** [comment]
所以你重置密码了吗

**Comment by LakeishaKowalczyk** [comment]
> 所以你重置密码了吗

重置过的，16 位大小写字母数字下划线特殊符号

**Comment by Xhofe** [comment]
请下载189pc客户端尝试登录。

**Comment by LakeishaKowalczyk** [comment]
经过为期 48 小时的长期观察研究论证，应该是挂载「天翼云盘（非客户端）」触发的风控，修改密码后只要再次挂载就会反复触发
单独使用「天翼云盘客户端」，避免触碰非客户端版，运行稳定
