### ISSUE TITLE
网页端文本乱码，找不到修改文件编码格式的入口

### ISSUE THREAD

**Issue by CleMooling** [alist-org/alist#4369]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.16.3（1Panel面板安装/docker）

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

上传的lrc歌词在网页端全部乱码，不影响文件名。
没有找到修改文件管理编码格式的入口，也不清楚Alist默认使用什么编码方式
如有需要，可以提供搭建的网盘地址以及测试的账号密码
浏览器是Microsoft Edge最新正式版（PC），其他端尚未测试

### Reproduction / 复现链接

暂无

### Logs / 日志

暂无

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/issues/4131#issuecomment-1505338234

仅支持utf-8。

**Comment by CleMooling** [comment]
> [#4131 (comment)](https://github.com/alist-org/alist/issues/4131#issuecomment-1505338234)
> 
> 仅支持utf-8。

强烈要求在项目文档明确说明这一点

**Comment by anwen-anyi** [comment]
> > [#4131 (comment)](https://github.com/alist-org/alist/issues/4131#issuecomment-1505338234)
> > 仅支持utf-8。
> 
> 强烈要求在项目文档明确说明这一点

这就加上~
