### ISSUE TITLE
希望添加一个退出登录功能

### ISSUE THREAD

**Issue by GomoXU** [alist-org/alist#4370]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

登陆成游客账户就没法进管理员账户管理，还得手动删除token，实在不大方便

**Comment by WANGFYPHYS** [comment]
管理页面右上角有退出图标，希望主页面也保留这个图标呀，不然每次退出需要进入管理页才行的。 @xhofe

**Comment by sakuyamaij** [comment]
> 管理页面右上角有退出图标，希望主页面也保留这个图标呀，不然每次退出需要进入管理页才行的。 @xhofe

的确，我是搜到这个issue才知道怎么登出的...

**Comment by fluidcat** [comment]
看了管理页面的登出，提供个思路：
全局-自定义内容，加一段js把版权替换成登出
```html
<script>const interval=setInterval(()=>{const footer=document.querySelector('.footer');if(footer){const firstLink=footer.querySelector('a');if(firstLink){firstLink.href='@login';firstLink.textContent='登出';firstLink.removeAttribute('target');clearInterval(interval);}}},100);</script>
```
没去看有没有真正的登出api，要是有用href登出api即可

仅供参考
