### ISSUE TITLE
挂载小雅alist显示   the site does not allow mounted

### ISSUE THREAD

**Issue by ooyyee** [alist-org/alist#4371]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.163,3.162

### Driver used / 使用的存储驱动

openwrt

### Describe the bug / 问题描述

挂载本地docker,3.161没有问题.

### Reproduction / 复现链接

http://alist.xiaoya.pro/

**Comment by Xhofe** [comment]
#4218

**Comment by xiaoyaliu00** [comment]
执行下面神秘的代码，你就能获取token

docker exec -i xiaoya sqlite3 data/data.db <<EOF
select value from x_setting_items where key = "token";
EOF

把获取的token填入“令牌”处，把用户名和密码留空

**Comment by wangrui1573** [comment]
> 

牛逼，可以了

**Comment by wangrui1573** [comment]
> 执行下面神秘的代码，你就能获取token
> 
> docker exec -i xiaoya sqlite3 data/data.db <<EOF select value from x_setting_items where key = "token"; EOF
> 
> 把获取的token填入“令牌”处，把用户名和密码留空

9月份又不行了

failed get objs: storage not init: Get "http://************92:5678/api/me": dial tcp ************92:5678: connect: connection refused

**Comment by wangrui1573** [comment]
现在直接查看 配置文件下的 alist_auth_token.txt 就好了，楼上是没更新，或者token不对

**Comment by whguorong** [comment]
[
![Screenshot](https://github.com/user-attachments/assets/ae721a00-72cf-47b0-9a52-a3f92c6714d7)
](url)

令牌按照上面友友提示搞好了，但保存时失败，上图所示问题。到底哪里出问题了呢

**Comment by psyhl** [comment]
> <img alt="截屏2023-06-26 22 18 00" width="957" src="https://private-user-images.githubusercontent.com/116001228/248833279-c0ee457d-5da2-4480-b303-ee238b2e9888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjczMjEsIm5iZiI6MTcyODgyNzAyMSwicGF0aCI6Ii8xMTYwMDEyMjgvMjQ4ODMzMjc5LWMwZWU0NTdkLTVkYTItNDQ4MC1iMzAzLWVlMjM4YjJlOTg4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMzQzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODY0ZWRmNmIwOWVmNjM2ZjJjODI2OGIzNDk2MTVjYzE4YzU1YWZkNDEyZDQwYTkzZDRhZDEzZmY4ZTcwNzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Iqq1IuUIga40Yq_YBzzVTED91OPfp1dFkOGoalvaHXY"> 你好： 输入token后成功挂载了，但是只出现了这个文件夹，点进去显示Request failed with status code 504，没有文件🤔️

我也出现了这个问题，请问你解决了吗
