### ISSUE TITLE
URLTREE(地址树), 疑似bug？

### ISSUE THREAD

**Issue by kingfren** [alist-org/alist#4372]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

URLTREE

### Describe the bug / 问题描述

在URLTREE中，添加视频直链时，可以直接播放，但是，由于有些视频名称毫无规律或者文件名过长时，根据提示填写
`视频名称:http://xxx.abc.com/video/123.mp4`
之后，只能下载，无法直接播放。

![测试截图](https://i.imgur.com/yMNnYkO.png)

### Reproduction / 复现链接

此处提供一个视频直链，如失效请回复。或任何一个视频均可测试。
`https://ks-xpc5.xpccdn.com/249d4437-f144-40cf-b143-05715ade3b7a.mp4`

**Comment by Xhofe** [comment]
所以你的文件后缀呢？
