### ISSUE TITLE
关于复制文件的后台管理

### ISSUE THREAD

**Issue by bunianguowang** [alist-org/alist#4375]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

大批量复制文件时，有的任务会失败，失败的任务需要一个一个的点击重新上传或者删除，会不会考虑增加批量删除或者重新上传功能。还有就是后台批量复制文件时，可以选择多少个任务同时进行的功能吗，默认好像是3个同时复制吧

### Suggested solution / 实现思路

希望复制功能增加一个批量重新上传或者批量删除的功能

**Comment by yubanmeiqin9048** [comment]
- https://github.com/alist-org/alist/issues/3151#issue-1557608252
