### ISSUE TITLE
建立索引时不会建立OneDrive的索引

### ISSUE THREAD

**Issue by floatanddream** [alist-org/alist#4387]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.16.3

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

建立索引时不会建立OneDrive的索引，存储在OneDrive的文件无法被搜索。

### Reproduction / 复现链接

Index cannot Search with OneDrive Storage

**Comment by anwen-anyi** [comment]
无任何问题，建议自己排查一下操作是否正确
![image](https://github.com/alist-org/alist/assets/56105412/15fb9cca-709d-427a-b398-b5a6756b7a34)

**Comment by floatanddream** [comment]
> 无法复现，建议排查一下操作是否正确
> ![image](https://github.com/alist-org/alist/assets/56105412/15fb9cca-709d-427a-b398-b5a6756b7a34)
> 

我排查出来了，是我用了数据库的第一个选项。后面选了非全文搜索再建立索引就能搜索出来了
