### ISSUE TITLE
context deadline exceeded (Client.Timeout or context cancellation while reading body)

### ISSUE THREAD

**Issue by DarremMolko** [alist-org/alist#4401]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.17.0

### Driver used / 使用的存储驱动

Google Drive, OneDrive

### Describe the bug / 问题描述

I can't copy files from my Google Drive driver to my OneDrive/OneDriveAPP driver because it always fails with the error from the title of this issue.

### Reproduction / 复现链接

Copy from Google Drive (or any other driver) to OneDrive.

### Logs / 日志

[31mERRO[0m[2023-05-16 20:47:23] error [context deadline exceeded (Client.Timeout or context cancellation while reading body)
github.com/alist-org/alist/v3/internal/op.Put
	/app/internal/op/fs.go:569
github.com/alist-org/alist/v3/internal/fs.copyFileBetween2Storages
	/app/internal/fs/copy.go:98
github.com/alist-org/alist/v3/internal/fs.copyBetween2Storages.func2
	/app/internal/fs/copy.go:76
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/app/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/app/pkg/task/manager.go:33
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1594] while run task [copy [/gdrive](/100MB.bin) to [/onedrive](/Docs)]

**Comment by plsy1** [comment]
Try changing the image version back to v3.16.3

**Comment by DarremMolko** [comment]
> Try changing the image version back to v3.16.3

Another solution is increasing the chunk size of the drivers. Anyway, this should be fixed by the next version with this commit https://github.com/alist-org/alist/commit/63de65be45b0feabc6a19c30317d997faee045d6
