### ISSUE TITLE
本地源，使用es浏览器和webdav协议，无法进行文件复制

### ISSUE THREAD

**Issue by sixiwanzi-live** [alist-org/alist#4407]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.17.0

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

当我使用es文件浏览器，用webdav协议连接到alist后台时，进行复制操作，会报错，无论是就在同一个挂载中复制，还是跨驱动复制，都一样。后台日志如下，该问题是必现。

### Reproduction / 复现链接

无

### Logs / 日志

[GIN] 2023/05/17 - 23:08:15 | 206 |   253.92313ms |     192.168.2.1 | GET      "/dav/家庭共享（勿删）/IMG_2811.MOV"
[GIN] 2023/05/17 - 23:08:19 | 401 |       4.664µs |     192.168.2.1 | PROPFIND  "/dav/"
[GIN] 2023/05/17 - 23:08:19 | 207 |    1.399987ms |     192.168.2.1 | PROPFIND  "/dav/"
[GIN] 2023/05/17 - 23:08:21 | 207 |   35.498189ms |     192.168.2.1 | PROPFIND  "/dav/temp/"
[GIN] 2023/05/17 - 23:08:23 | 207 |    33.01382ms |     192.168.2.1 | PROPFIND  "/dav/temp/"
[31mERRO[0m[2023-05-17 23:08:23] failed copy /zzz/家庭共享（勿删）/IMG_2811.MOV to /zzz/temp/IMG_2811.MOV: object not found
github.com/alist-org/alist/v3/internal/op.Get
	/home/runner/work/alist/alist/internal/op/fs.go:220
github.com/alist-org/alist/v3/internal/op.GetUnwrap
	/home/runner/work/alist/alist/internal/op/fs.go:224
github.com/alist-org/alist/v3/internal/op.Copy
	/home/runner/work/alist/alist/internal/op/fs.go:426
github.com/alist-org/alist/v3/internal/fs._copy
	/home/runner/work/alist/alist/internal/fs/copy.go:35
github.com/alist-org/alist/v3/internal/fs.Copy
	/home/runner/work/alist/alist/internal/fs/fs.go:73
github.com/alist-org/alist/v3/server/webdav.copyFiles
	/home/runner/work/alist/alist/server/webdav/file.go:57
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleCopyMove
	/home/runner/work/alist/alist/server/webdav/webdav.go:442
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/home/runner/work/alist/alist/server/webdav/webdav.go:67
github.com/alist-org/alist/v3/server.ServeWebDAV
	/home/runner/work/alist/alist/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/home/runner/work/alist/alist/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:2936
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:1995
runtime.goexit
	/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/asm_amd64.s:1598
failed to get dst dir 
[31mERRO[0m[2023-05-17 23:08:23] COPY /dav/家庭共享（勿删）/IMG_2811.MOV object not found
github.com/alist-org/alist/v3/internal/op.Get
	/home/runner/work/alist/alist/internal/op/fs.go:220
github.com/alist-org/alist/v3/internal/op.GetUnwrap
	/home/runner/work/alist/alist/internal/op/fs.go:224
github.com/alist-org/alist/v3/internal/op.Copy
	/home/runner/work/alist/alist/internal/op/fs.go:426
github.com/alist-org/alist/v3/internal/fs._copy
	/home/runner/work/alist/alist/internal/fs/copy.go:35
github.com/alist-org/alist/v3/internal/fs.Copy
	/home/runner/work/alist/alist/internal/fs/fs.go:73
github.com/alist-org/alist/v3/server/webdav.copyFiles
	/home/runner/work/alist/alist/server/webdav/file.go:57
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleCopyMove
	/home/runner/work/alist/alist/server/webdav/webdav.go:442
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/home/runner/work/alist/alist/server/webdav/webdav.go:67
github.com/alist-org/alist/v3/server.ServeWebDAV
	/home/runner/work/alist/alist/server/webdav.go:43
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/home/runner/work/alist/alist/server/webdav.go:92
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:2936
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:1995
runtime.goexit
	/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/asm_amd64.s:1598
failed to get dst dir 
[GIN] 2023/05/17 - 23:08:23 | 500 |    5.352658ms |     192.168.2.1 | COPY     "/dav/家庭共享（勿删）/IMG_2811.MOV"

**Comment by Winyer** [comment]
alist的webdav就像是摆设，复制东西进去基本上文件一多就报错，要上传还是老老实实的用客户端吧，怎么说呢，感觉alist就是什么都有，但是功能都有bug的一个产品
