### ISSUE TITLE
[BUG]升级最新版alist后，修改文本文件出错

### ISSUE THREAD

**Issue by Goooooooooood** [alist-org/alist#4408]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.17.0

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

[环境]
阿里云盘挂载为windows本地磁盘使用。

[简述]
alist从3.16.3更新至3.17.0后，直接打开修改文本文件，保存无法生效。退回3.16.3，正常了。

[过程]
平时看片遇到字幕里有翻译不对的，就会顺手改掉。改完之后，保存刷新一下就好了。但是更新至3.17.0后，保存刷新没用。打开文本显示出来，还是修改前的内容。

### Reproduction / 复现链接

本来怕这个功能用的人少，没想提这个issue。转念一想，万一其他人也有遇到呢，万一开发者就修复了这个问题呢，还是来碰碰运气提交一下。

[更新]
今天又装上3.17.0测试，故障出现了变化，变成了更令人困惑的IO错误：
https://github.com/alist-org/alist/issues/4408#issuecomment-1552407005
上传了个几十秒的视频，演示操作和报错过程：
https://github.com/alist-org/alist/issues/4408#issuecomment-1552441702

### Logs / 日志

感谢你看到这里！

**Comment by Goooooooooood** [comment]
[33mWARN[0m[2023-05-18 12:58:21] not enable search                            
[36mINFO[0m[2023-05-18 12:58:21] using aria2 version: 1.36.0                  
[GIN] 2023/05/18 - 12:58:21 | 200 |       537.6µs |       127.0.0.1 | PROPFIND  "/dav/rclone/"
[GIN] 2023/05/18 - 12:58:23 | 207 |      1.7421ms |       127.0.0.1 | PROPFIND  "/dav/rclone/"
[GIN] 2023/05/18 - 12:58:25 | 207 |      1.3812ms |       127.0.0.1 | PROPFIND  "/dav/rclone/"
2023/05/18 12:58:51 Unsolicited response received on idle HTTP channel starting with "\x15\x03\x03\x00\x1a\x00\x00\x00\x00\x00\x00\x00\x03G\x9cs\x9f]7\xf2\xf5\xc4g\x96\r\x93@\x0e>\xc7!"; err=<nil>
[GIN] 2023/05/18 - 12:58:53 | 401 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/"
[GIN] 2023/05/18 - 12:58:53 | 207 |    134.2735ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/"
[GIN] 2023/05/18 - 12:58:53 | 207 |      3.5638ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/"
[GIN] 2023/05/18 - 12:59:03 | 207 |    9.3287417s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun"
[GIN] 2023/05/18 - 12:59:03 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/"
[GIN] 2023/05/18 - 12:59:03 | 207 |     118.077ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/emby"
[GIN] 2023/05/18 - 12:59:03 | 207 |      1.5253ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:03 | 207 |    229.9729ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/临时存放"
[GIN] 2023/05/18 - 12:59:04 | 207 |    278.1267ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/来自分享"
[GIN] 2023/05/18 - 12:59:04 | 207 |    277.2004ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/我的分享"
[GIN] 2023/05/18 - 12:59:04 | 207 |      6.0047ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:04 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |     14.6695ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |       482.8µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |       286.7µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |       240.7µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |       220.9µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |      1.9256ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |      2.5038ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |      1.6723ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |      7.3102ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:05 | 302 |    183.1746ms |       127.0.0.1 | GET      "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:11 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:11 | 207 |         971µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:22 | 201 |   10.8375447s |       127.0.0.1 | PUT      "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:22 | 207 |       613.3µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:22 | 207 |     13.8559ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:22 | 207 |      1.1198ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:22 | 207 |      3.7106ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:23 | 207 |       803.6µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:23 | 207 |       711.3µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:23 | 207 |         722µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/"
[GIN] 2023/05/18 - 12:59:23 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:23 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun"
[GIN] 2023/05/18 - 12:59:28 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:28 | 207 |      1.5145ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/emby"
[GIN] 2023/05/18 - 12:59:28 | 207 |      1.3769ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/来自分享"
[GIN] 2023/05/18 - 12:59:28 | 207 |       535.5µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:28 | 207 |      1.2196ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/我的分享"
[GIN] 2023/05/18 - 12:59:28 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/临时存放"
[GIN] 2023/05/18 - 12:59:29 | 207 |     10.6489ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |       788.5µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |       276.2µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |       261.9µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |         239µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |      3.2816ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |      3.0153ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |      1.9804ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |      1.6245ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |       553.7µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:29 | 302 |            0s |       127.0.0.1 | GET      "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:50 | 207 |      8.0877ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun"
[GIN] 2023/05/18 - 12:59:50 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/emby"
[GIN] 2023/05/18 - 12:59:50 | 207 |      7.0303ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/来自分享"
[GIN] 2023/05/18 - 12:59:50 | 207 |        1.92ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/临时存放"
[GIN] 2023/05/18 - 12:59:50 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:50 | 207 |      2.4453ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:50 | 207 |       603.9µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/"
[GIN] 2023/05/18 - 12:59:50 | 207 |       177.7µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:50 | 207 |      1.6528ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/我的分享"
[GIN] 2023/05/18 - 12:59:51 | 207 |      14.489ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |       379.3µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |       332.5µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |       229.8µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |       228.5µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |       505.9µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |      4.4744ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |      1.7567ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |      4.6683ms |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |       658.8µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |       650.7µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"
[GIN] 2023/05/18 - 12:59:51 | 207 |       664.6µs |       127.0.0.1 | PROPFIND  "/dav/aliyun/aliyun/test.txt"

**Comment by Goooooooooood** [comment]
我装回了 3.17.0，进行测试，上一楼是日志。

更意外的事情发生了，编辑文本保修修改后，再打开文本，记事本会直接提示IO错误。
只能结束alist进程，重新启动alist。从windows资源管理器打开文本，显示出修改后的文件。

![399DEE04-6E66-4C55-A9AB-6E4783CB61AE](https://github.com/alist-org/alist/assets/90984890/6bd48faa-d692-40f6-a9bb-f81cbba07cc1)

**Comment by Goooooooooood** [comment]
v3.16.3 和 v3.17.0 对比，环境唯一不同处，只在于alist版本。
https://github.com/alist-org/alist/assets/90984890/2014dd33-03cd-4da5-bcf6-eac6b82ad523

**Comment by Xhofe** [comment]
1. 使用的什么挂载？如果是windows自身的挂载功能，那么可能是为windows自身问题清尝试更换软件；
2. 日志中记录上传与下载均正常，无错误。

**Comment by Goooooooooood** [comment]
> * 使用的什么挂载？如果是windows自身的挂载功能，那么可能是为windows自身问题清尝试更换软件；
> * 日志中记录上传与下载均正常，无错误。

感谢回复！

使用NetDrive挂载为“本地磁盘”的。如果是挂载工具的问题，在v3.16.3以及更早版本中，功能都很正常，到v3.17.0突然不行了，费解。

要是用rclone挂载，打开文本直接就会出现“IO错误”，打开图片就会提示“图像损坏”。总之能打开目录，打不开每个文件。
将alist里的阿里云盘open驱动，设置为“本地代理”，rclone才能正常使用。

这个问题是非致命的，所以我选择回退到了v3.16.3继续使用。

如果有希望修复最好，即使不能修复，目前也能继续用老版本。

**Comment by Xhofe** [comment]
我无法复现它：
![Kapture 2023-05-18 at 23 38 43](https://github.com/alist-org/alist/assets/36558727/90c76739-e71d-4926-88f9-4bce7cdf2d14)

**Comment by Goooooooooood** [comment]
> 我无法复现它：
> ![Kapture 2023-05-18 at 23 38 43](https://user-images.githubusercontent.com/36558727/239278982-90c76739-e71d-4926-88f9-4bce7cdf2d14.gif)

不同系统环境，无法复现也正常。

个人猜测alist v3.17.0和NetDrive之间，有兼容性问题。

由于不想使用“本地代理”，所以不用rclone挂载。alist v3.16.3 “重定向”+NetDrive也能继续用，挺好。

感谢花费时间测试，辛苦了。🙏
