### ISSUE TITLE
上传报错code500

### ISSUE THREAD

**Issue by KKISO574** [alist-org/alist#4411]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

V3.17

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

上传时候报错状态码500，网站采用Nginx反向代理5244端口，有ssl，上传大小Nginx无限制，form上传和stream上传都报错，之前老版本也有这个问题，但是我的另一头电脑装过没问题，请看截图

### Reproduction / 复现链接

![微信截图_20230518170958](https://github.com/alist-org/alist/assets/68904107/44f376ae-8cad-422b-8150-f46eb328d721)
![微信截图_20230518171011](https://github.com/alist-org/alist/assets/68904107/db409026-8c8f-4f98-8283-a2ec70439f09)
![微信截图_20230518171017](https://github.com/alist-org/alist/assets/68904107/1132e3c5-3c91-446d-bab0-f09276ab2b28)

### Logs / 日志

[GIN] 2023/05/18 - 17:17:27 | 200 |    7.275841ms |    36.5.174.232 | POST     "/api/fs/remove"
[GIN] 2023/05/18 - 17:17:28 | 200 |     348.192µs |    36.5.174.232 | POST     "/api/fs/list"
[36mINFO[0m[2023-05-18 17:17:29] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:17:30] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:17:30] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:30] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:17:30] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:34] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:17:35] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:17:35] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:17:35] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:35] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:39] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:17:40] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:17:40] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:40] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:17:40] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:44] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:17:45] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:17:45] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:17:45] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:45] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:49] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:17:50] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:17:50] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:17:50] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:50] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:54] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:17:55] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:17:55] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:17:55] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:55] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:17:59] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:18:00] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:18:00] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:18:00] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:18:00] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:18:04] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:18:05] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:18:05] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:18:05] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:18:05] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:18:09] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:18:10] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:18:10] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:18:10] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:18:10] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:18:14] index obj count: 46853                       
[GIN] 2023/05/18 - 17:18:14 | 200 |    1.185421ms |    8.218.60.227 | GET      "/"
[36mINFO[0m[2023-05-18 17:18:15] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:18:15] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:18:15] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:18:15] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:18:19] index obj count: 46853                       
[36mINFO[0m[2023-05-18 17:18:20] index obj count: 165594                      
[36mINFO[0m[2023-05-18 17:18:20] index obj count: 23                          
[36mINFO[0m[2023-05-18 17:18:20] index obj count: 1                           
[36mINFO[0m[2023-05-18 17:18:20] index obj count: 1

**Comment by KKISO574** [comment]
复现步骤就是正常上传任何文件会报错500

**Comment by Xhofe** [comment]
<img width="574" alt="image" src="https://github.com/alist-org/alist/assets/36558727/1b790a0e-9f2a-4c31-9b87-1de27a2365eb">

**Comment by KKISO574** [comment]
> <img alt="图像" width="574" src="https://user-images.githubusercontent.com/36558727/239275248-1b790a0e-9f2a-4c31-9b87-1de27a2365eb.png">

我的这个请求是错误的500，是需要时设置config文件里https还是反向代理的问题

**Comment by KKISO574** [comment]
我的这个远程地址默认跳到一个奇怪的保留地址上去了？
![微信截图_20230519085632](https://github.com/alist-org/alist/assets/68904107/fc92253e-725b-448b-909e-862d5f20f81b)

**Comment by KKISO574** [comment]
问题解决了，宝塔Nginx免费防火墙拦截了
