### ISSUE TITLE
希望前端调用aria2下载可以直接下载文件夹并保持原有结构（此问题在 #4283 提出，但这里有更多需求）

### ISSUE THREAD

**Issue by Jerry12228** [alist-org/alist#4413]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

需求原因：
1.相关存储驱动的官方客户端无法正常下载，但alist可以  
2.一个目录内挂载多个存储驱动，使用官方客户端不易操作  
3.文件数量庞大，单个文件巨大（虽然这种情况官方客户端更好，但原因见1、2）
其他众多未遇到、忘记、未列出的问题……  

需求：
希望前端调用aria2下载（即选择文件后点击下方下载按钮弹出的“发送到aria2”选项）可以直接下载文件夹并保持原有结构，并在下载前**询问用户下载目录**
![image](https://github.com/alist-org/alist/assets/86408775/cb5c599c-dab2-498f-9996-fe4f8f808115)

### Suggested solution / 实现思路

像使用“打包下载”时同样，获取文件列表  
在向aria2添加任务时，设置下载目录为用户设置的下载目录（即需求描述中提到的"询问用户下载目录"）+该文件的相对路径

**Comment by anwen-anyi** [comment]
目前还不支持Aria2下载文件夹 
欢迎Pr已经有人提过了😘

**Comment by VectorZhao** [comment]
aria2目前是无法下载阿里云资源了吗？

**Comment by Jerry12228** [comment]
> aria2目前是无法下载阿里云资源了吗？

可以（总之我可以），请注意添加存储时使用阿里云盘open驱动

测试：
访问https://pan.jerry.ink/
所见资源都存储于阿里云盘

**Comment by anwen-anyi** [comment]
有大佬 pr了 这就去测试一下效果
https://github.com/alist-org/alist-web/pull/88

**Comment by Xhofe** [comment]
暂未发现浏览器有`选择文件夹`获取fullpath的接口，因此无法实现`询问用户下载目录`。

如果有什么我忽略的地方，欢迎pr或者发在这里。

**Comment by Jerry12228** [comment]
> Hello @Jerry12228, your issue is a duplicate and will be closed. 你好 @Jerry12228，你的issue是重复的，将被关闭。

此功能已在#88实现，但有大佬认为功能多余又去掉了😂

**Comment by anwen-anyi** [comment]
去掉的哪个功能只是下载到自己本地文件夹的路径而已，没有用吖
可以直接使用`Aria2`软件配置的下载目录就行~ 
如果要写将`Aria2`下载到自己本地的路径  配置也很繁琐呐，得自己先找到文件夹然后cv到AList前端设置里面
 - 还不如直接让Aria2软件接管下载路径呢

**Comment by Jerry12228** [comment]
> 去掉的哪个功能只是下载到自己本地文件夹的路径而已，没有用吖 可以直接使用`Aria2`软件配置的下载目录就行~ 如果要写将`Aria2`下载到自己本地的路径 配置也很繁琐呐，得自己先找到文件夹然后cv到AList前端设置里面
> 
> * 还不如直接让Aria2软件接管下载路径呢

嗯，我本来意思是这样可以直接在浏览器完成配置，点击两下即可，不用打开文件资源管理器，打开藏在深处的配置文件改了
但猛然想起，可以用ariang…是我脑子抽了抱歉
