### ISSUE TITLE
使用蓝奏云cookie挂载下载文件出现“failed link: failed get link: not find file page param”

### ISSUE THREAD

**Issue by cyx200902** [alist-org/alist#4419]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.17.0

### Driver used / 使用的存储驱动

蓝奏云

### Describe the bug / 问题描述

使用蓝奏云cookie挂载下载文件出现“failed link: failed get link: not find file page param”，但可以正常上次，且在蓝奏云的网页上可以正常下载文件

### Reproduction / 复现链接

使用蓝奏云cookie存储

### Logs / 日志

[GIN] 2023/05/19 - 20:02:08 | 200 |       445.9µs |       127.0.0.1 | POST     "/api/fs/list"
[31mERRO[0m[2023-05-19 20:02:10] lanzou: err => not find file page param ,data => <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0" />
</head>
<body>
<style>
.off{text-align: center;font-size: 16px;color: #b3b3b3;margin-top: 10%;}
.off0{background: #eee;width: 70px;height: 60px;margin: 0 auto 30px auto;border-radius: 3px;padding-top: 10px;}
.off1{border-top: 30px solid #b1b1b1;width: 10px;height: 10px;border-bottom: 10px solid #b1b1b1;margin: auto;}
#link{background: #0088ff;color: #fff;padding: 10px 30px;border-radius: 3px;text-decoration: none;display: block;width: 100px;margin: 30px auto;}
</style>
<div class="off" id="off"><div class="off0"><div class="off1"></div></div>访问地址错误，请核查</div>
<script type="text/javascript">
	var url =window.location.pathname;
	var domain =window.location.host;
	url =url.substring(1,15);
window.onload=function(){
	for(var i=1;i<=10;i++) {
		if(i==2){
			var is_word ='%';
		}
		if(i==3){
			var is_word ='=';
		}
		if(i==4){
			var is_word ='@';
		}
		if(i==5){
			var is_word ='(';
		}
		if(i==6){
			var is_word =')';
		}
		if(i==7){
			var is_word ='http';
		}
		if(i==8){
			var is_word ='+';
		}
		if(i==9){
			var is_word ='-';
		}
		if(i==10){
			var is_word ='/';
		}
		var is_not_null = url.indexOf(is_word);
		if(is_not_null > 0){
			var w = url.split(is_word);
			var path_url = w[0];
			document.getElementById("off").innerHTML="你要访问的是不是?<br>https://"+ domain + "/" + path_url + "<br><a href=https://"+ domain + "/" + path_url +" id=link>继续访问</a>";
			break;
		}
	} 
}
</script>
<div style="display:none "><script src="https://s6.cnzz.com/z_stat.php?id=5289258&web_id=5289258" language="JavaScript"></script></div>
</body>
</html> 
[31mERRO[0m[2023-05-19 20:02:10] failed link /lanzou-Cookie/test/110000038.mp3: not find file page param
failed get link

**Comment by foxxorcat** [comment]
无法复现，请尝试重新获取cookie
分析该问题可能是文件分享链接异常导致，但这个问题不应该出现，大概率出现的错误应该是包含分享取消，文件不存在等。
如果可以请提供该文件分享链接（蓝奏云网页的）

**Comment by cyx200902** [comment]
我尝试重新获取cookie，但依然会出现报错
附：https://wwhx.lanzoum.com/b032ez97g
密码:dq1g

**Comment by foxxorcat** [comment]
麻烦先把原来的log文件删除后打开调试模式，出现错误后上传log文件。

**Comment by CandyMuj** [comment]
在添加存储时，打开 ```Web 代理```
在 ```WebDAV策略``` 上方
