### ISSUE TITLE
windows 10挂载pikpak时出现问题

### ISSUE THREAD

**Issue by plok00286750** [alist-org/alist#4423]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.17.0

### Driver used / 使用的存储驱动

pikpak

### Describe the bug / 问题描述

windows 10挂载pikpak时出现问题,前几天好好的突然不能用

### Reproduction / 复现链接

[https://i.imgur.com/FYytnOH.jpeg](url)

### Logs / 日志



**Comment by anwen-anyi** [comment]
这种一般是你的  `防火墙/网络`  导致的，你试试看

**Comment by plok00286750** [comment]
> 

改防火墻規則解決了感謝
