### ISSUE TITLE
设置存储空间限制

### ISSUE THREAD

**Issue by lwb-2021** [alist-org/alist#4424]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

比如说某个目录限制多少GB的空间

**Comment by anwen-anyi** [comment]
没戏了估计，AList只是一个列表程序

-----
`A file list program that supports multiple storage, powered by Gin and Solidjs. / 一个支持多存储的文件列表程序，使用 Gin 和 Solidjs。`

**Comment by zzzshare** [comment]
是不是可以只做一个显示的功能，比如配置的时候给多一个属性为最大容量，然后显示这个网盘的使用率为多少这样？还有现在的文件都有索引大小，但文件夹不会自动计算显示文件夹大小，感觉这个应该比较好实现吧

**Comment by Mai0313** [comment]
> 是不是可以只做一个显示的功能，比如配置的时候给多一个属性为最大容量，然后显示这个网盘的使用率为多少这样？还有现在的文件都有索引大小，但文件夹不会自动计算显示文件夹大小，感觉这个应该比较好实现吧

設置quota限制就能解決了 我懂你說的 alist如果能有這功能最好 但這個在ubuntu上是做不到的 (其他系統應該也是)
