### ISSUE TITLE
存储驱动希望添加七牛云

### ISSUE THREAD

**Issue by defeng-hub** [alist-org/alist#4427]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

存储驱动添加七牛云
七牛云
七牛云

### Suggested solution / 实现思路

七牛云也有Go的文档，集成应该不是很麻烦

**Comment by anwen-anyi** [comment]
S3 不就是吗？
