### ISSUE TITLE
115网盘 文件过多加载很慢或者加载不了

### ISSUE THREAD

**Issue by qaz19920713cs** [alist-org/alist#4429]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

115网盘某个文件夹内部可能有1万多个文件，alist无法进入 一直无法加载出来

### Suggested solution / 实现思路

文件夹为何没有分页  过多的文件无法快速加载这个问题如何解决

**Comment by anwen-anyi** [comment]
AList后台  -->  设置  -->  站点  -->  `分页`（不是可以设置吗？然后把`默认每页数量`也填下）

**Comment by qaz19920713cs** [comment]
好吧是我问题  我之前找半天没找到

**Comment by qaz19920713cs** [comment]
好吧是我问题  我之前找半天没找到
