### ISSUE TITLE
储存希望添加储存猫

### ISSUE THREAD

**Issue by zzx233a** [alist-org/alist#4432]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

这个网盘我希望能添加

**Comment by anwen-anyi** [comment]
你说的哪个`储存猫` 不就是https://cloudreve.org 搭建的？
