### ISSUE TITLE
挂载 v2 版本站点无法列出任何内容

### ISSUE THREAD

**Issue by cj-neo** [alist-org/alist#4435]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.17.0（arm64）

### Driver used / 使用的存储驱动

alist v2

### Describe the bug / 问题描述

我想下载 https://www.asmrgay.com 这个站台的某個子文件夾下面所有的文件夾和文件，但因文件夹结构复杂，且此站不提供子文件夹下载功能，打包下载又因为档案太大一直失败，所以打算曲线救国把整个站台挂载到我自己的 alist 上面，再利用webdav 的功能下载。

但挂载 alist v2 站点 （https://www.asmrgay.com） 之后却无法显示任何内容（整页空白）且没有显示任何的错误讯息。

设置如下：

![image](https://github.com/alist-org/alist/assets/35209118/bf0ef026-5a56-46ca-9808-a921378e2857)
![image](https://github.com/alist-org/alist/assets/35209118/06fba9d0-d42f-4133-8ac2-e7a6c0cac733)

不知道是否有那边设置错误，或者有什么其他办法可以达到我原本需求，感谢！

### Reproduction / 复现链接

无法挂载此网站 https://www.asmrgay.com

### Logs / 日志

没有任何错误讯息

**Comment by Xhofe** [comment]
![image](https://github.com/alist-org/alist/assets/36558727/c531ee13-78d4-44be-b71c-2cb22d52cdde)

**Comment by cj-neo** [comment]
可以告知为何 issue 无效吗？谢谢

**Comment by Xhofe** [comment]
我发了截图了 这个站点是v3的。

**Comment by cj-neo** [comment]
其实我一开始就用 v3 去挂，结果显示

Failed init storage but storage is already created: failed init storage: the site does not allow mounted

后来选 v2 竟然可以挂载而且不会显示任何错误（只是没内容），以致于才有上述的问题。
所以应该是这个网站限制了挂载，谢谢了！
