### ISSUE TITLE
希望任务能加上批处理功能

### ISSUE THREAD

**Issue by fflrichard** [alist-org/alist#4436]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我把一个天翼云网盘的内容复制到另一个天翼云网盘里面，文件比较多，复制完之后发现了100多页的失败，绝大多数是object not found。我点一下重试，就成功了。
然后有100多页，非常不方便，需要每一个都去点。
另外删除按钮，不需要确认，由于非常多，我点的有点快，直接有的就点到了删除上，直接删除了。

建议：
1、增加批量处理比如批量重试，全部重试
2、删除按钮需要增加确认

**Comment by fflrichard** [comment]
另外还有bug，我试了一下，有些明明重试没有成功，显示成功了

**Comment by Winyer** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure this feature is not implemented.
> * [x]  I'm sure it's a reasonable and popular requirement.
> 
> ### Description of the feature / 需求描述
> 我把一个天翼云网盘的内容复制到另一个天翼云网盘里面，文件比较多，复制完之后发现了100多页的失败，绝大多数是object not found。我点一下重试，就成功了。 然后有100多页，非常不方便，需要每一个都去点。 另外删除按钮，不需要确认，由于非常多，我点的有点快，直接有的就点到了删除上，直接删除了。
> 
> 建议： 1、增加批量处理比如批量重试，全部重试 2、删除按钮需要增加确认
> 
> ### Suggested solution / 实现思路
> _No response_
> 
> ### Additional context / 附件
> _No response_

这个问题提了很多次了也没有解决
