### ISSUE TITLE
version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by tangjin2580** [alist-org/alist#4437]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.17.0

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

环境都正常配置了，并且也升级了glibc版本，依然无法启动，x86平台，centos系统，看文档没有找到x64_musl版本的服务
[root@VM-4-10-centos home]# uname -m
x86_64
[root@VM-4-10-centos home]# ll /lib64/libc.so.6*
**lrwxrwxrwx 1 root root 12 5月  21 16:23 /lib64/libc.so.6 -> libc-2.18.so**
[root@VM-4-10-centos home]# ./alist server
./alist: /lib/libc.so.6: version `GLIBC_2.28' not found (required by ./alist)
[root@VM-4-10-centos home]# strings /lib64/libc.so.6|grep GLIBC| head -22 
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
**GLIBC_2.18**
GLIBC_PRIVATE

### Reproduction / 复现链接

NUll

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/releases/download/v3.17.0/alist-linux-musl-amd64.tar.gz

**Comment by tangjin2580** [comment]
> https://github.com/alist-org/alist/releases/download/v3.17.0/alist-linux-musl-amd64.tar.gz

谢谢，可以用了

**Comment by 1265578519** [comment]
楼主解决了吗？遇到一样的报错
```
[root@aliyun ~]# ldd --version
ldd (GNU libc) 2.17
```

alist-linux-musl-amd64.tar.gz alist-linux-amd64.tar.gz 这两个版本有什么区别

刚才试了下alist-linux-musl-amd64.tar.gz 就能正常启动
alist-linux-amd64.tar.gz 就报错./alist: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./alist)

如果没什么区别我就使用alist-linux-musl-amd64.tar.gz 了
