### ISSUE TITLE
挂载alist v3后无法上传文件

### ISSUE THREAD

**Issue by yeyudoc** [alist-org/alist#4457]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

alist v3

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/83936435/3515f6bc-5e51-46b0-8ca6-18b7b768731f)
挂载alist v3后无法上传文件

### Reproduction / 复现链接

无

### Logs / 日志

无

**Comment by Jeamorg** [comment]
请检查你的网站是否开了 cloudflare 的CDN，如果有，上传大于100M的文件时将它关掉

**Comment by yeyudoc** [comment]
> 请检查你的网站是否开了 cloudflare 的CDN，如果有，上传大于100M的文件时将它关掉

挂载的alist是平板termux搭建的，应该没有开了 cloudflare 的CDN

**Comment by xiaolei0125** [comment]
我存在同样的问题，将另一个alist v3挂载为当前alist存储后，上传文件报错，日志信息如下：
···
[GIN] 2023/05/27 - 17:58:26 | 200 |     502.911µs |    192.168.1.21 | GET      "/assets/Upload.ffbde94b.js"
ERRO[2023-05-27 17:58:44] failed put /office/图片/: request failed,code: 400, message: strconv.ParseInt: parsing "": invalid syntax
github.com/alist-org/alist/v3/internal/op.Put
        /app/internal/op/fs.go:569
github.com/alist-org/alist/v3/internal/fs.putDirectly
        /app/internal/fs/put.go:54
github.com/alist-org/alist/v3/internal/fs.PutDirectly
        /app/internal/fs/fs.go:97
github.com/alist-org/alist/v3/server/handles.FsStream
        /app/server/handles/fsup.go:49
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.FsUp
        /app/server/middlewares/fsup.go:43
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
        /app/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.MaxAllowed.func3
        /app/server/middlewares/limit.go:14
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
        /app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2947
net/http.(*conn).serve
        /usr/lib/go/src/net/http/server.go:1991
runtime.goexit
        /usr/lib/go/src/runtime/asm_arm64.s:1172 
[GIN] 2023/05/27 - 17:58:44 | 200 |  775.350284ms |    192.168.1.21 | PUT      "/api/fs/put"
···

**Comment by DoiiarX** [comment]
同问题。如何解决？

**Comment by DoiiarX** [comment]
已解决。方法：取消挂载，换成rclone挂载为本地再以本地模式挂载。
