### ISSUE TITLE
阿里云盘Open提示：Failed init storage: TokenVerifyFailed:The token was expected to have 3 parts, but got 1.

### ISSUE THREAD

**Issue by YouHan26** [alist-org/alist#4462]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.15.1

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

按照文档配置及获取refresh-token流程，可以正常获取到token，但是alist保存提示 Failed init storage: TokenVerifyFailed:The token was expected to have 3 parts, but got 1.

### Reproduction / 复现链接

*

### Logs / 日志

<img width="628" alt="image" src="https://github.com/alist-org/alist/assets/3397173/6f5b1f42-6f5c-4a52-b619-4d52f72900ab">

**Comment by LittleXingzzZ** [comment]
遇到了同样的问题

**Comment by LittleXingzzZ** [comment]
不知道什么情况，token 都是没问题的

**Comment by LittleXingzzZ** [comment]
其他云盘没问题 就是阿里云盘open 提示这个问题报错

**Comment by M123Mci** [comment]
我也是

**Comment by LittleXingzzZ** [comment]
> 我也是
> 
> 

应该不是我们的问题

**Comment by sakurasep** [comment]
遇到了同样的问题

**Comment by anwen-anyi** [comment]
阿里云盘open 遇到如下情况的升级最新版AList
👉The token was expected to have 3 parts, but got 1.
👉failed get objs: failed to list objs: TokenExpired:token expired

**Comment by magblank** [comment]
我用官网上的更新脚本更新了，但是结果还是一样，后面卸载重装就又可以了

**Comment by freeqd** [comment]
同样的问题 ，原来的token过期，再重新安装就无法完成了

**Comment by sparkssssssss** [comment]
同求,更新到最新版,重新获取了token,删除了重新添加都没用

**Comment by langjun** [comment]
更新后仍报错，可以尝试重启alist服务

openwrt
```
$ /etc/init.d/alist stop
$ /etc/init.d/alist start
```

**Comment by Jandaes** [comment]
我也遇到了、但是重新点下阿里挂载的保存按钮就可以了

**Comment by xqc520** [comment]
很奇怪，我卸载了阿里云盘和改了文件权限，重新安装又可以了

**Comment by WaterToy** [comment]
https://github.com/DDS-Derek/xiaoya-alist?tab=readme-ov-file通过docker部署的xiaoya，偶然发现

**Comment by pipipiper** [comment]
> 我也遇到了这个问题，不过我是通过 https://github.com/DDS-Derek/xiaoya-alist?tab=readme-ov-file 这个项目自动部署的。 多番尝试后发现并不是alist版本的问题，不知道什么原因，脚本自动部署过程中修改了 mytoken.txt 文件中的内容，导致出现上述问题，可以通过修改mytoken.txt 文件中内容为你自己的token，之后重启docker就好了。

请问您最后是怎么解决的，我改成自己的token后重启docker后mytoken.txt又再次被改了。

**Comment by WaterToy** [comment]
> > 我也遇到了这个问题，不过我是通过 https://github.com/DDS-Derek/xiaoya-alist?tab=readme-ov-file 这个项目自动部署的。 多番尝试后发现并不是alist版本的问题，不知道什么原因，脚本自动部署过程中修改了 mytoken.txt 文件中的内容，导致出现上述问题，可以通过修改mytoken.txt 文件中内容为你自己的token，之后重启docker就好了。
> 
> 请问您最后是怎么解决的，我改成自己的token后重启docker后mytoken.txt又再次被改了。

我这边是win11的WSL2运行的ubuntu24，配合docker desktop，前面也有几次遇到你描述的情况，当时好像是在doker desktop里面重启的。后来我关掉docker后，修改文件，在ubuntu里面通过命令行 重启docker，好像就没出问题了。你可以试试~

**Comment by DeTeKe** [comment]
把nn.ci域名添加到梯子里就ok了
