### ISSUE TITLE
阿里云open错误提示：Failed init storage:TokenExpired:token expired。但更新令牌后后台无法保存，文件读取依然失败.

### ISSUE THREAD

**Issue by jiangbianqi** [alist-org/alist#4465]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

RaiDrive

### Describe the bug / 问题描述

RaiDrive

一、原本正常使用的阿里网盘，突然无法读取，无法打开。Alist后台显示：阿里云open  状态“TokenExpired:token expired”
1、刷新Token后，无法在保存。
二、删除原有网盘设置，新建时现如下问题：
1、Token：在后台粘贴、保存时反馈错误：“Failed init storage:TokenExpired:token expired”。但我敢肯定这是刚刚刷新的Token。
2、Root folder file_id：打开网盘链接，地址栏file_id数字一闪而过，不再像以前可自由复制，只能截图，识别后方能填入后台。
3、在Alist主页进入阿里网盘，出现错误：“failed get objs:failed to list objs:TokenVerifyFailed:The token was expected to have 3 parts, but got 1.”

### Reproduction / 复现链接

![屏幕截图 2023-05-25 100847](https://github.com/alist-org/alist/assets/43953466/27dcd5fd-8d48-4234-93b4-eeed9f5a166a)
![屏幕截图 2023-05-25 101553](https://github.com/alist-org/alist/assets/43953466/3bd12ff1-3cd8-48db-be77-29af62538733)
![屏幕截图 2023-05-25 104342](https://github.com/alist-org/alist/assets/43953466/17b8a100-7ed6-48e4-8a2a-601c0ddd435a)

**Comment by Clost-java** [comment]
用文档中的更新脚本，更新下就可以了

**Comment by MrLi1982** [comment]
![1684983242451](https://github.com/alist-org/alist/assets/122736055/5817c3a1-9578-4dad-a6ef-4edf6baa50f8)
同问？如何解决？谢

**Comment by jiangbianqi** [comment]
> 用文档中的更新脚本，更新下就可以了

感谢提醒！
