### ISSUE TITLE
今天发现阿里云盘无法复制文件到另一个云盘了，数据是0，有同样的问题吗

### ISSUE THREAD

**Issue by lickceo** [alist-org/alist#4475]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.17.0

### Driver used / 使用的存储驱动

aliyun open

### Describe the bug / 问题描述

今天我从挂载的阿里云复制文件到GD，无法复制文件，进度条闪完，但是数据是0！

### Reproduction / 复现链接

无法提供链接 操作是 alist 挂载的aliyun open 然后用rai挂载到本，从阿里云往GD里复制，没有数据传输，直接是零，之前一切正常，就今早开始的！

### Logs / 日志

[GIN] 2023/05/25 - 18:18:49 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/"
[31mERRO[0m[2023-05-25 18:20:59] failed get /tv2/更新剧集: AccessTokenExpired:token expired
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/source/internal/op/fs.go:120
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/source/internal/op/fs.go:117
github.com/alist-org/alist/v3/internal/op.Get
	/source/internal/op/fs.go:210
github.com/alist-org/alist/v3/internal/fs.get
	/source/internal/fs/get.go:38
github.com/alist-org/alist/v3/internal/fs.Get

**Comment by imroc** [comment]
今天遇到阿里云盘通过alist打不开了，报AccessTokenExpired，没做任何改动，之前一直用的还好好的

<img width="786" alt="image" src="https://github.com/alist-org/alist/assets/7448852/a7da6123-f286-4583-8b04-a2ba65d287ff">

即使尝试重新刷新token，填进去，一样报相同的错

<img width="473" alt="image" src="https://github.com/alist-org/alist/assets/7448852/6a03a8c8-12e5-4cd3-a1b5-890d9131d21f">

**Comment by lickceo** [comment]
我也是今天才有这种情况的，之前一直正常，今天从阿里云复制文件到GD,就是瞬时间过去，但是没数据，数据是0！

**Comment by lickceo** [comment]
额，直接  failed get objs: failed to list objs: AccessTokenExpired:token expired

**Comment by Xhofe** [comment]
此错误在 https://github.com/alist-org/alist/commit/b7ea73b3c24060582abd79fee9f2b7dbd2d39140 中被修复，请检查你所使用的版本，管理-设置-站点。

**Comment by imroc** [comment]
果然更新下alist版本就可以了~

**Comment by lickceo** [comment]
是可以了，谢谢！
