### ISSUE TITLE
夸克无法使用 api/fs/link 获取直连地址

### ISSUE THREAD

**Issue by viqbgrg** [alist-org/alist#4484]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.17.0

### Driver used / 使用的存储驱动

quark

### Describe the bug / 问题描述

夸克无法使用 api/fs/link 获取直连地址

### Reproduction / 复现链接

夸克所有的链接都是这个样子

**Comment by anwen-anyi** [comment]
夸克强制使用本地中转。应该没办法获取直链

**Comment by Xhofe** [comment]
> 夸克强制使用本地中转。应该没办法获取直链

yep
