### ISSUE TITLE
必须要重新启动一次才可以使用

### ISSUE THREAD

**Issue by WAN8023** [alist-org/alist#4485]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.17.0

### Driver used / 使用的存储驱动

阿里云盘 Open

### Describe the bug / 问题描述

开机启动后挂载正常，但无法访问内容
![1](https://github.com/alist-org/alist/assets/82212659/35f382d7-5f21-40c2-8217-53205b11e5cf)
![2](https://github.com/alist-org/alist/assets/82212659/2d07694f-bdce-42dc-9df8-f4ef21d3826a)

### Reproduction / 复现链接

局域网部署，无法提供链接

### Logs / 日志

[log.log](https://github.com/alist-org/alist/files/11580782/log.log)

**Comment by Xhofe** [comment]
dns服务器启动过慢，请自行设置延时启动
