### ISSUE TITLE
最新版本 TokenVerifyFailed:The token was expected to have 3 parts, but got 1.

### ISSUE THREAD

**Issue by sparkssssssss** [alist-org/alist#4486]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

 v3.17.0

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

之前使用的是v3.16.3 一直正常,大约三四天前吧,出现以下错误
```
Failed init storage:TokenExpired:token expired
```

我以为是token过期了,得空今天更新了一下,结果发现无效.上github看有相关issue https://github.com/alist-org/alist/issues/4465 里面就是说更新最新版,就关闭了

我随即更新至最新版本3.17.0,结果不行,我删除了原来的配置,重新添加后,错误变为以下:
```
TokenVerifyFailed:The token was expected to have 3 parts, but got 1.
```

我看还是有挺多人有这个问题的,https://github.com/alist-org/alist/issues/4462 但是issue也是无回应的关闭了,discussion里面也有人反映,请确认下.谢谢

### Reproduction / 复现链接

使用的armv7版本

### Logs / 日志

May 27 09:47:17 wky alist[22172]: ERRO[2023-05-27 09:47:17] failed get enabled storages: AccessTokenExp
May 27 09:47:17 wky alist[22172]: failed init storage
May 27 09:47:17 wky alist[22172]: github.com/alist-org/alist/v3/internal/op.initStorage
May 27 09:47:17 wky alist[22172]:         /source/internal/op/storage.go:99
May 27 09:47:17 wky alist[22172]: github.com/alist-org/alist/v3/internal/op.LoadStorage
May 27 09:47:17 wky alist[22172]:         /source/internal/op/storage.go:80
May 27 09:47:17 wky alist[22172]: github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
May 27 09:47:17 wky alist[22172]:         /source/internal/bootstrap/storage.go:20
May 27 09:47:17 wky alist[22172]: runtime.goexit
May 27 09:47:17 wky alist[22172]:         /usr/local/go/src/runtime/asm_arm.s:831

**Comment by sparkssssssss** [comment]
> ### See
> 1. 59% [阿里云盘Open提示：Failed init storage: TokenVerifyFailed:The token was expected to have 3 parts, but got 1. #4462](https://github.com/alist-org/alist/issues/4462)

已更新到最新版本,alist-linux-arm-7.tar.gz  问题依旧

**Comment by Xhofe** [comment]
请通过管理-设置-站点 确认你的版本。

**Comment by sparkssssssss** [comment]
谢谢,经查确实用的是老版本.
是我个人问题,更新了错误的路径.抱歉

**Comment by ddvgg** [comment]
> 请通过管理-设置-站点确认您的版本。

### ### 不错成功了  感谢了  v3.34最新版本了   可以了
![image](https://github.com/alist-org/alist/assets/51362049/83372189-3679-49a9-8bf8-720d1c37b220)
