### ISSUE TITLE
"阿里云盘分享"的挂载方式的建议

### ISSUE THREAD

**Issue by chainofhonor** [alist-org/alist#4490]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议"阿里云盘分享"改为只需要添加自己账号的token(可以直接添加网页版的token)
然后在线观看分享文件夹里面的视频的时候 先保存到用户自己的网盘(指定一个特定的目录)
然后点击了视频直接跳转到阿里云官方网站的链接观看

这样就简单方便多了 
阿里云估计也乐于用户这样用,毕竟最后是跳转到阿里云官方的,可以吸引用户付费

希望能酌情考虑  双赢的方式才能长久

**Comment by dmcslt** [comment]
转存播放？这个已经有人提过issues了[3777](https://github.com/alist-org/alist/issues/3777)

**Comment by chainofhonor** [comment]
看了上面那个转存播放的issue  
里面有提到说阿里没有提供API? 

我很疑惑,把共享的文件转存到自己的网盘里面,这个API没有吗?   

那是否可以间接的实现,查看视频列表用alist,然后播放的时候跳转到阿里云的共享界面,由用户自己保存,然后自己去点击观看

如果是手机,可以直接调用阿里云网盘的APP

**Comment by chainofhonor** [comment]
总之:
最后观看视频这一步必须是在阿里网盘的网页或者APP上

**Comment by JsonSong89** [comment]
在阿里云上面可以看高清吗?

**Comment by Stephen2023088** [comment]
> 看了上面那个转存播放的issue 里面有提到说阿里没有提供API?
> 
> 我很疑惑,把共享的文件转存到自己的网盘里面,这个API没有吗?
> 
> 那是否可以间接的实现,查看视频列表用alist,然后播放的时候跳转到阿里云的共享界面,由用户自己保存,然后自己去点击观看
> 
> 如果是手机,可以直接调用阿里云网盘的APP



> 在阿里云上面可以看高清吗?

会员可以看高清， 每天签到会赏你看高清的权限

**Comment by Stephen2023088** [comment]
> 在阿里云上面可以看高清吗?

每天签到会有看高清的机会的权限

**Comment by oyksoft** [comment]
阿里云盘已经不敢挂载第三方的客户端了，会被封。我刚用2天时间才解封。
阿里云还是比较小气，或者说不好控制。
最近的open但阿里云不好好控制，只能靠封锁。
