### ISSUE TITLE
搜索可以用绕过元信息隐藏限制！

### ISSUE THREAD

**Issue by xing-yv** [alist-org/alist#4494]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.17.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

使用索引：非全文搜索
如题，在使用搜索功能时，元信息中使用隐藏对文件夹进行的隐藏会失效（直接隐藏文件不会），未具有访问隐藏文件权限的用户可以直接绕过该限制，直接访问被隐藏的文件，并可通过点击文件列表上方路径的方式访问整个被隐藏目录中的内容，影响用户隐私。请尽快修复此问题。

### Reproduction / 复现链接

如下演示
![image](https://github.com/alist-org/alist/assets/109603760/3447e202-437f-47a6-af42-c96b1ff9c702)
![image](https://github.com/alist-org/alist/assets/109603760/9025d0ef-1a84-4bc7-bacb-dd6051f24a19)
![image](https://github.com/alist-org/alist/assets/109603760/90551851-fd49-4078-a8ed-c6cb5281b104)
![image](https://github.com/alist-org/alist/assets/109603760/38c955ea-9340-4ca7-b150-dd2bdd6d623d)

**Comment by anwen-anyi** [comment]
隐藏的无法搜索到

## 元信息隐藏方式
![image](https://github.com/alist-org/alist/assets/56105412/26a54eb8-ee7d-4f9a-8513-b2563882b206)

## 隐藏前和隐藏后对比
![image](https://github.com/alist-org/alist/assets/56105412/910746a1-f082-4b20-8dd9-d3a57645507c)

**Comment by xing-yv** [comment]
> 隐藏的无法搜索到
> 
> ## 元信息隐藏方式
> ![image](https://user-images.githubusercontent.com/56105412/241550863-26a54eb8-ee7d-4f9a-8513-b2563882b206.png)
> 
> ## 隐藏前和隐藏后对比
> 上图是隐藏后搜索不到，下图是隐藏前可以搜索到
> 
> ![image](https://user-images.githubusercontent.com/56105412/241550706-910746a1-f082-4b20-8dd9-d3a57645507c.png)

感谢您的纠正！在元信息中直接隐藏文件是可行的，但是隐藏文件夹是不行的，隐藏文件夹后文件夹下的文件仍会被搜索到，已更改反馈内容。

**Comment by xing-yv** [comment]
> 隐藏的无法搜索到
> 
> ## 元信息隐藏方式
> ![image](https://user-images.githubusercontent.com/56105412/241550863-26a54eb8-ee7d-4f9a-8513-b2563882b206.png)
> 
> ## 隐藏前和隐藏后对比
> 上图是隐藏后搜索不到，下图是隐藏前可以搜索到
> 
> ![image](https://user-images.githubusercontent.com/56105412/241550706-910746a1-f082-4b20-8dd9-d3a57645507c.png)

再次感谢您的提醒！我漏看了您的截图，经过尝试后，我发现在隐藏文件夹时勾选应用到子文件夹是可行的，感谢！

**Comment by xing-yv** [comment]
> 隐藏的无法搜索到
> 
> ## 元信息隐藏方式
> ![image](https://user-images.githubusercontent.com/56105412/241550863-26a54eb8-ee7d-4f9a-8513-b2563882b206.png)
> 
> ## 隐藏前和隐藏后对比
> 上图是隐藏后搜索不到，下图是隐藏前可以搜索到
> 
> ![image](https://user-images.githubusercontent.com/56105412/241550706-910746a1-f082-4b20-8dd9-d3a57645507c.png)

一小时前的回复由于没有重建索引是错误的。

**Comment by anwen-anyi** [comment]
文件夹隐藏有什么问题吗？（如果不能在线播放可以下载下来看）

https://github.com/alist-org/alist/assets/56105412/107d4a69-cda3-4f37-9517-a906e73e0c57

**Comment by xing-yv** [comment]
> Member

隐藏文件夹后，文件夹是不可以搜索到的，但该文件夹下的文件夹及文件是可以搜索到的，欢迎前往https://pan.xingyv.site/搜索我图片中提供的内容进行尝试

**Comment by Xhofe** [comment]
正则表达式只匹配文件名，你要隐藏某个目录下的文件需要添加：
- Path: `你要隐藏的文件夹路径`
- Hide: `.*` & apply to sub folder

**Comment by xing-yv** [comment]
> 嗯 刚 翻了翻，下面这俩应该也是一样的
> 
> * [游客用户可通过索引搜索到向游客用户隐藏的文件并播放 #4196](https://github.com/alist-org/alist/issues/4196)
> * [3.11.0  guest用户可以通过搜索或者地址栏输入地址访问隐藏文件 #3452](https://github.com/alist-org/alist/issues/3452)
> 
> 就如 `Xhofe` 说的那样，看来不能偷懒咯QAQ，真要隐藏还得是手动设置条元信息一个文件夹哈哈
> 
> 不能像我那样 直接 路径选择 `/`，隐藏选项 写要隐藏的文件夹 ❌错误示范 ❌

是的，所以我应该close这个issue吗

**Comment by anwen-anyi** [comment]
嗯 关了吧 `Xhofe` 已经说了，如果你要隐藏你要新建一条新的元信息 

而不是直接在路径选择 `/` 隐藏哪里选择你要隐藏的文件夹

**Comment by xing-yv** [comment]
感谢两位的帮助( •̀ ω •́ )✧

**Comment by slaners** [comment]
如果想隐藏根目录的文件夹应该怎么搞？现在设置隐藏根目录文件夹后，游客登陆还会显示一个 隐藏 测试 文件夹 的标签![img](https://files.catbox.moe/8x0oer.jpg)
