### ISSUE TITLE
可以考虑增加 “阿里云盘 m3u8 外链” 选项

### ISSUE THREAD

**Issue by SuLingGG** [alist-org/alist#4498]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我注意到在文档 <https://alist.nn.ci/zh/guide/drivers/aliyundrive_open.html> 中提到：“在线播放视频” 不计算 “请求次数”。

所以可以考虑增加 “阿里云盘 m3u8 外链” 选项，使访客访问类似如下链接时:

<https://alist-example.com/videos/EP01.mp4.m3u8>

可以跳转到 `/video/EP01.mp4` 这个视频文件被转码后最高画质的 m3u8 链接。这样在一定程度上可以方便博客等用途直接外链存放在阿里云盘中的视频。

**Comment by anwen-anyi** [comment]
OpenAPI 禁止的哦~

**Comment by SuLingGG** [comment]
> OpenAPI 禁止的哦～

好吧捏~
