### ISSUE TITLE
[FEATURE]1Panel 应用商店快速安装 Alist.

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [alist-org/alist#4500]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

[1Panel Linux 面板](https://github.com/1Panel-dev/1Panel) ，进入应用商店，支持快速安装 Alist。
- 应用商店 - 工具，选择 Alist
![image](https://github.com/alist-org/alist/assets/46734380/0377b71f-9ab4-421d-978d-26ddc83d8487)
- 进入详情页面，点击安装，输入名称等参数后，点击确认按钮安装 Alist
![image](https://github.com/alist-org/alist/assets/46734380/a0306411-e9d6-4c6d-ab57-dc932da00740)

**Comment by anwen-anyi** [comment]
应该到`Discussions`，并且我看了一下好像还需要迭代一下,里面就一个版本

**Comment by wanghe-fit2cloud** [comment]
> 应该到`Discussions`，并且我看了一下好像还需要迭代一下,里面就一个版本

感谢反馈。
