### ISSUE TITLE
希望支持图床功能

### ISSUE THREAD

**Issue by hyhy01** [alist-org/alist#4504]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能够通过API上传文件，上传后能返回对应的路径

**Comment by Xhofe** [comment]
https://github.com/jinzhi0123/picgo-plugin-alist

**Comment by grofis** [comment]
> https://github.com/jinzhi0123/picgo-plugin-alist

完全没法用！这个插件设计的初衷是上传图片之后返回url，这里的上传是picgo面板对吧？
那么如果我不是通过picgo上传的图片，是不是不能用了呢？
Alist我觉得现在最大的需求就是实现图床的功能？什么是图床的功能呢？就是Alist的目录下的图片都能够正常在img标签里引用。
现在的问题是点击Alist里的图片，看地址是1000字的长链接，右键预览直接下载了....搞得人一点心肠都没有。
