### ISSUE TITLE
[建议]可以给Alist增加一个用户注册和sso登录自动注册吗？

### ISSUE THREAD

**Issue by Timolop233** [alist-org/alist#4508]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在特殊情况下，alist可能要用户登录后上传、查看文件
但目前只有admin用户有这个权限
所以我在想，能否在alist里增加用户注册或sso登录自动注册
注册后用户在特定权限组，权限设定由权限组规则决定
这样可以更加符合一个网盘的设定（？大概

**Comment by anwen-anyi** [comment]
你说的这个应该不行，而且AList不是网盘 是`一个支持多存储的文件列表程序，使用 Gin 和 Solidjs。`

**Comment by ty114514** [comment]
你的需求可以看看隔壁 Cloudreve
