### ISSUE TITLE
message: failed link: failed get link: Get * no such host data :nul

### ISSUE THREAD

**Issue by Greyisttot** [alist-org/alist#4509]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.18.0

### Driver used / 使用的存储驱动

CentOS Stream 9 x86_64(Py3.7.16)

### Describe the bug / 问题描述

{"code":500,"message":"failed link: failed get link: Get \"https://download-cdn.123pan.cn/123-152/5bfaf308/1815016300-0/5bfaf308d61982de5e4550b569af9898/c-m2?v=5\u0026t=1685588939\u0026s=16855889399c878e0527edc7a04c4bb6451040c1c6\u0026r=H7E4U6\u0026filename=%E7%99%BB%E5%BD%95%E5%99%A8.zip\u0026x-mf-biz-cid=fa636bd0-9c89-4c7c-919b-087a70b40a3e-47df1e\u0026auto_redirect=0\": dial tcp: lookup download-cdn.123pan.cn on ***********36:53: no such host","data":null}

### Reproduction / 复现链接

在
`https://cdn.douyin.mba/0/MS/%E7%99%BB%E5%BD%95%E5%99%A8.zip`
这个页面可以点击下载，鼠标移上去显示的是解析后的支链，可以下载。

但直接打开下载链接
`https://cdn.douyin.mba/d/0/MS/%E7%99%BB%E5%BD%95%E5%99%A8.zip`
就会出现错误提示。

**Comment by Xhofe** [comment]
cache: https://cdn.douyin.mba/d/0/MS/%E7%99%BB%E5%BD%95%E5%99%A80.zip
random: https://cdn.douyin.mba/d/0/MS/%E7%99%BB%E5%BD%95%E5%99%A80.zip?random

**Comment by Greyisttot** [comment]
> 缓存： https: [//cdn.douyin.mba/d/0/MS/%E7%99%BB%E5%BD%95%E5%99%A80.zip](https://cdn.douyin.mba/d/0/MS/%E7%99%BB%E5%BD%95%E5%99%A80.zip) no_cache： https: [//cdn.douyin.mba/ d/0/MS/%E7%99%BB%E5%BD%95%E5%99%A80.zip?随机](https://cdn.douyin.mba/d/0/MS/%E7%99%BB%E5%BD%95%E5%99%A80.zip?random)

https://cdn.douyin.mba/d/0/MS/%E7%99%BB%E5%BD%95%E5%99%A8.zip?random

{"code":401,"message":"expire missing","data":null}

**Comment by Greyisttot** [comment]
{"code":500,"message":"failed link: failed to get file: object not found","data":null}
