### ISSUE TITLE
Is possible use image preview in list mode?

### ISSUE THREAD

**Issue by Huelse** [alist-org/alist#4519]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Now I can only use image preview in image mode, it will lead loading problem. What if open the preview by context menu?

**Comment by Xhofe** [comment]
click the icon of the file.
