### ISSUE TITLE
failed list /: please add a storage first.

### ISSUE THREAD

**Issue by wowdd1** [alist-org/alist#4523]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.18 3.17

### Driver used / 使用的存储驱动

Pikpak分享

### Describe the bug / 问题描述

挂在pikpak分享链接 成功    能看得到里面的内容  等到下次alist重新启动后报错   挂在的pikpak分享全部消失不见了 

好像alist无法保存状态了  改了密码   下次启动  密码又不对  

[GIN] 2023/06/02 - 23:35:29 | 200 |      832.05µs |    184.72.23.68 | POST     "/api/fs/get"
[31mERRO[0m[2023-06-02 23:35:30] failed list /: please add a storage first.
github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath
	/source/internal/op/path.go:19
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:18
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:82
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1995
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
failed get storage 

### Reproduction / 复现链接

任何pikpak分享链接挂载

**Comment by anwen-anyi** [comment]
检查你是否有 保存(写入) 权限. 估计是你没写入权限导致关闭后无法保存

要么检查你数据存储位置是否正确，在不同的目录启动会使用不用数据库
