### ISSUE TITLE
使用远程数据库时出错

### ISSUE THREAD

**Issue by DEV4895** [alist-org/alist#4535]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.18.0

### Driver used / 使用的存储驱动

YugabyteDB

### Describe the bug / 问题描述

平台：Windows 10 amd64；Linux amd64；Replit bash。
远程数据库：YugabyteDB
启动参数：./alist server --no-prefix
表现：在数据库为空的状态下正常启动并创建管理员用户，并创建TABLE，不会有任何报错。随后停止，再重新启动，这期间不做任何其他操作，但在第二次启动之后以1的状态码退出，log见下；随后使用DROP TABLE命令删除所有的表；第三次启动便与数据库为空的情况下启动完全一样，能创建新的管理员用户并正常启动；停止再启动依旧以1的状态码推出。因此使用时每次启动都需要清空数据。
同样的问题在bit.io远程数据库上不会出现。

### Reproduction / 复现链接

非网页问题无复现链接

### Logs / 日志

![1](https://github.com/alist-org/alist/assets/101171334/e75d48a3-290d-443b-8c30-8d267611211e)
![2](https://github.com/alist-org/alist/assets/101171334/adc62d65-aa56-4b23-9858-11fbc3f84fda)
![3](https://github.com/alist-org/alist/assets/101171334/728e7080-b795-457e-ab47-e6678add9510)

**Comment by Xhofe** [comment]
我想这是YugabyteDB的问题：
- https://github.com/yugabyte/yugabyte-db/issues/13395
- https://github.com/yugabyte/yugabyte-db/issues/12422

**Comment by sonrixmomo** [comment]
+1,同样有这个问题
