### ISSUE TITLE
请求添加关闭Aliyun Video Previewer的开关

### ISSUE THREAD

**Issue by ljxi** [alist-org/alist#4539]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Aliyun Video Previewer播放的源是经过阿里云转码的，转码速度慢，清晰度低，播放体验完全不如Video选项卡使用原始文件作为直链播放，但是Aliyun Video Previewer无法关闭，且默认排在第一位，希望能够出一个开关用于关闭Aliyun Video Previewer或者能够调整默认预览方式

### Suggested solution / 实现思路

新增一个开关用于关闭Aliyun Video Previewer

**Comment by KarlLee830** [comment]
支持

**Comment by 1273082756** [comment]
支持

**Comment by Leon406** [comment]
原来是这样的, 怪不得视频加载不出来,换Video就可以了

**Comment by bnbp** [comment]
这个有计划支持吗，或者默认不选中也行，因为在国外，阿里云盘内容无法直连，Aliyun Video Previewer 无法播放

**Comment by ypq123456789** [comment]
同问。感觉很有必要

**Comment by ydcool** [comment]
对于其他类型比如压缩文件、iso等，也希望能够控制默认是否展示preview或者默认展示下载提示
