### ISSUE TITLE
建议增加 联通云盘

### ISSUE THREAD

**Issue by huolanyun** [alist-org/alist#4541]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://pan.wo.cn/
联通云盘，运营商的不限速云盘，稳定

**Comment by zzsrv** [comment]
附议

**Comment by Xhofe** [comment]
To be integrated:  https://github.com/Xhofe/wopan-sdk-go

**Comment by Skimige** [comment]
@Xhofe 请问联通云盘什么时候会添加文档呢？找到了 refresh token，但是看不懂文件夹 ID。
