### ISSUE TITLE
使手机端可以更方便的下载备份

### ISSUE THREAD

**Issue by html5syt** [alist-org/alist#4551]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在手机端由于WebView本身不支持下载blob数据格式，导致无法下载备份文件，希望能在手机端也可以下载备份文件。

### Suggested solution / 实现思路

①对blob进行base64编码（网上搜的）
②更改生成方式（比如在服务器临时缓存，并提供链接下载）
③备份到挂载的网盘中，之后手动下载（顺便也可以实现从网盘中恢复备份）

**Comment by anwen-anyi** [comment]
手机我记得是可以 下载备份文件的 你用的什么浏览器

**Comment by html5syt** [comment]
我用的via和qq浏览器，后来换了自带内核的chrome成功了，应该是webview不支持吧。
但是还是希望更改一下，毕竟浏览器换来换去很麻烦。

**Comment by html5syt** [comment]
而且如果可以直接备份到网盘就好了。

**Comment by html5syt** [comment]
#4585

**Comment by woshichenghaibo** [comment]
> 手机我记得是可以 下载备份文件的 你用的什么浏览器

我的via不支持
