### ISSUE TITLE
alist元信息在更改后会恢复到原来的内容

### ISSUE THREAD

**Issue by yearnstudio** [alist-org/alist#4558]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.16.3

### Driver used / 使用的存储驱动

123pan、WebDav

### Describe the bug / 问题描述

当我修改根目录的元信息后，第二天就恢复到了我更改前的样子。但是在更改后是正常的。我的alist部署在Repl上

### Reproduction / 复现链接

https://alist.2009yangyi.repl.co

**Comment by Xhofe** [comment]
你在repl上使用sqlite3数据库相当于裸奔，任何人都可以查看修改你的所有信息。
