### ISSUE TITLE
使用cloudflare worker反代时出现EOF错误

### ISSUE THREAD

**Issue by html5syt** [alist-org/alist#4559]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.18.0

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

由于服务器域名被*，又无法更换，所以我是用cloudflare workers反代到另一个可以国内访问的域名，但我访问这个反代后的域名，在登录和访问文件的地方都显示“EOF”。
注：反代的源码暂时复制不过来，应该是网上比较长的那一种。

### Reproduction / 复现链接

https://alist.html5syt.cf/

**Comment by html5syt** [comment]
忘记说了，我使用docker版本，在okteto上部署

**Comment by Xhofe** [comment]
你的cf workers代码对content-type为`application/json;charset=UTF-8`的处理有问题。

**Comment by mianlaodie** [comment]
我也是同样的问题  楼主解决了么？
