### ISSUE TITLE
希望增加任务功能，即 定义某个文件夹文件自动移动至目标文件夹，实现文件的自动归档

### ISSUE THREAD

**Issue by lgclgclgc111** [alist-org/alist#4560]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加任务功能，即 定义某个文件夹文件自动移动至目标文件夹，实现文件的自动归档，这里说两个应用
①比如说我所有的电影通过埃里云盘下到某个文件夹，命名为'movie_download'，alist检测到movie_download有新文件出现，自动触发脚本，按照写好的规则，自动复制到本地存储的‘movie’文件夹，并可以实现规则的自主定义以及检测周期，可以尝试使用软链、硬链、复制或者剪切几种模式的选择
②我的手机拍的照片，通过某个网盘自动存储，alist检测出某网盘有新文件出现，按照定义好的规则，自动移动或者复制至我的本地存储‘picture’文件夹，实现照片的自动管理
相信有了这个功能，会使Alist有质的提升与改变，本人已经购买了桌面版

### Suggested solution / 实现思路

Python 脚本

**Comment by ZXiangQAQ** [comment]
这功能，隔壁nas-tools停更了想用alist重构是吧

**Comment by lgclgclgc111** [comment]
我用的nastool老版，怎么说呢，感觉这个功能还是交给alist比较好，nastool只负责刮削就行，毕竟下载方式不止qb一种啊，咱们这个多网盘支持太厉害了，👍🏻发自我的手机-------- 原始邮件 --------发件人： ZXiangQAQ ***@***.***>日期： 2023年6月14日周三 上午9:27收件人： alist-org/alist ***@***.***>抄送： lgclgclgc111 ***@***.***>, Author ***@***.***>主    题： Re: [alist-org/alist] 希望增加任务功能，即 定义某个文件夹文件自动移动至目标文件夹，实现文件的自动归档 (Issue #4560)
这功能，隔壁nas-tools停更了想用alist重构是吧

**Comment by huolanyun** [comment]
增加任务脚本功能
可以自定义脚本 实现 自动创建 复制 删除 文件等脚本支持的任务

**Comment by CafeBabe202** [comment]
希望添加该功能，这样就可以自动的将本地文件夹发布到自己的网站了

**Comment by lgclgclgc111** [comment]
继续顶一下，非常希望拥有这样的功能，这样就能实现下载文件的自动归档，自动备份，对于数据的安全也很有必要

**Comment by tx1ee** [comment]
期待这个功能

**Comment by AIEOV** [comment]
用api ，目录设置好存储。 然后脚本移动就可以了
