### ISSUE TITLE
希望增加默认跳转入口关闭功能

### ISSUE THREAD

**Issue by Winyer** [alist-org/alist#4564]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如果关闭了guest访问，那访问到alist的时候会自动跳转到登录页面，希望能够可以手动改变这一功能，比如自定义后台地址加自定义guest被禁用后访问目录显示的内容等，如，访问a.com/123时，可以设置显示的文字或者是跳转到别的网址，这也是从安全方面的更好考虑，防止被爆破密码，我就曾被登录过后台，后来想想可能是因为用了admin+admin123这样的密码，加上guest禁用后直接访问的后台地址，所以，请修改它。

### Suggested solution / 实现思路

如果WEB端代码分离，这个问题很好解决，但是因为Alist的web端和后端代码融为一体，所以需要你们修改了

### Additional context / 附件

无

**Comment by anwen-anyi** [comment]
正常不是`弱口令`密码不会被爆破，加上连续错误6次就冻结30分钟不能输入密码

**Comment by Xhofe** [comment]
无异于掩耳盗铃
