### ISSUE TITLE
阿里云盘 https://api.nn.ci/alist/ali_open/token EOF  并且二维码无法获取token

### ISSUE THREAD

**Issue by jzdayz** [alist-org/alist#4569]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.18.0

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

无法获取qrCode并且后台报错(使用wifi，联通电话卡均无法获取qrCode)

<img width="1439" alt="image" src="https://github.com/alist-org/alist/assets/35563513/71d9ae78-6654-41c0-877e-8fc94bbc8e7d">

### Reproduction / 复现链接

https://alist.nn.ci/tool/aliyundrive/request.html

### Logs / 日志

```log
INFO[2023-06-13 12:25:54] reading config file: data/config.json        
INFO[2023-06-13 12:25:54] load config from env with prefix: ALIST_     
INFO[2023-06-13 12:25:54] init logrus...                               
INFO[2023-06-13 12:25:54] start server @ 0.0.0.0:5244                  
INFO[2023-06-13 12:25:54] Aria2 not ready.                             
INFO[2023-06-13 12:25:54] qbittorrent not ready.                       
2023/06/13 12:25:58.659748 ERROR RESTY Post "https://api.nn.ci/alist/ali_open/token": EOF, Attempt 1
2023/06/13 12:26:02.775932 ERROR RESTY Post "https://api.nn.ci/alist/ali_open/token": EOF, Attempt 2
2023/06/13 12:26:06.982476 ERROR RESTY Post "https://api.nn.ci/alist/ali_open/token": EOF, Attempt 3
2023/06/13 12:26:11.275825 ERROR RESTY Post "https://api.nn.ci/alist/ali_open/token": EOF, Attempt 4
ERRO[2023-06-13 12:26:11] failed get enabled storages: Post "https://api.nn.ci/alist/ali_open/token": EOF
failed init storage
github.com/alist-org/alist/v3/internal/op.initStorage
	/source/internal/op/storage.go:99
github.com/alist-org/alist/v3/internal/op.LoadStorage
	/source/internal/op/storage.go:80
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
	/source/internal/bootstrap/storage.go:20
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1172 
```

**Comment by anwen-anyi** [comment]
api.nn.ci被阻断了，目前得挂全局代理才可以（后面暂时不清楚）

阿里云盘open，今天出现的会比较多，默认会重试5次
等加载完把后台的阿里云盘的Oauth令牌链接
换成 https://api-cf.nn.ci/alist/ali_open/token 
或者 https://api.xhofe.top/alist/ali_open/token 
 - 热心群友提供的：https://sni_api_nn_ci.cooluc.com/alist/ali_open/token

![image](https://github.com/alist-org/alist/assets/56105412/760a597c-0f16-416c-a7fa-90c47d6417d8)

**Comment by jzdayz** [comment]
> 

好的，感谢，我把这个域名加入proxy后就能正常使用了

**Comment by msycn** [comment]
> > api.nn.ci被阻断了，目前得挂全局代理才可以（后面暂时不清楚）
> > 阿里云盘open，今天出现的会比较多，默认会重试5次 等加载完把后台的阿里云盘的Oauth令牌链接 换成 https://api-cf.nn.ci/alist/ali_open/token 或者 https://api.xhofe.top/alist/ali_open/token
> > 
> > * 热心群友提供的：https://sni_api_nn_ci.cooluc.com/alist/ali_open/token
> > 
> > ![image](https://user-images.githubusercontent.com/56105412/245352767-760a597c-0f16-416c-a7fa-90c47d6417d8.png)
> 
> ## 好的，感谢，我把这个域名加入proxy后就能正常使用了

感谢 mark一下

**Comment by msycn** [comment]
> api.nn.ci被阻断了，目前得挂全局代理才可以（后面暂时不清楚）
> 
> 阿里云盘open，今天出现的会比较多，默认会重试5次 等加载完把后台的阿里云盘的Oauth令牌链接 换成 https://api-cf.nn.ci/alist/ali_open/token 或者 https://api.xhofe.top/alist/ali_open/token
> 
> * 热心群友提供的：https://sni_api_nn_ci.cooluc.com/alist/ali_open/token
> 
> ![image](https://user-images.githubusercontent.com/56105412/245352767-760a597c-0f16-416c-a7fa-90c47d6417d8.png)

感谢 mark一下
