### ISSUE TITLE
阿里云盘获取 token 失败

### ISSUE THREAD

**Issue by fioepq9** [alist-org/alist#4571]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.18.0

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

如题
![image](https://github.com/alist-org/alist/assets/63338741/51ab0dba-d088-40ba-b434-46eb2e25f503)
允许后，跳转回来一直转圈

### Reproduction / 复现链接

https://alist.nn.ci/tool/aliyundrive/request.html

### Logs / 日志

![1686636786909](https://github.com/alist-org/alist/assets/63338741/5b2d3036-16f4-4091-85cc-a2a26a14488d)

**Comment by kissaa6** [comment]
之前挂载的阿里云盘也无法访问了，后台显示Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by Xhofe** [comment]
- #4572
