### ISSUE TITLE
自定义字幕路径

### ISSUE THREAD

**Issue by fangyuan99** [alist-org/alist#4573]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用`阿里云open`播放时，**目前仅支持和视频文件相同的字幕文件**，如果资源里面带有`简体中文.ass`或者`繁体中文.ass`这种字幕需要**手动重命名**才能正确加载，是否可以让**用户自定义选择字幕的路径**呢？

**Comment by fangyuan99** [comment]
😂并且电脑上的字幕不能调节大小的话有点太小了，是否可以自定义字幕大小

**Comment by kesonglu** [comment]
楼上不知道 有个东西叫webdav嘛 有个软件叫KODI嘛 这种问题就不用提了

**Comment by ITManCHINA** [comment]
挂载WebDAV，用Infuse、PotPlayer、Kodi、VLC之类的播放器看嘛
