### ISSUE TITLE
potplayer播放alist代理的webdav视频开始频繁报错

### ISSUE THREAD

**Issue by gedo123** [alist-org/alist#4583]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v2.0.0

### Driver used / 使用的存储驱动

夸克，阿里云盘open

### Describe the bug / 问题描述

使用本地代理的webdav，稳定使用了很长一段时间，最近开始提示“无法播放，服务器已关闭或地址错误，尝试渲染下列pin时失败了”，看上去似乎是播放器无法获取正确的视频地址
尝试过重新启动alist，重新挂载网盘，或重新在播放器里设置地址，或换成302代理，以及从网页点开视频再跳转到播放器均无果
现只能使用浏览器alist网页上的播放

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/95561576/983d0366-5135-485f-bd84-28f36fa19eb1)
![image](https://github.com/alist-org/alist/assets/95561576/c1ee938f-2fb4-4b62-8d31-f297b4aa8aa3)
![image](https://github.com/alist-org/alist/assets/95561576/93967222-900b-4eb6-9991-239cda50300d)

**Comment by ccstarhyl** [comment]
遇到同样问题，baidu网盘，页面可以播放，web权限也开了，potplayer也是报这个错
