### ISSUE TITLE
希望增加定时备份alist配置到挂载的网盘的功能

### ISSUE THREAD

**Issue by html5syt** [alist-org/alist#4585]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

来自于issue #4551 
我在一些免费平台部署alist时，经常担心本地配置丢失，所以我经常备份配置并手动上传到网盘中，但是这太麻烦了，希望增加定时备份alist配置到挂载的网盘的功能。

### Suggested solution / 实现思路

定时部分可以使用cron定时任务，定时触发备份操作并在服务器临时缓存+上传到指定文件夹，如果可以的话希望可以在网页上显示备份日志。

**Comment by huolanyun** [comment]
希望增加任务脚本功能，自定义脚本实行 实现定时任务

**Comment by Gokou-Ruri** [comment]
alist的备份数据可是明文保存的啊，你就这么随便把token啥的保存到网盘？心真大啊。

**Comment by Gokou-Ruri** [comment]
alist的备份数据可是明文保存的啊，你就这么随便把token啥的保存到网盘？心真大啊。
