### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by lugangmail** [alist-org/alist#4586]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0

### Driver used / 使用的存储驱动

aliyun open  阿里云盘open

### Describe the bug / 问题描述

状态: invalid character '<' looking for beginning of value
![image](https://github.com/alist-org/alist/assets/29701635/91d2cf7b-38bc-446f-a29d-9f58ebc535db)

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/29701635/b05337c0-87d6-4b1c-aa83-dd31e2ed7e0a)

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/29701635/60fc16d7-20d0-4a69-a4cd-4ac4065bee4f)

**Comment by html5syt** [comment]
你可以先尝试更新一下alist，或许有用
