### ISSUE TITLE
阿里云盘，音乐，iphone 无法播放

### ISSUE THREAD

**Issue by hyy34** [alist-org/alist#4596]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.18.0

### Driver used / 使用的存储驱动

阿里云盘OPEN

### Describe the bug / 问题描述

上传的歌曲，flac格式，iphone无法在线播放，提示：An audio error has occurred，player will skip forward in 2 seconds。然后直接播放下一首，提示依旧，循环。
PC端，安卓端，均正常。、
更换天翼云盘，问题解决。

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E8%83%BD%E9%A2%84%E8%A7%88%E8%A7%86%E9%A2%91%E6%88%96%E9%9F%B3%E9%A2%91%E6%96%87%E4%BB%B6

**Comment by ain-soph** [comment]
@hyy34 看看有没有可能是权限问题。我刚刚也遇到这问题了，发现是音频文件权限不对。设置成777就好了。

https://github.com/DIYgod/APlayer/issues/704#issuecomment-1920653574
