### ISSUE TITLE
中国移动网盘显示鉴权失败

### ISSUE THREAD

**Issue by 1273082756** [alist-org/alist#4598]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.18.0

### Driver used / 使用的存储驱动

中国移动网盘

### Describe the bug / 问题描述

输入cookie与账号后点击保存,显示鉴权失败

### Reproduction / 复现链接

无

### Logs / 日志

鉴权失败

**Comment by Xhofe** [comment]
- #4563
