### ISSUE TITLE
Docker版本的alist在设置本机存储中，无法正确读取本机存储目录及文件

### ISSUE THREAD

**Issue by lcvy** [alist-org/alist#4604]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

Docker -latest

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

部署：
docker执行的命令如下：
docker run -d --privileged=true --restart=always -v /etc/alist:/opt/alist/data -p 8089:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest

错误：
“/www/wwwlogs”目录无法正确挂载
![image](https://github.com/alist-org/alist/assets/54807723/dcc2c1d1-692e-41c2-b111-f1c7ca2993e4)

日志：
容器重启后错误提示。
![image](https://github.com/alist-org/alist/assets/54807723/106a6122-2402-4e8f-8b98-5428be9c14d7)

log.log错误提示及“/www/wwwlogs”目录真实存在。
![image](https://github.com/alist-org/alist/assets/54807723/814880df-6c95-42dd-bd92-90333cd42f47)

发现：
“/etc”目录可成功读取，读写权限正常；部分目录可挂载，但不可读取。
“/var”目录可成功挂载，但子文件无法读取。
![image](https://github.com/alist-org/alist/assets/54807723/701b023c-dc4a-4ed1-9f4e-9634c1176e09)

### Reproduction / 复现链接

无。

### Logs / 日志

见错误描述。

**Comment by Xhofe** [comment]
https://www.google.com/search?q=%E4%BB%80%E4%B9%88%E6%98%AF%E5%AE%B9%E5%99%A8
