### ISSUE TITLE
定时备份一个网盘的数据到另一个网盘中

### ISSUE THREAD

**Issue by html5syt** [alist-org/alist#4605]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我有一个office e5开发者账号的OneDrive和一个阿里云盘，由于开发原因程序会在OneDrive里生成一些应用数据，由于担心e5不知道哪一天可能被封，我只好手动复制数据到阿里云盘，但是很麻烦又经常会忘记。请问可不可以增加定时备份一个网盘中的数据到到另一个网盘中的功能？

### Suggested solution / 实现思路

利用定时任务（cron或者其他）定时查询源网盘里的指定文件夹的文件是否有更新（可以利用索引的自动更新），如果有更新，就将有变化的文件复制到备份网盘里

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/issues/4585  你不是已经提交过一了吗?

**Comment by anwen-anyi** [comment]
大概率没戏（我大胆猜测一下~） 而且AList只是一个列表程序 不是用来上传备份的QAQ~（也不适合用来多上传/大文件上传)

**Comment by html5syt** [comment]
> 大概率没戏（我大胆猜测一下~） 而且AList只是一个列表程序 不是用来上传备份的QAQ~（也不适合用来多上传/大文件上传)

其实我需要copy的文件也不是很大，就几个阅读软件产生的json的同步数据，大约也只有1mb左右，如果有大文件我直接用官方app手动上传就好了

**Comment by anwen-anyi** [comment]
> > 大概率没戏（我大胆猜测一下~） 而且AList只是一个列表程序 不是用来上传备份的QAQ~（也不适合用来多上传/大文件上传)
> 
> 其实我需要copy的文件也不是很大，就几个阅读软件产生的json的同步数据，大约也只有1mb左右，如果有大文件我直接用官方app手动上传就好了

https://github.com/z-mio/Alist-bot 你试试这个，还有你上一个问题 https://github.com/alist-org/alist/issues/4585 这个项目也能解决

**Comment by html5syt** [comment]
> > > 大概率没戏（我大胆猜测一下~） 而且AList只是一个列表程序 不是用来上传备份的QAQ~（也不适合用来多上传/大文件上传)
> > 
> > 
> > 其实我需要copy的文件也不是很大，就几个阅读软件产生的json的同步数据，大约也只有1mb左右，如果有大文件我直接用官方app手动上传就好了
> 
> https://github.com/z-mio/Alist-bot 你试试这个，还有你上一个问题 #4585 这个项目也能解决

我待会去试试，把它部署在replit上，应该可以。

**Comment by anwen-anyi** [comment]
> 

:sob: :sob: :sob: 放过repliit吧~~~~

**Comment by html5syt** [comment]
> > > > > 大概率没戏（我大胆猜测一下~） 而且AList只是一个列表程序 不是用来上传备份的QAQ~（也不适合用来多上传/大文件上传)
> > > > 
> > > > 
> > > > 其实我需要copy的文件也不是很大，就几个阅读软件产生的json的同步数据，大约也只有1mb左右，如果有大文件我直接用官方app手动上传就好了
> > > 
> > > 
> > > https://github.com/z-mio/Alist-bot 你试试这个，还有你上一个问题 #4585 这个项目也能解决
> > 
> > 
> > 我待会去试试，把它部署在replit上，应该可以。
> 
> sob sob sob 放过repliit吧~~~~
额。。。replit我觉得挺好用的，啥都可以干
我alist就搭上面
