### ISSUE TITLE
天翼云盘图形验证码错误

### ISSUE THREAD

**Issue by okami-chen** [alist-org/alist#4612]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

189

### Describe the bug / 问题描述

已禁用OCR，保存存储，提示错误。

之前的版本返回存储列表会显示验证码，但此版本只报错，未显示验证码。

### Reproduction / 复现链接

https://d.131.im/@manage/storages/edit/17

### Logs / 日志

Failed load storage: failed init storage: login failed,No toUrl obtained, msg: 图形验证码错误，请重新输入

**Comment by Leoin1** [comment]
我和你一样的问题，天翼云登陆逻辑问题。
