### ISSUE TITLE
增加 底部连接和描述 符合备案的要求

### ISSUE THREAD

**Issue by pt2go** [alist-org/alist#4614]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增加 底部连接和描述 符合备案的要求，类似
![image](https://github.com/alist-org/alist/assets/40349936/cee50055-446c-48bb-bc72-c654c61c5103)

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/config/global.html#%E8%87%AA%E5%AE%9A%E4%B9%89body
