### ISSUE TITLE
鉴权失败 

### ISSUE THREAD

**Issue by okami-chen** [alist-org/alist#4615]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

139 189

### Describe the bug / 问题描述

189提示：
```
状态: 

login failed,No toUrl obtained, msg: 图形验证码错误，请重新输入

```

移动云盘提示:
```
状态: 

鉴权失败
```

### Reproduction / 复现链接

https://d.131.im

**Comment by okami-chen** [comment]
提示：
```
态: 

login failed,No toUrl obtained, msg: 图形验证码错误，请重新输入
```

**Comment by Xhofe** [comment]
- 139: 已更换鉴权方式，请查阅文档
- 189: web端登录已更换为滑动验证码，不再支持ocr与手动输入，若需要验证码请使用cookie登录或使用`189pc`驱动。
