### ISSUE TITLE
你好大佬，请问下fuse有没有被安排上日程？

### ISSUE THREAD

**Issue by user1121114685** [alist-org/alist#4617]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://github.com/orgs/alist-org/projects/1?pane=issue&itemId=6060397

### Suggested solution / 实现思路

使用fuse ，在alist中实现fuse的几个接口

### Additional context / 附件

无

**Comment by hankqqu** [comment]
> ### Please make sure of the following things
> 
> - [x] I have read the [documentation](https://alist.nn.ci).
> - [x] I'm sure there are no duplicate issues or discussions.
> - [x] I'm sure this feature is not implemented.
> - [x] I'm sure it's a reasonable and popular requirement.
> 
> ### Description of the feature / 需求描述
> 
> https://github.com/orgs/alist-org/projects/1?pane=issue&itemId=6060397
> 
> ### Suggested solution / 实现思路
> 
> 使用fuse ，在alist中实现fuse的几个接口
> 
> ### Additional context / 附件
> 
> 无

**Comment by Bennie-CHEN** [comment]
up
