### ISSUE TITLE
钉钉单点登录直接获得管理员权限

### ISSUE THREAD

**Issue by musicking** [alist-org/alist#4619]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

AliyunOSS

### Describe the bug / 问题描述

后台配置钉钉单点登录，使用钉钉扫码登录后，直接是管理员权限！
![image](https://github.com/alist-org/alist/assets/8167146/0a2f6645-d5ed-4330-a78f-fa093dbdf661)

### Reproduction / 复现链接

NO

**Comment by Xhofe** [comment]
绑定的普通用户，登录是管理员？

**Comment by musicking** [comment]
> 绑定的普通用户，登录是管理员？

还没有进行任何绑定。
![image](https://github.com/alist-org/alist/assets/8167146/b533e863-fb5b-45f0-8d13-470efdd93f4c)
部署完之后，使用admin正常登录，进行钉钉登录配置，然后注销admin管理登录，通过钉钉授权登录，可以进入管理员后台。

**Comment by anwen-anyi** [comment]
你使用钉钉绑定了admin 肯定是登录的admin后台 没有问题~

**Comment by anwen-anyi** [comment]
刚验证了一下没有出现你的情况   你试试点击绑定单点登录再解绑试试
![image](https://github.com/alist-org/alist/assets/56105412/e4b37e4d-c5cf-41f0-9524-d830285e66a8)

**Comment by musicking** [comment]
> 刚验证了一下没有出现你的情况 你试试点击绑定单点登录再解绑试试 ![image](https://user-images.githubusercontent.com/56105412/246720118-e4b37e4d-c5cf-41f0-9524-d830285e66a8.png)

按照这个操作，解绑后就不能登录了，感觉大佬指导。
![image](https://github.com/alist-org/alist/assets/8167146/0f0ac7a0-046e-4d8b-b846-703af46a9974)
