### ISSUE TITLE
新版本CF反代无法下载

### ISSUE THREAD

**Issue by syscc** [alist-org/alist#4622]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.19

### Driver used / 使用的存储驱动

ONEDRIVEAPP

### Describe the bug / 问题描述

从3.18升级3.19后，cf的workers反代无法正常下载，访问反代域名是正常的但是下载是错误1101，仓试过重置令牌，依然无效，包括吧alist部署到新加坡依然如此

### Reproduction / 复现链接

https://alist.wq.ee/d/E3/system/windows10_LTSC_2021_64BIT.ISO

**Comment by Xhofe** [comment]
You've requested a page on a website that is part of the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (alist-proxy.777678.xyz) resolved to an IP address that the owner of the website does not have access to.

**Comment by syscc** [comment]
我之前一直正常的，更新到3.19后出现这个情况了
