### ISSUE TITLE
部署在子路径时右键 “复制链接” 出现子路径丢失

### ISSUE THREAD

**Issue by zent00** [alist-org/alist#4624]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

Local storage

### Describe the bug / 问题描述

假设 alist 部署地址为 https://www.xxx.com/alist

在页面上右键点击某个目录，选择 `复制链接`，正常链接应该为：
https://www.xxx.com/alist/Videos/202306

实际复制到的链接为：
https://www.xxx.com/Videos/202306

子路径 `alist` 丢失。

**补充信息**：
* 对文件进行操作时没有问题，仅在对目录操作时有这个问题。
* 鼠标悬停在目录上时，能看到正确的链接，只是右键复制链接时会丢失子路径。

### Reproduction / 复现链接

无

**Comment by anwen-anyi** [comment]
config.json  --> site_url 配置了没？

**Comment by zent00** [comment]
> `config.json` --> `site_url` 配置了没？

配置了。

`"site_url": "/alist",`

**Comment by anwen-anyi** [comment]
> > `config.json` --> `site_url` 配置了没？
> 
> 配置了。
> 
> `"site_url": "/alist",`

你这样写是不对的吧？
应该是 `"site_url": "http(s)://URL/alist",`

**Comment by zent00** [comment]
> > > `config.json` --> `site_url` 配置了没？
> > 
> > 
> > 配置了。
> > `"site_url": "/alist",`
> 
> 你这样写是不对的吧？ 应该是 `"site_url": "http(s)://URL/alist",`

刚刚尝试了填写完整域名加子路径，`"site_url": "https://www.xxx.com/alist",`

重启容器还是一样，没变化。

**Comment by anwen-anyi** [comment]
> > > > `config.json` --> `site_url` 配置了没？
> > > 
> > > 
> > > 配置了。
> > > `"site_url": "/alist",`
> > 
> > 
> > 你这样写是不对的吧？ 应该是 `"site_url": "http(s)://URL/alist",`
> 
> 刚刚尝试了填写完整域名加子路径，`"site_url": "https://www.xxx.com/alist",`
> 
> 重启容器还是一样，没变化。

好吧，等开发者看看什么情况吧

**Comment by zent00** [comment]
刚刚发现好像使用右键下载目录也不成功，一直显示 Fetching 目录中的第一个文件，然后就没有动静了。

另外，下载文件是没有问题的。
