### ISSUE TITLE
挂载的百度网盘，无法加载及下载 

### ISSUE THREAD

**Issue by xjsyy** [alist-org/alist#4628]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

Failed to fetch http://127.0.0.1:5244/p/test/jihuo%20.txt?sign=oww_ADlyerlKLA9Iop_EAkkPGmCCpzFe6kejbR1-emY=:0: AxiosError: Network Error
![246638364-6f39e1bf-41a7-4127-988a-58215f40472f](https://github.com/alist-org/alist/assets/118407022/4154ccfb-12dc-4ced-8406-60a15fe02f50)

挂载配置：下载接口用的非官方，开启了Web代理,WebDav策略用的本地代理，签名已启用。
下载接口如果用官方，可以下载和加载。

### Reproduction / 复现链接

无

**Comment by anwen-anyi** [comment]
非官方不可保证可用性
