### ISSUE TITLE
用一个盘做另一个盘的缓存

### ISSUE THREAD

**Issue by tempwswm** [alist-org/alist#4643]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

用一个盘为另一个盘做缓存
主盘是存储盘，缓存盘用作实际下载盘
用流量便宜或可达性高的盘来给低速大容量盘做缓存
是负载兼容的另一种用法

### Suggested solution / 实现思路

这个pr是可以用的，但是请检查代码规范性及可能的漏洞
https://github.com/alist-org/alist/pull/4642

**Comment by youtehub** [comment]
好东西，下大文件的时候很有用

**Comment by JsonSong89** [comment]
有点没理解,是可以用阿里云盘加速百度云盘吗?

**Comment by tempwswm** [comment]
> 有点不懂，是可以用阿里云盘加速百度云盘吗？

可以用任何盘加速任何盘

**Comment by HGameBlog** [comment]
我更觉得这可以理解是一种备份行为，a盘备份b盘，如果a盘被封了，还有b盘补救

**Comment by JsonSong89** [comment]
> 

这个的前提还是把百度的资源放进阿里云盘吧
难道是说把百度资源下载到本地,然后再上传到阿里云盘?

**Comment by lxcau** [comment]
是否这样：将百度网盘中的最近经常访问的资源cache到本地或者阿里网盘，然后访问百度网盘这些资源的时候，优先从cache目录访问，如果cache目录中没有，再从百度网盘服务器访问

**Comment by tempwswm** [comment]
捞一下

**Comment by tempwswm** [comment]
> 

是的，如果没有的话会自动从主盘复制一份到缓存盘
