### ISSUE TITLE
正则表达式重命名预览正确但修改错误

### ISSUE THREAD

**Issue by lelemka0** [alist-org/alist#4644]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

aliyundrive_open

### Describe the bug / 问题描述

正则表达式文件重命名 预览显示正确 但修改结果错误

```
源文件名: ^(\d+).mp4$
新文件名: 第$1话.mp4
```

源文件: `250.mp4`，实际修改为`第.mp4`

修改预览：
![image](https://github.com/alist-org/alist/assets/20322043/7096da18-eff1-41bd-aeaa-b32dc7734aea)

api请求体：
![image](https://github.com/alist-org/alist/assets/20322043/98717ff8-3f2b-45c6-b4d7-d8690259af0d)

修改结果：
![image](https://github.com/alist-org/alist/assets/20322043/b0946e94-15c0-43ed-bf1d-de53b582dcd4)

### Reproduction / 复现链接

没有公网链接

**Comment by Xhofe** [comment]
@varg1714

**Comment by xiaoyaliu00** [comment]
是的，一般引用匹配 $1 $2就经常出这样的问题

**Comment by varg1714** [comment]
我排查了下，似乎是Go解析正则和JS有些区别导致的。第$1话.mp4中分组被解析成了"$1话"而不是"$1"，使用“第${1}话.mp4”这个才可以。（不过按文中描述，只有字母数字下划线会被匹配成分组名，中文不应该被匹配才对。）

<img width="548" alt="image" src="https://github.com/alist-org/alist/assets/51254954/6ff3353c-f07f-49fe-a4a1-cd363762c888">
<img width="707" alt="image" src="https://github.com/alist-org/alist/assets/51254954/4a499343-af6e-44db-a0d6-39eef7502b93">

或许有其他人对Go的正则了解多些的么？这个PR是当时为了做这个功能现看go写的，所以可能没时间仔细研究这一块的。如果没有比较好的方式解决这一点那我就把这个重命名的调用放到前端去，保持和预览看到的一致。

**Comment by varg1714** [comment]
已提PR
