### ISSUE TITLE
音乐播放器能否增强一些

### ISSUE THREAD

**Issue by jxjxjhjh** [alist-org/alist#4650]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在需要打开音乐文件所在目录，点击某个音乐文件，才能跳转到音乐播放器，而且网址还是点击的音乐文件的直连地址。
每一次都要重复这个操作，比较麻烦，能否增加一个设定，可以直接打开音乐播放器界面，这样就方便多了。

### Suggested solution / 实现思路

增加一个类似 https://xxx.com/player 之类的地址，打开就是音乐播放界面，后台可以设定音乐目录。

**Comment by Gokou-Ruri** [comment]
个人觉得alist的媒体播放功能主要还是以临时预览作用为主吧，真要做成易用的播放器的话，各种文件格式的预览功能都得大改了，而且体验可能还不如本地播放器好。
