### ISSUE TITLE
Universal Configuration DOCS 针对OIDC的通用配置文档

### ISSUE THREAD

**Issue by finalparanoia** [alist-org/alist#4652]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在针对OIDC的功能已经基本实现，但仍旧缺乏：

针对OIDC的通用配置文档
或
更多OIDC后端的适配

比如：
Authelia是一个流行的OIDC提供商，但在与AList的集成中仍存在一些问题。
转跳
/api/oidc/authorization?client_id=alist&redirect_uri=https%3A%2F%2Fdisk.dataark.org%2Fapi%2Fauth%2Fsso_callback%3Fmethod%3Dsso_get_token&response_type=code&scope=openid+profile&state=state
将会获得
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls."}

### Suggested solution / 实现思路

我相信这上述问题是由不同的OIDC实现造成的，并可以通过正确的配置解决。

**Comment by finalparanoia** [comment]
一个可能的思路是通过.well-known实现OIDC的自动配置，这个特性被Authelia所支持，我不确定这个特性在其他OIDC提供商的支持状态。

**Comment by catfishlty** [comment]
@finalparanoia 
经测试Authelia已经能用了，不知道您解决这个问题没。
https://github.com/AlistGo/alist/issues/3914#issuecomment-2900940285
