### ISSUE TITLE
ios nplayer挂载webdav，打不开阿里云PDF文件，一直转圈。电脑，iphone，ipad网页端alist都正常打开PDF

### ISSUE THREAD

**Issue by WinterBoring** [alist-org/alist#4657]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

本地服务器，甲骨文云都装了alist测试！http，https方式都试过。
电脑，iphone，ipad网页端进alist打开阿里云盘PDF文件都正常；RaiDrive挂载alist，电脑端打开PDF正常，已解决IDM问题！
问题：iphone，ipad用nplayer webdav挂载，打开PDF就一直转圈，也没有错误提示。但iphone，ipad用nplayer webdav挂载自建云盘Cloudreve，打开PDF正常，（Cloudreve未添加在alist）所以排除nplayer问题！应该是nplayer和alist之间的问题，请求大佬支援，谢谢！

### Reproduction / 复现链接

没有链接！

**Comment by Gokou-Ruri** [comment]
方便上传pdf文件吗？我试试看？

**Comment by WinterBoring** [comment]
上传没有问题，就是不能查看PDF

**Comment by xhofe** [comment]
nplayer对302的支持可能不太好 你可以尝试选择 `webdav策略`为 `本地代理`

**Comment by WinterBoring** [comment]
> nplayer对302的支持可能不太好 你可以尝试选择 为`webdav策略``本地代理`

好的，谢谢！我试试！

**Comment by WinterBoring** [comment]
> nplayer对302的支持可能不太好 你可以尝试选择 为`webdav策略``本地代理`

测试了，改为本地代理还是不行！但自建的云盘webdav打开pdf就没问题
