### ISSUE TITLE
又拍云存储没有用

### ISSUE THREAD

**Issue by izhangguapi** [alist-org/alist#4662]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

又拍云存储

### Describe the bug / 问题描述

设置都没问题，不知道为什么，他会显示下列内容：
failed get objs: failed to list objs: list error: status=401, code=40100005, message=signature error, request-id=289436f93ff2a6ee45d8388facc98f40

### Reproduction / 复现链接

https://cloud.zhangguapi.com/upyun

### Logs / 日志

[GIN] 2023/06/28 - 04:48:04 | 200 |     124.925µs | 120.235.117.138 | GET      "/upyun"
[GIN] 2023/06/28 - 04:48:04 | 200 |     633.521µs | 120.235.117.138 | GET      "/api/public/settings"
[GIN] 2023/06/28 - 04:48:04 | 200 |     451.336µs | 120.235.117.138 | GET      "/api/me"
[GIN] 2023/06/28 - 04:48:04 | 200 |     765.097µs | 120.235.117.138 | POST     "/api/fs/get"
[31mERRO[0m[2023-06-28 04:48:04] fs/list: list error: status=401, code=40100005, message=signature error, request-id=289436f93ff2a6ee45d8388facc98f40
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/home/wwwroot/cloud/git/alist/internal/op/fs.go:120
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/home/wwwroot/cloud/git/alist/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/home/wwwroot/cloud/git/alist/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/home/wwwroot/cloud/git/alist/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/home/wwwroot/cloud/git/alist/internal/op/fs.go:117
github.com/alist-org/alist/v3/internal/fs.list
	/home/wwwroot/cloud/git/alist/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/home/wwwroot/cloud/git/alist/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/home/wwwroot/cloud/git/alist/server/handles/fsread.go:82
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/wwwroot/cloud/git/alist/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/wwwroot/cloud/git/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1991
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594 
[31mERRO[0m[2023-06-28 04:48:04] failed list /upyun: list error: status=401, code=40100005, message=signature error, request-id=289436f93ff2a6ee45d8388facc98f40
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/home/wwwroot/cloud/git/alist/internal/op/fs.go:120
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/home/wwwroot/cloud/git/alist/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/home/wwwroot/cloud/git/alist/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/home/wwwroot/cloud/git/alist/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/home/wwwroot/cloud/git/alist/internal/op/fs.go:117
github.com/alist-org/alist/v3/internal/fs.list
	/home/wwwroot/cloud/git/alist/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/home/wwwroot/cloud/git/alist/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/home/wwwroot/cloud/git/alist/server/handles/fsread.go:82
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/wwwroot/cloud/git/alist/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/wwwroot/cloud/git/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1991
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
failed get objs 
[GIN] 2023/06/28 - 04:48:04 | 200 |   96.056184ms | 120.235.117.138 | POST     "/api/fs/list"

**Comment by izhangguapi** [comment]
看了也解决不了

**Comment by anwen-anyi** [comment]
无任何问题 自己参阅文档仔细添加
![image](https://github.com/alist-org/alist/assets/56105412/57a795e9-c05f-4324-b5c0-2f8c80af1da9)
![image](https://github.com/alist-org/alist/assets/56105412/98dc6452-f6e6-4d9d-bfc5-3ae686324506)

**Comment by izhangguapi** [comment]
感谢您的建议，是upyun密码的问题
