### ISSUE TITLE
一刻相册无法下载

### ISSUE THREAD

**Issue by RyanQwQ** [alist-org/alist#4666]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

一刻相册

### Describe the bug / 问题描述

一刻相册挂载后无法播放视频以及打开文件，只能列出列表

### Reproduction / 复现链接

https://apn.moedot.net/d/yike/%E6%97%A0%E6%95%8C11.mp4

### Logs / 日志

failed link: failed get link: errno: 1, refer to https://photo.baidu.com/union/doc

**Comment by foxxorcat** [comment]
所有图片视频都无法播放或查看吗

**Comment by anwen-anyi** [comment]
截图一下你的填写配置，昨晚我刚试了没有问题

**Comment by RyanQwQ** [comment]
> 截图一下你的填写配置，刚试了没有问题（以及你测试的视频文件多大） 视频虽然没画面但是可以播放，是因为编码问题属于正常情况（调用下面播放器就正常有画面了） ![](https://user-images.githubusercontent.com/56105412/249642850-04230b91-4796-4ac3-9990-75087ea90de4.png)

我换了个账号尝试了下没问题，估计是被限制了？
