### ISSUE TITLE
希望增强markdown预览功能

### ISSUE THREAD

**Issue by CafeBabe202** [alist-org/alist#4676]
### Description of the feature / 需求描述

现在的markdown预览功能做的很好，不过貌似不支持公式，并且使用相对文件路径的图片也不能显示，希望能够增加这两个功能的支持，这样就可以更好的组建我的知识库，谢谢

**Comment by anwen-anyi** [comment]
你指的相对路径是指的直接用网盘的吗？还是搭建AList本机的

**Comment by CafeBabe202** [comment]
> 

我的markdown 文件是托管在阿里云盘的，markdown 中的图片使用的是相对路径，他不能正常显示，[这是我的博客地址](线性回归算法.md | undo的世界 https://undo.vip/%E5%8D%9A%E5%AE%A2/%E5%A4%A7%E6%95%B0%E6%8D%AE/%E5%8D%81%E5%A4%A7%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E7%AE%97%E6%B3%95/%E7%BA%BF%E6%80%A7%E5%9B%9E%E5%BD%92%E7%AE%97%E6%B3%95.md) 你可以看一下。
图片的问题我可以使用图床来解决，我最一样的是这样能够正常显示公式。

**Comment by anwen-anyi** [comment]
> > 
> 
> 
> 
> 我的markdown 文件是托管在阿里云盘的，markdown 中的图片使用的是相对路径，他不能正常显示，[这是我的博客地址](线性回归算法.md | undo的世界 https://undo.vip/%E5%8D%9A%E5%AE%A2/%E5%A4%A7%E6%95%B0%E6%8D%AE/%E5%8D%81%E5%A4%A7%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E7%AE%97%E6%B3%95/%E7%BA%BF%E6%80%A7%E5%9B%9E%E5%BD%92%E7%AE%97%E6%B3%95.md) 你可以看一下。
> 
> 图片的问题我可以使用图床来解决，我最一样的是这样能够正常显示公式。

呃呃呃… 我主要是问的图片 你托管在阿里云盘相对路径肯定不行

计算公式得等开发者看看了

**Comment by CafeBabe202** [comment]
> 你指的相对路径是指的直接用网盘的吗？还是搭建AList本机的



> > > 
> > 
> > 
> > 我的markdown 文件是托管在阿里云盘的，markdown 中的图片使用的是相对路径，他不能正常显示，[这是我的博客地址](线性回归算法.md | undo的世界 https://undo.vip/%E5%8D%9A%E5%AE%A2/%E5%A4%A7%E6%95%B0%E6%8D%AE/%E5%8D%81%E5%A4%A7%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E7%AE%97%E6%B3%95/%E7%BA%BF%E6%80%A7%E5%9B%9E%E5%BD%92%E7%AE%97%E6%B3%95.md) 你可以看一下。
> > 图片的问题我可以使用图床来解决，我最一样的是这样能够正常显示公式。
> 
> 呃呃呃… 我主要是问的图片 你托管在阿里云盘相对路径肯定不行
> 
> 计算公式得等开发者看看了

好的，希望能够支持公式，那图片要怎样引用才能显示呢？

**Comment by CafeBabe202** [comment]
> > > 
> > 
> > 
> > 我的markdown 文件是托管在阿里云盘的，markdown 中的图片使用的是相对路径，他不能正常显示，[这是我的博客地址](线性回归算法.md | undo的世界 https://undo.vip/%E5%8D%9A%E5%AE%A2/%E5%A4%A7%E6%95%B0%E6%8D%AE/%E5%8D%81%E5%A4%A7%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E7%AE%97%E6%B3%95/%E7%BA%BF%E6%80%A7%E5%9B%9E%E5%BD%92%E7%AE%97%E6%B3%95.md) 你可以看一下。
> > 图片的问题我可以使用图床来解决，我最一样的是这样能够正常显示公式。
> 
> 呃呃呃… 我主要是问的图片 你托管在阿里云盘相对路径肯定不行
> 
> 计算公式得等开发者看看了

我通过一个定时的外挂脚本解决了图像的问题，把下边的代码插入到自定义内容

```javascript
function replace(a, b, c) {
    if (a.startsWith(b) && !a.startsWith(c)) {
        return c + a.slice(b.length);
    }
    return a;
}
let nowOrigin = window.location.origin;
function check() {
    let imgs = $(".markdown-body").find("img");
    imgs.each(function (index, img) {
        let nowURL = img.src;
        let finalPrefix = nowOrigin + "/d";
        let rep = replace(nowURL, nowOrigin, finalPrefix);
        if (rep != nowURL) {
            img.src = rep;
        }
    })
}
$(document).ready(function () {
    setInterval("check()", 1000);
});
```

想尝试对含有公式的块使用其他工具重新解析的方式来支持公式的显示

**Comment by CafeBabe202** [comment]
我通过外挂的方式几乎实现了这两个功能。
首先在自定头中引入jquery和mathJS
```html
<script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML"></script>
```
然后在自定义内容中添加一下内容
```html
<script>
let isMathjaxConfig = false;
const initMathjaxConfig = () => {
    if (!window.MathJax) {
        return;
    }
    window.MathJax.Hub.Config({
        showProcessingMessages: false,
        messageStyle: "none",
        jax: ["input/TeX", "output/HTML-CSS", "output/PreviewHTML"],
        tex2jax: {
            inlineMath: [["$", "$"], ["\\(", "\\)"]],
            displayMath: [["$$", "$$"], ["\\[", "\\]"]],
            skipTags: ["script", "noscript", "style", "textarea", "pre", "code", "a"]
        },
        "HTML-CSS": {
            showMathMenu: false,
            linebreaks: { automatic: true, width: "container" },
            availableFonts: ["STIX", "TeX"],
            preferredFonts: "STIX",
            webFont: "STIX"
        }
    });
    isMathjaxConfig = true; // 
};
if (isMathjaxConfig === false) {
    initMathjaxConfig();
}
function replace(a, b, c) {
    if (a.startsWith(b) && !a.startsWith(c)) {
        return c + a.slice(b.length);
    }
    return a;
}
let nowOrigin = window.location.origin;
function check() {
    let markEle = $(".markdown-body");
    if (markEle.length == 0) {
        return;
    }
    window.MathJax.Hub.Queue(["Typeset", MathJax.Hub, document.getElementsByClassName("markdown-body")]);
    let imgs = markEle.find("img");
    imgs.each(function (index, img) {
        let nowURL = img.src;
        let finalPrefix = nowOrigin + "/d";
        let rep = replace(nowURL, nowOrigin, finalPrefix);
        if (rep != nowURL) {
            img.src = rep;
        }
    })
}
$(document).ready(function () {
    setInterval("check()", 1000);
});
</script>
```
图片的解决方案是将相对路径的图像链接替换为alist的直链，这样就可以显示图像了。如果页面中存在大量图像可能会导致部分图像加载不成功，应该是因为请求太多后台响应不过来的问题，多刷新几次就行了。

公式是使用了一个工具，不过这个工具我也没用过，只是按照网上的一些教程进行设置的，目前还有一些问题，多行公式不能正确显示，希望有用过的大佬来帮忙解决一下。

因为他这个是单页面应用，所以我没办法在界面加载完成后只渲染一次，我尝试监控浏览器url的变化但是没有成功，所以只能使用定时任务，这会比较浪费性能，但是我也没有办法。如果有大佬能够找到较好的方式希望能够回复。如果是官方支持我觉得在markdown预览中添加回调函数来完成就行。希望能够官方支持该功能。

**Comment by langren1353** [comment]
在上面大佬的基础上修改了下代码，只处理图片问题，同时解决了由于网页地址末尾斜杠（无斜杠时资源异常）导致的资源无法加载的问题
`
<script>
  function markdownImageHandle() {
    const windowPathName = window.location.pathname

    let markEle = document.querySelector('.markdown-body')
    if (!markEle) {
      return;
    }
    const imageList = markEle.querySelectorAll('img')
    imageList.forEach(img => {
      let imgSrc = img.getAttribute('src');
      // 以横杠开始的不做处理
      if(!imgSrc.startsWith('/d/')) {
        img.setAttribute('src', '/d' + windowPathName + '/' + imgSrc)
      }
    })
  }
  setInterval(() => {
    if(document.body.querySelector('.markdown-body')) {
      markdownImageHandle()
    }
  }, 500)

</script>

`

**Comment by TharinWONG** [comment]
請求參考 wik.js 的 Markdown 編輯器 及 語法
https://docs.requarks.io/editors/markdown

希望能新增 Content Tabs (內容選項卡)
