### ISSUE TITLE
支持文件/视频加密上传

### ISSUE THREAD

**Issue by luneew** [alist-org/alist#4679]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

上传场景：用户在某一目录下上传界面选择要上传的文件，勾选加密支持，完成上传；
下载场景：用户选择需要下载的文件点击下载，下载链接支持流式解密
视频场景：
可以使用hls标准
上传：同样使用密钥，完成视频流的hls加密
m3u8下载/播放：动态完成key_url的改写，使用标准播放器播放

可以实现无感知无侵入的文件/视频加解密

### Suggested solution / 实现思路

可以支持配置或者内嵌一个本地KMS服务器，当用户上传时，通过KMS的密钥在alist节点完成文件的流式加密；当用户下载时，代理下载流量，完成流式解密，返回给用户。简单化可以一个挂盘使用一个密钥。
普通文件场景：
主要流程如下：
上传：
1. 用户在界面触发上传，选择文件加密
2. alist通过kms服务获取相应的数据密钥
3. alist服务通过获取的数据密钥将上传的字节流式加密
4. alist将流式加密的数据写入上传
5. alist生成文件对应的加密信息元数据，加密算法等
下载：
1. 用户在界面触发下载，返回代理后的下载地址
2. alist读取加密元数据文件，查询文件对应的加密密钥
3. alist服务通过获取的数据密钥流式解密读取的文件
4. alist将解密的数据返回

视频场景：
上传：
1. 用户在界面触发上传，选择hls加密转码
2. 同上上传流程
3. 视频上传完成生成对应的m3u8文件，文件不包含key url的信息，可以附带alist的加密标签标识是alist加密的
下载：
1. 用户在界面触发m3u8下载/播放
2. alist通过查找相应的数据密钥，改写填充密钥url和视频地址，并返回
3. 播放器通过key url获取数据密钥，完成本地解密播放

**Comment by mengguyi** [comment]
https://github.com/traceless/alist-encrypt

**Comment by bilibili2077** [comment]
支持支持支持！

**Comment by seanhe26** [comment]
> https://github.com/traceless/alist-encrypt
这个项目我尝试在生产环境使用，发现了很多问题：
1. 文件名加密不合理算法导致极小概率没有勾选文件名加密也会某些文件名出错。
2. 流加密文件没有使用noonce，所以加密等级大大降低，可以理解为是个混淆器，而非真正加密
3. http pipe的使用貌似有问题，经常在看视频等调用大文件时，即使调用结束，但是检测不到，继续占用带宽进行全文件下载

经过一阵子的研究，只有rclone的crypt使用的secretbox中 XSalsa20/Poly1305 MAC 是合理有效的加密，文件名加密也是有效的。

我在尝试把rclone的加解密放到alist中来，通过client和server两种模式：
server模式：
server需要请求源文件并解密，然后发给请求者，占用server上传和下载带宽。支持webdav
client模式：
server和目前的alist逻辑无区别，但是client的浏览器会对文件名和文件进行解密，client浏览器可以直接连接各个网盘的源。不占用server的上传和下载带宽。 不支持webdav

**Comment by luneew** [comment]
当前缺乏针对普通文件的端到端加密标准，针对普通文件的加解密只能做本地或服务端代理加解密方案；针对视频文件有标准的方案可以用，并且得到了各种播放器的支持，可以直接采用hls标准，这样基本可以做到无感知的。

**Comment by seanhe26** [comment]
> 当前缺乏针对普通文件的端到端加密标准，针对普通文件的加解密只能做本地或服务端代理加解密方案；针对视频文件有标准的方案可以用，并且得到了各种播放器的支持，可以直接采用hls标准，这样基本可以做到无感知的。

简单研究了下，你想要的这个hls要想实现工程量比目前的alist整个都大，除非有大神来做，否则放弃这个幻想吧。能有文件加解密已经很好了

**Comment by seanhe26** [comment]
new driver in beta, will send a pull request once proved stable.
Discussion:https://github.com/alist-org/alist/discussions/4788
