### ISSUE TITLE
获取沃盘Token时，报错：请求失败，rsp_code: 6006,rep_desc: 图形验证码未输入或返回参数！

### ISSUE THREAD

**Issue by pda8888** [alist-org/alist#4682]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

wopan

### Describe the bug / 问题描述

在https://alist.nn.ci/tool/wopan/token.html去获取wopan需要的refresh_token和access_token时，输入了正确的手机号和密码，点击“Get Verify Code”按钮，手机收到了短信，输入验证码后，点击获取"Get Token"按钮，结果报错：
```txt
Error
request failed with rsp_code: 6006,rep_desc: 图形验证码未输入或缺失参数！
```
可是没有界面显示图形验证码，也没有地方输入图形验证码。

### Reproduction / 复现链接

https://alist.nn.ci/tool/wopan/token.html

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/61155282/48493a63-7786-4a7b-9a61-35eabe8804d4)

**Comment by ma3252788** [comment]
解决方案：[https://www.machunjie.com/linux/1741.html](https://www.machunjie.com/linux/1741.html)
