### ISSUE TITLE
关于直链下载链接地址问题

### ISSUE THREAD

**Issue by kj163kj** [alist-org/alist#4685]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望Alist 可以出一个短链功能 用于直链下载 类似ZFile的短链功能 直链有中文转码后较长 特别是有多层目录时 希望我的建议能被采纳 在此感谢Alist 的开发者！

**Comment by anwen-anyi** [comment]
AList 没带，但是可以借用第三方短连接程序，[搭建教程](https://anwen-anyi.github.io/index/10-dlianjie.html)
