### ISSUE TITLE
添加可选全局搜索 or 目录搜索的开关

### ISSUE THREAD

**Issue by jerryyang-git** [alist-org/alist#4686]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

# 添加全局搜索&目录搜索开关
目前Alist默认搜索当前目录下所有子/文件
希望后台增加搜索设置默认搜索全局或从当前目录搜索
或者在搜索组件添加一个全局或当前的选择器，大概像这样
![image](https://github.com/alist-org/alist/assets/60727068/eacd49d3-4170-47f2-a518-938026cab3b3)

**Comment by Xhofe** [comment]
没有这个必要 你切换到根目录不就是全局搜索吗。

**Comment by jerryyang-git** [comment]
> 没有这个必要 你切换到根目录不就是全局搜索吗。

算是个人需求吧，全局搜索用习惯了，有时候喜欢直接ctrl+k，搜索不到才发现不在根目录，然后又回去搜😅
