### ISSUE TITLE
不能在线播放mp3文件

### ISSUE THREAD

**Issue by CrazyJasonwell** [alist-org/alist#4689]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

播放mp3文件，出现下列错误：
System error: TypeError: Cannot read properties of undefined (reading 'toString')

### Reproduction / 复现链接

播放mp3文件，出现下列错误：
System error: TypeError: Cannot read properties of undefined (reading 'toString')

**Comment by Dagsi** [comment]
能否提供一下MP3文件

**Comment by CrazyJasonwell** [comment]
[](url)
[mp3demo.zip](https://github.com/alist-org/alist/files/11956631/mp3demo.zip)

**Comment by Xhofe** [comment]
https://al.nn.ci/test_local/003%E4%B8%A8%E8%8A%B1%E6%9E%9C%E5%B1%B1%E5%B1%85%E7%84%B6%E4%B8%8D%E5%9C%A8%E4%B8%AD%E5%9B%BD%EF%BC%9F.mp3
