### ISSUE TITLE
支持SSO自动注册

### ISSUE THREAD

**Issue by WinterOfBit** [alist-org/alist#4692]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在使用SSO登录时，为新用户自动注册，同时可自定义自动注册用户的默认权限和默认Path

## 有两点额外问题：
1. 安全起见，我认为应当只允许 Casdoor 或 OIDC 作为SSO认证时支持自动注册，且限制用户组，是否合理
2. 目前 Casdoor情形下，sso_id [使用 claim `preferred_username` 获取](https://github.com/alist-org/alist/blob/59dbf4496ff1c8f596770299db5c36868ba37e01/server/handles/ssologin.go#L253C14-L253C14)，且在数据库中用此保存，对于自动注册和 SSO 来说，是否是一个bug? 

### Suggested solution / 实现思路

添加相应配置字段后，在 [ssologin.go](https://github.com/alist-org/alist/blob/59dbf4496ff1c8f596770299db5c36868ba37e01/server/handles/ssologin.go#L319) 此处增加判断

**Comment by woshichenghaibo** [comment]
越来越复杂了，唉
