### ISSUE TITLE
迁移过程中配置文件似乎未生效

### ISSUE THREAD

**Issue by lushi78778** [alist-org/alist#4693]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.18.0 musl

### Driver used / 使用的存储驱动

尚未登入使用

### Describe the bug / 问题描述

目前我将其部署到阿里云函数计算上，其官网：https://help.aliyun.com/product/50980.html
配置文件：
![image](https://github.com/alist-org/alist/assets/64238218/0a2a3132-2f0b-4d2c-b50e-9d3b588d57c3)
可以看到是指定配置文件 使用alist server 启动，无法使用用户名密码登录，
![image](https://github.com/alist-org/alist/assets/64238218/343df512-f3c5-40c2-a8d2-5068a0f1baa4)
这个是根本未使用指定配置文件，restart后有时候倒是使用了（但也有无法使用时候），但无法登陆，还是只能使用未指定配置文件自动生成的账号密码。
![image](https://github.com/alist-org/alist/assets/64238218/bbf2f545-1de2-493d-b6ad-dd4c3c69bb61)

由于使用的函数计算是空闲时间销毁实例，有人访问才会新建实例，如果不能绑定配置文件根本没法登录使用

无法登陆
![image](https://github.com/alist-org/alist/assets/64238218/0a1e1ac7-cb56-4820-9852-26b363ed9c3d)

config.json：（mysql配置齐全，这里脱敏）
```json
{
  "force": true,
  "address": "0.0.0.0",
  "port": 5244,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "AfOf5OoMte1Bergv",
  "token_expires_in": 48,
  "database": {
    "type": "mysql",
    "host": "****.**.ewlgc.top",
    "port": ****,
    "user": "****",
    "password": "****",
    "name": "alist",
    "db_file": "",
    "table_prefix": "ewlgc_",
    "ssl_mode": ""
  },
  "scheme": {
    "https": false,
    "cert_file": "",
    "key_file": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "max_connections": 0,
  "tls_insecure_skip_verify": false
}
```

### Reproduction / 复现链接

http://api.ewlgc.top/

目前admin会密码错误，lushi账户会账户记录不存在，也就是说未使用配置文件

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/64238218/c2c75e49-a195-4cb9-92bd-846a4e5546a3)
请看图片

**Comment by lushi78778** [comment]
注意：函数计算是空闲时间销毁实例，有人访问才会新建实例，如果上述admin账户密码失效应当是可以理解的，因为alist没有配置文件会自动生成对吧？

**Comment by lushi78778** [comment]
![image](https://github.com/alist-org/alist/assets/64238218/701b7846-30c3-4fc2-8dae-3a559a07f5c5)
重启后也不会改变，我看配置文件，居然被覆盖了！！！

**Comment by Xhofe** [comment]
注意你的启动路径，你在/code目录运行，读取的配置文件是 /code/data/config.json 。
