### ISSUE TITLE
qbittorrent 离线到 onedrive 文件损坏

### ISSUE THREAD

**Issue by ty114514** [alist-org/alist#4696]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.18.0

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

下载上传过程无报错，但在文件列表浏览发现文件体积不对，图片只能加载一半，视频跳转时间后直接终止播放，目测都损坏了

### Reproduction / 复现链接

![](https://link.storjshare.io/s/jxespbacqjgyrqi5envbx3aty5tq/dc5cb556-bb0e-44d5-9506-01b94d9592f8/alist/Screenshot_2023-07-04-19-35-45-183_io.github.forkmaintainers.iceraven.jpg?wrap=0)
![](https://link.storjshare.io/jvqsnszczj7xy4fm7mutsx4gctgq/dc5cb556-bb0e-44d5-9506-01b94d9592f8%2Falist%2FScreenshot_2023-07-04-19-35-13-235_io.github.forkmaintainers.iceraven.jpg?wrap=0)
![](https://link.storjshare.io/s/jvaue2dd56zmoct6hgogvj5pjusa/dc5cb556-bb0e-44d5-9506-01b94d9592f8/alist/Screenshot_2023-07-04-19-22-29-341_io.github.forkmaintainers.iceraven.jpg?wrap=0)

**Comment by seanhe26** [comment]
不仅仅是这个功能，因为目前alist使用的流处理没有考虑size，也没有实现断点续传，很多网盘这类复制、移动都会失败，产生不完整文件。目前不建议使用。
我后面会从根本上解决，具体实现后会在fork主页说明。 https://github.com/seanhe26/alist-private-cloud

**Comment by ty114514** [comment]
谢谢！您会将优化后的部分提交到上游吗
