### ISSUE TITLE
123网盘不能正常挂载

### ISSUE THREAD

**Issue by rootddms** [alist-org/alist#4697]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

123网盘

### Describe the bug / 问题描述

在后台正确配置了123网盘，登录后，不能显示网盘里面的文件，三天前都还能正常使用

### Reproduction / 复现链接

api/fs/get
Request Method:
POST

### Logs / 日志

/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 
[GIN] 2023/07/04 - 00:09:16 | 200 |  759.730396ms |  119.86.176.168 | POST     "/api/fs/get"
[31mERRO[0m[2023-07-04 00:09:16] fs/list: 当前登录操作频繁，请稍后再试
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/home/runner/work/alist/alist/internal/op/fs.go:120
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/home/runner/work/alist/alist/internal/op/fs.go:117
github.com/alist-org/alist/v3/internal/fs.list
	/home/runner/work/alist/alist/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/home/runner/work/alist/alist/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/home/runner/work/alist/alist/server/handles/fsread.go:82
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/runner/work/alist/alist/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2936
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:1995
runtime.goexit
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598

**Comment by srcenchen** [comment]
+1 无法正常登录

**Comment by srcenchen** [comment]
![image](https://github.com/alist-org/alist/assets/48435089/48144724-103f-4f87-b4a6-b9de4b5d9328)
