### ISSUE TITLE
Aliyun open播放器多一个画质选择,导致全屏按钮不显示

### ISSUE THREAD

**Issue by anwen-anyi** [alist-org/alist#4700]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.20.0

### Driver used / 使用的存储驱动

Aliyun Open

### Describe the bug / 问题描述

在手机端使用open播放器时 因为多一个画质选项导致右侧的按钮被挤出范围内
（3.19.0直接看不到全屏按钮）
![5)BJ )FWN$UH`OE8LMRKX1_tmb](https://github.com/alist-org/alist/assets/56105412/27a9b383-8acd-4991-8e69-2e750aaea31d)

### Reproduction / 复现链接

将 CSS  `.art-video-player .art-bottom .art-controls .art-control` 里面的`mix-wiidth：36px`使用默认的即可

![7JK}@~H13}~3AK3BFR5(KAW](https://github.com/alist-org/alist/assets/56105412/9a7fabe0-1cd5-479c-9a48-1633f9eb2126)

### Logs / 日志

No log

**Comment by Xhofe** [comment]
因为这是artplayer提供的样式，我认为这最好应直接由artplayer处理。

在artplayer处理之前，可以直接在自定义头部/body中添加自定义css以适应自己的设备。

**Comment by anwen-anyi** [comment]
```css
/*artplayer video*/
.art-video-player .art-bottom .art-controls .art-control {
  min-width: 0px !important;
}
```
:disappointed_relieved: 不知道这样对不对，测试没发现有啥影响（其他有需要的自取吧）

**Comment by liu-ce** [comment]
> ```css
> /*artplayer video*/
> .art-video-player .art-bottom .art-controls .art-control {
>   min-width: 0px !important;
> }
> ```
> 
> 😥 不知道这样对不对，测试没发现有啥影响（其他小伙伴有需要的自取吧）

能用 牛逼

**Comment by pkq66882** [comment]
/*手机视频显示比例调整*/
.art-video-player .art-bottom .art-controls .art-control {
  min-width: 0px !important;
}


/* 隐藏网页全屏按钮元素 */
.art-icon-fullscreenWebOn.art-icon,
.hint--top.hint--rounded.art-control-fullscreenWeb.art-control {
    display: none !important;
}


结合上面在修改的应该会正常显示，最新版本

**Comment by pkq66882** [comment]
```/*手机视频显示比例调整*/
.art-video-player .art-bottom .art-controls .art-control {
  min-width: 0px !important;
}


/* 隐藏网页全屏按钮元素 */
.art-icon-fullscreenWebOn.art-icon,
.hint--top.hint--rounded.art-control-fullscreenWeb.art-control {
    display: none !important;
}
```
结合上面修改一下应该，没有问题了，目前最新版本测试没有问题
