### ISSUE TITLE
下载123网盘的文件时，跳防盗链提示

### ISSUE THREAD

**Issue by ken357525161** [alist-org/alist#4704]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.20.1

### Driver used / 使用的存储驱动

123网盘

### Describe the bug / 问题描述

下载就跳出这个界面：

https://218-60-174-250.d.cjjd15.com:30443/download-app.123pan.cn/123%E4%BA%91%E7%9B%98(123pan.com).mp4?xmfcid=3e3d5b8f-01d6-4cfc-bd7c-ca333a39b01c-0-9eed82220

### Reproduction / 复现链接

https://218-60-174-250.d.cjjd15.com:30443/download-app.123pan.cn/123%E4%BA%91%E7%9B%98(123pan.com).mp4?xmfcid=3e3d5b8f-01d6-4cfc-bd7c-ca333a39b01c-0-9eed82220

**Comment by Xhofe** [comment]
这是123云盘端的限制，使用浏览器直接请求文件alist无法做任何处理，你应该

- 向123云盘请求取消referer检查；
- 或者打开存储中的`web代理`与webdav`本地代理`让alist来帮你请求文件，它会自动添加123云盘的referer以阻止防盗链，但是代价是流量将由服务器中转，当然如果你在本地使用那么你可以忽略这一点。

**Comment by 645710596** [comment]
现在WEB代理不行了
