### ISSUE TITLE
当文件夹名称中包含'/'时，会被当成地址解析，导致解析异常

### ISSUE THREAD

**Issue by 454592673** [alist-org/alist#4706]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.20.1 

### Driver used / 使用的存储驱动

阿里云open

### Describe the bug / 问题描述

通过小白羊上传文件夹到阿里云盘，文件夹层级路径会被当成文件完整地址保存，
![image](https://github.com/alist-org/alist/assets/22283930/033f4d20-5ef2-474d-92af-bcf57e0b6e7a)
这里的“图片包/百雀羚+车管家产品图包-0704/车管家/GJ-8037”在阿里云盘是文件名，但是被解析成文件夹
小白羊那边也提了issues [：](https://github.com/gaozhangmin/aliyunpan/issues/221)
那边是会把文件所属文件夹路径当成文件名保存
这边是会把包含文件夹'/'层级结构的文件名当成文件夹处理
由一个bug，碰巧找到了这边的bug，官方可以正常显示带'/'的文件夹
![image](https://github.com/alist-org/alist/assets/22283930/46100691-1e11-49e0-857c-031d66dfbd34)

### Reproduction / 复现链接

阿里云盘第三方客户端上传文件夹挂载即可实现

**Comment by 454592673** [comment]
![image](https://github.com/alist-org/alist/assets/22283930/d5c75c8e-8640-41a6-8662-dd070586a6fc)

**Comment by anwen-anyi** [comment]
https://alist.nn.ci/zh/config/global.html#文件名字符映射
