### ISSUE TITLE
alist恢复备份文件设置项提示Request failed with status code 502错误

### ISSUE THREAD

**Issue by 9E307** [alist-org/alist#4707]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.20.1

### Driver used / 使用的存储驱动

与存储驱动无关

### Describe the bug / 问题描述

通过docker全新安装的alist，在用V3.18版本备份的设置文件恢复时候出现Request failed with status code 502错误。除了设置选项内的内容无法恢复外，用户选项和存储选项可以正常恢复。
同时自己手动在alist后台修改设置也会提示Request failed with status code 502错误。

并且重新安装V3.18版本也无法进行设置
针对无法保存设置的情况，请问如何处理？

### Reproduction / 复现链接

无

### Logs / 日志

出现错误的反馈：
ℹ️开始恢复
ℹ️开始备份
✅[ 设置 ] 备份成功
✅[ 用户 ] 备份成功
✅[ 存储 ] 备份成功
✅[ 元信息 ] 备份成功
ℹ️备份完成
❌[ 设置 ] 恢复失败:Request failed with status code 502
✅[ 用户 ] 恢复成功-[admin]
✅[ 用户 ] 恢复成功-[guest]
✅[ 存储 ] 恢复成功-[/阿里云盘]
✅[ 存储 ] 恢复成功-[/夸克网盘]
✅[ 存储 ] 恢复成功-[/PikPak]

docker日志：
INFO[2023-07-06 03:31:49] reading config file: data/config.json        
INFO[2023-07-06 03:31:49] config file not exists, creating default config file 
INFO[2023-07-06 03:31:49] load config from env with prefix:            
INFO[2023-07-06 03:31:49] init logrus...                               
INFO[2023-07-06 03:31:49] Successfully created the admin user and the initial password is: lWWZHkpQ 
INFO[2023-07-06 03:31:49] start HTTP server @ 0.0.0.0:5244             
INFO[2023-07-06 03:31:49] qbittorrent not ready.

**Comment by Xhofe** [comment]
日志。

**Comment by Xhofe** [comment]
你可能需要检查你的反向代理设置 根据你的日志 后端没有收到任何请求。

**Comment by 9E307** [comment]
感谢建议，关掉了本地的代理软件就好了，这个alist我是安装在新加坡的服务器上的，本地也开了代理访问这个网页。看样子是代理的问题
