### ISSUE TITLE
自定义配置文件目录路径

### ISSUE THREAD

**Issue by zhajianjun** [alist-org/alist#4715]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

需求：自定义配置文件目录路径。
场景：虽然有配置备份功能，但是不小心重装系统，又忘记备份，又要重新配置，很麻烦。对于桌面端会很友好。

**Comment by Xhofe** [comment]
./alist server --data 数据目录
