### ISSUE TITLE
发送到Aria2下载时提示：Failed to send to aria2: AxiosError: Network Error

### ISSUE THREAD

**Issue by Gokou-Ruri** [alist-org/alist#4716]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.20.1

### Driver used / 使用的存储驱动

baidu

### Describe the bug / 问题描述

登录远程服务器上的alist网页端时，勾选文件夹，使用`发送到Aria2`，网页右上角会提示 `Failed to send to aria2: AxiosError: Network Error` ，无法调用本地Aria2进行下载。
Alist网页端的下载请求是Alist后端发送的吗？不是在网页端实现的吗？这样的话不就无法在本地设备上用Aria2下载文件了吗？

### Reproduction / 复现链接

无

**Comment by loryncien** [comment]
> @Gokou-Ruri How did you resolve this issue? I am getting the same.

May be caused by browser extensions such as AdBlock, uBlock Origin, Duckduckgo !?

**Comment by fujiawei-dev** [comment]
@Gokou-Ruri How did you resolve this issue? I am getting the same.

**Comment by xxssww0258** [comment]
@Gokou-Ruri How did you resolve this issue? I am getting the same.

**Comment by xxssww0258** [comment]
I found that Docker network aliases are not supported

**Comment by ChiotOnAGE** [comment]
If you access AList via HTTPS but your Aria2 endpoint is served in HTTP. The browser will block requests to you Aria2 endpoint because that is exposing you to MITM attacks which should have been ruled out by using HTTPs unless you trusted some insecure proxies. It is suggested that you upgrade your Aria2 endpoint to HTTPs or if you are using Aria2 only for local use, check out some browser settings like `chrome://flags/#allow-insecure-localhost`.

如果你的 AList 是通过 HTTPS 访问的，而你的 Aria2 endpoint 是 HTTP, 浏览器会禁止这种安全降级的行为。你最好给 Aria2 也上一个反向代理并提供 SSL 证书。如果是本地的话，可以看看浏览器的一些 flag 比如 `chrome://flags/#allow-insecure-localhost`. 明明没有给出答解答，不知道 issue 怎么就被关了，这个查重 bot 也是搞笑，关键是被 reference 的那个 issue 也是无人解答，导致虚假的 closed issue 越来越多还互相 reference……

**Comment by grimm9652** [comment]
你好，你的问题解决了吗，我也遇到同样的问题

**Comment by lemon-o** [comment]
> 你好，你的问题解决了吗，我也遇到同样的问题

默认的Aria2地址是http地址，需要改为https地址，可以用ngnix反向代理Aria2服务器从而得到https地址

**Comment by fengchen-github** [comment]
我遇到的同样问题的解决方法是AList页面上再设置下aria
![1](https://github.com/user-attachments/assets/a7b786c0-27aa-4538-9cfc-c35301406746)
![2](https://github.com/user-attachments/assets/f7d19870-c7c7-4f78-89e7-cb2162ff70ab)

**Comment by hdzj-1981** [comment]
> 我遇到同样问题的解决方法是AListPages上再设置下aria ![1](https://private-user-images.githubusercontent.com/16919103/350744209-a7b786c0-27aa-4538-9cfc-c35301406746.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3Nzc5MDcsIm5iZiI6MTcyMjc3NzYwNywicGF0aCI6Ii8xNjkxOTEwMy8zNTA3NDQyMDktYTdiNzg2YzAtMjdhYS00NTM4LTljZmMtYzM1MzAxNDA2NzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzMjAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNDY2ODM1MzE3MmFhNjM2NjgyOTQxZTdmZWEzZWVjY2ExYmFjMjNiNjZkZjUyOGZmNDUxNGVmOTRhMTNjOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KS5Mi0kZmly8LJzFMhNH39voq7mTtTt4K-vjcPw1xMk) ![2](https://private-user-images.githubusercontent.com/16919103/350744214-f7d19870-c7c7-4f78-89e7-cb2162ff70ab.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3Nzc5MDcsIm5iZiI6MTcyMjc3NzYwNywicGF0aCI6Ii8xNjkxOTEwMy8zNTA3NDQyMTQtZjdkMTk4NzAtYzdjNy00Zjc4LTg5ZTctY2IyMTYyZmY3MGFiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzMjAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMDA4NWExZjFjYWVhOGFjZTc3ZTE5NTk1ZmVmNDQyMTk0MmRlNzNjZDAzYzU3NmEwZTc0OTY4Njg4MzA3OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VLGCMXQdLZiR1w9RENzFfYyVZ3HKvggiGRHbCPX3Pf4)

我都设置了，还是报这个错。

**Comment by frankk007** [comment]
> > 你好，你的问题解决了吗，我也遇到同样的问题
> 
> 默认的Aria2地址是http地址，需要改为https地址，可以用ngnix反向代理Aria2服务器从而得到https地址

有没有教程，我在局域网里也遇到同样的问题，打开[chrome ](chrome://flags/#allow-insecure-localhost)也不行

**Comment by Temacc0531** [comment]
同不行，alist在云上，调用本地aria2一直失败，页面的本地设置也配了

**Comment by areslp** [comment]
> 同不行，alist在云上，调用本地aria2一直失败，页面的本地设置也配了，都是http
> 
> 折腾几天终于解决了，应该是新版浏览器http的限制问题，需要在chrome://flags/#unsafely-treat-insecure-origin-as-secure加上网址设置允许

网址地址允许应该怎么写啊?写云上的地址,还是本地访问alist的呢?

**Comment by Temacc0531** [comment]
> 网址地址允许应该怎么写啊?写云上的地址,还是本地访问alist的呢?

你的浏览器访问alist网页的地址

**Comment by Wings168** [comment]
> > 网址地址允许应该怎么写啊?写云上的地址,还是本地访问alist的呢?
> 
> [@areslp](https://github.com/areslp) 你的浏览器访问alist网页的地址

需要带上端口吗？

**Comment by Temacc0531** [comment]
> 需要带上端口吗？

需要
