### ISSUE TITLE
使用非标准https端口反向代理后，本机存储的视频无法播放

### ISSUE THREAD

**Issue by WANG-Guangxin** [alist-org/alist#4719]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.20.1

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

1. 使用docker alist-aria2 镜像部署 Alist，挂载本机存储
![image](https://github.com/alist-org/alist/assets/71872849/6c40c750-6d94-4365-8ad8-7265bfddfaaa)
![image](https://github.com/alist-org/alist/assets/71872849/dcb454e8-466c-4be1-a86c-223c9887b859)

2. 使用OpenResty 反向代理 Alist ，并开启 https 。
3. 无法播放本地视频。
![image](https://github.com/alist-org/alist/assets/71872849/a0a4e6c2-cea0-41e1-95cc-0652ef3a0243)

点击 复制连接 和 下载 都能成功。

### Reproduction / 复现链接

[GIN] 2023/07/07 - 07:05:12 | 200 |     135.775µs |   | GET      "/Local/一口气看完《封神榜》，最经典的电视剧之一，惊呆了无数人，爆肝5小时超长解说.mp4"
[GIN] 2023/07/07 - 07:05:13 | 200 |     116.428µs |   | GET      "/api/public/settings"
[GIN] 2023/07/07 - 07:05:13 | 200 |     140.523µs |   | GET      "/api/me"
[GIN] 2023/07/07 - 07:05:14 | 200 |     665.183µs |   | POST     "/api/fs/get"

**Comment by Xhofe** [comment]
- #726
- #1159
- #2429
- #3644
- #4181
