### ISSUE TITLE
配置文件开启SSL失败

### ISSUE THREAD

**Issue by Winyer** [alist-org/alist#4721]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.20

### Driver used / 使用的存储驱动

OneDrive，天翼云盘，移动云盘，百度云盘

### Describe the bug / 问题描述

使用配置文件开启SSL失败，一直报错，详细如下：
[**当使用连接里的配置方法去配置config.json时，**](https://github.com/alist-org/alist/issues/4720)
  "scheme": {
    "address": "0.0.0.0",
    "http_port": -1,
    "https_port": 5244,
    "force_https": false,
    "cert_file": "data/SSL/cert.pem",
    "key_file": "data/SSL/cert.key",
    "unix_file": ""
这个配置的时候，启动报错如下：
INFO[2023-07-07 19:03:29] start HTTPS server @ 0.0.0.0:-1              
FATA[2023-07-07 19:03:29] failed to start https: listen tcp: address -1: invalid port 

**当使用**
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5223,
    "https_port": 5244,
    "force_https": false,
    "cert_file": "data/SSL/cert.pem",
    "key_file": "data/SSL/cert.key",
    "unix_file": ""
这个配置时，HTTPS会很神奇的去使用HTTP的端口，报错如下：
INFO[2023-07-07 19:04:57] start HTTP server @ 0.0.0.0:5223             
INFO[2023-07-07 19:04:57] start HTTPS server @ 0.0.0.0:5223            
FATA[2023-07-07 19:04:57] failed to start https: listen tcp 0.0.0.0:5223: bind: address already in use 

再尝试开启强制HTTPS时，报错还是一样的：
INFO[2023-07-07 19:06:06] start HTTP server @ 0.0.0.0:5223             
INFO[2023-07-07 19:06:06] start HTTPS server @ 0.0.0.0:5223            
FATA[2023-07-07 19:06:06] failed to start https: listen tcp 0.0.0.0:5223: bind: address already in use 

**如果让HTTP和HTTPS使用同一端口，使用如下配置**
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5224,
    "https_port": 5244,
    "force_https": true,
    "cert_file": "data/SSL/cert.pem",
    "key_file": "data/SSL/cert.key",
    "unix_file": ""

还是会显示端口占用：
INFO[2023-07-07 19:06:43] start HTTP server @ 0.0.0.0:5224             
INFO[2023-07-07 19:06:43] start HTTPS server @ 0.0.0.0:5224            
FATA[2023-07-07 19:06:43] failed to start https: listen tcp 0.0.0.0:5224: bind: address already in use 

所以到底应该怎么去配置，HTTP和HTTPS使用了两个端口，但是HTTPS就是会去使用HTTP的端口导致端口占用无法开启HTTPS的端口...只需要用HTTPS不想用HTTP也不行，所有可能的配置都试过了，说明文档里也没有相关内容，百度谷歌必应都搜不到，全是反代加SSL的，但是反代会有BUG，真的无语了

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/releases/tag/v3.20.1

**Comment by Winyer** [comment]
> https://github.com/alist-org/alist/releases/tag/v3.20.1

所以折腾了这几天因为程序有BUG....?
还有有配置文件的说明文档吗

**Comment by Winyer** [comment]
> Hello @Winyer, your issue is invalid and will be closed. 你好 @Winyer，你的issue无效，将被关闭。

加一个，3.20.1版本如果HTTP和HTTPS使用同一个端口还是不行，但是如果用HTTP访问HTTPS端口会显示
Client sent an HTTP request to an HTTPS server.
而不是跳转到HTTPS，这个可以改一下吗？
