### ISSUE TITLE
123云盘不自动跳转，文件不直接下载

### ISSUE THREAD

**Issue by VirtualHotBar** [alist-org/alist#4729]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.20.1

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

希望他访问能直接下载

可更改auto_redirect参数，实现

![image](https://github.com/alist-org/alist/assets/96966978/cd9cd69e-9dd4-413c-b83c-5a756bd76d2c)

### Reproduction / 复现链接

https://down.hotpe.top/d/OS/Win10/SW_DVD9_WIN_ENT_LTSC_2021_64BIT_ChnSimp_MLF_X22-84402.ISO

上面链接跳转：
down.hotpe.top/d/ => p0.hotpe.top(ip:5244/d/)
CDN没有缓存

**Comment by anwen-anyi** [comment]
` I'm sure there are no duplicate issues or discussions.` 勾选的选项白勾了 =，=
