### ISSUE TITLE
网格视图下，部分图片无法查看

### ISSUE THREAD

**Issue by SerendipityR-2022** [alist-org/alist#4733]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.20.1

### Driver used / 使用的存储驱动

阿里云盘OPEN

### Describe the bug / 问题描述

部分图片无法预览，显示"Oops... Failed to load content..."，但在下载页面下可以正常显示。

### Reproduction / 复现链接

内网搭建Alist，无法提供链接。
存在问题的图片样例：https://www.123pan.com/s/oWzzVv-JFyVH.html

### Logs / 日志

前端控制台有报错
Uncaught TypeError: Cannot read properties of undefined (reading 'offsetHeight')
    at s.getImageSize (Folder.0395c53d.js:114:3156)
    at s.setZoomEssentials (Folder.0395c53d.js:114:4392)
    at HTMLDivElement.<anonymous> (Folder.0395c53d.js:114:9457)
    at s.trigger (Folder.0395c53d.js:19:6679)
    at Folder.0395c53d.js:71:8519

**Comment by Xhofe** [comment]
请提供一个复现链接，内网可以使用内网穿透服务。
