### ISSUE TITLE
阿里云OSS重命名文件夹会导致文件夹被删除

### ISSUE THREAD

**Issue by musicking** [alist-org/alist#4738]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.20.1

### Driver used / 使用的存储驱动

AliyunOSS

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/8167146/1088f9a5-372f-4122-9b24-8d8533e4519b)
![image](https://github.com/alist-org/alist/assets/8167146/25f4a3f0-41d4-4f6b-bdc7-c8a32acd0800)
（新建一个文件夹）
![image](https://github.com/alist-org/alist/assets/8167146/27bb301d-0d99-46b6-9714-993b9af40b07)
![image](https://github.com/alist-org/alist/assets/8167146/a280d017-0882-41f7-9189-b7f413674881)
（重命名文件夹）
![image](https://github.com/alist-org/alist/assets/8167146/91f6fd31-0655-4692-a92b-f9ec13b40c6d)
（文件夹消失）

经过测试：
1. 文件重命名正常，不会被删除。
2. 文件夹下面有文件也可以重命名成功
3. 空文件夹重名会被删除
4. 文件夹下面有空的文件夹，重命名也一样会被删除

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
duplicate with #4620
