### ISSUE TITLE
预览PDF出现错误：pdf.js载入 PDF 时发生错误，信息：Failed to fetch

### ISSUE THREAD

**Issue by ShiaBox** [alist-org/alist#4739]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.20.1-docker-arm64

### Driver used / 使用的存储驱动

smb

### Describe the bug / 问题描述

内网环境下使用pdf.js载入 PDF 时发生错误，信息：Failed to fetch
控制台错误信息如下：

Mixed Content: The page at 'https://alist-org.github.io/pdf.js/web/viewer.html?file=http%3A%2F%2F172.18.101.111%2Fp%2Fprinter%2F20230710142504940.pdf' was loaded over HTTPS, but requested an insecure resource 'http://172.18.101.111/p/printer/20230710142504940.pdf'. This request has been blocked; the content must be served over HTTPS.

问题可能来源于pdf预览由https://alist-org.github.io来驱动，这使得它无法加载http的资源。
并且这可能不适用于纯内网无外网的情况，希望开发组可以想办法做一下兼容，非常感谢。

### Reproduction / 复现链接

https://alist-org.github.io/pdf.js/web/viewer.html?file=http%3A%2F%2F172.18.101.111%2Fp%2Fprinter%2F20230710142504940.pdf

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/130141407/2791d97a-bc65-492a-b138-73784820b5a0)

**Comment by Xhofe** [comment]
内网使用请考虑自行建立一个pdf.js 网页，默认只提供https预览。

**Comment by ShiaBox** [comment]
> https://alist-org.github.io/pdf.js

好的，那有没有可能在设置里可以添加自定义的pdf.js网址？

**Comment by Xhofe** [comment]
> > [alist-org.github.io/pdf.js](https://alist-org.github.io/pdf.js)
> 
> 好的，那有没有可能在设置里可以添加自定义的pdf.js网址？

https://alist.nn.ci/zh/config/preview.html#iframe-%E9%A2%84%E8%A7%88

**Comment by vecHao** [comment]
补充一点，如图PDF.js加载错误可能是浏览器IDM插件所致，在我这里关闭插件就能预览了

**Comment by Xbai-hang** [comment]
填一个坑，如果采用内网构建一个 pdf.js 网页（即 http 访问）官方的 dist 无法使用，会报错：`SecurityError: Failed to read a named property 'document' from 'Window': Blocked a frame with origin "http://10.xxx.xxx.xxx:xxxx" from accessing a cross-origin frame.`
解决方案是拉取 [PDF.js](https://github.com/mozilla/pdf.js) 官方仓库，然后注释掉 [Line 696]（当然这样就比较危险，校验的本质是为了安全捏）(https://github.com/mozilla/pdf.js/blob/master/web/app.js#L696) 这行代码
然后 `npx gulp generic`，之后获取 `build/generic` 文件夹下的静态文件。
然后按照正常部署流程部署即可。
