### ISSUE TITLE
建议增加支持 小飞机网盘

### ISSUE THREAD

**Issue by AKA2048** [alist-org/alist#4743]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

暂时未发现限速 比较稳定
https://www.feijipan.com

**Comment by anwen-anyi** [comment]
好像是属于`网赚网盘`算了吧~

**Comment by woshichenghaibo** [comment]
这种就算了，垃圾公司随时倒闭
