### ISSUE TITLE
长文本标题显示不全

### ISSUE THREAD

**Issue by WQY916** [alist-org/alist#4744]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

列表显示长文本标题的文件时，无法显示完整的标题名，导致无法确定文件

### Suggested solution / 实现思路

可以设置长文本标题滚动显示或者换行显示

**Comment by Xhofe** [comment]
默认添加了title属性
![image](https://github.com/alist-org/alist/assets/36558727/e6152b63-76ba-42f3-861c-cd039e6857d5)

如果你想要换行显示可以自行在自定义头部中添加style：
```html
<style>
.name-box .name {
	white-space: unset !important;
	overflow: unset !important;
}
</style>
```

**Comment by WQY916** [comment]
ok
