### ISSUE TITLE
管理页面点击主页拒绝打开新页面

### ISSUE THREAD

**Issue by yuanzhimengbian** [alist-org/alist#4747]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

![image](https://github.com/alist-org/alist/assets/93107257/fc2b4f4e-0530-4533-93f1-4bd5d8e67283)
上述圈住的红色部分点击后会跳转到新的页面，希望能将不通过新的标签页打开它

### Suggested solution / 实现思路

将上述html的返回中元素为<a class="hope-anchor hope-c-iHuheP hope-c-PJLV hope-c-PJLV-icXpZyG-css" target="_blank" rel="noopener noreferrer" cancelbase="false" href="/"><svg fill="currentColor" stroke-width="0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="hope-icon hope-c-XNyZK hope-c-PJLV hope-c-PJLV-igabNEN-css" height="1em" width="1em" style="overflow: visible;">该定位中的target="_blank" 改为target="_self"即可

**Comment by yuanzhimengbian** [comment]
\<a class="hope-anchor hope-c-iHuheP hope-c-PJLV hope-c-PJLV-icXpZyG-css" target="_blank" rel="noopener noreferrer" cancelbase="false" href="/"\>
不知道为什么那个标签显示不出来

**Comment by anwen-anyi** [comment]
自定义CSS不支持自定义后台我记得

**Comment by yuanzhimengbian** [comment]
那有没有什么可以实现这个需求的方式

**Comment by yuanzhimengbian** [comment]
我本意是想改源代码中的返回的html template中的部分，但是我没找到这个位置的对应部分在哪
