### ISSUE TITLE
缩略图很多是倒的

### ISSUE THREAD

**Issue by junevin1** [alist-org/alist#4749]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.20.1

### Driver used / 使用的存储驱动

本地储存

### Describe the bug / 问题描述

很多图片的缩略图是倒的，打开是正的，但是缩略图是倒的，希望能处理一下这个bug.

### Reproduction / 复现链接

![IMG_7288](https://github.com/alist-org/alist/assets/122676932/44fada4a-0e5b-47cf-9106-bf78dacafee0)

**Comment by Xhofe** [comment]
Provide a reproduction, please.

**Comment by junevin1** [comment]
比如这张图片，用alist做成缩略图时缩略图是倒的。
![2023_02_21_10_28_IMG_6755](https://github.com/alist-org/alist/assets/122676932/c76dc2ee-0412-4d41-bcbb-478ae42adb17)

**Comment by anwen-anyi** [comment]
上面提供的图在Windows桌面也是旋转了的~ 应该就是这样的
![image](https://github.com/alist-org/alist/assets/56105412/e6b76b99-da16-4a12-b745-6a8d9a42dd69)
