### ISSUE TITLE
无法添加123云盘存储

### ISSUE THREAD

**Issue by sui117** [alist-org/alist#4756]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.21.0

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

添加123云盘时，弹出错误**Failed init storage but storage is already created: failed init storage: 123pan forbidden**
昨天晚上还可以顺利添加，今天再次尝试就不行了

### Reproduction / 复现链接

无

**Comment by sui117** [comment]
已解决，原因是123云盘非会员用户最多允许3个用户登录

**Comment by tom2025** [comment]
我也出现这样的问题了

**Comment by liaohui5** [comment]
你们解决了吗? 怎么解决的?
