### ISSUE TITLE
123pan forbidden

### ISSUE THREAD

**Issue by GHOST1834** [alist-org/alist#4758]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.21.0

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

<img width="481" alt="CleanShot 2023-07-13 at 13 49 07@2x" src="https://github.com/alist-org/alist/assets/125651481/65d64c57-80c3-4228-8f35-d9d7013509d6">

两天里用alist往123盘上传了150G左右的文件后公网和本地alist的挂载都断了，重新启用会显示123pan forbidden，但是网页版123盘还是能正常使用，不知道有没有什么办法解决这个问题呢。

### Reproduction / 复现链接

<img width="481" alt="CleanShot 2023-07-13 at 13 49 07@2x" src="https://github.com/alist-org/alist/assets/125651481/e16b6c9c-42e6-42d0-a55d-8b3f5c05848c">

### Logs / 日志

<img width="481" alt="CleanShot 2023-07-13 at 13 49 07@2x" src="https://github.com/alist-org/alist/assets/125651481/454e95cb-b1f3-4bc3-b1e5-689a366ec59a">

**Comment by xx6z8v** [comment]
建议不要再使用AList挂载123云盘,123云盘已开启严格的防盗,我的123云盘账号因为挂在AList上已被封号

**Comment by GHOST1834** [comment]
明白！感谢提醒！



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 13, 2023 15:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alist-org/alist] 123pan forbidden (Issue #4758)




 
建议不要再使用AList挂载123云盘,123云盘已开启严格的防盗,我的123云盘账号因为挂在AList上已被封号

**Comment by Xhofe** [comment]
- https://github.com/alist-org/alist/issues/4756#issuecomment-1633594598

**Comment by huolanyun** [comment]
我这边 显示work，但是 主页 是空内容，确实有问题
账号正常，新建目录 修改根目录ID ，放文件 ，alist 也显示空白

**Comment by huolanyun** [comment]
@Xhofe 
上午 我更新到3.21.0 还是正常的，下午再看 就是空文件了
123盘后台是 有文件的

**Comment by Xhofe** [comment]
不要在issue中@我 谢谢。

**Comment by huolanyun** [comment]
抱歉，希望尽快查看

**Comment by kll8926** [comment]
经检查，为123盘驱动App-Version问题导致，代码中使用的是1.2，现web访问时使用的为3，如使用1.2则会报错123pan forbidden

**Comment by huolanyun** [comment]
怎么修改

**Comment by stucf** [comment]
1.2改3.0可行+1

**Comment by huolanyun** [comment]
这个App-Version 如果经常变化 ，是不是可以考虑 放在驱动里面可以修改

**Comment by anwen-anyi** [comment]
> 经检查，为123盘驱动App-Version问题导致，代码中使用的是1.2，现web访问时使用的为3，如使用1.2则会报错123pan forbidden

感谢~已可以

**Comment by huolanyun** [comment]
> 可以用我这个二进制 https://github.com/pongfcnkl/alist/actions/runs/5543313023

替换可以了

**Comment by laoqijun1** [comment]
> 

提示签名错误

**Comment by laoqijun1** [comment]
> 可以用我这个二进制 https://github.com/pongfcnkl/alist/actions/runs/5543313023

提示签名错误
