### ISSUE TITLE
希望在对象存储的引擎中添加session_token可选字段

### ISSUE THREAD

**Issue by QJZX** [alist-org/alist#4761]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我看到`alist/drivers/s3/util.go:25`有`credentials.NewStaticCredentials(d.AccessKeyID, d.SecretAccessKey, "")`，第三个字段是空的。

但在一些场景下是需要自定义填写的，比如我遇到了 :sob:  。

我需要AccessKeyId、SecretAccessKey、SessionToken三者同时使用才可以正常访问，因为我的角色是临时被授予的。[悲]

### Suggested solution / 实现思路

在创建引擎时传入第三个字段的信息即可。

**Comment by anwen-anyi** [comment]
这样是不是多吉云可以使用了？     两段式的`token`可以用了？

**Comment by QJZX** [comment]
我是在aws s3上使用主token签发的临时token，这个临时token是id、sec_key、session_key形式的，因此需要把这三者补全才能正常使用。

但发现还是存在些bug，重命名时总是提示对象的key（对象的完整路径）不存在，在winscp上没这个问题。

看了下s3的重命名的代码逻辑，看不出什么问题，挺奇特的。

查资料时说对象的key不合法时会提示异常，但winscp不知为何没这个异常。

我的对象的key中包含的字符有：“小写字母、下划线、数字、汉字、文件后缀名用到的.”。
