### ISSUE TITLE
从本地复制文件到alist挂载的腾讯云对象存储，每个目录都会多出来一个.alist文件

### ISSUE THREAD

**Issue by rangdengdashi** [alist-org/alist#4764]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.16.3

### Driver used / 使用的存储驱动

对象存储

### Describe the bug / 问题描述

环境：istoreos 
固件版本：iStoreOS 21.02.3 2023051913 / LuCI istoreos-21.02 branch git-23.088.34636-f8cc111
架构：x86
安装来源：从istore商店安装
alist版本：v3.16.3
问题描述：从本地复制文件到alist挂载的腾讯云对象存储，在腾讯云对象存储中，每个目录都会多出来一个.alist文件，本地没有，ls -alF都没有

### Reproduction / 复现链接

无

**Comment by anwen-anyi** [comment]
我记得似乎好像是占位文件符？ 不过你可以删了没事儿
