### ISSUE TITLE
阿里云盘open增加秒传功能

### ISSUE THREAD

**Issue by Rishou04** [alist-org/alist#4766]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

阿里云盘open增加秒传功能

### Suggested solution / 实现思路

https://www.yuque.com/aliyundrive/zpfszx/ezlzok
可以看这个

**Comment by anwen-anyi** [comment]
之前有人提过 **https://github.com/alist-org/alist/issues/4352** (可能是因为AList的上传逻辑不好搞？ 因为要兼容其他驱动上传,我猜的)

**Comment by Rishou04** [comment]
> 之前有人提过 **#4352** (可能是因为AList的上传逻辑不好搞？ 因为要兼容其他驱动上传,我猜的)

好吧，如果加了秒传离线下载效率会很高，服务器上传速度太慢了
