### ISSUE TITLE
md5计算错误

### ISSUE THREAD

**Issue by meaningfulcloud** [alist-org/alist#4772]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

您好，我是123盘官方工作人员，您这边计算MD5的方式是错误的，会导致无法校验文件的完整性，我们将会逐步清理掉类似文件。

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/136693889/e6e9cc04-e005-4d20-b6d9-a1f6e1f8ed66)

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/136693889/01d61be7-6913-45f4-bfde-da0b3aa3dab2)

**Comment by Xhofe** [comment]
好的 我会去掉StreamUpload，以计算完整的md5

**Comment by Xhofe** [comment]
感谢提醒 🙏
