### ISSUE TITLE
请求大佬增加磁力空间云盘

### ISSUE THREAD

**Issue by clttmtb** [alist-org/alist#4773]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

请求大佬增加磁力空间云盘
https://cilikongjian.com/login

**Comment by anwen-anyi** [comment]
小网盘还是算了，随时跑路后期维护还麻烦，
虽然你可能现在用着还好，等用的人一多参考`123云盘`直接被黑产用崩了

看了下工商信息，注册地址还是在小区家庭住址~
```log
注册资本    50万(元)
参保人数    0人
```
