### ISSUE TITLE
文件列表页返回的文件信息，加一个文件md5值的字段

### ISSUE THREAD

**Issue by twogo** [alist-org/alist#4780]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

对于能拿到文件md5值的驱动，可以把md5值返回出来吗？有些文件损坏了，可以直接对比md5值来校验。
md5值返回出来就可以了，不用体现在列表页。其他程序API请求alist文件列表，可以拿到就可以的了

### Suggested solution / 实现思路

看了源码，移动云盘和天翼这两个驱动是有md5值的，其他的不清楚。

**Comment by seanhe26** [comment]
这个已经在做了，但是不是为了展示md5等hash，而是为了不同网盘之间可以使用秒传。 
新功能都会在https://github.com/seanhe26/alist-private-cloud 测试，功能实现后会在fork主页说明
