### ISSUE TITLE
alist web端管理页点击主页按钮不应打开新页面

### ISSUE THREAD

**Issue by Oliv1a** [alist-org/alist#4784]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前在alist web端主页点击管理进入管理页是在当前页面打开，而在管理页点击主页返回的时候却是在新页面中打开，不符合产品设计逻辑和用户操作预期。

### Suggested solution / 实现思路

在管理页点击主页返回的时候在当前页面打开，保持前后操作的一致性。

### Additional context / 附件

之前有人提过类似的问题，但不知道为什么问题被关闭了，这个需求是没有办法实现还是什么情况？谢谢啦。

**Comment by anwen-anyi** [comment]
我觉得挺合理的，后台的 `文档`和`主页`只是一个快捷键
况且大部分的时候是需要后台和前端页面一起打开的，修改一些东西需要实时查看效果
如果不需要后台，打开的时候就直接打开前端页面就可以了，不用打开后台

**Comment by Oliv1a** [comment]
> 我觉得挺合理的，后台的 `文档`和`主页`只是一个快捷键
> 况且大部分的时候是需要后台和前端页面一起打开的，修改一些东西需要实时查看效果
> 如果不需要后台，打开的时候就直接打开前端页面就可以了，不用打开后台

从产品角度来说，“主页”是产品功能的一部分，而“文档”可以是也可以不是，产品内的功能跳转和外部文档的快捷链接不是一码事，而管理页上的那么多产品功能按钮都是在当前页面上操作，而同为产品功能的“主页”按钮却打开了新页面，此为逻辑不一致的地方，此外，alist web端设计精美，说是web app也不过分，从app角度来看，主页打开新页面就更奇怪了。

从实用角度来说，如果后台即管理页不是一个常用的功能，那么不吹毛求疵的话，哪怕不符合产品设计逻辑，实用层面也影响不大，比如典型的场景是，安装好后，进入后台配置了一遍，然后就完事了，几乎是个一劳永逸的事情，那“主页”按钮从实用层面来说无论是当前页面返回还是新页面打开都没多大影响。但是目前alist的web后台里却有一个非常常用的功能，那就是“任务”，抛去任务里的aria2和qB不谈，单说“上传”和“复制”这两项，就很常用。而正常的产品设计是会把这种东西放在前台的，随便举个例子，百度网盘，你执行一个上传任务，在当前页面就可以直接查看上传的进度以及成功失败情况以及失败后的重试等等，这是合理的。而alist实质上会比百度网盘更需要关注任务的执行情况，因为alist是第三方，本来上传下载复制什么的就容易出现失败情况，但这个本该在前台的功能却放在了后台，所以才导致进入后台成了个高频操作，所以主页按钮的合理与否的体验和重要性也被放大了。
