### ISSUE TITLE
建议增加支持 曲奇云盘

### ISSUE THREAD

**Issue by bxxyzbxxzy** [alist-org/alist#4785]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

请求大佬增加曲奇云盘
https://www.quqi.com/

**Comment by Greatwallcorner** [comment]
https://zhuanlan.zhihu.com/p/132638942 我看网上说这体验不好啊 用过的可以说说

**Comment by anwen-anyi** [comment]
> https://zhuanlan.zhihu.com/p/132638942 我看网上说这体验不好啊 用过的可以说说 ![图片](https://user-images.githubusercontent.com/49832311/253812302-ee423662-d1ad-4e46-954f-f71c60e46ed7.png) 而且这个有点离谱

确实离谱~曲奇算了吧

**Comment by JunketPear** [comment]
> https://zhuanlan.zhihu.com/p/132638942 我看网上说这体验不好啊 用过的可以说说 ![图片](https://user-images.githubusercontent.com/49832311/253812302-ee423662-d1ad-4e46-954f-f71c60e46ed7.png) 而且这个有点离谱

那可太不好了
什么程度呢 你下载文件必须要保持网盘页面打开 而且不开会员只有十几kb 页面一关 下载中断
优点是私人盘文件随便放 大部分都不封
缺点就是下载体验贼tm傻逼 关了网页就下不了

**Comment by ZJWiGithub** [comment]
支持增加

**Comment by SuperLoserPeco** [comment]
> > https://zhuanlan.zhihu.com/p/132638942 我看网上说这体验不好啊 用过的可以说说 ![图片](https://user-images.githubusercontent.com/49832311/253812302-ee423662-d1ad-4e46-954f-f71c60e46ed7.png) 而且这个有点离谱
> 
> 那可太不好了 什么程度呢 你下载文件必须要保持网盘页面打开 而且不开会员只有十几kb 页面一关 下载中断 优点是私人盘文件随便放 大部分都不封 缺点就是下载体验贼tm傻逼 关了网页就下不了

其实只要有能有webdav那样丝滑的文件操作方式就挺好的了
