### ISSUE TITLE
添加更多权限控制的功能

### ISSUE THREAD

**Issue by HGameBlog** [alist-org/alist#4787]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

![image](https://github.com/alist-org/alist/assets/138053033/4978e6b3-13bb-4ee1-9736-a2ca99d0263f)
下载权限
不同目录的查看权限
预览权限

**Comment by jinyu2022** [comment]
特别是下载权限，貌似游客可以无限制下载别人分享的链接。我希望即使是分享的链接也需要登录验证身份

**Comment by PPsteven** [comment]
下载权限那块是一个很大的风险，分享链接最好也需要验证身份，或者添加过期时间。

**Comment by anwen-anyi** [comment]
> 下载权限那块是一个很大的风险，分享链接最好也需要验证身份，或者添加过期时间。

分享链接本来就有过期时间 需要自己设置

**Comment by jinyu2022** [comment]
> > 下载权限那块是一个很大的风险，分享链接最好也需要验证身份，或者添加过期时间。
> 
> 分享链接本来就有过期时间 需要自己设置 默认是0不会过期

是的, 需要在 设置-全局里设置. 但是实测分享的链接是可以无限制下载的

**Comment by anwen-anyi** [comment]
> > > 下载权限那块是一个很大的风险，分享链接最好也需要验证身份，或者添加过期时间。
> 
> > 
> 
> > 分享链接本来就有过期时间 需要自己设置 默认是0不会过期
> 
> 
> 
> 是的, 需要在 设置-全局里设置. 但是实测分享的链接是可以无限制下载的

你得把签名所有打开呀…不然怎么校验过期时间

**Comment by jinyu2022** [comment]
> > > > 下载权限那块是一个很大的风险，分享链接最好也需要验证身份，或者添加过期时间。
> > 
> > 
> > > 
> > 
> > 
> > > 分享链接本来就有过期时间 需要自己设置 默认是0不会过期
> > 
> > 
> > 是的, 需要在 设置-全局里设置. 但是实测分享的链接是可以无限制下载的
> 
> 你得把签名所有打开呀…不然怎么校验过期时间

我的意思是,确实可以控制时间,但是无法控制下载的身份.如果可以,我希望以后可以控制下载的身份/用户.

**Comment by mengguyi** [comment]
> ###
> **[jinyu2022](/jinyu2022) ** commented [Jul 19, 2023](#issuecomment-1642041215)

关闭签名所有，这样会要求用户提供 cookie 来下载
