### ISSUE TITLE
阿里云盘open下载失败

### ISSUE THREAD

**Issue by Rishou04** [alist-org/alist#4789]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.22.1

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

点击这里的下载，会报错，请看图片

### Reproduction / 复现链接

![IMG_20230717_084831](https://github.com/alist-org/alist/assets/62320562/00d8a4d9-69d5-4d79-ab92-ad48cf6a9da0)

**Comment by Rishou04** [comment]
![Uploading IMG_20230717_084842.jpg…]()

**Comment by anwen-anyi** [comment]
无效信息

**Comment by Rishou04** [comment]
![Uploading IMG_20230717_084842.jpg…]()

**Comment by Rishou04** [comment]
![IMG_20230717_084842](https://github.com/alist-org/alist/assets/62320562/b09d9636-3ca3-4b10-bab7-5bdf3ff28ebe)

**Comment by Rishou04** [comment]
> 无效信息

这个

**Comment by anwen-anyi** [comment]
手机浏览器的原因 换浏览器就行 盲猜  `via`

**Comment by Rishou04** [comment]
> 手机浏览器的原因 换浏览器就行 盲猜 `via`

对我刚刚试了电脑没问题

**Comment by anwen-anyi** [comment]
> > 手机浏览器的原因 换浏览器就行 盲猜 `via`
> 
> 对我刚刚试了电脑没问题

就是via浏览器的问题 都是这样，你点旁边的哪个复制链接再去下载就没事儿

**Comment by anwen-anyi** [comment]
> > > 手机浏览器的原因 换浏览器就行 盲猜 `via`
> > 
> > 
> > 对我刚刚试了电脑没问题
> 
> 就是via浏览器的问题 都是这样，你点旁边的哪个复制链接再去下载就没事儿

跟AList没什么关系~

**Comment by Xhofe** [comment]
via似乎无法识别HTML中的禁用referer的meta，所以这属于浏览器方问题，也只能由浏览器方修复
