### ISSUE TITLE
谁有alist挂载百度网盘的完整设置

### ISSUE THREAD

**Issue by zzfree2021** [alist-org/alist#4791]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

就是挂载百度网盘，然后用raidrive挂到本地z，百度网盘的文件夹不管新建还是上传提示无权限访问该文件夹，但是删除可以用。谁能给个百度网盘的完整设置图，新版的0.22.1，谢谢

**Comment by anwen-anyi** [comment]
请自行到文档     常见问题 --> 为什么 --> `RaiDrive挂载百度网盘，可以下载文件，不能上传文件。`

**Comment by zzfree2021** [comment]
站长，我用netdrive也测试了，也有这个问题，是跟alist版本有关呢还是怎么回事
