### ISSUE TITLE
请求添加微云驱动

### ISSUE THREAD

**Issue by twogo** [alist-org/alist#4802]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

腾讯微云网盘不限速，下载和在线看视频速度稳定，请求加入alist。

微云网址：https://www.weiyun.com

### Suggested solution / 实现思路

不懂程序，不知道思路。请求作者大大考虑一下这个驱动。

**Comment by twogo** [comment]
微云大公司产品，稳定靠谱。请求作者大大增加此驱动。感谢

**Comment by anwen-anyi** [comment]
22年年初的时候就有大佬研究过哩~不的行

**Comment by foxxorcat** [comment]
微云[api文档](https://open.weiyun.com/)不完整，只能实现上传、下载、重命名，连文件夹都创不了。付：（从wps抓的）
client_id：iciY14xT8lJF0SrlfvIhuTD36VeOkm9R
client_secret：26gJq9sDVHHxVUrAJy0COQ196v0EVXaW
重命名api：POST:https://user.weiyun.com/twoa/v1/files/{rs_id}/rename?new_filename=
查看文件详细信息：GET:https://user.weiyun.com/twoa/v1/files/{rs_id}

**Comment by msterzhang** [comment]
腾讯这个尿性，没有二维码，还让你扫码登录，真是大无语，很多东西庞大无条理；之前我就对接过，当时也是没办法解决登录问题，我是复制的cookie，但是基本一天就失效了：
![image](https://github.com/alist-org/alist/assets/31364579/af4ac423-3f32-4184-995a-1fac8b682ca0)

**Comment by anwen-anyi** [comment]
顺着楼上大佬提供的信息摸到了"`管事儿`"的人问了下具体情，
开放`平台API`已不使用/不维护，大概率是鸽啦~（之前提到的大佬就是我说的楼上大佬 :joy_cat:  ）

**Comment by twogo** [comment]
天翼云盘也是没有open api的吧，都是抓的客户端或者网页端的接口，然后解密他们的签名算法，自己做对接的。

**Comment by twogo** [comment]
> 微云[api文档](https://open.weiyun.com/)不完整，只能实现上传、下载、重命名，连文件夹都创不了。付：（从wps抓的） client_id：iciY14xT8lJF0SrlfvIhuTD36VeOkm9R client_secret：26gJq9sDVHHxVUrAJy0COQ196v0EVXaW 重命名api：POST:[https://user.weiyun.com/twoa/v1/files/{rs_id}/rename?new_filename=](https://user.weiyun.com/twoa/v1/files/%7Brs_id%7D/rename?new_filename=) 查看文件详细信息：GET:[https://user.weiyun.com/twoa/v1/files/{rs_id}](https://user.weiyun.com/twoa/v1/files/%7Brs_id%7D)


微云驱动，只需要能下载和在线观看视频就可以了。上传和文件操作不是必要功能，可以不做的。真心期望作者大大能添加微云这个驱动！！跪求。

**Comment by foxxorcat** [comment]
主要问题是微云网页端如果用QQ登录的话会存在cookie过期的情况，并且会很快。目前已知就算保活也活不过48h。微信登录那就没这个问题，用的是token。
本来想抓客户端的api的，但发现用的不是http而是tcp，不好搞。。。

**Comment by twogo** [comment]
> 主要问题是微云网页端如果用QQ登录的话会存在cookie过期的情况，并且会很快。目前已知就算保活也活不过48h。微信登录那就没这个问题，用的是token。 本来想抓客户端的api的，但发现用的不是http而是tcp，不好搞。。。

cookie的保活我有点思路，可以加好友详细聊聊吗？我去你博客评论区发了我的联系方式给你，望回复，感谢。

**Comment by GH6324** [comment]
> 主要问题是微云网页端如果用QQ登录的话会存在cookie过期的情况，并且会很快。目前已知就算保活也活不过48h。微信登录那就没这个问题，用的是token。 本来想抓客户端的api的，但发现用的不是http而是tcp，不好搞。。。

大佬，Token抓哪一个呢，我看有好几个Token
![image](https://github.com/alist-org/alist/assets/47879885/b4746872-098a-4b79-9495-1da49b333548)
