### ISSUE TITLE
123云盘 签名错误:auth-key empty

### ISSUE THREAD

**Issue by BnqDzj** [alist-org/alist#4811]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.22.1

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

挂载123云盘完成（没有提示错误，状态为work）后再打开主页出现failed get objs: failed to list objs: 签名错误:auth-key empty
并没有开启“启用签名”和“签名所有”
![image](https://github.com/alist-org/alist/assets/64721413/35fc8150-5d72-4895-aa3d-dabc99742d63)
![image](https://github.com/alist-org/alist/assets/64721413/016bc9ed-dfa6-463e-8324-d6aedd8b7c2e)
![image](https://github.com/alist-org/alist/assets/64721413/054728a6-849a-4c9e-b272-489819acddd2)
![image](https://github.com/alist-org/alist/assets/64721413/ae51aafe-eec3-49a2-bb54-e00275edb2aa)

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/64721413/7bb94e3b-ed5d-4525-b14f-56e5ea8b4c52)

### Logs / 日志

[31mERRO[0m[2023-07-20 10:07:44] fs/list: 签名错误:auth-key empty
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/home/runner/work/alist/alist/internal/op/fs.go:120
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/home/runner/work/alist/alist/internal/op/fs.go:117
github.com/alist-org/alist/v3/internal/fs.list
	/home/runner/work/alist/alist/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/home/runner/work/alist/alist/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/home/runner/work/alist/alist/server/handles/fsread.go:82
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/runner/work/alist/alist/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2936
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:1995
runtime.goexit
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 
[31mERRO[0m[2023-07-20 10:07:44] failed list /123云盘: 签名错误:auth-key empty
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/home/runner/work/alist/alist/internal/op/fs.go:120
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/home/runner/work/alist/alist/internal/op/fs.go:117
github.com/alist-org/alist/v3/internal/fs.list
	/home/runner/work/alist/alist/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/home/runner/work/alist/alist/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/home/runner/work/alist/alist/server/handles/fsread.go:82
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/runner/work/alist/alist/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2936
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:1995
runtime.goexit
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598
failed get objs

**Comment by YanCastle** [comment]
他们今天添加了auth-key签名，用的是md5，密钥是8-8D$sL8gPjom7bk#cY，注意这个密钥可能随时发生变化，所以123盘后面可用性不确定。

**Comment by Qi-2007** [comment]
本人才浅，用E写了一段
.版本 2
.支持库 spec

.子程序 auth_key, 文本型
.参数 url, 文本型
.局部变量 time, 文本型
.局部变量 random, 文本型
.局部变量 str, 文本型
.局部变量 md5, 文本型

time ＝ 时间_取北京时间戳 (真)
random ＝ 文本_取随机数字 (7)
str ＝ time ＋ “|” ＋ random ＋ “|” ＋ url ＋ “|web|3|8-8D$sL8gPjom7bk#cY”
调试输出 (str)
md5 ＝ 校验_取md5_文本 (str)
str ＝ time ＋ “-” ＋ random ＋ “-” ＋ md5
调试输出 (str)
返回 (str)

**Comment by YanCastle** [comment]
> 

他们打包了再一个js文件中的，我给你个js版本的签名算法。
go版本的我这两天赶项目，来不及。

**Comment by YanCastle** [comment]
> > 他们今天添加了auth-key签名，用的是md5，密钥是8-8D$sL8gPjom7bk#cY，注意这个密钥可能随时发生变化，所以123盘后面可用性不确定。 由于目前123盘的代码结构调用部分是分开的，所以我就提供思路，哪位有空的可以改一下，统一使用一个请求函数，然后把签名计算放在函数里面进行签名操作。
> 
> 可以详细说说这个签名算法在哪个js文件里面吗

`function getAuthKey(path: string) {
    // 1689861813|5436091|/b/api/file/info|web|3|8-8D$sL8gPjom7bk#cY => 25778ae9304bdbd4ba17b55570ac2a96
    // 1689862348|4908899|/b/api/user/info|web|3|8-8D$sL8gPjom7bk#cY => 5b077e47d3b0ec170c791cd68eab2d61
    let key = '8-8D$sL8gPjom7bk#cY',
        p2 = Math.round(0x989680 * Math.random()),
        p3 = Math.round(Date.now() / 0x3e8),
        p4 = [p3, p2, path, "web", "3", key].join("|");
    // 某种加密 .update(p4).hex()
    //@ts-ignore
    return [p3, p2, md5(p4)].join("-")

}`

**Comment by GeekTR** [comment]
没有解决上传问题，就不提交pr了。有人有需要的话我打包了docker，仅支持amd64. https://hub.docker.com/r/tangrui605/alist
