### ISSUE TITLE
115/阿里云跨网盘秒传

### ISSUE THREAD

**Issue by liuhangbin** [alist-org/alist#4819]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

请问是否可以实现阿里云和115之间的跨网盘妙传。目前两个网盘的秒传思路好像是一样的。CD2就支持这个功能。

**Comment by seanhe26** [comment]
已经在规划的功能内

**Comment by i990049** [comment]
> 已经在规划的功能内

  百度迅雷夸克天翼能不能秒传到115？

**Comment by seanhe26** [comment]
> > 已经在规划的功能内
> 
> 百度迅雷夸克天翼能不能秒传到115？

网盘之间免下载秒传的前提是： 源头和目标可以获取到相同算法的hash。 比如百度网盘用的是MD5，而阿里云盘用的是SHA-1，115 用的是sha-1. 等等。 这个功能需要我最新的pr合并之后才会开发，因为需要用到pr里的功能。

**Comment by wdisk2020** [comment]
隔壁的CD2 要收费了 期待大佬升级这个功能

**Comment by JsonSong89** [comment]
> 隔壁的CD2 要收费了 期待大佬升级这个功能

那个简直是迷,功能那么弱,除了一个挂载本地盘有点用(也是依赖的winfsp),还很不稳定,说要收费之后,我立马换了rclone ,无非是稍微配置一下

**Comment by wdisk2020** [comment]
> > 隔壁的CD2 要收费了 期待大佬升级这个功能
> 
> 那个简直是迷,功能那么弱,除了一个挂载本地盘有点用(也是依赖的winfsp),还很不稳定,说要收费之后,我立马换了rclone ,无非是稍微配置一下

115之前互导不错

**Comment by murazi** [comment]
支持天翼吗，189的资源太少了

**Comment by SeanHeuc** [comment]
> 支持天翼吗，189的资源太少了

暂不支持，因为我不用你说的盘，所以我也不知道可行性。你开新issue讨论吧，这个已经关闭了
