### ISSUE TITLE
能增加挂载oss后，上传使用oss的域名信息吗

### ISSUE THREAD

**Issue by ZhYuLn** [alist-org/alist#4820]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前挂载了阿里云的oss后，上传文件是先传递到服务器上，再由服务器调用oss的接口上传文件到阿里云上，能否在上传的时候由后端获得oss签名后，返回给前端一个上传链接，上传流量不经过服务器

**Comment by JsonSong89** [comment]
那你不如直接用阿里云的oss-browser来做上传

**Comment by Sunakier** [comment]
> 那你不如直接用阿里云的oss-browser来做上传

统一管理会方便些，而且这个功能还有其他需求，Teambition的国内版使用的就是阿里云OSS，就是服务端返回临时链接由客户端直接上传阿里云OSS不经Teambition服务器，适配s3
