### ISSUE TITLE
构建前端报错

### ISSUE THREAD

**Issue by Greyisttot** [alist-org/alist#4821]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

dd5c0e560d116e91f13e552fe36880b6ff511af1

### Driver used / 使用的存储驱动

CentOS Stream 9, node-20.4.0, npm-9.7.2, pnpm-8.6.9

### Describe the bug / 问题描述

[vite:load-fallback] Could not load /alist/alist-web/solid-router/src (imported by src/main.tsx): ENOENT: no such file or directory, open '/alist/alist-web/solid-router/src'
error during build:
Error: Could not load /alist/alist-web/solid-router/src (imported by src/main.tsx): ENOENT: no such file or directory, open '/alist/alist-web/solid-router/src'
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction / 复现链接

yum update && yum upgrade

wget https://mirrors.aliyun.com/nodejs-release/v20.4.0/node-v20.4.0-linux-x64.tar.gz -O /usr/local/node-v20.4.0-linux-x64.tar.gz

tar -zxvf /usr/local/node-v20.4.0-linux-x64.tar.gz -C /usr/local

mv /usr/local/node-v20.4.0-linux-x64 /usr/local/node-v20.4.0

echo 'export NODE_HOME=/usr/local/node-v20.4.0' >> /etc/profile

echo 'export PATH=$PATH:$NODE_HOME/bin' >> /etc/profile

source /etc/profile

npm config set registry "https://registry.npm.taobao.org"

npm config get registry

node -v

npm -v

npm install -g pnpm

pnpm -v

cd /

yum install -y git

mkdir alist

cd alist

git clone https://github.com/alist-org/alist.git

git clone https://github.com/alist-org/alist-web.git

cd alist-web

wget https://crowdin.com/backend/download/project/alist/zh-CN.zip

unzip zh-CN.zip

node ./scripts/i18n.mjs

rm zh-CN.zip

pnpm install && pnpm run build

**Comment by Greyisttot** [comment]
https://github.com/alist-org/alist/issues/1763

**Comment by Greyisttot** [comment]
https://github.com/alist-org/alist-web/issues/5

**Comment by Greyisttot** [comment]
这样克隆才行
git clone --recurse-submodules https://github.com/alist-org/alist-web.git

**Comment by anwen-anyi** [comment]
> 这样克隆才行 git clone --recurse-submodules https://github.com/alist-org/alist-web.git

https://anwen-anyi.github.io/index/build/linux.html
你可以参考一下这个教程，我看你使用的是 `npm` 编译是需要`pnpm`的
