### ISSUE TITLE
退出kodi后，alist仍在占用大量的下行带宽

### ISSUE THREAD

**Issue by NijatInHIT** [alist-org/alist#4827]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

alist v3.18

### Driver used / 使用的存储驱动

夸克，阿里云，百度云

### Describe the bug / 问题描述

**kodi视频看一半退出或者选择播放其他视频后**， 仍然在占用大量的网速的下载。 打开log也没有相关内容，严重影响整体网络的速度。

这台机器上只有alist， 没有其他因素干扰网络

### Reproduction / 复现链接

1. alist挂载夸克网盘
2. kodi链接alist webdav
3. 打开电影播放，查看网络占用
4. 退出kodi，再查看网络占用
5. 即使没有kodi在消费数据，alist仍在10mb/s的下载资源

### Logs / 日志

日志里没有任何下载流量相关的内容，无法提供日志

**Comment by NijatInHIT** [comment]
是按照模版写的，有什么问题吗

**Comment by seanhe26** [comment]
只有夸克有这个问题吧？  如果是的那我已经修复了 会近期合并

**Comment by NijatInHIT** [comment]
> 只有夸克有这个问题吧？ 如果是的那我已经修复了 会近期合并

不好意思有点想不起来了， 回去我可以再试一下阿里云和百度云

**Comment by seanhe26** [comment]
> > 只有夸克有这个问题吧？ 如果是的那我已经修复了 会近期合并
> 
> 不好意思有点想不起来了， 回去我可以再试一下阿里云和百度云

有条件的话测一下 https://github.com/alist-org/alist/actions/runs/5700341236  这个build， 我自己测试随时关闭用户端连接，服务端的远程连接也很快关闭

**Comment by NijatInHIT** [comment]
> > > 只有夸克有这个问题吧？ 如果是的那我已经修复了 会近期合并
> > 
> > 
> > 不好意思有点想不起来了， 回去我可以再试一下阿里云和百度云
> 
> 有条件的话测一下 https://github.com/alist-org/alist/actions/runs/5700341236 这个build， 我自己测试随时关闭用户端连接，服务端的远程连接也很快关闭

好，有空我试试
