### ISSUE TITLE
[安全]该账户因涉嫌违规，暂时无法使用阿里云盘服务

### ISSUE THREAD

**Issue by Yuelioi** [alist-org/alist#4828]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.23.0

### Driver used / 使用的存储驱动

阿里云盘 Open

### Describe the bug / 问题描述

该账号已被限制登录

尊敬的用户你好，该账户因涉嫌违规，暂时无法使用阿里云盘服务，如有问题请联系客服邮箱：adrive@service.alibaba.com

我只用过alist, 再更新alist并且想登录手机扫描更新token, 提示我账号被限制

---

官网文档说的是

同一 IP 在 60 分钟内请求 10 次，会出现 Too Many Requests 🚫避免滥用，请勿滥用🚫

例如在 保存/编辑 的时候算一次请求，查看文件看视频下载不算。

但是我基本上只查看, 我看文档留言也有人被封了

### Reproduction / 复现链接

https://pan.yuelili.com/

**Comment by Yuelioi** [comment]
昨天还没事, 今天就不行了~

**Comment by Xhofe** [comment]
alist官网的文档描述的只是针对刷新令牌的速率做限制。

其他任何操作以阿里网盘官方为准。

**Comment by msycn** [comment]
同被封号

**Comment by Yuelioi** [comment]
> 同被封号

你给官方发邮件解封, 然后别再用alist挂载了就行了

**Comment by msycn** [comment]
> 

谢谢，已经解封。aliyun回复说下次再用服务器挂载第三方软件永封😭

**Comment by miaopasimiao** [comment]
> > 
> 
> 谢谢，已经解封。aliyun回复说下次再用服务器挂载第三方软件永封😭

其实和这个没关系 你肯定做了一些违规操作 比如让一堆人用你连接看视频 但是你却用的302重定向 或者你站被爬虫爬了
如果开的代理模式基本上流量不是特别特别大都不会被封

**Comment by mrc321** [comment]
话说Alist不是阿里官方都推荐过的第三方应用吗？现在都还挂在他们官网上。https://www.aliyundrive.com/download/externalApplications

**Comment by Yuelioi** [comment]
> 话说Alist不是阿里官方都推荐过的第三方应用吗？现在都还挂在他们官网上。https://www.aliyundrive.com/download/externalApplications

个人用应该问题不大 这个是针对之前做外链

alist官方补了说明

 请勿将阿里云盘进行公开分享，禁止帐号被多IP访问，若进行分享后帐号被冻结后果自负  添加存储后请及时设置元信息等措施防止被{其他人/爬虫}恶意[访问/分享]导致帐号被冻结，其他云盘也一样防止被冻结/封号
