### ISSUE TITLE
挂载115网盘无法上传文件提示升级到最新版本

### ISSUE THREAD

**Issue by WUFXXX** [alist-org/alist#4831]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.23.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

v3.23.0版本挂载115网盘无法上传文件，报错并提示升级到最新版本，当前版本已是最新版本，可以正常上传到百度阿里等其它网盘

### Reproduction / 复现链接

1

### Logs / 日志

![IMG_20230722_235624](https://github.com/alist-org/alist/assets/128899217/69e7bb3c-1e35-43a7-be58-3fedccf8a9a0)

**Comment by superliurui** [comment]
还是一样的不能上传呀
