### ISSUE TITLE
"别名"驱动无法播放挂载为SMB路径下的音乐

### ISSUE THREAD

**Issue by AndyPany** [alist-org/alist#4832]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.22.1

### Driver used / 使用的存储驱动

别名驱动

### Describe the bug / 问题描述

在Alist上面添加了SMB驱动(设备为路由器)，按常规方式打开路径，假设我的路径是/🔒私密/路由器SMB/音乐，点击里面的音乐是可以正常播放的。

但我使用"别名驱动"引用"/🔒私密/路由器SMB/音乐"这个路径时，假设我的"别名驱动"挂载路径为"/多媒体/音乐"，点击里面的音乐是没法播放的。

### Reproduction / 复现链接

An audio error has occurred,player will skpi forward in 2 seconds

### Logs / 日志

错误提示："An audio error has occurred,player will skpi forward in 2 seconds"

![Screenshot_2023-07-22-23-57-25-45_df198e732186825c8df26e3c5a10d7cd](https://github.com/alist-org/alist/assets/133225345/6c5ce636-1c26-469f-93a2-5286a3a3b5e2)
![Screenshot_2023-07-22-23-20-43-84_df198e732186825c8df26e3c5a10d7cd](https://github.com/alist-org/alist/assets/133225345/fe06ee2b-ac80-4238-b4b2-1f7cd68b2e90)
![Screenshot_2023-07-22-23-19-20-85_df198e732186825c8df26e3c5a10d7cd](https://github.com/alist-org/alist/assets/133225345/1c1411b1-c8a8-4430-b05e-7f81eade9263)
![Screenshot_2023-07-22-23-58-08-45_df198e732186825c8df26e3c5a10d7cd](https://github.com/alist-org/alist/assets/133225345/55c81617-c75b-4363-8acc-a0a95e6eba8e)

**Comment by AndyPany** [comment]
图一是SMB驱动，播放音乐正常。
图二是别名驱动，引用了图一的路径。
图三是使用别名驱动，音乐播放失败及错误提示。
图四是SMB驱动，按正常进入路径点击音乐播放正常。

**Comment by Xhofe** [comment]
请提供一个在线链接。

**Comment by AndyPany** [comment]
> 
https://android.ddnsto.com/%E5%A4%9A%E5%AA%92%E4%BD%93/%E9%9F%B3%E4%B9%90/%E5%91%A8%E6%9D%B0%E4%BC%A6%E4%B8%93%E8%BE%91

**Comment by AndyPany** [comment]
> 请提供一个在线链接。

> 请提供一个在线链接。

但是我使用的是ddnsto的内网穿透服务，必须要我授权才能访问我提供的连接

**Comment by Xhofe** [comment]
1. 别名种的路径需要是绝对路径，即要在路径前面加`/`，具体参照文档：https://alist.nn.ci/zh/guide/drivers/alias.html#%E5%A1%AB%E5%86%99%E6%96%B9%E5%BC%8F
2. 你需要让程序知道正确的协议，给程序传递`X-Forwarded-Proto`头，或者设置 https://alist.nn.ci/zh/config/configuration.html#site-url
