### ISSUE TITLE
将Alist版本降级为v2.6.4后，配置RaiDrive时显示401未经授权错误

### ISSUE THREAD

**Issue by Holiday2019** [alist-org/alist#4839]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v2.6.4

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

我的目的是通过网盘挂载本地，将百度网盘里的一些文件转移到夸克网盘。

用最新版的Alist，显示“你需要权限来执行此操作”

查阅Alist文档得知需要使用v2版本的Alist，参考资料：[为什么 | AList文档](https://alist.nn.ci/zh/faq/why.html#raidrive%E6%8C%82%E8%BD%BD%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98-%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6-%E4%B8%8D%E8%83%BD%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E3%80%82%E5%BE%80%E6%8C%82%E8%BD%BD%E7%9B%AE%E5%BD%95%E4%B8%A2%E6%96%87%E4%BB%B6%E6%8F%90%E7%A4%BA-%E6%8F%90%E7%A4%BA-%E4%BD%A0%E9%9C%80%E8%A6%81%E6%9D%83%E9%99%90%E6%9D%A5%E6%89%A7%E8%A1%8C%E6%AD%A4%E6%93%8D%E4%BD%9C-%E3%80%82%E8%BF%99%E4%B8%AA%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3)

然后，当我这么做之后，在我正确配置网页端管理后台后，无法正确配置RaiDrive：

下图表示：Alist配置正确
![image-20230724130526466](https://picture-cloud-master.oss-cn-hangzhou.aliyuncs.com/img202307241305623.png)

下图表示：RaiDrive配置，401未经授权错误

![image-20230724130607821](https://picture-cloud-master.oss-cn-hangzhou.aliyuncs.com/img202307241306862.png)

![image-20230724130618314](https://picture-cloud-master.oss-cn-hangzhou.aliyuncs.com/img202307241306354.png)

请问，我该如何解决？谢谢

### Reproduction / 复现链接

https://github.com/alist-org/alist/releases?page=5

### Logs / 日志

![image-20230724130607821](https://picture-cloud-master.oss-cn-hangzhou.aliyuncs.com/img202307241306862.png)

![图片](https://github.com/alist-org/alist/assets/54856595/d72ab6a7-699f-4bc7-8f24-e51968e2587e)

**Comment by Holiday2019** [comment]
您好，请问我该如何解决？@Xhofe

**Comment by Xhofe** [comment]
https://alist-doc.nn.ci/docs/intro/

**Comment by Holiday2019** [comment]
v3什么以后会支持上传空文件夹么？

> https://alist-doc.nn.ci/docs/intro/

**Comment by mintisan** [comment]
将 `/dav` 改成 `/dav/` 试试看
