### ISSUE TITLE
aliyun_open驱动 后台显示work 前台访问偶发出现一个错误

### ISSUE THREAD

**Issue by huolanyun** [alist-org/alist#4840]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.23.0

### Driver used / 使用的存储驱动

阿里云盘 Open

### Describe the bug / 问题描述

主页访问偶尔出现 这个错误，刷新有时候会好，后台驱动显示work
failed get objs: failed to list objs: invalid character '<' looking for beginning of value

### Reproduction / 复现链接

暂无，这个不是一定会发生得

**Comment by anwen-anyi** [comment]
你需要更新你的AList版本了🫤

**Comment by STEVENTAN100** [comment]
我也是偶尔出现这个错误，最新版本的

**Comment by li-peifeng** [comment]
> 我觉得你的版本信息不对
> 
> 你需要更新你的AList版本了🫤

我也是有这个问题，版本信息有问题吗？

**Comment by huolanyun** [comment]
> 我觉得你的版本信息不对
> 
> 你需要更新你的AList版本了🫤

一键安装linux更新的最新版本，更新完 刷新 就出现了，之前是3.22.0 版本没有此驱动问题

**Comment by Xhofe** [comment]
3.22.0对aliyundrive_open无任何修改，这个错误取决于aliyundrive api的返回内容。它有时候返回的不是json格式的内容而是xml的时候就会出现此错误，但是阿里云盘Open的官方API文档中并没有提到何时会返回xml内容，故暂时搁置。

**Comment by BakaJzon** [comment]
3.25.1 再踢一脚

**Comment by JsonSong89** [comment]
可以检查一下 Oauth令牌链接 这个配置
有可能用了被屏蔽的那个

**Comment by JsonSong89** [comment]
https://alist.nn.ci/zh/guide/drivers/aliyundrive_open.html

**Comment by xhofe** [comment]
此问题应该在更换API服务器后被修复，暂关闭。
