### ISSUE TITLE
希望增加对 OneDrive 的 “文件夹共享链接” 挂载

### ISSUE THREAD

**Issue by nibazshab** [alist-org/alist#4849]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

管理员关闭了 API，没办法使用正常的 OneDrive 挂载方式

根据 [AList Docs #webdav#onedrive-sharepoint](https://alist.nn.ci/zh/guide/drivers/webdav.html#onedrive-sharepoint) 的教程 ，实测会出现 `PROPFIND /: 403` 错误，猜测管理员同样关闭了 WebDAV

希望能够添加一种新的挂载方式，就是直接去挂载 OneDrive 的 “共享链接”

### Suggested solution / 实现思路

1. 在 OneDrive 页面，对某一个文件夹开启共享，~~并允许所有人编辑~~
2. 即可获得 `https://xxxx.sharepoint.com/:f:/g/personal/xxxxxxxx/mmmmmmmmm` 这样的共享链接
3. 然后对这个 “文件夹的共享链接” 进行挂载

### Additional context / 附件

从 OneManager-php 项目那里确认了可行性 `https://github.com/qkqpttgf/OneManager-php/blob/master/disk/Sharelink.php`
![image](https://github.com/alist-org/alist/assets/44338441/999df491-f3ea-4de0-b2c2-e8ca4483d845)
![image](https://github.com/alist-org/alist/assets/44338441/746ce5ab-fc82-4fb9-b18d-50120193f90a)

**Comment by Sakura-Byte** [comment]
M$脑子有问题，OD/SP的分享链接的“编辑”权限有点搞笑，没法删除的，只能查看/新上传
我觉得这个需求可能没法这么满足。

**Comment by nibazshab** [comment]
即使只能查看也是好事啊，最起码可以让电视直接 WebDAV 挂载，然后看视频了

**Comment by nibazshab** [comment]
> 即使只能查看也是好事啊，最起码可以让电视直接 WebDAV 挂载，然后看视频了

就像这个 “阿里云盘分享”，即使只能查看也很棒的

![image](https://github.com/alist-org/alist/assets/44338441/c94d038e-012c-435c-9346-4d014030ed36)

**Comment by nibazshab** [comment]
保活

**Comment by ChenyangGao** [comment]
今天我本来也想提这个需求

**Comment by Luotianyi-0712** [comment]
我也希望能够增加这个功能，onedrive的分享太难用了

**Comment by xhofe** [comment]
closed in #6793
