### ISSUE TITLE
修改文本类文件后点击保存不生效

### ISSUE THREAD

**Issue by ziyuand** [alist-org/alist#4852]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.23.0

### Driver used / 使用的存储驱动

Aliyundrive

### Describe the bug / 问题描述

修改文本类文件后点击保存或上传修改后的同名文件，未能及时更新文件缓存重新编辑或浏览时还是原未修改文件，下载也是下载的未修改文件，目前在阿里云盘上出现，其他驱动未测试

### Reproduction / 复现链接

上传新文件名称与旧文件相同时，使用在线Text Editor修改文件保存后

**Comment by Greatwallcorner** [comment]
对于重名文件， 一般怎么处理呢， 我在local测试， 会直接把原文件覆盖，是应该自动重命名/提示用户重命名， 还是保持原状呢
