### ISSUE TITLE
挂载123pan时报错

### ISSUE THREAD

**Issue by Qi-2007** [alist-org/alist#4857]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

 Built At: 2023-07-27 07:54:24 +0000 Go Version: go1.20.6 linux/amd64 Author: Xhofe <i@nn.ci> Commit ID: 4afa822 Version: dev WebVersion: dev

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

挂载123pan时报错如下：
Failed init storage: Get "https://www.123pan.com/api/user/info": dial tcp: lookup www.123pan.com on [**1]:53: read udp [**1]:51453->[**1]:53: read: connection refused
打开挂载的123pan时报错如下：
failed get objs: failed to list objs: Get "https://www.123pan.com/api/file/list/new?Page=1&driveId=0&limit=100&next=0&orderBy=file_name&orderDirection=asc&parentFileId=0&trashed=false": dial tcp: lookup www.123pan.com on [**1]:53: read udp [**1]:34146->[**1]:53: read: connection refused

tip：在运行alist的平台上能正常打开www.123pan.com

### Reproduction / 复现链接

http://192.168.43.22/@manage/storages/edit/1
http://192.168.43.22/123

### Logs / 日志

Failed init storage: Get "https://www.123pan.com/api/user/info": dial tcp: lookup www.123pan.com on [**1]:53: read udp [**1]:51453->[**1]:53: read: connection refused

**Comment by Qi-2007** [comment]
@Xhofe 为啥无效啊

**Comment by Xhofe** [comment]
https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host

**Comment by Qi-2007** [comment]
> https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host

已经尽力去排查了，ping和curl都是能访问123的，而且我试了下添加迅雷网盘也报错,后面用termux下载了alist再到shell去启动alist是可以正常访问网络的，感觉是dev版本可能哪里出问题了
