### ISSUE TITLE
希望能自由固定一种视图预览模式，默认是列表，每次预览图片，视频都要切换一下不方便

### ISSUE THREAD

**Issue by softwareygr** [alist-org/alist#4861]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能自由固定一种视图预览模式，默认是列表，每次预览图片，视频都要切换一下不方便

### Suggested solution / 实现思路

能否用js 打开的时候自动去点击修改

**Comment by KNaiFen** [comment]
你这个需求我正好自己改过，我自己改的源码然后编译的，在alist-web的layout.tsx中添加这个：
```
  onMount(() => {
    const currentUrl = window.location.href;
    const targetUrl_1 = "your_url_1";
    const targetUrl_2 = "your_url_2";
    if (currentUrl === targetUrl_1) {
      setLayout('image');
    }
    if (currentUrl === targetUrl_2) {
      setLayout('list');
    }
  });
```
这样当url等于your_url_1的时候就会触发然后自动改变视图了，我自己的笨办法🤣
我也希望新版本能内置这个功能，具体表现大概就是元数据中能添加这个路径的视图，每次到这个路径就自动变成这个视图

**Comment by luoben4040** [comment]
我也遇到这个问题，我希望所有用户默认视图是”网格视图“，而不是默认的”列表视图“。我不知道怎么样才能实现。
