### ISSUE TITLE
搜索功能无法建立 Alist v3驱动方式添加的索引

### ISSUE THREAD

**Issue by liujianchao1995** [alist-org/alist#4865]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [x] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.23.0

### Driver used / 使用的存储驱动

Alist v3

### Describe the bug / 问题描述

搜索功能无法建立 Alist v3驱动方式添加的索引，资源无法搜索。
我通过ALIST v3驱动挂载了“小雅alist”，然后使用alist自带的搜索功能，无法搜得小雅目录下的资源。

### Reproduction / 复现链接

https://al.nn.ci/

### Logs / 日志

{"code":200,"message":"success","data":{"content":[],"total":0}}

**Comment by anwen-anyi** [comment]
这你得去问小雅了，小雅的是魔改过的 和`AList`无关

**Comment by huolanyun** [comment]
> 

安大，怎么编译linux  musl 版本，按照你的教程去Codespace Templates 编译，在放回 centos 提示 glibc 找不到2.28
/lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./alist)
