### ISSUE TITLE
123云盘挂载错误 ERROR RESTY Get "https://www.123pan.com/api/file/list/new?Page=1&driveId=0&limit=100&next=0&orderBy=file_name&orderDirection=asc&parentFileId=0&trashed=false": EOF, Attempt 1

### ISSUE THREAD

**Issue by fvlw** [alist-org/alist#4868]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.24.0

### Driver used / 使用的存储驱动

123pan

### Describe the bug / 问题描述

![图片](https://github.com/alist-org/alist/assets/71577616/07ef946c-637f-4b2f-8bce-7ed0e368fa99)

![图片](https://github.com/alist-org/alist/assets/71577616/fc48a2c5-c36d-4acc-ba7e-6768713e2e25)

### Reproduction / 复现链接

http://localhost:5244/123

**Comment by anwen-anyi** [comment]
检查你自己网络问题，并无此问题
![image](https://github.com/alist-org/alist/assets/56105412/050c12c3-df7e-4cfd-963c-488ce3ed11b9)

在线播放都可以
![image](https://github.com/alist-org/alist/assets/56105412/3e888d2d-54ec-44a0-aed5-8e1b6c10c699)
