### ISSUE TITLE
一刻相册只删除相册中的照片 而并没有真实的在一刻相册中删除

### ISSUE THREAD

**Issue by aiXlau** [alist-org/alist#4872]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.24.0

### Driver used / 使用的存储驱动

一刻相册

### Describe the bug / 问题描述

一刻相册只删除相册中的照片 而并没有真实的在一刻相册中删除

### Reproduction / 复现链接

一刻相册只删除相册中的照片 而并没有真实的在一刻相册中删除

**Comment by aiXlau** [comment]
只是移出了相册

**Comment by foxxorcat** [comment]
如果删除了就会存在一个逻辑上的矛盾，两个相册存在同一个图片，当第一个相册删除了源文件，第二个相册的图片就会一起被删除

**Comment by aiXlau** [comment]
> 

所以能不能将删除设置为真实删除，再加一个移除相册的按钮

**Comment by foxxorcat** [comment]
alist不是专门适配一刻相册的程序，不过可以在后台添加一个选项，删除相册图片时删除源文件
