### ISSUE TITLE
添加ip记录

### ISSUE THREAD

**Issue by AixLau** [alist-org/alist#4878]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否在管理中添加一个 ip设备登录记录，这样可以防范alist有没有被陌生人给获取密码登录进来 ，设置登录设备白名单 ip白名单 黑名单等

**Comment by anwen-anyi** [comment]
1. 你说的 IP登录记录 log.log日志文件有，只不过没有显示是哪个用户名登录的而已,有IP显示
```json
[GIN] 2023/07/31 - 17:57:06 | 200 |            0s |  192.168.31.103 | POST     "/api/auth/login"
[GIN] 2023/07/31 - 17:57:06 | 200 |            0s |  192.168.31.103 | GET      "/api/me"
[GIN] 2023/07/31 - 17:57:07 | 200 |      1.0001ms |  192.168.31.103 | GET      "/@manage/metas"
[GIN] 2023/07/31 - 17:57:07 | 200 |           1ms |  192.168.31.103 | GET      "/@manage/storages"
```

2. 你说的登录设备白名单/黑名单
    - 你是否在寻找Nginx？？？

**Comment by Kx-Y** [comment]
直接上防火墙不是更方便？

**Comment by 443126500** [comment]
黑名单可以用第三方实现，登录历史记录及ip可以考虑添加上，类似：
账户名 登录ip ip归属地 登录时间

**Comment by wisinfun** [comment]
后台没有日志显示吧，其实如果能自定义通知是极好的，有新ip访问，能推送通知到指定的通知客户端（邮件、Bark）
