### ISSUE TITLE
 华硕路由器 v3.24.0 无法播放115视频，有出现目录，但是无法播放

### ISSUE THREAD

**Issue by fanxu1218** [alist-org/alist#4888]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.24.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

我是使用华硕路由器安装的，目前更新到最新版本了，115还是无法播放。目录有加载出来，但是播放的时候提示加载失败，出现一个三角惊叹号

### Reproduction / 复现链接

额，我是用路由器的，好像无法提供这个链接

### Logs / 日志

![WX20230801-100635@2x](https://github.com/alist-org/alist/assets/3733447/101dfb00-a3d4-4ca6-a604-b3065d25bfcd)
![WX20230801-100627@2x](https://github.com/alist-org/alist/assets/3733447/d001feff-7baa-4141-bf2d-94c5d50ef76c)
![截图1](https://github.com/alist-org/alist/assets/3733447/5b7c8a2f-995a-477d-b206-5e2ae8c23d6a)

**Comment by anwen-anyi** [comment]
看不到是 `H265`?

**Comment by fanxu1218** [comment]
> 

不是H265也无法播放呀

**Comment by fanxu1218** [comment]
> 看不到是 `H265`么? 你需要搜下文档为什么不能播放~

不是H265也是无法播放，我是用infuse加载webDAV的，阿里云盘百度网盘都可以，115网盘会提示加载此内容时发生错误。

**Comment by fanxu1218** [comment]
> 



> Hello @fanxu1218, your issue is invalid and will be closed. 你好 @fanxu1218，你的issue无效，将被关闭。

我不是截图了吗，的确无法播放呀

**Comment by Xhofe** [comment]
![image](https://github.com/alist-org/alist/assets/36558727/ea107335-eab6-476e-8aa7-49b50cafc092)

**Comment by fanxu1218** [comment]
> ![image](https://user-images.githubusercontent.com/36558727/257424800-ea107335-eab6-476e-8aa7-49b50cafc092.png)
我是用本地路由器播放的呀，我怎么复现呀，拍个视频？

**Comment by Xhofe** [comment]
你可以使用内网穿透工具来提供在线的链接。

你提供的三种截图视频格式全都是h265/hevc的 本身就无法在网页中播放。

**Comment by fanxu1218** [comment]
> 你可以使用内网穿透工具来提供在线的链接。
> 
> 你提供的三个截图视频格式全都是h265/hevc的 本身就无法在网页中播放。

网页的之前是有测试过是可以播放的，我是用Infuse+webDAV播放的也放不出来呀，提示加载此内容时发生错误

**Comment by Xhofe** [comment]
我不知道你的情况 所以我需要一个复现链接来判断是什么问题。

**Comment by fanxu1218** [comment]
> 我不知道你的情况 所以我需要一个复现链接来判断是什么问题。

我还不知道你说的使用内网穿透工具来提供在线的链接，我得研究一下

**Comment by fanxu1218** [comment]
> 我不知道你的情况 所以我需要一个复现链接来判断是什么问题。

搞不定这个在线链接，就记得115的驱动问题你们之前有修正过，但是后面更新的版本也还是经常出现无法播放的问题。

> 我不知道你的情况 所以我需要一个复现链接来判断是什么问题。

或者我开向日葵，你远程登录看下，我的识别码:537190133 验证码8rg770

**Comment by Xhofe** [comment]
你的site_url配置有问题。另外你没有给予远程控制的权限 我无法操作。

**Comment by fanxu1218** [comment]
授权了，可以操作了么

**Comment by Xhofe** [comment]
不行 我已经告诉你了 你的site_url 配置有问题，具体请参考：https://alist.nn.ci/zh/config/configuration.html#site-url

**Comment by fanxu1218** [comment]
我是路由器版本，是在哪个位置，我没看到设置site_url 配置的地方

**Comment by Xhofe** [comment]
路由器版本并非由我提供 请咨询提供方。
