### ISSUE TITLE
从老版本升级到新版本后进不去了，显示一片空白

### ISSUE THREAD

**Issue by ilkeiii** [alist-org/alist#4891]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.24.0

### Driver used / 使用的存储驱动

阿里云盘open等

### Describe the bug / 问题描述

从老版本（v3.23.0）升级到新版本（v3.24.0）后进不去了，显示一片空白，过了很久还是一样，回退v3.23.0后正常进入，我拉取v3.24.0的镜像重新开一个空白容器后能进得去，但是当我配置好驱动器，重新启动后又是空白进不去了，看了下终端貌似是加载驱动器的时候卡住了，我配置了多个不同账号的阿里云盘open驱动器，是帮朋友挂载的。

### Reproduction / 复现链接

配置多个驱动器后就会卡住

**Comment by ilkeiii** [comment]
[https://s2.loli.net/2023/08/01/ZBp6NnXKES8urt9.png](url)
[https://s2.loli.net/2023/08/01/Rb5h7vtHjDcp8TG.png](url)

**Comment by ilkeiii** [comment]
<img width="772" alt="屏幕截图 2023-08-01 143116" src="https://github.com/alist-org/alist/assets/62320562/1f5e227b-8959-49a6-88ca-10184fc9cd8c">
<img width="1280" alt="屏幕截图 2023-08-01 143443" src="https://github.com/alist-org/alist/assets/62320562/66c76fc1-3e89-41ab-9ff6-eaa5661f7522">

**Comment by earthjasonlin** [comment]
检查时候使用饿了么CDN，饿了么CDN不回源，饿了么方面原因

**Comment by ilkeiii** [comment]
> 检查时候使用饿了么CDN，饿了么CDN不回源，饿了么方面原因

还真是，删了cdn就没问题了。以前的版本都没这问题还真没想到这方面

**Comment by hkiceflow** [comment]
麻了，这远古问题有出现了，我现在cdn怎么改都不行，首页好的，主页白屏

**Comment by ilkeiii** [comment]
> 麻了，这远古问题有出现了，我现在cdn怎么改都不行，首页好的，主页白屏

试试把全局里的<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>删了

**Comment by yunkixyf** [comment]
+1，打开空白

**Comment by yunkixyf** [comment]
可以了，删了可以进去，感谢

**Comment by yunkixyf** [comment]
转自贴吧：https://tieba.baidu.com/p/8911224676   8楼
根据楼上的方法
# 主页打开白屏
# 127.0.0.1:5244/@manage/settings/global
修改 自定义头部
# polyfill.io/v3/polyfill.min.js # 修改前
# polyfill.alicdn.com/v3/polyfill.min.js # 修改后
# cdn.polyfill.io/v3/polyfill.min.js # 这样也行
原因应该是polyfill.min.js报错的关系
