### ISSUE TITLE
Yandex图片不能预览不能下载

### ISSUE THREAD

**Issue by woshichenghaibo** [alist-org/alist#4899]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.24

### Driver used / 使用的存储驱动

Yandex

### Describe the bug / 问题描述

嗯，可以正常列出文件目录，但是切换到图片视图的时候，图片都无法显示，点开图片之后也无法显示。切换为download的下载，也无法下载。

Yandex是墙内唯一一个能直接访问的国外网盘了，建议修复

### Reproduction / 复现链接

http://192.168.1.8:5244/Yandex/Mountains.jpg

### Logs / 日志

![Screenshot_2023-08-01-22-56-05-572_mark via](https://github.com/alist-org/alist/assets/80568737/5f62a120-0dbb-47df-ba62-0bbfe3c73c0e)
![Screenshot_2023-08-01-22-56-05-572_mark via](https://github.com/alist-org/alist/assets/80568737/01f32094-d2d0-4554-b0f8-90674a2cf9fe)
![Screenshot_2023-08-01-22-56-17-336_mark via](https://github.com/alist-org/alist/assets/80568737/d152aecc-b5bd-4c46-8da2-4d09baf4c80f)

**Comment by Xhofe** [comment]
下载代理链接不要乱填。
