### ISSUE TITLE
Request failed with status code 413

### ISSUE THREAD

**Issue by Princess-Connect** [alist-org/alist#4905]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.24.0

### Driver used / 使用的存储驱动

WebDav

### Describe the bug / 问题描述

I use an Onedrive account linked with rclone, and I use webdav to connect and create storage. When I upload a file under 100MB, it is successful, but when the file is over 100MB, I encounter the error "Request failed with status code 413". This error occurs on any file uploaded with a size over 100MB.

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/119152652/4294370b-bc93-43c5-9081-e1df4c2407af)

**Comment by Xhofe** [comment]
https://alist.nn.ci/faq/why.html#why-do-i-get-413-http-code-when-i-upload-a-file

https://developers.cloudflare.com/workers/platform/limits/#request-limits
