### ISSUE TITLE
在网格视图中无法查看svg格式的缩略图

### ISSUE THREAD

**Issue by aiXlau** [alist-org/alist#4911]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.24.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

在网格视图中无法查看svg格式的缩略图

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
不支持
