### ISSUE TITLE
百度网盘无法播放视频

### ISSUE THREAD

**Issue by SuperLoserPeco** [alist-org/alist#4912]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [ ] I'm sure I'm using the latest version

### Alist Version / Alist 版本

3.23.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

使用的是PotPlayer的webdav 百度网盘挂载没问题
但是播放视频的时候就会报错

### Reproduction / 复现链接

无

### Logs / 日志

![图片](https://github.com/alist-org/alist/assets/24469740/d379e7f5-e552-442d-8350-31399a71ea60)

**Comment by anwen-anyi** [comment]
1. 你的`WebDav策略`是什么？
2. 是否是`超级会员`？
3. 你的AList搭建在哪里？带宽怎么样？
     - 你的AList搭建应该是在本地家宽，家庭宽带够用了 

## 可以播放
1. 有`超级会员`和`WebDav策略`正确都能播放的 （图一）
2. 有上述提到的内容，在线调用播放器也能播放（需开启Web代理-图二）
![image](https://github.com/alist-org/alist/assets/56105412/bab587c7-c6e8-4bee-80c3-e8ab43418aeb)
![image](https://github.com/alist-org/alist/assets/56105412/00da237a-c9bb-4a68-a533-1c6d224d7665)

**Comment by brainiac19** [comment]
我注意到类似的问题，后发现在我测试的格式中仅mkv不能在web正常播放，且可以调用第三方播放器正常播放。供参考。

**Comment by anwen-anyi** [comment]
> 我注意到类似的问题，后发现在我测试的格式中仅mkv不能在web正常播放，且可以调用第三方播放器正常播放。供参考。

mkv不能播放很大概率是因为编码/格式等问题

**Comment by killyzhou** [comment]
无法播放视频，大概率视频是MKV格式的问题，希望修复，谢谢

**Comment by hfxu9399** [comment]
WebDav策略改成本地代理，下载接口改成非官方就可以了

**Comment by ChricLu** [comment]
> WebDav策略改成本地代理，下载接口改成非官方就可以了

有用！谢谢
