### ISSUE TITLE
3.24版安卓nplayer无法播放阿里云open

### ISSUE THREAD

**Issue by bennywnn** [alist-org/alist#4915]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.24.0

### Driver used / 使用的存储驱动

aliyunopen

### Describe the bug / 问题描述

升级docker版3.24后，安卓nplayer播放阿里云open挂载视频，会先缓冲一下，然后就不再有网络活动的迹象，换reex可以播放，换回3.23版，nplayer也可以播放了

### Reproduction / 复现链接

无需

### Config / 配置

无需

**Comment by Xhofe** [comment]
请提供具体复现步骤与一个复现链接。

**Comment by simear2004** [comment]
我原来用RaiDrive本地挂载，正常播放，升级后也无法播放了，升级之前那个版本可以，但是不记得是哪个版本。。。

**Comment by qiulin6** [comment]
同样情况，alist3.24 版本，nplayer缓冲严重，经常不能播放

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/compare/v3.23.0...v3.24.0

3.24.0中并没有对阿里云盘Open做特殊的修改，且使用302的方式观看视频时是直接与阿里云盘进行通信并不经过alist。
我无法复现任何不能播放的情况。

**Comment by qiulin6** [comment]
我更新3.24后，同时阿里云盘app也更了，其中在阿里云盘APP中删除了一个设备，有samsing三星字样的设备账号，然后就出现了速度下降，缓冲严重情况，视频打不开情况。这个samsung设备账号是什么？？我记得以前也出现过这样情况，删除设备列表中的一个samsung设备，然后alist就没有速度了，后来不记得在哪里看到过恢复这个samsung设备方法，然后又可满速了。早几天又手贱删了这个设备（当然这不是我的设备），然后alist又看不了视频了。哪位高人教教如何恢复这个samsung设备账号？？同时请教这是什么原因？？？

**Comment by anwen-anyi** [comment]
> 我更新3.24后，同时阿里云盘app也更了，其中在阿里云盘APP中删除了一个设备，有samsing三星字样的设备账号，然后就出现了速度下降，缓冲严重情况，视频打不开情况。这个samsung设备账号是什么？？我记得以前也出现过这样情况，删除设备列表中的一个samsung设备，然后alist就没有速度了，后来不记得在哪里看到过恢复这个samsung设备方法，然后又可满速了。早几天又手贱删了这个设备（当然这不是我的设备），然后alist又看不了视频了。哪位高人教教如何恢复这个samsung设备账号？？同时请教这是什么原因？？？

你这是属于以前版本的了，而且现在这种方式已经不维护了

**Comment by SeanHeuc** [comment]
近期本来阿里云就不稳定  速度时快时慢  建议你控制变量 重复实验三次看下
我本地测试的时候也是一下快一下慢

**Comment by shanhai2333** [comment]
登陆过移动端最新的app(v4.9.0)就不行了，

**Comment by jarofcolor** [comment]
同样的问题，升级了最新阿里云盘就出现了，挂载后，有的视频能播放，有的一点速度没有，不知道怎么回事。

**Comment by paranoiagu** [comment]
确实最近出现了问题。
我是用xiaoya的，奇怪的是，用xiaoya的网页，播放视频没问题，但是用webdav挂到potplayer，或者用tvbox就不行，很卡很卡，有些视频不快进，是能看的，有些根本没有速度。

**Comment by qiulin6** [comment]
从网上得知关闭ipv6，确实可以满速了。

**Comment by jarofcolor** [comment]
跟ipv6确实有关，我用dns changer改了手机ipv6的dns，就可以跑满了。

**Comment by paranoiagu** [comment]
> 

改成什么 dns？

**Comment by qiulin6** [comment]
现在正常了。
早两天反馈给阿里，是否ipv6出了问题，客服回答说把情况交技术部门。今天重新打开ipv6，播放都正常了。
