### ISSUE TITLE
关于nginx文件大小限制触发的错误

### ISSUE THREAD

**Issue by Sincejunly** [alist-org/alist#4916]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

目前最新的版本

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

对于nginx配置
```
    keepalive_timeout 0;
    send_timeout 0;
```
有错误：
`System error: TypeError: Failed to fetch dynamically imported module: xxxxxxxxxxx/AList/assets/Layout.9787268b.js`

起因是我要上传大文件，我使用nginx反代，一开始我以为是网络环境波动，但是当我删除后立马就好。

完整配置：
```
  location /AList/ {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_redirect off;

    proxy_pass http://127.0.0.1:5244/AList/;
    # the max size of file to upload
    client_max_body_size 0;
    keepalive_timeout 0;
    send_timeout 0;
  }
```
注：   
```
 keepalive_timeout 0;
    send_timeout 0;
```
放在子路径代理时只是有概率出现这个错误，放在根路径时一定有这个错误。

### Reproduction / 复现链接

。

### Config / 配置

```
{
  "force": false,
  "site_url": "xxxxxx/AList/",
  "cdn": "",
  "jwt_secret": "xxxxx",
  "token_expires_in": 48,
  "database": {
    "type": "mysql",
    "host": "xxxxx",
    "port": xxxxx,
    "user": "xxxxx",
    "password": "xxxxx",
    "name": "xxxxx",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}
```

### Logs / 日志

日志无错误。

**Comment by Sincejunly** [comment]
还需要我提供什么信息？我用的就是模版啊

**Comment by Xhofe** [comment]
![image](https://github.com/alist-org/alist/assets/36558727/4411da02-9e64-4189-88c7-d0bfd6ade278)

**Comment by Sincejunly** [comment]
> ![image](https://user-images.githubusercontent.com/36558727/258074062-4411da02-9e64-4189-88c7-d0bfd6ade278.png)

https://office.homura.top:82/AList/ 看看吧

**Comment by Xhofe** [comment]
供参考： https://github.com/xhlwill/blog/issues/17

这不属于AList的问题。

**Comment by Sincejunly** [comment]
> 供参考： [xhlwill/blog#17](https://github.com/xhlwill/blog/issues/17)
> 
> 这不属于AList的问题。
有点难顶，nginx日志没信息，
```
cat /var/log/nginx/error.log | grep "index.af742395.js"
find / -type d -name "proxy_temp"
```
啥都找不到
