### ISSUE TITLE
希望管理员账户能够查看特定用户组的浏览历史和每个文件观看时间和时长等

### ISSUE THREAD

**Issue by tingyue-wu** [alist-org/alist#4928]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望管理员账户能够查看特定用户组(注册用户进行分组)的浏览历史和每个文件观看时间和时长，最好对勾选的特定组注册用户生成一个在线统计表。
这个功能方便了解班级学生是否观看学习资料、观看时长，还有不同班级看学习视频的完成率。

**Comment by anwen-anyi** [comment]
过分了昂........

AList的About是
```txt
A file list/WebDAV program that supports multiple storages, powered by Gin and Solidjs. 
一个支持多存储的文件列表/WebDAV程序，使用 Gin 和 Solidjs。
```
