### ISSUE TITLE
挂载 OneDrive 后下载文件并非直链的问题

### ISSUE THREAD

**Issue by roywangdev** [alist-org/alist#4929]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.24.0

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

在挂载 OneDrive （未打开SharePoint）后，通过在文件目录中，右键点击选择下载后并非 xxxx-my.sharepoint.com 下载地址，而是 Alist 站点的下载地址，其好像通过了 Alist  反代然后再传输给用户。

即获取的是非直链地址，而通过点击文件，打开页面详情页面，再点击下载才可正确获得文件 onedrive 直链。

### Reproduction / 复现链接

因为隐私问题，OneDrive仅管理员才可访问，如您需要可以通过邮件联系

**Comment by Xhofe** [comment]
i@nn.ci

**Comment by roywangdev** [comment]
> [i@nn.ci](mailto:i@nn.ci)

具体复现方式以及复现链接已经发送到了您的邮箱，请您查收。

**Comment by Xhofe** [comment]
#2149

**Comment by roywangdev** [comment]
问题已经解决，感谢
