### ISSUE TITLE
请求加入V3版本的API文档

### ISSUE THREAD

**Issue by wiketool** [alist-org/alist#4933]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如果有API文档的话，可以加速基于Alist周边的工具的兴起，而不用要到代码和控制台里找出请求的参数和地址

**Comment by Kuingsmile** [comment]
已整理好API文档并在文档仓库提交了PR  https://github.com/alist-org/docs/pull/258 @xhofe
