### ISSUE TITLE
中国移动云盘无法在线播放，但是能下载

### ISSUE THREAD

**Issue by j2rong4cn** [alist-org/alist#4934]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.24.0

### Driver used / 使用的存储驱动

中国移动云盘

### Describe the bug / 问题描述

添加中国移动云盘之后无法网页播放，但是能下载，webdav也可以播放、下载

### Reproduction / 复现链接

链接：https://caiyun.139.com/m/i?135CmW2qwc9GE
提取码：emuP 
复制本段信息，打开最新版「中国移动云盘APP」即可获取，超大空间随心存，移动用户免流量。

### Config / 配置

302定向到云盘

**Comment by BnqDzj** [comment]
因为中国移动云盘的下载链接没法根据文件返回对应状态码（视频文件状态码应返回206但返回200）所以网页没法播放（Artplayer会一直重新连接），中国移动云盘为此将视频转码成m3u8并推出了新的API用于获取视频的m3u8地址

个人云
URL
https://yun.139.com/orchestration/personalCloud/content/v1.2/getFlvOnlineAddr

Body
{"getFlvOnlineAddrReq":{"contentID":"资源ID","commonAccountInfo":{"account":"账号","accountType":1}}}

Response
{"success":true,"code":"0","message":"OK","data":{"result":{"resultCode":"0","resultDesc":null},"getFlvOnlineAddrRes":{"presentURL":"presentURL"}}}

取Response里的presentURL即可

家庭云
https://yun.139.com/orchestration/familyCloud-rebuild/content/v1.0/getFlvOnlineAddr

Body
{"contentID":"资源ID","cloudID":"cloudID","path":"全路径","catalogType":3,"commonAccountInfo":{"account":"账号","accountType":1}}

Response
{"success":true,"code":"0","message":"OK","data":{"result":{"resultCode":"0","resultDesc":"SUCCESS"},"presentURL":"presentURL","presentLURL":null,"presentHURL":null,"duration":1457323}}

也是取Response里的presentURL即可
家庭云的全路径是 https://yun.139.com/orchestration/familyCloud-rebuild/content/v1.0/queryContentList 中的data中的path

**Comment by SeanHeuc** [comment]
唯一的办法是通过在proxy.go里面加入逻辑：监测到Accept-Ranges: bytes 之后将http statuscode改成206， 但这应该是移动云盘他们服务器改的，他们没有遵守http标准，而且这也意味着移动云盘不能302而是使用代理

**Comment by xhofe** [comment]
很奇怪

> 链接: https://caiyun.139.com/m/i?1R5BUx5CKRIhz  提取码:8rut  复制内容打开中国移动云盘手机APP，操作更方便哦

这个视频的响应也是没有遵守http标准的，但是可以播放。不知道为什么

**Comment by SeanHeuc** [comment]
> 很奇怪
> 
> > 链接: https://caiyun.139.com/m/i?1R5BUx5CKRIhz  提取码:8rut  复制内容打开中国移动云盘手机APP，操作更方便哦
> 
> 这个视频的响应也是没有遵守http标准的，但是可以播放。不知道为什么

从头播放是没事的，主要是加了range header, 大部分app都会按照标准匹配206， 但是移动这边除了200返回码错了，剩下都是对的，这样app以为自己拿到了从头开始的流（因为range header发过去，返回了200说明此文件不支持range header），就肯定乱了

**Comment by foxxorcat** [comment]
这种问题应该直接向移动云盘的客服反馈，不按照标准的话很多地方都要出问题，比如只能单线程下载、下载慢、下载无法恢复等等，随便找个借口就说了。

**Comment by 253551464** [comment]
> 很奇怪
> 
> > 链接: https://caiyun.139.com/m/i?1R5BUx5CKRIhz  提取码:8rut  复制内容打开中国移动云盘手机APP，操作更方便哦
> 
> 这个视频的响应也是没有遵守http标准的，但是可以播放。不知道为什么

使用[Crypt(加密)](https://alist.nn.ci/zh/guide/drivers/Crypt.html)驱动将存储地址设置为中国移动云盘的挂载目录，还是无法网页播放（第一个请求206之后416状态码），但可以下载。使用[alist-encrypt](https://github.com/traceless/alist-encrypt)代理返回206状态可以正常播放

**Comment by SeanHeuc** [comment]
> > 很奇怪
> > > 链接: https://caiyun.139.com/m/i?1R5BUx5CKRIhz  提取码:8rut  复制内容打开中国移动云盘手机APP，操作更方便哦
> > 
> > 
> > 这个视频的响应也是没有遵守http标准的，但是可以播放。不知道为什么
> 
> 使用[Crypt(加密)](https://alist.nn.ci/zh/guide/drivers/Crypt.html)驱动将存储地址设置为中国移动云盘的挂载目录，还是无法网页播放（第一个请求206之后416状态码），但可以下载。使用[alist-encrypt](https://github.com/traceless/alist-encrypt)代理返回206状态可以正常播放

我上面解释很多遍了， 在有range header的时候会出错，crypt尤其依赖这个header。 精力转到如果让他们改对http status code返回值吧

**Comment by 253551464** [comment]
> > > 很奇怪
> > > > 链接: https://caiyun.139.com/m/i?1R5BUx5CKRIhz  提取码:8rut  复制内容打开中国移动云盘手机APP，操作更方便哦
> > > 
> > > 
> > > 这个视频的响应也是没有遵守http标准的，但是可以播放。不知道为什么
> > 
> > 
> > 使用[Crypt(加密)](https://alist.nn.ci/zh/guide/drivers/Crypt.html)驱动将存储地址设置为中国移动云盘的挂载目录，还是无法网页播放（第一个请求206之后416状态码），但可以下载。使用[alist-encrypt](https://github.com/traceless/alist-encrypt)代理返回206状态可以正常播放
> 
> 我上面解释很多遍了， 在有range header的时候会出错，crypt和在线视频播放尤其依赖这个header。 精力转到如何让他们改对http status code返回值吧。 alist-encyrpt 本身就相当于劫持客户端，相当于本地必须跑一个那个客户端才行，alist如果强制改返回http status code，移动云盘就只能支持本地代理了，无法支持302

中国移动云是可以通过请求头content-range返回相应的数据的，所以[alist/crypt
/driver.go:275](https://github.com/alist-org/alist/blob/a797494aa3c44e3ca2894c32858dc221997ccb44/drivers/crypt/driver.go#L275C50-L275C50)这里我觉得改为： response.StatusCode == http.StatusOK && response的响应头中没有content-range 
我试过

**Comment by SeanHeuc** [comment]
> > > > 很奇怪
> > > > > 链接: https://caiyun.139.com/m/i?1R5BUx5CKRIhz  提取码:8rut  复制内容打开中国移动云盘手机APP，操作更方便哦
> > > > 
> > > > 
> > > > 这个视频的响应也是没有遵守http标准的，但是可以播放。不知道为什么
> > > 
> > > 
> > > 使用[Crypt(加密)](https://alist.nn.ci/zh/guide/drivers/Crypt.html)驱动将存储地址设置为中国移动云盘的挂载目录，还是无法网页播放（第一个请求206之后416状态码），但可以下载。使用[alist-encrypt](https://github.com/traceless/alist-encrypt)代理返回206状态可以正常播放
> > 
> > 
> > 我上面解释很多遍了， 在有range header的时候会出错，crypt和在线视频播放尤其依赖这个header。 精力转到如何让他们改对http status code返回值吧。 alist-encyrpt 本身就相当于劫持客户端，相当于本地必须跑一个那个客户端才行，alist如果强制改返回http status code，移动云盘就只能支持本地代理了，无法支持302
> 
> 中国移动云是可以通过请求头range返回相应的数据的，所以[alist/crypt /driver.go:275](https://github.com/alist-org/alist/blob/a797494aa3c44e3ca2894c32858dc221997ccb44/drivers/crypt/driver.go#L275C50-L275C50)这里我觉得改为： response.StatusCode == http.StatusOK && response的响应头中没有content-range

这样改只能让crypt兼容移动云盘的这个错误返回，其他使用移动云盘的方法一样会有错误。 这不是http标准，谁不按照标准应该谁来改

**Comment by 253551464** [comment]
> > > > > 很奇怪
> > > > > > 链接: https://caiyun.139.com/m/i?1R5BUx5CKRIhz  提取码:8rut  复制内容打开中国移动云盘手机APP，操作更方便哦
> > > > > 
> > > > > 
> > > > > 这个视频的响应也是没有遵守http标准的，但是可以播放。不知道为什么
> > > > 
> > > > 
> > > > 使用[Crypt(加密)](https://alist.nn.ci/zh/guide/drivers/Crypt.html)驱动将存储地址设置为中国移动云盘的挂载目录，还是无法网页播放（第一个请求206之后416状态码），但可以下载。使用[alist-encrypt](https://github.com/traceless/alist-encrypt)代理返回206状态可以正常播放
> > > 
> > > 
> > > 我上面解释很多遍了， 在有range header的时候会出错，crypt和在线视频播放尤其依赖这个header。 精力转到如何让他们改对http status code返回值吧。 alist-encyrpt 本身就相当于劫持客户端，相当于本地必须跑一个那个客户端才行，alist如果强制改返回http status code，移动云盘就只能支持本地代理了，无法支持302
> > 
> > 
> > 中国移动云是可以通过请求头range返回相应的数据的，所以[alist/crypt /driver.go:275](https://github.com/alist-org/alist/blob/a797494aa3c44e3ca2894c32858dc221997ccb44/drivers/crypt/driver.go#L275C50-L275C50)这里我觉得改为： response.StatusCode == http.StatusOK && response的响应头中没有content-range
> 
> 这样改只能让crypt兼容移动云盘的这个错误返回，其他使用移动云盘的方法一样会有错误。 这不是http标准，谁不按照标准应该谁来改

就算不是单纯为了兼容中国移动云盘而修改，响应头有content-range就可以直接返回了不需要用net.GetRangedHttpReader处理。http标准的问题已经向中国移动云盘反馈了，不知道会不会处理

**Comment by SeanHeuc** [comment]
> 

有一种返回叫做multipart，header不是那么简单的处理，看这里：https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206
我在写crypt和给alist做proxy的简化和标准化时参阅了很多文档代码，包括http标准，rclone，aws-sdk实现，目前的实现是符合标准的，也是各大厂商的实现方法。

**Comment by happyubiquity** [comment]
这次兼容了，那以后都得专门兼容移动云盘，得逼着移动云盘改，所以这次不能兼容移动云盘

**Comment by SeanHeuc** [comment]
> > > 
> > 
> > 
> > 有一种返回叫做multipart，header不是那么简单的处理，看这里：https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206 我在写crypt和给alist做proxy的简化和标准化时参阅了很多文档代码，包括http标准，rclone，aws-sdk实现，目前的实现是符合标准的，也是各大厂商的实现方法。
> 
> 我不是专业的，相应头中有Content-Range就不用net.GetRangedHttpReader处理，因为服务器已经按照请求头Range返回对应数据了。 让Crypt兼容 容易，让中国移动云盘修改 难，希望下个版本Crypt能先兼容一下中国移动云盘

”相应头中有Content-Range就不用net.GetRangedHttpReader处理“，这个不是的，拥有Content-Range也可以是完整文件。200返回码本身就是错误的了，你不能因为移动云这边是由固定这个错误就加一个可能影响其他符合请求的逻辑。
举个例子，某网盘支持range，使用crypt加密，因为该网盘内部存储服务升级，某些服务器不支持range request了，添加了header  Content-Range: bytes 0-7999/8000，也就是完整文件，那crypt按照你的hack逻辑又处理错了

**Comment by SeanHeuc** [comment]
这样吧，crypt可以再加一个返回Content-Range的判断，如果符合请求的range，那就按照服务器支持range来处理

**Comment by 253551464** [comment]
> 这次兼容了，那以后都得专门兼容移动云盘，得逼着移动云盘改，所以这次不能兼容移动云盘

中国移动云盘能根据请求头Range返回对应的数据，不过没有按照http标准返回206状态码，不需要net.GetRangedHttpReader。而无法根据请求头Range返回数据的[alist/crypt /driver.go:268](https://github.com/alist-org/alist/blob/a797494aa3c44e3ca2894c32858dc221997ccb44/drivers/crypt/driver.go#L268C8-L268C8):response，才应该用net.GetRangedHttpReader读取请求头Range对应的数据

**Comment by 253551464** [comment]
> 这样吧，crypt可以再加一个返回Content-Range的判断，如果符合请求的range，那就按照服务器支持range来处理

能者多劳👍

**Comment by haohao232323** [comment]
菜鸡看了半天讨论，还是没看懂怎么办，截至现在问题仍然还在。

**Comment by htyjswf** [comment]
> 菜鸡看了半天讨论，还是没看懂怎么办，截至现在问题仍然还在。

我也一样，你们说的太高端了

**Comment by j2rong4cn** [comment]
> > 菜鸡看了半天讨论，还是没看懂怎么办，截至现在问题仍然还在。
> 
> 我也一样，你们说的太高端了

别用网页播放，Windows用rclone挂载到本地是可以播放的，安卓的话用nplayer

**Comment by htyjswf** [comment]
> > > 菜鸡看了半天讨论，还是没看懂怎么办，截至现在问题仍然还在。
> > 
> > 
> > 我也一样，你们说的太高端了
> 
> 别用网页播放，Windows用rclone挂载到本地是可以播放的，安卓的话用nplayer

我用的infuse，主要是有的文件上传进移动云盘，网页移动云盘看着缩略图也能正常显示，用infuse也能正常播，但是有的视频就说播着播着就转圈了，无法往后拖进度条，彻底卡死。即使去云盘APP把这个视频下载下来，也还是无法播放（下载后，本地播到那个损坏的时间点就同样卡死崩溃）。这个保不准哪个视频出现，所以现在我一般都是不超过10G的小视频传云盘里面，几十G的大的原盘之类的还是阿里或者本地。
还有一点就说网页云盘里，正常视频显示缩略图，有的视频就没有缩略图（不是我没等待生成缩略图），没有缩略图的视频有的用infuse能播，有的不能播，谜一样。
我所知道的和谐的视频的其中一种方式就是没缩略图
![微信截图_20240124171151](https://github.com/alist-org/alist/assets/29861780/b75af593-8aa7-42cd-99bc-d892393410b1)

**Comment by includezlh** [comment]
笑得虽然你们说的很对但是完全看不懂，我只知道到现在这个问题依然存在

**Comment by 814747889** [comment]
这个问题存在好像是个无解，除非移动200改206,移动貌似没有想解决这个问题

**Comment by 814747889** [comment]
> > 
> 
> 有一种返回叫做multipart，header不是那么简单的处理，看这里：https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206 我在写crypt和给alist做proxy的简化和标准化时参阅了很多文档代码，包括http标准，rclone，aws-sdk实现，目前的实现是符合标准的，也是各大厂商的实现方法。
是否可以尝试移动的m3u8做为一个备用方案，比如在列表中加入一个m3u8的类型

**Comment by 814747889** [comment]
> > > > 
> > > 
> > > 
> > > 返回一种称为多部分，标头不是那么简单的处理，看这里：https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206我在写crypt和给alist做proxy的简化并且标准化时看到了很多文档代码，包括http标准，rclone，aws-sdk实现，目前的实现是符合标准的，也是各大厂商的实现方法。
> > 
> > 
> > 我修改不是专业的，相应的头有Content-Range就不用net.GetRangedHttpReader处理，因为服务器已经按照请求头Range让返回对应数据了。Crypt兼容很容易，让中国移动云盘难，希望下一个版本Crypt能先兼容一下中国移动云盘
> 
> ”相应头有Content-Range就不用net.GetRangedHttpReader处理“，这个不是的，拥有Content-Range也可以是完整文件。200返回码本身就是错误的了，你因为不能移动云核心是由这个固定的错误就加一个可能影响其他符合请求的逻辑。 举个例子，某网盘支持range，使用crypt加密，因为该网盘内部存储服务升级，某些服务器不支持range请求了，添加了header Content-Range : bytes 0-7999/8000，清晰完整文件，那crypt按照你的hack逻辑又处理错了

是否可以尝试移动的m3u8
做一个备用方案，比如在列表中加入一个m3u8的类型

**Comment by 814747889** [comment]
https://yun.139.com/orchestration/personalCloud/content/v1.0/getContentInfo
Body
{"getFlvOnlineAddrReq":{"contentID":"资源ID","commonAccountInfo":{"account":"账号","accountType":1}}}
