### ISSUE TITLE
某些命名方式类似于路径的文件名导致文件无法访问和重命名

### ISSUE THREAD

**Issue by cscwxu** [alist-org/alist#4935]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.24.0

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

1. 如图：
<img width="954" alt="image" src="https://github.com/alist-org/alist/assets/57207775/69740e66-5f73-4783-b29c-9120445e7a8b">
2.对该文件重命名：
<img width="1433" alt="image" src="https://github.com/alist-org/alist/assets/57207775/1f9f7f08-935c-4b13-92fb-567baf168bb0">

### Reproduction / 复现链接

如上

### Config / 配置

<img width="1218" alt="image" src="https://github.com/alist-org/alist/assets/57207775/ea0e63c4-b856-4fda-a7ba-21dc8766d6a2">

### Logs / 日志

<img width="1433" alt="image" src="https://github.com/alist-org/alist/assets/57207775/1f9f7f08-935c-4b13-92fb-567baf168bb0">

**Comment by xhofe** [comment]
对不起 我们不支持非法文件名。
