### ISSUE TITLE
Modified date is changed when file is uploaded to AList

### ISSUE THREAD

**Issue by nZeus** [alist-org/alist#4938]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.24.0

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

Every file that I upload to AList, gets a new `Modified` timestamp. It doesn't matter if I'm uploading via web interface or WebDav client, the timestamp is changed.

<img width="1066" alt="image" src="https://github.com/alist-org/alist/assets/2727326/988734af-439d-4fb6-912e-d462cf25105e">

Original file:
<img width="580" alt="image" src="https://github.com/alist-org/alist/assets/2727326/ba13f17e-e235-444a-b861-3c73361e9fb7">

It's important for me to preserve the original date 🙏 

### Reproduction / 复现链接

?

### Config / 配置

TrueNAS Chart

**Comment by SeanHeuc** [comment]
this will be addressed soon

**Comment by nZeus** [comment]
Hi @SeanHeuc ,

Thank you very much!
Looking forward to it!

**Comment by SeanHeuc** [comment]
if u use webdav to upload, "X-OC-Mtime" and "X-OC-Ctime" is supported to sepcify updateTime and createTime.  I will push MR to rclone to support these 2 headers natively later. (for now, u can use "fastmail" in rclone as a temporary solution)
if u use web upload, there's no way to perserve the 2 dates.
the recommended way for now is to mount local disk into alist, then use "copy" function to copy from local disk to remote, and if remote  storage supports, the 2 dates will be applied during upload. (i tested baidu_netdisk and aliyun_open)

**Comment by xhofe** [comment]
Uploading on the web page also supports `lastModified` now.

**Comment by nZeus** [comment]
Could you please release the changes? 🙏

**Comment by xhofe** [comment]
There are still some issues to be fixed, and a new release will be shipped after the fix.

**Comment by SeanHeuc** [comment]
> > the recommended way for now is to mount local disk into alist, then use "copy" function to copy from local disk to remote, and if remote storage supports, the 2 dates will be applied during upload. (i tested baidu_netdisk and aliyun_open)
> 
> @SeanHeuc Please tell me how to mount AList locally? Via rclone? Can you share the specific command?
> 
> I used Synology's File Station to mount the AList and put the files directly into it, but the problem still recurred.

I meant mount a local disk into alist, then use alist copy function to copy from local disk to cloud remote(aliyun).
mount alist webdav into other system (synology,linux...) will not work.

**Comment by SeanHeuc** [comment]
> > I meant mount a local disk into alist, then use alist copy function to copy from local disk to cloud remote(aliyun). mount alist webdav into other system (synology,linux...) will not work.
> 
> Thanks for the reply. @SeanHeuc
> 
> When I use local mount into alist and copy the file to alipan, the File Modified Date still changes to the date at the time of sync, not the original date. Attached are diagrams of the operation steps. Let's see if there's any problem.
> 
> @xhofe @SeanHeuc
> 
> [ ![IMG_8674](https://private-user-images.githubusercontent.com/4717125/293337764-d3213b1a-8895-4389-ab89-927e9eb14224.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjY4NzAsIm5iZiI6MTcwMzg2NjU3MCwicGF0aCI6Ii80NzE3MTI1LzI5MzMzNzc2NC1kMzIxM2IxYS04ODk1LTQzODktYWI4OS05MjdlOWViMTQyMjQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE2MTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMGYzOThhODk0OGUyYzc0ODI5YTU1YTYwMzJhNGMwNmY3ZDg5NWM3NjBlMGIxODI1MWZmZGZlODhlMDAzYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xel8zbp0ETp5gy5UqcLBV5WGl8x3P5EJ2MI8yAY2pso) ![IMG_8675](https://private-user-images.githubusercontent.com/4717125/293337790-0ea2c67c-dfb5-4533-8537-f7a446c187d0.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjY4NzAsIm5iZiI6MTcwMzg2NjU3MCwicGF0aCI6Ii80NzE3MTI1LzI5MzMzNzc5MC0wZWEyYzY3Yy1kZmI1LTQ1MzMtODUzNy1mN2E0NDZjMTg3ZDAuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE2MTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYTViZWI0MTgyODQ2NjZmNjc1YWQ0OWYwNDM4YWQzY2EyZDcyMDMyZTg4ZmFkY2QzYjdmNmJiYWU2MTQ5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OQFTF7lgkKlYRaWCnwpU2T8XofIDyuLHtPGJIVaTHxM) ![IMG_8673](https://private-user-images.githubusercontent.com/4717125/293337797-176d24ff-4a51-4995-b1aa-80da1ff39b10.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjY4NzAsIm5iZiI6MTcwMzg2NjU3MCwicGF0aCI6Ii80NzE3MTI1LzI5MzMzNzc5Ny0xNzZkMjRmZi00YTUxLTQ5OTUtYjFhYS04MGRhMWZmMzliMTAuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE2MTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNDA0ODk5MDIzMWJhZTY0YjFmMTUzNzg2OTFjOWVjMWFkYWIzNGJlMWUzZDAyYjM4OWU4ODU4N2JkMTllOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8c1ModGb2Vx3KO7JiGiC-ZV_AVrLesOd17u5WQCHISA) ![IMG_8672](https://private-user-images.githubusercontent.com/4717125/293337800-a80377fa-3ccd-44c8-9ca9-10092f744c68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjY4NzAsIm5iZiI6MTcwMzg2NjU3MCwicGF0aCI6Ii80NzE3MTI1LzI5MzMzNzgwMC1hODAzNzdmYS0zY2NkLTQ0YzgtOWNhOS0xMDA5MmY3NDRjNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTYxNjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDE5YThkMDY1NmU1OTM2MTk0M2Q2YWIzY2Q2OGMzMzE3NjUwZDVkMTAzYzZiNTcwZTBmYjAyYTZlNDZjMjAxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6v8Ti7bSGt9Kfs9GEHe4Z43XOCshF0mmYizJkVdhlo0) ](url)

from the screenshot i guess you are running alist on an ARM decive?  my previous test is done on Mac and windows only.
-  alist need to use go sdk to get the file modification & create time, different OS have diff implementation, the GO SDK support is not very good/clear on this
-  the remote side, aliyun/baiduCloud need to use the timestamp alist put in the request. not all cloud providers support them, and their support can change over time 

you can:
-  clone the soure, add some log output for this time parameters
-  build your own binary. deploy and check the log.
And you can diagnose by yourself.  Im busy these few months, I propabably will check this when i am back. I actually use the upload function a lot, but im only checking the file size &name in backup for now. it will be nice to have timestamp to do incremental sync.
