### ISSUE TITLE
添加阿里云盘Open 失败，报错Failed init storage: Post "https://openapi.aliyundrive.com/ad ...

### ISSUE THREAD

**Issue by xiaodatao2007** [alist-org/alist#4942]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.24.0

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

alist-linux-musl-arm64.zip

在android 设备运行，./alist start 后， 在web端登录，添国阿里云盘open失败，token 100％刚刚是正常的。

Failed init storage: Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [**1]:53: read udp [**1]:49761->[**1]:53: read: connection refused

### Reproduction / 复现链接

...

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "gdWnMtFgY8x4ttQG",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "/data/local/tmp/alist4/data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "/data/local/tmp/alist4/data/temp",
  "bleve_dir": "/data/local/tmp/alist4/data/bleve",
  "log": {
    "enable": true,
    "name": "/data/local/tmp/alist4/data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

### Logs / 日志

[33mWARN[0m[2023-08-07 02:56:36] not enable search                            
[36mINFO[0m[2023-08-07 02:56:36] using aria2 version: 1.19.0                  
[GIN] 2023/08/07 - 02:56:53 | 200 |     567.875µs |   168.168.10.55 | GET      "/@manage/storages/edit/1"
[GIN] 2023/08/07 - 02:56:53 | 200 |    8.891459ms |   168.168.10.55 | GET      "/api/public/settings"
[GIN] 2023/08/07 - 02:56:53 | 200 |    3.160792ms |   168.168.10.55 | GET      "/api/me"
[GIN] 2023/08/07 - 02:57:03 | 200 |    7.354959ms |   168.168.10.55 | POST     "/api/auth/login"
[GIN] 2023/08/07 - 02:57:03 | 200 |     620.959µs |   168.168.10.55 | GET      "/api/me"
[31mERRO[0m[2023-08-07 02:57:03] record not found                             
[GIN] 2023/08/07 - 02:57:03 | 200 |    2.801167ms |   168.168.10.55 | GET      "/api/admin/storage/get?id=1"
[GIN] 2023/08/07 - 02:57:13 | 200 |    1.311625ms |   168.168.10.55 | GET      "/assets/Users.976b87a4.js"
[GIN] 2023/08/07 - 02:57:13 | 200 |    1.404583ms |   168.168.10.55 | GET      "/assets/Wether.652f578d.js"
[GIN] 2023/08/07 - 02:57:13 | 200 |       1.701ms |   168.168.10.55 | GET      "/api/admin/user/list"
[GIN] 2023/08/07 - 02:57:16 | 200 |         483µs |   168.168.10.55 | GET      "/assets/AddOrEdit.93290b34.js"
[GIN] 2023/08/07 - 02:57:16 | 200 |    3.228751ms |   168.168.10.55 | GET      "/api/admin/user/get?id=1"
[GIN] 2023/08/07 - 02:57:23 | 200 |    6.553459ms |   168.168.10.55 | POST     "/api/admin/user/update"
[GIN] 2023/08/07 - 02:57:23 | 200 |    2.919875ms |   168.168.10.55 | GET      "/api/admin/user/list"
[GIN] 2023/08/07 - 02:57:30 | 200 |     940.041µs |   168.168.10.55 | GET      "/api/admin/driver/names"
[GIN] 2023/08/07 - 02:57:30 | 200 |    6.866417ms |   168.168.10.55 | GET      "/api/admin/storage/list"
[GIN] 2023/08/07 - 02:57:33 | 200 |    3.393542ms |   168.168.10.55 | GET      "/api/admin/user/list"
[GIN] 2023/08/07 - 02:58:03 | 200 |      621.25µs |   168.168.10.55 | GET      "/api/admin/driver/names"
[GIN] 2023/08/07 - 02:58:03 | 200 |    2.203833ms |   168.168.10.55 | GET      "/api/admin/storage/list"
[GIN] 2023/08/07 - 02:58:05 | 200 |   20.571543ms |   168.168.10.55 | GET      "/api/admin/driver/list"
[31mERRO[0m[2023-08-07 02:58:44] [aliyundrive_open] request error:            
[31mERRO[0m[2023-08-07 02:58:44] failed init storage but storage is already created: failed init storage: Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:49893->[::1]:53: read: connection refused 
[GIN] 2023/08/07 - 02:58:44 | 200 |  617.717229ms |   168.168.10.55 | POST     "/api/admin/storage/create"
[GIN] 2023/08/07 - 02:58:44 | 200 |    5.788126ms |   168.168.10.55 | GET      "/api/admin/storage/get?id=1"
[GIN] 2023/08/07 - 02:58:44 | 200 |     3.43875ms |   168.168.10.55 | GET      "/api/admin/driver/info?driver=AliyundriveOpen"
[31mERRO[0m[2023-08-07 02:58:54] [aliyundrive_open] request error:            
[31mERRO[0m[2023-08-07 02:58:54] failed init storage: Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp: lookup openapi.aliyundrive.com on [::1]:53: read udp [::1]:49761->[::1]:53: read: connection refused 
[GIN] 2023/08/07 - 02:58:54 | 200 |  669.726651ms |   168.168.10.55 | POST     "/api/admin/storage/update"

**Comment by xiaodatao2007** [comment]
需要胁助，怎么查看解决办法？
是重复问题吗？
方便的话，给个链接，非常感谢！
@xhofe

**Comment by mengguyi** [comment]
> 需要胁助，怎么查看解决办法？ 是重复问题吗？ 方便的话，给个链接，非常感谢！ @xhofe

网络问题自行解决。第三个选项白勾了
