### ISSUE TITLE
dns解析等网络错误希望增加重试容错机制

### ISSUE THREAD

**Issue by whatagoodboy** [alist-org/alist#4946]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

作者您好，非常抱歉，我已阅读文档关于此类问题不得提出issue，也看到了很多关闭的issue提到此情况，但确实希望能够增加相关机制来容错网络问题，以增加alist的适应性和健壮性。

我也尝试用docker compose 来控制启动顺序，但发现docker仅仅是控制启动，并不会等到服务可用时再启动下一个容器，仍然会出现先于dns启动的情况。我在文档中也没有搜到关于alist自身延迟启动服务的相关方法。

希望：
1.能够增加自动重试机制
2.或者docker容器启动时遇到网络错误能够中断容器运行，这样也可以使用docker自身的always restart机制来实现重试。
3.或alist能控制自身启动延时

谢谢！

**Comment by anwen-anyi** [comment]
alist能控制自身启动延时 
 - 已经有了 应该是这个 https://alist.nn.ci/zh/config/configuration.html#delayed-start

**Comment by whatagoodboy** [comment]
> 

收到，是我看漏了，感谢指导！
