### ISSUE TITLE
又拍云开启时间戳防盗链后无法正常读取文件

### ISSUE THREAD

**Issue by h1k4r** [alist-org/alist#4948]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.24.0

### Driver used / 使用的存储驱动

Upyun

### Describe the bug / 问题描述

又拍云开启时间戳防盗链后，文件内的内容不能够被读取/下载/查看，但上传文件相关（如新建文件或文件夹）是可以正常使用的。

### Reproduction / 复现链接

https://cloud.awa.ink/Static%20[%20:Upyun%20]

### Config / 配置

相关问题与配置文件无关。

**Comment by Kagurain** [comment]
似乎这更应该被提交到功能添加的分类去，因为 AList 并没有支持添加防盗链密钥。

**Comment by xhofe** [comment]
这应该已经在#5115 中被修复
