### ISSUE TITLE
storage命令行执行disabled操作后前端页面列表仍显示的bug

### ISSUE THREAD

**Issue by troray** [alist-org/alist#4961]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

当使用storage disable禁用某个驱动时，在alist后台查看状态也是disable状态，但前端网页的列表中是可见状态的,并且是可访问的。

我不知道命令行操作disable在设计之初是仅跳过该驱动的加载，还是能达到和后台禁用一样的效果。
如果是仅跳过，那么该问题就不是bug。

### Reproduction / 复现链接

命令行操作，无复现链接。

### Config / 配置

alist默认配置

**Comment by xhofe** [comment]
storage disable 为禁用存储并非禁用驱动，它只是修改了数据库中的数据。如果alist已经在运行中，那么在内存中也会存有此数据，命令行对此无影响。所以你需要重启使其生效。

**Comment by troray** [comment]
> storage disable 为禁用存储并非禁用驱动，它只是修改了数据库中的数据。如果alist已经在运行中，那么在内存中也会存有此数据，命令行对此无影响。所以你需要重启使其生效。

好的，我明白了。

**Comment by anwen-anyi** [comment]
这个是怎么使用的吖？  看到了两个命令
```txt
Available Commands:
  disable     Disable a storage
  list        List all storages
```
alist storage list  命令倒是可以用
```txt
INFO[2023-08-09 08:59:48] Found 59 storages
ERRO[2023-08-09 08:59:48] failed to run program: unable to set console to raw mode: The parameter is incorrect.

```

alist storage disable 这个命令是怎么用的？ 没看太明白
```bash
alist storage disable  /123    #/123是路径名字
alist storage disable  1       #1 是驱动ID
```

**Comment by xhofe** [comment]
> 这个是怎么使用的吖？ 看到了两个命令
> 
> ```
> Available Commands:
>   disable     Disable a storage
>   list        List all storages
> ```
> 
> alist storage list 命令倒是可以用
> 
> ```
> INFO[2023-08-09 08:59:48] Found 59 storages
> ERRO[2023-08-09 08:59:48] failed to run program: unable to set console to raw mode: The parameter is incorrect.
> ```
> 
> alist storage disable 这个命令是怎么用的？ 没看太明白
> 
> ```shell
> alist storage disable  /123    #/123是路径名字
> alist storage disable  1       #1 是驱动ID
> ```

![image](https://github.com/alist-org/alist/assets/36558727/ea8934ca-86d1-46c6-9660-34ce47e43074)

**Comment by anwen-anyi** [comment]
> ![image](https://user-images.githubusercontent.com/36558727/259418750-ea8934ca-86d1-46c6-9660-34ce47e43074.png)

好像不太对诶~使用的是 https://github.com/alist-org/alist/actions/runs/5806549996 构建的
使用`.\alist-windows-amd64-upx-26.0-test.exe storage disable /212312312`也不行

```log
$ '/c/Users/Administrator/Desktop/新建文件夹 (5)/alist-windows-amd64-upx-26.0-test.exe' storage disable /212312312
INFO[2023-08-09 22:01:21] reading config file: data\config.json
INFO[2023-08-09 22:01:21] load config from env with prefix: ALIST_
INFO[2023-08-09 22:01:21] init logrus...
ERRO[2023-08-09 22:01:21] failed to query storage: record not found
github.com/alist-org/alist/v3/internal/db.GetStorageByMountPath
        /source/internal/db/storage.go:58
github.com/alist-org/alist/v3/cmd.glob..func11
        /source/cmd/storage.go:34
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/alist-org/alist/v3/cmd.Execute
        /source/cmd/root.go:20
main.main
        /source/main.go:6
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598

```
![image](https://github.com/alist-org/alist/assets/56105412/0e09eccd-f7d8-4c67-ba8a-cb42a4b86d15)

**Comment by Troray** [comment]
已经发布的版本是：
```
alist storage disable -m  /123pan  # /123pan是挂载的存储的名称
```
![](https://i.imgur.com/WYUuQGs.png)

仓库中，尚未正式发布的版本是：
```
alist storage disable  /123  # /123是挂载的存储的名称
```
![](https://i.imgur.com/E4cL7hd.png)

**Comment by anwen-anyi** [comment]
> 已经发布的版本是：
> 
> ```
> alist storage disable -m  /123pan  # /123pan是挂载的存储的名称
> ```
> 
> ![](https://camo.githubusercontent.com/6b69df968bbe70ed3edf4a54e20adb3c609509086be44887ea04b5e489ba134c/68747470733a2f2f692e696d6775722e636f6d2f575955755147732e706e67)
> 
> 仓库中，尚未正式发布的版本是：
> 
> ```
> alist storage disable  /123  # /123是挂载的存储的名称
> ```
> 
> ![](https://camo.githubusercontent.com/898e586783709e63f9900b8158854a91431f1f1277418b192fa3f97018492023/68747470733a2f2f692e696d6775722e636f6d2f4534634c3768642e706e67)


是的  我用的是仓库的版本....我也不知道怎么回事了... :joy_cat: :joy_cat: :joy_cat: 

用 Git bash的终端就出现我上述的报错信息.

用`CMD`和`powershell`这两个终端就没事儿...就很奇怪了

**Comment by Troray** [comment]
Git bash是MinGW，这是他本身的问题。在win中，几乎没人会使用他。
一般情况下，cmd、powershell、Windows terminal能使用就没问题了。

**Comment by anwen-anyi** [comment]
> > 是的 我用的是仓库的版本....我也不知道怎么回事了... 😹 😹 😹
> 
> > 
> 
> > 用 Git bash的终端就出现我上述的报错信息.
> 
> > 
> 
> > 用`CMD`和`powershell`这两个终端就没事儿...就很奇怪了
> 
> 
> 
> Git bash是MinGW，这是他本身的问题。在win中，几乎没人会使用他。
> 
> 一般情况下，cmd、powershell、Windows terminal能使用就没问题了。


难怪…不过我倒是习惯了Git bash😂…没太多注意这个
这次长经验了
