### ISSUE TITLE
500: Internal server error

### ISSUE THREAD

**Issue by DarremMolko** [alist-org/alist#4971]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

GoogleDrive, OneDrive

### Describe the bug / 问题描述

When I try to download a link from the command line using wget I get this:
HTTP request sent, awaiting response... 500 Internal Server Error
2023-08-09 01:06:05 ERROR 500: Internal Server Error.

### Reproduction / 复现链接

1. Copy a link from Google Drive or OneDrive driver with url proxy enabled (Cloudflare alist-proxy)
2. Try to download it in the command line using wget

### Config / 配置

I'm using a PaaS service, no configuration file except environment variables.

### Logs / 日志

[GIN] 2023/08/09 - 00:51:30 | 302 |   33.313916ms | 999.999.999.999 | GET      "/d/Folder1/Folder2/Folder3/XYZ.XYZ.2005.mkv?sign=XXXXXXXXXXXXXX=:0"
[GIN] 2023/08/09 - 00:51:32 | 200 |  1.332242021s | 2a06:98c0:3600::103 | POST     "/api/fs/link"
Error #01: common.Resp[interface {}].Data: model.Link.PartSize: Concurrency: IPCacheKey: Expiration: ReadSeekCloser: RangeReadCloser: model.RangeReadCloser.Closers: RangeReader:  RangeReadCloser RangeReadermodel.RangeReaderFunc is unsupported type
[GIN] 2023/08/09 - 00:51:38 | 302 |       96.25µs |  999.999.999.999 | GET      "/d/Folder1/Folder2/Folder3/XYZ.XYZ.2005.mkv?sign=XXXXXXXXXXXXXX=:0"
[GIN] 2023/08/09 - 00:51:40 | 200 |  1.150900666s | 2a06:98c0:3600::103 | POST     "/api/fs/link"
Error #01: common.Resp[interface {}].Data: model.Link.PartSize: Concurrency: IPCacheKey: Expiration: ReadSeekCloser: RangeReadCloser: model.RangeReadCloser.Closers: RangeReader:  RangeReadCloser RangeReadermodel.RangeReaderFunc is unsupported type

**Comment by SeanHeuc** [comment]
alist此次更新后 alist-proxy需要也改代码适配才行，具体时间就不好说了

**Comment by Minerchu** [comment]
一样的问题，期待早日修复

**Comment by yeungon** [comment]
I tested and Cloudflare alist-proxy does not work on Alistv 3.25.1 version but works well on 3.240

**Comment by DarremMolko** [comment]
> I tested and Cloudflare alist-proxy does not work on Alistv 3.25.1 version but works well on 3.240

I have not tested it myself but this should be fixed with this commit https://github.com/alist-org/alist/commit/9d45718e5f3a26459ccb773e4f8e6074e5c83616, you can use the development version (xhofe/alist:main) or wait for the next stable release (v3.26.0).

**Comment by yeungon** [comment]
Yeah @DarremMolko it works on the latest version (the main tag on the docker image). Can confirmed that.
