### ISSUE TITLE
直链不随目录结构一同刷新

### ISSUE THREAD

**Issue by liblaf** [alist-org/alist#4975]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.24.0

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

刷新 Cache 后, AList 能够正常更新目录结构, 但直链仍无法下载, 即 `example.com/d/abc.txt` 返回如下错误:

```json
{"code":500,"message":"failed link: failed to get file: object not found","data":null}
```

### Reproduction / 复现链接

Cache 失效后该直链应该可以正常下载: <https://alist.liblaf.me/d/img/2023/08/09/2023-08-09T163128.png>.

### Config / 配置

```json
{
  "force": false,
  "site_url": "***",
  "cdn": "",
  "jwt_secret": "***",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}
```

**Comment by xhofe** [comment]
请提供一个目录结构已更新，直链无法下载的链接

**Comment by liblaf** [comment]
> 请提供一个目录结构已更新，直链无法下载的链接

<https://alist.liblaf.me/d/img/2023/08/09/2023-08-09T172627.png>

**Comment by liblaf** [comment]
触发方法为:

1. 上传文件
2. 访问直链, object not found (这时直链可能缓存为不存在)
3. 访问 AList 页面刷新缓存
4. 访问直链, 仍然 object not found

**Comment by xhofe** [comment]
> > 请提供一个目录结构已更新，直链无法下载的链接
> 
> <https://alist.liblaf.me/d/img/2023/08/09/2023-08-09T172627.png>

cdn 缓存了
