### ISSUE TITLE
下载BUG

### ISSUE THREAD

**Issue by momo54181** [alist-org/alist#4984]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

在文件下载页面的地址加d会从源站下载文件，而不是走的网盘
例如https://test.cn/刷机/GIONEE/Google.zip
更改后的链接https://test.cn/d/刷机/GIONEE/Google.zip
会直接从源站下载文件

### Reproduction / 复现链接

抱歉，害怕被刷流量，CDN配置了 回源URL重写配置
https://alist.mocn.top/d/%E5%88%B7%E6%9C%BA/GIONEE%EF%BC%88%E9%87%91%E7%AB%8B%EF%BC%89/GN8002S%EF%BC%88M6%20Plus%EF%BC%89/amigo%EF%BC%88%E5%8E%9F%E5%8E%82%EF%BC%89/GIONEE_GN8002S_Mo3.1.1%20Google.zip
现在无法直接从源站下载
![image](https://github.com/alist-org/alist/assets/79344479/042ea2d9-7405-405e-b7cb-9db5e347c77d)

### Config / 配置

openwrt配置的

### Logs / 日志

[GIN] 2023/08/10 - 18:36:15 | 302 |     631.097µs |   .*.*.*.* | GET      "/d/刷机/GIONEE（金立）/GN8002S（M6 Plus）/flyme/flyme_M6plus_6.7.12.29R.zip"
[GIN] 2023/08/10 - 18:36:16 | 302 |      669.37µs |   .*.*.*.* | GET      "/d/刷机/GIONEE（金立）/GN8002S（M6 Plus）/flyme/flyme_M6plus_6.7.12.29R.zip"
[GIN] 2023/08/10 - 18:36:16 | 302 |    1.145137ms |   .*.*.*.*5 | GET      "/d/刷机/GIONEE（金立）/GN8002S（M6 Plus）/flyme/flyme_M6plus_6.7.12.29R.zip"
[GIN] 2023/08/10 - 18:36:16 | 302 |    1.258841ms |   .*.*.*.* | GET      "/d/刷机/GIONEE（金立）/GN8002S（M6 Plus）/flyme/flyme_M6plus_6.7.12.29R.zip"
[GIN] 2023/08/10 - 18:36:16 | 302 |    1.399922ms |   .*.*.*.* | GET      "/d/刷机/GIONEE（金立）/GN8002S（M6 Plus）/flyme/flyme_M6plus_6.7.12.29R.zip"
[GIN] 2023/08/10 - 18:36:16 | 302 |    1.080324ms |  *.*.*.** | GET      "/d/刷机/GIONEE（金立）/GN8002S（M6 Plus）/flyme/flyme_M6plus_6.7.12.29R.zip"
[GIN] 2023/08/10 - 18:36:17 | 302 |    2.408727ms |   *.*.*.* | GET      "/d/刷机/GIONEE（金立）/GN8002S（M6 Plus）/flyme/flyme_M6plus_6.7.12.29R.zip"

**Comment by xhofe** [comment]
- #4929

**Comment by anwen-anyi** [comment]
CDN/缓存等在AList会出问题，不要使用CDN/缓存这些比较好~

**Comment by momo54181** [comment]
CDN缓存已经关了

**Comment by momo54181** [comment]
将 CDN 的 重定向跟随 关闭即可。
