### ISSUE TITLE
Cannot use Cloudflare Proxy with Yandex Disk

### ISSUE THREAD

**Issue by yeungon** [alist-org/alist#4996]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

xhofe/alist:main

### Driver used / 使用的存储驱动

Yandex

### Describe the bug / 问题描述

While I can use Cloudflare Worker as proxy for Google Drive, Mega and other... It seems to me that it does not work when setting up with Yandex.

### Reproduction / 复现链接

It does not work on the version 3.24.0, 3.25.1 and the latest one.

### Config / 配置

![Screenshot from 2023-08-12 10-35-46](https://github.com/alist-org/alist/assets/3062418/0fdc26ab-aed0-4105-9f94-2831ee9bb0ee)

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/issues/4971

**Comment by xhofe** [comment]
What error is displayed while downloading with `alist-proxy` ?

**Comment by yeungon** [comment]
Hi @xhofe thanks for your quick reply. It simply downloads the direct link given by yandex.

**Comment by xhofe** [comment]
Could you provide a reproduction link?

**Comment by yeungon** [comment]
I am testing on this stagging site: 

https://file.giaovien.org/yandex/giaovien/sachgiaokhoa/ch%C6%B0%C6%A1ng%20tr%C3%ACnh%20c%C5%A9%20/tieuhoc/Ti%E1%BA%BFng%20Vi%E1%BB%87t

**Comment by yeungon** [comment]
I checked the log on Cloudflare Worker. And below is the 200 code returns.

`{
  "outcome": "ok",
  "scriptName": "hello-world-wispy-forest-4244",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [],
  "eventTimestamp": 1691821710237,
  "event": {
    "request": {
      "url": "https://hello-world-wispy-forest-4244.vuong.workers.dev/yandex/IMG_0237.JPG?sign=REDACTED=:0",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.9",
        "cf-connecting-ip": "14.243.26.132",
        "cf-ipcountry": "VN",
        "cf-ray": "7f56a898ea5b04a9",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "hello-world-wispy-forest-4244.vuong.workers.dev",
        "sec-ch-ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "cross-site",
        "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "14.243.26.132"
      },
      "cf": {
        "clientTcpRtt": 131,
        "longitude": "106.62570",
        "latitude": "10.82200",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 45899,
        "clientAcceptEncoding": "gzip, deflate, br",
        "country": "VN",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "90efc6716e914524f98e24053041f2c3cb290830d575dfb2e5e29375822534e7",
          "clientHandshake": "528247d8301e48acd1f8cd1f8e20934ed571e15e453413d8dc1476dababe1a33",
          "serverHandshake": "2282c4ca3b6941811b567c58b116bc3a1fe1f87d3a6d2514ec4a43160359a313",
          "serverFinished": "ea2580aa5048cde97500da18adcab5366aacbdecbda2d66606c17f92758e5dae"
        },
        "tlsVersion": "TLSv1.3",
        "city": "Ho Chi Minh City",
        "timezone": "Asia/Ho_Chi_Minh",
        "region": "Ho Chi Minh",
        "requestPriority": "weight=256;exclusive=1",
        "colo": "HKG",
        "httpProtocol": "HTTP/2",
        "regionCode": "SG",
        "asOrganization": "VNPT",
        "edgeRequestKeepAliveStatus": 1
      }
    },
    "response": {
      "status": 302
    }
  },
  "id": 1
}`

**Comment by yeungon** [comment]
But the link returned back by the browser is still the original link provided by yandex.

**Comment by xhofe** [comment]
Please test if this code works:
```js
// src/const.ts
var ADDRESS = "YOUR_ADDRESS";
var TOKEN = "YOUR_TOKEN";

// src/verify.ts
var verify = async (data, _sign) => {
  const signSlice = _sign.split(":");
  if (!signSlice[signSlice.length - 1]) {
    return "expire missing";
  }
  const expire = parseInt(signSlice[signSlice.length - 1]);
  if (isNaN(expire)) {
    return "expire invalid";
  }
  if (expire < Date.now() / 1e3 && expire > 0) {
    return "expire expired";
  }
  const right = await hmacSha256Sign(data, expire);
  if (_sign !== right) {
    return "sign mismatch";
  }
  return "";
};
var hmacSha256Sign = async (data, expire) => {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(TOKEN),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign", "verify"]
  );
  const buf = await crypto.subtle.sign(
    {
      name: "HMAC",
      hash: "SHA-256"
    },
    key,
    new TextEncoder().encode(`${data}:${expire}`)
  );
  return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g, "-").replace(/\//g, "_") + ":" + expire;
};

// src/handleDownload.ts
async function handleDownload(request) {
  const origin = request.headers.get("origin") ?? "*";
  const url = new URL(request.url);
  const path = decodeURIComponent(url.pathname);
  const sign = url.searchParams.get("sign") ?? "";
  const verifyResult = await verify(path, sign);
  if (verifyResult !== "") {
    const resp2 = new Response(
      JSON.stringify({
        code: 401,
        message: verifyResult
      }),
      {
        headers: {
          "content-type": "application/json;charset=UTF-8"
        }
      }
    );
    resp2.headers.set("Access-Control-Allow-Origin", origin);
    return resp2;
  }
  let resp = await fetch(`${ADDRESS}/api/fs/link`, {
    method: "POST",
    headers: {
      "content-type": "application/json;charset=UTF-8",
      Authorization: TOKEN
    },
    body: JSON.stringify({
      path
    })
  });
  let res = await resp.json();
  if (res.code !== 200) {
    return new Response(JSON.stringify(res));
  }
  request = new Request(res.data.url, {...request, redirect: "follow"});
  if (res.data.header) {
    for (const k in res.data.header) {
      for (const v of res.data.header[k]) {
        request.headers.set(k, v);
      }
    }
  }
  let response = await fetch(request);
  response = new Response(response.body, response);
  response.headers.delete("set-cookie");
  response.headers.set("Access-Control-Allow-Origin", origin);
  response.headers.append("Vary", "Origin");
  return response;
}

// src/handleOptions.ts
function handleOptions(request) {
  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET,HEAD,POST,OPTIONS",
    "Access-Control-Max-Age": "86400"
  };
  let headers = request.headers;
  if (headers.get("Origin") !== null && headers.get("Access-Control-Request-Method") !== null) {
    let respHeaders = {
      ...corsHeaders,
      "Access-Control-Allow-Headers": request.headers.get("Access-Control-Request-Headers") || ""
    };
    return new Response(null, {
      headers: respHeaders
    });
  } else {
    return new Response(null, {
      headers: {
        Allow: "GET, HEAD, POST, OPTIONS"
      }
    });
  }
}

// src/index.ts
var src_default = {
  async fetch(request, env, ctx) {
    if (request.method === "OPTIONS") {
      return handleOptions(request);
    }
    return handleDownload(request);
  }
};
export {
  src_default as default
};
//# sourceMappingURL=index.js.map
```
I will push it to the repo if it works

**Comment by yeungon** [comment]
1) Thanks @xhofe for your the code updated. Yet it does not run as I double check it for sure.

2) I also switched to the native proxy but it still got the link provided by yandex.

3) I switched to the native proxy with google drive and it worked as expected.

I am using the version 3.24.0.

**Comment by yeungon** [comment]
@xhofe 

Yooo, when upgrading to docker pull xhofe/alist:main it works really well and I am using the above proxy code on cloudflare.

**Comment by xhofe** [comment]
> 1. Thanks @xhofe for your the code updated. Yet it does not run as I double check it for sure.
> 2. I also switched to the native proxy but it still got the link provided by yandex.
> 3. I switched to the native proxy with google drive and it worked as expected.
> 
> I am using the version 3.24.0.

`native proxy` is just for `WebDAV` policy. If you want to use `native proxy` for web UI, you should open `web-proxy` with an empty `Download proxy URL`

**Comment by yeungon** [comment]
And btw, cloudflare proxy does not work on the current stable version 3.25.1 no matter google drive or meta...

**Comment by xhofe** [comment]
> And btw, cloudflare proxy does not work on the current stable version 3.25.1 no matter google drive or meta...

Wait for the next release please

**Comment by yeungon** [comment]
> > And btw, cloudflare proxy does not work on the current stable version 3.25.1 no matter google drive or meta...
> 
> Wait for the next release please

Thanks for your great work. Cheer and have a great day.

**Comment by yeungon** [comment]
> > 1. Thanks @xhofe for your the code updated. Yet it does not run as I double check it for sure.
> > 2. I also switched to the native proxy but it still got the link provided by yandex.
> > 3. I switched to the native proxy with google drive and it worked as expected.
> > 

> > I am using the version 3.24.0.
> 
> `native proxy` is just for `WebDAV` policy. If you want to use `native proxy` for web UI, you should open `web-proxy` with an empty `Download proxy URL`

FYI, while it seems that the code updated has fixed the Cloudflare proxy, I cannot use "native proxy" with yandex. I made the url field empty and picked "native proxy", it returned the original yandex link.

The version I have tested is the dev one.

**Comment by xhofe** [comment]
> > > 1. Thanks @xhofe for your the code updated. Yet it does not run as I double check it for sure.
> > > 2. I also switched to the native proxy but it still got the link provided by yandex.
> > > 3. I switched to the native proxy with google drive and it worked as expected.
> 
> > > I am using the version 3.24.0.
> > 
> > 
> > `native proxy` is just for `WebDAV` policy. If you want to use `native proxy` for web UI, you should open `web-proxy` with an empty `Download proxy URL`
> 
> FYI, while it seems that the code updated has fixed the Cloudflare proxy, I cannot use "native proxy" with yandex. I made the url field empty and picked "native proxy", it returned the original yandex link.
> 
> The version I have tested is the dev one.

`native proxy` is for webdav, did you open the `web-proxy`?

**Comment by yeungon** [comment]
> `native proxy` is for webdav, did you open the `web-proxy`?

No, I know what does `web-proxy` mean.

Here is the screenshot and I am using the dev version (docker). I hope it can give you some sort of hints.

![photo_6251007398621853678_y](https://github.com/alist-org/alist/assets/3062418/b07a5042-6aac-46bc-8e43-dc3d3b605201)

**Comment by xhofe** [comment]
> 

you need to open `web-proxy`

**Comment by yeungon** [comment]
> > 
> 
> you need to open `web-proxy`

Oh yeah it works, but it seems to me that the information "320 redirect" seems confusing. Anyway, thanks for fixing the bug and clarifying the configuration.
