### ISSUE TITLE
windows下本地存储自动在前面添加'/'

### ISSUE THREAD

**Issue by ljlVink** [alist-org/alist#4999]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

windows环境下，添加本地储存时，在保存时自动在前面加了`/`符号。导致挂载位置错误。

![image](https://github.com/alist-org/alist/assets/46098706/af32aab3-5c0c-4998-b27f-020faf6036b5)

### Reproduction / 复现链接

http://127.0.0.1:5244/@manage/storages/add

### Config / 配置

PS F:\Desktop> cd alist
PS F:\Desktop\alist> ./alist server --debug

### Logs / 日志
```
2023/08/12 18:05:46 /source/internal/db/storage.go:22
[0.000ms] [rows:1] UPDATE `x_storages` SET `mount_path`="/F:/Desktop/要挂在的文件夹",`order`=0,`driver`="Local",`cache_expiration`=0,`status`="work",`addition`="{\"root_folder_path\":\"F:\\\",\"thumbnail\":false,\"thumb_cache_folder\":\"\",\"show_hidden\":true,\"mkdir_perm\":\"777\"}",`remark`="",`modified`="2023-08-12 18:05:46.185",`disabled`=false,`enable_sign`=false,`order_by`="",`order_direction`="",`extract_folder`="",`web_proxy`=false,`webdav_policy`="native_proxy",`down_proxy_url`="" WHERE `id` = 1
DEBU[2023-08-12 18:05:46]/source/internal/op/storage.go:65 github.com/alist-org/alist/v3/internal/op.CreateStorage() storage &{Storage:{ID:1 MountPath:/F:/Desktop/要挂在的文件夹 Order:0 Driver:Local CacheExpiration:0 Status:work Addition:{"root_folder_path":"F:\\","thumbnail":false,"thumb_cache_folder":"","show_hidden":true,"mkdir_perm":"777"} Remark: Modified:2023-08-12 18:05:46.1852238 +0800 CST m=+148.199615901 Disabled:false EnableSign:false Sort:{OrderBy: OrderDirection: ExtractFolder:} Proxy:{WebProxy:false WebdavPolicy:native_proxy DownProxyUrl:}} Addition:{RootPath:{RootFolderPath:F:\} Thumbnail:false ThumbCacheFolder: ShowHidden:true MkdirPerm:777} mkdirPerm:511} is created
```

**Comment by xhofe** [comment]
https://alist.nn.ci/zh/guide/drivers/common.html#%E6%8C%82%E8%BD%BD%E8%B7%AF%E5%BE%84
