### ISSUE TITLE
从夸克网盘复制文件到本地速度很慢

### ISSUE THREAD

**Issue by luvjojo** [alist-org/alist#5000]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.25.1

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

Alist升级到最新版本后，从夸克复制文件到本地速度突然变得非常慢，上一个版本则正常。现在速度大概只有几百kb左右，但是用aria2下载到本地速度就是正常的，其他网盘没有出现这种问题，不知道怎么回事。

### Reproduction / 复现链接

![IMG_20230813_075651](https://github.com/alist-org/alist/assets/48212475/a7215098-5443-4823-bf07-d7544e4e705c)
![IMG_20230813_075635](https://github.com/alist-org/alist/assets/48212475/2c738a5b-65b1-463c-8535-888ec51cb47b)

### Config / 配置

![IMG_20230813_080529](https://github.com/alist-org/alist/assets/48212475/5eb0b1e0-7d59-4b3a-8891-fea8022478b0)

**Comment by iyangpengyu** [comment]
怎么使用这个复制功能呢？我这边都是这样的：
![image](https://github.com/alist-org/alist/assets/34344496/5b5f1e20-adf7-4127-bf60-1a57a4af7a9f)

**Comment by luvjojo** [comment]
> 怎么使用这个复制功能呢？我这边都是这样的： ![image](https://user-images.githubusercontent.com/34344496/260470982-5b5f1e20-adf7-4127-bf60-1a57a4af7a9f.png)
选中你要复制的文件然后复制到你想复制网盘或者本地存储里就行了啊……
![IMG_20230814_221230](https://github.com/alist-org/alist/assets/48212475/0736c573-cf87-4e7a-af0c-dab2d565a024)

**Comment by Kado814** [comment]
+1
