### ISSUE TITLE
为alist添加归档功能

### ISSUE THREAD

**Issue by shadowofgost** [alist-org/alist#5002]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist可以建立归档数据库，保存相关文件的保存路径，文件元信息和hash值。当使用者需要恢复数据时可以借用各大云盘秒传的方式恢复数据。同时，可以和复制功能结合，同一个文件在不同网盘的hash都有保存，便于开发alist的分享功能（因为这样只要分享hash值就可以了）

**Comment by okou19900722** [comment]
很强大的功能

**Comment by 1049731887** [comment]
这要是做出来不得是炸裂界十分炸裂的事

**Comment by JsonSong89** [comment]
你这个还是基于秒传功能吧?
阿里云盘的秒传现在需要全部文件才行,因为会随机截取整个文件的一小块内容计算hash 
除非有其他文件持有者帮你计算这个hash .

**Comment by shadowofgost** [comment]
> 你这个还是基于秒传功能吧?
> 阿里云盘的秒传现在需要全部文件才行,因为会随机截取整个文件的一小块内容计算hash 
> 除非有其他文件持有者帮你计算这个hash .

我是看issue中提到可以实现不用下载的复制功能，所以衍生出来的一个想法，就是那个115网盘和阿里云盘的复制那个issue。如果那样的话我觉得是能直接获取文件的hash值的。当然如果要下载自己计算那确实这个功能就没有存在的必要了

**Comment by xhofe** [comment]
阿里云盘需要根据token对文件进行随机读写，因此只能做到依赖range来做复制，无法归档因为它的`proof_code`是动态的。
> https://www.yuque.com/aliyundrive/zpfszx/ezlzok#hwSW3

**Comment by shadowofgost** [comment]
> 阿里云盘需要根据token对文件进行随机读写，因此只能做到依赖range来做复制，无法归档因为它的`proof_code`是动态的。
> > https://www.yuque.com/aliyundrive/zpfszx/ezlzok#hwSW3

如果这样那么这种功能只是一种空想了，这个issue应该可以关掉了

**Comment by JsonSong89** [comment]
> 

那个是115和阿里云盘互秒转,首先前提是这两个hash算法一致,都是sha-1
然后因为你在另一个盘有全部文件,所以可以从另一个盘,读取需要的那个随机chunk的内容然后进行hash计算
