### ISSUE TITLE
阿里云盘 401

### ISSUE THREAD

**Issue by aiXlau** [alist-org/alist#5013]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

点击下载 浏览器自动跳转Neat Download Manager下载 错误提示Error : HTTP/1.1 403 Forbidden

### Reproduction / 复现链接

![215613055e8c034581184c8e7131c753.png](https://ice.frostsky.com/2023/08/15/215613055e8c034581184c8e7131c753.png)

### Config / 配置

无

### Logs / 日志

INFO   2023-08-15 14:21:50 ( 1692080510 )   Opening LogFile...
INFO   2023-08-15 14:21:50 ( 1692080510 )   DownloadID = 123 , Protocol = HTTPS , OS = MAC , AppVersion = MacVersion1324
INFO   2023-08-15 14:21:50 ( 1692080510 )   DownloadEngine State Changed : Unknown -> Starting...
DEBUG  2023-08-15 14:21:50 ( 1692080510 )   DownloadEngine is Starting...
INFO   2023-08-15 14:21:50 ( 1692080510 )   Trying to Start Download for -> https://cn-beijing-data.aliyundrive.net/6ZzyEM4X/587064631/64d83f9ba85c59a549d54d5fa75565536ae01ad8/64d83f9b706ec2ea785846ea9f9dd296aefa127f?di=bj29&dr=685547872&f=64da7f6f4ab77d3bfb6040d5836eb8334db7a7f1&response-content-disposition=attachment; filename*=UTF-8''%E6%96%97%E7%A0%B4%E8%8B%8D%E7%A9%B9S05E57.mp4&security-token=CAIS+gF1q6Ft5B2yfSjIr5DaeOPdmItn9I+BNFHot1IhW8dJpb/m1Dz2IHFPeHJrBeAYt/oxmW1X5vwSlq5rR4QAXlDfNW3hCwagqFHPWZHInuDox55m4cTXNAr+Ihr/29CoEIedZdjBe/CrRknZnytou9XTfimjWFrXWv/gy+QQDLItUxK/cCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF+97DRbG/dNRpMZtFVNO44fd7bKKp0lQLukMWr/wq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J+q/zxhTPrMnpkSlacGoABFk6W8HsHGxQXfaWeaictUZA6JsIwzb5emLIY/i+U2ck3DkPoPXFxT3XzMWAEbH1GRuMmMq//WOC5oDW+xKiskgwpHhYYmDDsyYILR3j/uXFegyzVXShTPrpSaNtc24OSiC2GqPU73ybJe2izlD/6KjJaxaGratGrOmR1NMxlKKY=&u=f408c19f7c36455aa9ec5e43368e029c&x-oss-access-key-id=STS.NSo3YiuTFCMj6wYSRtWHeJzM6&x-oss-expires=1692094258&x-oss-signature=0rmySvu57vwGXzT/r+Xt2OyDCg+yDXmMUMrzxk/A5rI=&x-oss-signature-version=OSS2
INFO   2023-08-15 14:21:50 ( 1692080510 )   New Socket(s) Created. MaxAllowedConnection = 12 And ActiveSockets = 1
DEBUG  2023-08-15 14:21:50 ( 1692080510 )   Socket ( 1 )  Connecting to  198.18.1.78:443 ...
INFO   2023-08-15 14:21:50 ( 1692080510 )   Initializing SslHandShake for Socket (1 )
INFO   2023-08-15 14:21:50 ( 1692080510 )   SslHandShake OK for Socket ( 1 )
DEBUG  2023-08-15 14:21:50 ( 1692080510 )   SegmentManager Created a New Segment and now has 1 Segments.
DEBUG  2023-08-15 14:21:50 ( 1692080510 )   Socket ( 1 ) HttpStatus =  HTTP_STATE_VOID  RoundNumberServer = 0 and RoundNumberProxy = 0
INFO   2023-08-15 14:21:50 ( 1692080510 )   Sending Http-GET  for Socket ( 1 )  Range = 0-
DEBUG  2023-08-15 14:21:50 ( 1692080510 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_VOID  ->  HTTP_STATE_GET_SENT 
INFO   2023-08-15 14:21:50 ( 1692080510 )   GET Sent : 
<< GET /6ZzyEM4X/587064631/64d83f9ba85c59a549d54d5fa75565536ae01ad8/64d83f9b706ec2ea785846ea9f9dd296aefa127f?di=bj29&dr=685547872&f=64da7f6f4ab77d3bfb6040d5836eb8334db7a7f1&response-content-disposition=attachment; filename*=UTF-8''%E6%96%97%E7%A0%B4%E8%8B%8D%E7%A9%B9S05E57.mp4&security-token=CAIS+gF1q6Ft5B2yfSjIr5DaeOPdmItn9I+BNFHot1IhW8dJpb/m1Dz2IHFPeHJrBeAYt/oxmW1X5vwSlq5rR4QAXlDfNW3hCwagqFHPWZHInuDox55m4cTXNAr+Ihr/29CoEIedZdjBe/CrRknZnytou9XTfimjWFrXWv/gy+QQDLItUxK/cCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF+97DRbG/dNRpMZtFVNO44fd7bKKp0lQLukMWr/wq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J+q/zxhTPrMnpkSlacGoABFk6W8HsHGxQXfaWeaictUZA6JsIwzb5emLIY/i+U2ck3DkPoPXFxT3XzMWAEbH1GRuMmMq//WOC5oDW+xKiskgwpHhYYmDDsyYILR3j/uXFegyzVXShTPrpSaNtc24OSiC2GqPU73ybJe2izlD/6KjJaxaGratGrOmR1NMxlKKY=&u=f408c19f7c36455aa9ec5e43368e029c&x-oss-access-key-id=STS.NSo3YiuTFCMj6wYSRtWHeJzM6&x-oss-expires=1692094258&x-oss-signature=0rmySvu57vwGXzT/r+Xt2OyDCg+yDXmMUMrzxk/A5rI=&x-oss-signature-version=OSS2 HTTP/1.1
Host: cn-beijing-data.aliyundrive.net
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Accept: */*
Accept-Encoding: identity
Accept-Language: en-US,en;q=0.9
Accept-Charset: *
Origin: https://cn-beijing-data.aliyundrive.net
Referer: https://cn-beijing-data.aliyundrive.net/6ZzyEM4X/587064631/64d83f9ba85c59a549d54d5fa75565536ae01ad8/64d83f9b706ec2ea785846ea9f9dd296aefa127f?di=bj29&dr=685547872&f=64da7f6f4ab77d3bfb6040d5836eb8334db7a7f1&response-content-disposition=attachment; filename*=UTF-8''%E6%96%97%E7%A0%B4%E8%8B%8D%E7%A9%B9S05E57.mp4&security-token=CAIS+gF1q6Ft5B2yfSjIr5DaeOPdmItn9I+BNFHot1IhW8dJpb/m1Dz2IHFPeHJrBeAYt/oxmW1X5vwSlq5rR4QAXlDfNW3hCwagqFHPWZHInuDox55m4cTXNAr+Ihr/29CoEIedZdjBe/CrRknZnytou9XTfimjWFrXWv/gy+QQDLItUxK/cCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF+97DRbG/dNRpMZtFVNO44fd7bKKp0lQLukMWr/wq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J+q/zxhTPrMnpkSlacGoABFk6W8HsHGxQXfaWeaictUZA6JsIwzb5emLIY/i+U2ck3DkPoPXFxT3XzMWAEbH1GRuMmMq//WOC5oDW+xKiskgwpHhYYmDDsyYILR3j/uXFegyzVXShTPrpSaNtc24OSiC2GqPU73ybJe2izlD/6KjJaxaGratGrOmR1NMxlKKY=&u=f408c19f7c36455aa9ec5e43368e029c&x-oss-access-key-id=STS.NSo3YiuTFCMj6wYSRtWHeJzM6&x-oss-expires=1692094258&x-oss-signature=0rmySvu57vwGXzT/r+Xt2OyDCg+yDXmMUMrzxk/A5rI=&x-oss-signature-version=OSS2
Range: bytes=0-

>>
INFO   2023-08-15 14:21:50 ( 1692080510 )   All Response Headers For Socket ( 1 ) :
INFO   2023-08-15 14:21:50 ( 1692080510 )   
<<HTTP/1.1 403 Forbidden
Server: AliyunOSS
Date: Tue, 15 Aug 2023 06:21:47 GMT
Content-Type: application/xml
Content-Length: 322
Connection: keep-alive
x-oss-request-id: 64DB197BC93A583138213BC6
Vary: Origin
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, HEAD
Access-Control-Expose-Headers: ETag
Access-Control-Max-Age: 0
x-oss-server-time: 3
x-oss-ec: 0003-00000503>>

DEBUG  2023-08-15 14:21:50 ( 1692080510 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_GET_SENT  ->  HTTP_STATE_PARSING_HTTP_HEADER 
DEBUG  2023-08-15 14:21:50 ( 1692080510 )   Status Code For Socket (1 ) = 403
ERROR  2023-08-15 14:21:50 ( 1692080510 )   Handling Error - Socket ( 1 ) - SocketState =  HTTP_STATE_PARSING_HTTP_HEADER  ErrorText = HTTP/1.1 403 Forbidden
ERROR  2023-08-15 14:21:50 ( 1692080510 )   HTTP/1.1 403 Forbidden
INFO   2023-08-15 14:21:50 ( 1692080510 )   DownloadEngine State Changed : Starting... ( 4 ) -> Error
DEBUG  2023-08-15 14:21:50 ( 1692080510 )   Socket ( 1 ) All Headers have been Parsed. Now HttpStatus =  HTTP_STATE_PARSING_HTTP_HEADER  And StatusCode = 403
ERROR  2023-08-15 14:21:50 ( 1692080510 )   Error Occurred. HTTP/1.1 403 Forbidden
DEBUG  2023-08-15 14:21:50 ( 1692080510 )   DownloadEngine Is Terminating , EngineState = Error.
DEBUG  2023-08-15 14:21:50 ( 1692080510 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_PARSING_HTTP_HEADER  ->  HTTP_STATE_VOID 
INFO   2023-08-15 14:21:50 ( 1692080510 )   Closing LogFile.

**Comment by xhofe** [comment]
阿里云盘下载禁止携带[Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer)

**Comment by dfvips** [comment]
这个问题很早之前就遇到过，你复制alist的链接，比如http://127.0.0.1:5244/test.mp4，到NDM就能下载。
