### ISSUE TITLE
关于加密驱动挂载顺序早于其存储加密数据的网盘驱动导致的错误

### ISSUE THREAD

**Issue by AssassinHjx** [alist-org/alist#5018]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

alist如果添加了加密驱动，在重新启动如果加密驱动早于其存储数据的驱动器加载的话，就会因为找不到该驱动器而加载错误。希望可以将加密驱动器的加载置于起存储加密数据的驱动器之后。

### Reproduction / 复现链接

内网使用，无法分享

### Config / 配置

![IMG_0445](https://github.com/alist-org/alist/assets/91854457/f1a69b90-e2fa-4339-a5be-661067d4b4c7)
![IMG_0446](https://github.com/alist-org/alist/assets/91854457/7a874f70-46b5-4ced-b3a3-e76768bfd250)
![IMG_0447](https://github.com/alist-org/alist/assets/91854457/a96dc2c6-93f3-4f36-a8ff-1f6882e418f2)
![IMG_0448](https://github.com/alist-org/alist/assets/91854457/a7a66987-47af-49a5-9a31-54c55289592e)

**Comment by anwen-anyi** [comment]
你添加 加密存储时不是先添加的阿里，才添加的加密存储吗？  我这里没问题吖~
![image](https://github.com/alist-org/alist/assets/56105412/477fb782-a64e-48bc-91cd-002b1e1313d5)

**Comment by AssassinHjx** [comment]
> 你添加 加密存储时不是先添加的阿里，才添加的加密存储吗？ 我这里没问题吖~
> ![image](https://user-images.githubusercontent.com/56105412/261167634-477fb782-a64e-48bc-91cd-002b1e1313d5.png)

alist重启后加载驱动器的顺序是按照添加的顺序来加载的嘛？按道理不添加存储加密数据的网盘驱动器是没办法挂载加密驱动的诶？我把加密驱动删了重新添加后又正常了。

**Comment by anwen-anyi** [comment]
> alist重启后加载驱动器的顺序是按照添加的顺序来加载的嘛？按道理不添加存储加密数据的网盘驱动器是没办法挂载加密驱动的诶？我把加密驱动删了重新添加后又正常了。

看启动顺序好像是按照添加的顺序来的，但是你是怎么添加的？你是先添加的`Cytpt加密`驱动？才添加的正常驱动么？
