### ISSUE TITLE
测试版使用cloudflare workers在线播放和webdav播放onedrive网盘仍出现问题

### ISSUE THREAD

**Issue by ypq123456789** [alist-org/alist#5021]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

测试版

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

我通过alist actions中的https://github.com/alist-org/alist/actions/runs/5883220796 安装了测试版的alist，发现cloudflare workers下载onedrive网盘已经没有问题，不会返回错误码，但浏览器在线观看视频需要等很久，且webdav无法观看。
浏览器在线观看时打开f12开发者工具，发现等很久是因为每次打开视频alist都会下载完整个视频，然后再开始加载，并且是顺序加载，如果跳跃点击还没加载出来的部分，会重头再开始加载一遍。开发者页面的网络的问题显示“使用了已弃用的功能”和“Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform”，不知道是否有关。
![@}9BY$UI}50~UOPRI~S{{A](https://github.com/alist-org/alist/assets/114487221/580e197e-dc7f-421d-84c0-4a7a98642374)
webdav使用安卓端的nplayer播放，提示媒体类型无效，有时会提醒此文件不可播放：110。
![7f506ef1d7218eaed0df31ad55ada21](https://github.com/alist-org/alist/assets/114487221/504f4184-21a3-4e3c-9eca-bbf35d9ce8f3)
cloudflare workers日志显示如下，不过这个websocket监听必须要开代理才能用，所以我的网络环境有所变化，是香港节点。显示前两次都是cancel失败，最后才ok开始加载视频。
![1692247674384](https://github.com/alist-org/alist/assets/114487221/310de1bd-0f6e-43ab-a910-6a9fffa33b81)
视频内点击后面没加载的部分，会继续cancel失败2次，没有ok了，但是视频过段时间能加载出来。
![1692247848656](https://github.com/alist-org/alist/assets/114487221/fbdde503-7f4b-4a12-aaad-35759af98e7e)
第一次的失败日志：
{
  "outcome": "canceled",
  "scriptName": "alist",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [],
  "eventTimestamp": 1692247567840,
  "event": {
    "request": {
      "url": "https://p.bacon123.eu.org/onedrive%20cf%E4%BB%A3%E7%90%86/onedrive%E5%85%AC%E5%BC%80/%E7%9F%A5%E4%B9%8E%E5%85%AC%E5%BC%80%E8%AF%BE3%E8%A1%8C%E6%B5%8B%E7%A7%92%E6%9D%80.mp4?sign=REDACTED=:1692463567",
      "method": "HEAD",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "zh-CN,zh;q=0.9",
        "cf-connecting-ip": "202.64.124.163",
        "cf-ipcountry": "HK",
        "cf-ray": "7f7f4582fdc7044e",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "p.bacon123.eu.org",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "none",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "202.64.124.163"
      },
      "cf": {
        "clientTcpRtt": 12,
        "longitude": "114.15010",
        "latitude": "22.29080",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 9381,
        "clientAcceptEncoding": "gzip, deflate, br",
        "country": "HK",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "8113c4f971149e25db494133d7413b3460cce2cf72e0f82e3f1bb1d89bcdbf20",
          "clientHandshake": "3ee186ccf3b1b7bb9de4e8294dd204762c7ccbe959221f278a7f1b15d08720f1",
          "serverHandshake": "7d5d73f09954090135634a12bf53e143e5759e7370b0eb83d060e5d627d283bc",
          "serverFinished": "26c344bd0e8c3739b3042e13bb00fd44b254edfa97795901397a83b95c2495b4"
        },
        "tlsVersion": "TLSv1.3",
        "city": "Central",
        "timezone": "Asia/Hong_Kong",
        "region": "Central and Western District",
        "requestPriority": "weight=220;exclusive=1",
        "colo": "HKG",
        "httpProtocol": "HTTP/2",
        "regionCode": "HCW",
        "asOrganization": "Hong Kong Broadband Network",
        "edgeRequestKeepAliveStatus": 1
      }
    },
    "response": {
      "status": 200
    }
  },
  "id": 0
}
第二次的失败日志
{
  "outcome": "canceled",
  "scriptName": "alist",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [],
  "eventTimestamp": 1692247567840,
  "event": {
    "request": {
      "url": "https://p.bacon123.eu.org/onedrive%20cf%E4%BB%A3%E7%90%86/onedrive%E5%85%AC%E5%BC%80/%E7%9F%A5%E4%B9%8E%E5%85%AC%E5%BC%80%E8%AF%BE3%E8%A1%8C%E6%B5%8B%E7%A7%92%E6%9D%80.mp4?sign=REDACTED=:1692463567",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "zh-CN,zh;q=0.9",
        "cf-connecting-ip": "202.64.124.163",
        "cf-ipcountry": "HK",
        "cf-ray": "7f7f4582fd782118",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "p.bacon123.eu.org",
        "range": "bytes=0-",
        "sec-ch-ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "video",
        "sec-fetch-mode": "no-cors",
        "sec-fetch-site": "cross-site",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "202.64.124.163"
      },
      "cf": {
        "clientTcpRtt": 11,
        "longitude": "114.15010",
        "latitude": "22.29080",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 9381,
        "clientAcceptEncoding": "identity;q=1, *;q=0",
        "country": "HK",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "5881b885f0004e89f0839a1245e01b99c00db95538e1cc6e253e23d599735194",
          "clientHandshake": "344f461ac5a3a3386ad98396a760bad8136ab40cbe3b4233a2765e79652f9bf5",
          "serverHandshake": "7cb70176b5ede7fa8e787e8b3c1ecc9033a02395a7a5b795074ad39b8c42d45e",
          "serverFinished": "cab78fceb6396fe556d9ba19365e7d83d8afdf8b33411abbe0c1e96ac4ba06be"
        },
        "tlsVersion": "TLSv1.3",
        "city": "Central",
        "timezone": "Asia/Hong_Kong",
        "region": "Central and Western District",
        "requestPriority": "weight=147;exclusive=1",
        "colo": "HKG",
        "httpProtocol": "HTTP/2",
        "regionCode": "HCW",
        "asOrganization": "Hong Kong Broadband Network",
        "edgeRequestKeepAliveStatus": 1
      }
    },
    "response": {
      "status": 200
    }
  },
  "id": 1
}

### Reproduction / 复现链接

https://bacon1.store/%E7%9F%A5%E4%B9%8E%E5%85%AC%E5%BC%80%E8%AF%BE3%E8%A1%8C%E6%B5%8B%E7%A7%92%E6%9D%80.mp4

### Config / 配置

![5_KAX0$4~P45DZW~}YB}J3T](https://github.com/alist-org/alist/assets/114487221/af898b10-4c34-48cd-b267-fe5b98da43d7)

### Logs / 日志

![94VWLVY36QVDATN4E8B2MGL](https://github.com/alist-org/alist/assets/114487221/f7fd98fe-dd4c-4f8e-96b1-7935a5c98c28)
日志没看出来啥问题

**Comment by xhofe** [comment]
现在它抛出 500 错误， 请再次检查一下cloudflare workers日志 并贴出 相关的 500 日志

**Comment by ypq123456789** [comment]
> 现在它抛出 500 错误， 请再次检查一下cloudflare workers日志 并贴出 相关的 500 日志

好的，现在又出现500错误了，错误如下
![Uploading 0]00ER4VG~J9HQ1IG1KYV~U.png…]()
第一次错误日志是：{
  "outcome": "exception",
  "scriptName": "alist",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "name": "SyntaxError",
      "message": "Unexpected end of JSON input",
      "timestamp": 1692256484877
    }
  ],
  "logs": [],
  "eventTimestamp": 1692256484296,
  "event": {
    "request": {
      "url": "https://p.bacon123.eu.org/onedrive%20cf%E4%BB%A3%E7%90%86/onedrive%E5%85%AC%E5%BC%80/%E7%9F%A5%E4%B9%8E%E5%85%AC%E5%BC%80%E8%AF%BE3%E8%A1%8C%E6%B5%8B%E7%A7%92%E6%9D%80.mp4?sign=REDACTED=:1692472484",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "zh-CN,zh;q=0.9",
        "cf-connecting-ip": "202.64.124.163",
        "cf-ipcountry": "HK",
        "cf-ray": "7f801f32cad7098f",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "p.bacon123.eu.org",
        "range": "bytes=0-",
        "sec-ch-ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "video",
        "sec-fetch-mode": "no-cors",
        "sec-fetch-site": "cross-site",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "202.64.124.163"
      },
      "cf": {
        "clientTcpRtt": 12,
        "longitude": "114.15010",
        "latitude": "22.29080",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 9381,
        "clientAcceptEncoding": "identity;q=1, *;q=0",
        "country": "HK",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "c732250c400180fbf9715bd9229347b275f63562837c14b37aad0831109880ab",
          "clientHandshake": "4ef3164b33ff10c9054dcb9deb38623bcf54f8a83f11866f96146df237120d80",
          "serverHandshake": "a3cf1f97af8e2cd9715201930252a8f50248ea2a8347bbdd576feadc93f8026d",
          "serverFinished": "9aab48338d504549a03a63a08c24d4ddfe9590d6ea5eee51716490ad01d9abad"
        },
        "tlsVersion": "TLSv1.3",
        "city": "Central",
        "timezone": "Asia/Hong_Kong",
        "region": "Central and Western District",
        "requestPriority": "weight=147;exclusive=1",
        "colo": "HKG",
        "httpProtocol": "HTTP/2",
        "regionCode": "HCW",
        "asOrganization": "Hong Kong Broadband Network",
        "edgeRequestKeepAliveStatus": 1
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 0
}
第二次错误日志是
{
  "outcome": "exception",
  "scriptName": "alist",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "name": "SyntaxError",
      "message": "Unexpected end of JSON input",
      "timestamp": 1692256494538
    }
  ],
  "logs": [],
  "eventTimestamp": 1692256493977,
  "event": {
    "request": {
      "url": "https://p.bacon123.eu.org/onedrive%20cf%E4%BB%A3%E7%90%86/onedrive%E5%85%AC%E5%BC%80/%E7%9F%A5%E4%B9%8E%E5%85%AC%E5%BC%80%E8%AF%BE3%E8%A1%8C%E6%B5%8B%E7%A7%92%E6%9D%80.mp4?sign=REDACTED=:1692472484",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "zh-CN,zh;q=0.9",
        "cf-connecting-ip": "202.64.124.163",
        "cf-ipcountry": "HK",
        "cf-ray": "7f801f6f5b56098f",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "p.bacon123.eu.org",
        "range": "bytes=0-",
        "sec-ch-ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "video",
        "sec-fetch-mode": "no-cors",
        "sec-fetch-site": "cross-site",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "202.64.124.163"
      },
      "cf": {
        "clientTcpRtt": 11,
        "longitude": "114.15010",
        "latitude": "22.29080",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 9381,
        "clientAcceptEncoding": "identity;q=1, *;q=0",
        "country": "HK",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "c732250c400180fbf9715bd9229347b275f63562837c14b37aad0831109880ab",
          "clientHandshake": "4ef3164b33ff10c9054dcb9deb38623bcf54f8a83f11866f96146df237120d80",
          "serverHandshake": "a3cf1f97af8e2cd9715201930252a8f50248ea2a8347bbdd576feadc93f8026d",
          "serverFinished": "9aab48338d504549a03a63a08c24d4ddfe9590d6ea5eee51716490ad01d9abad"
        },
        "tlsVersion": "TLSv1.3",
        "city": "Central",
        "timezone": "Asia/Hong_Kong",
        "region": "Central and Western District",
        "requestPriority": "weight=147;exclusive=1",
        "colo": "HKG",
        "httpProtocol": "HTTP/2",
        "regionCode": "HCW",
        "asOrganization": "Hong Kong Broadband Network",
        "edgeRequestKeepAliveStatus": 1
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 1
}
第三次错误日志是
{
  "outcome": "exception",
  "scriptName": "alist",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "name": "SyntaxError",
      "message": "Unexpected end of JSON input",
      "timestamp": 1692256496396
    }
  ],
  "logs": [],
  "eventTimestamp": 1692256495824,
  "event": {
    "request": {
      "url": "https://p.bacon123.eu.org/onedrive%20cf%E4%BB%A3%E7%90%86/onedrive%E5%85%AC%E5%BC%80/%E7%9F%A5%E4%B9%8E%E5%85%AC%E5%BC%80%E8%AF%BE3%E8%A1%8C%E6%B5%8B%E7%A7%92%E6%9D%80.mp4?sign=REDACTED=:1692472484",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "zh-CN,zh;q=0.9",
        "cf-connecting-ip": "202.64.124.163",
        "cf-ipcountry": "HK",
        "cf-ray": "7f801f7adf57098f",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "p.bacon123.eu.org",
        "range": "bytes=0-",
        "sec-ch-ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "video",
        "sec-fetch-mode": "no-cors",
        "sec-fetch-site": "cross-site",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "202.64.124.163"
      },
      "cf": {
        "clientTcpRtt": 10,
        "longitude": "114.15010",
        "latitude": "22.29080",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 9381,
        "clientAcceptEncoding": "identity;q=1, *;q=0",
        "country": "HK",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "c732250c400180fbf9715bd9229347b275f63562837c14b37aad0831109880ab",
          "clientHandshake": "4ef3164b33ff10c9054dcb9deb38623bcf54f8a83f11866f96146df237120d80",
          "serverHandshake": "a3cf1f97af8e2cd9715201930252a8f50248ea2a8347bbdd576feadc93f8026d",
          "serverFinished": "9aab48338d504549a03a63a08c24d4ddfe9590d6ea5eee51716490ad01d9abad"
        },
        "tlsVersion": "TLSv1.3",
        "city": "Central",
        "timezone": "Asia/Hong_Kong",
        "region": "Central and Western District",
        "requestPriority": "weight=147;exclusive=1",
        "colo": "HKG",
        "httpProtocol": "HTTP/2",
        "regionCode": "HCW",
        "asOrganization": "Hong Kong Broadband Network",
        "edgeRequestKeepAliveStatus": 1
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 2
}

**Comment by xhofe** [comment]
我需要管理员账户debug，mailto:i@nn.ci

**Comment by xhofe** [comment]
发的密码似乎不正确

**Comment by xhofe** [comment]
你现在使用似乎是最新的release 3.25.1 而不是测试版

**Comment by xhofe** [comment]
请使用新的脚本 https://github.com/alist-org/alist-proxy/blob/main/alist-proxy.js

**Comment by ypq123456789** [comment]
感谢光速修复，现在已经没有任何问题了，辛苦了，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alist-org/alist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月17日(星期四) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alist-org/alist] 测试版使用cloudflare workers在线播放和webdav播放onedrive网盘仍出现问题 (Issue #5021)





 
请使用新的脚本 https://github.com/alist-org/alist-proxy/blob/main/alist-proxy.js
