### ISSUE TITLE
挂载索引问题

### ISSUE THREAD

**Issue by shadowofgost** [alist-org/alist#5022]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

用alist v3.25.1 对alist v3.25.1 进行嵌套挂载，子系统开启允许挂载和允许索引选项。但是在母系统中用管理员信息挂载子系统后开启索引索引数量是0.请添加 webdav和alist 挂载的索引功能

**Comment by xhofe** [comment]
无法复现
![image](https://github.com/alist-org/alist/assets/36558727/8289894e-4db7-4c52-98e9-7c7ed1600684)

![image](https://github.com/alist-org/alist/assets/36558727/e574ae5a-5a51-47dd-94ee-b76e4521b83b)

**Comment by shadowofgost** [comment]
![image](https://github.com/alist-org/alist/assets/59472916/48fc84b5-ef5f-4dc3-8bca-e3f1bac62826)
![image](https://github.com/alist-org/alist/assets/59472916/6534fb32-fce2-4571-9704-b6c369b1c68f)
![image](https://github.com/alist-org/alist/assets/59472916/4a2570c2-8c7e-4965-866c-c97824ed48bd)
是这样的，被挂载的站点开启允许索引但是没有用

**Comment by shadowofgost** [comment]
具体来说，我在第一个alist上挂载了百度网盘和阿里云盘，在第二个上挂载第一个alist，第一个alist允许挂载和索引，但是结果是第二个alist索引数为0

**Comment by shadowofgost** [comment]
> 无法复现 ![image](https://user-images.githubusercontent.com/36558727/261787725-8289894e-4db7-4c52-98e9-7c7ed1600684.png)
> 
> ![image](https://user-images.githubusercontent.com/36558727/261787709-e574ae5a-5a51-47dd-94ee-b76e4521b83b.png)

请看一下最新的回复
