### ISSUE TITLE
索引生成过慢

### ISSUE THREAD

**Issue by shadowofgost** [alist-org/alist#5023]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在v3.25.1中，挂载百度网盘生成索引时速度过慢，平均为每秒4个，一个小时只能索引4000个左右的文件。反观onedrive，半个多小时可以索引全部的8万多份文件。文件结构相同。请问有没有解决方法还是百度网盘进行了限制

**Comment by xhofe** [comment]
索引的方式对于所有的driver都相同 仅取决于机器向相关driver的请求速度。
