### ISSUE TITLE
Dropbox添加成功后无法读取文件

### ISSUE THREAD

**Issue by graysui** [alist-org/alist#5024]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

dropbox

### Describe the bug / 问题描述

文件夹可以正确打开，文件无法打开
提示错误 failed link: failed get link: {}:

### Reproduction / 复现链接

http://ip:5244/dp/%E5%89%A7%E9%9B%86/%E7%BA%AA%E5%BD%95%E7%89%87/%E4%B8%83%E4%B8%AA%E4%B8%96%E7%95%8C%EF%BC%8C%E4%B8%80%E4%B8%AA%E6%98%9F%E7%90%83%20(2019)/Season%201/%E4%B8%83%E4%B8%AA%E4%B8%96%E7%95%8C%EF%BC%8C%E4%B8%80%E4%B8%AA%E6%98%9F%E7%90%83%20-%20S01E02%20-%20%E7%AC%AC2%E9%9B%86.mkv

### Config / 配置

使用的自己的客户端id和密钥
![97bef320b1d23bf2d73d2074e7d7a21](https://github.com/alist-org/alist/assets/131964332/31a7516c-4e92-4d78-bdee-cebc686bdd8b)

### Logs / 日志

[31mERRO[0m[2023-08-17 03:00:50] failed link /dp/剧集/纪录片/七个世界，一个星球 (2019)/Season 1/七个世界，一个星球 - S01E02 - 第2集.mkv: {}:
failed get link
github.com/alist-org/alist/v3/internal/op.Link.func1
	/home/runner/work/alist/alist/internal/op/fs.go:253
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.Link
	/home/runner/work/alist/alist/internal/op/fs.go:263
github.com/alist-org/alist/v3/internal/fs.link
	/home/runner/work/alist/alist/internal/fs/link.go:19
github.com/alist-org/alist/v3/internal/fs.Link
	/home/runner/work/alist/alist/internal/fs/fs.go:48
github.com/alist-org/alist/v3/server/handles.FsGet
	/home/runner/work/alist/alist/server/handles/fsread.go:289
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/runner/work/alist/alist/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/http/server.go:2936
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/http/server.go:1995
runtime.goexit
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/asm_arm64.s:1172
failed link 
[GIN] 2023/08/17 - 03:00:50 | 200 |    153.9334ms | 103.171.177.217 | POST     "/api/fs/get"

**Comment by xhofe** [comment]
请检查你的client权限设置。
