### ISSUE TITLE
Safari浏览器无法预览视频

### ISSUE THREAD

**Issue by wisinfun** [alist-org/alist#5026]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

迅雷云盘、天翼云盘

### Describe the bug / 问题描述

在Mac上使用Safari浏览器无法预览视频，苹果手机Safari浏览器也是同样的问题
切换到Chrome浏览器是能正常预览的

### Reproduction / 复现链接

暂无链接

### Config / 配置

暂无配置

**Comment by xhofe** [comment]
https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E8%83%BD%E9%A2%84%E8%A7%88%E8%A7%86%E9%A2%91%E6%88%96%E9%9F%B3%E9%A2%91%E6%96%87%E4%BB%B6
