### ISSUE TITLE
视频播放不能跳转到vlc

### ISSUE THREAD

**Issue by CrazyJasonwell** [alist-org/alist#5029]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

任意

### Describe the bug / 问题描述

mac microsoft edge 浏览器，在视频播放器点击vlc，不跳转，我电脑装了vlc app 能正常使用，点击infuse可以跳转infuse app 播放。
vlc://https://xxx./xxx.mp4 没反应。

### Reproduction / 复现链接

mac microsoft edge 浏览器，在视频播放器点击vlc，不跳转，我电脑装了vlc app 能正常使用，点击infuse可以跳转infuse app 播放。
vlc://https://xxx./xxx.mp4 没反应。

### Config / 配置

mac microsoft edge 浏览器，在视频播放器点击vlc，不跳转，我电脑装了vlc app 能正常使用，点击infuse可以跳转infuse app 播放。
vlc://https://xxx./xxx.mp4 没反应。

### Logs / 日志

mac microsoft edge 浏览器，在视频播放器点击vlc，不跳转，我电脑装了vlc app 能正常使用，点击infuse可以跳转infuse app 播放。
vlc://https://xxx./xxx.mp4 没反应。

**Comment by CrazyJasonwell** [comment]
请提供重复问题的编号好吗？我没找到。

**Comment by xhofe** [comment]
善用搜索

- #911

**Comment by CrazyJasonwell** [comment]
> 善用搜索
> 
> * [请求加入VLC电脑版调用播放 #911](https://github.com/alist-org/alist/issues/911)

多谢！
