### ISSUE TITLE
123网盘报错导致启动慢，无法删除123网盘

### ISSUE THREAD

**Issue by xixky** [alist-org/alist#5030]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

123网盘

### Describe the bug / 问题描述

123网盘报错导致启动慢，无法删除123网盘

### Reproduction / 复现链接

Aug 18 02:34:50 instance-20210826-1504 alist[65438]: 2023/08/18 02:34:50.732990 ERROR RESTY Post "https://www.123pan.com/api/user/logout": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
Aug 18 02:35:07 instance-20210826-1504 alist[65438]: 2023/08/18 02:35:07.217681 ERROR RESTY Post "https://www.123pan.com/api/user/logout": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
Aug 18 02:35:20 instance-20210826-1504 alist[65438]: 2023/08/18 02:35:20.933399 ERROR RESTY Post "https://www.123pan.com/api/user/logout": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
Aug 18 02:35:37 instance-20210826-1504 alist[65438]: 2023/08/18 02:35:37.487102 ERROR RESTY Post "https://www.123pan.com/api/user/logout": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 4
Aug 18 02:35:51 instance-20210826-1504 alist[65438]: 2023/08/18 02:35:51.180401 ERROR RESTY Post "https://www.123pan.com/api/user/logout": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 4
Aug 18 02:36:07 instance-20210826-1504 alist[65438]: 2023/08/18 02:36:07.175006 ERROR RESTY Post "https://www.123pan.com/api/user/logout": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
Aug 18 02:36:37 instance-20210826-1504 alist[65438]: 2023/08/18 02:36:37.276486 ERROR RESTY Post "https://www.123pan.com/api/user/logout": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
Aug 18 02:37:07 instance-20210826-1504 alist[65438]: 2023/08/18 02:37:07.457058 ERROR RESTY Post "https://www.123pan.com/api/user/logout": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
Aug 18 02:37:37 instance-20210826-1504 alist[65438]: 2023/08/18 02:37:37.840400 ERROR RESTY Post "https://www.123pan.com/api/user/logout": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 4
Aug 18 02:38:07 instance-20210826-1504 alist[65438]: 2023/08/18 02:38:07.865216 ERROR RESTY Get "https://www.123pan.com/api/user/info": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xxx,
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": false
}

### Logs / 日志

![AXBV}Q@~1ZV3B$ ~0{CH46K](https://github.com/alist-org/alist/assets/21142462/31fe085e-8cfe-47e0-a348-8b14099bddc6)
![SGA B5S{JU)3G)X_DQ7FTJW](https://github.com/alist-org/alist/assets/21142462/189fa0cf-02d2-45e5-870e-16623db3f96b)
![1692326492220](https://github.com/alist-org/alist/assets/21142462/3fd4bfda-d8db-4636-8df4-b9e1c98a8d0d)

**Comment by anwen-anyi** [comment]
等待进入后台后  直接删除就可以，可能需要等待一会儿. 但是别再添加了

**Comment by kuyoos** [comment]
同样的问题

**Comment by anwen-anyi** [comment]
> 同样的问题

删了别再添加了

**Comment by xhofe** [comment]
https://github.com/alist-org/alist/issues/4961#issuecomment-1673184342
