### ISSUE TITLE
使用cf workers代理时仍然500错误

### ISSUE THREAD

**Issue by DEV4895** [alist-org/alist#5031]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

OnedriveAPP

### Describe the bug / 问题描述

自从alist-proxy.js 的https://github.com/alist-org/alist-proxy/commit/0b02d5968b5682887417ada3e9555fe42f5f791f
这次提交后，在更新了workers代码后仍然报500.
![image](https://github.com/alist-org/alist/assets/101171334/e8c84b76-9c9d-4485-8feb-d336c1c6c22e)

### Reproduction / 复现链接

https://003225.xyz/alist

### Config / 配置

注：使用远程数据库
{
  "force": false,
  "site_url": "/alist",
  "cdn": "",
  "jwt_secret": "{hide}",
  "token_expires_in": 48,
  "database": {
    "type": "mysql",
    "host": "{hide}",
    "port": {hide},
    "user": "{hide}",
    "password": "{hide}",
    "name": "{hide}",
    "db_file": "data/data.db",
    "table_prefix": "{hide}",
    "ssl_mode": "true"
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

### Logs / 日志

这是请求一个文件所产生的日志
[36mINFO[0m[2023-08-18 06:33:13] index obj count: 4                           
[36mINFO[0m[2023-08-18 06:33:15] index obj count: 3                           
[36mINFO[0m[2023-08-18 06:33:15] index obj count: 2                           
[36mINFO[0m[2023-08-18 06:33:18] index obj count: 4                           
[36mINFO[0m[2023-08-18 06:33:20] index obj count: 3                           
[36mINFO[0m[2023-08-18 06:33:20] index obj count: 2                           
[36mINFO[0m[2023-08-18 06:33:23] index obj count: 4                           
[GIN] 2023/08/18 - 06:33:24 | 302 |  566.281467ms |    172.104.42.5 | GET      "/alist/d/Sharepoint_DEV4895/Games/Dead Cells/setup.exe?sign=Qs1GBh5nZhU_I7tho_07jMIt_sSY9xo3xnY-_d8O2lo=:1692340308"
[36mINFO[0m[2023-08-18 06:33:25] index obj count: 3                           
[36mINFO[0m[2023-08-18 06:33:25] index obj count: 2                           
[GIN] 2023/08/18 - 06:33:26 | 200 |  1.281786265s | 2a06:98c0:3600::103 | POST     "/alist/api/fs/link"
Error #01: common.Resp[interface {}].Data: model.Link.PartSize: Concurrency: IPCacheKey: Expiration: ReadSeekCloser: RangeReadCloser: model.RangeReadCloser.Closers: RangeReader:  RangeReadCloser RangeReadermodel.RangeReaderFunc is unsupported type
[36mINFO[0m[2023-08-18 06:33:28] index obj count: 4                           
[36mINFO[0m[2023-08-18 06:33:30] index obj count: 3                           
[36mINFO[0m[2023-08-18 06:33:30] index obj count: 2                           
[36mINFO[0m[2023-08-18 06:33:33] index obj count: 4                           

到此为止cf页面报出Worker threw exception

重定向的代理链接为https://alist-proxy.nawa.gq/Sharepoint_DEV4895/Games/Dead%20Cells/setup.exe?sign=zHKkWfdCgcGHBsCvnga7kweQDlGlZ0AANBBI61GJiJo=:1692340404

![image](https://github.com/alist-org/alist/assets/101171334/9790753e-284b-4a33-b1f7-e760740bc646)

**Comment by xhofe** [comment]
#4971

**Comment by benzBrake** [comment]
今天刚挂 Google Drive，一样的问题

**Comment by yurhett** [comment]
@benzBrake 仔细读文档填写链接，我刚才就是填错了，URL后面不能有“/”

**Comment by Sunhelter** [comment]
同 error 1101，之前可以，半个月前OneDrive不能用了，按最新的代码部署上去也还是 error 1101

**Comment by DoiiarX** [comment]
没有斜杠。同样问题。

**Comment by DoiiarX** [comment]
解决。奇奇怪怪。有一个原因是我代理的某一个磁盘是挂载的本地磁盘。不能用代理。结果我在那个地方测试。。。
