### ISSUE TITLE
请求添加插件支持（webhook）

### ISSUE THREAD

**Issue by tempwswm** [alist-org/alist#5032]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist 发展至今在文件挂载功能上已经非常完善
但各种自动化功能的需求也很大，与产品定位合的也不适宜合并入代码库
也具备可以扩大社区的条件了
插件需求：
1、提供外部调用alist 相关方法（前后端分离已有，请整理API文档，感谢 https://github.com/alist-org/docs/pull/258 ）
2、alist产生的各类变化通知到外部。

### Suggested solution / 实现思路

针对alist各项操作的hook，golang为编译语言，加载插件可能不便
同时面对自动化类插件需求，python，shell等脚本语言更有优势
以上为个人观点，人生苦短，我用python

建议使用webhook功能通知外部系统响应变更，与web接口同一为fs层即可
再执行完成后调用webhook更好，在收到web请求后转发给webhook则更为简单快速

### Additional context / 附件

暂无

**Comment by tempwswm** [comment]
还有一部分原因是我的pr没合并，每次我想跟上主仓库版本就要syncfork 处理冲突然后部署
麻烦的捏(～￣▽￣)～

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/pull/4230  有，但是好像也也只是一个测试demo，并未深度开发

**Comment by foxxorcat** [comment]
我在想或许等wasi完善了用wasi更好一点 https://github.com/stealthrocket/wasi-go。这样也可以兼顾多个语言

**Comment by tempwswm** [comment]
> 人生苦短，我用python

**Comment by tempwswm** [comment]
人生苦短，我用python
做了个python包装
https://github.com/tempwswm/alistclient
