### ISSUE TITLE
点击上传文件夹时，文件夹内的文件最多只能有100个，之前也有别人提过，半年了能不能修好了？

### ISSUE THREAD

**Issue by 2218153** [alist-org/alist#5034]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

aliyun

### Describe the bug / 问题描述

所有的漫画 单文件夹文件多于100的全部丢失，图片也是，视频也是。只读取100个文件剩下的自动无效。
**必须手动选择所有文件而非文件夹才能做到上传多于100个文件，这一点为什么不用斗大的字说清楚？**不是每个人开始就能用大量文件夹测试的，前面文件少的测试没问题直接麻痹了，半夜里自动上传，24小时后本地文件已经删除灭失。

### 我不知道你们是怎么做事的，这个bug半年前就有人提了。你们出来解释解释？？？

[12189108](https://github.com/12189108) commented [on Nov 17, 2022](https://github.com/alist-org/alist/issues/2404#issue-1453574675) • 
Please make sure of the following things
 I have read the [documentation](https://alist.nn.ci/).
 I'm sure there are no duplicate issues or discussions.
 I'm sure it's due to alist and not something else(such as Dependencies or Operational).
 I'm sure I'm using the latest version
Alist Version / Alist 版本
v3.4.0

Driver used / 使用的存储驱动
任何存储驱动

Describe the bug / 问题描述
在Windows下，点开上传按钮，出现上传窗口，在资源管理器(explorer.exe)里拖动文件夹至上传窗口，只会上传100个文件

Reproduction / 复现链接
Logs / 日志

### Reproduction / 复现链接

人都死了你问我要心电图是吧？

### Config / 配置

如果有控制文件数的请你告诉我，我谢谢你。

### Logs / 日志

丢了10w+的图片文件。我谢谢你

**Comment by arstum** [comment]
As of March 3, 2024, are there still quantity limit issues?

**Comment by yohototo** [comment]
> As of March 3, 2024, are there still quantity limit issues?

yes，still
