### ISSUE TITLE
从挂载的本地存储给挂载的百度网盘复制文件时原文件会被删除

### ISSUE THREAD

**Issue by Oliv1a** [alist-org/alist#5037]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

从挂载的本地存储（驱动：本机存储）给挂载的百度网盘（接口：官方）复制文件或者文件夹时，当复制任务完成后，本地存储里的源文件会被删除（等同于执行了“移动”操作，复制文件夹时源文件夹内的文件会被删除，文件夹会保留）

### Reproduction / 复现链接

非常抱歉受限于网络环境无法提供公网可访问的链接，但应该可以轻易复现。

### Config / 配置

![IMG_2450](https://github.com/alist-org/alist/assets/91003254/712148dd-0ade-4883-881d-9e1bfc05cc20)
![IMG_2451](https://github.com/alist-org/alist/assets/91003254/190aba84-a762-4b74-9b94-863a6b6b0c69)

**Comment by anwen-anyi** [comment]
已经修复了 目前好像从本地复制到任意网盘 本地的都会被删除
