### ISSUE TITLE
建议新增全局上传下载限速

### ISSUE THREAD

**Issue by BugKun** [alist-org/alist#5039]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

由于上传文件时把上传带宽跑满了，导致其他设备出现严重丢包的问题。又因为部署alist的机器也跑着其他服务，为了保证其他服务的质量，希望只限制alist的网速。
1. 建议在设置中新增全局上传下载限速功能
2. 建议在设置中新增任务并行数量设置，可以按需调整并发任务数

**Comment by BugKun** [comment]
> 这个你可以用第三方软件实现 比如各种安全软件的限速功能

放在linux上用的，没有好用的基于应用限速的软件

**Comment by BugKun** [comment]
> 谷歌搜一下 linux 限速

是有限速软件，但不好用，要么是基于网口限速的，要么是基于ip限速的，我也不知道外部网盘的所有cdn的ip地址，也没法限速

**Comment by BugKun** [comment]
> 加个 进程

你说trickle吗？这个每次调整限速都要重启服务，不好用。或者你觉得有好用的麻烦推荐一下

**Comment by manduted** [comment]
确实。。如有个时间段+全局限速就好了。。每次都是手动调路由器

**Comment by NovaShen555** [comment]
基于端口限速，就限内网alist端口

**Comment by BugKun** [comment]
> 基于端口限速，就限内网alist端口

那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？

**Comment by NovaShen555** [comment]
> > 基于端口限速，就限内网alist端口
> 
> 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？

你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分

**Comment by BugKun** [comment]
> > > 基于端口限速，就限内网alist端口
> > 
> > 
> > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> 
> 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分

你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了

**Comment by NovaShen555** [comment]
> > > > 基于端口限速，就限内网alist端口
> > > 
> > > 
> > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > 
> > 
> > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> 
> 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了

1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的

**Comment by manduted** [comment]
> > > > > 基于端口限速，就限内网alist端口
> > > > 
> > > > 
> > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > 
> > > 
> > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > 
> > 
> > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> 
>     1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> 
>     2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的

对的。我是直接traefik反代+反代的authentik验证+Alist开启游客模式。。我只是觉得nginx那些的限速不咋样。而且不支持我的时间段需求，nginx和caddy有没有时间段就不知道了。。。
我现在是直接上了物理硬件磊科做流控。新开个NPM的docker反代单独走磊科那边。

**Comment by BugKun** [comment]
> > > > > 基于端口限速，就限内网alist端口
> > > > 
> > > > 
> > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > 
> > > 
> > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > 
> > 
> > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> 
> 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的

1. 没说你的方案不行，但可以说不适合大多数alist用户
2. 确实没有nginx做反代，我没有对外开放访问的需求

**Comment by NovaShen555** [comment]
> > > > > > 基于端口限速，就限内网alist端口
> > > > > 
> > > > > 
> > > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > > 
> > > > 
> > > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > > 
> > > 
> > > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> > 
> > 
> > ```
> > 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> > 
> > 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的
> > ```
> 
> 对的。我是直接traefik反代+反代的authentik验证+Alist开启游客模式。。我只是觉得nginx那些的限速不咋样。而且不支持我的时间段需求，nginx和caddy有没有时间段就不知道了。。。 我现在是直接上了物理硬件磊科做流控。新开个NPM的docker反代单独走磊科那边。

这些nginx功能挺少，就能限速好像
而且，不论是硬件还是软件，你这不都是多加了一层么
我猜这种只做限速的反代github上应该是有轮子的

**Comment by manduted** [comment]
> > > > > > > 基于端口限速，就限内网alist端口
> > > > > > 
> > > > > > 
> > > > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > > > 
> > > > > 
> > > > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > > > 
> > > > 
> > > > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> > > 
> > > 
> > > ```
> > > 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> > > 
> > > 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的
> > > ```
> > 
> > 
> > 对的。我是直接traefik反代+反代的authentik验证+Alist开启游客模式。。我只是觉得nginx那些的限速不咋样。而且不支持我的时间段需求，nginx和caddy有没有时间段就不知道了。。。 我现在是直接上了物理硬件磊科做流控。新开个NPM的docker反代单独走磊科那边。
> 
> 这些nginx功能挺少，就能限速好像 而且，不论是硬件还是软件，你这不都是多加了一层么 我猜这种只做限速的反代github上应该是有轮子的

恩。我是没办法。这些反代限速是有。不过整的就跟我开关路由器限速一样了。所以我嫌麻烦。直接上了硬件 - -。其实开个爱快虚拟机都行的。

**Comment by NovaShen555** [comment]
> > > > > > 基于端口限速，就限内网alist端口
> > > > > 
> > > > > 
> > > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > > 
> > > > 
> > > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > > 
> > > 
> > > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> > 
> > 
> > 
> > 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> > 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的
> 
> 1. 没说你的方案不行，但可以说不适合大多数alist用户，不是每个用户都有这技术
> 2. 确实没有nginx做反代，我没有对外开放访问的需求

1. 善于找轮子
2. 内网访问也可以做反代啊。。。除非你做v6防火墙，不然现在家庭内网和外网没区别

**Comment by BugKun** [comment]
> > > > > > > 基于端口限速，就限内网alist端口
> > > > > > 
> > > > > > 
> > > > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > > > 
> > > > > 
> > > > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > > > 
> > > > 
> > > > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> > > 
> > > 
> > > 
> > > 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> > > 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的
> > 
> > 
> > 
> > 1. 没说你的方案不行，但可以说不适合大多数alist用户，不是每个用户都有这技术
> > 2. 确实没有nginx做反代，我没有对外开放访问的需求
> 
> 1. 善于找轮子
> 2. 内网访问也可以做反代啊。。。除非你做v6防火墙，不然现在家庭内网和外网没区别

1. 还是上面说的，不适合大多数alist用户，不是每个用户都有这技术和有这个时间
2. 内网访问没必要上反代，有点多此一举，而且即使在alist前套一个nginx对我也没用，我上传的都是服务器里的本地文件，不经过nginx

**Comment by NovaShen555** [comment]
> > > > > > > > 基于端口限速，就限内网alist端口
> > > > > > > 
> > > > > > > 
> > > > > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > > > > 
> > > > > > 
> > > > > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > > > > 
> > > > > 
> > > > > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> > > > 
> > > > 
> > > > ```
> > > > 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> > > > 
> > > > 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的
> > > > ```
> > > 
> > > 
> > > 对的。我是直接traefik反代+反代的authentik验证+Alist开启游客模式。。我只是觉得nginx那些的限速不咋样。而且不支持我的时间段需求，nginx和caddy有没有时间段就不知道了。。。 我现在是直接上了物理硬件磊科做流控。新开个NPM的docker反代单独走磊科那边。
> > 
> > 
> > 这些nginx功能挺少，就能限速好像 而且，不论是硬件还是软件，你这不都是多加了一层么 我猜这种只做限速的反代github上应该是有轮子的
> 
> 恩。我是没办法。这些反代限速是有。不过整的就跟我开关路由器限速一样了。所以我嫌麻烦。直接上了硬件 - -。其实开个爱快虚拟机都行的。

tc+iptable写个脚本就可以，不过确实，就，见仁见智咯

**Comment by NovaShen555** [comment]
> > > > > > > > 基于端口限速，就限内网alist端口
> > > > > > > 
> > > > > > > 
> > > > > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > > > > 
> > > > > > 
> > > > > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > > > > 
> > > > > 
> > > > > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> > > > 
> > > > 
> > > > 
> > > > 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> > > > 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的
> > > 
> > > 
> > > 
> > > 1. 没说你的方案不行，但可以说不适合大多数alist用户，不是每个用户都有这技术
> > > 2. 确实没有nginx做反代，我没有对外开放访问的需求
> > 
> > 
> > 
> > 1. 善于找轮子
> > 2. 内网访问也可以做反代啊。。。除非你做v6防火墙，不然现在家庭内网和外网没区别
> 
> 1. 还是上面说的，不适合大多数alist用户，不是每个用户都有这技术和有这个时间
> 2. 内网访问没必要上反代，有点多此一举，而且即使在alist前套一个nginx对我也没用，我上传的都是服务器里的本地文件，不经过nginx

上传的都是服务器里的本地文件？好奇怪的需求 😂

**Comment by manduted** [comment]
> > > > > > > > > 基于端口限速，就限内网alist端口
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > > > > > 
> > > > > > > 
> > > > > > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > > > > > 
> > > > > > 
> > > > > > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> > > > > 
> > > > > 
> > > > > ```
> > > > > 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> > > > > 
> > > > > 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的
> > > > > ```
> > > > 
> > > > 
> > > > 对的。我是直接traefik反代+反代的authentik验证+Alist开启游客模式。。我只是觉得nginx那些的限速不咋样。而且不支持我的时间段需求，nginx和caddy有没有时间段就不知道了。。。 我现在是直接上了物理硬件磊科做流控。新开个NPM的docker反代单独走磊科那边。
> > > 
> > > 
> > > 这些nginx功能挺少，就能限速好像 而且，不论是硬件还是软件，你这不都是多加了一层么 我猜这种只做限速的反代github上应该是有轮子的
> > 
> > 
> > 恩。我是没办法。这些反代限速是有。不过整的就跟我开关路由器限速一样了。所以我嫌麻烦。直接上了硬件 - -。其实开个爱快虚拟机都行的。
> 
> tc+iptable写个脚本就可以，不过确实，就，见仁见智咯

确实。。tc+iptable是可以。都试过。效果只能说还行。我Unraid的脚本都还在。不过还是嫌麻烦。直接300块上硬件。哈哈哈哈哈。。要不是nas性能不够。不然直接最简单就是 ikuai的虚拟机

**Comment by BugKun** [comment]
> > > > > > > > > 基于端口限速，就限内网alist端口
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > > > > > 
> > > > > > > 
> > > > > > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > > > > > 
> > > > > > 
> > > > > > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> > > > > 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的
> > > > 
> > > > 
> > > > 
> > > > 1. 没说你的方案不行，但可以说不适合大多数alist用户，不是每个用户都有这技术
> > > > 2. 确实没有nginx做反代，我没有对外开放访问的需求
> > > 
> > > 
> > > 
> > > 1. 善于找轮子
> > > 2. 内网访问也可以做反代啊。。。除非你做v6防火墙，不然现在家庭内网和外网没区别
> > 
> > 
> > 
> > 1. 还是上面说的，不适合大多数alist用户，不是每个用户都有这技术和有这个时间
> > 2. 内网访问没必要上反代，有点多此一举，而且即使在alist前套一个nginx对我也没用，我上传的都是服务器里的本地文件，不经过nginx
> 
> 上传的都是服务器里的本地文件？好奇怪的需求 😂

不奇怪，例如把一些重要的资料端对端加密，保存在云盘做备份

**Comment by NovaShen555** [comment]
> > > > > > > > > > 基于端口限速，就限内网alist端口
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 那你又怎么知道alist与云盘通讯的端口是什么呢？端口是随机的。如果是并发上传还可能会有多个ip和端口，你又能怎么限制呢？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你并没有说上传到何处，而且，即使是上传到云盘，如果走机子代理上传，那端口一定是确定的啊，因为你就开放了那一个端口供客户端连接，上传速度取决于水桶最低的部分
> > > > > > > 
> > > > > > > 
> > > > > > > 你这是能做限速，但为此你要给alist配置一个代理服务器，感觉这是不是弄得更复杂了
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 1. 我只是提出一个合理的可行的解决方案，**复杂与否见仁见智**，没有什么是多一层做不了的，包括 @manduted 说的时间段+全局限速
> > > > > > 2. 难道你不用nginx等进行反代吗？这些反代都是可以做到限制上传速度的
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. 没说你的方案不行，但可以说不适合大多数alist用户，不是每个用户都有这技术
> > > > > 2. 确实没有nginx做反代，我没有对外开放访问的需求
> > > > 
> > > > 
> > > > 
> > > > 1. 善于找轮子
> > > > 2. 内网访问也可以做反代啊。。。除非你做v6防火墙，不然现在家庭内网和外网没区别
> > > 
> > > 
> > > 
> > > 1. 还是上面说的，不适合大多数alist用户，不是每个用户都有这技术和有这个时间
> > > 2. 内网访问没必要上反代，有点多此一举，而且即使在alist前套一个nginx对我也没用，我上传的都是服务器里的本地文件，不经过nginx
> > 
> > 
> > 上传的都是服务器里的本地文件？好奇怪的需求 😂
> 
> 不奇怪，例如把一些重要的资料端对端加密，保存在云盘做备份

不过我觉得你这个需求其实挺合理的，能直接做出来肯定会方便很多

**Comment by fflrichard** [comment]
我也有这个需求，家里的宽带电信上传速度才5MB不到，一上传东西占用全部带宽然后整个网络就出故障了。用的是电视盒子装的armbian，插了个移动硬盘，经常需要上传一些东西，只能用路由器限速。如果能有上传限速功能就太棒了。
