### ISSUE TITLE
中国移动云盘无法正常下载

### ISSUE THREAD

**Issue by xx6z8v** [alist-org/alist#5047]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

中国移动云盘

### Describe the bug / 问题描述

问题与[本issue2763](https://github.com/alist-org/alist/issues/2763)类似,需要复制链接下载,无法直接使用下载按钮进行下载,会出现403提示

PS:在Android系统上,我测试了Via,X,雨见,FirefoxNightly共4款浏览器,只有Via出现此问题

### Reproduction / 复现链接

任意Alist挂载的中国移动云盘的下载链接

### Logs / 日志

# 下面是403复现
***
<h1 style="color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">403 Forbidden</h1><p style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">You don't have permission to access the URL on this server. Sorry for the inconvenience.<br>Please report this message and include the following information to us.<br>Thank you very much!</p>

URL: | (此处是真实文件的下载链接,故屏蔽)
-- | --
Server: | dgnginx90
Date: | 2023/08/19 16:36:38

<hr style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Powered by Tengine</span>

**Comment by xhofe** [comment]
如果via 无视Referrer-Policy meta的话， 你应该向via反馈， 而不是这儿。
