### ISSUE TITLE
谷歌相册无法打开

### ISSUE THREAD

**Issue by kissunyeason** [alist-org/alist#5056]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

Google Photos

### Describe the bug / 问题描述

1、开启谷歌云盘api
2、开启photos api
3、挂载后能看到《全部媒体》《全部影集》《共享影集》
4、打开后一直转圈，数十秒后提示failed get objs: failed to list objs: Get "https://photoslibrary.googleapis.com/v1/sharedAlbums?fields=sharedAlbums%28id%2Ctitle%2CcoverPhotoBaseUrl%29%2CnextPageToken&pageSize=50&pageToken=": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### Reproduction / 复现链接

我并不知道要填什么链接，是需要我开启访问权限给你？或者说这样？
http://0.0.0.0:5244/%E8%B0%B7%E6%AD%8C%E7%9B%B8%E5%86%8C

### Config / 配置

驱动：谷歌相册
挂载路径：/谷歌相册
webdav策略：本机代理
根文件ID：root
启用签名：是/否
刷新令牌
1//0e*******
客户端ID
636402113252-mk************ontent.com
客户端密钥
GOC**********ZZ4D
显示归档：是/否均测试

**Comment by anwen-anyi** [comment]
- 哪里搭建的？
    - 本机搭建的？
- 能裸连谷歌？

**Comment by kissunyeason** [comment]
> * 哪里搭建的？
>   
>   * 本机搭建的？
> * 能裸连谷歌？

本机安装了clash，可以打开谷歌相册，开了代理了。

**Comment by kissunyeason** [comment]
> * 哪里搭建的？
>   
>   * 本机搭建的？
> * 能裸连谷歌？

刚才测试了。打开tun模式可以了，但是部分影集内是空的，没有照片，但我确定存了照片

**Comment by anwen-anyi** [comment]
> > * 哪里搭建的？
> >   
> >   * 本机搭建的？
> > * 能裸连谷歌？
> 
> 刚才测试了。打开tun模式可以了，但是部分影集内是空的，我已经删除了影集，这个应该是谷歌的问题，也没有办法直接屏蔽呢？

tun模式是可以，其他的模式不行。
