### ISSUE TITLE
蓝奏云下载提示500 已超时，请刷新

### ISSUE THREAD

**Issue by luomo-pro** [alist-org/alist#5057]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

蓝奏云

### Describe the bug / 问题描述

今天突然发现蓝奏云下载都会报如下错误：
{"code":500,"message":"failed link: failed get link: 已超时，请刷新","data":null}
尝试了账号密码登录、cookie登录，都是一样的问题。
也尝试开启web代理、选择本地代理，也是一样。
并且获取蓝奏云里的文件，都是可以正常获取显示的，就只是下载文件的时候，会报这个错误。

### Reproduction / 复现链接

https://alist.lmdbk.com/d/m/LuomoToolbox.apk

### Config / 配置

无

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/pull/5048

**Comment by luomo-pro** [comment]
@anwen-anyi
抱歉，之前没看到已经提交修复了。
我看现在是还没有发布release版本，不知道何时可以发布？
如果我现在需要windows版的话，有地方可以下载修复后的程序吗？
谢谢！

**Comment by anwen-anyi** [comment]
> @anwen-anyi 抱歉，之前没看到已经提交修复了。 我看现在是还没有发布release版本，不知道何时可以发布？ 如果我现在需要windows版的话，有地方可以下载修复后的程序吗？ 谢谢！

打开 https://github.com/alist-org/alist/actions/runs/5915529259

下载这个里面的就行 里面有Windows版本的.
![image](https://github.com/alist-org/alist/assets/56105412/9005420a-fe23-47ec-8778-d8aa4da08895)

**Comment by luomo-pro** [comment]
万分感谢
