### ISSUE TITLE
上传大文件(甚至不大于1G)无法上传

### ISSUE THREAD

**Issue by GeNi114514** [alist-org/alist#5062]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

OneDrive通过加密挂载上传小文件没问题（比如照片），上传大文件几乎无法上传

### Additional context / 附件

![CU6{F2V 5QM4U(18UJPZC5I](https://github.com/alist-org/alist/assets/140315365/3879d7cf-e579-4029-a7df-5dac81bfcedb)

**Comment by xhofe** [comment]
麻烦发一下浏览器`开发人员工具`中的错误信息

**Comment by kiki-theone** [comment]
> 

确实，我也是多线程失败，单线程可以。
