### ISSUE TITLE
crypt挂载的天翼云盘alist启动时无法加载

### ISSUE THREAD

**Issue by BJAny** [alist-org/alist#5063]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

天翼云盘、crypt

### Describe the bug / 问题描述

重启alist或者已停止的alist启动时，挂载的crypt在天翼云盘上会出现报错，每次都得手动点全部重新加载或者进驱动点保存，测试过序号高低不影响复现bug
![image](https://github.com/alist-org/alist/assets/6690619/220a9e05-1b50-4d46-894f-8fb455b226ac)
![image](https://github.com/alist-org/alist/assets/6690619/f415c8ef-d814-4e23-9cb3-7c81c2b3ad41)

### Reproduction / 复现链接

无

### Config / 配置

无

### Logs / 日志

无

**Comment by xhofe** [comment]
duplicate with #5018
