### ISSUE TITLE
115网盘离线下载功能

### ISSUE THREAD

**Issue by brighteye-233** [alist-org/alist#5069]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否为115网盘增加离线功能，例如在115网盘界面提交磁力链接，能够使用api直接在115网网盘中离线下载

**Comment by rrq0514** [comment]
115连BT种子分析都要收费
