### ISSUE TITLE
离线下载至OneDrive在上传阶段出现错误

### ISSUE THREAD

**Issue by zzh-zzh-zzh** [alist-org/alist#5074]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

使用alist挂载OneDrive，离线下载在上传阶段会被终止，错误如下图
![屏幕截图 2023-08-22 103302](https://github.com/alist-org/alist/assets/82568506/18bc43f8-6d6d-4255-bbd7-938f2f815689)
有时候能够正常上传完成，现在上传失败概率很大。
不清楚是否是alist的原因还是OneDrive的原因。
试过重新注册应用程序也还是一样。

### Reproduction / 复现链接

无

### Config / 配置

![屏幕截图 2023-08-22 103802](https://github.com/alist-org/alist/assets/82568506/b04edb28-d3ab-4d90-8c46-44f2f963995c)

### Logs / 日志

![屏幕截图 2023-08-22 103302](https://github.com/alist-org/alist/assets/82568506/892f369b-ad89-4e24-9c68-dbb083063f2c)

**Comment by xhofe** [comment]
这个提示是onedrive侧关闭了链接。

> https://gosamples.dev/connection-reset-by-peer/

**Comment by zzh-zzh-zzh** [comment]
> 这个提示是onedrive侧关闭了链接。
> 
> > https://gosamples.dev/connection-reset-by-peer/

请问这个有可能是什么原因导致的呢，我试了改分片大小，还是会出现这个，IPv6的原因吗？还是和OneDrive账号有关系

**Comment by xhofe** [comment]
> > 这个提示是onedrive侧关闭了链接。
> > 
> > > https://gosamples.dev/connection-reset-by-peer/
> 
> 请问这个有可能是什么原因导致的呢，我试了改分片大小，还是会出现这个，IPv6的原因吗？还是和OneDrive账号有关系

不清楚 这个可能需要咨询onedrive方

可以试试禁用ipv6

**Comment by zzh-zzh-zzh** [comment]
> > > 这个提示是onedrive侧关闭了链接。
> > > > https://gosamples.dev/connection-reset-by-peer/
> > 
> > 
> > 请问这个有可能是什么原因导致的呢，我试了改分片大小，还是会出现这个，IPv6的原因吗？还是和OneDrive账号有关系
> 
> 不清楚 这个可能需要咨询onedrive方
> 
> 可以试试禁用ipv6

好的，issue就先关了，我再找找原因，想了下应该和alist关系不大

**Comment by Faramitas** [comment]
> > > > 这个提示是onedrive侧关闭了链接。
> > > > > https://gosamples.dev/connection-reset-by-peer/
> > > 
> > > 
> > > 请问这个有可能是什么原因导致的呢，我试了改分片大小，还是会出现这个，IPv6的原因吗？还是和OneDrive账号有关系
> > 
> > 
> > 不清楚 这个可能需要咨询onedrive方
> > 可以试试禁用ipv6
> 
> 好的，issue就先关了，我再找找原因，想了下应该和alist关系不大

我也是这个问题，ipv4公网也不行，但是我直接网页端上传不会出现这个情况，Alist开始是在传的，传着传着速度就慢下来了（几百KB），然后长时间之后，似乎onedrive那边就关闭了链接

**Comment by Faramitas** [comment]
> > > 这个提示是onedrive侧关闭了链接。
> > > > https://gosamples.dev/connection-reset-by-peer/
> > 
> > 
> > 请问这个有可能是什么原因导致的呢，我试了改分片大小，还是会出现这个，IPv6的原因吗？还是和OneDrive账号有关系
> 
> 不清楚 这个可能需要咨询onedrive方
> 
> 可以试试禁用ipv6

![Screenshot_20231016_185257_com microsoft emmx](https://github.com/alist-org/alist/assets/29322214/5dcea984-7ca8-4555-939f-f0c41ff03cbc)
大文件上传，我网页端不会限速，而且这个上传的目标服务器IP竟然是北京的

**Comment by onyourhead** [comment]
> 我也遇到了这个问题。你看看是不是docker安装的。我今天从docker安装换成了一键下载，alist的访问速度快了很多。

我在个人版onedirve碰到这个问题，你的是商业版吗，个人版上传的目标ip是ipv4

**Comment by liangzilixueha** [comment]
我是e5 开发者版本,alist部署在公网服务器上，目前我多半确认是docker网络配置问题，我不走docker后，目前下载过40gb的数据，大的也有2g，没遇见过上传onedrive断开连接的问题
&nbsp;


542876162
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年2月11日(星期二) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AlistGo/alist] 离线下载至OneDrive在上传阶段出现错误 (Issue #5074)














  
我也遇到了这个问题。你看看是不是docker安装的。我今天从docker安装换成了一键下载，alist的访问速度快了很多。
  
我在个人版onedirve碰到这个问题，你的是商业版吗，个人版上传的目标ip是ipv4
