### ISSUE TITLE
Rclone的Crypt支持通过重命名/移动已上传文件来更改filename_encoding ，从而不用重复上传，alist能否支持这个功能？

### ISSUE THREAD

**Issue by haohaohaoadsad** [alist-org/alist#5084]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望alsit支持通过重命名/移动已上传文件的方式来更改filename_encoding
我在使用alist+rclone的时候使用这个功能有些问题，能否在alist上实现一遍？
https://forum.rclone.org/t/convert-filename-encoding/34008

### Suggested solution / 实现思路

Rclone Server side across的文档
https://rclone.org/crypt/#crypt-server-side-across-configs

**Comment by SeanHeuc** [comment]
rclone 既然支持，你为什么不直接用帖子[https://rclone.org/crypt/#crypt-server-side-across-configs] 中的命令批量修改文件名呢？ alist已经提供webdav了，你可以用rclone挂载webdav， 然后你可以按照那个帖子里面的步骤配置两种crypt... 等等步骤操作
