### ISSUE TITLE
上传文件设置单线程运行

### ISSUE THREAD

**Issue by jianboy** [alist-org/alist#5093]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用上传，复制文件夹的功能。默认会一次发起多个任务。但是都是上传失败的情况。

需要用户一个一个上传者不会出现问题。

猜测问题是，云盘（如百度，天翼云盘）等会**限制多个请求同时发起（大文件，长时间链接）**，所以在设置里面添加一个选项，上传文件单线程运行。

**Comment by jianboy** [comment]
这里设置的最大线程数3，希望添加可配置设置项。


https://github.com/alist-org/alist/blob/3504f017b94407ac891fe3dfeed5f4ed5a4fbd53/internal/fs/copy.go#L20


在后台添加一个选项，多线程下载。

![image](https://github.com/alist-org/alist/assets/11532015/b4dbfd9a-2c5f-40db-a462-0d7d9fdfc0a9)

**Comment by thomasdba** [comment]
189网盘也遇到类似的问题，就是在复制目录里，只有最开始几个文件成功，后面就全失败了。
