### ISSUE TITLE
百度网盘api挂了吗

### ISSUE THREAD

**Issue by sw586** [alist-org/alist#5094]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.26

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

failed get objs: failed to list objs: req: [https://pan.baidu.com/rest/2.0/xpan/file] ,errno: -9, refer to https://pan.baidu.com/union/doc/

### Reproduction / 复现链接

https://pan.baidu.com

### Config / 配置

[1](https://pan.baidu.com)

**Comment by nigo81** [comment]
同样问题。failed get objs: failed to list objs: req: [https://pan.baidu.com/rest/2.0/xpan/file] ,errno: -9, refer to https://pan.baidu.com/union/doc/
