### ISSUE TITLE
README.md 文件具有可执行权限

### ISSUE THREAD

**Issue by jimyag** [alist-org/alist#5097]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

no

### Describe the bug / 问题描述

如题，README.md 具有可执行权限

<img width="678" alt="image" src="https://github.com/alist-org/alist/assets/69233189/d195aa0e-8065-445e-a226-ecd81a0121db">

我不确定这是否是预期的，在整个代码库中没有找到需要执行 ‘README.md’

如果这是非预期的，我可以提交 PR 修复。
<img width="657" alt="image" src="https://github.com/alist-org/alist/assets/69233189/59ba33b2-d33d-4fba-9c72-7129a38e8521">

### Reproduction / 复现链接

下载 master 分支代码之后 ls -l，即可查看。

### Config / 配置

无配置。

**Comment by xhofe** [comment]
我不知道这会有什么影响，但是我很乐意接受一个pr。
