### ISSUE TITLE
Crypt能否支持base32768的filename_encoding 

### ISSUE THREAD

**Issue by haohaohaoadsad** [alist-org/alist#5109]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ]   I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望Crypt能增加支持base32768格式的filename_encoding 

### Suggested solution / 实现思路

https://rclone.org/crypt/

**Comment by SeanHeuc** [comment]
这个选项filename_encoding，会在下个版本开放自定义，但是除了base64之外的任何选项不会被测试，遇到问题你只能自己解决。
