### ISSUE TITLE
Alist Nginx二级目录配置后，管理员页面主页点击跳转错误

### ISSUE THREAD

**Issue by FocusProgram** [alist-org/alist#5110]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

在配置Nginx中配置

```
location /alist/ {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_redirect off;
    proxy_pass http://127.0.0.1:5244/alist/;
    # the max size of file to upload
    client_max_body_size 20000m;
}
```

在/data/config.json

```
"site_url": "/alist"
```

在管理员面板中点击主页一直重定向到一级目录：http://127.0.0.1，而不是配置的二级目录：http://127.0.0.1/alist

在查看历史issues中，发现是不是由于solve [alist-org/alist#4784](https://github.com/alist-org/alist/issues/4784) commit [feat: open home in current tab](https://github.com/alist-org/alist-web/commit/966576f0a4052e8db567b49f8f07e55193a71dac) 导致

### Reproduction / 复现链接

Local test, not available

### Config / 配置

其他保持默认，修改如下：

```
"site_url": "/alist"
```

**Comment by xhofe** [comment]
![image](https://github.com/alist-org/alist/assets/36558727/f76b95db-6572-4f09-9a9e-50e2b578a3b7)
未能复现

**Comment by FocusProgram** [comment]
![image](https://github.com/alist-org/alist/assets/44283663/bf5c5afc-a55f-4708-9957-7b31f2d0daf5)

![image](https://github.com/alist-org/alist/assets/44283663/528ecb66-8413-49c7-bba1-5e15a221a1af)

我这边就是Nginx 80代理了一下，没有用默认的5245，点击主页herf是http://p-alist.com/alist，但是点击后就跳转到http://p-alist.com

**Comment by shenlijun** [comment]
确实是最近版本的问题，我刚想发个issue，看来下次版本更新就好了
