### ISSUE TITLE
Local storage preview not working/本地存储预览失效

### ISSUE THREAD

**Issue by lznux** [alist-org/alist#5112]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

local storage

### Describe the bug / 问题描述

本地存储网格形式，不能预览视频封面，图片也不能预览，网盘（我只挂载了阿里云盘和百度云）能正常预览图片和视频封面，本地机器我使用wsl2环境，Ubuntu22，我的亚马逊云instance（ubuntu20）安装alist后同样存在该问题。我使用文档默认docker-cli命令安装alist.
![FireShot Capture 002 - movies - AList - 127 0 0 1](https://github.com/alist-org/alist/assets/108497240/32e96023-66d1-40e1-a602-a16d8028d91a)
![FireShot Capture 003 - 绝命毒师S01 Breaking Bad 2008 2160p WEBrip x265 AC3￡cXcY@FRDS - AList - 127 0 0 1](https://github.com/alist-org/alist/assets/108497240/814d90ad-6ec4-42d2-a32d-66a8f38015e0)

### Reproduction / 复现链接

docker run -d --restart=always -v /etc/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest

### Config / 配置

除挂载文件外，未更改其余设置
![FireShot Capture 001 - 存储 - AList 管理 - 127 0 0 1](https://github.com/alist-org/alist/assets/108497240/08ecdeaa-c57e-48b7-88b4-be5d111d45a2)

**Comment by lznux** [comment]
我注意到之前存在相同bug， #116 #4212 移动或者重命名文件并不能使预览生效

**Comment by anwen-anyi** [comment]
![image](https://github.com/alist-org/alist/assets/56105412/bc1c7aef-caba-49c9-bf57-dd2993bba4f0)

**Comment by wsmbsbbz** [comment]
如果你只在本地使用alist，记得在[`site_url`](https://alist.nn.ci/zh/config/configuration.html#site-url)末尾处加上端口号
Don't forget to add port number to the end of [`site_url`](https://alist.nn.ci/zh/config/configuration.html#site-url) if you only use alist in your local network.
- Right: `"site_url": "http://127.0.0.1:5244"`
- Wrong: `"site_url": "http://127.0.0.1"`

**Comment by Qian119lsj** [comment]
搞不懂这个/api/fs/get请求为什么不用Host的端口拼接
