### ISSUE TITLE
115又不行了，我使用的是桌面版，无法读出目录，阿里云正常

### ISSUE THREAD

**Issue by fanxu1218** [alist-org/alist#5117]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

webDAV

### Describe the bug / 问题描述

115又不行了，我使用的是桌面版，无法读出目录，阿里云正常,不管是路由器版本还是桌面版都不行呢

### Reproduction / 复现链接

没有连接呢，要不加我QQ 380075850，远程让大佬看看

### Config / 配置

115又不行了，我使用的是桌面版，无法读出目录，阿里云正常,不管是路由器版本还是桌面版都不行呢

**Comment by xhofe** [comment]
无法复现 发下日志文件。

**Comment by fanxu1218** [comment]
> 无法复现 请提供日志文件及其他有效信息。

远程我演示给你看看，向日葵 
我的识别码:537190133
验证码8rg770
使用向日葵即可对我发起远程协助
向日葵下载地址:http://url.oray.com/tGJdas/

**Comment by xhofe** [comment]
看不出来 发日志文件

**Comment by fanxu1218** [comment]
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleGetHeadPost
	/source/server/webdav/webdav.go:239
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/source/server/webdav/webdav.go:59
github.com/alist-org/alist/v3/server.ServeWebDAV
	/source/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/source/server/webdav.go:66
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2938
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2009
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650
failed link

**Comment by xhofe** [comment]
更多-打开日志文件夹 日志文件

**Comment by fanxu1218** [comment]
> 看不出来 发日志文件
 我用网盘给你
链接: https://pan.baidu.com/s/1h-d7rQC1jlT7u9lAjxovYw?pwd=7zb4 提取码: 7zb4 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v6的分享
