### ISSUE TITLE
從第3頁的搜索結果開始，無論點擊多少次得到的搜索結果都是保持第2頁。

### ISSUE THREAD

**Issue by ITtest1** [alist-org/alist#5118]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26

### Driver used / 使用的存储驱动

無關網盤的問題

### Describe the bug / 问题描述

當搜索結果有許多頁時，只有最前面2頁和最後面一頁的搜索結果是正確的。
有的時候第3頁也是正確，但是當你從第3頁點擊下一頁進入第4頁後，你得到的是第2頁，無論你點擊多少次下一頁都會是第2頁。這時你點擊第3頁，得到的結果也會是第2頁。

### Reproduction / 复现链接

沒有

### Config / 配置

arm
docker-compose版alist

### Logs / 日志

沒有

**Comment by xhofe** [comment]
至少索引部分的设置得发一下吧……

**Comment by anwen-anyi** [comment]
:joy_cat: 截下图很困难吗~

**Comment by ITtest1** [comment]
> 😹 截下图很困难吗~

我選的是資料庫（非全文搜索），但是我回去索引頁面，會變成是數據庫。因此我認為截圖不能傳達些什麼有用信息。

**Comment by ITtest1** [comment]
up

**Comment by xhofe** [comment]
无法复现。
<img width="735" alt="image" src="https://github.com/alist-org/alist/assets/36558727/c1615142-9220-49cb-8812-379cbc97e7ba">
