### ISSUE TITLE
本机存储的预览链接的Host不正确

### ISSUE THREAD

**Issue by dlnn** [alist-org/alist#5124]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

本机存储的图片/视频预览host是localhost不是域名 导致外部无法访问
![image](https://github.com/alist-org/alist/assets/22004270/161b2e12-593a-483b-b563-dfcee9d1c591)

但是下载生成链接host是正常的反代域名

json文件的预览倒是可以正常替换成反代的域名 

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by anwen-anyi** [comment]
config.json 配置文件里面的site_url填一下？
