### ISSUE TITLE
能否增加支持谷歌google cloud stroage

### ISSUE THREAD

**Issue by GordonHuangYong** [alist-org/alist#5125]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否增加支持谷歌google cloud stroage?

**Comment by xhofe** [comment]
它不是s3兼容的吗
