### ISSUE TITLE
一个文件夹内文件过多大概几十万个文件，总是打不开 每页几百条都加载不出来

### ISSUE THREAD

**Issue by JasonWangJie** [alist-org/alist#5127]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.24

### Driver used / 使用的存储驱动

189cloud

### Describe the bug / 问题描述

一个文件夹内文件过多大概几十万个文件，总是打不开 每页几百条都加载不出来

### Reproduction / 复现链接

没有相关链接

### Config / 配置

![image](https://github.com/alist-org/alist/assets/18652988/532f2e4f-4d9e-4255-aa2b-96eba186c3ab)
![image](https://github.com/alist-org/alist/assets/18652988/68225d5d-41e6-459b-9001-31b2d640f534)

**Comment by JasonWangJie** [comment]
1

**Comment by anwen-anyi** [comment]
要不你再试试每次100条？ 在什么机器上面搭建的？

**Comment by JasonWangJie** [comment]
> 要不你再试试每次100条？ 在什么机器上面搭建的？

没有用 每次几条都没用 其他文件夹内文件少的里面一次1000都正常打开
