### ISSUE TITLE
aliyunopen Driver Enabling Error

### ISSUE THREAD

**Issue by mcmy** [alist-org/alist#5129]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

aliyun open

### Describe the bug / 问题描述

aliyunopen Driver Enabling Error

### Reproduction / 复现链接

https://pan.nfcat.com/

### Config / 配置

https://pan.nfcat.com/fs/local/issue

### Logs / 日志

https://pan.nfcat.com/fs/local/issue

2023/08/31 18:22:28.031966 ERROR RESTY invalid character '<' looking for beginning of value, Attempt 1
ERRO[2023-08-31 18:22:28] failed get enabled storages: invalid character '<' looking for beginning of value
failed init storage
github.com/alist-org/alist/v3/internal/op.initStorage
        /home/runner/work/alist/alist/internal/op/storage.go:99
github.com/alist-org/alist/v3/internal/op.LoadStorage
        /home/runner/work/alist/alist/internal/op/storage.go:80
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
        /home/runner/work/alist/alist/internal/bootstrap/storage.go:20
runtime.goexit
        /opt/hostedtoolcache/go/1.20.7/x64/src/runtime/asm_amd64.s:1598 
2023/08/31 18:22:28.061332 ERROR RESTY invalid character '<' looking for beginning of value, Attempt 1
2023/08/31 18:22:28.082430 ERROR RESTY invalid character '<' looking for beginning of value, Attempt 1
2023/08/31 18:22:28.103859 ERROR RESTY invalid character '<' looking for beginning of value, Attempt 1
2023/08/31 18:22:28.124734 ERROR RESTY invalid character '<' looking for beginning of value, Attempt 1

**Comment by Heathcliff-third-space** [comment]
+1
