### ISSUE TITLE
希望可以增加文件分享连接的到期时间

### ISSUE THREAD

**Issue by c469591** [alist-org/alist#5135]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

你好，因为想把alist挂载后所分享的连接分享出去，但服务器流量有限，因此希望可以增加一个练接到其时间的功能。

### Suggested solution / 实现思路

在复制连接的按钮旁边新增一个设定到期时间的按钮，
点击后可以设置几天后到期，到期之后连接将无法下载，
目前我是使用本地挂载到alist，
感谢！

**Comment by anwen-anyi** [comment]
AList后台设置 --> 全局 --> 直链有效期
自己设置 单位小时

**Comment by c469591** [comment]
能否增加对某些文件的单独设置呢，这个是全局的好像
