### ISSUE TITLE
115网盘WebDav 新版3.26.0没之前稳定了

### ISSUE THREAD

**Issue by sunxiaochuan2506** [alist-org/alist#5136]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v.3.26.0

### Driver used / 使用的存储驱动

115网盘

### Describe the bug / 问题描述

过去的Alist3.11.0版本其中的115网盘，使用快一年的时间。这不到一年的时间，使用起来非常满意。
我是把115网盘以WebDAV的形式挂载到KODI当中。没有出现过Alist崩溃的情况。
但前几天我换成了新版的3.26.0版本。
在刷新电影时，Alist会出现崩溃的情况。即使刷新完毕，在观看电影的时候，因为我的快进后退过于频繁，
新版的Alist扛不住，会崩溃挂掉。需要重启我的软路由，他才能重置。
这种情况在过去的Alist使用当中是没有的。

感谢作者团队，为Alist付出的辛苦贡献！

希望我的这个问题反馈会被您看到。

### Reproduction / 复现链接

无

### Config / 配置

![IIFXRL AT`_6AH71F7GG@5K](https://github.com/alist-org/alist/assets/125409799/0d0e6164-3797-4ba3-9246-f7e0661b965b)

**Comment by 1105169500** [comment]
https://github.com/sbwml/luci-app-alist/issues/80
我遇到与你同样的问题
