### ISSUE TITLE
123云盘挂载 出现 签名错误:ak illegality 999

### ISSUE THREAD

**Issue by xszx** [alist-org/alist#5137]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

列举目录时出现提示

failed get objs: failed to list objs: 签名错误:ak illegality 999

### Reproduction / 复现链接

无

### Config / 配置

![存储 _ AList 管理](https://github.com/alist-org/alist/assets/16921483/ed9a0296-b91a-4217-a608-e0ed40d8d0cc)
![image](https://github.com/alist-org/alist/assets/16921483/38bd7357-e50a-44de-9062-eac0393619ca)

**Comment by wtnwin** [comment]
where to find the solution to the issue? Where is the duplicated one with a solution?
