### ISSUE TITLE
Teambition支持重名文件但是alist不支持

### ISSUE THREAD

**Issue by Sunakier** [alist-org/alist#5142]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

Teambition(CN)

### Describe the bug / 问题描述

我确认我使用的alist版本目前最新（我使用的是v3.26.0），于2023/09/02进行测试，问题存在

我使用了Alist v3.26.0挂载了国区的Teambition(CN)，发现通过Teambition官方的网页端上传文件，是可以上传多个同名文件（相关截图如图1和图2），但是在alist中，只能看到一个文件（如图3），经过测试，通过时间的文件大小判断后续上传的文件会覆盖旧的文件（对于alist是这样的），但是在官方网页可以正常下载之前上传的文件并且可以共存

这个问题应该是alist对于文件名的处理相关问题，理论不难解决，因为调用api所的响应中包含了多个同名文件的相关信息，只是可能会对现有alist的路径产生冲突，alist使用路径+文件名的方式索引目标文件，同名文件情况下可能需要传入更多参数，如排序、文件id（或者自定义id然后通过数据库和实际文件id对应）、远端文件时间（teambition是提供了的）

![image](https://github.com/alist-org/alist/assets/128236579/3a2dc23d-6aa5-4c5b-8bfb-7da7a6475fca)
![image](https://github.com/alist-org/alist/assets/128236579/d264845a-4dec-4a5d-9545-4280d9a5b1b6)
![image](https://github.com/alist-org/alist/assets/128236579/ba2f23ee-b00e-4915-bf47-3bdd5bd9365e)

### Reproduction / 复现链接

我并不清楚如何提供复现链接，具体操作过程如下：

1.准备两个不同内容但是名字相同的文件
2.登录Teambition网页端，打开对应项目上传文件
3.此时可以在Teambition网页端看到两个同名文件，此时这两个文件可以正常下载、复制、移动、重命名
4.打开alist挂载对应文件，发现只存在一个文件，可以正常下载

使用此流程即可完整复现以上问题

### Config / 配置

以下是在alist中的配置文件，无太大参考价值

![image](https://github.com/alist-org/alist/assets/128236579/f4630630-7e83-4d19-8277-3610aa1c5dc8)

### Logs / 日志

我使用的是docker部署，确认是c重新拉取的最新版本的镜像，日志如下，无太大参考价值

![image](https://github.com/alist-org/alist/assets/128236579/66313deb-26b3-4f84-a6af-e15c4c7b4f37)

**Comment by xhofe** [comment]
不支持在alist中有重名文件，alist的文件系统与操作系统文件系统类似，只以路径来标识唯一文件。且大部分存储中路径都是唯一的，不会为teambition做单独适配。
