### ISSUE TITLE
针对部分可以实现直传的网盘实现直传

### ISSUE THREAD

**Issue by Sunakier** [alist-org/alist#5143]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我已经清楚并且了解以下这个issues： https://github.com/alist-org/alist/issues/4348

上面这个issues中请求实现直传，得到回复部分网盘无法实现，那么能否针对部分网盘实现直传呢
我部署alist的服务器在海外，带宽较小，走服务器中转较慢，我希望请求适配的是Teambition驱动的上传直传

Teambition使用的是阿里云张家口的OSS，国内速度友好，家宽上传直传能到15MB/s，速度友好，目前未发现什么限制

### Suggested solution / 实现思路

此功能可能需要较多的修改alist的上传逻辑，对于部分支持的网盘，可以进行单独适配直传功能并且增加开关，保留原来服务器中转方案增加直传，应该是不难的

大体思路（Teambition）：
1.客户端请求上传，上报信息到Alist服务端
2.服务端请求API获取对应临时上传链接下发客户端浏览器对应上传js
3.客户端根据参数上传完成后上报服务器，服务器调用API完成上传

**Comment by SeanHeuc** [comment]
看了半天还是不理解你的“直传”是什么意思。拿阿里云举例子，必须向阿里云的指定api发送http请求才能上传数据，alist服务端有所有的逻辑。你用浏览器上传到alist，或者用跨存储复制等等，最后都是alist需要调用那些阿里的上传api才能把数据传上去。你理解了这个之后你就会发现没有什么“直传”， 因为上传的逻辑写在alist里面，所以要想上传速度快你就把alist部署在快的网络环境中就好了。（我看你写的家用宽带上行是15m/s 这个速度很好了，你在家庭网络内部部署alist就好了）

另： 下一个版本的alist已经优化上传，某些网盘上传可以不生成临时文件，而且某些网盘之间可以秒传

**Comment by Sunakier** [comment]
抱歉我的表述不太清楚，带来困扰


并非这样的，我说的直传是指的是客户端不上传文件到部署Alist的服务器，直接上传对应源站（网盘服务商提供的地址）


我同样使用阿里云举例子，阿里云OSS兼容s3，可以通过api获取临时上传的SessionToken下发客户端，客户端通过这个token可以直接向阿里云的api发送文件而无法操作除了限定外的内容，实现思路就是alist服务端可以通过签发低权限key和token下发，实现直传，这时候文件不经服务器中转


我主力所使用的Teambition官方上传逻辑就是这样的，其文件直接传到阿里云OSS。另外像Cloudreve支持直传的网盘的上传逻辑是一样的


我希望表述的是：alist是作为网盘服务端（比如阿里云API）和客户端（浏览器）通信的bridge，实现直传，而且避免部分信息直接暴露给客户端，不知是否清楚


另外的，我的Alist并非部署在内网，需要部署在其他地方，带宽没那么大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月3日(周日) 凌晨0:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alist-org/alist] 针对部分可以实现直传的网盘实现直传 (Issue #5143)




 
看了半天还是不理解你的“直传”是什么意思。拿阿里云举例子，必须向阿里云的指定api发送http请求才能上传数据，alist服务端有所有的逻辑。你用浏览器上传到alist，或者用跨存储复制等等，最后都是alist需要调用那些阿里的上传api才能把数据传上去。你理解了这个之后你就会发现没有什么“直传”， 因为上传的逻辑写在alist里面，所以要想上传速度快你就把alist部署在快的网络环境中就好了。（我看你写的家用宽带上行是15m/s 这个速度很好了，你在家庭网络内部部署alist就好了）
 
另： 下一个版本的alist已经优化上传，某些网盘上传可以不生成临时文件，而且某些网盘之间可以秒传

**Comment by SeanHeuc** [comment]
我理解你的意思了，
1. 极少数网盘支持token下发后通过客户端“直传”，alist客户端暂时只有浏览器，浏览器实现需要一定量的改动。
2. alist的上传逻辑是可以断点续传的，用了浏览器“直传”后很难做断点续传，秒传更是不可能的。
3. 浏览器“直传” 并没有太大意义，唯一的意义在于alist服务跑在上传带宽很低的外网。而大多数人的使用场景是部署在带宽很高的外网或者家庭内网，“直传”没有任何帮助

所以alist为极少数网盘添加一个浏览器“直传”功能需要一定的开发，让上传变得更复杂，而且受众用户很少。鉴于目前alist没有良好的客户端支持，所以个人建议是让alist跑在高带宽外网或者家庭内网

**Comment by Sunakier** [comment]
大体如此


改进需要较多修改alist上传逻辑，但是其实很多网盘都可以用这个逻辑直接在浏览器实现直传了
断点续传也是可以做的其实，只不过会比较复杂起来，很多网盘上传链接是有一定有效期的，客户端上报alist当前上传分块进度，断点续传时alist下发，实现比较麻烦，但是具体看个人需求吧
关于秒传，我并不太清楚你所说的秒传是哪样的实现，但是据我所知一般的秒传都是通过匹配文件hash实现的，理论来说，客户端可以上传同时计算hash并且上报alist比对或者继续上报网盘服务端实现"秒传"，甚至于可以实现在记录信息吻合的时候实现"跨网盘"，但我相信那并不是alist目标





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月3日(周日) 上午9:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alist-org/alist] 针对部分可以实现直传的网盘实现直传 (Issue #5143)




 
我理解你的意思了，
  
极少数网盘支持token下发后通过客户端“直传”，alist客户端暂时只有浏览器，浏览器实现需要一定量的改动。
 
alist的上传逻辑是可以断点续传的，用了浏览器“直传”后很难做断点续传，秒传更是不可能的。
 
浏览器“直传” 并没有太大意义，唯一的意义在于alist服务跑在上传带宽很低的外网。而大多数人的使用场景是部署在带宽很高的外网或者家庭内网，“直传”没有任何帮助
  
所以alist为极少数网盘添加一个浏览器“直传”功能需要一定的开发，让上传变得更复杂，而且受众用户很少。鉴于目前alist没有良好的客户端支持，所以个人建议是让alist跑在高带宽外网或者家庭内网

**Comment by SeanHeuc** [comment]
你说的很多网盘支持网页上传的“直传”是调用他们内部的上传接口，即使有更稳定的内部接口，这种方式传输大文件也往往会有问题，所以网盘也基本上推荐使用他们的平台客户端去上传。我大概看了下，只有s3和阿里云有这种api设计供“直传”，其他的都不行，例如百度盘支持2gb以下的直接上传，但是需要access token。 浏览器现在也支持对文件流进行高级处理了（包括hash），但是需要精通前端的人去实现相关代码。总体来说，这个需求太小众，需要的改动也太大。

另下个版本跨存储秒传已经实现了，这是alist的目标。因为这是个大众的需求，对大家分享电影等数据很方便，减少上传等待，对于网盘商也能促进一点销量，属于共赢的场景

**Comment by MasterKeee** [comment]
https://help.aliyun.com/zh/oss/use-cases/obtain-signature-information-from-the-server-and-upload-data-to-oss

**Comment by IAALAI** [comment]
我也认为这个功能是意义的，但是开发难度应该是大的不行啊

**Comment by Sunakier** [comment]
> 我也认为这个功能是意义的，但是开发难度应该是大的不行啊

仔细想想这个需求确实比较难以实现，而且对于很多网盘来说，即使实现，也有安全问题，比如很多网盘通过cookie进行鉴权，但是对于很多网盘这个cookie没有权限划分，权利很大，直接下发在公有环境不安全，在可以信任的的私有环境来看这个受众就很小了，正如上文所言，可以安全的实现的网盘很少，比较好的解决方案是仅允许信任账号调用直传/其他用户拒绝上传/只允许中转上传，但是这意味着需要大幅改动上传逻辑，并且需要为上传单独js实现

另外，我已经完成我对应需求私有实现，方案是：在对公提供上传服务时，对于可以安全直传的存储（如Onedrive、对象存储）在客户端实现直传，对于必要中转的存储，用了Cloudflare Worker进行传输，目前很稳定

这个Issue我会关闭，如果有人有兴趣，我期待实现

**Comment by Sunakier** [comment]
> > > 我也认为这个功能是意义的，但是开发难度应该是大的不行啊
> > 
> > 仔细想想这个需求确实比较难以实现，而且对于很多网盘来说，即使实现，也有安全问题，比如很多网盘通过cookie进行鉴权，但是对于很多网盘这个cookie没有权限划分，权利很大，直接下发在公有环境不安全，在可以信任的的私有环境来看这个受众就很小了，正如上文所言，可以安全的实现的网盘很少，比较好的解决方案是仅允许信任账号调用直传/其他用户拒绝上传/只允许中转上传，但是这意味着需要大幅改动上传逻辑，并且需要为上传单独js实现
> > 
> > 另外，我已经完成我对应需求私有实现，方案是：在对公提供上传服务时，对于可以安全直传的存储（如Onedrive、对象存储）在客户端实现直传，对于必要中转的存储，用了Cloudflare Worker进行传输，目前很稳定
> > 
> > 这个Issue我会关闭，如果有人有兴趣，我期待实现
> 
> 怎么才能用上你的对象存储直传？在哪里设置
> 

请您**根据自己的业务需求**自行完成您的**私有实现**，我的实现并不基于 Alist，也不考虑公开，见谅

**Comment by gamelife40v** [comment]
> > > > 我也认为这个功能是意义的，但是开发难度应该是大的不行啊
> > > 
> > > 
> > > 仔细想想这个需求确实比较难以实现，而且对于很多网盘来说，即使实现，也有安全问题，比如很多网盘通过cookie进行鉴权，但是对于很多网盘这个cookie没有权限划分，权利很大，直接下发在公有环境不安全，在可以信任的的私有环境来看这个受众就很小了，正如上文所言，可以安全的实现的网盘很少，比较好的解决方案是仅允许信任账号调用直传/其他用户拒绝上传/只允许中转上传，但是这意味着需要大幅改动上传逻辑，并且需要为上传单独js实现
> > > 另外，我已经完成我对应需求私有实现，方案是：在对公提供上传服务时，对于可以安全直传的存储（如Onedrive、对象存储）在客户端实现直传，对于必要中转的存储，用了Cloudflare Worker进行传输，目前很稳定
> > > 这个Issue我会关闭，如果有人有兴趣，我期待实现
> > 
> > 
> > 怎么才能用上你的对象存储直传？在哪里设置
> 
> 请您**根据自己的业务需求**自行完成您的**私有实现**，我的实现并不基于 Alist，也不考虑公开，见谅

github上有另一个项目【Cloudreve】，支持网页客户端直传，也就是说网页端直传技术上是可行的。
但是Cloudreve的功能较少，1.不持支持跨存储桶之间的文件交互，2.一个用户只能对应一个存储桶。且Cloudreve的路径和文件名是数据库管理，与物理路径是脱钩的，会导致前端和后端数据路径和名称脱钩。不便于物理文件管理。

我的理解是，因为alist本体功能复杂(跨存储间的交互)，并将所有[对象存储]类型的整合到了一起(没有区分不同运行商的对象存储)，最终**导致虽然技术上可行**，但是功能的复杂度使得**上传模式只能使用所有模式都支持的【最大公约数】**
