### ISSUE TITLE
蓝奏云下载文件提示：failed link: failed get link: not find data

### ISSUE THREAD

**Issue by SDCOM-0415** [alist-org/alist#5146]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.26.0

### Driver used / 使用的存储驱动

lanzou

### Describe the bug / 问题描述

使用蓝奏云进行下载文件的时候，会提示
failed link: failed get link: not find data
![image](https://github.com/alist-org/alist/assets/127208666/467bb6e5-525d-4755-972d-760e816ed69a)
采用帐号登录，确保正确（能够在官网正常登录、上传、下载）
![image](https://github.com/alist-org/alist/assets/127208666/aa13faf1-a6e5-4a9d-ba5e-cb547b60c905)
![image](https://github.com/alist-org/alist/assets/127208666/5747fb6b-48ca-428a-a51b-b4b28b926ce0)
![image](https://github.com/alist-org/alist/assets/127208666/e2a63a27-6160-4d4a-9ac5-cf3afbaf3ffc)
![image](https://github.com/alist-org/alist/assets/127208666/ecc5a710-9265-4fdd-aed4-1ebed51a8a25)
也能够正常的在alist中读取文件列表
![image](https://github.com/alist-org/alist/assets/127208666/b8457375-e12a-4ea7-97ff-edb388566eb8)

但是有个玄学的是音乐能够正常的播放，下载
![image](https://github.com/alist-org/alist/assets/127208666/5a689f02-0f87-4b9c-be91-5b3718d2a483)

在TG官方群聊中，我没有得到任何有用的答复
希望能够有人能够帮忙解决

（本人并不会太多的linux技巧，而且这个项目只是通过一键脚本在一台云服务器上部署的，所以也就谈不上调取log，开启debug等操作，希望大佬多多包容，耐心教一下我，谢谢！🙏）

### Reproduction / 复现链接

https://dz.sdcom.asia/lanzou/%E5%B8%B8%E7%94%A8%E5%B0%8F%E5%B7%A5%E5%85%B7.zip

https://dz.sdcom.asia/lanzou/

https://dz.sdcom.asia/lanzou/%E9%9F%B3%E4%B9%90/Ilkay%20Sencan%20-%20Do%20It.mp3

### Config / 配置
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "rvVxu7mYT4xEEXh2",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

### Logs / 日志

太长了，放在云盘里了
https://sdcom.lanzouy.com/ia6gv17b0rzc

**Comment by SDCOM-0415** [comment]
追加说明
只有部分文件可以下载，不可下载文件集中于压缩包文件
其他例如.mp3 .exe均可下载，例如
![image](https://github.com/alist-org/alist/assets/127208666/14dffc8f-4879-410a-a4dc-55b25478d3e7)
![image](https://github.com/alist-org/alist/assets/127208666/5115ea79-6725-4a7a-b743-1b9630303c64)

**Comment by itsHenry35** [comment]
你这个其他储存的cookie咋都直接明文贴出来了啊，会泄露的啊

**Comment by SDCOM-0415** [comment]
没注意到

**Comment by itsHenry35** [comment]
> 没注意到

配置文件不是这个，是/opt/alist/data的config.json，日志就是里面的log.log

**Comment by SDCOM-0415** [comment]
嗯嗯

**Comment by xhofe** [comment]
#5088

**Comment by SDCOM-0415** [comment]
本人今天更新过

**Comment by SDCOM-0415** [comment]
> Member

看了，没看懂，请指教一下

**Comment by xhofe** [comment]
请尝试 开发版本

**Comment by SDCOM-0415** [comment]
> 

请问如何更新至开发版本？

**Comment by SDCOM-0415** [comment]
我没有在releases页面中找到开发版本
![image](https://github.com/alist-org/alist/assets/127208666/e85f17b9-fcb6-4112-866e-acbfa03f937f)

**Comment by xhofe** [comment]
https://github.com/alist-org/alist/actions/workflows/build.yml

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/pull/5088 修复的没有问题 可以下载压缩包 exe apk等文件。
- 账号密码登录 ✅
- cookie登录     ✅
- 分享链接        ✅
![image](https://github.com/alist-org/alist/assets/56105412/58fdea8c-b46d-42f2-9c37-78ed3adb8873)
![image](https://github.com/alist-org/alist/assets/56105412/bd9c3c12-2283-4140-84f5-d95a637afae1)
![image](https://github.com/alist-org/alist/assets/56105412/6e2a31ba-0b36-4b23-86c4-1ca2aa805355)
![image](https://github.com/alist-org/alist/assets/56105412/3598f7a3-d23c-47e7-b9cc-0484137d3088)

**Comment by SDCOM-0415** [comment]
我个小白没有理解如何修复，小白完全看不懂

**Comment by SDCOM-0415** [comment]
前面的大佬说更新到开发版，但是我不会
下面又说使用之前提供的方法，但是我不会使用
可以教教我吗？

**Comment by anwen-anyi** [comment]
> 前面的大佬说更新到开发版，但是我不会 下面又说使用之前提供的方法，但是我不会使用 可以教教我吗？

打开 **https://github.com/alist-org/alist/actions/workflows/build.yml** 这个链接

然后选择一个靠前的，最好是点第一个。

![image](https://github.com/alist-org/alist/assets/56105412/6fc8714c-0522-4442-9749-73fe9ccad559)

点开后进去点击下方的哪个进行下载，就是测试版，使用最新`commit`提交的代码构建的，下载好后根据自己的机器选择
- Windows
- Mac
- Linux

![image](https://github.com/alist-org/alist/assets/56105412/ca4bff94-057c-4aae-bc33-5c10e7423686)

**Comment by xhofe** [comment]
这应该在v3.27.0中被修复。

**Comment by Hanson-zhy** [comment]
> 这应该在v3.27.0中被修复。
希望Docker能够同步
