### ISSUE TITLE
FTP挂载后可以看到文件夹及文件但无法下载

### ISSUE THREAD

**Issue by HFGZH** [alist-org/alist#5150]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

docker alist main c65ab08ee440

### Driver used / 使用的存储驱动

FTP

### Describe the bug / 问题描述

![Screenshot_20230903_163452_com huawei browser](https://github.com/alist-org/alist/assets/26871282/a9367fac-5dc7-4745-aa19-5b64e3c619bb)
![Screenshot_20230903_163457_com huawei browser](https://github.com/alist-org/alist/assets/26871282/317d2427-035c-409f-b0b0-35f98ca1e5bc)
docker最新版alist main c65ab08ee440，挂载FTP后可以看到目录结构及文件，但除图片以外文件均无法下载。alist latest v3.26.0挂载FTP功能正常。

### Reproduction / 复现链接

http://121.206.204.35:1111/

### Config / 配置

![Screenshot_20230903_170145_com.mixplorer.silver.jpg](https://s2.loli.net/2023/09/03/rF8l4D3JBKTEA6p.jpg)
![Screenshot_20230903_165652_com.huawei.browser.jpg](https://s2.loli.net/2023/09/03/Q2nEWyw4rtLvaTk.jpg)

### Logs / 日志

[33mWARN[0m[2023-09-03 16:38:11] not enable search                            
[GIN] 2023/09/03 - 16:38:59 | 304 |   26.142037ms |      172.17.0.1 | GET      "/p/ftptest/Alist-picture.jpg"
[GIN] 2023/09/03 - 16:39:03 | 200 |   12.672685ms |      172.17.0.1 | GET      "/p/ftptest/花瓣测速.apk"

[31m2023/09/03 16:39:04 [Recovery] 2023/09/03 - 16:39:04 panic recovered:
runtime error: slice bounds out of range [28:13]
/usr/lib/go/src/runtime/panic.go:153 (0x43d4ab)
/usr/lib/go/src/bufio/bufio.go:347 (0x677b83)
/usr/lib/go/src/bufio/bufio.go:401 (0x677bd3)
/usr/lib/go/src/net/textproto/reader.go:56 (0x67c2bb)
/usr/lib/go/src/net/textproto/reader.go:39 (0x67cbb3)
/usr/lib/go/src/net/textproto/reader.go:188 (0x67cbac)
/usr/lib/go/src/net/textproto/reader.go:267 (0x67cf33)
/root/go/pkg/mod/github.com/jlaffaye/ftp@v0.2.0/ftp.go:593 (0x126f70f)
/root/go/pkg/mod/github.com/jlaffaye/ftp@v0.2.0/ftp.go:821 (0x1270ac3)
/app/drivers/ftp/util.go:95 (0x1275c33)
/usr/lib/go/src/net/http/fs.go:196 (0x6b10b7)
/usr/lib/go/src/net/http/fs.go:254 (0x6b125b)
/usr/lib/go/src/net/http/fs.go:206 (0x6b100b)
/app/server/common/proxy.go:20 (0xcb910b)
/app/server/handles/down.go:105 (0x145b6c7)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1429f27)
/app/server/middlewares/down.go:40 (0x1429e7c)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1429a03)
/app/server/middlewares/check.go:14 (0x14299e4)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xcae8ab)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0xcae88c)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xcadb8b)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0xcadb68)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xcacccb)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0xcac9f4)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0xcac5f3)
/usr/lib/go/src/net/http/server.go:2936 (0x6f424f)
/usr/lib/go/src/net/http/server.go:1995 (0x6f0027)
/usr/lib/go/src/runtime/asm_arm64.s:1172 (0x475d03)
[0m
[GIN] 2023/09/03 - 16:39:04 | 500 |   4.03849881s |      172.17.0.1 | GET      "/p/ftptest/ad-pc.txt?ts=1693730080659"
[GIN] 2023/09/03 - 16:39:06 | 200 |    1.552329ms |      172.17.0.1 | GET      "/ftptest/花瓣测速.apk"
[GIN] 2023/09/03 - 16:39:06 | 200 |    9.030167ms |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:39:06 | 200 |     7.64293ms |      172.17.0.1 | POST     "/api/fs/get"
[GIN] 2023/09/03 - 16:39:07 | 200 |    5.307729ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:39:08 | 200 |    4.406141ms |      172.17.0.1 | POST     "/api/fs/get"
[GIN] 2023/09/03 - 16:39:08 | 304 |    1.954266ms |      172.17.0.1 | GET      "/p/ftptest/404.gif"
[GIN] 2023/09/03 - 16:39:09 | 200 |     1.89418ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:39:11 | 200 |    1.155934ms |      172.17.0.1 | POST     "/api/fs/get"
[GIN] 2023/09/03 - 16:39:14 | 200 |    3.541305ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:40:12 | 200 |     2.75814ms |      172.17.0.1 | POST     "/api/fs/get"
[GIN] 2023/09/03 - 16:40:12 | 200 |    1.818926ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:40:14 | 200 |     716.453µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:40:16 | 200 |    1.024969ms |      172.17.0.1 | GET      "/api/admin/driver/names"
[GIN] 2023/09/03 - 16:40:16 | 200 |    5.258142ms |      172.17.0.1 | GET      "/api/admin/storage/list"
[GIN] 2023/09/03 - 16:40:19 | 200 |     630.616µs |      172.17.0.1 | GET      "/@manage/storages"
[GIN] 2023/09/03 - 16:40:19 | 200 |    8.433096ms |      172.17.0.1 | GET      "/api/public/settings"
[GIN] 2023/09/03 - 16:40:19 | 200 |     936.881µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:40:19 | 200 |     747.579µs |      172.17.0.1 | GET      "/api/admin/driver/names"
[GIN] 2023/09/03 - 16:40:19 | 200 |    3.763858ms |      172.17.0.1 | GET      "/api/admin/storage/list"
[GIN] 2023/09/03 - 16:40:22 | 200 |   21.761481ms |      172.17.0.1 | GET      "/api/admin/driver/list"
[31mERRO[0m[2023-09-03 16:41:07] failed init storage but storage is already created: failed init storage: root folder /tmp/log/Alist/test not exists 
[GIN] 2023/09/03 - 16:41:07 | 200 |   13.997503ms |      172.17.0.1 | POST     "/api/admin/storage/create"
[GIN] 2023/09/03 - 16:41:07 | 200 |    5.421192ms |      172.17.0.1 | GET      "/api/admin/storage/get?id=4"
[GIN] 2023/09/03 - 16:41:07 | 200 |    3.835903ms |      172.17.0.1 | GET      "/api/admin/driver/info?driver=Local"
[GIN] 2023/09/03 - 16:41:26 | 200 |    8.490848ms |      172.17.0.1 | POST     "/api/admin/storage/update"
[GIN] 2023/09/03 - 16:41:26 | 200 |   15.655837ms |      172.17.0.1 | GET      "/api/admin/driver/list"
[GIN] 2023/09/03 - 16:41:29 | 200 |     1.26794ms |      172.17.0.1 | GET      "/api/admin/driver/names"
[GIN] 2023/09/03 - 16:41:29 | 200 |    6.450828ms |      172.17.0.1 | GET      "/api/admin/storage/list"
[GIN] 2023/09/03 - 16:41:31 | 200 |    6.765552ms |      172.17.0.1 | GET      "/api/admin/storage/list"
[GIN] 2023/09/03 - 16:41:32 | 200 |    6.407075ms |      172.17.0.1 | GET      "/api/admin/storage/list"
[GIN] 2023/09/03 - 16:41:34 | 200 |    1.342318ms |      172.17.0.1 | GET      "/"
[GIN] 2023/09/03 - 16:41:34 | 200 |     987.634µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:41:34 | 200 |     874.461µs |      172.17.0.1 | GET      "/api/public/settings"
[GIN] 2023/09/03 - 16:41:34 | 200 |     939.506µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:41:34 | 200 |    1.922181ms |      172.17.0.1 | POST     "/api/fs/get"
[GIN] 2023/09/03 - 16:41:34 | 200 |     1.72588ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:41:35 | 200 |    4.980753ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:41:36 | 200 |    4.991837ms |      172.17.0.1 | POST     "/api/fs/get"
[GIN] 2023/09/03 - 16:41:37 | 200 |    1.911973ms |      172.17.0.1 | GET      "/p/log/Alist.log"
[GIN] 2023/09/03 - 16:41:38 | 200 |    2.530046ms |      172.17.0.1 | GET      "/p/log/Alist.log"
[GIN] 2023/09/03 - 16:41:47 | 200 |    2.048479ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:45:11 | 500 |          6m0s |      172.17.0.1 | GET      "/p/ftptest/花瓣测速.apk"
[GIN] 2023/09/03 - 16:55:09 | 200 |    1.125016ms |      172.17.0.1 | GET      "/"
[GIN] 2023/09/03 - 16:55:09 | 200 |    1.063762ms |      172.17.0.1 | GET      "/api/public/settings"
[GIN] 2023/09/03 - 16:55:09 | 200 |     919.088µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:55:09 | 200 |   55.782042ms |      172.17.0.1 | POST     "/api/fs/get"
[GIN] 2023/09/03 - 16:55:10 | 200 |  111.159815ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:55:11 | 200 |    1.063762ms |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:55:16 | 200 |     742.329µs |      172.17.0.1 | GET      "/assets/Users.9af32cd6.js"
[GIN] 2023/09/03 - 16:55:16 | 200 |     747.288µs |      172.17.0.1 | GET      "/assets/Wether.656b91c1.js"
[GIN] 2023/09/03 - 16:55:17 | 200 |    5.858715ms |      172.17.0.1 | GET      "/api/admin/user/list"
[GIN] 2023/09/03 - 16:55:21 | 200 |     518.318µs |      172.17.0.1 | GET      "/assets/AddOrEdit.8f86b918.js"
[GIN] 2023/09/03 - 16:55:21 | 200 |     4.36268ms |      172.17.0.1 | GET      "/api/admin/user/get?id=2"
[GIN] 2023/09/03 - 16:55:27 | 200 |   98.591551ms |      172.17.0.1 | POST     "/api/admin/user/update"
[GIN] 2023/09/03 - 16:55:27 | 200 |    4.075666ms |      172.17.0.1 | GET      "/api/admin/user/list"
[GIN] 2023/09/03 - 16:55:31 | 200 |    2.756974ms |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:55:32 | 200 |    1.038387ms |      172.17.0.1 | GET      "/api/admin/user/list"
[GIN] 2023/09/03 - 16:55:35 | 200 |     322.891µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:55:35 | 200 |    1.133766ms |      172.17.0.1 | GET      "/"
[GIN] 2023/09/03 - 16:55:36 | 200 |     828.083µs |      172.17.0.1 | GET      "/api/public/settings"
[GIN] 2023/09/03 - 16:55:36 | 200 |     242.679µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:55:36 | 200 |   16.085067ms |      172.17.0.1 | POST     "/api/fs/get"
[GIN] 2023/09/03 - 16:55:36 | 200 |  101.511574ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:55:38 | 200 |   55.641452ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:56:33 | 200 |   62.554262ms |      172.17.0.1 | POST     "/api/auth/login/hash"
[GIN] 2023/09/03 - 16:56:33 | 200 |     1.08593ms |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:56:33 | 200 |   96.033962ms |      172.17.0.1 | POST     "/api/fs/list"
[GIN] 2023/09/03 - 16:56:35 | 200 |     934.548µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:56:39 | 200 |    1.248106ms |      172.17.0.1 | GET      "/api/admin/driver/names"
[GIN] 2023/09/03 - 16:56:39 | 200 |    6.610835ms |      172.17.0.1 | GET      "/api/admin/storage/list"
[GIN] 2023/09/03 - 16:56:46 | 200 |    3.443884ms |      172.17.0.1 | GET      "/api/admin/storage/get?id=3"
[GIN] 2023/09/03 - 16:56:46 | 200 |    1.162643ms |      172.17.0.1 | GET      "/api/admin/driver/info?driver=FTP"
[GIN] 2023/09/03 - 16:57:02 | 200 |     916.464µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:57:02 | 200 |    1.250439ms |      172.17.0.1 | GET      "/"
[GIN] 2023/09/03 - 16:57:03 | 200 |     905.379µs |      172.17.0.1 | GET      "/api/public/settings"
[GIN] 2023/09/03 - 16:57:03 | 200 |     929.006µs |      172.17.0.1 | GET      "/api/me"
[GIN] 2023/09/03 - 16:57:03 | 200 |  110.140096ms |      172.17.0.1 | POST     "/api/fs/get"
[GIN] 2023/09/03 - 16:57:03 | 200 |    5.092467ms |      172.17.0.1 | POST     "/api/fs/list"

**Comment by SeanHeuc** [comment]
main是测试版呀，你拉github action最新版应该已经修了，docker有很大延迟的

**Comment by HFGZH** [comment]
是一小时前更新的最新的版本docker alist main c65ab08ee440，修完之后只有图片下载时灵时不灵，压缩包 文档等文件都无法下载。

**Comment by HFGZH** [comment]
![Screenshot_20230903_171915.jpg](https://s2.loli.net/2023/09/03/51PumCgDoINzcbZ.jpg)
![Screenshot_20230903_165652_com.huawei.browser.jpg](https://s2.loli.net/2023/09/03/Q2nEWyw4rtLvaTk.jpg)
![Screenshot_20230903_170145_com.mixplorer.silver.jpg](https://s2.loli.net/2023/09/03/rF8l4D3JBKTEA6p.jpg)

**Comment by NovaShen555** [comment]
ERR_CONNECTION_TIMED_OUT
🙂

**Comment by HFGZH** [comment]
要晚点，家里停电，这个服务是跑在软路由上的

**Comment by HFGZH** [comment]
http://121.206.204.35:1111/

**Comment by xhofe** [comment]
有一点奇怪 看日志是 SIZE FTP command 命令的响应解析错误，不知道是与FTP服务器之间的通信问题还是FTP服务器的支持度问题，你的FTP服务器是什么，我使用 https://hub.docker.com/r/delfer/alpine-ftp-server 这个镜像测试 ftp是没有问题的。

不过我们也可以选择不使用这个command请求

**Comment by NovaShen555** [comment]
latest挂载没有问题哦
请尝试我的ftp
114.132.232.47:21
admin
zxcvbnm?2

**Comment by HFGZH** [comment]
![Screenshot_20230903_183456_com.huawei.browser.jpg](https://s2.loli.net/2023/09/03/OqFDcCnt6xQ9hzg.jpg)
![Screenshot_20230903_183619_com.huawei.browser.jpg](https://s2.loli.net/2023/09/03/RTS3QVZB1H8oO4j.jpg)
是OpenWrt自带的FTP服务

**Comment by NovaShen555** [comment]
> latest挂载没有问题哦 请尝试我的ftp 114.132.232.47:21 admin zxcvbnm?2

我使用的是fauria/vsftpd

**Comment by HFGZH** [comment]
latest挂载没有问题，是最新的main存在问题

**Comment by xhofe** [comment]
可以试一下现在的最新开发版本是否可用

**Comment by HFGZH** [comment]
> 可以试一下现在的最新开发版本是否可用

现在正常了，麻烦啦
