### ISSUE TITLE
public/dist/README.md says "Put dist of frontend here." but doesn't explain where does it come from

### ISSUE THREAD

**Issue by yurivict** [alist-org/alist#5154]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

n/a

### Describe the bug / 问题描述

```alist server``` fails:
> FATA[2023-09-03 07:52:34] index.html not exist, you may forget to put dist of frontend to public/dist 

but ```public/dist/README.md``` doesn't explain where does this frontend come from.

### Reproduction / 复现链接

n/a

### Config / 配置

n/a

### Logs / 日志

```
$ alist server
INFO[2023-09-03 07:52:34] reading config file: data/config.json        
INFO[2023-09-03 07:52:34] load config from env with prefix: ALIST_     
INFO[2023-09-03 07:52:34] init logrus...                               
FATA[2023-09-03 07:52:34] index.html not exist, you may forget to put dist of frontend to public/dist 
```

**Comment by Troray** [comment]
alist version： `v3.27.0`
OS：`Windows 10` and `armbian`
Unable to reproduce the issue on both.
均无法复现问题。
```
> alist server
INFO[2023-09-04 00:35:13] reading config file: D:\scoop\apps\alist\current\data\config.json
INFO[2023-09-04 00:35:13] load config from env with prefix: ALIST_
INFO[2023-09-04 00:35:13] init logrus...
INFO[2023-09-04 00:35:13] start HTTP server @ 0.0.0.0:80
INFO[2023-09-04 00:35:13] Aria2 not ready.
INFO[2023-09-04 00:35:13] qbittorrent not ready.
INFO[2023-09-04 00:35:14] success load storage: [/189], driver: [189CloudPC]
INFO[2023-09-04 00:35:14] success load storage: [/onedrive], driver: [OnedriveAPP]
```
```
root@armbian:/home/327# ./alist server
INFO[2023-09-04 00:30:14] reading config file: data/config.json        
INFO[2023-09-04 00:30:14] load config from env with prefix: ALIST_     
INFO[2023-09-04 00:30:14] init logrus...                               
INFO[2023-09-04 00:30:14] start HTTP server @ 0.0.0.0:5327             
INFO[2023-09-04 00:30:14] qbittorrent not ready.                       
INFO[2023-09-04 00:30:14] Aria2 not ready.  
```

**Comment by yurivict** [comment]
```public/dist``` only has the README file.
Where is index.html supposed to come from?

My OS is FreeBSD 13.2

**Comment by Troray** [comment]
> `public/dist` only has the README file. Where is index.html supposed to come from?
> 
> My OS is FreeBSD 13.2

[https://github.com/alist-org/alist-web](https://github.com/alist-org/alist-web)
Compile the frontend source code and place it in the 'dist' directory.

**Comment by Troray** [comment]
[https://github.com/alist-org/alist/releases](https://github.com/alist-org/alist/releases)
or use the precompiled files

docker：
https://hub.docker.com/r/xhofe/alist

document：
https://alist.nn.ci/

**Comment by yurivict** [comment]
@Troray 
Are pre-built web frontend files available as a tarball to download?

The files in https://github.com/alist-org/alist/releases are for particular architectures.
Docker doesn't support FreeBSD.

IMO you should add the tarball with pre-built web frontend to Assets in https://github.com/alist-org/alist/releases

**Comment by Troray** [comment]
> @Troray Are pre-built web frontend files available as a tarball to download?
> 
> The files in https://github.com/alist-org/alist/releases are for particular architectures. Docker doesn't support FreeBSD.
> 
> IMO you should add the tarball with pre-built web frontend to Assets in https://github.com/alist-org/alist/releases

Compiling the web frontend is relatively straightforward. If you wish to compile executable files for FreeBSD on your own, you can refer to this document: [Run from source](https://alist.nn.ci/guide/install/source.html#environmental-preparation).

Since I've never used FreeBSD, I can't offer you much advice, but I found these two documents and am unsure if they would be of help to you.
https://wiki.freebsd.org/Linuxulator
https://wiki.freebsd.org/Docker

**Comment by xhofe** [comment]
refer to https://alist.nn.ci/guide/install/source.html
