### ISSUE TITLE
建议Crypt支持rclone高级参数

### ISSUE THREAD

**Issue by fgfg163** [alist-org/alist#5155]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

不同网盘限制不同的特殊字符串，导致互相备份时总有文件失败。
我在rclone官网发现可以只加密文件名而不加密文件内容，于是想到用这种方法解决文件名的问题
希望Crypt能设置高级参数以便我使用--crypt-no-data-encryption这个参数只加密文件名不加密内容

### Suggested solution / 实现思路

支持rclone的参数--crypt-no-data-encryption，新增一些选项或者直接支持输入附加的命令
https://rclone.org/crypt/#crypt-no-data-encryption

**Comment by SeanHeuc** [comment]
正是因为不同网盘对于文件名编码的支持的不同，所以alist才默认用了base64，如果你要同时用rclnoe和alist建议用base64. 对于你需要的不改变文件加密内容而更改文件名/目录名， 请参考：https://github.com/alist-org/alist/issues/5084
