### ISSUE TITLE
error: that's not even a token 

### ISSUE THREAD

**Issue by 1010739073** [alist-org/alist#5158]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.26

### Driver used / 使用的存储驱动

aliopen

### Describe the bug / 问题描述

./alist admin set NEW_PASSWORD
INFO[2023-09-04 14:32:28] reading config file: data/config.json        
INFO[2023-09-04 14:32:28] load config from env with prefix: ALIST_     
INFO[2023-09-04 14:32:28] init logrus...                               
INFO[2023-09-04 14:32:28] admin user has been updated:                 
INFO[2023-09-04 14:32:28] username: admin                              
INFO[2023-09-04 14:32:28] password: NEW_PASSWORD                       
ERRO[2023-09-04 14:32:28] [del_user_cache_online] error: that's not even a token 

### Reproduction / 复现链接

./alist admin set NEW_PASSWORD

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "QGZfGPYu6goDVBk9",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

**Comment by xhofe** [comment]
请确保你执行此命令时读取的配置正确，另：此报错不影响使用，可忽略。

**Comment by silmace** [comment]
实测 这个bug 不能修改密码

> 请确保你执行此命令时读取的配置正确，另：此报错不影响使用，可忽略。

**Comment by xhofe** [comment]
> 实测 这个bug 不能修改密码
> 
> > 请确保你执行此命令时读取的配置正确，另：此报错不影响使用，可忽略。

# **请确保你执行此命令时读取的配置正确**

**Comment by asepsiswu** [comment]
reading config file: data/config.json 这个提示不够具体，
譬如 archlinux 按照aur/alist-bin对应的config.json位置在/var/lib/alist/。
 /usr/bin/alist admin 会在**当前位置**生成data目录，没有修改真正的data下的文件。
可通过ps -ef | grep alist 定位到 data目录。

**Comment by oyal** [comment]
如果是windows的计划任务，需要在 `起始于(可选)` 设置alist所在的目录，否者无法读写文件。我摸索了半个多小时

![image](https://github.com/alist-org/alist/assets/88022434/c4b75a5e-fb60-4649-85a4-ab1ad120f3c4)

**Comment by 3217333857** [comment]
> grep alist

请问你是如何解决的，我也遇到了这个问题

**Comment by arstum** [comment]
> reading config file: data/config.json 这个提示不够具体， 譬如 archlinux 按照aur/alist-bin对应的config.json位置在/var/lib/alist/。 /usr/bin/alist admin 会在**当前位置**生成data目录，没有修改真正的data下的文件。 可通过ps -ef | grep alist 定位到 data目录。

请问你是如何解决的，我也遇到了这个问题

**Comment by asepsiswu** [comment]
### 在ubuntu 22.04 LTS下面
```
ps -ef | grep alist
```
![image](https://github.com/alist-org/alist/assets/4438057/87c69331-00a4-411e-9dba-c3b32075c6c1)

切换到` /opt/alist`目录下面执行alist admin相关操作
```

sudo /opt/alist/alist admin set NEW_PASSWORD
```
### arch linux 下面
```
ps -ef | grep alist
```
![image](https://github.com/alist-org/alist/assets/4438057/9dbeeb1d-bc99-4b91-bb2b-f7cac16b1075)

切换到` /var/lib`目录下面，搞一个**data的软链接**，执行alist admin相关操作 
![image](https://github.com/alist-org/alist/assets/4438057/3fcb0fe3-c14c-407c-9ab0-1980eb17d58d)
```
sudo ln -s /var/lib/alist /var/lib/data
cd /var/lib # 必须是对应的data目录的上级文件
sudo alist admin set NEW_PASSWORD
```

**Comment by FlintyLemming** [comment]
初次运行时 data 文件夹会被生成到当前目录下，感觉怪怪的，我分享下我的方法吧，起码看起来整洁一点

1. 将 alist 二进制文件移动到环境变量包含的目录内（比如我这里是 `/usr/local/bin/`）
    ``` bash
    sudo cp alist /usr/local/bin/
    ```
2. 找一个地方创建目录保存配置文件（这里选用主流的 `~/.config`）
    ``` bash
    mkdir -p ~/.config/alist
    ```
3. 启动服务时指定这个目录
    ``` bash
    alist server --data '/home/USER_NAME/.config/alist'
    ```
4. 修改密码时也指定这个目录
   ``` bash
   alist admin set NEW_PASSWORD --data '/home/USER_NAME/.config/alist'
   ```

**Comment by 3217333857** [comment]
谢谢大家的分享，我的也解决了，我是重新安装386版本就行了

**Comment by shierleeee** [comment]
#第一步 找到配置文件位置
root@ImmortalWrt:/usr/bin# ps -ef | grep alist
 5061 root     1248m S    /usr/bin/alist server --data /etc/alist --no-prefix
 5124 root      1316 S    grep alist
#第二步 更新密码 指定配置位置
/usr/bin/alist admin set Xinmima --data '/etc/alist'

**Comment by woshichenghaibo** [comment]
> #第一步 找到配置文件位置 root@ImmortalWrt:/usr/bin# ps -ef | grep alist 5061 root 1248m S /usr/bin/alist server --data /etc/alist --no-prefix 5124 root 1316 S grep alist #第二步 更新密码 指定配置位置 /usr/bin/alist admin set Xinmima --data '/etc/alist'

可以设置密码领域，但是登陆不了

**Comment by woshichenghaibo** [comment]
> 谢谢大家的分享，我的也解决了，我是重新安装386重新安装？
