### ISSUE TITLE
地址树：文件名异常

### ISSUE THREAD

**Issue by 1049731887** [alist-org/alist#5165]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

地址树

### Describe the bug / 问题描述

地址树对于含参地址，如
```
https://example.com/file.zip?request_id=48471024
```
这样的文件无法正常显示文件名

### Reproduction / 复现链接

如上步骤即可复现

### Config / 配置

不必

### Logs / 日志

不必

**Comment by xhofe** [comment]
对于这种不是以文件名作为结尾的url，请自行设置文件名。Schema：
```
[FileName:][FileSize:][Modified:]Url
```

**Comment by 1049731887** [comment]
不可以写个判断吗嘤嘤嘤
