### ISSUE TITLE
配置项 database.name 不生效

### ISSUE THREAD

**Issue by Puqns67** [alist-org/alist#5168]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

暂无

### Describe the bug / 问题描述

当配置项 database.type 为 postgres 时，指定 database.name 不生效。

此时的数据库状态：
```
postgres=# \l
                                                      数据库列表
   名称    |   拥有者    | 字元编码 |  校对规则   |    Ctype    | ICU Locale | Locale Provider |       存取权限
-----------+-------------+----------+-------------+-------------+------------+-----------------+-----------------------
 storage   | alist       | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 |            | libc            |
```

此时若将数据库名改为 alist，即使保持 database.name 为 storage，也能正常连接至数据库。

### Reproduction / 复现链接

暂无

### Config / 配置

```json
{
    "database": {
        "type": "postgres",
        "user": "alist",
        "name": "storage"
    }
}
```

### Logs / 日志

```
FATA[2023-09-04 23:50:31] failed to connect database:failed to connect to `host=localhost user=alist database=`: server error (致命错误: 数据库 "alist" 不存在 (SQLSTATE 3D000))
```

**Comment by xhofe** [comment]
![image](https://github.com/alist-org/alist/assets/36558727/9f689676-f12a-4b6d-b5c5-278382cf5bf4)

我无法复现此问题，请确保你读取的配置文件正确。

**Comment by Puqns67** [comment]
原因找到了，是因为 database.password 未填写，且默认空字符串，导致[此处](https://github.com/alist-org/alist/blob/6f6d20e1ba32c50c473c5751941edb1581f88aad/internal/bootstrap/db.go#L65)生成的数据库链接格式有问题，gorm 把 password 识别成了 ` dbname=storage`，最后导致 database.name 不生效

**Comment by Puqns67** [comment]
> 原因找到了，是因为 database.password 未填写，且默认为空字符串，导致[此处](https://github.com/alist-org/alist/blob/6f6d20e1ba32c50c473c5751941edb1581f88aad/internal/bootstrap/db.go#L65)生成的数据库链接格式有问题，gorm 把 password 识别成了 ` dbname=storage`，最后导致 database.name 不生效。（这种问题不翻源代码真的很难找到原因。。。

@xhofe 您好，请问您对此处提出的问题有何看法？
