### ISSUE TITLE
[Aliyunpan_open] upload get 500 when use webdav

### ISSUE THREAD

**Issue by ericma15** [alist-org/alist#5174]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

aliyunpan_open

### Describe the bug / 问题描述

在通过webdav上传文件时，返回500，之前版本一直没有问题，这个版本才出现问题。相关调用栈。
```

2023/09/05 05:36:24 [Recovery] 2023/09/05 - 05:36:24 panic recovered:
runtime error: makeslice: cap out of range
/usr/lib/go/src/runtime/slice.go:33 (0x45a564)
/usr/lib/go/src/runtime/slice.go:100 (0x45a54c)
/app/internal/stream/stream.go:90 (0x9d3914)
/app/drivers/aliyundrive_open/upload.go:246 (0x1330ab3)
/app/drivers/aliyundrive_open/driver.go:196 (0x132e5b9)
/app/internal/op/fs.go:531 (0x8f1425)
/app/internal/fs/put.go:54 (0xdaac1c)
/app/internal/fs/fs.go:96 (0xda8ad4)
/app/server/webdav/webdav.go:336 (0x1667294)
/app/server/webdav/webdav.go:64 (0x166496f)
/app/server/webdav.go:46 (0x1671a64)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x16723ef)
/app/server/webdav.go:112 (0x16723d3)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x15f782d)
/app/server/middlewares/check.go:14 (0x15f7819)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd99821)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0xd9980c)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd98946)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0xd98929)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd979aa)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0xd97631)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0xd9715c)
/usr/lib/go/src/net/http/server.go:2936 (0x75b875)
/usr/lib/go/src/net/http/server.go:1995 (0x756d91)
/usr/lib/go/src/runtime/asm_amd64.s:1598 (0x479ae0)
```

### Reproduction / 复现链接

无

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xxxxxx",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/xxxx",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": xxx,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true

![图片](https://github.com/alist-org/alist/assets/27952575/4c907a78-1c97-4023-adb0-035c004d875a)

### Logs / 日志

2023/09/05 05:36:24 [Recovery] 2023/09/05 - 05:36:24 panic recovered:
runtime error: makeslice: cap out of range
/usr/lib/go/src/runtime/slice.go:33 (0x45a564)
/usr/lib/go/src/runtime/slice.go:100 (0x45a54c)
/app/internal/stream/stream.go:90 (0x9d3914)
/app/drivers/aliyundrive_open/upload.go:246 (0x1330ab3)
/app/drivers/aliyundrive_open/driver.go:196 (0x132e5b9)
/app/internal/op/fs.go:531 (0x8f1425)
/app/internal/fs/put.go:54 (0xdaac1c)
/app/internal/fs/fs.go:96 (0xda8ad4)
/app/server/webdav/webdav.go:336 (0x1667294)
/app/server/webdav/webdav.go:64 (0x166496f)
/app/server/webdav.go:46 (0x1671a64)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x16723ef)
/app/server/webdav.go:112 (0x16723d3)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x15f782d)
/app/server/middlewares/check.go:14 (0x15f7819)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd99821)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0xd9980c)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd98946)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0xd98929)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd979aa)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0xd97631)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0xd9715c)
/usr/lib/go/src/net/http/server.go:2936 (0x75b875)
/usr/lib/go/src/net/http/server.go:1995 (0x756d91)
/usr/lib/go/src/runtime/asm_amd64.s:1598 (0x479ae0)

**Comment by xhofe** [comment]
上传的是多大的文件

**Comment by ericma15** [comment]
1kb

**Comment by xhofe** [comment]
哪个webdav客户端

**Comment by ericma15** [comment]
用的一个备份软件，将webdav作为备份后端，用的kopia

**Comment by ericma15** [comment]
切回v3.26.0 ,就正常了

**Comment by ericma15** [comment]
应该是兼容问题，加了一层rclone做webdav到webdav转化，正常了

**Comment by LakeishaKowalczyk** [comment]
兼容问题还是存在

**Comment by xiaotianxt** [comment]
问题还是存在，阿里网盘无法被 webdav 上传文件
