### ISSUE TITLE
希望能增加分片上傳功能

### ISSUE THREAD

**Issue by Mr-Smilin** [alist-org/alist#5176]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

本人有使用 Cloudflare 做反代，Alist 用來提供本地存儲一個公開的頁面

透過爬文已經盡量解決 413 問題，目前卡在上傳檔案到 server 方式

無論是 stream 或是 form 都必須要提高單檔上傳上限才能解決傳輸問題

Cloudflare 沒辦法繞過這點，又不想另外開一個端點給 Cloudflare
  
如果能實作分片上傳，解決檔案上傳上限的問題，勢必會成為一種受歡迎的熱門功能

希望能提供第三種檔案上傳方式

如不能添加，希望能知道原因

### Suggested solution / 实现思路

查資料的過程，發現同樣是自建雲盤  

Cloudreve跟Nextcloud都有分片上傳的實現  

希望可以提供參考

**Comment by SeanHeuc** [comment]
网页上传根本不适合大文件上传，很容易出错，除非支持断点续传,例如mega做的很好，在没有开源代码可以借鉴的情况下，开发量还是不小的，还是建议webdav上传大文件，用rclone这样的工具会自动重试，完成后检测大小

**Comment by Mr-Smilin** [comment]
了解，並不是一定要做分片上傳，只是設計網頁讓所有人都能上傳，會希望能有較為穩定的上傳方式

只是自己人上傳的話方法很多，難免會有只希望讓人訪問網站的狀況，可以理解開發上困難，只能說比較可惜一點 。
