### ISSUE TITLE
建议支持s3访问（alist作为s3服务）

### ISSUE THREAD

**Issue by nick008a** [alist-org/alist#5186]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议在webdav之外，支持s3访问（alist作为s3服务）。
webdav协议现在不如s3协议支持广泛（支持s3可以串联restic备份工具/docker registry等）。
另外，许多网盘的功能支持也只有s3水平（不支持webdav的复制等）。

**Comment by xhofe** [comment]
related refer:
- https://github.com/rclone/rclone/issues/3382
- https://github.com/rclone/rclone/pull/6461

**Comment by Kuingsmile** [comment]
Support

**Comment by itsHenry35** [comment]
Rclone has had this feature done: https://github.com/rclone/rclone/commit/23abac2a59224321325018945953d35904909940
Dependency available: https://github.com/johannesboyne/gofakes3
