### ISSUE TITLE
希望增加将网盘目录模拟为本地目录的功能

### ISSUE THREAD

**Issue by jxjxjhjh** [alist-org/alist#5187]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

navidrome、PhotoPrism 这样的音乐和相册服务都需要将音乐文件、照片文件放在本地目录中，如果VPS空间不够大就无法使用，不知道alist能否将网盘的目录模拟成本地目录，如此一来就可以使用这些服务了。

**Comment by jxjxjhjh** [comment]
希望alist能增加这个功能。

**Comment by JsonSong89** [comment]
> 

alist是标准的BS结构的程序,怎么管到你client的东西?

**Comment by jxjxjhjh** [comment]
> > 
> 
> alist是标准的BS结构的程序,怎么管到你client的东西?
> 
> 你可以试试桌面版,或者小白羊 自己弄rclone也不麻烦

我觉得你们都理解错了我的意思。

我是想让alist把阿里云盘的目录挂在到alist所在本机目录中，有点软连接的意思。
桌面版并没有这个功能，rclone我查了下没看懂是不是我要的功能。

网上倒是有个项目，好像是叫 docker-webdav-client 这样的名字，可以把webdav模拟成本地目录。就是觉得不如alist本身支持比较好。

**Comment by anwen-anyi** [comment]
> > > 
> 
> > 
> 
> > alist是标准的BS结构的程序,怎么管到你client的东西?
> 
> > 
> 
> > 你可以试试桌面版,或者小白羊 自己弄rclone也不麻烦
> 
> 
> 
> 我觉得你们都理解错了我的意思。
> 
> 
> 
> 我是想让alist把阿里云盘的目录挂在到alist所在本机目录中，有点软连接的意思。
> 
> 桌面版并没有这个功能，rclone我查了下没看懂是不是我要的功能。
> 
> 
> 
> 网上倒是有个项目，好像是叫 docker-webdav-client 这样的名字，可以把webdav模拟成本地目录。就是觉得不如alist本身支持比较好。
> 
> 
> 
> 

你是指?把Alist像硬盘一样挂载到电脑?这个功能桌面版有啊

**Comment by smy116** [comment]
桌面版有这个功能

**Comment by jxjxjhjh** [comment]
> > > >
> > 
> > 
> > > 
> > 
> > 
> > > alist是标准的BS结构的程序,怎么管到你client的东西?
> > 
> > 
> > > 
> > 
> > 
> > > 你可以试试桌面版,或者小白羊 自己弄rclone也不麻烦
> > 
> > 
> > 我觉得你们都理解错了我的意思。
> > 我是想让alist把阿里云盘的目录挂在到alist所在本机目录中，有点软连接的意思。
> > 桌面版并没有这个功能，rclone我查了下没看懂是不是我要的功能。
> > 网上倒是有个项目，好像是叫 docker-webdav-client 这样的名字，可以把webdav模拟成本地目录。就是觉得不如alist本身支持比较好。
> 
> 你是指?把Alist像硬盘一样挂载到电脑?这个功能桌面版有啊


不是。
alist建立在vps上，在alist中添加本地存储，就可以将vps上的本地目录添加到alist中，但alist中添加的阿里云盘、百度网盘等存储，想要能够在vps上模拟成本地目录。
因为有一些其他服务，比如自建音乐库，只能扫描本地音乐文件。

**Comment by itsHenry35** [comment]
> 

用rclone或者桌面版就能模拟成本地目录啊

**Comment by KyrieWang0410** [comment]
桌面版有这个功能，但是复制不了文件
