### ISSUE TITLE
音频播放器 列表默认顺序播放

### ISSUE THREAD

**Issue by qian9008** [alist-org/alist#5188]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

最新版无法设置相关项目，当前默认为随机播放。

**Comment by jxjxjhjh** [comment]
音频播放器不够现代化，无论在PC还是手机操作，按钮都太小，不好操作，按钮状态也难以分辨，希望改进。

**Comment by itsHenry35** [comment]
@xhofe this shall be closed, completed in: https://github.com/alist-org/alist-web/commit/243416a5c5e9ea4dc646633ef8079bb165f4db6c

**Comment by itsHenry35** [comment]
Completed in: https://github.com/alist-org/alist-web/commit/243416a5c5e9ea4dc646633ef8079bb165f4db6c
