### ISSUE TITLE
使用阿里云OSS或S3均会在文件夹中出现占位文件，在设置中填写文件名或留空都不会消失

### ISSUE THREAD

**Issue by ltycn** [alist-org/alist#5190]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

S3

### Describe the bug / 问题描述

使用阿里云OSS或S3均会在文件夹中出现占位文件，在设置中填写文件名或留空都不会消失

### Reproduction / 复现链接

file.lnvpe.com

### Config / 配置

https://lnvpe-dl.oss-cn-hongkong.aliyuncs.com/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-09-07%20175128.png

**Comment by xhofe** [comment]
占位文件是必须的 不填则使用默认的名称。

**Comment by ltycn** [comment]
@xhofe 没太明白，这个空文件没办法移除掉？

**Comment by xhofe** [comment]
没办法

**Comment by Sakura-zyu** [comment]
@ltycn 您可以试试使用 “隐藏文件功能”来进行隐藏无效文件，在“设置-全局-隐藏文件”内用正则表达式来进行填写。例如    /\/二级文件夹名字/i

**Comment by Harrison3-1122** [comment]
> @ltycn 您可以试试使用 “隐藏文件功能”来进行隐藏无效文件，在“设置-全局-隐藏文件”内用正则表达式来进行填写。例如 //二级文件夹名字/i 亲测有效！！！ ![Snipaste_2023-09-11_23-56-24](https://private-user-images.githubusercontent.com/38059916/267078611-09b570eb-855b-4e1e-84ff-04ee2b54cbd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjM0MzIsIm5iZiI6MTcyNjU2MzEzMiwicGF0aCI6Ii8zODA1OTkxNi8yNjcwNzg2MTEtMDliNTcwZWItODU1Yi00ZTFlLTg0ZmYtMDRlZTJiNTRjYmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA4NTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYTY5ZGZmYzMyMjVkNmRlNzFjOGU0OWJmZTBiMTc5ZGI0ZTcyYTQyNzg0Yjk5NDRjYWM4YTVhZTAzMjhiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PtS9F0X7hvBg_IcutRQxPt2vGl3vlUUFgMpUgjIaUkE)

请问所有文件夹都需要写一遍这个规则吗

**Comment by bingsanyu** [comment]
@Harrison3-1122 
“列出对象版本”选择“V2”即可。
![image](https://github.com/user-attachments/assets/3771f200-799e-4b14-8214-4425ece1a3ab)
