### ISSUE TITLE
数据库路径以及日志路径反斜杠的问题

### ISSUE THREAD

**Issue by dreamncn** [alist-org/alist#5192]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

略

### Describe the bug / 问题描述

- 系统环境是Centos
在Linux中文件路径分隔符应该是 `/`
```shell
[root@centos-linux-test alist]# ls -lah
总用量 50M
drwxr-xr-x. 5 root root  154 9月   8 03:24 .
drwxr-xr-x. 5 root root   41 9月   7 23:32 ..
-rwxr-xr-x. 1 root root  49M 9月   3 23:21 alist
drwx------. 2 root root   23 9月   8 02:25 daemon
drwx------. 4 root root  101 9月   8 03:23 data
-rw-r--r--. 1 root root 4.0K 9月   8 03:24 data\data.db
-rw-r--r--. 1 root root  32K 9月   8 03:25 data\data.db-shm
-rw-r--r--. 1 root root 580K 9月   8 03:25 data\data.db-wal
-rw-r--r--. 1 root root  13K 9月   8 03:27 data\log\log.log
drwxr-xr-x. 2 root root    6 9月   8 03:24 data\temp
[root@centos-linux-test alist]# 
```

<img width="1013" alt="image" src="https://github.com/alist-org/alist/assets/37787014/41adebec-4461-45dd-a33b-d5f3fe3ec475">

### Reproduction / 复现链接

略

### Config / 配置

略

**Comment by xhofe** [comment]
路径均在`config.json`中设置，此文件在初次启动时生成
