### ISSUE TITLE
按目录查询文件/文件夹接口分页参数失效

### ISSUE THREAD

**Issue by vvnocode** [alist-org/alist#5197]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

按目录查询文件/文件夹接口分页接口为/api/fs/list，参数如下：
```json
{
    "path": "/Pictures/插画/yande_pools_collection",
    "password": "",
    "page": 1,
    "per_page": 0,
    "refresh": false
}
```
由于该文件夹下子文件有8000+多个，返回速度1.3秒，但是web端渲染花费5-6秒。

经测试，per_page在postman中传入非0值，/api/fs/list接口是可以生效的，也就是说分页接口没问题。
我在设置-站点-默认每页数量设置了30，但是实际接口调用传入依然是0。web端需要滚动时查询，而不是传入0查询全量数据。

综上，web端应该是有缺陷。

### Reproduction / 复现链接

https://myip/api/fs/list

### Config / 配置

```json
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "****",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}
```

**Comment by xhofe** [comment]
https://alist.nn.ci/zh/config/site.html#%E5%88%86%E9%A1%B5%E7%B1%BB%E5%9E%8B

**Comment by vvnocode** [comment]
> https://alist.nn.ci/zh/config/site.html#%E5%88%86%E9%A1%B5%E7%B1%BB%E5%9E%8B

设置-站点-默认每页数量设置成20了，但是没用。

**Comment by xhofe** [comment]
> > [alist.nn.ci/zh/config/site.html#%E5%88%86%E9%A1%B5%E7%B1%BB%E5%9E%8B](https://alist.nn.ci/zh/config/site.html#%E5%88%86%E9%A1%B5%E7%B1%BB%E5%9E%8B)
> 
> 设置-站点-默认每页数量设置成20了，但是没用。

看清楚我发的是什么

**Comment by vvnocode** [comment]
> > > [alist.nn.ci/zh/config/site.html#%E5%88%86%E9%A1%B5%E7%B1%BB%E5%9E%8B](https://alist.nn.ci/zh/config/site.html#%E5%88%86%E9%A1%B5%E7%B1%BB%E5%9E%8B)
> > 
> > 
> > 设置-站点-默认每页数量设置成20了，但是没用。
> 
> 看清楚我发的是什么

网站设置的配置文件在哪呢？找半天没找到。

**Comment by vvnocode** [comment]
> > > [alist.nn.ci/zh/config/site.html#%E5%88%86%E9%A1%B5%E7%B1%BB%E5%9E%8B](https://alist.nn.ci/zh/config/site.html#%E5%88%86%E9%A1%B5%E7%B1%BB%E5%9E%8B)
> > 
> > 
> > 设置-站点-默认每页数量设置成20了，但是没用。
> 
> 看清楚我发的是什么

谢谢
