### ISSUE TITLE
本地储存IPA安装

### ISSUE THREAD

**Issue by mrlihx** [alist-org/alist#5201]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

本地储存

### Describe the bug / 问题描述

网站已经开启了SSL，alist生成的.plist文件配置里的IPA文件下载地址是http开头，在IOS设备中无法安装

同样的IPA安装包使用阿里云盘Open可以正常安装

![微信截图_20230911103553](https://github.com/alist-org/alist/assets/68861286/cb35aace-9f77-43f7-b096-2f9c580d194f)

### Reproduction / 复现链接

no

### Config / 配置

![微信截图_20230911104117](https://github.com/alist-org/alist/assets/68861286/9eef567f-35cf-47f7-b13e-6e61fd75e872)

**Comment by xhofe** [comment]
- #726 
- #1159 
- #2429 
- #3644 
- #4181 
- #4719
- https://alist.nn.ci/guide/install/reverse-proxy.html
