### ISSUE TITLE
从阿里云盘秒传到115的文件会少几个文件

### ISSUE THREAD

**Issue by free-150** [alist-org/alist#5204]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v.3.27.0 

### Driver used / 使用的存储驱动

阿里、115

### Describe the bug / 问题描述

原本复制的文件夹里有720个文件复制完只有710多个。从阿里云盘秒传到115的文件会少几个文件，特别是文件多的复制任务。

### Reproduction / 复现链接

https://www.aliyundrive.com/s/8BYw3gYBsp7/folder/636a6f78217a1d5445f346e4a297d296dbe8ee21

### Config / 配置

<img width="474" alt="图片" src="https://github.com/alist-org/alist/assets/92285544/bfe064b6-9087-4546-a855-91f9204e51b1">

### Logs / 日志

查看「任务」-->「复制」并没有报错的文件

**Comment by bymao** [comment]
我也有这个问题。

**Comment by a5vq11** [comment]
我从移动硬盘传到115，有些文件也报错下面的代码，这是怎么回事你？
runtime error: slice bounds out of range [:24350] with capacity 144
