### ISSUE TITLE
文本文件预览：编码猜测

### ISSUE THREAD

**Issue by 1049731887** [alist-org/alist#5228]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

网页点击txt文件预览时，默认UTF-8，没有进行**编码猜测**导致文本乱码
_感觉这**算是**个bug吧，所以提交到这里了_

### Reproduction / 复现链接

不必

### Config / 配置

不必

**Comment by xiaoyaliu00** [comment]
是的，如果先预判，然后有下拉菜单可以手动选就好了
