### ISSUE TITLE
支持自动备份

### ISSUE THREAD

**Issue by 1049731887** [alist-org/alist#5231]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

AList内部支持自动备份，即选中一个需要备份的目录和一个备份到的目录，然后AList将自动开始备份
备份模式：

1. 增量备份：新增文件即备份
2. 全量备份：将备份目录做一个完整拷贝，同步更改
3. 历史记录备份：保存为多个按日期分类的文件夹，并进行备份

### Suggested solution / 实现思路

很需要，谢谢你！
而且这应该也可以方便大部分人

**Comment by MeTerminator** [comment]
感觉这个功能挺不错的，希望做一个同步储存功能，虽然不会golang，但是这是我想出对应的实现思路：
1.初次设置，需要对应的备份文件夹为空，自动将所有文件复制到对应存储
2.可以设置一个同步存储的上传优先级，从优先级最高的存储开始上传，再依次向下上传到对应的存储
3.定时执行目录扫描同步（或者用户在访问对应目录时比较，如果两方的文件不同则都显示，如果说有重名文件，可以设置默认显示修改日期最新或者保留两者等等）然后自动更新文件

**Comment by bilibili2077** [comment]
有时候docker出问题，alist存储要一个个添加很烦，有自动备份后即使出现问题也没事，很需要这个功能！

**Comment by SeanHeuc** [comment]
有很多第三方软件专门做备份的，建议去研究学习，然后分享。好用的备份功能需要的开发量可不是一点半点，关键是最怕就是什么都做做出四不像，什么都没有做好，大部分人都会用alist提供的webdav对接第三方成熟备份软件。软件工程角度叫做高内聚，低耦合

**Comment by free-150** [comment]
有个 `duplicati`开源软件可以配合 alist 实现备份
