### ISSUE TITLE
正常启动后5s后但是显示未运行

### ISSUE THREAD

**Issue by AbianTang** [alist-org/alist#5235]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

Version: v3.25.1-aarch64

### Driver used / 使用的存储驱动

/

### Describe the bug / 问题描述

🔧[33mWARN🔧[0m[2023-09-18 03:34:15] not enable search                            
🔧[33mWARN🔧[0m[2023-09-18 03:34:20] not enable search                            
🔧[33mWARN🔧[0m[2023-09-18 03:34:25] not enable search                            
🔧[33mWARN🔧[0m[2023-09-18 03:34:31] not enable search                            
🔧[33mWARN🔧[0m[2023-09-18 03:34:36] not enable search                            

### Reproduction / 复现链接

🔧[33mWARN🔧[0m[2023-09-18 03:34:15] not enable search                            
🔧[33mWARN🔧[0m[2023-09-18 03:34:20] not enable search                            
🔧[33mWARN🔧[0m[2023-09-18 03:34:25] not enable search                            
🔧[33mWARN🔧[0m[2023-09-18 03:34:31] not enable search                            
🔧[33mWARN🔧[0m[2023-09-18 03:34:36] not enable search                            

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 3306,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "/etc/alist/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 9000,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "/var/alist.sock",
    "unix_file_perm": ""
  },
  "temp_dir": "/tmp/alist",
  "bleve_dir": "/etc/alist/bleve",
  "log": {
    "enable": true,
    "name": "/tmp/alist/alist.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

**Comment by AbianTang** [comment]
log已经上传

**Comment by eunrui** [comment]
一样的问题
