### ISSUE TITLE
希望能增加访问频率限制

### ISSUE THREAD

**Issue by 443126500** [alist-org/alist#5236]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目的是为了防止同一资源获取到直链下载链接后，某些心理扭曲的人进行刷流量操作
希望能增加同一个ip固定时间内访问某个固定的路径，对访问频率进行限制，比如一个固定路径，单个ip限制每分钟访问5次
另外希望增加访问ip与访问次数统计功能！！！

**Comment by 443126500** [comment]
![image](https://github.com/alist-org/alist/assets/57339701/c56d405a-43cd-475a-91bc-f6c0db52d51e)
遇到这种刷流量的就很烦，虽然能nginx封禁ip，但是ip随随便便都可以换了！

**Comment by cabudon** [comment]
> ![image](https://user-images.githubusercontent.com/57339701/268539289-c56d405a-43cd-475a-91bc-f6c0db52d51e.png) 遇到这种刷流量的就很烦，虽然能nginx封禁ip，但是ip随随便便都可以换了！

你是开启了访客登录吗，大哥能私发一下站点吗

**Comment by 443126500** [comment]
开通访客登录了，也加密了，但是他那个验证是固定死的，等于一次获取直链后，就可以写个脚本无限制刷流量来恶心人，24-25号这两天有一千四百多个ip访问两个具体的资源刷流量

**Comment by 443126500** [comment]
![image](https://github.com/alist-org/alist/assets/57339701/0685dedd-9ba8-4fec-b74a-f312d47f9e16)
![image](https://github.com/alist-org/alist/assets/57339701/e0e78ab2-d767-4ed7-bf72-18d369f467ac)
![image](https://github.com/alist-org/alist/assets/57339701/f54f233a-81a6-4edf-8ff7-0ad87d81d281)
nginx能封禁ip，但是ip太多了，而且都是国内的

**Comment by xhofe** [comment]
https://www.google.com/search?q=nginx+%E9%98%B2%E7%81%AB%E5%A2%99
