### ISSUE TITLE
复制失败后增加一键重试按钮

### ISSUE THREAD

**Issue by liuhangbin** [alist-org/alist#5242]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

跨网盘复制的时候经常会出现复制出错。每个失败都需要单独点击重试。有点麻烦。请问是否可以增加一个一键全部重试按钮。这样方便大家重新复制。

另外如果可以的话，还可以增加一个选择框，可以一键全部选择，然后单独取消个别失败不再重试。

### Suggested solution / 实现思路

类似CD2实现。

**Comment by ssln5014** [comment]
赞成

**Comment by ssln5014** [comment]
> 简单的用python写了个一键重试(自己糊弄的半成品，欢迎python大神修改) [alist一键重试.zip](https://github.com/alist-org/alist/files/12774968/alist.zip)
> 
> config.yaml里api_domain是你的alist域名或者ip端口，authorization需要f12抓取，在网络里，找到get就有了 ![QQ截图20230930212839](https://user-images.githubusercontent.com/24273319/271779826-4c249cf9-1363-4fcb-aca1-5abb1042f405.png)

很好用，谢谢

**Comment by ssln5014** [comment]
> 简单的用python写了个一键重试(自己糊弄的半成品，欢迎python大神修改) [alist一键重试.zip](https://github.com/alist-org/alist/files/12774968/alist.zip)
> 
> config.yaml里api_domain是你的alist域名或者ip端口，authorization需要f12抓取，在网络里，找到get就有了 ![QQ截图20230930212839](https://user-images.githubusercontent.com/24273319/271779826-4c249cf9-1363-4fcb-aca1-5abb1042f405.png)

放到action上定时运行[https://github.com/ssln5014/alist-retry-copy-task]( https://github.com/ssln5014/alist-retry-copy-task )

**Comment by jianboy** [comment]
我问一下，**复制**

A 文件夹 复制到 B文件夹，复制到一半异常。 那么，重新执行 A文件夹复制到 B文件夹, 那么 B文件夹是会

- 1、文件覆盖呢，
- 2、重命名保存，
- 3、检测是否存在，存在则不复制。

哪种情况呢？

**Comment by jianboy** [comment]
注意：

复制异常，重启alist复制列表清空了。所以无法重试。。。。。。。。。。。。。。所以重试按钮都没用，想问一下，复制的规则是什么。

**Comment by jianboy** [comment]
@pongfcnkl **谢谢，那目录怎么同步呢？**

长时间运行，alist会崩溃的，比如网络异常，接口异常。所以重启是无法避免的。

比如 A 目录，同步到 B 目录。同步策略：

文件大小一致，或者简单的文件名存在就不复制。

**Comment by ox68** [comment]
希望作者可以实现这个功能

**Comment by ssln5014** [comment]
好耶！
