### ISSUE TITLE
支持导出strm文件，用于Emby本地刮削

### ISSUE THREAD

**Issue by wisinfun** [alist-org/alist#5249]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://emby.media/support/articles/Strm-Files.html

strm文件是一种外部链接文件，适用于Emby搜刮。这样emby客户端播放时是直接访问的源地址。

之前是利用alist和rclone将云盘挂载到本地，但这样，emby客户端播放时，会占用emby服务器的带宽。所以如果能实现导出strm，对影音爱好者是极其有用的

### Suggested solution / 实现思路

alist文件夹可以一键导出strm包，保持原有文件夹结构，自动将视频文件转为包含alist链接的strm文件，其他文件（图片、字幕）直接下载

PS：如果能实现自动导出到指定目录，那就更完美了

PS：纠正下，emby不支持strm直链，jellyfin据说支持，待验证

**Comment by arthurxxy** [comment]
现在支持这个功能了吗

**Comment by xtxt19931207** [comment]
> 现在支持这个功能了吗

正好我用python做了这个脚本，把alist直链转存为strm

**Comment by xtxt19931207** [comment]
我用python做了这个脚本，把alist播放直链转存为strm，但是在外网播放好像没法直链播放，还是走的服务器流量

**Comment by arthurxxy** [comment]
推荐用小雅alist，strm包括元数据都帮你整理好了

xtxt19931207 ***@***.***> 于2023年11月3日周五 08:24写道：

**Comment by CGG888** [comment]
“之前是利用alist和rclone将云盘挂载到本地，但这样，emby客户端播放时，会占用emby服务器的带宽。所以如果能实现导出strm，对影音爱好者是极其有用的”

通过Nginx以后，客户端播放的时候不占用服务器带宽啊！emby和alist的key利用好不就可以了！

**Comment by aaaol** [comment]
> “之前是利用alist和rclone将云盘挂载到本地，但这样，emby客户端播放时，会占用emby服务器的带宽。所以如果能实现导出strm，对影音爱好者是极其有用的”
> 
> 通过Nginx以后，客户端播放的时候不占用服务器带宽啊！emby和alist的key利用好不就可以了！

具体时怎样操作 njs难度太高了
