### ISSUE TITLE
恳请增加对曲奇云盘支持

### ISSUE THREAD

**Issue by qwe159357890** [alist-org/alist#5251]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

恳请增加对曲奇云盘支持(https://quqi.com/)
使用好几年了,免费空间就2T 无限速,不吞文件
个人感觉要比其他好多了

**Comment by SuperLoserPeco** [comment]
同求

**Comment by bamboo512** [comment]
我之前也恰好研究过 Alist 支持曲奇的可能性。

曲奇并未提供官方 API。
更糟糕的是，曲奇的网页版几乎等同于无，甚至无法完整下载云盘中的相当一部分文件。此外，App 版也仅限一台设备登录。
从这些角度出发，可以说曲奇做得十分糟糕，根本无法作为 Alist 的存储盘。
