### ISSUE TITLE
请支持115的内部上传

### ISSUE THREAD

**Issue by free-150** [alist-org/alist#5252]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

115使用阿里深圳的服务器可以使用内部上传的功能。
需要115在服务器的所在地域开通了阿里云OSS，可以在服务器上运行 `curl https://uplb.115.com/3.0/getuploadinfo.php` 查看OSS地域。

**Comment by xhofe** [comment]
deps: https://github.com/SheltonZhu/115driver

**Comment by SheltonZhu** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure this feature is not implemented.
> * [x]  I'm sure it's a reasonable and popular requirement.
> 
> ### Description of the feature / 需求描述
> 115使用阿里深圳的服务器可以使用内部上传的功能。 需要115在服务器的所在地域开通了阿里云OSS，可以在服务器上运行 `curl https://uplb.115.com/3.0/getuploadinfo.php` 查看OSS地域。
> 
> ### Suggested solution / 实现思路
> _No response_
> 
> ### Additional context / 附件
> _No response_

请具体描述下如何内部上传。查看地域的接口应该是实现了的。

**Comment by free-150** [comment]
可以看看这个：https://github.com/orzogc/fake115uploader

**Comment by SheltonZhu** [comment]
> 可以看看这个：https://github.com/orzogc/fake115uploader

看了下原理，其实也就是oss域名增加了-internal，实现起来不难，但是需要测试一下…正好刚买了阿里云的服务器🤣
