### ISSUE TITLE
显示IP

### ISSUE THREAD

**Issue by sonichy** [alist-org/alist#5264]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

```
alist server
start HTTP server @ 0.0.0.0:5244
```
显示 192.168.1.105:5244，不然还要去查看 IP 地址。

**Comment by pshen** [comment]
0.0.0.0是listen在所有interface上。如果一台机器有多个ip地址，那只显示一个就没意思了。
