### ISSUE TITLE
建议网盘挂载通用选项添加“无缓存”选项

### ISSUE THREAD

**Issue by LittleJake** [alist-org/alist#5270]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

由于缓存的存在，会导致client app进行webdav挂载时出现client app无法校验文件的修改导致重复上传或目录刷新严重超时的情况。

### Suggested solution / 实现思路

网盘挂载通用项增加 `无缓存` 选项，缓存根据这个选项判断是否每次请求进行刷新。

**Comment by xhofe** [comment]
0即无缓存。
