### ISSUE TITLE
未登录可以下载任意文件

### ISSUE THREAD

**Issue by JefferyTest** [alist-org/alist#5272]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.19.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

windows上部署的alist服务，用admin账户上传了一些文件，但是guest用户可不见此文件，如果用admin登陆之后，复制文件下载的链接发给其他人， 其他人可以直接下载该文件，是哪里配置错了吗？

### Reproduction / 复现链接

无

### Config / 配置

无

### Logs / 日志

无

**Comment by xhofe** [comment]
https://alist.nn.ci/config/global.html#sign-all
