### ISSUE TITLE
离线下载上传阶段出现大量未知错误

### ISSUE THREAD

**Issue by DEV4895** [alist-org/alist#5274]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

OnedriveAPP

### Describe the bug / 问题描述

离线下载上传时出现很多unexpected EOF
出现无规律，与文件大小似乎没有关系
![image](https://github.com/alist-org/alist/assets/101171334/78c449f0-b387-4e2d-9490-2ce0a34178ba)
![image](https://github.com/alist-org/alist/assets/101171334/ff84d98c-4ad7-449c-812c-35254a908765)

### Reproduction / 复现链接

无法提供

### Config / 配置

{
  "force": false,
  "site_url": "/alist",
  "cdn": "",
  "jwt_secret": .
  "token_expires_in": 48,
  "database": {
    "type": "mysql",
    "host": ".
    "port": .
    "user": ".,
    "password":.
    "name": .
    "db_file": .
    "table_prefix": .
    "ssl_mode": .
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

### Logs / 日志

[31mERRO[0m[2023-09-23 08:57:55] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 IMAX UHD 4K Box Cover.png: file already closed 
[31mERRO[0m[2023-09-23 08:57:55] error [unexpected EOF
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	/home/runner/work/alist/alist/internal/qbittorrent/monitor.go:175
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598] while run task [transfer /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 IMAX UHD 4K Box Cover.png to [/Sharepoint_DEV4895Admin](/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 IMAX UHD 4K Box Cover.png)] 
[31mERRO[0m[2023-09-23 08:57:56] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 IMAX UHD 4K Box Cover 2.png: file already closed 
[31mERRO[0m[2023-09-23 08:57:57] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 02.jpg: file already closed 
[31mERRO[0m[2023-09-23 08:57:57] error [unexpected EOF
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	/home/runner/work/alist/alist/internal/qbittorrent/monitor.go:175
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598] while run task [transfer /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 02.jpg to [/Sharepoint_DEV4895Admin](/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 02.jpg)] 
[31mERRO[0m[2023-09-23 08:57:58] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 Poster 2.jpg: file already closed 
[31mERRO[0m[2023-09-23 08:57:58] error [unexpected EOF
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	/home/runner/work/alist/alist/internal/qbittorrent/monitor.go:175
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598] while run task [transfer /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 Poster 2.jpg to [/Sharepoint_DEV4895Admin](/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 Poster 2.jpg)] 
[31mERRO[0m[2023-09-23 08:57:58] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 IMAX UHD 4K Box Cover 3.png: file already closed 
[31mERRO[0m[2023-09-23 08:57:58] error [unexpected EOF
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	/home/runner/work/alist/alist/internal/qbittorrent/monitor.go:175
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598] while run task [transfer /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 IMAX UHD 4K Box Cover 3.png to [/Sharepoint_DEV4895Admin](/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 IMAX UHD 4K Box Cover 3.png)] 
[36mINFO[0m[2023-09-23 08:57:58] build index for: [/Sharepoint_DEV4895Admin/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster] 
[36mINFO[0m[2023-09-23 08:57:58] ignore paths: [/Local]                       
[31mERRO[0m[2023-09-23 08:57:59] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 Poster.jpg: file already closed 
[31mERRO[0m[2023-09-23 08:57:59] error [unexpected EOF
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	/home/runner/work/alist/alist/internal/qbittorrent/monitor.go:175
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598] while run task [transfer /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 Poster.jpg to [/Sharepoint_DEV4895Admin](/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 Poster.jpg)] 
[31mERRO[0m[2023-09-23 08:57:59] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 Poster 3.jpg: file already closed 
[31mERRO[0m[2023-09-23 08:57:59] error [unexpected EOF
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	/home/runner/work/alist/alist/internal/qbittorrent/monitor.go:175
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598] while run task [transfer /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 Poster 3.jpg to [/Sharepoint_DEV4895Admin](/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster/Mission Impossible Fallout 2018 Poster 3.jpg)] 
[36mINFO[0m[2023-09-23 08:57:59] build index for: [/Sharepoint_DEV4895Admin/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Box Cover,Poster] 
[36mINFO[0m[2023-09-23 08:57:59] ignore paths: [/Local]                       
[31mERRO[0m[2023-09-23 08:58:00] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 03.jpg: file already closed 
[31mERRO[0m[2023-09-23 08:58:00] error [unexpected EOF
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	/home/runner/work/alist/alist/internal/qbittorrent/monitor.go:175
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598] while run task [transfer /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 03.jpg to [/Sharepoint_DEV4895Admin](/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 03.jpg)] 
[36mINFO[0m[2023-09-23 08:58:01] success build index, count: 1                
[36mINFO[0m[2023-09-23 08:58:01] build index for: [/Sharepoint_DEV4895Admin/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens] 
[36mINFO[0m[2023-09-23 08:58:01] ignore paths: [/Local]                       
[31mERRO[0m[2023-09-23 08:58:01] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 06.jpg: file already closed 
[31mERRO[0m[2023-09-23 08:58:01] error [unexpected EOF
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	/home/runner/work/alist/alist/internal/qbittorrent/monitor.go:175
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598] while run task [transfer /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 06.jpg to [/Sharepoint_DEV4895Admin](/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 06.jpg)] 
[31mERRO[0m[2023-09-23 08:58:02] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 04.jpg: file already closed 
[31mERRO[0m[2023-09-23 08:58:02] error [unexpected EOF
github.com/alist-org/alist/v3/internal/op.Put
	/home/runner/work/alist/alist/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/qbittorrent.(*Monitor).complete.func2
	/home/runner/work/alist/alist/internal/qbittorrent/monitor.go:175
github.com/alist-org/alist/v3/pkg/task.(*Task[...]).run
	/home/runner/work/alist/alist/pkg/task/task.go:82
github.com/alist-org/alist/v3/pkg/task.(*Manager[...]).do.func1
	/home/runner/work/alist/alist/pkg/task/manager.go:33
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598] while run task [transfer /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 04.jpg to [/Sharepoint_DEV4895Admin](/Anime/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 04.jpg)] 
[31mERRO[0m[2023-09-23 08:58:03] failed to close file streamer, close /opt/alist/data/temp/qbittorrent/e7f59852-e74d-4982-8807-a4caa1920f00/Mission Impossible Fallout 2018 IMAX UHD 4K BluRay 2160p HDR10 TrueHD 7.1 Atmos H.265-MgB/Sample,Screens/Mission Impossible Fallout 2018 IMAX UHD 4K Screen 08.jpg: file already closed

**Comment by xhofe** [comment]
这可能只与网络相关。

**Comment by DEV4895** [comment]
从前没有出现过（大概是v3.26之前）

**Comment by DEV4895** [comment]
再次测试，使用aria2下载时全部成功，感觉有点奇怪

**Comment by xhofe** [comment]
所以说与网络有关，之后会加上重试。
