### ISSUE TITLE
添加迅雷提示错误

### ISSUE THREAD

**Issue by wxiaofan** [alist-org/alist#5286]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

最新版本

### Driver used / 使用的存储驱动

迅雷

### Describe the bug / 问题描述

Failed init storage but storage is already created: failed init storage: ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: meta.username expect, but got map[phone_number:+86 ******* result:accept], please check captcha init params

### Reproduction / 复现链接

Failed init storage but storage is already created: failed init storage: ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: meta.username expect, but got map[phone_number:+86 ******* result:accept], please check captcha init params

### Config / 配置

Failed init storage but storage is already created: failed init storage: ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: meta.username expect, but got map[phone_number:+86 ******* result:accept], please check captcha init params

### Logs / 日志

Failed init storage but storage is already created: failed init storage: ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: meta.username expect, but got map[phone_number:+86 ******* result:accept], please check captcha init params

**Comment by foxxorcat** [comment]
迅雷规则有变，账号前面加区号改为 “+86 xxxxxx”

**Comment by anwen-anyi** [comment]
这样就可以。
![image](https://github.com/alist-org/alist/assets/56105412/d59982ff-2976-40b7-831b-f5a4f7f1ceff)

**Comment by i990049** [comment]
能不能搞个扫码刷token，还有那个pikpak也是

**Comment by EricLeeaaaaa** [comment]
> 这样就可以。 ![image](https://user-images.githubusercontent.com/56105412/270319194-d59982ff-2976-40b7-831b-f5a4f7f1ceff.png)

貌似在我这里不行

**Comment by Logzhan** [comment]
实在不行就把之前的删除了，然后重新建立

**Comment by Logzhan** [comment]
> 迅雷规则有变，账号前面加区号改为 “+86 xxxxxx”



> 这样就可以。 ![image](https://private-user-images.githubusercontent.com/56105412/270319194-d59982ff-2976-40b7-831b-f5a4f7f1ceff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NzI2MTUsIm5iZiI6MTcwNzk3MjMxNSwicGF0aCI6Ii81NjEwNTQxMi8yNzAzMTkxOTQtZDU5OTgyZmYtMjk3Ni00MGI3LTgzMWItZjVhNGY3ZjFjZWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA0NDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZjZlZjk0ZGQxODMyNmVjMmFiNmM2NmFiZjM2Y2NhN2M0YjNjOTA5ODRiYWY0OWIwMzI4NmE0NjM4ZWRhNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iqys9l9mSklCkPQDY6Z8Fu9F6bFEQ0eGZp2q1hwMLFk)

注意要加空格
