### ISSUE TITLE
一直请求更新，即时更新后，它依旧提醒

### ISSUE THREAD

**Issue by siwuxei** [alist-org/alist#5295]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.28.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/50586809/d5d2c971-78d0-4aae-bc3f-e9cca684b8ca)

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/50586809/d5d2c971-78d0-4aae-bc3f-e9cca684b8ca)

### Config / 配置

![image](https://github.com/alist-org/alist/assets/50586809/d5d2c971-78d0-4aae-bc3f-e9cca684b8ca)

**Comment by xhofe** [comment]
查看版本的话是v3.28.0吗？

不是的话可以去https://ad.nn.ci/ 手动下载更新一下。

**Comment by siwuxei** [comment]
> 查看版本的话是v3.28.0吗？
> 
> 不是的话可以去https://ad.nn.ci/ 手动下载更新一下。
是新版本，每次重启电脑就会提醒我更新（貌似自动退回老版本了），我明明更新不下于十几次了

更新后启动不了：
[AD] Starting AList...
INFO[2023-09-27 16:58:29] reading config file: C:\Users\intel\AppData\Roaming\ci.nn.alist\config.json
INFO[2023-09-27 16:58:29] load config from env with prefix: ALIST_
INFO[2023-09-27 16:58:29] init logrus...
WARN[2023-09-27 16:58:29] not enable search
INFO[2023-09-27 16:58:29] start HTTP server @ 0.0.0.0:5244
FATA[2023-09-27 16:58:29] failed to start http: listen tcp 0.0.0.0:5244: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
[AD] Command finished with code 1 and signal null
[AD] Restarting AList...
[AD] Stopping AList...
[AD] Starting AList...
INFO[2023-09-27 16:58:42] reading config file: C:\Users\intel\AppData\Roaming\ci.nn.alist\config.json
INFO[2023-09-27 16:58:42] load config from env with prefix: ALIST_
INFO[2023-09-27 16:58:42] init logrus...
WARN[2023-09-27 16:58:42] not enable search
INFO[2023-09-27 16:58:42] start HTTP server @ 0.0.0.0:5244
FATA[2023-09-27 16:58:42] failed to start http: listen tcp 0.0.0.0:5244: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
[AD] Command finished with code 1 and signal null

**Comment by siwuxei** [comment]
每次重启电脑就会提醒我更新（貌似自动退回老版本了），我明明更新不下于十几次了

**Comment by siwuxei** [comment]
每次重启电脑就会提醒我更新，这时它退回老版本，更新后无法启动，报错如上所示，唉，死循环

**Comment by xhofe** [comment]
请通过面包多私信远程。
