### ISSUE TITLE
ts文件不能在线播放，期望优化支持，谢谢

### ISSUE THREAD

**Issue by zilaiwei** [alist-org/alist#5301]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

ts文件不能在线播放，期望优化支持，谢谢

### Suggested solution / 实现思路

ts文件不能在线播放，期望优化支持，谢谢

### Additional context / 附件

ts文件不能在线播放，期望优化支持，谢谢

**Comment by xhofe** [comment]
我目前没有发现任何有关于在浏览器中支持播放ts文件的库或示例，也没有找到”浏览器支持ts文件“的任何依据。

如果我忽略了什么，欢迎你提供一个相关的示例来支持此issue。
