### ISSUE TITLE
希望增加Seafile的token登录

### ISSUE THREAD

**Issue by TanO732** [alist-org/alist#5302]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

某些学校使用Seafile搭建的网盘通过接入学校的统一认证来登录，无法通过现有Seafile驱动挂载

### Suggested solution / 实现思路

Seafile的Terminal 客户端在 8.0.4 版本后以后支持使用 Token 进行同步，以某大学网盘系统为例，每个账户的 Token 是唯一的，并且不会过期。seaf-cli 实质上是通过 pysearpc 与 seaf-daemon 通讯，因此大部分发行版默认源中较低版本的 seafile 在只替换 seaf-cli 的情况下也能正常工作。通过安装 Terminal 客户端后替换 seaf-cli 实现 Token 登录。

**Comment by xhofe** [comment]
需要更多信息，比如使用Token请求的一个示例。

**Comment by TanO732** [comment]
![Screenshot_20231001-234817~2.png](https://github.com/alist-org/alist/assets/52616511/c5f3e656-8fc8-4464-aafd-d7f25b340ea0)

这是他人给出的具体流程以供参考

**Comment by itsHenry35** [comment]
![image](https://github.com/alist-org/alist/assets/58730749/f7206dde-fc2a-43b7-bd16-65d0d2a6d15f)
do you mean this token

**Comment by TanO732** [comment]
I think yes
