### ISSUE TITLE
failed get enabled storages: Post "https://api.xhofe.top/alist/ali_open/token": EOF

### ISSUE THREAD

**Issue by ZHLONG-CN** [alist-org/alist#5303]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

 v3.26.0

### Driver used / 使用的存储驱动

阿里云盘 open

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/20869871/30125ebb-cdb7-45dc-802a-6156fe5083fb)

建议检查 `59.47.74.99` 服务器所在的问题

### Reproduction / 复现链接

[https://alist.nn.ci/zh/guide/drivers/aliyundrive_open.html](https://alist.nn.ci/zh/guide/drivers/aliyundrive_open.html)

使用 `https://api.xhofe.top` (辽宁多线， 由亚洲云赞助) 即可复现.

### Config / 配置

/

### Logs / 日志

```
2023/09/28 19:46:13.212466 ERROR RESTY Post "https://api.xhofe.top/alist/ali_open/token": EOF, Attempt 1
2023/09/28 19:46:13.486265 ERROR RESTY Post "https://api.xhofe.top/alist/ali_open/token": EOF, Attempt 2
2023/09/28 19:46:13.836822 ERROR RESTY Post "https://api.xhofe.top/alist/ali_open/token": EOF, Attempt 3
2023/09/28 19:46:14.274032 ERROR RESTY Post "https://api.xhofe.top/alist/ali_open/token": EOF, Attempt 4
ERRO[2023-09-28 19:46:14] failed get enabled storages: Post "https://api.xhofe.top/alist/ali_open/token": EOF
failed init storage
github.com/alist-org/alist/v3/internal/op.initStorage
        /source/internal/op/storage.go:99
github.com/alist-org/alist/v3/internal/op.LoadStorage
        /source/internal/op/storage.go:80
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
        /source/internal/bootstrap/storage.go:20
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1650
```

**Comment by xhofe** [comment]
已切服务器。
