### ISSUE TITLE
关于onedrive加速的意见

### ISSUE THREAD

**Issue by ixmu** [alist-org/alist#5310]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist直接访问的是https://uname-my.sharepoint.com/.......................................一串
速度有点慢，是不是考虑使用nginx或者cdn加速

### Suggested solution / 实现思路

可以用nginx或者cdn反代uname-my.sharepoint.com，变成uname-my.ixnic.net实现加速
后台可以考虑增加一个功能，自动将uname-my.sharepoint.com替换成uname-my.ixnic.net的选项
例如nginx配置
`location /
{
    expires 12h;
    if ($request_uri ~* "(php|jsp|cgi|asp|aspx)")
    {
         expires 0;
    }
    proxy_pass https://v4mrz-my.sharepoint.com;
    proxy_set_header Host v4mrz-my.sharepoint.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_buffering off;
    proxy_cache off;
    proxy_set_header X-Forwarded-Proto $scheme;
    add_header X-Cache $upstream_cache_status;
}`

**Comment by bilibili2077** [comment]
有CF的反代说明！

**Comment by ypq123456789** [comment]
uname-my.ixnic.net   老哥这个是啥，你自己搭建的加速服务器吗

**Comment by ixmu** [comment]
> Referenc

看了一下是cf反代了alist，而我要实现的是反代onedrive
这样可以最大限度加速

**Comment by ixmu** [comment]
> uname-my.ixnic.net 老哥这个是啥，你自己搭建的加速服务器吗

nginx的加速器或者使用CDN
nginx代码在上面，供参考
