### ISSUE TITLE
能否实现任务持久化

### ISSUE THREAD

**Issue by ssln5014** [alist-org/alist#5313]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

例如复制文件，或者离线下载，重启程序后没办法继续，而且也没有历史记录，不知道能不能实现这个功能

**Comment by ox68** [comment]
希望能够实现这个功能，非常需要

**Comment by yyyytawa** [comment]
> ### Please make sure of the following things
> * [ ]  I have read the [文档](https://alist.nn.ci)。
> * [ ]  I'm sure there are no duplicate issues or discussions.
> * [ ]  I'm sure this feature is not implemented.
> * [ ]  I'm sure it's a reasonable and popular requirement.
> 
> ### Description of the feature / 需求描述
> 例如复制文件，或者离线下载，重启程序后没办法继续，而且也没有历史记录，不知道能不能实现这个功能
> 
> ### Suggested solution / 实现思路
> _No response_
> 
> ### Additional context / 附件
> _No response_

建议再加个强制取消所有任务(或者是给个持久化的开关),避免alist出bug导致任务无法取消
