### ISSUE TITLE
alist作为容器启动，能都通过环境变量或者启动参数来实现预设配置直接自动化部署上线。尤其在K8S里面。

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#5314]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

用了1年，

[单纯用于挂载第三方网盘] 

从来源的单机直接安装在服务器，后面玩到单个docker部署，最后升级到K8S部署。
对于易迁移和恢复，一直觉得有点力不从心。
每次都要备份整个db，打包zip，复制到另一个服务器。累啊...

通过webui备份下来是一个json，里面看了，直接就包含各个项目和存储配置项目。
所以，能不能在Alist启动的时候 直接指定 config.json 文件映射 实现alist启动后的自动部署(等于webui的操作 备份与恢复的 恢复操作)  这样一来 真心不用 到哪都打包一个db文件到处跑。直接把需要的信息写死在启动参数里面。一个Pipeline流水线 自动就完成了。最多拖一个json配置文件岂不快哉.

另外对于 设置默认admin 账密 目前如果用docker-compose.yml 无法实现 alist启动后自动执行shell来设置，K8S pod生命后期hook倒是特别好弄。所以，干脆，直接给出 初始化参数 command 跟随alist启动 来设置管理员账密如何？

毕竟，单纯用于挂载第三方网盘的alist 真心没必要 拖着db来迁移.. 缓存可丢弃其实!
而且如果alist后期版本大更新db结构变化，拖着db备份映射 docker镜像一次性大升级会导致不可预知的错误...

### Suggested solution / 实现思路

参考 docker-compose.yml 的 command 这块

**Comment by xx6z8v** [comment]
使用远程数据库,完全可以实现一个config.json随处使用

**Comment by gowy222** [comment]
> 使用远程数据库,完全可以实现一个config.json随处使用

镜像跨版本更新db数据结构不同会变成灾难.. nextcloud就是典型案例!
