### ISSUE TITLE
可以不可以实现托拉到网页上传呀！

### ISSUE THREAD

**Issue by jiuaiwo** [alist-org/alist#5318]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

可以不可以实现托拉到网页上传呀！
直接拖拉文件到网页实现上床

**Comment by xhofe** [comment]
![image](https://github.com/alist-org/alist/assets/36558727/5ccdd9b4-1982-4eb8-bd77-d04f057a4f07)
