### ISSUE TITLE
/api/fs/put接口分块编码上传空文件报错

### ISSUE THREAD

**Issue by ChenyangGao** [alist-org/alist#5319]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

使用/api/fs/put上传空文件，请求头为
```json
{
    "User-Agent": "python-requests/2.31.0",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept": "*/*",
    "Connection": "keep-alive",
    "Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNjk2MzQzNDU2LCJuYmYiOjE2OTYxNzA2NTYsImlhdCI6MTY5NjE3MDY1Nn0.e9fqRrjufWme6tTLNvfmmYncGRu1nwMGA4B_1TDYGTA",
    "File-Path": "/115/1",
    "Transfer-Encoding": "chunked"
}
```
这里没有Content-Length，而Transfer-Encoding为chunked，然后服务端获得响应
```json
{
    "code": 400,
    "message": "strconv.ParseInt: parsing \"\": invalid syntax",
    "data": null
}
```
粗略猜测是，请求头没有Content-Length，默认值为空字符串""，go语言的strconv.ParseInt对空字符串处理会报错

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by xhofe** [comment]
抱歉 当前上传接口暂不支持chunked模式，必须要获取文件的大小，否则无法处理。
