### ISSUE TITLE
文件和文件夹前增加一个多选框，支持批量移动、删除、复制、统计等功能

### ISSUE THREAD

**Issue by ChenyangGao** [alist-org/alist#5320]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

类似这些网盘，文件和文件夹有多选框，支持批量操作

<img width="951" alt="截屏2023-10-01 22 52 23" src="https://github.com/alist-org/alist/assets/26198875/ab039353-6bca-4100-a347-eb5c7b7db491">
<img width="936" alt="截屏2023-10-01 22 52 34" src="https://github.com/alist-org/alist/assets/26198875/caa82b88-9bc3-4a2d-a8ad-e8e5808a7247">

**Comment by xhofe** [comment]
![image](https://github.com/alist-org/alist/assets/36558727/dd935080-f29b-4218-9f7d-3207cfa9be7b)
