### ISSUE TITLE
使用qb离线下载到115，文件与实际不符

### ISSUE THREAD

**Issue by ggrreeeedd** [alist-org/alist#5321]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

alist离线下载到挂载的115，磁力包含2个文件，mp4和nfo，mp4秒传，nfo需要上传，本来磁力内的nfo很小，但经过上传后和mp4大小一样。
已上传成功文件如下：
![photo_2023-10-01_23-18-45](https://github.com/alist-org/alist/assets/131668611/0d0a77e1-6d7d-4d30-9e89-29762bee62c4)

实际的nfo大小
![photo_2023-10-01_23-18-53](https://github.com/alist-org/alist/assets/131668611/b484857d-18f4-4246-bc9a-bfe2aac1e618)

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by DEV4895** [comment]
到Onedrive也会有这个问题，我下了一个剧集，本来每个文件都有1.3G左右，上传上去只有400多M，本来想提，但是vps重新装了机，后来就没问题了，就没提（还以为是系统/内存的问题），确实感觉有哪里出问题了
