### ISSUE TITLE
在“别名”存储驱动下若路径中包含有“-”符号时会导致输出内容出现问题

### ISSUE THREAD

**Issue by Mcxunyun666** [alist-org/alist#5328]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

别名

### Describe the bug / 问题描述

当路径中包含特殊符号时会导致输出文件夹内容出现错误。
例如，“-”会导致路径出现输出问题（描述似乎不是特别清楚可以直接看图）

### Reproduction / 复现链接

https://d.oxyxc.top/%E4%BA%A4%E4%BA%92%E5%BC%8F%E6%99%BA%E8%83%BD%E7%99%BD%E6%9D%BFPC%E6%A8%A1%E5%9D%97%E7%B3%BB%E7%BB%9F%E9%95%9C%E5%83%8F

### Config / 配置

![image](https://github.com/alist-org/alist/assets/51842260/6883fd09-7e65-4ba6-8aa9-f3dbd32501d0)
![image](https://github.com/alist-org/alist/assets/51842260/29cbbc48-8bf5-440d-9209-1e58fb267738)
![image](https://github.com/alist-org/alist/assets/51842260/6a9d4cab-f9e5-4233-addf-e6499f5d308f)
![image](https://github.com/alist-org/alist/assets/51842260/f82922fe-0ca1-40bf-b67e-5802c63a5457)

**Comment by xhofe** [comment]
没有看到哪里有问题？

**Comment by Mcxunyun666** [comment]
> 没有看到哪里有问题？请明确指出

正常来说 “/交互式智能白板PC模块系统镜像” 下的文件应该是指向的这两个目录下文件的混合，但是由于“/mount/189yun_9023_family/lmxiao/mirr-xrgzs/教育系统镜像”中包含了字符“-”导致显示为两个单独的文件夹“iwbsys”,“教育系统镜像”。
当我把“/mount/189yun_9023_family/lmxiao/mirr-xrgzs/教育系统镜像”条目删除后才会显示正常

**Comment by Mcxunyun666** [comment]
> 没有看到哪里有问题？请明确指出

抱歉刚才又仔细看了下文档，似乎是我设置的逻辑有问题，麻烦开发者大大了
