### ISSUE TITLE
蓝奏云cookie账号登录下载文件提示failed link: failed get link: not find file page param

### ISSUE THREAD

**Issue by luomo-pro** [alist-org/alist#5332]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

蓝奏云

### Describe the bug / 问题描述

昨天正常，今天刚刚发现出现问题，只有在使用账号或者cookie挂在蓝奏云的情况才会出现，报错信息是：
failed link: failed get link: not find file page param 标题2
我尝试了重新挂在，问题仍存在。
如果是使用分享链接挂在的，则正常。

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by foxxorcat** [comment]
改一下设置分享链接，改成 https://wwop.lanzoul.com ，或者去官网找，蓝奏云正常操作换域名

**Comment by luomo-pro** [comment]
问题已经解决，多谢！
