### ISSUE TITLE
概率BUG ./alist admin set 时机太快和alist初始化设置随机账密冲突？db还没准备好？能不能支持下容器参数直接指定admin账密？

### ISSUE THREAD

**Issue by gowy222** [alist-org/alist#5337]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.28.0

### Driver used / 使用的存储驱动

不涉及

### Describe the bug / 问题描述

INFO[2023-10-05 14:51:33] config file not exists, creating default config file 
INFO[2023-10-05 14:51:33] load config from env with prefix: ALIST_     
INFO[2023-10-05 14:51:33] init logrus...                               
INFO[2023-10-05 14:51:33] Successfully created the admin user and the initial password is: BqlLRFh0 
FATA[2023-10-05 14:51:33] failed save setting: UNIQUE constraint failed: x_setting_items.key
github.com/alist-org/alist/v3/internal/db.SaveSettingItem
	/app/internal/db/settingitem.go:63
github.com/alist-org/alist/v3/internal/op.SaveSettingItem
	/app/internal/op/setting.go:181
github.com/alist-org/alist/v3/internal/bootstrap/data.initSettings
	/app/internal/bootstrap/data/setting.go:48
github.com/alist-org/alist/v3/internal/bootstrap/data.InitData
	/app/internal/bootstrap/data/data.go:7
github.com/alist-org/alist/v3/cmd.Init
	/app/cmd/common.go:19
github.com/alist-org/alist/v3/cmd.setAdminPassword
	/app/cmd/admin.go:68
github.com/alist-org/alist/v3/cmd.glob..func3
	/app/cmd/admin.go:52
github.com/spf13/cobra.(*Command).execute
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/alist-org/alist/v3/cmd.Execute
	/app/cmd/root.go:20
main.main
	/app/main.go:6
runtime.main
	/usr/lib/go/src/runtime/proc.go:250
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1598

### Reproduction / 复现链接

容器启动 alist内部db没有初始化就绪，外部脚本已经接受到容器就绪信号开始执行 ./alist admin set ..

### Config / 配置

docker镜像 无配置

**Comment by xhofe** [comment]
不支持 请自行在脚本中添加延时操作。
