### ISSUE TITLE
3.28使用MySQL时，自启会报错，改回sqlite3正常启动

### ISSUE THREAD

**Issue by oe77** [alist-org/alist#5342]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.28

### Driver used / 使用的存储驱动

baidu

### Describe the bug / 问题描述

`[root@localhost ~]# systemctl status alist
● alist.service - Alist service
   Loaded: loaded (/etc/systemd/system/alist.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 六 2023-10-07 02:26:32 CST; 1min 11s ago
  Process: 1108 ExecStart=/www/wwwroot/alist.junkai.cc/alist/alist server (code=exited, status=1/FAILURE)
 Main PID: 1108 (code=exited, status=1/FAILURE)

10月 07 02:26:31 localhost.localdomain systemd[1]: Started Alist service.
10月 07 02:26:32 localhost.localdomain alist[1108]: INFO[2023-10-07 02:26:32] reading config file: data/config.json
10月 07 02:26:32 localhost.localdomain alist[1108]: INFO[2023-10-07 02:26:32] load config from env with prefix: ALIST_
10月 07 02:26:32 localhost.localdomain alist[1108]: INFO[2023-10-07 02:26:32] init logrus...
10月 07 02:26:32 localhost.localdomain systemd[1]: alist.service: main process exited, code=exited, status=1/FAILURE
10月 07 02:26:32 localhost.localdomain systemd[1]: Unit alist.service entered failed state.
10月 07 02:26:32 localhost.localdomain systemd[1]: alist.service failed.
`

### Reproduction / 复现链接

无

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "https://registry.npmmirror.com/alist-web/$version/files/dist/",
  "jwt_secret": "NN8YRzR4rrIr66U9",
  "token_expires_in": 48,
  "database": {
    "type": "mysql",
    "host": "127.0.0.1",
    "port": 3306,
    "user": "AList",
    "password": "GbNXAjXtFRkrYnXP",
    "name": "alist",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

**Comment by anwen-anyi** [comment]
试试用root用户名呢

**Comment by oe77** [comment]
> 试试用root用户名呢 我这里用的`MySQL`没有问题

systemctl start alist 手动启动正常，MySQL里面也有数据，但就是自启会出错，用新的服务器安装也是这种情况，3.27是正常的

**Comment by anwen-anyi** [comment]
> > 试试用root用户名呢 我这里用的`MySQL`没有问题
> 
> systemctl start alist 手动启动正常，MySQL里面也有数据，但就是自启会出错，用新的服务器安装也是这种情况，3.27是正常的

重启后自启动吗？ 这样的话你设置一下AList延时启动呢，可能是你AList在启动时候MySQL服务还未启动起来导致AList找不到

**Comment by oe77** [comment]
> > > 试试用root用户名呢 我这里用的`MySQL`没有问题
> > 
> > 
> > systemctl start alist 手动启动正常，MySQL里面也有数据，但就是自启会出错，用新的服务器安装也是这种情况，3.27是正常的
> 
> 重启后自启动吗？ 这样的话你设置一下AList延时启动呢，可能是你AList在启动时候MySQL服务还未启动起来导致AList找不到

ExecStartPre=/bin/sleep 30  延时了30秒，正常启动了
