### ISSUE TITLE
播放界面 播放列表显示不在底部，改在右侧

### ISSUE THREAD

**Issue by wensheng006** [alist-org/alist#5343]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

![image](https://github.com/alist-org/alist/assets/31528790/072fec74-0953-4116-8db2-0f80db1f2b22)

这几乎是所有播放器的显示形式， 播放列表在右侧， 最方便人选择

### Suggested solution / 实现思路

<img width="1611" alt="image" src="https://github.com/alist-org/alist/assets/31528790/dcaf8df9-f2d6-484b-92c1-dfc5d1f3e930">

**Comment by wensheng006** [comment]
下面的播放列表 不仔细看， 还以为没有呢，  我以前都是跳到前面列表页面再选择。。。。

**Comment by brokenman1** [comment]
特别需要，支持！有人开发吗，可以付费开发

**Comment by IAALAI** [comment]
确实重要，但是这个其实要实现应该是在 [alist-web](https://github.com/alist-org/alist-web) 实现
