### ISSUE TITLE
希望支持 Cloudreve 的缩略图

### ISSUE THREAD

**Issue by ty114514** [alist-org/alist#5348]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

rt

**Comment by ty114514** [comment]
瞅了一眼缩略图好像是 js 请求出去的, 不好爬, 不过请求的参数倒是很简单
?imageMogr2%2Fthumbnail%2F400x400=
但是非图片的文件我就没头绪了

**Comment by itsHenry35** [comment]
缩略图api: https://example.com/api/v3/file/thumb/{fileid(/directory api获得的)}
![image](https://github.com/alist-org/alist/assets/58730749/7a9d2c21-148f-48e8-8b59-43a306014a26)
![image](https://github.com/alist-org/alist/assets/58730749/ecf8d6ad-7e8c-4bc8-b0ca-5d3a990d1ae2)
![image](https://github.com/alist-org/alist/assets/58730749/5446d22e-6f67-40fa-bc04-13fe5cca3c6f)

如果没有缩略图，就回return一个空200okresponse，有缩略图就是301
