### ISSUE TITLE
[权限错误]不用登录直接可以下载文件

### ISSUE THREAD

**Issue by power721** [alist-org/alist#5349]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

任意

### Describe the bug / 问题描述

不需要登录和认证token，通过链接直接下载文件。
部署在公网的AList，查看日志发现大量的下载请求。虽然访问的资源不存在，但是返回了200.
使用存在的资源路径，可以直接下载文件。

### Reproduction / 复现链接

/d/纪录片/豆瓣9.7纪录片《宇宙：时空之旅》完整全集 中英字幕/第一集：宇宙起源更多资源-XH1080.com.mkv
/p/纪录片/豆瓣9.7纪录片《宇宙：时空之旅》完整全集 中英字幕/第一集：宇宙起源更多资源-XH1080.com.mkv

### Config / 配置

默认

### Logs / 日志

[GIN] 2023/10/08 - 20:04:23 | 200 |     352.013µs |  102.36.231.114 | GET      "/d/纪录片/豆瓣9.7纪录片《宇宙：时空之旅》完整全集 中英字幕/第一集：宇宙起源更多资源-XH1080.com.mkv?sign=E6ku-aQh6bDmDumhIH6bFlAI0-dU8TpEcAdA7u6-5iE=:0"
[GIN] 2023/10/08 - 20:04:24 | 200 |     111.982µs |  102.36.231.114 | GET      "/d/纪录片/豆瓣9.7纪录片《宇宙：时空之旅》完整全集 中英字幕/第一集：宇宙起源更多资源-XH1080.com.mkv?sign=E6ku-aQh6bDmDumhIH6bFlAI0-dU8TpEcAdA7u6-5iE=:0"
[GIN] 2023/10/08 - 20:04:24 | 200 |     131.754µs |  102.36.231.114 | GET      "/d/纪录片/豆瓣9.7纪录片《宇宙：时空之旅》完整全集 中英字幕/第一集：宇宙起源更多资源-XH1080.com.mkv?sign=E6ku-aQh6bDmDumhIH6bFlAI0-dU8TpEcAdA7u6-5iE=:0"
[GIN] 2023/10/08 - 20:04:24 | 200 |     122.883µs |  102.36.231.114 | GET      "/d/纪录片/豆瓣9.7纪录片《宇宙：时空之旅》完整全集 中英字幕/第一集：宇宙起源更多资源-XH1080.com.mkv?sign=E6ku-aQh6bDmDumhIH6bFlAI0-dU8TpEcAdA7u6-5iE=:0"
[GIN] 2023/10/08 - 20:04:24 | 200 |     101.303µs |  102.36.231.114 | GET      "/d/纪录片/豆瓣9.7纪录片《宇宙：时空之旅》完整全集 中英字幕/第一集：宇宙起源更多资源-XH1080.com.mkv?sign=E6ku-aQh6bDmDumhIH6bFlAI0-dU8TpEcAdA7u6-5iE=:0"
[GIN] 2023/10/08 - 20:04:39 | 200 |     130.793µs |  102.36.231.114 | GET      "/d/纪录片/豆瓣9.7纪录片《宇宙：时空之旅》完整全集 中英字幕/第一集：宇宙起源更多资源-XH1080.com.mkv?sign=E6ku-aQh6bDmDumhIH6bFlAI0-dU8TpEcAdA7u6-5iE=:0"
[GIN] 2023/10/08 - 20:04:41 | 200 |     111.381µs |  102.36.231.114 | GET      "/d/纪录片/豆瓣9.7纪录片《宇宙：时空之旅》完整全集 中英字幕/第一集：宇宙起源更多资源-XH1080.com.mkv?sign=E6ku-aQh6bDmDumhIH6bFlAI0-dU8TpEcAdA7u6-5iE=:0"

**Comment by xhofe** [comment]
https://alist.nn.ci/config/global.html#customize-body
