### ISSUE TITLE
联通云盘-fatal error: concurrent map writes

### ISSUE THREAD

**Issue by seanlees** [alist-org/alist#5352]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

WoPan

### Describe the bug / 问题描述

1、使用docker版本
2、使用联通云盘驱动WoPan按照官网文档进行配置

联通云盘挂在正常，开启上传同步本地到云盘，几分钟后就会Crash docker崩溃重启

### Reproduction / 复现链接

无

### Config / 配置

![image](https://github.com/alist-org/alist/assets/2920470/b54ada34-0270-45ba-8a63-dc9bb7f83a91)

### Logs / 日志

INFO[2023-10-09 20:38:07] success load storage: [/unicomdrive], driver: [WoPan] 
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 269 [running]:
github.com/Xhofe/wopan-sdk-go.(*WoClient).NewBody(0x1bfe02f?, {0x1bf1f78?, 0x18b1471f39f?}, 0x188d8?, 0x1bf1f78?)
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/req_body.go:26 +0x5f
github.com/Xhofe/wopan-sdk-go.(*WoClient).request(0xc00016a600, {0x1bf1f78, 0x8}, {0x1bfe02f, 0xf}, 0x414387?, 0x10?, {0x1861600, 0xc000b85720}, 0x1, ...)
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/request.go:19 +0x565
github.com/Xhofe/wopan-sdk-go.(*WoClient).Request(...)
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/request.go:68
github.com/Xhofe/wopan-sdk-go.(*WoClient).RequestApiUser(0xc?, {0x1bfe02f?, 0xc00170c7d8?}, 0x51de1c?, 0x0?, {0x1861600?, 0xc000b85720?}, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/request.go:72 +0x77
github.com/Xhofe/wopan-sdk-go.(*WoClient).AppRefreshToken(0xc00016a600, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/api-user.go:80 +0x159
github.com/Xhofe/wopan-sdk-go.(*WoClient).RefreshToken(0xc00016a600)
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/operation.go:39 +0x29
github.com/Xhofe/wopan-sdk-go.(*WoClient).request(0xc00016a600, {0x1beea13, 0x6}, {0x1c0b116, 0x15}, 0x414387?, 0x10?, {0x0, 0x0}, 0x1, ...)
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/request.go:43 +0x9ff
github.com/Xhofe/wopan-sdk-go.(*WoClient).Request(...)
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/request.go:68
github.com/Xhofe/wopan-sdk-go.(*WoClient).RequestWoHome(0x8?, {0x1c0b116?, 0x4d83af?}, 0x36?, 0x1a?, {0x0?, 0x0?}, {0xc00072ed40, 0x1, 0x1})
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/request.go:76 +0x77
github.com/Xhofe/wopan-sdk-go.(*WoClient).RenameFileOrDirectory(0x4134ed?, {0x26ac300, 0x1}, 0x1, {0xc001bef7e0, 0x20}, {0xc000449c80, 0x2b}, {0x0, 0x0}, ...)
	/root/go/pkg/mod/github.com/!xhofe/wopan-sdk-go@v0.1.1/api-fs.go:130 +0x3a5
github.com/alist-org/alist/v3/drivers/wopan.(*Wopan).Rename(0xc0007f8b00, {0x26c9b40, 0xc0007e0870}, {0x26d2e60, 0xc00085df40}, {0xc000449c80, 0x2b})
	/app/drivers/wopan/driver.go:121 +0x17f
github.com/alist-org/alist/v3/internal/op.Rename({0x26c9b40, 0xc0007e0870}, {0x26d2eb8, 0xc0007f8b00?}, {0xc000b9e700, 0x36}, {0xc000449c80, 0x2b}, {0x0, 0x0, ...})
	/app/internal/op/fs.go:415 +0x47a
github.com/alist-org/alist/v3/internal/op.Put({0x26c9b40, 0xc0007e0870}, {0x26d2eb8, 0xc0007f8b00}, {0xc0016dcc8c, 0x1a}, {0x26e2ed8?, 0xc000733780?}, 0x0, {0x0, ...})
	/app/internal/op/fs.go:518 +0x516
github.com/alist-org/alist/v3/internal/fs.putDirectly({0x26c9b40, 0xc0007e0870}, {0xc0016dcc80?, 0x1bf574a?}, {0x26e2ed8, 0xc000733780}, {0x0, 0x0, 0x0})
	/app/internal/fs/put.go:54 +0x27d
github.com/alist-org/alist/v3/internal/fs.PutDirectly({0x26c9b40?, 0xc0007e0870?}, {0xc0016dcc80, 0x26}, {0x26e2ed8?, 0xc000733780?}, {0x0?, 0xc00167f460?, 0xc00072f340?})
	/app/internal/fs/fs.go:96 +0x55
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePut(0xc0008b61b0, {0x26c5be0, 0xc0007e08a0}, 0xc000b34900)
	/app/server/webdav/webdav.go:341 +0x675
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP(0xc0008b61b0, {0x7f301b4df338, 0xc00071a400}, 0xc000b34900)
	/app/server/webdav/webdav.go:65 +0xd0
github.com/alist-org/alist/v3/server.ServeWebDAV(0xc00071a400)
	/app/server/webdav.go:46 +0x185
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth(0xc00071a400)
	/app/server/webdav.go:113 +0x950
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded(0xc00071a400)
	/app/server/middlewares/check.go:14 +0xae
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc00071a400)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 +0x82
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc00071a400)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 +0xe7
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00085e9c0, 0xc00071a400)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x66b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00085e9c0, {0x26c8490?, 0xc000170000}, 0xc0004dfe00)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
net/http.serverHandler.ServeHTTP({0x26c3af8?}, {0x26c8490, 0xc000170000}, 0xc0004dfe00)
	/usr/lib/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0008dfa70, {0x26c9b40, 0xc0008d0f30})
	/usr/lib/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:3089 +0x5ed

goroutine 1 [chan receive]:
github.com/alist-org/alist/v3/cmd.glob..func8(0x3374bc0?, {0x1be4e17?, 0x1?, 0x1?})
	/app/cmd/server.go:101 +0x75e
github.com/spf13/cobra.(*Command).execute(0x3374bc0, {0xc000229d80, 0x1, 0x1})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x33748e0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/alist-org/alist/v3/cmd.Execute()
	/app/cmd/root.go:20 +0x25
main.main()
	/app/main.go:6 +0x17

goroutine 19 [select]:
github.com/Xhofe/go-cache.NewMemCache[...].func1()
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:115 +0xf9
created by github.com/Xhofe/go-cache.NewMemCache[...]
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:108 +0x29a

goroutine 20 [select]:
github.com/Xhofe/go-cache.NewMemCache[...].func1()
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:115 +0xf9
created by github.com/Xhofe/go-cache.NewMemCache[...]
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:108 +0x29a

goroutine 21 [select]:
github.com/Xhofe/go-cache.NewMemCache[...].func1()
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:115 +0xf9
created by github.com/Xhofe/go-cache.NewMemCache[...]
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:108 +0x29a

goroutine 22 [select]:
github.com/Xhofe/go-cache.NewMemCache[...].func1()
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:115 +0xf9
created by github.com/Xhofe/go-cache.NewMemCache[...]
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:108 +0x29a

goroutine 23 [select]:
github.com/Xhofe/go-cache.NewMemCache[...].func1()
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:115 +0xf9
created by github.com/Xhofe/go-cache.NewMemCache[...]
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:108 +0x29a

goroutine 24 [select]:
github.com/Xhofe/go-cache.NewMemCache[...].func1()
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:115 +0xf9
created by github.com/Xhofe/go-cache.NewMemCache[...]
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:108 +0x29a

goroutine 25 [select]:
github.com/Xhofe/go-cache.NewMemCache[...].func1()
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:115 +0xf9
created by github.com/Xhofe/go-cache.NewMemCache[...]
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:108 +0x29a

goroutine 27 [select]:
github.com/blevesearch/bleve_index_api.AnalysisWorker({0xc0004ee000?, 0xc0004ee060?})
	/root/go/pkg/mod/github.com/blevesearch/bleve_index_api@v1.0.6/analysis.go:46 +0x8f
created by github.com/blevesearch/bleve_index_api.NewAnalysisQueue
	/root/go/pkg/mod/github.com/blevesearch/bleve_index_api@v1.0.6/analysis.go:38 +0x92

goroutine 28 [select]:
github.com/blevesearch/bleve_index_api.AnalysisWorker({0xc0004ee000?, 0xc0004ee060?})
	/root/go/pkg/mod/github.com/blevesearch/bleve_index_api@v1.0.6/analysis.go:46 +0x8f
created by github.com/blevesearch/bleve_index_api.NewAnalysisQueue
	/root/go/pkg/mod/github.com/blevesearch/bleve_index_api@v1.0.6/analysis.go:38 +0x92

goroutine 29 [select]:
github.com/blevesearch/bleve_index_api.AnalysisWorker({0xc0004ee000?, 0xc0004ee060?})
	/root/go/pkg/mod/github.com/blevesearch/bleve_index_api@v1.0.6/analysis.go:46 +0x8f
created by github.com/blevesearch/bleve_index_api.NewAnalysisQueue
	/root/go/pkg/mod/github.com/blevesearch/bleve_index_api@v1.0.6/analysis.go:38 +0x92

goroutine 30 [select]:
github.com/blevesearch/bleve_index_api.AnalysisWorker({0xc0004ee000?, 0xc0004ee060?})
	/root/go/pkg/mod/github.com/blevesearch/bleve_index_api@v1.0.6/analysis.go:46 +0x8f
created by github.com/blevesearch/bleve_index_api.NewAnalysisQueue
	/root/go/pkg/mod/github.com/blevesearch/bleve_index_api@v1.0.6/analysis.go:38 +0x92

goroutine 33 [select]:
github.com/Xhofe/go-cache.NewMemCache[...].func1()
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:115 +0xf9
created by github.com/Xhofe/go-cache.NewMemCache[...]
	/root/go/pkg/mod/github.com/!xhofe/go-cache@v0.0.0-20220723083548-714439c8af9a/cache.go:108 +0x29a

goroutine 34 [select]:
database/sql.(*DB).connectionOpener(0xc0007f04e0, {0x26c9a98, 0xc000094f50})
	/usr/lib/go/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/usr/lib/go/src/database/sql/sql.go:791 +0x18d

goroutine 35 [chan receive]:
github.com/natefinch/lumberjack.(*Logger).millRun(0xc0007ea1e0)
	/root/go/pkg/mod/github.com/natefinch/lumberjack@v2.0.0+incompatible/lumberjack.go:379 +0x45
created by github.com/natefinch/lumberjack.(*Logger).mill.func1
	/root/go/pkg/mod/github.com/natefinch/lumberjack@v2.0.0+incompatible/lumberjack.go:390 +0x96

goroutine 98 [IO wait]:
internal/poll.runtime_pollWait(0x7f301b5e6308, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0008dac80?, 0xc000c5a000?, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0008dac80, {0xc000c5a000, 0x1300, 0x1300})
	/usr/lib/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc0008dac80, {0xc000c5a000?, 0xc000c5a00d?, 0x29b?})
	/usr/lib/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000014590, {0xc000c5a000?, 0x12f3?, 0xc000c5a005?})
	/usr/lib/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00098c6a8, {0xc000c5a000?, 0xc00098c6a8?, 0x0?})
	/usr/lib/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc0003a6610, {0x26b5960, 0xc00098c6a8})
	/usr/lib/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0003a6380, {0x26b9200?, 0xc000014590}, 0x45aa38?)
	/usr/lib/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0003a6380, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc0003a6380, {0xc000c67000, 0x1000, 0x7235c0?})
	/usr/lib/go/src/crypto/tls/conn.go:1316 +0x16f
bufio.(*Reader).Read(0xc000b99140, {0xc000b7a3c0, 0x9, 0x741245?})
	/usr/lib/go/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x26b56e0, 0xc000b99140}, {0xc000b7a3c0, 0x9, 0x9}, 0x9)
	/usr/lib/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/lib/go/src/io/io.go:351
net/http.http2readFrameHeader({0xc000b7a3c0?, 0x9?, 0xc000701a40?}, {0x26b56e0?, 0xc000b99140?})
	/usr/lib/go/src/net/http/h2_bundle.go:1567 +0x6e
net/http.(*http2Framer).ReadFrame(0xc000b7a380)
	/usr/lib/go/src/net/http/h2_bundle.go:1831 +0x95
net/http.(*http2clientConnReadLoop).run(0xc000c52f98)
	/usr/lib/go/src/net/http/h2_bundle.go:9187 +0x12e
net/http.(*http2ClientConn).readLoop(0xc0007eef00)
	/usr/lib/go/src/net/http/h2_bundle.go:9082 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/lib/go/src/net/http/h2_bundle.go:7779 +0xc3c

**Comment by RyanQwQ** [comment]
`[31mERRO[0m[2023-10-09 22:10:26] failed list /wo: request failed with rsp_code: 8005,rep_desc: 登录失败！
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/home/runner/work/alist/alist/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/home/runner/work/alist/alist/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	/home/runner/work/alist/alist/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/home/runner/work/alist/alist/internal/fs/fs.go:21
github.com/alist-org/alist/v3/server/handles.FsList
	/home/runner/work/alist/alist/server/handles/fsread.go:85
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/runner/work/alist/alist/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/server.go:2936
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/server.go:1995
runtime.goexit
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/asm_amd64.s:1598
failed get objs `
