### ISSUE TITLE
希望添加网易云音乐云盘的支持

### ISSUE THREAD

**Issue by lveMonsi** [alist-org/alist#5364]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

恳请增加对网易云音乐云盘支持
免费空间60G 无限速,不吞文件 只支持音频文件
有第三方api https://neteasecloudmusicapi.vercel.app/#/?id=%e4%ba%91%e7%9b%98

**Comment by AtWhuhu** [comment]
转存音频文件至其余网盘后希望可以直接复制到网易云音乐云盘

**Comment by IAALAI** [comment]
我个人感觉意义不大。你是不是还没有被网易云偷偷删掉过文件？
