### ISSUE TITLE
alist的webdav功能是否不支持流式传输？

### ISSUE THREAD

**Issue by goldsoft8888** [alist-org/alist#5369]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist的webdav功能是否不支持流式传输？
我用rclone 挂载alist的webdav，会提示如下：
2023/10/12 06:18:34 NOTICE: webdav root '网盘': --vfs-cache-mode writes or full is recommended for this remote as it can't stream

--vfs-cache-mode writes 加入这个参数是正常的，但会占用大量的CPU、内存、磁盘，所以我想采用流式传输，但我不确定这是rclone的问题，还是alist的问题。 alist 挂载云盘的流式上传非常棒，我想让rclone也实现类似的功能，不在磁盘上缓存。

**Comment by goldsoft8888** [comment]
如果可以不用rclone，只用alist实现映射smb或本地文件夹，会更好，愿意为此捐赠

**Comment by xhofe** [comment]
rclone没有为webdav 实现stream，对于fuse：与#1747 重复。

**Comment by goldsoft8888** [comment]
> rclone没有为webdav实现stream，对于fuse：与#1747重复。
谢谢您的解答


> 建议用隔壁的cd2 https://www.clouddrive2.com/
谢谢，我测试了，它不是我需要

**Comment by CCCAUCHY** [comment]
> rclone没有为webdav 实现stream，对于fuse：与#1747 重复。

同样的问题, 视频文件必须完全下载才能打开, Windows 10的webdav是否实现了stream?

**Comment by acvlwe** [comment]
将webdav配置的vendor改成owncloud 同时加上flag --vfs-cache-mode=writes
参考https://forum.rclone.org/t/support-putstream-for-webdav-servers-with-partial-update-support/27247

**Comment by goldsoft8888** [comment]
> 将webdav配置的vendor改成owncloud 同时加上flag --vfs-cache-mode=writes 参考 https://forum.rclone.org/t/support-putstream-for-webdav-servers-with-partial-update-support/27247

修改alist 是否能实现？

**Comment by acvlwe** [comment]
> > 将webdav配置的vendor改成owncloud 同时加上flag --vfs-cache-mode=writes 参考 https://forum.rclone.org/t/support-putstream-for-webdav-servers-with-partial-update-support/27247
> 
> 修改alist 是否能实现？我不喜欢再挂载rclone, 希望只用alist一个软件可以实现。

alist没有提供挂载功能，webdav是否支持流式传输取决于服务端和客户端的实现和协商问题
