### ISSUE TITLE
用户密码错误过多影响其他用户

### ISSUE THREAD

**Issue by cgwxq** [alist-org/alist#5371]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

.

### Describe the bug / 问题描述

非管理员账户密码错误超过6次，导致管理员密码正确的情况下无法进入。但是通过重启可恢复，是否对错误密码的情况下不影响其他用户。

### Reproduction / 复现链接

登录页面

### Config / 配置

无

**Comment by anwen-anyi** [comment]
可以重启解决，或者等待30分钟

**Comment by xhofe** [comment]
这只是针对ip封禁 正常不同用户ip不会相同所以不会影响。

**Comment by yigedabuliu** [comment]
v3.40.0 在手机移动网络上用户密码错误过多影响，电脑上不同ip的用户登录

**Comment by yigedabuliu** [comment]
> v3.40.0 在手机移动网络上用户密码错误过多影响，电脑上不同ip的用户登录

emmm，破案了，我是用frp进行内网穿透所以每个用户访问的都是127.0.0.1
