### ISSUE TITLE
反代后百度网盘分享视频，前端关闭后，服务端还在继续下载或者上传

### ISSUE THREAD

**Issue by JJTools** [alist-org/alist#5372]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28

### Driver used / 使用的存储驱动

百度分享

### Describe the bug / 问题描述

反代后百度网盘分享视频，前端关闭后，服务端还在继续下载或者上传
如果不使用反代。修改端口80/433 直接接入。CF套上CDN依旧可以复现

### Reproduction / 复现链接

反代后百度网盘分享视频，前端关闭后，服务端还在继续下载或者上传

### Config / 配置

![图片](https://github.com/alist-org/alist/assets/125969063/7b8e343b-2c72-44c3-be74-78e9e833041f)
![image](https://github.com/alist-org/alist/assets/125969063/28b8dad5-1a03-4e18-a7ff-19636febd847)

**Comment by DFDzaidu** [comment]
借楼，群晖nas中部署的宝塔环境，安装后无法启动
![image](https://github.com/alist-org/alist/assets/92215296/dab26e50-2831-4f48-84a7-3d3b7a4a9f94)
