### ISSUE TITLE
能否实现无人值守时，令牌失效，授权码失效，网盘异常等通知功能？

### ISSUE THREAD

**Issue by goldsoft8888** [alist-org/alist#5376]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否实现无人值守时，令牌失效，授权码失效，网盘异常等通知功能？
邮件或短信通知，因为我把alist装在路由器里，不能随时观察工作状态，需要自动触发一些机制，比如重新获取授权码

**Comment by IAALAI** [comment]
确实，用api自己写吧
