### ISSUE TITLE
能否把网盘以文件夹的方式挂载

### ISSUE THREAD

**Issue by webnet918** [alist-org/alist#5380]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

网盘挂载的多了显得很乱，能否按自己的需求创建虚拟盘，然后把网盘以文件夹的形式挂载到这个虚拟盘里？如果能根据自己的需要随意创建和挂载就更好了。

**Comment by webnet918** [comment]
> https://ad.nn.ci/ https://www.clouddrive2.com/

谢谢提供的链接，我已经买过AList了

**Comment by xhofe** [comment]
你是否指的是 https://alist.nn.ci/zh/guide/drivers/common.html#%E6%8C%82%E8%BD%BD%E8%B7%AF%E5%BE%84
这个配置项是可以任意填的，可以包含 `/`，比如 `/a/b`。

**Comment by webnet918** [comment]
> 你是否指的是 https://alist.nn.ci/zh/guide/drivers/common.html#%E6%8C%82%E8%BD%BD%E8%B7%AF%E5%BE%84 这个配置项是可以任意填的，可以包含 `/`，比如 `/a/b`。

谢谢提醒！用这样的办法的确可以。不过，我试了一下嵌套挂载效果不太理想，比如：我在C盘创建了一个目录A，并将其挂载为D盘，然后，我把网盘挂载到这个目录A里时，在D盘里只能看到一个不能识别的图标，打不开。而且系统会变得非常卡。如果把网盘直接挂载到已经挂载的D盘时，挂载不成功。目前把网盘挂载到目录里还是可以的。

**Comment by anwen-anyi** [comment]
有个比较绕的办法，就是先把整个网盘进行挂载，然后使用`别名`将需要挂载的单独列出来
然后将根目录进行隐藏以及加密，同时在后台进行隐藏
![image](https://github.com/alist-org/alist/assets/56105412/1f735bbf-3ff2-41ee-b00f-2a343bc0a138)
![image](https://github.com/alist-org/alist/assets/56105412/b5f9c9d0-4c8b-4bc6-b5ae-5f4f10ea0cb9)

**Comment by webnet918** [comment]
> 有个比较绕的办法，就是先把整个网盘进行挂载，然后使用`别名`将需要挂载的单独列出来 然后将根目录进行隐藏以及加密，同时在后台进行隐藏 ![image](https://user-images.githubusercontent.com/56105412/275314825-1f735bbf-3ff2-41ee-b00f-2a343bc0a138.png) ![image](https://user-images.githubusercontent.com/56105412/275314876-b5f9c9d0-4c8b-4bc6-b5ae-5f4f10ea0cb9.png) 正常这个两个文件夹也是要在根目录显示的，上面隐藏了 我用别名把它们汇聚在一个文件夹里面了。

谢谢！但是没有完全理解，我用了另外一个方法。第一步先用subst虚拟出来一个虚拟磁盘，然后在aList里把网盘挂载到源路径的文件夹里。界面看着整洁多了
