### ISSUE TITLE
一键复制文件直链

### ISSUE THREAD

**Issue by onexiaolaji** [alist-org/alist#5383]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望新增一键复制文件直链，像teambition视频图片等直链可以用来做外链，且不会失效。

**Comment by xhofe** [comment]
对于这种，你可以右键下载按钮-复制链接，否则我们一般推荐使用AList的直链，它对所有的存储都是不会失效的。
