### ISSUE TITLE
115直接挂载分享链接

### ISSUE THREAD

**Issue by ChenyangGao** [alist-org/alist#5384]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我使用115浏览器的过程中发现，115浏览器可以直接打开一个分享链接，不经过转存，就可以下载。
这说明，理论上，115的分享链接是可以直接挂载的，因此我希望能增加这个功能。

### Suggested solution / 实现思路

下面是有关的技术实现：
alist 的 115 driver 是 [115driver](https://github.com/SheltonZhu/115driver)，115driver 对下载链接的加解密用的是 [fake115uploader](https://github.com/orzogc/fake115uploader/blob/master/cipher/cipher.go)。
对于自己网盘的文件，是通过 POST 请求 https://proapi.115.com/app/chrome/downurl ，并且附带请求参数（需要 url-encoded）
```
{"data": RSA加密({"pickcode": pick_code})}
```
并对返回的结果解密即可

同样的，对于分享链接中的文件，也用同样的RSA加密，通过 POST 请求 https://proapi.115.com/app/share/downurl ，并且附带请求参数（需要 url-encoded）
```
{"data": RSA加密({"share_code": share_code, "receive_code": receive_code, "file_id": file_id})}
```
并对返回的结果解密即可

例如，有个分享链接 https://115.com/s/sw60op83nuc?password=y909#
那么就有
```
share_code = "sw60op83nuc"
receive_code = "y909"
```
而另一个参数 file_id ，可罗列分享文件中的文件信息获得
```
# GET 请求
api = "https://webapi.115.com/share/snap"
params = {
    "share_code": "sw6cvxb3w8m", 
    "receive_code": "ed69", 
    "offset": 0, 
    "limit": 100, 
    "cid": 0, 
}
```

**Comment by wowdd1** [comment]
https://github.com/ChenyangGao/web-mount-packs
这个有实现115分享链接挂载 可以参考

**Comment by ChenyangGao** [comment]
> 参考

这就是我写的

**Comment by wowdd1** [comment]
> https://github.com/ChenyangGao/web-mount-packs**★ 10****★ 10**

原来就是你写的啊  

你那个wsgidav实现的webdav是不是有些问题   只能在web浏览器看  其他软件都挂载不了   能否做成像alist wedav这样可以被其他软件挂载呀？？

**Comment by ChenyangGao** [comment]
> > [https://github.com/ChenyangGao/web-mount-packs**★](https://github.com/ChenyangGao/web-mount-packs**%E2%98%85) 10****★ 10**
> 
> 原来就是你写的啊
> 
> 你那个wsgidav实现的webdav是不是有些问题 只能在web浏览器看 其他软件都挂载不了 能否做成像alist wedav这样可以被其他软件挂载呀？？

可以挂，后面不要加/dav，http://localhost:8080，浏览器什么地址，挂载也是这地址，没有用户名和密码，如果要加密码保护，有个配置文件wsgidav.yaml，在工作目录下

**Comment by wowdd1** [comment]
> > > [https://github.com/ChenyangGao/web-mount-packs**★**★ NaNundefined****★ NaNundefined**](https://github.com/ChenyangGao/web-mount-packs**%E2%98%85) 10****★ 10**
> > 
> > 
> > 原来就是你写的啊
> > 你那个wsgidav实现的webdav是不是有些问题 只能在web浏览器看 其他软件都挂载不了 能否做成像alist wedav这样可以被其他软件挂载呀？？
> 
> 可以挂，后面不要加/dav，浏览器什么地址，挂载也是这地址 http://localhost:8080 没有用户名和密码，如果要加密码保护，有个配置文件wsgidav.yaml，在工作目录下 <img alt="截屏2023-10-19 11 46 11" width="1024" src="https://user-images.githubusercontent.com/26198875/276476054-6f161da8-87dc-4dce-aa95-da5590ee2c47.png"> <img alt="截屏2023-10-19 11 49 21" width="1005" src="https://user-images.githubusercontent.com/26198875/276477017-61a1efcd-4be0-48d1-9ff6-df2cf33a458c.png">

你的alist 咋能挂115 分享链接？？

**Comment by ChenyangGao** [comment]
> > > > [https://github.com/ChenyangGao/web-mount-packs**★**★ NaNundefined****★ NaNundefined**](https://github.com/ChenyangGao/web-mount-packs**%E2%98%85) 10****★ 10**
> > > 
> > > 
> > > 原来就是你写的啊
> > > 你那个wsgidav实现的webdav是不是有些问题 只能在web浏览器看 其他软件都挂载不了 能否做成像alist wedav这样可以被其他软件挂载呀？？
> > 
> > 可以挂，后面不要加/dav，浏览器什么地址，挂载也是这地址 http://localhost:8080 没有用户名和密码，如果要加密码保护，有个配置文件wsgidav.yaml，在工作目录下 <img alt="截屏2023-10-19 11 46 11" width="1024" src="https://user-images.githubusercontent.com/26198875/276476054-6f161da8-87dc-4dce-aa95-da5590ee2c47.png"> <img alt="截屏2023-10-19 11 49 21" width="1005" src="https://user-images.githubusercontent.com/26198875/276477017-61a1efcd-4be0-48d1-9ff6-df2cf33a458c.png">
> 
> 你的alist 咋能挂115 分享链接？？

运行我那个程序，就可以有一个webdav，再用alist挂这个webdav即可

**Comment by wowdd1** [comment]
已经挂载成功 感谢

**Comment by SheltonZhu** [comment]
> > 参考
> 
> 这就是我写的项目😄，我提issue，我另起炉灶，不喜欢go语言，不知道能不能在rust语言层面合作，我可以贡献rust代码

意思是说，点击下载的时候，先创建一个分享？然后通过分享链接下载？这样就可以不经过代理了是吧？

有几个问题可能要考虑下：
1. 分享链接对大文件是否有限制
2. 创建的分享链接一直有效的话是否安全， 下载完成后如何撤回分享

这个功能会考虑加到sdk中，但是是否能集成到 alist，还有待商榷

**Comment by xhofe** [comment]
> > > 参考
> > 
> > 
> > 这就是我写的项目😄，我提issue，我另起炉灶，不喜欢go语言，不知道能不能在rust语言层面合作，我可以贡献rust代码
> 
> 意思是说，点击下载的时候，先创建一个分享？然后通过分享链接下载？这样就可以不经过代理了是吧？
> 
> 有几个问题可能要考虑下：
> 
> 1. 分享链接对大文件是否有限制
> 2. 创建的分享链接一直有效的话是否安全， 下载完成后如何撤回分享
> 
> 这个功能会考虑加到sdk中，但是是否能集成到 alist，还有待商榷

看起来应该是直接获取分享链接的文件的直链，而不需要转存到自己的账号中。

**Comment by SheltonZhu** [comment]
> > > > 参考
> > > 
> > > 
> > > 这就是我写的项目😄，我提issue，我另起炉灶，不喜欢go语言，不知道能不能在rust语言层面合作，我可以贡献rust代码
> > 
> > 
> > 意思是说，点击下载的时候，先创建一个分享？然后通过分享链接下载？这样就可以不经过代理了是吧？
> > 有几个问题可能要考虑下：
> > 
> > 1. 分享链接对大文件是否有限制
> > 2. 创建的分享链接一直有效的话是否安全， 下载完成后如何撤回分享
> > 
> > 这个功能会考虑加到sdk中，但是是否能集成到 alist，还有待商榷
> 
> 看起来应该是直接获取分享链接的文件的直链，而不需要转存到自己的账号中。

{"data": RSA加密({"share_code": share_code, "receive_code": receive_code, "file_id": file_id})}

通过分享码，提取码和文件id这个测试通过了， 但是还有个问题， 怎么获取，分享码，提取码。。。

**Comment by SheltonZhu** [comment]
> > > > 参考
> > > 
> > > 
> > > 这就是我写的项目😄，我提issue，我另起炉灶，不喜欢go语言，不知道能不能在rust语言层面合作，我可以贡献rust代码
> > 
> > 
> > 意思是说，点击下载的时候，先创建一个分享？然后通过分享链接下载？这样就可以不经过代理了是吧？
> > 有几个问题可能要考虑下：
> > 
> > 1. 分享链接对大文件是否有限制
> > 2. 创建的分享链接一直有效的话是否安全， 下载完成后如何撤回分享
> > 
> > 这个功能会考虑加到sdk中，但是是否能集成到 alist，还有待商榷
> 
> 看起来应该是直接获取分享链接的文件的直链，而不需要转存到自己的账号中。

这两个api的功能已经实现， 但是alist中如何获取分享码和访问码？
https://webapi.115.com/share/snap
https://proapi.115.com/app/share/downurl

**Comment by SheltonZhu** [comment]
难道说的是把根目录直接分享出去，然后配置分享码和访问码来挂载文件， 达成直链下载？

**Comment by kddy918** [comment]
> > 参考
> 
> 这是我写的项目😄，我提问题，我又起炉灶，不喜欢go语言，不知道能不能在rust语言方面合作，我可以贡献rust代码

可否增加对https://share.115.com/链接的支持？

**Comment by SheltonZhu** [comment]
> > > 参考
> > 
> > 
> > 这是我写的项目😄，我提问题，我又起炉灶，不喜欢go语言，不知道能不能在rust语言方面合作，我可以贡献rust代码
> 
> 可否增加对[https://share.115.com/链接的支持？](https://share.115.com/%E9%93%BE%E6%8E%A5%E7%9A%84%E6%94%AF%E6%8C%81%EF%BC%9F)
发个真实的例子我看看原理是不是一样的

**Comment by kddy918** [comment]
> > > > 参考
> > > 
> > > 
> > > 这是我写的项目😄，我提问题，我又起炉灶，不喜欢go语言，不知道能不能在rust语言方面合作，我可以贡献rust代码
> > 
> > 
> > 可否增加对[https://share.115.com/链接的支持？](https://share.115.com/%E9%93%BE%E6%8E%A5%E7%9A%84%E6%94%AF%E6%8C%81%EF%BC%9F)
> > 发个真实的例子我看看原理是不是一样的

https://share.115.com/sw68b0u3hhq?password=gd41#
提示：WARNING : '/原盘 ISO 电影666.3TB' :: the corresponding link is not available

**Comment by kddy918** [comment]
网页可以读出cid=2596442822729660057

**Comment by SheltonZhu** [comment]
> > > > > 参考
> > > > 
> > > > 
> > > > 这是我写的项目😄，我提问题，我又起炉灶，不喜欢go语言，不知道能不能在rust语言方面合作，我可以贡献rust代码
> > > 
> > > 
> > > 可否增加对[https://share.115.com/链接的支持？](https://share.115.com/%E9%93%BE%E6%8E%A5%E7%9A%84%E6%94%AF%E6%8C%81%EF%BC%9F)
> > > 发个真实的例子我看看原理是不是一样的
> 
> https://share.115.com/sw68b0u3hhq?password=gd41# 提示：WARNING : '/原盘 ISO 电影666.3TB' :: the corresponding link is not available
> 
> 网页可以读出文件cid=2596442822729660057

试过了可以挂载

https://115.com/s/sw68b0u3hhq?password=gd41#
和
https://share.115.com/sw68b0u3hhq?password=gd41#
没有区别
