### ISSUE TITLE
Download File on Local Storage by Mobile

### ISSUE THREAD

**Issue by zonprox** [alist-org/alist#5385]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

When I download an Apk file on mobile (iOS, Android) .zip is automatically added after the .apk file. This error does not occur if the apk file is downloaded on the computer. This error also only occurs in Local drive. No proxy involved.

### Reproduction / 复现链接

Download .Apk file on Local storage by mobile phone.

### Config / 配置

config.json
```
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "S31bllGG1xEfgvVd",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}
```
Storage Config:
![image](https://github.com/alist-org/alist/assets/18046425/2e23dac7-23f0-43da-85f5-33c6f4e37efe)

**Comment by xhofe** [comment]
This is system/browser behavior and has nothing to do with AList

**Comment by xhofe** [comment]
My fault, this should be fixable

**Comment by DFDzaidu** [comment]
> 我的错，这应该是可以修复的

会修复嘛大佬，apk文件下载下来是zip格式，按道理是MIME 类型设置为 application/vnd.android.package-archive就可以解决啊，我不知道配置文件目录在哪里

**Comment by DFDzaidu** [comment]
> 我的错，这应该是可以修复的

May I ask when it will be repaired?

**Comment by DFDzaidu** [comment]
> My fault, this should be fixable

请问什么时候可以修复完成嘞，想知道下进度，非常感谢谢

**Comment by DFDzaidu** [comment]
滴滴滴

**Comment by DFDzaidu** [comment]
> My fault, this should be fixable
Boss, can you update the code in Docker
