### ISSUE TITLE
[Feature request] 115 获取Linux客户端 Cookies

### ISSUE THREAD

**Issue by cvcodeminer** [alist-org/alist#5386]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's a reasonable and popular requirement.
- [X] I'm sure this feature is not implemented.

### Description of the feature / 需求描述

目前文档提供的115扫码登录是网页版二维码，有效期较短且在手机端APP/网页端重新登录后原cookies会强制失效。

使用Linux端二维码可避免以上问题，希望能更改。

参考来源：115小幸运/Clouddrive的扫码登录方式

**Comment by SheltonZhu** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure it's a reasonable and popular requirement.
> * [x]  I'm sure this feature is not implemented.
> 
> ### Description of the feature / 需求描述
> 目前文档提供的115扫码登录是网页版二维码，有效期较短且在手机端APP/网页端重新登录后原cookies会强制失效。
> 
> 使用Linux端二维码可避免以上问题，希望能更改。
> 
> 参考来源：115小幸运/Clouddrive的扫码登录方式
> 
> ### Suggested solution / 实现思路
> _No response_
> 
> ### Additional context / 附件
> _No response_

已找到方法，修改qrcode 的api的 path 参数web为linux，且传入的参数app: "linux"，即可实现

明天我提pr
