### ISSUE TITLE
[bug] 夸克网盘配置[文件排序] 选择 [文件类型]报错

### ISSUE THREAD

**Issue by giserd** [alist-org/alist#5388]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3

### Driver used / 使用的存储驱动

夸克网盘

### Describe the bug / 问题描述

配置[文件排序] 选择 [文件类型]报错

### Reproduction / 复现链接

只填写cookie可以正常使用没有问题，配置**文件排序**  选择  **文件类型**方式排序会报错

### Config / 配置

只填写cookie可以正常使用没有问题，配置文件排序选文件类型方式排序会报错

**Comment by Mosaic-c** [comment]
同样遇到这个问题，排查好久没用，幸好看到这个issue；
多个版本均有此问题，当前最新版本v3.35.0仍会这样

**Comment by suixing8** [comment]
排序选择 无 解决
