### ISSUE TITLE
web端音频播放增加倍率选择（包含pc web及移动web）

### ISSUE THREAD

**Issue by covered0000** [alist-org/alist#5389]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

web端音频播放增加倍率选择（包含pc web及移动web）
0.5x
1x
1.5x
2x
2.5x
3x

**Comment by vagrant-psyche** [comment]
这个用油猴插件就可以搞定，插件名字为[HTML5视频播放器增强脚本]
