### ISSUE TITLE
百度网盘无法上传大小超过10G的单个文件

### ISSUE THREAD

**Issue by CookiC** [alist-org/alist#5392]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

使用百度网盘无法上传超过10G的单个文件。使用百度网盘客户端可以上传成功，使用alist网页端和alist webdav均无法上传成功。"error_code"是31299，可能是分片问题？

### Reproduction / 复现链接

百度网盘上传超过10G的单个文件即可复现。

### Config / 配置

百度网盘本地代理、官方接口

### Logs / 日志

ERRO[2023-10-17 02:20:05] failed put /: All attempts fail:
#1: upload/download stream incomplete, possible network issue; error in uploading to baidu, will retry. response={"error_code":31299, "error_msg":"Invalid param keylist"}
#2: upload/download stream incomplete, possible network issue; error in uploading to baidu, will retry. response={"error_code":31299, "error_msg":"Invalid param keylist"}
#3: upload/download stream incomplete, possible network issue; error in uploading to baidu, will retry. response={"error_code":31299, "error_msg":"Invalid param keylist"}

**Comment by Taygetus** [comment]
https://pan.baidu.com/disk/help?tab=windows/
普通用户使用百度网盘Web端上传文件时，单文件最大支持1G大小；使用网盘Windows电脑客户端上传文件时，单文件最大支持4G；
如果您需要上传大于4G文件，可充值百度网盘会员，其中：
1)百度网盘会员使用网盘Windows电脑客户端进行大文件上传时，单文件最高达到10G；
2)百度网盘超级会员使用网盘Windows电脑客户端进行大文件上传时，单文件最高达到20G。

**Comment by CookiC** [comment]
我是超级会员，我也试过网盘客户端了，客户端是可以上传成功的，我问题描述里面也说了。

**Comment by iamty7** [comment]
提供一个dp。会员，在网页端，几十M和一百多M的文件，一直重复如上一样的错误。Web代理，WebDAV本地代理/重定向，官方以及非官方接口，UA：netdisk和pan.baidu.com都使用过

**Comment by cancundeyingzi** [comment]
现在大文件似乎还是有这个问题
