### ISSUE TITLE
挂载的驱动如果很多的话，不好找，希望增加一个关键字搜索功能

### ISSUE THREAD

**Issue by twogo** [alist-org/alist#5393]
### Please make sure of the following things

- [√] I have read the [documentation](https://alist.nn.ci).
- [√] ] I'm sure there are no duplicate issues or discussions.
- [√]] I'm sure this feature is not implemented.
- [√] ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

挂载的驱动如果很多的话，不好找，希望增加一个关键字搜索功能。例如：挂载阿里盘的时候，挂载路径填写的是/alipan/西游记，就可以搜索“ali“或者“西游“等关键字可以把这个驱动搜索出来，方便查找

### Suggested solution / 实现思路

查询数据库，只显示符合查询条件的结果，即可实现

**Comment by anwen-anyi** [comment]
自己 Ctrl+F 搜索是一样的吖~ :joy_cat:
