### ISSUE TITLE
浏览器点击下载格式会变ZIP，原本是apk格式文件

### ISSUE THREAD

**Issue by DFDzaidu** [alist-org/alist#5397]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/92215296/11e51f47-07cd-4d0d-9043-cf407ca08d4e)
![image](https://github.com/alist-org/alist/assets/92215296/3b07dd7c-cc6c-46ea-95e6-eba47b83f70c)

### Reproduction / 复现链接

http://cdn-game-fsapk.zaidu.in/d/%E6%B8%B8%E6%88%8F%E5%BA%93/%E6%8B%AF%E6%95%91%E8%80%85%E4%B9%8B%E6%A0%91M.apk

### Config / 配置

![image](https://github.com/alist-org/alist/assets/92215296/b31090e1-51db-4be1-b215-53613bbe8eb6)

### Logs / 日志

无报错

**Comment by DFDzaidu** [comment]
> Hello @DFDzaidu, your issue is a duplicate and will be closed. 你好 @DFDzaidu，你的issue是重复的，将被关闭。
没有重复啊，我只是说明这个问题，而且是可以通过修改服务器配置解决吧，docker的服务器配置在哪个目录啊

**Comment by xhofe** [comment]
#5385

**Comment by DFDzaidu** [comment]
> #5385
请问有解决办法吗
