### ISSUE TITLE
提供存储隐藏功能

### ISSUE THREAD

**Issue by WANGFYPHYS** [alist-org/alist#5401]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

文件加密存储在云端，先以原始数据盘挂载到alist，暂取名为A盘，为了在alist端便于对文件进行查看、修改、下载等操作，在alist中再在A盘的基础上创建加密存储B盘，此时所有功能都可以正常使用。

这里我只需要在主页中看到解密后的B盘即可，解密前的A盘我不需要看到，隐藏在后台运行即可(仅仅是主页上不需要看到A盘，不能直接对它禁用)。所以想要在“存储”模块添加“隐藏”功能，这种情况下“禁用”选项不能满足需求。

### Suggested solution / 实现思路

在“存储”模块添加“隐藏”功能，使其后台运行即可，主页上不显示该存储。

**Comment by anwen-anyi** [comment]
自行将需要隐藏的存储添加到以下位置

- 后台 --> 设置 --> 全局 --> 隐藏文件

注意这个只是前端隐藏了如果你想别人不能访问你也要在元信息设置一下加密措施，否则别人是可以直接通过路径来访问的

**Comment by WANGFYPHYS** [comment]
> 自行将需要隐藏的存储添加到以下位置，像隐藏readme文件那样隐藏一下
> 
>     * 后台 --> 设置 --> 全局 --> 隐藏文件
> 
> 
> 注意这个只是前端隐藏了如果你想别人不能访问你也要在元信息设置一下加密措施，否则别人是可以直接通过路径来访问的

@anwen-anyi 非常感谢您的回复，按照您的方法可以实现隐藏效果。

同时有点问题这里再请教下：正则表达式实现的隐藏——如readme.md文件的隐藏方式——会对所有文件进行索引匹配，这里可能会存在一种误伤的情况，如某文件或者文件夹包含可匹配的字符串。

仿照readme.md文件的隐藏方式，我在隐藏onedrive存储时，包含onedrive字符串的其它存储同时也被隐藏了。同理，可能会自动隐藏其它路径上包含onedrive字符串的文件夹和文件。对于readme.md文件，文件名和后缀都非常具体，而且在页面下端有其内容的直接展示，基本不会误伤文件，对于其它正则表达式的字符串可能需要非常小心的设置才能实现精准隐藏，而不会存在误伤的情况。

以上是我的一点肤浅的理解，对正则表示的理解也不深入。如理解有误，还请大佬多多批评指正。

**Comment by xhofe** [comment]
后台设置-元信息-添加
- 路径: /盘路径目录
- 隐藏: /盘路径名称

**Comment by anwen-anyi** [comment]
> > 自行将需要隐藏的存储添加到以下位置，像隐藏readme文件那样隐藏一下
> > ```
> > * 后台 --> 设置 --> 全局 --> 隐藏文件
> > ```
> > 
> > 
> > 注意这个只是前端隐藏了如果你想别人不能访问你也要在元信息设置一下加密措施，否则别人是可以直接通过路径来访问的
> 
> @anwen-anyi 非常感谢您的回复，按照您的方法可以实现隐藏效果。
> 
> 同时有点问题这里再请教下：正则表达式实现的隐藏——如readme.md文件的隐藏方式——会对所有文件进行索引匹配，这里可能会存在一种误伤的情况，如某文件或者文件夹包含可匹配的字符串。
> 
> 仿照readme.md文件的隐藏方式，我在隐藏onedrive存储时，包含onedrive字符串的其它存储同时也被隐藏了。同理，可能会自动隐藏其它路径上包含onedrive字符串的文件夹和文件。对于readme.md文件，文件名和后缀都非常具体，而且在页面下端有其内容的直接展示，基本不会误伤文件，对于其它正则表达式的字符串可能需要非常小心的设置才能实现精准隐藏，而不会存在误伤的情况。
> 
> 以上是我的一点肤浅的理解，对正则表达式的理解也不深入。如表述有误，还请大佬多多批评指正。
> 
> 最后，如有可能，希望后续开发也可以考虑在存储配置的位置，“禁用”功能旁边也添加一个“隐藏”的功能。

那目前只能起名字争取不和隐藏的名字文件/夹避免冲突了...这个是最好的办法了应该

**Comment by WANGFYPHYS** [comment]
好的，已经了解相关设置的方法，感谢两位大佬的耐心解答！
