### ISSUE TITLE
优先级功能

### ISSUE THREAD

**Issue by windy664** [alist-org/alist#5406]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

![image](https://github.com/alist-org/alist/assets/81475218/ea7070f5-9b7d-4def-a7a1-8a2279e01b72)
怎么设置优先级
比如
下载第一
因为谷歌和微软国内用不了。。

**Comment by IAALAI** [comment]
你的需求可能需要在 [alist-web](https://github.com/alist-org/alist-web) 实现
