### ISSUE TITLE
断网后，仍挂载网盘会导致资源管理器崩溃，进而导致死机

### ISSUE THREAD

**Issue by teleen** [alist-org/alist#5410]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.27.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

使用需要验证登录的网络时，如果发生了验证过期，而导致网络服务中断时，仍挂载着网盘的Alist会导致文件资源管理器发生卡死，进而影响整个系统的运行，表现为文件资源管理器无响应，任务栏静止并失灵，桌面图标无法点击，除触控反馈外一切操作都无法进行；此时整个系统处于卡死状态，只能强制关机；
卸载了网盘后，网络验证过期后，没有再发现上述问题，由此推出应该是Alist软件的问题；

使用的设备为 surface pro x sq2，使用 windows on arm，版本：22635.2486

### Reproduction / 复现链接

你找个限制用户登录数的校园网，用Alist挂载自己的网盘，然后打开文件资源管理器（打开即可，甚至不需要进入到网盘的子目录），然后随便找个新设备把挂载着网盘的设备踢下线，就能复现死机的问题了；

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "KXSLrEhQWIdPkZoA",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "C:\\Users\\HI\\AppData\\Roaming\\ci.nn.alist\\data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "C:\\Users\\HI\\AppData\\Roaming\\ci.nn.alist\\temp",
  "bleve_dir": "C:\\Users\\HI\\AppData\\Roaming\\ci.nn.alist\\bleve",
  "log": {
    "enable": true,
    "name": "C:\\Users\\HI\\AppData\\Roaming\\ci.nn.alist\\log\\log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

### Logs / 日志

[GIN] 2023/10/20 - 17:39:44 | 207 |      1.09795s |       127.0.0.1 | PROPFIND  "/dav/百度网盘/"
[GIN] 2023/10/20 - 17:39:45 | 207 |     745.598ms |       127.0.0.1 | PROPFIND  "/dav/百度网盘/课程/"
[GIN] 2023/10/20 - 17:39:45 | 207 |    498.1406ms |       127.0.0.1 | PROPFIND  "/dav/百度网盘/课程/0.考研/"
[GIN] 2023/10/20 - 17:39:46 | 207 |    509.1558ms |       127.0.0.1 | PROPFIND  "/dav/百度网盘/课程/0.考研/考研政治/"
[GIN] 2023/10/20 - 17:39:47 | 207 |    507.7608ms |       127.0.0.1 | PROPFIND  "/dav/百度网盘/课程/0.考研/考研政治/徐涛考研政治课程/"
[GIN] 2023/10/20 - 17:39:47 | 207 |    730.5424ms |       127.0.0.1 | PROPFIND  "/dav/百度网盘/课程/0.考研/考研政治/徐涛考研政治课程/01.徐涛/"
[GIN] 2023/10/20 - 17:39:48 | 207 |      6.7055ms |       127.0.0.1 | PROPFIND  "/dav/"
[GIN] 2023/10/20 - 18:56:34 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/"
[GIN] 2023/10/20 - 19:01:54 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/"
[33mWARN[0m[2023-10-20 19:05:25] not enable search                    

（仅复制一小段，应该是这段时间内死的机，我19：00多唤醒电脑的时候就直接死机了）

**Comment by bukaixyz** [comment]
弄这个政治有什么用啊 中共国天天不下台 不民主 不自由 这些政治都是中共的洗脑话术🌝

**Comment by teleen** [comment]
> 弄这个政治有什么用啊 中共国天天不下台 不民主 不自由 这些政治都是中共的洗脑话术🌝

麻烦请不要发表煽动性言论；并且，不管您支持何种观点，请不要侮辱我所学习的学科，侮辱科学，侮辱一门国际公认的哲学学科，谢谢

**Comment by bukaixyz** [comment]
> > 弄这个政治有什么用啊 中共国天天不下台 不民主 不自由 这些政治都是中共的洗脑话术🌝
> 
> 麻烦请不要发表煽动性言论；并且，不管您支持何种观点，请不要侮辱我所学习的学科，侮辱科学，侮辱一门国际公认的哲学学科，谢谢

我坚决支持资本主义 有些东西只有资本主义才能实现 中共社会主义 工人过的也不好 比亚迪工厂剥削工人 社会主义有什么用啊 比亚迪工人吃的东西 他们自己说是“猪食” 反而资本主义有福利政策 特斯拉工人待遇就好 🌝

而且**马克思**主义 有些就是胡乱想象 没有意义 这些说难听点就是废话🌝共产主义也是完全无法实现的🌝

**Comment by bukaixyz** [comment]
> > 弄这个政治有什么用啊 中共国天天不下台 不民主 不自由 这些政治都是中共的洗脑话术🌝
> 
> 麻烦请不要发表煽动性言论；并且，不管您支持何种观点，请不要侮辱我所学习的学科，侮辱科学，侮辱一门国际公认的哲学学科，谢谢

没有资本主义，**美国🇺🇸就不可能发展成为一个经济，军事全球第一的发达国家**

**Comment by bukaixyz** [comment]
所以中共就要搞Github 进行大规模DNS污染 阻碍访问 但是又不能彻底墙掉 因为一堆程序员要用 程序员可以解决这些DNS污染问题 🌝🌝🌝

**Comment by woshichenghaibo** [comment]
> 弄这个政治有什么用啊 中共国天天不下台 不民主 不自由 这些政治都是中共的洗脑话术🌝

废话，那都是没办法的事，你不学就没法毕业，能怎么办
