### ISSUE TITLE
通过/api/fs/form接口上传文件操作，提示400错误

### ISSUE THREAD

**Issue by DFDzaidu** [alist-org/alist#5411]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

使用的axios
请求头
```
 const config = {
        method: 'put',
        url: 'http://nas.baidu.in:5244/api/fs/form',
        headers: {
            'Authorization': token,//通过接口登录获取的
            'Content-Type': 'multipart/form-data;',
            'Content-Length': fileSize.bytes, // 文件的字节数 145456
            'file_path': ‘file%3A%2F%2FD%3A%5C%E5%89%8D%E7%AB%AF%E5%AD%A6%E4%B9%A0%5Cmain%5Cinterface%5Creptile%5CGoogelPlay%5Cimg%5Caaaa.png’
        },
        data: {   //body内容
  file: 'file://D:\\前端学习\\main\\interface\\reptile\\GoogelPlay\\img\\aaaa.png'
}
    };
```
   
**请求后返回**

`{"code":400,"message":"storage not found; please add a storage first","data":null}`

![image](https://github.com/alist-org/alist/assets/92215296/ea6dfdbe-3632-4b06-bbc8-1b0317fec3df)

有一个本地存储
![image](https://github.com/alist-org/alist/assets/92215296/b97df84b-8fb5-4d44-9aab-355ed058105f)

    

### Reproduction / 复现链接

无

### Config / 配置

![image](https://github.com/alist-org/alist/assets/92215296/a2fe0721-f8e5-42b9-9d00-6f1a2d5b8408)

**Comment by DFDzaidu** [comment]
为啥？不能帮忙解答下吗

**Comment by KnIfER** [comment]
解决了吗？上传到哪里怎么指定呢，
