### ISSUE TITLE
CloudFlare Worker Custom Domain

### ISSUE THREAD

**Issue by zonprox** [alist-org/alist#5419]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Support Custom domain for CloudFlare Worker

ex: api.domain.worker.dev -> api.domain.com

I've try but it will result in error "Error 1101 - Worker thrown exception".

**Comment by woshichenghaibo** [comment]
没看懂什么意思

cf 域名根这个有啥关系？

**Comment by zonprox** [comment]
> 没看懂什么意思
> 
> cf 域名根这个有啥关系？

例如，如果您下载普通文件，则链接将为：https://api.domain.workers.dev/file.zip，但是Cloudflare支持自定义域名，那么您可以使用您的域名下载文件。 ：https://api.domain.net/file.zip

但也许 Alist 还不支持这个自定义域

**Comment by zonprox** [comment]
Issues with CW.

**Comment by sd14** [comment]
1101错误跟自定义域没关系，本来就都是用自定义域，workers.dev被墙了又不通的。
你看看worker里的ADDRESS是不是填了IP？
