### ISSUE TITLE
国内访问polyfill.io速度不稳定，导致首页加载速度有时很慢

### ISSUE THREAD

**Issue by ghxtgh** [alist-org/alist#5424]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

国内访问polyfill.io速度不稳定
https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll这个接口的请求时间国内不稳定

### Suggested solution / 实现思路

使用阿里云cdn加速
https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll

### Additional context / 附件

[](url)
![微信图片_20231024171305](https://github.com/alist-org/alist/assets/42051128/a2e699d7-1430-40ea-ab4e-6f6ca78736af)

**Comment by xhofe** [comment]
这只是一个默认的设置 你完全可以自行在后台的设置中自行更改。

**Comment by Coder-ZZY** [comment]
hello,如何更改这个接口的设置

**Comment by gdtv** [comment]
> hello,如何更改这个接口的设置

管理 -> 设置 -> 全局 -> 自定义头部，将里面的 https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll 改成 https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll
