### ISSUE TITLE
希望增加在FTP挂载alist功能，兼容其它应用

### ISSUE THREAD

**Issue by goldsoft8888** [alist-org/alist#5426]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加在FTP挂载alist功能，兼容其它应用

就是在FTP里可以操作ALIST，这个比SMB挂载alist应该更容易实现，
现在只有用webdav一种访问方式，一些应用并不支持webdav

**Comment by goldsoft8888** [comment]
RCLONE是支持的

**Comment by yyyytawa** [comment]
加一 有的应用死活不支持webdav

**Comment by goldsoft8888** [comment]
老设备与应用，非常需要FTP挂载ALIST功能

**Comment by oldsento** [comment]
现在支持了吗？或者有没有其他方法
