### ISSUE TITLE
123直链有效期异常

### ISSUE THREAD

**Issue by cancundeyingzi** [alist-org/alist#5428]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.28

### Driver used / 使用的存储驱动

123直链

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/73635883/df73f659-6de2-415e-bc3d-db05ed6cc1c3)
有效时长无效,被全局覆盖
![image](https://github.com/alist-org/alist/assets/73635883/e32aceed-0f60-492c-a363-aaa71164f517)
![image](https://github.com/alist-org/alist/assets/73635883/f0d7a19a-0113-4207-b483-028f75535a58)

### Reproduction / 复现链接

这个直链链接是可以公开的吗?

### Config / 配置

![image](https://github.com/alist-org/alist/assets/73635883/59a202c7-b717-44e7-80af-979b8d490246)
![image](https://github.com/alist-org/alist/assets/73635883/b187b352-163e-4770-9fc2-4b7659389371)
![image](https://github.com/alist-org/alist/assets/73635883/a18d9728-ec60-4095-871c-867212533840)
![image](https://github.com/alist-org/alist/assets/73635883/dc65daff-a0dd-40c0-a1e0-d90564d720a5)

**Comment by xhofe** [comment]
这个不是123直链的有效期，而是alist直链的有效期，302跳转之后才是123的链接。
