### ISSUE TITLE
挂载百度网盘选择“web代理+本地代理”，会出错 unexpected eof，表现为下载速度变慢、中断、或失败

### ISSUE THREAD

**Issue by leungdavid7233** [alist-org/alist#5433]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.00

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

挂载百度网盘选择“web代理+本地代理”，会出错 unexpected eof，表现为下载速度变慢、中断、或失败

### Reproduction / 复现链接

挂载百度网盘选择“web代理+本地代理”，会出错 unexpected eof，表现为下载速度变慢、中断、或失败

### Config / 配置

挂载百度网盘选择“web代理+本地代理”，会出错 unexpected eof，表现为下载速度变慢、中断、或失败

**Comment by xhofe** [comment]
这应该与网络相关，在好的网络中表现是正常的。我说的提issue的是指
```
failed link: failed get link: json: cannot unmarshal number into Go struct field DownloadResp.request_id of type string
````
