### ISSUE TITLE
离线上传

### ISSUE THREAD

**Issue by Hua-Fen** [alist-org/alist#5438]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在使用openalist的时候，我想通过路由器本身进行文件上传，而不是通过电脑上传，这样即使电脑关机，上传任务也不会中断。

### Suggested solution / 实现思路

我看到alist中的离线下载功能是先通过aria2，先下载文件到本地设备，然后再将下载的文件传输到相应的存储。在使用openalist时，此时的本地设备应该是路由器本身的存储设备，如果能把后半部分“将下载的文件传输到相应的存储”功能拆分出来，一个就可以实现从路由器上传文件到网盘中了。

**Comment by anwen-anyi** [comment]
你在路由器搭建就可以了呀~ :joy_cat:

**Comment by Hua-Fen** [comment]
> 你在路由器搭建就可以了呀~ 😹

您可以说的具体一点吗

**Comment by IAALAI** [comment]
你想要的是:直接用路由器下载一个文件，然后再让它自己传到alist上吗？

老实说，我总感觉这里的问题总有逆天的。。。

你可以先去百度一下离线下载，然后再百度一下离线上传

**Comment by Hua-Fen** [comment]
> 你想要的是:直接用路由器下载一个文件，然后再让它自己传到alist上吗？
> 
> 老实说，我总感觉这里的问题总有逆天的。。。
> 
> 你可以先去百度一下离线下载，然后再百度一下离线上传

我在电脑上有想要上传到视频文件，但是学校晚上会停电，我害怕文件传不完电脑就关机了，想着把文件先传到路由器挂载的存储器上，再从路由器把文件上传到阿里云盘，因为我的alist就是部署在路由器上的嘛。

**Comment by IAALAI** [comment]
> 我在电脑上有想要上传到视频文件，但是学校晚上会停电，我害怕文件传不完电脑就关机了，想着把文件先传到路由器挂载的存储器上，再从路由器把文件上传到阿里云盘，因为我的alist就是部署在路由器上的嘛。

但是你标题的离线上传，还是感觉很逆天。

你功能的需求倒是可以简单实现。这个都不需要对alist本身做任何改动

我有一个很简单的实现方式,alist是支持添加本地存储的，也就是服务器内置的磁盘。同时支持在已添加的不同存储之间移动或者复制文件。剩下的你应该明白了吧

**Comment by Hua-Fen** [comment]
> > 我在电脑上有想要上传到视频文件，但是学校晚上会停电，我害怕文件传不完电脑就关机了，想着把文件先传到路由器挂载的存储器上，再从路由器把文件上传到阿里云盘，因为我的alist就是部署在路由器上的嘛。
> 
> 但是你标题的离线上传，还是感觉很逆天。
> 
> 你功能的需求倒是可以简单实现。这个都不需要对alist本身做任何改动
> 
> 我有一个很简单的实现方式,alist是支持添加本地存储的，也就是服务器内置的磁盘。同时支持在已添加的不同存储之间移动或者复制文件。剩下的你应该明白了吧

非常感谢

**Comment by gowy222** [comment]
小哥哥为何不折腾下软路由？ @Hua-Fen
