### ISSUE TITLE
移动与复制

### ISSUE THREAD

**Issue by Oliyrs** [alist-org/alist#5441]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

移动与复制能否直接将文件从一个文件夹拖入另一个文件夹

**Comment by anwen-anyi** [comment]
`移动`：一般是同一个存储之间移动用的吧，就是例如挂载路径写的是`A`那你只能在A网盘到A网盘之间的文件夹

`复制`：可以将其它存储的文件/夹 复制过来，当然复制是需要下载上传的，如果能秒传不需要下载。

并且你这个应该去`Discussions`合适一些~

**Comment by jianboy** [comment]
@anwen-anyi 

我问一下，**复制**

A 文件夹 复制到 B文件夹，复制到一半异常。 那么，**重新执行 A文件夹复制到 B文件夹**, 那么 B文件夹是会文件覆盖呢，还是重命名保存，还是检测是否存在，存在则不复制。

**Comment by IAALAI** [comment]
@anwen-anyi 

> `移动`：一般是同一个存储之间移动用的吧，就是例如挂载路径写的是`A`那你只能在A网盘到A网盘之间的文件夹
> 
> `复制`：可以将其它存储的文件/夹 复制过来，当然复制是需要下载上传的，如果能秒传不需要下载。
> 
> 并且你这个应该去`Discussions`合适一些~

其实我倒是希望可以实现从一个直接下载内容然后传到另一个网盘上面，就像一个stream一样，等另一个网盘接收完成再删除掉第一个网盘中的内容。
