### ISSUE TITLE
老是出现502 Bad Gateway nginx

### ISSUE THREAD

**Issue by MrOldsix6** [alist-org/alist#5442]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

不知道怎么回事，我的Alist 老是出现502 Bad Gateway nginx ，一般一天之内会出现一两次这样。需要重启服务器之后就可以正常访问了。

**Comment by anwen-anyi** [comment]
你的AList崩了吧？你在做什么操作在AList里面~

**Comment by MrOldsix6** [comment]
应该是，就是不知道怎么解决

**Comment by MrOldsix6** [comment]
> 你的AList崩了吧？你操作在AList里面~

应该是的，不知道怎么解决
