### ISSUE TITLE
Sometimes BaiduNetdisk assigns an IPv6 download link in IPv4 only network

### ISSUE THREAD

**Issue by 2ndMessiah** [alist-org/alist#5443]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

BaiduNetdisk

### Describe the bug / 问题描述

Hi~! Appreciate the contribution to the development of the prestigious Alist !!

I'm using BaiduNetdisk and sometimes it responds with an ipv6 link and my network is ipv4 only..

`{"code":500,"message":"Get \"http://[********************************6]/b/nd6.baidupcs.com/file/[omitted]by=themis\": dial tcp [***************************]:80: connect: cannot assign requested address","data":null}`

Any suggestions for mitigating this? 

An option of ipv4/6 first, or an ipv4/6 fail/retry mechanism would be nice.

Waiting for a reply. Thx again!

### Reproduction / 复现链接

http://[********************************6]/b/nd6.baidupcs.com/file/[omitted]by=themis\": dial tcp [***************************]:80

### Config / 配置

version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - './data:/opt/alist/data'
            - '/mnt/mmcblk2p4/tdl/downloads:/tg'
        ports:
            - '1000:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: alist
        image: 'xhofe/alist:latest'

**Comment by xhofe** [comment]
Provide a log file pls.

**Comment by 2ndMessiah** [comment]
> Provide a log file pls.

Thx for the reply, [xhofe](https://github.com/xhofe)!!

Here you are:
[log.log](https://github.com/alist-org/alist/files/13197388/log.log)

**Comment by xhofe** [comment]
The ipv6 address is returned by Baidu Netdisk. Currently, we cannot control the returned address through the document https://pan.baidu.com/union/doc/pkuo3snyp 
This may require consulting official technical support
