### ISSUE TITLE
通过RaiDrive同时挂载阿里云盘和天翼云盘个人盘, 阿里云盘可以复制文件到本地, 但天翼云盘复制提示"目标文件夹访问被拒绝"

### ISSUE THREAD

**Issue by leiax01** [alist-org/alist#5446]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

天翼云盘客户端

### Describe the bug / 问题描述

root@lax-pi:/repo_dev/devData/alist# docker exec -it alist ./alist version
Built At: 2023-09-22 14:57:58 +0000
Go Version: go1.20.8 linux/arm64
Author: Xhofe <i@nn.ci>
Commit ID: a64dd48
Version: v3.28.0
WebVersion: 3.28.0

同时挂载后, 从天翼云盘复制文件到本地, 提示"目标文件夹访问被拒绝";
alist通过docker部署, 使用的是:
xhofe/alist                                      latest                  3086087698be   5 weeks ago     62.4MB

部署在树莓派4B上, 通过RaiDrive挂载在win11上, 以上为win11上的操作结果, 阿里云盘能够正常复制到本地
![image](https://github.com/alist-org/alist/assets/69620433/21ed20f2-335f-40a0-86e1-78394648a5d6)

### Reproduction / 复现链接

链接目前无外网代理

### Config / 配置

![image](https://github.com/alist-org/alist/assets/69620433/c39434d1-4f64-4006-9cc9-b1b94a1e6b07)
配置文件为docker镜像默认配置, 还未进行定制修改

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/69620433/f6ff3939-5b5d-4cc8-8e0a-ffabb3ffc1de)
复制EdrawMax-v12.0.4.938.7z文件时的日志段如上图;

**Comment by xhofe** [comment]
请尝试将存储中的webdav策略改为 本地代理

**Comment by leiax01** [comment]
ok, 修改后能正常复制粘贴
