### ISSUE TITLE
截至目前2023年10月31日22:26:55为止的最新版 alist，挂载的百度网盘能访问列表，但不能下载文件

### ISSUE THREAD

**Issue by Hz2134** [alist-org/alist#5452]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0 

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

Chrome浏览器点击下载弹出新窗口错误代码：{"code":500,"message":"http request [https://d.pcs.baidu.com/file/1a4e49409t269eeff73e60cc11606ae6?fid=1208691927-250528-1105131477315054\u0026rt=pr\u0026sign=FDtAERK-DCb740ccc5511e5e8fedcff06b081203-MtLzzJfOe368eVI%2f44eKoVdQR7Y%3d\u0026expires=8h\u0026chkbd=0\u0026chkv=0\u0026dp-logid=131690834942927590\u0026dp-callid=0\u0026dstime=1698762791\u0026r=992257131\u0026vuk=1208691927\u0026origin=dlna] failure,status: 403 response:\u001f\ufffd\u0008\u0000\u0000\u0000\u0000\u0000\u0000\u0003-\ufffdA\n\ufffd \u0010\u0000\ufffd\ufffd,{\ufffd\ufffdJ\ufffd~\u0026,\ufffd\ufffd\ufffd\ufffd\ufffdN\ufffd\ufffd#h\ufffds#\ufffd\u001c2LG\u0026\ufffdV[\u0013\ufffd_[\ufffd1\ufffdR\u001a\ufffd\ufffd\ufffd\u0015\ufffdJ¥6P\ufffdea\ufffd4\u0013d\ufffd\u0013*\u0014:/\ufffdm(\u0019\ufffd\ufffdڅ.tޘ\ufffd\ufffd\ufffd\ufffd{^\u0018\ufffd 2h\u0000\u0000\u0000","data":null}

### Reproduction / 复现链接

http://127.0.0.1:5244/p/%E7%99%BE%E5%BA%A6/0.0%20%5B%E4%B8%B4%E6%97%B6%E6%96%87%E4%BB%B6%E5%A4%B9%5D/MicrosoftCorporationII.WindowsSubsystemForAndroid_2208.40000.5.0_neutral___8wekyb3d8bbwe.Msixbundle

### Config / 配置

不知道怎么弄 ... 为什么不在需要提供相关信息的后面加个括号超链接到相关的简单教程？并不是所有人的水平和理解能力都在某个线之上，提高门槛显得专业是很不理智的

**Comment by IAALAI** [comment]
我现在挂载的百度网盘还是可以正常下载的，超级VIP账号还能跑满带宽

![5ac00a672ac03e2048edbc7b5f7825d](https://github.com/alist-org/alist/assets/50038322/1011ebc7-99eb-4cac-b427-2d523385c449)

关于你对于配置的想法我感觉确实有道理，要是可以提供实现某些功能的简单配置案例拿来改就好了。好多时候看配置文件都实现不了自己想要的效果。研究还得费时间。可是等我自己懂了，又懒得去写给别人看。。。

**Comment by IAALAI** [comment]
我认为应该是你的设置没正确，大概率是添加存储的时候写错选项了

**Comment by tanpengsccd** [comment]
和你问题一样. 报 ：{"code":500,"message" .....
