### ISSUE TITLE
移动云盘家庭云的文件不支持删除吗？删除时出现提示：家庭云未知异常

### ISSUE THREAD

**Issue by yeyudoc** [alist-org/alist#5460]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

中国移动云盘

### Describe the bug / 问题描述

移动云盘家庭云的文件不支持删除吗？删除时出现提示：家庭云未知异常
教程文档中只说不支持家庭云不支持重命名、移动、复制和上传。

### Reproduction / 复现链接

无

### Config / 配置

无

### Logs / 日志

无

**Comment by StandGreat** [comment]
> 家庭云只能下载，其他操作都不支持

下载和播放视频也没用 也是报个人云异常  {"code":500,"message":"failed link: failed get link: 个人云未知异常","data":null}

**Comment by StandGreat** [comment]
> > > 家庭云只能下载，其他操作都不支持
> > 
> > 
> > 下载和播放视频也没用 也是报个人云异常 {"code":500,"message":"failed link: failed get link: 个人云未知异常","data":null}
> 
> 新号要用另外一个

我这不是新号，用了三年了，把家庭云（但是家庭户主不是当前账号）添加以后文件目录是正常的，但是打开视频就打不开，报错报的也是“个人云异常”

**Comment by StandGreat** [comment]
> > > > > 家庭云只能下载，其他操作都不支持
> > > > 
> > > > 
> > > > 下载和播放视频也没用 也是报个人云异常 {"code":500,"message":"failed link: failed get link: 个人云未知异常","data":null}
> > > 
> > > 
> > > 新号要用另外一个
> > 
> > 
> > 我这不是新号，用了三年了，把家庭云（但是家庭户主不是当前账号）添加以后文件目录是正常的，但是打开视频就打不开，报错报的也是“个人云异常”
> 
> 配置截个图看看

![image](https://github.com/alist-org/alist/assets/95478133/70d204eb-033b-416b-af8e-60300c8c23b2)
家庭云也就是配置一个Authorization和cloudid

**Comment by StandGreat** [comment]
> > > > > > > 家庭云只能下载，其他操作都不支持
> > > > > > 
> > > > > > 
> > > > > > 下载和播放视频也没用 也是报个人云异常 {"code":500,"message":"failed link: failed get link: 个人云未知异常","data":null}
> > > > > 
> > > > > 
> > > > > 新号要用另外一个
> > > > 
> > > > 
> > > > 我这不是新号，用了三年了，把家庭云（但是家庭户主不是当前账号）添加以后文件目录是正常的，但是打开视频就打不开，报错报的也是“个人云异常”
> > > 
> > > 
> > > 配置截个图看看
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/95478133/326235480-70d204eb-033b-416b-af8e-60300c8c23b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODY5OTcsIm5iZiI6MTcxNDI4NjY5NywicGF0aCI6Ii85NTQ3ODEzMy8zMjYyMzU0ODAtNzBkMjA0ZWItMDMzYi00MTZiLWFmOGUtNjAzMDBjOGMyM2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA2NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZThjMGNjMWJjOTFlNzVlZjQzYWVmOTdlODQ3NWI0N2IyZmEyNWIwYjIzYmMxYTUxMjFjMjNlZGQ3ZWRiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yOaUILtpRgArNGdLLgf60BIJ4WBYURgc1GHXsruKyQ0) 家庭云也就是配置一个Authorization和cloudid
> 
> 你用你自己创建的家庭Cloud id呢

用自己的没有问题，不过这样挂载的空间就是我自己账号的，那想要挂载非创建者的家庭云应该怎么实现呢？是不是暂时还不支持？

**Comment by StandGreat** [comment]
> > > > > > > > > 家庭云只能下载，其他操作都不支持
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 下载和播放视频也没用 也是报个人云异常 {"code":500,"message":"failed link: failed get link: 个人云未知异常","data":null}
> > > > > > > 
> > > > > > > 
> > > > > > > 新号要用另外一个
> > > > > > 
> > > > > > 
> > > > > > 我这不是新号，用了三年了，把家庭云（但是家庭户主不是当前账号）添加以后文件目录是正常的，但是打开视频就打不开，报错报的也是“个人云异常”
> > > > > 
> > > > > 
> > > > > 配置截个图看看
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/95478133/326235480-70d204eb-033b-416b-af8e-60300c8c23b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODY5OTcsIm5iZiI6MTcxNDI4NjY5NywicGF0aCI6Ii85NTQ3ODEzMy8zMjYyMzU0ODAtNzBkMjA0ZWItMDMzYi00MTZiLWFmOGUtNjAzMDBjOGMyM2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA2NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZThjMGNjMWJjOTFlNzVlZjQzYWVmOTdlODQ3NWI0N2IyZmEyNWIwYjIzYmMxYTUxMjFjMjNlZGQ3ZWRiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yOaUILtpRgArNGdLLgf60BIJ4WBYURgc1GHXsruKyQ0) 家庭云也就是配置一个Authorization和cloudid
> > > 
> > > 
> > > 你用你自己创建的家庭Cloud id呢
> > 
> > 
> > 用自己的没有问题，不过这样挂载的空间就是我自己账号的，那想要挂载非创建者的家庭云应该怎么实现呢？是不是暂时还不支持？
> 
> 把别人的cookie拿过来

哦哦 确实 就是以拿创建者的号挂载就行
