### ISSUE TITLE
列表视图也可以展示缩略图

### ISSUE THREAD

**Issue by ty114514** [alist-org/alist#5463]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

横向列表信息量更为丰富，但是缺乏预览；同样的网格视图看不了文件大小和日期信息，需要整合一下
我想可以参考 filebrowser
![Screenshot_2023-11-02-21-48-25-799_io github forkmaintainers iceraven](https://github.com/alist-org/alist/assets/128409628/765fb4ec-3248-49e8-b79b-63c4b5d85e53)

**Comment by ypq123456789** [comment]
支持，很有道理
