### ISSUE TITLE
使用webdav在“根文件夹路径”重命名文件会导致文件被移动至Onedrive根目录中

### ISSUE THREAD

**Issue by wc7086** [alist-org/alist#5468]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.28.0

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

例如我将`/public/test`设置为`根文件夹路径`，该文件夹中有一个名为`test`的文件，使用webdav连接后我修改了该文件的文件名，该文件将会被移动至Onedrive的`/`目录中。

### Reproduction / 复现链接

1. 在储存驱动的根文件夹中创建一个文件
2. 在webdav中修改该文件的名称

### Config / 配置

```
{
  "force": false,
  "site_url": "https://*",
  "cdn": "",
  "jwt_secret": "*",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}
```
![image](https://github.com/alist-org/alist/assets/74053663/0a32b825-ab0e-4a5a-ba8b-08b910a95d3d)

**Comment by kiki-theone** [comment]
我也遇到同样的问题。

**Comment by longnk** [comment]
WEB页面上重命名文件也会复现此问题
