### ISSUE TITLE
115网盘qrcode登陆出现错误

### ISSUE THREAD

**Issue by carlye** [alist-org/alist#5471]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

115 网盘

### Describe the bug / 问题描述

我在路由器使用alist，目前已经更新到最新版本，alist-linux-musl-mipsle v3.28.0。使用https://alist.nn.ci/zh/guide/drivers/115.html，qrcode扫码登陆后，在alist里填入二维码令牌，报错：
Failed init storage: failed to login by qrcode: json: cannot unmarshal number 2274283412 into Go struct field .data.is_vip of type int
前面做活动又买了8年，目前账号有效年限2042-01-26过期，感觉会不会vip过期时间是超限了，需要使用int64。
买8年会员前登陆正常的。

### Reproduction / 复现链接

http://192.168.10.200:5244/@manage/storages/edit/1

### Config / 配置

<img width="913" alt="image" src="https://github.com/alist-org/alist/assets/1324184/fd10ca1d-69e2-4cf7-b165-b03eba65ddee">
<img width="1037" alt="image" src="https://github.com/alist-org/alist/assets/1324184/9e55e393-5938-4e00-91ee-cf65975aca0a">

### Logs / 日志

Failed init storage: failed to login by qrcode: json: cannot unmarshal number 2274283412 into Go struct field .data.is_vip of type int

**Comment by xhofe** [comment]
This should be fixed in da1c7a4c230f731e0b2ce6a1b316cf779fb57700
