### ISSUE TITLE
GitHub Security Lab (GHSL) Vulnerability Report, Alist

### ISSUE THREAD

**Issue by Kwstubbs** [alist-org/alist#5477]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

[Github Security Lab](https://securitylab.github.com/) has submitted a vulnerability report at https://github.com/alist-org/alist/security/advisories/GHSA-6cg9-7cgv-727q. Please let us know if any the maintainers of Alist are able to see this report by replying in the advisory. We look forward to helping you fix this issue. Thank you.

### Reproduction / 复现链接

Can be found in vulnerability report.

### Config / 配置

Default

**Comment by itsHenry35** [comment]
<img width="1536" alt="image" src="https://github.com/alist-org/alist/assets/58730749/ff543cd1-ff58-404a-8aa2-bed45c1654a2">
where did you find this?

**Comment by itsHenry35** [comment]
sorry that I misunderstood you, i think you should email or tag him if it's urgent

**Comment by Kwstubbs** [comment]
@xhofe has responded in the draft advisory
