### ISSUE TITLE
在元信息设置文件夹密码后，网页端访问时需要输入密码，但在WebDav无需密码即可访问

### ISSUE THREAD

**Issue by AChangAZha** [alist-org/alist#5484]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

阿里云盘OneDrive

### Describe the bug / 问题描述

如题所述。文件夹密码仅对网页端生效。
WebDav使用的用户仅含有`Webdav 读取`权限。如我对`/test`设置密码，WebDav访问`/dav/test/`无需密码即可访问。使用的软件是Android的CX文件管理器。

### Reproduction / 复现链接

本地安装，http://localhost:5244/dav

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "Zxc8gsEf4yTVWbVL",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

### Logs / 日志

[GIN] 2023/11/07 - 07:44:51 | 207 |      258.97µs |      172.17.0.1 | PROPFIND  "/dav/"
[GIN] 2023/11/07 - 07:44:51 | 207 |     560.902µs |      172.17.0.1 | PROPFIND  "/dav/test/"

**Comment by xhofe** [comment]
webdav协议不支持二次密码。
