### ISSUE TITLE
docker版本挂载夸克上传文件会在5分钟超时

### ISSUE THREAD

**Issue by tonvoo** [alist-org/alist#5487]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.28

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

在dsm安装了docker版本的alist，3.28，挂载了夸克做webdav。
使用cloud sync的webdav向夸克同步数据，启用了加密，发现以下现象：一个文件，在5分钟时间内没有上传完成时，就会被清理掉，然后重新上传。一直循环，导致永远不能完成同步任务。
没有发现代码有5分钟限制，不知道问题在哪里。

### Reproduction / 复现链接

使用cloud sync的webdav向夸克同步数据，启用了加密，发现以下现象：一个文件，在5分钟时间内没有上传完成时，就会被清理掉，然后重新上传。一直循环，导致永远不能完成同步任务。

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xxxxxxxxx",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

### Logs / 日志

[31mERRO[0m[2023-11-07 19:14:01] PUT /dav/quark/NAS_Sync/Photos/2022.6.11#野营@中水湿地公园/DJI_0213.MP4 webdav: locked 
[GIN] 2023/11/07 - 19:14:01 | 423 |      84.771µs |      172.17.0.1 | PUT      "/dav/quark/NAS_Sync/Photos/2022.6.11#野营@中水湿地公园/DJI_0213.MP4"
[31mERRO[0m[2023-11-07 19:14:02] failed to close file streamer, close /opt/alist/data/temp/file-787402343: file already closed 
[31mERRO[0m[2023-11-07 19:14:02] failed put /quark/NAS_Sync/Photos/2022.6.11#野营@中水湿地公园: up status: 0, error: 
github.com/alist-org/alist/v3/internal/op.Put
	/app/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/fs.putDirectly
	/app/internal/fs/put.go:54
github.com/alist-org/alist/v3/internal/fs.PutDirectly
	/app/internal/fs/fs.go:96
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePut
	/app/server/webdav/webdav.go:341
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:65
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:113
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1995
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1598 
[31mERRO[0m[2023-11-07 19:14:02] PUT /dav/quark/NAS_Sync/Photos/2022.6.11#野营@中水湿地公园/DJI_0213.MP4 up status: 0, error: 
github.com/alist-org/alist/v3/internal/op.Put
	/app/internal/op/fs.go:578
github.com/alist-org/alist/v3/internal/fs.putDirectly
	/app/internal/fs/put.go:54
github.com/alist-org/alist/v3/internal/fs.PutDirectly
	/app/internal/fs/fs.go:96
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePut
	/app/server/webdav/webdav.go:341
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:65
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:113
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1995
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1598 
[GIN] 2023/11/07 - 19:14:02 | 405 |         5m15s |      172.17.0.1 | PUT      "/dav/quark/NAS_Sync/Photos/2022.6.11#野营@中水湿地公园/DJI_0213.MP4"
[31mERRO[0m[2023-11-07 19:14:10] failed to close file streamer, close /opt/alist/data/temp/file-4238584644: file already closed 
[GIN] 2023/11/07 - 19:14:16 | 201 |  13.20151754s |      172.17.0.1 | PUT      "/dav/quark/HyperBackup/FileSync/Pool/0/0/725.index"
[GIN] 2023/11/07 - 19:14:16 | 207 |     216.671µs |      172.17.0.1 | PROPFIND  "/dav/quark/HyperBackup/FileSync/Pool/0/0/725.index"
[31mERRO[0m[2023-11-07 19:14:16] failed to close file streamer, close /opt/alist/data/temp/file-2758587675: file already closed 
[33mWARN[0m[2023-11-07 19:14:16] failed get /quark/HyperBackup/FileSync/Pool/0/0/727.index: object not found 
[GIN] 2023/11/07 - 19:14:16 | 201 | 10.371500766s |      172.17.0.1 | PUT      "/dav/quark/HyperBackup/FileSync/Pool/0/0/727.index"
[31mERRO[0m[2023-11-07 19:14:16] failed to close file streamer, close /opt/alist/data/temp/file-3315978375: file already closed 
[33mWARN[0m[2023-11-07 19:14:16] failed get /quark/HyperBackup/FileSync/Pool/0/0/726.index: object not found 
[GIN] 2023/11/07 - 19:14:16 | 201 | 11.689826147s |      172.17.0.1 | PUT      "/dav/quark/HyperBackup/FileSync/Pool/0/0/726.index"
[31mERRO[0m[2023-11-07 19:14:16] failed to close file streamer, close /opt/alist/data/temp/file-786159912: file already closed 
[33mWARN[0m[2023-11-07 19:14:16] failed get /quark/HyperBackup/FileSync/Pool/0/0/727.index: object not found 
[33mWARN[0m[2023-11-07 19:14:16] failed get /quark/HyperBackup/FileSync/Pool/0/0/728.index: object not found 
[GIN] 2023/11/07 - 19:14:16 | 201 |  9.011356474s |      172.17.0.1 | PUT      "/dav/quark/HyperBackup/FileSync/Pool/0/0/728.index"
[31mERRO[0m[2023-11-07 19:14:16] PROPFIND /dav/quark/HyperBackup/FileSync/Pool/0/0/727.index object not found
github.com/alist-org/alist/v3/internal/op.Get
	/app/internal/op/fs.go:227
github.com/alist-org/alist/v3/internal/fs.get
	/app/internal/fs/get.go:38
github.com/alist-org/alist/v3/internal/fs.Get
	/app/internal/fs/fs.go:36
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
	/app/server/webdav/webdav.go:612
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:75
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:113
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1995
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1598 
[GIN] 2023/11/07 - 19:14:16 | 404 |     276.524µs |      172.17.0.1 | PROPFIND  "/dav/quark/HyperBackup/FileSync/Pool/0/0/727.index"
[33mWARN[0m[2023-11-07 19:14:16] failed get /quark/HyperBackup/FileSync/Pool/0/0/726.index: object not found 
[31mERRO[0m[2023-11-07 19:14:16] PROPFIND /dav/quark/HyperBackup/FileSync/Pool/0/0/726.index object not found
github.com/alist-org/alist/v3/internal/op.Get
	/app/internal/op/fs.go:227
github.com/alist-org/alist/v3/internal/fs.get
	/app/internal/fs/get.go:38
github.com/alist-org/alist/v3/internal/fs.Get
	/app/internal/fs/fs.go:36
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
	/app/server/webdav/webdav.go:612
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:75
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:113
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1995
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1598 
[GIN] 2023/11/07 - 19:14:16 | 404 |     260.498µs |      172.17.0.1 | PROPFIND  "/dav/quark/HyperBackup/FileSync/Pool/0/0/726.index"
[33mWARN[0m[2023-11-07 19:14:16] failed get /quark/HyperBackup/FileSync/Pool/0/0/728.index: object not found 
[31mERRO[0m[2023-11-07 19:14:16] PROPFIND /dav/quark/HyperBackup/FileSync/Pool/0/0/728.index object not found
github.com/alist-org/alist/v3/internal/op.Get
	/app/internal/op/fs.go:227
github.com/alist-org/alist/v3/internal/fs.get
	/app/internal/fs/get.go:38
github.com/alist-org/alist/v3/internal/fs.Get
	/app/internal/fs/fs.go:36
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
	/app/server/webdav/webdav.go:612
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/app/server/webdav/webdav.go:75
github.com/alist-org/alist/v3/server.ServeWebDAV
	/app/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	/app/server/webdav.go:113
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/lib/go/src/net/http/server.go:2936
net/http.(*conn).serve
	/usr/lib/go/src/net/http/server.go:1995
runtime.goexit

**Comment by tonvoo** [comment]
@xhofe 和哪个issue重复了？没搜到呢？解决了么？

**Comment by xhofe** [comment]
#5403
这是客户端的超时设置，与AList无关。
