### ISSUE TITLE
阿里云open无秒传选项

### ISSUE THREAD

**Issue by dribble-njr** [alist-org/alist#5488]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

阿里云open

### Describe the bug / 问题描述

选择阿里云open

下方无秒传选项

### Reproduction / 复现链接

http://127.0.0.1:5244/@manage/storages/edit/2

### Config / 配置

![image](https://github.com/alist-org/alist/assets/72367140/63ac5290-77e5-47c2-95fe-52d877b2974f)

![image](https://github.com/alist-org/alist/assets/72367140/a08391df-94f0-45ed-b7c8-1166a2525def)

**Comment by anwen-anyi** [comment]
更新AList去 你的都什么版本啦~ :joy_cat:

**Comment by dribble-njr** [comment]
啊，我是最新的版本 3.28.0 呀，但是我的设备是华为 matepad11，用的 termux 安装的，alist server 输出是 3.28.0，和我的环境有关系吗

**Comment by dribble-njr** [comment]
> 更新AList去 你的都什么版本啦~ 😹

啊，我是最新的版本 3.28.0 呀，但是我的设备是华为 matepad11，用的 termux 安装的，alist server 输出是 3.28.0，和我的环境有关系吗
