### ISSUE TITLE
webdav 挂载允许自签名ssl证书

### ISSUE THREAD

**Issue by nick008a** [alist-org/alist#5490]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

webdav 挂载，应该添加一个选项，允许自签名证书。很多用nginx配的webdav没公网，也没ssl证书

**Comment by IAALAI** [comment]
是不是报错证书验证失败，你可以试试看手动信任证书。这样比忽略证书验证更安全

**Comment by IAALAI** [comment]
我都是自己签发一个CA证书，然后给自己的设备的信任证书都加上自己签发的CA证书
