### ISSUE TITLE
TOP.md 无法生效

### ISSUE THREAD

**Issue by baojunz** [alist-org/alist#5494]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.28.0

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

挂载阿里云盘时，在目录中创建 TOP.md 文件，但并没有在顶部说明中显示出来

![image](https://github.com/alist-org/alist/assets/48702961/4efd36ff-5b59-45d5-ad98-c8314be00a17)

<img width="1058" alt="image" src="https://github.com/alist-org/alist/assets/48702961/17c1a07b-8037-4e65-ab63-93a7c4582bad">

### Reproduction / 复现链接

https://pan.buuu.cn/

### Config / 配置

<img width="916" alt="image" src="https://github.com/alist-org/alist/assets/48702961/561310a2-86e9-4087-9da3-adbb1a311a92">

无其他额外配置

**Comment by baojunz** [comment]
![image](https://github.com/alist-org/alist/assets/48702961/c8484b78-ee91-43fc-8adf-158eec7187a0)
底部说明生效，但顶部说明配置无效

**Comment by xhofe** [comment]
此feature还未release。
