### ISSUE TITLE
rclone copy command: Failed to copy: object not found

### ISSUE THREAD

**Issue by qjmiao** [alist-org/alist#5498]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

ALIYUNDRIVEOPEN

### Describe the bug / 问题描述

rclone copy命令使用webdav方式往ALIYUNDRIVEOPEN 目录上传文件

当目录含有大量文件时（比如1000个以上），会报告若干个错误，
《某某文件》: Failed to copy: object not found

对于出错的文件，rclone会重试上传，最终导致这样的现象：
1. 对于出错的文件，阿里云盘的web界面上能看到两个同名的文件，文件大小也一样
2. alist的web界面上是一个文件

如果rclone copy加上参数 --retries 1，报错的文件不会重新上传，现象如下：
1. 报错的文件在云盘web界面上能看到，只有一份
2. alist的web界面上看不到这个文件，如果点击右下角的刷新按钮，就会出现在页面上

### Reproduction / 复现链接

如上

### Config / 配置

n/a

**Comment by qjmiao** [comment]
如果直接用alist的web界面上传同样的目录，再用rclone sync -n对比会发现alist缺少几个文件，但是在云盘web界面能看到这几个缺失的文件

**Comment by takchichan** [comment]
rclone的--transfers指定为1试试。

**Comment by LoadingZhang** [comment]
遇到了同样问题，使用rclone并发往alist上传时，一段时间后会大量出现object not found错误。
--transfers 1单线程不容易出现，但会导致上传比较慢。

**Comment by YeQiuO** [comment]
有大佬知道是什么原因导致的吗，我也遇到了这个问题

**Comment by hale177** [comment]
我也遇到了这个问题, 大量的 这种错误，很愁人 

{"level":"error","event":"PostprocessingFinished","uploadid":"44ffea8f-de4e-4e4c-adb4-076e383dfe89","error":"ERR_UPLOAD_NOT_FOUND: upload not found","time":"2025-06-25T00:31:29+08:00","message":"Failed to get upload"}
