### ISSUE TITLE
允许设置多个管理员

### ISSUE THREAD

**Issue by t4wefan** [alist-org/alist#5511]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

允许设置多个管理员，不只有一个管理员账号

### Suggested solution / 实现思路

添加用户时加一个权限选择 普通用户/游客/管理员

**Comment by lee-cq** [comment]
手动更改数据库用户表的字段可以实现，我忘记了是哪个字段，可以试下。
