### ISSUE TITLE
手机播放视频无法上次进度

### ISSUE THREAD

**Issue by cgwxq** [alist-org/alist#5514]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

视频系位于本机存储，手机播放器无法实现。
使用的浏览器：手机Chrome
下图系电脑截图：
![image](https://github.com/alist-org/alist/assets/72975021/f782a825-319b-4a4c-865c-502dac3d566c)

**Comment by xhofe** [comment]
![Screenshot_2023-11-13-12-18-47-204_com.microsoft.emmx.jpg](https://github.com/alist-org/alist/assets/36558727/988a4d0d-da12-46fd-b224-09dd0b722f50)
