### ISSUE TITLE
播放器不支持 .ts结尾的视频播放

### ISSUE THREAD

**Issue by wpf900** [alist-org/alist#5522]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

ts 应该是m3u8的切片  阿里云是支持播放的 但是挂载后 只能下载 不支持在线播放了

**Comment by xhofe** [comment]
https://alist.nn.ci/config/preview.html#video-types

**Comment by wpf900** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andy ***@***.***&gt;; 
发送时间: 2023年11月14日(星期二) 下午5:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alist-org/alist] 播放器不支持 .ts结尾的视频播放 (Issue #5522)





 
https://alist.nn.ci/config/preview.html#video-types
