### ISSUE TITLE
内置的artplayer无法加载内嵌字幕

### ISSUE THREAD

**Issue by kimycai** [alist-org/alist#5523]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

看到artplayer原生版本是支持加载内嵌字幕的，但不知为何在alist里的artplayer无法识别并加载内嵌字幕，希望以后能有机会支持内嵌字幕的加载和选择。

**Comment by nexmoe** [comment]
https://github.com/zhw2590582/ArtPlayer/issues/582

**Comment by Deepsea-CN** [comment]
同求，有些内嵌字幕无法加载或者加载了默认的轨道却无法选择
