### ISSUE TITLE
建议：播放器可用户切换或者仅服务器控制选择

### ISSUE THREAD

**Issue by 8MiYile** [alist-org/alist#5529]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

因为我那边有人反馈说 文件过大的情况下 网页播放器无法拖动进度条 需要等很久才能拖动
但我知道说这个播放器不是你们开发的
所以我想知道说，会不会引用多个网页播放器
由用户或者站长，选择

版本 3.26.0-iStore商店版

**Comment by xhofe** [comment]
你可以通过https://alist.nn.ci/config/preview.html#iframe-previews 自定义播放器。

**Comment by 8MiYile** [comment]
@xhofe 有什么推荐的播放器调用地址吗
