### ISSUE TITLE
CI: 在release或actions的zip文件名后加上alist的版本或git commit id

### ISSUE THREAD

**Issue by itsHenry35** [alist-org/alist#5530]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题

### Suggested solution / 实现思路

release number可以用${{ github.event.release.tag_name }}
commit id可以用${GITHUB_SHA::7}

**Comment by itsHenry35** [comment]
电脑里都已经alist-windows-amd64_11.zip了，不在文件名上面加个标记有点难轻松地分辨版本

**Comment by xhofe** [comment]
release的话有一些其他的脚本/自动化依赖文件名 所以先不加了
