### ISSUE TITLE
阿里云盘Open驱动没了

### ISSUE THREAD

**Issue by youfly** [alist-org/alist#5535]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

最新版的阿里云盘Open驱动没了吗？

**Comment by anwen-anyi** [comment]
自己检查版本

**Comment by youfly** [comment]
> 检查
从3.28.0试到3.25.1都没有。有什么特别的配置？
