### ISSUE TITLE
文件列表能否支持自定义排序方式

### ISSUE THREAD

**Issue by hqw567** [alist-org/alist#5540]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### 每次切换文件夹时，排序方式都会改为默认的，能否提供设置自定义排序？参考下图
![image](https://github.com/alist-org/alist/assets/74847198/328637ad-a7db-4c77-aa5e-f171e11f37c4)

**Comment by xhofe** [comment]
<img width="1568" alt="image" src="https://github.com/alist-org/alist/assets/36558727/79efde33-3919-4e17-b3e8-3eb19cc7b30c">

**Comment by hqw567** [comment]
> <img alt="图像" width="1568" src="https://user-images.githubusercontent.com/36558727/284063905-79efde33-3919-4e17-b3e8-3eb19cc7b30c.png">

感谢你的回复，我指的是前端页面的排序，用户可以指定排序方式，而不是后台定死这种操作？请问能否实现吗？

**Comment by hqw567** [comment]
@xhofe 我指的是前端页面，设置默认排序方式
