### ISSUE TITLE
能否增加一个不同网盘自动同步功能？

### ISSUE THREAD

**Issue by goldsoft8888** [alist-org/alist#5543]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在的网盘并不可靠，说不定哪天就挂了。从张三网盘到李网盘，进行实时后台同步，张三网盘挂了，还有李四

**Comment by a1768623020** [comment]
我觉得这个功能可以有,本地一份,其他网盘上加密存一份,每次的修改都自动增量同步或者仅上传或双向同步

**Comment by BlueSkyXN** [comment]
Python+Alist API即可

**Comment by mbqw** [comment]
确实很需要这个功能，不同存储间的同步

**Comment by BlueSkyXN** [comment]
> 确实很需要这个功能，不同存储间的同步

很容易导致api爆炸
而且用rclone确实很容易实现
