### ISSUE TITLE
报错提示：Failed find user: record not found，重置了几次密码，都这样。重启ailst能改善，过几天又这样

### ISSUE THREAD

**Issue by Ren9527** [alist-org/alist#5545]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28

### Driver used / 使用的存储驱动

onedrive app

### Describe the bug / 问题描述

Failed find user: record not found

### Reproduction / 复现链接

http://renyi.dynv6.net:5244/@login?redirect=%2F

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "https://cdn1.tianli0.top/npm/alist-web@$version/dist/",
  "jwt_secret": "cLf5fC0pKdCbE6FB",
  "token_expires_in": 24,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data\\data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data\\temp",
  "bleve_dir": "data\\bleve",
  "log": {
    "enable": true,
    "name": "data\\log\\log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 15,
    "compress": true
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true
}

**Comment by iceloon** [comment]
解决了吗 我也遇到了

**Comment by YujioNako** [comment]
个人建议：备份好安装目录下的data文件夹后，卸载alist并重装；之后，更改重新安装的alist文件夹中的data/config.json，将其中所有`data/`更改为你备份好的那个data文件夹。

比如：我把卸载前的data内内容备份到了`/www/data`，那么就在重装后将config中所有`data/`更改为`/www/data/`
