### ISSUE TITLE
有没有可能实现文件变更通知？

### ISSUE THREAD

**Issue by x1ao4** [alist-org/alist#5546]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

挂载盘会定期刷新目录缓存，以实现网盘同步，有没有可能在刷新缓存时对比新旧缓存找到变更的文件，并获取文件目录？然后发出通知，或者保存信息供用户调用？

主要是网盘文件挂载到本地后本地文件系统无法识别到文件变更，在使用一些本地媒体库系统时就无法实现局部扫描，也就是只扫描有变更的文件夹，如果 Alist 支持文件变更通知，那么就可以利用这个通知触发媒体服务器扫描有变更的目录，从而实现局部扫描。

目前的同类产品中似乎 CD2 已经有文件变更通知这个功能了，不知道 Alist 有没有可能实现？

**Comment by x1ao4** [comment]
> @x1ao4 把缓存设置0？

不是刷新频率的问题，目前可以监测文件数量的变更，但是无法获取具体是哪个文件发生了变更，也就是无法获取新增或删除文件的信息，只能知道文件是多了还是少了，想要知道是哪个文件变更了需要定时获取所有文件的目录，然后进行对比，才能知道变化的文件是什么，而 Alist 每次刷新目录的时候理论上是可以保存一份目录在本地的，这样下一次刷新的时候就可以进行对比，就可以定位变更文件的位置，并获取信息。

在 Alist 不支持的情况下，我们需要在网盘自动定时刷新缓存之外额外的定时再获取目录，并进行定时对比，才能获取到变更文件的信息，网络请求有点多。

**Comment by x1ao4** [comment]
> @x1ao4 这个调用api自己写脚本呗

是可以写啊，写了，但是这样等于自己有多余的请求，明明网盘每次刷新的时候就可以下载每次目录并进行对比，然后保存变更文件信息，Alist 自己就可以做到，现在我们得自己做额外的请求，去获取目录，如果文件多，请求也会比较多，Alist 自己能去作对比是最好。

**Comment by BlueSkyXN** [comment]
Python+Alist API即可

**Comment by x1ao4** [comment]
> Python+Alist API即可 Rclone sync也可以

Alist API 和 Rclone Sync 能获取变更文件的文件夹目录信息？

**Comment by x1ao4** [comment]
> > Python+Alist API即可 Rclone sync也可以
> 
> Alist API 和 Rclone Sync 能获取变更文件的文件夹目录信息？在 Alist API 和 Rclone 的文档里没有看到相关说明，我能获取到数量的变化，但是不能直接获取到变更文件的具体数据。

测试使用 rclone lsf --files-only -R 可以列出监控文件夹的所有文件目录列表，通过定时获取目录和对比目录，可以筛选出变更文件的目录信息，少量监控可以用这个方式，如果文件数量较多或者保险起见，可以尝试增加请求间隔，避免过多连续请求。

之前误会了 Alist 和 Rclone 的请求方式，原本以为他们会自动定时请求，结果是有访问/读取才会有请求，所以平时没有读取动作的时候 Alist 和 Rclone 其实都没有任何请求，所以他们并没有文件的数据。

但我不太希望通过对比目录的方式获取变更信息，因为请求太多了，还是准备找别的思路。
