### ISSUE TITLE
发现一个惊天漏洞！python无需密码即可访问alist所有文件

### ISSUE THREAD

**Issue by tmqxiujin** [alist-org/alist#5561]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

使用以下python代码无需密码即可任意访问我alist中的文件，只需把链接添加进去即可
from urllib.request import urlopen
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
u = urlopen('file-address')
data = u.read().decode('utf-8')
print(data)
![截图_选择区域_20231123224843](https://github.com/alist-org/alist/assets/30311591/a59bf5ba-116d-448a-b651-e6041f2826cf)

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by tmqxiujin** [comment]
我测试的是代码和txt文件都可以直接输出里边的内容，其他的没测试，但应该都是一样的，到底咋回事，挺崩溃的，不行只能弃坑了

**Comment by tmqxiujin** [comment]
而且我在三台电脑上测试都可以无密码访问alist内的代码文件，包括一台从来没登录过的。。。。

**Comment by tmqxiujin** [comment]
有没有人解释一下。。。。。

**Comment by anwen-anyi** [comment]
你不添加密码 别人是可以正常访问的，你把全部签名开启 或者元信息加密 会携带 `sign` 参数就不能随意访问了

**Comment by ceozero** [comment]
噗，以后默认安装设置为全签名吧，不然容易造成人为重大bug。。。

**Comment by tmqxiujin** [comment]
原来如此，抱歉。。
