### ISSUE TITLE
更新索引无效 

### ISSUE THREAD

**Issue by Ausli** [alist-org/alist#5564]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

onedriver

### Describe the bug / 问题描述

启用了自动更新索引，删除文件后文件依然在索引中，没有生效，点入链接显示 object not found 

### Reproduction / 复现链接

url: https://file.richsnow.top/
user: test
password: test123456
权限：删除 上传

### Config / 配置

![屏幕截图 2023-11-24 213513](https://github.com/alist-org/alist/assets/70201547/082bc3a4-0011-4cb4-97a9-964129386fe6)

### Logs / 日志

![屏幕截图 2023-11-24 213427](https://github.com/alist-org/alist/assets/70201547/8d0d372b-cd24-49d0-8e0e-7a28b01aaeb7)
![屏幕截图 2023-11-24 213352](https://github.com/alist-org/alist/assets/70201547/cea1b3b8-215c-4259-beba-cab1f325364c)
![image](https://github.com/alist-org/alist/assets/70201547/390bda94-b4a9-44af-8436-9003592d26e9)

**Comment by Ausli** [comment]
文件删除后，索引不更新，这应该是一个bug

**Comment by anwen-anyi** [comment]
这个自动更新索引是指的 文件有新增进行数据索引，但是数据已经写到数据库了，应该没考虑删除自动删除无效索引，那得实时监测列表变化吧，毕竟只是一个列表程序，不是专业的网盘程序，不好搞。我也只是一个用户，当时添加索引时候已经很难搞了 理解开发者。

例如我原本添加了 /a/b.txt 文件，我在网盘中把它删除了，再加上AList有列表缓存不是实时刷新的，就算刷新了也无法感知，只能重新索引全部的才能知道哪里少了，这样索引全部的和手动全部索引没区别了

以上是我个人使用的理解，所以这个不好处理。

**Comment by Ausli** [comment]
@anwen-anyi 这个应该不难，我只需要修改后更新即可不需要实时监测列表变化，因为我的所有操作都是在alist中完成的，只需要修改命名，删除文件修改索引即可，索引做到了文件上传添加到了索引，但删除文件后还在，这个应该就属于漏洞了。而且它这个索引感觉就有问题，更新填了路径值/a索引点了，索引直接失效了，只能重构索引。

**Comment by anwen-anyi** [comment]
> @anwen-anyi 这个应该不难，我只需要修改后更新即可不需要实时监测列表变化，因为我的所有操作都是在alist中完成的，只需要修改命名，删除文件修改索引即可，索引做到了文件上传添加到了索引，但删除文件后还在，这个应该就属于漏洞了。而且它这个索引感觉就有问题，更新填了路径值/a索引点了，索引直接失效了，只能重构索引。

:cat: 需求一句话 技术敲烂手） 是bug没错，但是应该不好搞。

**Comment by IAALAI** [comment]
> @anwen-anyi 这个应该不难，我只需要修改后更新即可不需要实时监测列表变化，因为我的所有操作都是在alist中完成的，只需要修改命名，删除文件修改索引即可，索引做到了文件上传添加到了索引，但删除文件后还在，这个应该就属于漏洞了。而且它这个索引感觉就有问题，更新填了路径值/a索引点了，索引直接失效了，只能重构索引。

确实，调API删文件的时候，后端就可以操作索引了
