### ISSUE TITLE
复制多个文件时才会触发的bug。

### ISSUE THREAD

**Issue by j2rong4cn** [alist-org/alist#5565]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.0

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

在网页执行复制操作时，复制多个文件时才会触发的bug。
例如：
复制10个文件，只会完成5个文件，其他的全在等待，取消也一直显示正在取消。
我试了从 本地驱动 到 阿里云盘Open、中国移动云盘，阿里云盘Open 到 中国移动云盘 都是这样

### Reproduction / 复现链接

无

### Config / 配置
```json
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "1234567890",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": false,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}
```
### Logs / 日志

没报错

**Comment by woshichenghaibo** [comment]
我也遇到了这个问题嗯，不过这个问题影响不大嗯，它会一直显示正在取消，等你下次重启服务器的时候嗯，或者是等你把刀客重新启动一下的时候，这个正在取消这一行就会消失

**Comment by vvvaye** [comment]
我也遇到这个问题，请问如何解决啊？是昨晚更新了3.29之后出现的！

**Comment by vvvaye** [comment]
到底有没有人处理啊？

**Comment by vvvaye** [comment]
回复一下也行啊！

**Comment by kiki-theone** [comment]
同样遇到这个问题了

**Comment by qianbo-x** [comment]
为什么把那个骂人的删了，特意前来观光。

**Comment by qwqawawow** [comment]
> 为什么把那个骂人的删了，特意前来观光。

你想刷notice是吧

**Comment by YueDeYue** [comment]
QQ空间观光团，特意前来观光。

**Comment by j2rong4cn** [comment]
> QQ空间观光团，特意前来观光。

什么情况，这个issues关闭之后收到邮件没看就被我删了，错过了什么

**Comment by WYC-2020** [comment]
> 为什么把那个骂人的删了，特意前来观光。

我也是特意来观看的 结果没了，我有一张超长截图，本来还说来看原文的

**Comment by j2rong4cn** [comment]
> > 为什么把那个骂人的删了，特意前来观光。
> 
> 我也是特意来观看的 结果没了，我有一张超长截图，本来还说来看原文的

ta被封号了，所以issues没了

**Comment by WYC-2020** [comment]
> > > 为什么把那个骂人的删了，特意前来观光。
> > 
> > 
> > 我也是特意来观看的 结果没了，我有一张超长截图，本来还说来看原文的
> 
> ta被封号了，所以issues没了

哈哈 看图片都过瘾
