### ISSUE TITLE
希望增加指定路径的图片视图的默认显示

### ISSUE THREAD

**Issue by maxadc** [alist-org/alist#5570]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

用户故事：alist是一款优秀的程序，我alist用来做了一个简单的个人资源中心。alist可以展示我的文件资源，甚至是md文件，可以自由发挥。也可以展示图片，但展示图片时，需要用户自己点击，然而，不太可能告诉访问者去切换。我希望，在打开指定路径时，可以自动采用对应的视图模式。比如，打开A图片文件时，图片视图，打开B文件夹时，列表视图。

### Suggested solution / 实现思路

我看了看alist 的功能，我建议是否可以在元信息功能上增加此功能！
感谢！

**Comment by wanyuxi88** [comment]
复议
