### ISSUE TITLE
多文件复制BUG！不要删帖！！！！！！！！！！！

### ISSUE THREAD

**Issue by vvvaye** [alist-org/alist#5571]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.29

### Driver used / 使用的存储驱动

全部

### Describe the bug / 问题描述

昨天群晖更新alist3.29.0之后，多文件复制时候出现bug，只复制4个文件之后就不再继续进行了，全部都是“等待中”。
请不要删帖！先给个解释好不好？？？？自己的东西做不好，别人提出BUG，一句话都不回复就直接删帖？有没有你们这样的？？？？？？？逼着我们放弃alist是么？？？

### Reproduction / 复现链接

昨天群晖更新alist3.29.0之后，多文件复制时候出现bug，只复制4个文件之后就不再继续进行了，全部都是“等待中”。
请不要删帖！先给个解释好不好？？？？自己的东西做不好，别人提出BUG，一句话都不回复就直接删帖？有没有你们这样的？？？？？？？逼着我们放弃alist是么？？？

### Config / 配置

昨天群晖更新alist3.29.0之后，多文件复制时候出现bug，只复制4个文件之后就不再继续进行了，全部都是“等待中”。
请不要删帖！先给个解释好不好？？？？自己的东西做不好，别人提出BUG，一句话都不回复就直接删帖？有没有你们这样的？？？？？？？逼着我们放弃alist是么？？？

### Logs / 日志

昨天群晖更新alist3.29.0之后，多文件复制时候出现bug，只复制4个文件之后就不再继续进行了，全部都是“等待中”。
请不要删帖！先给个解释好不好？？？？自己的东西做不好，别人提出BUG，一句话都不回复就直接删帖？有没有你们这样的？？？？？？？逼着我们放弃alist是么？？？

**Comment by vvvaye** [comment]
我是用了你们的程序前来寻求帮助的！！！请不要删帖了事。请给个解释。

**Comment by xhofe** [comment]
请不要提重复的issue，具体情况请查看首条issue的timeline。

**Comment by BlueSkyXN** [comment]
你倒是给钱啊，先投资500USD先

**Comment by anwen-anyi** [comment]
你瞎吗？自己不会看 commit吗？不会看issue记录吗？
欠你的？而且你自己在上一个问了 处理没处理你不知道吗？
惯你臭毛病 什么玩意

**Comment by vvvaye** [comment]
> 你瞎吗？自己不会看 commit吗？不会看issue记录吗？ 欠你的？而且你自己在上一个问了 处理没处理你不知道吗？ 惯你臭毛病 什么玩意

呦呦呦您不瞎，您告诉我上一个issue在哪呢？？？处理了么？处理结果在哪呢？你给我找出来！动不动就满嘴喷粪，谁给你惯的啊！你自己是什么玩意儿？？？

**Comment by vvvaye** [comment]
> 请不要提重复的issue，具体情况请查看首条issue的timeline。

你说的issue在哪呢？你找出来！

**Comment by vvvaye** [comment]
> 你瞎吗？自己不会看 commit吗？不会看issue记录吗？ 欠你的？而且你自己在上一个问了 处理没处理你不知道吗？ 惯你臭毛病 什么玩意

你不瞎，你会看时间线是吧？你自己去看看我什么时候发的贴子，第一个issue是不是我发的，他们有什么什么时候处理的commit，你TM全都看清楚了再来放屁！

**Comment by vvvaye** [comment]
妈的发个求助的帖子不是被删就是挨骂。更过分的是被删之后还TM挨骂。这是什么傻逼平台！！！！！！！！

**Comment by vvvaye** [comment]
我们用户不反应问题你们能知道有bug啊？谁TM给你们的勇气这么骂人的？你们做了软件就是爹啊？我们不花钱用你的软件就TM得下跪啊？都他妈一群哪儿来的臭傻逼！

**Comment by vvvaye** [comment]
做个傻逼软件出了BUG还得翻墙来留言，留言了还被删，被删了还TM挨骂，谁给你们的勇气啊？一个他妈的反馈平台而已，用百度贴吧不行么？都他妈说中文的，整个英文平台干你妈逼啊？还特么的issue，还特么commit，装特么什么高大上啊？发的特么的一堆代码，英文，给谁看呢？我就想知道这个bug是我的问题还是你的问题，应该怎么处理，什么时候处理，妈的一句中国话不会说是吧？上来就他妈的删帖，整个什么他妈的commit？？又不是我发的主贴我上哪去看你的commit？？？我看不见commit发个贴就挨骂？？？？？都他妈什么爹妈教育出来的畜生啊？？？就算我看见了你那commit又咋的？有一句中文告诉我这个bug咋处理么？有一个人正经回复我到底是咋回事么？你们这帮畜生除了骂人有没有真正帮助过谁？麻痹的一群臭傻逼！

**Comment by anwen-anyi** [comment]
欠你的？你爱用不用 逼着你用了？  这不是你是谁
![image](https://github.com/alist-org/alist/assets/56105412/2f7cd568-f449-4e80-a17b-a9bc16bfdfd4)

**Comment by vvvaye** [comment]
> 欠你的？你爱用不用 逼着你用了？ 这不是你是谁 ![image](https://private-user-images.githubusercontent.com/56105412/285647165-2f7cd568-f449-4e80-a17b-a9bc16bfdfd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTgzNTMsIm5iZiI6MTcwMDk5ODA1MywicGF0aCI6Ii81NjEwNTQxMi8yODU2NDcxNjUtMmY3Y2Q1NjgtZjQ0OS00ZTgwLWExN2ItYTliYzE2YmZkZmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZWMxMmU0YmQ2MmI3NTVhYzIyNDQ3YjliOGFiYjkyZmMzMmIwODFmYTE5NjlhMzIxNzEzOGUwYjM1NjY5ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DZdLhk-DXuI7X6el6sy3f-M7hTjyopWjCoNfrnPenSI)

你TM也看见了我是什么时候留言的对吧？？？你看见了是不是commit在后面？？？你是不是也看见了那个issue已经关闭了我上哪看去？

**Comment by vvvaye** [comment]
> 你倒是给钱啊，先投资500USD先

你他妈的又是哪位？这么傻逼的软件改成收费啊！你他妈的看看还谁用！
我是来求助的，你帮不上忙就滚到一边去，臭傻逼！

**Comment by vvvaye** [comment]
> 欠你的？你爱用不用 逼着你用了？ 这不是你是谁 有问题就好好说话 嘴那么欠 不惯着你 ![image](https://private-user-images.githubusercontent.com/56105412/285647165-2f7cd568-f449-4e80-a17b-a9bc16bfdfd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTg0ODgsIm5iZiI6MTcwMDk5ODE4OCwicGF0aCI6Ii81NjEwNTQxMi8yODU2NDcxNjUtMmY3Y2Q1NjgtZjQ0OS00ZTgwLWExN2ItYTliYzE2YmZkZmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NGQ3MTdhNzZjNGUwOTBhZDkxOTcyZjc4MDY3NzEzMWQzMDk3ZjZlODJlYzNkYTJhODAyYzZkMTEwNzlkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QNNx4-nDDWsUa4toJdMNVEg29jPbknC2_f2GQWL0CTw)

你这个臭傻逼典型的就是来找骂的对吧？第一个issue不是我发的，我只是回帖，但是没人理所以我发了第二个，被删了，然后我发了第三个，被删了。这和你有鸡毛关系？你他妈的蹦出来干你妈逼？你就说你是不是找骂的？臭傻逼！

**Comment by anwen-anyi** [comment]
你都留言了 等着回复就是了   还开个帖子 不知道是一个问题？都处理了你还问问问... 欠你的啊，有问题好好说 嘴欠 谁惯着你  傻鸟一样

![image](https://github.com/alist-org/alist/assets/56105412/2b23acea-dbf0-454e-a994-f27abbe55415)

**Comment by vvvaye** [comment]
> 你都留言了 等着回复就是了 还开个帖子 不知道是一个问题？都处理了你还问问问... 欠你的啊，有问题好好说 嘴欠 谁惯着你 傻鸟一样
> 
> ![image](https://private-user-images.githubusercontent.com/56105412/285647348-2b23acea-dbf0-454e-a994-f27abbe55415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTg2MTMsIm5iZiI6MTcwMDk5ODMxMywicGF0aCI6Ii81NjEwNTQxMi8yODU2NDczNDgtMmIyM2FjZWEtZGJmMC00NTRlLWE5OTQtZjI3YWJiZTU1NDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0Njg1ZjkzOWQxMzU3YjM0ZDBhZGE4NmQzNGVjOTZkZTQxODE0ZDc2ODE2N2JjM2RmZTIwZDVhMWY2NTEyOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qLBmP3yyWHfqtOfvNKcCqtLf-7P50GUoYlBQLEUPJ8)

你知道我等了多久么你就瞎几把发言？你算哪儿根葱啊？

**Comment by vvvaye** [comment]
> > 你都留言了 等着回复就是了 还开个帖子 不知道是一个问题？都处理了你还问问问... 欠你的啊，有问题好好说 嘴欠 谁惯着你 傻鸟一样
> > ![image](https://private-user-images.githubusercontent.com/56105412/285647348-2b23acea-dbf0-454e-a994-f27abbe55415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTg2MTMsIm5iZiI6MTcwMDk5ODMxMywicGF0aCI6Ii81NjEwNTQxMi8yODU2NDczNDgtMmIyM2FjZWEtZGJmMC00NTRlLWE5OTQtZjI3YWJiZTU1NDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0Njg1ZjkzOWQxMzU3YjM0ZDBhZGE4NmQzNGVjOTZkZTQxODE0ZDc2ODE2N2JjM2RmZTIwZDVhMWY2NTEyOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qLBmP3yyWHfqtOfvNKcCqtLf-7P50GUoYlBQLEUPJ8)
> 
> 你知道我等了多久么你就瞎几把发言？你算哪儿根葱啊？

![1111](https://github.com/alist-org/alist/assets/142859985/fb1ba720-75e1-4464-af67-d04f7af7ba9e)
你到底是懂不懂啊？默认打开根本看不见已关闭的issue，你可闭嘴吧，别他妈在这丢人了好么？

**Comment by anwen-anyi** [comment]
傻鸟一样不会用怪平台，赶紧run吧 别丢人了。

**Comment by vvvaye** [comment]
> > 你都留言了 等着回复就是了 还开个帖子 不知道是一个问题？都处理了你还问问问... 欠你的啊，有问题好好说 嘴欠 谁惯着你 傻鸟一样
> > ![image](https://private-user-images.githubusercontent.com/56105412/285647348-2b23acea-dbf0-454e-a994-f27abbe55415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTg2MTMsIm5iZiI6MTcwMDk5ODMxMywicGF0aCI6Ii81NjEwNTQxMi8yODU2NDczNDgtMmIyM2FjZWEtZGJmMC00NTRlLWE5OTQtZjI3YWJiZTU1NDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0Njg1ZjkzOWQxMzU3YjM0ZDBhZGE4NmQzNGVjOTZkZTQxODE0ZDc2ODE2N2JjM2RmZTIwZDVhMWY2NTEyOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qLBmP3yyWHfqtOfvNKcCqtLf-7P50GUoYlBQLEUPJ8)
> 
> 你知道我等了多久么你就瞎几把发言？你算哪儿根葱啊？

草泥马的我都说过好几遍了我等了很久没人处理才发的贴子！你他妈有病是吧？你没事闲的了是吧？回家喝奶去行么？

**Comment by vvvaye** [comment]
> 傻鸟一样不会用怪平台，赶紧run吧 别丢人了。

就你会用是吧？你牛逼，你真tm牛逼！臭傻逼

**Comment by xhofe** [comment]
1. 首先我并没有删帖，GitHub中也没有删帖的说法，你提的两个issue都与这个issue #5565 重复了，issue模版中也标记了请不要提重复的issue，所以你的issue被标记为了duplicate并被自动关闭
2. #5565 这条issue我看到了就已经在处理了 但是一般我都是处理后直接在commit message中直接关闭而不会去特意回复，这也是开源社区中很常见的做法，看到你在那条issue下的评论 我之后马上就assign给了自己并加了working的标签作为回应， 此bug主要由另一个库相关，处理在这里：https://github.com/xhofe/tache/commit/61686b5d625788ad0665175d11e646838735e5e8 ，但是由于gomod有一些缓存，所以此仓库的提交会迟一些，提交后有关联的事件可以在时间线中看到：
<img width="979" alt="image" src="https://github.com/alist-org/alist/assets/36558727/f919742f-3827-4551-b33b-8a2b4c6ff5ce">
3. #5571 这个issue关闭也是被修复之后关闭的，你可以看到他是在这个提交中被关闭的： 68af284dad2ba332e3b91e64a422f9103dec603a 

4. 这是一个开源项目，所以不会保证SLA。

**Comment by vvvaye** [comment]
> 1. 首先我并没有删帖，GitHub中也没有删帖的说法，你提的两个issue都与这个issue [复制多个文件时才会触发的bug。 #5565](https://github.com/alist-org/alist/issues/5565) 重复了，issue模版中也标记了请不要提重复的issue，所以你的issue被标记为了duplicate并被自动关闭
> 2. [复制多个文件时才会触发的bug。 #5565](https://github.com/alist-org/alist/issues/5565) 这条issue我看到了就已经在处理了 但是一般我都是处理后直接在commit message中直接关闭而不会去特意回复，这也是开源社区中很常见的做法，看到你在那条issue下的评论 我之后马上就assign给了自己并加了working的标签作为回应， 此bug主要由另一个库相关，处理在这里：[xhofe/tache@61686b5](https://github.com/xhofe/tache/commit/61686b5d625788ad0665175d11e646838735e5e8) ，但是由于gomod有一些缓存，所以此仓库的提交会迟一些，提交后有关联的事件可以在时间线中看到：
> 
> <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/36558727/285647279-f919742f-3827-4551-b33b-8a2b4c6ff5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTg5MjksIm5iZiI6MTcwMDk5ODYyOSwicGF0aCI6Ii8zNjU1ODcyNy8yODU2NDcyNzktZjkxOTc0MmYtMzgyNy00NTUxLWIzM2ItOGEyYjRjNmZmNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwODYwMzQ4Yjk2ZjAwMGZjOGRiODAzZTNhMDQxMmY5NDliYTBjMTEwNzczOTNjNjQ4ZDdiMmRlMWUyMWUzNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gk3xY61vG48l5Wd2xdt9r7-lVOMhsU9u4OTPI8avVYE"> 3. #5571 这个issue关闭也是被修复之后关闭的，你可以看到他是在这个提交中被关闭的： [68af284](https://github.com/alist-org/alist/commit/68af284dad2ba332e3b91e64a422f9103dec603a)
> 4. 这是一个开源项目，所以不会保证SLA。

是啊，开源的，所以那些疯狗上来就骂人也是开源特色。真TM牛逼！

**Comment by vvvaye** [comment]
> 1. 首先我并没有删帖，GitHub中也没有删帖的说法，你提的两个issue都与这个issue [复制多个文件时才会触发的bug。 #5565](https://github.com/alist-org/alist/issues/5565) 重复了，issue模版中也标记了请不要提重复的issue，所以你的issue被标记为了duplicate并被自动关闭
> 2. [复制多个文件时才会触发的bug。 #5565](https://github.com/alist-org/alist/issues/5565) 这条issue我看到了就已经在处理了 但是一般我都是处理后直接在commit message中直接关闭而不会去特意回复，这也是开源社区中很常见的做法，看到你在那条issue下的评论 我之后马上就assign给了自己并加了working的标签作为回应， 此bug主要由另一个库相关，处理在这里：[xhofe/tache@61686b5](https://github.com/xhofe/tache/commit/61686b5d625788ad0665175d11e646838735e5e8) ，但是由于gomod有一些缓存，所以此仓库的提交会迟一些，提交后有关联的事件可以在时间线中看到：
> 
> <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/36558727/285647279-f919742f-3827-4551-b33b-8a2b4c6ff5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTg5MjksIm5iZiI6MTcwMDk5ODYyOSwicGF0aCI6Ii8zNjU1ODcyNy8yODU2NDcyNzktZjkxOTc0MmYtMzgyNy00NTUxLWIzM2ItOGEyYjRjNmZmNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExMzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwODYwMzQ4Yjk2ZjAwMGZjOGRiODAzZTNhMDQxMmY5NDliYTBjMTEwNzczOTNjNjQ4ZDdiMmRlMWUyMWUzNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gk3xY61vG48l5Wd2xdt9r7-lVOMhsU9u4OTPI8avVYE"> 3. #5571 这个issue关闭也是被修复之后关闭的，你可以看到他是在这个提交中被关闭的： [68af284](https://github.com/alist-org/alist/commit/68af284dad2ba332e3b91e64a422f9103dec603a)
> 4. 这是一个开源项目，所以不会保证SLA。

我就问你一句，你的东西是开源的不假，但是不是给大众用户使用的？我看不懂代码可以么？我看不懂英文可以么？我不会翻墙有可能吧？我也是第一次来这个鸡巴平台反馈可以吧？你回头看看你那些什么commit，什么issue，有一句中文么？有没有人用中国话告诉我到底这个bug是怎么回事？我急需用nas传输大量文件就因为生了个级两天耽误了还降不回去，我来问问就挨骂是吧？

**Comment by vvvaye** [comment]
> 1. 首先我并没有删帖，GitHub中也没有删帖的说法，你提的两个issue都与这个issue [复制多个文件时才会触发的bug。 #5565](https://github.com/alist-org/alist/issues/5565) 重复了，issue模版中也标记了请不要提重复的issue，所以你的issue被标记为了duplicate并被自动关闭
> 2. [复制多个文件时才会触发的bug。 #5565](https://github.com/alist-org/alist/issues/5565) 这条issue我看到了就已经在处理了 但是一般我都是处理后直接在commit message中直接关闭而不会去特意回复，这也是开源社区中很常见的做法，看到你在那条issue下的评论 我之后马上就assign给了自己并加了working的标签作为回应， 此bug主要由另一个库相关，处理在这里：[xhofe/tache@61686b5](https://github.com/xhofe/tache/commit/61686b5d625788ad0665175d11e646838735e5e8) ，但是由于gomod有一些缓存，所以此仓库的提交会迟一些，提交后有关联的事件可以在时间线中看到：
> 
> <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/36558727/285647279-f919742f-3827-4551-b33b-8a2b4c6ff5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTkxMzAsIm5iZiI6MTcwMDk5ODgzMCwicGF0aCI6Ii8zNjU1ODcyNy8yODU2NDcyNzktZjkxOTc0MmYtMzgyNy00NTUxLWIzM2ItOGEyYjRjNmZmNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDExNDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YTIyZGQ5ZWFkOGI4YzE3MjIzNGI0YmY0MDdkNjgyMWYzZTRmNDI0MmQ4MjZiMTdmMjVmYWRiOGJjM2NmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NNOm1W0Bo7zuSsmU9DedzgMnP3TqEYqRbbgWUxolWBQ"> 3. #5571 这个issue关闭也是被修复之后关闭的，你可以看到他是在这个提交中被关闭的： [68af284](https://github.com/alist-org/alist/commit/68af284dad2ba332e3b91e64a422f9103dec603a)
> 4. 这是一个开源项目，所以不会保证SLA。

我是不是简简单单的一个需求就是“有人回复一些也行啊”对吧？可是你们到现在也没回复我吧？整一堆时间线，给谁看呢？我是用户，我不是开发者，我看不懂！！！！我就需要一句中国话的回复，有么？有么？有么？妈的骂人的时候你们倒是用中文了，咋的，英文瘸腿了是么？不会用英文骂人是么?

**Comment by vvvaye** [comment]
来，用英文骂我。求你了。

**Comment by vvvaye** [comment]
一帮中国人装鸡毛洋鬼子。傻逼。

**Comment by vvvaye** [comment]
大周末的上个网被气个半死，就你们这个逼样的啥TM也别开发了。脱离群众自己玩去吧。

**Comment by xhofe** [comment]
我只能说 如果你不接受我们的契约行为准则，可以选择不使用此项目。

**Comment by BlueSkyXN** [comment]
> > 你倒是给钱啊，先投资500USD先
> 
> 你他妈的又是哪位？这么傻逼的软件改成收费啊！你他妈的看看还谁用！ 我是来求助的，你帮不上忙就滚到一边去，臭傻逼！

穷逼不要狗叫了，没钱合规自己用没人管你，当你想出来狗叫的时候先看看自己有没有Money，没钱玩你马币

**Comment by BlueSkyXN** [comment]
> > 你瞎吗？自己不会看 commit吗？不会看issue记录吗？ 欠你的？而且你自己在上一个问了 处理没处理你不知道吗？ 惯你臭毛病 什么玩意
> 
> 呦呦呦您不瞎，您告诉我上一个issue在哪呢？？？处理了么？处理结果在哪呢？你给我找出来！动不动就满嘴喷粪，谁给你惯的啊！你自己是什么玩意儿？？？

复制多个文件时才会触发的bug https://github.com/alist-org/alist/issues/5565
昨天群晖更新alist3.29.0之后，多文件复制时候出现bug，只复制4个文件之后就不再继续进行了，全部都是“等待中”。请问怎么处理啊？  https://github.com/alist-org/alist/issues/5569

针对5565的bug的修复 https://github.com/alist-org/alist/commit/68af284
修复后的新版本 https://github.com/alist-org/alist/releases/tag/v3.29.1

臭傻逼，眼睛瞎了就别玩，脑子坏了就早点重开，狗叫你马儿都没了

**Comment by t-satoru** [comment]
自己满嘴喷粪还说别人骂人，真是乌鸦说猪黑自己不知道自己黑，哈哈

**Comment by LXY1226** [comment]
哈哈别人怎么不提，怎么就你有问题，菜就多练(手动狗头

**Comment by Mrs4s** [comment]
牛逼 我本以为我见过够多极品了 没想到还有更厉害的

**Comment by gdrfgdrf** [comment]
见证生物多样性

**Comment by shugen002** [comment]
麻烦来个管理锁定一下帖子，谢谢。 @xhofe
