### ISSUE TITLE
oauth链接代理

### ISSUE THREAD

**Issue by Donkeyes** [alist-org/alist#5573]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://api-cf.nn.ci/，这个地址应该被墙了。无法验证token。

### Suggested solution / 实现思路

建议可以设置网络代理，支持sock5的

**Comment by xhofe** [comment]
[how to set socks5 proxy in terminal](https://www.google.com/search?q=how+to+set+socks5+proxy+in+terminal)
