### ISSUE TITLE
采用阿里云盘挂载，播放视频一直加载

### ISSUE THREAD

**Issue by Marchen-zcl** [alist-org/alist#5574]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

阿里云盘OPEN

### Describe the bug / 问题描述

每次播放阿里云盘的视频每隔二十分钟就会进入加载一直加载不了，只能刷新网页才能继续加载

### Reproduction / 复现链接

url: http://47.113.184.19:5244/
user: test
password: 123456

### Config / 配置

![QQ截图20231126003644](https://github.com/alist-org/alist/assets/32994063/a41d9ebe-a753-4dfa-abc7-faa6369c7866)

**Comment by anwen-anyi** [comment]
目前已知bug,等周一上班问问什么情况。

**Comment by CardiacCycle** [comment]
同样出现此问题

**Comment by ashuang001** [comment]
同样的问题。

**Comment by jorry49** [comment]
同样出现此问题，现在我的是一打开播放就是一帧一帧的播放，在此之前都是看15-20分钟我的播放器会卡死，然后需要关闭播放器，重新打开该视频文件就打不开了。我用的播放器是PotPlayer 64 bit，使用阿里云盘open进行挂载

**Comment by Mysaku** [comment]
> 同样出现此问题，现在我的是一打开播放就是一帧一帧的播放，在此之前都是看15-20分钟我的播放器会卡死，然后需要关闭播放器，重新打开该视频文件就打不开了。我用的播放器是PotPlayer 64 bit，使用阿里云盘open进行挂载

我也是，好像跟最近阿里云开始修改api有关

**Comment by JianJia2018** [comment]
同样出现, 使用第三方挂载webdav现在限速500K/s. 网页版流畅播放

**Comment by Lll05** [comment]
我也potplayer限速500k 网页aliyun video正常

**Comment by weilandehai** [comment]
相同的问题，webdav挂载正常，alist一直缓冲😭

**Comment by NongFu3Q** [comment]
同样出现, 使用第三方挂载webdav现在限速500K/s. 网页版流畅播放

**Comment by shenzihang** [comment]
> 同样出现， 使用第三方挂载webdav现在限速500K/s. 网页版流畅播放

确实是一样的问题，通过第三方webdav挂载就会限速，导致大一点的视频就会播放卡顿，但是用网页播放是流畅的

**Comment by limu96966** [comment]
> > 同样出现，使用第三方挂载webdav现在限速500K/s。网页版流畅播放
> 
> 确实是一样的问题，通过第三方webdav挂载就会限速，导致一大点的视频就会播放卡顿，但是用网页播放是流畅的

网页版似乎是直接播放的m3u8,第三方获取的好像是直链，直链就会限速，我这里最高速度512K/s

**Comment by jorry49** [comment]
> 同样问题，potplayer限速500k，网页aliyun video正常，期待解决，谢谢

我发现也不是potplayer限速500k，给我感觉是alist与阿里云盘通信的速度被限制到500k，昨天我做了个上传测试，18mb的文件上传到映射出来的盘上，一直是100k-200k左右的速度上传了5分钟左右吧。

**Comment by shenzihang** [comment]
> > > 同样出现，使用第三方挂载webdav现在限速500K/s。网页版流畅播放
> > 
> > 
> > 确实是一样的问题，通过第三方webdav挂载就会限速，导致一大点的视频就会播放卡顿，但是用网页播放是流畅的
> 
> 网页版似乎是直接播放的m3u8, 第三方获取的好像是直链，直链就会限速，我这里最高速度512K/s



> > 同样问题，potplayer限速500k，网页aliyun video正常，期待解决，谢谢
> 
> 我发现也不是potplayer限速500k，给我感觉是alist与阿里云盘通信的速度被限制到500k，昨天我做了个上传测试，18mb的文件上传到映射出来的盘上，一直是100k-200k左右的速度上传了5分钟左右吧。

代理走的是302重定向，应该就是阿里这边玩不起了，，
