### ISSUE TITLE
waf反代后链接不正确

### ISSUE THREAD

**Issue by Omoinemie** [alist-org/alist#5575]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

用safeline waf反代，site_url源地址：http://rt.vomiku.com:1234，前端地址：http://yun.vomiku.com
下载文件时，下载按钮的地址是正确的，但是复制链接按钮地址不正确，不能跳转到site_url，依然是http://yun.****.com，导致下载文件流量通过WAF中转。

### Reproduction / 复现链接

http://yun.vomiku.com/%E8%BD%AF%E4%BB%B6%E5%AE%89%E8%A3%85%E5%8C%85/Mac/NTFS%20X-1.0.3.dmg

### Config / 配置

  "site_url": "http://rt.vomiku.com:1234",

**Comment by xhofe** [comment]
后台管理-设置-全局-自定义内容添加：
```js
<script>
window.ALIST.api = "http://rt.vomiku.com:1234"
</script>
```
