### ISSUE TITLE
百度网盘当移动目标位置存在与源文件名相同的文件时，接口返回错误12

### ISSUE THREAD

**Issue by yyyr-p** [alist-org/alist#5576]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

如题。移动到相同目录本质上使用重命名接口，但存在相同问题（返回错误12）。API操作预期结果是覆盖目标文件。
#4505 似乎是一样的问题。

### Reproduction / 复现链接

在百度网盘驱动的目录中，创建a文件与b文件。
使用网页版移动/重命名（Web API请求 /api/fs/move）将b文件移动到a，操作失败，返回内容显示百度网盘接口错误12。
使用WebDAV接口请求MOVE方法将b文件移动到a，操作失败，HTTP返回500，AList日志显示百度网盘接口错误12。

### Config / 配置

感觉填写此字段意义不大，因为似乎这是普遍问题。
![image](https://github.com/alist-org/alist/assets/61129763/0fce8809-2efe-438b-b7c5-4fadb4b49e70)

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/61129763/043ea051-3ff1-47df-aeab-e9c9730d24d2)
![image](https://github.com/alist-org/alist/assets/61129763/af887128-8fb9-4aaf-80ce-f89623df76b2)

**Comment by xhofe** [comment]
请复制一份请求的fetch：
<img width="542" alt="image" src="https://github.com/alist-org/alist/assets/36558727/10c694d9-188c-4e84-8fa2-a422526da1ec">

**Comment by sunBob-2** [comment]
> 请复制一份请求的fetch： <img alt="image" width="542" src="https://private-user-images.githubusercontent.com/36558727/285634106-10c694d9-188c-4e84-8fa2-a422526da1ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODMyNDYsIm5iZiI6MTcwMjk4Mjk0NiwicGF0aCI6Ii8zNjU1ODcyNy8yODU2MzQxMDYtMTBjNjk0ZDktMTg4Yy00ZTg0LThmYTItYTQyMjUyNmRhMWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwNDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZmQzYzQ2YTIxNzgzYmYzN2RlMjMwYzRkMWEzYmM5MDQxNzZjOGJjZmQwMGNlMzVkZGM4ODBjZGNkNTA0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NE6INFz-RrYSHYsuhYYEk0Q4yjY2HZfVbTXirVdBc_Y">

```
fetch("http://127.0.0.1:5244/api/fs/move", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "zh,und;q=0.9,zh-CN;q=0.8,en;q=0.7,ja;q=0.6",
    "authorization": "[HIDDEN]",
    "content-type": "application/json;charset=UTF-8",
    "sec-ch-ua": "\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "http://127.0.0.1:5244/apps",
  "referrerPolicy": "same-origin",
  "body": "{\"src_dir\":\"/apps\",\"dst_dir\":\"\",\"names\":[\"alist.exe\"]}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```
预先操作：将一个百度网盘驱动挂载至```/```下。
该请求案例试图将位于```/app/```下的```alist.exe```文件移动到```/```下。
```
{
  "code": 500,
  "message": "req: [https://pan.baidu.com/rest/2.0/xpan/file] ,errno: 12, refer to https://pan.baidu.com/union/doc/",
  "data": null
}
```
以防万一，提供该请求在我的运行环境下的response。
我不认为提供该内容（AList前端对AList API的请求）对bug的修复有任何帮助，因为问题看上去存在于AList后端与储存驱动的交互中。

**Comment by xhebox** [comment]
测了侧, `/rest/2.0/xpan/file?method=filemanager ` 只要存在dest名字的文件, 就会报errno=12. 除非用`ondup: newcopy`或者`ondup: skip`, 而`ondup: overwrite`在rename/copy/move上并没有和我预期的一样, 把目标文件覆盖, 不再报错. 想要修复, 只能把dest文件也改个名字或者直接删掉.

**Comment by woshichenghaibo** [comment]
我也遇到了这个问题，以为是我的盘坏了
