### ISSUE TITLE
Alist太大了

### ISSUE THREAD

**Issue by xun188** [alist-org/alist#5577]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

3.28的版本还行，升级最新版本直接多了10来M，openwrt直接装不下了，是不是可以瘦点身

**Comment by BlueSkyXN** [comment]
装不下是多大

**Comment by Hiyajomaho-num9** [comment]
[Guide to compress GoLang binaries](https://dev.to/akshaybharambe14/guide-to-compress-golang-binaries-2d95)
建议使用upx压缩alist
按理来说，现在普遍新款路由的nand flash起步是128MB，理应是装的上。
若是传统nor flash，我建议换路由。

**Comment by xun188** [comment]
> [Guide to compress GoLang binaries](https://dev.to/akshaybharambe14/guide-to-compress-golang-binaries-2d95)
> 
> 建议使用upx压缩alist
> 
> 按理来说，现在普遍新款路由的nand flash起步是128MB，理应是装的上。
> 
> 若是传统nor flash，我建议换路由。

谢谢，通过安装到外挂usb解决了，之前可以刚好编译进去的，现在突然大了10来M

**Comment by Cp0204** [comment]
不能又要新功能，又要体积小
