### ISSUE TITLE
希望为API /fs/list ,  /fs/get 和 /fs/dirs 的返回对象中添加 full_path 属性，用于标记在该文件或目录在Alist中的绝对位置（全局位置）。

### ISSUE THREAD

**Issue by lee-cq** [alist-org/alist#5580]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望为API /fs/list ,  /fs/get 和 /fs/dirs 的返回对象中添加 full_path 属性，用于标记在该文件或目录在Alist中的绝对位置（全局位置）。

### Suggested solution / 实现思路

当请求 `/local` 的列表时，返回：
```json
{
    "code": 200,
    "message": "success",
    "data": {
        "content": [
            {
                "name": "t1",
                "full_path": "/local/t1" // 在Alist中的全局位置 （请求中的path + name）
                "size": 0,
                "is_dir": true,
                "modified": "2022-10-25T11:50:28.072504704+08:00",
                "created": "2022-10-25T11:50:28.072504704+08:00",
                "sign": "",
                "thumb": "",
                "type": 1,
                "hashinfo": "null",
                "hash_info": null
            }
        ],
        "total": 1,
        "readme": "",
        "write": true,
        "provider": "Local"
    }
}
```

**Comment by xhofe** [comment]
请求时会传入reqPath，full_path完全可以通过 pathJoin(reqPath, name)得到，所以感觉没有必要 添加了是冗余的。
