### ISSUE TITLE
v3.29.1版出现SSO问题

### ISSUE THREAD

**Issue by finalparanoia** [alist-org/alist#5587]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

v3.29.1版本会破坏alist与Authelia OIDC的集成，OAuth callback后alist会返还{"code":400,"message":"cannot get username from OIDC provider","data":null}错误。
回滚到v3.28.0后错误消失，程序工作正常。
我没有查看alist的代码，但我注意到webui中添加了Sso oidc 用户名键选项，默认值为name，我尝试过修改该选项来修复问题，但这没有起作用。

### Reproduction / 复现链接

我已经进行了回滚，且alist实例部署在内网，故无法提供复现链接

### Config / 配置

启用单点登录：是
单点登录平台：OIDC
单点登录客户端ID：omitted
单点登录客户端机密：omitted
单点登录组织名称：（空）
单点登录应用名称：alist
单点登录端点名称：ommited
单点登录JWT公钥：（空）
Sso自动注册：是
Sso默认路径：/
Sso 默认权限：1023
Sso 兼容模式：否
Sso oidc 用户名键：name

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "omitted",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true

### Logs / 日志

日志中没有汇报任何错误
INFO[2023-11-27 07:47:52] reading config file: data/config.json
INFO[2023-11-27 07:47:52] load config from env with prefix:
INFO[2023-11-27 07:47:52] init logrus...
INFO[2023-11-27 07:47:53] qbittorrent not ready.
INFO[2023-11-27 07:47:53] success load storage: [/public], driver: [Local]
INFO[2023-11-27 07:47:53] success load storage: [/mnt], driver: [Local]
INFO[2023-11-27 07:47:53] start HTTP server @ 0.0.0.0:5244

**Comment by xhofe** [comment]
fixed in 296be88b5f1c20c3df36051a10270125fafc7337
