### ISSUE TITLE
failed get objs: failed to list objs; driver not init

### ISSUE THREAD

**Issue by Harry6889** [alist-org/alist#5588]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

aliyun open

### Describe the bug / 问题描述

近期开始出现如下问题，原本正常使用，文件目录打不开，报如下错误：
![1](https://github.com/alist-org/alist/assets/142471377/c2a095b9-b9a5-4e70-bb89-3035f0d20b61)
![2](https://github.com/alist-org/alist/assets/142471377/a1698ba9-e0d8-404b-b185-4b8674357955)
打开编辑后，不作任何更改，直接保存，即可打开文件目录，继续使用。但一天以后会继续出现此问题。

### Reproduction / 复现链接

打开文件目录的链接：http://192.168.0.2:5244/Aliyun

### Config / 配置

只配置了一个aliyun open。我使用的是openwrt. 我的网络环境应该是正常的。一切都正常使用。小雅docker也是一直正常使用的。
![3](https://github.com/alist-org/alist/assets/142471377/ec3efe08-228a-4b52-8947-6d90dff48788)
![4](https://github.com/alist-org/alist/assets/142471377/da446868-617a-4584-9f5e-4d2fedd55154)
![5](https://github.com/alist-org/alist/assets/142471377/2cda24a7-e32d-4ae1-b38f-356fec03930d)
![6](https://github.com/alist-org/alist/assets/142471377/5e4bdf7c-aea2-455a-acce-b02bd677b801)

### Logs / 日志

清空日志后，打开文件目录的链接：http://192.168.0.2:5244/Aliyun，会记录以下日志：
[GIN] 2023/11/27 - 15:59:02 | 200 |     258.625µs |     192.168.0.3 | GET      "/Aliyun"
[GIN] 2023/11/27 - 15:59:02 | 200 |     733.417µs |     192.168.0.3 | GET      "/api/public/settings"
[GIN] 2023/11/27 - 15:59:02 | 200 |     769.417µs |     192.168.0.3 | GET      "/api/me"
[GIN] 2023/11/27 - 15:59:02 | 200 |    1.484417ms |     192.168.0.3 | POST     "/api/fs/get"
🔧[31mERRO🔧[0m[2023-11-27 15:59:02] fs/list: driver not init
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	github.com/alist-org/alist/v3/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	github.com/alist-org/alist/v3/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	github.com/alist-org/alist/v3/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	github.com/alist-org/alist/v3/internal/fs/fs.go:21
github.com/alist-org/alist/v3/server/handles.FsList
	github.com/alist-org/alist/v3/server/handles/fsread.go:85
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	github.com/alist-org/alist/v3/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	github.com/alist-org/alist/v3/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.(*conn).serve
	net/http/server.go:2009
runtime.goexit
	runtime/asm_arm64.s:1197 
🔧[31mERRO🔧[0m[2023-11-27 15:59:02] failed list /Aliyun: driver not init
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	github.com/alist-org/alist/v3/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	github.com/alist-org/alist/v3/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	github.com/alist-org/alist/v3/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	github.com/alist-org/alist/v3/internal/fs/fs.go:21
github.com/alist-org/alist/v3/server/handles.FsList
	github.com/alist-org/alist/v3/server/handles/fsread.go:85
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	github.com/alist-org/alist/v3/server/middlewares/auth.go:67
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	github.com/alist-org/alist/v3/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.(*conn).serve
	net/http/server.go:2009
runtime.goexit
	runtime/asm_arm64.s:1197
failed get objs 
[GIN] 2023/11/27 - 15:59:02 | 200 |    1.852916ms |     192.168.0.3 | POST     "/api/fs/list"

**Comment by Harry6889** [comment]
你好，可以告诉我大概我需要在哪里检查吗？

**Comment by Harry6889** [comment]
但是我其它的应用都是正常的呀

**Comment by xhofe** [comment]
我也不清楚 只是根据报错信息是dns的问题。

可能是你的系统在重启的时候 alist启动的速度早于dns服务 所以导致dns请求失败 你可以尝试设置延迟启动。

**Comment by Harry6889** [comment]
xhofe大佬：感谢您抽时间回复。
我的软路由是旁路由，从来不关机，也没有设置定时重启。因为我的主路由很烫，确实会每天会关机一段时间，但是一直是这么操作的，只是最近才出现这个问题。我先停掉主路由的关机来看看。谢谢啦！
**_“只会在请求发现令牌过期时去刷新令牌，更新 重启 编辑如果令牌仍然有效则不会去刷新。”_**
如果是刷新令牌失败造成的话，为什么小雅docker在同一个软路由里，却没有这样的问题。他们用的是同一个open token. 更次感谢。

**Comment by forever85** [comment]
在索引那个菜单里，手动点一下，能解决一些问题。
