### ISSUE TITLE
Alist指定目录分享功能

### ISSUE THREAD

**Issue by yu0o** [alist-org/alist#5590]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在分享文件时，用户能通过链接来访问其他文件，导致效果不尽人意！
建议如下：
1：生成一个目录链接，用户访问只能访问到该目录下文件，并隐藏其他元素，如下图红框内元素。
2：如果能加密网址不暴露网站主页，和短链接访问就更好！
![微信截图_20231127204333](https://github.com/alist-org/alist/assets/147189804/826fad4b-45eb-4fdd-8301-4cec1db698c9)

**Comment by Greenheir** [comment]
这个可以
