### ISSUE TITLE
阿里云盘限制并发下载

### ISSUE THREAD

**Issue by 12189108** [alist-org/alist#5591]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

本机代理下载时增加选项，限制总并发下载线程，否则会被403或者出现高达15b/s的下载速度

**Comment by BlueSkyXN** [comment]
32并发该浪继续浪

**Comment by anwen-anyi** [comment]
> 32并发该浪继续浪

这样的话好像容易被自己浪完犊子....
![image](https://github.com/alist-org/alist/assets/56105412/feebaa84-031d-47de-a2ae-ac3dc7c8e29f)

**Comment by Blanconature** [comment]
@BlueSkyXN 大佬 直链过期时间15分钟还有办法解决吗

**Comment by BlueSkyXN** [comment]
> @BlueSkyXN 大佬 直链过期时间15分钟还有办法解决吗

已经解决了，你没设置好吧
![屏幕截图 2023-12-01 141705.png](https://i0.wp.com/pic3.58cdn.com.cn/nowater/webim/big/n_v27ad70a58873a4bad9584ad4223e511f0.png)

**Comment by Blanconature** [comment]
> > @BlueSkyXN 大佬 直链过期时间15分钟还有办法解决吗
> 
> 
> 
> 已经解决了，你没设置好吧
> 
> ![屏幕截图 2023-12-01 141705.png](https://i0.wp.com/pic3.58cdn.com.cn/nowater/webim/big/n_v27ad70a58873a4bad9584ad4223e511f0.png)

是不是需要在自家NAS上才有这种效果 我的alist在云服务器上 webdav选择的302 第三方播放器播放 就会有15分钟的问题

**Comment by Blanconature** [comment]
> > > @BlueSkyXN 大佬 直链过期时间15分钟还有办法解决吗
> > 
> > 
> > 
> > 已经解决了，你没设置好吧
> > 
> > ![屏幕截图 2023-12-01 141705.png](https://i0.wp.com/pic3.58cdn.com.cn/nowater/webim/big/n_v27ad70a58873a4bad9584ad4223e511f0.png)
> 
> 是不是需要在自家NAS上才有这种效果 我的alist在云服务器上 webdav选择的302 第三方播放器播放 就会有15分钟的问题

Webdav选择本地代理也是一样

**Comment by BlueSkyXN** [comment]
> webdav选择的302

webdav选择的302 ？我记得302会导致rclone不能用，你这播放器倒是没事
根据我之前的说法

在线播放用V模式
web代理打开
缓存时间10分钟
webdav模式本地代理

之后在fileball、rclone、web、idm等方式均正常
