### ISSUE TITLE
LD|SD|HD|FHD|QHD分别代表什么画质？哪个才是最高画质？

### ISSUE THREAD

**Issue by NianBroken** [alist-org/alist#5592]
LD|SD|HD|FHD|QHD分别代表什么画质？哪个才是最高画质？

**Comment by anwen-anyi** [comment]
LD|SD|HD|FHD|QHD
- LD：普通清晰度 
- SD：标清
- HD：720P 
- FDH：1080P 
- QHD：2K四倍HD

**Comment by laorentou666** [comment]
现在阿里云盘是不是不让调清晰度了 视频都只有sd了
![Screenshot_20240724_184701](https://github.com/user-attachments/assets/b4b987af-4a65-4876-84ac-517dba2e1342)

**Comment by anwen-anyi** [comment]
> 现在阿里云盘是不是不让调清晰度了 视频都只有sd了
> 
> ![Screenshot_20240724_184701](https://github.com/user-attachments/assets/b4b987af-4a65-4876-84ac-517dba2e1342)
> 
> 

需要开通『三方应用权益包』
