### ISSUE TITLE
Google 验证器authenticator本地密钥丢失导致无法登录

### ISSUE THREAD

**Issue by FreeAlieX** [alist-org/alist#5600]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.29.1

### Driver used / 使用的存储驱动

openwrt

### Describe the bug / 问题描述

如题在输密码后提示获取OPT代码（但该密钥已丢失）
是否有办法重置alist？

### Reproduction / 复现链接

如题

### Config / 配置

抱歉现在进不去

**Comment by xhofe** [comment]
https://alist.nn.ci/zh/guide/advanced/2fa.html#%E5%A6%82%E4%BD%95%E8%A7%A3%E9%99%A42fa%E9%AA%8C%E8%AF%81
