### ISSUE TITLE
SVIP百度网盘WebDAV无法播放

### ISSUE THREAD

**Issue by co-ai** [alist-org/alist#5602]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.1

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

有SVIP，WebDAV使用302重定向策略，UA改为 pan.baidu.com，potplayer无法播放。

### Reproduction / 复现链接

http://admin:fixxxxx@127.0.0.1:5244/dav/BaiduWebDev/%E6%BD%98%E5%A4%9A%E6%8B%89.Pandora.2016.1080p.x264.AAC-%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95-BT4K/%E6%BD%98%E5%A4%9A%E6%8B%89.Pandora.2016.1080p.x264.AAC-%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95-BT4K.mp4?WithCaption

### Config / 配置

无

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/44060602/6c14aa1c-70d0-4d33-93d1-17fb4df58faf)
![image](https://github.com/alist-org/alist/assets/44060602/70ff7674-3321-4500-a02b-e61518b25330)

**Comment by co-ai** [comment]
log如下
![image](https://github.com/alist-org/alist/assets/44060602/0401ad79-5384-45fd-a24c-ab4b5a20ea96)

**Comment by xhofe** [comment]
在哪里设置了UA

**Comment by anwen-anyi** [comment]
Webdav 无法设置UA，所以你只能开启本地代理模式播放，如果还不能播放就是因为中转的机器网速不够快。

**Comment by co-ai** [comment]
看文档中说明WebDAV可以直接用302重定向，所以有此问题。
使用本地代理策略可以正常播放。
![image](https://github.com/alist-org/alist/assets/44060602/3920a4af-b316-4566-8b51-8a9d228a3b43)

**Comment by anwen-anyi** [comment]
非官方接口，但是不保证可用性，现在是否和谐了 暂未测试（一个月前是没问题）
![image](https://github.com/alist-org/alist/assets/56105412/8317bb0d-abd2-4d43-9950-51223166b373)

**Comment by xhofe** [comment]
> 看文档中说明WebDAV可以直接用302重定向，所以有此问题。
> 使用本地代理策略可以正常播放。
> ![image](https://github.com/alist-org/alist/assets/44060602/3920a4af-b316-4566-8b51-8a9d228a3b43)
> 

302的前提是客户端设置ua，目前并没有看到potplayer支持此设置。

**Comment by anwen-anyi** [comment]
他说的应该是这个，不过这个是干什们用的 可以说下么？@xhofe
![image](https://github.com/alist-org/alist/assets/56105412/458c30d8-767c-4967-bf84-7cf10f2221e6)

**Comment by xhofe** [comment]
> 他说的UA应该是改了这个，不过这个是干什们用的 可以说下么？@xhofe ![image](https://private-user-images.githubusercontent.com/56105412/286473872-458c30d8-767c-4967-bf84-7cf10f2221e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzE0OTUsIm5iZiI6MTcwMTIzMTE5NSwicGF0aCI6Ii81NjEwNTQxMi8yODY0NzM4NzItNDU4YzMwZDgtNzY3Yy00OTY3LWJmODQtN2NmMTBmMjIyMWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA0MTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MWRhZmZmMThhZjNjNGQwNGFjYWNkMDAwNmQ4M2ViZGJiOWQ0ZWI1NTgyMDUzYTRhNmY4MTc2MzYwMWUzYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R9UdI1tH2f2nPyMuIK-WgYFyZHbE_9dliJGBEZBKxiM)

使用本地代理时候使用的UA。

**Comment by womengnan** [comment]
PDF.js v3.0.44 (build: 6852001b0)
信息：Failed to fetch

默认设置，无法读取pdf和视频呢。

**Comment by clarance2018** [comment]
百度网盘复制到本地 出现限制下载数量的问题，可以成功下载一部分，另外的一直处于停顿状态

**Comment by Dododu** [comment]
请问 是不是改UA的方式只适用于网页端 本地代理策略是指打开Web代理选项吗（若打开Web代理选项 WebDav是选择本地策略吗）


> 看文档中说明WebDAV可以直接用302重定向，所以有此问题。 使用本地代理策略可以正常播放。 ![image](https://private-user-images.githubusercontent.com/44060602/286466515-3920a4af-b316-4566-8b51-8a9d228a3b43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODc4NDgsIm5iZiI6MTczMDE4NzU0OCwicGF0aCI6Ii80NDA2MDYwMi8yODY0NjY1MTUtMzkyMGE0YWYtYjMxNi00NTY2LThiNTEtOGE5ZDIyOGEzYjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOTFjZjdiM2Y0MTMyMzU0NzdlYjYyZTI3MTY0MDI1ZDJmMjQyNDNkNjNjMmRhMjk1ZjJkYzhlOTJmOGI1NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IWvVJRUznKjI6Pc2b1MV1m4ghVTu9MxbhDqS00Xm9sM)

**Comment by power521** [comment]
我之前没开百度云SVIP，可以正常观看，在apTV上，但开了SVIP突然就不能看了，怎么费事

**Comment by Rayciu** [comment]
> 我之前没开百度云SVIP，可以正常观看，在apTV上，但开了SVIP突然就不能看了，怎么费事

我也是啊，我是配合 raidrive 挂载到本地，用potplayer看，用本地代理加非官方接口看，一直都行，就昨晚开了SVIP还能看，今天早上看一会视频就不能看了

**Comment by Dododu** [comment]
百度有SVIP的话 开Web代理选项 选择本地策略 官方接口 亲测可用

**Comment by tommy20000** [comment]
> 百度有SVIP的话 开Web代理选项 选择本地策略 官方接口 亲测可用
百度盘的token很快就过期怎么办？必须过一段时间就手动更改吗？

**Comment by 362190147** [comment]
> 百度有SVIP的话 开Web代理选项 选择本地策略 官方接口 亲测可用
开web代理的话，是用服务器的网速吧

**Comment by abc53842726** [comment]
> 他说的UA应该是改了这个，不过这个是干什们用的 可以说下么？[@xhofe](https://github.com/xhofe) ![image](https://github.com/alist-org/alist/assets/56105412/458c30d8-767c-4967-bf84-7cf10f2221e6)

同求
