### ISSUE TITLE
迅雷云盘添加挂载时会自动填入以前的验证码，导致下一步无法进行

### ISSUE THREAD

**Issue by king-lei** [alist-org/alist#5603]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

迅雷

### Describe the bug / 问题描述

添加挂载迅雷云盘时，不填验证码保存，会自动填写以前输入过的验证码，但以前的验证码是无效的，删除后再保存还是如此，导致无法进行下一步操作。
![1](https://github.com/alist-org/alist/assets/26408193/019fe8c1-c60e-44bd-9b7e-7b120f55ce3c)
![2](https://github.com/alist-org/alist/assets/26408193/615a1ab8-8f8b-40e1-a8ea-72253e22bd40)
![3](https://github.com/alist-org/alist/assets/26408193/1c6b7ca2-1952-4369-a41a-140d2468c62b)
![4](https://github.com/alist-org/alist/assets/26408193/9f0870a6-eac1-44c7-8cff-386d1ec0f17f)

### Reproduction / 复现链接

http://wxl.synology.me:5244/@manage/storages

### Config / 配置

![5](https://github.com/alist-org/alist/assets/26408193/cb2cff7b-9e5d-4564-b161-bba1170ef53a)

### Logs / 日志

![2](https://github.com/alist-org/alist/assets/26408193/4afcb319-e748-4629-9476-4d7c8abdd621)
![4](https://github.com/alist-org/alist/assets/26408193/65604467-d5a8-4432-960f-0c16d6e5f132)

**Comment by king-lei** [comment]
麻烦进行修复

**Comment by xhofe** [comment]
#5286

**Comment by king-lei** [comment]
不是浏览器的表单自动填充，在用户名手机号前面增加+86后使用以前的验证码正确添加

**Comment by mmdctjj** [comment]
我也遇到了，有解决方法吗
