### ISSUE TITLE
添加minio：AuthorizationHeaderMalformed

### ISSUE THREAD

**Issue by Zac-Linley** [alist-org/alist#5604]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

对象存储

### Describe the bug / 问题描述

对象存储添加本地minio不成功

配置为：
Endpoint：http://127.0.0.1:8888
报错：
```
failed get objs: failed to list objs: AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'localhost'. status code: 400, request id: 179BD4B0D7A61430, host id: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

配置为：
Endpoint：127.0.0.1:8888
报错：
```
RequestError: send request failed
caused by: Get "https://127.0.0.1:8888/typora-note-image?delimiter=%2F&marker=&prefix=": http: server gave HTTP response to HTTPS client
failed to list objs
```

去掉https可以成功访问：
` http://127.0.0.1:8888/typora-note-image?delimiter=%2F&marker=&prefix= `
![image](https://github.com/alist-org/alist/assets/71690581/a29447d5-9649-4827-a00a-b66a5804be0a)

### Reproduction / 复现链接

本地自建存储，无法提供连接

### Config / 配置

```
"id": 5,
      "mount_path": "/typora-images",
      "order": 2,
      "driver": "S3",
      "cache_expiration": 30,
      "status": "work",
      "addition": "{\"root_folder_path\":\"/\",\"bucket\":\"typora-note-images\",\"endpoint\":\"http://127.0.0.1:8888/\",\"region\":\"alist\",\"access_key_id\":\"Lxr22Z*********nCl\",\"secret_access_key\":\"7lh*****************lAA\",\"session_token\":\"\",\"custom_host\":\"\",\"sign_url_expire\":4,\"placeholder\":\"\",\"force_path_style\":true,\"list_object_version\":\"v1\",\"remove_bucket\":false,\"add_filename_to_disposition\":false}",
      "remark": "",
      "modified": "2023-11-28T19:23:06.4273692+04:00",
      "disabled": false,
      "enable_sign": false,
      "order_by": "name",
      "order_direction": "asc",
      "extract_folder": "front",
      "web_proxy": false,
      "webdav_policy": "302_redirect",
      "down_proxy_url": ""
```

### Logs / 日志

```
[31mERRO[0m[2023-11-28 19:37:48] failed list /typora-images: AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'localhost'.
	status code: 400, request id: 179BD388B908C6A4, host id: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

**Comment by xhofe** [comment]
<img width="1034" alt="image" src="https://github.com/alist-org/alist/assets/36558727/e871d41a-f627-44a3-bff2-543a0a63c9d0">
请检查你的设置。
