### ISSUE TITLE
alist搭建onedrive盘的WebDAV，在windows10上挂载后，不能打开office文件。【非文件大小限制】

### ISSUE THREAD

**Issue by royccg** [alist-org/alist#5606]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

利用onedeive搭建的webdav挂载在windows10上；
1、webdav能成功挂载，一般文件均能正常读取写入，但是 office的文件就会打开失败。显示错误如下
![image](https://github.com/alist-org/alist/assets/44716144/1f321cfb-1401-40e2-901b-7b26ebea903b)

2、windows的webdav已经在注册表中修改了，允许挂在http，复现问题也不是 webdav的文件大小超出限制。

### Reproduction / 复现链接

工作环境，无法提供测试链接，但有截图。

### Config / 配置

存储配置都和v3.28.0完全一致

**Comment by xhofe** [comment]
Windows原生webdav兼容性较差 请考虑使用raidrive，rclone等第三方挂载软件。
