### ISSUE TITLE
元信息中添加删除

### ISSUE THREAD

**Issue by cgwxq** [alist-org/alist#5609]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

元信息中目前有 “写入”
希望可以添加一个删除，同写入一样当没有删除权限的时候，元信息中设置删除，即使无权限也可以删除。

**Comment by IAALAI** [comment]
按照文件系统的实现只有完全控制，写，读（执行）几种。实现删除理论上需要大于写的权限才有删除的权限。你这个需求看着我很不理解，感觉不合理

**Comment by cgwxq** [comment]
> 按照文件系统的实现只有完全控制，写，读（执行）几种。实现删除论需要大于写的权限一致删除的权限。你这个需求看着我很不理解，感觉不合理
用访客的视角，目前系统访客权限中“创建目录或上传”禁用的话是无法上传和创建内容，但是可以通过元信息单独设置一个或多个目录写入。
同理在元信息中新增一个删除，即使权限中没有允许“删除”，可以通过元信息设置单一目录的删除权限。

**Comment by IAALAI** [comment]
这个需求太少了，可能得要你自己去实现了。一般人应该不会在意这个的
