### ISSUE TITLE
上传IPA文件如果更改了名称会导致itms安装的plist里面的bundle id一起更改

### ISSUE THREAD

**Issue by panderman** [alist-org/alist#5612]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.29.1

### Driver used / 使用的存储驱动

不限

### Describe the bug / 问题描述

上传的ipa文件更改过名称，会导致itms安装时的plist里面的bundle id也会变，ios16以上将无法安装，请保留原始bundle id不要变动

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by xhofe** [comment]
bundleid就是根据文件名来的
