### ISSUE TITLE
安装错误提示不知道怎么解决

### ISSUE THREAD

**Issue by woxinzizai** [alist-org/alist#5616]
### AList Version / AList 版本

3.29.1

### Describe the bug / 问题描述

INFO[2023-11-30 23:54:28] reading config file: data\config.json
INFO[2023-11-30 23:54:28] config file not exists, creating default config file
INFO[2023-11-30 23:54:28] load config from env with prefix: ALIST_
INFO[2023-11-30 23:54:28] init logrus...
INFO[2023-11-30 23:54:28] Successfully created the admin user and the initial password is: VlLenLPg
WARN[2023-11-30 23:54:28] init tool qBittorrent failed: Post "http://localhost:8080/api/v2/auth/login": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
WARN[2023-11-30 23:54:28] init tool aria2 failed: failed get aria2 version: Post "http://localhost:6800/jsonrpc": dial tcp [::1]:6800: connectex: No connection could be made because the target machine actively refused it.
INFO[2023-11-30 23:54:28] init tool SimpleHttp success: ok
INFO[2023-11-30 23:54:28] start HTTP server @ 0.0.0.0:5244

**Comment by Linki-07** [comment]
遇到同样的问题不知解决没有

**Comment by Colorhhy** [comment]
我也遇到了 ，蹲一个解决方式

**Comment by ll-xxxxs** [comment]
我换了个安装包就好使了。你可以试试

**Comment by eeeGen** [comment]
我也遇到了 ，蹲一个解决方式
