### ISSUE TITLE
安装错误请求大家帮帮忙

### ISSUE THREAD

**Issue by woxinzizai** [alist-org/alist#5618]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.29.1

### Driver used / 使用的存储驱动

win10

### Describe the bug / 问题描述

安装时出现错误

### Reproduction / 复现链接

![错误](https://github.com/alist-org/alist/assets/104543013/208e0628-5a8b-4fa7-bb7f-1d7aa1434e62)

### Config / 配置

![错误](https://github.com/alist-org/alist/assets/104543013/16916719-8633-4933-b9c6-8ee1240a55f6)

**Comment by xhofe** [comment]
我没看到哪里有任何的错误 两个warning只是因为没有安装aria2和qbittorrent，请不要再提issue。
