### ISSUE TITLE
无法成功添加阿里云盘

### ISSUE THREAD

**Issue by xiaocainiao2020** [alist-org/alist#5621]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.29.1

### Driver used / 使用的存储驱动

阿里云盘

### Describe the bug / 问题描述

failed to refresh token: Too Many Requests
![image](https://github.com/alist-org/alist/assets/61716543/d51e85ed-46b4-4787-8625-f6398a83f236)
账号是正常使用的，不知道为什么会这样

### Reproduction / 复现链接

1

### Config / 配置

1

**Comment by BlueSkyXN** [comment]
有空没issue没空看文档的红色大字？
我可以说一句”滚吧你“吗，但是我觉得不太礼貌啊、
![屏幕截图 2023-12-01 151038.png](https://i0.wp.com/pic6.58cdn.com.cn/nowater/webim/big/n_v20faeaeae9b334e6980c972babcbd5048.png)

**Comment by xiaocainiao2020** [comment]
> 有空开issue，没空看文档的红色大字？ 我可以说一句”滚吧你“吗，但是我觉得不太礼貌啊？ ![屏幕截图 2023-12-01 151038.png](https://camo.githubusercontent.com/2108b7ae978607b3bf3a7bb9c14f6308992c61f2cc2a1389861287c93142cd9e/68747470733a2f2f69302e77702e636f6d2f706963362e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763230666165616561653962333334653639383063393732626162636264353034382e706e67)

你怎么知道我没看？？？我就没有过多请求，正常使用添加不上，我发issue问问怎么了？我想问问什么原因导致的过多请求不行吗？瞅你说话那欠揍语气，哪天让人打死了都是活该。

**Comment by BlueSkyXN** [comment]
> > 有空开issue，没空看文档的红色大字？ 我可以说一句”滚吧你“吗，但是我觉得不太礼貌啊？ ![屏幕截图 2023-12-01 151038.png](https://camo.githubusercontent.com/2108b7ae978607b3bf3a7bb9c14f6308992c61f2cc2a1389861287c93142cd9e/68747470733a2f2f69302e77702e636f6d2f706963362e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763230666165616561653962333334653639383063393732626162636264353034382e706e67)
> 
> 你怎么知道我没看？？？我就没有过多请求，正常使用添加不上，我发issue问问怎么了？我想问问什么原因导致的过多请求不行吗？瞅你说话那欠揍语气，哪天让人打死了都是活该。

同一 IP 在 60 分钟内请求 10 次，会出现 Too Many Requests 🚫避免滥用，请勿滥用🚫

你自己请求的你还说不知道？
“查看文件看视频下载不算，上述的分钟和次数是动态的
新增优化：只会在请求发现令牌过期时去刷新令牌，更新 重启 编辑如果令牌仍然有效则不会去刷新。”

自己关闭等2小时就行了，自己一直添加添加or共享IP还有啥好出来不服的

**Comment by Meatri** [comment]
> > > 有空开issue，没空看文档的红色大字？ 我可以说一句”滚吧你“吗，但是我觉得不太礼貌啊？ ![屏幕截图 2023-12-01 151038.png](https://camo.githubusercontent.com/2108b7ae978607b3bf3a7bb9c14f6308992c61f2cc2a1389861287c93142cd9e/68747470733a2f2f69302e77702e636f6d2f706963362e353863646e2e636f6d2e636e2f6e6f77617465722f776562696d2f6269672f6e5f763230666165616561653962333334653639383063393732626162636264353034382e706e67)
> > 
> > 
> > 你怎么知道我没看？？？我就没有过多请求，正常使用添加不上，我发issue问问怎么了？我想问问什么原因导致的过多请求不行吗？瞅你说话那欠揍语气，哪天让人打死了都是活该。
> 
> 同一 IP 在 60 分钟内请求 10 次，会出现 Too Many Requests 🚫避免滥用，请勿滥用🚫
> 
> 你自己请求的你还说不知道？ “查看文件看视频下载不算，上述的分钟和次数是动态的 新增优化：只会在请求发现令牌过期时去刷新令牌，更新 重启 编辑如果令牌仍然有效则不会去刷新。”
> 
> 自己关闭等2小时就行了，自己一直添加添加or共享IP还有啥好出来不服的

人家问问题，就你跟似了🐎一样上来就喷，他不看文档来问很正常，混那么就论坛你要求人人把规则都背下来？你哪怕说个“文档里有写”都比他妈的直接上来骂人强，傻逼东西
