### ISSUE TITLE
md文件渲染后图片显示问题

### ISSUE THREAD

**Issue by eya46** [alist-org/alist#5644]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

在md中的图片显示/渲染等 貌似有点问题

图片的url地址是对的，并且在网络中也加载了，但是不同于其它图片有预览的选项，并且在md中无法渲染

```md
### ACL 的分类与标识

- 基于 ACL 规则定义方式的分类
  ![Alt text](image-1.png)
  - 基本 ACL
    ![Alt text](image-2.png)
  - 高级 ACL
    ![Alt text](image-3.png)
  - 二层 ACL
  - 用户自定义 ACK
  - 用户 ACL
- 基于 ACL 标识方式的分类
  ![Alt text](image-4.png)
  - 数字型 ACL
  - 命名型 ACL
```

路径
![image](https://github.com/alist-org/alist/assets/61458340/081326de-2b37-41fd-a5ea-05f53d620d2f)

渲染的md
![image](https://github.com/alist-org/alist/assets/61458340/6130ecfb-ab40-4ae0-9e92-cf7503ef010c)
![image](https://github.com/alist-org/alist/assets/61458340/c0f1f380-c610-48a0-ac8c-635599b02d2c)
响应
![image](https://github.com/alist-org/alist/assets/61458340/e935b747-4361-4ad0-8c5b-551ecb8c13cb)
![image](https://github.com/alist-org/alist/assets/61458340/b18a0217-022b-42c0-90e3-38e16b1daca9)

### Reproduction / 复现链接

上面是内网测试的，试了下外网的，也是一样

https://talist.eya46.com/file.md

### Config / 配置

```json
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "114514",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}
```

**Comment by eya46** [comment]
复现链接对应的alist版本是v3.29.1

**Comment by xhofe** [comment]
暂不支持相对路径

**Comment by Toserk1024** [comment]
你可以试图将诸如"image-9.png"修改成"https://talist.eya46.com/d/image-9.png"或者使用第三方图床来解决此问题。
