### ISSUE TITLE
在展示大量图片缩略图时接口返回502

### ISSUE THREAD

**Issue by yinbohang** [alist-org/alist#5646]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.28.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

在有大量图片时 缩略图显示异常 接口报错502。有没有什么方法可以控制一下每次展示缩略图的数量。这样可以解决这个问题
![WechatIMG73598](https://github.com/alist-org/alist/assets/49786175/07b3b518-b89d-4d22-ad2f-a1ba26e9495b)

### Reproduction / 复现链接

https://alist.mourner.top/alist/12%E6%9C%883%E6%97%A5%E9%A6%99%E5%B1%B1%F0%9F%93%B7

### Config / 配置

{
  "force": false,
  "site_url": "https://alist.mourner.top",
  "cdn": "",
  "jwt_secret": "Wg3apg1QMYKknbs0",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "data/alist.mourner.top.pem",
    "key_file": "data/alist.mourner.top.key",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 10,
  "tls_insecure_skip_verify": true
}

**Comment by anwen-anyi** [comment]
这个改小点儿管用吗？
```json
"max_connections": 10,
```

**Comment by yinbohang** [comment]
<img width="525" alt="image" src="https://github.com/alist-org/alist/assets/49786175/c4e48190-2587-4ac7-9c58-6742792aaebf">
<img width="1268" alt="image" src="https://github.com/alist-org/alist/assets/49786175/ed1c56e4-674c-40c9-a68f-2a065952bb96">

我修改了max_connections = 3 在看api请求的时候依旧是批量的。
