### ISSUE TITLE
增加安卓和ios软件，实现全平台，通过备份恢复，实现账号同步，以此可以忽略没有vps与有些网盘无法302的不利，可以直接本地代理，只看本地宽带的网速

### ISSUE THREAD

**Issue by narrative-lion** [alist-org/alist#5649]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增加安卓和ios软件，实现全平台，通过备份恢复，实现账号同步，以此可以忽略没有vps与有些网盘无法302的不利，可以直接本地代理，只看本地宽带的网速，也更有利于推广

**Comment by woshichenghaibo** [comment]
搞那么多客户端，得需要多少人维护？谁给钱？推广了对作者有什么好处？

**Comment by itsHenry35** [comment]
有Community编写的客户端和能在移动设备上运行的服务端了，详见文档：https://alist.nn.ci/guide/ecosystem.html

**Comment by kuilei0926** [comment]
建议有想法就自己开发一个

**Comment by Cp0204** [comment]
有点指点江山的意味
