### ISSUE TITLE
v4/v6双栈环境，复制时能否双栈都利用上？

### ISSUE THREAD

**Issue by guiys** [alist-org/alist#5657]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

版本v3.29.1，docker使用host模式。网络环境ipv6出口走联通1，ipv4出口走联通2。
复制阿里云盘多个文件时候能看到流量全部走的ipv6，所以只能跑满一个出口。不知道能不能将任务平分到v4和v6上，这样复制时候可以跑满两个出口的带宽？
一个很小小小小众的想法

**Comment by fred913** [comment]
请多看一眼最前面Please make sure of the following things的第四条

I'm sure it's a reasonable and popular requirement

看到这了你还把很小众的想法提出来吗……
