### ISSUE TITLE
使用指定HTTPS端口访问时后台默认请求的是443端口

### ISSUE THREAD

**Issue by ikenxuan** [alist-org/alist#5658]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

本机存储/native storage

### Describe the bug / 问题描述

* 指定https端口访问（如：https://alist.example.com:5244） alist时观看‘本机存储’驱动下的内容（比如视频），开发者工具中可以看到网络请求是https://alist.example.com/p/localhost/1_0000.mp4?sign=lkIrGUSDIClpWd4lqSDhCRp4Hj2-gHxjvx3EH6iuuNc=:0 ，并不是带上端口的地址，并且在前端中点击'下载文件'的时候，请求的也是443端口（这个目前发现了是全局性的bug）

* 尝试使用过代理地址如为主页地址，虽然http状态码变成200了，但是还是看不了

### Reproduction / 复现链接

暂无

### Config / 配置

暂无

### Logs / 日志

暂无

**Comment by xhofe** [comment]
<img width="1360" alt="image" src="https://github.com/alist-org/alist/assets/36558727/c76b78d2-c3a8-4e25-b47b-ac0408b97354">

**Comment by xhofe** [comment]
无法复现，请提供详细的复现步骤与链接。

**Comment by ikenxuan** [comment]
> 无法复现，请提供详细的复现步骤与链接。

使用一键命令安装的alist；
https的是使用[1panel](https://github.com/1Panel-dev/1Panel)创建网站反向代理5244端口加https；

你可以看看我的这个https://alist.ikenxuan.top:5001/TMP/111.txt

**Comment by xhofe** [comment]
请在反向代理中传递正确的host。

**Comment by xhofe** [comment]
duplicate with 
- #726 
- #1159 
- #2429 
- #3644 
- #4181 
- #4719
