### ISSUE TITLE
阿里云盘OPEN每隔几天就会报一次101.201.69.253:443网络不可达

### ISSUE THREAD

**Issue by wsmayi** [alist-org/alist#5661]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

每隔几天时间（3-10天不等），alist就会连不上阿里云盘，在 管理后台—存储 看到阿里云盘open状态显示“Post "https://openapi.aliyundrive.com/adrive/v1.0/user/getDriveInfo": dial tcp 101.201.69.253:443: connect: network is unreachable”。
每当看到这个报错时，我用部署了alist的nas或者我电脑直接ping这个IP都是可达的。
需要点一下“全部重新加载”按钮，就可以恢复正常“work”状态。不点击这个按钮就一直不恢复。

### Reproduction / 复现链接

无。

### Config / 配置

![微信截图_20231208103229](https://github.com/alist-org/alist/assets/74253402/e6d89491-1eba-47fd-80af-f5930a150a8d)

**Comment by xhofe** [comment]
重启时 请设置alist启动在网络之后。
