### ISSUE TITLE
离线下载已经结束 qbittorrent 还在持续做种 并未删除任务

### ISSUE THREAD

**Issue by anwen-anyi** [alist-org/alist#5663]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

https://github.com/alist-org/alist/actions/runs/7075254591

### Driver used / 使用的存储驱动

none

### Describe the bug / 问题描述

https://github.com/alist-org/alist/issues/5595 此issue 已经被 https://github.com/alist-org/alist/commit/8bdfc7ac8e0ef07897ee5e72069f4659e2a1c6be 修复了
![image](https://github.com/alist-org/alist/assets/56105412/6f37c625-5a94-4a23-81d3-a257015b1d14)

然后使用 https://github.com/alist-org/alist/actions/runs/7075254591 最新自动构建的版本 测试上面的问题已经解决了，但是 qbittorrent 离线下载的文件还在持续做种中
- 选择了`上传成功后删除`
- 做种时间`0`

![UTUCTQ{5 01%~CHTWT00B T](https://github.com/alist-org/alist/assets/56105412/095ede89-5dd3-4608-8d45-d212cff7c0eb)

`3.29.1` 也测试过了也是有第二种问题的。

### Reproduction / 复现链接

none

### Config / 配置

none

### Logs / 日志

有全部 携带 `--debug` 启动的日志，但是由于太多不知道那个是...就提交了日志文本文件  [log - 副本.log](https://github.com/alist-org/alist/files/13615276/log.-.log)

**Comment by txt-vshy** [comment]
一样的情况，一直后台保种。
