### ISSUE TITLE
迅雷云盘非专业版挂载失效

### ISSUE THREAD

**Issue by LGuangming** [alist-org/alist#5667]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

迅雷

### Describe the bug / 问题描述

最近使用迅雷云盘挂载时候总是在挂在成功后几个小时失效，只能再次获取新CaptchaToken添加新存储，或者重新输入手机号码获取新CaptchaToken才能恢复，但过一段时间又会失效，提示如下。
![xunlei](https://github.com/alist-org/alist/assets/51586004/cc4805f5-ccae-4dd0-911e-f150fb3613fb)
![image](https://github.com/alist-org/alist/assets/51586004/b72fe7a7-e5ad-46e3-b397-722f4f7dee95)

### Reproduction / 复现链接

无

### Config / 配置

![image](https://github.com/alist-org/alist/assets/51586004/84869d2f-8fef-4bb0-85c7-5a3b23cc7a03)

**Comment by anwen-anyi** [comment]
你把  手机号中间的空格去掉呢？

**Comment by LGuangming** [comment]
> 你把  手机号中间的空格去掉呢？

我应该试过但我忘了是登不上去还是结果是一样的，因为我也早就注意到这个空格了，而且我有试着换用邮箱和密码挂载，结果也一样，过几个小时就会失效。

**Comment by LGuangming** [comment]
> 你把  手机号中间的空格去掉呢？

我又用没有空格的手机号码试了，结果依然是一样，过几个小时就失效，提示的内容和上面图片一样，

**Comment by zking0914** [comment]
我也是同样的问题，而且手机号直接不输入空格，也会显示为86 和 后边的数字之间 加入空格

**Comment by Eddie-cjz** [comment]
手机号填+86接着你的手机号
