### ISSUE TITLE
阿里云盘的下载链接能否固化

### ISSUE THREAD

**Issue by dzhl** [alist-org/alist#5671]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我在alist中加入了两个存储，1是阿里云盘，2是onedrive，然后我在网页端，找到两个盘里的文件，邮件，执行“复制链接”操作，得到的URL格式不一致，
对于onedrive，链接是直接指向文件，如http://xxxxxxxxx.com:5244/d/%E7%BE%8E%E5%89%A7/%E7%BE%8E%E5%89%A71/1883%20(2021)/Season%2001/1883%20-%20S01E01%20-%201883.ass,
而对于阿里云盘，复制出的链接中有一串变化的字符串，如
http://xxxxxxxxx.com:5244/d/ali/%E7%BE%8E%E5%89%A7/%E7%A6%8F%E5%B0%94%E6%91%A9%E6%96%AF%EF%BC%9A%E5%9F%BA%E6%9C%AC%E6%BC%94%E7%BB%8E%E6%B3%95%20(2012)/season02-poster.jpg?sign=4shMivxCXUbjnZwdewscdefrescdsQ-lvlVgGHHdxUAI=:0，其中“?sign=4shMivxCXUbjnZwdewscdefrescdsQ-lvlVgGHHdxUAI=:0”不是固定的，经常会变化
我想问，是否可以实现阿里云盘中文件下载链接也是固定的，后面不跟一段类似token的字符串。

### Suggested solution / 实现思路

我知道这串字符串可能是跟阿里云盘本身有关，那请问，我直接访问不带这串变化字符串的文件URL时（类似onedrive中链接），alist直接后台加入这串变化的字符串，这样的URL对于用户比较友好，当然会失去些安全性。

**Comment by itsHenry35** [comment]
https://alist.nn.ci/zh/guide/drivers/common.html#%E5%90%AF%E7%94%A8%E7%AD%BE%E5%90%8D https://alist.nn.ci/zh/config/global.html#%E7%AD%BE%E5%90%8D%E6%89%80%E6%9C%89 请参考Alist文档的配置
