### ISSUE TITLE
aria2离线下载状态不正确

### ISSUE THREAD

**Issue by tempppabx1** [alist-org/alist#5672]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

本机储存

### Describe the bug / 问题描述

在alist中添加aria2离线下载的任务完成后，后台-任务-离线下载-运行中依然会显示该任务在运行中，aria2 download completed, maybe transferring。
而同一个任务在下方的已完成中也会显示，显示内容为成功，transferring。
这些已完成的任务无法手动取消，手动点击取消后显示从运行中变成取消中，疑似依然占用同时下载数，导致新任务不会开始下载，只能手动重启服务器，清空所有任务列表
使用alist一键脚本安装alistv3.29.1版本，已经尝试了不同版本的aria2(1.36.0, 1.37.0)以及不同服务器系统，均可复现

### Reproduction / 复现链接

任意下载链接均可复现

### Config / 配置

暂无

**Comment by auhaij** [comment]
情况一模一样，alist是发行版最新    aira2是superng6/aria2:webui-latest ，都是dokcer
![image](https://github.com/alist-org/alist/assets/74290629/9bec7b53-87a0-4339-9aa5-bc8f30b1f820)
实际任务都是完成的

**Comment by auhaij** [comment]
> 情况一模一样，alist是发行版最新 aira2是superng6/aria2:webui-latest ，都是dokcer ![image](https://private-user-images.githubusercontent.com/74290629/289409023-9bec7b53-87a0-4339-9aa5-bc8f30b1f820.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjE3NTIsIm5iZiI6MTcwMjI2MTQ1MiwicGF0aCI6Ii83NDI5MDYyOS8yODk0MDkwMjMtOWJlYzdiNTMtODdhMC00MzM5LTlhYTUtYmM4ZjMwYjFmODIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAyMjQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZjcwNzQ0ZDRhYzJmZjRhYmU1NDhjMzJmODU5NjczODc2ZjcxMDg5MDMyOTQ1MmY0ZmUwOTNlZjRjNDVkNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IKId3UKujNZZ9kG2g3d8-einDdsPx4SO_uLCFansMW8) 实际任务都是完成的

这个情况我重启alist容器后好了，现在的问题是下载失败的链接，点击取消，状态一直是‘取消中’

**Comment by xhofe** [comment]
这应该在 8bdfc7ac8e0ef07897ee5e72069f4659e2a1c6be 中被修复。

**Comment by zx013** [comment]
未配置area2时也会复现
