### ISSUE TITLE
复制任务界面排版有点小问题

### ISSUE THREAD

**Issue by woshichenghaibo** [alist-org/alist#5673]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前的  删除已成功  这五个字显示不全，建议把四个按钮改成两行，或者是把其中的几个按钮汉字精简一下

目前用的是via浏览器

### Suggested solution / 实现思路

重新排版

### Additional context / 附件

![Screenshot_20231210_202347](https://github.com/alist-org/alist/assets/80568737/1883a013-efb5-485c-8b08-e10e74a46e54)

**Comment by woshichenghaibo** [comment]
强迫症实在受不了

**Comment by scalpl** [comment]
其他浏览器是否有同样的问题？比如Chrome   Microsoft Edge
