### ISSUE TITLE
游客身份分享音频文件练接，无法在新庄致中正确预览

### ISSUE THREAD

**Issue by c469591** [alist-org/alist#5692]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

最新版本

### Driver used / 使用的存储驱动

onedrive、本地

### Describe the bug / 问题描述

使用游客身份打开免登入帐号的储存区，在网页中预览音频文件时，可以正常收听，
复制练接，到其他装置打开该练接后网页能正常刷新，也能看到文件名，
但却显示Unknown，音频也无法播放，
从下拉框切换到download，再切换回audio后才能正常播放

### Reproduction / 复现链接

https://alist.lamb.tw/%E4%BD%9C%E5%93%81/%E9%AB%AE%E5%A6%82%E9%9B%AA_lara-002%20%E5%B0%8F%E7%BE%94%E7%BE%8A%E8%A3%BD%E4%BD%9C.wav

### Config / 配置

![image](https://github.com/alist-org/alist/assets/74401447/c2ed44e1-10cb-414b-972e-324565bb8062)
![image](https://github.com/alist-org/alist/assets/74401447/1276c924-25a6-4f04-893b-559f69327a9f)

### Logs / 日志

[GIN] 2023/12/14 - 09:36:55 | 200 |     538.545µs | 120.230.130.200 | GET      "/作品/髮如雪_lara-002 小羔羊製作.wav"
[GIN] 2023/12/14 - 09:36:58 | 200 |    1.332072ms | 120.230.130.200 | GET      "/assets/index.15d8d646.css"
[GIN] 2023/12/14 - 09:36:58 | 200 |    5.390937ms | 120.230.130.200 | GET      "/assets/index.afc5cbef.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |     652.881µs | 120.230.130.200 | GET      "/assets/entry.f25f5176.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |     894.531µs | 120.230.130.200 | GET      "/api/public/settings"
[GIN] 2023/12/14 - 09:36:59 | 200 |     248.918µs | 120.230.130.200 | GET      "/api/me"
[GIN] 2023/12/14 - 09:36:59 | 200 |      199.94µs | 120.230.130.200 | GET      "/assets/FolderTree.e40c5364.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |      89.128µs | 120.230.130.200 | GET      "/assets/index.7bba5123.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |      396.15µs | 120.230.130.200 | GET      "/assets/index.09dc6b85.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |     252.696µs | 120.230.130.200 | GET      "/assets/index.69ee4e7e.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |     563.827µs | 120.230.130.200 | GET      "/assets/Layout.53ea9934.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |     113.254µs | 120.230.130.200 | GET      "/static/manifest.json"
[GIN] 2023/12/14 - 09:36:59 | 200 |     374.145µs | 120.230.130.200 | GET      "/api/public/offline_download_tools"
[GIN] 2023/12/14 - 09:36:59 | 200 |  437.587889ms | 120.230.130.200 | POST     "/api/fs/get"
[GIN] 2023/12/14 - 09:36:59 | 200 |     203.608µs | 120.230.130.200 | GET      "/assets/File.35706d86.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |     241.927µs | 120.230.130.200 | GET      "/assets/icon.bcadb4b9.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |     570.341µs | 120.230.130.200 | GET      "/assets/audio.791c2686.js"
[GIN] 2023/12/14 - 09:36:59 | 200 |     352.132µs | 120.230.130.200 | GET      "/assets/audio.e5b5af14.css"
[GIN] 2023/12/14 - 09:36:59 | 200 |     192.851µs | 120.230.130.200 | GET      "/作品/undefined"
[GIN] 2023/12/14 - 09:37:07 | 206 |  7.926280763s | 120.230.130.200 | GET      "/d/share/作品/髮如雪_lara-002 小羔羊製作.wav"
[GIN] 2023/12/14 - 09:37:18 | 200 |     309.739µs | 120.230.130.200 | GET      "/作品/undefined"
[GIN] 2023/12/14 - 09:37:25 | 206 |  3.270776658s | 120.230.130.200 | GET      "/d/share/作品/髮如雪_lara-002 小羔羊製作.wav"

**Comment by xhofe** [comment]
无法复现。

**Comment by c469591** [comment]
已经在问题中更新了我当前配置的图片，
打开连接后无法播放，需要在下拉框切换到download，刷新到下载文件的画面后，在从下拉框选择回audio，这样才能成功播放，
还有哪边需要我补充呢？

**Comment by xhofe** [comment]
抱歉 我打开直接就可以播放 无法复现你所说的问题。

**Comment by c469591** [comment]
请问你是在哪个浏览器上测试正常？
这是我电脑上打开连接后的画面

![image](https://github.com/alist-org/alist/assets/74401447/7f9cbd20-561d-49bc-b2df-d0776acf1ef6)

目前电脑上测试了edge、firefox、brave，iphone上IOS16.7的firefox、brave以及内置浏览器都有相同问题，
iphone也有切换成wifi来测试，问题依旧，
昨天也有远程到中国地区的朋友电脑上测试，也是一样，
是否可以多尝试在另一个设备上打开连接，看看是否能付现问题？
谢谢！

**Comment by xhofe** [comment]
播放器左侧cover有一个播放按钮，请关注。
