### ISSUE TITLE
alist 挂载路径包含空格会无法获取到目录

### ISSUE THREAD

**Issue by megumi335400** [alist-org/alist#5694]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

AList V3

### Describe the bug / 问题描述

在挂载小雅alist 的时候 当目录中不含空格时,可以正常挂载
包含空格时:
![image](https://github.com/alist-org/alist/assets/49409819/ea0b9a42-8dac-4450-8488-2ec272f971af)
访问地址中的空格会转为%
如果我将挂载目录填写为
![image](https://github.com/alist-org/alist/assets/49409819/f5018d08-04f3-433f-b6b7-c9e6ba588874)

![image](https://github.com/alist-org/alist/assets/49409819/b624f37e-3618-44f3-a9ac-d24d8cbdc7fc)
Season%2001 或者改为包含空格的 Season 2001
均不能正常挂载
无法获取到目录

![image](https://github.com/alist-org/alist/assets/49409819/af63e4e4-2d89-4cff-bc23-4579445525ca)

### Reproduction / 复现链接

小雅alist:
http://v.elizen.me/%E5%8A%A8%E6%BC%AB/A-Z/X/%E5%BF%83%E7%90%86%E6%B5%8B%E9%87%8F%E8%80%85/Season%2001

### Config / 配置

[config.json](https://github.com/alist-org/alist/files/13677483/config.json)

**Comment by buyihou** [comment]
哎，我连注册账号都搞不定

**Comment by xhofe** [comment]
Season 01 不是 Season 2001

空格是 %20
