### ISSUE TITLE
希望音频、视频预览页面可以搭配键盘来播放以及快进快退，，以及更多的网页无障碍支持

### ISSUE THREAD

**Issue by c469591** [alist-org/alist#5698]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

你好，
为了让视觉障碍者能够搭配频幕阅读软件，用键盘更好的操作alist网页中的每个元素，我希望未来能够增强这方面的无障碍支持，具体如下：

1.希望在音频、视频的预览页面可以支持键盘的操作，
例如在预览页面中的任何地方，按左、右键可以快进快退；按空格可以暂停、继续播放，
类似B站是频中的键盘操作
2.希望音频、视频预览页面中的播放按钮、时间进度条等按钮控件，都能够加上文字，
例如播放的图片可以加上（播放）的文字，如果正在播放则显示（暂停），
3.按键盘上的TAB键可以切换到这些控件
例如按TAB键可以聚焦到播放的进度条上，按左、右键可以快进快退，
4. alist其他页面中有功能的纯图片都能加上文字，并且能用TAB键顺利的在这些控件中移动
装饰性图片则不需要有焦点

### Suggested solution / 实现思路

音频、视频预览页面的快进快退、播放暂停等键盘的操作代码，因为我对HTML不够熟悉所以暂且不知道该修改哪里来时键，
给有功能的图片、按钮加上文字，并且使其可按TAB键聚焦到控件上，用户可用enter或上、下、左、右与控件交互
关于网页无障碍的HTML代码示例，可以参考这里→
http://wai.forblind.org.tw/
谢谢！

**Comment by luomo-pro** [comment]
我是一位盲人程序员，alist现在在盲人群体中使用的还是很多的，大家使用所谓的“屏幕阅读器”，例如windows上的讲述人，操作电脑，会吧屏幕上的文字用语音朗读出来。
但朗读的前提是，控件本身有设置无障碍标签，那在html网页里，可以使用“aria-label”属性去设置标签，这样盲人就可以得知这个控件的作用了。
像现在alist在预览播放界面里，“播放”按钮就是无标签的。
还有文件夹页面底下的“刷新”、“新建文件夹”、“上传文件”等等，好几个图形，也都没有标签，盲人无法得知这些图形的作用。
这些图形还无法使用tab键切换到，那可以设置“tabindex”为0，从而添加tab焦点，从而让盲人可以点击操作这些图形。
这些改动虽然很小，但对盲人帮助却很大，希望alist官方可以坐下支持，万分感谢！要有什么疑问也可以随时问我。
