### ISSUE TITLE
Google Photos的视频无法快进

### ISSUE THREAD

**Issue by Xiefengshang** [alist-org/alist#5703]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

Google Photos

### Describe the bug / 问题描述

能够正常播放通过`alist`所挂载的`Google Photos`上的视频，但是无法快进视频(无论是在`Web`端还是将链接通过`Potplayer`等播放器打开)。网页端在拖动进度条之后又会自动回到当前位置。而挂载的`Google Drive`和阿里云盘都可以正常快进视频。

### Reproduction / 复现链接

直接按照`alist`挂载`Google Photos`的教程进行挂载即可，我测试了无论是`mkv`还是`mp4`的视频，无论是使用本地代理还是搭建`Cloudflare Workers`的代理地址，都无法快进视频。

### Config / 配置

按照官方教程的流程进行配置。启用了签名，显示了归档，缓存时间为`30min`。

### Logs / 日志

看起来不像是请求的问题？(
```
[GIN] 2023/12/16 - 22:54:11 | 200 |  2.938619261s | YourIP | POST     "/api/fs/link"
[GIN] 2023/12/16 - 22:54:14 | 302 |     197.644µs |    YourIP | GET      "/d/Google Photos/全部影集/VideoPath/VideoName.mp4?sign=signkey=:0"
[GIN] 2023/12/16 - 22:54:16 | 200 |  411.467448ms | YourIP | POST     "/api/fs/link"
[GIN] 2023/12/16 - 22:54:18 | 302 |      93.256µs |    YourIP | GET      "/d/Google Photos/全部影集/VideoPath/VideoName.mp4?sign=signkey=:0"
[GIN] 2023/12/16 - 22:54:19 | 200 |  500.512985ms | YourIP | POST     "/api/fs/link"
[GIN] 2023/12/16 - 22:54:20 | 302 |       121.9µs |    YourIP | GET      "/d/Google Photos/全部影集/VideoPath/VideoName.mp4?sign=signkey=:0"
[GIN] 2023/12/16 - 22:54:21 | 200 |  310.280602ms | YourIP | POST     "/api/fs/link"
[GIN] 2023/12/16 - 22:54:23 | 302 |      97.804µs |    YourIP | GET      "/d/Google Photos/全部影集/VideoPath/VideoName.mp4?sign=signkey=:0"
[GIN] 2023/12/16 - 22:54:24 | 200 |  327.654668ms | YourIP | POST     "/api/fs/link"
[GIN] 2023/12/16 - 22:54:25 | 302 |     116.379µs |    YourIP | GET      "/d/Google Photos/全部影集/VideoPath/VideoName.mp4?sign=signkey=:0"
[GIN] 2023/12/16 - 22:54:28 | 200 |  310.681518ms | YourIP | POST     "/api/fs/link"
[GIN] 2023/12/16 - 22:54:35 | 302 |     114.927µs |    YourIP | GET      "/d/Google Photos/全部影集/VideoPath/VideoName.mp4?sign=signkey=:0"
[GIN] 2023/12/16 - 22:54:36 | 200 |  378.041311ms | YourIP | POST     "/api/fs/link"
[GIN] 2023/12/16 - 22:55:17 | 200 |     496.497µs |    YourIP | GET      "/api/admin/storage/get?id=10"
[GIN] 2023/12/16 - 22:55:18 | 200 |     170.782µs |    YourIP | GET      "/api/admin/driver/info?driver=GooglePhoto"
[GIN] 2023/12/16 - 22:55:22 | 200 |   65.404923ms |    YourIP | POST     "/api/admin/storage/update"
[GIN] 2023/12/16 - 22:55:23 | 200 |     103.726µs |    YourIP | GET      "/api/admin/driver/names"
[GIN] 2023/12/16 - 22:55:23 | 200 |     425.363µs |    YourIP | GET      "/api/admin/storage/list"
[GIN] 2023/12/16 - 22:56:05 | 200 |     298.273µs |    YourIP | GET      "/api/admin/storage/get?id=10"
[GIN] 2023/12/16 - 22:56:06 | 200 |     177.855µs |    YourIP | GET      "/api/admin/driver/info?driver=GooglePhoto"

```

**Comment by xhofe** [comment]
https://developers.google.com/photos/library/guides/access-media-items?hl=zh-cn
文档中未说明支持 range请求。

**Comment by Xiefengshang** [comment]
> https://developers.google.com/photos/library/guides/access-media-items?hl=zh-cn 文档中未说明支持 range请求。

 原来如此，我还以为是我个人视频格式/`Alist`配置的问题，那我就不用折腾了，感谢回复！
