### ISSUE TITLE
能否优化一下打包的文件大小，路由设备内存小吃不消了。

### ISSUE THREAD

**Issue by pipipiper** [alist-org/alist#5708]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否优化一下打包的文件大小，路由设备内存小吃不消了。

**Comment by pipipiper** [comment]
> 上x86

没那条件啊 有那条件就不提这个问题了

**Comment by anwen-anyi** [comment]
不建议使用打包下载，推荐使用推送到 `Ari2`下载，支持保持目录结构。

**Comment by pipipiper** [comment]
> 不建议使用打包下载，推荐使用推送到 `Ari2`下载，支持保持目录结构。

您好，我说的是alist主程序的文件大小。

**Comment by anwen-anyi** [comment]
> > 不建议使用打包下载，推荐使用推送到 `Ari2`下载，支持保持目录结构。
> 
> 
> 
> 您好，我说的是alist主程序的文件大小。

抱歉 打扰了😗  我的👀可以捐了

**Comment by IAALAI** [comment]
这个可能得需要你自行编译裁剪了

**Comment by xhofe** [comment]
可以在https://github.com/alist-org/alist/blob/main/drivers/all.go 中注释掉不使用的驱动自行编译。
