### ISSUE TITLE
通过nginx反代后，通过浏览器访问地址 挂载的本地盘文件下载失败

### ISSUE THREAD

**Issue by mygit20230606** [alist-org/alist#5714]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

本地存储、SMB

### Describe the bug / 问题描述

我使用的istoreos下载的Alist,我使用Nginx Proxy Manager代理了alist，浏览器通过代理后的地址能成功打开Alist,我在下载挂载的本地存储和SMB存储时，下载失败，F12发现 丢失了端口号，把地址复制下来 手动添加端口号 可以下载。阿里云盘的可以正常下载。
![1](https://github.com/alist-org/alist/assets/135692202/f9217b44-83e3-400b-9115-6aab6bd051eb)

### Reproduction / 复现链接

暂无

### Config / 配置

暂无

**Comment by conglinyizhi** [comment]
您好，如果问题尚未解决，请参见 #4719

简单来说，需要在 nginx 后添加如下标记的内容

```nginx
location / {
    proxy_pass http://localhost:5244;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host; # 添加这一行
}
```
