### ISSUE TITLE
非常需要！！！添加临时用户，到期自动删除用户

### ISSUE THREAD

**Issue by yu0o** [alist-org/alist#5720]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

为方便指定用户访问指定目录，现版本指定目录已经可以实现现需要添加临时用户

### Suggested solution / 实现思路

建立新用户时可以选择用户存在时间，到期删除，最好是不必提醒或回收站
![微信截图_20231220234753](https://github.com/alist-org/alist/assets/147189804/f2018691-0ce3-434a-b71b-ba8b94d786df)

**Comment by xhwsd** [comment]
要不你搞个第三方任务调度系统，然后调用API操作？

**Comment by xhwsd** [comment]
看了下 https://alist-v3.apifox.cn/api-128101275 删除用户API也有了

**Comment by yu0o** [comment]
> 要不你搞个第三方任务调度系统，然后调用API操作？

感谢大佬，我去试试，但这个功能其实还是不错的，实行也不难
