### ISSUE TITLE
添加只读挂载功能

### ISSUE THREAD

**Issue by mlkt** [alist-org/alist#5721]
### Description of the feature / 需求描述

很多时候只是需要读取文件，并不需要修改文件，允许只读挂载可以防止意外修改或删除文件，同时增加安全性。虽然读写权限可以分用户指定，但增加只读挂载显然更方便，而且很多情况是管理员也只是想读取文件而已。

### Suggested solution / 实现思路

配置存储时增加一个选项勾选是否只读，对文件进行修改/删除/移动/改名等操作时检测当前存储是否为只读挂载，如果是则禁止修改。

**Comment by IAALAI** [comment]
在元信息里可以实现类似的权限控制吧

**Comment by xinxinenjoy** [comment]
只读的话单独添加个用户，把权限调一下不是也可以？

**Comment by IAALAI** [comment]
是的，这样应该也能实现你的需求
