### ISSUE TITLE
预览图片时能快速切换图片

### ISSUE THREAD

**Issue by laorentou666** [alist-org/alist#5726]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望可以在预览图片时添加如图的按钮来快速切换上一张 下一张
![image](https://github.com/alist-org/alist/assets/89732460/bcd6cf65-221f-4358-ab1c-364d03f08e2f)

**Comment by xhofe** [comment]
在目录中点击图片缩略图或icon。
