### ISSUE TITLE
io.copy中途channel被关闭 导致alist崩溃

### ISSUE THREAD

**Issue by mmooyyii** [alist-org/alist#5729]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.0

### Driver used / 使用的存储驱动

夸克网盘

### Describe the bug / 问题描述

io.copy中途channel被关闭 导致alist崩溃

### Reproduction / 复现链接

偶然出现， 我不知道怎么复现

### Config / 配置

应该和配置文件无关。

### Logs / 日志

```
panic: send on closed channel

goroutine 5162 [running]:
github.com/alist-org/alist/v3/internal/net.(*Buf).Write(0xc001ba86e0, {0xc000b54000, 0x1000, 0x8000})
        /source/internal/net/request.go:513 +0x10b
io.copyBuffer({0x40542c0, 0xc001ba86e0}, {0x27c73db3c80, 0xc000de8620}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:432 +0x1f4
io.Copy(...)
        /usr/local/go/src/io/io.go:389
github.com/alist-org/alist/v3/internal/net.(*downloader).tryDownloadChunk(0xc0019d4d10, 0xc000de80e0?, 0xc000de80e0)
        /source/internal/net/request.go:274 +0x146
github.com/alist-org/alist/v3/internal/net.(*downloader).downloadChunk(0xc0019d4d10, 0xc000de80e0)
        /source/internal/net/request.go:231 +0x18e
github.com/alist-org/alist/v3/internal/net.(*downloader).downloadPart(0xc0019d4d10)
        /source/internal/net/request.go:215 +0xde
created by github.com/alist-org/alist/v3/internal/net.(*downloader).download in goroutine 5102
        /source/internal/net/request.go:147 +0x219
```

**Comment by anwen-anyi** [comment]
感觉和自己本地内存有关，我之前复制几百G也遇到过但是没及时保存日志，但是后来换成十几G 分批复制就没这个问题了。

**Comment by KaoluAngel** [comment]
我也遇到了相同的问题

**Comment by 8MiYile** [comment]
我也遇到了这个问题
同样是把文件批量上传
天翼盘没问题 彩云盘没问题 沃盘就有这个问题
所以这个问题确实是需要修一下
（我还以为没人报告这个错误呢，差点就写了一份新的issue了）

**Comment by xhofe** [comment]
可以发一份更全的堆栈日志吗
