### ISSUE TITLE
群晖docker版本xhofe/alist经常挂死

### ISSUE THREAD

**Issue by senlinding** [alist-org/alist#5735]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

last

### Driver used / 使用的存储驱动

阿里云

### Describe the bug / 问题描述

群晖docker版本xhofe/alist经常挂死。经常挂死。

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/4864830/248fb68a-a1e2-4968-8fb2-d00f328c80c9)

### Config / 配置

![image](https://github.com/alist-org/alist/assets/4864830/dfb357b6-30b9-4cd1-8b8a-f658c85b2c0c)

**Comment by xhofe** [comment]
请附上崩溃日志。

**Comment by senlinding** [comment]
每次看完一集，服务就异常了。必须重启alist
[1.txt](https://github.com/alist-org/alist/files/13764591/1.txt)
