### ISSUE TITLE
在音乐文件夹搜索音乐之后，音乐播放列表里面没有打开这首歌？

### ISSUE THREAD

**Issue by masx200** [alist-org/alist#5736]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

在音乐文件夹搜索音乐之后，音乐播放列表里面没有打开这首歌？

### Reproduction / 复现链接

https://localhost:5443/music/%E6%B4%9B%E5%A4%A9%E4%BE%9D-badtozz-%E8%8A%B1%E5%A4%B4%E5%8F%B0.mp3

### Config / 配置

```json
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "9Vk2HZPZFerwFst7",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data\\data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": 5443,
    "force_https": false,
    "cert_file": "cert.crt",
    "key_file": "rsa_private.key",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data\\temp",
  "bleve_dir": "data\\bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data\\log\\log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}
```

### Logs / 日志

![mmexport1703490863724](https://github.com/alist-org/alist/assets/34191203/4761a4be-080b-46ad-aa77-ac1afb5bf873)
![mmexport1703490861114](https://github.com/alist-org/alist/assets/34191203/c6bb2a7a-9f37-4f6a-8c29-6b51ad6c8c44)

**Comment by anwen-anyi** [comment]
1. 你之前索引时有这个歌
2. 然后你把这个歌删了 或者移动到别的地方了
   - 然后没更新索引
4. 索引还是之前旧的 你点过去就没了

应该是这样的情况

**Comment by masx200** [comment]
> 1. 你之前索引时有这个歌
> 2. 然后你把这个歌删了 或者移动到别的地方了
>    - 然后没更新索引
> 4. 索引还是之前旧的 你点过去就没了
> 
> 应该是这样的情况

这首歌并没有删除，刷新一下又可以播放了，应该只是前端的bug

**Comment by masx200** [comment]
![image](https://github.com/alist-org/alist/assets/34191203/174bea75-bc35-48f5-9e30-dbe054df5faf)
