### ISSUE TITLE
无法用guest账号登陆webdav？已经给guest用户授予了webdav权限

### ISSUE THREAD

**Issue by masx200** [alist-org/alist#5737]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

无法用guest账号登陆webdav？已经给guest用户授予了webdav权限

### Reproduction / 复现链接

http://localhost:5244/dav

### Config / 配置

```json
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "9Vk2HZPZFerwFst7",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data\\data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": 5443,
    "force_https": false,
    "cert_file": "cert.crt",
    "key_file": "rsa_private.key",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data\\temp",
  "bleve_dir": "data\\bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data\\log\\log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}
```

### Logs / 日志

![mmexport1703491633873.png](https://github.com/alist-org/alist/assets/34191203/7218b81d-40a9-4a25-a0f2-8b2e07965ab7)![mmexport1703491630991.png](https://github.com/alist-org/alist/assets/34191203/75710f12-5f78-4665-a840-6d91f4decc62)![mmexport1703491627508.png](https://github.com/alist-org/alist/assets/34191203/87da26ee-8db9-4971-9157-3c3b365ce490)

**Comment by wangxso** [comment]
我发现在用户为guest的情况下, 还是会做密码的判断
user.ValidateRawPassword(password)
https://github.com/alist-org/alist/blob/f0e8c0e886d3521763c0436b558d26a02d481985/server/webdav.go#L82
然而guest本身在数据库中又存了一个hash
`3241f54e6b48a495eae1f12f736cc031d07ef41f37d3fec353005583af6f4bf0` 
然而guest的sha256 hash 最后对比值为
`d252f29c868d7b2455d2530da5f16b1430178796c9bf8a5cd1bc67a3c3dce22b`
我觉得如果guest只能无密码访问的话，应该加个特殊判断，因为我没看到又修改guest密码的选项

**Comment by wangxso** [comment]
> 我发现在用户为guest的情况下, 还是会做密码的判断 user.ValidateRawPassword(password)
> 
> https://github.com/alist-org/alist/blob/f0e8c0e886d3521763c0436b558d26a02d481985/server/webdav.go#L82
> 
> 
> 然而guest本身在数据库中又存了一个hash
> `3241f54e6b48a495eae1f12f736cc031d07ef41f37d3fec353005583af6f4bf0`
> 然而guest的sha256 hash 最后对比值为
> `d252f29c868d7b2455d2530da5f16b1430178796c9bf8a5cd1bc67a3c3dce22b`
> 我觉得如果guest只能无密码访问的话，应该加个特殊判断，因为我没看到又修改guest密码的选项

或者说在这里添加一个判断是否需要密码登录的判断

**Comment by littleneko** [comment]
这个问题貌似还是没解决

**Comment by mikal** [comment]
版本：v3.35.0-aarch64
日志报错，匿名用户依旧无法无密码访问。
[GIN] 2024/06/20 - 08:23:34 | 401 |    1.664214ms |   192.168.5.167 | HEAD     "/dav/"
[GIN] 2024/06/20 - 08:23:36 | 401 |    1.836585ms |   192.168.5.167 | HEAD     "/dav/"

**Comment by LouSpr** [comment]
> 版本：v3.35.0-aarch64 日志报错，匿名用户依旧无法无密码访问。 [GIN] 2024/06/20 - 08:23:34 | 401 | 1.664214ms | 192.168.5.167 | HEAD "/dav/" [GIN] 2024/06/20 - 08:23:36 | 401 | 1.836585ms | 192.168.5.167 | HEAD "/dav/"

webdav必须密码访问，用户名guest，密码guest

**Comment by LouSpr** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [文档](https://alist.nn.ci)。
>   我已经阅读了[文档](https://alist.nn.ci)。
> * [x]  I'm sure there are no duplicate issues or discussions.
>   我确定没有重复的issue或讨论。
> * [x]  I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ，`Dependencies` 或 `Operational`).
>   我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。
> * [x]  I'm sure this issue is not fixed in the latest version.
>   我确定这个问题在最新版本中没有被修复。
> 
> ### AList Version / AList 版本
> v3.29.1
> 
> ### Driver used / 使用的存储驱动
> 本机存储
> 
> ### Describe the bug / 问题描述
> 无法用guest账号登陆webdav？已经给guest用户授予了webdav权限
> 
> ### Reproduction / 复现链接
> http://localhost:5244/dav
> 
> ### Config / 配置
> ```json
> {
>   "force": false,
>   "site_url": "",
>   "cdn": "",
>   "jwt_secret": "9Vk2HZPZFerwFst7",
>   "token_expires_in": 48,
>   "database": {
>     "type": "sqlite3",
>     "host": "",
>     "port": 0,
>     "user": "",
>     "password": "",
>     "name": "",
>     "db_file": "data\\data.db",
>     "table_prefix": "x_",
>     "ssl_mode": ""
>   },
>   "scheme": {
>     "address": "0.0.0.0",
>     "http_port": 5244,
>     "https_port": 5443,
>     "force_https": false,
>     "cert_file": "cert.crt",
>     "key_file": "rsa_private.key",
>     "unix_file": "",
>     "unix_file_perm": ""
>   },
>   "temp_dir": "data\\temp",
>   "bleve_dir": "data\\bleve",
>   "dist_dir": "",
>   "log": {
>     "enable": true,
>     "name": "data\\log\\log.log",
>     "max_size": 50,
>     "max_backups": 30,
>     "max_age": 28,
>     "compress": false
>   },
>   "delayed_start": 0,
>   "max_connections": 0,
>   "tls_insecure_skip_verify": true,
>   "tasks": {
>     "download": {
>       "workers": 5,
>       "max_retry": 1
>     },
>     "transfer": {
>       "workers": 5,
>       "max_retry": 2
>     },
>     "upload": {
>       "workers": 5,
>       "max_retry": 0
>     },
>     "copy": {
>       "workers": 5,
>       "max_retry": 2
>     }
>   },
>   "cors": {
>     "allow_origins": [
>       "*"
>     ],
>     "allow_methods": [
>       "*"
>     ],
>     "allow_headers": [
>       "*"
>     ]
>   }
> }
> ```
> 
> ### Logs / 日志
> ![mmexport1703491633873.png](https://private-user-images.githubusercontent.com/34191203/292732079-7218b81d-40a9-4a25-a0f2-8b2e07965ab7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTA4NDEsIm5iZiI6MTcyNjIxMDU0MSwicGF0aCI6Ii8zNDE5MTIwMy8yOTI3MzIwNzktNzIxOGI4MWQtNDBhOS00YTI1LWEwZjItOGIyZTA3OTY1YWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA2NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMGVlZDJhZTU4OTM4OTJlZDdlZGEwZDdjZWVjNDhmMGJhMGE1MmFiMDQwNzE3MDM5MjlmZTFjYjRhYmY5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2stVgnds62wtsvV9HELg9rxyUYuxotGL8i5lFTq4bU)![mmexport1703491630991.png](https://private-user-images.githubusercontent.com/34191203/292732089-75710f12-5f78-4665-a840-6d91f4decc62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTA4NDEsIm5iZiI6MTcyNjIxMDU0MSwicGF0aCI6Ii8zNDE5MTIwMy8yOTI3MzIwODktNzU3MTBmMTItNWY3OC00NjY1LWE4NDAtNmQ5MWY0ZGVjYzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA2NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1Mjk0YzM1Y2E1YTI0ZTI0MGI2NDE4OWQ4MzM3OGQyMjNhM2Q1OTVhNWFiNjg0YTZkN2FkNTY4NmU0NmFmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qpaF1DUoXrfGGZS_-3YoNgrk6QUrOv0I2cpR_YXlaQM)![mmexport1703491627508.png](https://private-user-images.githubusercontent.com/34191203/292732274-87da26ee-8db9-4971-9157-3c3b365ce490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTA4NDEsIm5iZiI6MTcyNjIxMDU0MSwicGF0aCI6Ii8zNDE5MTIwMy8yOTI3MzIyNzQtODdkYTI2ZWUtOGRiOS00OTcxLTkxNTctM2MzYjM2NWNlNDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA2NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MWU4NjZhZjRkNDY2ODc3YzUzOGU4YmE5YjllOWM2NDg3NmJkNmYyOGFiYzJhNGFkYmM4NmY1M2FkNDAzOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ElwkVhq_Quc_cbytEx8Vav5CxUdx9vIkENGp_BjgUjM)

webdav必须密码访问，用户名guest，密码guest
设置里面是网页访问无需密码
