### ISSUE TITLE
建议增加文件的md5值输出，方便重复文件的检测

### ISSUE THREAD

**Issue by TankTim68** [alist-org/alist#5741]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

checksum值的输出可以方便对重复文件的检测

**Comment by woshichenghaibo** [comment]
那就越来越复杂了，，，，

**Comment by IAALAI** [comment]
好功能，但是实现起来有点麻烦。有的存储也不提供md5

**Comment by SheltonZhu** [comment]
计算md5是要耗费cpu资源的，如果存储不能提供，就要服务器或者浏览器来计算了😐
