### ISSUE TITLE
3.29.1版本，阿里云盘文件夹显示不全，备份盘里只显示固定的几个文件夹。其他的刷新不出来

### ISSUE THREAD

**Issue by aladGH** [alist-org/alist#5744]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.29.1

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

阿里云盘文件夹显示不全，备份盘里只显示固定的几个文件夹。其他的刷新不出来

### Reproduction / 复现链接

3.29.1版本，阿里云盘文件夹显示不全，备份盘里只显示固定的几个文件夹。其他的刷新不出来
![POPO-20231226-180207](https://github.com/alist-org/alist/assets/46032939/276bbc45-c1e5-4258-a58d-5953710c5642)

### Config / 配置

![tmp783E](https://github.com/alist-org/alist/assets/46032939/ad58c29c-495b-4646-8383-c6eb187118d8)

**Comment by xhofe** [comment]
修改时间都不一样 合理怀疑不是同一个账号。
