### ISSUE TITLE
支持常见的CDN刷新缓存API

### ISSUE THREAD

**Issue by valord577** [alist-org/alist#5749]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

将alist的服务作为源站时 cdn回源后可能会缓存

- 如果文件变更或删除时 希望能调用一下cdn的api 进行缓存刷新
- 如果发生版本更新时 也希望能调用一下cdn的api 刷新html等页面的缓存
- 参考API
  - https://help.aliyun.com/zh/cdn/developer-reference/api-cdn-2018-05-10-refreshobjectcaches
  - https://cloud.tencent.com/document/api/228/37870
  - https://cloud.tencent.com/document/api/228/37871

**Comment by jiangzm** [comment]
思路不对，CDN不是用来做内容存储，主要用作内容分发的。 对于内容的管理应该放在CDN的回源目标上。
一般用对象存储做CDN得回源内容，比如S3/OSS/COS。

**Comment by valord577** [comment]
> 思路不对，CDN不是用来做内容存储，主要用作内容分发的。 对于内容的管理应该放在CDN的回源目标上。 一般用对象存储做CDN得回源内容，比如S3/OSS/COS。

@jiangzm 

用户 -> CDN -> AList -> AList管理的存储

这个访问链路上 假设CDN有缓存。我在AList管理后台删除了一个文件 通过CDN访问的话 这个文件还能下载。

**Comment by JJTools** [comment]
我也遇到了。目前ALIST 确实不支持。我自己写了一个脚本在后面定时触发。。
