### ISSUE TITLE
添加PikPak存储时一次会添加两个, 并且删不掉

### ISSUE THREAD

**Issue by Jerry12228** [alist-org/alist#5762]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

PicPak

### Describe the bug / 问题描述

添加PikPak存储时一次会添加两个, 并且删不掉, 其中一个状态是work另一个没有状态
![image](https://github.com/alist-org/alist/assets/86408775/6a95d5f3-d0c3-4978-8c0b-4a339de2e3fb)
删除时第一次提示成功(但实际未成功),第二次报错(重启alist后再删除重复前两步)
![image](https://github.com/alist-org/alist/assets/86408775/8a6d46d3-9bc5-488f-90cd-ff5c281c3ab9)
重启alist,会无故多出几个存储(目前发现是将将之前的pikpak存储再复制一遍,2个变4个)
启动日志:
添加存储时配置正确:
```
INFO[2023-12-31 00:55:26] success load storage: [/PikPak], driver: [PikPak] 
INFO[2023-12-31 00:55:26] success load storage: [/PikPak], driver: [PikPak] 
```
配置错误:
```
ERRO[2023-12-31 00:17:07] failed get enabled storages: invalid_account_or_password
failed init storage
github.com/alist-org/alist/v3/internal/op.initStorage
        /source/internal/op/storage.go:99
github.com/alist-org/alist/v3/internal/op.LoadStorage
        /source/internal/op/storage.go:80
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
        /source/internal/bootstrap/storage.go:20
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1650 
```
在数据库中查看到:
![Uploading image.png…]()

### Reproduction / 复现链接

none

### Config / 配置

保持默认(更改temp目录)

### Logs / 日志

在描述中查看

**Comment by xhofe** [comment]
无法复现此问题

**Comment by Jerry12228** [comment]
> 无法复现此问题

更换数据库到MySQL 5.7后正常, 我应该提供什么以帮助解决问题? 原数据库文件? config.json? 或者完整的服务端目录?
