### ISSUE TITLE
希望增加推送功能，用来提醒挂载的网盘状态异常

### ISSUE THREAD

**Issue by reflander** [alist-org/alist#5763]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

网盘在挂载后当时是正常的，一段时间后可能会出现各种状态异常问题，如果不登录alist检查是无法发现的。希望alist可以增加email或微信推送功能

### Suggested solution / 实现思路

通过检测网盘挂载日志，设定推送条件实现推送提醒

**Comment by goldsoft8888** [comment]
支持

**Comment by shaojs321** [comment]
这个挺好，telegram通知很方便

**Comment by QuentinHsu** [comment]
附议！很需要通知系统！比如任务那儿，需要任务状态结果通知。
