### ISSUE TITLE
备份的时候只能备份账号不能备份密码

### ISSUE THREAD

**Issue by ipevel** [alist-org/alist#5765]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

备份的时候只能导出来的只有账号没有密码，恢复的时候也是账号数据能恢复但是密码都没有了，登录都显示密码错误。
如果不能复现这个bug，可以试试把账号弄多一些，就会出现了。

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by muxinxy** [comment]
#5662 和我之前提的 issue 类似
