### ISSUE TITLE
夸克网盘挂载报错require login [guest]

### ISSUE THREAD

**Issue by brainiac19** [alist-org/alist#5777]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

Quark

### Describe the bug / 问题描述

填写Cookie后保存配置，提示require login [guest]

### Reproduction / 复现链接

见图

### Config / 配置

![image](https://github.com/alist-org/alist/assets/51896856/25d507ca-29d5-439c-818e-b2e9ccded5e5)

### Logs / 日志

`[31mERRO [0m[2024-01-01 23:51:30] failed load storage: failed init storage: require login [guest] `
日志中并没有其他相关内容了，没有stack trace之类。怀疑这个信息是网络接口的直接返回内容。

**Comment by xhofe** [comment]
无法复现 我想是你的cookie粘贴的不完整。

**Comment by brainiac19** [comment]
> 无法复现 我想是你的cookie粘贴的不完整。

应该是这个原因。右键-copy value可以，手动选中十多次都不行。Firefox浏览器。
