### ISSUE TITLE
希望能考虑增加Azure Blob Storage的支持

### ISSUE THREAD

**Issue by rainrdx** [alist-org/alist#5780]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

搜索了一下似乎没有 Azure Blob Storage的FR。还是十分方便的在线存储系统，希望能够有机会支持。谢谢！

**Comment by woshichenghaibo** [comment]
没有说明？多大存储，免费用户有没有有效期，存储限制？

**Comment by wangxso** [comment]
这个类似OSS，不会有高额的流量费用吗

**Comment by rainrdx** [comment]
> 这个类似OSS，不会有高额的流量费用吗

这个就是OSS 类似于S3 其实冷存储非常便宜

**Comment by aohanhongzhi** [comment]
希望能支持azue存储

**Comment by ickacn** [comment]
支持增加支援
