### ISSUE TITLE
SSO 登录不成功

### ISSUE THREAD

**Issue by laopaoer-wallet** [alist-org/alist#5790]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

aliyunpan

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/75466368/53f862c7-0885-4f4e-8d50-1b3996aa6188)
我使用keycloak，按照alist的文档去配置相对应的sso，
结果，登录之后，就报错

{"code":400,"message":"no method provided","data":null}

### Reproduction / 复现链接

根据我截图去配置

### Config / 配置

根据我截图去配置

**Comment by itsHenry35** [comment]
请问你是怎么登录的？通过前端还是怎么样？ 你这个看起来好像是手动访问了重定向接口

**Comment by peterbuga** [comment]
got the same error with authelia, adding this to `redirect_uri` list made it work 
`https://alist.example.com/api/auth/sso_callback?method=sso_get_token` w/ setting `Sso compatibility mode: OFF`
