### ISSUE TITLE
Android 使用 foldersync 添加 alist WebDAV 错误

### ISSUE THREAD

**Issue by Hesidv** [alist-org/alist#5796]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

Built At: 2023-11-25 09:41:14 +0000 Go Version: go1.21.4 linux/amd64 Author: Andy Hsu <i@nn.ci> Commit ID: d54cb5a Version: 3.29.1 WebVersion: 3.29.0

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

org.xmlpull.v1.XmlPullParserException: Attr.value missing f. async (position:START_TAG <script src='https://g.alicdn.com/IMM/office-js/1.1.5/aliyun-web-office-sdk.min.js' async='https://jsd.nn.ci/gh/alist-org/logo@main/logo.png'>@19:5 in mp.t1@dd60200) 

### Reproduction / 复现链接

![Screenshot_20240103-122919_FolderSync Pro](https://github.com/alist-org/alist/assets/38974294/3cbdaf28-88e4-4945-91b4-7a7cbc61764d)
![Screenshot_20240103-123152_FolderSync Pro](https://github.com/alist-org/alist/assets/38974294/757c143a-9d11-47b5-93a9-d72d9fcbb2f0)
![Screenshot_20240103-123306_FolderSync Pro](https://github.com/alist-org/alist/assets/38974294/e6e598ea-b50e-4bdf-8575-69cbb1cc9ef5)

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": 5245,
    "force_https": false,
    "cert_file": "data/server.crt",
    "key_file": "data/private.key",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

### Logs / 日志

[GIN] 2024/01/03 - 04:18:59 | 200 |     432.344µs |       127.0.0.1 | PROPFIND  "/"

**Comment by xhofe** [comment]
dav加到服务器地址中 路径中不要填

**Comment by wangzhilin777** [comment]
一样的问题，不知道怎么解决

**Comment by wangzhilin777** [comment]
> dav加到服务器地址中 路径中不要填

感谢，终于解决了，确实要在地址里面才行
