### ISSUE TITLE
分享链接指向视频播放页面，而不是直接下载视频

### ISSUE THREAD

**Issue by ghost** [alist-org/alist#5809]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

创建带signatures的分享链接时，能否指向视频播放页面而非下载链接？

直接指向下载链接，在手机端聊天软件中使用时可能无法正确播放/下载。

前者也更符合一般网盘的分享习惯，用户也能有更多播放器选择。

### Suggested solution / 实现思路

播放页面增加 signatures 检查。更改分享链接的默认路径。

### Additional context / 附件

@xhofe

**Comment by Lstions** [comment]
+1，目前分享功能还可以增强下。
但是吧，涉及到资源分享就涉及到一些国家和地区的法律政策，有合规风险。
