### ISSUE TITLE
联通云盘获取不到token

### ISSUE THREAD

**Issue by huolanyun** [alist-org/alist#5811]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

联通云盘

### Describe the bug / 问题描述

按照教程 获取不到 token，提示输入图形验证

手动也抓不到，没有token 都是Data

大佬们看下 联通云盘 还有救吗

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by anwen-anyi** [comment]
没问题吖 手动抓取的
![image](https://github.com/alist-org/alist/assets/56105412/25bac6ef-0006-4621-87b3-7f5a4e4010bb)

多看几个请求，不一定在第一个或者第二个里面，在输入验证码确认前将全部请求先清空然后再点击确认，确认后你网盘的登录状态就被挤下来了 你就别登录网页版了
![image](https://github.com/alist-org/alist/assets/56105412/6ecccc71-d505-4a87-bcd6-1f5c05f5711b)

还有就是 默认应该是`个人云`文件夹ID为0，现在默认`0`写到了`Family id`后面需要改下，对你获取添加token影响不大

**Comment by huolanyun** [comment]
大佬回复了，我确实抓到了，关闭吧
