### ISSUE TITLE
Failed update storage in database: database is locked

### ISSUE THREAD

**Issue by puexine** [alist-org/alist#5815]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

1、创建“本机存储”，全部默认配置
2、创建成功后修改“根文件夹路径”为“/home”，成功
3、然后想修改“/home”为其它文件夹，始终出现上面错误

### Reproduction / 复现链接

http://192.168.88.99/@manage/storages/edit/6

### Config / 配置

默认配置

**Comment by xhofe** [comment]
数据库锁住了 可能需要重新配置下。
