### ISSUE TITLE
ipfs API不支持http://网关，http://网关上的视频不能正常播放。只能使用https://的网关才能正常播放视频。

### ISSUE THREAD

**Issue by vpei** [alist-org/alist#5818]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3

### Driver used / 使用的存储驱动

ipfs API

### Describe the bug / 问题描述

ipfs API不支持http://网关，http://网关上的视频不能正常播放。只能使用https://的网关才能正常播放视频。能不能支持IPFS网关的内容分享？

### Reproduction / 复现链接

ipfs API不支持http://网关，http://网关上的视频不能正常播放。只能使用https://的网关才能正常播放视频。能不能支持IPFS网关的内容分享？

### Config / 配置

ipfs API不支持http://网关，http://网关上的视频不能正常播放。只能使用https://的网关才能正常播放视频。能不能支持IPFS网关的内容分享？

### Logs / 日志

ipfs API不支持http://网关，http://网关上的视频不能正常播放。只能使用https://的网关才能正常播放视频。能不能支持IPFS网关的内容分享？

**Comment by vpei** [comment]
![Snipaste_2024-01-05_21-51-08](https://github.com/alist-org/alist/assets/42698055/2c2d7255-f605-4da4-a341-c7713725adb6)
![Snipaste_2024-01-05_21-53-05](https://github.com/alist-org/alist/assets/42698055/1ad980e5-0697-4efe-81b9-27d96030177e)

第一个图片是通过在线播放的视频出错，第二个是直接打开视频的网址，能播放。

**Comment by xhofe** [comment]
请提供一个复现链接。

**Comment by vpei** [comment]
> 请提供一个复现链接。

https://alist.vmess.com/ipfs/211330031018aa63a589288.mp4

**Comment by xhofe** [comment]
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure video '<URL>'. This request has been blocked; the content must be served over HTTPS.

浏览器不允许在https网站中请求http资源，这不安全。

**Comment by vpei** [comment]
> Mixed Content: The page at '' was loaded over HTTPS, but requested an insecure video ''. This request has been blocked; the content must be served over HTTPS.
> 
> 浏览器不允许在https网站中请求http资源，这不安全。

这个不能解决吗？😁
