### ISSUE TITLE
Alist docker容器服务每天停止多次，自动启动无效，仅手动开启才能运行

### ISSUE THREAD

**Issue by Kado814** [alist-org/alist#5822]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.29.1

### Driver used / 使用的存储驱动

阿里云open,夸克，本地存储

### Describe the bug / 问题描述

容器服务报错自动停止运行，自动启动无效，仅手动开启才能恢复一段时间

### Reproduction / 复现链接

没有链接

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "zllTU0RnfgnCz4UD",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

### Logs / 日志

panic: send on closed channel

goroutine 12262 [running]:
github.com/alist-org/alist/v3/internal/net.(*Buf).Write(0xc000b78820, {0xc001256000, 0x1000, 0x8000})
        /app/internal/net/request.go:513 +0x10b
io.copyBuffer({0x3428e40, 0xc000b78820}, {0x15059cae95d8, 0xc0015cbac0}, {0x0, 0x0, 0x0})
        /usr/lib/go/src/io/io.go:432 +0x1f4
io.Copy(...)
        /usr/lib/go/src/io/io.go:389
github.com/alist-org/alist/v3/internal/net.(*downloader).tryDownloadChunk(0xc0005d8bb0, 0xc001aa3300?, 0xc001aa3300)
        /app/internal/net/request.go:274 +0x146
github.com/alist-org/alist/v3/internal/net.(*downloader).downloadChunk(0xc0005d8bb0, 0xc001aa3300)
        /app/internal/net/request.go:231 +0x18e
github.com/alist-org/alist/v3/internal/net.(*downloader).downloadPart(0xc0005d8bb0)
        /app/internal/net/request.go:215 +0xde
created by github.com/alist-org/alist/v3/internal/net.(*downloader).download in goroutine 12231
        /app/internal/net/request.go:147 +0x219

**Comment by xhofe** [comment]
#5729
