### ISSUE TITLE
请求支持分片上传 Request for support for multipart upload

### ISSUE THREAD

**Issue by axyn45** [alist-org/alist#5824]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我的Alist站点套了阿里云的全站加速，而所有阿里云的CDN产品POST上传文件大小都被限制在了300M无法更改，这会导致在上传大文件的时候加速节点直接返回413，而且大文件上传很容易受到网络波动的影响，因此建议添加**分片上传到Alist服务端**的功能。 #5176 有提到同样的request和类似的use case，但是题主似乎主动关闭了。个人认为还是挺有必要的一个功能。

### Suggested solution / 实现思路

本人没有相关领域或者Golang开发经验，提供一些可能有用的帖子仅供参考。

- [File Upload in Go with multipart/form-data](https://blog.devgenius.io/file-upload-in-go-with-multipart-form-data-fa6ebe8569ae)
- [How to Multipart File Upload Using FormData with HTML](https://refine.dev/blog/how-to-multipart-upload/)
- [Example of doing a multipart upload in Go (golang)](https://gist.github.com/mattetti/5914158/f4d1393d83ebedc682a3c8e7bdc6b49670083b84)
- [POST data using the Content-Type multipart/form-data](https://stackoverflow.com/questions/20205796/post-data-using-the-content-type-multipart-form-data)

### Additional context / 附件

![image](https://github.com/alist-org/alist/assets/73621356/4fd3dc1b-9e04-4d6a-bff2-8465f8b8ca05)
已经确认是CDN节点返回的，因此没有提供log。

**Comment by yyyytawa** [comment]
+1
希望能像cloudreve一样可以不需要占用大量内存直接分片上传

**Comment by Syndesi** [comment]
Regarding resumable uploads in general, I can recommend the following standards/specifications:

**tus**: A stable resumable upload specification, supports protocol extensions, has a reference server implementation written in Go: https://github.com/tus/tusd , https://tus.io/ .

**httpbis-resumable-upload**: Upcoming official standard by IETF, not yet fully released. It is basically the successor of tus, but with a more complete specification and more examples. But as with any work in progress standard, small details can and will change.
https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/
