### ISSUE TITLE
请问能不能为路由器等小内存设备优化一下？

### ISSUE THREAD

**Issue by html5syt** [alist-org/alist#5829]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist虽然只有50MB左右大小，但是对于路由器等小内存设备压力还是很大，能不能让其占用空间减少到20MB左右，内存占用减少到40～50MB？

### Suggested solution / 实现思路

我想了想有3种方案：
①去除对于这一类设备不必要的功能，比如aria2、多用户等
②去除使用不多的存储来源，尽量减少因为SDK占用的空间（额...用到了SDK吗？）
③减少前端界面的空间占用，比如简洁的主题，或者去掉部分视觉效果

（其实只需要只需要对于这一类设备出专门的一版就可以了，而且路由器一版是arm64或MIPS等架构，只需要对这一类架构优化即可）

**Comment by woshichenghaibo** [comment]
作者肯定说请你自己精简。
我的服务器是5块钱买的随身WIFI，RAM 384MB总共。

**Comment by haohaohaoadsad** [comment]
https://github.com/alist-org/alist/issues/5708

**Comment by html5syt** [comment]
> #5708

请问这里自己编译能够用这个仓库的Github action脚本编译吗？这样可以更方便一点

**Comment by haohaohaoadsad** [comment]
> > #5708
> 
> 请问这里自己编译能够用这个仓库的Github action脚本编译吗？这样可以更方便一点

https://alist.nn.ci/zh/guide/install/source.html#%E6%9E%84%E5%BB%BA%E5%90%8E%E7%AB%AF

**Comment by IAALAI** [comment]
根据我的经验，裁剪额外的驱动提升效果有限，如果把前端拆出来放到单独的地方，比如cloudflare page或者github page 效果明显,大概可以减少20MB左右，还一个大杀器是上upx，也可以缩减一半左右。如果在按照作者的删减你不需要的驱动，应该是可以压缩到10MB左右的。不过可惜我用不上这个。。。我的设备光内存就有384GB了。。。

**Comment by xx6z8v** [comment]
方便问一下Alist在Linux上的最低运行标准是多少吗(RAM等)

**Comment by githubhc20** [comment]
> 作者肯定说请你自己精简。 我的服务器是5块钱买的随身WIFI，RAM 384MB总共。

可否具体说说是哪种随身WIFI呀？

**Comment by woshichenghaibo** [comment]
> > 作者肯定说请你自己精简。 我的服务器是5块钱买的随身WIFI，RAM 384MB总共。
> 
> 可否具体说说是哪种随身WIFI呀？

网上搜索  随身WIFI alist

**Comment by woshichenghaibo** [comment]
> 根据我的经验，裁剪额外的驱动提升效果有限，如果把前端拆出来放到单独的地方，比如cloudflare page或者github page 效果明显,大概可以减少20MB左右，还一个大杀器是上upx，也可以缩减一半左右。如果在按照作者的删减你不需要的驱动，应该是可以压缩到10MB左右的。不过可惜我用不上这个。。。我的设备光内存就有384GB了。。。

你说的驱动是存储器吗？那个不能删除吧，再说了那个也不占用内存吧？

**Comment by IAALAI** [comment]
> > 根据我的经验，裁剪额外的驱动提升效果有限，如果把前端拆出来放到单独的地方，比如cloudflare page或者github page 效果明显,大概可以减少20MB左右，还一个大杀器是上upx，也可以缩减一半左右。如果在按照作者的删减你不需要的驱动，应该是可以压缩到10MB左右的。不过可惜我用不上这个。。。我的设备光内存就有384GB了。。。
> 
> 你说的驱动是存储器吗？那个不能删除吧，再说了那个也不占用内存吧？

可以删的，作者以前的裁剪教程里就有提过。

只不过确实裁剪缩小的空间有限

真的要缩小空间还得是上UPX和裁掉前端

而且应该是存储不是内存。。。
