### ISSUE TITLE
How to see the version ?

### ISSUE THREAD

**Issue by sonichy** [alist-org/alist#5834]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

The version should be displayed in the about page.

**Comment by itsHenry35** [comment]
it's there in manage - settings - site, or you can see it in the console in f12 developer tools

**Comment by sonichy** [comment]
I want to the version in console, no need to login.
```
./alist server
alist version: 3.30
go version: 1.21
......
```
