### ISSUE TITLE
Password leak

### ISSUE THREAD

**Issue by sonichy** [alist-org/alist#5835]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

data/data.db
x_storages
addition
The password did not encrypt may leak.

### Suggested solution / 实现思路

Encrypt password

**Comment by anwen-anyi** [comment]
更新你的版本 后续已经加密了 还能看到明文吗？

**Comment by woshichenghaibo** [comment]
密码存储在哪里？
