### ISSUE TITLE
用API获取的115直链不可用

### ISSUE THREAD

**Issue by EscapeU** [alist-org/alist#5836]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

用API获取的115直链不可用

### Reproduction / 复现链接

curl --location --request POST 'http://xxx.xxx.xxx.xxx:5244/api/fs/get' \
--header 'Authorization: alist-token' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--data-raw '{
    "path": "/yourfilepath",
    "password": "",
    "page": 1,
    "per_page": 0,
    "refresh": false
}'
使用以上命令获取到的直链信息有误

### Config / 配置

![1704568800827](https://github.com/alist-org/alist/assets/125351094/8dc94806-4d99-4086-9e76-ea87179361f2)

**Comment by xhofe** [comment]
有什么误说清楚。

**Comment by EscapeU** [comment]
> 有什么误说清楚。

再alist中获取的下载直链可以下载，而通过api获得的直链不可用
图1为从alist中下载
![image](https://github.com/alist-org/alist/assets/125351094/8abb6860-a8b3-44aa-9b74-ff2f07e86df9)
图2为从api中获取
![1704611270993](https://github.com/alist-org/alist/assets/125351094/e4202f03-114d-4e73-9bcf-484a1eb554c3)
![1704611374907](https://github.com/alist-org/alist/assets/125351094/f434581d-1c02-40a1-bce7-070ed3a8b421)

**Comment by xhofe** [comment]
获取链接与下载时需要使用相同的UA

**Comment by EscapeU** [comment]
> 获取链接与下载时需要使用相同的UA

我修改了UA再次尝试了一般依旧不可用
![1704612760227](https://github.com/alist-org/alist/assets/125351094/b66832d5-4b35-4b7f-a0d3-82dc851e5cdf)

**Comment by EscapeU** [comment]
如果需要相同UA的话 我昨晚尝试复制出直链给别人 别人的手机是可以下载的UA应该是不一样的
![1d7f0cdee61beb462f78336d2ade735](https://github.com/alist-org/alist/assets/125351094/097735ed-ddbd-4902-a86b-39c90e108b19)

**Comment by xhofe** [comment]
终端会把 & 转义成 `\u002`

**Comment by sln162** [comment]
@EscapeU  我也遇到了，找到解决办法了吗？
