### ISSUE TITLE
Video player UI add previous and next

### ISSUE THREAD

**Issue by sonichy** [alist-org/alist#5839]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

|◀   ▶|     ▶
It is more convenient to skip video when fullscreen.

**Comment by itsHenry35** [comment]
it's there https://github.com/alist-org/alist-web/commit/ac8bfe0e12156c70dfbf8f186a5ba2a8e38cfcac

**Comment by sonichy** [comment]
Linux alist 3.30 still not seen previous and next button on video.
Demo (https://al.nn.ci/) add 2 videos  to test previous and next button.

**Comment by itsHenry35** [comment]
> Linux alist 3.30 still not seen previous and next button on video. Demo (https://al.nn.ci/) add 2 videos to test previous and next button.

oh i got it, are you using aliyundrive previewer?

**Comment by sonichy** [comment]
Yes,  aliyundrive previewer.

**Comment by itsHenry35** [comment]
不小心把阿里云盘预览漏掉了😂只改了通用的播放器



2671230065
***@***.***







                       
Original Email
                       
                     

Sender:"海天鹰"< ***@***.*** &gt;;

Sent Time:2024/1/12 17:40

To:"alist-org/alist"< ***@***.*** &gt;;

Cc recipient:"itsHenry"< ***@***.*** &gt;;"State change"< ***@***.*** &gt;;

Subject:Re: [alist-org/alist] Video player UI add previous and next (Issue#5839)




 
Yes,  aliyundrive previewer.

**Comment by sonichy** [comment]
嗦嘎
