### ISSUE TITLE
使用IDM和Aria2下载超时

### ISSUE THREAD

**Issue by bypp** [alist-org/alist#5845]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.30.0

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

下载夸克网盘中的文件时，使用IDM会链接超时，使用Aria2速度一直是0，但是用浏览器自带的下载工具正常
Aria2在家里局域网环境下也可以正常下载
发生问题时的使用环境是Aria2和AList部署在家里NAS的Docker上，人在公司登录AList，把夸克网盘里的文件发送到家里Aria2上
IDM版本6.42
Aria2版本1.36.0

### Reproduction / 复现链接

https://home.jwppp.com:5346/d/%E5%A4%B8%E5%85%8B%E7%BD%91%E7%9B%98/temp/Dolby%20Amaze%20(Dolby%20Vision).mp4?sign=zqRx1FsgGZN0w6PS2yx8OSzSrQ2HG58bT9Da10ozCwQ=:0

### Config / 配置

默认配置

**Comment by xhofe** [comment]
链接打不开

**Comment by bypp** [comment]
> 链接打不开

家里没有公网ipv4地址，所以只能用ipv6的

**Comment by bypp** [comment]
我刚又测试了下之前的版本，问题还在，我还以为是周末更新造成的，打扰了，先关闭

**Comment by tanmoumou252** [comment]
大概理解一下,是不是和我遇到的一模一样

域名访问ipv6环境的alist,发送到aria2 任务失败后详情页显示: 操作超时 timeout 

alist网页复制文件链接后,手动进行下载时浏览器依旧能正常下载,aria2仍然不能够进行下载,当然使用源服务器地址自然二者均正常

域名动态解析在路由上,且使用[lucky](https://github.com/gdy666/lucky)转发外部v6端口到局域网v4端口 
印象不太深,在没用lucky之前,本机域名解析,不经过一次端口转发,aria2好像是正常的,真记不清了 

但如果套上cf,设置隐性url转发`Origin Rules`5243端口(http端口),就可以正常发送下载到aria2了 
 
可通过浏览器和aria2自行验证这两个链接的效果 
![屏幕截图 2024-05-02 213854](https://github.com/alist-org/alist/assets/118299342/4688e3e8-ef0a-4c12-ad0e-4a43934448cd)
`aria2` 中 `check-certificate`已为`false` 

```
https://tanmoumou.v6.army:5244/d/123%E7%9B%98/ToDesk%20update.exe
```
cloud flare cdn v4环境可访问 
```
https://v4.tanmoumou.link/d/123%E7%9B%98/ToDesk%20update.exe
```

**Comment by tanmoumou252** [comment]
> 大概理解一下,是不是和我遇到的一模一样
> 
> 域名访问ipv6环境的alist,发送到aria2 任务失败后详情页显示: 操作超时 timeout
> 
> alist网页复制文件链接后,手动进行下载时浏览器依旧能正常下载,aria2仍然不能够进行下载,当然使用源服务器地址自然二者均正常
> 
> 域名动态解析在路由上,且使用[lucky](https://github.com/gdy666/lucky)转发外部v6端口到局域网v4端口 印象不太深,在没用lucky之前,本机域名解析,不经过一次端口转发,aria2好像是正常的,真记不清了
> 
> 但如果套上cf,设置隐性url转发`Origin Rules`5243端口(http端口),就可以正常发送下载到aria2了
> 
> 可通过浏览器和aria2自行验证这两个链接的效果 ![屏幕截图 2024-05-02 213854](https://private-user-images.githubusercontent.com/118299342/327449969-4688e3e8-ef0a-4c12-ad0e-4a43934448cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTc2NjQsIm5iZiI6MTcxNDY1NzM2NCwicGF0aCI6Ii8xMTgyOTkzNDIvMzI3NDQ5OTY5LTQ2ODhlM2U4LWVmMGEtNGMxMi1hZDBlLTRhNDM5MzQ0NDhjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxMzQyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzY3ZTIxYWE0YjYzMjQ2ZWJjMzdjYmI4ZjAyOTAxZjFiMmIwOWViYjI2NGJmN2I4MTY1ZWI5ODU2M2JhYTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xKu066o7pw1y-YsK7qe5CztcpoySU-ETO4Gyv7BOMI8) `aria2` 中 `check-certificate`已为`false`
> 
> ```
> https://tanmoumou.v6.army:5244/d/123%E7%9B%98/ToDesk%20update.exe
> ```
> 
> cloud flare cdn v4环境可访问
> 
> ```
> https://v4.tanmoumou.link/d/123%E7%9B%98/ToDesk%20update.exe
> ```

附带一提 这个timeout和是不是https似乎没有任何关系 

即便在url 1中将https换成5243,aria2依旧是无法下载的,在lucky后台看不到任何公网IP访问记录.  

但如果是url 2 ,则可以在后台看到cf访问使用的 `[2400:cb00::]:port` 

于是我想了个歪办法,不过有其他的隐患 

代理到安装alist的主机,即你访问你的设备localhost时,访问的实际是安装alist主机的内网,如此aria2就运作在v4环境了 
![屏幕截图 2024-05-02 215932](https://github.com/alist-org/alist/assets/118299342/7b82ef52-4977-4723-894f-1741060d015a)

也就是说域名在这个办法里,只是用来挂代理服务器的时候少输个IPv6地址

**Comment by w0ngzz** [comment]
同样的情况，idm下载0速度，浏览器正常下载

**Comment by qq565425677** [comment]
同样的情况，前置cf就好了，但是电信用cf太慢了
