### ISSUE TITLE
跪求大佬能增加分享地址需要输入验证码

### ISSUE THREAD

**Issue by jiaz520** [alist-org/alist#5851]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我的环境是alist挂在本地硬盘，发现链接只要被别人知道了，迅雷就开始拿我的资料和地址当p2p的点，上传带宽占满了，我设置了元信息，和签名，但是下载地址没有影响，知道知道地址，就可以下载，如果能设置个像百度网盘的验证吗，至少能让别人来我的网站下载，而不是p2p的下载点,

**Comment by huolanyun** [comment]
这个应该是个BUG，知道目录结构+文件名，任何验证信息都不要就能下载
@xhofe

**Comment by huolanyun** [comment]
未开放guest，不登录的情况下 ，没权限直接访问驱动文件可以直接下载
最新v3.30测试

**Comment by xhofe** [comment]
> 这个应该是个BUG，知道目录结构+文件名，任何验证信息都不要就能下载 @xhofe

https://alist.nn.ci/config/global.html#sign-all

**Comment by nibazshab** [comment]
你把这个打开就行了

![image](https://github.com/alist-org/alist/assets/44338441/aec80bd9-c924-4228-90d3-e880fda4952c)

刚试的，打开这个后，直接用链接地址是行不通的，必须要有后面的 `?sign=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`才行

![{69333FFF-B206-4C79-9853-ADB34AA1D66F}](https://github.com/alist-org/alist/assets/44338441/dd35547f-7401-4823-a8fc-d73749613745)

**Comment by jiaz520** [comment]
其实我想最终达到的目的是，下载你随便下载，但是不能直接输入地址就下载，必须通过我的站点，还要防止迅雷把我的点当成P2P点。

**Comment by zzxupp** [comment]
install时候不是指定了域名么，比如mp4.abc.com，你的文件路径是https://mp4.abc.com/2024/hahah.mp4，即使加入密码功能，下载地址还是这个，也不会像百度链接那样多层、多类型加密吧。

退一步说，真要实现这样功能，感觉对服务器的资源消耗也是非常大的

**Comment by crossxyz** [comment]
> install时候不是指定了域名么，比如mp4.abc.com，你的文件路径是[https://mp4.abc.com/2024/hahah.mp4，即使加入密码功能，下载地址还是这个，也不会像百度链接那样多层、多类型加密吧。](https://mp4.abc.com/2024/hahah.mp4%EF%BC%8C%E5%8D%B3%E4%BD%BF%E5%8A%A0%E5%85%A5%E5%AF%86%E7%A0%81%E5%8A%9F%E8%83%BD%EF%BC%8C%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80%E8%BF%98%E6%98%AF%E8%BF%99%E4%B8%AA%EF%BC%8C%E4%B9%9F%E4%B8%8D%E4%BC%9A%E5%83%8F%E7%99%BE%E5%BA%A6%E9%93%BE%E6%8E%A5%E9%82%A3%E6%A0%B7%E5%A4%9A%E5%B1%82%E3%80%81%E5%A4%9A%E7%B1%BB%E5%9E%8B%E5%8A%A0%E5%AF%86%E5%90%A7%E3%80%82)
> 
> 退一步说，真要实现这样功能，感觉对服务器的资源消耗也是非常大的

可以参考一下filebrowser，对分享的文件/文件夹进行短链处理隐藏路径，设置分享时间和密码验证或无密码，再添加个分享管理。
直接打开文件路径需要账户验证。

**Comment by zzxupp** [comment]
> > install时候不是指定了域名么，比如mp4.abc.com，你的文件路径是[https://mp4.abc.com/2024/hahah.mp4，即使加入密码功能，下载地址还是这个，也不会像百度链接那样多层、多类型加密吧。](https://mp4.abc.com/2024/hahah.mp4%EF%BC%8C%E5%8D%B3%E4%BD%BF%E5%8A%A0%E5%85%A5%E5%AF%86%E7%A0%81%E5%8A%9F%E8%83%BD%EF%BC%8C%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80%E8%BF%98%E6%98%AF%E8%BF%99%E4%B8%AA%EF%BC%8C%E4%B9%9F%E4%B8%8D%E4%BC%9A%E5%83%8F%E7%99%BE%E5%BA%A6%E9%93%BE%E6%8E%A5%E9%82%A3%E6%A0%B7%E5%A4%9A%E5%B1%82%E3%80%81%E5%A4%9A%E7%B1%BB%E5%9E%8B%E5%8A%A0%E5%AF%86%E5%90%A7%E3%80%82)
> > 退一步说，真要实现这样功能，感觉对服务器的资源消耗也是非常大的
> 
> 可以参考一下filebrowser，对分享的文件/文件夹进行短链处理隐藏路径，设置分享时间和密码验证或无密码，再添加个分享管理。 直接打开文件路径需要账户验证。

看了下确实可行
