### ISSUE TITLE
转存任务没有限制并发数量导致宕机

### ISSUE THREAD

**Issue by Deepsea-CN** [alist-org/alist#5855]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30

### Driver used / 使用的存储驱动

无关

### Describe the bug / 问题描述

转存任务包括但不限于离线下载后的自动转存，复制和移动任务，不是一个一个文件执行而同时开始，当文件数量过多时导致我的vps的cpu负荷99%最终宕机，希望可以添加任务并发限制，或者依次转存，或者离线下载BT时可以选择下载的内容

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by xhofe** [comment]
https://alist.nn.ci/config/configuration.html#tasks
