### ISSUE TITLE
安稳大佬，加个小飞机盘备，薅羊毛 结构和蓝奏云优享版一样，上传好像都一样

### ISSUE THREAD

**Issue by huolanyun** [alist-org/alist#5856]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://www.feijipan.com/

薅羊毛，可以分流下载，速度还可以，cdn跑过也能到 40M/s

### Suggested solution / 实现思路

和蓝奏云优享版一样界面，文件路径和上传地址

**Comment by anwen-anyi** [comment]
:joy_cat: 好像用的就是七牛OSS？
![image](https://github.com/alist-org/alist/assets/56105412/31d985a9-156f-466d-90ba-77eec345d1f8)

**Comment by huolanyun** [comment]
> 😹 好像用的就是七牛OSS？ ![image](https://private-user-images.githubusercontent.com/56105412/296150507-31d985a9-156f-466d-90ba-77eec345d1f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTIwMTYsIm5iZiI6MTcwNjE1MTcxNiwicGF0aCI6Ii81NjEwNTQxMi8yOTYxNTA1MDctMzFkOTg1YTktMTU2Zi00NjZkLTkwYmEtNzdlZWMzNDVkMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAzMDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMDUyYjZkMTYzMmM5OGU1ZDcyNzk2MTU5YjllMTA1NTJjZTI1ZjE4N2QzY2RkN2FkOTY3YTVjN2ExNDQyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Kgt7b5vaeJZh4Bsmot7Acyik7TL-J7E57y_siD2rFg)

是的，现在云盘 也在卷，我们薅一薅 看着他们跑路

新建的codespaces 运行pnpm install 报错，显示淘宝源 下载不到文件，但是 复制链接出来 能下载到
