### ISSUE TITLE
使用qBittorrent导致宕机

### ISSUE THREAD

**Issue by Deepseaon** [alist-org/alist#5857]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30

### Driver used / 使用的存储驱动

无关

### Describe the bug / 问题描述

感谢开发人员的解答，重新排查了问题，发现是出在qBittorrent4.1.9上，使用aria2下载时后台可以正常显示状态，下载完也能正常转存，但是qBittorrent就会稳定触发，首先是创建任务成功后在后台不会正常显示进度，但是qb上看是正常创建任务并开始下载了，等到下载完成后vps就宕机了，如下图，cpu使用率爆满
我注意到说明文档中说使用了2.8.3的api所以建议使用高版本的qb，所以这个问题是必须更新qb解决吗，是否有别的解决方案？

### Reproduction / 复现链接

无

### Config / 配置

完全按照文档配置

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/111950052/545225aa-640c-4e4b-a1ed-6a2695bcec07)

**Comment by Deepsea-CN** [comment]
疑似是和之前的问题类似，解析种子有问题然后alist没法正常获取信息最后导致没法离线下载，把qb相关文件全部删除重装可以恢复正常，找不到到底哪里有问题

**Comment by Deepsea-CN** [comment]
排查完了，中了病毒，与qb无关与alist无关，不过还是请警惕某些相关的脚本，我看还有人在中招
