### ISSUE TITLE
百度网盘非官方接口下载 500

### ISSUE THREAD

**Issue by caoler** [alist-org/alist#5872]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

百度网盘除 mp4 类型以外，其他资源下载均为 500：

{
    "code": 500,
    "message": "http request [https://d.pcs.baidu.com/file/4620c7472g9e6670a3b25d81dcb64d4a?fid=3812896526-250528-1336001367918&rt=pr&sign=FDtAERK-DCb740ccc5511e5e8fedcff06b081203-lekmEumUYe3piDByD1ZY%2fSgeBHk%3d&expires=8h&chkbd=0&chkv=0&dp-logid=265758191301530697&dp-callid=0&dstime=1705028427&r=625588119&vuk=3812896526&origin=dlna] failure,status: 403 response:\u001f\ufffd\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003-\ufffd1\u000e\ufffd \f\u0000\ufffd\ufffd4\ufffdY\u0004\u0011\ufffd3\u0006\ufffdQb\ufffdX`2\ufffdݘx\ufffd\ufffdH\"\ufffd\ufffd\ufffd\u0019\t\ufffdi\ufffd\u001e\ufffd_{^\ufffd\ufffd\ufffd\nL\u001c\ufffd\rj&\ufffd\ufffd\u000b(\ufffd21SX\b\"\u001f\u0001\u0015\n]\ufffdr\u0019SD\ufffd;\ufffdlo\ufffdm]\ufffdik\u0006\ufffd\ufffd\ufffd\ufffd\u001b\ufffdh\u0000\u0000\u0000",
    "data": null
}

切换为官方接口后可以正常下载，但是非常慢。aria2 的 ua，pan.baidu.com、netdisk都试过了

### Reproduction / 复现链接

无

### Config / 配置

<img width="719" alt="image" src="https://github.com/alist-org/alist/assets/26300971/04d5b985-3867-4b3b-bb7b-26b19fc0acc9">

**Comment by xhofe** [comment]
不保证非官方接口可用，请勿再为此提issue。
