### ISSUE TITLE
升级之后本机存储加载不出来

### ISSUE THREAD

**Issue by MoYuYuDe** [alist-org/alist#5874]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.30.0

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

我是使用的termux 进行部署的, 从3.29.0 升级到3.30.0之后, 本机存储加载不出来, 提示521, 删除之后重新添加, 删除termux 重新配置, 还是无法加载

### Reproduction / 复现链接

无

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "f11nlSIpaodP372f",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

**Comment by MoYuYuDe** [comment]
升级到3.30.0之后, 打开之前添加的本机存储 (部署在termux上, 安卓版本9 ), 界面提示 "Request failed with status code 521"
![微信图片_20240112182350](https://github.com/alist-org/alist/assets/107624890/030420f6-e37b-4c8e-b26a-87af19d2fde4)
控制台报错
![微信图片_20240112182400](https://github.com/alist-org/alist/assets/107624890/f26fb18e-5a56-4e32-abdb-a835a030e525)
我的存储配置如下
      "driver": "Local",
      "cache_expiration": 0,
      "status": "work",{\"root_folder_path\":\"/data/data/com.termux/files/home\",\"thumbnail\":false,\"thumb_cache_folder\":\"\",\"show_hidden\":true,\"mkdir_perm\":\"777\"}",
      "modified": "2024-01-05T00:31:29.422994738Z",
      "disabled": false,
      "enable_sign": false,
      "order_by": "name",
      "order_direction": "asc",
      "extract_folder": "front",
      "web_proxy": false,
      "webdav_policy": "native_proxy",
      "down_

**Comment by xhofe** [comment]
https://github.com/djherbis/times/issues/10

**Comment by MoYuYuDe** [comment]
> [djherbis/times#10](https://github.com/djherbis/times/issues/10)

请问这个是Go 的依赖问题吗?

**Comment by ycmm3424** [comment]
我也一样，安卓版本9，在Termux中升级Alist版本到3.30.0后无法使用本地存储，但是我另一台安卓版本为11的设备升级后使用正常。

**Comment by ametoyuki098** [comment]
请问这个问题解决了吗。我好像也有同样的问题，一旦挂载本地存储，在主页中打开挂载路径时程序就会崩溃![image](https://github.com/alist-org/alist/assets/109204477/d194a49c-7a0a-468e-9589-d21cac8a0154)
