### ISSUE TITLE
请问能加入自动重载功能吗？

### ISSUE THREAD

**Issue by wangzhilin777** [alist-org/alist#5881]
挂在路由器上的，路由器重启后，不知道是不是设置问题，每次都要去手动重载一下网盘才能正常使用。希望能加入重载功能，或者延迟加载网盘功能。

**Comment by xhofe** [comment]
https://alist.nn.ci/config/configuration.html#delayed-start

**Comment by wangzhilin777** [comment]
> https://alist.nn.ci/config/configuration.html#delayed-start

我测试了，直接不启动了，😂，然后端口还被占用，重启alist也不行。只能改端口命令重启，或者改0后重启路由器才能启动。
