### ISSUE TITLE
安卓浏览器访问阿里云open错误

### ISSUE THREAD

**Issue by btrencai** [alist-org/alist#5882]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.30.3

### Driver used / 使用的存储驱动

阿里云open

### Describe the bug / 问题描述

 this XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>You are denied by bucket referer policy.</Message>
<RequestId>65A2A25652CE7136352CF92B</RequestId>
<HostId>cn-beijing-data.aliyundrive.net</HostId>
<BucketName>ccp-bj29-bj-1592982087</BucketName>
<EC>0003-00000503</EC>
<RecommendDoc>https://api.aliyun.com/troubleshoot?q=0003-00000503</RecommendDoc>
</Error>

电脑，平板均可正常下载，安卓手机浏览器出现如上问题
复制链接可以下载，点击立即下载出现以上问题

### Reproduction / 复现链接

https://down.btrencai.top/考研电子书/工程数学线性代数第六版.pdf

### Config / 配置

正常阿里云open配置

**Comment by ddjjll87** [comment]
@btrencai 我也遇到了这个情况，目前只知道是referer的原因，点击下载按钮，在head里面有<meta name="referrer" content="same-origin"，所以在head里面写<meta name="referrer" content="never"也没用，点击复制链接，粘贴直链就可以正常下载，这个情况最近才出现的

**Comment by anwen-anyi** [comment]
盲猜是 `via`浏览器?

**Comment by btrencai** [comment]
> 盲猜是 `via`浏览器?

via，夸克都这样，小米自带浏览器下载会失败

**Comment by xhofe** [comment]
请使用 Chrome/Edge。
