### ISSUE TITLE
图标引入和一致性功能建议

### ISSUE THREAD

**Issue by sudocodus** [alist-org/alist#5896]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

比如我想引入外部的矢量图标作为装饰，希望能提供方法，比如这个网站：https://pictogrammers.com

**Comment by anwen-anyi** [comment]
自己在 自定义头部引入
