### ISSUE TITLE
关于Google Photos 获取未经过任何转码的原始视频

### ISSUE THREAD

**Issue by Xiefengshang** [alist-org/alist#5897]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### 提供一个获取原始视频的按钮/接口
首先说明，原始代码没有任何问题，符合`Google Photos API`所说的获取最高质量转码视频的情况。
但是我在使用网页版获取视频时，发现可以构造出没有任何转码的源视频的URL：需要获取视频的`photoID`(和`API`获取的`media ID`完全不一样，是访问相册链接如`https://photos.google.com/share/AFXXX`，然后点击目标视频，链接会变成`https://photos.google.com/share/AFXXX/photo/photoID?key=XXX`，需要的便是这个`photoID`)，然后构造链接`https://lh3.googleusercontent.com/p/photoID=dv`，这就是未经过任何转码的源视频链接。
**所以能否提供一个获取原始视频的按钮呢？**
个人尝试过修改，但不知道如何使用`API`或者其他使用`Oauth2 Token`的方式获取`photoID`，并且`API`获取的相册`ID`是适用于`https://photos.google.com/lr/album/album-id`的而不是网页版的`https://photos.google.com/share/albumid`，所以自己不懂如何修改，请指教。

### Suggested solution / 实现思路

得到网页版的`photoID`，然后使用`https://lh3.googleusercontent.com/p/photoID=dv`作为`baseURL`。

### Additional context / 附件

在`util.go`中可以输出获取到的文件`ID`
`fmt.Println("File ID:", id)`
然后对比发现，同一文件的该`id`与`Google Photos`网页版的`id`完全不同。

**Comment by wnbh** [comment]
顶
