### ISSUE TITLE
搜索结果跳转异常

### ISSUE THREAD

**Issue by z-mio** [alist-org/alist#5900]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

Webdav

### Describe the bug / 问题描述

最新版的 AList 搜索结果链接中带了一个参数 ?from=search
打开/刷新网页后，只有第一次搜索会正常跳转，之后都会把参数当成文件名

![image](https://github.com/alist-org/alist/assets/52116367/eea53e18-e8df-48ed-9ae2-74fc50c2cb6c)
![动画](https://github.com/alist-org/alist/assets/52116367/012347a0-c953-4b53-b81e-e5620b305fcb)

### Reproduction / 复现链接

curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s install
使用脚本一键安装

### Config / 配置

无

**Comment by woshichenghaibo** [comment]
是有个

**Comment by SRainot** [comment]
插眼，在开发大佬修复之前可以暂时用伪静态暴力解决。
不用伪静态的话每次搜索后地址栏手动删一下也可以解决。
但是对于站长以外的普通用户来说，可能这个搜索功能就相当于用不了了。。好多人跟我反映说什么为啥搜什么都会404，我才发现的这个问题。。
