### ISSUE TITLE
我在使用宝塔的ftp功能，但是连接之后页面显示 550 

### ISSUE THREAD

**Issue by shxsun** [alist-org/alist#5903]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

FTP

### Describe the bug / 问题描述

我在使用宝塔的ftp功能，但是连接之后页面显示 failed get objs: failed to list objs: 550 Can't check for file existence 。在网上搜索了一下没有发现具体的解决方法。

### Reproduction / 复现链接

https://olilo.org/A

### Config / 配置

![image](https://github.com/alist-org/alist/assets/142009191/3726154b-5629-4c77-bbe9-9e3991599ee2)

**Comment by xhofe** [comment]
填写的根文件夹路径是否存在，若不存在则可能会返回这个错误。
