### ISSUE TITLE
阿里云盘上传文件的“内部上传”功能失效，因为URL的域名变了

### ISSUE THREAD

**Issue by mlkt** [alist-org/alist#5904]
### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

aliyunpan_open

### Describe the bug / 问题描述

阿里云盘上传文件的“内部上传”功能失效，因为抓包发现现在返回的域名不再是这里写死的 `cn-beijing-data.aliyundrive.net` ， 而是`bj29-enet.cn-beijing.data.alicloudccp.com`，所以替换无效

https://github.com/alist-org/alist/blob/main/drivers/aliyundrive_open/upload.go#L70

不过经过测试将返回的新域名还是直接换成 `ccp-bj29-bj-1592982087.oss-cn-beijing-internal.aliyuncs.com` 这个内部域名还是有效的，建议这个原域名和替换后的域名都搞成可配置的而不是写死，比如允许配置原域名为正则，这样就能忽略原域名具体是什么。而且我刚刚测试过，不仅上传可以用这个域名，下载也是可以的，建议也加上“内部下载”的选项(开启代理转发的情况下)。

不过话说这个内部域名 `ccp-bj29-bj-1592982087.oss-cn-beijing-internal.aliyuncs.com` 是从哪搞到的？没有搜到有相关文档，看上去和一般的OSS域名也不一样，能分享一下是怎么搞到的吗？

### Reproduction / 复现链接

往阿里云盘上传任意文件，抓包查看getUploadUrl接口返回的url

**Comment by wwkk2580** [comment]
同样问题，还以为是服务器出问题了🤔

**Comment by v2wy** [comment]
#5921

**Comment by Lang0722** [comment]
cn-beijing-data.aliyundrive.net域名能通过ipv6解析，而其他上传域名（如bj29-enet.cn-beijing.data.alicloudccp.com）则没有ipv6解析，本地网络（非北京）的ipv6上传能达到500mbps，而ipv4上传则只有30mbps
