### ISSUE TITLE
离线下载页面报错

### ISSUE THREAD

**Issue by eeviriyi** [alist-org/alist#5906]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

Onedrive and local

### Describe the bug / 问题描述

在打开 任务-离线下载 时，右上角弹出错误

![image](https://github.com/alist-org/alist/assets/110186775/8d78a8b3-c390-403b-b012-d17a1ea6e9f6)

### Reproduction / 复现链接

http://***.***.com/@manage/tasks/aria2

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "ljJrDCxc6lBRtyJt",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }

### Logs / 日志

[GIN] 2024/01/18 - 16:26:06 | 200 |      74.335µs |   183.42.139.40 | GET      "/api/admin/task/offline_download_transfer/undone"
[GIN] 2024/01/18 - 16:26:08 | 200 |     109.178µs |   183.42.139.40 | GET      "/api/admin/task/offline_download/undone"
Error #01: common.Resp[interface {}].Data: []handles.TaskInfo: handles.TaskInfo.Error: Progress: unsupported value: NaN
[GIN] 2024/01/18 - 16:26:08 | 200 |      87.022µs |   183.42.139.40 | GET      "/api/admin/task/offline_download_transfer/undone"
[GIN] 2024/01/18 - 16:26:10 | 200 |       107.7µs |   183.42.139.40 | GET      "/api/admin/task/offline_download/undone"
Error #01: common.Resp[interface {}].Data: []handles.TaskInfo: handles.TaskInfo.Error: Progress: unsupported value: NaN

**Comment by Deepsea-CN** [comment]
貌似是前端显示问题，有时候能正常显示，大概是502之类的错，总之就是刷新状态获取不到就会弹这个

**Comment by xhofe** [comment]
是离线下载到什么盘 以及离线下载的链接是什么

**Comment by Deepsea-CN** [comment]
> 是离线下载到什么盘 以及离线下载的链接是什么

任何网盘，aria2及qb都有这种情况，新版本才用这个，我观察了一下，大概就是添加新的下载任务之后后台这个页面就一直会尝试获取下载状态，然后获取不到的话就会一直弹，但是奇怪的就是这个弹出来的东西就是白的
我同时观察alist后台和aria2/qb后台，在创建任务、下载元数据的时候alist这边就会一直弹这个空白报错，开始正常下载了这边也就正常显示了，另外，手动点那个刷新也可以触发这个空白的弹窗，只要那边出现异常这边获取不到信息了就会这样，而且出现这种不同步的情况就算我点取消任务也取消不掉，删除任务了也还是会一直这个空白弹窗，重启之后恢复正常

**Comment by haohao232323** [comment]
> > 是离线下载到什么盘 以及离线下载的链接是什么
> 
> 任何网盘，aria2及qb都有这种情况，新版本才用这个，我观察了一下，大概就是添加新的下载任务之后后台这个页面就一直会尝试获取下载状态，然后获取不到的话就会一直弹，但是奇怪的就是这个弹出来的东西就是白的 我同时观察alist后台和aria2/qb后台，在创建任务、下载元数据的时候alist这边就会一直弹这个空白报错，开始正常下载了这边也就正常显示了，另外，手动点那个刷新也可以触发这个空白的弹窗，只要那边出现异常这边获取不到信息了就会这样，而且出现这种不同步的情况就算我点取消任务也取消不掉，删除任务了也还是会一直这个空白弹窗，重启之后恢复正常

请问是重启Alist还是整个宿主机，我重启Alist和Aria2后仍然弹这个错误。
![image](https://github.com/alist-org/alist/assets/42701714/f6e982ca-1711-498e-9595-8dd00f3c85e8)

**Comment by Deepsea-CN** [comment]
> > > 是离线下载到什么盘 以及离线下载的链接是什么
> > 
> > 
> > 任何网盘，aria2及qb都有这种情况，新版本才用这个，我观察了一下，大概就是添加新的下载任务之后后台这个页面就一直会尝试获取下载状态，然后获取不到的话就会一直弹，但是奇怪的就是这个弹出来的东西就是白的 我同时观察alist后台和aria2/qb后台，在创建任务、下载元数据的时候alist这边就会一直弹这个空白报错，开始正常下载了这边也就正常显示了，另外，手动点那个刷新也可以触发这个空白的弹窗，只要那边出现异常这边获取不到信息了就会这样，而且出现这种不同步的情况就算我点取消任务也取消不掉，删除任务了也还是会一直这个空白弹窗，重启之后恢复正常
> 
> 请问是重启Alist还是整个宿主机，我重启Alist和Aria2后仍然弹这个错误。并且我进入Aria2把所有任务都清空了仍然如此。 ![image](https://private-user-images.githubusercontent.com/42701714/298429340-f6e982ca-1711-498e-9595-8dd00f3c85e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTgyODAsIm5iZiI6MTcwNTkxNzk4MCwicGF0aCI6Ii80MjcwMTcxNC8yOTg0MjkzNDAtZjZlOTgyY2EtMTcxMS00OThlLTk1OTUtOGRkMDBmM2M4NWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEwMDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OWEwYjc4NDQ0M2I2N2QwNDQzOWI0YjhkOTgwMTMxYzVhOWI2NzM2M2Q2OWYxMzUzNmUxMzhlYmI3YTdhMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ymVu5X_9ZZQA6A312JLWh7AjYNWKaji4DRYwDpSg2C8)

目前的话是要重启alist或者直接重启服务器，其实一重启alist就好了，这个是alist的问题，作者已经修了，下个版本应该就好了

**Comment by haohao232323** [comment]
> > > > 是离线下载到什么盘 以及离线下载的链接是什么
> > > 
> > > 
> > > 任何网盘，aria2及qb都有这种情况，新版本才用这个，我观察了一下，大概就是添加新的下载任务之后后台这个页面就一直会尝试获取下载状态，然后获取不到的话就会一直弹，但是奇怪的就是这个弹出来的东西就是白的 我同时观察alist后台和aria2/qb后台，在创建任务、下载元数据的时候alist这边就会一直弹这个空白报错，开始正常下载了这边也就正常显示了，另外，手动点那个刷新也可以触发这个空白的弹窗，只要那边出现异常这边获取不到信息了就会这样，而且出现这种不同步的情况就算我点取消任务也取消不掉，删除任务了也还是会一直这个空白弹窗，重启之后恢复正常
> > 
> > 
> > 请问是重启Alist还是整个宿主机，我重启Alist和Aria2后仍然弹这个错误。并且我进入Aria2把所有任务都清空了仍然如此。 ![image](https://private-user-images.githubusercontent.com/42701714/298429340-f6e982ca-1711-498e-9595-8dd00f3c85e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTgyODAsIm5iZiI6MTcwNTkxNzk4MCwicGF0aCI6Ii80MjcwMTcxNC8yOTg0MjkzNDAtZjZlOTgyY2EtMTcxMS00OThlLTk1OTUtOGRkMDBmM2M4NWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEwMDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OWEwYjc4NDQ0M2I2N2QwNDQzOWI0YjhkOTgwMTMxYzVhOWI2NzM2M2Q2OWYxMzUzNmUxMzhlYmI3YTdhMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ymVu5X_9ZZQA6A312JLWh7AjYNWKaji4DRYwDpSg2C8)
> 
> 目前的话是要重启alist或者直接重启服务器，其实一重启alist就好了，你也可以进aria2的面板把不正常的任务都删干净看看，如果还不行，那就重启服务器吧，这个主要是alist的问题，作者已经修了，下个版本应该就好了

换了QB还是一样的问题，右上角弹叹号

**Comment by Deepsea-CN** [comment]
> > > > > 是离线下载到什么盘 以及离线下载的链接是什么
> > > > 
> > > > 
> > > > 任何网盘，aria2及qb都有这种情况，新版本才用这个，我观察了一下，大概就是添加新的下载任务之后后台这个页面就一直会尝试获取下载状态，然后获取不到的话就会一直弹，但是奇怪的就是这个弹出来的东西就是白的 我同时观察alist后台和aria2/qb后台，在创建任务、下载元数据的时候alist这边就会一直弹这个空白报错，开始正常下载了这边也就正常显示了，另外，手动点那个刷新也可以触发这个空白的弹窗，只要那边出现异常这边获取不到信息了就会这样，而且出现这种不同步的情况就算我点取消任务也取消不掉，删除任务了也还是会一直这个空白弹窗，重启之后恢复正常
> > > 
> > > 
> > > 请问是重启Alist还是整个宿主机，我重启Alist和Aria2后仍然弹这个错误。并且我进入Aria2把所有任务都清空了仍然如此。 ![image](https://private-user-images.githubusercontent.com/42701714/298429340-f6e982ca-1711-498e-9595-8dd00f3c85e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTgyODAsIm5iZiI6MTcwNTkxNzk4MCwicGF0aCI6Ii80MjcwMTcxNC8yOTg0MjkzNDAtZjZlOTgyY2EtMTcxMS00OThlLTk1OTUtOGRkMDBmM2M4NWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEwMDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OWEwYjc4NDQ0M2I2N2QwNDQzOWI0YjhkOTgwMTMxYzVhOWI2NzM2M2Q2OWYxMzUzNmUxMzhlYmI3YTdhMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ymVu5X_9ZZQA6A312JLWh7AjYNWKaji4DRYwDpSg2C8)
> > 
> > 
> > 目前的话是要重启alist或者直接重启服务器，其实一重启alist就好了，你也可以进aria2的面板把不正常的任务都删干净看看，如果还不行，那就重启服务器吧，这个主要是alist的问题，作者已经修了，下个版本应该就好了
> 
> 换了QB还是一样的问题，右上角弹叹号

目前版本的解决方案（个人测试）先重启服务器，然后使用离线下载的时候一次只发布一个任务，如果下不动了点删除删不干净就去aria2和qb后台删任务，不然就一直弹
