### ISSUE TITLE
Alibaba Cloud Linux 3中不管是一键安装还是手动安装，都失败！

### ISSUE THREAD

**Issue by hack0573** [alist-org/alist#5913]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30

### Driver used / 使用的存储驱动

未到挂载驱动这一步

### Describe the bug / 问题描述

一键脚本安装如下：

下载 Alist latest ...
#################################### 50.7%
curl: (18) transfer closed with 12005258 bytes remaining to read

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
下载成功
Alist 安装成功！

访问地址：http://YOUR_IP:5244/

配置文件路径：/home/alist/data/config.json
---------如何获取密码？--------
先cd到alist所在目录:
cd /home/alist
随机设置新密码:
./alist admin random
或者手动设置新密码:
./alist admin set NEW_PASSWORD
启动服务中

查看状态：systemctl status alist
启动服务：systemctl start alist
重启服务：systemctl restart alist
停止服务：systemctl stop alist

温馨提示：如果端口无法正常访问，请检查 服务器安全组、本机防火墙、Alist状态

[root@hqwaliyun2024 home]# ^C
[root@hqwaliyun2024 home]# pwd
/home
[root@hqwaliyun2024 home]# cd alist/
[root@hqwaliyun2024 alist]# ll
total 32928
-rwx------ 1 root root 33718272 Jan 19 11:23 alist
[root@hqwaliyun2024 alist]# ./alist admin set xxxxxx
Segmentation fault
[root@hqwaliyun2024 alist]# ./alist admin random
Segmentation fault
[root@hqwaliyun2024 alist]# ^C
[root@hqwaliyun2024 alist]# systemctl status alist
● alist.service - Alist service
Loaded: loaded (/etc/systemd/system/alist.service; enabled; vendor preset: enabled)
Active: failed (Result: signal) since Fri 2024-01-19 11:23:26 CST; 12min ago
Process: 24248 ExecStart=/home/alist/alist server (code=killed, signal=SEGV)
Main PID: 24248 (code=killed, signal=SEGV)

Jan 19 11:23:26 hqwaliyun2024 systemd[1]: Started Alist service.
Jan 19 11:23:26 hqwaliyun2024 systemd[1]: alist.service: Main process exited, code=killed, status=1>
Jan 19 11:23:26 hqwaliyun2024 systemd[1]: alist.service: Failed with result 'signal'.

[root@hqwaliyun2024 alist]# systemctl start alist
[root@hqwaliyun2024 alist]# systemctl status alist
● alist.service - Alist service
Loaded: loaded (/etc/systemd/system/alist.service; enabled; vendor preset: enabled)
Active: failed (Result: signal) since Fri 2024-01-19 11:36:08 CST; 3s ago
Process: 24304 ExecStart=/home/alist/alist server (code=killed, signal=SEGV)
Main PID: 24304 (code=killed, signal=SEGV)
========================================
手动安装同样失败：

[root@hqwaliyun2024 alist]# ./alist server
INFO[2024-01-19 14:32:41] reading config file: data/config.json        
INFO[2024-01-19 14:32:41] load config from env with prefix: ALIST_     
INFO[2024-01-19 14:32:41] init logrus...                               
WARN[2024-01-19 14:32:41] init tool qBittorrent failed: Post "http://localhost:8080/api/v2/auth/login": dial tcp [::1]:8080: connect: connection refused 
WARN[2024-01-19 14:32:41] init tool aria2 failed: failed get aria2 version: Post "http://localhost:6800/jsonrpc": dial tcp [::1]:6800: connect: connection refused 
INFO[2024-01-19 14:32:41] init tool SimpleHttp success: ok             
INFO[2024-01-19 14:32:41] start HTTP server @ 0.0.0.0:5244             

### Reproduction / 复现链接

无链接

### Config / 配置

[Unit]
Description=alist
After=network.target
 
[Service]
Type=simple
WorkingDirectory=/home/alist
ExecStart=path_alist/alist server
Restart=on-failure
 
[Install]
WantedBy=multi-user.target

**Comment by xhofe** [comment]
脚本为网络问题 请自行解决

手动为已经在运行中 无问题

**Comment by RiverChu0** [comment]
这个问题我也遇到了。
后面发现是`GH_PROXY`这个变量引起的！根本不需要用这个加速。
把一键安装脚本下载到你的VPS，然后定位到`GH_PROXY='https://mirror.ghproxy.com/'`改为`GH_PROXY=‘’`，使用`less v3.sh | bash -s install`进行安装就可以了
