### ISSUE TITLE
钉钉单点登录校验是否为企业内部人员

### ISSUE THREAD

**Issue by judiw** [alist-org/alist#5917]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前钉钉单点登录在开启自动注册的前提下，任何钉钉账号均可在登录后自动注册，在企业内部应用的场景下容易出现安全风险，建议增加企业内部人员校验开关

### Suggested solution / 实现思路

在调用[获取用户通讯录个人信息](https://open.dingtalk.com/document/orgapp/dingtalk-retrieve-user-information)获取到unionid后，再调用[根据unionid获取用户userid](https://open.dingtalk.com/document/orgapp/query-a-user-by-the-union-id)：
返回 code 为 60121 则非企业内人员，不允许注册；
返回 code 为 0 则为为企业内人员，允许自动注册。

### Additional context / 附件

![image](https://github.com/alist-org/alist/assets/38564340/abeafc1c-4439-4bd1-91da-c1854b36e76f)

**Comment by Vito-huanghk** [comment]
哥 这个在docker 上面怎么实现呢？
