### ISSUE TITLE
希望支持freeBSD

### ISSUE THREAD

**Issue by csuleiw** [alist-org/alist#5918]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前官方编译没有freeBSD版本，希望增加这一版本。

**Comment by itsHenry35** [comment]
freeBSD好像可以开启linux二进制文件兼容吧，应该用linux的就可以了
https://docs.freebsd.org/en/books/handbook/linuxemu/
