### ISSUE TITLE
cloudflare workers代理 500错误

### ISSUE THREAD

**Issue by ypq123456789** [alist-org/alist#5924]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

播放onedrive视频使用cloudflare workers代理，提示500 Internal Server Error，视频无法播放。

### Reproduction / 复现链接

如需调试，可邮箱告知网站账号密码

### Config / 配置

![1705747700086](https://github.com/alist-org/alist/assets/114487221/b8dbc32b-80c0-4c50-a321-4c50dbd694f1)

### Logs / 日志

cloudflare的日志：
{
  "outcome": "exception",
  "scriptName": "alist",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "name": "SyntaxError",
      "message": "Unexpected token 'e', \"error code: 520\" is not valid JSON",
      "timestamp": 1705744780371
    }
  ],
  "logs": [],
  "eventTimestamp": 1705744780117,
  "event": {
    "request": {
      "url": "https://p.bacon123.eu.org/onedrive%20%E7%9B%B4%E8%BF%9E/%E5%9B%BD%E4%BA%A7%E7%B2%BE%E5%93%81/%E2%80%98%E4%BD%A0%E5%A5%BD%E5%85%88%E7%94%9F%E2%80%99%E5%8F%8C%E9%A9%AC%E5%B0%BE%E8%90%9D%E8%8E%89%E7%BE%8E%E5%B0%91%E5%A5%B3%E5%86%85%E5%B0%84%E8%AE%B0%EF%BC%8C%E7%9C%8B%E5%87%A0%E6%AC%A1%E9%83%BD%E9%9A%BE%E4%BB%A5%E5%BF%98%E6%80%80%21.mp4?sign=REDACTED=:1705960779",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "cf-connecting-ip": "112.3.236.102",
        "cf-ipcountry": "CN",
        "cf-ray": "8486774bbb1cb1e6",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "p.bacon123.eu.org",
        "user-agent": "nPlayer/3.0",
        "x-forwarded-proto": "https",
        "x-real-ip": "112.3.236.102"
      },
      "cf": {
        "clientTcpRtt": 42,
        "longitude": "118.77380",
        "latitude": "32.05890",
        "tlsCipher": "ECDHE-RSA-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 56046,
        "country": "CN",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "",
          "clientHandshake": "",
          "serverHandshake": "",
          "serverFinished": ""
        },
        "tlsVersion": "TLSv1.2",
        "city": "Nanjing",
        "timezone": "Asia/Shanghai",
        "colo": "HKG",
        "region": "Jiangsu",
        "requestPriority": "",
        "verifiedBotCategory": "",
        "httpProtocol": "HTTP/1.1",
        "regionCode": "JS",
        "asOrganization": "China Mobile",
        "edgeRequestKeepAliveStatus": 1
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 38
}

浏览器f12的提示：
请求网址:
https://p.bacon123.eu.org/onedrive%20%E7%9B%B4%E8%BF%9E/%E6%98%8E%E6%98%9F/%E5%88%98%E4%BA%A6%E8%8F%B2%E6%8D%A2%E8%84%B8.mp4?sign=J-DiQqHY6pKGwLcBjjHQ9TrQ2qZIsTY456KC9fEn1p0=:1705962903
请求方法:
GET
状态代码:
500 Internal Server Error
远程地址:
127.0.0.1:10809
引荐来源网址政策:
same-origin
Alt-Svc:
h3=":443"; ma=86400
Cache-Control:
private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cf-Ray:
8486ab55c82d7d2c-HKG
Content-Length:
4303
Content-Type:
text/html; charset=UTF-8
Date:
Sat, 20 Jan 2024 10:35:11 GMT
Expires:
Thu, 01 Jan 1970 00:00:01 GMT
Nel:
{"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Referrer-Policy:
same-origin
Report-To:
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=fkXKSmlsfBN%2Fcry%2B59cmiPDjsAMhetVYJwkQty%2BpTOpCOwfKqCKQqlmUuB1X278DhT4Mpn0L1PoemBTn5jGq%2BG5gvs9Y02jNqyiPWWqGJO%2FkweTz65KZxG3zQT7ii4yW0pU53A%3D%3D"}],"group":"cf-nel","max_age":604800}
Server:
cloudflare
Vary:
Accept-Encoding
X-Frame-Options:
SAMEORIGIN
:authority:
p.bacon123.eu.org
:method:
GET
:path:
/onedrive%20%E7%9B%B4%E8%BF%9E/%E6%98%8E%E6%98%9F/%E5%88%98%E4%BA%A6%E8%8F%B2%E6%8D%A2%E8%84%B8.mp4?sign=J-DiQqHY6pKGwLcBjjHQ9TrQ2qZIsTY456KC9fEn1p0=:1705962903
:scheme:
https
Accept:
*/*
Accept-Encoding:
identity;q=1, *;q=0
Accept-Language:
zh-CN,zh;q=0.9
Range:
bytes=0-
Sec-Ch-Ua:
"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
video
Sec-Fetch-Mode:
no-cors
Sec-Fetch-Site:
same-site
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by xhofe** [comment]
脚本里的地址怎么填的

**Comment by ypq123456789** [comment]
> 脚本里的地址怎么填的

// src/const.ts
var ADDRESS = "https://alist.bacon123.eu.org";
var TOKEN = "打码";

// src/verify.ts
var verify = async (data, _sign) => {
  const signSlice = _sign.split(":");
  if (!signSlice[signSlice.length - 1]) {
    return "expire missing";
  }
  const expire = parseInt(signSlice[signSlice.length - 1]);
  if (isNaN(expire)) {
    return "expire invalid";
  }
  if (expire < Date.now() / 1e3 && expire > 0) {
    return "expire expired";
  }
  const right = await hmacSha256Sign(data, expire);
  if (_sign !== right) {
    return "sign mismatch";
  }
  return "";
};
var hmacSha256Sign = async (data, expire) => {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(TOKEN),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign", "verify"]
  );
  const buf = await crypto.subtle.sign(
    {
      name: "HMAC",
      hash: "SHA-256"
    },
    key,
    new TextEncoder().encode(`${data}:${expire}`)
  );
  return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g, "-").replace(/\//g, "_") + ":" + expire;
};

// src/handleDownload.ts
async function handleDownload(request) {
  const origin = request.headers.get("origin") ?? "*";
  const url = new URL(request.url);
  const path = decodeURIComponent(url.pathname);
  const sign = url.searchParams.get("sign") ?? "";
  const verifyResult = await verify(path, sign);
  if (verifyResult !== "") {
    const resp2 = new Response(
      JSON.stringify({
        code: 401,
        message: verifyResult
      }),
      {
        headers: {
          "content-type": "application/json;charset=UTF-8"
        }
      }
    );
    resp2.headers.set("Access-Control-Allow-Origin", origin);
    return resp2;
  }
  let resp = await fetch(`${ADDRESS}/api/fs/link`, {
    method: "POST",
    headers: {
      "content-type": "application/json;charset=UTF-8",
      Authorization: TOKEN
    },
    body: JSON.stringify({
      path
    })
  });
  let res = await resp.json();
  if (res.code !== 200) {
    return new Response(JSON.stringify(res));
  }
  request = new Request(res.data.url, request);
  request = new Request(request, { redirect: "follow" });
  if (res.data.header) {
    for (const k in res.data.header) {
      for (const v of res.data.header[k]) {
        request.headers.set(k, v);
      }
    }
  }
  let response = await fetch(request);
  response = new Response(response.body, response);
  response.headers.delete("set-cookie");
  response.headers.set("Access-Control-Allow-Origin", origin);
  response.headers.append("Vary", "Origin");
  return response;
}

// src/handleOptions.ts
function handleOptions(request) {
  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET,HEAD,POST,OPTIONS",
    "Access-Control-Max-Age": "86400"
  };
  let headers = request.headers;
  if (headers.get("Origin") !== null && headers.get("Access-Control-Request-Method") !== null) {
    let respHeaders = {
      ...corsHeaders,
      "Access-Control-Allow-Headers": request.headers.get("Access-Control-Request-Headers") || ""
    };
    return new Response(null, {
      headers: respHeaders
    });
  } else {
    return new Response(null, {
      headers: {
        Allow: "GET, HEAD, POST, OPTIONS"
      }
    });
  }
}

// src/index.ts
var src_default = {
  async fetch(request, env, ctx) {
    if (request.method === "OPTIONS") {
      return handleOptions(request);
    }
    return handleDownload(request);
  }
};
export {
  src_default as default
};
//# sourceMappingURL=index.js.map

**Comment by xhofe** [comment]
地址需要携带协议 如 https://

**Comment by ypq123456789** [comment]
> 地址需要携带协议 如 https://
都是有的呀
![1705759599901](https://github.com/alist-org/alist/assets/114487221/e456b5ab-1710-4e42-bf9e-be442f2de781)
![1705759638141](https://github.com/alist-org/alist/assets/114487221/1ef3b710-1fc5-4fd0-9b49-6ea05d5d357f)

**Comment by sd14** [comment]
你脚本里改成
var ADDRESS = "http://alist.bacon123.eu.org:5244";
就可以了

**Comment by ypq123456789** [comment]
好的我试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月22日(周一) 凌晨4:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alist-org/alist] cloudflare workers代理 500错误 (Issue #5924)




 
你脚本里改成
 var ADDRESS = "http://alist.bacon123.eu.org:5244";
 就可以了

**Comment by ypq123456789** [comment]
真的可以了，谢谢老哥，帮大忙了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月22日(周一) 凌晨4:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alist-org/alist] cloudflare workers代理 500错误 (Issue #5924)




 
你脚本里改成
 var ADDRESS = "http://alist.bacon123.eu.org:5244";
 就可以了
