### ISSUE TITLE
在向蓝奏云优享版上传较大文件时上传出现错误（-1: token不能为空！

### ISSUE THREAD

**Issue by fly-pigawa** [alist-org/alist#5928]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

蓝奏云优享版

### Describe the bug / 问题描述

在向蓝奏云优享版上传较大文件时上传出现错误（本文件约3G（-1: token不能为空！
前端提示成功，此时后台任务处显示正在上传，稍候显示“-1: token不能为空！”
![image](https://github.com/alist-org/alist/assets/103082780/981cf89d-9f8d-4351-87ef-7e4ef71781ca)

### Reproduction / 复现链接

抱歉，由于站点为个人使用且服务器服务器使用国内主机且暂未备案、绑定域名，直接放出ip有一定风险，如需要可复现链接麻烦回复

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "oOoeTwYK1hIyH0aR",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data\\data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data\\temp",
  "bleve_dir": "data\\bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data\\log\\log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}
![image](https://github.com/alist-org/alist/assets/103082780/fc97bf47-9f5a-40e5-9377-dfbaf4b92e42)
![Uploading image.png…]()

### Logs / 日志

[GIN] 2024/01/21 - 14:31:07 | 200 |    813.4997ms |       127.0.0.1 | PUT      "/api/fs/put"
2024/01/21 14:31:07 INFO worker execute task worker=3 task=vf4mfLmb_MtobsRgeuYdq
[36mINFO[0m[2024-01-21 14:31:11] index obj count: 3                           
[GIN] 2024/01/21 - 14:31:12 | 200 |     91.9907ms |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:31:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:31:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:31:38] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:31:43] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:31:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:31:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:31:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:03] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:32:12 | 200 |      2.0041ms |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:32:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:38] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:43] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:32:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:03] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:33:12 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:33:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:38] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:43] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:33:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:03] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:34:12 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:34:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:38] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:43] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:34:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:03] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:35:12 | 200 |      2.4959ms |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:35:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:38] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:43] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:35:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:03] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:36:12 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:36:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:38] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:43] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:36:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:37:03] index obj count: 3                           
2024/01/21 14:37:05 INFO worker execute task worker=0 task=IsTiyqrOjzSLJEVzhYcjV
[GIN] 2024/01/21 - 14:37:05 | 200 |    229.2602ms |       127.0.0.1 | PUT      "/api/fs/put"
[GIN] 2024/01/21 - 14:37:07 | 200 |       124.8µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:09 | 200 |       499.5µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:11 | 200 |       285.8µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:13 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:13] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:15 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:17 | 200 |       204.7µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:18] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:19 | 200 |       409.9µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:21 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:23 | 200 |       382.2µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:23] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:25 | 200 |       181.8µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:27 | 200 |       369.2µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:28] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:29 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:31 | 200 |       486.9µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:33 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:33] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:35 | 200 |         462µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:37 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:38] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:39 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:41 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:43 | 200 |       166.1µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:43] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:45 | 200 |       120.1µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:47 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
2024/01/21 14:37:47 INFO worker execute task worker=2 task=CxvsBId5rO_xpgfFq3pTQ
[GIN] 2024/01/21 - 14:37:47 | 200 |    748.5863ms |       127.0.0.1 | PUT      "/api/fs/put"
[36mINFO[0m[2024-01-21 14:37:48] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:49 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:51 | 200 |       404.3µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:53 | 200 |         211µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:53] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:55 | 200 |       159.8µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:37:57 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:37:58] index obj count: 3                           
[GIN] 2024/01/21 - 14:37:59 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:01 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:03 | 200 |       136.7µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:38:03] index obj count: 3                           
[GIN] 2024/01/21 - 14:38:05 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:07 | 200 |         172µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:38:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:38:12 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:38:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:38:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:38:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:38:28] index obj count: 3                           
[GIN] 2024/01/21 - 14:38:32 | 200 |       219.1µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:32 | 200 |        92.2µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:38:33] index obj count: 3                           
[GIN] 2024/01/21 - 14:38:34 | 200 |          77µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:36 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:38:38] index obj count: 3                           
[GIN] 2024/01/21 - 14:38:38 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:40 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:42 | 200 |        74.9µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:38:43] index obj count: 3                           
[GIN] 2024/01/21 - 14:38:44 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:46 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:38:48] index obj count: 3                           
[GIN] 2024/01/21 - 14:38:48 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:51 | 200 |       349.4µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:53 | 200 |       475.6µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:38:53] index obj count: 3                           
[GIN] 2024/01/21 - 14:38:55 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:38:57 | 200 |       154.5µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:38:58] index obj count: 3                           
[GIN] 2024/01/21 - 14:38:59 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:01 | 200 |         249µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:03 | 200 |       426.7µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:03] index obj count: 3                           
[GIN] 2024/01/21 - 14:39:05 | 200 |        74.6µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:07 | 200 |       464.5µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:39:09 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:11 | 200 |       258.3µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:13 | 200 |       299.6µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:13] index obj count: 3                           
[GIN] 2024/01/21 - 14:39:15 | 200 |       403.4µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:17 | 200 |         504µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:18] index obj count: 3                           
[GIN] 2024/01/21 - 14:39:19 | 200 |       500.5µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:21 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:23 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:23] index obj count: 3                           
[GIN] 2024/01/21 - 14:39:25 | 200 |         490µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:27 | 200 |       200.4µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:28] index obj count: 3                           
[GIN] 2024/01/21 - 14:39:29 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:31 | 200 |       301.7µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:33 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:33] index obj count: 3                           
[GIN] 2024/01/21 - 14:39:35 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:37 | 200 |       118.5µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:38] index obj count: 3                           
[GIN] 2024/01/21 - 14:39:39 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:41 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:43 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:43] index obj count: 3                           
[GIN] 2024/01/21 - 14:39:45 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:39:47 | 200 |       182.1µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:39:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:39:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:39:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:03] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:40:12 | 200 |       181.3µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:40:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:38] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:43] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:40:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:41:03] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:41:08] index obj count: 3                           
[GIN] 2024/01/21 - 14:41:12 | 200 |     26.5293ms |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:41:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:41:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:41:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:41:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:41:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:41:38] index obj count: 3                           
[GIN] 2024/01/21 - 14:41:41 | 200 |       285.7µs |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[GIN] 2024/01/21 - 14:41:42 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/task/upload/undone"
[36mINFO[0m[2024-01-21 14:41:43] index obj count: 3                           
[GIN] 2024/01/21 - 14:41:45 | 200 |    198.0651ms |       127.0.0.1 | GET      "/api/admin/setting/list?group=1"
[36mINFO[0m[2024-01-21 14:41:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:41:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:41:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:03] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:08] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:38] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:43] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:48] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:53] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:42:58] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:43:03] index obj count: 3                           
[GIN] 2024/01/21 - 14:43:04 | 200 |       504.1µs |       127.0.0.1 | GET      "/api/admin/driver/names"
[GIN] 2024/01/21 - 14:43:04 | 200 |       999.2µs |       127.0.0.1 | GET      "/api/admin/storage/list"
[GIN] 2024/01/21 - 14:43:05 | 200 |       499.2µs |       127.0.0.1 | GET      "/assets/AddOrEdit.e153aa6c.js"
[GIN] 2024/01/21 - 14:43:05 | 200 |         500µs |       127.0.0.1 | GET      "/api/admin/storage/get?id=4"
[GIN] 2024/01/21 - 14:43:05 | 200 |       499.9µs |       127.0.0.1 | GET      "/api/admin/driver/info?driver=ILanZou"
[36mINFO[0m[2024-01-21 14:43:08] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:43:13] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:43:18] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:43:23] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:43:28] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:43:33] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:43:38] index obj count: 3                           
[36mINFO[0m[2024-01-21 14:43:43] index obj count: 3

**Comment by xhofe** [comment]
这应该在 555ef0e 中被修复。

**Comment by eritpchy** [comment]
<img width="457" alt="image" src="https://github.com/user-attachments/assets/70f0c8c6-3655-4d5d-98e4-4efe9c60dee0">
目前测试latest 和 main 还是有这个问题, 网页上传60m的文件 

选择Stream出现“-1: token不能为空！” 
选择Form则成功

**Comment by eritpchy** [comment]
<img width="851" alt="image" src="https://github.com/user-attachments/assets/911fe95a-fd8c-477e-a437-80d92e2eaa51">

看起来是秒传了
