### ISSUE TITLE
阿里云盘open怎么没了

### ISSUE THREAD

**Issue by ding00006** [alist-org/alist#5936]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

之前有的，后来盒子坏了重新装了Openwrt，就发现alist里面的阿里云盘open不见了，只有“阿里云盘”的“阿里云盘分享”两个了。版本是3.30
![1](https://github.com/alist-org/alist/assets/100015168/60a729b0-0f4c-4053-a94a-198ed57c2f2d)
![2](https://github.com/alist-org/alist/assets/100015168/384203f4-1b0f-47e2-9d9b-7eab733163ca)

**Comment by anwen-anyi** [comment]
更新版本去 你这个明显不是

这里显示3.30是ALlist版本  不是你安装的版本
![image](https://github.com/alist-org/alist/assets/56105412/44733b7a-2649-4109-8284-45f159965080)
