### ISSUE TITLE
是否可能支持jpeg-xl格式的预览？

### ISSUE THREAD

**Issue by IvanmaAcademic** [alist-org/alist#5940]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题所述，支持使用内置的image预览而无需外部预览或iframe

**Comment by URenko** [comment]
使用 Firefox nightly 开启 JPEG XL 支持再将扩展名加入预览列表可以预览。
