### ISSUE TITLE
docker版alist，aria2本地下载出错，xhofe/alist-aria2

### ISSUE THREAD

**Issue by arstum** [alist-org/alist#5943]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

docker pull xhofe/alist-aria2:latest

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

问题：能离线下载文件到百度网盘，但不能从百度网盘下载文件到本地，只尝试过使用 前端界面--> “发送到 aria2”，失败，提示“Failed to send to aria2: AxiosError: Network Error”

时间：2024年1月24日
使用 docker pull xhofe/alist-aria2:latest，alist已经设置为ssl（https）登陆，登陆主页和管理页面正常，都是https登陆。
具体情况：
1.后台管理-->设置-->其他 aria2离线从网站下载文件到百度网盘顺利。
2.前端界面-->本地设置（右下角的齿轮）aria2本地下载百度网盘文件出错，提示“Failed to send to aria2: AxiosError: Network Error”
措施：
1.核对aria2的离线下载，本地下载的配置，一致，但不是https,而是http的，不知道有没有影响。
2.尝试在.前端界面-->本地设置（右下角的齿轮），将Aria2 地址从默认的http改为https,还是出现一样的错误，提示“Failed to send to aria2: AxiosError: Network Error”。

最终还是不能从百度网盘下载文件到本地，不知道哪里出问题了。

### Reproduction / 复现链接

![Uploading 2024-01-24-200243_1920x1080_scrot.png…]()

### Config / 配置

docker run -d --restart=unless-stopped \
   -v /etc/alist:/opt/alist/data \
   -v $PWD/.acme.sh/xxx.cfd_ecc/:/root/cert/ \
   -p 5243:5244 -e PUID=0 -e PGID=0 -e UMASK=022 \
   --name="alist" xhofe/alist-aria2:latest

后台管理-->设置-->其他
Aria2 地址
http://localhost:6800/jsonrpc 
Aria2 密钥
1Fvoyi`[:Z5:){DU"

前端界面-->本地设置（右下角的齿轮）
Aria2 RPC 链接
http://localhost:6800/jsonrpc 
Aria2 RPC 密钥
1Fvoyi`[:Z5:){DU"

**Comment by IAALAI** [comment]
它们是在同一个容器中吗?有没有正确的设置端口的映射？

**Comment by xhofe** [comment]
alist-aria2默认未映射端口 请自行添加端口映射

**Comment by arstum** [comment]
> alist-aria2默认未映射端口 请自行添加端口映射

假设是端口问题，为什么
后台管理-->设置-->其他 aria2离线从网站下载文件到百度网盘顺利。

**Comment by arstum** [comment]
> 它们是在同一个容器中吗?有没有正确的设置端口的映射？
xhofe/alist-aria2:latest是官方推荐docker,内置 aria2 离线下载

**Comment by pansila** [comment]
碰到了同样的问题，discussion里面也有反馈，https://github.com/alist-org/alist/discussions/5886。我用的network时host模式，但是看不到6800暴露出来，只有5244。改成bridge后，加了两个端口的映射，但是进容器里netstat也看不到6800

**Comment by hdzj-1981** [comment]
> alist-aria2默认未映射端口请自行添加端口映射

host网络模式如何映射端口？

**Comment by Yxini-p** [comment]
+1 查看了文档还是不知道alist-aria2的密钥怎么获取，而且也是提示网络错误；有没有人解答一下；

**Comment by LancelotOho** [comment]
我是正常下载单文件就报：Failed to send to aria2: AxiosError: Network Error alist
我后来这样解决了。关于Aria2的设置有两处
一处在管理，其他，里面填好aria2的参数。另一处是在主页，右下角本地设置里还有aria2的参数。写全，写对。
希望有参考价值
