### ISSUE TITLE
关于alist自动更新token的建议

### ISSUE THREAD

**Issue by 1746390664** [alist-org/alist#5945]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

开发者能否根据52破解发表的一篇云盘自动签到脚本自动更新token的脚本，做一个自动更新token的alist
#https://www.52pojie.cn/thread-1869673-1-1.html

### Suggested solution / 实现思路

// 主要代码
 let my_token = HTTP.post("https://auth.aliyundrive.com/v2/account/token",
                                JSON.stringify({
                                    "grant_type": "refresh_token",
                                    "refresh_token": refresh_token
                                }));
                            my_token = my_token.json()["refresh_token"]

**Comment by anwen-anyi** [comment]
什么token？ 你说的这个token和AList的使用的token不是一个，而且AList挂载的阿里云盘token是会自动刷新的
- 不太理解你需要什么

-----

- 你提供的是自己抓包的token
   - 直接获取的是阿里云盘官方的
   - 是否会自动刷新不清楚
- AList使用的是通过开发者ID和秘钥然后授权获取的
   - AList授权获取的是携带开发者应用信息的token
   - 这个会自动刷新
