### ISSUE TITLE
支持下m3u8和.m3u文件后缀的在线修改

### ISSUE THREAD

**Issue by hayXiang** [alist-org/alist#5946]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

本地放了一堆.m3u8后缀的IPTV信源，发现alist只能下载，没法编辑，请直接下

### Suggested solution / 实现思路

请支持下用户自定义文件后缀可编辑。

**Comment by xhofe** [comment]
https://alist.nn.ci/config/preview.html#text-types
