### ISSUE TITLE
feature: 302地址缓存

### ISSUE THREAD

**Issue by 8MiYile** [alist-org/alist#5949]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能将请求的302地址缓存起来，然后第二次调用就能快速拉取，然后过期方式和缓存过期方式一样
因为我发现多个IP同时请求的情况下 有概率gateway-timeout或者499错误
然后还希望自动预先缓存302
自动缓存指定路径下的文件的302地址

### Suggested solution / 实现思路

可以数据库/Redis

**Comment by 8MiYile** [comment]
@xhofe 为什么不会做这方面的支持呢？

**Comment by xhofe** [comment]
https://github.com/alist-org/alist/blob/aef952ae6815d6d52d74b8cb95f0ca414e00a8b9/internal/model/args.go#L31

**Comment by 8MiYile** [comment]
嗯 这个指的是 在用户请求的时候才去获取地址并缓存
我希望的是 能预先缓存某个路径下的所有302地址，并循环式刷新
https://bd.bangbang93.com
这个网站记录了请求量
我的Nginx几乎有499和50x的报错
我等会把日志贴出来你就懂了

**Comment by 8MiYile** [comment]
@xhofe 我希望你能移除invaid 然后重新决定是否做支持

**Comment by 8MiYile** [comment]
@xhofe 哎呀早说nginx有缓存功能不就行了哈哈哈哈

**Comment by wzdc** [comment]
你好，我也遇到这种问题了，有办法可以缓存302链接吗？

**Comment by 8MiYile** [comment]
@wzdc 
https://github.com/alist-org/alist/issues/5949#issuecomment-1911933765

**Comment by wzdc** [comment]
> @xhofe 哎呀早说nginx有缓存功能不就行了哈哈哈哈

nginx的缓存只能固定时间，网盘的文件链接过期时间不固定但是在GET参数里可以看到过期时间戳
