### ISSUE TITLE
[bug] 当别名中有两个来源不同的相同路径合并时 大小计算出错

### ISSUE THREAD

**Issue by shoucandanghehe** [alist-org/alist#5953]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

Onedrive + 别名

### Describe the bug / 问题描述

当别名中有两个来源不同的相同路径合并
并且内容并不相同时
外层文件夹大小计算出错
![image](https://github.com/alist-org/alist/assets/51957264/5dbbb210-1637-4817-a8bf-d6e89c235313)
![image](https://github.com/alist-org/alist/assets/51957264/63fe5939-6273-44ce-b392-7ec0a5796c1d)
```
drive1
└─test
   └─path # 共同路径
       └─path1

drive2
└─test
   └─path # 共同路径
       └─path2
```

### Reproduction / 复现链接

https://alist.xn--dtra.com/bug

### Config / 配置

![image](https://github.com/alist-org/alist/assets/51957264/78a6cdd3-51c0-45cc-9b9e-6a1f76c866b9)

**Comment by xhofe** [comment]
仅onedrive的文件夹拥有大小，故暂不对文件夹进行大小计算处理。
