### ISSUE TITLE
夸克网盘下载空文件报错

### ISSUE THREAD

**Issue by linkq** [alist-org/alist#5963]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30`

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

下载大小为0的空文件时报“index out of range [0] with length 0”
从夸克网盘能正常下载
![image](https://github.com/alist-org/alist/assets/3353261/d3ac2cdb-94c5-4238-ab6c-12b152ae8d84)
![image](https://github.com/alist-org/alist/assets/3353261/b09ae31b-5cb8-47b3-badc-1281b900f9d7)
![1706450301045](https://github.com/alist-org/alist/assets/3353261/1970d3a0-5472-4941-8e5e-98aa2939f5e9)

### Reproduction / 复现链接

https://alist.linkq.xyz:4443/p/Quark/NAS/Ds-lin_1.hbk/Control/@reader.8f54c590-c198-4537-a0b0-6fb02c44dfcd/23.cinfo?sign=w9BtAXnevnFfEcYvGIIYsCeTupx9ShJDmA8qx3jAxmg=:1706453390

### Config / 配置

![1706449920051](https://github.com/alist-org/alist/assets/3353261/a2547847-7a3a-40f1-8b14-81731cad37d3)

### Logs / 日志

[GIN] 2024/01/28 - 21:07:52 | 500 |  117.863036ms |    192.168.31.2 | GET      "/d/Quark/NAS/Ds-lin_1.hbk/Control/@reader.8f54c590-c198-4537-a0b0-6fb02c44dfcd/23.cinfo?sign=c0roZtgl7y0pzWDmFqNnKJZKReAA7Uy6inz77tdTRxQ=:1706450869"

2024/01/28 21:07:53 [Recovery] 2024/01/28 - 21:07:53 panic recovered:
runtime error: index out of range [0] with length 0
/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:114 (0x439bbb)
/home/runner/work/alist/alist/internal/net/request.go:154 (0xbc8bdb)
/home/runner/work/alist/alist/internal/net/request.go:86 (0xbc853d)
/home/runner/work/alist/alist/server/common/proxy.go:50 (0xd7562b)
/home/runner/work/alist/alist/internal/net/serve.go:114 (0xbcb393)
/home/runner/work/alist/alist/server/common/proxy.go:54 (0xd74b64)
/home/runner/work/alist/alist/server/handles/down.go:109 (0x165a22f)
/home/runner/work/alist/alist/server/handles/down.go:30 (0x16599bb)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1618333)
/home/runner/work/alist/alist/server/middlewares/down.go:40 (0x1618298)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1617dc5)
/home/runner/work/alist/alist/server/middlewares/check.go:14 (0x1617db3)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd69679)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0xd69667)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd6881d)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0xd687e0)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd678da)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0xd6756d)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0xd6709c)
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2938 (0x7426ed)
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2009 (0x73e5d3)
/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/asm_amd64.s:1650 (0x472c40)

**Comment by ickacn** [comment]
每次下載的夸克的文件，如果裏面有大小是0的文件，比如就一個txt，裏面沒東西，比如有的人上傳壓縮文件，弄個txt，名字是解壓縮密碼，這樣下載，那個txt檔案會下載不下來，就報錯，其他的檔案就可以下載下來。百度等下載0字節大小的沒問題 。目前只有遇見夸克會這樣，和樓主的問題相同。我用其他的下載工具連alist下載空文件是提示500錯誤。
