### ISSUE TITLE
希望可以增加明文保存密码的开关

### ISSUE THREAD

**Issue by Aurora211** [alist-org/alist#5966]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我的服务器部署在内网，有时家人会忘记密码，每次忘记密码就需要重置数据库非常繁琐，希望可以让数据库中的密码可以明文保存，或者是新增一个配置文件的项允许密码的明文保存。谢谢

**Comment by mo-han** [comment]
请使用密码管理软件，再不济自己存一份txt也行
