### ISSUE TITLE
Bug: HTTP状态码错误反馈

### ISSUE THREAD

**Issue by 8MiYile** [alist-org/alist#5967]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

非存储驱动问题

### Describe the bug / 问题描述

当我访问如下地址的时候
他返回的内容是
```json
{
  "code": 500,
  "message": "storage not found; rawPath: /1",
  "data": null
}
```
但是网页状态码却是200，这导致我不能方便的做缓存
![image](https://github.com/alist-org/alist/assets/25455400/2a8e133f-b671-4785-b751-3e2a0723dc3d)
如果json输出的code能同时应用在HTTP状态码就更好了

影响范围 nginx反代缓存系统

### Reproduction / 复现链接

`https://<alist-domain>/d/<不存在的路径>`

### Config / 配置

这个与配置无关吧

**Comment by liuyuhang9066** [comment]
我也遇到了这个问题，希望开发组能跟进和注意

**Comment by 8MiYile** [comment]
。

**Comment by luomo-pro** [comment]
同样的问题，一直存在，但好像都没人意识到
