### ISSUE TITLE
阿里云分享挂载的资源妙传失效

### ISSUE THREAD

**Issue by Ayanokouji-Kiyotaka** [alist-org/alist#5968]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我使用”阿里云盘分享“挂载的资源通过复制到“阿里云盘open”里面显示的是成功，但是并没有。我是希望通过挂载上“阿里云分享”的链接可以直接互传到“阿里云盘open”里面，就是分享（挂载别人的分享链接）保存（自己云盘里面）那一种，可以单独选取或者全部保存。就把”阿里云盘分享“分享的资源通过挂载得到（因为如若是影视资源会更新分享内容），然后再通过自己筛选保存到自己阿里云盘open里面去进行操作播放。

**Comment by anwen-anyi** [comment]
建议使用官方APP/Web端进行操作。
