### ISSUE TITLE
百度网盘本地代理下载的时候会500炸掉 

### ISSUE THREAD

**Issue by xzh767** [alist-org/alist#5970]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

用百度网盘下载东西的时候任何大文件直接500，小文件可以正常下载和播放
![image](https://github.com/alist-org/alist/assets/79035424/2a3be978-6d48-4989-84d9-52bb6b1d4f89)

### Reproduction / 复现链接

http://127.0.0.1:5244/p/%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98/任何东西

### Config / 配置

![image](https://github.com/alist-org/alist/assets/79035424/1d9280fb-fb07-4a48-8d6e-f3ca9bc02689)

[log.log](https://github.com/alist-org/alist/files/14080844/log.log)

[config.json](https://github.com/alist-org/alist/files/14080852/config.json)

### Logs / 日志

{
    "code": 500,
    "message": "http request [https://d.pcs.baidu.com/file/5a52ad111**********************?fid=1103579749304-250528-543900618337963&rt=pr&sign=FDtAERK-DCb740ccc5511e5e8fedcff06b081203-x*******************************YmPc%3d&expires=8h&chkbd=0&chkv=0&dp-logid=8734690************2480&dp-callid=0&dstime=1706512888&r=890451367&vuk=1103579749304&origin=dlna] failure,status: 403 response:\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003-�A\u000e@0\u0010\u0000��l��\u0003ڢ���nh,b['�w����H\"�\f�\u0011\t��u��_[����\n�\u001c�\u0015�L�)\u0017P�eb�0\u0013D�\u0003*\u0014:/�eH\u0011}�iӺ���1U�jc��\u0002�~f�i\u0000\u0000\u0000",
    "data": null
}

部分文件信息星号隐藏

**Comment by xhofe** [comment]
不保证非官方接口可用。
