### ISSUE TITLE
网页端跳转PotPlayer播放器的链接拼接错误，导致无法播放

### ISSUE THREAD

**Issue by Kosette** [alist-org/alist#5974]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

AliyundriveOpen

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/35268640/ce8cbfcd-d115-44f6-aa04-d5dce089d93c)
第二个PotPlayer图标对应的链接应当是`potplayer://http://<url>`，现在是`potplayer://http//<url>`。遗漏了HTTP协议后面的冒号`:`，导致播放器调用后识别为错误连接，无法正常播放。

### Reproduction / 复现链接

任意视频下方的链接

### Config / 配置

任意配置

**Comment by bin16** [comment]
The second colon in `potplayer://https://xxx` is removed by Firefox (v122) when jumping to potplayer. When you inspect that `<a>` tag in alist, it is `potplayer://https://xxx` but not `potplayer://https//xxx` in href attribute, alist is right.

Just found this: https://stackoverflow.com/questions/77886374/firefox-122-0-extensions-chrome-scripting-executescript-removes-colon

`potplayer:https://xxx` without the two slash will navigate you to potplayer successfully, however the url can not be read by PotPlayer. It should have removed the `potplayer:` to play the video:

![图片](https://github.com/alist-org/alist/assets/11701531/23ce0d77-0231-4c48-b3a6-d5fd313b6b20)

Firefox or PotPlayer should fix this I guess.

Chrome (v121) is good.

**Comment by bin16** [comment]
[Bug 1876731 - Firefox 122.0. Extensions. "chrome.scripting.executeScript" removes ":" (colon) from url when using in double with protocol url in](https://bugzilla.mozilla.org/show_bug.cgi?id=1876731)

**Comment by bin16** [comment]
https://github.com/whatwg/url/issues/815
