### ISSUE TITLE
alist启动时加载存储的顺序

### ISSUE THREAD

**Issue by j2rong4cn** [alist-org/alist#5976]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用CRYPT驱动时，把 '加密后文件存储路径' 设置为 CRYPT之后的的挂载路径会报错，例如下图这个 把加密后文件存储路径 改为 /189yun，启动时就会报错。但不想重新添加CRYPT
![Screenshot_20240131-130637_Kiwi Browser](https://github.com/alist-org/alist/assets/36783515/a1d3d24c-8fb4-4a17-a0f4-103b9a706c26)

希望alist启动时按照这个 序号 排序再加载存储，或者把CRYPT驱动改为最后加载
![Screenshot_20240131-125324_Kiwi Browser](https://github.com/alist-org/alist/assets/36783515/7cb6ebee-adf2-45f5-89df-39272177e8bf)

### Suggested solution / 实现思路

alist的备份
![Screenshot_20240131-131451_MT管理器~2](https://github.com/alist-org/alist/assets/36783515/510d022f-4908-4ce2-9e3f-0e0d020a8d47)
我不会go语言，写了个java的例子
具体效果：
```java
  public static void main(String...args) {
    class SD{
      int id;
      int order;
      SD(int id, int order) {
        this.id = id;this.order = order;
      }
      public String toString() {
        return String.valueOf(id + "/" + order);
      }
    }
    List<SD> l=Arrays.asList(new SD[]{new SD(1, 0),new SD(2, 2),new SD(3, 1),new SD(4, 1),new SD(5, 0)});
    System.out.println(l);
    Collections.sort(l, new Comparator<SD>(){
        @Override
        public int compare(SD sd1, SD sd2) {
          int i=Integer.compare(sd1.order, sd2.order);
          if (i != 0) {
            return i;
          }
          return Integer.compare(sd1.id, sd2.id);
        }
      });
    System.out.println(l);
  }
```
输出：
[1/0, 2/2, 3/1, 4/1, 5/0]
[1/0, 5/0, 3/1, 4/1, 2/2]

**Comment by ypq123456789** [comment]
我也发现这个问题了，还没修复吗，有啥好办法

**Comment by ypq123456789** [comment]
我发现alist加载存储的顺序是你添加存储的顺序，目前唯一的解决办法就是删除加密存储，重新添加一遍加密

**Comment by kiki-theone** [comment]
我也发现这个问题了，现在是按序号的顺序加载的，不过通常应用了Crypt的“加密后文件存储路径”必然是不常用的目录，所以必然会设置为比较大的序号。然而设置为大序号就会后加载，这就会导致Crypt加载失败，我觉得最好的解决方案就是Crypt倒数第二和别名倒数第一都最后加载。
