### ISSUE TITLE
Alist V3 add_aria2 api 返回错误信息

### ISSUE THREAD

**Issue by Naielc** [alist-org/alist#5980]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

尝试使用alist api 推送磁力链接，完整使用文档的代码（https://alist-v3.apifox.cn/api-128101261）
能够正确登录获得token，列出文件目录、获取站点设置等操作，尝试使用添加aria2下载api时返回的信息均为html。

### Reproduction / 复现链接

```
import requests
import json

server_url = "https://example.com"
auth_headers ={'User-Agent': 'Mozilla/5.0 auto_script','Content-Type': 'application/json'}
user_info = {
    "username": "",
    "password": ""
}
download_path = "/下载"


def auth_login(user_info):
    global token
    global auth_headers
    auth_login_url = server_url + "/api/auth/login"
    payload = json.dumps(user_info)
    response = requests.request("POST", auth_login_url, headers=auth_headers, data=payload)
    response = response.json()
    message = response["message"]
    if response["code"] == 200:
        auth_headers["Authorization"] = response["data"]["token"]
        print("登录成功")
    else:
        raise Exception(f"登录失败：{message}")
    
auth_login(user_info)
    
def add_aria2(add_aria2_info):
    global auth_headers
    add_aria2_url = server_url + "/api/fs/add_aria2"
    payload = json.dumps(add_aria2_info)
    response = requests.request("POST", add_aria2_url, headers=auth_headers, data=payload)
    response = response.json()
    message = response["message"]
    if response["code"] == 200:
        return message
    else:
        raise Exception(f"添加aria2下载任务失败：{message}")

aria2 = add_aria2({
    "urls": [
        'magnet:?xt=urn:btih:D13A4800C7766630C9CF7B6ED11044B3E7227156', 
        'magnet:?xt=urn:btih:6966939BAE7F73039CCC6D0E95F179CA52589FF7'
    ],
    "path": download_path
})
print(aria2)
```
![1](https://github.com/alist-org/alist/assets/32182694/3b83649d-de18-489a-9b4d-e4707e9728b0)

**Comment by xhofe** [comment]
add_aria2 以删除，请使用 `add_offline_download` api。

此文档不由官方维护
