### ISSUE TITLE
使用webdav挂载koofr网盘出错

### ISSUE THREAD

**Issue by woshichenghaibo** [alist-org/alist#5984]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

koofr

### Describe the bug / 问题描述

我新增驱动器，选择webdav，别的不动，在地址填入
https://app.koofr.net/dav/Koofr
或者
https://app.koofr.net/dav/
用户名密码填入koofr账户的用户名密码，在alist里面打开显示：

failed get objs: failed to list objs: PROPFIND /: 429

官网介绍页面在 https://koofr.eu/help/koofr_with_webdav/

以下是官网介绍

How do I connect a service to Koofr through WebDAV?
There are a few services that work with Koofr through WebDAV - [Zotero](https://koofr.eu/blog/posts/koofr-with-zotero-via-webdav), [Duplicati for Windows](https://koofr.eu/blog/posts/3-easy-steps-to-backup-your-files), [Duplicati for Linux](https://koofr.eu/blog/posts/how-to-backup-your-ubuntu-computer), [Duplicati for macOS](https://koofr.eu/blog/posts/easily-backup-files-from-your-mac-computer-to-koofr), [QNAP](https://koofr.eu/blog/posts/how-to-backup-your-qnap-nas-to-koofr-with-webdav) and [Synology](https://koofr.eu/blog/posts/how-to-backup-your-synology-nas-to-koofr-with-webdav) backups, and others.

You'll need to generate an application-specific password in your Koofr account to set up each of these connections. Watch our [tutorial](https://www.youtube.com/watch?v=izrj955mMqo) for detailed instructions on how to do that.

Note: You will not be able to set up a WebDAV connection, without using an application-specific password.

The WebDAV connection settings:

Host: https://app.koofr.net/dav/Koofr

Port: 443

User: the email address that you used when creating a Koofr account

Password: the application password that you generated above

Note: If there is a Root or Path field available in the WebDAV settings of the service you are trying to connect, you must input https://app.koofr.net/ into the Host field and /dav/Koofr into the Root field.

Note: If you want to create a subfolder, include it into the Root field /dav/Koofr/pathtosubfolder.

Note: Letters in the Host name are case sensitive.

Note: If you have trouble establishing your WebDAV connection with the details provided here, please contact our support through our Help and support center and we will do our best to help you.

### Reproduction / 复现链接

https://pan.gegebu.ru/Koofr

### Config / 配置

{
  "force": true,
  "site_url": "https://p.fo.ax",
  "cdn": "",
  "jwt_secret": "6FMG0bvuYFKxzGHc",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 1,
      "max_retry": 3
    },
    "transfer": {
      "workers": 1,
      "max_retry": 3
    },
    "upload": {
      "workers": 1,
      "max_retry": 3
    },
    "copy": {
      "workers": 1,
      "max_retry": 3
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

**Comment by woshichenghaibo** [comment]
input https://app.koofr.net/ into the Host field and /dav/Koofr into the Root field.


这个方法也试过了，也不行

我又看到

How to generate an application-specific password in Koofr?
You can connect many services to Koofr with the use of the WebDAV protocol. You need to generate an application-specific password each time you want to connect a new service to Koofr via WebDAV due to data safety reasons.

You can do that by clicking on your Profile picture icon the top-right corner of the Koofr web app. When the Account menu opens, click on Preferences and select Password from the menu on the left. Scroll down to App passwords, type in a new password name into the Generate new password text box and click on Generate.

You can see the whole process in our [video tutorial](https://www.youtube.com/watch?v=izrj955mMqo).

于是我设置了专门的问、bdav密码，还是不行，奇怪了

**Comment by woshichenghaibo** [comment]
我看到了一段话


I am getting a 429 error message when connecting a service through WebDAV. What should I do?
Error 429 typically indicates that you entered the wrong password, and due to multiple incorrect login attempts, your account has been temporarily blocked. Wait 1 hour for a block to expire before attempting a new login, and then make sure to use the correct [application-specific password](https://koofr.eu/help/linking-koofr-with-desktops/how-to-generate-an-application-specific-password-in-koofr/) for WebDAV.

那我明天再试试吧，或许尝试次数太多了

**Comment by xhofe** [comment]
https://al.nn.ci/koofr

**Comment by xuze1993** [comment]
> 我看到了一段话
> 
> I am getting a 429 error message when connecting a service through WebDAV. What should I do? Error 429 typically indicates that you entered the wrong password, and due to multiple incorrect login attempts, your account has been temporarily blocked. Wait 1 hour for a block to expire before attempting a new login, and then make sure to use the correct [application-specific password](https://koofr.eu/help/linking-koofr-with-desktops/how-to-generate-an-application-specific-password-in-koofr/) for WebDAV.
> 
> 那我明天再试试吧，或许尝试次数太多了

这个似乎是网络问题，我有时候能正常访问，有时失败就是这个429报错。配置没变过
