### ISSUE TITLE
离线下载添加的任务做种时无法取消

### ISSUE THREAD

**Issue by yegetables** [alist-org/alist#5985]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

如题,添加qbittort离线任务上传任意存储(onedrive)
下载到服务器成功,显示在做种 offline download completed, waiting for seeding
传输到对应的网盘存储成功,已清除记录

取消做种任务时显示成功但是瞬间页面刷新还存在此条记录,正在取消中.....
![image](https://github.com/alist-org/alist/assets/37119488/2d673ea0-57c2-4833-bbc1-61fd5f20608d)

### Reproduction / 复现链接

https://mirrors.aliyun.com/archlinux/iso/2024.01.01/archlinux-2024.01.01-x86_64.iso.torrent

### Config / 配置

archlinux系统使用docker版本alist. 
qbittort-enhanced-nox在服务器上使用systemctl管理
![image](https://github.com/alist-org/alist/assets/37119488/5db10b1d-7bfb-4af5-a553-a7277d056322)

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/37119488/69e01801-eb9a-461d-81f3-59dbec6958d3)

**Comment by Gerrit1999** [comment]
一样的问题
