### ISSUE TITLE
重做多选

### ISSUE THREAD

**Issue by Marrrrrrrrry** [alist-org/alist#5989]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在的多选我个人觉得十分难用，根据[官方文档](https://alist.nn.ci/zh/guide/advanced/rapid_upload.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)给出的方法，体验也非常差
我认为在电脑web端，用鼠标**框选**是有必要的，如果可以增加键盘快捷键，例如shift和ctrl来实现多选的其他功能会更好
而且现在的多选，开启复选框后一个个重新选择，一不小心就会点进想选中的文件/文件夹里面去，退出后又得**从头开始**选择，用户十分生气

**Comment by liuycy** [comment]
https://github.com/alist-org/alist-web/pull/157
