### ISSUE TITLE
四川电信魔盘登录失效，需要使用验证码登录，请求修复

### ISSUE THREAD

**Issue by xiaoxin3242** [alist-org/alist#5992]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

四川电信魔盘

### Describe the bug / 问题描述

四川电信魔盘登录失效，需要使用验证码登录，请求修复

### Reproduction / 复现链接

https://yun.xiaoxinbk.cn/od2

### Config / 配置

![image](https://github.com/alist-org/alist/assets/62818722/7494e0be-c443-45fc-9ca1-7ca5ba214944)

### Logs / 日志

状态: 

Code:100030, Message:请采用验证码方式登陆

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/pull/5987

**Comment by xiaoxin3242** [comment]
> [第5987章](https://github.com/alist-org/alist/pull/5987)

在存储设置页面SMSCode字段填入 send 即可发送短信验证码

没找到SMSCode字段

**Comment by anwen-anyi** [comment]
> > [第5987章](https://github.com/alist-org/alist/pull/5987)
> 
> 在存储设置页面SMSCode字段填入 send 即可发送短信验证码
> 
> 没找到SMSCode字段

测试版已经可以使用，正式版等待后续发布

**Comment by xiaoxin3242** [comment]
> > > [第5987章](https://github.com/alist-org/alist/pull/5987)
> > 
> > 
> > 在存储设置页面SMSCode字段填入 send 即可发送短信验证码
> > 没找到SMSCode字段
> 
> 测试版已经可以使用，正式版等待后续发布

如何更新为测试版？
