### ISSUE TITLE
在一键脚本中提供关闭 GitHub Proxy 的选项

### ISSUE THREAD

**Issue by scientificworld** [alist-org/alist#5999]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在大部分网络环境中，不存在对 GitHub 资源的访问问题，依赖于代理服务反而会降低稳定性。

以 `https://mirror.ghproxy.com/https://github.com/xhofe/alist/releases/latest/download/alist-linux-musl-amd64.tar.gz` 这个链接为例，目前它处于 502 状态，导致一键脚本不可用，而将 GH_PROXY 变量设置为空字符串以后即可正常下载。

### Suggested solution / 实现思路

添加类似于 `--disable-ghproxy` 的选项。

### Additional context / 附件

<img width="781" alt="502" src="https://github.com/alist-org/alist/assets/30764166/2d3ac8d3-a0e1-4cdb-9b7e-5bb6ddc6f7a3">

**Comment by 8MiYile** [comment]
有道理，不过我的建议是  
```
curl -fsSL "https://alist.nn.ci/v3.sh" | env GH_PROXY='https://hub.gitmirror.com/' bash -s install
```
