### ISSUE TITLE
能否在上传到百度网盘时保留本地源文件的modification time?

### ISSUE THREAD

**Issue by blue-cosmos** [alist-org/alist#6001]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

我查到过去有一个issue #4938 是有关modification time的，但和我的issue可能不一样，因此新开了一个issue。
我用rclone sync从本地上传到Alist挂载的百度网盘，上传后的文件的modification time被设成了上传时的时间，而不是本地源文件的modification time. 
使用百度网盘官方客户端上传文件，可以保留本地源文件的modification time.
在Rclone的文档中，提到某些Webdav providers可以支持保留modification time:
[WebDAV (rclone.org)](https://rclone.org/webdav/)
> Modification times and hashes
Plain WebDAV does not support modified times. However when used with Fastmail Files, Owncloud or Nextcloud rclone will support modified times.

原因可能是这些providers支持`X-OC-Mtime` header.

有没有可能让Alist的Webdav也支持rclone sync保留modification time的特性呢？

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by mo-han** [comment]
这个问题解决了吗
