### ISSUE TITLE
一些优化

### ISSUE THREAD

**Issue by flansing** [alist-org/alist#6021]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

问题1：在文件比较多的时候，启用复选框，鼠标点击的时候，容易点进去文件，返回上一层后，又需要重新来，容错率很低，太容易犯错了

问题2：账号中似乎缺少备注的地方，有的时候账号比较多，很难区分开每个账号之间的区别

### Suggested solution / 实现思路

问题1解决方法：是否考虑可以使用鼠标框选的方法？
问题2解决方法：能否多增加一个值来添加备注信息？

**Comment by ssln5014** [comment]
第一点赞成

**Comment by wongz** [comment]
建议复选框启用的情况下，底部工具条出现时，点击为选择，否则为进入
