### ISSUE TITLE
IPFS API 驱动，下载包含空格的文件名时会报错

### ISSUE THREAD

**Issue by WriteMemory** [alist-org/alist#6027]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

IPFS API

### Describe the bug / 问题描述

使用IPFS API 驱动，下载包含空格的文件名时会报错

### Reproduction / 复现链接

不需要链接，本地运行一个ipfs daemon，上传一个文件，并将文件名修改成带空格的文件名就可以

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "***************",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

### Logs / 日志

{"code":500,"message":"http request [http://*********:5080/ipfs/*******************************/?filename=test -HDR.ts] failure,status: 400 response:400 Bad Request","data":null}

**Comment by chenjia404** [comment]
我来修复这个问题，可能是没有对特殊文件名进行转码。

**Comment by chenjia404** [comment]
我这里无法复现这个问题
https://alist.ipfsscan.io/%E8%BD%AF%E4%BB%B6/PotPlayer

**Comment by chenjia404** [comment]
> > 我这里无法复现这个问题 https://alist.ipfsscan.io/%E8%BD%AF%E4%BB%B6/PotPlayer
> 
> 我重新测试了一下，需要打开alist的“Web代理”功能才会产生这个问题。

我开启了web代理，也无法复现。你用我的网关试一下呢  https://cdn.ipfsscan.io

**Comment by chenjia404** [comment]
已经提交pr等待合并了
