### ISSUE TITLE
阿里云盘open添加不上去，Api已更新

### ISSUE THREAD

**Issue by lsk5201** [alist-org/alist#6030]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Failed init storage: failed to refresh token: Too Many Requests

### Suggested solution / 实现思路

/

### Additional context / 附件

/

**Comment by lsk5201** [comment]
OK，解决了

**Comment by elven2016** [comment]
> OK，解决了

请问你怎么解决的？能告诉下处理办法吗？

**Comment by xcsweb** [comment]
怎么解决的，我也遇到了

**Comment by muxinxy** [comment]
将`aliyundrive_open`配置中的`Oauth令牌链接`更换为
`https://api-cf.nn.ci/alist/ali_open/token`

**Comment by nibazshab** [comment]
我也遇到了，【Oauth令牌链接】改为哪个都不行，这情况已经持续一个月多了
