### ISSUE TITLE
在线播放希望可以增加movist player

### ISSUE THREAD

**Issue by luange** [alist-org/alist#6033]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在线播放希望可以增加movist player

**Comment by woshichenghaibo** [comment]
增加那么多功能干啥？要不要把微信加进去？
