### ISSUE TITLE
使用网页版无法上传 Hi-Res 音乐

### ISSUE THREAD

**Issue by ZsOg** [alist-org/alist#6038]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

OneDrive

### Describe the bug / 问题描述

使用网页版无法上传 **Hi-Res** 音乐。两种上传方式**都不行**。
1. 显示上传时，不显示上传速度，就像是卡在那里了（图1），但网页并没有卡住，通过F12也没看出来在报错（图2）。这种情况会持续从几分钟到十几分钟不等，然后就开始上传了。
![image](https://github.com/alist-org/alist/assets/62445523/ef146c19-41eb-4b4a-83f5-b7017bd06083)
![image](https://github.com/alist-org/alist/assets/62445523/6e901550-7931-43b0-8acd-98dcb2c5b399)

2. 真正的开始上传后，会突然显示上传失败（无确切时间，有时候需要很长时间才会显示，有时候1分钟后就显示了）：`Cannot read properties of undefined (reading 'status')`，通过F12查看显示说是网络问题，但即使在网络流畅且快速的情况下也会显示。即使尝试了很多次都是这样。
![image](https://github.com/alist-org/alist/assets/62445523/e04660fc-1ada-4ff2-b91e-197fee08d063)

网盘是搭建在 docker 的 s390x 架构上(LinuxOne)，尝试了 alist 和 alist-aria2 都有此问题。

### Reproduction / 复现链接

[地址](http://148.100.112.233/)
用户名和密码都是`test`

### Config / 配置

```json
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "kqbJ4UC8AumhJxDB",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}
```

**Comment by ZsOg** [comment]
服务器过期了，已重新申请

**Comment by ZsOg** [comment]
好了，[地址](http://148.100.112.233/)
用户名和密码都是`test`

**Comment by ZsOg** [comment]
@xhofe 你上传的并非 Hi-Res，虽然是 flac 格式，但里面的频率、波形和大小都对不上。根据音乐播放器里显示，你上传的的这首 flac 音乐是 SQ 音质，并非 Hi-Res

![Screenshot_20240218_103318.jpg](https://github.com/alist-org/alist/assets/62445523/c4a7eda0-d5ec-4867-83ce-5ec1f3849e0b)
![Screenshot_20240218_103352.jpg](https://github.com/alist-org/alist/assets/62445523/c545937c-0798-4d12-9f12-fe90f3a3f739)
![Screenshot_20240218_103734.jpg](https://github.com/alist-org/alist/assets/62445523/feea6c2e-eff6-4c6a-8934-9f9eab48306f)
![Screenshot_20240218_103431.jpg](https://github.com/alist-org/alist/assets/62445523/7a997041-e14b-4b23-a175-64111ccbba05)

**Comment by xhofe** [comment]
<img width="492" alt="image" src="https://github.com/alist-org/alist/assets/36558727/88a59623-f6aa-4b5a-9d11-2f79419e6e85">

这本身就与文件内容没有关系。

**Comment by ZsOg** [comment]
> <img width="492" alt="image" src="https://github.com/alist-org/alist/assets/36558727/88a59623-f6aa-4b5a-9d11-2f79419e6e85">
> 
> 这本身就与文件内容没有关系。

那为什么我当时上传时出现了错误？我也测速了，当时是一百多 Mbps，所以不可能网络不好
