### ISSUE TITLE
[feature request] 希望可以支持网盘的搜索api

### ISSUE THREAD

**Issue by BrettDean** [alist-org/alist#6040]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

网盘内有`3313959`个文件和`273058`个文件夹，不敢打开索引
要是alist的搜索能直接 ~~破解~~ 对接网盘的官方搜索api就舒服了

**Comment by woshichenghaibo** [comment]
不要搞得过于复杂
