### ISSUE TITLE
alist ssh连接非常卡，且有些BUG，能不能完善一下

### ISSUE THREAD

**Issue by ncdn** [alist-org/alist#6042]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3

### Driver used / 使用的存储驱动

sftp

### Describe the bug / 问题描述

经常接上了过半天就坏了，能不能保持一下，或者重连，filezilla就非常稳

### Reproduction / 复现链接

内网未开放公网

### Config / 配置

连接没有问题

### Logs / 日志

failed get objs: failed to list objs: connection lost

alist  | ERRO[2024-02-16 00:08:33] failed get enabled storages: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
alist  | failed init storage
alist  | github.com/alist-org/alist/v3/internal/op.initStorage
alist  | 	/home/runner/work/alist/alist/internal/op/storage.go:99
alist  | github.com/alist-org/alist/v3/internal/op.LoadStorage
alist  | 	/home/runner/work/alist/alist/internal/op/storage.go:80
alist  | github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
alist  | 	/home/runner/work/alist/alist/internal/bootstrap/storage.go:20
alist  | runtime.goexit
alist  | 	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/asm_amd64.s:1650

**Comment by moeo8** [comment]
同样的问题，网络环境改变就会出现，在设置里重启才能恢复。

**Comment by petulat** [comment]
> 同样的问题，网络环境改变就会出现，在设置里重启才能恢复。

同样的问题，这太影响使用体验了
