### ISSUE TITLE
挂载阿里云盘open不可用

### ISSUE THREAD

**Issue by gimgoo** [alist-org/alist#6052]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

之前一直都是好好的，没有任何问题，知道有一天打开网站提示报错 
![image](https://github.com/alist-org/alist/assets/31849284/f26e2928-ee59-4fbf-8c00-013ee4150f52)

然后登陆进后台看到挂载出问题了

![image](https://github.com/alist-org/alist/assets/31849284/eeac3316-86d1-49e9-ad56-08aaf0099bc1)

### Reproduction / 复现链接

无

### Config / 配置

未曾修改配置，一直都是正常的，属于突然暴毙，与配置无关

**Comment by huolanyun** [comment]
换个DNS试下，你是不是用1.1.1.1 这个DNS了

**Comment by gimgoo** [comment]
> 换个DNS试下，你是不是用1.1.1.1 这个DNS了

不是，我用的谷歌的 8.8.8.8

**Comment by huolanyun** [comment]
把阿里的Oauth令牌链接 地址 改成国内的
https://api.xhofe.top/alist/ali_open/token

**Comment by gimgoo** [comment]
> 把阿里的Oauth令牌链接 地址 改成国内的 https://api.xhofe.top/alist/ali_open/token

没用的，这个我试过了，还有那个带cf的域名也换过了，一个样，我的是国外VPS，不用还国内的，就是不知道为何暴毙。而且服务器的DNS都不是1.1.1.1

**Comment by huolanyun** [comment]
阿里估计不让海外用户使用
我国内 正常
