### ISSUE TITLE
希望增加文件下载数统计和访客统计功能

### ISSUE THREAD

**Issue by Winyer** [alist-org/alist#6058]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题，今天早上新买的服务器，中午接到流量超载警报，一看已经没了2T的流量，因为分享出去的文件挺多的，而且是放在OD上的，所以服务器开了本机代理功能提高国内下载网速，现在因为也不知道哪个文件下载数太多了引起的，只好暂时关闭了Alist😂
![Screenshot_20240218-203641-679](https://github.com/alist-org/alist/assets/19600350/c946e1b2-47eb-4346-ad97-a9cea13b6563)

### Suggested solution / 实现思路

无，你们更专业

**Comment by m0ch3** [comment]
如果你没有调整alist的日志配置（默认配置），cd到alist同目录下`data/log`文件夹，使用`grep "\"/p/" log.log`过滤出下载文件的日志条目，剩下的就是分析统计了

**Comment by Winyer** [comment]
> 如果你没有调整alist的日志配置（默认配置），cd到alist同目录下`data/log`文件夹，使用`grep "\"/p/" log.log`过滤出下载文件的日志条目，剩下的就是分析统计了

稍微有点麻烦，希望像蓝奏云那样直接能看到

**Comment by IAALAI** [comment]
> > 如果你没有调整alist的日志配置（默认配置），cd到alist同目录下`data/log`文件夹，使用`grep "\"/p/" log.log`过滤出下载文件的日志条目，剩下的就是分析统计了
> 
> 稍微有点麻烦，希望像蓝奏云那样直接能看到

那这个功能就得要你自己开发了

**Comment by babadebabjiaoshenmo** [comment]
同样希望增加
