### ISSUE TITLE
复制或移动时希望添加“新建文件夹”按钮

### ISSUE THREAD

**Issue by laorentou666** [alist-org/alist#6067]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题，在复制或移动文件夹时能有一个新建文件夹的按钮，这样能节省返回创建文件夹的时间

![image](https://github.com/alist-org/alist/assets/89732460/c88285ba-071f-4cac-b2bf-6e443a979fc3)

**Comment by huolanyun** [comment]
复制 是不是 先下载到服务器再通过服务器上传

**Comment by yyyytawa** [comment]
> 复制 是不是 先下载到服务器再通过服务器上传

要看情况 同一个存储里面可以直接复制不走服务器,直接用云盘厂商的API
不在同一个存储的话要走服务器
