### ISSUE TITLE
增加自动 “重新加载” 的建议

### ISSUE THREAD

**Issue by CG1995** [alist-org/alist#6068]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

latest

### Driver used / 使用的存储驱动

Aliyun Drive

### Describe the bug / 问题描述

每隔一段时间，挂载好的盘就会掉线，但是登陆上去点一下“重新加载”就能解决，是否能增加检测到掉线就自动重新加载或者每隔一段时间自动重新加载的功能，这样不用每次登陆上去手动按

### Reproduction / 复现链接

无

### Config / 配置

无

### Logs / 日志

无

**Comment by ddns6** [comment]
同样遇到过掉盘问题。后来结果自己排查：系op重启后网络未就绪的情况下alist启动造成的。您可以尝试延时启动alist
![image](https://github.com/alist-org/alist/assets/100478073/b512547b-bfb9-4268-81d5-63dc104fef64)

**Comment by CG1995** [comment]
> 同样遇到过掉盘问题。后来结果自己排查：系op重启后网络未就绪的情况下alist启动造成的。您可以尝试延时启动alist ![image](https://private-user-images.githubusercontent.com/100478073/307561288-b512547b-bfb9-4268-81d5-63dc104fef64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NjEwMDYsIm5iZiI6MTcwODg2MDcwNiwicGF0aCI6Ii8xMDA0NzgwNzMvMzA3NTYxMjg4LWI1MTI1NDdiLWJmYjktNDI2OC04MWQ1LTYzZGMxMDRmZWY2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxMTMxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWY5MTVhNmY2NzhjNDkxZjdhZTI1N2E5MzViNWRmYjRkNTI1YTA0YTBhOGE4YTYwZThmY2UzMjk0ZGY0MDhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tp0oRi1f48oXZ4NHXXjdEPC9jI-hvimInp-WVTyeAXo)

十分感谢~亲测好用

**Comment by nozomu11** [comment]
可以调用官方api接口参数做一个自定义定时任务。linux系统里cron任务跑这个就可以
curl --location --request POST 'http://127.0.0.1:5244/api/admin/storage/load_all' \--header 'Authorization: alist-96f8xxxxx-xxxx-4635-xxxe-0c12db284xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxBJI'
ip和令牌替换成自己的就行。
