### ISSUE TITLE
复制列表将运行中的任务放在最前面，显示状态是下载还是上传，显示速度

### ISSUE THREAD

**Issue by ypq123456789** [alist-org/alist#6069]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在复制列表中，目前最前面的是“等待中”，“运行中”的任务在后面某一页很难找，希望能将运行中的任务放在最前面。而且希望能显示任务目前的状态是下载还是上传，显示下载或上传速度。

**Comment by anyingxiuluo** [comment]
支持，如果复制文件过多的话，很难找到目前正在复制的内容
