### ISSUE TITLE
alist win11桌面版 在挂载后，夸克网盘和阿里云盘都可以直接正常打开视频，百度网盘无法打开，但网页内可以正常下载

### ISSUE THREAD

**Issue by 17656319795** [alist-org/alist#6070]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.30.1 桌面端

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

alist win11桌面版 在挂载后，夸克网盘和阿里云盘都可以直接正常打开视频，百度网盘无法打开，但网页内可以正常下载

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by xhofe** [comment]
webdav策略选择本地代理

**Comment by 17656319795** [comment]
好的 可以了 谢谢
