### ISSUE TITLE
dav下 HEAD与GET获取到的内容不一致

### ISSUE THREAD

**Issue by 8MiYile** [alist-org/alist#6080]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

非存储驱动问题

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/25455400/2d872ce9-cb34-45e4-81b8-0e5586f59830)
HEAD与GET获得的内容不同，请修复一下这个问题，应与GET的内容一致

除非是说这个HEAD是给那个WebDAV客户端显示文件大小的标准。。那就可以直接关了

### Reproduction / 复现链接

-X HEAD 与 -X GET 的区别 任意地址

### Config / 配置

与配置无关，我检查了一下，是设计问题

**Comment by yedajiang44** [comment]
这个问题有任何进展吗 @8MiYile 
而且`curl -I`的应答报文中缺少`Last-Modified`信息
