### ISSUE TITLE
alist-v3.31.0用Microsoft Edge( 版本 122.0.2365.52) 浏览界面，点击文件夹变选择（无法打开文件夹）

### ISSUE THREAD

**Issue by gexiaopeng** [alist-org/alist#6096]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.31.0

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

alist-v3.31.0用Microsoft Edge( 版本 122.0.2365.52) 浏览界面，点击文件夹变选择（无法打开文件夹)。alist 版本v3.29.1是正常的。

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by xhofe** [comment]
取消多选 或者 按住 alt/option

**Comment by gexiaopeng** [comment]
> 取消多选 或者 按住 alt/option

按键盘alt再点击可以打开文件夹与文件了。请问取消多选在哪里？  这个是新功能还是BUG?

**Comment by anwen-anyi** [comment]
> > 取消多选 或者 按住 alt/option
> 
> 按键盘alt再点击可以打开文件夹与文件了。请问取消多选在哪里？ 这个是新功能还是BUG?

右下角 能关闭多选
