### ISSUE TITLE
alist web 页面无法加载

### ISSUE THREAD

**Issue by EverlastingMagic** [alist-org/alist#6099]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.31.0   WebVersion: 3.31.0

### Driver used / 使用的存储驱动

none

### Describe the bug / 问题描述

web页面脚本加载错误：
aliyun-web-office-sdk.min.js:1 aliyun JS-SDK V1.1.5
index.44cc2916.js:20  Uncaught TypeError: Cannot assign to read only property '__symbol@@0.8530341164659176' of object '[object Object]'
    at index.44cc2916.js:20:187868
    at yc (index.44cc2916.js:20:186273)
    at J8 (index.44cc2916.js:20:187835)
    at Object.IC [as freezeMethods] (index.44cc2916.js:20:187911)
    at index.44cc2916.js:21:2839
(匿名) @ index.44cc2916.js:20
yc @ index.44cc2916.js:20
J8 @ index.44cc2916.js:20
IC @ index.44cc2916.js:20
(匿名) @ index.44cc2916.js:21

### Reproduction / 复现链接

http://localhost:5244/

### Config / 配置

空配置，刚刚初始化alist，命令提示窗口生成初始随机密码

### Logs / 日志

[localhost-1708936587743.log](https://github.com/alist-org/alist/files/14401856/localhost-1708936587743.log)
aliyun-web-office-sdk.min.js:1 aliyun JS-SDK V1.1.5
index.44cc2916.js:20  Uncaught TypeError: Cannot assign to read only property '__symbol@@0.8530341164659176' of object '[object Object]'
    at index.44cc2916.js:20:187868
    at yc (index.44cc2916.js:20:186273)
    at J8 (index.44cc2916.js:20:187835)
    at Object.IC [as freezeMethods] (index.44cc2916.js:20:187911)
    at index.44cc2916.js:21:2839
(匿名) @ index.44cc2916.js:20
yc @ index.44cc2916.js:20
J8 @ index.44cc2916.js:20
IC @ index.44cc2916.js:20
(匿名) @ index.44cc2916.js:21

**Comment by Rambin** [comment]
试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill地址](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回了一堆内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后就不返回任何代码

使用F12阻止polyfill.io后，编辑AList管理-“设置”-“全局”内的“自定义头部”，添加“&version=3.111.0”即可修复
```<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">```
修改为
```<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">```

**Comment by sonytyh** [comment]
> 试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回地址了一批内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后不返回任何代码
> 
> 使用F12阻止修改polyfill.io后，编辑AList管理-“设置”-“全局”内的“头部头部”，添加“&version=3.111.0”即可修复 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">` 为 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">`

我也遇到了这个问题，请问如何在F12阻止修改polyfill.io ？感谢感谢

**Comment by yxiZo** [comment]
> > 试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回地址了一批内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后不返回任何代码
> > 使用F12阻止修改polyfill.io后，编辑AList管理-“设置”-“全局”内的“头部头部”，添加“&version=3.111.0”即可修复 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">` 为 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">`
> 
> 我也遇到了这个问题，请问如何在F12阻止修改polyfill.io ？感谢感谢

<img width="342" alt="image" src="https://github.com/alist-org/alist/assets/134839633/e6cabdf6-e450-44ad-866d-e48aa57d7b3e">

<img width="798" alt="image" src="https://github.com/alist-org/alist/assets/134839633/6c8be746-467c-4a41-bcb8-26cfbcc46457">

**Comment by carolcoral** [comment]
感谢各位大佬，刚好我也遇到这个问题了，在3.30.0和3.31.0的时候突然就白了

**Comment by EntropyGenerator** [comment]
Thanks for the solution. Confirmed working by blocking polyfill.io

**Comment by Justsenger** [comment]
同样的问题，估计所有alist用户都影响到了，不过我手机端打开是正常的，可以先在手机上改。
