### ISSUE TITLE
网页突然无法显示，一片空白

### ISSUE THREAD

**Issue by mlkt** [alist-org/alist#6100]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.31.0

### Driver used / 使用的存储驱动

aliyunpan_open

### Describe the bug / 问题描述

网页突然无法显示，一片空白，换用新版也是一样，旧版的也是如此，换用不同浏览器也是这样
![微信截图_20240226165719](https://github.com/alist-org/alist/assets/10374085/a1caf8ef-ac55-43c2-86d0-9d43d296ba1b)
![微信截图_20240226165739](https://github.com/alist-org/alist/assets/10374085/f5298a5f-a404-4c89-866a-903c70daac1a)

### Reproduction / 复现链接

无

### Config / 配置

初始配置

**Comment by hipedo** [comment]
一模一样的问题我就不开新issue了，昨天晚上还好好的，今天用各类浏览器，重启，重装都没用了，全是一片空白，用的极空间NAS

**Comment by mlkt** [comment]
感觉是依赖了什么第三方的SDK新版有bug造成的

**Comment by Rambin** [comment]
> 感觉是依赖了什么第三方的SDK新版有bug造成的

试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill地址](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回了一堆内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后就不返回任何代码

**Comment by xhofe** [comment]
https://al.nn.ci/

未能复现

**Comment by mlkt** [comment]
> https://al.nn.ci/
> 
> 未能复现

同样无法显示，清下缓存或者在无痕模式下打开试试
![image](https://github.com/alist-org/alist/assets/10374085/fd093387-d804-46f4-99d9-bcd80208a94a)

**Comment by mlkt** [comment]
> > 感觉是依赖了什么第三方的SDK新版有bug造成的
> 
> 试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill地址](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回了一堆内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后就不返回任何代码
> 
> 补充： F12阻止polyfill.io后，编辑AList管理-“设置”-“全局”内的“自定义头部”，添加“&version=3.111.0”即可修复 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">` 修改为 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">`

确实右键屏蔽这个请求后恢复正常

![image](https://github.com/alist-org/alist/assets/10374085/ff8f395a-bef8-4bb5-84ff-9b7764717a83)
![image](https://github.com/alist-org/alist/assets/10374085/6c822e34-07a0-4da6-816e-7ee774bf7a0c)

**Comment by jizhazha** [comment]
+1 我也是这种情况，昨天还好好的，没有进行任何操作，今天突然就不行了，360、火狐、edge、chrome都不行

**Comment by Rambin** [comment]
> 我这里 https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll 返回的都是正常内容

所以可能是polyfill对部分地区或者部分浏览器响应有异常，我这里得到的是给string添加replaceAll的代码，加上版本号或者去掉min之后返回空代码

**Comment by mlkt** [comment]
我的chrome和edge版本

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0

**Comment by ifwwww** [comment]
我这里也有同样的问题，完全一样

**Comment by ifwwww** [comment]
开了代理就正常进

**Comment by free-150** [comment]
+1 firefox浏览器也有同样的问题

**Comment by ifwwww** [comment]
恢复正常

**Comment by hugcabbage** [comment]
+1

**Comment by koogg** [comment]
遇到了同样的问题，按照 上面的方法改成 阿里的正常了

**Comment by fulracoco** [comment]
> > 感觉是依赖了什么第三方的SDK新版有bug造成的
> 
> 试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill地址](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回了一堆内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后就不返回任何代码
> 
> 补充： F12阻止polyfill.io后，编辑AList管理-“设置”-“全局”内的“自定义头部”，添加“&version=3.111.0”即可修复 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">` 修改为 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">`

加&version=3.111.0貌似会影响手机端访问，不能自适应。alicdn正常

**Comment by Rambin** [comment]
> > > 感觉是依赖了什么第三方的SDK新版有bug造成的
> > 
> > 
> > 试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill地址](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回了一堆内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后就不返回任何代码
> > 补充： F12阻止polyfill.io后，编辑AList管理-“设置”-“全局”内的“自定义头部”，添加“&version=3.111.0”即可修复 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">` 修改为 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">`
> 
> 加&version=3.111.0貌似会影响手机端访问，不能自适应。alicdn正常

这个可能和浏览器有关，足够新的浏览器支持string的replaceAll方法，不需要这个polyfill，只有不支持的会出问题，不过可能还是polyfill.io的逻辑出故障了，不能正确识别浏览器是否支持对应的方法

**Comment by EverlastingMagic** [comment]
感觉alist可以添加一个导出并使用该静态文件模板的命令

**Comment by mlkt** [comment]
估计就是 `polyfill.io` 的bug，版本判断错误了，导致本来不需要polyfill的浏览器也返回了polyfill代码，新浏览器本来就有`String.replaceAll` 方法并且被设置为了只读字段，导致修改字段失败

**Comment by W-Haooooo** [comment]
> > 感觉是依赖了什么第三方的SDK新版有bug造成的
> 
> 试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill地址](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回了一堆内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后就不返回任何代码
> 
> 补充： F12阻止polyfill.io后，编辑AList管理-“设置”-“全局”内的“自定义头部”，添加“&version=3.111.0”即可修复 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">` 修改为 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">`

按照你的方法成功打开了

**Comment by Demprace** [comment]
> > 感觉是依赖了什么第三方的SDK新版有bug造成的
> 
> 试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill地址](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回了一堆内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后就不返回任何代码
> 
> 补充： F12阻止polyfill.io后，编辑AList管理-“设置”-“全局”内的“自定义头部”，添加“&version=3.111.0”即可修复 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">` 修改为 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">`
遇到了同样的问题，我在本地打开正常，公网访问一篇空白，按此方法设置后正常访问。

**Comment by Golubb** [comment]
> AList打开空白的 进入后台后台 全局 自定义头部里面换一下
> 
> ```
> <script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> ```
> 
> 换成这个阿里的
> 
> ```
> <script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> ```
> 
> 直接删了也可以，但是可能会导致其他人访问时候浏览器如果不兼容会打不开
> 
> 不知道怎么进后台的 [https://域名/@manage](https://%E5%9F%9F%E5%90%8D/@manage)

按这个方法解决了，十分感谢！

**Comment by muse243** [comment]
> AList打开空白的进入后台后台全局自定义头部里面换一下
> 
> ```
> <script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> ```
> 
> 换成这个阿里的
> 
> ```
> <script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> ```
> 
> 直接删除了也可以，但是可能会导致其他人访问时浏览器如果不兼容会打不开
> 
> 不知道怎么进后台的 [https://域名/@manage](https://%E5%9F%9F%E5%90%8D/@manage)

给了可以进但是有报错“System error: Error: [Hope UI]: useColorMode must be used within a HopeProvider”正常吗

**Comment by br201** [comment]
3.10版本也存在这个问题

**Comment by ddns6** [comment]
+1，更新后后台进不去了。重刷固件后首次配置时后台加载较慢，配置完之后也可以正常访问。重启设备后后台就无法访问了，挂载的资源可以在webdav客户端正常访问，访问后台时标题可以正常加载，其余一片空白！以为是跳转问题，使用2F完整链依然无法访问！![IMG_20240227_211234.jpg](https://github.com/alist-org/alist/assets/100478073/a0bf90bb-e020-4f88-b88a-d35b6d1904fd)

**Comment by ruterfu** [comment]
有同样的问题，但是开了代理就莫名其妙好了

**Comment by arkylin** [comment]
我的是手机空白，电脑正常，在电脑上把 polyfill 删了就都正常了

**Comment by qzrsa** [comment]
同样问题。昨天开始出现的。卸载了换最新版本也不行。按照上面大佬说的可以了。

**Comment by FOXBALL-ONE** [comment]
我也是突然就白屏问题，重装了都不管用，用了chrome，edge，QQ浏览器都不行，内外网都白屏（包括手机的数据网络）阻止polyfill.io就能正常访问了

**Comment by eagleandsanake** [comment]
同样是这样的情况 希望尽快修复, 感谢

**Comment by freeAhao** [comment]
挂梯子后才能正常打开

**Comment by OldCoding** [comment]
同样的情况

**Comment by zhouym233** [comment]
出现相同问题，非代理环境下白屏。

**Comment by paomian** [comment]
可能和这个有关系？https://github.com/polyfillpolyfill/polyfill-service/issues/2834

**Comment by moon-umbrella** [comment]
> AList打开空白的

把<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">改掉，确实能打开网页了。

**Comment by fzlychee2019** [comment]
高手在民间，删除后，确实正常了。

**Comment by spaceflyx** [comment]
遇到同样的问题，感谢高人出手相助。

**Comment by KB64ba** [comment]
> ```
> <script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> ```

白屏按此方法可以解决
先进进后台的 [https://域名、IP/@manage]，再修改

**Comment by grock304** [comment]
> AList打开空白的 进入后台 --> 全局 --> 自定义头部里面换一下
> 
> ```
> <script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> ```
> 
> 换成这个阿里的（**直接删了也可以，但是可能会导致其他人访问时候浏览器如果不兼容会打不开**）
> 
> ```
> <script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> ```
> 
> 不知道怎么进后台的 [https://域名/@manage](https://%E5%9F%9F%E5%90%8D/@manage)
> 
> 如果还是出现请使用 **`Ctrl+F5`** 刷新网页，或者是否使用美化教程里面也携带了上面提到的 js静态资源，检查一下
> 
> * 手机用户修改好后 清理浏览器缓存

我把 polyfill.io 走了代理也不行，还是换了地址解决了，感谢！

**Comment by chenanu123** [comment]
> AList打开空白的 进入后台 --> 全局 --> 自定义头部里面换一下
> 
> ```
> <script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> ```
> 
> 换成这个阿里的（**直接删了也可以，但是可能会导致其他人访问时候浏览器如果不兼容会打不开**）
> 
> ```
> <script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> ```
> 
> 不知道怎么进后台的 [https://域名/@manage](https://%E5%9F%9F%E5%90%8D/@manage)
> 
> 如果还是出现请使用 **`Ctrl+F5`** 刷新网页，或者是否使用美化教程里面也携带了上面提到的 js静态资源，检查一下
> 
> * 手机用户修改好后 清理浏览器缓存

感谢有效~

**Comment by rhwong** [comment]
same issue
更换头部之后所有页面报错
`System error: Error: [Hope UI]: useColorMode must be used within a HopeProvider`

**Comment by chenanu123** [comment]
> same issue 更换头部之后所有页面报错 `System error: Error: [Hope UI]: useColorMode must be used within a HopeProvider`

下载最新版本，可以直接替换

**Comment by leioukupo** [comment]
加一，我也出现了，今天才发现

**Comment by haoenz** [comment]
统计了一下手头的几个设备的情况

Win11 22H2
Edge 122.0.2365.52 异常
Edge 122.0.2365.59 异常
FireFox 123.0 异常

Win11 23H2
Vivaldi 6.5.3206.63 异常
Edge 122.0.2365.59 异常

Ubuntu 22.04.4 LTS
Edge 122.0.2365.38 beta 正常

Android 14 Xiaomi HyperOS 1.0.6.0
Edge 121.0.2277.133 异常
Vivaldi 6.5.3217.122 异常

iOS 17.3.1
Safari 正常

**Comment by 4873** [comment]
出现同样的问题，通过楼上的方法解决了

**Comment by ericlian319** [comment]
> <script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll"></s

> > AList打开空白的 进入后台 --> 全局 --> 自定义头部里面换一下
> > ```
> > <script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 换成这个阿里的（**直接删了也可以，但是可能会导致其他人访问时候浏览器如果不兼容会打不开**）
> > ```
> > <script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不知道怎么进后台的 [https://域名/@manage](https://%E5%9F%9F%E5%90%8D/@manage)
> > 如果还是出现请使用 **`Ctrl+F5`** 刷新网页，或者是否使用美化教程里面也携带了上面提到的 js静态资源，检查一下
> > 
> > * 手机用户修改好后 清理浏览器缓存
> 
> 感谢有效~

改完后一刷新还是空白。是不是没有保存？谢谢！

**Comment by lichengxun** [comment]
在网页端播放的时候 你们有没有出现放着放着跳开头 然后又跳回来的问题
改了这个东西后出现的，但我不是很确定是这个导致的

**Comment by ee44** [comment]
我感觉代码中访问了github.com链接，有的地方github.com被屏蔽了不能访问，所以打开网页就是空白的，部分浏览器储存了上次访问的cookei还能正常访问。

**Comment by JJTools** [comment]
确认就是 polyfill.io 的问题。我测了一下。是区域性的。我的国内服务器和香港服务器返回都是异常的。但是美国和欧洲两个地区是由问题。建议换成 
https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll
走阿里的代理是最稳妥的。

**Comment by AlphaZ19** [comment]
我的还是不行，进入管理界面的URL是不请求polyfill了，但 https://cdn.jsdelivr.net/gh/alist-org/web-dist@dev/dist/assets/index.44cc2916.js 这个请求还是404，不管我挂不挂代理
页面还是空白的，不管是正常的页面还是管理页面都是空白

**Comment by BubbleBearU** [comment]
> > > 感觉是依赖了什么第三方的SDK新版有bug造成的
> > 
> > 
> > 试了一下，polyfill.io返回的东西有问题，F12里阻止polyfill.io之后正常了，用Edge 121访问请求的[polyfill地址](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll)返回了一堆内容，而按polyfill.io上的操作[加上版本号](https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0)后就不返回任何代码
> > 补充： F12阻止polyfill.io后，编辑AList管理-“设置”-“全局”内的“自定义头部”，添加“&version=3.111.0”即可修复 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">` 修改为 `<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">`
> 
> 加&version=3.111.0貌似会影响手机端访问，不能自适应。alicdn正常

感谢 恢复正常

**Comment by AlphaZ19** [comment]
我把 polyfill.io 这个域名加到代理的路由里面后，polyfill 的请求正常了，但 [index.44cc2916.js](https://cdn.jsdelivr.net/gh/alist-org/web-dist@dev/dist/assets/index.44cc2916.js) 还是404，这个是arm机器上的docker版本，我还有两个PC版的都没问题，心累，虽然不影响通过API调用，但打不开网页，想修改挂载盘啥的都没办法

**Comment by yanggu47** [comment]
一样的问题，使用127.0.0.1或IP访问正常；但使用localhost访问空白
![image](https://github.com/alist-org/alist/assets/79220974/1b644b33-96bd-4ab0-bcd7-83a981a3a26b)
