### ISSUE TITLE
升级3.31.0版本后无法打开Windows挂载的dav

### ISSUE THREAD

**Issue by wolfsilver** [alist-org/alist#6104]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.31.0

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

打开时报错 找不到网络路径 此链接尚未还原

### Reproduction / 复现链接

无

### Config / 配置

使用的默认配置

**Comment by tursom** [comment]
我也遇到同样的问题了，截图如下

**Comment by tursom** [comment]
我也遇到同样的问题了，截图如下
![image](https://github.com/alist-org/alist/assets/33368546/79fdd84f-1330-4cab-86bb-fdb0d62d95ec)
但是只有根目录无法访问，alist 挂载的各个存储目录是可以正常访问的

**Comment by mlkt** [comment]
Windows自带的dav客户端很垃圾，bug和限制很多，不要用

**Comment by BubbleBearU** [comment]
Raidrive测试正常  挂载群辉上的alist webdav
