### ISSUE TITLE
添加webdav存储，使用IPV6地址时的问题

### ISSUE THREAD

**Issue by JayeDieyan** [alist-org/alist#6109]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30

### Driver used / 使用的存储驱动

webdav

### Describe the bug / 问题描述

webdav地址使用性问题，地址识别和windows自带的webdav地址识别一样，准确来说并不是BUG。
当使用ipv6地址连接webdav时，和windows自带的webdav一梓，需要手动进行地址转换，如IPV6地址为 http://[fdff::f]:5244时，直接这样写会报路径错误，其对应的地址需要手动将其转换为域名格式 http://ffdf--f.ipv6-literal.net:5244 才能正常使用。
对于第三方webdav连接webdav时通常不需要进行域名转换，希望Alist添加webdav存储驱动时可以识别原始的IPV6地址格式。

### Reproduction / 复现链接

alist的webdav存储驱动
![QQ截图20240228081342](https://github.com/alist-org/alist/assets/90337518/cb753e29-2cbc-41d9-ad56-9c4127d725dd)
![QQ截图20240228081458](https://github.com/alist-org/alist/assets/90337518/65b14258-90ef-4623-a952-eb4d7bd420c2)

### Config / 配置

webdav

**Comment by BubbleBearU** [comment]
正如你所说这个不是bug，是建议，其实支持的话 就是自适应嘛  之前的填写方式也要支持

**Comment by gyurmogyuri** [comment]
Thanks, I have same BUG. With my IPv6 address
