### ISSUE TITLE
最新版开关复选框开启后只能勾选了

### ISSUE THREAD

**Issue by lm379** [alist-org/alist#6113]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.31.0

### Driver used / 使用的存储驱动

所有存储均复现

### Describe the bug / 问题描述

首页打开开关复选框后无法进入文件夹或者文件详情页，只能勾选，不管点什么位置，以前的版本只有点击复选框的位置才是勾选，现在不取消复选框都没办法进存储了

### Reproduction / 复现链接

https://pan.lm379.cn/

### Config / 配置

```
{
  "force": false,
  "site_url": "https://pan.lm379.cn",
  "cdn": "https://registry.npmmirror.com/alist-web/$version/files/dist/",
  "jwt_secret": "",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }

```

**Comment by anwen-anyi** [comment]
要么关闭复选框，要么在显示多选框时，按住 alt 键点击打开文件夹（MacOS 则按住 option 键）

**Comment by zhengzavan** [comment]
> 要么关闭复选框，要么在显示多选框时，按住 alt 键点击打开文件夹（MacOS 则按住 option 键）

不理解为什么要改成这样，我想用下载的时候必须多选才能发送到aria2，但是多选模式又不能进入文件夹，频繁切换模式，按alt也也是多此一举，完全不符合直觉。
