### ISSUE TITLE
本地复制到crypt好像还是会复制到tmp再上传？大文件直接把磁盘占满了

### ISSUE THREAD

**Issue by ashesofdream** [alist-org/alist#6114]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

Crypt;Quark;Local

### Describe the bug / 问题描述

Local复制到加密的Quark会占用大量空间。

### Reproduction / 复现链接

无

### Config / 配置

docker默认

**Comment by anwen-anyi** [comment]
就是这样的 上传文件都会走`temp`临时文件夹存储然后上传，就算你不是上传到crypt，单独上传到夸克也是

**Comment by ashesofdream** [comment]
> 就是这样的 上传文件都会走`temp`临时文件夹存储然后上传（不秒传的都是），就算你不是上传到crypt，单独上传到夸克也是
https://github.com/alist-org/alist/issues/2186
https://github.com/alist-org/alist/pull/3354
我看这两个似乎是有尝试去修过了？

**Comment by woshichenghaibo** [comment]
直接把系统弄死机了
