### ISSUE TITLE
网页端播放异常，播放一段时间后会跳转视频开头让后再跳回来

### ISSUE THREAD

**Issue by lichengxun** [alist-org/alist#6122]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.30.0

### Driver used / 使用的存储驱动

aliyun

### Describe the bug / 问题描述

为了解决网页端页面空白的问题，我编辑了AList管理-“设置”-“全局”内的“自定义头部”<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll">修改为<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll&version=3.111.0">
改了这个东西后在网页端播放的时候出现放着放着跳开头 然后又跳回来的问题
我在#6100 中询问过其他人是否出现过该问题
现在是无法确定是否是该原因导致的

### Reproduction / 复现链接

http://104.168.236.145:5244/

**Comment by xhofe** [comment]
阿里云盘给的链接只有十五分钟有效期，所以会定时刷新视频链接，正常现象。

**Comment by 17629310883** [comment]
小雅机会每次看到中间都会开始重新播放其他资源，很重大bug希望能赶紧修复！

**Comment by 17629310883** [comment]
小雅几乎每次看到中间都会开始重新播放其他资源，很重大bug希望能赶紧修复！（任意播放一个视频，自然播放到中间 声音会重新播放其他视频，必须刷新页面重新播放才能解决，超级影响体验）
