### ISSUE TITLE
增加压缩功能

### ISSUE THREAD

**Issue by meiguimaizangai** [alist-org/alist#6135]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前alist支持打包下载，但是当机器性能不行的时候，边压缩边下载受性能影响严重，下载速度快不起来。所以希望增加一个压缩功能，先全部打包压缩好再下载。

**Comment by anwen-anyi** [comment]
说个和 打包下载不相关的回答，不推荐使用打包下载，尤其是文件多还大，不合适，还是推荐使用Aria2 RPC推送下载方便
 - Aria2 RPC 既不用等待打包，也不用下载好还解压，也支持下载文件夹并且保持目录状态
 - https://alist.nn.ci/zh/config/other.html#其他
