### ISSUE TITLE
alist挂载阿里云盘 将视频发送到potplayer播放后，potplayer暴力缓存整个视频，带宽占用严重

### ISSUE THREAD

**Issue by abandonstudy** [alist-org/alist#6136]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.31.0

### Driver used / 使用的存储驱动

阿里云盘open

### Describe the bug / 问题描述

alist将阿里云盘发送到potplayer播放，potplayer会暴力缓存整个视频，严重占用带宽，并且我如果切换几个大的视频（不看完，但会被完整缓存）过大流量会被阿里云盘降速/封控
如图：

https://github.com/alist-org/alist/assets/94209629/2745df1f-de43-481d-95e0-08513297ca9f

PS:我不太确定是alist还是potplayer的问题，这个缓存策略估计是potplayer定的，但还是想拜托作者找办法限制下

### Reproduction / 复现链接

无

### Config / 配置

[config.json](https://github.com/alist-org/alist/files/14470032/config.json)

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/94209629/d5ab7cef-62ae-4067-874c-2f354fa58c2c)

**Comment by ypq123456789** [comment]
这是potplayer的缓存策略，但是讲道理应该不会被封啊，我是阿里云盘open自建的api，到现在也没被封啊。我觉得这策略很好，nplayer不如potplayer的点就在这里，od这种下载能满速webdav播放不能满速的也就potplayer能治了

**Comment by yyyytawa** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [文档](https://alist.nn.ci)。
>   我已经阅读了[文档](https://alist.nn.ci)。
> * [x]  I'm sure there are no duplicate issues or discussions.
>   我确定没有重复的issue或讨论。
> * [x]  I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ，`Dependencies` 或 `Operational`).
>   我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。
> * [x]  I'm sure this issue is not fixed in the latest version.
>   我确定这个问题在最新版本中没有被修复。
> 
> ### AList Version / AList 版本
> v3.31.0
> 
> ### Driver used / 使用的存储驱动
> 阿里云盘open
> 
> ### Describe the bug / 问题描述
> alist将阿里云盘发送到potplayer播放，potplayer会暴力缓存整个视频，严重占用带宽，并且我如果切换几个大的视频（不看完，但会被完整缓存）过大流量会被阿里云盘降速/封控 如图：
> 
>  2024-03-03.00-11-18.mp4 
> PS:我不太确定是alist还是potplayer的问题，这个缓存策略估计是potplayer定的，但还是想拜托作者找办法限制下
> 
> ### Reproduction / 复现链接
> 无
> 
> ### Config / 配置
> [config.json](https://github.com/alist-org/alist/files/14470032/config.json)
> 
> ### Logs / 日志
> ![image](https://private-user-images.githubusercontent.com/94209629/309486726-d5ab7cef-62ae-4067-874c-2f354fa58c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MzE0NzksIm5iZiI6MTcwOTQzMTE3OSwicGF0aCI6Ii85NDIwOTYyOS8zMDk0ODY3MjYtZDVhYjdjZWYtNjJhZS00MDY3LTg3NGMtMmYzNTRmYTU4YzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDAxNTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMjU4OTkwNDViMDZmZmMyOWJlNjVmYWVkZDdjY2U5YmMzZmFhNjQyZGUyZGJlZjJiYzYzMmMwNzJiYjk0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-kBGkgxO--Z_dgSPPbH4OPNGLan_F5RC0dcI4kajPmc)

没法限制,302重定向文件根本不走AList的,本地代理的话可以给AList限速.缓存是PotPlayer的问题,非AList问题,AList无法也无权去限制.建议换成RaiDrive,Clouddrive等软件挂在为本地磁盘来避免PotPlayer缓存文件

**Comment by yyyytawa** [comment]
> 这是potplayer的缓存策略，但是讲道理应该不会被封啊，我是阿里云盘open自建的api，到现在也没被封啊。我觉得这策略很好，nplayer不如potplayer的点就在这里，od这种下载能满速webdav播放不能满速的也就potplayer能治了

确实,OneDrive播放一卡一卡的,就算是网页PotPlayer直接播放也会遇到下载速度不够的瓶颈.后面RaiDrive挂载AList发现只要是OneDrive的文件PotPlayer打开统统报错,而且速度很慢,后面不得已换成别的挂载软件来解决问题........
