### ISSUE TITLE
公告自动复原

### ISSUE THREAD

**Issue by GeNi114514** [alist-org/alist#6143]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.32.0

### Driver used / 使用的存储驱动

任意

### Describe the bug / 问题描述

如果公告是空白的，重启alist后会自动复原成默认公告，3.30.0版本没有问题，3.32.0版本出现该问题

### Reproduction / 复现链接

1

### Config / 配置

1

**Comment by nxjonson** [comment]
+1

**Comment by x441** [comment]
一样

**Comment by jinnan11** [comment]
AList打开后页面空白的 进入后台👉全局👉自定义头部 进行修改
 - 不知道怎么进后台的  https://域名/@manage
 
找到这条静态代码
<script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>

换成这个阿里的（直接删了也可以，但是可能会导致其他人访问时候浏览器如果不兼容会打不开）
<script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=String.prototype.replaceAll"></script>

如果使用美化教程的，请检查美化教程中是否还有重复添加

换好后还是不可以 请按 Ctrl+F5 刷新

🫶🫶🫶🫶🫶🫶🫶🫶🫶🫶🫶

AList 更新了 v3.31.0 版本，新增了一些功能，导致CSS有些变化
左侧为新增的一些功能，右侧为新增美化的CSS
美化教程文档已更新：https://anwen-anyi.github.io/index/05-head.html 
- 如果不是新版的代码可以使用 Ctrl+F5刷新
如果填补可以查看代码高亮部分，然后根据自己之前使用的配色进行修改保持一致，都有注释很好理解

新功能开启 --> 右下角设置里面
- Show sidebar(左侧标目录栏，未及时汉化下次更新补上) 
- 标题栏和导航栏的位置 --> 三种不同形态
- 打开md文件 右侧显示目录大纲（自动默认启用，关闭在右下角会看到，目前元信息填写的也会被识别出大纲后续修复）

**Comment by jiemo9527** [comment]
设置-全局也是，隐藏文件设为空（不隐藏readme）。又被自动还原为隐藏
