### ISSUE TITLE
建议加入web本地代理

### ISSUE THREAD

**Issue by a152917** [alist-org/alist#6147]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议加入web本地代理，目前的web代理为302直链，如果cloudflare Workers作为代理或者多服务器做代理会被识别为多用户使用，会被限速或者封号。

webdav也有一样的问题，如果有cloudflare Workers也会被识别为多用户，建议在本地代理的基础上在加入代理下载功能
【云盘】→【本地代理】→【代理地址】→【用户】

这样也不用担心云盘限制下载线程，同时还能把资源缓存到cdn，获得更好的下载体验。

**Comment by hahach** [comment]
你的意思是先经过本机再上传到cdn？
我有个想法，没试过，你要不要试一试？
添加一个alist v3存储类型，也就是alist挂载自己生成的webdav，目录我觉得最好选你需要这样做的目录（存储），选根目录不知道有没有循环的问题。这个alist存储用cf，被挂的存储用本地代理？
