### ISSUE TITLE
百度接口上传文件失败

### ISSUE THREAD

**Issue by conglinyizhi** [alist-org/alist#6149]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.32.0

### Driver used / 使用的存储驱动

BaiduNetdisk

### Describe the bug / 问题描述

使用 `BaiduNetdisk` 上传一个名为 `MinecraftPackage_1.18.2_匠造之传 - 百米冲刺.zip` 的文件的时候，打开管理，上传页面一直没有进度，稍后 alist 会直接崩溃

我没有找到需要输入系统信息的地方
使用的是 Ubuntu server，详细版本信息如下：
Linux version 5.15.0-91-generic (buildd@lcy02-amd64-045) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 

### Reproduction / 复现链接

很抱歉这是私有服务器，我希望尽可能的不提供我的服务器链接，我可以提供更多额外的信息，比如日志文件片段

### Config / 配置

{
  "encrypted": "",
  "settings": "Hide",
  "users": "Hide",
  "storages": [
    {
      "id": 8,
      "mount_path": ".../BaiduDisk",
      "order": 0,
      "driver": "BaiduNetdisk",
      "cache_expiration": 30,
      "status": "work",
      "addition": "{\"refresh_token\":\"122.....OT5xRQ\",\"root_folder_path\":\"/\",\"order_by\":\"name\",\"order_direction\":\"asc\",\"download_api\":\"official\",\"client_id\":\"....\",\"client_secret\":\"....\",\"custom_crack_ua\":\"netdisk\",\"AccessToken\":\"121.............WcQ99Q\",\"upload_thread\":\"3\",\"upload_api\":\"https://d.pcs.baidu.com\"}",
      "remark": ".........",
      "modified": "2024-03-03T01:41:31.079564054+08:00",
      "disabled": false,
      "enable_sign": false,
      "order_by": "",
      "order_direction": "",
      "extract_folder": "",
      "web_proxy": false,
      "webdav_policy": "native_proxy",
      "down_proxy_url": ""
    }
  ],
  "metas": []
}

### Logs / 日志

2024/03/05 22:55:19.506872 WARN RESTY Post "https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=<HideToken>&method=upload&partseq=0&path=<HidePath>%2FMinecraftPackage_1.18.2_%E5%8C%A0%E9%80%A0%E4%B9%8B%E4%BC%A0+-+%E7%99%BE%E7%B1%B3%E5%86%B2%E5%88%BA.zip&type=tmpfile&uploadid=P1-MTAuMzkuNS43NzoxNzA5NjUwNTE2OjM1MzU2OTYwNDMyNDQwMDUyMA%3D%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
2024/03/05 22:55:19.517670 WARN RESTY Post "https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=<HideToken>&method=upload&partseq=2&path=<HidePath>%2FMinecraftPackage_1.18.2_%E5%8C%A0%E9%80%A0%E4%B9%8B%E4%BC%A0+-+%E7%99%BE%E7%B1%B3%E5%86%B2%E5%88%BA.zip&type=tmpfile&uploadid=P1-MTAuMzkuNS43NzoxNzA5NjUwNTE2OjM1MzU2OTYwNDMyNDQwMDUyMA%3D%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
2024/03/05 22:55:19.594430 WARN RESTY Post "https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=<HideToken>&method=upload&partseq=1&path=<HidePath>%2FMinecraftPackage_1.18.2_%E5%8C%A0%E9%80%A0%E4%B9%8B%E4%BC%A0+-+%E7%99%BE%E7%B1%B3%E5%86%B2%E5%88%BA.zip&type=tmpfile&uploadid=P1-MTAuMzkuNS43NzoxNzA5NjUwNTE2OjM1MzU2OTYwNDMyNDQwMDUyMA%3D%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
2024/03/05 22:55:49.903185 WARN RESTY Post "https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=<HideToken>&method=upload&partseq=0&path=<HidePath>%2FMinecraftPackage_1.18.2_%E5%8C%A0%E9%80%A0%E4%B9%8B%E4%BC%A0+-+%E7%99%BE%E7%B1%B3%E5%86%B2%E5%88%BA.zip&type=tmpfile&uploadid=P1-MTAuMzkuNS43NzoxNzA5NjUwNTE2OjM1MzU2OTYwNDMyNDQwMDUyMA%3D%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
2024/03/05 22:55:50.203854 WARN RESTY Post "https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=<HideToken>&method=upload&partseq=2&path=<HidePath>%2FMinecraftPackage_1.18.2_%E5%8C%A0%E9%80%A0%E4%B9%8B%E4%BC%A0+-+%E7%99%BE%E7%B1%B3%E5%86%B2%E5%88%BA.zip&type=tmpfile&uploadid=P1-MTAuMzkuNS43NzoxNzA5NjUwNTE2OjM1MzU2OTYwNDMyNDQwMDUyMA%3D%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
2024/03/05 22:55:50.308833 WARN RESTY Post "https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=<HideToken>&method=upload&partseq=1&path=<HidePath>%2FMinecraftPackage_1.18.2_%E5%8C%A0%E9%80%A0%E4%B9%8B%E4%BC%A0+-+%E7%99%BE%E7%B1%B3%E5%86%B2%E5%88%BA.zip&type=tmpfile&uploadid=P1-MTAuMzkuNS43NzoxNzA5NjUwNTE2OjM1MzU2OTYwNDMyNDQwMDUyMA%3D%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
2024/03/05 22:56:26.362845 WARN RESTY Post "https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=<HideToken>&method=upload&partseq=2&path=<HidePath>%2FMinecraftPackage_1.18.2_%E5%8C%A0%E9%80%A0%E4%B9%8B%E4%BC%A0+-+%E7%99%BE%E7%B1%B3%E5%86%B2%E5%88%BA.zip&type=tmpfile&uploadid=P1-MTAuMzkuNS43NzoxNzA5NjUwNTE2OjM1MzU2OTYwNDMyNDQwMDUyMA%3D%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
2024/03/05 22:56:27.290637 WARN RESTY Post "https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=<HideToken>&method=upload&partseq=1&path=<HidePath>%2FMinecraftPackage_1.18.2_%E5%8C%A0%E9%80%A0%E4%B9%8B%E4%BC%A0+-+%E7%99%BE%E7%B1%B3%E5%86%B2%E5%88%BA.zip&type=tmpfile&uploadid=P1-MTAuMzkuNS43NzoxNzA5NjUwNTE2OjM1MzU2OTYwNDMyNDQwMDUyMA%3D%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
2024/03/05 22:56:27.561163 WARN RESTY Post "https://d.pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=<HideToken>&method=upload&partseq=0&path=<HidePath>%2FMinecraftPackage_1.18.2_%E5%8C%A0%E9%80%A0%E4%B9%8B%E4%BC%A0+-+%E7%99%BE%E7%B1%B3%E5%86%B2%E5%88%BA.zip&type=tmpfile&uploadid=P1-MTAuMzkuNS43NzoxNzA5NjUwNTE2OjM1MzU2OTYwNDMyNDQwMDUyMA%3D%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3

**Comment by takchichan** [comment]
解决了吗，一样的问题。不断重试/rest/2.0/pcs/superfile2

**Comment by conglinyizhi** [comment]
> 解决了吗，一样的问题。不断重试/rest/2.0/pcs/superfile2

没有，因为没人回应，这个 issues 是被我主动关闭的

**Comment by longbill** [comment]
同样的问题。导致alist不断崩溃，不断尝试。   我的是在尝试上传视频大文件的时候发生的。日志里面没有记录崩溃的原因。

**Comment by 54145a** [comment]
#5757

**Comment by longbill** [comment]
修改设置里面的分片大小到4194304就好了。这个是4m最小分片的字节数。

**Comment by cpcgskill** [comment]
> 修改设置里面的分片大小到4194304就好了。这是4m最小分片的字节数。

你好我也遇上了类似的问题， 是修改`存储/{百度网盘配置}/自定义上传分片大小`吗？
