### ISSUE TITLE
挂载quark播放时快进显示error并卡顿

### ISSUE THREAD

**Issue by ygt1233211** [alist-org/alist#6153]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.32.0（桌面版）

### Driver used / 使用的存储驱动

Windows

### Describe the bug / 问题描述

挂载quark 无论调用potplayer播放 还是网页部分 只要快进log都会显示“Maybe size incorrect or reader not giving correct/full data, or connection closed before finish.”并会卡数秒甚至几十秒不等。
尝试过重装alist但无法解决

### Reproduction / 复现链接

基本挂载quark的视频都会出现同样的情况

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "IWWeEAwcynqsfdyJ",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "C:\\Users\\ygt_1\\AppData\\Roaming\\ci.nn.alist\\data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "C:\\Users\\ygt_1\\AppData\\Roaming\\ci.nn.alist\\temp",
  "bleve_dir": "C:\\Users\\ygt_1\\AppData\\Roaming\\ci.nn.alist\\bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "C:\\Users\\ygt_1\\AppData\\Roaming\\ci.nn.alist\\log\\log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

### Logs / 日志

[AD] Starting AList...
INFO[2024-03-06 14:33:57] reading config file: C:\Users\ygt_1\AppData\Roaming\ci.nn.alist\config.json
INFO[2024-03-06 14:33:57] load config from env with prefix: ALIST_
INFO[2024-03-06 14:33:57] init logrus...
WARN[2024-03-06 14:33:57] not enable search
WARN[2024-03-06 14:34:01] init tool aria2 failed: failed get aria2 version: Post "http://192.168.50.240:6800/jsonrpc": dial tcp 192.168.50.240:6800: connectex: No connection could be made because the target machine actively refused it.
INFO[2024-03-06 14:34:01] init tool SimpleHttp success: ok
WARN[2024-03-06 14:34:01] init tool qBittorrent failed: Post "http://localhost:8080/api/v2/auth/login": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
INFO[2024-03-06 14:34:01] start HTTP server @ 0.0.0.0:5244
[GIN] 2024/03/06 - 14:34:02 | 200 | 0s | 127.0.0.1 | PROPFIND "/dav/"
INFO[2024-03-06 14:34:02] success load storage: [/PikPak], driver: [PikPak]
INFO[2024-03-06 14:34:03] success load storage: [/quark], driver: [Quark]
INFO[2024-03-06 14:34:03] [ali_open] token exchange: 

INFO[2024-03-06 14:34:03] success load storage: [/ali], driver: [AliyundriveOpen]
INFO[2024-03-06 14:34:03] success load storage: [/115], driver: [115 Cloud]
[GIN] 2024/03/06 - 14:34:06 | 207 | 1.0312ms | 127.0.0.1 | PROPFIND "/dav/"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/"
[GIN] 2024/03/06 - 14:34:19 | 200 | 434.5µs | 127.0.0.1 | GET "/assets/index.15d8d646.css"
[GIN] 2024/03/06 - 14:34:19 | 200 | 1.1061ms | 127.0.0.1 | GET "/assets/index.f05a6743.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 1.0004ms | 127.0.0.1 | GET "/assets/entry.2fe9aaeb.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 204.8µs | 127.0.0.1 | GET "/api/public/settings"
[GIN] 2024/03/06 - 14:34:19 | 200 | 90.1µs | 127.0.0.1 | GET "/api/me"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/static/manifest.json"
[GIN] 2024/03/06 - 14:34:19 | 200 | 719.4µs | 127.0.0.1 | GET "/assets/Layout.7bf6e35a.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/index.8712760c.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/index.6e7284c8.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/FolderTree.bc0bb1c2.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/index.1c00cb52.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 163.4µs | 127.0.0.1 | GET "/api/public/offline_download_tools"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | POST "/api/fs/get"
[GIN] 2024/03/06 - 14:34:19 | 200 | 210.4µs | 127.0.0.1 | POST "/api/fs/list"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/Folder.b511ba9e.css"
[GIN] 2024/03/06 - 14:34:19 | 200 | 919.4µs | 127.0.0.1 | GET "/assets/Folder.0acc51cd.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/index.1aed234b.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/icon.fd054932.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/_commonjs-dynamic-modules.30ae7933.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 509.3µs | 127.0.0.1 | GET "/assets/video_box.a8c20856.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/Paginator.9b0a5d12.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/List.9482e44b.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/helper.e1241295.js"
[GIN] 2024/03/06 - 14:34:19 | 200 | 0s | 127.0.0.1 | GET "/assets/index.2965be06.js"
[GIN] 2024/03/06 - 14:34:23 | 200 | 1.9875437s | 127.0.0.1 | POST "/api/fs/list"
[GIN] 2024/03/06 - 14:34:31 | 200 | 7.1814021s | 127.0.0.1 | POST "/api/fs/list"
[GIN] 2024/03/06 - 14:34:35 | 200 | 406.3366ms | 127.0.0.1 | POST "/api/fs/list"
[GIN] 2024/03/06 - 14:34:37 | 200 | 1.0011ms | 127.0.0.1 | POST "/api/fs/get"
[GIN] 2024/03/06 - 14:34:37 | 200 | 244.1µs | 127.0.0.1 | GET "/assets/File.c7bed0ff.js"
[GIN] 2024/03/06 - 14:34:37 | 200 | 588.9µs | 127.0.0.1 | GET "/assets/video.f5bafd86.js"
[GIN] 2024/03/06 - 14:34:37 | 200 | 511.1µs | 127.0.0.1 | GET "/assets/hls.2d616245.js"
[GIN] 2024/03/06 - 14:34:37 | 200 | 324.8µs | 127.0.0.1 | GET "/images/potplayer.webp"
[GIN] 2024/03/06 - 14:34:37 | 200 | 324.8µs | 127.0.0.1 | GET "/images/iina.webp"
[GIN] 2024/03/06 - 14:34:37 | 200 | 0s | 127.0.0.1 | GET "/images/omniplayer.webp"
[GIN] 2024/03/06 - 14:34:37 | 200 | 506.8µs | 127.0.0.1 | GET "/images/figplayer.webp"
[GIN] 2024/03/06 - 14:34:37 | 200 | 0s | 127.0.0.1 | GET "/images/vlc.webp"
[GIN] 2024/03/06 - 14:34:37 | 200 | 0s | 127.0.0.1 | GET "/images/nplayer.webp"
[GIN] 2024/03/06 - 14:34:37 | 200 | 0s | 127.0.0.1 | GET "/images/infuse.webp"
[GIN] 2024/03/06 - 14:34:37 | 200 | 0s | 127.0.0.1 | GET "/images/mxplayer.webp"
[GIN] 2024/03/06 - 14:34:37 | 200 | 710.8µs | 127.0.0.1 | GET "/images/mxplayer-pro.webp"
WARN[2024-03-06 14:34:37] ServeHttp error. err: write tcp 127.0.0.1:5244->127.0.0.1:50347: wsasend: An established connection was aborted by the software in your host machine.
WARN[2024-03-06 14:34:37] Maybe size incorrect or reader not giving correct/full data, or connection closed before finish. written bytes: 3009753 ,sendSize:1305219184,
[GIN] 2024/03/06 - 14:34:37 | 206 | 482.8344ms | 127.0.0.1 | GET "/p/quark/来自：分享/幕府将军（更新02）（务必返回文章点点末尾的小广告~）/幕府将军01（看日剧公号：日剧部屋）.mp4"
[GIN] 2024/03/06 - 14:34:37 | 206 | 273.0214ms | 127.0.0.1 | GET "/p/quark/来自：分享/幕府将军（更新02）（务必返回文章点点末尾的小广告~）/幕府将军01（看日剧公号：日剧部屋）.mp4"
WARN[2024-03-06 14:34:40] ServeHttp error. err: write tcp 127.0.0.1:5244->127.0.0.1:50345: wsasend: An existing connection was forcibly closed by the remote host.
WARN[2024-03-06 14:34:40] Maybe size incorrect or reader not giving correct/full data, or connection closed before finish. written bytes: 10747904 ,sendSize:1301180921,
[GIN] 2024/03/06 - 14:34:40 | 206 | 2.1685554s | 127.0.0.1 | GET "/p/quark/来自：分享/幕府将军（更新02）（务必返回文章点点末尾的小广告~）/幕府将军01（看日剧公号：日剧部屋）.mp4"
WARN[2024-03-06 14:34:41] ServeHttp error. err: write tcp 127.0.0.1:5244->127.0.0.1:50346: wsasend: An existing connection was forcibly closed by the remote host.
WARN[2024-03-06 14:34:41] Maybe size incorrect or reader not giving correct/full data, or connection closed before finish. written bytes: 10911744 ,sendSize:1207336960,
[GIN] 2024/03/06 - 14:34:41 | 206 | 1.4373175s | 127.0.0.1 | GET "/p/quark/来自：分享/幕府将军（更新02）（务必返回文章点点末尾的小广告~）/幕府将军01（看日剧公号：日剧部屋）.mp4"
WARN[2024-03-06 14:34:42] ServeHttp error. err: write tcp 127.0.0.1:5244->127.0.0.1:50340: wsasend: An established connection was aborted by the software in your host machine.
WARN[2024-03-06 14:34:42] Maybe size incorrect or reader not giving correct/full data, or connection closed before finish. written bytes: 9555152 ,sendSize:1163624448,
[GIN] 2024/03/06 - 14:34:42 | 206 | 699.1158ms | 127.0.0.1 | GET "/p/quark/来自：分享/幕府将军（更新02）（务必返回文章点点末尾的小广告~）/幕府将军01（看日剧公号：日剧部屋）.mp4"
WARN[2024-03-06 14:34:51] ServeHttp error. err: write tcp 127.0.0.1:5244->127.0.0.1:50343: wsasend: An existing connection was forcibly closed by the remote host.
WARN[2024-03-06 14:34:51] Maybe size incorrect or reader not giving correct/full data, or connection closed before finish. written bytes: 13139968 ,sendSize:1131380736,
[GIN] 2024/03/06 - 14:34:51 | 206 | 9.5064933s | 127.0.0.1 | GET "/p/quark/来自：分享/幕府将军（更新02）（务必返回文章点点末尾的小广告~）/幕府将军01（看日剧公号：日剧部屋）.mp4"
📖

**Comment by Alexander-Porter** [comment]
@ygt1233211 你阿里网盘的token被泄露了

**Comment by ygt1233211** [comment]
> @ygt1233211 你阿里网盘的token被泄露了

感谢提醒！

**Comment by zishuzy** [comment]
这个问题有结论了吗？我也遇到类似的问题了。
