### ISSUE TITLE
alist S3 后台配置enable， 但是实际上仍然提示未启用

### ISSUE THREAD

**Issue by lllwan** [alist-org/alist#6157]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.32.0

### Driver used / 使用的存储驱动

天翼云盘

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/32893806/80f23dc0-de5c-47bd-94ac-7bd408180624)

### Reproduction / 复现链接

无

### Config / 配置

![image](https://github.com/alist-org/alist/assets/32893806/bde3f531-3e1b-456f-8309-5c4602e6773f)

### Logs / 日志

无

**Comment by lllwan** [comment]
重启之后，报错信息变了：
![image](https://github.com/alist-org/alist/assets/32893806/171590c9-49ba-4a36-b5ce-6388e07b717d)

**Comment by xhofe** [comment]
请使用 S3 client 访问。
