### ISSUE TITLE
国外服务器天翼云盘302重定向无速度

### ISSUE THREAD

**Issue by isChengshi** [alist-org/alist#6162]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.32.0

### Driver used / 使用的存储驱动

天翼云盘

### Describe the bug / 问题描述

1.alist架在国外服务器（甲骨文首尔Arm）
①天翼云盘 302 webdav播放无速度
②天翼云盘 本地代理 有速度且不慢
③阿里云盘 302和115的302都速度很好，无问题
2.架在本地nas的天翼云盘302速度很好，无问题

### Reproduction / 复现链接

alist架在国外服务器，天翼云盘设置为302重定向，国内wendav链接播放，无速度

### Config / 配置

天翼云盘设置为302重定向

**Comment by isChengshi** [comment]
已发现，不是alist的问题，而是fileball的bug

**Comment by dts88** [comment]
我也遇到了相同的问题，天翼云盘+alist + Clouddrive2+jellyfin，302无速度，本地代理就可以，其他设置完全一致。地点在新加坡。

**Comment by qazhw** [comment]
> 我也遇到了相同的问题，天翼云盘+alist + Clouddrive2+jellyfin，302无速度，本地代理就可以，其他设置完全一致。地点在新加坡。
解决了嘛？？我也遇到了
