### ISSUE TITLE
failed get objs: failed to list objs: -1: 超时请求

### ISSUE THREAD

**Issue by Greyisttot** [alist-org/alist#6171]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.32.0

### Driver used / 使用的存储驱动

蓝奏云优享版

### Describe the bug / 问题描述

failed get objs: failed to list objs: -1: 超时请求

### Reproduction / 复现链接

failed get objs: failed to list objs: -1: 超时请求

### Config / 配置

failed get objs: failed to list objs: -1: 超时请求

### Logs / 日志

failed get objs: failed to list objs: -1: 超时请求

**Comment by Greyisttot** [comment]
更换服务器，更换账号均为超时。

**Comment by Greyisttot** [comment]
https://github.com/alist-org/alist/discussions/6169

**Comment by wxz-12138** [comment]
所以解决方案是什么啊

**Comment by blueflower1** [comment]
我的蓝奏云优享版也这样了，更新了版本也是异常

**Comment by laoqijun1** [comment]
小飞机盘也是，估摸着和蓝奏云优享版用的是同一个服务提供商

**Comment by ZOHI666** [comment]
大概啥时候能好呢

**Comment by laoqijun1** [comment]
@xhofe 正式版还有问题，编译版已经没了

**Comment by my208928** [comment]
> @xhofe 正式版还有问题，编译版已经没了

請問編譯版在何處download

**Comment by blueflower1** [comment]
> > @xhofe 正式版还有问题，编译版已经没了
> 
> 請問編譯版在何處download

根据自己的部署平台进行编译哈，自行编译即可，官方文档中有详细的编译教程，可以参考尝试

**Comment by my208928** [comment]
请指教一下，我使用的是Termux命令pkg install alist安装的，该怎么进行更新服务呢，谢谢发自我的手机

**Comment by Greyisttot** [comment]
> @xhofe 正式版还有问题，编译版已经没了

编译版一样超时 v3.32.0-13-g9c84b65
