### ISSUE TITLE
Alist 挂载webdav  PC端正常，手机端浏览器无法打开

### ISSUE THREAD

**Issue by Flying-Pika** [alist-org/alist#6179]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.32.0

### Driver used / 使用的存储驱动

Webdav

### Describe the bug / 问题描述

alist 远程挂载的webdav，同样的文件， 在pc端均能正常浏览，下载，但是在移动端就无法下载，也无法浏览。

### Reproduction / 复现链接

https://one.daddytractor.cc/share

### Config / 配置

{
  "force": false,
  "site_url": "https://one.daddytractor.cc",
  "cdn": "",
  "jwt_secret": "zHyrZuelmLzWHEEC",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": -1,
    "https_port": 443,
    "force_https": false,
    "cert_file": "data/daddytractor.cer",
    "key_file": "data/daddytractor.key",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

### Logs / 日志

移动端访问出现如下错误日志
[GIN] 2024/03/09 - 16:58:30 | 200 |    1.017321ms | 171.218.220.176 | POST     "/api/fs/get"
[GIN] 2024/03/09 - 16:58:30 | 200 |      323.04碌s | 171.218.220.176 | POST     "/api/fs/list"
[GIN] 2024/03/09 - 16:58:31 | 200 |     505.988碌s | 171.218.220.176 | POST     "/api/fs/list"
[GIN] 2024/03/09 - 16:58:33 | 200 |   10.353022ms | 171.218.220.176 | POST     "/api/fs/get"
[31mERRO[0m[2024-03-09 16:58:35] http2: stream closed                         
[GIN] 2024/03/09 - 16:58:35 | 200 |  977.124084ms | 171.218.220.176 | GET      "/p/share/t-t-21598-tommy-thumb-stick-puppets_ver_2.pdf?sign=js4QvcujcgCH0LQgT4IMPARGGUX84G5NVS-itIQ3988=:0"
Error #01: http2: stream closed

**Comment by xhofe** [comment]
这看起来是网络问题 或客户端不支持http2。

**Comment by Flying-Pika** [comment]
> 这看起来是网络问题 或客户端不支持http2。

您好，我这方面不是专业人士，查了很久，没有解决办法：
目前情况是这样：
1. alist是通过docker部署在vps里面。
2. alist通过webdav挂载威联通NAS。
3. 目前NAS的webdav设置是没有问题，在各种客户端都正常工作。
4. 网络也确定是没有问题。
5. 我在桌面端，无论是windows还是macOS上，链接都可以正常下载。
6. 在iOS的safari上，无法打开下载链接，并且alist服务器端的日志中会出现：Error #01: http2: stream closed
目前我个人认为可能是ios上safari的问题，但是又觉得不应该是这样，我是否可以通过更改alist'服务器端设置，避免这一问题。感谢🙏。
