### ISSUE TITLE
是否可以为中国移动云增加一个m3u8的解析

### ISSUE THREAD

**Issue by 814747889** [alist-org/alist#6187]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

是否可以尝试中国移动云盘的m3u8
做一个备用方案，在web预览中加入一个m3u8播放项的类型
https://yun.139.com/orchestration/personalCloud/content/v1.0/getContentInfo
Body
{"contentID":"资源ID","path":"","entryShareCatalogID":"","commonAccountInfo":{"account":"账号", “accountType”：1}}
中国移动云盘webdav的解决方法在视频资源目录中加入的m3u8目录作为播放的备选方案

**Comment by 1994qrq** [comment]
支持啊
