### ISSUE TITLE
用鼠标调节音量不能归位

### ISSUE THREAD

**Issue by Colawater** [alist-org/alist#6188]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.32.0

### Driver used / 使用的存储驱动

天翼云盘客户端、阿里云盘 Open

### Describe the bug / 问题描述

网页视频界面的音量默认为 50，用鼠标调节音量不能调节至 50。

此 Bug 在视频不全屏的情况下为几率事件，全屏状态为百分百。

1. 先随意调节音量
2. 再用鼠标调节到 50 失败，音量只跳 49和 51，会跳过 50。

键盘正常：方向键上 / 下 调节至极限，再调节为 50。

### Reproduction / 复现链接

none

### Config / 配置

none

**Comment by xhofe** [comment]
deps: https://github.com/zhw2590582/ArtPlayer
