### ISSUE TITLE
群晖hyperbackup套件 webdav挂载阿里云盘，移动云盘进行备份任务，一段时间后报错

### ISSUE THREAD

**Issue by PrestarLin** [alist-org/alist#6192]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.32.0 群晖套件，矿神打包

### Driver used / 使用的存储驱动

夸克以及移动

### Describe the bug / 问题描述

备份一段时间后，差不多是30g左右后报错，需要手动重连，夸克网盘默认开启了本机代理，移动网盘是302重定向

### Reproduction / 复现链接

without

### Config / 配置

![image](https://github.com/alist-org/alist/assets/77814393/ed044d34-b6ea-4d62-b6f3-e39bbf6ed02a)
![image](https://github.com/alist-org/alist/assets/77814393/38f01b93-e0c2-4083-8698-a7e90457c5c2)

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "PgqIYSjZPigr37nW",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "/volume4/@appdata/alist3/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": 15244,
    "force_https": false,
    "cert_file": "*",
    "key_file": "*",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "/volume4/@appdata/alist3/temp",
  "bleve_dir": "/volume4/@appdata/alist3/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "/volume4/@appdata/alist3/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }

### Logs / 日志

[log.log](https://github.com/alist-org/alist/files/14549760/log.log)

**Comment by Ahrievil** [comment]
+1 mark
