### ISSUE TITLE
大家好，我从3.8.0win amd64升到了3.32.0，但出现了错误提示：System error: TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:5244/assets/2fa.03f9113e.js

### ISSUE THREAD

**Issue by yangchaoqqq** [alist-org/alist#6195]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.32.0

### Driver used / 使用的存储驱动

2FA

### Describe the bug / 问题描述

大家好，我从3.8.0win amd64升到了3.32.0，但出现了错误提示：System error: TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:5244/assets/2fa.03f9113e.js

### Reproduction / 复现链接

http://127.0.0.1:5244/@manage/2fa

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "Ss50hr3hqls6QjKD",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data\\data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": 5244,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data\\temp",
  "bleve_dir": "data\\bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data\\log\\log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

### Logs / 日志

![屏幕截图_10-3-2024_21404_127 0 0 1](https://github.com/alist-org/alist/assets/123721430/ef0f5eca-add1-469c-80fc-25dc66f8248c)

**Comment by liuycy** [comment]
`Failed to fetch dynamically imported module` 这一类问题应该都是 [浏览器缓存](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Cache-Control) 导致的

看[代码](https://vscode.dev/github/alist-org/alist/blob/main/server/static/static.go#L92)是设置了 `max-age=15552000` 这个单位是按秒算的，换算成小时就是这些 静态文件 会缓存 4320 个小时，会不会太长了 😂

<img width="1090" alt="image" src="https://github.com/alist-org/alist/assets/55272688/295e5457-2ca1-4feb-ba5a-c1241f89a10f">

理论上讲 `2fa.ddeef545.js` 这个文件是从 `index.2b8f646e.js` 动态 improt 的，如果 `index.2b8f646e.js` 没有改动 走缓存，那里面的 import 语句应该是不会变化，但是 `2fa.ddeef545.js` 这个文件被改动了，在 build 的时候该文件的 hash 就会变化，这些静态文件如果不是增量更新而是直接全量替换，就会导致请求不到旧文件而报错的问题

<img width="953" alt="image" src="https://github.com/alist-org/alist/assets/55272688/cbcb51b3-a34a-443a-ad18-53d52f6901af">
