### ISSUE TITLE
是否可以考虑索引和配置数据库分离

### ISSUE THREAD

**Issue by snailwind** [alist-org/alist#6197]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

将存储索引数据的数据库放在前端页面上配置，配置信息就通过本地的配置文件来决定存储位置。
很多人通过网上的免费数据库等搭建，但这类服务大多限制容量，只用于储存配置信息还好，存储索引往往就不可靠了。索引可以通过本地文件或其他方式获取的数据库来存储。
其实是希望，通过网络免费数据库储存配置信息，而本地搭建的数据库储存索引，因为本地不一定一直开机没有网络服务稳定，很多时候也不需要用到索引。  因为是多地使用同一套配置的原因，偏向于使用稳定些的数据库，而个人 NAS 一直开机又大多时间闲置。 且索引数据本地化，也可以解决多端使用同一套配置索引互相覆盖的问题

### Suggested solution / 实现思路

将存储索引数据的数据库放在前端页面上配置，配置信息就通过本地的配置文件来决定存储位置。

_No response_

**Comment by IAALAI** [comment]
你别告诉我你想要把索引扔到前端的 indexDB 上。分别实现是否具有意义也值得商榷
我自己用是全扔倒本地的sqlite上，目前感觉这样用着也挺好的
