### ISSUE TITLE
docker-Container 的xhofe/alist:latest使用占用cpu高

### ISSUE THREAD

**Issue by 80718666** [alist-org/alist#6205]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

lastest

### Driver used / 使用的存储驱动

One

### Describe the bug / 问题描述

用docker Container 构建alist
'''version: '3.3'  
services:  
  alist:  
    image: 'xhofe/alist:latest'  
    container_name: alist  
    network_mode: host  
    volumes:  
      - '/volume1/docker/alist:/opt/alist/data'  
    environment:  
      - PUID=0  
      - PGID=0  
      - UMASK=022  
    restart: unless-stopped'''

构建后使用时cpu一直占用率高，关闭手机播放器软件后，alist也一直在工作，而且cpu一直占用很高，视乎有些不正常。

### Reproduction / 复现链接

![QQ截图·](https://github.com/alist-org/alist/assets/133854825/78e8b501-b636-4158-8465-d7d5898b894f)
![QQ截图2](https://github.com/alist-org/alist/assets/133854825/59691126-c151-4d46-8af6-d691a9e1e6bc)

### Config / 配置

123

### Logs / 日志

![QQ截图·](https://github.com/alist-org/alist/assets/133854825/8fbc6eb1-7abb-462a-8e94-1f11ee83fdc5)
![QQ截图2](https://github.com/alist-org/alist/assets/133854825/fb8ad216-7b26-4c26-adf5-d9fc11f6e6a9)

**Comment by 80718666** [comment]
电报群有人说可能是本地回环导致，可是要怎样修复和改善这个问题呢，因为也需要用到本地回环访问。。

**Comment by woshichenghaibo** [comment]
我的占15%左右。

**Comment by woshichenghaibo** [comment]
那用什么版本？怎么安装？
________________________________
发件人: msycn ***@***.***>
发送时间: 2024年3月26日 22:36
收件人: alist-org/alist ***@***.***>
抄送: woshichenghaibo ***@***.***>; Comment ***@***.***>
主题: Re: [alist-org/alist] docker-Container 的xhofe/alist:latest使用占用cpu高 (Issue #6205)


解决方法找到了: 不用Docker版

―
