### ISSUE TITLE
既然都用上数据库了，为什么不增加一个登录功能呢？

### ISSUE THREAD

**Issue by im-dashan** [alist-org/alist#6216]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

既然都用上数据库了，为什么不增加一个登录功能呢？希望能添加一个登录功能，就不要用单点登录了，挺麻烦的

**Comment by IAALAI** [comment]
?
这个问题就很奇怪，意义不明的说

**Comment by IAALAI** [comment]
你难道是想说增加一个注册功能？

**Comment by im-dashan** [comment]
哦哦哦，是注册功能，才发现打错了

IAALAI ***@***.***>于2024年3月13日 周三22:47写道：

**Comment by IAALAI** [comment]
你这字，错的可不是一般的离谱啊。。。
后端API是有增加用户相关功能，但是设计之初就没想到让一个陌生的用户进行注册有关的功能
如果你想要增加注册我估计要改的东西还挺多的

**Comment by im-dashan** [comment]
改不了太多，就增加一个登录Api就行了，前端登录界面改改，一个最简单的登录功能就行，不需要太多的验证，数据库表我看了一下，也是现成的，就 user 个
passwd 就够了

IAALAI ***@***.***>于2024年3月13日 周三23:12写道：

**Comment by woshichenghaibo** [comment]
没有任何必要。

**Comment by im-dashan** [comment]
太有必要了

woshichenghaibo ***@***.***>于2024年3月14日 周四11:24写道：

**Comment by JsonSong89** [comment]
这种非核心功能,社区驱动的项目一般都不想做,也没必要做
用户管理模块自己外置管理吧

**Comment by im-dashan** [comment]
出个收费，功能完全的pro 版就好了，哎，

JsonSong89 ***@***.***>于2024年3月18日 周一14:11写道：

**Comment by IAALAI** [comment]
这个得要你自己出钱找人为你专门开发了，这个是只有你需要的功能
