### ISSUE TITLE
对象存储OSS如果配置自定义Host（此host走CDN）时下载文件不会自动增加签名参数

### ISSUE THREAD

**Issue by 2545504198** [alist-org/alist#6218]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.32.0

### Driver used / 使用的存储驱动

对象存储OSS

### Describe the bug / 问题描述

如题，如果对象存储OSS配置私有那么使用CDN中转（因为CDN流量便宜），配置了Host后不会增加签名参数，但是不配置Host时是有的

### Reproduction / 复现链接

https://ecs.eryun.top/backup-NAS/%E4%B8%AA%E4%BA%BA/%E7%AC%94%E8%AE%B0/%E4%B8%B4%E6%97%B6.md

### Config / 配置

![image](https://github.com/alist-org/alist/assets/31626186/e38050bc-432d-4813-80b9-2fd016405806)

**Comment by hailcar** [comment]
一直下载失败,我也在查这个问题,看到你这才明白过来。
变通方法，如果你的域名是a.com, 桶的名字 b, 自定义host为 b.a.com 
存储桶填b, endpoint填 a.com, 自定义host不填,我可以下载成功

**Comment by 2545504198** [comment]
> 一直下载失败,我也在查这个问题,看到你这才明白过来。 变通方法，如果你的域名是a.com, 桶的名字 b, 自定义host为 b.a.com 存储桶填b, endpoint填 a.com, 自定义host不填,我可以下载成功

我试过不填Host也就是使用默认域名是正常的，但是一旦写了Host就不会自动添加参数了，桶是私有的（为了安全），，就没办法使用了

**Comment by hailcar** [comment]
按照我的方法填他不久走cdn了么

**Comment by 2545504198** [comment]
是走了，但是访问不了
![image](https://github.com/alist-org/alist/assets/31626186/f179909e-9751-4cbe-b645-9880bd2df3e9)

**Comment by 2545504198** [comment]
你的现在能用么

**Comment by hailcar** [comment]
你咋填的啊， 用你cdn的域名。 我走cloudflare代理oss可以下载

**Comment by 2545504198** [comment]
> 按照我的方法填它不就走cdn了么

我好像知道咋回事了，你用的阿里云的的话看下你CDN配置里面下面三项开了没有，没开的话只能支持公共读，加密参数Alist里面应该是过去了，我现在填Host能下载了
![image](https://github.com/alist-org/alist/assets/31626186/c9224948-2f97-41a8-8163-20526ae6baac)

**Comment by 2545504198** [comment]
还有你为啥用CF代理OSS的，那玩意又不会更便宜

**Comment by 2545504198** [comment]
> 香港aliyunoss，走cloudflare,不是免流量费用么

好吧，触及盲区了

**Comment by hailcar** [comment]
你图里域名啥信息透露的有点多估计要换一个桶了

**Comment by 2545504198** [comment]
> > 按照我的方法填它不就走cdn了么
> 
> 我好像知道咋回事了，你用的阿里云的的话看下你CDN配置里面下面三项开了没有，没开的话只能支持公共读，加密参数Alist里面应该是过去了，我现在填Host能下载了 ![image](https://private-user-images.githubusercontent.com/31626186/312769660-c9224948-2f97-41a8-8163-20526ae6baac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDczMTYsIm5iZiI6MTcxMDQwNzAxNiwicGF0aCI6Ii8zMTYyNjE4Ni8zMTI3Njk2NjAtYzkyMjQ5NDgtMmY5Ny00MWE4LTgxNjMtMjA1MjZhZTZiYWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA5MDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNGQ2ZTIxNjg5OGMzMGUxZTNjYmRmY2Q1YzI2YTA2NjM2MjM1ZTZjNmYxMWNiNGRiMjc1ZjBmZjcyN2FmMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BdpbnvXkNTF8K_-7tloIA1B6jRuypt0gidF_xrX2TVg)

不对，还是有问题，配置的那几个CDN选项是免认证用的，还以为是传参问题

**Comment by hailcar** [comment]
那你还是按照我说的试试吧

**Comment by 2545504198** [comment]
> 那你还是按照我说的试试吧

我试过，认证过不去，签名参数倒是有，但是没用
![image](https://github.com/alist-org/alist/assets/31626186/38863d1f-ca01-4a3d-9a36-c30752e14e82)
![image](https://github.com/alist-org/alist/assets/31626186/244580ff-ca94-4cce-91b6-93a9ab541a06)

**Comment by hailcar** [comment]
你的桶不是那个eryuns-ecs
你的cdn域名应该是eryuns-ecs.eryun.top

**Comment by anwen-anyi** [comment]
> https://ecs.eryun.top/backup-NAS/%E4%B8%AA%E4%BA%BA/%E7%AC%94%E8%AE%B0/%E4%B8%B4%E6%97%B6.md

这是你对象存储的域名吧？ 这个加密和AList有什么关系嘛，你这是真实链接吖而且也没办法加吧，加了你也没法用

你应该看AList的复制链接才对，我添加的CF R2对象存储也使用了自定义host，复制链接是加密的没问题吖

![image](https://github.com/alist-org/alist/assets/56105412/c31a97e0-c198-4788-9f66-efb46561c97a)

**Comment by 2545504198** [comment]
> > https://ecs.eryun.top/backup-NAS/%E4%B8%AA%E4%BA%BA/%E7%AC%94%E8%AE%B0/%E4%B8%B4%E6%97%B6.md
> 
> 这是你对象存储的域名吧？ 这个加密和AList有什么关系嘛，你这是真实链接吖而且也没办法加吧，加了你也没法用
> 
> 你应该看AList的复制链接才对，我添加的CF R2对象存储也使用了自定义host，复制链接是加密的没问题吖
> 
> ![image](https://private-user-images.githubusercontent.com/56105412/312778764-c31a97e0-c198-4788-9f66-efb46561c97a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDg3MjMsIm5iZiI6MTcxMDQwODQyMywicGF0aCI6Ii81NjEwNTQxMi8zMTI3Nzg3NjQtYzMxYTk3ZTAtYzE5OC00Nzg4LTlmNjYtZWZiNDY1NjFjOTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA5MjcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMTRjYjMyZWNhZGYzNzg2NDNjODBkYWE4OTRmYjEyNjUwMTdkNjlhZDRhYThkYmI0MzAxODljOTE2OTEwNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EOAQbkvTHAblFzGdlODaEZXfX4zOFmNbgcwZXDpN54c)

你看下这个：https://alist.eryun.top/d/OSS/WX.jpg?sign=-tvBiGPtG7YU75UR9iTfMy9_YygzxEMmTIjChYJzNMI=:0，跳转之后没有签名参数了

**Comment by 2545504198** [comment]
不是的，这个只是示例情况用的，实际是跳转之后参数是空的，就跟这个链接一样的性质

**Comment by 2545504198** [comment]
> 你的桶不是那个eryuns-ecs 你的cdn域名应该是eryuns-ecs.eryun.top

试了一下，跟之前是一样的签名错误

**Comment by hailcar** [comment]
现在的参数截图让我看一下

**Comment by 2545504198** [comment]
![image](https://github.com/alist-org/alist/assets/31626186/29619810-c676-4351-8d91-cb17cfb9554f)
![image](https://github.com/alist-org/alist/assets/31626186/907ea9f2-7c92-4a1c-a600-00b20d7c8c8f)



> 现在的参数截图让我看一下

**Comment by hailcar** [comment]
endpoint错了， endpoint填你自己的域名eryun.top

**Comment by hailcar** [comment]
这个方法原理就是
cdn把 桶名.eryun.top cname到了 桶名.oss-cn-beijing.aliyuncs.com

**Comment by 2545504198** [comment]
> endpoint错了， endpoint填你自己的域名eryun.top

现在改了，你打开https://alist.eryun.top/试试，签名是有了，但是是错误的

**Comment by hailcar** [comment]
我看了我的有中文会encode掉

**Comment by 2545504198** [comment]
> 我看了我的有中文会encode掉

跟这个关系不大吧，默认域名就能直接使用，不论是不是中文

**Comment by hailcar** [comment]
我没启用签名，移除bucket和添加filename没选

**Comment by 2545504198** [comment]
> 我没启用签名，移除bucket和添加filename没选

那估计确实跟这些选项关系不大，主要还是自定义Host没加签名的问题

**Comment by hailcar** [comment]
我这个方法自定义host不用加，留空

**Comment by 2545504198** [comment]
> 我这个方法自定义host不用加，留空

我知道，试过好几次了，报错签名错误

**Comment by hailcar** [comment]
建议对照一下
变通方法，如果你的域名是a.com, 桶的名字 b, 自定义host为 b.a.com
存储桶填b, endpoint填 a.com, 自定义host不填

**Comment by 2545504198** [comment]
![image](https://github.com/alist-org/alist/assets/31626186/01e69f60-24b3-47a8-869f-a64e8d26320c)
现在我配置成这样了，你试一下
https://alist.eryun.top/

**Comment by hailcar** [comment]
最后区别 我直接挂载在根目录下面，下载之后没有多出一个文件夹
你也试试 再不行也没办法了

**Comment by hailcar** [comment]
还有存储桶填其他的应该也没问题，只要桶名+域名能cname到指定域名就没问题

**Comment by hailcar** [comment]
你的oss是不是没有绑定域名啊eryuns-ecs.eryun.top

**Comment by 2545504198** [comment]
域名绑定过，而且也CDN解析了
暂时等修复吧，先用默认的用着

**Comment by aoxue** [comment]
我也遇到了同样的问题，阿里云Bucket设置读写权限是私有的，如果设置了自定义域名，签名就没有了，不设置链接是正常的。
因为我需要用来存放apk文件，阿里云oss规定必须使用自定义域名来访问，这个BUG会在近期修复吗？
https://api.aliyun.com/troubleshoot?q=0048-00000200

**Comment by 2545504198** [comment]
是这个说法，但是对于私有分享的话这样就成了公开访问了，不如直接公开桶，当然我也仅仅说是这个，大部分人既然是分享基本就不会使用私有权限

**Comment by MoeGakuen** [comment]
@eryunser hi 老哥，这个问题你解决了吗，想请教一下
