### ISSUE TITLE
配置onedrive的“根文件夹路径”无论填什么路径显示的都是网盘的全部内容

### ISSUE THREAD

**Issue by redstoneleo** [alist-org/alist#6220]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

最新版

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

配置onedrive的“根文件夹路径”无论填什么路径也不管路径是否存在显示的都是网盘的全部内容，希望更正这个功能，比如说我的onedrive里的根目录下面有个test文件夹，我填/test之后只能显示该文件夹的内容

### Reproduction / 复现链接

无法提供

### Config / 配置

![image](https://github.com/alist-org/alist/assets/5896180/3514211a-d25c-4d18-a1d8-24f3b5f5af16)

**Comment by im-dashan** [comment]
这个可以解决的，挂载/后路径和onedrive保持一致就好了，只能挂载/,确实有bug，可以按我这样就不会乱了

**Comment by xhofe** [comment]
https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8A%E4%BC%A0%E7%9A%84%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA-%E5%88%A0%E9%99%A4%E7%9A%84%E6%96%87%E4%BB%B6%E8%BF%98%E5%9C%A8-%E4%BF%AE%E6%94%B9%E6%A0%B9%E7%9B%AE%E5%BD%95%E4%B8%8D%E7%94%9F%E6%95%88

**Comment by suykjay** [comment]
重新启动Alist或者刷新缓存即可

**Comment by redstoneleo** [comment]
我按照两位的说法刷新缓存还是老样子，所以不是缓存的问题

**Comment by redstoneleo** [comment]
问题仍然存在

**Comment by 194180194** [comment]
我是用1panel安装的alist，也是OneDrive，刚开始也是这样，后来我去1panel重启alist就行了

**Comment by im-dashan** [comment]
你说的 1panel 是什么，怎么没有听过，不过我的问题现在解决了

黎明前的浪曼 ***@***.***>于2024年6月23日 周日11:00写道：

**Comment by EricZhou05** [comment]
重启alist即可解决
