### ISSUE TITLE
使用MySQL作为数据库，设置页面的选项顺序是乱的

### ISSUE THREAD

**Issue by linzeliang1222** [alist-org/alist#6231]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.32.0

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

初次启动，使用MySQL作为数据库，设置页面的选项顺序是乱的，使用sqlite就正常，数据库编码是utf8mb4，字符集编码是utf8mb4_0900_ai_ci
<img width="1135" alt="image" src="https://github.com/alist-org/alist/assets/27925260/e0723155-2e97-41b0-ab31-bc42bc3f3940">

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by j2rong4cn** [comment]
这个PR会修复
* #6560

**Comment by itsHenry35** [comment]
closed in https://github.com/alist-org/alist/pull/6560
