### ISSUE TITLE
网站反应慢，文件上传至阿里云后要等好久才能在alist上显示出来

### ISSUE THREAD

**Issue by rEco1LLLL** [alist-org/alist#6247]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

网站反应慢，文件上传至阿里云后要等好久才能在alist上显示出来，目前只能依靠停止alist再启动才能在alist上快速显示刚转存的资源，希望可以增强alist响应速度

**Comment by huolanyun** [comment]
通过alist上传的是实时显示的，因为访问频率问题，过快容易提示错误，后台添加驱动的时候 你可以看下时间，默认30分钟
你也可以通过阿里云客户端同步后，再去alist上刷新一下即可
