### ISSUE TITLE
使用aria2下载时文件分割符错误

### ISSUE THREAD

**Issue by mzbgf** [alist-org/alist#6252]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.32.0

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

或许alist调用aria2rpc时使用了错误的文件分隔符
我试图通过aria2将文件离线下载到alist drive中，但最终alist指示文件不存在

```transfer /opt/alist/data\temp/aria2/5b1b949b```

一些信息：
我的alist通过一键脚本安装在ubuntu上，然后我使用docker安装了aria2，我使用命令```docker run -v /opt/alist/data:/opt/alist/data ...```来确保文件互通，但我发现alist要求aria2把文件下载到'/opt/alist/data\temp/aria2/'而不是'/opt/alist/data/temp/aria2/'，最终alist从'/opt/alist/data\temp/aria2/'取走这些文件

### Reproduction / 复现链接

在linux上运行alist和aria2, 使用alist的aria2离线下载功能，然后运行以下命令:
```ls /opt/alist```
然后你将会看到:
```
# ls /opt/alist
 alist   data  'data\temp'
 ```
 

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "https://jsd.onmicrosoft.cn/npm/alist-web@$version/dist",
  "jwt_secret": "*****",
  "token_expires_in": 48,
  "database": {
     *****
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data\\temp",
  "bleve_dir": "data\\bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data\\log\\log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 16,
      "max_retry": 2
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 8,
      "max_retry": 2
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

**Comment by xhofe** [comment]
你的配置文件不是自动生成的？
