### ISSUE TITLE
设置允许修改上传文件大小限制

### ISSUE THREAD

**Issue by superen7527** [alist-org/alist#6258]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

通过文档 "上传表单文件"和"流式上传"，写了一个api本地上传到云盘。测试效果小文件没问题。但是大文件会显示413文件太大。目测是超过100mb还是200mb就会触发？

一开始以为是存储盘限制 把所有存储(我试过onedrive官方上传1g没有问题)全试了一下都是这样 得出结论应该是api这里限制了，而且返回太大报错还不是json而是html格式。能不能后台添加最大文件限制或者直接不限制上传大小？

**Comment by xhofe** [comment]
未限制，检查前置代理。
