### ISSUE TITLE
请求添加分块上传功能api

### ISSUE THREAD

**Issue by superen7527** [alist-org/alist#6259]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在一些使用场景里，比如cdn限制单次上传文件的大小。寻求解决方案，发现大部分处理是使用分块上传 如https://github.com/khanzadimahdi/UploadManager 以及WordPress里也有类似插件绕过上传限制。

这个功能无法通过现有的上传api实现(客户端分割后分块上传后会产生多个小文件)，只能通过开发团队实现新的上传api上传后自动合并，可惜我不懂编程没办法pr只能提个issue。如果好实现的话后面能否支持？如果太难就算了，我再寻求别的方案，感谢项目。

**Comment by xhofe** [comment]
duplicate with #5480
