### ISSUE TITLE
添加驱动后 能不能看到 在前台或者后台 看到 剩余空间 100M/10G 这样的显示

### ISSUE THREAD

**Issue by huolanyun** [alist-org/alist#6262]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

添加驱动后 能不能看到 在前台或者后台 看到 剩余空间 100M/10G 这样的显示
不知道能不能实现

**Comment by anwen-anyi** [comment]
不出意外 应该不能 :joy_cat:

**Comment by sunny-00001** [comment]
但是clouddrive好像实现了这个功能，其他的webdav挂载服务空间显示都是有问题的

**Comment by xx6z8v** [comment]
据我所知，像OneDrive,百度 这些开放Api服务的是可以使用Api获取已用空间和总空间的

**Comment by IAALAI** [comment]
理论上应该是可以的

**Comment by IAALAI** [comment]
该加载哪里好？是加在后台管理界面吗?如果是前台的目录的设计似乎是对于存储无感的，去查询是哪个存储还有额外需求。要不然做到后台的那个存储里面。刚好管理的时候看到总容量和使用量来，然后挂载之后手动刷新去调取最新数据，给那个状态下面加一行使用量怎么怎么样？

**Comment by IAALAI** [comment]
![image](https://github.com/alist-org/alist/assets/50038322/00371022-472a-49c1-b960-cc87ce50d53a)
给某一个加还算比较容易，比如百度网盘这种有文档的。但是如果给全面都加上，再加上 alist 的 api和前端就得要点时间了

**Comment by Newdea** [comment]
想要这样的功能，这样就方便在上传文件时清楚空间是否足够，整理文件也会方便些。

**Comment by IAALAI** [comment]
虽然这个issues 被关闭了，但是我仍然还在开发中

**Comment by IAALAI** [comment]
虽然这个issues 被关闭了，但是我仍然还在开发中
