### ISSUE TITLE
迅雷云盘总是添加失败，偶尔成功也是很快过期。 

### ISSUE THREAD

**Issue by curryhendry** [alist-org/alist#6264]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.31.0

### Driver used / 使用的存储驱动

迅雷

### Describe the bug / 问题描述

Failed init storage: ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: client_id:"Xp6vsxz_7IYVw2BB" meta:{key:"phone_number" value:"+86 18*********"} meta:{key:"result" value:"review"} result:review

感谢指点

### Reproduction / 复现链接

..

### Config / 配置

..

**Comment by curryhendry** [comment]
> ### See
> 1. 55% [阿里云盘视频转码播放被限制15分钟  #5631](https://github.com/alist-org/alist/issues/5631)
> 2. 55% [鉴权失败  #4615](https://github.com/alist-org/alist/issues/4615)
> 3. 55% [阿里云盘无法设置根文件夹  #1873](https://github.com/alist-org/alist/issues/1873)
> 4. 52% [百度网盘本地代理下载的时候会500炸掉  #5970](https://github.com/alist-org/alist/issues/5970)
> 5. 52% [windows部署失败  #5914](https://github.com/alist-org/alist/issues/5914)
> 6. 52% [能把derivers功能独立出来吗?  #5499](https://github.com/alist-org/alist/issues/5499)
> 7. 52% [希望加入图片的缩略图直链  #4630](https://github.com/alist-org/alist/issues/4630)
> 8. 52% [挂载的百度网盘，无法加载及下载  #4628](https://github.com/alist-org/alist/issues/4628)
> 9. 52% [2023年3月23日Alist挂载115网盘后，资源无法下载读取，导致全面失效。目前报Internet服务错误500  #3937](https://github.com/alist-org/alist/issues/3937)
> 10. 52% [ 使用阿里open接口能力自动转存阿里分享文件到用户自己的阿里云盘，进而解决阿里分享限速。 #3855](https://github.com/alist-org/alist/issues/3855)
> 11. 52% [希望增加读取同一个文件下的视频字幕  #1572](https://github.com/alist-org/alist/issues/1572)
> 12. 52% [阿里网盘refresh_token（刷新令牌）获取不到token  #860](https://github.com/alist-org/alist/issues/860)
> 13. 51% [挂载另一个alist时，对方的证书可能有问题，忽略对方的证书错误问题  #3306](https://github.com/alist-org/alist/issues/3306)
> 14. 50% [更新索引无效  #5564](https://github.com/alist-org/alist/issues/5564)
> 15. 50% [ . #5309](https://github.com/alist-org/alist/issues/5309)
> 16. 50% [Crypt能否支持base32768的filename_encoding  #5109](https://github.com/alist-org/alist/issues/5109)
> 17. 50% [livp（实况)图片无法下载  #4890](https://github.com/alist-org/alist/issues/4890)
> 18. 50% [在windows服务控制管理器中注册成服务无法启动  #3071](https://github.com/alist-org/alist/issues/3071)
> 19. 50% [onedrive  #2862](https://github.com/alist-org/alist/issues/2862)

您好，以上问题都不相关。

**Comment by curryhendry** [comment]
> ＋86后面空一格，点保存，会跳出错误的弹窗，然后打开弹窗里的url 获取验证码验证一下，点确认没反应不用管，返回alist之后点保存

就是这样添加的，就是我现在这个提示。

**Comment by curryhendry** [comment]
> @curryhendry 验证码输入了还是一样？ 他的验证码不是alist的那个验证码，是另外一个网页 ![截图_20240325175312](https://private-user-images.githubusercontent.com/24273319/316459240-b75a6adc-1401-482c-8309-0b84cd771cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjk0NTQsIm5iZiI6MTcxMTM2OTE1NCwicGF0aCI6Ii8yNDI3MzMxOS8zMTY0NTkyNDAtYjc1YTZhZGMtMTQwMS00ODJjLTgzMDktMGI4NGNkNzcxY2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEyMTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NGMxOTA5MzM4NTFkZjI4YTQ5MDBlYTNiY2E4ZmVkYzUzYTI3ZWIzMTM3MjE4NDA3ZjkxN2I4MjY1MjhhZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BmFD9qn0Dh72-7Iaq4VhGwYIOj5cJ8eJ2sVugzL7rk4)

不加86、+86、+86空格，都试过了，只有最开始的时候可以添加。操作方法是对的。
认证的页面，不论自动还是查看源文件获取token都试过。都是这样的结果。
而且，只有不加86才会有那个认证，+86直接报错。

**Comment by curryhendry** [comment]
> @curryhendry 你的短信验证码页面出来了没？ 点保存之后有一个不一样的报错弹窗在右上角 你把它全部复制到记事本，然后就能看到url了 ![截图_20240325203856](https://private-user-images.githubusercontent.com/24273319/316501586-fbcc4b9f-1cac-4e46-900a-f43e49adbcf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDg3ODMsIm5iZiI6MTcxMTQwODQ4MywicGF0aCI6Ii8yNDI3MzMxOS8zMTY1MDE1ODYtZmJjYzRiOWYtMWNhYy00ZTQ2LTkwMGEtZjQzZTQ5YWRiY2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIzMTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNzg0ZTU5ZDFiZWYxM2EwNDc4MjMzMjM0ZmI5NDgxNGY2ZjA4MGQ1ZThlOTcxMTM5Yzc4NDUwMTZjZTBkNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.83AvcTqWzu7y2MVPWyEdNw_MWs8rQcUBAwkgoVAziSs)

出来了，我也收到短信验证码了。我所提的问题，都在短信验证码之后的步骤。
我之前添加成功过，操作是没问题的，不知道怎么就是报错。

**Comment by 821368256** [comment]
文档里的方法已经过时，复制打开链接后，f12把浏览器设置成手机一样的长方形，这样可以拉动下面滑动的图片，拼好图后，按以前的方法，会查看到内容Failed to launch 'xlaccsdk01://xunlei.com/callback?state=harbor&state=undefined&captcha_token=ckXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&expires_in=558' because the scheme does not have a registered handler.
复制captcha_token的内容就能正常使用。
我刚测试过

**Comment by curryhendry** [comment]
> 文档里的方法已经过时，复制打开链接后，f12把浏览器设置成手机一样的长方形，这样可以拉动下面滑动的图片，拼好图后，按以前的方法，会查看到内容Failed to launch 'xlaccsdk01://xunlei.com/callback?state=harbor&state=undefined&captcha_token=ckXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&expires_in=558' because the scheme does not have a registered handler. 复制captcha_token的内容就能正常使用。 我刚测试过

你好，“f12把浏览器设置成手机一样的长方形，这样可以拉动下面滑动的图片，拼好图后，”
这句话没懂，下滑的图片什么？

**Comment by donkeykangwang10** [comment]
我和你的问题一样，迅雷过一阵子就会挂载失败。显示的错误信息和你一样
