### ISSUE TITLE
在手机上feijipan跟ilanzou在没有独立播放器的浏览器都无法播放视频

### ISSUE THREAD

**Issue by Greyisttot** [alist-org/alist#6267]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

ilanzou,feijipan

### Describe the bug / 问题描述

never
no-referrer
same-origin

alist自带same-origin不知道其他两种meta标签是否能工作，我也不知道在哪里修改无法测试。

alist自带的播放器也无法播放，另外测试了天翼云盘，所有方式都可以播放。

**Comment by zuilintan** [comment]
类似的情况，在Chrome上，pikpak无法播放部分视频（非H265），
但在手机版夸克上却可以正常播放

**Comment by Greyisttot** [comment]
> 类似的情况，在Chrome上，pikpak无法播放部分视频（非H265）， 但在手机版夸克上却可以正常播放

UC和夸克都是独立的播放器，其他浏览器都测试了，全都不行。

**Comment by zuilintan** [comment]
> > 类似的情况，在Chrome上，pikpak无法播放部分视频（非H265）， 但在手机版夸克上却可以正常播放
> 
> UC和夸克都是独立的播放器，其他浏览器都测试了，全都不行。不是格式问题，是防盗链。

可能你我的情况不完全一样，我这边只有部分视频会如此，特别奇怪，我一度怀疑是解码器的问题

**Comment by zuilintan** [comment]
> > > 类似的情况，在Chrome上，pikpak无法播放部分视频（非H265）， 但在手机版夸克上却可以正常播放
> > 
> > 
> > UC和夸克都是独立的播放器，其他浏览器都测试了，全都不行。不是格式问题，是防盗链。
> 
> 可能你我的情况不完全一样，我这边只有部分视频会如此，特别奇怪，我一度怀疑是解码器的问题。
> 
> ![image](https://private-user-images.githubusercontent.com/34953840/316913604-1741c299-80cf-48ce-be7d-52bfb4d95a7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMTEzNTAsIm5iZiI6MTcxMjMxMTA1MCwicGF0aCI6Ii8zNDk1Mzg0MC8zMTY5MTM2MDQtMTc0MWMyOTktODBjZi00OGNlLWJlN2QtNTJiZmI0ZDk1YTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA5NTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYWYxZWI0ZWY5MGY2ZGUzZDcxOTk3NmI4OTAzYzdiYjQwNDljYjUxOTA2MTNlZjFlYWJiYWM2ODQxNjIwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Nm4EzQtYje6jEIgN4sFUddMQ0NvGStAWNGqtnfm6Gk)

通过PikPak官方WebDav方式，并关闭视频优化，该问题解决
