### ISSUE TITLE
蓝奏云优享版的bug

### ISSUE THREAD

**Issue by yunzhongci** [alist-org/alist#6271]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

蓝奏云优享版

### Describe the bug / 问题描述

添加蓝奏云优享版之后
挂在的根目录为/蓝奏云
然后在里面创建新的文件夹
在alist里面新创建的文件夹路径上会自动嵌套一个同名文件夹。而这个同名文件夹其实映射的是根目录挂载的。
比如，我在/蓝奏云优享 这个根目录里新创建了一个测试文件夹
出现的 /蓝奏云优享/测试 其实跟/蓝奏云 是一样的
/蓝奏云/测试/测试 这个才是新创建的文件夹。
<img width="435" alt="image" src="https://github.com/alist-org/alist/assets/49399931/f8eb4b35-3118-4c95-8761-6d42e89d1ecd">

而蓝奏云优享版那边其实只在根目录下有一个测试 文件夹。并没有实质上生成嵌套的两个文件夹
<img width="572" alt="image" src="https://github.com/alist-org/alist/assets/49399931/eb4fe221-4e1f-4cca-9674-1c00c3d6c78f">

### Reproduction / 复现链接

……

### Config / 配置

……

**Comment by yu9955** [comment]
飞机盘也有这个问题，新建的文件夹，会直接套根目录，复制东西过去会直接到根目录

**Comment by Moebyte** [comment]
这个问题依旧存在
