### ISSUE TITLE
安装alist后网页空白 这问题太诡异了

### ISSUE THREAD

**Issue by yespush** [alist-org/alist#6272]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.33.0

### Driver used / 使用的存储驱动

no

### Describe the bug / 问题描述

本机windows11安装alist后，首次打开网页是正常的，当关闭alist再重开运行，网页就显示空白，重装alist或系统重启或换其它浏览器都一样，但重装系统后安装alist，首次打开网页正常，重启alist问题又出现了。在虚拟机(windows11)上安装运行重启，网页却一切正常，束手无策了

### Reproduction / 复现链接

no

### Config / 配置

![PixPin_2024-03-26_23-05-03](https://github.com/alist-org/alist/assets/137385859/9dfc60a6-4a2f-416b-a1d3-a26cfe82f0ad)

**Comment by liuycy** [comment]
<img width="626" alt="image" src="https://github.com/alist-org/alist/assets/55272688/8aa1c051-0b9a-482b-941b-a19d49b5387c">
把这个钩上刷新页面试试

**Comment by yespush** [comment]
> <img alt="图像" width="626" src="https://private-user-images.githubusercontent.com/55272688/317098998-8aa1c051-0b9a-482b-941b-a19d49b5387c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDg0MDgsIm5iZiI6MTcxMTUwODEwOCwicGF0aCI6Ii81NTI3MjY4OC8zMTcwOTg5OTgtOGFhMWMwNTEtMGI5YS00ODJiLTk0MWItYTE5ZDQ5YjUzODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAyNTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkY2JhYzk2ZGFkM2U4ZGMxN2Q5MjgzZTZjZTQ0OTdhYmM0ZDgxMTBlZjEwNmM1YzExMTkxYzRiMzYyZDRkNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4a-dbuPwk8WLcfsxv_6ZBdZyBMExO93HnvwWIGmQdcM"> 把这个钩子放在刷新页面上尝试

![2](https://github.com/alist-org/alist/assets/137385859/5df7b35f-1bf1-480b-b2c2-342d4f004ad5)
还是一样

**Comment by xhofe** [comment]
#184
