### ISSUE TITLE
挂载 CloudFlare R2 失败

### ISSUE THREAD

**Issue by Mooling0602** [alist-org/alist#6274]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

对象存储

### Describe the bug / 问题描述

挂载 CloudFlare R2 后，进入对应目录显示报错（浏览器环境），详见 Logs

### Reproduction / 复现链接

可参见 Logs，若需要更多信息可以通过回复的方式要求提供

### Config / 配置

详细信息见此网页：https://www.yuque.com/clemooling/personal_note/alist-config

### Logs / 日志

![Screenshot_20240327-151717_Chrome](https://github.com/alist-org/alist/assets/147964268/042d0f91-3b51-4078-913d-d78ee4a174b8)

**Comment by anwen-anyi** [comment]
地区你写的什么? APAC  还有会话令牌你填的啥~ 这俩参数怎么得来的~

我这边测试是没问题的 `v3.33.0` 也添加了自定义host
![image](https://github.com/alist-org/alist/assets/56105412/e4115cf7-e890-4573-bcfd-49066bb5a2fa)
![image](https://github.com/alist-org/alist/assets/56105412/fdaa7bd6-df5d-4737-ab4e-b92e559abbc6)

**Comment by Mooling0602** [comment]
> 地区你写的什么? APAC 还有会话令牌你填的啥~ 这俩参数怎么得来的~
> 
> 我这边测试是没问题的 `v3.33.0` 也添加了自定义host ![image](https://private-user-images.githubusercontent.com/56105412/317272131-e4115cf7-e890-4573-bcfd-49066bb5a2fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDYwOTIsIm5iZiI6MTcxMTU0NTc5MiwicGF0aCI6Ii81NjEwNTQxMi8zMTcyNzIxMzEtZTQxMTVjZjctZTg5MC00NTczLWJjZmQtNDkwNjZiYjVhMmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzMjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0Nzg1ZDgxODI5YjFkMjg3NWYxNjkwMTQ4YjU2ZmIyOWRkYzYxNTViZjMxMzk2ODI3Yzk1YTRiOTU0NjQ3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IvaXXbRdX9xluWUtA2jnc04Lf7_ft8kBnYZeoPmedik) ![image](https://private-user-images.githubusercontent.com/56105412/317272629-fdaa7bd6-df5d-4737-ab4e-b92e559abbc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDYwOTIsIm5iZiI6MTcxMTU0NTc5MiwicGF0aCI6Ii81NjEwNTQxMi8zMTcyNzI2MjktZmRhYTdiZDYtZGY1ZC00NzM3LWFiNGUtYjkyZTU1OWFiYmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzMjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNzRkYTJkNjE3MzNlNDhkODgwMTA5Y2RkNWVhMDU0MThjYTgyNWUwYTY0ZjQ1NDhkYjgyNTk4NTk5YzE0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CDIIvdZfO2O5ERfOgU-FNUQxAD79568LGrHbS3Zq2nI)

大佬可以看一下修改后的issue中的相关内容awa

**Comment by anwen-anyi** [comment]
请按照 alist.nn.ci 文档中对象存储 CF R2添加示例来添加

**Comment by Mooling0602** [comment]
> 请按照 [https://alist.nn.ci/zh/guide/drivers/s3.html#添加对象存储示例及官方文档](https://alist.nn.ci/zh/guide/drivers/s3.html#%E6%B7%BB%E5%8A%A0%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%E7%A4%BA%E4%BE%8B%E5%8F%8A%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3) 文档中对象存储 R2添加示例来添加

我是按照那篇文档操作的啊，把里面没提到的选项清空？

**Comment by anwen-anyi** [comment]
> > 请按照 [https://alist.nn.ci/zh/guide/drivers/s3.html#添加对象存储示例及官方文档](https://alist.nn.ci/zh/guide/drivers/s3.html#%E6%B7%BB%E5%8A%A0%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%E7%A4%BA%E4%BE%8B%E5%8F%8A%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3) 文档中对象存储 R2添加示例来添加
> 
> 我是按照那篇文档操作的啊，把里面没提到的选项清空？

该写的写 不该写的不用写 :cat: 
地区：你是怎么获取的我到现在木有明白？文档示例中不是教你了吗 填写 auto
会话令牌：没叫你填写吖..  :joy_cat:

**Comment by Mooling0602** [comment]
> > > 请按照 [https://alist.nn.ci/zh/guide/drivers/s3.html#添加对象存储示例及官方文档](https://alist.nn.ci/zh/guide/drivers/s3.html#%E6%B7%BB%E5%8A%A0%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%E7%A4%BA%E4%BE%8B%E5%8F%8A%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3) 文档中对象存储 R2添加示例来添加
> > 
> > 
> > 我是按照那篇文档操作的啊，把里面没提到的选项清空？
> 
> 该写的写 不该写的不用写 🐱 地区：你是怎么获取的我到现在木有明白？文档示例中不是教你了吗 填写 auto 会话令牌：没叫你填写吖.. 😹

按你这条操作后，报错变成
![image](https://github.com/alist-org/alist/assets/147964268/4258fb26-3153-498f-a5fd-c0853ccf3e0a)

**Comment by anwen-anyi** [comment]
> 按你这条操作后，报错变成 ![image](https://private-user-images.githubusercontent.com/147964268/317290079-4258fb26-3153-498f-a5fd-c0853ccf3e0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDcyNzYsIm5iZiI6MTcxMTU0Njk3NiwicGF0aCI6Ii8xNDc5NjQyNjgvMzE3MjkwMDc5LTQyNThmYjI2LTMxNTMtNDk4Zi1hNWZkLWMwODUzY2NmM2UwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMzQyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjM2NTMxMmEyZTk4OTIyZWZkOTMzNDExOTExYjAxMGEyNzQyNjkwNzdjYTg2ZDVjOGFmOGM4M2Y3NDRlMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._LxS7nvA2Csk8xx99DW_guOyKbWTL7Yd5-QZBN-rrCc)

你的操作可能不对，你删掉驱动重新添加一下，文档没有问题的...

**Comment by Mooling0602** [comment]
> > 按你这条操作后，报错变成 ![image](https://private-user-images.githubusercontent.com/147964268/317290079-4258fb26-3153-498f-a5fd-c0853ccf3e0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDcyNzYsIm5iZiI6MTcxMTU0Njk3NiwicGF0aCI6Ii8xNDc5NjQyNjgvMzE3MjkwMDc5LTQyNThmYjI2LTMxNTMtNDk4Zi1hNWZkLWMwODUzY2NmM2UwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMzQyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjM2NTMxMmEyZTk4OTIyZWZkOTMzNDExOTExYjAxMGEyNzQyNjkwNzdjYTg2ZDVjOGFmOGM4M2Y3NDRlMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._LxS7nvA2Csk8xx99DW_guOyKbWTL7Yd5-QZBN-rrCc)
> 
> 你的操作可能不对，你删掉驱动重新添加一下，文档没有问题的...

Web代理、启用签名、列出对象版本你是怎么设置的我参考一下

**Comment by anwen-anyi** [comment]
> Web代理、启用签名、列出对象版本你是怎么设置的我参考一下

主要是这几个选中的参数 其它的不用写也可以
![image](https://github.com/alist-org/alist/assets/56105412/3e0698cb-d977-453b-a2b3-05cedfa66c8b)

**Comment by Mooling0602** [comment]
> > Web代理、启用签名、列出对象版本你是怎么设置的我参考一下
> 
> 主要是这几个选中的参数 其它的不用写也可以 ![image](https://private-user-images.githubusercontent.com/56105412/317292941-3e0698cb-d977-453b-a2b3-05cedfa66c8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDc3MjIsIm5iZiI6MTcxMTU0NzQyMiwicGF0aCI6Ii81NjEwNTQxMi8zMTcyOTI5NDEtM2UwNjk4Y2ItZDk3Ny00NTNiLWEyYjMtMDVjZWRmYTY2YzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzNTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZWUwNDlmMmEzOWNiMWU4NTVhM2Y4N2I4MmNmYjA1ZjNkM2E1M2UzZjg2YTBhNTRkMmQwM2JkZTA3MDk5OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bsOuyebx2zMCBxxulzKlt_hocZNHl4L5k8PdfgbEIWA)

感谢帮助
