### ISSUE TITLE
关闭我的问题，倒是提供一个解决的方法，直接关闭，这种方式过分恶心，

### ISSUE THREAD

**Issue by yespush** [alist-org/alist#6276]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.33.0

### Driver used / 使用的存储驱动

no

### Describe the bug / 问题描述

如果这是一个重复问题，存在有效的解决方法，关闭问题没有任何问题，但这似乎不是个小众问题，同样也没有一个正确的修复方式，那么这个问题没有任何必要被关闭，你修不修复bug是你的问题，提问是使用者的权利。

### Reproduction / 复现链接

如果这是一个重复问题，存在有效的解决方法，关闭问题没有任何问题，但这似乎不是个小众问题，同样也没有一个正确的修复方式，那么这个问题没有任何必要被关闭，你修不修复bug是你的问题，提问是使用者的权利。

### Config / 配置

如果这是一个重复问题，存在有效的解决方法，关闭问题没有任何问题，但这似乎不是个小众问题，同样也没有一个正确的修复方式，那么这个问题没有任何必要被关闭，你修不修复bug是你的问题，提问是使用者的权利。

**Comment by yespush** [comment]
有bug，不管有没有修复方式，就让他展示出来，怕什么呢？我搞不懂

**Comment by xhofe** [comment]
我想我的回复中已经提供了解决方法。

- https://github.com/alist-org/alist/discussions/186#discussioncomment-1741800
