### ISSUE TITLE
阿里云盘刷新不及时

### ISSUE THREAD

**Issue by DrZhang1208** [alist-org/alist#6278]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.33.0

### Driver used / 使用的存储驱动

阿里云盘 open

### Describe the bug / 问题描述

1.挂载本地，存储使用情况不准确，左图是clouddrive2，右图是alist
![Clip_2024-03-28_19-04-15](https://github.com/alist-org/alist/assets/97793620/5d3408e5-1965-45b6-a355-7704cffaf3ba)
2.从阿里云盘分享链接保存到阿里云盘的文件迟迟不能显示出来，无论是缓存过期时间默认30秒，还是1秒都。都迟迟不能显示出来，clouddrive2是可以直接显示出来的。

### Reproduction / 复现链接
上面的是clouddrive2挂载的阿里云盘，下面的是alist挂载的阿里云盘

https://github.com/alist-org/alist/assets/97793620/0e1781bc-0dee-44bf-92ce-206c98394cdc

### Config / 配置

--

**Comment by xhofe** [comment]
挂载到本地要看挂载到本地程序的缓存时间。

**Comment by fredericky123** [comment]
最后解决了吗？好像alist默认设置为30分钟，能设置为0吗
