### ISSUE TITLE
在alist查看日志，发现日志报道的时间显示不正确。

### ISSUE THREAD

**Issue by youtuxp** [alist-org/alist#6285]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v.3.33.0

### Driver used / 使用的存储驱动

在alist查看日志，时间不正确

### Describe the bug / 问题描述

在alist查看日志，发现日志报道的时间显示不正确。

### Reproduction / 复现链接

在本地查看，无法提供链接

### Config / 配置

iStore里面的插件版本

### Logs / 日志

<img width="1433" alt="iShot_2024-03-30_09 32 51" src="https://github.com/alist-org/alist/assets/19292042/8f3e11a2-b2da-42ee-af55-d76f550b21c4">

**Comment by anwen-anyi** [comment]
这个应该是和你openwrt的utc时区时间有关吧？我这边本地看没问题吖~
![image](https://github.com/alist-org/alist/assets/56105412/185e138c-edc4-45fa-969a-8f6bb6cb58d3)

**Comment by youtuxp** [comment]
查了下原来是 openwrt 默认没有安装 zoneinfo，安装后即可.

**Comment by ShanshanHY** [comment]
请问android在这种情况下要如何处理 安卓并没有/etc/localtime和/user/share/zoneinfo作为时区来源
