### ISSUE TITLE
新版本新增的S3无法绑定端口导致启动失败

### ISSUE THREAD

**Issue by caixiaohaier** [alist-org/alist#6287]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.33.0

### Driver used / 使用的存储驱动

WebDav

### Describe the bug / 问题描述

环境：
昨日新装一台物理机，最小化安装Debian11.9系统镜像，系统安装后安装了1Panel面板，WG软件，未安装其他软件。

故障现象：
1.今日直接在SSH命令行安装Alist成功后发现Status显示启动失败，无法绑定S3程序的5246端口。后查找发现5246未被占用，改其他端口也失败。再通过排查，把WG程序关掉，ip addr显示wg0网卡消失，再开启Alist则正常开启。后将config配置文件中的绑定IP地址从0.0.0.0改成127.0.0.1。发现wg和Alist能同时开启并不报错

2.在config配置文件配置"site_url"站点参数。配置：https://abc.com:4430。重启AList发现无法启动，报错，显示S3的端口又未绑定成功引起的，把站点参数配为不带端口则正常。（关闭了wg的情况下测试的）

Ps :  按理这个新增的S3应该在后台启用后再重启在绑定端口吧，为啥一开始没启用都要强制要监听端口。。。

### Reproduction / 复现链接

![1](https://github.com/alist-org/alist/assets/48126754/e0a051a5-8edf-41ab-9f12-e972a597c239)
![2](https://github.com/alist-org/alist/assets/48126754/4c6ddecd-3cd8-49ff-9a23-c472e07acdd4)

### Config / 配置

  "s3": {
    "enable": false,
    "port": 52460,
    "ssl": false
  }
}

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/pull/6291
