### ISSUE TITLE
alist运行在局域网（有公网ip）的时候，micresoft插件不能预览，希望改进

### ISSUE THREAD

**Issue by wangzichenglong** [alist-org/alist#6292]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

同样是[https://view.officeapps.live.com/op/view.aspx?src=$e_url"的调用](https://view.officeapps.live.com/op/view.aspx?src=$e_url%22%E7%9A%84%E8%B0%83%E7%94%A8)
alist运行在局域网（有公网ip）的时候，micresoft插件不能预览天翼云盘、阿里云盘、onedrive盘、局域网本地服务器上的文件（192.168.1.10:5244形式），而Oneindex这个老牌的程序同样运行在局域网，micresoft插件却能浏览onedrive盘、局域网本地服务器上的文件。
想来脚本的运行逻辑是有一些出入的。而运行在局域网却能不受限的在线打开网盘或本地盘列表里的micresoft文件进行查看，是非常方便的功能。希望alist作者大佬能借鉴Oneindex的预览模式，改进功能。
![image](https://github.com/alist-org/alist/assets/101960731/35628610-1826-4f27-886d-621864fa6aae)

### Suggested solution / 实现思路

借鉴Oneindex的预览模式
它好像是直链，或者不是直链的话，逻辑可能是对需要预览的文件先转换再预览，所以不受是否运行在局域网还是广域网的限制，都能正确连接到https://view.officeapps.live.com打开文件。

**Comment by xx6z8v** [comment]
试试把e-url修改成durl或e_durl，否则你提供的就是内网地址
