### ISSUE TITLE
接入WPS文件预览服务

### ISSUE THREAD

**Issue by Nick-DL** [alist-org/alist#6293]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

感觉PDF.js对.pdf的预览有时候加载起来太慢了，而.docx、.pptx、.xlsx的Microsoft和Google文件预览在一般网络环境下基本上是不能用的。看到WPS提供了文件预览服务的API，故觉得可以考虑接入WPS文件预览服务

### Suggested solution / 实现思路

参考 https://open.wps.cn/previous/docs

**Comment by anwen-anyi** [comment]
作为平台服务商的开发者，你的`企业`需要通过开放平台的服务商认证。

**Comment by xx6z8v** [comment]
你可以尝试使用OnlyOffice

**Comment by Nick-DL** [comment]
@xx6z8v 可以在AList在线预览文件吗
