### ISSUE TITLE
无法添加 Webauthn 

### ISSUE THREAD

**Issue by gkl1368** [alist-org/alist#6294]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.30

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

无法添加 Webauthn，但在最后网页提示 “Error validating origin”。已开启https

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by gkl1368** [comment]
> 请确保你的site_url配置正确：https://alist.nn.ci/zh/config/configuration.html#site-url

确定 site_url 配置正确

**Comment by itsHenry35** [comment]
> > 请确保你的site_url配置正确：https://alist.nn.ci/zh/config/configuration.html#site-url
> 
> 确定 site_url 配置正确

你的site_url配置是什么？

**Comment by gkl1368** [comment]
> > > 请确保你的site_url配置正确：https://alist.nn.ci/zh/config/configuration.html#site-url
> > 
> > 
> > 确定 site_url 配置正确
> 
> 你的site_url配置是什么？

site_url 是。https://自己的域名/alist  
打开网页也是这个地址
是nginx反代的
和这个人的问题一样
https://github.com/alist-org/alist/discussions/5534

**Comment by itsHenry35** [comment]
> > > > 请确保你的site_url配置正确：https://alist.nn.ci/zh/config/configuration.html#site-url
> > > 
> > > 
> > > 确定 site_url 配置正确
> > 
> > 
> > 你的site_url配置是什么？
> 
> site_url 是。[https://自己的域名/alist](https://%E8%87%AA%E5%B7%B1%E7%9A%84%E5%9F%9F%E5%90%8D/alist) 打开网页也是这个地址 是nginx反代的 和这个人的问题一样 #5534

二级目录啊，那我大概知道问题了

**Comment by itsHenry35** [comment]
> > > > > > 请确保你的site_url配置正确：https://alist.nn.ci/zh/config/configuration.html#site-url
> > > > > 
> > > > > 
> > > > > 确定 site_url 配置正确
> > > > 
> > > > 
> > > > 你的site_url配置是什么？
> > > 
> > > 
> > > site_url 是。[https://自己的域名/alist](https://%E8%87%AA%E5%B7%B1%E7%9A%84%E5%9F%9F%E5%90%8D/alist) 打开网页也是这个地址 是nginx反代的 和这个人的问题一样 #5534
> > 
> > 
> > 二级目录啊，那我大概知道问题了
> 
> 是alist的bug吗？

应该是的，我要去看一下

**Comment by itsHenry35** [comment]
@gkl1368 你去试试最新actions编译版，因为我也没反代测试，只是理论可行，需要你测试一下：https://github.com/alist-org/alist/actions/runs/8509227249?pr=6301

**Comment by gkl1368** [comment]
> https://github.com/alist-org/alist/actions/runs/8509227249?pr=6301

我是docker部署的

**Comment by gkl1368** [comment]
> https://github.com/alist-org/alist/actions/runs/8509227249?pr=6301

凭据成功添加了，但是不能改名字吗

**Comment by itsHenry35** [comment]
> > https://github.com/alist-org/alist/actions/runs/8509227249?pr=6301
> 
> 凭据成功添加了，但是不能改名字吗

不能，暂时没打算做改名的，到时候再说吧

**Comment by gkl1368** [comment]
> > > https://github.com/alist-org/alist/actions/runs/8509227249?pr=6301
> > 
> > 
> > 凭据成功添加了，但是不能改名字吗
> 
> 不能，暂时没打算做改名的，到时候再说吧

好吧 现在可以添加了，期待以后能修改凭据名称，不然会搞不清楚
