### ISSUE TITLE
Crypt: can't find remote storage: storage not found

### ISSUE THREAD

**Issue by muxinxy** [alist-org/alist#6297]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

Crypt

### Describe the bug / 问题描述

添加阿里云盘Open和Crypt（加密后文件存储路径在阿里云盘Open中），删除阿里云盘Open后重新添加，重新启动AList，Crypt报错`can't find remote storage: storage not found`

### Reproduction / 复现链接

添加阿里云盘Open和Crypt（加密后文件存储路径在阿里云盘Open中），删除阿里云盘Open后重新添加，重新启动AList

### Config / 配置

![image](https://github.com/alist-org/alist/assets/32673109/58c162f7-aa8d-4377-abeb-d6b988fa3198)

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/32673109/a641098d-d51a-48cc-8881-c9bff85e99a1)

**Comment by haohaohaoadsad** [comment]
注意加载顺序  加载Crypt的时候 阿里云还没有存在

**Comment by muxinxy** [comment]
> 注意加载顺序 加载Crypt的时候 阿里云还没有存在

可以在后台调整加载顺序吗

**Comment by muxinxy** [comment]
找到办法了，只要填写序号，并且序号比真实存储位置的序号大就可以了。
