### ISSUE TITLE
alist启动失败

### ISSUE THREAD

**Issue by hhhhhge** [alist-org/alist#6298]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

alist服务无法启动，就算在那个目录下手动运行也是

### Reproduction / 复现链接

无

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "D3rKpsI8fMNBtObO",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

### Logs / 日志

× alist.service - Alist service
     Loaded: loaded (/etc/systemd/system/alist.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Sun 2024-03-31 20:23:00 CST; 2s ago
    Process: 141199 ExecStart=/opt/alist/alist server (code=killed, signal=SEGV)
   Main PID: 141199 (code=killed, signal=SEGV)
        CPU: 3ms

3月 31 20:23:00 orangepi5 systemd[1]: Started Alist service.
3月 31 20:23:00 orangepi5 systemd[1]: alist.service: Main process exited, code=killed, status=11/SEGV
3月 31 20:23:00 orangepi5 systemd[1]: alist.service: Failed with result 'signal'.

**Comment by xhofe** [comment]
手动运行报什么错

**Comment by hhhhhge** [comment]
段错误

**Comment by hhhhhge** [comment]
只有这个返回

**Comment by xhofe** [comment]
Segmentation fault?

可能是下载了错误的版本。

**Comment by hhhhhge** [comment]
我用的是自动脚本啊

**Comment by hhhhhge** [comment]
arm64的Ubuntu

**Comment by xhofe** [comment]
那不知道了 自行编译试试。

**Comment by bibichuan** [comment]
我也遇到了同样的问题，也是用自动脚本安装的，阿里云的系统

**Comment by AIEOV** [comment]
同样  腾讯云ubuntu。  在国外服务器一切正常
