### ISSUE TITLE
顺序重命名就一定要填第一行吗？第一行为空按不了确认

### ISSUE THREAD

**Issue by guiys** [alist-org/alist#6300]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我想把转存的长文件名改成纯数字的，这样电视上看到的就是简单的顺序数字。但是顺序重命名貌似一定要加上"第" "S01"这样的前缀，形成"第xx.mp4"这样的文件名。
如图所示。同样的还有正则表达式重命名，第二行输入新文件名正则表达式也不能为空，也就是不能直接删掉匹配上的字符串，必须要替换成什么别的。
![IMG_8629](https://github.com/alist-org/alist/assets/61960072/c80f9800-8eaa-4832-a7a3-bc1abf67f869)

**Comment by xx6z8v** [comment]
用WebDav管理器对Alist重命名操作不会有限制的
