### ISSUE TITLE
管理页面添加日志查看功能 Management page adding another section to view the logs

### ISSUE THREAD

**Issue by itsHenry35** [alist-org/alist#6302]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议在管理页面左侧多加一个显示日志的功能，就不需要每次想要查看日志都需要去ssh连接服务器查看了，此外希望加入log类型分类与筛选功能（例如仅显示ERROR，或仅显示ERROR与WARNING日志等）

**Comment by xx6z8v** [comment]
可以选择使用本地储存挂载Alist工作目录查看log文件

**Comment by WXZhao7** [comment]
config的log level，日志中的登录ip和用户信息绑定，这两个觉得都挺有用的
