### ISSUE TITLE
贡献一个新的存储，免费4T空间。

### ISSUE THREAD

**Issue by OuOumm** [alist-org/alist#6303]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

[1号链接](https://www.playbook.com/s/warhut/leo-natsume-x-playbook)

点进去之后点上面的获取合集。  
Get this collection

选择谷歌账户登录，就可以获取4T永久空间。

注：[2号链接](https://www.playbook.com/s/giveaway/leo-natsume-3d)

### Suggested solution / 实现思路

[1号链接](https://www.playbook.com/s/warhut/leo-natsume-x-playbook)
点进去之后点上面的获取合集。  
Get this collection

选择谷歌账户登录，就可以获取4T永久空间。

注：[2号链接](https://www.playbook.com/s/giveaway/leo-natsume-3d)

**Comment by wj2008** [comment]
好东西啊，刚获取4T 刚上来alist上看能不能挂上

**Comment by wowdd1** [comment]
单次最大传1GB  不能压缩 加密

**Comment by minisind** [comment]
像是一个“交换产品”， 你喂数据、知识给它，它送个“免费”的存储给你。
