### ISSUE TITLE
希望能添加浏览器上拖拽文件自动上传

### ISSUE THREAD

**Issue by loveu5522** [alist-org/alist#6309]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望能添加浏览器上拖拽文件自动上传，就是不用点上传按钮，在文件夹界面拖拽文件到浏览器就可以上传。感觉这样要符合日常使用逻辑。希望作者采纳

**Comment by anwen-anyi** [comment]
应该不行吧？ 因为上传有两个模式还有一个是否添加为任务选项

**Comment by jxjxjhjh** [comment]
> 应该不行吧？ 因为上传有两个模式还有一个是否添加为任务选项

那就默认选择一种并且默认不添加为任务呗

**Comment by axyn45** [comment]
我也觉得这样比较符合直觉，阿里云盘web端就是直接拖拽到网页就可以上传的

**Comment by aohanhongzhi** [comment]
非常需要，我第一次搭建，找了5244界面，找了官网，硬是没有找到上传。最后看b站视频，发现，竟然再右下角一个小按钮上传。这个设计不得不说，是个败笔。

![image](https://github.com/alist-org/alist/assets/37319319/8e4052ae-82c7-4153-87bf-68372c641836)

**Comment by cancundeyingzi** [comment]
> 非常需要，我第一次搭建，找了5244界面，找了官网，硬是没有找到上传。最后看b站视频，发现，竟然再右下角一个小按钮上传。这个设计不得不说，是个败笔。
> 
> ![image](https://private-user-images.githubusercontent.com/37319319/335651776-8e4052ae-82c7-4153-87bf-68372c641836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTAyMTgsIm5iZiI6MTcxNzU4OTkxOCwicGF0aCI6Ii8zNzMxOTMxOS8zMzU2NTE3NzYtOGU0MDUyYWUtODJjNy00MTUzLTg3YmYtNjgzNzJjNjQxODM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEyMTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMzk0ODg4ZjllYWIxYTY3ZmI4NmI2MDZiM2M4ZjE4MzQ5OWZlNDE0M2Q5OTdmOWUzODdiMDhkYWIxZmE4NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s2n4lkXgoLpAz_FCdThhm4NxWdK6rGB6LtfxdFSIQ44)

v3和v2比在易用性上退步了很多
