### ISSUE TITLE
建议地址树支持 github上的release发布最新版文件下载链接

### ISSUE THREAD

**Issue by chrisdong** [alist-org/alist#6311]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist现在有很好用的 地址树功能，我有个建议能否 让地址树支持 github上的release发布的最新版文件下载功能，就是给 一个release的发布链接，alist直接能 解析到最新版release的下载链接。 个人在alist上做一个 github合集，收藏平时经常用的 release

我现在是手动输入 某个release的直链，但问题是不能自动获取最新版
![PixPin_2024-04-05_09-36-12](https://github.com/alist-org/alist/assets/3366796/0d623d35-34a9-41fe-83b6-ce9eb130aedb)

github文档里有 如何获取最新版的参数
https://docs.github.com/zh/repositories/releasing-projects-on-github/linking-to-releases

**Comment by anwen-anyi** [comment]
自己写脚本调用AList API
