### ISSUE TITLE
页面是动态渲染的，如何友好支持seo？让搜索引擎收录

### ISSUE THREAD

**Issue by jiawei666** [alist-org/alist#6313]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

页面是动态渲染的，如何友好支持seo？让搜索引擎收录

**Comment by BlueSkyXN** [comment]
CDN缓存？
