### ISSUE TITLE
failed get objs: failed to list objs: PROPFIND /: 403

### ISSUE THREAD

**Issue by yggcwx** [alist-org/alist#6314]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

webdav

### Describe the bug / 问题描述

![003](https://github.com/alist-org/alist/assets/90705180/fb2baccd-dbec-49f0-bb13-b5994bdf7c04)
![微信图片_20240405153741](https://github.com/alist-org/alist/assets/90705180/01b473b4-3e85-4fdf-ac28-f7ca746db427)
私有部署的cloudreve，webdav通过其它客户端连接没问题，包括windows资源管理器都可以正常连接。但在本地alist程序中以webdav方式挂载cloudreve后，一直显示“failed get objs: failed to list objs: PROPFIND /: 403”。用官方文档里有关[错误提示](https://alist.nn.ci/zh/guide/drivers/webdav.html#%E9%94%99%E8%AF%AF%E6%8F%90%E7%A4%BA)的解决方案无效。

### Reproduction / 复现链接

http://127.0.0.1:5244/零维云盘

### Config / 配置

[GIN] 2024/04/05 - 15:35:51 | 200 | 384.7µs | 127.0.0.1 | GET "/"
[GIN] 2024/04/05 - 15:35:51 | 200 | 0s | 127.0.0.1 | GET "/api/me"
[GIN] 2024/04/05 - 15:35:52 | 200 | 0s | 127.0.0.1 | GET "/api/public/settings"
[GIN] 2024/04/05 - 15:35:52 | 200 | 0s | 127.0.0.1 | GET "/api/me"
[GIN] 2024/04/05 - 15:35:52 | 200 | 0s | 127.0.0.1 | POST "/api/fs/get"
[GIN] 2024/04/05 - 15:35:52 | 200 | 0s | 127.0.0.1 | GET "/api/public/offline_download_tools"
[GIN] 2024/04/05 - 15:35:52 | 200 | 1.0009ms | 127.0.0.1 | POST "/api/fs/list"
ERRO[2024-04-05 15:35:53] fs/list: PROPFIND /: 403
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:2938
net/http.(*conn).serve
/usr/local/go/src/net/http/server.go:2009
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1650
ERRO[2024-04-05 15:35:53] failed list /零维云盘: PROPFIND /: 403
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:2938
net/http.(*conn).serve
/usr/local/go/src/net/http/server.go:2009
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1650
failed get objs
[GIN] 2024/04/05 - 15:35:53 | 200 | 237.8288ms | 127.0.0.1 | POST "/api/fs/list"

### Logs / 日志
![002](https://github.com/alist-org/alist/assets/90705180/15ee4eed-2875-4b38-ad7e-5638b8c6a018)

**Comment by jaychou11177** [comment]
我也遇到了

**Comment by AthesFrey** [comment]
怎么解决这个问题呢？

**Comment by 0x5e** [comment]
文档中获取WebdAV 根地址的工具貌似已经过时
```
OneDrive: https://xx-my.sharepoint.xx/personal/xx_xx_xx/_layouts/15/onedrive.aspx
```
https://xx-my.sharepoint.xx/my?id=%2Fpersonal%2Fxx_xx_xx%2FDocuments%2Fxxxxxxx
现在能取到的链接都是这样格式的，手工拼接成旧格式就成功了。
