### ISSUE TITLE
在主页或者管理页增加新版本提醒

### ISSUE THREAD

**Issue by lssb** [alist-org/alist#6323]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在主页或者管理页增加新版本提醒，现在并不知道有无新版本发布，无法及时更新Alist

**Comment by xx6z8v** [comment]
可以尝试自己搞，GH有相关Api:https://api.github.com/repos/alist-org/alist/releases/latest
