### ISSUE TITLE
搜索结果建议支持复制，移动等基本操作

### ISSUE THREAD

**Issue by bigmouse0001** [alist-org/alist#6326]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题，有时候想直接对搜索结果进行**复制，移动等基本操作**，但是现有操作逻辑似乎无法实现？

![image](https://github.com/alist-org/alist/assets/119995454/bc7f0015-2090-40d8-89e6-64ec5e56bf1e)

搜索结果点进去之后也只有**复制链接和下载**，无法进行基本功能操作。
![image](https://github.com/alist-org/alist/assets/119995454/5221aa3b-6dfa-42b7-b801-aa1909eb3308)

目前发现，**只有目录页面才能进行复制，移动，删除等基本操作**，如果有大量网盘文件的话就不太友好了，因为不可能在几百万文件中点进某个目录进行基本操作。所以还是**希望能支持一下搜索结果和单文件页面的基本操作功能**

希望能改进一下，支持**搜索结果的复选框**，或者支持**单文件页面进行复制，移动，删除等基本操作**，谢谢！

**Comment by east-fang** [comment]
+10086
