### ISSUE TITLE
上传到本地硬盘文件的权限

### ISSUE THREAD

**Issue by Jiao-Xia-Ke** [alist-org/alist#6328]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist从网页上传到挂载的本地硬盘,文件夹和文件无法设置所有者和组,上传文件夹权限设置777,实际变成了755.新建文件的权限是644

### Additional context / 附件

![5Z 5)C9JSD)BX`G0P2{8)G0](https://github.com/alist-org/alist/assets/100463449/9a175827-7d97-4ced-a171-584b3ccaadc0)

![D$)O$F4TMB@P1(E_2$0V0CG](https://github.com/alist-org/alist/assets/100463449/053ce59d-6f1b-484f-abb3-4957f465eb1f)
![)@}%)T6EV~$M{K`72G)_D%R](https://github.com/alist-org/alist/assets/100463449/8d4037fd-07e1-4894-acea-dd231ff22236)

**Comment by jiaoxiake888** [comment]
问题已解决,设置GID  UID
