### ISSUE TITLE
复制中止/恢复

### ISSUE THREAD

**Issue by xx6z8v** [alist-org/alist#6330]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用Alist复制文件时，可能出现设备断电/断网等一系列突发情况，导致复制终止。
然而，Alist并没有一个持久记录复制过程的方法。
在复制意外中止时，甚至因为停电导致重启时，我无法知晓上一次复制过程的中止点，只能重新复制。

### Suggested solution / 实现思路

方法1：直接使用数据库来记录；
方法2：在/data目录下增加类似“aria2.session”的文件，比如"copy.session"，用于记录复制信息，以便在突发情况下恢复

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/issues/5313
