### ISSUE TITLE
飞机盘 获取不到下载地址了，能进入列表页面

### ISSUE THREAD

**Issue by huolanyun** [alist-org/alist#6333]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.33.0

### Driver used / 使用的存储驱动

FEIJIPAN

### Describe the bug / 问题描述

进入点击文件下载提示
failed link: failed get link: redirect failed, status: 200

### Reproduction / 复现链接

哪位大佬修复一下

### Config / 配置

哪位大佬修复一下

**Comment by rigolang** [comment]
一样    能获取列表  但是打开文件提示 failed link: failed get link: redirect failed, status: 200

**Comment by yu9955** [comment]
一样

**Comment by laoqijun1** [comment]
同

**Comment by vpei** [comment]
同问

**Comment by vpei** [comment]
同问

**Comment by arch3rPro** [comment]
求更

**Comment by Greyisttot** [comment]
你们开会员没

**Comment by laoqijun1** [comment]
> 你们开会员没

我开了

**Comment by laoqijun1** [comment]
1
