### ISSUE TITLE
复制任务的进度只有管理员可见，能不能让普通用户也可见

### ISSUE THREAD

**Issue by zkaif** [alist-org/alist#6342]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我目前使用AList作为网盘的下载工具，但是普通用户看不到一个复制任务是否完成，只有管理员后台可见，能不能让普通用户也可见，最好能在首页加一个任务进度。
暂时不支持管理也可以，起码进度条能看的到。不然都不知道负责完成了没有

**Comment by woshichenghaibo** [comment]
没必要那么复杂，越复杂越是容易出错，越容易有bug

**Comment by IAALAI** [comment]
这个设计非常复杂，如果想要调整不是一时半刻有办法修改的
而且alist的用户功能整体强度不高。最开始设计是一个人用于管理自己的多个云盘的
所以以上的API设计上比较难做到区分不同人可见
