### ISSUE TITLE
Windows自带webdav上传文件提示网络错误和文件已存在

### ISSUE THREAD

**Issue by Dilskry** [alist-org/alist#6343]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

在群辉套件中心安装alist和群辉docker中安装alist后产生的错误是相同的。症状：给alist的子账号(不是主账号)设定指定访问目录后，用win10/win11自带的webdav连接后，上传文件提示网络错误，再次上传提示文件已存在，并且文件大小为0kb。该目录有alist的完全控制权限。相同webdav链接用【主账号】登录就没有这些问题，包括其他设备和第三方软件连接该webdav也没有这些问题，只有Windows自带的webdav连接才有这个问题。

### Reproduction / 复现链接

https://file.****.com/dav

### Config / 配置

{
  "encrypted": "",
  "settings": [
    {
      "key": "version",
      "value": "v3.33.0",
      "help": "",
      "type": "string",
      "options": "",
      "group": 1,
      "flag": 2
    },
    {
      "key": "site_title",
      "value": "AList",
      "help": "",
      "type": "string",
      "options": "",
      "group": 1,
      "flag": 0
    },
    {
      "key": "announcement",
      "value": "### repo\nhttps://github.com/alist-org/alist",
      "help": "",
      "type": "text",
      "options": "",
      "group": 1,
      "flag": 0
    },
    {
      "key": "pagination_type",
      "value": "all",
      "help": "",
      "type": "select",
      "options": "all,pagination,load_more,auto_load_more",
      "group": 1,
      "flag": 0
    },
    {
      "key": "default_page_size",
      "value": "30",
      "help": "",
      "type": "number",
      "options": "",
      "group": 1,
      "flag": 0
    },
    {
      "key": "allow_indexed",
      "value": "false",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 1,
      "flag": 0
    },
    {
      "key": "allow_mounted",
      "value": "true",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 1,
      "flag": 0
    },
    {
      "key": "robots_txt",
      "value": "User-agent: *\nAllow: /",
      "help": "",
      "type": "text",
      "options": "",
      "group": 1,
      "flag": 0
    },
    {
      "key": "logo",
      "value": "https://cdn.jsdelivr.net/gh/alist-org/logo@main/logo.svg",
      "help": "",
      "type": "text",
      "options": "",
      "group": 2,
      "flag": 0
    },
    {
      "key": "favicon",
      "value": "https://cdn.jsdelivr.net/gh/alist-org/logo@main/logo.svg",
      "help": "",
      "type": "string",
      "options": "",
      "group": 2,
      "flag": 0
    },
    {
      "key": "main_color",
      "value": "#1890ff",
      "help": "",
      "type": "string",
      "options": "",
      "group": 2,
      "flag": 0
    },
    {
      "key": "home_icon",
      "value": "🏠",
      "help": "",
      "type": "string",
      "options": "",
      "group": 2,
      "flag": 0
    },
    {
      "key": "home_container",
      "value": "max_980px",
      "help": "",
      "type": "select",
      "options": "max_980px,hope_container",
      "group": 2,
      "flag": 0
    },
    {
      "key": "settings_layout",
      "value": "list",
      "help": "",
      "type": "select",
      "options": "list,responsive",
      "group": 2,
      "flag": 0
    },
    {
      "key": "text_types",
      "value": "txt,htm,html,xml,java,properties,sql,js,md,json,conf,ini,vue,php,py,bat,gitignore,yml,go,sh,c,cpp,h,hpp,tsx,vtt,srt,ass,rs,lrc",
      "help": "",
      "type": "text",
      "options": "",
      "group": 3,
      "flag": 1
    },
    {
      "key": "audio_types",
      "value": "mp3,flac,ogg,m4a,wav,opus,wma",
      "help": "",
      "type": "text",
      "options": "",
      "group": 3,
      "flag": 1
    },
    {
      "key": "video_types",
      "value": "mp4,mkv,avi,mov,rmvb,webm,flv,m3u8",
      "help": "",
      "type": "text",
      "options": "",
      "group": 3,
      "flag": 1
    },
    {
      "key": "image_types",
      "value": "jpg,tiff,jpeg,png,gif,bmp,svg,ico,swf,webp",
      "help": "",
      "type": "text",
      "options": "",
      "group": 3,
      "flag": 1
    },
    {
      "key": "proxy_types",
      "value": "m3u8",
      "help": "",
      "type": "text",
      "options": "",
      "group": 3,
      "flag": 1
    },
    {
      "key": "proxy_ignore_headers",
      "value": "authorization,referer",
      "help": "",
      "type": "text",
      "options": "",
      "group": 3,
      "flag": 1
    },
    {
      "key": "external_previews",
      "value": "{}",
      "help": "",
      "type": "text",
      "options": "",
      "group": 3,
      "flag": 0
    },
    {
      "key": "iframe_previews",
      "value": "{\n\t\"doc,docx,xls,xlsx,ppt,pptx\": {\n\t\t\"Microsoft\":\"https://view.officeapps.live.com/op/view.aspx?src=$e_url\",\n\t\t\"Google\":\"https://docs.google.com/gview?url=$e_url&embedded=true\"\n\t},\n\t\"pdf\": {\n\t\t\"PDF.js\":\"https://alist-org.github.io/pdf.js/web/viewer.html?file=$e_url\"\n\t},\n\t\"epub\": {\n\t\t\"EPUB.js\":\"https://alist-org.github.io/static/epub.js/viewer.html?url=$e_url\"\n\t}\n}",
      "help": "",
      "type": "text",
      "options": "",
      "group": 3,
      "flag": 0
    },
    {
      "key": "audio_cover",
      "value": "https://jsd.nn.ci/gh/alist-org/logo@main/logo.svg",
      "help": "",
      "type": "string",
      "options": "",
      "group": 3,
      "flag": 0
    },
    {
      "key": "audio_autoplay",
      "value": "true",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 3,
      "flag": 0
    },
    {
      "key": "video_autoplay",
      "value": "true",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 3,
      "flag": 0
    },
    {
      "key": "hide_files",
      "value": "/\\/README.md/i",
      "help": "",
      "type": "text",
      "options": "",
      "group": 4,
      "flag": 0
    },
    {
      "key": "package_download",
      "value": "true",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 4,
      "flag": 0
    },
    {
      "key": "customize_head",
      "value": "",
      "help": "",
      "type": "text",
      "options": "",
      "group": 4,
      "flag": 1
    },
    {
      "key": "customize_body",
      "value": "",
      "help": "",
      "type": "text",
      "options": "",
      "group": 4,
      "flag": 1
    },
    {
      "key": "link_expiration",
      "value": "0",
      "help": "",
      "type": "number",
      "options": "",
      "group": 4,
      "flag": 1
    },
    {
      "key": "sign_all",
      "value": "true",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 4,
      "flag": 1
    },
    {
      "key": "privacy_regs",
      "value": "(?:(?:\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(?:\\d|[1-9]\\d|1\\d\\d|2[0-4]\\d|25[0-5])\n([[:xdigit:]]{1,4}(?::[[:xdigit:]]{1,4}){7}|::|:(?::[[:xdigit:]]{1,4}){1,6}|[[:xdigit:]]{1,4}:(?::[[:xdigit:]]{1,4}){1,5}|(?:[[:xdigit:]]{1,4}:){2}(?::[[:xdigit:]]{1,4}){1,4}|(?:[[:xdigit:]]{1,4}:){3}(?::[[:xdigit:]]{1,4}){1,3}|(?:[[:xdigit:]]{1,4}:){4}(?::[[:xdigit:]]{1,4}){1,2}|(?:[[:xdigit:]]{1,4}:){5}:[[:xdigit:]]{1,4}|(?:[[:xdigit:]]{1,4}:){1,6}:)\n(?U)access_token=(.*)&",
      "help": "",
      "type": "text",
      "options": "",
      "group": 4,
      "flag": 1
    },
    {
      "key": "ocr_api",
      "value": "https://api.nn.ci/ocr/file/json",
      "help": "",
      "type": "string",
      "options": "",
      "group": 4,
      "flag": 0
    },
    {
      "key": "filename_char_mapping",
      "value": "{\"/\": \"|\"}",
      "help": "",
      "type": "text",
      "options": "",
      "group": 4,
      "flag": 0
    },
    {
      "key": "forward_direct_link_params",
      "value": "false",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 4,
      "flag": 0
    },
    {
      "key": "ignore_direct_link_params",
      "value": "sign,alist_ts",
      "help": "",
      "type": "string",
      "options": "",
      "group": 4,
      "flag": 0
    },
    {
      "key": "webauthn_login_enabled",
      "value": "false",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 4,
      "flag": 0
    },
    {
      "key": "token",
      "value": "alist-4d50adc1-0933-4190-b2c6-02d65fbcb8d0NBhQlqLGMAfEZ44h6rtslBU65ybHaFVDeMdtiBsY9LLg32EqKpWV6UpYLrEqcfYT",
      "help": "",
      "type": "string",
      "options": "",
      "group": 0,
      "flag": 1
    },
    {
      "key": "search_index",
      "value": "none",
      "help": "",
      "type": "select",
      "options": "database,database_non_full_text,bleve,meilisearch,none",
      "group": 6,
      "flag": 0
    },
    {
      "key": "auto_update_index",
      "value": "false",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 6,
      "flag": 0
    },
    {
      "key": "ignore_paths",
      "value": "",
      "help": "one path per line",
      "type": "text",
      "options": "",
      "group": 6,
      "flag": 1
    },
    {
      "key": "max_index_depth",
      "value": "20",
      "help": "max depth of index",
      "type": "number",
      "options": "",
      "group": 6,
      "flag": 1
    },
    {
      "key": "index_progress",
      "value": "{\"obj_count\":0,\"is_done\":true,\"last_done_time\":null,\"error\":\"\"}",
      "help": "",
      "type": "text",
      "options": "",
      "group": 0,
      "flag": 1
    },
    {
      "key": "sso_login_enabled",
      "value": "false",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 7,
      "flag": 0
    },
    {
      "key": "sso_login_platform",
      "value": "",
      "help": "",
      "type": "select",
      "options": "Casdoor,Github,Microsoft,Google,Dingtalk,OIDC",
      "group": 7,
      "flag": 0
    },
    {
      "key": "sso_client_id",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_client_secret",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_oidc_username_key",
      "value": "name",
      "help": "",
      "type": "string",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_organization_name",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_application_name",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_endpoint_name",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_jwt_public_key",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_auto_register",
      "value": "false",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_default_dir",
      "value": "/",
      "help": "",
      "type": "string",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_default_permission",
      "value": "0",
      "help": "",
      "type": "number",
      "options": "",
      "group": 7,
      "flag": 1
    },
    {
      "key": "sso_compatibility_mode",
      "value": "false",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 7,
      "flag": 0
    },
    {
      "key": "ldap_login_enabled",
      "value": "false",
      "help": "",
      "type": "bool",
      "options": "",
      "group": 8,
      "flag": 0
    },
    {
      "key": "ldap_server",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 8,
      "flag": 1
    },
    {
      "key": "ldap_manager_dn",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 8,
      "flag": 1
    },
    {
      "key": "ldap_manager_password",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 8,
      "flag": 1
    },
    {
      "key": "ldap_user_search_base",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 8,
      "flag": 1
    },
    {
      "key": "ldap_user_search_filter",
      "value": "(uid=%s)",
      "help": "",
      "type": "string",
      "options": "",
      "group": 8,
      "flag": 1
    },
    {
      "key": "ldap_default_dir",
      "value": "/",
      "help": "",
      "type": "string",
      "options": "",
      "group": 8,
      "flag": 1
    },
    {
      "key": "ldap_default_permission",
      "value": "0",
      "help": "",
      "type": "number",
      "options": "",
      "group": 8,
      "flag": 1
    },
    {
      "key": "ldap_login_tips",
      "value": "login with ldap",
      "help": "",
      "type": "string",
      "options": "",
      "group": 8,
      "flag": 0
    },
    {
      "key": "s3_access_key_id",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 9,
      "flag": 1
    },
    {
      "key": "s3_secret_access_key",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 9,
      "flag": 1
    },
    {
      "key": "s3_buckets",
      "value": "[]",
      "help": "",
      "type": "string",
      "options": "",
      "group": 9,
      "flag": 1
    },
    {
      "key": "aria2_uri",
      "value": "http://localhost:6800/jsonrpc",
      "help": "",
      "type": "string",
      "options": "",
      "group": 5,
      "flag": 1
    },
    {
      "key": "aria2_secret",
      "value": "",
      "help": "",
      "type": "string",
      "options": "",
      "group": 5,
      "flag": 1
    },
    {
      "key": "qbittorrent_url",
      "value": "http://admin:adminadmin@localhost:8080/",
      "help": "",
      "type": "string",
      "options": "",
      "group": 5,
      "flag": 1
    },
    {
      "key": "qbittorrent_seedtime",
      "value": "0",
      "help": "",
      "type": "number",
      "options": "",
      "group": 5,
      "flag": 1
    }
  ],
  "users": [
    {
      "id": 1,
      "username": "admin",
      "password": "",
      "base_path": "/",
      "role": 2,
      "disabled": false,
      "permission": 0,
      "sso_id": ""
    },
    {
      "id": 2,
      "username": "guest",
      "password": "",
      "base_path": "/",
      "role": 1,
      "disabled": true,
      "permission": 0,
      "sso_id": ""
    },
    {
      "id": 3,
      "username": "test",
      "password": "",
      "base_path": "/分享/test",
      "role": 0,
      "disabled": false,
      "permission": 1016,
      "sso_id": ""
    }
  ],
  "storages": [
    {
      "id": 1,
      "mount_path": "/分享",
      "order": 0,
      "driver": "Local",
      "cache_expiration": 0,
      "status": "work",
      "addition": "{\"root_folder_path\":\"/volume1/homes/admin/Files/tmp\",\"thumbnail\":true,\"thumb_cache_folder\":\"\",\"show_hidden\":true,\"mkdir_perm\":\"777\",\"recycle_bin_path\":\"delete permanently\"}",
      "remark": "",
      "modified": "2024-04-13T13:20:35.610898186+08:00",
      "disabled": false,
      "enable_sign": false,
      "order_by": "",
      "order_direction": "",
      "extract_folder": "",
      "web_proxy": false,
      "webdav_policy": "native_proxy",
      "down_proxy_url": ""
    }
  ],
  "metas": []
}

### Logs / 日志

![Snipaste_2024-04-13_13-12-43](https://github.com/alist-org/alist/assets/48763829/1527fa7b-8a27-448e-822f-2b4ee835c1a2)
![Snipaste_2024-04-13_13-13-40](https://github.com/alist-org/alist/assets/48763829/450c7125-db99-4511-9d4b-a8f740b3ae2e)
![Snipaste_2024-04-13_13-14-31](https://github.com/alist-org/alist/assets/48763829/71db43ac-940b-423a-a02d-d19e8e65c632)

**Comment by MJ-spmoon** [comment]
win挂载webdav子账号登录，确实有这个bug，排查很久，确定是alist子账号的bug，但全网貌似没有解决办法，不知官方何时解决
