### ISSUE TITLE
Quark: failed get objs: failed to list objs: token [st invalid]

### ISSUE THREAD

**Issue by alexbiaolol** [alist-org/alist#6348]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.33.0

### Driver used / 使用的存储驱动

Quark

### Describe the bug / 问题描述

The configuration didn't change but recently shows "failed get objs: failed to list objs: token [st invalid]"

### Reproduction / 复现链接

N/A

### Config / 配置

N/A

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/166027685/f579579f-4b9e-41cd-97e5-705534d375a9)

**Comment by anwen-anyi** [comment]
无任何问题吖？ 能添加 能列出列表 能下载
![image](https://github.com/alist-org/alist/assets/56105412/127e869a-b8d9-48d2-9528-1a7e0218585b)
![image](https://github.com/alist-org/alist/assets/56105412/2ceb658f-0883-410c-a915-d45719eb9cf4)
![image](https://github.com/alist-org/alist/assets/56105412/0cb020b5-decb-4b79-80fb-ee5e8b89c4c1)

**Comment by DestinyYZH** [comment]
遇到了类似的问题，简单检查了一下，应该是网页版夸克请求网址变化了，现在请求网址是 drive-pc.quark.cn/* ,过去是drive.quark.cn/* ,在alist里请求的还是旧地址
![屏幕截图 2024-05-12 104538](https://github.com/alist-org/alist/assets/169570069/b06bffa7-261e-4a27-88d9-f60b16700c50)
![屏幕截图 2024-05-12 105322](https://github.com/alist-org/alist/assets/169570069/45a60774-e849-4e31-b676-a200fc9eebee)

**Comment by DeodarPeng** [comment]
重新获取更新下cookie

**Comment by gaoshulaoshi** [comment]
我卸载掉从istore os商店一键安装的版本从这个（https://dl.openwrt.ai）仓库重新安装后，设备重启alist也不会挂了
