### ISSUE TITLE
office文件 预览，不知道什么原因，有的可以，有的提示“很抱歉，无法打开此文档，因为与服务通信时出现问题。”

### ISSUE THREAD

**Issue by wangzichenglong** [alist-org/alist#6349]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33

### Driver used / 使用的存储驱动

天翼云盘家庭云

### Describe the bug / 问题描述

office文件 预览，不知道什么原因，有的可以，有的提示“很抱歉，无法打开此文档，因为与服务通信时出现问题。”
可以如图：
![image](https://github.com/alist-org/alist/assets/101960731/59e0fbb6-688a-4a36-af00-579c14b55690)
同一路径下另一个文件，不可以预览，如图：
![image](https://github.com/alist-org/alist/assets/101960731/25a30077-6cb9-4c30-b94a-668eee65d291)

pptx文件也是这样
这个可以，如图：
![image](https://github.com/alist-org/alist/assets/101960731/240585ec-596c-4534-9ccf-0e3280b20091)

这个却不可以，文件只有54KB，并不是很大。如图：
![image](https://github.com/alist-org/alist/assets/101960731/2ad2a69b-1336-439e-95ee-ac877116c996)

之前，一直用Oneindex，任何office文件都可以加载预览，没有问题，而且有一个特点是播放ppt就直接全屏，不会重新刷新加载一次页面。alist点击“开始放映幻灯片”会在全屏时重新加载刷新一次页面文件。
不过Oneindex不支持天翼、阿里等网盘，只好放弃，因为我的E5账户续期了两年终于还是到期，续不了了。现在众多网盘列表应用，只有alist独居榜首，希望能解决这个小问题。我会一直支持大佬的。

### Reproduction / 复现链接

http://860510.xyz:5244/%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98/%E7%A7%81%E4%BA%BA/%E6%B1%9F%E9%98%B4%E5%B8%82%E5%88%9D%E4%B8%AD%E7%94%9F%E8%AF%BE%E5%A4%96%E9%98%85%E8%AF%BB%E4%B9%A6%E7%9B%AE%EF%BC%88%E9%99%84%E7%94%B5%E5%AD%90%E4%B9%A6%E7%89%88%E6%9C%AC%EF%BC%89.doc

http://860510.xyz:5244/%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98/%E7%A7%81%E4%BA%BA/2023%E4%B8%83%E4%B8%8B/%E7%BB%83%E4%B9%A0%E5%92%8C%E5%A4%8D%E4%B9%A0/%E6%9C%A8%E5%85%B0%E8%AF%97%E3%80%81%E5%9B%9B%E9%A6%96%E8%AF%97%E7%90%86%E8%A7%A3%E6%80%A7%E9%BB%98%E5%86%99%E3%80%81%E5%AD%99%E6%9D%83%E5%8A%9D%E5%AD%A6%E7%BF%BB%E8%AF%91.pptx

### Config / 配置

![image](https://github.com/alist-org/alist/assets/101960731/c9bea76e-2578-4e75-980f-3717111a95a5)
![image](https://github.com/alist-org/alist/assets/101960731/5db948d3-f347-413e-a6d7-0ca947820c89)
![image](https://github.com/alist-org/alist/assets/101960731/c7392eb1-d296-4c0f-ade8-6cd30c5dcb8f)
![image](https://github.com/alist-org/alist/assets/101960731/7d615a79-713a-4dad-a1fc-430436928246)
![image](https://github.com/alist-org/alist/assets/101960731/8774f92c-bbc7-461b-b92a-1a51b96cf8ad)
![image](https://github.com/alist-org/alist/assets/101960731/9287894f-f928-47f6-a5a0-4782f4a8efa0)

config文件内容
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "*************",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

### Logs / 日志

没有错误日志

**Comment by wangzichenglong** [comment]
摸索了一上午，好像是文件名太长就出现这个问题，那希望大佬解除文件名太长不能预览的限制

**Comment by xhofe** [comment]
如果有限制，则为预览提供商（微软）的限制，alist未做任何限制。

**Comment by wangzichenglong** [comment]
> 如果有限制，则为预览提供商（微软）的限制，alist未做任何限制。

好的。主要是之前用别的列表程序没有遇到过。我自己修改成短文件名，来避免不能预览吧。谢谢大佬回复。

另一个问题，是点击“开始放映幻灯片”会在全屏时重新加载刷新一次页面文件。导致本来在当前预览页已经浏览到第40张幻灯片，全屏放映，就自动切回第一张幻灯片。如果能够预览时第n张幻灯片，全屏播放依然是在这个n张幻灯片开始，不要重载。不知道大佬能不能在下个版本调整。
