### ISSUE TITLE
最简单易用的WireGuard VPN服务器——萤火虫

### ISSUE THREAD

**Issue by Safe3** [alist-org/alist#6350]
项目地址：https://github.com/Safe3/firefly

软件介绍：
最简单易用的WireGuard VPN服务器。可广泛应用于内网穿透、异地组网、远程办公等场景。

界面展示：
![image](https://raw.githubusercontent.com/Safe3/firefly/main/firefly_cn.png)

**Comment by Cp0204** [comment]
打广告有点节操，别再干这种事了，会被唾弃的
