### ISSUE TITLE
webdav文件移动重命名失败

### ISSUE THREAD

**Issue by AoEiuV020** [alist-org/alist#6351]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

webdav

### Describe the bug / 问题描述

webdav挂载后移动和重命名操作失败， 
尝试了windows rclone和linux dav2fs都一样， 
似乎偶尔能正常， 刚升级时试着移动几个文件正常， 过后再移动又失败了，

### Reproduction / 复现链接

/dav

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "CEvh。。。q",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

### Logs / 日志

D:\aoeiuv020\mnt>rclone mount alias:/ W:
2024/04/15 11:14:11 NOTICE: webdav root '': --vfs-cache-mode writes or full is recommended for this remote as it can't stream
The service rclone has been started.
2024/04/15 11:14:28 ERROR : backup/android/jks/key.properties: WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >= writes
2024/04/15 11:14:40 ERROR : backup/android/jks/key.properties: Couldn't move: copy call failed: Locked: 423 Locked
2024/04/15 11:14:40 ERROR : backup/android/jks/TaikoSongs.properties: File.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:14:40 ERROR : backup/android/jks/key.properties: Dir.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:14:40 ERROR : IO error: copy call failed: Locked: 423 Locked
2024/04/15 11:17:45 ERROR : backup/android/jks/key.properties: Couldn't move: copy call failed: Locked: 423 Locked
2024/04/15 11:17:45 ERROR : backup/android/jks/TaikoSongs/key.properties: File.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:17:45 ERROR : backup/android/jks/key.properties: Dir.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:17:45 ERROR : IO error: copy call failed: Locked: 423 Locked
2024/04/15 11:18:15 ERROR : backup/android/jks/TaikoSongs.jks: Couldn't move: copy call failed: Locked: 423 Locked
2024/04/15 11:18:15 ERROR : backup/android/jks/TaikoSongs/TaikoSongs.jks: File.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:18:15 ERROR : backup/android/jks/TaikoSongs.jks: Dir.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:18:15 ERROR : IO error: copy call failed: Locked: 423 Locked
2024/04/15 11:28:03 ERROR : backup/android/jks/panovel.jks: WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >= writes
2024/04/15 11:28:03 ERROR : backup/android/jks/signing.properties: WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >= writes
2024/04/15 11:28:03 ERROR : backup/android/jks/signing.txt: WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >= writes
2024/04/15 11:28:25 ERROR : backup/android/jks/panovel.jks: Couldn't move: copy call failed: Locked: 423 Locked
2024/04/15 11:28:25 ERROR : backup/android/jks/PaNovel/panovel.jks: File.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:28:25 ERROR : backup/android/jks/panovel.jks: Dir.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:28:25 ERROR : IO error: copy call failed: Locked: 423 Locked
2024/04/15 11:28:50 ERROR : backup/android/jks/panovel.jks: Couldn't move: copy call failed: Locked: 423 Locked
2024/04/15 11:28:50 ERROR : backup/android/jks/PaNovel/panovel.jks: File.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:28:50 ERROR : backup/android/jks/panovel.jks: Dir.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:28:50 ERROR : IO error: copy call failed: Locked: 423 Locked
The service rclone has been stopped.
2024/04/15 11:29:01 ERROR : W:: Unmounted rclone mount

D:\aoeiuv020\mnt>rclone mount alias:/ W:
2024/04/15 11:29:03 NOTICE: webdav root '': --vfs-cache-mode writes or full is recommended for this remote as it can't stream
The service rclone has been started.
2024/04/15 11:29:49 ERROR : backup/android/jks/panovel.jks: Couldn't move: copy call failed: Locked: 423 Locked
2024/04/15 11:29:49 ERROR : backup/android/jks/PaNovel/panovel.jks: File.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:29:49 ERROR : backup/android/jks/panovel.jks: Dir.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:29:49 ERROR : IO error: copy call failed: Locked: 423 Locked
2024/04/15 11:30:37 ERROR : backup/android/jks/signing.properties: Couldn't move: copy call failed: Locked: 423 Locked
2024/04/15 11:30:37 ERROR : backup/android/jks/PaNovel/signing.properties: File.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:30:37 ERROR : backup/android/jks/signing.properties: Dir.Rename error: copy call failed: Locked: 423 Locked
2024/04/15 11:30:37 ERROR : IO error: copy call failed: Locked: 423 Locked

**Comment by AoEiuV020** [comment]
@pongfcnkl 没有涉及云盘和跨盘之类的，就是最基本的本机存储开webdav，当前目录下重命名或者移动到子目录，报错，
alist网页操作是正常的， 就webdav不行，

**Comment by AoEiuV020** [comment]
webdav上传和删除也是正常的， 权限都有给，
![image](https://github.com/alist-org/alist/assets/11682198/a9d60f80-6ac9-4ef3-ac7e-f9aac63088d5)

**Comment by xhofe** [comment]
看日志是修改冲突 文件lock了

**Comment by AoEiuV020** [comment]
@xhofe  看到了，可是没找到什么冲突，rclone是刚安装挂载的， 文件是刚上传的，文件夹是刚创建的， 到这里都正常，然后重命名或者移动文件就失败， 翻来覆去都失败，但现在又正常了，

**Comment by AoEiuV020** [comment]
别自动关闭吧，
