### ISSUE TITLE
工具栏显示选中文件的数量

### ISSUE THREAD

**Issue by SingleRottenChips** [alist-org/alist#6354]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

选中文件时能在工具栏显示选中的数量

（因为文件比较多，已经不小心选中误删了三次了... 尽管几乎每次删除前都会确认是否有选多，或者取消选择再次选择以确保没有选错，但还是难免会出现误删的情况）

**Comment by asforest** [comment]
+1，多选时确实需要一个文件数量的显示，统计一下目录内有多少个文件也会很方便

**Comment by trdong19** [comment]
+1
