### ISSUE TITLE
下载后文件名带sgin

### ISSUE THREAD

**Issue by KKISO574** [alist-org/alist#6364]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

Onedrive OSS

### Describe the bug / 问题描述

复制的下载链接带sgin，下载后的文件名也带一堆信息
用wget会有这样的问题。window浏览器正常下载不会。

### Reproduction / 复现链接

![微信截图_20240419163012](https://github.com/alist-org/alist/assets/68904107/8bafb9b2-5ea0-455d-b434-be1bcf09079b)
尝试使用wget下载文件链接 https://cloud.7boe.top/d/Onedrive/Softwar/JAVA/jdk-8u401-linux-x64.tar.gz?sign=M1HMFXaVYIsKGD_dLmHPS254CvUJQqqkjcxn8-lmXnM=:0

### Config / 配置

![image](https://github.com/alist-org/alist/assets/68904107/cb8715b4-7004-4a20-851c-c1a68118945f)
![image](https://github.com/alist-org/alist/assets/68904107/9759d383-a863-4808-939a-883391e6bbed)

**Comment by xhofe** [comment]
- -o 指定 文件名
- 关闭签名
