### ISSUE TITLE
才发现alist，很不错！第一次用，有点建议。

### ISSUE THREAD

**Issue by niubility000** [alist-org/alist#6379]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

1. 左上角为啥一直在转圈圈？转圈圈是表示还在加载啊。可页面都加载完成了啊？看着很怪异。如果是个动图想看着漂亮，换个其他的。
2. 当文件夹里有大量图片，数千张的时候，在图片视图下，拖拽滚动条会卡顿，很卡，基本没法浏览了。而且加载时图片排版会不停变化，不停闪。能不能加个虚拟列表技术？或者直接从jpg的exif里读取缩略图？这样速度会快很多。或者建立一个图片缓存(还没仔细研究)，下次加载时速度就会快很多。
3. 在手机深色背景时，选择框消失了，页面看着有些怪。
其他的都很好，漂亮。

### Reproduction / 复现链接

https://al.nn.ci/

### Config / 配置

就用demo网站观看就行。demo的配置。

**Comment by vpei** [comment]
左上角图片，可以在后台设置成https://alist.nn.ci/logo.svg，默认的网址给墙了。
