### ISSUE TITLE
最新版本alist重启时有很大概率无法启动，提示s3服务端口冲突

### ISSUE THREAD

**Issue by ttpcy** [alist-org/alist#6391]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.33.0

### Driver used / 使用的存储驱动

/

### Describe the bug / 问题描述

平时使用通过AList Desktop管理alist，最近发现不论是使用软件自带的定时重启，还是人工点击重启，都有很大概率无法启动，具体报错如下：
FATA[2024-04-24 23:07:26] failed to start http: listen tcp 0.0.0.0:5246: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

我尝试解决：
1确认主机并没有其他程序监听5246端口
2尝试更换过默认的5246端口，依然无效
3重启操作并非每次都无法启动，多重启几次可能有概率就能起来
4日志文件没有异常

配置文件没有做过改动，通过AList Desktop配置每天0点自动重启一次alist，早期版本没发现这个问题，最近每天早晨都有概率出现服务已停止，故判断是最新版本才出现。

希望可以得到确认回复，非常感谢。

### Reproduction / 复现链接

/

### Config / 配置

/

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/54440651/bf797a03-4564-4d53-9b87-d29785978963)

**Comment by im-dashan** [comment]
config.json配置文件有3个端口，如果你有多个alist服务的话可以把这3个端口的端口号改一下就可正常启动

**Comment by ttpcy** [comment]
> config.json配置文件有3个端口，如果你有多个alist服务的话可以把这3个端口的端口号改一下就可正常启动

我只有1个alist服务。
改了端口之后他也会提示新端口冲突。。。

**Comment by ttpcy** [comment]
> config.json配置文件有3个端口，如果你有多个alist服务的话可以把这3个端口的端口号改一下就可正常启动

只是s3服务端口冲突

  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }

这段配置文件不能删，删了还会自动加回来，只能改端口。
不理解为啥配置成false，还有这个端口监听。

**Comment by BlueSkyXN** [comment]
`通过AList Desktop配置每天0点自动重启一次alist`

很难理解这是在干嘛

**Comment by itsHenry35** [comment]
fixed in 3.34.0
