### ISSUE TITLE
OneDrive 添加成功后报错 failed get objs: failed to list objs: Tenant does not have a SPO license.

### ISSUE THREAD

**Issue by cc1477** [alist-org/alist#6402]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.33.0

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

failed get objs: failed to list objs: Tenant does not have a SPO license.

### Reproduction / 复现链接

https://alist.youcc.top/OneDrive

### Config / 配置

.

### Logs / 日志

failed get objs: failed to list objs: Tenant does not have a SPO license.

**Comment by wangzh6859** [comment]
I don't know if you have solved it, I have the same problem now.

**Comment by oboard** [comment]
Same problem
