### ISSUE TITLE
sftp存储 bug

### ISSUE THREAD

**Issue by petulat** [alist-org/alist#6403]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

SFTP

### Describe the bug / 问题描述

经常接上不到半天就坏了，报错： failed get objs: failed to list objs: connection lost
必须重启（restart docker）才能再次正常连接
之前有人提过（[issue-6042](https://github.com/alist-org/alist/issues/6042)），评论中不少人也遇到了，但没有被开发者注意到。能不能尽快修正下这个 bug？

### Reproduction / 复现链接

内网未开放公网

### Config / 配置

内网未开放公网

### Logs / 日志

链接页面显示： failed get objs: failed to list objs: connection lost
docker 日志似乎无报错显示

**Comment by li-jun** [comment]
同样遇到此问题，缓存设置为1分钟也不会自动重新连接，请早日修复，谢谢！
