### ISSUE TITLE
alist账号登录的设备记录

### ISSUE THREAD

**Issue by at86397388** [alist-org/alist#6404]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否增加以下功能：
1、后台记录所有登录的设备名称。
2、可以撤销已登录的设备的登录。

**Comment by anwen-anyi** [comment]
没必要....
