### ISSUE TITLE
新版本下载连接如果关闭sign=这一部分的字段？

### ISSUE THREAD

**Issue by Jack-Ywn** [alist-org/alist#6405]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.31.0

### Driver used / 使用的存储驱动

本地驱动

### Describe the bug / 问题描述

旧版本中的下载连接我使用wget命令就可以直接下载并且文件名称也是正确的
wget http://10.10.0.243:5244/d/xelis/xelis_luna_miner_1

新版本中多了后面多了sign这部分的内容（此时我下载后的名称就不是正确的）
wget http://10.10.0.243:5244/d/xelis/xelis_luna_miner_1?sign=MFsc9XD_rMLXN3DJkbfR49_-NldhWVqyBoLn0KW5Rcs=:0

这个sign这部分的内容可以关闭吗，我找了很久并没有发现相关的关闭选项，希望得到一些帮助指引

### Reproduction / 复现链接

内网环境

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "musYfjne0X03Kf95",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  }
}

**Comment by Jack-Ywn** [comment]
不好意思，全部关闭签名就可以了
![image](https://github.com/alist-org/alist/assets/72083949/239223db-0ce2-4369-803c-33880af99a0c)

**Comment by Dragon1573** [comment]
> 不好意思，全部关闭签名就可以了

我使用 `nssm.exe` 将 _Alist_ 作为 Windows 服务进行安装，已关闭 **设置 > 全局 > 签名所有** 并重启 _Alist_ ，此处 `sign` 仍未被移除。

![image](https://github.com/alist-org/alist/assets/49941141/0042d7e3-5b31-46eb-bb53-29115c040e95)

我正在使用 _Alist_ 作为 `winget.exe` 的本地测试服务器，存在 `sign` 会阻塞 `winget.exe` 下载安装程序。

![image](https://github.com/alist-org/alist/assets/49941141/1d22c9cb-4e3c-41ea-955d-cfb2390a183b)

<details><summary><code>config.json</code></summary>

```json
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "__masked__",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data\\data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 80,
    "https_port": 443,
    "force_https": false,
    "cert_file": "data\\cert\\www_example_com.crt",
    "key_file": "data\\cert\\www_example_com.key",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data\\temp",
  "bleve_dir": "data\\bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data\\log\\log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}
```

</details>

**Comment by ArenaDruid** [comment]
> > 不好意思，全部关闭签名就可以了
> 
> 我使用 `nssm.exe` 将 _Alist_ 作为 Windows 服务进行安装，已关闭 **设置 > 全局 > 签名所有** 并重启 _Alist_ ，此处 `sign` 仍未被移除。
> 
> ![image](https://private-user-images.githubusercontent.com/49941141/335807730-0042d7e3-5b31-46eb-bb53-29115c040e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzU3MDcsIm5iZiI6MTcyMzQzNTQwNywicGF0aCI6Ii80OTk0MTE0MS8zMzU4MDc3MzAtMDA0MmQ3ZTMtNWIzMS00NmViLWJiNTMtMjkxMTVjMDQwZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA0MDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzg3MWE5Y2Q5YmM2M2RkYTE3NzczMzcwNTljYTk0NjAwYzE0MDUyOGI3MDY5ZDM5OGNlMzgyNjk2ZDNiMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WnGhdmuWtG7sawsspq8nxpDfG5znoZeO9LGa-9tmplQ)
> 
> 我正在使用 _Alist_ 作为 `winget.exe` 的本地测试服务器，存在 `sign` 会阻塞 `winget.exe` 下载安装程序。
> 
> ![image](https://private-user-images.githubusercontent.com/49941141/335807648-1d22c9cb-4e3c-41ea-955d-cfb2390a183b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzU3MDcsIm5iZiI6MTcyMzQzNTQwNywicGF0aCI6Ii80OTk0MTE0MS8zMzU4MDc2NDgtMWQyMmM5Y2ItNGUzYy00MWVhLTk1NWQtY2ZiMjM5MGExODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA0MDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNGRiN2VlNThmZDgyY2Y0YzlmZjViYWE4NWNjYmJjNTczZjZmYzFjMDFjNGYxM2Y4MWViNTEzYmU0MjI1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pfa0feqwccgzG9OoSKMtQ-Ow_X5mfgSBxpnpAvXCgFM)
> 
> `config.json`
> ```json
> {
>   "force": false,
>   "site_url": "",
>   "cdn": "",
>   "jwt_secret": "__masked__",
>   "token_expires_in": 48,
>   "database": {
>     "type": "sqlite3",
>     "host": "",
>     "port": 0,
>     "user": "",
>     "password": "",
>     "name": "",
>     "db_file": "data\\data.db",
>     "table_prefix": "x_",
>     "ssl_mode": "",
>     "dsn": ""
>   },
>   "meilisearch": {
>     "host": "http://localhost:7700",
>     "api_key": "",
>     "index_prefix": ""
>   },
>   "scheme": {
>     "address": "0.0.0.0",
>     "http_port": 80,
>     "https_port": 443,
>     "force_https": false,
>     "cert_file": "data\\cert\\www_example_com.crt",
>     "key_file": "data\\cert\\www_example_com.key",
>     "unix_file": "",
>     "unix_file_perm": ""
>   },
>   "temp_dir": "data\\temp",
>   "bleve_dir": "data\\bleve",
>   "dist_dir": "",
>   "log": {
>     "enable": true,
>     "name": "data\\log\\log.log",
>     "max_size": 50,
>     "max_backups": 30,
>     "max_age": 28,
>     "compress": false
>   },
>   "delayed_start": 0,
>   "max_connections": 0,
>   "tls_insecure_skip_verify": true,
>   "tasks": {
>     "download": {
>       "workers": 5,
>       "max_retry": 1
>     },
>     "transfer": {
>       "workers": 5,
>       "max_retry": 2
>     },
>     "upload": {
>       "workers": 5,
>       "max_retry": 0
>     },
>     "copy": {
>       "workers": 5,
>       "max_retry": 2
>     }
>   },
>   "cors": {
>     "allow_origins": [
>       "*"
>     ],
>     "allow_methods": [
>       "*"
>     ],
>     "allow_headers": [
>       "*"
>     ]
>   },
>   "s3": {
>     "enable": false,
>     "port": 5246,
>     "ssl": false
>   }
> }
> ```

不仅那个界面有“签名所有”的选项需要关闭，在存储的设置界面也有“签名”的选项需要关闭。
![image](https://github.com/user-attachments/assets/0685efaf-14b7-403a-a9ac-c56b3fc85a85)

**Comment by Dragon1573** [comment]
> 不仅那个界面有「签名所有」的选项需要关闭，在存储的设置界面也有「签名」的选项需要关闭。

已把这两处全部都关闭，现在确认 `?sign=` 部分已被移除。
