### ISSUE TITLE
蓝奏云优享版failed link: failed get link: redirect failed, status: 200

### ISSUE THREAD

**Issue by songqingawa** [alist-org/alist#6415]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

编译最新开发版32

### Driver used / 使用的存储驱动

蓝奏云优享版

### Describe the bug / 问题描述

提示失败链接：失败 获取链接：重定向失败，状态：200

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/76278016/bf356698-ab69-4bda-b495-630369f1dc11)

### Config / 配置

无

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/76278016/95ecff0e-0299-4a56-a83c-6895b63483af)

**Comment by ZOHI666** [comment]
一样的BUG

**Comment by Sakurai-Yukina** [comment]
同上，一样的问题

**Comment by arch3rPro** [comment]
小飞机网盘一样的问题吼

**Comment by im-dashan** [comment]
蓝奏云优享版确实会出现200问题

**Comment by Greyisttot** [comment]
你们开会员没

**Comment by Sakurai-Yukina** [comment]
> 你们开会员没

开会员和不开会员都会200

**Comment by juzipi91917** [comment]
有人解决了吗

**Comment by huolanyun** [comment]
@xhofe 大佬修复一下飞机盘和蓝奏优享盘备

**Comment by trainliang** [comment]
新版本直接锁定ip了：failed link: failed get link: redirect failed, content: {"msg":"该IP已被锁定，请联系客服","code":-1}
昨天发布的的版本

**Comment by im-dashan** [comment]
那怎么办


trainliang ***@***.***> 于2024年5月24日周五 09:28写道：
