### ISSUE TITLE
希望添加对无后缀文件的预览选项

### ISSUE THREAD

**Issue by Cnily03** [alist-org/alist#6417]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

诸如 `Dockerfile` 等文件固定为文本文件，但是当前的 alist 只能设置后缀名

### Suggested solution / 实现思路

希望对“预览”配置增加一个根据文件名（或其正则）的配置（而不仅仅是根据后缀名来设置）

或者在前端能够支持`?type=txt`的 URL 参数

**Comment by potoo0** [comment]
@xhofe 我也有类似需求，你觉得以下方式哪种比较好？

- *设置/预览* 的 **文本类型** 支持正则/或者简单通配符
- 前端从地址参数获取 type，文件详情页面增加 **以文本方式预览** 按照

**Comment by potoo0** [comment]
使用说明( 后续会补充到文档里 ):

请求参数加 `type`, 可选值:
```
UNKNOWN
FOLDER
VIDEO
AUDIO
TEXT
IMAGE
```

示例: `http://alist.code.com/local/test.ahk?type=text`
