### ISSUE TITLE
游客无法显示文件夹说明中的本地图片

### ISSUE THREAD

**Issue by LanYangYang-114** [alist-org/alist#6419]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.0

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

以游客身份浏览时无法显示文件夹说明中的本地图片，使用其他身份（Admin和General账户）则能正常显示，尝试过删除元信息、替换别的图片都是这个现象
![PixPin_2024-05-04_00-03-13](https://github.com/alist-org/alist/assets/84030410/cb1e5887-a287-4ad3-af1a-a112739d3504)

### Reproduction / 复现链接

没有公网，给不了链接

### Config / 配置

![image](https://github.com/alist-org/alist/assets/84030410/af9239a1-c01c-4c10-8cd3-2c6267c61dd5)
![image](https://github.com/alist-org/alist/assets/84030410/009cd486-07a7-4673-b14e-92719167d65a)
![image](https://github.com/alist-org/alist/assets/84030410/de4dc9a5-d3bf-427c-8d23-19430d598d4a)

**Comment by liuycy** [comment]
😂 因为 guset 用户设置了 `基本路径`，Markdown 里解析你的图片地址 `default.jpg` 没有带上这个基本路径

在没有修复之前，你可以尝试
- 修改 guest 用户的 基本路径 为 `/`
- 使用绝对路径 `/共享文件夹/公共文件夹/default.jpg`

**Comment by LanYangYang-114** [comment]
> 😂 因为 guset 用户设置了 `基本路径`，Markdown 里解析你的图片地址 `default.jpg` 没有带上这个基本路径
> 
> 在没有修复之前，你可以尝试
> 
> * 修改 guest 用户的 基本路径 为 `/`
> * 使用绝对路径 `/共享文件夹/公共文件夹/default.jpg`

原来还可以这样调用🤔，我以为设置基本路径后无法访问到基本路径上一级的目录
