### ISSUE TITLE
[Feature] 文件移动时, 添加一个 上次位置 的可选项 (类似百度云存储时的效果)

### ISSUE THREAD

**Issue by zuilintan** [alist-org/alist#6428]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

文件移动时, 添加一个 上次位置 的可选项, 
用于快速进行多次文件迁移, 现在每次移动都要从root开始选择, 十分不便, 尤其是当目录很深时

(或者可以考虑留存一个历史记录列表, 效率更高 )

### Additional context / 附件

![image](https://github.com/alist-org/alist/assets/34953840/63f2a07a-4d8e-4cc2-b82b-9c1a0c30b026)

![image](https://github.com/alist-org/alist/assets/34953840/0ac2293a-1d25-4971-af78-6f2978f4ab7c)

**Comment by ypq123456789** [comment]
支持，非常需要这个功能

**Comment by liuycy** [comment]
😂 什么都不选 直接点确定, 就会移动到上次位置 

https://github.com/alist-org/alist/assets/55272688/44d2202d-f856-46c1-9d79-d672fdb5abd8

**Comment by ypq123456789** [comment]
所以这只是个前端显示上的问题，不应该增加功能，反而是修复了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月13日(周一) 晚上6:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alist-org/alist] [Feature] 文件移动时, 添加一个 上次位置 的可选项 (类似百度云存储时的效果) (Issue #6428)




 
😂 什么都不选 直接点确定, 就会移动到上次位置
 
https://github.com/alist-org/alist/assets/55272688/44d2202d-f856-46c1-9d79-d672fdb5abd8

**Comment by zuilintan** [comment]
hah, 有点好笑, 
明白了
