### ISSUE TITLE
【本地设置】希望提供默认Aria2地址配置

### ISSUE THREAD

**Issue by junfengP** [alist-org/alist#6429]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

当前【本地设置】中可以配置Aria2的下载地址和密钥，该信息的存储似乎是基于浏览器的本地存储。当切换设备 或 浏览器数据被清理时，需要重新配置【本地设置】。

希望能提供一个解决方案，避免重复配置【本地设置】

### Suggested solution / 实现思路

1. 提供环境变量/程序配置能力，可以指定全局-本地设置-aria2配置
2. 增加帐号级别配置，在配置页面管理-本地设置-aria2配置
3. 在自定义网站样式设置中，将aria2配置抽象出来，在管理页面进行配置

从alist目前的使用体验上来看，方案3是最合理的。

**Comment by li-peifeng** [comment]
首先很多人是共享alist出来的，你配置好了别人要是点了难道都下载到你的设备上？ 如果你想要默认配置好的可以使用自己编译
