### ISSUE TITLE
挂载谷歌相册，一段时间后（大概三四周？）就无法打开了

### ISSUE THREAD

**Issue by justhy** [alist-org/alist#6433]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.0

### Driver used / 使用的存储驱动

谷歌相册

### Describe the bug / 问题描述

挂载谷歌相册，一段时间后（大概三四周？）就无法打开了。需要重新授权后又可以打开，但是过一段时间又不能打开了。
![Snipaste_2024-05-08_17-23-01](https://github.com/alist-org/alist/assets/17880968/bb0f1bed-0e3c-43ab-ab97-e1e8dc5377da)

### Reproduction / 复现链接

https://github.com/alist-org/alist/assets/17880968/bb0f1bed-0e3c-43ab-ab97-e1e8dc5377da
![Snipaste_2024-05-08_17-23-01](https://github.com/alist-org/alist/assets/17880968/366dcccd-dd60-4bdd-bc5b-8d62db2fc290)

### Config / 配置

配置没有太多更改
![Snipaste_2024-05-08_17-25-45](https://github.com/alist-org/alist/assets/17880968/54ecd4f9-b850-40cc-8452-3d072905aa4e)

**Comment by anwen-anyi** [comment]
应该和云盘一样？ 测试版一段时间就会掉 得转换成发布/稳定版才可以长久吧？（个人猜测）

**Comment by Xiefengshang** [comment]
应该是上个评论所说的情况，因为我的`google photos`正常挂载使用快半年了，没掉过
