### ISSUE TITLE
SMB无法正常进入子目录

### ISSUE THREAD

**Issue by kaozb** [alist-org/alist#6440]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

samba

### Describe the bug / 问题描述

配置好蒲公英的目录挂载后，文件夹始终只能在最外面一层，无法进入子文件夹

![image](https://github.com/alist-org/alist/assets/85659592/1d2b6380-f120-4bfa-b5e2-8438149c0e48)

### Reproduction / 复现链接

没有

### Config / 配置

![image](https://github.com/alist-org/alist/assets/85659592/bee818e1-439f-432e-8b98-a50266fb8524)

**Comment by kaozb** [comment]
蒲公英X1 的文件共享

**Comment by blueveryday** [comment]
我遇到了相同的问题，无法访问子文件夹。
