### ISSUE TITLE
文件复制时存在很大的内存占用

### ISSUE THREAD

**Issue by mcoo** [alist-org/alist#6444]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.0

### Driver used / 使用的存储驱动

 ALIST V3

### Describe the bug / 问题描述

从本地存储复制一个5GB左右的文件到另一个 ALIST V3 时出现高内存占用
[heap.zip](https://github.com/alist-org/alist/files/15283116/heap.zip)

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by anwen-anyi** [comment]
占用内存是正常的情况，不然如何复制到另一个存储呢。

**Comment by mcoo** [comment]
是否可以对其进行限制
![image](https://github.com/alist-org/alist/assets/26184088/e167d24c-0c18-4f26-b730-208011e11169)
主机的内存被耗尽，然后alist 会重启导致复制任务中断
![image](https://github.com/alist-org/alist/assets/26184088/029294c2-1d7b-462b-b610-79385c4924c5)
[heap_4.zip](https://github.com/alist-org/alist/files/15284909/heap_4.zip)

**Comment by mcoo** [comment]
> 同时复制文件数量设置的少一点

这个和文件数量应该无关，是因为使用的 resty 在请求时会一次性读取全部的文件到内存，导致内存的大量占用所引起的。
目前有一个解决方法，只需要挂载为 webdav 就可以解决这个问题。
