### ISSUE TITLE
证书过期导致无法访问

### ISSUE THREAD

**Issue by PterX** [alist-org/alist#6448]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.0

### Driver used / 使用的存储驱动

All

### Describe the bug / 问题描述

Post "https://api.xhofe.top/alist/ali_open/token": tls: failed to verify certificate: x509: certificate has expired or is not yet valid

### Reproduction / 复现链接

Post "https://api.xhofe.top/alist/ali_open/token": tls: failed to verify certificate: x509: certificate has expired or is not yet valid

### Config / 配置

*

**Comment by MT-Black** [comment]
后台管理存储内，阿里云盘存储里面的Oauth令牌链接，更换成
https://api-cf.nn.ci/alist/ali_open/token
试试
参考文档：https://alist.nn.ci/guide/drivers/aliyundrive_open.html

**Comment by PterX** [comment]
> 后台管理存储内，阿里云盘存储里面的Oauth令牌链接，更换成 https://api-cf.nn.ci/alist/ali_open/token 试试 参考文档：https://alist.nn.ci/guide/drivers/aliyundrive_open.html

我看到现在证书已经修复了，也谢谢你的解答
