### ISSUE TITLE
建议在一个用户下增加多个路径

### ISSUE THREAD

**Issue by cclove845** [alist-org/alist#6452]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议在一个用户下增加多个路径，这样可以更方便的给其它用户分享数据，谢谢。
![QQ截图20240513092339](https://github.com/alist-org/alist/assets/67997283/0e675a65-d4dd-4712-9e3f-c637ec2b898c)

**Comment by cclove845** [comment]
> 可以用别名

但是没有直接添加多个路径方便操作

**Comment by im-dashan** [comment]
别名需要怎么设置呢

**Comment by JiuMengDz** [comment]
别名不知道怎么设置  根据教程的设置也没有办法分到多个文件夹内

**Comment by cclove845** [comment]
> @cclove845别名也挺方便的

感觉并不方便

**Comment by BuTingBa** [comment]
真觉得需要这个该功能
