### ISSUE TITLE
阿里云盘经常出现 driver not init 错误

### ISSUE THREAD

**Issue by gexiaopeng** [alist-org/alist#6454]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.0

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

应用运行一段时间以后，打开阿里云盘Open列表经常出现 driver not init 错误，重启应用以后就恢复正常。
![微信图片_20240513164402](https://github.com/alist-org/alist/assets/7857056/9426b6e4-e753-4bb2-ad22-ba195f0e0aa1)

### Reproduction / 复现链接

无

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xxxxxx",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 11223,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "/logs/alist/alist.log",
    "max_size": 3,
    "max_backups": 50,
    "max_age": 48,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5247,
    "ssl": false
  }
}

### Logs / 日志

[31mERRO[0m[2024-05-12 14:51:07] fs/list: driver not init
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2938
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2009
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650

**Comment by gexiaopeng** [comment]
这种情况一般是在更新token的时候网络不通，那是否可以重新获取token呢，如果有重试机制，就不会有这个问题了。重启应用能恢复，说明没有去重试。

**Comment by leisolidworks** [comment]
我的出现Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
阿里云盘是不是已经开始针对了？

**Comment by anwen-anyi** [comment]
> 我的出现Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 阿里云盘是不是已经开始针对了？

你网络问题

**Comment by gexiaopeng** [comment]
> > 我的出现Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 阿里云盘是不是已经开始针对了？
> 
> 你网络问题

就算网络问题，如果出现driver not init，也应该有定期重新获取token的机制。

**Comment by leioukupo** [comment]
> > 就算网络问题，如果出现driver not init，也应该有定期重新获取token的机制。
> 
> 确实应该是网络问题，今天我打开alist发现所有盘都出现这个问题。找到这帖子看到说网络问题才想起代理端口换了，改了后就好了。

昨天我查了下，靠，服务器ip被阿里云盘拉黑了，只能换个服务器部署

**Comment by Deepsea-CN** [comment]
> > > 就算网络问题，如果出现driver not init，也应该有定期重新获取token的机制。
> > 
> > 
> > 确实应该是网络问题，今天我打开alist发现所有盘都出现这个问题。找到这帖子看到说网络问题才想起代理端口换了，改了后就好了。
> 
> 昨天我查了下，靠，服务器ip被阿里云盘拉黑了，只能换个服务器部署

不一定，你等1-2个小时重试一下应该就好了，我的之前也是莫名其妙的看电影看一半页面报too many requests 看服务器alist日志的错误就是你那个，等了一个多小时重新启动阿里open的存储就正常获取到token了

**Comment by HughRyu** [comment]
好多境外IP已经被阿里屏蔽了，想问一下怎么能给alist代理出去呢?

**Comment by leioukupo** [comment]
> 好多境外IP已经被阿里屏蔽了，想问一下怎么能给alist代理出去呢?
自己在家部署一个，内网穿透到公网
