### ISSUE TITLE
关于139网盘的bug

### ISSUE THREAD

**Issue by ThelevenFD** [alist-org/alist#6460]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.00

### Driver used / 使用的存储驱动

139(中国移动云盘)

### Describe the bug / 问题描述

root无法找到对应文件夹
FolderID显示个人云未知异常

### Reproduction / 复现链接

1.folderid in edge
![image](https://github.com/alist-org/alist/assets/104363913/4d7b4b02-0f0a-4eb7-b0b7-da517b99b5d7)
2.folderid in alist
![image](https://github.com/alist-org/alist/assets/104363913/c4f29cf4-6172-441e-8ced-0819ed654a21)
3.error
![image](https://github.com/alist-org/alist/assets/104363913/eb17482a-f58d-440a-a499-3bc726ecc92b)

1.139
![image](https://github.com/alist-org/alist/assets/104363913/4cf71c68-25e8-4828-a46c-ef1cd2afeacd)
2.alist
![image](https://github.com/alist-org/alist/assets/104363913/2e43dd07-5b6c-4d4a-925b-7f0ec3f8b3a6)

### Config / 配置

![image](https://github.com/alist-org/alist/assets/104363913/ff46b1f2-3a1a-4b8c-b61b-e0f2719b68b0)

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/104363913/a6de1207-ab50-4b0a-96c8-7f3757639b1b)
win10服务器版本

**Comment by anwen-anyi** [comment]
有文档你自己看看吖...

**Comment by ThelevenFD** [comment]
> 有文档你自己看看吖... 你文档不看乱填报错不很正常嘛~
> 
> * **[https://alist.nn.ci/zh/guide/drivers/139.html#个人云](https://alist.nn.ci/zh/guide/drivers/139.html#%E4%B8%AA%E4%BA%BA%E4%BA%91)**

我刚完整的读了一遍（其实已经读过很多遍了
不认为有哪里填错了啊（（
另外，我搜不到任何queryContentList，getDisk 如下
已经ctrl+f5,换了浏览器甚至拿了服务器来登陆
![image](https://github.com/alist-org/alist/assets/104363913/a0a607b1-221e-4126-9188-f102ce2c2bfc)
![image](https://github.com/alist-org/alist/assets/104363913/2d242da5-31fa-4e4e-83c0-dd9fb5fa10e9)

**Comment by anwen-anyi** [comment]
截图你填写AList的所有配置页面截图 敏感信息记得打码（记得别打死稍微留点儿可以辨别的）

**Comment by ThelevenFD** [comment]
![image](https://github.com/alist-org/alist/assets/104363913/0dc6c88e-ba80-41ab-9f73-94773a358434)
![image](https://github.com/alist-org/alist/assets/104363913/0e38f276-f6dc-477a-bfe9-ce6ef5401089)
![image](https://github.com/alist-org/alist/assets/104363913/0b9c7e6b-e8ca-462d-a0e6-ee75d7ffda18)
![image](https://github.com/alist-org/alist/assets/104363913/a9e6b514-b120-4e9b-a92a-bd93edfccdfe)
![image](https://github.com/alist-org/alist/assets/104363913/fdd268c3-3764-4333-a425-f4a5199cdb67)
![image](https://github.com/alist-org/alist/assets/104363913/8a5880f1-bc95-422e-96e5-c8f41771f49d)
![image](https://github.com/alist-org/alist/assets/104363913/ce3e4a18-a440-40d9-b560-de637aa3a1f1)
![image](https://github.com/alist-org/alist/assets/104363913/fbdebd1e-65e7-4ac4-8c63-fbb068958e9b)
![image](https://github.com/alist-org/alist/assets/104363913/359d6949-5954-4c9d-b8af-1fca3f3a6bed)
![image](https://github.com/alist-org/alist/assets/104363913/60433430-da73-4a62-a3cc-ec13301cbed0)
![image](https://github.com/alist-org/alist/assets/104363913/08b9a26f-6303-427b-81f3-18784dd94b05)
![image](https://github.com/alist-org/alist/assets/104363913/0cd4ce40-98e1-4a0a-9f78-4a2dca3f928a)

**Comment by anwen-anyi** [comment]
.......关键的你是一点儿没截到 云盘类型你到底使用的是个人云还是新个人云.... :sleeping:

**Comment by ThelevenFD** [comment]
我重新获取了个cookie，现在能读到了。。。
issue关了，麻烦了
