### ISSUE TITLE
Translation to another language

### ISSUE THREAD

**Issue by UrbanSide** [alist-org/alist#6470]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Is it possible to translate into Russian? I couldn’t find the translation file.

**Comment by xhofe** [comment]
I have added Russian to the target language, please feel free to help translate it [here](https://crwd.in/alist).
