### ISSUE TITLE
Alist的别名功能有问题，无法使用

### ISSUE THREAD

**Issue by JiuMengDz** [alist-org/alist#6474]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.0

### Driver used / 使用的存储驱动

别名

### Describe the bug / 问题描述

我想要创建多个用户可以访问，我知道可以使用别名功能来分配他们的文件夹
但是这个功能似乎有问题
我试了下
```
测试1:/文件夹1
测试2:/文件夹2
```

但是在最后打开这个别名文件夹里面直接就是文件夹1，没有出现测试1、测试2作为父目录。

https://alist.nn.ci/zh/guide/drivers/alias.html?giscus=2e5c5ec2d83e4fc03521d0d9rpaLWEA/NxdcnEjzcYXGgdSYA1Pa8SOYXlCnfpqMUvWklwB8jXbxTAWuXoPdrnlQFwJE70vbKcDse
cNp/6u5KopJoi6cWomtN0xGyxfabHNu8OvjkujX%2BmEi6BM=

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by anwen-anyi** [comment]
好像没啥问题？
![image](https://github.com/alist-org/alist/assets/56105412/84a1f01e-8be7-4c6a-8e2a-7a10c8e32af5)

**Comment by anwen-anyi** [comment]
> > 好像没啥问题？ ![image](https://private-user-images.githubusercontent.com/56105412/331863170-84a1f01e-8be7-4c6a-8e2a-7a10c8e32af5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTkyNzQsIm5iZiI6MTcxNjE5ODk3NCwicGF0aCI6Ii81NjEwNTQxMi8zMzE4NjMxNzAtODRhMWYwMWUtOGJlNy00YzZhLThlMmEtN2ExMGM4ZTMyYWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA5NTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMWZjZWFjMGMzM2RmZGZmZjQxZWE4MzU5ZDgxZGZlMzYwMWM3ZDA0MzlmYzBhZmY0NjEyMGYxOGFhMmQ1MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s1YoFwM3od1RXT5HZigmm8o-yOM81SNnHFwKC1fUjNs)
> 
> 
> 
> 添加时
> 
> ```yaml
> 
> 本地1:/1
> 
> 本地1:/2
> 
> ```
> 
> 编辑成
> 
> ```yaml
> 
> 本地1:/1
> 
> 本地2:/2
> 
> ```
> 
> 这样才会触发这个bug

嗯 编辑的话好像需要把驱动禁用一下再启用
