### ISSUE TITLE
S3存储桶中文文件名URL编码导致无法预览EPUB的问题

### ISSUE THREAD

**Issue by pengjianmim** [alist-org/alist#6477]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.0

### Driver used / 使用的存储驱动

对象存储 s3

### Describe the bug / 问题描述

排查发现是`response-content-disposition`参数的问题

预览中文EPUB文件失败 参数为 `attachment;%20filename*=UTF-8%27%27%E5%BA%86%E4%BD%99%E5%B9%B4.epub`
![image](https://github.com/alist-org/alist/assets/46677097/05e80a9f-c1ff-4dbb-af12-7f61efcdffbf)
预览英文EPUB文件成功 参数为 `attachment;%20filename*=UTF-8%27%27qingyunuan.epub`
![image](https://github.com/alist-org/alist/assets/46677097/91323d0a-d738-4032-b4a3-925010c30eb4)
使用下载功能时 参数为`attachment%3B%20filename%2A%3DUTF-8%27%27%25E5%25BA%2586%25E4%25BD%2599%25E5%25B9%25B4.epub`
![image](https://github.com/alist-org/alist/assets/46677097/7b65bcce-0b83-4744-a465-cf56361aa1b0)

### Reproduction / 复现链接

中文EPUB文件

https://s3.example.com/%E5%85%B6%E4%BB%96/%E5%BA%86%E4%BD%99%E5%B9%B4.epub?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=23995b90b0f9e414106d941202a7e8c2/20240520/auto/s3/aws4_request&X-Amz-Date=20240520T080109Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&response-content-disposition=attachment;%20filename*=UTF-8%27%27%E5%BA%86%E4%BD%99%E5%B9%B4.epub&X-Amz-Signature=5b07f92507553bf32e97a04d4ee3f20bae0ba029d311c08f2213e09f13834184

### Config / 配置

使用cloudflare r2的对象存储服务 没有开启直链访问

**Comment by ricolxwz** [comment]
你能预览pdf吗, 我用s3没法预览pdf, 但是直接用s3的url预览是可以的.

**Comment by pengjianmim** [comment]
> 你能预览pdf吗, 我用s3没法预览pdf, 但是直接用s3的url预览是可以的.

pdf可以正常预览 无论中文还是英文文件名
