### ISSUE TITLE
后台设置使用aria2出现证书验证相关错误

### ISSUE THREAD

**Issue by JanthonAlyn** [alist-org/alist#6479]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.0

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

我在AList的服务上安装了aria2程序，并配置好支持RPC调用，同时启用了SSL证书，但是后台设置aria2时，使用https或者wss协议连接会报错Failed to init aria2 client: tls: failed to verify certificate: x509: certificate signed by unknown authority
该证书DigiCert签发且在有效期内，且使用AriaNg前端调用该aria2正常（使用https协议或wss协议）。
![image](https://github.com/alist-org/alist/assets/59256720/373ea745-0b08-4766-b7e5-3f22dbf211fe)

若关闭RPC安全调用，使用http/ws协议调用aria则正常，SSL证书域名与调用aria RPC时使用的域名相符合
![image](https://github.com/alist-org/alist/assets/59256720/51b3cef2-9078-4a25-837f-6685a662adc3)

### Reproduction / 复现链接

https://alist.any-x.cn:5243/@manage/settings/other

### Config / 配置

[config.json](https://github.com/alist-org/alist/files/15378950/config.json)

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/59256720/6cbf301a-8953-4002-8a68-c6a0702efa13)

**Comment by 412999826** [comment]
我也有同样的问题，而且特别神奇的是如果我把alist也开启了证书，alist生成的下载链接无法发送到本机的aria2，本机的aria2也会提示证书错误

而且我在部署了alist的机器，curl alist的管理页面，也会提示证书出错

但是我如果把alist生成的下载链接发送其他机器的aria2，则一切正常；用其他机器curl alist管理页面，也不提示证书出错了，实在是搞不明白为什么。

**Comment by 412999826** [comment]
> ### Please make sure of the following things
> * [x] 
>   [x]  I have read the [documentation](https://alist.nn.ci).
>   我已经阅读了[文档](https://alist.nn.ci)。
>   [x] 
>   [x]  I'm sure there are no duplicate issues or discussions.
>   我确定没有重复的issue或讨论。
>   [x] 
>   [x]  I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
>   我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。
>   [x] 
>   [x]  I'm sure this issue is not fixed in the latest version.
>   我确定这个问题在最新版本中没有被修复。
> 
> ### AList Version / AList 版本
> v3.34.0
> 
> ### Driver used / 使用的存储驱动
> Onedrive
> 
> ### Describe the bug / 问题描述
> 我在AList的服务上安装了aria2程序，并配置好支持RPC调用，同时启用了SSL证书，但是后台设置aria2时，使用https或者wss协议连接会报错Failed to init aria2 client: tls: failed to verify certificate: x509: certificate signed by unknown authority 该证书DigiCert签发且在有效期内，且使用AriaNg前端调用该aria2正常（使用https协议或wss协议）。 ![image](https://github.com/alist-org/alist/assets/59256720/373ea745-0b08-4766-b7e5-3f22dbf211fe)
> 
> 若关闭RPC安全调用，使用http/ws协议调用aria则正常，SSL证书域名与调用aria RPC时使用的域名相符合 ![image](https://github.com/alist-org/alist/assets/59256720/51b3cef2-9078-4a25-837f-6685a662adc3)
> 
> ### Reproduction / 复现链接
> https://alist.any-x.cn:5243/@manage/settings/other
> 
> ### Config / 配置
> [config.json](https://github.com/alist-org/alist/files/15378950/config.json)
> 
> ### Logs / 日志
> ![image](https://github.com/alist-org/alist/assets/59256720/6cbf301a-8953-4002-8a68-c6a0702efa13)




我找到原因了，你申请的证书应该是三个文件
`cert.pem`
`chain.pem`
`privkey.pem`

你搭建ARIA2的时候，应该只使用了 `cert` 和 `privkey`。
通常来讲这不会出现问题，因为现代浏览器（如 Chrome、Firefox、Edge）通常会缓存常见的 CA 证书，但是某些 API 客户端或服务器端（如 curl）可能会遇到 certificate verify failed 错误。

所以你需要将 `cert.pem` 和 `chain.pem` 合成 `fullchain.pem`

并且在aria2的配置 `rpc-certificate` 引用 `fullchain.pem`

**Comment by JanthonAlyn** [comment]
> > ### Please make sure of the following things
> > 
> > * [x]
> >   [x]  I have read the [documentation](https://alist.nn.ci).
> >   我已经阅读了[文档](https://alist.nn.ci)。
> >   [x]
> >   [x]  I'm sure there are no duplicate issues or discussions.
> >   我确定没有重复的issue或讨论。
> >   [x]
> >   [x]  I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
> >   我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。
> >   [x]
> >   [x]  I'm sure this issue is not fixed in the latest version.
> >   我确定这个问题在最新版本中没有被修复。
> > 
> > ### AList Version / AList 版本
> > v3.34.0
> > ### Driver used / 使用的存储驱动
> > Onedrive
> > ### Describe the bug / 问题描述
> > 我在AList的服务上安装了aria2程序，并配置好支持RPC调用，同时启用了SSL证书，但是后台设置aria2时，使用https或者wss协议连接会报错Failed to init aria2 client: tls: failed to verify certificate: x509: certificate signed by unknown authority 该证书DigiCert签发且在有效期内，且使用AriaNg前端调用该aria2正常（使用https协议或wss协议）。 ![image](https://github.com/alist-org/alist/assets/59256720/373ea745-0b08-4766-b7e5-3f22dbf211fe)
> > 若关闭RPC安全调用，使用http/ws协议调用aria则正常，SSL证书域名与调用aria RPC时使用的域名相符合 ![image](https://github.com/alist-org/alist/assets/59256720/51b3cef2-9078-4a25-837f-6685a662adc3)
> > ### Reproduction / 复现链接
> > https://alist.any-x.cn:5243/@manage/settings/other
> > ### Config / 配置
> > [config.json](https://github.com/alist-org/alist/files/15378950/config.json)
> > ### Logs / 日志
> > ![image](https://github.com/alist-org/alist/assets/59256720/6cbf301a-8953-4002-8a68-c6a0702efa13)
> 
> 我找到原因了，你申请的证书应该是三个文件 `cert.pem` `chain.pem` `privkey.pem`
> 
> 你搭建ARIA2的时候，应该只使用了 `cert` 和 `privkey`
> 
> 通常来讲这不会出现问题，因为现代浏览器（如 Chrome、Firefox、Edge）通常会缓存常见的 CA 证书，但是某些 API 客户端或服务器端（如 curl）可能会遇到 certificate verify failed 错误。
> 
> 所以你需要用以下指令将 `cert.pem` 和 `chain.pem` 合成 `fullchain.pem`，并且在aria2的配置 `rpc-certificate` 引用 `fullchain.pem`
> 
> `cat cert.pem <(echo "") chain.pem > fullchain.pem`

感谢建议，刚登录服务器检查了下，我的SSL证书一直都是配备了完整证书链的，申请的证书格式是2个文件，而且自我更新Alist版本至v3.36.0时，此问题已经修复，本issue可关闭。

**Comment by Losalado** [comment]
> > > ### Please make sure of the following things
> > > 
> > > * [x]
> > >   [x]  I have read the [documentation](https://alist.nn.ci).
> > >   我已经阅读了[文档](https://alist.nn.ci)。
> > >   [x]
> > >   [x]  I'm sure there are no duplicate issues or discussions.
> > >   我确定没有重复的issue或讨论。
> > >   [x]
> > >   [x]  I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
> > >   我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。
> > >   [x]
> > >   [x]  I'm sure this issue is not fixed in the latest version.
> > >   我确定这个问题在最新版本中没有被修复。
> > > 
> > > ### AList Version / AList 版本
> > > v3.34.0
> > > ### Driver used / 使用的存储驱动
> > > Onedrive
> > > ### Describe the bug / 问题描述
> > > 我在AList的服务上安装了aria2程序，并配置好支持RPC调用，同时启用了SSL证书，但是后台设置aria2时，使用https或者wss协议连接会报错Failed to init aria2 client: tls: failed to verify certificate: x509: certificate signed by unknown authority 该证书DigiCert签发且在有效期内，且使用AriaNg前端调用该aria2正常（使用https协议或wss协议）。 ![image](https://github.com/alist-org/alist/assets/59256720/373ea745-0b08-4766-b7e5-3f22dbf211fe)
> > > 若关闭RPC安全调用，使用http/ws协议调用aria则正常，SSL证书域名与调用aria RPC时使用的域名相符合 ![image](https://github.com/alist-org/alist/assets/59256720/51b3cef2-9078-4a25-837f-6685a662adc3)
> > > ### Reproduction / 复现链接
> > > https://alist.any-x.cn:5243/@manage/settings/other
> > > ### Config / 配置
> > > [config.json](https://github.com/alist-org/alist/files/15378950/config.json)
> > > ### Logs / 日志
> > > ![image](https://github.com/alist-org/alist/assets/59256720/6cbf301a-8953-4002-8a68-c6a0702efa13)
> > 
> > 
> > 我找到原因了，你申请的证书应该是三个文件 `cert.pem` `chain.pem` `privkey.pem`
> > 你搭建ARIA2的时候，应该只使用了 `cert` 和 `privkey`
> > 通常来讲这不会出现问题，因为现代浏览器（如 Chrome、Firefox、Edge）通常会缓存常见的 CA 证书，但是某些 API 客户端或服务器端（如 curl）可能会遇到 certificate verify failed 错误。
> > 所以你需要用以下指令将 `cert.pem` 和 `chain.pem` 合成 `fullchain.pem`，并且在aria2的配置 `rpc-certificate` 引用 `fullchain.pem`
> > `cat cert.pem <(echo "") chain.pem > fullchain.pem`
> 
> 感谢建议，刚登录服务器检查了下，我的SSL证书一直都是配备了完整证书链的，申请的证书格式是2个文件，而且自我更新Alist版本至v3.36.0时，此问题已经修复，本issue可关闭。

遇到了类似的问题，使用完整证书链后解决。
记录一下，非常感谢。
