### ISSUE TITLE
WebDav无法复制大文件到本地磁盘

### ISSUE THREAD

**Issue by nickweiminhan** [alist-org/alist#6485]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.34.0

### Driver used / 使用的存储驱动

win10

### Describe the bug / 问题描述

无法改head头，不知道怎么解决
百度网盘 通过 raidrive软件 挂载到 Y盘
通过挂载的Y盘(百度网盘)复制20M以下文件/文件夹,可以正常复制的本地磁盘（图中Captura.zip）
大于20M文件/文件夹,不能复制，会显示管理员权限，权限不足的问题(图中PyCharm 2022.1.3.zip)。
没有地方改head头，无法解决。

![3](https://github.com/alist-org/alist/assets/51074475/009c57d4-f8f3-400c-b860-99262ef9e0b9)

![4](https://github.com/alist-org/alist/assets/51074475/96c509ff-f488-4208-bd18-984ab67e6617)

![6](https://github.com/alist-org/alist/assets/51074475/c5e20189-0623-436b-855d-b68f3e79f0ec)

![1](https://github.com/alist-org/alist/assets/51074475/01a158c0-54f1-45c7-a414-6ebf0150aff7)

### Reproduction / 复现链接

http://127.0.0.1:5244/

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "5JAqoFJXMin1XvFH",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data\\data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data\\temp",
  "bleve_dir": "data\\bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data\\log\\log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

**Comment by anwen-anyi** [comment]
关于百度和`Raidrive`

- **https://alist.nn.ci/zh/faq/why.html#raidrive%E6%8C%82%E8%BD%BD%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98-%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6-%E4%B8%8D%E8%83%BD%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E3%80%82%E5%BE%80%E6%8C%82%E8%BD%BD%E7%9B%AE%E5%BD%95%E4%B8%A2%E6%96%87%E4%BB%B6%E6%8F%90%E7%A4%BA-%E6%8F%90%E7%A4%BA-%E4%BD%A0%E9%9C%80%E8%A6%81%E6%9D%83%E9%99%90%E6%9D%A5%E6%89%A7%E8%A1%8C%E6%AD%A4%E6%93%8D%E4%BD%9C-%E3%80%82%E8%BF%99%E4%B8%AA%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3**

**Comment by nickweiminhan** [comment]
> 建议换clouddrive2

好的，我有空试一下

**Comment by nickweiminhan** [comment]
> 关于百度和`Raidrive`
> 
> * **https://alist.nn.ci/zh/faq/why.html#raidrive%E6%8C%82%E8%BD%BD%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98-%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E6%96%87%E4%BB%B6-%E4%B8%8D%E8%83%BD%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E3%80%82%E5%BE%80%E6%8C%82%E8%BD%BD%E7%9B%AE%E5%BD%95%E4%B8%A2%E6%96%87%E4%BB%B6%E6%8F%90%E7%A4%BA-%E6%8F%90%E7%A4%BA-%E4%BD%A0%E9%9C%80%E8%A6%81%E6%9D%83%E9%99%90%E6%9D%A5%E6%89%A7%E8%A1%8C%E6%AD%A4%E6%93%8D%E4%BD%9C-%E3%80%82%E8%BF%99%E4%B8%AA%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3**


谢谢，使用AList的V2版本可以从WebDav下载百度网盘大文件么

**Comment by nickweiminhan** [comment]
> clouddrive2

clouddrive2 是收费的么

**Comment by nickweiminhan** [comment]
> 建议换clouddrive2

WebDav无法复制百度大文件到本地磁盘 是可以了。但是网速非常的飘忽不定，忽高忽低。()
大批量复制百度 小文件到本地磁盘 速度也正常。()

![11](https://github.com/alist-org/alist/assets/51074475/cae329d8-e57e-44a4-9bd1-a8884284ae0b)

![1](https://github.com/alist-org/alist/assets/51074475/6971aaff-6051-482e-a165-292f9290815e)

![2](https://github.com/alist-org/alist/assets/51074475/d67416a9-8b2c-4388-9bde-51d49f522417)
![22](https://github.com/alist-org/alist/assets/51074475/4e6097c8-0f3f-495d-9058-1b31cb2c0ea2)
![222](https://github.com/alist-org/alist/assets/51074475/a2b2cb20-6024-45d1-9374-bb830ef5fffc)

**Comment by nickweiminhan** [comment]
> 建议换clouddrive2

您好，clouddrive2好像免费版只可以挂载2个网盘，还有别的软件可以推荐么
