### ISSUE TITLE
更新内置视频播放器的版本

### ISSUE THREAD

**Issue by Deepsea-CN** [alist-org/alist#6489]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

artplayer官方已经更新到5.1.2了，现版本alist内置版本还在5.0.9，希望可以更新到最新版本
之前看到过一个更新播放器的请求，但是后面alist版本实际没有更新成功

**Comment by ghostWindows-files** [comment]
希望能切换播放器，能在dplay和artplayer之间任意切换

**Comment by li-peifeng** [comment]
自己可以打包升级了，不过latest是5.1.1， 5.1.2 还没正式发布

**Comment by li-peifeng** [comment]
docker pull leolitaly/sweet-cloud:latest

此镜像已更新 Artplayer 至 5.1.1
