### ISSUE TITLE
scp 支持多线程（mscp）

### ISSUE THREAD

**Issue by ghost** [alist-org/alist#6494]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

scp 支持多线程（mscp）

### Suggested solution / 实现思路

https://github.com/upa/mscp

**Comment by read8873** [comment]
any chance?

**Comment by aogg** [comment]
麻烦支持下scp    @rayiins
