### ISSUE TITLE
别名驱动无法上传文件

### ISSUE THREAD

**Issue by WhateverMO** [alist-org/alist#6503]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

alias

### Describe the bug / 问题描述

在别名驱动中上传文件失败：
<img width="509" alt="image" src="https://github.com/alist-org/alist/assets/75033001/588be0e8-fdc1-498b-81ac-bdaed4ab26ca">
在原始驱动中是没问题的。
下载，查看，删除，均不受影响。

### Reproduction / 复现链接

---

### Config / 配置

{
  "force": false,
  "site_url": "https://xxx.xxx",
  "cdn": "",
  "jwt_secret": "xxxxxxxx",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": -1,
    "https_port": 65445,
    "force_https": true,
    "cert_file": "/usr/local/cert/xxx.xxx.crt",
    "key_file": "/usr/local/cert/xxx.xxx.key",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}⏎

### Logs / 日志

[GIN] 2024/05/23 - 22:22:59 | 200 |     307.165µs |  222.178.10.197 | POST     "/api/fs/list"
[GIN] 2024/05/23 - 22:25:48 | 200 |     169.984µs |  222.178.10.197 | GET      "/api/me"
[GIN] 2024/05/23 - 22:25:51 | 200 |     131.967µs |  222.178.10.197 | GET      "/api/admin/driver/names"
[GIN] 2024/05/23 - 22:25:51 | 200 |     597.476µs |  222.178.10.197 | GET      "/api/admin/storage/list"
[GIN] 2024/05/23 - 22:25:54 | 200 |     109.172µs |  222.178.10.197 | GET      "/api/me"
[GIN] 2024/05/23 - 22:25:54 | 200 |       48.27µs |  222.178.10.197 | GET      "/api/public/offline_download_tools"
[GIN] 2024/05/23 - 22:25:54 | 200 |     584.466µs |  222.178.10.197 | POST     "/api/fs/list"
ERRO[2024-05-23 22:26:03] failed put /zjj/aliyunpan/: upload not supported
github.com/alist-org/alist/v3/internal/fs.putDirectly
	/home/runner/work/alist/alist/internal/fs/put.go:68
github.com/alist-org/alist/v3/internal/fs.PutDirectly
	/home/runner/work/alist/alist/internal/fs/fs.go:97
github.com/alist-org/alist/v3/server/handles.FsStream
	/home/runner/work/alist/alist/server/handles/fsup.go:65
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.FsUp
	/home/runner/work/alist/alist/server/middlewares/fsup.go:43
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	/home/runner/work/alist/alist/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.21.10/x64/src/net/http/server.go:2938
net/http.initALPNRequest.ServeHTTP
	/opt/hostedtoolcache/go/1.21.10/x64/src/net/http/server.go:3546
net/http.(*http2serverConn).runHandler
	/opt/hostedtoolcache/go/1.21.10/x64/src/net/http/h2_bundle.go:6232
runtime.goexit
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/asm_amd64.s:1650
[GIN] 2024/05/23 - 22:26:03 | 200 |     335.967µs |  222.178.10.197 | PUT      "/api/fs/put"
[GIN] 2024/05/23 - 22:26:04 | 200 |     303.805µs |  222.178.10.197 | POST     "/api/fs/list"

**Comment by anwen-anyi** [comment]
别名不支持上传
