### ISSUE TITLE
115网盘文件重命名无法更改文件后缀名

### ISSUE THREAD

**Issue by dreamoeu** [alist-org/alist#6504]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.34.0

### Driver used / 使用的存储驱动

115

## 将文件后缀名更改为不同后缀名无法生效，只会加一个相同的后缀名，将文件后缀名更改为相同后缀名则可以生效
![Screenshot_2024-05-24-04-52-44-279_com android browser](https://github.com/alist-org/alist/assets/109009825/ff8f6297-a9e7-41cc-a6a2-9b93a0928e4f)
![Screenshot_2024-05-24-04-52-52-135_com android browser](https://github.com/alist-org/alist/assets/109009825/0cb72b73-0493-45d8-8e6f-75468beb28a5)
![Screenshot_2024-05-24-04-53-08-928_com android browser](https://github.com/alist-org/alist/assets/109009825/f131d49d-4193-4c5a-822d-25a40a08bcf1)
![Screenshot_2024-05-24-04-53-21-126_com android browser](https://github.com/alist-org/alist/assets/109009825/e2b1a863-fb7c-43f4-b735-502deb0ed725)

### Reproduction / 复现链接

将115网盘文件重命名

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "aruqn4RHnSzhDEyH",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

**Comment by oditian** [comment]
为什么这个issue被关闭了？确实是无法对扩展名重命名
