### ISSUE TITLE
Every film just can see 60% of time

### ISSUE THREAD

**Issue by chenhy66tw** [alist-org/alist#6505]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

Latest version of alist.exe

### Driver used / 使用的存储驱动

pikpak share

### Describe the bug / 问题描述

Every film just can see 50% of the film time

### Reproduction / 复现链接

play the film to see it just can see only 50% of the file time

### Config / 配置

alist.exe latest to add pikpak share function

### Logs / 日志

maybe the customer id and the customer key cause ths issue happened

**Comment by chenhy66tw** [comment]
pikpak 分享的影片只能撥放50%

**Comment by kiolygenius** [comment]
#6493 同一个问题

**Comment by chenhy66tw** [comment]
用wget 和aria2c下載都只能下載一半的檔案，但是用谷歌商店的 webdav nav lite 沒個這個問題，看來是pikpak 服務器 會限制wget 和aria2c下載檔案的大小，請參考

**Comment by chenhy66tw** [comment]
Sorry,檔案只能下載一半，無解
