### ISSUE TITLE
优化秒传，对于复制过程中无法秒传的项目直接跳过

### ISSUE THREAD

**Issue by JamaisVuu** [alist-org/alist#6512]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

1. 许多人将 alist 部署在带宽较低的主机上。如果某个项目无法秒传，则会采用先下载再上传的方式，这对于带宽较低的主机来说将是一个非常漫长的过程。是否可以提供一个功能，将不能秒传的文件搁置或列出并暂停，然后让其他可以秒传的项目继续进行？
2. 在设置复制进程时，将正在复制的项目排到第一个位置，这样可以优化秒传过程，用户可以更好地判断是否能接受不能秒传的文件。目前的问题是用户需要在众多项目中寻找无法秒传并正在下载的项目。

<img width="263" alt="image" src="https://github.com/alist-org/alist/assets/106464306/8cd2041f-120b-42d6-99fe-e223eb51caa2">

### Suggested solution / 实现思路
增加“跳过不能秒传项目”并列出。
_No response_

**Comment by JamaisVuu** [comment]
已用其他软件秒传完成，alist秒传存在些许问题

**Comment by yonly1314** [comment]
这个优化建议很好，建议打开

**Comment by Jiayou-Chao** [comment]
> 可以搭配rclone 复制 同webdav名称复制，可以秒传，在加个跳过重复文件的参数，可以跳过重复的文件 另外可以用移动云手机，每天一小时，一天可以搬个一两百G非秒传文件(国内盘)

能不能展开说说，云手机怎么搬运？
