### ISSUE TITLE
网易云音乐挂载失败

### ISSUE THREAD

**Issue by ilkeiii** [alist-org/alist#6517]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

网易云音乐

### Describe the bug / 问题描述

![屏幕截图 2024-05-25 134149](https://github.com/alist-org/alist/assets/62320562/cefdbd27-2908-4f13-b482-9f8b3843cbb4)

### Reproduction / 复现链接

如题

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xxx",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": 5245,
    "force_https": false,
    "cert_file": "./data/cert/fullchain1.pem",
    "key_file": "./data/cert/privkey1.pem",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

**Comment by anwen-anyi** [comment]
没问题
![image](https://github.com/alist-org/alist/assets/56105412/24d1e84f-8d20-41b8-88e4-0ad2c1139cad)

挂载方式（文档暂时还未提交）
![image](https://github.com/alist-org/alist/assets/56105412/e417047f-c48f-4dad-b86d-e61e0c449ad3)

**Comment by ilkeiii** [comment]
> 没问题 ![image](https://private-user-images.githubusercontent.com/56105412/333778327-24d1e84f-8d20-41b8-88e4-0ad2c1139cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjQ3NjgsIm5iZiI6MTcxNjYyNDQ2OCwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzMjctMjRkMWU4NGYtOGQyMC00MWI4LTg4ZTQtMGFkMmMxMTM5Y2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MGE2NjYyZDU0ODQ0Y2E4M2JkMDlhNmZjMGE3OWI3YjQxOWUzMzhmYjU0NzRjZDExZWZiY2YwMWE2YzBhZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oS4LrM-WN4hh8I721vwhl0lOhvNDCp-bsLjAYOKXbNU)
> 
> 挂载方式（文档暂时还未提交） ![image](https://private-user-images.githubusercontent.com/56105412/333778385-e417047f-c48f-4dad-b86d-e61e0c449ad3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjQ3NjgsIm5iZiI6MTcxNjYyNDQ2OCwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzODUtZTQxNzA0N2YtYzQ4Zi00ZGFkLWI4NmQtZTYxZTBjNDQ5YWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5OWU0OTdhOGE1YTc5YTBmNDE5NTdlMDRlM2E0MGVmNjFlOWMzYWNlODk1N2Y3ZDNiMTI1NGRkYjk4MzdlOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0jkRtIZa8fUiTnDGbaTEUSFvhCrauOgBdfoTaJjo3JY)

奇怪了，我填的应该没错啊，还是不行
![Uploading 屏幕截图 2024-05-25 160829.png…]()

**Comment by ilkeiii** [comment]
> 没问题 ![image](https://private-user-images.githubusercontent.com/56105412/333778327-24d1e84f-8d20-41b8-88e4-0ad2c1139cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjUyMDEsIm5iZiI6MTcxNjYyNDkwMSwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzMjctMjRkMWU4NGYtOGQyMC00MWI4LTg4ZTQtMGFkMmMxMTM5Y2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NTM2YTIxNzMyZDAwMjU4YjhlYTYwMzMxMDAyM2EyNjdhODQ1OGJkMjdhNDI2ZDcxZTViNTg1ZGJiODI0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lR6GTI2BpZBaVG5DnnZczDgRDJPjUj6LpmjfBGCrx0o)
> 
> 挂载方式（文档暂时还未提交） ![image](https://private-user-images.githubusercontent.com/56105412/333778385-e417047f-c48f-4dad-b86d-e61e0c449ad3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjUyMDEsIm5iZiI6MTcxNjYyNDkwMSwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzODUtZTQxNzA0N2YtYzQ4Zi00ZGFkLWI4NmQtZTYxZTBjNDQ5YWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ODMxYzYyZjVmODYxMDNiNWQyMmI1YmU4NmQ1YTFkZDNjZWE2MDRmYjA4MzE1YzgzYjk5NzMzYTJlYTJmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sf9QCxS05vScsB_cMWjHP9hMEVS0dnX0F8fkLhFu8Js)

刚测试了行了，我云盘里是别人那导入的音乐不行，刚刚手动上传了一首音乐它显示了
![屏幕截图 2024-05-25 161554](https://github.com/alist-org/alist/assets/62320562/02ef8df4-39a5-4132-a093-a026fb6fa044)

**Comment by liuycy** [comment]
> > 没问题 ![image](https://private-user-images.githubusercontent.com/56105412/333778327-24d1e84f-8d20-41b8-88e4-0ad2c1139cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjUyMDEsIm5iZiI6MTcxNjYyNDkwMSwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzMjctMjRkMWU4NGYtOGQyMC00MWI4LTg4ZTQtMGFkMmMxMTM5Y2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NTM2YTIxNzMyZDAwMjU4YjhlYTYwMzMxMDAyM2EyNjdhODQ1OGJkMjdhNDI2ZDcxZTViNTg1ZGJiODI0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lR6GTI2BpZBaVG5DnnZczDgRDJPjUj6LpmjfBGCrx0o)
> > 挂载方式（文档暂时还未提交） ![image](https://private-user-images.githubusercontent.com/56105412/333778385-e417047f-c48f-4dad-b86d-e61e0c449ad3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjUyMDEsIm5iZiI6MTcxNjYyNDkwMSwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzODUtZTQxNzA0N2YtYzQ4Zi00ZGFkLWI4NmQtZTYxZTBjNDQ5YWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ODMxYzYyZjVmODYxMDNiNWQyMmI1YmU4NmQ1YTFkZDNjZWE2MDRmYjA4MzE1YzgzYjk5NzMzYTJlYTJmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sf9QCxS05vScsB_cMWjHP9hMEVS0dnX0F8fkLhFu8Js)
> 
> 刚测试了行了，我云盘里是别人那导入的音乐不行，刚刚手动上传了一首音乐它显示了 ![屏幕截图 2024-05-25 161554](https://private-user-images.githubusercontent.com/62320562/333783079-02ef8df4-39a5-4132-a093-a026fb6fa044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjYyMDIsIm5iZiI6MTcxNjYyNTkwMiwicGF0aCI6Ii82MjMyMDU2Mi8zMzM3ODMwNzktMDJlZjhkZjQtMzlhNS00MTMyLWEwOTMtYTAyNmZiNmZhMDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MzE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzM4ZmE1Zjk2MzFlODA1NzA5MTEzNDAyZDRjNzVhYjM5NDQyZDVmMTg0YTE2ZDBlNjM1Yjc0YWFkYTJjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEOjnUUxUy-AA7M9HmuyVUGdT9pdncPsRPAOyvWoj6U)

不行的这首是非 mp3/flac 格式的文件吗？

**Comment by ilkeiii** [comment]
> > > 没问题 ![image](https://private-user-images.githubusercontent.com/56105412/333778327-24d1e84f-8d20-41b8-88e4-0ad2c1139cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjUyMDEsIm5iZiI6MTcxNjYyNDkwMSwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzMjctMjRkMWU4NGYtOGQyMC00MWI4LTg4ZTQtMGFkMmMxMTM5Y2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NTM2YTIxNzMyZDAwMjU4YjhlYTYwMzMxMDAyM2EyNjdhODQ1OGJkMjdhNDI2ZDcxZTViNTg1ZGJiODI0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lR6GTI2BpZBaVG5DnnZczDgRDJPjUj6LpmjfBGCrx0o)
> > > 挂载方式（文档暂时还未提交） ![image](https://private-user-images.githubusercontent.com/56105412/333778385-e417047f-c48f-4dad-b86d-e61e0c449ad3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjUyMDEsIm5iZiI6MTcxNjYyNDkwMSwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzODUtZTQxNzA0N2YtYzQ4Zi00ZGFkLWI4NmQtZTYxZTBjNDQ5YWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ODMxYzYyZjVmODYxMDNiNWQyMmI1YmU4NmQ1YTFkZDNjZWE2MDRmYjA4MzE1YzgzYjk5NzMzYTJlYTJmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sf9QCxS05vScsB_cMWjHP9hMEVS0dnX0F8fkLhFu8Js)
> > 
> > 
> > 刚测试了行了，我云盘里是别人那导入的音乐不行，刚刚手动上传了一首音乐它显示了 ![屏幕截图 2024-05-25 161554](https://private-user-images.githubusercontent.com/62320562/333783079-02ef8df4-39a5-4132-a093-a026fb6fa044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjYyMDIsIm5iZiI6MTcxNjYyNTkwMiwicGF0aCI6Ii82MjMyMDU2Mi8zMzM3ODMwNzktMDJlZjhkZjQtMzlhNS00MTMyLWEwOTMtYTAyNmZiNmZhMDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MzE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzM4ZmE1Zjk2MzFlODA1NzA5MTEzNDAyZDRjNzVhYjM5NDQyZDVmMTg0YTE2ZDBlNjM1Yjc0YWFkYTJjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEOjnUUxUy-AA7M9HmuyVUGdT9pdncPsRPAOyvWoj6U)
> 
> 不行的这首是非 mp3/flac 格式的文件吗？

是这样的，我之前在拼夕夕买的这种导入到网易云云盘的歌，我不知道原理是什么
![Screenshot_2024-05-25-16-37-54-340_com netease cloudmusic](https://github.com/alist-org/alist/assets/62320562/1e22cbcf-db2a-4ea0-9474-010053da2aff)

**Comment by ilkeiii** [comment]
> > > 没问题 ![image](https://private-user-images.githubusercontent.com/56105412/333778327-24d1e84f-8d20-41b8-88e4-0ad2c1139cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjUyMDEsIm5iZiI6MTcxNjYyNDkwMSwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzMjctMjRkMWU4NGYtOGQyMC00MWI4LTg4ZTQtMGFkMmMxMTM5Y2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NTM2YTIxNzMyZDAwMjU4YjhlYTYwMzMxMDAyM2EyNjdhODQ1OGJkMjdhNDI2ZDcxZTViNTg1ZGJiODI0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lR6GTI2BpZBaVG5DnnZczDgRDJPjUj6LpmjfBGCrx0o)
> > > 挂载方式（文档暂时还未提交） ![image](https://private-user-images.githubusercontent.com/56105412/333778385-e417047f-c48f-4dad-b86d-e61e0c449ad3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjUyMDEsIm5iZiI6MTcxNjYyNDkwMSwicGF0aCI6Ii81NjEwNTQxMi8zMzM3NzgzODUtZTQxNzA0N2YtYzQ4Zi00ZGFkLWI4NmQtZTYxZTBjNDQ5YWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ODMxYzYyZjVmODYxMDNiNWQyMmI1YmU4NmQ1YTFkZDNjZWE2MDRmYjA4MzE1YzgzYjk5NzMzYTJlYTJmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sf9QCxS05vScsB_cMWjHP9hMEVS0dnX0F8fkLhFu8Js)
> > 
> > 
> > 刚测试了行了，我云盘里是别人那导入的音乐不行，刚刚手动上传了一首音乐它显示了 ![屏幕截图 2024-05-25 161554](https://private-user-images.githubusercontent.com/62320562/333783079-02ef8df4-39a5-4132-a093-a026fb6fa044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjYyMDIsIm5iZiI6MTcxNjYyNTkwMiwicGF0aCI6Ii82MjMyMDU2Mi8zMzM3ODMwNzktMDJlZjhkZjQtMzlhNS00MTMyLWEwOTMtYTAyNmZiNmZhMDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MzE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzM4ZmE1Zjk2MzFlODA1NzA5MTEzNDAyZDRjNzVhYjM5NDQyZDVmMTg0YTE2ZDBlNjM1Yjc0YWFkYTJjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QEOjnUUxUy-AA7M9HmuyVUGdT9pdncPsRPAOyvWoj6U)
> 
> 不行的这首是非 mp3/flac 格式的文件吗？

这样的
![Screenshot_2024-05-25-16-41-52-816_com xunmeng pinduoduo](https://github.com/alist-org/alist/assets/62320562/1e23df2a-5df1-4cc7-954e-501ef49e9cdf)
