### ISSUE TITLE
蓝奏云优享版failed link: failed get link: redirect failed, content: {"msg":"该IP已被锁定，请联系客服","code":-1}

### ISSUE THREAD

**Issue by songqingawa** [alist-org/alist#6519]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

编译最新开发版v1.53.10

### Driver used / 使用的存储驱动

蓝奏云优享版

### Describe the bug / 问题描述

failed link: failed get link: redirect failed, content: {"msg":"该IP已被锁定，请联系客服","code":-1}

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/76278016/49664b11-7d15-43ea-bf16-61cdb2526ec5)

### Config / 配置

无

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/76278016/d440af2f-25f0-45a1-b3f1-0bc58c2a34f8)

**Comment by xhofe** [comment]
#6673
