### ISSUE TITLE
蓝光mkv中的字幕无法显示

### ISSUE THREAD

**Issue by womengnan** [alist-org/alist#6522]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.55

### Driver used / 使用的存储驱动

aliyun

### Describe the bug / 问题描述

蓝光mkv中的字幕无法显示

### Reproduction / 复现链接

[蓝光mkv中的字幕无法显示](http://127.0.0.1:520/meiju/S01E01.2018.1080p.WEB-DL.x265.AC3%EF%BF%A1.mkv)

### Config / 配置

 "id": 1,
      "mount_path": "/阿里1",
      "order": 0,
      "driver": "AliyundriveOpen",
      "cache_expiration": 30,
      "status": "work",
      "addition": "{\"drive_type\":\"backup\",\"root_folder_id\":\"root\",\"refresh_token\":\"xx\",\"order_by\":\"name\",\"order_direction\":\"ASC\",\"oauth_token_url\":\"https://api.xhofe.top/alist/ali_open/token\",\"client_id\":\"\",\"client_secret\":\"\",\"remove_way\":\"trash\",\"rapid_upload\":false,\"internal_upload\":false,\"livp_download_format\":\"jpeg\",\"AccessToken\":\"xx\"}",
      "remark": "阿里1",
      "modified": "2024-04-26T23:23:00.0252825+08:00",
      "disabled": false,
      "enable_sign": false,
      "order_by": "",
      "order_direction": "",
      "extract_folder": "",
      "web_proxy": false,
      "webdav_policy": "302_redirect",
      "down_proxy_url": ""

**Comment by Deepsea-CN** [comment]
mkv很多内封字幕都识别不出来，用下面的链接转到vlc，potplayer等等专业播放器即可选择
