### ISSUE TITLE
登陆错误次数检查严重阻碍基于api的开发

### ISSUE THREAD

**Issue by panderman** [alist-org/alist#6524]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.29.1

### Driver used / 使用的存储驱动

不限

### Describe the bug / 问题描述

由于项目需要很频繁的调用alist相关api进行刷新下载链接的操作，实际开发中发现经常报：
Too many unsuccessful sign-in attempts havade using an incorrect username or password, Try again later.

检查源码发现此异常存在在于：
alist/server/handles/auth.go，第55行
alist/server/handles/ldap_login.go，第41行

**跟踪发现defaultTimes于代码中写死，此判断应该去除，抛出异常由开发者自行判断如何操作，或者把defaultTimes纳入到config.json配置，现在的代码直接把路堵死了**

![WX20240526-092738@2x](https://github.com/alist-org/alist/assets/2589642/abbd88a9-c03a-4778-b970-3fb5184997d4)

### Reproduction / 复现链接

无

### Config / 配置

无

### Logs / 日志

无

**Comment by li-peifeng** [comment]
你自己编译一下就好了

**Comment by panderman** [comment]
> 你自己编译一下就好了

我现在是自己编译的，但是官方能修改这部分是最好的，源码本身这块是存在问题的

**Comment by anwen-anyi** [comment]
如果是自己调试，自己知道账号密码 怎么会遇到账号密码错误呢 :joy_cat:

**Comment by panderman** [comment]
> 如果是自己调试，自己知道账号密码 怎么会遇到账号密码错误呢 :joy_cat: 

我项目中试过缓存token和每次请求都获取新token，长时间运行就会报这个错，重启alist又可以，跟踪才发现代码的这个问题

**Comment by panderman** [comment]
> 如果是自己调试，自己知道账号密码 怎么会遇到账号密码错误呢 :joy_cat: 

把那段判断代码删掉，自己编译连续运行2天未出问题，可以确定那段代码逻辑存在问题

**Comment by anwen-anyi** [comment]
我有个小脚本用了几个月了暂时没遇到过这个问题~ :joy_cat:

**Comment by panderman** [comment]
> 我有个小脚本用了几个月了暂时没遇到过这个问题~ 😹

我每隔一秒遍历所有链接，可能场景不一样

**Comment by anwen-anyi** [comment]
> > 我有个小脚本用了几个月了暂时没遇到过这个问题~ 😹
> 
> 我每隔一秒遍历所有链接，可能场景不一样

这需要有点儿离谱哈哈，不过没必要一直用账号密码获取 token，可以用已经获取到未失效的token继续使用吖

**Comment by panderman** [comment]
> > > 我有个小脚本用了几个月了暂时没遇到过这个问题~ 😹
> > 
> > 
> > 我每隔一秒遍历所有链接，可能场景不一样
> 
> 这需要有点儿离谱哈哈，不过没必要一直用账号密码获取 token，可以用已经获取到未失效的token继续使用吖

试过的，用缓存token，一样报错，删掉那段代码目前连续运行3天没出问题

**Comment by j2rong4cn** [comment]
> > > > 我有个小脚本用了几个月了暂时没遇到过这个问题~ 😹
> > > 
> > > 
> > > 我每隔一秒遍历所有链接，可能场景不一样
> > 
> > 
> > 这需要有点儿离谱哈哈，不过没必要一直用账号密码获取 token，可以用已经获取到未失效的token继续使用吖
> 
> 试过的，用缓存token，一样报错，删掉那段代码目前连续运行3天没出问题

管理-设置-其他-令牌 ，这个永不过期

**Comment by panderman** [comment]
这不是token的问题，是alist检查错误次数机制的问题

**Comment by j2rong4cn** [comment]
> 这不是token的问题，是alist检查错误次数机制的问题

错误次数检测是为了账号安全，你用我说的那个令牌不用登录就可以访问api，不登录就不会有限制
