### ISSUE TITLE
Pikpak: 403 Forbidden

### ISSUE THREAD

**Issue by DarremMolko** [alist-org/alist#6527]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

Pikpak

### Describe the bug / 问题描述

When trying to download a file from Pikpak using wget I receive 403 Forbidden error.

### Reproduction / 复现链接

[Darrem@]:<~>$ wget "https://domain.ltd/d/path/pikpak/file.mkv"
--2024-05-26 11:08:16--  https://domain.ltd/pikpak/file.mkv
Resolving domain.ltd (domain.ltd)... 0.0.0.0, 0.0.0.0, 0.0.0.0, ...
Connecting to domain.ltd (domain.ltd)|0.0.0.0|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl-a10b-1191.mypikpak.com/download/?fid=REDACTED[following]
--2024-05-26 11:08:17--  https://dl-a10b-1191.mypikpak.com/download/?fid=REDACTED
Resolving dl-a10b-1191.mypikpak.com (dl-a10b-1191.mypikpak.com)... 47.79.0.89, 47.79.2.251, 47.79.1.71
Connecting to dl-a10b-1191.mypikpak.com (dl-a10b-1191.mypikpak.com)|47.79.0.89|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-05-26 11:08:18 ERROR 403: Forbidden.

### Config / 配置

Default config, no changes have been made.

### Logs / 日志

[31mERRO[0m[2024-05-26 11:00:51] failed link /path/pikpak: not a file
github.com/alist-org/alist/v3/internal/op.Link
	/home/runner/work/alist/alist/internal/op/fs.go:253
github.com/alist-org/alist/v3/internal/fs.link
	/home/runner/work/alist/alist/internal/fs/link.go:19
github.com/alist-org/alist/v3/internal/fs.Link
	/home/runner/work/alist/alist/internal/fs/fs.go:48
github.com/alist-org/alist/v3/server/handles.Down
	/home/runner/work/alist/alist/server/handles/down.go:33
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Down
	/home/runner/work/alist/alist/server/middlewares/down.go:40
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.22.3/x64/src/net/http/server.go:3137
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.22.3/x64/src/net/http/server.go:2039
runtime.goexit
	/opt/hostedtoolcache/go/1.22.3/x64/src/runtime/asm_amd64.s:1695
failed link

**Comment by DarremMolko** [comment]
> 开web代理 本地代理

It used to work without the native proxy, does it means that the 302 redirect no longer works? I'd like to avoid using my server bandwidth.

**Comment by wuyu8512** [comment]
api和下载如果ip不一样也可能出这个问题

**Comment by DarremMolko** [comment]
I didn't know the API is now linked to the IP. Thank you, I guess there's nothing we can do so I'll close the issue.

**Comment by li-peifeng** [comment]
开web代理， IP一样的话播放下载没问题
