### ISSUE TITLE
PikPak无法挂载到alist

### ISSUE THREAD

**Issue by haoxiaoyueh** [alist-org/alist#6534]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

PikPak

### Describe the bug / 问题描述

在我试图按照教程将PikPak挂载到alist的时候
![image](https://github.com/alist-org/alist/assets/113106402/20973e97-88f0-4dee-ba5c-855fc257efcc)
它并没有成功，反而是这个状态
![image](https://github.com/alist-org/alist/assets/113106402/9e3c9735-22bd-4ce2-b7e5-120413ce818f)
并且我的网络问题并没有问题，普通打开pikpak是可以做到的
![image](https://github.com/alist-org/alist/assets/113106402/71306510-6272-4380-8080-dd8a700fdc69)
我在设置里也将web代理打开了
![image](https://github.com/alist-org/alist/assets/113106402/cf6b3b8e-09a7-426e-9c2b-c33b5ced043c)
但是仍然失败了。

### Reproduction / 复现链接

https://mypikpak.com/
https://user.mypikpak.com/v1/auth/token

### Config / 配置

![image](https://github.com/alist-org/alist/assets/113106402/c05a69f6-8fab-4eb9-9333-abd88dd0c39d)

### Logs / 日志

[31mERRO[0m[2024-05-28 09:24:51] failed init storage but storage is already created: failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6214->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:24:51 | 200 |    424.6709ms |       127.0.0.1 | POST     "/api/admin/storage/create"
[GIN] 2024/05/28 - 09:24:51 | 200 |       444.3µs |       127.0.0.1 | GET      "/api/admin/storage/get?id=3"
[GIN] 2024/05/28 - 09:24:51 | 200 |       910.6µs |       127.0.0.1 | GET      "/api/admin/driver/info?driver=PikPak"
[31mERRO[0m[2024-05-28 09:25:25] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6237->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:25:25 | 200 |    347.3196ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:25:57] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6291->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:25:57 | 200 |    1.3629649s |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:26:25] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6316->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:26:25 | 200 |     338.484ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:26:27] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6318->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:26:27 | 200 |    335.3655ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:26:28] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6320->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:26:28 | 200 |    336.9781ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:26:30] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6321->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:26:30 | 200 |    334.5009ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:27:37] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6376->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:27:37 | 200 |    353.0462ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:27:38] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6378->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:27:38 | 200 |     336.923ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:28:32] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6417->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:28:32 | 200 |    381.0456ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:29:28] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6459->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:29:28 | 200 |    351.8397ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:29:36] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6468->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:29:36 | 200 |    348.7671ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:29:37] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6470->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:29:37 | 200 |    337.1309ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:29:39] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6471->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:29:39 | 200 |    340.8113ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[GIN] 2024/05/28 - 09:32:57 | 207 |            0s |       127.0.0.1 | PROPFIND  "/dav/CMCC/"
[31mERRO[0m[2024-05-28 09:34:43] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6952->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host. 
[GIN] 2024/05/28 - 09:34:43 | 200 |    372.8929ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[31mERRO[0m[2024-05-28 09:34:50] failed init storage: Post "https://user.mypikpak.com/v1/auth/token": read tcp 172.17.17.74:6955->8.219.103.183:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by haoxiaoyueh** [comment]
是否是获取token的网址失效的原因？我在直接访问这个网址的时候也有
![image](https://github.com/alist-org/alist/assets/113106402/7b9c4fae-d536-49a5-8c10-b0b58e771952)
而且这个网址是ping不通的，是否已经失效了？
![image](https://github.com/alist-org/alist/assets/113106402/a9c19a51-1a84-4034-8189-8536b14d0527)

**Comment by haoxiaoyueh** [comment]
> 给alist挂代理

挂上了，用的这个教程：https://github.com/alist-org/alist/discussions/4363
但是虽然显示有连接，但实际上是搜索不到文件
![image](https://github.com/alist-org/alist/assets/113106402/6253823a-e8e3-4c01-a2d0-587933367a13)
![image](https://github.com/alist-org/alist/assets/113106402/af935e46-0532-489e-b74f-952696bfe7a3)

**Comment by Deepsea-CN** [comment]
我用的海外服务器挂载没有问题，你开web代理的话也需要你的alist机器有访问外网的能力

**Comment by suntao12138** [comment]
现在不是墙和梯子的问题是鉴权页面换了

**Comment by suntao12138** [comment]
> 给alist挂代理

就不是代理的事情，有些地方不限制也不能挂载
