### ISSUE TITLE
如何配置多管理员

### ISSUE THREAD

**Issue by charliez0** [alist-org/alist#6539]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

配置多个能管理的管理员

**Comment by Seele0oO** [comment]
尝试了一下，貌似不行。
使用api设置，提示不能创建管理员用户。
尝试修改sqlite文件，也不行。
可能设计上就不让多管理员。

**Comment by huolanyun** [comment]
新建用户，权限全给，不就是管理员？

**Comment by anwen-anyi** [comment]
没记错的话应该只能通过修改数据库来操作

**Comment by Seele0oO** [comment]
```sql
CREATE TRIGGER change_role_if_zero
AFTER INSERT ON x_users
FOR EACH ROW
WHEN NEW.role = 0
BEGIN
    UPDATE x_users
    SET role = 2
    WHERE id = NEW.id;
END;
```
这样就能保证每个新用户都是管理员了。
可惜alist默认并不带sqlite3软件，不能直接在docker启动顺便执行一下。

**Comment by charliez0** [comment]
.
