### ISSUE TITLE
pikpak分享报错，点击重新加载之后又能恢复正常，过一段时间之后还是会报错

### ISSUE THREAD

**Issue by dddd64693** [alist-org/alist#6544]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v.3.35.0

### Driver used / 使用的存储驱动

pikpak分享

### Describe the bug / 问题描述

pikpak分享报错，点击重新加载之后又能恢复正常,i过一段时间之后还是会报错
![image](https://github.com/alist-org/alist/assets/14047878/9e6682a1-2b69-411c-a844-4e44f0862381)
![image](https://github.com/alist-org/alist/assets/14047878/0a8cefa2-cc2d-4040-8a78-8c07ca4476af)

### Reproduction / 复现链接

http://alist.sdtec.top/@manage/storages

### Config / 配置

![image](https://github.com/alist-org/alist/assets/14047878/35af19d1-bce3-4dd1-8751-47fcf8c5fb37)
![image](https://github.com/alist-org/alist/assets/14047878/6c8959f9-45df-479e-9e78-c4069dd37054)

**Comment by Three-taile-dragon** [comment]
请看： #6511

**Comment by 907739769** [comment]
一样的问题
