### ISSUE TITLE
139云盘的根文件夹id参数不生效

### ISSUE THREAD

**Issue by so1ve** [alist-org/alist#6547]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

139

### Describe the bug / 问题描述

在挂载139云盘时，无论设置什么根文件夹id都只会显示设置为root的目录结构

### Reproduction / 复现链接

本地挂载

### Config / 配置

![Screenshot_20240529-234200](https://github.com/alist-org/alist/assets/58381667/a981e52b-b4f9-4ba9-b4b0-3765ff872cbf)
![Screenshot_20240529-233930](https://github.com/alist-org/alist/assets/58381667/5d3039e7-6f16-4180-9fd7-8cae8157ee2a)

**Comment by so1ve** [comment]
退出再登录正常了 离谱。。

**Comment by anwen-anyi** [comment]
不用退出 刷新就好
![image](https://github.com/alist-org/alist/assets/56105412/b7a2e8be-7c56-4549-a285-953cce058527)

**Comment by so1ve** [comment]
Thx
