### ISSUE TITLE
能否支持 OAuth 2.0 + PKCE 方式

### ISSUE THREAD

**Issue by qy527145** [alist-org/alist#6549]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我想搭个alist服务用于多账户聚合（大概30多个号）
但是我注意到refresh_token换access_token的接口针对ip有限制调用频率
alist能否在开放平台配置一下支持[PKCE](https://www.yuque.com/aliyundrive/zpfszx/eam8ls1lmawwwksv)的方式，这样可以自己请求阿里云盘的token刷新接口

**Comment by qy527145** [comment]
有部分账号在换access_token时429了
![image](https://github.com/alist-org/alist/assets/39358262/01f913d4-c114-47d8-be95-28298b0901e5)

**Comment by anwen-anyi** [comment]
..... 你这是薅羊毛大户吧

**Comment by xhofe** [comment]
添加存储时填上自己的client 清空Oauth令牌链接就行

**Comment by qy527145** [comment]
> 添加存储时填上自己的client 清空Oauth令牌链接就行

这个需要自己申请阿里云盘Open 客户端吧
我还有个办法绕过接口频率限制，就是用一个代理池中转`https://api.nn.ci/alist/ali_open/token`接口

**Comment by qy527145** [comment]
> https://github.com/520yxl/Aliyundrive_Refresh_Token_php

这个其实还是得知道client_secret

**Comment by qy527145** [comment]
> ..... 你这是薅羊毛大户吧 😹

才30个号，小户小户[doge]

**Comment by qy527145** [comment]
能否把`https://api.nn.ci/alist/ali_open/token`接口的频率限制调大一些，比如30次/2小时，因为access_token的过期时间也是2个小时，这样应该更合理一些

**Comment by anwen-anyi** [comment]
> > ..... 你这是薅羊毛大户吧 😹
> 
> 才30个号，小户小户[doge]

属于灰/黑产用途了~ 哈哈 :joy_cat:

**Comment by qy527145** [comment]
已解决，不小心绕过了请求频率限制
