### ISSUE TITLE
别名能否增加上传移动删除功能

### ISSUE THREAD

**Issue by ww198610** [alist-org/alist#6551]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

为了解决一个用户操作多个文件夹

我目前的做法，同一个存储，添加多次，第一个挂载给user1,第二个挂载给user2
再分别针对user1和user2 去配置无信息   

因为别名，无法上传文件

**Comment by anwen-anyi** [comment]
还是不推荐在别名进行移动上传操作，别名显示的不光只是一个目录的文件他也不知道上传到哪儿
- 删除已经有了

**Comment by ww198610** [comment]
收到，感谢你的回复
因为别名可以用作分享，按理说，只有只读功能才行，我看最新版本增加了重命名和删除，相当于已经作了改变，是会影响原路径，既然已经开放了，就多开放点
是否可以把权限放在创建别名的时候，让管理员，自己选择，当然只是建议
