### ISSUE TITLE
百度网盘 webDAV播放视频 提示403 Forbidden

### ISSUE THREAD

**Issue by chenchenfang** [alist-org/alist#6554]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

通过quanx的抓包情况来看
首先访问我的服务器的url:http://IP:5244/dav/%E7%99%BE%E5%BA%A6/%E3%80%90%E8%BF%AA%E5%A3%AB%E5%B0%BC%E7%89%88%E3%80%91S02.2024.1080p.DSNP.WEB-DL.H264.AAC-ADWeb/S02E08.2024.1080p.DSNP.WEB-DL.H264.AAC-ADWeb.mkv

然后response:是302到http://nd6.baidupcs.com/file/9a4ae57b8h75a3c8b0bc0b1ff05771b1?bkt=en-06f5c65000af0ed63082adcf0e4f800741700b10036311aff978e144f98de9b28387bbc1d96f7161&xcode=0e075748384c4c17eb81e1b158ef55d4078420e671710e9a49032c9f84455fec572c25cf63e9a258226aaf4bac39de110b2977702d3e6764&fid=2570864441-250528-1001305326265528&time=1717061673&sign=FDTAXUbGERQlBHSKfaqi-DCb740ccc5511e5e8fedcff06b081203-Lh0DYQKAwiZVw1wKr%2BOT8XfP%2FEc%3D&to=nd6&size=2332524122&sta_dx=2332524122&sta_cs=5618&sta_ft=mkv&sta_ct=3&sta_mt=1&fm2=MH%2CXian%2CAnywhere%2C%2CNone%2Cany&ctime=1716032812&mtime=1716956440&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=2332524122&vuk=2570864441&iv=2&vl=3&htype=&randtype=&tkbind_id=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-cd80b4575a2b018f33f23384d884521292d90583bd5721a0568d6065da985159fcef851117e622eb&expires=8h&rt=pr&r=277870482&vbdid=2426926586&fin=S02E08.2024.1080p.DSNP.WEB-DL.H264.AAC-ADWeb.mkv&rtype=1&dp-logid=1964906133449415100&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=KRLKcxkJX%2B5WrjEY6y5%2Fl7sjzwo%3D&so=1&ut=1&uter=0&serv=1&uc=1559654663&ti=068bcab50ae430c71405ef42625f5414d5d5fcbb8f44d4b0&hflag=10&from_type=3&adg=a_1fd091a9bb61d4b3658da6943cf47571&reqlabel=25571201_f_b62baffe7e7722cce4c2c2661e913bd7_-1_82c5734cd0c1bc3a261ca8375b1fbe88&fpath=%E5%BD%B1%E8%A7%86%2F%E3%80%90%E8%BF%AA%E5%A3%AB%E5%B0%BC%E7%89%88%E3%80%91S02.2024.1080p.DSNP.WEB-DL.H264.AAC-ADWeb&by=themis

然后访问这个url的response header是:
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Thu, 30 May 2024 09:34:33 GMT
Content-Type: text/html
Connection: close
Location: http://110.53.110.36/b/nd6.baidupcs.com/file/9a4ae57b8h75a3c8b0bc0b1ff05771b1?bkt=en-06f5c65000af0ed63082adcf0e4f800741700b10036311aff978e144f98de9b28387bbc1d96f7161&xcode=0e075748384c4c17eb81e1b158ef55d4078420e671710e9a49032c9f84455fec572c25cf63e9a258226aaf4bac39de110b2977702d3e6764&fid=2570864441-250528-1001305326265528&time=1717061673&sign=FDTAXUbGERQlBHSKfaqi-DCb740ccc5511e5e8fedcff06b081203-Lh0DYQKAwiZVw1wKr%2BOT8XfP%2FEc%3D&to=nd6&size=2332524122&sta_dx=2332524122&sta_cs=5618&sta_ft=mkv&sta_ct=3&sta_mt=1&fm2=MH%2CXian%2CAnywhere%2C%2CNone%2Cany&ctime=1716032812&mtime=1716956440&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=2332524122&vuk=2570864441&iv=2&vl=3&htype=&randtype=&tkbind_id=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-cd80b4575a2b018f33f23384d884521292d90583bd5721a0568d6065da985159fcef851117e622eb&expires=8h&rt=pr&r=277870482&vbdid=2426926586&fin=S02E08.2024.1080p.DSNP.WEB-DL.H264.AAC-ADWeb.mkv&rtype=1&dp-logid=1964906133449415100&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=KRLKcxkJX%2B5WrjEY6y5%2Fl7sjzwo%3D&so=1&ut=1&uter=0&serv=1&uc=1559654663&ti=068bcab50ae430c71405ef42625f5414d5d5fcbb8f44d4b0&hflag=10&from_type=3&adg=a_1fd091a9bb61d4b3658da6943cf47571&reqlabel=25571201_f_b62baffe7e7722cce4c2c2661e913bd7_-1_82c5734cd0c1bc3a261ca8375b1fbe88&fpath=%E5%BD%B1%E8%A7%86%2F%E3%80%90%E8%BF%AA%E5%A3%AB%E5%B0%BC%E7%89%88%E3%80%91S02.2024.1080p.DSNP.WEB-DL.H264.AAC-ADWeb&by=themis
content-length: 0
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS,HEAD

在访问这个url返回的response header就是:
HTTP/1.1 302 Moved Temporarily
Server: JSP3/2.0.14
Date: Thu, 30 May 2024 09:34:34 GMT
Content-Type: text/html
Content-Length: 152
Connection: keep-alive
pcs-check: 1
pcs-check-status: 403
pcs-check-code: 111
X-Cache-Status: MISS
Location: http://www.baidupcs.com/403.html
X-Error-Info: site.netdisk.xcode.access
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Range, Origin, Content-Type, Accept, Content-Length
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS, HEAD
Access-Control-Expose-Headers: Content-Length, ETag, x-bs-request-id, x-pcs-request-id
Access-Control-Allow-Origin: *

以下是我的配置:
<img width="498" alt="image" src="https://github.com/alist-org/alist/assets/50065243/e39e7532-b2de-4381-a518-7ae23f34b99d">
<img width="716" alt="image" src="https://github.com/alist-org/alist/assets/50065243/174ff40f-74f6-4fd4-8722-91b99667ddb7">

我的账号是超级会员,列表是可以读取出来,
发现不能播放之后,我试了一下curl + ua 下载文件,是可以下载文件的,并且下载速度很快
刚开始还能看,突然有一天晚上看了一个视频再看下一个就不行了

### Reproduction / 复现链接

无

### Config / 配置

无

### Logs / 日志

无

**Comment by anwen-anyi** [comment]
应该是正常情况? 
根据提供的配置图片 首先百度使用302+官方api是得修改UA头才能使用的 
然后因为Webdav无法修改 固根据你提供的配置截图无法播放是正常情况

如果想用Webdav播放试试非官方接口 倒是仅能播放一些视频 倒是不一定都能用, 不100%办证可用性，或者使用官方api然后开启代理模式

**Comment by chenchenfang** [comment]
> 应该是正常情况? 根据提供的配置图片 首先百度使用302+官方api是得修改UA头才能使用的 然后因为Webdav无法修改 固根据你提供的配置截图无法播放是正常情况
> 
> 如果想用Webdav播放试试非官方接口 倒是仅能播放一些视频 倒是不一定都能用, 不100%办证可用性，或者使用官方api然后开启代理模式


我看看官方文档里,是这么描述的,webdav如何修改ua呢?  添加存储的配置里不可以实现是么? 我看配置里有一个填ua的地方
不想用代理...那不得多花服务器的流量么
<img width="879" alt="image" src="https://github.com/alist-org/alist/assets/50065243/bc8176ae-3973-4c7c-be0f-a2ec3cf4598d">

**Comment by anwen-anyi** [comment]
> > 应该是正常情况? 根据提供的配置图片 首先百度使用302+官方api是得修改UA头才能使用的 然后因为Webdav无法修改 固根据你提供的配置截图无法播放是正常情况
> > 如果想用Webdav播放试试非官方接口 倒是仅能播放一些视频 倒是不一定都能用, 不100%办证可用性，或者使用官方api然后开启代理模式
> 
> 我看看官方文档里,是这么描述的,webdav如何修改ua呢? 添加存储的配置里不可以实现是么? 我看配置里有一个填ua的地方 不想用代理...那不得多花服务器的流量么 <img alt="image" width="879" src="https://private-user-images.githubusercontent.com/50065243/335476231-bc8176ae-3973-4c7c-be0f-a2ec3cf4598d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDA2NjIsIm5iZiI6MTcxNzE0MDM2MiwicGF0aCI6Ii81MDA2NTI0My8zMzU0NzYyMzEtYmM4MTc2YWUtMzk3My00YzdjLWJlMGYtYTJlYzNjZjQ1OThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA3MjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYWM3MWQ2M2NhMDgwNzFhNGU5NjkwOTQwZjBjZTVlNDE0MmE0ZDk1OGY0MzI4MWYzNzJlMjc3YTg0Njc0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.53KrjY0II9ZbQTB0AihQZdJ4vABg12n4Ftri9BIDMBY">

这是根据网页端的，WebDav没办法改，可能这个图理解不同误会了，后面改一下，不想用代理也没办法了

- 配置里有一个填ua的地方：这个文档有解释

**Comment by chenchenfang** [comment]
> > > 应该是正常情况? 根据提供的配置图片 首先百度使用302+官方api是得修改UA头才能使用的 然后因为Webdav无法修改 固根据你提供的配置截图无法播放是正常情况
> > > 如果想用Webdav播放试试非官方接口 倒是仅能播放一些视频 倒是不一定都能用, 不100%办证可用性，或者使用官方api然后开启代理模式
> > 
> > 
> > 我看看官方文档里,是这么描述的,webdav如何修改ua呢? 添加存储的配置里不可以实现是么? 我看配置里有一个填ua的地方 不想用代理...那不得多花服务器的流量么
> 
> 这是根据网页端的，WebDav没办法改，可能这个图理解不同误会了，后面改一下，不想用代理也没办法了暂时
> 
> * 配置里有一个填ua的地方：这个文档有解释

好的 感谢!
