### ISSUE TITLE
网易云出现mixed content / Mixed content issue with Netease(163music) driver

### ISSUE THREAD

**Issue by axyn45** [alist-org/alist#6556]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

网易云音乐云盘

### Describe the bug / 问题描述

网易云驱动加载的歌曲和歌词链接为http协议，在部署证书的网站上会出现mixed content错误导致歌词无法正常加载。
![image](https://github.com/alist-org/alist/assets/73621356/6eafc2cd-b0e6-45e8-8fec-2dfc7fecedbb)
建议增加对用户当前协议的识别并替换歌曲资源链接中的scheme

### Reproduction / 复现链接

https://drive.okkk.cc/netease/%E9%AB%98%E6%9D%89%E3%81%95%E3%81%A8%E7%BE%8E%20-%20%E7%99%BE%E6%81%8B%E6%AD%8C.flac

### Config / 配置

![image](https://github.com/alist-org/alist/assets/73621356/23403316-b077-4965-9b60-da7f3c00a49c)

**Comment by liuycy** [comment]
歌词地址 host 是用 [GetApiUrl](https://github.com/alist-org/alist/blob/main/server/common/base.go#L12) 拼接的，默认配置的话走 http_port 的话是返回 http 的，试试 [配置文件](https://alist.nn.ci/zh/config/configuration.html) 里 scheme 设置一下 https 相关字段，修改端口转发到 https 端口看看能不能行？

<img width="950" alt="image" src="https://github.com/alist-org/alist/assets/55272688/4c55c6e2-4c5d-43af-a028-5fd98f65489e">

**Comment by axyn45** [comment]
> 歌词地址 host 是用 [GetApiUrl](https://github.com/alist-org/alist/blob/main/server/common/base.go#L12) 拼接的，默认配置的话走 http_port 的话是返回 http 的，试试 [配置文件](https://alist.nn.ci/zh/config/configuration.html) 里 scheme 设置一下 https 相关字段，修改端口转发到 https 端口看看能不能行？


”我用了反向代理，证书不是直接配置在alist里。希望能通过识别x-forwarded-proto这样的头部来判断当前用户是否为https连接， #6559 似乎就是这样解决的。“

原本是想这么说的，但是刚刚发现我的cdn回源时没有配置x-forwarded-proto导致了alist没能正确识别协议。现在添加了响应头后问题解决了。所以似乎 #6559 并没有解决问题，因为GetApiUrl中自带对X-Forwarded-Proto的识别。
