### ISSUE TITLE
视频播放增加复制按钮

### ISSUE THREAD

**Issue by aohanhongzhi** [alist-org/alist#6565]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

增加复制按钮，复制视频链接

### Additional context / 附件

<img width="1728" alt="image" src="https://github.com/alist-org/alist/assets/37319319/4f676f0d-8627-4886-98ca-ad0315890ba4">

**Comment by ghostWindows-files** [comment]
在播放器上右键选择视频信息就有链接显示,点一下会自动全选然后右键复制就好了

**Comment by aohanhongzhi** [comment]
> 在播放器上右键选择视频信息就有链接显示,点一下会自动全选然后右键复制就好了

貌似不是同一个链接。

<img width="810" alt="image" src="https://github.com/alist-org/alist/assets/37319319/a9f23094-4442-4422-968a-7db52b7404e2">

**Comment by li-peifeng** [comment]
视频上面下拉菜单不就有下载么？

**Comment by li-peifeng** [comment]
> > 视频上面下拉菜单不就有下载么？
> 
> 不是下载，是用软件在线播放

默认的播放器没有你要的么？

**Comment by aohanhongzhi** [comment]
> > > 视频上面下拉菜单不就有下载么？
> > 
> > 
> > 不是下载，是用软件在线播放
> 
> 默认的播放器没有你要的么？

linux不能直接打开vlc，所以只能复制。
