### ISSUE TITLE
alist有定时同步文件到网盘的功能吗?

### ISSUE THREAD

**Issue by hudingwen** [alist-org/alist#6569]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

类似这种,把服务器上某个文件夹的内容,实时同步到阿里云盘或者百度网盘
https://github.com/tickstep/aliyunpan

### Suggested solution / 实现思路

我都是在docker下进行的
比如给alist映射一个同步文件夹目录,这样docker版本的alist就可以上传同步文件到指定的网盘上去

**Comment by hudingwen** [comment]
> ### See
> 1. 50% [alist有没有文件分享功能啊？ #5812](https://github.com/alist-org/alist/issues/5812)

不是分享功能,是同步服务器上某个文件夹里面的文件到云盘

**Comment by hudingwen** [comment]
暂时用了上面提到的同步库,不影响日常使用,只是习惯用alist,想着看看有没有可能集成在一起

**Comment by xrgzs** [comment]
有个第三方 alist webdav + rclone 的整合客户端的实现：https://github.com/VirtualHotBar/NetMount/

![](https://github.com/alist-org/alist/assets/26499123/4b87f59a-5bb6-4ede-b5fd-ce2045413c20)

**Comment by woshichenghaibo** [comment]
> 有个第三方 alist webdav + rclone 的整合客户端的实现：https://github.com/VirtualHotBar/NetMount/
> 
> ![](https://private-user-images.githubusercontent.com/26499123/343034593-4b87f59a-5bb6-4ede-b5fd-ce2045413c20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MzYzMjksIm5iZiI6MTcyMTQzNjAyOSwicGF0aCI6Ii8yNjQ5OTEyMy8zNDMwMzQ1OTMtNGI4N2Y1OWEtNWJiNi00ZWRlLWI1ZmQtY2UyMDQ1NDEzYzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDAwNDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2Yjg3NmNhMzgxNjNhNDkyNmRjYzIyYjg4YWM1YjA5ZTNiNjA0ZTU2NmExNmVmYjY4OTQzYTZlMjViZDY1YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oKZEV3H86FuQMOmbHeVd-W6D4vxAPlctnYfz0Gig7NA)

可以用，稍微麻烦点
