### ISSUE TITLE
增加夸克分享驱动，通过转存到用户夸克盘播放

### ISSUE THREAD

**Issue by xiaoyaliu00** [alist-org/alist#6571]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

夸克现在没有分享驱动，而夸克的分享资源挺多，能不能迂回的通过转存来实现分享的播放下载

### Suggested solution / 实现思路

可以转存到自己夸克盘，获取新fid再播放，举例

请求：
https://drive-pc.quark.cn/1/clouddrive/share/sharepage/save?pr=ucpro&fr=pc&uc_param_str=&__dt=29418&__t=1716817707174
POST内容：
{"fid_list":["92b53f8a670243628f8aa2fd94c9af6d"],"fid_token_list":["9a1601abf70a916b194163b501cbc41c"],"to_pdir_fid":"4e51a4bf74d84d6d82e8a9eda3f5372f","pwd_id":"3d0adc9f7429","stoken":"eXOtPYMDWe3oCPJiryOYoDhPwb+3HemggLfqrKGja8M=","pdir_fid":"0","scene":"link"}
返回：
{
"status": 200,
"code": 0,
"message": "ok",
"timestamp": 1716817708,
"data": {
"task_id": "e12eef9bc9c042d9891e89e0881e632f"
},
"metadata": {
"tq_gap": 500
}
}

获取任务编号 e12eef9bc9c042d9891e89e0881e632f ，然后请求任务编号获取结果，也就是新的file id

请求：
https://drive-pc.quark.cn/1/clouddrive/task?pr=ucpro&fr=pc&uc_param_str=&task_id=e12eef9bc9c042d9891e89e0881e632f&retry_index=2&__dt=31269&__t=1716817709025
返回：
{
"status": 200,
"code": 0,
"message": "ok",
"timestamp": 1716817710,
"data": {
"task_id": "e12eef9bc9c042d9891e89e0881e632f",
"event_id": "99fk42-228c9e052978bb",
"task_type": 17,
"task_title": "分享-转存",
"status": 2,
"created_at": 1716817708654,
"finished_at": 1716817710050,
"share": {},
"save_as": {
"search_exit": true,
"to_pdir_fid": "4e51a4bf74d84d6d82e8a9eda3f5372f",
"is_pack": "0",
"save_as_top_fids": [
"13d4fad2bcb143ad8add01a8019c6fa6"
],
"to_pdir_name": "来自：分享"
}
},
"metadata": {
"tq_gap": 1500
}
}

13d4fad2bcb143ad8add01a8019c6fa6 应该就是新的 file id

**Comment by 907739769** [comment]
附议

**Comment by shmily1866** [comment]
+1

**Comment by hztbhtbh** [comment]
+1

**Comment by wo0work** [comment]
臣附议

**Comment by caowenhao** [comment]
+1

**Comment by huolanyun** [comment]
支持一下，夸克分享好像需要cookies 好像支持302，会员速度能达到50M/s,非会员10M/s
