### ISSUE TITLE
下载APK MD5不匹配

### ISSUE THREAD

**Issue by sherardxu** [alist-org/alist#6573]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.33.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

本地存储驱动，手机端访问，下载APK，安装提示包无法解析，检查MD5与源文件不匹配

### Reproduction / 复现链接

手机访问

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "gi9PIfAGpMJ58pTE",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 8080,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

### Logs / 日志

没有日志

**Comment by sherardxu** [comment]
> 不建议用多线程下载，比如via的多线程

使用华为手机浏览器下载，没用第三方浏览器

**Comment by xygzy** [comment]
我复现了同样的问题，我这边下载的是zip格式文件。似乎alist记住了某一个旧版本的文件，不管本地存储如何替换，始终下载的是这个旧版本。重启alist服务无效。

**Comment by SutoLiu** [comment]
同样的问题，本地存储使用多线程大概率会导致文件损坏，单线程就没事，但是单线程又不能跑满带宽，而且不少软件默认是使用多线程的，目前3.36.0版本可以稳定复现 @xhofe

**Comment by Royal520** [comment]
我也出现了同样的问题，.tar文件多线程下载下来后md5不对，单线程没问题。
