### ISSUE TITLE
增加网盘授权页面

### ISSUE THREAD

**Issue by sunny-00001** [alist-org/alist#6575]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在添加存储时，对于提供api授权接口的网盘添加授权页面，类似CD2这样
![20240605_111543_545_copy](https://github.com/alist-org/alist/assets/28869215/5d089227-9041-4a2d-a016-615eb5de39d5)
![图片](https://github.com/alist-org/alist/assets/28869215/4d17fbd8-3081-4624-8ee1-105a52c665b2)
简化添加cookie或token的流程

**Comment by sunny-00001** [comment]
这里是举个例子，每次添加阿里网盘，要先打开alist参考文档，然后点击开始，然后点击存储，然后找到阿里云盘，然后翻到refresh token请求页面，再点击链接授权，或者提前收藏链接
操作能不能更加便捷、傻白一点，在alist网页端添加存储这里直接集成进去，一键操作
事实上我的浏览器都有登录阿里云盘、百度网盘、123云盘等网盘，要是令牌过期了，提示我点一下重新授权，更新就完美了

**Comment by anwen-anyi** [comment]
CD2接入的是开放平台 不多说了
