### ISSUE TITLE
同名文件上传，能不能提弹出一个提示信息，是否要覆盖

### ISSUE THREAD

**Issue by ww198610** [alist-org/alist#6580]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

同名文件上传，能不能提弹出一个提示信息，是否要覆盖

**Comment by ww198610** [comment]
我是想要覆盖这个文件，只是一个提示信息，告诉操作者，有同名文件，他可以点击确定来覆盖，或者取消，不替换

**Comment by ww198610** [comment]
好的，我试试，谢谢

**Comment by ww198610** [comment]
reclone 对使用者，不是很友好，如果是个人兴趣，可以，如果作为几个人公用的网盘，就不是很友好了

**Comment by gdtv** [comment]
是的，如果网页界面上有提示信息就好了。
