### ISSUE TITLE
迅雷X在添加成功一段时间后无法创建新文件夹

### ISSUE THREAD

**Issue by karma-sun** [alist-org/alist#6584]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35

### Driver used / 使用的存储驱动

迅雷X

### Describe the bug / 问题描述

迅雷X在添加成功约十个小时后无法执行创建新文件夹操作,请求API /api/fs/mkdir卡死无任何响应，必须重启alist才恢复正常

### Reproduction / 复现链接

正常添加迅雷X存储，等待约十个小时后在迅雷X任意目录下创建新文件夹

### Config / 配置

默认配置

**Comment by Three-taile-dragon** [comment]
此问题是否经常出现？
