### ISSUE TITLE
failed get objs: failed to list objs: oauth2: "invalid_grant" "invalid refresh token for it may be has been refreshed by other process, more info redis: nil, RefreshToken os.BLLXu-TZ7GZiijkOL7rIb5lb3F0oKdNFOQSh6WdRCNFCgkyAvCWk7IK5ZyTa"

### ISSUE THREAD

**Issue by 907739769** [alist-org/alist#6589]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

pikpak分享

### Describe the bug / 问题描述

failed get objs: failed to list objs: oauth2: "invalid_grant" "invalid refresh token for it may be has been refreshed by other process, more info redis: nil, RefreshToken os.BLLXu-TZ7GZiijkOL7rIb5lb3F0oKdNFOQSh6WdRCNFCgkyAvCWk7IK5ZyTa"
过两个小时就会显示如上错误，重新加载挂载之后恢复，过两个小时又会有如上错误

### Reproduction / 复现链接

无

### Config / 配置

![image](https://github.com/alist-org/alist/assets/27858369/37a289f8-a4f6-4286-983a-b001febfcbf8)

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/27858369/de3d2ede-f2b3-4818-8e6f-e82e1faf2d4c)
![image](https://github.com/alist-org/alist/assets/27858369/a45ef746-97d1-4ff1-972d-26f9b40a2d26)
![image](https://github.com/alist-org/alist/assets/27858369/fa09a985-f413-41a9-bb66-398242ad69d4)

**Comment by anwen-anyi** [comment]
https://github.com/alist-org/alist/issues/6511 应该是这个 你可以试试看

**Comment by 907739769** [comment]
> #6511 应该修复了 你可以试试看

用的是最新版v3.35.0
也没有用

**Comment by anwen-anyi** [comment]
> > #6511 应该修复了 你可以试试看
> 
> 用的是最新版v3.35.0 也没有用

这个不是3.35.0  这个是测试版 比3.35.0高的版本

**Comment by 907739769** [comment]
> > > #6511 应该修复了 你可以试试看
> > 
> > 
> > 用的是最新版v3.35.0 也没有用
> 
> 这个不是3.35.0 这个是测试版 比3.35.0高的版本

好的  是main标签的docker镜像吧

**Comment by anwen-anyi** [comment]
> > > > #6511 应该修复了 你可以试试看
> > > 
> > > 
> > > 用的是最新版v3.35.0 也没有用
> > 
> > 
> > 这个不是3.35.0 这个是测试版 比3.35.0高的版本
> 
> 好的 是main标签的docker镜像吧

是的
