### ISSUE TITLE
Cann't download files in google drive and dropbox

### ISSUE THREAD

**Issue by tuthanika** [alist-org/alist#6591]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

onedrive, google drive, dropbox

### Describe the bug / 问题描述

Same file, downloaded in one drive normally, but google drive and dropbox have errors

I have tried using rclone to download from google drive and dropbox both are normal.

### Reproduction / 复现链接

https://alist.vietstarhp.com/d/dropbox/APK/Ads/vpnify_v2.1.9.4(219400).apk?sign=A-XEge2Qe9P7btHN6jkSFyOEuWcFLsoO04XEgmmdWbs=:0
https://alist.tuthanika.pp.ua/gd/APK/Ads/vpnify_v2.1.9.5%28219500%29.apk?sign=_33VID4qCu4jAL7J471RYTFioXFC1ml8yZzsthI3CaY=:0

### Config / 配置

https://alist.vietstarhp.com/d/dropbox/APK/Ads/vpnify_v2.1.9.4(219400).apk?sign=A-XEge2Qe9P7btHN6jkSFyOEuWcFLsoO04XEgmmdWbs=:0
https://alist.tuthanika.pp.ua/gd/APK/Ads/vpnify_v2.1.9.5%28219500%29.apk?sign=_33VID4qCu4jAL7J471RYTFioXFC1ml8yZzsthI3CaY=:0

### Logs / 日志

Google Drive:
{
  "error": {
    "code": 403,
    "message": "This file has been identified as malware or spam and cannot be downloaded.",
    "errors": [
      {
        "message": "This file has been identified as malware or spam and cannot be downloaded.",
        "domain": "global",
        "reason": "cannotDownloadAbusiveFile"
      }
    ]
  }
}

Dropbox :
{"code":500,"message":"failed link: failed get link: {not_allowed}:not_allowed/..","data":null}

**Comment by itsHenry35** [comment]
In your log, it has already shown that it can't be downloaded because it's a malware. This is a policy set by your cloud provider, instead of a bug of Alist.

**Comment by tuthanika** [comment]
2 days later, my file was downloaded normally. If I use rclone I can download immediately.

**Comment by tuthanika** [comment]
> In your log, it has already shown that it can't be downloaded because it's a malware. This is a policy set by your cloud provider, instead of a bug of Alist.

2 days later, my file was downloaded normally. If I use rclone I can download immediately.
