### ISSUE TITLE
115大文件上传不了

### ISSUE THREAD

**Issue by huhengbo** [alist-org/alist#6594]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

115大文件上传不了，我从本地存储复制上传5g以上文件提示错误，错误信息如下
upload reach the limit
我大概看了下源码（小白）似乎是115驱动里面限制判断的，或者说因为我不是会员？😳

### Reproduction / 复现链接

我是随意用的一个7.13g的视频复制的

### Config / 配置

![Screenshot_2024-06-08-16-15-10-303_com android chrome-edit](https://github.com/alist-org/alist/assets/22932717/645fef9e-3485-4feb-8f28-683f301626b0)

没有任何其他操作，大概检查了下，似乎都是5g以上出的错

### Logs / 日志

![Screenshot_2024-06-08-16-17-09-004_com android chrome-edit](https://github.com/alist-org/alist/assets/22932717/dce2e9e4-d7c2-45ac-89bb-62296cb427a3)

**Comment by djniche** [comment]
不是会员限制最大5G 此贴终结..

**Comment by huhengbo** [comment]
> 不是会员限制最大5G 此贴终结..

感谢

**Comment by chengnan049** [comment]
此 Issues 应该被关闭

**Comment by btke** [comment]
我有115会员，试了2次大文件（大文件在一个目录里面），都是10G多一点，虽然显示上传成功了但是网盘里面只有目录，大文件没上传成功，我用的是docker的3.36版（latest）
