### ISSUE TITLE
115重命名无法更改扩展名

### ISSUE THREAD

**Issue by oditian** [alist-org/alist#6596]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

115重命名无法更改扩展名
我试了其它存储驱动是正常的

### Reproduction / 复现链接

暂无

### Config / 配置

暂无

**Comment by djniche** [comment]
115的限制 无法更改扩展名..

**Comment by anwen-anyi** [comment]
本身就无法修改 115自身的问题

**Comment by Narut0123** [comment]
有一个方法——秒传到阿里云盘，在阿里云盘里修改后缀，再秒传回115
