### ISSUE TITLE
bug(ilanzou): cannot download pdf files due to `failed get link: redirect failed, status: 200`.

### ISSUE THREAD

**Issue by 7086cmd** [alist-org/alist#6597]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.25.0

### Driver used / 使用的存储驱动

iLanZou

### Describe the bug / 问题描述

When I log in to the iLanZou with my Phone Number and Password, the folders display normally, while when I am about to download files, it displays "failed to get the link: redirect failed, status: 200".

When I directly load the `/d/`, which is the direct link, it reports "`{"code":500,"message":"failed link: failed get link: redirect failed, status: 200","data":null}`".
<img width="975" alt="image" src="https://github.com/alist-org/alist/assets/54303040/dbbee705-d7b0-4517-b853-945ea82bd2dc">
<img width="958" alt="image" src="https://github.com/alist-org/alist/assets/54303040/a8495093-9f98-4c0e-8b67-d4f1e02d7483">

### Reproduction / 复现链接

It seems everywhere can reproduce it once you log in it through phone number and password. Sadly, I don't have enough servers to provide it.
<img width="1278" alt="image" src="https://github.com/alist-org/alist/assets/54303040/495f0ed8-fd03-4f53-9473-76874f76c86f">

### Config / 配置

It is just the default configuration.
<img width="449" alt="image" src="https://github.com/alist-org/alist/assets/54303040/034a6568-c7ef-4422-9528-5437a64e2f1c">

### Logs / 日志

```
2024-06-09 15:27:11 WARN[2024-06-09 07:27:11] init tool aria2 failed: failed get aria2 version: Post "http://localhost:6800/jsonrpc": dial tcp [::1]:6800: connect: connection refused 
2024-06-09 15:27:11 INFO[2024-06-09 07:27:11] start HTTP server @ 0.0.0.0:5244   
```
<img width="974" alt="image" src="https://github.com/alist-org/alist/assets/54303040/b5dc3e4d-093c-45cd-9132-7cc3d41df814">

**Comment by 7086cmd** [comment]
It shouldn't be a network error, as the log isn't reported after start.

**Comment by Greyisttot** [comment]
跟服务器没关系，这个盘已经很久不能用了
