### ISSUE TITLE
别名驱动文件排列顺序刷新后会改变

### ISSUE THREAD

**Issue by yyyytawa** [alist-org/alist#6600]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.35.0

### Driver used / 使用的存储驱动

别名

### Describe the bug / 问题描述

别名存储里面的文件(夹)刷新后文件排列顺序会改变,例如说(纯刷新)
![screen01](https://img.yyyyt.top/github/alist/issues/6600/screen01.png)
![screen02](https://img.yyyyt.top/github/alist/issues/6600/screen02.png)
文件夹顺序会改变

希望别名存储文件夹排列顺序固定的规则,而不是每次刷新都改变

### Reproduction / 复现链接

https://alist.yyyyt.top/

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "*******************",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5245,
    "https_port": 5244,
    "force_https": false,
    "cert_file": "**************",
    "key_file": "***************",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "/tmp/alist",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "/tmp/alist/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 30,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/116234899/618bffa0-4698-4d46-b89b-8c306a7fcfc9)

**Comment by j2rong4cn** [comment]
是不是没有设置排序？

**Comment by yyyytawa** [comment]
忘记设置排列顺序了,谢谢
