### ISSUE TITLE
能添加一个 https://bunny.net/  这个平台吗 这个是官方

### ISSUE THREAD

**Issue by 458722** [alist-org/alist#6604]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://bunny.net/  这个平台能加一下吗

**Comment by MooWantFree** [comment]
根据这个https://bunny.net/blog/whats-happening-with-s3-compatibility/来看, 这个网站似乎支持s3协议, 建议可以尝试通过s3协议添加
