### ISSUE TITLE
最近使用alist挂载阿里云open，看视频很卡，速度很慢

### ISSUE THREAD

**Issue by Zhengshihangcn** [alist-org/alist#6606]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

Latest

### Driver used / 使用的存储驱动

阿里云open

### Describe the bug / 问题描述

最近使用alist挂载阿里云open，在软件上用webdav看阿里云的视频很卡，速度很慢

### Reproduction / 复现链接

？

### Config / 配置

{
  "force": true,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "",
  "token_expires_in": 66,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 3306,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "/etc/alist/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "/tmp/alist",
  "bleve_dir": "/etc/alist/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "/tmp/alist/alist.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

**Comment by Zhengshihangcn** [comment]
不行阿，点击跳转阿里云授权会出现{"code":"InvalidRedirectUri","message":"invalid redirect_uri","requestId":"0ecdeb03-43af-41d2-9133-a8467a85d3f6"}发自我的 iPhone在 2024年6月12日，11:02，pongfcnkl ***@***.***> 写道：﻿
可以试试用我的Oauth令牌链接
https://444.psllll1.shop/aliyundrive.php

**Comment by TT-HR** [comment]
同样遇到了这个问题，好像是在alist页面通过aliyun video播放不卡顿，但是使用webdav后在其他播放器播放就出现卡顿。有解决方法吗

**Comment by wjming136** [comment]
同样问题，页面播放正常，使用webdav后在potplayer只有800K左右速度，以前正常，近一周发现的问题。

其他工具的webdav速度正常，排除了账号问题

**Comment by mdjs1py** [comment]
第三方api限速了，目前第三方挂载测速只有40mbp，只能等阿里的第三方权益包上线了

**Comment by Zhengshihangcn** [comment]
第三方权益包？发自我的 iPhone在 2024年6月17日，10:42，mdjs1py ***@***.***> 写道：﻿
第三方api限速了，目前第三方挂载测速只有40mbp，只能等阿里的第三方权益包上线了

**Comment by mdjs1py** [comment]
> 第三方权益包？发自我的 iPhone在 2024年6月17日，10:42，mdjs1py ***@***.***> 写道：﻿ 第三方api限速了，目前第三方挂载测速只有40mbp，只能等阿里的第三方权益包上线了 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

五月初有消息说阿里云盘要上架第三方权益包，好像是188一年，不买权益包就限速。

**Comment by mdjs1py** [comment]
> 太恶心了，本身就是会员还限速

那没有吧，我昨天开了会员，速度马上稳定到150，恶心人倒是没错。

**Comment by bxb100** [comment]
> > 太恶心了，本身就是会员还限速
> 
> 那没有吧，我昨天开了会员，速度马上稳定到150，恶心人倒是没错。

现在怕未来第三方权益包上来后, 现有的会员也限速

**Comment by uclinch** [comment]
限速了。我这里只有1000k/s   只能看看国产1080P的剧了。码率高点的1080都跑不动。4K更不用想了，2秒一卡

**Comment by fredericky123** [comment]
说好的不限速呢

**Comment by Gierry** [comment]
web页面观看不卡，说明是没限速的，wedav使用其他方式播放就卡，个人觉得是不是有啥bug，或者如何把网页播放的逻辑扩展到webdav？

**Comment by Anyfc** [comment]
多线程下载还是有30M速度，但是使用webdav还是只有1M，有什么播放器可以多线程下载的？

**Comment by banshaobao** [comment]
限速也不该只有1M/s吧。1M/s等于8M的带宽

**Comment by banshaobao** [comment]
我使用的时候大概950kb/s

**Comment by fredericky123** [comment]
> 限速也不该只有1M/s吧。1M/s等于8M的带宽

确实如此

**Comment by banshaobao** [comment]
如果限速40M的话。那应该是5MB/s的速度

**Comment by banshaobao** [comment]
![image](https://github.com/alist-org/alist/assets/45708805/1bb68e65-d4b0-4553-9e7d-b9669f0174ec)

**Comment by zyd16888** [comment]
> web页面观看不卡，说明是没限速的，wedav使用其他方式播放就卡，个人觉得是不是有啥bug，或者如何把网页播放的逻辑扩展到webdav？

web页面观看是用的官方的视频播放接口，是转码以后的，webdav使用的是文件下载链接，这两个不一样

**Comment by isamlee** [comment]
> web页面观看不卡，说明是没速度的，wedav使用其他方式播放就卡，个人感觉是不是有啥bug，或者如何把网页播放的逻辑地址放在webdav里？

web页面观看是经过阿里转码的，画质就不一样了。

**Comment by Benborba-github** [comment]
> > web页面观看不卡，说明是没限速的，wedav使用其他方式播放就卡，个人觉得是不是有啥bug，或者如何把网页播放的逻辑扩展到webdav？
> 
> web页面观看是用的官方的视频播放接口，是转码以后的，webdav使用的是文件下载链接，这两个不一样

  我也限速10mbps了

**Comment by fn-share** [comment]
似乎是 alist 网页内播放器的缓存不协调导致，大约每 10 秒一卡顿，网页从阿里云盘拉视频流，大约隔 10 秒拉一次，没有并行拉取，每次拉取结束，播放就会卡顿一下。让播放器缓存时间变长一点应能解决本问题。

**Comment by lowking** [comment]
> 似乎是 alist 网页内播放器的缓存不协调导致，大约每 10 秒一卡顿，网页从阿里云盘拉视频流，大约隔 10 秒拉一次，没有并行拉取，每次拉取结束，播放就会卡顿一下。让播放器缓存时间变长一点应能解决本问题。

应该和这个关系不大，我调用iina播放的，也是1秒一卡，速度900kb/s

**Comment by simear2004** [comment]
不开会员速度只几百k，阿里云盘也废了，还是自建nas靠谱

**Comment by Anyfc** [comment]
现在只能用idm多线程下载回来，15MB/秒，在线看是不敢想了

**Comment by MrNiebit** [comment]
废了，用页面的Aliyun video previewer播放 视频模糊，用Video或Webdav是原画，但是限速，阿里云开的还有会员。

现在看保存视频只能在阿里云网盘网页端或者客户端才能保证   **画质和速度** 了

**Comment by Deepseaon** [comment]
> ![image](https://github.com/alist-org/alist/assets/45708805/1bb68e65-d4b0-4553-9e7d-b9669f0174ec)

这个是怎么调出来的？网速显示

**Comment by aihuali213** [comment]
> > ![image](https://github.com/alist-org/alist/assets/45708805/1bb68e65-d4b0-4553-9e7d-b9669f0174ec)
> 
> 这个是怎么调出来的？网速显示

这个应该是播放器显示的速度
