### ISSUE TITLE
添加功能

### ISSUE THREAD

**Issue by cookie1038** [alist-org/alist#6614]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能添加分享链接的功能吗？可以像一些网盘一样，设置访问码

**Comment by ProjectNyaser** [comment]
经过测试，带“签名所有 (sign)”的下载链接可以未登录打开，这不失为一种替代方法
