### ISSUE TITLE
apple-touch-icon 无法修改

### ISSUE THREAD

**Issue by Emtier** [alist-org/alist#6617]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

head里面的
#<link rel="apple-touch-icon"href="https://jsd.nn.ci/gh/alist-org/logo@main/logo.png">
无法通过后台修改。建议增加修改功能。
<img width="414" alt="截屏2024-06-13 23 53 33" src="https://github.com/alist-org/alist/assets/166900875/dd2bd5d4-9bb6-431c-a662-994a595e82bf">

这里还有中文描述

**Comment by li-peifeng** [comment]
自己编译

**Comment by woshichenghaibo** [comment]
我也很作者提了。不能改先不说，这个文件巨大无此，稍微压缩一下可以到10KB以下甚至到2KB，作者这个。。。无语了
