### ISSUE TITLE
希望解决onedrive for business在不使用web代理的情况下能够在线预览音乐

### ISSUE THREAD

**Issue by laoguanTX** [alist-org/alist#6620]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望解决onedrive for business在不使用web代理的情况下能够在线预览音乐。
如果不开启web代理，那么onedrive for business中的音乐是不能够被预览的，会提示An audio error has occurred的提示字样。

**Comment by itsHenry35** [comment]
我没有遇到这个问题欸，可以正常预览
![image](https://github.com/alist-org/alist/assets/58730749/ae04e441-2f6b-4809-b869-4ab15bb62c29)
请你打开浏览器console进行截图
