### ISSUE TITLE
如何给直链添加防盗链

### ISSUE THREAD

**Issue by jinghuashang** [alist-org/alist#6625]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

获取的115网盘视频挂载到网盘后被白嫖，怎么能添加防盗链域名白名单。
已试过元信息方式加密，但是要提供服务的网站不知道如何验证密码从而无法正常访问

**Comment by jinghuashang** [comment]
> 开签名

有教程或案例提供参考吗

**Comment by yyyytawa** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [文档](https://alist.nn.ci)。
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure this feature is not implemented.
> * [x]  I'm sure it's a reasonable and popular requirement.
> 
> ### Description of the feature / 需求描述
> 获取的115网盘视频挂载到网盘后被白嫖，怎么能添加防盗链域名白名单。 已试过元信息方式加密，但是要提供服务的网站不知道如何验证密码从而无法正常访问
> 
> ### Suggested solution / 实现思路
> _No response_
> 
> ### Additional context / 附件
> _No response_

使用NGINX反代,限制refer
