### ISSUE TITLE
onedrive挂载后显示Access Denied

### ISSUE THREAD

**Issue by HayaseYuu** [alist-org/alist#6628]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.35.0

### Driver used / 使用的存储驱动

onedrive

### Describe the bug / 问题描述

![image](https://github.com/alist-org/alist/assets/84274858/74784e7d-ad8a-4eb2-af12-26728807128b)
挂载后显示这个

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/84274858/e9e48164-5c9d-4fbc-af85-5c39e88ba1c0)
会不会是这个的原因

### Config / 配置

![image](https://github.com/alist-org/alist/assets/84274858/c6c05781-e041-4211-ab57-d67400cefea3)

**Comment by Deepsea-CN** [comment]
空间满了不删文件内容都看不了的，而且只能官方app能访问
