### ISSUE TITLE
使用 ./alist 的任何命令提示 Segmentation fault（段错误）

### ISSUE THREAD

**Issue by iweec** [alist-org/alist#6643]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35

### Driver used / 使用的存储驱动

五

### Describe the bug / 问题描述

我在一台Debian系统上安装了此程序，后设置密码时提示段错误
后尝试运行 ./alist version 仍提示段错误

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/136957005/6c4ae368-ed0b-4575-840c-ca931e32af3c)

### Config / 配置

未知

### Logs / 日志

![image](https://github.com/alist-org/alist/assets/136957005/47ce0d96-7b82-46dc-a2f7-7130a737de0d)

**Comment by iweec** [comment]
> 校验一下哈希，看看是不是没下完

怎么校验啊

**Comment by VergilGao** [comment]
有 md5sum 命令？
https://github.com/alist-org/alist/releases/download/v3.35.0/md5.txt
这是各个二进制的MD5
你用md5sum 对比一下你下载的那个二进制

**Comment by iweec** [comment]
> 有 md5sum 命令？ https://github.com/alist-org/alist/releases/download/v3.35.0/md5.txt 这是各个二进制的MD5 你用md5sum 对比一下你下载的那个二进制

我是直接用的一键安装，没安装包

**Comment by iweec** [comment]
> > > 有 md5sum 命令？ https://github.com/alist-org/alist/releases/download/v3.35.0/md5.txt 这是各个二进制的MD5 你用md5sum 对比一下你下载的那个二进制
> > 
> > 
> > 我是直接用的一键安装，没安装包
> 
> 你是arm的设备？

是
arrch64的

**Comment by iweec** [comment]
> > > > > 有 md5sum 命令？ https://github.com/alist-org/alist/releases/download/v3.35.0/md5.txt 这是各个二进制的MD5 你用md5sum 对比一下你下载的那个二进制
> > > > 
> > > > 
> > > > 我是直接用的一键安装，没安装包
> > > 
> > > 
> > > 你是arm的设备？
> > 
> > 
> > 是 arrch64的
> 
> arm建议手动安装

![image](https://github.com/alist-org/alist/assets/136957005/c03c0131-c503-42f7-b1ba-9f7eb3be9aba)
手动安装执行 ./alist server 后显示-bash: ./alist: 没有那个文件或目录，但ls有alist文件

**Comment by iweec** [comment]
> > > > > > > 有 md5sum 命令？ https://github.com/alist-org/alist/releases/download/v3.35.0/md5.txt 这是各个二进制的MD5 你用md5sum 对比一下你下载的那个二进制
> > > > > > 
> > > > > > 
> > > > > > 我是直接用的一键安装，没安装包
> > > > > 
> > > > > 
> > > > > 你是arm的设备？
> > > > 
> > > > 
> > > > 是 arrch64的
> > > 
> > > 
> > > arm建议手动安装
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/136957005/342654795-c03c0131-c503-42f7-b1ba-9f7eb3be9aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDcxOTMsIm5iZiI6MTcxOTMwNjg5MywicGF0aCI6Ii8xMzY5NTcwMDUvMzQyNjU0Nzk1LWMwM2MwMTMxLWM1MDMtNDJmNy1iMWJhLTlmN2ViM2JlOWFiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwOTE0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjM3NTY3ODUwNzc2NTU1YzIyYWI1MGNkNjQxNGE2ZTJhMDRjNTNhZWZkNzExMTQ0MTlkZGVlMGIzZGZhZTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GpZafj1CDwHJDwEnUs2LXro44WW5DaLyHI2dTakZN0) 手动安装执行 ./alist server 后显示-bash: ./alist: 没有那个文件或目录，但ls有alist文件
> 
> 解压了没？给权限了没？

都做了

**Comment by iweec** [comment]
> > > > > > > > 有 md5sum 命令？ https://github.com/alist-org/alist/releases/download/v3.35.0/md5.txt 这是各个二进制的MD5 你用md5sum 对比一下你下载的那个二进制
> > > > > > > 
> > > > > > > 
> > > > > > > 我是直接用的一键安装，没安装包
> > > > > > 
> > > > > > 
> > > > > > 你是arm的设备？
> > > > > 
> > > > > 
> > > > > 是 arrch64的
> > > > 
> > > > 
> > > > arm建议手动安装
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/136957005/342654795-c03c0131-c503-42f7-b1ba-9f7eb3be9aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDcxOTMsIm5iZiI6MTcxOTMwNjg5MywicGF0aCI6Ii8xMzY5NTcwMDUvMzQyNjU0Nzk1LWMwM2MwMTMxLWM1MDMtNDJmNy1iMWJhLTlmN2ViM2JlOWFiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwOTE0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjM3NTY3ODUwNzc2NTU1YzIyYWI1MGNkNjQxNGE2ZTJhMDRjNTNhZWZkNzExMTQ0MTlkZGVlMGIzZGZhZTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GpZafj1CDwHJDwEnUs2LXro44WW5DaLyHI2dTakZN0) 手动安装执行 ./alist server 后显示-bash: ./alist: 没有那个文件或目录，但ls有alist文件
> > 
> > 
> > 解压了没？给权限了没？
> 
> ls -l 看看文件大小

![image](https://github.com/alist-org/alist/assets/136957005/b6a07129-82b8-4917-9898-e498de1a6f57)

**Comment by iweec** [comment]
> > > > > > > > > > 有 md5sum 命令？ https://github.com/alist-org/alist/releases/download/v3.35.0/md5.txt 这是各个二进制的MD5 你用md5sum 对比一下你下载的那个二进制
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我是直接用的一键安装，没安装包
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你是arm的设备？
> > > > > > > 
> > > > > > > 
> > > > > > > 是 arrch64的
> > > > > > 
> > > > > > 
> > > > > > arm建议手动安装
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/136957005/342654795-c03c0131-c503-42f7-b1ba-9f7eb3be9aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDcxOTMsIm5iZiI6MTcxOTMwNjg5MywicGF0aCI6Ii8xMzY5NTcwMDUvMzQyNjU0Nzk1LWMwM2MwMTMxLWM1MDMtNDJmNy1iMWJhLTlmN2ViM2JlOWFiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwOTE0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjM3NTY3ODUwNzc2NTU1YzIyYWI1MGNkNjQxNGE2ZTJhMDRjNTNhZWZkNzExMTQ0MTlkZGVlMGIzZGZhZTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GpZafj1CDwHJDwEnUs2LXro44WW5DaLyHI2dTakZN0) 手动安装执行 ./alist server 后显示-bash: ./alist: 没有那个文件或目录，但ls有alist文件
> > > > 
> > > > 
> > > > 解压了没？给权限了没？
> > > 
> > > 
> > > ls -l 看看文件大小
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/136957005/343057939-b6a07129-82b8-4917-9898-e498de1a6f57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTIyMDgsIm5iZiI6MTcxOTM5MTkwOCwicGF0aCI6Ii8xMzY5NTcwMDUvMzQzMDU3OTM5LWI2YTA3MTI5LTgyYjgtNDkxNy05ODk4LWU0OThkZTFhNmY1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwODUxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjUyYTZlMTgxNWEyNzljNTg5MzU0YTYyMDJlMTllYjgwZTU5NTlmMWUwNDlhMTMxNmFlNDZhNGQ3MWQwNjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jX6gjyDorHPXlIxYV9rmN82-YkPItdKNfswc-f2hWU0)
> 
> 不是arm64吗？怎么是arm6？

我好愚蠢 版本安装错了 现在好了 太感谢你了
