### ISSUE TITLE
115网盘重命名后缀行为异常

### ISSUE THREAD

**Issue by 1049731887** [alist-org/alist#6649]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

115网盘

### Describe the bug / 问题描述

重命名123.txt到123.md，但实际上文件名变成了123.txt.txt

### Reproduction / 复现链接

http://127.0.0.1:5244😅

### Config / 配置

115网盘扫码登陆，其他全默认

**Comment by anwen-anyi** [comment]
115本身就不允许修改后缀，你去官网也不能改吧 :joy_cat:

**Comment by flansing** [comment]
115官方不支持修改后缀，你如果要修改需要先下载下来然后改完了做覆盖处理
