### ISSUE TITLE
Support HEIC Format in Image View | 在图片视图中支持HEIC格式

### ISSUE THREAD

**Issue by RainoutOvO** [alist-org/alist#6650]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

HEIC images can be previewed in grid view, but cannot be displayed properly in image view. Therefore, it is expected that they can be displayed in image view like regular image files (such as PNG)

HEIC图片在网格视图下可以正常预览，然而在图片视图中无法正常显示，因而期望在图片视图下能够像一般图片文件（如PNG）一样展示

**Comment by li-peifeng** [comment]
我的可以正常显示啊![image](https://github.com/alist-org/alist/assets/103113557/93fef4aa-51a8-414f-97a4-578ff9e05993)

**Comment by li-peifeng** [comment]
> 我的可以正常显示啊![image](https://github.com/alist-org/alist/assets/103113557/93fef4aa-51a8-414f-97a4-578ff9e05993)

我是自己编译的，用了最新版的lightgallery

**Comment by beyondth** [comment]
我的也是无法预览heic格式图片，着急啊！
