### ISSUE TITLE
阿里云盘open到115，复制失败

### ISSUE THREAD

**Issue by z-henry** [alist-org/alist#6656]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

阿里云盘open和115网盘

### Describe the bug / 问题描述

使用复制功能，将两个视频文件（8g，10g）从阿里云盘open复制到115网盘。没有触发秒传，正常上传，最终提示红字，115网盘没有出现对应视频文件
![image](https://github.com/alist-org/alist/assets/40875274/8e43264b-8f42-4787-b1c4-c78db7fa7da9)

### Reproduction / 复现链接

无

### Config / 配置

![image](https://github.com/alist-org/alist/assets/40875274/0d46cd1a-3575-4623-9549-3103531e3155)
![image](https://github.com/alist-org/alist/assets/40875274/206c5acc-de06-4bc6-b290-1f9f4d434d4c)

### Logs / 日志

>[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/server/middlewares/auth.go:27 github.com/alist-org/alist/v3/server/middlewares.Auth() use admin token: &{ID:1 Username:admin PwdHash: PwdTS:0 Salt: Password: BasePath:/ Role:2 Disabled:false Permission:0 OtpSecret: SsoID: Authn:[]} 
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/path.go:25 github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath() use storage:  /aliyun                        
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/path.go:25 github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath() use storage:  /115                           
[GIN] 2024/06/25 - 22:31:23 | 200 |     577.684µs |  192.168.100.10 | POST     "/api/fs/copy"
2024/06/25 22:31:23 INFO worker execute task worker=0 task=TybU14GEH7Z2Rd7QxSt9J
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:167 github.com/alist-org/alist/v3/internal/op.Get() op.Get /emby/动漫/鬼灭之刃/S05/鬼灭之刃.S05E06.mkv     
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:108 github.com/alist-org/alist/v3/internal/op.List() op.List /emby/动漫/鬼灭之刃/S05                    
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:112 github.com/alist-org/alist/v3/internal/op.List() use cache when list /emby/动漫/鬼灭之刃/S05        
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:167 github.com/alist-org/alist/v3/internal/op.Get() op.Get /emby/动漫/鬼灭之刃/S05/鬼灭之刃.S05E06.mkv     
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:108 github.com/alist-org/alist/v3/internal/op.List() op.List /emby/动漫/鬼灭之刃/S05                    
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:112 github.com/alist-org/alist/v3/internal/op.List() use cache when list /emby/动漫/鬼灭之刃/S05        
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:167 github.com/alist-org/alist/v3/internal/op.Get() op.Get /emby/动漫/鬼灭之刃/S05/鬼灭之刃.S05E06.mkv     
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:108 github.com/alist-org/alist/v3/internal/op.List() op.List /emby/动漫/鬼灭之刃/S05                    
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:112 github.com/alist-org/alist/v3/internal/op.List() use cache when list /emby/动漫/鬼灭之刃/S05        
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/server/middlewares/auth.go:27 github.com/alist-org/alist/v3/server/middlewares.Auth() use admin token: &{ID:1 Username:admin PwdHash: PwdTS:0 Salt: Password: BasePath:/ Role:2 Disabled:false Permission:0 OtpSecret: SsoID: Authn:[]} 
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/path.go:25 github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath() use storage:  /aliyun                        
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/path.go:25 github.com/alist-org/alist/v3/internal/op.GetStorageAndActualPath() use storage:  /115                           
[GIN] 2024/06/25 - 22:31:23 | 200 |     415.796µs |  192.168.100.10 | POST     "/api/fs/copy"
2024/06/25 22:31:23 INFO worker execute task worker=1 task=76e4Ieb44pMsB9fyRX8Wr
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:167 github.com/alist-org/alist/v3/internal/op.Get() op.Get /emby/动漫/鬼灭之刃/S05/鬼灭之刃.S05E07.mkv     
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:108 github.com/alist-org/alist/v3/internal/op.List() op.List /emby/动漫/鬼灭之刃/S05                    
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:112 github.com/alist-org/alist/v3/internal/op.List() use cache when list /emby/动漫/鬼灭之刃/S05        
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:167 github.com/alist-org/alist/v3/internal/op.Get() op.Get /emby/动漫/鬼灭之刃/S05/鬼灭之刃.S05E07.mkv     
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:108 github.com/alist-org/alist/v3/internal/op.List() op.List /emby/动漫/鬼灭之刃/S05                    
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:112 github.com/alist-org/alist/v3/internal/op.List() use cache when list /emby/动漫/鬼灭之刃/S05        
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:167 github.com/alist-org/alist/v3/internal/op.Get() op.Get /emby/动漫/鬼灭之刃/S05/鬼灭之刃.S05E07.mkv     
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:108 github.com/alist-org/alist/v3/internal/op.List() op.List /emby/动漫/鬼灭之刃/S05                    
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/internal/op/fs.go:112 github.com/alist-org/alist/v3/internal/op.List() use cache when list /emby/动漫/鬼灭之刃/S05        
[37mDEBU[0m[2024-06-25 22:31:23]/home/runner/work/alist/alist/server/middlewares/auth.go:27 github.com/alist-org/alist/v3/server/middlewares.Auth() use admin token: &{ID:1 Username:admin PwdHash: PwdTS:0 Salt: Password: BasePath:/ Role:2 Disabled:false Permission:0 OtpSecret: SsoID: Authn:[]} 

[37mDEBU[0m[2024-06-25 23:29:59]/home/runner/work/alist/alist/internal/op/fs.go:561 github.com/alist-org/alist/v3/internal/op.Put() put file [鬼灭之刃.S05E07.mkv] done              
2024/06/25 23:29:59 INFO worker execute task worker=4 task=76e4Ieb44pMsB9fyRX8Wr
[37mDEBU[0m[2024-06-25 23:37:15]/home/runner/work/alist/alist/internal/op/fs.go:561 github.com/alist-org/alist/v3/internal/op.Put() put file [鬼灭之刃.S05E06.mkv] done              
2024/06/25 23:37:15 INFO worker execute task worker=2 task=TybU14GEH7Z2Rd7QxSt9J

**Comment by z-henry** [comment]
有的，并且是开了会员之后再抓的手机app的cookie

**Comment by Narut0123** [comment]
不是所有文件都可以秒传到115，秒传的前提是115服务器里有这个文件

**Comment by Narut0123** [comment]
你可以测试下，打开115浏览器或者115电脑客户端，往里面传一集鬼灭之刃试试，看看能不能秒传

**Comment by z-henry** [comment]
> 不是所有文件都可以秒传到115，秒传的前提是115服务器里有这个文件

这个我理解，但是我想问的是为什么这次非秒传传输失败了

**Comment by Narut0123** [comment]
> > 不是所有文件都可以秒传到115，秒传的前提是115服务器里有这个文件
> 
> 这个我理解，但是我想问的是为什么这次非秒传传输失败了

不能秒传的文件，会先从阿里云盘下载到部署alist的设备上，再上传至115网盘，你看看是不是你安装alist的设备空间不够了

**Comment by z-henry** [comment]
> > > 不是所有文件都可以秒传到115，秒传的前提是115服务器里有这个文件
> > 
> > 
> > 这个我理解，但是我想问的是为什么这次非秒传传输失败了
> 
> 不能秒传的文件，会先从阿里云盘下载到部署alist的设备上，再上传至115网盘，你看看是不是你安装alist的设备空间不够了

设备空间是一定够的，而且这次错误提示看起来像是和token有关。但是当时我的挂载都是正常的。
昨晚也进行了一次非秒传，8g的文件，最终成功了。
