### ISSUE TITLE
Windows 7无法正常运行alist

### ISSUE THREAD

**Issue by Rosabis** [alist-org/alist#6659]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

没有能够添加

### Describe the bug / 问题描述

无法正常在windows 7下正常运行alist，在命令提示符下运行窗口标题一闪而过，没有任何错误提示

### Reproduction / 复现链接

无

### Config / 配置

还没有能够配置，仅刚下载解压缩

### Logs / 日志

![图片](https://github.com/alist-org/alist/assets/124857271/47e32b56-d380-4c9d-bbcf-5524bb7955a3)

**Comment by anwen-anyi** [comment]
AList v3.30.0版本开始将不再支持Win7/Server2008，因为Go不支持了,[点击查看详细说明](https://github.com/golang/go/issues/64622).
