### ISSUE TITLE
[Bug] [联通网盘] 上传接口已废，希望更新个新的上传接口

### ISSUE THREAD

**Issue by 8MiYile** [alist-org/alist#6663]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35

### Driver used / 使用的存储驱动

联通网盘(WoPan)

### Describe the bug / 问题描述

上传接口 gxupload.pan.wo.cn:8443 无法访问 tcp ping和icmp ping都无法访问
![image](https://github.com/alist-org/alist/assets/25455400/ed21f311-ad90-4d26-a196-abb135645ced)

### Reproduction / 复现链接

上传接口
gxupload.pan.wo.cn:8443

### Config / 配置

与配置无关

**Comment by CirnoSalt** [comment]
的确失效了

**Comment by YangHaoNing-CN** [comment]
一样

**Comment by YangHaoNing-CN** [comment]
https://tjupload.pan.wo.cn/openapi/client/upload2C

**Comment by ZXAS007** [comment]
https://tjupload.pan.wo.cn/openapi/upload/data

**Comment by Rafeal-Ma** [comment]
![微信图片_20240709130830](https://github.com/alist-org/alist/assets/126082509/ce5f7718-efdf-41d4-b7ea-0d4e7a3338d4)一样 希望能修复

**Comment by yippee0539** [comment]
怎么解决啊，巨佬
