### ISSUE TITLE
希望为Alias别名阿里云盘Open后的视频增加Aliyun Video Previewer选项

### ISSUE THREAD

**Issue by Simonzhang8** [alist-org/alist#6667]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

阿里云盘上存储的部分视频直接通过Video播放会报错或者没有声音，通过Aliyun Video Previewer播放正常。但将阿里云盘通过别名挂载后，文件就没有Aliyun Video Previewer的选项了。希望能够为别名支持Aliyun Video Previewer播放器。
之前有好几条相关的Issues和Discussions了，但都没有人理会

### Suggested solution / 实现思路

为别名支持Aliyun Video Previewer播放器

**Comment by tuqigo** [comment]
希望Aliyun Video Previewer的开关
