### ISSUE TITLE
希望网页观看视频时，能调整字幕大小

### ISSUE THREAD

**Issue by Watercolor-tone** [alist-org/alist#6670]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望网页观看视频时，能调整字幕大小

**Comment by AndyLin2020** [comment]
是的，全屏时字幕更小，希望能加个选择字体样式和大小调整
