### ISSUE TITLE
希望内置同步功能

### ISSUE THREAD

**Issue by 1049731887** [alist-org/alist#6672]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

https://github.com/lee-cq/alist-sync

**Comment by ypq123456789** [comment]
这个大佬做一半都不做了。。。。

**Comment by 1049731887** [comment]
rclone难用啊
