### ISSUE TITLE
元信息内容Markdown填写链接提示Failed to fetch XXX（markdown的地址）: AxiosError: Network Error

### ISSUE THREAD

**Issue by Simonzhang8** [alist-org/alist#6682]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

元信息内容中的Markdown填写了一个md文件的链接，但未能正确加载，提示Failed to fetch XXX（markdown的地址）: AxiosError: Network Error，但是这个链接是能够在公网正常访问的，所以应该也不是网络的问题

### Reproduction / 复现链接

![image](https://github.com/alist-org/alist/assets/165749751/2713e54a-6d6f-46d3-ae36-e7aa92051292)

### Config / 配置

![image](https://github.com/alist-org/alist/assets/165749751/538628c6-828d-4152-af84-de7b70e11ef0)

**Comment by xhofe** [comment]
链接需要支持 cors 

或者贴一下链接

**Comment by Simonzhang8** [comment]
> 链接需要支持 cors

好的好的，刚才修改了下nginx的配置文件，可以用了，谢谢xhofe❤

**Comment by Simonzhang8** [comment]
> 链接需要支持 cors

好的好的，刚才修改了下nginx的配置文件，可以用了，谢谢xhofe❤
