### ISSUE TITLE
手机端搜索栏错乱

### ISSUE THREAD

**Issue by ALRCMt** [alist-org/alist#6687]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

任意

### Describe the bug / 问题描述

手机端网页使用搜索栏，若用中文键盘键入，会弹出字母
![image](https://github.com/alist-org/alist/assets/140961960/1b51bb52-651b-4342-98c1-85d9d3757ad8)

**Comment by itsHenry35** [comment]
请附上你的浏览器+输入法的名称与版本
未能复现

**Comment by ALRCMt** [comment]
> 请附上你的浏览器+输入法的名称与版本
> 
> 未能复现

使用ios原版safari与夸克浏览器等皆有此现象，输入法为ios原版中文26键输入法，我觉得是iOS原版输入法的锅

**Comment by itsHenry35** [comment]
> > 请附上你的浏览器+输入法的名称与版本
> > 未能复现
> 
> 使用ios原版safari与夸克浏览器等皆有此现象，输入法为ios原版中文26键输入法，我觉得是iOS原版输入法的锅

我没有ios设备，看看有没有别人看到这个issue测试一下吧

**Comment by sunzongzheng** [comment]
是iOS14吗

**Comment by ALRCMt** [comment]
> 是iOS14吗

我是ios15.6

**Comment by sunzongzheng** [comment]
> > 是iOS14吗
> 
> 我是ios15.6

可以尝试下这个分支构建后是否还有问题：https://github.com/alist-org/alist-web/pull/192#issuecomment-2283791922
和PR中描述的iOS14.8的问题看起来有点类似
