### ISSUE TITLE
请教AlistCloudflare加速CDN怎么配置，明明都每个值都填了却报sign missmatch错误

### ISSUE THREAD

**Issue by ghostWindows-files** [alist-org/alist#6689]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

Terabox,Pikpak

### Describe the bug / 问题描述

[alist-proxy.js](https://github.com/alist-org/alist-proxy/blob/main/alist-proxy.js)
这个代码最近新增了一个叫WORKER_ADDRESS的变量但是当我在pages部署好以后填入网址并下载却提示sign missmatch
希望有人帮我解答一下

### Reproduction / 复现链接

[alist-proxy.js](https://github.com/alist-org/alist-proxy/blob/main/alist-proxy.js)

### Config / 配置

[alist-proxy.js](https://github.com/alist-org/alist-proxy/blob/main/alist-proxy.js)

**Comment by Simonzhang8** [comment]
你填的内容是什么啊？注意网址后面不能有斜杠/，如https://al.nn.ci不能填成https://al.nn.ci/

**Comment by ghostWindows-files** [comment]
> 你填的内容是什么啊？注意网址后面不能有斜杠/，如[https://al.nn.ci不能填成https://al.nn.ci/](https://al.nn.ci%E4%B8%8D%E8%83%BD%E5%A1%AB%E6%88%90https://al.nn.ci/)

玩全安装要求填的啊，刚刚我还特地洗了把脸确定是完全按照要求的

**Comment by Simonzhang8** [comment]
你具体填的是什么啊，代码那里放出来看一下，我刚才试了下新版代码是可以正常用的

**Comment by Simonzhang8** [comment]
sign mismatch也可能是你TOKEN填错了

**Comment by ghostWindows-files** [comment]
> sign mismatch也可能是你TOKEN填错了

token又检查了一遍是正确的，结果还是sign mismatch
请问worker address里面的地址开头需要加https://吗

**Comment by Simonzhang8** [comment]
要的，两个address都需要加上https（或者http）

**Comment by ghostWindows-files** [comment]
> 要的，两个address都需要加上https（或者http）

好，我加上再试一下

**Comment by ghostWindows-files** [comment]
> 要的，两个address都需要加上https（或者http）

已正常
