### ISSUE TITLE
Alist映射为对象存储添加 Region 参数

### ISSUE THREAD

**Issue by kexue-z** [alist-org/alist#6695]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望添加 可选的 `Region` 参数
![image](https://github.com/alist-org/alist/assets/71873002/5ae13cff-b49f-4317-8519-164fb3dd9b6b)

**Comment by itsHenry35** [comment]
可以说个使用场景么，我感觉貌似没啥必要

**Comment by kexue-z** [comment]
> 可以说个使用场景么，我感觉貌似没啥必要

有些软件挂载的时候，需要填这个参数。然后不知道怎么填*

**Comment by itsHenry35** [comment]
> > 可以说个使用场景么，我感觉貌似没啥必要
> 
> 有些软件挂载的时候，需要填这个参数。然后不知道怎么填*

填写auto就行了
