### ISSUE TITLE
Alist 无法连接 MariaDB 11.4.2

### ISSUE THREAD

**Issue by xmb505** [alist-org/alist#6699]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

nope

### Describe the bug / 问题描述

其他程序可以连接数据库，但是Alist无法连接MariaDB 11.4，但是通过降低版本到10.6却可以连接。

### Reproduction / 复现链接

nope

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "5qNOfMYxp8mB44R4",
  "token_expires_in": 48,
  "database": {
    "type": "mysql",
    "host": "localhost",
    "port": 3306,
    "user": "xxxxxxxx",
    "password": "xxxxxxxx",
    "name": "xxxxxxxxx",
    "db_file": "data/data.db",
    "table_prefix": "alist_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": 5243,
    "force_https": true,
    "cert_file": "./ssl/fullchain.pem",
    "key_file": "./ssl/privkey.pem",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
}

### Logs / 日志

MariaDB 11.4
2024-07-04 15:55:58 5821 [Warning] Aborted connection 5821 to db: 'unconnected' user: 'unauthenticated' host: '192.168.1.111' (This connection closed normally without authentication)

Alist
INFO[2024-07-04 15:55:58] reading config file: data/config.json        
INFO[2024-07-04 15:55:58] load config from env with prefix: ALIST_     
INFO[2024-07-04 15:55:58] init logrus... 

降低数据库版本后的Alist
INFO[2024-07-04 16:14:06] reading config file: data/config.json        
INFO[2024-07-04 16:14:06] load config from env with prefix: ALIST_     
INFO[2024-07-04 16:14:06] init logrus...                               
INFO[2024-07-04 16:14:08] Successfully created the admin user and the initial password is: ozHNKzLb

**Comment by meethuhu** [comment]
我的可以正常连接
AList：v3.35.0
MariaDB：11.4.2
