### ISSUE TITLE
115分享不支持32位架构，failed get objs: failed to list objs: json: cannot unmarshal number 2755523652316298479 into Go struct field ShareFile.data.list.cid of type int

### ISSUE THREAD

**Issue by ThomasChooo** [alist-org/alist#6704]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

115 Cloud / Share

### Describe the bug / 问题描述

32位系统，armv7l，挂载115分享链接报的错，文件夹能看到，点进去文件夹看不到文件报的错，挂载自己的115网盘没问题，看报错是超过int范围了。

### Reproduction / 复现链接

无

### Config / 配置

32位系统，armv7l，安装的alist版本alist-linux-musleabihf-armv7l.tar.gz，底包Armbian-unofficial_24.5.0-trunk_Onecloud_bullseye_current_6.6.21_minimal.burn.img，Casaos系统。

### Logs / 日志

![捕获](https://github.com/alist-org/alist/assets/140310113/5d080463-dae0-4b6b-9f97-0ade635c5efa)

**Comment by ThomasChooo** [comment]
修改建议：
将Go结构体中cid字段的类型从int更改为能够处理大数字的类型，例如int64、uint64或string。

**Comment by xindongzetong** [comment]
夸克上传文件也有这个问题，32位会出错，64位就没问题https://github.com/alist-org/alist/issues/6572
