### ISSUE TITLE
WebDAV无法挂载个人版Onedrive

### ISSUE THREAD

**Issue by i207M** [alist-org/alist#6707]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

WebDAV

### Describe the bug / 问题描述

WebDAV挂载个人版Onedrive，vendor选择sharepoint之后，如果地址填d.docs.live.net会报错net tld not supported. 然而根据 [WinSCP的教程](https://winscp.net/eng/docs/guide_microsoft_onedrive)，是（亲测）能以WebDAV形式通过d.docs.live.net访问Onedrive的。因此我觉得Alist理论上也可以支持，应该将my-sharepoint之类的域名替换为d.docs.live.net可以解决。

最后说明一下为什么不能用Onedrive driver来挂载个人版Onedrive：

新的个人版Onedrive账号自微软更新政策后无法创建应用程序和密码。自2024年6月起，必须激活Azure或者加入微软开发者计划后，才能创建“应用”，进而得到client_id和client_secret. 然而激活Azure需要验证银行卡，比较麻烦。

来源：https://learn.microsoft.com/en-us/entra/identity-platform/reference-breaking-changes#applications-must-be-registered-in-a-directory

### Reproduction / 复现链接

N/A

### Config / 配置

如WinSCP的教程，地址填d.docs.live.net，账号密码是Microsoft账号密码（未开启两步验证）

**Comment by zhouqiqiqiqi** [comment]
个人版挂载不了的，只能用商业版，教育版，e5这种

**Comment by i207M** [comment]
WinSCP是能挂载的，可惜不开源

**Comment by Simonzhang8** [comment]
直接用alist官网默认提供的client去get refresh token啊，不需要自己创建应用的

**Comment by i207M** [comment]
@Simonzhang8 多谢，我最后是借别的账号的client拿的token. Alist官网提供的话，本issue的功能就不必要了. Closing

**Comment by yifas** [comment]
> 直接用alist官网默认提供的client去get refresh token啊，不需要自己创建应用的，因为个人版没有组织管理员批准这一步，所以alist提供的是可以直接用的

看了你回复才知道怎么挂载个人版
