### ISSUE TITLE
自动备份

### ISSUE THREAD

**Issue by DreamlingBig** [alist-org/alist#6714]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加webdav配置
用来备份（上传/取拉）alist的配置备份

### Suggested solution / 实现思路

备份上传的方式：[手动/定时/修改后]
手动：现在的备份是下载一个json（alist配置）到用户端，而webdav则是手动点击备份上传至webdav服务器
定时：定时备份alist配置
修改后：增加储存或者修改设置后自动webdav上传至服务器

### Additional context / 附件

@
![Screenshot_2024-07-08-00-56-02-985_com yucore swashbucklerdiary-edit](https://github.com/alist-org/alist/assets/44178151/05d0bf61-d022-499b-9b38-b0023a77eaac)

**Comment by woshichenghaibo** [comment]
我自己写了bash脚本实现了。
