### ISSUE TITLE
[alist-web]  Push `Size`,`Modified` colomns to the right with minimal width

### ISSUE THREAD

**Issue by Ender-Wang** [alist-org/alist#6720]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

- Push the `Size` and `Modified` cols to the right with minimal width needed, so the `Name` col can take as much space as possible to display the full file name without scrolling or displaying them in two lines.
- Motivation: I found this a little annoying to view files with long names, especially those TV shows or films with standard names that include video and audio formats, etc.

### Suggested solution / 实现思路

- I have look through the src code of alist-web but found no luck on pinpointing the section that manages this kinda style, I did find  out that the length is these three tags are in ratio not in pixels, but I am not sure it can be converted to pixels or not, since the structure of the alist-web repo is kinda tricky to me. 
- Currently I am using Stylish to rewrite CSS:
  ```
  /*------------------------Header------------------------*/
  /*Name*/
  .hope-c-PJLV-ibXlJvp-css {
	  flex: 1;
  }
  
  /*Size*/
  .hope-c-PJLV-ikuZzan-css {
    width: 70px !important;
    flex: 0 0 70px;
  }
  
  /*Modified*/
  .hope-c-PJLV-ieXfLml-css {
    width: 170px !important;
    flex: 0 0 170px;
  }
  
  /*------------------------Body------------------------*/
  /*Name*/
  .hope-c-PJLV-ibXlJvp-css {
	  flex: 1;
  }
  
  /*Size*/
  .hope-c-PJLV-iiKmFQI-css {
    width: 70px !important;
    flex: 0 0 70px;
  }
  
  /*Modified*/
  .hope-c-PJLV-ifzpvXi-css {
    width: 170px !important;
    flex: 0 0 170px;
  }
  ```
- Before:
![CleanShot_2024-07-08_12-44-47](https://github.com/alist-org/alist/assets/33310255/2a5b2bae-97fd-4132-b0e9-eb489353f988)

- After:
![CleanShot_2024-07-08_12-43-59](https://github.com/alist-org/alist/assets/33310255/a1e5f6f6-6b12-4e70-80db-20fdf0d5b7e8)

**Comment by anwen-anyi** [comment]
Maybe you can set it like this :v:  
![image](https://github.com/alist-org/alist/assets/56105412/aace829e-9b6c-4b60-8309-5f57dbe49a96)

**Comment by Ender-Wang** [comment]
Right, I have tried this for a while and found it a little messy and then I made my own CSS, which leads me here :)

**Comment by itsHenry35** [comment]
I think adding a vertical dragging line to allow users to adjust the size would be a better idea, donno if someone has an idea for this.
