### ISSUE TITLE
希望能将cloudreve显示文件夹大小和缩略图功能分开

### ISSUE THREAD

**Issue by Ayazk726** [alist-org/alist#6721]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

-  当cloudreve文件数量很多或者大小很大时，计算文件夹大小会消耗大量的时间（有时甚至会504）的同时会让部署了cloudreve的服务器负载很高，希望分开功能只显示缩略图或者只显示文件夹大小

### Suggested solution / 实现思路

1. 我建议只在网格视图打开时才通过api请求缩略图url从而先显示出内容，谁都不想点进去一直转圈圈。
2. 目前的alist在获取完文件夹大小和缩略图url后，由于自动同步刷新的缘故会清空缓存导致重新发送请求获取，这会导致alist还未获取完url后就自动刷新，实际做了无用功。而cloudreve的api提供的缩略图url貌似是永久的可以考虑创建一个thumb_url字段写入数据库中永久保存，通过对比/api/v3/directory获得的文件id和thumb_url最后的文件id的一致性判断文件是否有被修改，加快缩略图的显示速度。
3. 获取文件夹大小功能建议删掉感觉没用。

**Comment by Simonzhang8** [comment]
？这个不是cloudreve的问题吗

**Comment by Ayazk726** [comment]
> ###
> [Jul 9, 2024](#issuecomment-2215854317)

1. 计算文件夹大小在文件夹内容很多时cr的反应确实很慢，我说实话这功能没什么用还特别影响响应速度可以删了。
2. 我非常不理解alist获取cr文件缩略图的逻辑，假如文件夹内有1w张图片alist必须列取完所有的缩略图url后才会显示而不是获取到url后立即显示，这会消耗大量的时间，这是cr那边的问题导致的吗？
