### ISSUE TITLE
Alist挂载阿里云open无法进入根目录展示全部云盘内容（资源库和备份盘已合并）

### ISSUE THREAD

**Issue by hztbhtbh** [alist-org/alist#6723]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Alist挂载阿里云open无法进入根目录展示全部云盘内容（资源库和备份盘已合并），
只能把所有文件夹和文件移动到备份文件（系统）文件夹下才能访问，放在外面就不行。
需要大佬更新维护升级版本。

### Suggested solution / 实现思路

清除云盘类型：资源库和备份盘 

### Additional context / 附件

![2](https://github.com/alist-org/alist/assets/104251804/797517fc-dcf8-44af-8a75-bf919c5a28fd)
![1](https://github.com/alist-org/alist/assets/104251804/c90a537c-dc34-4694-a045-5b29e075eb80)

**Comment by anwen-anyi** [comment]
在API 还是区分备份盘和资源库，并没有合并。

**Comment by hztbhtbh** [comment]
> 在API 还是区分备份盘和资源库，并没有合并。 ![image](https://private-user-images.githubusercontent.com/56105412/346910017-76e06f14-b01c-4475-aead-00458934e738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTk2MzcsIm5iZiI6MTcyMDUxOTMzNywicGF0aCI6Ii81NjEwNTQxMi8zNDY5MTAwMTctNzZlMDZmMTQtYjAxYy00NDc1LWFlYWQtMDA0NTg5MzRlNzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEwMDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTk3YzU1YmYxYmY4M2YzYjk0NGQwNWJiMDViMDFkNzhkZDliOGFiOGIyMWM0NzM5YzIwYmZhYTAxNzlmYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-v8cMkoAyIjvtprR1HW0s8041oiA8OI1ExaS7fAImuA)

阿里云盘webdav插件中的云盘根目录保持默认的斜杠，
和Alist插件添加的阿里云盘open默认云盘类型
都加载不到备份文件以外的文件，是不是需要修改？
![1](https://github.com/alist-org/alist/assets/104251804/9dd8604d-6f5c-4a48-8429-c9f74d38e6b6)
![2](https://github.com/alist-org/alist/assets/104251804/8e73836a-8ba0-484a-bfda-05668cefe8b8)

**Comment by anwen-anyi** [comment]
云盘类型你改成资源库吖。

**Comment by hztbhtbh** [comment]
> 云盘类型你改成资源库吖。
我改了以后也一样打开就直接进入备份文件夹里面去了，这个外面的文件夹都看不到
是不是以后文件都要放到备份文件夹下才能行，我纠结的就是这个
![44](https://github.com/alist-org/alist/assets/104251804/336b87c6-cf40-4c01-824f-652cb59395ac)
![333](https://github.com/alist-org/alist/assets/104251804/dcb98f31-7f93-42c2-ae3e-812238220819)

**Comment by hztbhtbh** [comment]
> > 都加载不到备份文件之外的文件，是不是需要修改？
> 
> 云盘类型你改成的资源库。

我改了资源盘或者备份盘以后打开都直接跳转到备份文件夹里面去了，这个外面的文件夹都看不到
是不是以后文件都要放到备份文件夹下才能行，我纠结的就是这个
![1111](https://github.com/alist-org/alist/assets/104251804/cc2a95c1-1825-40b3-84ce-98f59b32f519)
![2222](https://github.com/alist-org/alist/assets/104251804/c4e6f11e-d58c-470e-aa0f-8f6016d4ad2f)

**Comment by anwen-anyi** [comment]
改成资源库之后 保存，回到网盘页面，右下角选项顶部刷新

**Comment by hztbhtbh** [comment]
> 改成资源库之后 保存，回到网盘页面，右下角选项顶部刷新
> 
> > 是不是以后文件都要放到备份文件夹下才能行，我纠结的就是这个
> 
> 不是，你修改后看到的还是备份盘里面文件，是你缓存问题，照着上面给你的刷新一下就好

你好，按照你的设置了，我Alist是安装在X86软路由上的
云盘类型设置默认和备份盘后刷新都直接进备份文件夹下的
云盘类型设置资源盘后刷新后看到除备份文件夹以外的文件夹
就没有看到全部文件夹的如下图
![1111](https://github.com/alist-org/alist/assets/104251804/13f68bc8-a839-4cbc-acf9-51e419c8a31d)

**Comment by anwen-anyi** [comment]
TG找我

**Comment by anwen-anyi** [comment]
> 云盘类型设置资源盘后刷新后看到除备份文件夹以外的文件夹，就没有看到全部文件夹的如下图

没错就是这样设计的

**Comment by hztbhtbh** [comment]
> 没错就是这样设计的

好的，谢谢。要是看电影就把电影文件移动到-备份文件夹-就能访问。

**Comment by anwen-anyi** [comment]
> > 没错就是这样设计的
> 
> 好的，谢谢。要是看电影就把电影文件移动到-备份文件夹-就能访问。

？ 你网络转存的电影你存储到资源库就好，为什么要保存到备份盘呢~

**Comment by hztbhtbh** [comment]
> ？ 你网络转存的电影你存储到资源库就好，为什么要保存到备份盘呢~

现在没有资源库了，文件夹都看不到了，只有系统生成一个备份文件夹，你都删除不了，

**Comment by anwen-anyi** [comment]
> > ？ 你网络转存的电影你存储到资源库就好，为什么要保存到备份盘呢~
> 
> 现在没有资源库了，文件夹都看不到了，只有系统生成一个备份文件夹，你都删除不了，

资源库就是你正常的文件夹，非备份文件内容就是，除了这个备份文件是其它的都是属于资源库
![image](https://github.com/alist-org/alist/assets/56105412/39fd1bce-e2a1-40e8-b986-a36544f94fb9)

**Comment by hztbhtbh** [comment]
> 资源库就是你正常的文件夹，非备份文件内容就是，除了这个备份文件是其它的都是属于资源库

我知道了，关键还有一个问题就是我在X86软路由上又安装阿里云webdav插件，这个默认根目录就是备份文件夹，其它文件夹看不到
![1](https://github.com/alist-org/alist/assets/104251804/95248eb3-1c05-4b12-b1bf-ffbde01e83e6)
打开网址http://192.168.5.1:8080/后显示如下：
![66](https://github.com/alist-org/alist/assets/104251804/78d054c4-c3bc-4c90-a86d-211e42b170a8)

**Comment by anwen-anyi** [comment]
> > 资源库就是你正常的文件夹，非备份文件内容就是，除了这个备份文件是其它的都是属于资源库
> 
> 我知道了，关键还有一个问题就是我在X86软路由上又安装阿里云webdav插件，这个默认根目录就是备份文件夹，其它文件夹看不到 ![1](https://private-user-images.githubusercontent.com/104251804/346960837-95248eb3-1c05-4b12-b1bf-ffbde01e83e6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mjk3ODksIm5iZiI6MTcyMDUyOTQ4OSwicGF0aCI6Ii8xMDQyNTE4MDQvMzQ2OTYwODM3LTk1MjQ4ZWIzLTFjMDUtNGIxMi1iMWJmLWZmYmRlMDFlODNlNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjUxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWI4MGMzZTI4OTZiMjgxZDBhMmZhZDAwMDkyNjJhY2VlYzE4N2YwOWRlMTU3N2U0ODEyY2YzYzA4MGJlZWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m36y6mDRvR9bpZHjfIPDoRqgjeYXVJ5sWvODPmsZJxg) 打开网址[http://192.168.5.1:8080/后显示如下：](http://192.168.5.1:8080/%E5%90%8E%E6%98%BE%E7%A4%BA%E5%A6%82%E4%B8%8B%EF%BC%9A) ![66](https://private-user-images.githubusercontent.com/104251804/346962705-78d054c4-c3bc-4c90-a86d-211e42b170a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mjk3ODksIm5iZiI6MTcyMDUyOTQ4OSwicGF0aCI6Ii8xMDQyNTE4MDQvMzQ2OTYyNzA1LTc4ZDA1NGM0LWMzYmMtNGM5MC1hODZkLTIxMWU0MmIxNzBhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjUxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWZhNjMwOTI2OTJhZjdkMmEyOWU1ZDc5M2MxOGIzZTRhNTYyMjQ0NDVlOTY3ZDM2YTFlNTVjMTVkMDdlMzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Un1CLGqqdS2Coyh2dQyvdnQH14H_X3PoaegYK-pb-U4)

这个你得去问`阿里云webdav` 我不是很懂这个 :joy_cat:

**Comment by hztbhtbh** [comment]
> 这个你得去问`阿里云webdav` 我不是很懂这个 😹 不是AList开发的

好的，谢谢你了

**Comment by wyndam** [comment]
> > ？ 你网络转存的电影你存储到资源库就好，为什么要保存到备份盘呢~
> 
> 现在没有资源库了，文件夹都看不到了，只有系统生成一个备份文件夹，你都删除不了，

是的，我找不到资源库这个选项了，无法安装小雅了

**Comment by hztbhtbh** [comment]
后来问题早就解决了，是要你用手机扫码获取Refresh Token的时候在手机上取消备份盘勾选，在允许获取的Refresh Token就OK了。

![Image](https://github.com/user-attachments/assets/219fc6ab-bc93-48e3-9566-80634a0c2a59)

![Image](https://github.com/user-attachments/assets/aaf7919c-4998-45e9-8a75-809137c339c3)
