### ISSUE TITLE
是否考虑支持自定义PWA应用的图标和名称

### ISSUE THREAD

**Issue by NXY666** [alist-org/alist#6724]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在的PWA应用安装时是直接用Alist和默认图标。
是否可以使用用户在设置中自定义的名称和图标？

### Suggested solution / 实现思路

![image](https://github.com/alist-org/alist/assets/62371554/445c0e8d-c7b7-4ea3-a44f-d6b1d3c74d7d)
我没开发过PWA应用，但是我认为只需要动态地改变manifest就行？

### Additional context / 附件

![image](https://github.com/alist-org/alist/assets/62371554/f96228b0-66d9-4a61-86e7-35859f2413d6)

电脑似乎是可以重命名并且换图标的，但是通过手机Chrome安装后就真改不了了 :(

目前我没有找到和PWA应用相关的文档。如果这个功能已经存在了，请告诉我应该如何操作，非常感谢！

**Comment by anwen-anyi** [comment]
目前PWA没有自定义，是固定内容写在前端 `alist-web/index.html`
- https://github.com/alist-org/alist-web/blob/c73b5205bfcba468fa25b0e7e49b542defb1d87e/index.html#L14-L17

**Comment by Simonzhang8** [comment]
修改PWA图标和名称是修改这个mainifest.json，不是安稳说的index.html，具体可以参考这条 #3229 
安稳截取的index.html里这段，是设置苹果手机显示图标的

**Comment by anwen-anyi** [comment]
> 修改PWA图标和名称是修改这个mainifest.json，把name和src字段修改成你需要的就可以了。具体可以参考这条 #3229 ，不是安稳说的index.html
> 
> 安稳截取的index.html里这段，是设置苹果手机显示图标的

对 草率了 我忘记了安卓也能设置pwa😂

**Comment by NXY666** [comment]
> 对 草率了 我忘记了安卓也能设置pwa😂

目前我使用的是自动脚本安装的alist，似乎无法直接修改这个文件？

嗯，如果方便的话，还是希望能够有个自定义选项☺️

**Comment by anwen-anyi** [comment]
> 嗯，如果方便的话，还是希望能够有个自定义选项☺️

看了下大概好像是懂了你可以新建一个`alistpwa.webmanifest`的文件，然后在后台自定义引用它

引用示例：
```html
<link rel="manifest" href="https://www.xxx.com/alistpwa.webmanifest" />
```
也可以放在AList里面然后右键文件填写AList的链接


`alistpwa.webmanifest`内容如下自己填写就行，具体每个参数都是什么意思自己后续调整
```json
{
  "name": "Alist Progressive Web App",
  "short_name": "AlistPWA",
  "description": "Progressive Web App for alist.",
  "icons": [
    {
      "src": "icons/icon-32.png",
      "sizes": "32x32",
      "type": "image/png"
    },
    {
      "src": "icons/icon-512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "start_url": "/",
  "display": "fullscreen",
  "theme_color": "#B12A34",
  "background_color": "#B12A34"
}
```
`icons`：可以设置多个，如果你就设置一个删掉一个就行 尺寸自己选择

## 示例、演示图
![image](https://github.com/alist-org/alist/assets/56105412/864055ec-93d1-4419-baca-381e76c7a5c0)
![%BE}YKY4EJ $8AJ~4QQ5{L8_tmb](https://github.com/alist-org/alist/assets/56105412/19e3ecc4-4d2b-44e9-84bd-c3859ad5c6db)

## 参数示意（from ChatGPT）
这些参数是在 Progressive Web App 清单（manifest）中使用的关键字段，用于定义 Web 应用的各种属性。

1. **name**：这是 Web 应用的全名，通常是应用的正式名称。

2. **short_name**：这是 Web 应用的简称或缩写，用于在有限的空间内显示应用名称，比如设备主屏幕上的图标。

3. **description**：描述字段用于提供对 Web 应用的简要说明，通常在用户查看应用详细信息时显示。

4. **start_url**：指定用户打开应用时所显示的起始 URL。这有助于确保用户添加到主屏幕的应用可以以正确的方式打开。

5. **display**：决定了应用的显示模式，可以是 "fullscreen"、"standalone"、"minimal-ui" 或 "browser"。这一参数可以决定应用的外观以及用户与应用交互的方式。

6. **theme_color**：指定应用的主题色，可以影响浏览器工具栏、状态栏或者其他系统界面元素的颜色。

7. **background_color**：定义应用加载时所显示的背景色，可以确保在应用加载之前展示与应用风格一致的背景。

## 后续
就是没办法设置iOS的，安卓的倒是可以生效，后续试试看将源码index.html的去掉再设置能不能生效 :joy_cat: 
- 主要是图标设置了不生效，应用名称倒是生效的。

**Comment by Simonzhang8** [comment]
> ## 后续
> 就是没办法设置iOS的，安卓的倒是可以生效，后续试试看将源码index.html的去掉再设置能不能生效 😹
> 
> * 主要是图标设置了不生效，应用名称倒是生效的。

其实把安稳你前面引用的<a href="https://github.com/alist-org/alist-web/blob/c73b5205bfcba468fa25b0e7e49b542defb1d87e/index.html#L14-L17">index.html</a>里面14-17行修改好图标地址后添加到后台的自定义头部里，iOS的图标也可以生效

**Comment by anwen-anyi** [comment]
> > ## 后续
> > 就是没办法设置iOS的，安卓的倒是可以生效，后续试试看将源码index.html的去掉再设置能不能生效 😹
> > 
> > * 主要是图标设置了不生效，应用名称倒是生效的。
> 
> 其实把安稳你前面引用的[index.html](https://github.com/alist-org/alist-web/blob/c73b5205bfcba468fa25b0e7e49b542defb1d87e/index.html#L14-L17)里面14-17行修改好图标地址后拷贝到后台的自定义头部里，iOS的图标也可以生效（实测OK）

还得是你~ 果然可以 :star_struck:

**Comment by NXY666** [comment]
> 看了下大概好像是懂了你可以新建一个`alistpwa.webmanifest`的文件，然后在后台自定义引用它
> 
> 引用示例：
> ```html
> <link rel="manifest" href="https://www.xxx.com/alistpwa.webmanifest" />
> ```
> 也可以放在AList里面然后右键文件填写AList的链接
> 
> 
> `alistpwa.webmanifest`内容如下自己填写就行，具体每个参数都是什么意思自己后续调整
> ```json
> {
>   "name": "Alist Progressive Web App",
>   "short_name": "AlistPWA",
>   "description": "Progressive Web App for alist.",
>   "icons": [
>     {
>       "src": "icons/icon-32.png",
>       "sizes": "32x32",
>       "type": "image/png"
>     },
>     {
>       "src": "icons/icon-512.png",
>       "sizes": "512x512",
>       "type": "image/png"
>     }
>   ],
>   "start_url": "/",
>   "display": "fullscreen",
>   "theme_color": "#B12A34",
>   "background_color": "#B12A34"
> }
> ```
> - `icons`：可以设置多个，如果你就设置一个删掉一个就行 尺寸自己选择
> - `sizes`尺寸：可以有多个，也可以将多个不同尺寸填写进去，可以单独写尺寸，也可以`"sizes": "64x64 32x32 24x24 16x16",`这样写多个不同尺寸
>    - `64x64` `32x32` `24x24` `16x16` `128x128` `256x256` `512x512`
> - `type`类型：也有很多不同的 一般图标都是`"type": "image/png"`这样应该
>    - 全部类型`image/x-icon`、`image/png`、`image/svg+xml`、`image/gif`、`image/jpeg 或 image/jpg`
> 
> -----
> 
> ## 示例、演示图
> ![image](https://github.com/alist-org/alist/assets/56105412/864055ec-93d1-4419-baca-381e76c7a5c0)
> ![%BE}YKY4EJ $8AJ~4QQ5{L8_tmb](https://github.com/alist-org/alist/assets/56105412/19e3ecc4-4d2b-44e9-84bd-c3859ad5c6db)
> 
> ## 参数示意（from ChatGPT）
> 这些参数是在 Progressive Web App 清单（manifest）中使用的关键字段，用于定义 Web 应用的各种属性。
> 
> 1. **name**：这是 Web 应用的全名，通常是应用的正式名称。
> 
> 2. **short_name**：这是 Web 应用的简称或缩写，用于在有限的空间内显示应用名称，比如设备主屏幕上的图标。
> 
> 3. **description**：描述字段用于提供对 Web 应用的简要说明，通常在用户查看应用详细信息时显示。
> 
> 4. **start_url**：指定用户打开应用时所显示的起始 URL。这有助于确保用户添加到主屏幕的应用可以以正确的方式打开。
> 
> 5. **display**：决定了应用的显示模式，可以是 "fullscreen"、"standalone"、"minimal-ui" 或 "browser"。这一参数可以决定应用的外观以及用户与应用交互的方式。
> 
> 6. **theme_color**：指定应用的主题色，可以影响浏览器工具栏、状态栏或者其他系统界面元素的颜色。
> 
> 7. **background_color**：定义应用加载时所显示的背景色，可以确保在应用加载之前展示与应用风格一致的背景。
> 
> ## 后续
> ~~就是没办法设置iOS的，安卓的倒是可以生效，后续试试看将源码index.html的去掉再设置能不能生效~~ :joy_cat: 
> - ~~主要是图标设置了不生效，应用名称倒是生效的。~~
> 
> 已解决 https://github.com/alist-org/alist/issues/6724#issuecomment-2220328471
> 在AList后台自定义头部填写如下内容，可以替换掉AList index.html默认内容中的图标logo样式
> ```html
> <linkrel="apple-touch-icon"href="images_url"/>
> ```

成功了，非常感谢！

不过还是遇到了一些麻烦，因为我启用了全局sign，在重启alist后所有分享链接都会失效，因此我无法在alist中存放manifest。

所以我只能找另一个地方托管我的manifest，然后该死的Chrome说我cross origin，部分配置被强制忽略了😓

个人觉得，或许还是alist原生支持自定义比较方便一点，如果你们有空，可以加一个 :)
