### ISSUE TITLE
针对大文件无法下载

### ISSUE THREAD

**Issue by xKarida** [alist-org/alist#6725]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

quark

### Describe the bug / 问题描述

只能下载小文件，大文件直接失败，如果是视频，则无法观看或下载

### Reproduction / 复现链接

无法提供

### Config / 配置

[config.json](https://github.com/user-attachments/files/16143603/config.json)

### Logs / 日志

[log.log](https://github.com/user-attachments/files/16143845/log.log)

**Comment by xKarida** [comment]
> #4981 推荐放过路由器吧

我不是部署在路由上，设备用的是Nas

**Comment by houruomu** [comment]
> > > #4981 推荐放过路由器吧
> > 
> > 
> > 我不是部署在路由上，设备用的是Nas
> 
> nas也一样，如果配置太低就这样

到底需要多高的配置，一般的nas/路由torrent好几tb的东西都没问题，这还是和很多节点同时通信。到底是什么导致alist处理大文件吃性能这么严重？
