### ISSUE TITLE
使用chrome浏览器，在文件更新后，重新下载下来的仍然是浏览器缓存的旧文件，得清除浏览器缓存才能得到更新后的文件

### ISSUE THREAD

**Issue by Demprace** [alist-org/alist#6731]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

SMB/FTP

### Describe the bug / 问题描述

已经下载过一次的文件，我在更新替换该文件之后，再重新下载得到的还是之前的文件。
得清除浏览器缓存之后再重新下载才能得到正确的更新后的文件，Ctrl+F5强制刷新都不行。
不太确定是bug还是我什么地方的设置有问题。

### Reproduction / 复现链接

N/A

### Config / 配置

N/A

### Logs / 日志

N/A

**Comment by anwen-anyi** [comment]
使用这个刷新呢
![image](https://github.com/alist-org/alist/assets/56105412/fb7d45a2-8500-41a1-8e27-9306c8a7897a)
