### ISSUE TITLE
直链链接 访问不存在的文件 / 路径不正确 时, 状态码为200而不是404

### ISSUE THREAD

**Issue by cinyan10** [alist-org/alist#6732]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

<img width="848" alt="image" src="https://github.com/alist-org/alist/assets/111641699/1fe0258d-1586-42a1-b020-c3dc2e3896e5">
如图
希望能有设置选项可以使其像普通网站的直链一样访问不存在的文件返回404

### Reproduction / 复现链接

https://dl.axekz.com/d/fastdl/csgo/maps/kz_p2.bsp.bz2

### Config / 配置

<img width="325" alt="image" src="https://github.com/alist-org/alist/assets/111641699/d7ed7205-b105-485d-8c39-6a7a823de4cc">

**Comment by Deepsea-CN** [comment]
我这访问显示是304，不是200
