### ISSUE TITLE
123网盘是否可使用手机app端令牌进行挂载，以绕过PC端10G 下载限制

### ISSUE THREAD

**Issue by abandonstudy** [alist-org/alist#6733]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题

**Comment by anwen-anyi** [comment]
123盯着呢 哈哈 这边发布他那边就修复 :joy_cat:
