### ISSUE TITLE
无法识别139中国移动网盘根文件夹id，报错“个人云未知异常”

### ISSUE THREAD

**Issue by jakkpop** [alist-org/alist#6735]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

所有v3版本

### Driver used / 使用的存储驱动

中国移动云盘

### Describe the bug / 问题描述

已经按教程获取了currentCatalogID，但一直报错“个人云未知问题”。
安装了多个版本，也是如此。
但用了v2以前的保存的根文件夹id，却可以了，不过是几个月前的文件列表，无法更新到最新的文件列表，而且更奇怪的是云盘那里已经删除的文件，居然还可以下载，这个是中国移动云盘的问题，还是alist的？

### Reproduction / 复现链接

![WeChat截图_20240711010201](https://github.com/alist-org/alist/assets/30544872/23eb0e2e-5fbc-4ce4-a98e-2e8ea165bc66)
![WeChat截图_20240711010326](https://github.com/alist-org/alist/assets/30544872/6b9ec748-14c2-4bb5-acd8-829c31ed58f8)

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "WtAbUoqH1UeyaMg9",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

**Comment by jakkpop** [comment]
> 正常 应该是你没抓对 ![photo_2024-07-11_07-44-43](https://private-user-images.githubusercontent.com/24273319/347635379-72210bfb-a36d-4209-8511-ec364efeb4c8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODAyMzEsIm5iZiI6MTcyMDY3OTkzMSwicGF0aCI6Ii8yNDI3MzMxOS8zNDc2MzUzNzktNzIyMTBiZmItYTM2ZC00MjA5LTg1MTEtZWMzNjRlZmViNGM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA2Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YmNkN2E0MTIxNjVjOGY4YTY2Yzc0MWYwYWUwNWYzYWIwYzRkYTBmZjlhZWUxNjRiMTRiOGIyZWI3MjFiY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HRIJ_lY2S4RnN1XWCk6F_gFFONTAPFAsdss42qi50vA)

我的f12里面找不到getDisk，网盘已经用了很多年了。

**Comment by anwen-anyi** [comment]
你试试看 `新个人云`类型，根据文档获取新个人云的cookie
![image](https://github.com/alist-org/alist/assets/56105412/9def4400-28ec-44b2-8738-f7f105e4a1f9)

**Comment by jakkpop** [comment]
> 你试试看 `新个人云`类型，根据文档获取新个人云的cookie ![image](https://private-user-images.githubusercontent.com/56105412/347780900-9def4400-28ec-44b2-8738-f7f105e4a1f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTQwOTgsIm5iZiI6MTcyMDY5Mzc5OCwicGF0aCI6Ii81NjEwNTQxMi8zNDc3ODA5MDAtOWRlZjQ0MDAtMjhlYy00NGIyLTg3MzgtZjdmMTA1ZTRhMWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEwMjk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMTRlYWE5NGU3NDVlZDY3MWM3NzMwNGMxMDYwOWJiZTg4YmZkOGU5YTExYTBjYjI4MDMyOTY2YjViZDhiZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YMXWTICULWyNmHDzSHuEanFMplwEMLnosCSV5wLFzo0)

就是按照新个人云获取的，然后显示“个人云未知异常”

**Comment by jakkpop** [comment]
> > > > > 正常 应该是你没抓对 ![photo_2024-07-11_07-44-43](https://private-user-images.githubusercontent.com/24273319/347635379-72210bfb-a36d-4209-8511-ec364efeb4c8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODAyMzEsIm5iZiI6MTcyMDY3OTkzMSwicGF0aCI6Ii8yNDI3MzMxOS8zNDc2MzUzNzktNzIyMTBiZmItYTM2ZC00MjA5LTg1MTEtZWMzNjRlZmViNGM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA2Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YmNkN2E0MTIxNjVjOGY4YTY2Yzc0MWYwYWUwNWYzYWIwYzRkYTBmZjlhZWUxNjRiMTRiOGIyZWI3MjFiY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HRIJ_lY2S4RnN1XWCk6F_gFFONTAPFAsdss42qi50vA)
> > > > 
> > > > 
> > > > 我的f12里面找不到getDisk，网盘已经用了很多年了。
> > > > 咋找不到
> > > > ![IMG_20240711_123525_196](https://private-user-images.githubusercontent.com/24273319/347721824-21617e24-2e3f-4547-925a-3c27c743ef50.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODQzODIsIm5iZiI6MTcyMDY4NDA4MiwicGF0aCI6Ii8yNDI3MzMxOS8zNDc3MjE4MjQtMjE2MTdlMjQtMmUzZi00NTQ3LTkyNWEtM2MyN2M3NDNlZjUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA3NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMGE1Zjk3MzJhNjFjNTJkZTNlM2FjYWU1NjQxMjg5Y2E5YWMzZjE1NGM0ZDJjYTkzMjNmZTY3N2JiMzEwZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.690KvSKkrK3T0yTEecJHGI7iOgECpViKY2hxgDUMliU)
> > 
> > 
> > 我也觉得很奇怪，但事实上就是没有了，而且不是最近，是去年开始就找不到了，换了几个浏览器都没有，只不过之前只需要换Authorization还可以苟活，最近就无法使用了。。。 ![WeChat截图_20240711154848](https://private-user-images.githubusercontent.com/30544872/347728599-2d6a9f2f-b437-4dcd-974d-ce95c9038ae8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODgxMzgsIm5iZiI6MTcyMDY4NzgzOCwicGF0aCI6Ii8zMDU0NDg3Mi8zNDc3Mjg1OTktMmQ2YTlmMmYtYjQzNy00ZGNkLTk3NGQtY2U5NWM5MDM4YWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA4NTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDM0ODEzMmUxOGFiYjY1M2NjZDdlNDU5NGI0ZmRkNzY1ZGU2ZjdkMmM4ZDBkMTg4YTViYjMxYWEwM2RmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.22j3hxcpGQIjxOuGSpQjSQx3vCJdBKVlV23SGezb_ak)
> 
> > > > > 正常 应该是你没抓对 ![photo_2024-07-11_07-44-43](https://private-user-images.githubusercontent.com/24273319/347635379-72210bfb-a36d-4209-8511-ec364efeb4c8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODAyMzEsIm5iZiI6MTcyMDY3OTkzMSwicGF0aCI6Ii8yNDI3MzMxOS8zNDc2MzUzNzktNzIyMTBiZmItYTM2ZC00MjA5LTg1MTEtZWMzNjRlZmViNGM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA2Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YmNkN2E0MTIxNjVjOGY4YTY2Yzc0MWYwYWUwNWYzYWIwYzRkYTBmZjlhZWUxNjRiMTRiOGIyZWI3MjFiY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HRIJ_lY2S4RnN1XWCk6F_gFFONTAPFAsdss42qi50vA)
> > > > 
> > > > 
> > > > 我的f12里面找不到getDisk，网盘已经用了很多年了。
> > > > 咋找不到
> > > > ![IMG_20240711_123525_196](https://private-user-images.githubusercontent.com/24273319/347721824-21617e24-2e3f-4547-925a-3c27c743ef50.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODQzODIsIm5iZiI6MTcyMDY4NDA4MiwicGF0aCI6Ii8yNDI3MzMxOS8zNDc3MjE4MjQtMjE2MTdlMjQtMmUzZi00NTQ3LTkyNWEtM2MyN2M3NDNlZjUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA3NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMGE1Zjk3MzJhNjFjNTJkZTNlM2FjYWU1NjQxMjg5Y2E5YWMzZjE1NGM0ZDJjYTkzMjNmZTY3N2JiMzEwZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.690KvSKkrK3T0yTEecJHGI7iOgECpViKY2hxgDUMliU)
> > 
> > 
> > 我也觉得很奇怪，但事实上就是没有了，而且不是最近，是去年开始就找不到了，换了几个浏览器都没有，只不过之前只需要换Authorization还可以苟活，最近就无法使用了。。。 ![WeChat截图_20240711154848](https://private-user-images.githubusercontent.com/30544872/347728599-2d6a9f2f-b437-4dcd-974d-ce95c9038ae8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODgxMzgsIm5iZiI6MTcyMDY4NzgzOCwicGF0aCI6Ii8zMDU0NDg3Mi8zNDc3Mjg1OTktMmQ2YTlmMmYtYjQzNy00ZGNkLTk3NGQtY2U5NWM5MDM4YWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA4NTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDM0ODEzMmUxOGFiYjY1M2NjZDdlNDU5NGI0ZmRkNzY1ZGU2ZjdkMmM4ZDBkMTg4YTViYjMxYWEwM2RmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.22j3hxcpGQIjxOuGSpQjSQx3vCJdBKVlV23SGezb_ak)
> 
> 你在文件夹里看的吗？

是的，我有几个号码，刚才测试了，有两个有getdisk，有两个没有，麻了，不知道是不是被限制了。

**Comment by anwen-anyi** [comment]
你把所有的中国移动云盘挂载的都删除，然后去重新添加，添加后后右下角刷新一下

1. 有`getDisk`请求的就 类型就选择`个人云`
2. 没有`getDisk`请求的就去按照文档中新个人云如何获取`Authorization`的方式来获取，类型选择`新个人云`

在获取`getDisk`请求之前先把开发者模式打开，清掉所有请求，刷新一下网页，就就按照个人云选择，没有就按照新个人云

填写好配置截图一下记得打码

**Comment by anwen-anyi** [comment]
直接在原驱动编辑可能会提示 个人云异常，刚刚测试的。
然后删掉原驱动重新添加一个 把`Authorization`填进去就没问题了
![image](https://github.com/alist-org/alist/assets/56105412/d844e516-f360-4967-9e43-2ceaca2007ef)

**Comment by jakkpop** [comment]
> 你把所有的中国移动云盘挂载的都删除，然后去重新添加，添加后后右下角刷新一下
> 
> 1. 有`getDisk`请求的就 类型就选择`个人云`
> 2. 没有`getDisk`请求的就去按照文档中新个人云如何获取`Authorization`的方式来获取，类型选择`新个人云`
> 
> 在获取`getDisk`请求之前先把开发者模式打开，清掉所有请求，刷新一下网页，就就按照个人云选择，没有就按照新个人云
> 
> 填写好配置截图一下记得打码

还是没有getdisk，删掉重新添加后还是一样“个人云未知异常”
![WeChat截图_20240711191553](https://github.com/alist-org/alist/assets/30544872/f07d247b-bd97-4c9f-af40-35327a8fc3f2)

**Comment by anwen-anyi** [comment]
......都跟你说了 没有`getDisk`的去按照`新个人云`获取`Authorization` 你类型你也记得改一下啊 
![image](https://github.com/alist-org/alist/assets/56105412/3f8f1132-43c2-40b5-b46f-7552b696f806)

**Comment by jakkpop** [comment]
> ......都跟你说了 没有`getDisk`的去按照`新个人云`获取`Authorization` 你类型你也记得改一下啊
> 
> ![image](https://private-user-images.githubusercontent.com/56105412/347797182-06e38509-d7ac-4bb9-8005-4e21a8ecf569.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTcxNzIsIm5iZiI6MTcyMDY5Njg3MiwicGF0aCI6Ii81NjEwNTQxMi8zNDc3OTcxODItMDZlMzg1MDktZDdhYy00YmI5LTgwMDUtNGUyMWE4ZWNmNTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NzMyMjAxOTYwMzNjNzFhNTkyMWIzODM4Njk3ZDBhMzBiMTlkMzM3MmQ1OWQ0YjM3ZTg2NTk0MDYzYWNmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1oPM0XB6IGkkToJzNW1F2K9ndnAO4kmFQdvM-YxAnXE)

哦，谢谢！是要在类型那里选择“新的个人盘”，我都还不知道这里也更新了。。。
![WeChat截图_20240711192355](https://github.com/alist-org/alist/assets/30544872/a0a39a38-825d-4a9e-8426-63117676fc86)

**Comment by jakkpop** [comment]
> 你试试看 `新个人云`类型，根据文档获取新个人云的cookie ![image](https://private-user-images.githubusercontent.com/56105412/347780900-9def4400-28ec-44b2-8738-f7f105e4a1f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTc1MjksIm5iZiI6MTcyMDY5NzIyOSwicGF0aCI6Ii81NjEwNTQxMi8zNDc3ODA5MDAtOWRlZjQ0MDAtMjhlYy00NGIyLTg3MzgtZjdmMTA1ZTRhMWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMjcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZDAwNWMzNjkyMDYxNGQ4Y2U2N2U4MzhiNDRhZjk2OGM3NjRkMTRlMTk1NjA4OWQ4MzU3NjZmMjM4MTdkNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dDy9Z4d2NrCUDEUiabtE7NXnVL8KyS9dKmBbptaZNHo)

尴尬，原来你早就提醒我了，我一直没有注意到这里也改了！

**Comment by jakkpop** [comment]
not bug

**Comment by chopsticksbo** [comment]
把类型改成新的个人云就好了，中国移动云盘那里选择类型的时候更改一下就好，注意默认是个人云，要你自己选择
