### ISSUE TITLE
能否解决一下预览插件的缓存问题

### ISSUE THREAD

**Issue by Demprace** [alist-org/alist#6737]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

遇到的问题的就是PDF.j插件预览打开文件，在文件覆盖更新之后，再打开还是缓存的旧文件，下载的也是旧文件。
看到有其他朋友也提过OFFICE预览好像也有遇到这个问题。

我反复尝试，目前确认的。
1、pdf.js插件的，不管是预览还是下载，包括打开文件页面的下载和文件列表点右键下载，都会遇到缓存问题。
2、文本类的，预览和打开文件页面后的下载都能得到正确文件，在文件列表右键下载会遇到缓存问题。
3、没有预览插件的文件，打开文件页面后的下载可以得到正确文件，在文件列表右键下载会遇到缓存问题。

这个可能影响并不算大，更大的原因应该是浏览器或者那些插件的缓存机制造成的。但是遇到了真的很头疼。而且在文件列表直接右键下载在我试验的各种情况下也都有这个问题，这个地方跟插件就没什么关系了，还是希望能费心解决一下。

### Suggested solution / 实现思路

经过搜索了解到只要在文件下载链接里加入一个随机变量的参数，就能解决这个缓存问题。
是否可以考虑按此思路，给文件的下载链接加入一个随机变量的参数，不管是直接下载还是预览插件的缓存问题应该都能解决。

**Comment by Demprace** [comment]
> 打开签名试试
是说存储设置里的那个启用签名选项吗
我刚勾上试了，没能解决问题。

**Comment by Demprace** [comment]
> 打开签名试试

是说存储设置里的那个启用签名选项吗
我刚勾上试了，没能解决问题。

**Comment by Demprace** [comment]
> > > 打开签名试试
> > > 是说存储设置里的那个启用签名选项吗
> > > 我刚勾上试了，没能解决问题。
> 
> 搭建onlyoffice试试 不用自带的pdf

刚才可能是我操作失误，勾选启用签名有效。
我再仔细试一下，谢谢。

**Comment by Simonzhang8** [comment]
你用的是哪个存储？如果存储设置里有缓存过期时间，把它改成0以后再试试看？
![image](https://github.com/alist-org/alist/assets/165749751/15635e58-2811-46c9-9c3f-5a4fcd454daf)

**Comment by woshichenghaibo** [comment]
我从来没有预览成功过，我都不知道我的问题在哪，是自己还要搭建一个服务器用来放浏览插件吗？

**Comment by Simonzhang8** [comment]
> 我从来没有预览成功过，我都不知道我的问题在哪，是自己还要搭建一个服务器用来放浏览插件吗？

要看你具体预览的是什么文件以及存储的位置？

**Comment by Demprace** [comment]
> 打开签名试试

我有点懵了，那天打开了签名各位置测试都正常能获取到正确的文件了。
结果今天更新文件时，又出问题了。
文件列表右键下载，onlyoffice插件预览能获取到正确的文件。
pdf.js预览，点开文件后的download页面点下载按钮下载获取到的是本地缓存的文件。

**Comment by Demprace** [comment]
> 你用的是哪个存储？如果存储设置里有缓存过期时间，把它改成0以后再试试看？ ![image](https://private-user-images.githubusercontent.com/165749751/347831063-15635e58-2811-46c9-9c3f-5a4fcd454daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTMzNjgsIm5iZiI6MTcyMTgxMzA2OCwicGF0aCI6Ii8xNjU3NDk3NTEvMzQ3ODMxMDYzLTE1NjM1ZTU4LTI4MTEtNDZjOS05YzNmLTVhNGZjZDQ1NGRhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwOTI0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2IyMzBjZjVlZDQwYmQ1YmE0MWNmOGJlZGUxNGY0YzlhM2VhMmNiN2JlNTU1NzNmNmQzMjg1MWU1NzA5OWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hqaDLwFmFCs4TiKN5K9yiGk0w8JAgC713MnKt9KeCbw)

SMB，没有缓存时间相关的设置项。

**Comment by Demprace** [comment]
> 我从来没有预览成功过，我都不知道我的问题在哪，是自己还要搭建一个服务器用来放浏览插件吗？

不管插件在本地还是云端，它能从你的文件服务器取到文件就可以。

**Comment by Demprace** [comment]
> > 我从来没有预览成功过，我都不知道我的问题在哪，是自己还要搭建一个服务器用来放浏览插件吗？
> 
> 不管插件在本地还是云端，它能从你的文件服务器取到文件就可以。

我是alist架在内网，所以插件也就只有在内网搭才行。

**Comment by woshichenghaibo** [comment]
没有nginx如何使用onlyoffice？我就是单纯刀客
________________________________
发件人: pongfcnkl ***@***.***>
发送时间: 2024年7月25日 7:33
收件人: alist-org/alist ***@***.***>
抄送: woshichenghaibo ***@***.***>; Comment ***@***.***>
主题: Re: [alist-org/alist] 能否解决一下预览插件的缓存问题 (Issue #6737)


onlyoffice

你把pdf也改成onlyoffice呢・

―

**Comment by Simonzhang8** [comment]
> 没有nginx如何使用onlyoffice？我就是单纯刀客

docker就够了，docker拉取onlyoffice的镜像就行了，最后填到alist里面写ip+端口就行

**Comment by Demprace** [comment]
> > onlyoffice
> 
> 你把pdf也改成onlyoffice呢·

改到onlyoffice预览没问题，但是下载的时候有问题。
不只是这些文档类的。其他没预览的点开文件后的页面，用下载按钮下载会有缓存问题。在文件列表右键下载没有缓存问题。

**Comment by Demprace** [comment]
> > > > onlyoffice
> > > 
> > > 
> > > 你把pdf也改成onlyoffice呢·
> > 
> > 
> > 改到onlyoffice预览没问题，但是下载的时候有问题。 不只是这些文档类的。其他没预览的点开文件后的页面，用下载按钮下载会有缓存问题。在文件列表右键下载没有缓存问题。
> 
> 你是不是反代了？

路由设置内网域名到群晖，然后用群晖系统设置里的反代服务器设的二级域名到alist。
