### ISSUE TITLE
你好 阿里网盘更新6.0合并备份和资源盘，alist不识别阿里网盘文件下面文件夹的ID,一定要放到备份文件里面才能识别ID

### ISSUE THREAD

**Issue by myzhongqiang** [alist-org/alist#6739]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

阿里云盘OPEN

### Describe the bug / 问题描述

你好 现在阿里网盘更新6.0合并备份和资源盘，alist不识别阿里网盘文件下面文件夹的ID,一定要放到备份文件里面才能识别ID，是不是你这边要更新一下alist对接阿里网盘文件下面的文件夹？？

### Reproduction / 复现链接

你好 阿里网盘更新6.0合并备份和资源盘，alist不识别阿里网盘文件下面文件夹的ID,一定要放到备份文件里面才能识别ID

### Config / 配置

你好 阿里网盘更新6.0合并备份和资源盘，alist不识别阿里网盘文件下面文件夹的ID,一定要放到备份文件里面才能识别ID

**Comment by Simonzhang8** [comment]
后台添加阿里云盘Open存储时，云盘类型选择资源库即可
不过确实更新之后这个逻辑有变化，所以建议开发者们把“默认”就设置成资源库吧

**Comment by myzhongqiang** [comment]
> 后台添加阿里云盘OpenStorage时，云盘类型选择资源库即可不过 确实更新之后这个逻辑有变化，所以建议开发者把“默认”就设置成资源库吧

原来如此感谢指导
