### ISSUE TITLE
阿里云盘Open中云盘类型建议将默认修改为资源库

### ISSUE THREAD

**Issue by Simonzhang8** [alist-org/alist#6741]
阿里云盘6.0更新后合并了备份盘和资源库为文件，且目前文件显示的是资源库内容，备份盘在阿里云盘官方显示为首页的“备份文件”文件夹。
但是目前Alist中添加阿里云盘Open时，云盘类型的默认对大部分用户而言是备份盘，这会导致很多用户尤其是新用户添加后找不到所存储的文件。因此建议将云盘类型的默认逻辑设置为与资源库相同，或直接取消默认由资源库替代默认

> 后台添加阿里云盘Open存储时，云盘类型选择资源库即可
> 不过确实更新之后这个逻辑有变化，所以建议开发者们把“默认”就设置成资源库吧

_Originally posted by @Simonzhang8 in https://github.com/alist-org/alist/issues/6739#issuecomment-2221982520_

**Comment by Simonzhang8** [comment]
有没有管理员可以帮忙添加个label，bug或enhancement都行，不知道为什么label不见了

**Comment by xhofe** [comment]
![image](https://github.com/user-attachments/assets/ac7f65ce-7b3b-4a4f-ba94-fb13f3a4841f)

**Comment by gdzjy** [comment]
我就是吃了这个亏，alist旧版本不用设置默认是资源库。 
前端时间更新版本后，没注意看，默认备份到阿里的备份文件夹了。
导致自动上传的数据错乱，现在云盘里有2份都是不全的备份资料了。
