### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by happygithub007** [alist-org/alist#6742]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0-x86_64

### Driver used / 使用的存储驱动

AList V3

### Describe the bug / 问题描述

访问： http://xxxxx:5678/提示failed get storage: please add a storage first.

### Reproduction / 复现链接

https://github.com/alist-org/alist

### Config / 配置

http://192.168.5.1:5678/

### Logs / 日志

🔧[31mERRO🔧[0m[2024-07-11 05:23:11] fs/list: request failed,code: 500, message: failed get storage: please add a storage first.
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	github.com/alist-org/alist/v3/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	github.com/alist-org/alist/v3/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	github.com/alist-org/alist/v3/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	github.com/alist-org/alist/v3/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	github.com/alist-org/alist/v3/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	github.com/alist-org/alist/v3/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	github.com/alist-org/alist/v3/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.(*conn).serve
	net/http/server.go:2009
runtime.goexit
	runtime/asm_amd64.s:1650 
🔧[31mERRO🔧[0m[2024-07-11 05:23:11] failed list /小雅: request failed,code: 500, message: failed get storage: please add a storage first.
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	github.com/alist-org/alist/v3/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	github.com/alist-org/alist/v3/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	github.com/alist-org/alist/v3/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	github.com/alist-org/alist/v3/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	github.com/alist-org/alist/v3/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	github.com/alist-org/alist/v3/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
	github.com/alist-org/alist/v3/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	github.com/alist-org/alist/v3/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.(*conn).serve
	net/http/server.go:2009
runtime.goexit
	runtime/asm_amd64.s:1650
failed get objs 
[GIN] 2024/07/11 - 05:23:11 | 200 |    8.870958ms |   192.168.5.217 | POST     "/api/fs/list"

**Comment by Simonzhang8** [comment]
提示failed get storage: please add a storage first.是因为刚安装好没有存储，通过链接https://ip:port/@manage或https://ip:port/@login登录管理员账号之后到后台添加存储就好了

**Comment by Simonzhang8** [comment]
> 提示failed get storage: please add a storage first.是因为刚安装好没有存储，通过链接https://ip:port/@manage 或 https://ip:port/@login 登录管理员账号之后到后台添加存储就好了

**Comment by anwen-anyi** [comment]
显示这样？ 你还没添加存储 去添加了就好
![image](https://github.com/alist-org/alist/assets/56105412/dae81815-b192-43db-a03e-f666d8787108)
