### ISSUE TITLE
建议增加服务器选择文件上传

### ISSUE THREAD

**Issue by Hirsi-He** [alist-org/alist#6744]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

想上传服务器上的文件到百度网盘，但是选择不了服务器上的文件

### Suggested solution / 实现思路

选择文件的时候可以从服务器选择文件上传，也可以从客户端本地选择文件

**Comment by anwen-anyi** [comment]
自己在服务器搭建AList，然后挂载本地存储，选择复制，复制到百度云盘。

**Comment by Hello-XPH** [comment]
alist 能不能 限制游客上传文件 比如说只能上传音乐文件其他文件都不能上传

**Comment by anwen-anyi** [comment]
>  alist 能不能 限制游客上传文件 比如说只能上传音乐文件其他文件都不能上传

不能

**Comment by Hello-XPH** [comment]
> >  alist 能不能 限制游客上传文件 比如说只能上传音乐文件其他文件都不能上传
> 
> 不能

以后会开发这个功能吗？

**Comment by Hirsi-He** [comment]
> 自己在服务器搭建AList，然后挂载本地存储，选择复制，复制到百度云盘。

感谢
