### ISSUE TITLE
请问能不能把加载不出的存储当作bug处理？重启alist之后直接进不去界面

### ISSUE THREAD

**Issue by STEVENTAN100** [alist-org/alist#6745]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

Aliyun Open

### Describe the bug / 问题描述

请问能不能把加载不出来的存储当作bug处理，先让其他能正常加载的先加载，重复点击会卡死
ps：阿里云open的api（https://api.nn.ci/alist/ali_open/token ）不知道出现什么问题，前几天还能用的
![image](https://github.com/user-attachments/assets/ad78da57-0021-4870-a48d-94d2ad7b4540)

### Reproduction / 复现链接

暂无

### Config / 配置

默认配置

### Logs / 日志

![image](https://github.com/user-attachments/assets/741041fe-c4e0-41a6-bb2b-fd47ac1e4f70)

**Comment by anwen-anyi** [comment]
阿里云盘授权的API 似乎暂时链接不上，晚点试试看

**Comment by anwen-anyi** [comment]
现在试试看 应该恢复了
- 如果不行把 `https://api-cf.nn.ci/alist/ali_open/token` 换成 `https://api.xhofe.top/alist/ali_open/token`

**Comment by STEVENTAN100** [comment]
> 现在试试看 应该恢复了
> 
> * 如果不行把 `https://api-cf.nn.ci/alist/ali_open/token` 换成 `https://api.xhofe.top/alist/ali_open/token`

谢谢，恢复了
