### ISSUE TITLE
配置排序方式使用名称 无效

### ISSUE THREAD

**Issue by Kaiser-DMr** [alist-org/alist#6746]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.35

### Driver used / 使用的存储驱动

aliyun open

### Describe the bug / 问题描述

配置排序方式使用 **名称** 无效,在网站中一直显示 **修改时间**
![5b09e4019674f8932431a21e51974be](https://github.com/user-attachments/assets/6c1a5690-b328-49e7-ac62-11757c652db3)
![image](https://github.com/user-attachments/assets/2b9f689b-3854-49ee-88da-b84cb39dde82)

### Reproduction / 复现链接

内网地址无法提供

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "----------------",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "D:\\alist\\data\\data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "D:\\alist\\data\\temp",
  "bleve_dir": "D:\\alist\\data\\bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "D:\\alist\\data\\log\\log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

### Logs / 日志

无报错

**Comment by li-peifeng** [comment]
这个排序好像是存储的排序，非资源排序

**Comment by xhofe** [comment]
右下角刷新

**Comment by Kaiser-DMr** [comment]
> 右下角刷新

刷新之后没有用，还是一直只能显示 **修改时间** 排序
