### ISSUE TITLE
关于追加泰语/韩语翻译选项的请求

### ISSUE THREAD

**Issue by Wasabi-TheSpicyNinjaScrolls** [alist-org/alist#6748]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

请问一下未来会考虑追加泰语/韩语的翻译吗
或是支持自定义修改语言文本之类的

**Comment by xhofe** [comment]
已添加 target language， 欢迎在此处贡献翻译：https://crwd.in/alist

**Comment by Wasabi-TheSpicyNinjaScrolls** [comment]
谢谢 已经提交
