### ISSUE TITLE
pikpak挂载成功，但无法下载或播放。下载请求404

### ISSUE THREAD

**Issue by chen-coco** [alist-org/alist#6752]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.35

### Driver used / 使用的存储驱动

pikpak

### Describe the bug / 问题描述

pikpak挂载成功，但无法下载或播放。下载请求404

### Reproduction / 复现链接

pikpak用户挂载成功之后，文件无法下载或播放。全局代理或不代理情况相同

### Config / 配置

![image](https://github.com/user-attachments/assets/fe07a88b-16eb-4933-848c-508c02674abb)

### Logs / 日志

![image](https://github.com/user-attachments/assets/fae4881b-8cfe-4964-ad06-fe8a0bb448ee)
![image](https://github.com/user-attachments/assets/7201c9a0-2b64-4eb1-8712-87e0e7c2adfd)

**Comment by anwen-anyi** [comment]
转发消息∶官方改了请求方式返回的播放链接直接404🫥

**Comment by thuvaragan-g** [comment]
I'm also facing the same issue. 
<img width="1016" alt="Screenshot 2024-07-13 at 10 44 10" src="https://github.com/user-attachments/assets/2559873f-2815-43d5-b05e-d4a715f40f81">
<img width="782" alt="Screenshot 2024-07-13 at 16 54 41" src="https://github.com/user-attachments/assets/34265abb-63d9-4559-ba24-c984f7bb1a44">

**Comment by WaveBird** [comment]
遇到了同样的问题！

**Comment by Three-taile-dragon** [comment]
#6775 已PR，等合并

**Comment by thuvaragan-g** [comment]
When the fix will be release? I try to build with source code. But I can't. @Three-taile-dragon

**Comment by Three-taile-dragon** [comment]
> When the fix will be release? I try to build with source code. But I can't. @Three-taile-dragon

You can download the test version from Github Actions

For example: https://github.com/alist-org/alist/actions/runs/9931471158?pr=6788

**Comment by ghostWindows-files** [comment]
> I'm also facing the same issue. <img alt="Screenshot 2024-07-13 at 10 44 10" width="1016" src="https://private-user-images.githubusercontent.com/54566564/348468699-2559873f-2815-43d5-b05e-d4a715f40f81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTM5NDEsIm5iZiI6MTcyMTc5MzY0MSwicGF0aCI6Ii81NDU2NjU2NC8zNDg0Njg2OTktMjU1OTg3M2YtMjgxNS00M2Q1LWIwNWUtZDRhNzE1ZjQwZjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA0MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNDk2ZmFiODFhYmUzYjA5MDMyZDAyZWNlOTk3NDg2NWM0ZTIwNmNhNzAyNzJkYzgxN2NmYjNhMmU0ZGE4YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X2YWKsmgfyZfc1SDm6kOA2swvsqklZKcVZ8hXQri9EY"> <img alt="Screenshot 2024-07-13 at 16 54 41" width="782" src="https://private-user-images.githubusercontent.com/54566564/348468708-34265abb-63d9-4559-ba24-c984f7bb1a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTM5NDEsIm5iZiI6MTcyMTc5MzY0MSwicGF0aCI6Ii81NDU2NjU2NC8zNDg0Njg3MDgtMzQyNjVhYmItNjNkOS00NTU5LWJhMjQtYzk4NGY3YmIxYTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA0MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNWRiZGNkYjczMDNlM2Q4YWE5ZjcwNTZkNzY5YzU5NjM5NDllYzFhZWZjNzU2MWUyODNiMmZhNzc3NDZjYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SHNBuC03QIOUT4bd_VjXexFf3pnbrXSyWebF5xX0i3w">

直接把播放地址改成"dl-a10b-0623.mypikpak.com"即可
