### ISSUE TITLE
本地存储无法保存挂载目录作为存储根目录

### ISSUE THREAD

**Issue by WaveBird** [alist-org/alist#6774]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

本地存储根目录如果使用了nas中挂载的目录，报错：root folder /volume1/docker not exists，其中/volume1是/dev/md2的挂载目录

### Reproduction / 复现链接

None

### Config / 配置

默认配置

### Logs / 日志

![image](https://github.com/user-attachments/assets/705a73aa-86b4-404f-9449-ab637e0ac1db)
![image](https://github.com/user-attachments/assets/af874643-0772-4455-9082-0a5fd73b8c33)
<img width="1517" alt="image" src="https://github.com/user-attachments/assets/3bf7163e-5c24-4a47-ae8e-e0601592ed71">

**Comment by xhofe** [comment]
？Docker

**Comment by WaveBird** [comment]
对的，是docker，知道问题了，没有映射目录，谢谢回复
