### ISSUE TITLE
改密码不成功

### ISSUE THREAD

**Issue by zong400** [alist-org/alist#6776]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

alist admin set xxx 或者 ramdon 改密码之后启动，alist server 可以使用新密码登录，alist start就不行，提示密码不对。

### Reproduction / 复现链接

无

### Config / 配置

无

### Logs / 日志

INFO[2024-07-14 04:58:18] reading config file: data/config.json        
INFO[2024-07-14 04:58:18] load config from env with prefix: ALIST_     
INFO[2024-07-14 04:58:18] init logrus...                               
INFO[2024-07-14 04:58:18] admin user has been updated:                 
INFO[2024-07-14 04:58:18] username: admin                              
INFO[2024-07-14 04:58:18] password: bwHGu5im                           
ERRO[2024-07-14 04:58:18] [del_user_cache_online] error: that's not even a token 

debug：
2024/07/14 05:01:15 /home/runner/work/alist/alist/internal/db/user.go:49
[0.718ms] [rows:1] UPDATE `x_users` SET `username`="admin",`pwd_hash`="72878eeeef0459c27ce67f2b75ce10d510a49e05c04ad06f46b99d67d41b85f0",`pwd_ts`=1720933275,`salt`="QCpUeWHGPESSDIFq",`password`="",`base_path`="/",`role`=2,`disabled`=false,`permission`=0,`otp_secret`="",`sso_id`="",`authn`="[]" WHERE `id` = 1
INFO[2024-07-14 05:01:15]/home/runner/work/alist/alist/cmd/admin.go:80 github.com/alist-org/alist/v3/cmd.setAdminPassword() admin user has been updated:                 
INFO[2024-07-14 05:01:15]/home/runner/work/alist/alist/cmd/admin.go:81 github.com/alist-org/alist/v3/cmd.setAdminPassword() username: admin                              
INFO[2024-07-14 05:01:15]/home/runner/work/alist/alist/cmd/admin.go:82 github.com/alist-org/alist/v3/cmd.setAdminPassword() password: bwHGu5im                           

2024/07/14 05:01:15 /home/runner/work/alist/alist/internal/db/user.go:14
[0.517ms] [rows:1] SELECT * FROM `x_users` WHERE `x_users`.`role` = 2 LIMIT 1

2024/07/14 05:01:15 /home/runner/work/alist/alist/internal/db/settingitem.go:20
[0.331ms] [rows:1] SELECT * FROM `x_setting_items` WHERE `key` = "token" ORDER BY `x_setting_items`.`key` LIMIT 1
ERRO[2024-07-14 05:01:15]/home/runner/work/alist/alist/cmd/user.go:48 github.com/alist-org/alist/v3/cmd.DelUserCacheOnline() [del_user_cache_online] error: that's not even a token 
INFO[2024-07-14 05:01:15]/home/runner/work/alist/alist/internal/db/db.go:36 github.com/alist-org/alist/v3/internal/db.Close() closing db

**Comment by xhofe** [comment]
请确保在运行命令时使用相同的配置文件。

**Comment by zong400** [comment]
> 请确保在运行命令时使用相同的配置文件。

我是重新安装之后导入配置，这和改密码有什么关系，请明示

**Comment by aiaimimi0920** [comment]
@zong400 
1. sudo -i
2. ps -ef | grep alist
你会得到类似这样的东西：
alist3    9668     1  0 15:54 ?        00:00:00 /volume1/@appstore/alist3/bin/alist server --data /volume1/@appdata/alist3

3.  cd  /volume1/@appstore/alist3/bin/
4.  ./alist admin set 你的密码 --data /volume1/@appdata/alist3

**Comment by zong400** [comment]
@edgexie 按上面回复的大概率能解决，我的是因为用了软连接
