### ISSUE TITLE
请求为alist带来真正的登出

### ISSUE THREAD

**Issue by Luminet2023** [alist-org/alist#6792]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题，alist当前的登出按钮仅仅是清除了前端的Authorization，而未将要登出的TOKEN进行销毁

### Suggested solution / 实现思路

增加一个loginout接口，后端将登出的TOKEN标记为过期

**Comment by jianboy** [comment]
我看到有相应的接口的：

```
	Logout           = MainApi + "/user/logout"
```

**Comment by Luminet2023** [comment]
> 我看到有相应的接口的：
> 
> ```
> 	Logout           = MainApi + "/user/logout"
> ```

你指的是[drivers/123/util.go](https://github.com/alist-org/alist/blob/8b5727a0aa6a8277cc8776042f6cb0f527ea4c6f/drivers/123/util.go#L31)吗，这是存储驱动的logout,而不是Alist WebAPI的登出

**Comment by Luminet2023** [comment]
目前在[server/router.go](https://github.com/alist-org/alist/blob/8b5727a0aa6a8277cc8776042f6cb0f527ea4c6f/server/router.go)上没有logout的接口
