### ISSUE TITLE
更换教程文档中的alist前端CDN

### ISSUE THREAD

**Issue by ghostWindows-files** [alist-org/alist#6796]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

全局

### Describe the bug / 问题描述

原本官方文档中的CDN： https://jsd.onmicrosoft.cn 现在（2024.7.16实测）无法正常访问，疑似被攻击。目前可用的cdn是jsd官方域名下的 https://testingcf.jsdelivr.net (2024.7.16实测)国内可高速访问正常加载，还有官方文档中的饿了吗CDN也失效，请直接删除即可
https://alist.nn.ci/zh/config/configuration.html#cdn
### Reproduction / 复现链接

https://jsd.onmicrosoft.cn/gh/alist-org/web-dist@latest/dist/assets/index.a0597adf.js
https://alist.nn.ci/zh/config/configuration.html#cdn
### Config / 配置

https://jsd.onmicrosoft.cn/gh/alist-org/web-dist@latest/dist/assets/index.a0597adf.js

### Logs / 日志
https://alist.nn.ci/zh/config/configuration.html#cdn
https://jsd.onmicrosoft.cn/gh/alist-org/web-dist@latest/dist/assets/index.a0597adf.js

**Comment by Simonzhang8** [comment]
你或许可以直接到教程文档 [alist-org/docs](/alist-org/docs) 里提个PR，如果你会markdown的话
