### ISSUE TITLE
秒传支持夸克

### ISSUE THREAD

**Issue by liangrenjing** [alist-org/alist#6803]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望添加夸克秒传功能，如夸克秒传到115，因为现在阿里云盘和谐资源太快，资源多数逐步向夸克靠近。

### Suggested solution / 实现思路

如果夸克与115校验唯一值的算法不一样，能否自己算出资源的唯一值，实现秒传？

**Comment by winnerhus** [comment]
同求，需求夸克秒传至天翼，夸克SVIP晚上只有3MB/s以下的速度，看大码率电影不停缓冲，天翼黄金会员晚上也有最少30MB/s。多谢大佬

**Comment by foxxorcat** [comment]
夸克秒传需要同时满足md5和sha1，基本上没法秒传到夸克（上传可以只用sha1，但会导致下面的md5错误
夸克无法获取到文件列表的sha1，通过下载接口返回的md5不可信
综上所述无法实现

**Comment by fflrichard** [comment]
> 夸克秒传需要同时满足md5和sha1，基本上没法秒传到夸克（上传可以只用sha1，但会导致下面的md5错误 夸克无法获取到文件列表的sha1，通过下载接口返回的md5不可信 综上所述无法实现

夸克居然这么奇葩，然而现在好多资源都在夸克┓( ´∀` )┏
