### ISSUE TITLE
添加视频调用mpv-android播放器

### ISSUE THREAD

**Issue by FlyLoongZ** [alist-org/alist#6804]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

视频播放器下方添加mpv-android的intent url跳转到播放器

### Suggested solution / 实现思路

https://github.com/mpv-android/mpv-android/blob/master/docs/intent.html
好像跟MXPlayer的实现是差不多的

**Comment by wzdc** [comment]
直接整个自定义第三方播放器得了

**Comment by noxman** [comment]
https://github.com/akiirui/mpv-handler
