### ISSUE TITLE
请求适配阿里云盘的第三方权益

### ISSUE THREAD

**Issue by Deepsea-CN** [alist-org/alist#6810]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现版本应该是需要传参识别用户是否有第三方权益，现在使用alist出现阿里云盘的视频没法webdav播放等等问题

**Comment by EJianZQ** [comment]
歪个楼，真的会愿意掏钱再买个权益包吗，我感觉很屈辱，我个人而言宁愿不用也不会掏钱额外再买了

**Comment by anwen-anyi** [comment]
现在应该恢复了 你试试 
回复你消息1秒前我用Fileball挂载Webdav协议可以播放了

![image](https://github.com/user-attachments/assets/bf8afba3-4dda-4cc7-b77b-110ced299061)

**Comment by Deepsea-CN** [comment]
谁会愿意啊，本来就是为了挂alist才开的会员，现在又减量加价，不过不用阿里的话我就只有od的云盘能挂载了，看视频就算走中转加上科学上网有时候还是挺卡的，百度又没有好用的webdav，挂alist还要改agent才能看视频，太不方便了，自己nas没组起来之前只能再坚持用一下阿里了，再者他们好像说会考虑给现在的会员按剩余时长补偿权益包，反正就算以后继续用阿里我也只充权益包，相对别的网盘会员到底还是能便宜点吧，反正我现在就充了1个月的，也就10块钱，看他怎么样吧，还要恶心人的话那就用到到期就摆烂了

**Comment by Deepsea-CN** [comment]
> 现在应该恢复了 你试试 回复你消息1秒前我用Fileball挂载Webdav协议可以播放了
> 
> ![image](https://private-user-images.githubusercontent.com/56105412/349935732-bf8afba3-4dda-4cc7-b77b-110ced299061.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDIxNTQsIm5iZiI6MTcyMTMwMTg1NCwicGF0aCI6Ii81NjEwNTQxMi8zNDk5MzU3MzItYmY4YWZiYTMtNGRkYS00Y2M3LWI3N2ItMTEwY2VkMjk5MDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDExMjQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZDRmZDE5ZGM2MjIwYjA4MDQ0OTM0ZTRlYjY0NjdhMWI1ZmI3YTM2NGI5Yjg2NDA1MjYxMmU2ZjNlZjJmY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S7LAws22G9xXw8w-5CH71nzP9Nd5r33FKue6fbuC0OQ)

试了一下，现在可以播放了，速度还可以，但是官方文档不是说现在认证应用下载链接有限期是4小时了吗，alist看转码视频还是会15分钟断一次啊

**Comment by Deepsea-CN** [comment]
> 歪个楼，真的会愿意掏钱再买个权益包吗，我感觉很屈辱，我个人而言宁愿不用也不会掏钱额外再买了

唉，完全只是为了流畅使用alist才绑定消费了，如果只有他们这个app，我一分钱都不想给

**Comment by anwen-anyi** [comment]
> 试了一下，现在可以播放了，速度还可以，但是官方文档不是说现在认证应用下载链接有限期是4小时了吗，alist看转码视频还是会15分钟断一次啊


什么版本?我测试了一个多小时的 也没问题呀

**Comment by Deepsea-CN** [comment]
> 什么版本?我测试了一个多小时的 也没问题呀

就是3.35.0，最新版本，难道是挂载的有问题？我去重新挂一下看看

**Comment by anwen-anyi** [comment]
> 谁会愿意啊，本来就是为了挂alist才开的会员，现在又减量加价，不过不用阿里的话我就只有od的云盘能挂载了，看视频就算走中转加上科学上网有时候还是挺卡的，百度又没有好用的webdav，挂alist还要改agent才能看视频，太不方便了，自己nas没组起来之前只能再坚持用一下阿里了，再者他们好像说会考虑给现在的会员按剩余时长补偿权益包，反正就算以后继续用阿里我也只充权益包，相对别的网盘会员到底还是能便宜点吧，反正我现在就充了1个月的，也就10块钱，看他怎么样吧，还要恶心人的话那就用到到期就摆烂了

如果你只是看视频 使用转码后的播放器看 不会消耗权益包流量 

- Aliyun Video Previewer 这个播放器

**Comment by fuyubi** [comment]
恢复了但是只有400-500k，看个1080p的都总是缓冲，但昨天都是跑满速的

**Comment by Deepsea-CN** [comment]
> 恢复了但是只有400-500k，看个1080p的都总是缓冲，但昨天都是跑满速的

多刷几个视频，或者多放一会，我现在能拉到10MBS+

**Comment by Deepsea-CN** [comment]
> > 试了一下，现在可以播放了，速度还可以，但是官方文档不是说现在认证应用下载链接有限期是4小时了吗，alist看转码视频还是会15分钟断一次啊
> 
> 什么版本?我测试了一个多小时的 也没问题呀

很奇怪啊，看一些电影，一两个小时的可以一直播，但是今天放一些几十分钟的视频，或者暂停一段时间的情况，他还是会触发刷新

**Comment by anwen-anyi** [comment]
> 很奇怪啊，看一些电影，一两个小时的可以一直播，但是今天放一些几十分钟的视频，或者暂停一段时间的情况，他还是会触发刷新

嗯 我前两天确认了一下  目前还是会的😗之前是我记错了… 后续要是改了再和你说下吧
