### ISSUE TITLE
重启Alist(停电）后复制任务丢失

### ISSUE THREAD

**Issue by yueyue5201314** [alist-org/alist#6817]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

onedrive,alistv3

### Describe the bug / 问题描述

alist进程退出或者重启都会导致复制任务丢失………我需要复制接近5T的文件到onedrive！！！因为停电，导致alist进程被关闭，复制任务全部丢失！

### Reproduction / 复现链接

将文件从一个存储复制到另一个存储，关闭或者重启alist进程都能复现

### Config / 配置

![Screenshot_2024-07-19-23-02-18-245_com android chrome-edit](https://github.com/user-attachments/assets/b2770312-47a7-4138-b297-c2f8fb37fc74)

**Comment by Deepsea-CN** [comment]
我记得为了避免出错alist重启之后会清空缓存文件的，所以任务相关内容都会消失

**Comment by yueyue5201314** [comment]
> 我记得为了避免出错alist重启之后会清空缓存文件的，所以任务相关内容都会消失

希望开发者能改一下吧！我刚复制到300G左右的文件，结果停电导致alist被关了……又得重新复制！

**Comment by yueyue5201314** [comment]
> 可以搭配rclone来进行复制，能跳过重复的文件

………你是不是忘了，有些文件复制会不全，那么多文件压根不知道是哪些文件只复制了一部分

**Comment by yueyue5201314** [comment]
> > > 可以搭配rclone来进行复制，能跳过重复的文件
> > 
> > ………你是不是忘了，有些文件复制会不全，那么多文件压根不知道是哪些文件只复制了一部分
> 
> 
> rclone会自动判断缺失的文件的
> 中断的又不会断点续传，没传完的重新传呗
> 
rclone能够在进程重启后保留任务，断点续传吗？

**Comment by yueyue5201314** [comment]
> > > > > 可以搭配rclone来进行复制，能跳过重复的文件
> > > > 
> > > > 
> > > > ………你是不是忘了，有些文件复制会不全，那么多文件压根不知道是哪些文件只复制了一部分
> > > 
> > > 
> > > rclone会自动判断缺失的文件的
> > > 中断的又不会断点续传，没传完的重新传呗
> > 
> > rclone能够在进程重启后保留任务，断点续传吗？
> 
> 没传完的重新传，传完的加参数跳过

就是没办法分辨是哪些文件没有传，哪些文件传完了，哪些文件没传完整，我才需要保留复制任务呀！！！文件夹大小接近5个T，每个文件在1-3G左右，还有部分md和图片；还不是都在根目录，全是多级目录！如果复制到1T左右中断了，总不能一个一个去找吧……而且文件也没在本地，在云端！

**Comment by yueyue5201314** [comment]
> > > > > > > 可以搭配rclone来进行复制，能跳过重复的文件
> > > > > > 
> > > > > > 
> > > > > > ………你是不是忘了，有些文件复制会不全，那么多文件压根不知道是哪些文件只复制了一部分
> > > > > 
> > > > > 
> > > > > rclone会自动判断缺失的文件的
> > > > > 中断的又不会断点续传，没传完的重新传呗
> > > > 
> > > > 
> > > > rclone能够在进程重启后保留任务，断点续传吗？
> > > 
> > > 
> > > 没传完的重新传，传完的加参数跳过
> > 
> > 就是没办法分辨是哪些文件没有传，哪些文件传完了，哪些文件没传完整，我才需要保留复制任务呀！！！文件夹大小接近5个T，每个文件在1-3G左右，还有部分md和图片；还不是都在根目录，全是多级目录！如果复制到1T左右中断了，总不能一个一个去找吧……而且文件也没在本地，在云端！
> 
> rclone是可以分辨哪些文件没有传，哪些文件传完了,加个重复文件的参数就行。但是有没有传完整无法分辨，因为alist本身就不带断点续传。只能先跳过重复文件，也就是文件传完的自动跳过，最后没传完的重新上传。可以自己翻rclone文档
> 另外rclone建议同webdav复制，这样走的是alist的内部复制，如果能快速复制，还能秒传过去。

就是不知道哪些没传完呀！！！！如果我跳过重复文件，等全部复制完之后有接近5T……再对比文件大小找没传完的，无异于大海捞(浪费时间呀！！！）……我直接用alist的复制，直接覆盖不是更好……最好的办法还是保留复制任务！！！

**Comment by shirakun** [comment]
> > > > 可以搭配rclone来进行复制，能跳过重复的文件
> > > 
> > > 
> > > ………你是不是忘了，有些文件复制会不全，那么多文件压根不知道是哪些文件只复制了一部分
> > 
> > 
> > rclone会自动判断缺失的文件的
> > 中断的又不会断点续传，没传完的重新传呗
> 
> rclone能够在进程重启后保留任务，断点续传吗？

有sync功能
