### ISSUE TITLE
alist 使用123云盘存储无法识别 "." 开头文件夹和文件

### ISSUE THREAD

**Issue by shawflee** [alist-org/alist#6820]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

123云盘

### Describe the bug / 问题描述

如下图中123云盘中存在 ".test" 文件夹，而 alsit 中不显示。
![image](https://github.com/user-attachments/assets/1002700b-30ad-4ee9-b270-caf04ba10409)
![image](https://github.com/user-attachments/assets/db9c05e6-bc7c-4c0a-b6d7-d5b7750ad5c5)

### Reproduction / 复现链接

两种方式均可复现
1.123云盘中创建 "."开头文件夹或文件如 ".test"，alist 中不会显示。
2.在 alist 中创建 "." 开头文件夹或文件如 ".test"，alist 中提示创建成功但不显示该文件，而123云盘中确实已经创建成功。

### Config / 配置

![image](https://github.com/user-attachments/assets/68b966c7-5a1c-43d1-b6c6-851317bb4f0e)

### Logs / 日志

非 ERROR BUG，无报错日志

**Comment by Ruler27** [comment]
这是123的问题，不是alist的
