### ISSUE TITLE
直链有效期没单位啊

### ISSUE THREAD

**Issue by 1049731887** [alist-org/alist#6821]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

直链有效期没单位啊，评论一下单位我看到提个PR吧

### Reproduction / 复现链接

。

### Config / 配置

。

**Comment by 1049731887** [comment]
![image](https://github.com/user-attachments/assets/19f92a56-b1c5-449f-aad1-8121b82125b2)

**Comment by anwen-anyi** [comment]
文档不是写了吗 单位是小时 😘
![image](https://github.com/user-attachments/assets/b482847d-0803-4ea3-927a-a71301f33eb2)

**Comment by 1049731887** [comment]
我的意思是想写在配置的地方，比较直观
