### ISSUE TITLE
webdav 通过透传登录信息给客户端来支持302重定向

### ISSUE THREAD

**Issue by wdsjhskj** [alist-org/alist#6822]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

webdav 可以通过透传登录信息给客户端来支持302重定向

### Suggested solution / 实现思路

通过类似 http://username:password@example.com 透传登录信息至下游客户端，直连下载服务器流量不需要被Alist或代理服务器代理，提升下载速度。存在一些风险，由用户权衡利弊后选择。我觉得在自用状态下没啥问题。

**Comment by itsHenry35** [comment]
本来就是支持这个功能的，例如想要请求/test/example.txt，你可以在浏览器里打开url：http://admin:yourpassword@localhost:5244/dav/test/example.txt

**Comment by wdsjhskj** [comment]
> 本来就是支持这个功能的，例如想要请求/test/example.txt，你可以在浏览器里打开url：http://admin:yourpassword@localhost:5244/dav/test/example.txt

我指的是WEBDAV存储不是alist的WEBDAV功能：https://alist.nn.ci/zh/guide/drivers/webdav.html

**Comment by itsHenry35** [comment]
> > 本来就是支持这个功能的，例如想要请求/test/example.txt，你可以在浏览器里打开url：http://admin:yourpassword@localhost:5244/dav/test/example.txt
> 
> 我指的是WEBDAV存储不是alist的WEBDAV功能：https://alist.nn.ci/zh/guide/drivers/webdav.html

那这个安全风险也太大了，@xhofe 你来评估一下~
