### ISSUE TITLE
启动时，链接到远程存储的加密存储无法加载，每次都要重点1次重新加载

### ISSUE THREAD

**Issue by 1049731887** [alist-org/alist#6825]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

加密存储

### Describe the bug / 问题描述

如题，加密存储应该等待到远程存储加载完毕时，再开始加载

### Reproduction / 复现链接

。

### Config / 配置

。

**Comment by anwen-anyi** [comment]
应该是你的 加密驱动比原本的驱动考前导致的  你可以写一下加密驱动的序号 让加密驱动靠后 这样就不会了 3.35.0不知道生效了吗

  ![image](https://github.com/user-attachments/assets/921b53e3-0fe7-428d-99c9-4576a622f95b)
