### ISSUE TITLE
详情页能否提供完整的文件操作功能

### ISSUE THREAD

**Issue by kylehz** [alist-org/alist#6845]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

<img width="203" alt="image" src="https://github.com/user-attachments/assets/d78394e5-193f-4a6a-b5c5-fc16274af706">
能否提供完整的文件操作功能：重命名、移动、复制、删除、复制链接、下载

**Comment by Narut0123** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure this feature is not implemented.
> * [x]  I'm sure it's a reasonable and popular requirement.
> 
> ### Description of the feature / 需求描述
> <img alt="image" width="203" src="https://private-user-images.githubusercontent.com/20038464/350822176-d78394e5-193f-4a6a-b5c5-fc16274af706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTc5OTksIm5iZiI6MTcyMTY5NzY5OSwicGF0aCI6Ii8yMDAzODQ2NC8zNTA4MjIxNzYtZDc4Mzk0ZTUtMTkzZi00YTZhLWI1YzUtZmMxNjI3NGFmNzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAxMjEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ODI3YzY5ZDBkNzE0NzM4ZDVmMzNlOGNlMDdmYjMzM2U2NjY3NzJjYzE1YWFmMDJiOWZjMWIxMjIzNmFkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vl9PzOHznjoXdPmuzjQqf6eMYuFdW9b4jBxh0rVc3Jw"> 能否提供完整的文件操作功能：重命名、移动、复制、删除、复制链接、下载
> ### Suggested solution / 实现思路
> _No response_
> 
> ### Additional context / 附件
> _No response_

你点一下红框里最下面一个，圆圈里三个点那个图标，把选项展开，就看到完整的功能了

**Comment by kylehz** [comment]
红框已经是点三个点的展开状态了

**Comment by StackExplode** [comment]
+1。
同时在目录列表中勾选文件后底部工具栏可选发送到Aria2，但点进单个文件内则没有底部工具栏，希望能加上。

**Comment by Weidows** [comment]
+1+1, 非常需要
我现在遇到的问题是, 文件夹里上百个文件, 我想操作其中某一个

如果通过搜索找到对应文件, 没有任何按钮提供删除/移动/重命名之类的操作 (只有个下载)
所以现在只能挨个对名字找, 找花了眼, 或者 ssh 进服务器搞(只能用于本地存储)
