### ISSUE TITLE
Windows挂载Webdav列目录正常但无法访问文件

### ISSUE THREAD

**Issue by toreyink** [alist-org/alist#6846]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

![微信截图_20240722112604](https://github.com/user-attachments/assets/38b348eb-73e7-4dc8-abcc-3759e2f826d8)
![微信截图_20240722112636](https://github.com/user-attachments/assets/a21f6fa4-abdc-42b9-aa7d-935996a72c80)
115使用302中转，Windows 挂载Webdav，列目录正常，但无法浏览文件。WEB网页端正常，顺利播放。

### Reproduction / 复现链接

暂无

### Config / 配置

{
  "force": false,
  "site_url": "https://drive*********",
  "cdn": "",
  "jwt_secret": "**********",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

**Comment by LIUBANGJIAN** [comment]
同样的问题，用app  fileball的alist协议是可以正常播放的，但是用了webdav协议就一直卡着播放页面无法播放。换了其他app例如vidhub、senplayer、fimly用webdav协议也是无法播放的，都是卡播放页面。

**Comment by Hugo7th** [comment]
同样的问题，alist挂载阿里云盘open，已开第三方权益，在浏览器alist打开视频无论是aliyun video previewer还是alist的video播放器都可以顺利播放视频，但是在android的kodi上面按照webdav方式能够看到视频文件，也可以刮肖到电影信息，但是播放就会提示文件播放错误。

**Comment by LIUBANGJIAN** [comment]
看样子是普遍问题，但是作者只关心问题模板问题，而不是关心bug。

**Comment by MidnightShake** [comment]
docker安装的同样升级到新版后，曾经是秒开，现在就非常卡了，web页面也非常卡，webdav挂载也卡，内网windows挂载加载文件列表非常慢如果打开文件经常卡死文件管理器并且文件经常打不开，mac挂载加载文件列表同样，不打开文件但是传入文件速度非常慢，确定不是自身硬盘问题和机器配置问题或者网络问题，不得已只能先停用，明天试试旧版本

**Comment by MidnightShake** [comment]
使用docker版本的main版本同样卡，恢复到3.35版本正常
