### ISSUE TITLE
Terabox现在似乎已经无法住区cookie

### ISSUE THREAD

**Issue by xinglingsui** [alist-org/alist#6850]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在Terabox网页里已无法开f12，右键被禁止，强行打开会直接跳转about:blank

**Comment by itsHenry35** [comment]
![image](https://github.com/user-attachments/assets/cc318c14-8200-4a06-8d84-c6551f90f8ae)
其实打开terabox之前先开f12，勾上preserve log就行了

**Comment by yhchong2014** [comment]
填了cookie可是出现这个怎么办？
failed to check login status according to cookie
![Screenshot 2024-08-06 100600](https://github.com/user-attachments/assets/0e708472-6861-4355-98fe-f94637be19ac)

browserid= removed; __bid_n=removed; PANWEB=removed; TSID=removed; lang=en; ndus=removed; csrfToken=removed; ndut_fmt=removed

**Comment by anwen-anyi** [comment]
> javascript:(function() { var cookies = document.cookie; var textarea = document.createElement("textarea"); textarea.value = cookies; document.body.appendChild(textarea); textarea.select(); document.execCommand("copy"); document.body.removeChild(textarea); alert("Cookies have been copied to clipboard!"); })();

这个好像也不行？ 提示
```txt
Failed init storage but storage is already created: failed init storage: failed to check login status according to cookie
```

**Comment by anwen-anyi** [comment]
> 其实打开terabox之前先开f12，勾上preserve log就行了

还得是这个 嘿嘿~ :joy_cat:
