### ISSUE TITLE
Pikpak离线下载成功后自动刷新文件夹

### ISSUE THREAD

**Issue by jackson977800** [alist-org/alist#6851]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

最新版本，pikpak离线下载成功后自动刷新文件夹。每次下载了不会显示出来，需要手动刷新。

### Suggested solution / 实现思路

pikpak离线下载成功后自动刷新文件夹

**Comment by chivehao** [comment]
我这边手动刷新都不出来，要等好久再刷新才出来
