### ISSUE TITLE
Alist 3.36.0的Windows amd64版本release被Windows Defender拦截

### ISSUE THREAD

**Issue by blue-cosmos** [alist-org/alist#6852]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

Alist 3.36.0的Windows amd64版本release被Windows Defender拦截，说是有trojan. 3.35.0 Windows amd64版本下载没有问题。

### Reproduction / 复现链接

https://github.com/alist-org/alist/releases/download/v3.36.0/alist-windows-amd64.zip

### Config / 配置

NA

**Comment by thesexday** [comment]
我这里直接被卡巴斯基查杀了，说是有病毒。

**Comment by zxw11211** [comment]
我的也是，被卡巴斯基直接干掉了

**Comment by jianboy** [comment]
在windows中启动一个web服务器当然可能报病毒。

简单的方法就是数字签名，但是alist是开源免费软件。

其次就是设置杀毒软件忽然该软件即可。

alist 其实在linux上运行就好了，在 windows 通过web访问即可。

**Comment by blue-cosmos** [comment]
> 在windows中启动一个web服务器当然可能报病毒。
> 
> 简单的方法就是数字签名，但是alist是开源免费软件。
> 
> 其次就是设置杀毒软件忽然该软件即可。
> 
> alist 其实在linux上运行就好了，在 windows 通过web访问即可。

下载时直接被拦截了，并非在运行时拦截。

**Comment by Deepsea-CN** [comment]
> > 在windows中启动一个web服务器当然可能报病毒。
> > 简单的方法就是数字签名，但是alist是开源免费软件。
> > 其次就是设置杀毒软件忽然该软件即可。
> > alist 其实在linux上运行就好了，在 windows 通过web访问即可。
> 
> 下载时直接被拦截了，并非在运行时拦截。

下载时关闭defender的实时防御

**Comment by djniche** [comment]
defender这玩意除了毒杀不掉,其余都能被杀,比如汉化,各种安装包(滑稽)
