### ISSUE TITLE
加密盘总是出现这个提示，然后就无法访问，需要到存储那里再保存一下就好了，为什么啊？ can't find remote storage: storage not found; rawPath:

### ISSUE THREAD

**Issue by at86397388** [alist-org/alist#6865]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36

### Driver used / 使用的存储驱动

阿里，天翼

### Describe the bug / 问题描述

加密盘总是出现这个提示，然后就无法访问，需要到存储那里再保存一下就好了，为什么啊？
can't find remote storage: storage not found; rawPath:

### Reproduction / 复现链接

加密盘总是出现这个提示，然后就无法访问，需要到存储那里再保存一下就好了，为什么啊？
can't find remote storage: storage not found; rawPath:

### Config / 配置

加密盘总是出现这个提示，然后就无法访问，需要到存储那里再保存一下就好了，为什么啊？
can't find remote storage: storage not found; rawPath:

**Comment by anwen-anyi** [comment]
是刚重启AList以后遇到的吗?

**Comment by Simonzhang8** [comment]
如果是重启后出现的，可以给加密盘和原始盘设置里添加序号，加密盘序号比原始盘的序号大就可以了，这样重启后先加载原始盘再加载加密盘就不会出现问题，参考[Crypt: can't find remote storage: storage not found #6297](https://github.com/alist-org/alist/issues/6297)
