### ISSUE TITLE
如何用命令行手动刷新Alist某个递归目录的所有内容

### ISSUE THREAD

**Issue by Super-Passerby** [alist-org/alist#6868]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

如题，如何用命令行手动刷新Alist某个递归目录的所有内容

**Comment by onexiaolaji** [comment]
可以吧
POST /api/fs/list
<html>
<body>

refresh | body | boolean | 否 | 是否强制刷新 | none
-- | -- | -- | -- | -- | --



</body>
</html>

**Comment by wj2008** [comment]
function refresh(){
    res=`curl -X POST -H "Authorization: $TOKEN" -H "Content-Type: application/json" -d '{"path": "'$(dirname $1)'", "refresh": true}' -s $ALIST_URL/api/fs/list`
    names=$(echo $res | jq -r '.message')
    echo -e "refresh $(dirname $1) => $names"
}
