### ISSUE TITLE
启用 Crypt 驱动后，传输降速

### ISSUE THREAD

**Issue by YinsenHo** [alist-org/alist#6881]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

天翼云盘-个人网盘

### Describe the bug / 问题描述

启用crypt驱动后，原来不管是 302（天翼） 还是本地代理（夸克）的驱动下载，速度降到了 1M/s以内。没有启用的情况下，相同条件下能达到 15M/s。而且重启 docker 会解决，但是过一段时间又必然复现。

### Reproduction / 复现链接

内网部署

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xCqokDl5vEaVe2FX",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2
    },
    "upload": {
      "workers": 5,
      "max_retry": 0
    },
    "copy": {
      "workers": 5,
      "max_retry": 2
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

**Comment by tunanx** [comment]
老问题了，去你的网络管理界面看看，是不是很多天翼云盘的tcp连接没有关闭。把天翼云tcp连接全关闭后，速度就恢复了。

**Comment by UncleUncleWang** [comment]
> 老问题了，去你的网络管理界面看看，是不是很多天翼云盘的tcp连接没有关闭。把天翼云tcp连接全关闭后，速度就恢复了。

啊，哪里的网络管理界面啊，alist 的吗，还是 dokcer？或者有没有什么根治的方法，Crypt 功能还是很实用的，也不想老是手动操作。非常感谢

**Comment by tunanx** [comment]
去clash或者openwrt里的网络管理看，暂时没有根治方法，因为这个问题不好复现。前段时间我路由器上接了个软路由走代理，就一直速度卡，不走软路由代理就一切正常。你试试换设备或者切换网络环境代理吧。

**Comment by UncleUncleWang** [comment]
> 去clash或者openwrt里的网络管理看，暂时没有根治方法，因为这个问题不好复现。前段时间我路由器上接了个软路由走代理，就一直速度卡，不走软路由代理就一切正常。你试试换设备或者切换网络环境代理吧。

我的环境里面没有代理，也没有软路由，奇怪了

**Comment by sususu98** [comment]
我也遇到了相同或的问题

![Image](https://github.com/user-attachments/assets/46391bbe-36f0-40df-b519-c7a0a8171d79)

直接下载加密的问题是没有问题的，下载Crypt解密后的文件就会只有几十KB/s
