### ISSUE TITLE
登录提示Failed find user: record not found

### ISSUE THREAD

**Issue by iceloon** [alist-org/alist#6893]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

115 夸克

### Describe the bug / 问题描述

昨天正常.今天登录提示Failed find user: record not found
![IMG_4664](https://github.com/user-attachments/assets/8f22c5b9-607f-4e53-8a53-4d100703ceea)

### Reproduction / 复现链接

1

### Config / 配置

1

**Comment by iceloon** [comment]
就是因为上一个issue没有结果才renew一个

**Comment by Simonzhang8** [comment]
登的管理员账号吗？还是普通用户

**Comment by iceloon** [comment]
> 登的管理员账号吗？还是普通用户

管理员账号

**Comment by iceloon** [comment]
重新部署好了，猜测是koyeb删数据库导致的
