### ISSUE TITLE
夸克网盘挂载 突然失效，手动访问网页和域名，均正常

### ISSUE THREAD

**Issue by msxfXF** [alist-org/alist#6894]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

Built At: 2024-05-23 12:20:17 +0000 Go Version: go1.21.10 linux/amd64 Author: Xhofe <i@nn.ci> Commit ID: 8e2b9c6 Version: v3.35.0 WebVersion: 

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

2024/07/27 11:56:50.528723 WARN RESTY Get "https://drive.quark.cn/1/clouddrive/config?fr=pc&pr=ucpro": dial tcp: lookup drive.quark.cn: no such host, Attempt 1
2024/07/27 11:56:50.528803 WARN RESTY Get "https://drive.quark.cn/1/clouddrive/config?fr=pc&pr=ucpro": dial tcp: lookup drive.quark.cn: no such host, Attempt 2
2024/07/27 11:56:50.528723 WARN RESTY Get "https://drive.quark.cn/1/clouddrive/file/sort?_fetch_total=1&_page=1&_size=100&fr=pc&pdir_fid=08dffdc2e6be4705a74422b4e418f374&pr=ucpro": dial tcp: lookup drive.quark.cn: no such host, Attempt 2

### Reproduction / 复现链接

夸克挂载

### Config / 配置

夸克挂载

**Comment by Simonzhang8** [comment]
网络问题？检查下Alist所在的机器能否访问互联网，或者晚些重试一下？
