### ISSUE TITLE
希望支持彩虹聚合登录的单点登录方式

### ISSUE THREAD

**Issue by Rickrollcc** [alist-org/alist#6899]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望支持彩虹聚合登录的单点登录方式

### Suggested solution / 实现思路

感觉不可能但有待一试

**Comment by itsHenry35** [comment]
为啥不用casdoor...

**Comment by Rickrollcc** [comment]
> 为啥不用casdoor...

也是 但只是需求建议 不过不可能，因为我看这种彩虹聚合登录有点依赖php好像

**Comment by itsHenry35** [comment]
> > 为啥不用casdoor...
> 
> 也是 但只是需求建议 不过不可能，因为我看这种彩虹聚合登录有点依赖php好像

是可能的，但已有casdoor的解决方案，没必要再接入一个商业公司的闭源产品了
