### ISSUE TITLE
302重定向

### ISSUE THREAD

**Issue by chenweiliang6** [alist-org/alist#6900]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

这个文档上写的302重定向不建议共享使用，有封禁分享，共享使用具体是指什么

**Comment by Simonzhang8** [comment]
同时间多个IP访问，换句话说就是你在访问你发给你的朋友他也在同时访问

**Comment by chenweiliang6** [comment]
> 同时间多个IP访问，换句话说就是你在访问你发给你的朋友他也在同时访问

意思就是不同ip同时访问那个网盘喽，跟alist没关系的是吧，就算在同一局域网下也不行

**Comment by Simonzhang8** [comment]
> 意思就是不同ip同时访问那个网盘喽，跟alist没关系的是吧，就算在同一局域网下也不行

302就是访问alist的设备（手机、电脑等）直接请求相应存储网盘的链接
如果是同一局域网的话一般问题不大，因为网盘只能识别到你的公网IP，同一局域网下一般公网IP是一样的，不过同一IP也有请求数限制。
反正你个人正常使用的话一般都不会触发风控的，但具体的风控逻辑是什么因平台而异。
