### ISSUE TITLE
希望阿里云盘Open添加默认播放器选项

### ISSUE THREAD

**Issue by makierika** [alist-org/alist#6903]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在Aliyun Video Preview播放器只能播放标清视频了
希望阿里云盘Open添加默认播放器选项，这样我就可以设置默认播放器为Video了

**Comment by anwen-anyi** [comment]
自己切换成Video播放器就可以

**Comment by Simonzhang8** [comment]
> 自己切换成Video播放器就可以

是可以，不过帖主的意思是每次这样手动切换很麻烦

**Comment by Simonzhang8** [comment]
一个暂时的解决方案是给阿里云盘Open的路径添加个别名，因为别名不支持Aliyun Video Previewer，在别名路径下访问默认就是Video了

**Comment by makierika** [comment]
> 一个暂时的解决方案是给阿里云盘Open的路径添加个别名，因为别名不支持Aliyun Video Previewer，在别名路径下访问默认就是Video了

第一次知道别名，搞定了🎉
