### ISSUE TITLE
挂载网易云歌词不显示

### ISSUE THREAD

**Issue by iowong** [alist-org/alist#6914]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.36

### Driver used / 使用的存储驱动

网易云

### Describe the bug / 问题描述

挂载网易云歌词不显示
![微信截图_20240731150454](https://github.com/user-attachments/assets/6a958299-a704-47da-8be7-330edf7359e4)

### Reproduction / 复现链接

挂载网易云歌词不显示

### Config / 配置

挂载网易云歌词不显示

**Comment by iowong** [comment]
站点有证书 歌词请求是http导致歌词请求不到
![Uploading 微信截图_20240731171812.png…]()

**Comment by RedSTARO** [comment]
跨站请求问题，都配置为http或者https即可
建议https（

**Comment by iowong** [comment]
> 跨站请求问题，都配置为http或者https即可 建议https（

我的站点就是https  加载歌词是alist处理的 歌词链接变成了http导致请求不成功

**Comment by liuycy** [comment]
https://github.com/alist-org/alist/issues/6556 之前有人遇到过类似的问题，讨论过解决方案，你试试看能否搞定？
