### ISSUE TITLE
缓存302链接

### ISSUE THREAD

**Issue by wzdc** [alist-org/alist#6916]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

缓存网盘的302链接，网盘的文件直连有时效限制，很多网盘的文件过期时间都可以在文件直链的GET参数上获取到或者让用户手动设置链接缓存时长也可以。不知道为什么只缓存阿里云盘的302链接。 很多播放器的WEBDAV每次缓存视频或音乐都会向Alist发起请求，影响速度而且太频繁的请求可能会被网盘封号。
（如图所示）
![Screenshot_2024_07_31_18_30_24_23_265eefe1b4d950c11f237ceaad3e5729](https://github.com/user-attachments/assets/c19296d1-e55e-4d0a-b476-4b5047484262)

### Suggested solution / 实现思路

部分网盘链接过期时间获取示例
115：https://cdnfhnfdfs.115.com/X/XX/XX?t= `1722467317` &u=...
天翼云：https://media-gxnn-person.gxoss.xstore.ctyun.cn/PERSONCLOUD/XX.mp4?x-amz-CLIENTTYPEIN=PC&AWSAccessKeyId=...&Expires= `1722422048` &x-amz-FSIZE=...
阿里云：https://cn-beijing-data.aliyundrive.net/...&x-oss-expires= `1722435972` ..

**Comment by AkashiCoin** [comment]
可以选择各个网盘各自适配各自的缓存时间，如果你需要可以自行修改对应存储的返回链接逻辑

**Comment by wzdc** [comment]
要怎么改呀？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月2日(周五) 下午2:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alist-org/alist] 缓存302链接 (Issue #6916)




 
可以选择各个网盘各自适配各自的缓存时间，如果你需要可以自行修改对应存储的返回链接逻辑
 
&mdash;

**Comment by AkashiCoin** [comment]
改哪个存储的link返回逻辑代码，加个cache，然后再自己编译咯
