### ISSUE TITLE
蓝奏云下载文件提示：failed link: failed get link: not find file page param

### ISSUE THREAD

**Issue by SDCOM-0415** [alist-org/alist#6936]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0 for Windows

### Driver used / 使用的存储驱动

蓝奏云

### Describe the bug / 问题描述

使用蓝奏云进行下载文件的时候，会提示
failed link: failed get link: not find data
![image](https://github.com/user-attachments/assets/952814ab-c776-491e-bb41-a00d09fa6fd3)
采用帐号登录，确保正确（能够在官网正常登录、上传、下载）
![image](https://github.com/user-attachments/assets/83e7bb15-295e-489c-b600-b730447463e3)
![image](https://github.com/user-attachments/assets/2796d174-2711-4c6b-915f-2a95e312a8f3)
![image](https://github.com/user-attachments/assets/0ed2e9a1-a2f5-4708-bd03-b2ecd513c2a8)
![image](https://github.com/user-attachments/assets/36204d10-2e30-4d5a-89c7-1da57d064307)
也能够正常的在alist中读取文件列表
![image](https://github.com/user-attachments/assets/0a9718a3-d153-4ad7-83b0-d0478b1bd783)

相比于上一次的issues（#5146），这次是所有文件都无法下载
![image](https://github.com/user-attachments/assets/c54d6242-d413-4dfb-9bf3-35b3adf93a39)
![image](https://github.com/user-attachments/assets/2ef06096-cd06-44e5-a0ef-f4729a6ab662)
最新的actions只有Linux的二进制文件，我的系统是Windows 2012 R2
![image](https://github.com/user-attachments/assets/42cfe73d-0847-4d27-ae00-3cdfdf6f2a7c)
![image](https://github.com/user-attachments/assets/e0132e87-a513-42b1-8195-74ba43233301)

### Reproduction / 复现链接

http://home-v6.sdcom.asia:5244/lanzou
http://home-v6.sdcom.icu:5244/lanzou
（仅IPv6访问）
http://alist.sdcom.asia/lanzou
（临时使用frp）

### Config / 配置

[config.json](https://github.com/user-attachments/files/16486419/config.json)
![image](https://github.com/user-attachments/assets/55429c28-9978-4796-b151-d9f62f03e5d9)

### Logs / 日志

[GIN] 2024/08/03 - 18:12:39 | 207 |     560.825ms |    192.168.31.5 | PROPFIND  "/dav/lanzou"
[GIN] 2024/08/03 - 18:12:40 | 207 |    660.9736ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/病毒样本库"
[GIN] 2024/08/03 - 18:12:40 | 207 |    237.3511ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/辅助工具"
[GIN] 2024/08/03 - 18:12:41 | 207 |    235.3473ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/mc"
[GIN] 2024/08/03 - 18:12:41 | 207 |     156.229ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/工具"
[GIN] 2024/08/03 - 18:12:41 | 207 |    157.2298ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/OneThing-X86-Pro-1.1.20.ova"
[GIN] 2024/08/03 - 18:12:41 | 207 |    238.3528ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/资源库"
[GIN] 2024/08/03 - 18:12:42 | 207 |    234.3511ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/114514"
[GIN] 2024/08/03 - 18:12:42 | 207 |    154.2277ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/114514/test"
[GIN] 2024/08/03 - 18:12:42 | 207 |    234.3375ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/ocat"
[GIN] 2024/08/03 - 18:12:45 | 207 |    2.9373235s |    192.168.31.5 | PROPFIND  "/dav/lanzou/音乐"
[GIN] 2024/08/03 - 18:12:49 | 207 |    234.3422ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/test"
[GIN] 2024/08/03 - 18:12:49 | 207 |    233.3473ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/frp"
[GIN] 2024/08/03 - 18:12:50 | 207 |    237.3519ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/dmg"
[GIN] 2024/08/03 - 18:12:50 | 207 |    266.3847ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/QQbot"
[GIN] 2024/08/03 - 18:12:50 | 207 |    238.3523ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/小说"
[GIN] 2024/08/03 - 18:12:51 | 207 |    155.2307ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/小说/十宗罪系列"
[GIN] 2024/08/03 - 18:12:51 | 207 |    241.3561ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/小说/十宗罪系列/十宗罪2"
[GIN] 2024/08/03 - 18:12:51 | 207 |    238.3524ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/小说/十宗罪系列/十宗罪1"
[GIN] 2024/08/03 - 18:12:51 | 207 |    232.3468ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/Sonoma博通"
[GIN] 2024/08/03 - 18:12:51 | 207 |    160.2383ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/代理"
[GIN] 2024/08/03 - 18:12:52 | 207 |    236.3481ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/代理/Windows"
[GIN] 2024/08/03 - 18:12:52 | 207 |    234.3464ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/代理/macOS"
[GIN] 2024/08/03 - 18:12:52 | 207 |    492.7253ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/代理/android"
[GIN] 2024/08/03 - 18:12:53 | 207 |    245.3625ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/WindowsXP壁纸"
[GIN] 2024/08/03 - 18:12:53 | 207 |    247.3667ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/mc整合包"
[GIN] 2024/08/03 - 18:12:53 | 207 |    247.3662ms |    192.168.31.5 | PROPFIND  "/dav/lanzou/lucky"
[31mERRO[0m[2024-08-04 13:06:11] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:06:11] failed link /lanzou/资源库/Bandicam-7.0.0.2117-x64-Portable.7z: not find file page param
[31mERRO[0m[2024-08-04 13:06:20] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:06:20] failed link /lanzou/资源库/ApowerREC-v1.6.8.2-CN-Portable.7z: not find file page param
[31mERRO[0m[2024-08-04 13:06:23] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:06:23] failed link /lanzou/资源库/SakuraLauncher.exe: not find file page param
[31mERRO[0m[2024-08-04 13:06:32] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:06:32] failed link /lanzou/v2rayN-Core.7z: not find file page param
[31mERRO[0m[2024-08-04 13:06:40] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:06:40] failed link /lanzou/WinUninstaller.exe: not find file page param
[GIN] 2024/08/04 - 13:07:30 | 200 |            0s |    192.168.31.5 | GET      "/api/admin/driver/info?driver=Lanzou"
[31mERRO[0m[2024-08-04 13:07:50] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:07:50] failed link /lanzou/资源库/Bandicam-7.0.0.2117-x64-Portable.7z: not find file page param
[31mERRO[0m[2024-08-04 13:09:18] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:09:18] failed link /lanzou/资源库/SakuraLauncher.exe: not find file page param
[GIN] 2024/08/04 - 13:09:49 | 200 |      1.0013ms |    192.168.31.5 | GET      "/api/admin/driver/info?driver=Lanzou"
[GIN] 2024/08/04 - 13:09:59 | 200 |            0s |    192.168.31.5 | GET      "/api/admin/driver/info?driver=Lanzou"
[31mERRO[0m[2024-08-04 13:10:20] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:10:20] failed link /lanzou/资源库/Bandicam-7.0.0.2117-x64-Portable.7z: not find file page param
[31mERRO[0m[2024-08-04 13:10:25] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:10:25] failed link /lanzou/资源库/ToDesk_Setup.exe: not find file page param
[31mERRO[0m[2024-08-04 13:12:41] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:12:41] failed link /lanzou/资源库/ApowerREC-v1.6.8.2-CN-Portable.7z: not find file page param
[31mERRO[0m[2024-08-04 13:18:04] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:18:04] failed link /lanzou/资源库/ApowerREC-v1.6.8.2-CN-Portable.7z: not find file page param
[31mERRO[0m[2024-08-04 13:21:41] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:21:41] failed link /lanzou/ocat/OCAT-Win64.zip: not find file page param
[31mERRO[0m[2024-08-04 13:21:45] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:21:45] failed link /lanzou/ocat/OCAT_Mac10.12.and.below.dmg: not find file page param
[31mERRO[0m[2024-08-04 13:21:49] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:21:49] failed link /lanzou/v2rayN-Core.7z: not find file page param
[31mERRO[0m[2024-08-04 13:25:17] lanzou: err => not find file page param ,data =>  
[31mERRO[0m[2024-08-04 13:25:17] failed link /lanzou/ipsignature.zip: not find file page param
[GIN] 2024/08/04 - 13:35:45 | 200 |            0s |    192.168.31.5 | GET      "/api/admin/driver/info?driver=Lanzou"

这是今日所有和蓝奏云有关的日志

**Comment by rockxsj** [comment]
同样的问题
