### ISSUE TITLE
免密码登录

### ISSUE THREAD

**Issue by 2575044704** [alist-org/alist#6937]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我给群里的老哥分享资源，但是每次都要登录才能下载里面的文件，群友时不时找我要账号密码超烦人，有时候我连自己密码都不知道。我搜了一遍相关文档，暂时没找到取消密码方法。所以想新增一个免密登录的功能

### Suggested solution / 实现思路

两种方案：1.取消登录界面，打开后就能直接进入alist页面。
2. 打开页面后，自动填写用户名：admin 还有密码：xxx，别人就能直接进去网盘了。

**Comment by xhofe** [comment]
https://alist.nn.ci/zh/guide/advanced/user.html#tips
