### ISSUE TITLE
win挂载alist子账号登录上传错误bug

### ISSUE THREAD

**Issue by MJ-spmoon** [alist-org/alist#6945]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

win挂载alist，用子账号登录，向子账号挂载目录上传文件，提示网络错误或文件已存在，且上传文件大小为0kb。用主账号登录就不会出现此问题！

### Reproduction / 复现链接

![20240805000238](https://github.com/user-attachments/assets/a632b28e-aec0-4432-a905-0aa301121096)

### Config / 配置

      "username": "team",
      "password": "",
      "base_path": "/team",
      "role": 0,
      "disabled": false,
      "permission": 1020,
      "sso_id": ""

**Comment by Deepsea-CN** [comment]
你是否为子账号配置了webdav管理的权限

**Comment by MJ-spmoon** [comment]
权限全部勾选，并尝试多次


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月06日 09:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alist-org/alist] win挂载alist子账号登录上传错误bug (Issue #6945) |

你是否为子账号配置了webdav管理的权限

**Comment by Deepsea-CN** [comment]
那你测试过子账户在网页端可以正常上传吗

**Comment by MJ-spmoon** [comment]
网页端和第三方挂载都正常



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月06日 10:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alist-org/alist] win挂载alist子账号登录上传错误bug (Issue #6945) |

那你测试过子账户在网页端可以正常上传吗

**Comment by Deepsea-CN** [comment]
emm那我建议你换别的客户端在win上使用，比如rclone，filezilla这些，win自带的webdav客户端bug比较多，下载还好，上传很不稳定，我也试过上传文件，虽然没有报错，但是云端文件大小就是0，所以想挂载为磁盘还是用rclone，要稳定得多

**Comment by MJ-spmoon** [comment]
谢谢，还是希望能修复这个bug，第三方总归用的不方便，需要另外安装，单独启动，没有直接挂载为本地磁盘方便



在 2024-08-06 19:17:07，"Hexa" ***@***.***> 写道：

emm那我建议你换别的客户端在win上使用，比如rclone，filezilla这些，win自带的webdav客户端bug比较多，下载还好，上传很不稳定，我也试过上传文件，虽然没有报错，但是云端文件大小就是0，所以想挂载为磁盘还是用rclone，要稳定得多

**Comment by MJ-spmoon** [comment]
有没有可能是反代webdav导致的上传错误？（猜测），参考：
https://huaweicloud.csdn.net/63566846d3efff3090b5de78.html?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Eactivity-1-120566252-blog-88418255.235%5Ev39%5Epc_relevant_3m_sort_dl_base2&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Eactivity-1-120566252-blog-88418255.235%5Ev39%5Epc_relevant_3m_sort_dl_base2&utm_relevant_index=2



在 2024-08-06 19:17:07，"Hexa" ***@***.***> 写道：

emm那我建议你换别的客户端在win上使用，比如rclone，filezilla这些，win自带的webdav客户端bug比较多，下载还好，上传很不稳定，我也试过上传文件，虽然没有报错，但是云端文件大小就是0，所以想挂载为磁盘还是用rclone，要稳定得多

**Comment by Tidra** [comment]
确实是子账户无法做任何修改，但是admin账号可以，不知道吧子账号修改为管理员角色是不是可以解决
