### ISSUE TITLE
Availability of long-term Authorization 

### ISSUE THREAD

**Issue by Seele0oO** [alist-org/alist#6948]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

I noticed that the Authorization header in the alist v2 version was calculated via md5, in v3, this is implemented differently for security purposes.

I was wondering if it would be possible to provide a long term authentication method to make api calls and use webdav without exposing the original account password.

### Suggested solution / 实现思路

Allow accounts to generate their own bearer key in place of the account password.

**Comment by Muione** [comment]
You can create a new account for webdav only in current version.
