### ISSUE TITLE
关于下载度盘 pdf 等文档文件的新思路

### ISSUE THREAD

**Issue by JamesBrosy** [alist-org/alist#6949]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我是非svip用户，我在本地电脑的 `docker` 上部署的 `alist`，能看视频，但是作为网盘存书的重度用户，下载和预览百度网盘的 pdf 等文档文件，很重要，但是在 `alist` 预览时，`Failed to fetch`， `无效或损坏的 PDF 文件` 是常态，并且下载时返回 `code：500, failure,status: 403 response`，我感觉这应该不是office服务的问题 #3165 ，也不是 https 的问题 [#为什么我不能预览pdf文件](https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E8%83%BD%E9%A2%84%E8%A7%88-pdf-%E6%96%87%E4%BB%B6) 而是无法下载资源导致无法预览，我其他网盘都能预览。
#2181

所以有如下需求：已更快的速度下载和预览度盘 pdf 等文档文件，我仅在此提供如何提供更快下载pdf等文档的思路。

### Suggested solution / 实现思路

我平时能在手机app上通过如下方法，以几兆的速度下载百度网盘中的文档文件（下面是我在模拟器中的的思路复现）

<p>
    <span><img src="https://github.com/user-attachments/assets/430455a2-b7d5-4c07-a029-3611e1f3d583" height="800" /></span>
    <span><img src="https://github.com/user-attachments/assets/ca9cc0eb-452d-4522-8d39-82b39ff3067d" height="800" /></span>
    <br/>
    <span><img src="https://github.com/user-attachments/assets/62efe99f-221c-4ae2-8403-1215ad63ba72" height="800" /></span>
    <span><img src="https://github.com/user-attachments/assets/9497cc20-bc49-4f95-bfe8-aa8ec39417bb" height="800" /></span>
</p>

我尝试通过 `Burpsuite` 抓包解决：

![Screenshot_20240805_133559-1](https://github.com/user-attachments/assets/f960f692-4608-4ab4-b183-5c9ca8827a36)
![Screenshot_20240805_140815-1](https://github.com/user-attachments/assets/9d223e43-2bfc-4f0e-8b51-e55f9adaa04f)

我将上面获取到的 url 粘贴到 motrix 中，并修改 ua，速度很快：

![0-Screenshot_20240805_151250-2](https://github.com/user-attachments/assets/fcc25377-242d-4a2e-a45f-60b20ee97eef)
![Screenshot_20240805_152426](https://github.com/user-attachments/assets/d34ac75c-d6f1-482d-8307-ec9ad5a6de1d)

这里有个推荐项目：[BaiduPCS-Go](https://github.com/qjfoidnh/BaiduPCS-Go)，我这个项目中也提了差不多的 [BaiduPCS-Go #342](https://github.com/qjfoidnh/BaiduPCS-Go/issues/342) 。

**建议**

使用 BaiduPCS-Go 中登录百度网盘的方法，不需要刷新令牌，只需要 `cookie` 中的 `BDUSS` 值即可登录百度网盘，BaiduPCS-Go 获取到的直链和我获取的链接几乎没有区别，但是下载速度干差万别，具体看 issue [BaiduPCS-Go #342](https://github.com/qjfoidnh/BaiduPCS-Go/issues/342)

**最后**

我不知道是否能通过此方法下载音视频或者压缩文件，因为没办法在手机上使用相同思路下载它们。

**Comment by yucho123987** [comment]
> 建议直接开svip

垃圾百毒网盘开个锤子SVIP
