### ISSUE TITLE
Thunder浏览器 驱动提示 找不到文件 / 文件夹

### ISSUE THREAD

**Issue by GMBuilding** [alist-org/alist#6950]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

Thunder浏览器

### Describe the bug / 问题描述

使用 Thunder浏览器 挂载时候，进入其下 迅雷云盘 目录的文件夹/ 读取文件时候，有概率出现
```
failed get objs: failed get dir: failed get parent list: failed to list objs: ErrorCode: 5 ,Error: file_not_found ,ErrorDescription: 文件或文件夹不存在，请检查确认
```

但其在父目录可以正常显示，当点击时候无法打开

### Reproduction / 复现链接

内网暂无

### Config / 配置

![00866573444908d9032f1094e7184bf0.png](https://ice.frostsky.com/2024/08/05/00866573444908d9032f1094e7184bf0.png)

### Logs / 日志

failed get objs: failed get dir: failed get parent list: failed to list objs: ErrorCode: 5 ,Error: file_not_found ,ErrorDescription: 文件或文件夹不存在，请检查确认

**Comment by Three-taile-dragon** [comment]
可以试试新的PR #6952 
> 改进了特殊文件夹的识别方式，现在应该可以正确识别了

**Comment by GenshinMinecraft** [comment]
> 可以试试新的PR #6952
> 
> > 改进了特殊文件夹的识别方式，现在应该可以正确识别了

感谢，已经成功解决，希望下个版本merge
