### ISSUE TITLE
游客只可查阅不可下载功能

### ISSUE THREAD

**Issue by yckjgs** [alist-org/alist#6955]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

实现游客只可查阅不可下载功能。

**Comment by yckjgs** [comment]
> 下载代理URL乱填就不能下载了

要是管理员可以控制游客是否有下载按钮就更好了

**Comment by yckjgs** [comment]
手机端视频操作栏溢出，无法全屏处理，需优化下兼容性。
![2024-08-08_155828](https://github.com/user-attachments/assets/9939beab-bb92-489f-9139-711625f03370)

**Comment by Deepsea-CN** [comment]
> 手机端视频操作栏溢出，无法全屏处理，需优化下兼容性。 
确实有这毛病，但是请另开一个issue，一般一个issue只描述一个问题
