### ISSUE TITLE
Terabox Failed init storage: failed to check login status according to cookie

### ISSUE THREAD

**Issue by pentacuber1210** [alist-org/alist#6961]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

Terabox

### Describe the bug / 问题描述

无论是填cookie 还是jstoken 28%22xxxxxx%22%29，都显示的Failed init storage: failed to check login status according to cookie，用的是edge浏览器
![Screenshot 2024-08-07 184642](https://github.com/user-attachments/assets/6fdf4924-2e36-4d7d-8e2a-f39acb945bcf)
![Screenshot 2024-08-07 184547](https://github.com/user-attachments/assets/709e6d33-10ca-47a2-9824-ea9435dd1653)

### Reproduction / 复现链接

.

### Config / 配置

.

### Logs / 日志

ERRO[2024-08-11 08:28:48] failed get enabled storages: failed to check login status according to cookie
failed init storage
github.com/alist-org/alist/v3/internal/op.initStorage
        /source/internal/op/storage.go:99
github.com/alist-org/alist/v3/internal/op.LoadStorage
        /source/internal/op/storage.go:80
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
        /source/internal/bootstrap/storage.go:20
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1695

**Comment by orayneo1984** [comment]
Facing same issue, even existing TeraBox account also required new cookie verification, but failed as shown.

**Comment by URenko** [comment]
疑似账号分区，打开 terabox 网页版，看看你的域名是不是 www.terabox.com

---

It seems that the accounts are divided into different regions. Login the terabox website and check if your domain name is www.terabox.com

**Comment by orayneo1984** [comment]
> 疑似账号分区，打开 terabox 网页版，看看你的域名是不是 [www.terabox.com](http://www.terabox.com)
> 
> It seems that the accounts are divided into different regions. Login the terabox website and check if your domain name is [www.terabox.com](http://www.terabox.com)

是的。https://www.terabox.com
难道不应该是 www.terabox.com ？

**Comment by URenko** [comment]
你这个就比较奇怪了，有的是像最上面一样，跳转到 dm.terabox.com , 这似乎是根据账号的，所以要登录看看跳转到哪

**Comment by orayneo1984** [comment]
> 你这个就比较奇怪了，有的是像最上面一样，跳转到 dm.terabox.com , 这似乎是根据账号的，所以要登录看看跳转到哪

不好意思，有点误导了。
我有两个 Terabox 账号，上面显示的 https://www.terabox.com/ 是那个还能识别 cookie 的账号。

但是显示 cookie 错误的账号确实就是 跳转到 dm.terabox.com 的。
（PS: 刚刚用了另外一台电脑测试了那不能用 cookie 的）

**Comment by URenko** [comment]
https://github.com/URenko/alist/actions/runs/11071911885

可以尝试这一修复，过段时间提交

**Comment by orayneo1984** [comment]
> https://github.com/URenko/alist/actions/runs/11071911885
> 
> 可以尝试这一修复，过段时间提交

多谢！
由于我正在用的是 docker 镜像的 alist, 你的下载文件不清楚咋搞进 docker 所以还是等等吧。
不过还是感谢您提供解决帮助，还以为这 Terabox 不是国内热门网盘要等到天荒地老才能有补丁呢。

**Comment by gitiray** [comment]
> 疑似账号分区，打开 terabox 网页版，看看你的域名是不是 [www.terabox.com](http://www.terabox.com)
> 
> It seems that the accounts are divided into different regions. Login the terabox website and check if your domain name is [www.terabox.com](http://www.terabox.com)

我的域名强制跳转到 dm.terabox.com，Cookie内容很短，这种是无法使用吗？

**Comment by levanphuc342** [comment]
我在 alist localhost 上添加了 terabox，一切正常，但是当我将 alist 上传到 koyeb 后添加 terabox 时，出现错误“ Failed init storage but storage is already created: failed init storage: failed to check login status according to cookie”
![image](https://github.com/user-attachments/assets/c8db48a7-bb30-457f-acb4-92e549660b6e)
