### ISSUE TITLE
目录映射功能

### ISSUE THREAD

**Issue by zhbzxf** [alist-org/alist#6965]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

当有多个网盘时，能否将不同目录中的文件映射到同一目录，方便统一下载链接路径？

**Comment by Simonzhang8** [comment]
别名就可以实现

**Comment by Deepsea-CN** [comment]
创一个别名存储，只要添加同名文件夹，自动给你整合，具体规则看文档介绍
