### ISSUE TITLE
terabox上传，复制，离线下载出现 [terabox] failed to precreate file, errno: 58 / [terabox] failed to precreate file, errno: -7

### ISSUE THREAD

**Issue by lightworld689** [alist-org/alist#6983]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

Terabox

### Describe the bug / 问题描述

定位到terabox的目录，然后点击右下角“…”中的离线下载，然后转到后台就发现将下载的文件传输到相应的存储时出现错误：
![图片](https://github.com/user-attachments/assets/5634f96a-c9f5-465e-b58c-5c6bdb9f0d80)
![图片](https://github.com/user-attachments/assets/ee13bc52-5a15-4fc1-9666-2b49a05d8479)
```
transfer /opt/alist/data/temp/SimpleHttp/3ffb27ce-ea98-40f6-86b6-6f77c96c7132/__down to [/*PRIVACY*]
失败

transferring

[terabox] failed to precreate file, errno: -7

```
```
transfer /opt/alist/data/temp/SimpleHttp/8d878c23-8442-457f-bce2-70d824921d59/__down to [/*PRIVACY*]
失败

transferring

[terabox] failed to precreate file, errno: 58

```

补充：现在复制和上传也都炸了

### Reproduction / 复现链接

N/A

### Config / 配置

![图片](https://github.com/user-attachments/assets/7bafaa49-6939-4137-b0ea-e095f765eb4b)
![图片](https://github.com/user-attachments/assets/80421e87-67ee-450c-93f5-30bef073f3c6)

### Logs / 日志

![图片](https://github.com/user-attachments/assets/cb385e72-6035-4c76-b4cc-1c52a7052f64)
![图片](https://github.com/user-attachments/assets/60638286-e229-4355-89e7-2a47acee1564)
![图片](https://github.com/user-attachments/assets/1db46574-0aa0-41e7-aae6-112a1114f9cb)

**Comment by danicaStarR** [comment]
我也遇到了相似的问题，不过我是上传的时候出现这个错误`（failed to precreate file, errno: -7）`，其他操作均没有问题。

**Comment by 006lp** [comment]
我也是，不知道是什么原因

**Comment by lightworld689** [comment]
之前还只是离线下载有问题，现在上传复制又炸了，玄学

**Comment by Sudle2008** [comment]
我也遇到此问题，从其他盘复制到terabox时时报错
[terabox] failed to precreate file, errno: -7

**Comment by dsfseguo** [comment]
同样
[terabox] failed to precreate file, errno: -7

**Comment by The-GO** [comment]
我也是这样子，不知道可以考虑修复一下这个问题吗？
