### ISSUE TITLE
pikpak代理相关

### ISSUE THREAD

**Issue by jdysya** [alist-org/alist#6986]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

pikpak

### Describe the bug / 问题描述

挂载pikpak全局代理则正常使用，但实际上对应的直链并没有被墙，可以不走代理。
测试发现：
1. 若**不代理**直链(`dl-`开头的直链)和`api-drive.mypkpak.com`，则在官网可以正常加载和下载，但在alist中pikpak无法正常挂载，此时若采取一种投机的方法，即在挂载时让`api-drive.mypkpak.com`走代理，在挂载成功后可正常显示文件列表时，设置``api-drive.mypkpak.com``不走代理，此时可借助当前目录缓存的文件列表完成下载动作，且下载的文件名**正常**
2. 若**不代理**直链，**代理**`api-drive.mypkpak.com`，则可以正常挂载，但无法下载文件，在官网中是一样的情况（无法下载），此时直接访问直链会出现**访问 dl-a10b-1192.mypikpak.com 的请求遭到拒绝**字样，若开启clash的增强模式，则在alist中可正常下载，但下载速度很慢，在官网无法下载；
3. 若两者**均走代理**，则在alist中和官网中均**无法正常使用**，经测试是普通的终端代理命令无效，即:
```
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
```
此时，若开启`clash`的**增强模式**（记得清除掉之前的终端代理），即`TUN`模式，则在alist中可**正常**下载,而此时反而在官网**无法正常使用**

具如表格所示：
> 1. 对于`TUN`模式下，不知道规则判断是否还生效，在连接查看器中看不到详细的域名信息
> 2. 官网下，可以配合[油猴插件](https://github.com/xiaoziguys/pikpakHelpr) ，将文件下载请求推送到aria2(此插件有bug未修复，需要手动调整源代码，可参考https://github.com/xiaoziguys/pikpakHelpr/pull/8)

| 途径    | 代理方式  | 代理直链 | 代理api-drive | alist效果   | aria2效果     |
|-------|-------|------|-------------|-----------|-------------|
| alist | 终端代理  | 否    | 否           | ❌无法加载文件列表 |             |
| alist | 终端代理  | 否    | 是           | ❌可加载，无法下载 |     ❌无法下载        |
| alist | 终端代理  | 是    | 是           | ❌可加载，无法下载 |   ❌无法下载          |
| alist | TUN模式 | 否    | 否           | ❌无法加载文件列表 |   |
| alist | TUN模式 | 否    | 是           | ❌无法下载     | ✅可下载，但下载速度慢 |
| alist | TUN模式 | 是    | 是           | ✅可下载      | ✅可下载        |
| 官网    | 正常代理  | 否    | 否           | ✅正常       |             |
| 官网    | 正常代理  | 否    | 是           | ❌无法下载     |    ❌无法下载         |
| 官网    | 正常代理  | 是    | 是           | ✅正常       |             |
| 官网    | TUN模式 | 否    | 否           | ✅正常       |             |
| 官网    | TUN模式 | 否    | 是           | ❌无法下载     | ✅可下载        |
| 官网    | TUN模式 | 是    | 是           | ✅正常       |             |

所以有以下几个问题：
1. 为什么在`alist`中需要代理`api-drive.mypkpak.com`,否则就无法正常加载文件列表，而在官网不用？
2. 应该如何正确的获取到正确的直链进行下载？
3. 如何正确的绕开代理，避免大量消耗机场流量？

### Reproduction / 复现链接

无

### Config / 配置

alist为默认配置
<img width="389" alt="image" src="https://github.com/user-attachments/assets/f3dfea9c-7458-47a1-95af-1b3df5465d6e">
<img width="447" alt="image" src="https://github.com/user-attachments/assets/b7116d20-4d4e-4470-a7b6-f3bc1860e73a">

在`clash`中选择规则模式，添加规则如下，若取消注释，则会让`api-drive.mypikpak.com`走代理
```
rules:
rules:
    - 'DOMAIN,mypikpak.com,机场名'
    - 'DOMAIN,mypikpak.net,机场名'
    - 'DOMAIN,user.mypikpak.com,机场名'
    - 'DOMAIN,access.mypikpak.com,机场名'
    - 'DOMAIN,api-drive.mypikpak.com,DIRECT'
    - 'DOMAIN-KEYWORD,dl-a10b-,DIRECT'
 ```

**Comment by jdysya** [comment]
开启web代理即可
<img width="320" alt="image" src="https://github.com/user-attachments/assets/1434acc7-8c96-414b-99e8-7cadd8489f90">

**Comment by jdysya** [comment]
开启web代理后重启服务，可正常运行一段时间。
![image](https://github.com/user-attachments/assets/f65db6ca-8527-471c-9c36-55863c720c4b)

**Comment by jdysya** [comment]
修改clash代理如下，可解决问题
rules:
    - 'DOMAIN,mypikpak.com,大机场 Big Airport'
    - 'DOMAIN,mypikpak.net,大机场 Big Airport'
    - 'DOMAIN,user.mypikpak.com,大机场 Big Airport'
    - 'DOMAIN,access.mypikpak.com,大机场 Big Airport'
    - 'DOMAIN,api-drive.mypikpak.com,DIRECT'
    - 'DOMAIN-KEYWORD,dl-a10b-,DIRECT'

**Comment by anwen-anyi** [comment]
这个代理命令在终端是有效的吖，需要的是你在终端输入命令后还需要再用这个终端启动才行...当然命令中端口号忽略，每个软件的不一样
```txt
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
```

例如参考：
- https://anwen-anyi.github.io/index/07-wenti.html#_41-alist%E5%A6%82%E4%BD%95-%E4%BD%BF%E7%94%A8-%E5%90%83%E5%88%B0-%E4%BB%A3%E7%90%86-proxy

国内机器我测试一些国外网盘需要代理的我都是这样使用代理命令才启动的，
否则只开了普通代理不管用，代理工具我使用的是`V2rayN`
Clash的 `tun` 模式倒是不需要输入命令了

V2rayN设置了个路由规则中把如下链接都改成了 `direct` 没走直链速度可能比较慢（看自己需求）
```txt
vod0393-aliyun18-vip-lixian.mypikpak.com,
vod0394-aliyun18-vip-lixian.mypikpak.com,
vod0395-aliyun18-vip-lixian.mypikpak.com,
dl-a10b-0621.mypikpak.com,
dl-a10b-0622.mypikpak.com,
dl-a10b-0623.mypikpak.com,
dl-a10b-0624.mypikpak.com,
dl-a10b-0625.mypikpak.com,
dl-a10b-0393.mypikpak.com,
dl-a10b-0394.mypikpak.com,
dl-a10b-0395.mypikpak.com,
dl-a10b-0481.mypikpak.com,
dl-a10b-0483.mypikpak.com,
dl-a10b-0484.mypikpak.com,
dl-a10b-0585.mypikpak.com,
dl-a10b-0586.mypikpak.com,
dl-a10b-0046.mypikpak.com,
dl-a10b-0182.mypikpak.com,
dl-a10b-0183.mypikpak.com,
dl-a10b-0480.mypikpak.com,
dl-a10b-0482.mypikpak.com,
dl-a10b-0589.mypikpak.com,
dl-a10b-0593.mypikpak.com,
dl-a10b-0597.mypikpak.com,
dl-a10b-0822.mypikpak.com,
dl-a10b-0835.mypikpak.com,
dl-a10b-0858.mypikpak.com,
dl-a10b-0859.mypikpak.com,
dl-a10b-0860.mypikpak.com,
dl-a10b-0861.mypikpak.com,
dl-a10b-0862.mypikpak.com,
dl-a10b-0863.mypikpak.com,
dl-a10b-0864.mypikpak.com,
dl-a10b-0865.mypikpak.com,
dl-a10b-0866.mypikpak.com,
dl-a10b-0868.mypikpak.com,
dl-a10b-0869.mypikpak.com,
dl-a10b-0870.mypikpak.com,
dl-a10b-0871.mypikpak.com,
dl-a10b-0872.mypikpak.com,
dl-a10b-0874.mypikpak.com,
dl-a10b-0875.mypikpak.com,
dl-a10b-0876.mypikpak.com,
dl-a10b-0878.mypikpak.com,
dl-a10b-0879.mypikpak.com,
dl-a10b-0880.mypikpak.com,
dl-a10b-0881.mypikpak.com,
dl-a10b-0882.mypikpak.com,
dl-a10b-0883.mypikpak.com,
dl-a10b-0884.mypikpak.com,
dl-a10b-0885.mypikpak.com,
dl-a10b-0887.mypikpak.com,
dl-a10b-0822.mypikpak.com,
dl-a10b-0835.mypikpak.com,
dl-a10b-0858.mypikpak.com,
dl-a10b-0859.mypikpak.com,
dl-a10b-0860.mypikpak.com,
dl-a10b-0861.mypikpak.com,
dl-a10b-0862.mypikpak.com,
dl-a10b-0863.mypikpak.com,
dl-a10b-0864.mypikpak.com,
dl-a10b-0865.mypikpak.com,
dl-a10b-0866.mypikpak.com,
dl-a10b-0867.mypikpak.com,
dl-a10b-0868.mypikpak.com,
dl-a10b-0869.mypikpak.com,
dl-a10b-0870.mypikpak.com,
dl-a10b-0871.mypikpak.com,
dl-a10b-0872.mypikpak.com,
dl-a10b-0873.mypikpak.com,
dl-a10b-0874.mypikpak.com,
dl-a10b-0875.mypikpak.com,
dl-a10b-0876.mypikpak.com,
dl-a10b-0877.mypikpak.com,
dl-a10b-0878.mypikpak.com,
dl-a10b-0879.mypikpak.com,
dl-a10b-0880.mypikpak.com,
dl-a10b-0881.mypikpak.com,
dl-a10b-0882.mypikpak.com,
dl-a10b-0883.mypikpak.com,
dl-a10b-0884.mypikpak.com,
dl-a10b-0885.mypikpak.com,
dl-a10b-0886.mypikpak.com,
dl-a10b-0887.mypikpak.com
```

**Comment by jdysya** [comment]
> 这个代理命令在终端是有效的吖，需要的是你在终端输入命令后还需要再用这个终端启动才行...当然命令中端口号忽略，每个软件的不一样
> ```txt
> export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
> ```
> 
> 例如参考：
> - https://anwen-anyi.github.io/index/07-wenti.html#_41-alist%E5%A6%82%E4%BD%95-%E4%BD%BF%E7%94%A8-%E5%90%83%E5%88%B0-%E4%BB%A3%E7%90%86-proxy
> 
> 国内机器我测试一些国外网盘需要代理的我都是这样使用代理命令才启动的，
> 否则只开了普通代理不管用，代理工具我使用的是`V2rayN`
> Clash的 `tun` 模式倒是不需要输入命令了
> 
> V2rayN设置了个路由规则中把如下链接都改成了 `direct` 没走直链速度可能比较慢（看自己需求）
> ```txt
> vod0393-aliyun18-vip-lixian.mypikpak.com,
> vod0394-aliyun18-vip-lixian.mypikpak.com,
> vod0395-aliyun18-vip-lixian.mypikpak.com,
> dl-a10b-0621.mypikpak.com,
> dl-a10b-0622.mypikpak.com,
> dl-a10b-0623.mypikpak.com,
> dl-a10b-0624.mypikpak.com,
> dl-a10b-0625.mypikpak.com,
> dl-a10b-0393.mypikpak.com,
> dl-a10b-0394.mypikpak.com,
> dl-a10b-0395.mypikpak.com,
> dl-a10b-0481.mypikpak.com,
> dl-a10b-0483.mypikpak.com,
> dl-a10b-0484.mypikpak.com,
> dl-a10b-0585.mypikpak.com,
> dl-a10b-0586.mypikpak.com,
> dl-a10b-0046.mypikpak.com,
> dl-a10b-0182.mypikpak.com,
> dl-a10b-0183.mypikpak.com,
> dl-a10b-0480.mypikpak.com,
> dl-a10b-0482.mypikpak.com,
> dl-a10b-0589.mypikpak.com,
> dl-a10b-0593.mypikpak.com,
> dl-a10b-0597.mypikpak.com,
> dl-a10b-0822.mypikpak.com,
> dl-a10b-0835.mypikpak.com,
> dl-a10b-0858.mypikpak.com,
> dl-a10b-0859.mypikpak.com,
> dl-a10b-0860.mypikpak.com,
> dl-a10b-0861.mypikpak.com,
> dl-a10b-0862.mypikpak.com,
> dl-a10b-0863.mypikpak.com,
> dl-a10b-0864.mypikpak.com,
> dl-a10b-0865.mypikpak.com,
> dl-a10b-0866.mypikpak.com,
> dl-a10b-0868.mypikpak.com,
> dl-a10b-0869.mypikpak.com,
> dl-a10b-0870.mypikpak.com,
> dl-a10b-0871.mypikpak.com,
> dl-a10b-0872.mypikpak.com,
> dl-a10b-0874.mypikpak.com,
> dl-a10b-0875.mypikpak.com,
> dl-a10b-0876.mypikpak.com,
> dl-a10b-0878.mypikpak.com,
> dl-a10b-0879.mypikpak.com,
> dl-a10b-0880.mypikpak.com,
> dl-a10b-0881.mypikpak.com,
> dl-a10b-0882.mypikpak.com,
> dl-a10b-0883.mypikpak.com,
> dl-a10b-0884.mypikpak.com,
> dl-a10b-0885.mypikpak.com,
> dl-a10b-0887.mypikpak.com,
> dl-a10b-0822.mypikpak.com,
> dl-a10b-0835.mypikpak.com,
> dl-a10b-0858.mypikpak.com,
> dl-a10b-0859.mypikpak.com,
> dl-a10b-0860.mypikpak.com,
> dl-a10b-0861.mypikpak.com,
> dl-a10b-0862.mypikpak.com,
> dl-a10b-0863.mypikpak.com,
> dl-a10b-0864.mypikpak.com,
> dl-a10b-0865.mypikpak.com,
> dl-a10b-0866.mypikpak.com,
> dl-a10b-0867.mypikpak.com,
> dl-a10b-0868.mypikpak.com,
> dl-a10b-0869.mypikpak.com,
> dl-a10b-0870.mypikpak.com,
> dl-a10b-0871.mypikpak.com,
> dl-a10b-0872.mypikpak.com,
> dl-a10b-0873.mypikpak.com,
> dl-a10b-0874.mypikpak.com,
> dl-a10b-0875.mypikpak.com,
> dl-a10b-0876.mypikpak.com,
> dl-a10b-0877.mypikpak.com,
> dl-a10b-0878.mypikpak.com,
> dl-a10b-0879.mypikpak.com,
> dl-a10b-0880.mypikpak.com,
> dl-a10b-0881.mypikpak.com,
> dl-a10b-0882.mypikpak.com,
> dl-a10b-0883.mypikpak.com,
> dl-a10b-0884.mypikpak.com,
> dl-a10b-0885.mypikpak.com,
> dl-a10b-0886.mypikpak.com,
> dl-a10b-0887.mypikpak.com
> ```

按照我的测试，必须要api-drive.mypikpak.com和直链同时不走代理才能正常使用，之前出现问题是因为代理规则有点问题，clash的配置里有keyword这个判断方式，以dl-a10b-作为关键字，可实现相关直链不走代理，就不需要像你这样写这么多了

**Comment by anwen-anyi** [comment]
> 按照我的测试，必须要api-drive.mypikpak.com和直链同时不走代理才能正常使用，之前出现问题是因为代理规则有点问题，clash的配置里有keyword这个判断方式，以dl-a10b-作为关键字，可实现相关直链不走代理，就不需要像你这样写这么多了

跟以前是可以播放的，现在不能我大概猜到了是什么原因，大概是1个月前的一次pikpak更新导致的吧，
- 例如你在 IP 1.1.1.1服务器搭建的AList，但是你本人IP是2.2.2.2，无法播放下载，或者开启代理中转策略
  - 也就导致现在代理获取列表的API(api-drive.mypikpak.com)，但是不代理直链，不能播放

**Comment by jdysya** [comment]
> > 按照我的测试，必须要api-drive.mypikpak.com和直链同时不走代理才能正常使用，之前出现问题是因为代理规则有点问题，clash的配置里有keyword这个判断方式，以dl-a10b-作为关键字，可实现相关直链不走代理，就不需要像你这样写这么多了
> 
> 跟以前是可以播放的，现在不能我大概猜到了是什么原因，大概是1个月前的一次pikpak更新导致的吧，
> 
> * 例如你在 IP 1.1.1.1服务器搭建的AList，但是你本人IP是2.2.2.2，无法播放下载，或者开启代理中转策略
>   
>   * 也就导致现在代理获取列表的API(api-drive.mypikpak.com)，但是不代理直链，不能播放

但是不代理`api-drive.mypikpak.com`，alist无法获取文件列表，明明我不挂代理能ping通这个地址
