### ISSUE TITLE
建议icloud drive驱动

### ISSUE THREAD

**Issue by at86397388** [alist-org/alist#6998]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

建议icloud drive驱动

**Comment by at86397388** [comment]
增加苹果icloud驱动，然后实现webdav挂载

**Comment by SheltonZhu** [comment]
这个难度有点大，之前想搞来着，苹果的安全太难突破了
