### ISSUE TITLE
网易云音乐云盘出现错误

### ISSUE THREAD

**Issue by xiaomo-xxx** [alist-org/alist#7010]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

网易云音乐

### Describe the bug / 问题描述

错误failed get objs: failed to list objs: Post "https://music.163.com/weapi/v1/cloud/get": net/http: invalid header field value for "Cookie"

### Reproduction / 复现链接

failed get objs: failed to list objs: Post "https://music.163.com/weapi/v1/cloud/get": net/http: invalid header field value for "Cookie"

### Config / 配置

![QQ20240814-224422](https://github.com/user-attachments/assets/132995bd-c4eb-4f45-8ce0-922aa36cc89b)

### Logs / 日志

![QQ20240814-224422](https://github.com/user-attachments/assets/ba4e7329-9918-404d-b1d9-f70da8b9fe7e)

**Comment by laorentou666** [comment]
两个cookie的值之间不要换行

![Image](https://github.com/user-attachments/assets/23ac4413-0442-4eee-899b-e444833405c1)

**Comment by xiaomo-xxx** [comment]
> 两个cookie的值之间不要换行
> 
> ![Image](https://github.com/user-attachments/assets/23ac4413-0442-4eee-899b-e444833405c1)

问题已经解决了，是我cookie复制错了
