### ISSUE TITLE
能否挂载小雅后，将小雅的文件，复制（秒传）到115网盘，而不是先下载。

### ISSUE THREAD

**Issue by wangzixin100** [alist-org/alist#7015]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

能否挂载小雅后，将小雅的文件，复制（秒传）到115网盘，而不是先下载。

**Comment by xrgzs** [comment]
小雅的问题建议去小雅那边反馈
