### ISSUE TITLE
回退版本后密码错误 ！！

### ISSUE THREAD

**Issue by kitkw** [alist-org/alist#7029]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.16.3

### Driver used / 使用的存储驱动

Onedrive APP

### Describe the bug / 问题描述

最版 rclone 上传 ondrive 一直不成功（上传一段时间后完成没速度）。我记得v3.16.3 是正常的，但不小心升级了latest 当再次回退v3.16.3时登录不上 ，在latest上登录是正常的。
![image](https://github.com/user-attachments/assets/c8fbe3bb-8d34-4196-bb23-af54651291a3)

### Reproduction / 复现链接

略

### Config / 配置

略

**Comment by xhofe** [comment]
请重置密码，不再支持获取密码信息。

**Comment by kitkw** [comment]
> 请重置密码，不再支持获取密码信息。

重置后没有反应，还是一直报密码错误
