### ISSUE TITLE
本地存储   本地访问加载慢

### ISSUE THREAD

**Issue by GithubGey** [alist-org/alist#7031]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

/3.36

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

使用的本地存储，照片也不多   ，进去页面会转很久的圈。
![Screenshot_2024-08-18-04-43-30-91_32cba261fc08a501ce70de75bdbe2575](https://github.com/user-attachments/assets/36b9ab07-9616-48f9-bb5f-d0db1b471c67)

使用localhost和内网访问   都存在这个这个问题

### Reproduction / 复现链接

 localhost:5244

### Config / 配置

  默认，未修改

**Comment by BlueSkyXN** [comment]
也许你的不多就是很多
