### ISSUE TITLE
115 云盘分享：很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。

### ISSUE THREAD

**Issue by x1ao4** [alist-org/alist#7034]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

115 云盘分享

### Describe the bug / 问题描述

目前向 AList 添加 115 云盘分享会出现一个问题，115 似乎对单次请求的文件数量进行了限制，超过限制会出现 “很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。” 提示，并且会导致该用户所在的网络暂时无法访问所有的 115 分享链接，也会导致 AList 的所有 115 云盘分享出现这个报错。

比如我同时在 AList 添加了一个包含 200 个文件夹的 115 云盘分享和一个包含 2000 个文件夹的 115 云盘分享，先打开 200 个的，是可以正常访问的，然后打开 2000 个的，就会报错，然后 200 个的也会报错。过一阵子，对用户 IP 的限制会解除，此时 200 个的可以恢复正常访问，但如果再次打开 2000 个的，又会导致所有 115 云盘分享都无法访问。（自己的 115 网盘不受影响，仅影响 115 分享）

这个无法访问的问题确实不仅局限在 AList 内部，而是当出现超过限制的请求后 115 对用户的 IP 进行了暂时的封禁（标记异常），导致用户无法访问任何 115 分享链接，包括直接访问 115 分享的网页也会提示异常。

但由于测试后发现文件数量会影响结果，我猜测是否和单次请求文件数量有关？AList 是否可以增加一个分批次获取列表的机制？我目前测试的是 230 不会触发异常，2300 会，不知道具体的临界值是多少，有没有可能在请求列表时设置一个临界值以内的值，超过这个值的分批次获取列表，这样是否就不会触发异常了？

### Reproduction / 复现链接

localhost:5244

### Config / 配置

默认

**Comment by hnzhaihui** [comment]
我发现之前获取过115分享大包的路由器安装的alist，还是可以继续访问，获取文件列表一旦超过一定数量就会触发405错误，访问即被阻断。最好就是能增加分批次（例如200）获取文件列表的功能就能绕过115的检测了。

**Comment by x1ao4** [comment]
> 最好就是能增加分批次（例如200）获取文件列表的功能就能绕过115的检测了

这个分批请求的方式小雅已经测试过了，单次请求的值可以设置到 1500 都不会异常，基本上验证了我的猜测。

![11](https://github.com/user-attachments/assets/088e6bbc-8f27-490a-81d9-9db8420dfbcb)

但是目前对于 AList 来说，他的所有存储都是一次性获取所有项目的，不知道有没有办法单独给 115 分享增加一个分批获取的功能。但基本上分批获取项目应该确实可以解决这个问题。

**Comment by x1ao4** [comment]
![WX20240819-215731@2x](https://github.com/user-attachments/assets/70f5ea07-9535-4a6c-8575-6246e5fb2e6d)

测试把这个分页大小改成 1500 就不会异常了，这样应该就是修改了单次请求的项目数量，原本分页大小是 20，如果有 2000 个文件夹就要请求 100 次，现在分页大小是 1500，2000 个文件夹只需要请求 2 次，所以就不会异常了。

**Comment by spin6lock** [comment]
我这边是打开云下载的具体电影目录才会出现这个警告，云下载目录本身没有问题，具体电影目录内文件数目应该不超过10个，我用的分页类型是“加载更多”，115的分页大小已经改为1500了，还是遇到相同的报错

**Comment by spin6lock** [comment]
另外，我是看自己的115网盘内容，不是115网盘分享，但似乎阿里云405的issue都会说跟这个issue重复而被关闭，所以提到这里

**Comment by x1ao4** [comment]
> 我这边是打开云下载的具体电影目录才会出现这个警告，云下载目录本身没有问题，具体电影目录内文件数目应该不超过10个，我用的分页类型是“加载更多”，115的分页大小已经改为1500了，还是遇到相同的报错

异常出现后需要等待一段时间才会恢复，恢复后使用此方案才可以正常访问，你可以等你能正常访问 115 分享链接以后在进行修改和测试。不知道你自己的网盘异常的时候，分享链接是否也会异常，我的分享链接异常是不影响自己的 115 网盘的。

**Comment by spin6lock** [comment]
现在好了，感谢

**Comment by Z2112** [comment]
我也是这样，分页设置10，打开一个1150个文件的目录，然后播放视频，没一分钟就限制了。

**Comment by x1ao4** [comment]
> 我也是这样，分页设置10，打开一个1150个文件的目录，然后播放视频，没一分钟就限制了。

建议「分页大小」设置为 100-1500 左右，你设置 10 当然是不可以的。

**Comment by Z2112** [comment]
> > 我也是这样，分页设置10，打开一个1150个文件的目录，然后播放视频，没一分钟就限制了。
> 
> 建议「分页大小」设置为 100-1500 左右，你设置 10 当然是不可以的。
> 
> 原本分页大小是 20，如果有 2000 个文件夹就要请求 100 次，现在分页大小是 1500，2000 个文件夹只需要请求 2 次，所以就不会异常了。

但我测试了10-1500区间，不管是20、100、200、500、1000、1500都不行。都会限制。后面看CD2更新，说是限制了线程数为4，我就用CD2挂载了，现在也没有出问题。

**Comment by LouisLoong** [comment]
> > > 我也是这样，分页设置10，打开一个1150个文件的目录，然后播放视频，没一分钟就限制了。
> > 
> > 
> > 建议「分页大小」设置为 100-1500 左右，你设置 10 当然是不可以的。
> > 原本分页大小是 20，如果有 2000 个文件夹就要请求 100 次，现在分页大小是 1500，2000 个文件夹只需要请求 2 次，所以就不会异常了。
> 
> 但我测试了10-1500区间，不管是20、100、200、500、1000、1500都不行。都会限制。后面看CD2更新，说是限制了线程数为4，我就用CD2挂载了，现在也没有出问题。

我也是，不管怎么改，只要infuse/vidhub刷新一下媒体库甚至操作频繁了就又会被限制。太苦恼啦！
请问你说的CD2是什么？在哪挂载？怎么配置？多谢！

**Comment by Z2112** [comment]
> > > > 我也是这样，分页设置10，打开一个1150个文件的目录，然后播放视频，没一分钟就限制了。
> > > 
> > > 
> > > 建议「分页大小」设置为 100-1500 左右，你设置 10 当然是不可以的。
> > > 原本分页大小是 20，如果有 2000 个文件夹就要请求 100 次，现在分页大小是 1500，2000 个文件夹只需要请求 2 次，所以就不会异常了。
> > 
> > 
> > 但我测试了10-1500区间，不管是20、100、200、500、1000、1500都不行。都会限制。后面看CD2更新，说是限制了线程数为4，我就用CD2挂载了，现在也没有出问题。
> 
> 我也是，不管怎么改，只要infuse/vidhub刷新一下媒体库甚至操作频繁了就又会被限制。太苦恼啦！ 请问你说的CD2是什么？在哪挂载？怎么配置？多谢！

CloudDrive2，可以挂载本地。

**Comment by LouisLoong** [comment]
> > > > > 我也是这样，分页设置10，打开一个1150个文件的目录，然后播放视频，没一分钟就限制了。
> > > > 
> > > > 
> > > > 建议「分页大小」设置为 100-1500 左右，你设置 10 当然是不可以的。
> > > > 原本分页大小是 20，如果有 2000 个文件夹就要请求 100 次，现在分页大小是 1500，2000 个文件夹只需要请求 2 次，所以就不会异常了。
> > > 
> > > 
> > > 但我测试了10-1500区间，不管是20、100、200、500、1000、1500都不行。都会限制。后面看CD2更新，说是限制了线程数为4，我就用CD2挂载了，现在也没有出问题。
> > 
> > 
> > 我也是，不管怎么改，只要infuse/vidhub刷新一下媒体库甚至操作频繁了就又会被限制。太苦恼啦！ 请问你说的CD2是什么？在哪挂载？怎么配置？多谢！
> 
> CloudDrive2，可以挂载本地。

意思是不用AList了，换CloudDrive2？

**Comment by Z2112** [comment]
> > > > > > 我也是这样，分页设置10，打开一个1150个文件的目录，然后播放视频，没一分钟就限制了。
> > > > > 
> > > > > 
> > > > > 建议「分页大小」设置为 [100-1500](tel:100-1500) 左右，你设置 10 当然是不可以的。
> > > > > 原本分页大小是 20，如果有 2000 个文件夹就要请求 100 次，现在分页大小是 1500，2000 个文件夹只需要请求 2 次，所以就不会异常了。
> > > > 
> > > > 
> > > > 但我测试了10-1500区间，不管是20、100、200、500、1000、1500都不行。都会限制。后面看CD2更新，说是限制了线程数为4，我就用CD2挂载了，现在也没有出问题。
> > > 
> > > 
> > > 我也是，不管怎么改，只要infuse/vidhub刷新一下媒体库甚至操作频繁了就又会被限制。太苦恼啦！ 请问你说的CD2是什么？在哪挂载？怎么配置？多谢！
> > 
> > 
> > CloudDrive2，可以挂载本地。
> 
> 意思是不用AList了，换CloudDrive2？

我用CD2本地挂载给EMBY了。

**Comment by LouisLoong** [comment]
> > > > > > > 我也是这样，分页设置10，打开一个1150个文件的目录，然后播放视频，没一分钟就限制了。
> > > > > > 
> > > > > > 
> > > > > > 建议「分页大小」设置为 100-1500 左右，你设置 10 当然是不可以的。
> > > > > > 原本分页大小是 20，如果有 2000 个文件夹就要请求 100 次，现在分页大小是 1500，2000 个文件夹只需要请求 2 次，所以就不会异常了。
> > > > > 
> > > > > 
> > > > > 但我测试了10-1500区间，不管是20、100、200、500、1000、1500都不行。都会限制。后面看CD2更新，说是限制了线程数为4，我就用CD2挂载了，现在也没有出问题。
> > > > 
> > > > 
> > > > 我也是，不管怎么改，只要infuse/vidhub刷新一下媒体库甚至操作频繁了就又会被限制。太苦恼啦！ 请问你说的CD2是什么？在哪挂载？怎么配置？多谢！
> > > 
> > > 
> > > CloudDrive2，可以挂载本地。
> > 
> > 
> > 意思是不用AList了，换CloudDrive2？
> 
> 我用CD2本地挂载给EMBY了。

多谢，貌似不适合我的场景，我是想在路由器上搞。只能等AList更新或者看有没有别的解决方案

**Comment by x1ao4** [comment]
> 多谢，貌似不适合我的场景，我是想在路由器上搞。只能等AList更新或者看有没有别的解决方案

你可以尝试把 115 存储的「限制速率」改成「2」，默认是「0」，应该就是不限制。

**Comment by LouisLoong** [comment]
> > 多谢，貌似不适合我的场景，我是想在路由器上搞。只能等AList更新或者看有没有别的解决方案
> 
> 你可以尝试把 115 存储的「限制速率」改成「2」，默认是「0」，应该就是不限制。

「限制速率」改成「1」了，目前良好，换之前相同操作早就崩了，就是打开列表有点慢。
他的单位写的是：限制所有 api 请求速率(1r/[limit_rate]s)，感觉改成「1」已经是最快的了，改成「2」的话是2秒才能请求1次？

**Comment by x1ao4** [comment]
> 改成「2」的话是2秒才能请求1次？

看起来好像是那个意思，我也不确定。

**Comment by hnzhaihui** [comment]
> ![WX20240819-215731@2x](https://private-user-images.githubusercontent.com/112841659/359127528-70f5ea07-9535-4a6c-8575-6246e5fb2e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTc1MjcsIm5iZiI6MTcyNTk1NzIyNywicGF0aCI6Ii8xMTI4NDE2NTkvMzU5MTI3NTI4LTcwZjVlYTA3LTk1MzUtNGE2Yy04NTc1LTYyNDZlNWZiMmU2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwODMzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDFiMjBkNmEwZjIwNWJhNTBiNTE3NWQ1MTA0OTNjNGVhZDBiYTI2N2ZhZjQ0Nzc1ZmMwNTI1YzhiNTRkY2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-HCcxZbcMmUaTdpr_w8A17rs0qm1yjsTiAh164Ux4Ag)
> 
> 测试把这个分页大小改成 1500 就不会异常了，这样应该就是修改了单次请求的项目数量，原本分页大小是 20，如果有 2000 个文件夹就要请求 100 次，现在分页大小是 1500，2000 个文件夹只需要请求 2 次，所以就不会异常了。
> 
> 如果你在 AList 挂载 115 分享出现了 “很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。” 提示，你可以在 AList 的「设置-站点-分页类型」中将分页类型设置为「分页/加载更多/自动加载更多」中的一种，或者设置 115 云盘分享的「分页大小」为 100-1500 左右。这样可以降低短时间内的请求次数，防止被判定为异常访问，就不会报错了（异常出现后需要等待一段时间才会恢复，恢复后使用此方案才可以正常访问，你可以等你能正常访问 115 分享链接以后在进行修改和测试）。

115分享挂载列表异常后，修改分页大小为1000，现在文件列表访问都可以了，但是windwos挂载却不能播放了，potplayer加载文件后就一直转圈不播放，也不错误提示，但是自己的115网盘内容的挂载可以正常播放，不知道哪里又出了问题。

**Comment by ivensfor** [comment]
> > 115分享挂载列表异常后，修改分页大小为1000，现在文件列表访问都可以了，但是windwos挂载却不能播放了，potplayer加载文件后就一直转圈不播放，也不错误提示，但是自己的115网盘内容的挂载可以正常播放，不知道哪里又出了问题。
> 
> 我还是改的1500，改不改这个对我影响不大。我把「限制速率」改成「1」了，获取列表时慢点，但一切正常了。包括115浏览器本身、AList、CloudDrive2

請問你把 `限制速率` 改成 `1` 之後，是同時使用 alist 和 clouddrive2 都正常嗎？我前幾天試過同時使用會觸發風控。

**Comment by LouisLoong** [comment]
> 請問你把 `限制速率` 改成 `1` 之後，是同時使用 alist 和 clouddrive2 都正常嗎？我前幾天試過同時使用會觸發風控。

都在使用，有没有“同一时刻”不清楚，应该是没有。
总之改成1之后，再也没出现过风控提示。只是打开大目录的速度慢了一些

**Comment by Saber0517** [comment]
> 我还是改的1500，改不改这个对我影响不大。我把「限制速率」改成「1」了，获取列表时慢点，但一切正常了。包括115浏览器本身、AList、CloudDrive2

works for me!

**Comment by Zhowl** [comment]
更新cookie解决

**Comment by Xiangyi-Deng** [comment]
修改这个参数,  建议「分页大小」  其实 和你 的文件 多少有关系, 而不是盲目的 100-1500
我感觉.

**Comment by Z2112** [comment]
> 修改这个参数, 建议「分页大小」 其实 和你 的文件 多少有关系, 而不是盲目的 100-1500 我感觉.

你说的对，我之前一个文件夹内有1150个目录，访问就报错，不管设置多少都报错，把每个文件夹弄115个就再没有报错过了。
