### ISSUE TITLE
115网盘挂载分享链接出现405：很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断

### ISSUE THREAD

**Issue by thshu** [alist-org/alist#7038]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

115 云盘分享

### Describe the bug / 问题描述

主文件夹可以正常加载，但是所有的子文件夹都加载失败
![image](https://github.com/user-attachments/assets/8f1b9a0f-c609-4d51-b712-95a7eb3ce8b8)

### Reproduction / 复现链接

分享码：swz6s743fwo
提取码：8888

### Config / 配置

![image](https://github.com/user-attachments/assets/9bea41bc-66a0-4ba7-93df-4e647eb4766c)

**Comment by x1ao4** [comment]
如果你在 AList 挂载 115 分享出现了 “很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。” 提示，你可以在 AList 的「设置-站点-分页类型」中将分页类型设置为「分页/加载更多/自动加载更多」中的一种，或者设置 115 云盘分享的「分页大小」为 100-1500 左右。这样可以降低短时间内的请求次数，防止被判定为异常访问，就不会报错了。

**Comment by sun3u** [comment]
v3.39.1,目前又出现这个报错了，我看了下  分页 默认是1000,
