### ISSUE TITLE
搜索问题，没有访问文件夹权限的用户，搜索结果前几页是空白的

### ISSUE THREAD

**Issue by LemonPG** [alist-org/alist#7054]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

左边是管理员用户有全部文件夹的访问权限，正常搜索出来全部结果。
右边是普通用户有一部分访问文件夹权限，搜索结果前几页是空白的，点到第五页才有数据。
![image](https://github.com/user-attachments/assets/3ae664a2-4f26-44d9-a9f9-09f3216813eb)
![image](https://github.com/user-attachments/assets/c26e67fe-5db4-4786-a9d7-8558683f2e7f)

### Reproduction / 复现链接

NA

### Config / 配置

![image](https://github.com/user-attachments/assets/ea5bc3ac-c100-4fd3-a222-d938d2bc758f)

### Logs / 日志

NA

**Comment by Insulinocytus** [comment]
我也出现了类似的问题，现象和你一模一样。
我在思考这个搜索功能是不是没有考虑到别名的情况。

比如我的本地数据储存在
```
/data/foo
/data/bar
```

然后我创建别名
```
/user/hoge => /data/foo
```

最后把这个别名作为新用户hoge的初始路径

这样当我以用户hoge登录时，我就能看到一个foo文件夹
然后我创建索引，开始搜索foo文件夹里的文件时，就会出现无搜索结果但是翻页却有一堆的情况
