### ISSUE TITLE
播放器能支持flv嘛

### ISSUE THREAD

**Issue by woshichenbenshuai** [alist-org/alist#7055]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在视频播放器不支持flv呢 提示video.994f2170.js:9 [TransmuxingController] > Non-FLV, Unsupported media type!

**Comment by Simonzhang8** [comment]
是你视频有问题吧？实测flv可以播放

**Comment by woshichenbenshuai** [comment]
https://pan.quark.cn/s/42f95cbc4518  看不出什么异常呀

**Comment by woshichenbenshuai** [comment]
![image](https://github.com/user-attachments/assets/6fcfa500-92e9-49f8-9b19-0cb3903aae17)

**Comment by caixin1218** [comment]
任何格式的视频视频都无法播放，音频文件可以。不知道是什么原因

**Comment by Simonzhang8** [comment]
> 任何格式的视频视频都无法播放，音频文件可以。不知道是什么原因

单独提一个Issue或Discussion
