### ISSUE TITLE
离线下载的暂存路径是否有更好的方案

### ISSUE THREAD

**Issue by Huiyicc** [alist-org/alist#7063]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

alist使用aria2或者bt等离线下载时会修改默认下载地址为alist/data/temp下,此时如果是物理机还好，可以将temp挂载到大容量分区,但是如果此时使用的是docker容器,会出现如下情况:
- alist处在docker内的/opt/alist
- alist创建任务,指定下载路径为/opt/alist/data/temp
- aria2/bt下载器下载到/opt/alist/data/temp
- 此时下载器下载的路径依旧是相对下载器能访问的系统/容器目录,alist由于系统隔离/容器隔离无法找到对应路径,导致离线下载失败/文件太大导致磁盘空间爆满(因为下载器直接在系统的opt/alist下下载东西了)

### Suggested solution / 实现思路

想要解决依旧是手动将系统上相对于容器的temp路径挂载到其他分区,这个是否有更好的解决方案
例如配置内指定暂存目录或者使用下载器的默认目录?

**Comment by anwen-anyi** [comment]
我不太会用docker，Docker没记错的话可以映射多个路径吧？你映射几个大容量分区的就好？

**Comment by Huiyicc** [comment]
> 我不太会用docker，Docker没记错的话可以映射多个路径吧？你映射几个大容量分区的就好？

目前确实是这样，用的是1panel提供的容器，我需要在fstab内挂载这两个路径，还是挺麻烦的,配置之前离线下载一个镜像塞满了整个系统分区给我干蒙了😢
![image](https://github.com/user-attachments/assets/4eb1b5c4-b2ce-47c1-ba90-8b0e03ccda15)
