### ISSUE TITLE
Windows的版本重启之后，会把/data/temp文件夹删掉

### ISSUE THREAD

**Issue by JoeNik** [alist-org/alist#7067]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.36.0

### Driver used / 使用的存储驱动

aliyunopen

### Describe the bug / 问题描述

程序重启之后会把data目录下的temp给删除，并且不会自动创建，这样复制文件的时候就出现错误,错误日志贴在下面了，同时这个问题在v3.35.0是不存在的

### Reproduction / 复现链接

无

### Config / 配置

无

### Logs / 日志

```
getting src object

open F:\alist\data\temp\file-409226004: The system cannot find the path specified.
```

**Comment by Deepsea-CN** [comment]
这不是bug，是专门设计的，详见文档，为了避免出现问题，alist默认在重启时自动清空temp和beleve文件夹，请勿在此存放持久化数据

**Comment by JoeNik** [comment]
但现在重启后，如果没有手动创建tmp目录，直接去复制文件，就会报这个错误

```
getting src object

open F:\alist\data\temp\file-409226004: The system cannot find the path specified.
```

**Comment by Deepsea-CN** [comment]
> 但现在重启后，如果没有手动创建tmp目录，直接去复制文件，就会报这个错误，早期的版本没有这个问题呀
> 
> ```
> getting src object
> 
> open F:\alist\data\temp\file-409226004: The system cannot find the path specified.
> ```

这个确实是个问题，前面我理解的不对，我在复制文件是也遇到过这个问题，使用的是Linux版本，症状就是不能正确生成中转文件导致不能复制，正常情况重启应该只会清掉temp下的内容，但是现在整个/data/temp文件夹都丢失了，你应该把这段报错放到问题描述里，让开发者能看到

**Comment by JoeNik** [comment]
嗯 ，我贴到描述里面了

**Comment by AsenHu** [comment]
同样的问题发生在 https://github.com/alist-org/alist/commit/d4e3355f5692a690a8aa02298b0052e4340a3e55 [linux-musl-amd64](https://github.com/alist-org/alist/releases/download/beta/alist-linux-musl-amd64.tar.gz)

**Comment by HADB** [comment]
同样遇到这个问题

**Comment by HADB** [comment]
对比了下 v3.35.0 和 v3.36.0 的 diff，感觉问题可能出在这个 [commit](https://github.com/alist-org/alist/pull/6925/commits/9770a5c92df57b96686896ff082556f5b8999a23)，新增了一个 CleanTempDir 方法，会删除整个 temp 文件夹。

**Comment by itsHenry35** [comment]
应该已经在这个commit中被修复：https://github.com/alist-org/alist/commit/c9fa3d7cd60796bc30df45ef8a6b52edab1b1313

**Comment by JoeNik** [comment]
> 应该已经在这个commit中被修复：[c9fa3d7](https://github.com/alist-org/alist/commit/c9fa3d7cd60796bc30df45ef8a6b52edab1b1313)

嗯嗯，确实修复了已经
