### ISSUE TITLE
最新beta版本前端文件配置了cdn会导致前端无法渲染

### ISSUE THREAD

**Issue by lm379** [alist-org/alist#7069]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

AList Beta Version

### Driver used / 使用的存储驱动

任何

### Describe the bug / 问题描述

使用最新的[AList Beta Version](https://github.com/alist-org/alist/releases/tag/beta)，在config.json中的cdn字段配置了npm镜像[https://registry.npmmirror.com/alist-web/$version/files/dist/](https://registry.npmmirror.com/alist-web/$version/files/dist/)，疑似因为version字段获取失败导致前端一片空白
![](https://pic.lm379.gq/2024/08/f6bc23a72a3d92b22639eb07cdbfb353.png)
删除cdn字段或手动指定verison字段即恢复正常

### Reproduction / 复现链接

http://127.0.0.1:5244/

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "https://registry.npmmirror.com/alist-web/$version/files/dist/",
  "jwt_secret": "X8ADb6ZSDnJfBbeM",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },

**Comment by xhofe** [comment]
beta版本不提供cdn，仅稳定版提供
