### ISSUE TITLE
挂 pikpak 云盘 重启提示 无效令牌

### ISSUE THREAD

**Issue by fgr178707** [alist-org/alist#7092]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

dev-217c319 Actions-#3283

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

 挂 pikpak 云盘 重启提示 oauth2: "invalid_grant" "invalid refresh token for it may be has been refreshed by other process, more info redis: nil, RefreshToken

令牌不能自动刷新吗?

每次都得进入 手动删除刷新令牌才可以

### Reproduction / 复现链接

无

### Config / 配置

无

### Logs / 日志

oauth2: "invalid_grant" "invalid refresh token for it may be has been refreshed by other process, more info redis: nil, RefreshToken

**Comment by fgr178707** [comment]
> android


Refresh Token 获取方式 邮箱+密码

platform 选的是 android  

版本 [#3283](https://github.com/alist-org/alist/actions/runs/10547589191)

**Comment by Three-taile-dragon** [comment]
> > android
> 
> 
> Refresh Token 获取方式 邮箱+密码
> 
> platform 选的是 android  
> 
> 版本 [#3283](https://github.com/alist-org/alist/actions/runs/10547589191)
> 

试过最新的 beta版本了吗？

**Comment by fgr178707** [comment]
> > > android
> > 
> > 
> > Refresh Token 获取方式 邮箱+密码
> > platform 选的是 android
> > 版本 [#3283](https://github.com/alist-org/alist/actions/runs/10547589191)
> 
> 试过最新的 beta版本了吗？

试过了

**Comment by hhsw2015** [comment]
加个自动刷新不就行了  判断一下令牌是不是失效

**Comment by 1015156857** [comment]
> 什么方式获取的 Refresh Token，platform 选的是 android 还是 web。 有试过最新的 beta 版本吗？

我用的web端，从网页f12里面提取的令牌，为什么过几个小时令牌就会失效呢

**Comment by a131656** [comment]
> > 用什么方式获取刷新令牌，平台选择是android还是web。有试过最新的beta版本吗？
> 
> 我用的web端，从网页f12里面提取出令牌，为什么过了几个小时令牌就会失效呢

我也这样，就5个小时左右就失效了，看了下pikpak网页端也推出登录了，不知道是不是网页端的问题。

**Comment by wangjunkai2022** [comment]
大哥 我这边写了个api 可以传入一个 验证时收到的url地址 你那边可以改为需要滑块验证时请求我的api url 在需要验证时get请求 调用我的api api会直接返回  json数据 数据内容为
{
            'url_received': url, #这里是传给api的url
            'token':"', # 这里是经过验证的api 
            "code": 200, #状态200 表示成功 -1表示失败
        }
get请求需要穿入的内容是：域名/api/login?url=这里写pikpak验证地址
把这个 域名/api/login 填写到存储模块

**Comment by wangjunkai2022** [comment]
我对 go语言不熟悉 请大佬看看 #7106

**Comment by Three-taile-dragon** [comment]
> > > > android
> > > 
> > > 
> > > Refresh Token 获取方式 邮箱+密码
> > > platform 选的是 android
> > > 版本 [#3283](https://github.com/alist-org/alist/actions/runs/10547589191)
> > 
> > 
> > 试过最新的 beta版本了吗？
> 
> 试过了

#7117 试试

**Comment by fgr178707** [comment]
> > > > > android
> > > > 
> > > > 
> > > > Refresh Token 获取方式 邮箱+密码
> > > > platform 选的是 android
> > > > 版本 [#3283](https://github.com/alist-org/alist/actions/runs/10547589191)
> > > 
> > > 
> > > 试过最新的 beta版本了吗？
> > 
> > 
> > 试过了
> 
> #7117 试试

可以 https://github.com/alist-org/alist/actions/runs/10644783202

**Comment by Andreerassel** [comment]
> > > > > android
> > > > 
> > > > 
> > > > Refresh Token 获取方式 邮箱+密码
> > > > platform 选的是 android
> > > > 版本 [#3283](https://github.com/alist-org/alist/actions/runs/10547589191)
> > > 
> > > 
> > > 试过最新的 beta版本了吗？
> > 
> > 
> > 试过了
> 
> #7117 试试

您好，这个问题如何解决？我依然存在此问题
![1d53c171256d2dc4cbd99849cd151651_720](https://github.com/user-attachments/assets/43099dc5-e7fc-419e-abc1-4eae1a32b054)
