### ISSUE TITLE
PikPak - Request failed with status code 500 Error

### ISSUE THREAD

**Issue by oyudaniel** [alist-org/alist#7118]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

AList Beta, v3.36.0

### Driver used / 使用的存储驱动

PikPak

### Describe the bug / 问题描述

PikPak Request failed with status code 500 error

Connect PikPak to Alist, Error message 'Request failed with status code 500'
(Windows10, AList Beta Version, v3.36.0)

How can solve this problem?

![PikPak-code 500 error](https://github.com/user-attachments/assets/a9e15531-2c15-4d7f-b8f7-edaf75c18c5b)

### Reproduction / 复现链接

https://github.com/alist-org/alist/releases

### Config / 配置

![PikPak-code 500 error 02](https://github.com/user-attachments/assets/16ce2803-a29f-4760-9fc8-eba4100abb51)

**Comment by Three-taile-dragon** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
>   我已经阅读了[文档](https://alist.nn.ci)。
> * [x]  I'm sure there are no duplicate issues or discussions.
>   我确定没有重复的issue或讨论。
> * [x]  I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
>   我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。
> * [x]  I'm sure this issue is not fixed in the latest version.
>   我确定这个问题在最新版本中没有被修复。
> 
> ### AList Version / AList 版本
> AList Beta, v3.36.0
> 
> ### Driver used / 使用的存储驱动
> PikPak
> 
> ### Describe the bug / 问题描述
> PikPak Request failed with status code 500 error
> 
> Connect PikPak to Alist, Error message 'Request failed with status code 500' (Windows10, AList Beta Version, v3.36.0)
> 
> How can solve this problem?
> 
> ![PikPak-code 500 error](https://private-user-images.githubusercontent.com/180050680/363439022-a9e15531-2c15-4d7f-b8f7-edaf75c18c5b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNTY0NjksIm5iZiI6MTcyNTE1NjE2OSwicGF0aCI6Ii8xODAwNTA2ODAvMzYzNDM5MDIyLWE5ZTE1NTMxLTJjMTUtNGQ3Zi1iOGY3LWVkYWY3NWMxOGM1Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwMjAyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTljNTg1OTFkZGY0ZjgzYjExOTZiNThiNzZkYTMyOGI4ZGI1YWFiZmRiNTUyNjA2MDJkZDk0N2E5OTJmNjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uwQmuK4m6InA9gu0isjFu1lgIaf0rRnacLBe_VG7qi0)
> 
> ### Reproduction / 复现链接
> https://github.com/alist-org/alist/releases
> 
> ### Config / 配置
> ![PikPak-code 500 error 02](https://private-user-images.githubusercontent.com/180050680/363439327-16ce2803-a29f-4760-9fc8-eba4100abb51.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNTY0NjksIm5iZiI6MTcyNTE1NjE2OSwicGF0aCI6Ii8xODAwNTA2ODAvMzYzNDM5MzI3LTE2Y2UyODAzLWEyOWYtNDc2MC05ZmM4LWViYTQxMDBhYmI1MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwMjAyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWE3NmVhMTVhMDE3OGFkNjA4YzhmMmFiNzc2MzY0OGZmMDUwZTI4Yjg0NGRmYmZhY2U0NDhlYTE1M2RmNmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PEykzHG80sOnWl9OwDc0nh1zfQgSH7--WPnzmrAd7ck)
> 
> ### Logs / 日志
> _No response_

The error in the picture is due to the official risk control verification. It is now recommended to use a third-party account to log in to the official website and obtain `refresh_token`

---

Please use the version built by Github Actions: https://github.com/alist-org/alist/actions/runs/10644783202?pr=7117
For configuration items, refer to #7024 and #7117

**Comment by oyudaniel** [comment]
to use a third-party account to log in to the official website <...  Does that mean pikpak premium?

**Comment by Three-taile-dragon** [comment]
> to use a third-party account to log in to the official website <... Does that mean pikpak premium?

no. you just need to tie your third-party account, such as Google or Facebook

**Comment by oyudaniel** [comment]
I don't know the details, but I'll try it, thank you

**Comment by oyudaniel** [comment]
to use a third-party account to log in to the official website <.. Is there a link where I can learn how to connect?

**Comment by Three-taile-dragon** [comment]
> to use a third-party account to log in to the official website <.. Is there a link where I can learn how to connect?

https://github.com/alist-org/alist/pull/7024

**Comment by oyudaniel** [comment]
I'm  log in PikPak use google account (third-party set it up) but Alist error 
![pikpak - Error02](https://github.com/user-attachments/assets/79c50cef-5168-41ff-9f5e-5add77d01f5b)

**Comment by Three-taile-dragon** [comment]
> Refresh token - Where can I find it ? 
> ![pikpak - Refresh token](https://github.com/user-attachments/assets/56972646-1322-4fd8-891b-a1151b45d109)
> 

Open the console in the browser and get it from it. For specific steps, please see #7024
