### ISSUE TITLE
小白使用遇到的问题，求解决

### ISSUE THREAD

**Issue by sunn1ngs** [alist-org/alist#7129]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

版本3.86.00

### Driver used / 使用的存储驱动

百度网盘

### Describe the bug / 问题描述

挂载百度网盘后，点击任意文件出现failed link: failed get link: json: cannot unmarshal number into Go struct field DownloadResp.request_id of type string代码

### Reproduction / 复现链接

![屏幕截图 2024-09-05 170454](https://github.com/user-attachments/assets/053e6524-d4e9-464f-b16f-e06a05b47d57)

### Config / 配置

![屏幕截图 2024-09-05 170621](https://github.com/user-attachments/assets/bcf5f9b8-0060-40e7-938f-4ad5c2301e6b)
![屏幕截图 2024-09-05 170641](https://github.com/user-attachments/assets/f46450e3-bce1-4ce9-b9a9-24e9cdca2e79)

**Comment by sunn1ngs** [comment]
alist版本是3.36.0.不好意思

**Comment by sunn1ngs** [comment]
不好意识，在讨论里看到了解决方法。感谢

**Comment by a214955582** [comment]
> 不好意识，在讨论里看到了解决方法。感谢
> 

请问方法是什么呢，我是百度网盘svip，选择302重定向下载不了也在线观看不了，需要把302和web代理一起勾上才行

**Comment by sunn1ngs** [comment]
你可以试试重新登陆百度网盘，我当时在讨论区看到了这个方法，就尝试试了一下，重新登陆之后，网盘会提示你修改密码。改完密码之后就可以了


发件人: a214955582 ***@***.***>
发送时间: 2024年12月11日 18:27
收件人: AlistGo/alist ***@***.***>
抄送: sunn1ngs ***@***.***>; State change ***@***.***>
主题: Re: [AlistGo/alist] 小白使用遇到的问题，求解决 (Issue #7129)


不好意识，在讨论里看到了解决方法。感谢

请问方法是什么呢，我是百度网盘svip，选择302重定向下载不了也在线观看不了，需要把302和web代理一起勾上才行
