### ISSUE TITLE
本地代理和nginx反向代理冲突

### ISSUE THREAD

**Issue by mcmy** [alist-org/alist#7131]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

baidu

### Describe the bug / 问题描述

如果网站架设到本地，通过nginx反向代理到127.0.0.1:5244时，下载代理设置为空点击下载会跳转到127.0.0.1:443/p/xxxxx，把下载连接的127.0.0.1:443改为代理后的域名能正常下载，如果设置为代理后的地址，比如http://pan.nfcat.com 或者 http://pan.nfcat.com/p 时会无限重定向

**已测试不开启反向代理能正确读取域名
后台设置加一个设置本站域名应该能解决此问题**，参考cloudreve或者gitea，在访问时判断获取的域名和前端域名是否相同

![image](https://github.com/user-attachments/assets/21669caf-fb04-4036-ac28-97d3bbfdbef1)

### Reproduction / 复现链接

http://pan.nfcat.com

### Config / 配置

![image](https://github.com/user-attachments/assets/0af63b13-e9c9-439a-9e36-a544dd30df0f)
![image](https://github.com/user-attachments/assets/843b01f6-a304-4f3c-9b1f-6b1fe63477c0)

**Comment by Suiyi-Light** [comment]
https://alist.nn.ci/zh/config/configuration.html#site_url
设置下site_url试试

**Comment by mcmy** [comment]
> https://alist.nn.ci/zh/config/configuration.html#site-url 设置下site_url试试

解决了，设置里面没有，忘了这还有个配置文件
