### ISSUE TITLE
一刻相册崩溃了

### ISSUE THREAD

**Issue by zzy-ac** [alist-org/alist#7133]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

一刻相册

### Describe the bug / 问题描述

failed link: failed get link: errno: 9019, refer to https://photo.baidu.com/union/doc

### Reproduction / 复现链接

任何一刻都这样随时可以复现

### Config / 配置

无

**Comment by zzy-ac** [comment]
> ### See
> 1. 56% [一刻相册没反应 #3277](https://github.com/alist-org/alist/issues/3277)
> 2. 50% [一刻相册无法下载 #4666](https://github.com/alist-org/alist/issues/4666)

不是这俩问题，切换了多个账号都一样的报错，配置也没问题，前几天都好的，没去动过

**Comment by RoxasLong** [comment]
是刚出现的问题，这样的话，群会的套件也需要等待更新才行吗？

**Comment by RoxasLong** [comment]
目前是3.37.1 任然是9019错误

**Comment by sunyuan789** [comment]
一刻相册挂载需要的Cookie怎么获得呢，感觉和之前的挂载方式不一样了
