### ISSUE TITLE
更新最新版本 网页打不开

### ISSUE THREAD

**Issue by gkl1368** [alist-org/alist#7143]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

最新Docker

### Driver used / 使用的存储驱动

无

### Describe the bug / 问题描述

更新了最新版 网页打开报错

### Reproduction / 复现链接

<img width="670" alt="image" src="https://github.com/user-attachments/assets/b079b729-72cd-4c6e-a83f-b68e70910c2e">

### Config / 配置

无

**Comment by simear2004** [comment]
与楼主发生同样的问题
在 UNRAID 上更新 Alist Docker 最新版本后，打开就提示这个错误
![QQ20240908-132210](https://github.com/user-attachments/assets/234f813a-61d6-46e5-adf0-945e6a9d56da)

**Comment by WXZhao7** [comment]
debian12测试同样的错误，手动编译也是的

**Comment by qqq-qqqq** [comment]
Windows版本也能复现

![image](https://github.com/user-attachments/assets/2340f95d-b674-4068-995a-4b7b68e908e1)

**Comment by Moeweb647252** [comment]
脚本安装后访问直接出这个错，无其他操作

**Comment by Three-taile-dragon** [comment]
应该是 https://github.com/alist-org/alist-web 那边的问题，用之前的前端版本编译后正常

**Comment by venuses** [comment]
同样的问题
![image](https://github.com/user-attachments/assets/f40d00fa-6478-4f10-86e9-56dc2e11b72a)

**Comment by GZTimeWalker** [comment]
同样的问题，根据报错信息，应该是如下代码的编译产物产生了问题

https://github.com/alist-org/alist-web/blob/8595bf3d791bea10e9114f2d0d058a2955c5e27e/src/pages/login/CornerBottom.tsx#L10-L20

**Comment by kennysoul** [comment]
同样的问题，使用一键脚本更新后就不能登录页面，客户端就能正常使用

**Comment by mufeng510** [comment]
docker  ARM64同样的问题

**Comment by night-rainy** [comment]
![image](https://github.com/user-attachments/assets/5f6ce2b8-cfec-477a-b470-8b7319b51d3b)

**Comment by night-rainy** [comment]
一样的问题

**Comment by SingingDalong** [comment]
Me too...

**Comment by fgr178707** [comment]
https://github.com/alist-org/alist-web/releases/download/3.36.0/dist.zip

下载这个 修改 配置文件里dist_dir
改成你这个文件解压到哪里就改到哪里 需要把路径里的 \->\\修改成双\\

**Comment by xingpingcn** [comment]
一样的问题

**Comment by meishiffx** [comment]
AList Desktop一样（

**Comment by SHutdog** [comment]
群辉套件版一样

**Comment by likevi9528** [comment]
+1. System error: TypeError: Mr is not a function

**Comment by chinndesu** [comment]
群晖套件+1，更新后出现System error: TypeError: Mr is not a function

**Comment by fgr178707** [comment]
https://github.com/alist-org/alist/releases/tag/v3.37.1

**Comment by SHutdog** [comment]
群辉套件版我的提示是System error: TypeError: Re is not a function

**Comment by suyang320** [comment]
群晖套件目前也打不开了，还是V3.37.0版本

**Comment by he-sb** [comment]
v3.37.1 版本可以正常使用了

**Comment by xhofe** [comment]
fixed in https://github.com/alist-org/alist/releases/tag/v3.37.1
