### ISSUE TITLE
[PikPak] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Muione** [alist-org/alist#7149]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.1

### Driver used / 使用的存储驱动

PikPak

### Describe the bug / 问题描述

更新 `alist` 到最新版本之后，打开 `UseLowLatencyAddress` 选择项 `CustomLowLatencyAddress` 字段留空，重启 `alist` 之后出现报错，并且无法启动：
```
panic: runtime error: invalid memory address or nil pointer dereference
```
并且无法启动 `alist`。

### Reproduction / 复现链接

这个 *BUG* 触发需要前置条件，触发的流程如下：
- 更新主程序后， PikPak 存储提示 `refresh_token` 被其他程序刷新：
  ```
  oauth2: "invalid_grant" "refresh token os.0ueD_vBzW2bdYp8Ixvbj3AicurBTUUtb4zUPJzrWreVgwxncE0V55LGU has been refresh at 2024-09-08T16:38:56+08:00"
  ```
- 将 `refresh_token` 和 `capatch_token` 字段（填写了用户名和密码字段）清除然后保存，这时报错:
  ```
  ailed init storage: oauth2: "invalid_grant" "refresh token os.0ueD_vBzW2bdYp8Ixvbj3AicurBTUUtb4zUPJzrWreVgwxncE0V55LGU has been refresh at 2024-09-08T16:38:56+08:00"
  ```
- 打开 `UseLowLatencyAddress` 选择项 `CustomLowLatencyAddress` 字段留空，并保存（这一步应该无关紧要）
- 禁用 PikPak 存储，再启用，这时提示 `request error 500`，实际上存储并未正常启用，这时只有禁用按钮
![image](https://github.com/user-attachments/assets/d98c3e19-cd3e-4e80-9bb6-f37b0d20cc1d)
- 这时添加的 PikPak 完全不可用，重启 `alist` 主程序，可以复现这一*BUG*，日志可见下方内容
- 这一*BUG*出现后，`alist` 将无法正常启动

### Config / 配置

- 平台：网页
- 刷新令牌方法： Oauth2

### Logs / 日志

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16aa22c]

goroutine 166 [running]:
github.com/alist-org/alist/v3/drivers/pikpak.(*PikPak).request(0x4000e6dc00, {0x247bf81, 0x30}, {0x23f4fb7, 0x4}, 0x40000537f0, {0x1dae100, 0x4000e3e2d0})
        /source/drivers/pikpak/util.go:234 +0x3ac
github.com/alist-org/alist/v3/drivers/pikpak.(*PikPak).refreshCaptchaToken(0x4000e6dc00, {0x4000e0e318?, 0x23f7429?}, 0x5?)
        /source/drivers/pikpak/util.go:466 +0x140
github.com/alist-org/alist/v3/drivers/pikpak.(*PikPak).RefreshCaptchaTokenInLogin(0x4000e6dc00, {0x4000e0e318, 0x14}, {0x4000c9a450, 0x23})
        /source/drivers/pikpak/util.go:440 +0x16c
github.com/alist-org/alist/v3/drivers/pikpak.(*PikPak).login(0x4000e6dc00)
        /source/drivers/pikpak/util.go:140 +0x68
github.com/alist-org/alist/v3/drivers/pikpak.(*PikPak).Init(0x4000e6dc00, {0x3853730, 0x4d5a4a0})
        /source/drivers/pikpak/driver.go:117 +0x93c
github.com/alist-org/alist/v3/internal/op.initStorage({0x3853730, _}, {0x14, {0x40007f9920, 0x7}, 0x0, {0x40007f9930, 0x6}, 0x1e, {0x40007f9940, ...}, ...}, ...)
        /source/internal/op/storage.go:94 +0xe4
github.com/alist-org/alist/v3/internal/op.LoadStorage({0x3853730, _}, {0x14, {0x40007f9920, 0x7}, 0x0, {0x40007f9930, 0x6}, 0x1e, {0x40007f9940, ...}, ...})
        /source/internal/op/storage.go:80 +0x10c
github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1({0x4000928608, 0xd, 0x4000bdf300?})
        /source/internal/bootstrap/storage.go:20 +0xb4
created by github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages in goroutine 1
        /source/internal/bootstrap/storage.go:18 +0xc0
```

**Comment by Three-taile-dragon** [comment]
所以是 用户名和密码以及 refresh_token 都没填写的情况下，保存->禁用->启用->重启Alist ？
ORZ，没想到还有这操作🤡

**Comment by Muione** [comment]
> 所以是 用户名和密码以及 refresh_token 都没填写的情况下，保存->禁用->启用->重启Alist ？ ORZ，没想到还有这操作🤡

不是，其他都保留着。
因为refresh_token失效了，本来想将refresh_token 和 capatch_token 字段清除后使用用户名、密码重新登陆获取refresh_token，就进行了上述步骤，出现的这个BUG，我这边可以100%复现

**Comment by Three-taile-dragon** [comment]
> > 所以是 用户名和密码以及 refresh_token 都没填写的情况下，保存->禁用->启用->重启Alist ？ ORZ，没想到还有这操作🤡
> 
> 不是，其他都保留着。 因为refresh_token失效了，本来想将refresh_token 和 capatch_token 字段清除后使用用户名、密码重新登陆获取refresh_token，就进行了上述步骤，出现的这个BUG，我这边可以100%复现

就是说，用户名和密码都有填写，只是清空了 refreshtoken字段 后进行的操作？

**Comment by Muione** [comment]
> 就是说，用户名和密码都有填写，只是清空了 refreshtoken字段 后进行的操作？

是的

**Comment by Three-taile-dragon** [comment]
#7150 试试这版有修复不

**Comment by Muione** [comment]
> #7150 试试这版有修复不

这个版本没问题；
清除 refresh_token 和 capatch_token 字段后，保存，然后禁用再启用磁盘，能正常进行登陆并挂载。
