### ISSUE TITLE
使用api上传文件，对象存储中秒加载，但是界面加载时间不确定，时快时慢

### ISSUE THREAD

**Issue by mark8s** [alist-org/alist#7161]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36   docker 部署

### Driver used / 使用的存储驱动

minio

### Describe the bug / 问题描述

是这样，我使用api 去对接的alist 以存储图片，接口是：PUT /api/fs/form，我发现个问题。我curl api上传后，我的minio基本上上实时上传了图片，但是我的alist主页需要加载几分钟才能看到，这是什么原因？

主页：
![image](https://github.com/user-attachments/assets/d167c639-f684-4d76-88e5-bff1ff4cbf78)

minio:
![image](https://github.com/user-attachments/assets/7ffdd3ea-c9bd-458f-b43b-3ade19f0dd88)

### Reproduction / 复现链接

无

### Config / 配置

.......

### Logs / 日志

无

**Comment by yyxytop** [comment]
这个不太清楚，我用halo博客的插件上传没有啥问题，你这个我没用过，是不是你源站的问题，

**Comment by ThinkerWen** [comment]
右下角三个点点开有强制刷新，或者`/api/fs/list` `refresh: "true"`

**Comment by Simonzhang8** [comment]
修改一下Alist这边的缓存过期时间看看？（比如调整为0）
![image](https://github.com/user-attachments/assets/bd68cfbc-6e1f-4224-9e36-5e2fe4ed6d0c)
