### ISSUE TITLE
为啥文件上传路径和实际访问直链地址不一致？直链地址需要加/d、/p前缀

### ISSUE THREAD

**Issue by mark8s** [alist-org/alist#7166]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

minio

### Describe the bug / 问题描述

我有些困惑，就是为啥文件上传的路径和实际访问的地址不一致，实际访问的prefix path多/d或者/p。

比如我上传一个文件到一个路径如：`/minio/bug/f3500a0d-56e0-4dcc-ab0d-534895bd10c0.jpg`

我关掉了sign，我想直链访问。我理想的访问路径就是 `/minio/bug/f3500a0d-56e0-4dcc-ab0d-534895bd10c0.jpg`，也就是说只要我用 alist服务地址+ `/minio/bug/f3500a0d-56e0-4dcc-ab0d-534895bd10c0.jpg`，我就应该能直接访问到我的图片才对。但是实际中，我需要用 alist服务地址+ **/d** +`/minio/bug/f3500a0d-56e0-4dcc-ab0d-534895bd10c0.jpg` 才能访问。这是为啥？

前端的实现貌似如下：
<img width="377" alt="1726041750547_63D7DEE1-D4D9-43f5-BD49-449A7B3DAB30" src="https://github.com/user-attachments/assets/b8e896e7-ad4d-4b14-8924-6437111d68f6">

为什么需要这么做呢？整个实现的原理是咋样的啊？有没有人知道？

### Reproduction / 复现链接

xx

### Config / 配置

xx

**Comment by Simonzhang8** [comment]
你不加/d相当于访问Alist的前端页面
比如https://al.nn.ci/alist.png 访问的就是Alist页面，并在页面中预览相应路径的图片
![image](https://github.com/user-attachments/assets/49ec3d02-b560-4fbe-84e0-c1f10cd7066c)
而https://al.nn.ci/d/alist.png 才是直接打开的图片文件（当然本案例中需要加sign）
![image](https://github.com/user-attachments/assets/a45f9fd2-dca0-4074-90b3-23ff1bf4d79b)

**Comment by yyxytop** [comment]
> 你不加/d相当于访问Alist的前端页面 比如https://al.nn.ci/alist.png 访问的就是Alist页面，并在页面中预览相应路径的图片 ![image](https://private-user-images.githubusercontent.com/165749751/366390302-49ec3d02-b560-4fbe-84e0-c1f10cd7066c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDgzNTksIm5iZiI6MTcyNjA0ODA1OSwicGF0aCI6Ii8xNjU3NDk3NTEvMzY2MzkwMzAyLTQ5ZWMzZDAyLWI1NjAtNGZiZS04NGUwLWMxZjEwY2Q3MDY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwOTQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmY0NmI2ZjdlMWU0NTU3OGIwMGM2MWNiNGIxMmUwOTE3OWE0NDNhYjUyNTZhMmQ2MTNlMWYyMTAwNjI2NDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ER2_97H8nGVIBUd7usEfVDX4_QyFuMI7MTS6l0TM_9Q) 而https://al.nn.ci/d/alist.png 才是直接打开的图片文件（当然本案例中需要加sign） ![image](https://private-user-images.githubusercontent.com/165749751/366390442-a45f9fd2-dca0-4074-90b3-23ff1bf4d79b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDgzNTksIm5iZiI6MTcyNjA0ODA1OSwicGF0aCI6Ii8xNjU3NDk3NTEvMzY2MzkwNDQyLWE0NWY5ZmQyLWRjYTAtNDA3NC05MGIzLTIzZmYxYmY0ZDc5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwOTQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTNjMThhODJmYzczMmYwNjYyNjYzNGMyMDU0ODczYmQ5M2RjOTcwZmRmNzY5NWI4YjBhMjJhNGYxZTI4OTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gEflQBO-mHCSlF_wVf79YEePYNRZolc6Qf9gbAXC7AI)

你这是怎么做到的，我的加了d直接就下载了 你这是预览

**Comment by Simonzhang8** [comment]
> @Simonzhang8 你这是怎么做到的，我的加了d直接就下载了 你这是预览



> @Simonzhang8 你这是怎么做到的，我的加了d直接就下载了 你这是预览

这个取决于原链接的设置，原链接预览就是预览，原链接直接下载就是下载，我也不太清楚怎么调整这个😂

**Comment by ThinkerWen** [comment]
> @Simonzhang8 你这是怎么做到的，我的加了d直接就下载了 你这是预览

响应体有content-disposition: attachment，会直接下载图片，他这个好像调用系统的图片查看器展示图片，如果设置成content-disposition: inline就可以在浏览器页面内嵌展示了

**Comment by Simonzhang8** [comment]
> 响应体有content-disposition: attachment，会直接下载图片，他这个好像调用系统的图片查看器展示图片，如果设置成content-disposition: inline就可以在浏览器页面内嵌展示了

应该是这样，那就需要直接修改响应体了，Alist这边默认就是保留源链接的响应体，原本是attachment就下载，原本是inline就内嵌

**Comment by yyxytop** [comment]
> > 响应体有content-disposition: attachment，会直接下载图片，他这个好像调用系统的图片查看器展示图片，如果设置成content-disposition: inline就可以在浏览器页面内嵌展示了
> 
> 应该是这样，那就需要直接修改响应体了，Alist这边默认就是保留源链接的响应体，原本是attachment就下载，原本是inline就内嵌

好的想到了，可以预览的好像叫流媒体？是流不是文件？，一般对象存储可以预览好像就是这样，alist的可以直接在文章中引用展示图片，但是点开链接就是下载，对象存储就不是。哈哈 没啥问题了，影响不大 @Simonzhang8
