### ISSUE TITLE
夸克TV报错，授权二维码过期

### ISSUE THREAD

**Issue by icexk** [alist-org/alist#7167]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.1

### Driver used / 使用的存储驱动

QuarkTV

### Describe the bug / 问题描述

APP扫码后，点禁用，然后点启用报授权二维码过期

### Reproduction / 复现链接

部署在内网，无法提供

### Config / 配置

<img width="431" alt="image" src="https://github.com/user-attachments/assets/caf2464b-f6f0-4f60-9165-2a17d854fe7c">
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "QnYAzqTbqhS6Zooe",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": false,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1,
      "task_persistant": true
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    },
    "upload": {
      "workers": 5,
      "max_retry": 0,
      "task_persistant": false
    },
    "copy": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

### Logs / 日志

2024/09/11 10:02:44.450632 WARN RESTY Get "https://open-api-drive.quark.cn/oauth/authorize?access_token=&activity_rect=%7B%7D&app_ver=1.5.6&auth_type=code&build_device=M2004J7AC&build_product=M2004J7AC&channel=CP&client_id=d3194e61504e493eb6222857bccfed94&device_brand=Xiaomi&device_gpu=Adreno+%28TM%29+550&device_id=915906e145338b1c1ce1c52e2e6c692a&device_model=M2004J7AC&device_name=M2004J7AC&platform=tv&qr_height=460&qr_width=460&qrcode=1&req_id=24d04fac594adf8b7acfbc4003f29c5a&scope=netdisk": context deadline exceeded, Attempt 1
2024/09/11 10:02:44.450692 ERROR RESTY Get "https://open-api-drive.quark.cn/oauth/authorize?access_token=&activity_rect=%7B%7D&app_ver=1.5.6&auth_type=code&build_device=M2004J7AC&build_product=M2004J7AC&channel=CP&client_id=d3194e61504e493eb6222857bccfed94&device_brand=Xiaomi&device_gpu=Adreno+%28TM%29+550&device_id=915906e145338b1c1ce1c52e2e6c692a&device_model=M2004J7AC&device_name=M2004J7AC&platform=tv&qr_height=460&qr_width=460&qrcode=1&req_id=24d04fac594adf8b7acfbc4003f29c5a&scope=netdisk": context deadline exceeded
2024/09/11 10:04:46.605740 WARN RESTY Post "http://api.extscreen.com/quarkdrive/token": context deadline exceeded, Attempt 1
2024/09/11 10:04:46.605809 ERROR RESTY Post "http://api.extscreen.com/quarkdrive/token": context deadline exceeded
2024/09/11 10:07:02.252550 WARN RESTY Get "https://open-api-drive.quark.cn/oauth/authorize?access_token=&activity_rect=%7B%7D&app_ver=1.5.6&auth_type=code&build_device=M2004J7AC&build_product=M2004J7AC&channel=CP&client_id=d3194e61504e493eb6222857bccfed94&device_brand=Xiaomi&device_gpu=Adreno+%28TM%29+550&device_id=12b1c0175837cc5ddcfb619069766f36&device_model=M2004J7AC&device_name=M2004J7AC&platform=tv&qr_height=460&qr_width=460&qrcode=1&req_id=f4ac5c4d62fbcd4571b84f4e117cda59&scope=netdisk": context deadline exceeded, Attempt 1
2024/09/11 10:07:02.252628 ERROR RESTY Get "https://open-api-drive.quark.cn/oauth/authorize?access_token=&activity_rect=%7B%7D&app_ver=1.5.6&auth_type=code&build_device=M2004J7AC&build_product=M2004J7AC&channel=CP&client_id=d3194e61504e493eb6222857bccfed94&device_brand=Xiaomi&device_gpu=Adreno+%28TM%29+550&device_id=12b1c0175837cc5ddcfb619069766f36&device_model=M2004J7AC&device_name=M2004J7AC&platform=tv&qr_height=460&qr_width=460&qrcode=1&req_id=f4ac5c4d62fbcd4571b84f4e117cda59&scope=netdisk": context deadline exceeded
2024/09/11 10:08:53.408916 WARN RESTY Get "https://open-api-drive.quark.cn/oauth/authorize?access_token=&activity_rect=%7B%7D&app_ver=1.5.6&auth_type=code&build_device=M2004J7AC&build_product=M2004J7AC&channel=CP&client_id=d3194e61504e493eb6222857bccfed94&device_brand=Xiaomi&device_gpu=Adreno+%28TM%29+550&device_id=32f31aa25c9d5560e76b6d847cab5cab&device_model=M2004J7AC&device_name=M2004J7AC&platform=tv&qr_height=460&qr_width=460&qrcode=1&req_id=da5a10238114f604ff87fa9f8f7e232a&scope=netdisk": context deadline exceeded, Attempt 1
2024/09/11 10:08:53.408964 ERROR RESTY Get "https://open-api-drive.quark.cn/oauth/authorize?access_token=&activity_rect=%7B%7D&app_ver=1.5.6&auth_type=code&build_device=M2004J7AC&build_product=M2004J7AC&channel=CP&client_id=d3194e61504e493eb6222857bccfed94&device_brand=Xiaomi&device_gpu=Adreno+%28TM%29+550&device_id=32f31aa25c9d5560e76b6d847cab5cab&device_model=M2004J7AC&device_name=M2004J7AC&platform=tv&qr_height=460&qr_width=460&qrcode=1&req_id=da5a10238114f604ff87fa9f8f7e232a&scope=netdisk": context deadline exceeded
2024/09/11 10:10:26.508728 WARN RESTY Post "http://api.extscreen.com/quarkdrive/token": context deadline exceeded, Attempt 1
2024/09/11 10:10:26.508841 ERROR RESTY Post "http://api.extscreen.com/quarkdrive/token": context deadline exceeded
2024/09/11 10:12:11.954046 WARN RESTY Post "http://api.extscreen.com/quarkdrive/token": context deadline exceeded, Attempt 1
2024/09/11 10:12:11.954090 ERROR RESTY Post "http://api.extscreen.com/quarkdrive/token": context deadline exceeded

**Comment by icexk** [comment]
我是从3.36.0升级到最新版本的，请看看

**Comment by icexk** [comment]
刷新令牌为空，只有查询令牌

**Comment by Three-taile-dragon** [comment]
> 刷新令牌为空，只有查询令牌

这个报错就是字面意思，二维码过期了，扫码完成后请快速禁用再启用

现在请尝试 删除重新添加该驱动

**Comment by icexk** [comment]
> > 刷新令牌为空，只有查询令牌
> 
> 这个报错就是字面意思，二维码过期了，扫码完成后请快速禁用再启用
> 
> 现在请尝试 删除重新添加该驱动

可以了谢谢，扫码后就是需要快速的点禁用和启用才行

**Comment by windfall4us** [comment]
问一句。添加后保存。不显示二维码是什么原因？显示授权码Code二维码过期

**Comment by Arvin225** [comment]
> 问一句。添加后保存。不显示二维码是什么原因？显示授权码Code二维码过期

是的，按照文档，并不显示登录二维码
