### ISSUE TITLE
3.37.2版本号显示问题

### ISSUE THREAD

**Issue by tbc0309** [alist-org/alist#7182]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.2

### Driver used / 使用的存储驱动

all

### Describe the bug / 问题描述

Docker中版本显示正常
![1726369468621](https://github.com/user-attachments/assets/e872a8f7-2ece-4e2d-9520-06dbcb4aba77)
![1726369540604](https://github.com/user-attachments/assets/1d129dc5-bdea-46ba-a1ff-db0afbbc3845)

直接运行的显示为beta
![1726369502924](https://github.com/user-attachments/assets/ea2a2574-16ff-427d-afd1-098f37ca2e8a)
![1726369567965](https://github.com/user-attachments/assets/f12f783c-fa4b-43b6-84f8-44936f1f868a)

### Reproduction / 复现链接

all

### Config / 配置

all

**Comment by DrENDzZ** [comment]
Same, the version number is marked as beta.

**Comment by pctoolsx** [comment]
<img width="416" alt="截屏2024-09-15 23 16 53" src="https://github.com/user-attachments/assets/97a1d483-1e57-4f62-814b-5eb2e221c1c9">
<img width="266" alt="截屏2024-09-15 23 16 19" src="https://github.com/user-attachments/assets/d6c5078f-1b13-4994-8a50-c0d083078c96">
Same problem

**Comment by Water-Oldbrother** [comment]
版本号又不影响使用，就是alist-helper 点更新会白屏。。。  哈哈

**Comment by zanewayne78** [comment]
alist-helper更新白屏+1，是懒得编译新的吗...
