### ISSUE TITLE
添加的115存储打不开了

### ISSUE THREAD

**Issue by SingleRottenChips** [alist-org/alist#7191]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.2

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

> failed get objs: failed to list objs: <!doctypehtml><html lang="zh-cn"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible"content="IE=edge,chrome=1"><meta name="data-spm"content="a3c0e"><title>405</title><style>a,body,div,h2,html,p{margin:0;padding:0}a{text-decoration:none;color:#3b6ea3}.container{width:1000px;margin:auto;color:#696969}.header{padding:110px 0}.header .message{height:36px;padding-left:120px;background:url(https://errors.aliyun.com/images/TB1TpamHpXXXXaJXXXXeB7nYVXX-104-162.png) no-repeat 0 -128px;line-height:36px}.main{padding:50px 0;background:#f4f5f7}#block_image{position:relative;left:120px}.footer{margin-top:30px;text-align:right}.footer a{padding:8px 30px;border-radius:10px;border:1px solid #4babec}.footer a:hover{opacity:.8}.alert-shadow{display:none;position:absolute;top:0;left:0;width:100%;height:100%;background:#999;opacity:.5}.alert{display:none;position:absolute;top:200px;left:50%;width:600px;margin-left:-300px;padding-bottom:25px;border:1px solid #ddd;box-shadow:0 2px 2px 1px rgba(0,0,0,.1);background:#fff;font-size:14px;color:#696969}.alert h2{margin:0 2px;padding:10px 15px 5px 15px;font-size:14px;font-weight:400;border-bottom:1px solid #ddd}.alert a{display:block;position:absolute;right:10px;top:8px;width:30px;height:20px;text-align:center}.alert p{padding:20px 15px}</style><body data-spm="7663354"><div data-spm="1998410538"><div class="header"><div class="container"><div class="message"><div id="block_message"></div><div><span id="block_url_tips"></span><strong id="url"></strong></div><div><span id="block_time_tips"></span><strong id="time"></strong></div><div><span id="block_traceid_tips"></span><strong id="traceid"></strong></div></div></div></div><div class="main"><div class="container"><img id="block_image"></div></div><div class="footer"><div class="container"><a target="_blank"id="report"href="javascript:;"data-spm-click="gostr=/waf.123.123;locaid=d001;"style="display:none">误报反馈</a></div></div></div><script>function getRenderData(){var e=document.getElementById("renderData");return JSON.parse(e.innerHTML)}function convertTimestampToString(e){e=parseInt(e,10),e=new Date(e);return e.getFullYear()+"-"+("0"+(e.getMonth()+1)).slice(-2)+"-"+("0"+e.getDate()).slice(-2)+" "+("0"+e.getHours()).slice(-2)+":"+("0"+e.getMinutes()).slice(-2)+":"+("0"+e.getSeconds()).slice(-2)}var en_tips={block_message:"Sorry, your request has been blocked as it may cause potential threats to the server's security.",block_url_tips:"Current URL: ",block_time_tips:"Request Time: ",block_traceid_tips:"Your Request ID is: "},cn_tips={block_message:"很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。",block_url_tips:"当前网址: ",block_time_tips:"请求时间: ",block_traceid_tips:"您的请求ID是: "};window.onload=function(){var e=getRenderData();if(e){var t,n=cn_tips,i=document.getElementById("block_image");for(t in"en"===e.lang?(n=en_tips,i.src="https://g.alicdn.com/sd-base/static/1.0.5/image/405.png",i.id="en_block"):(i.src="https://errors.aliyun.com/images/TB15QGaHpXXXXXOaXXXXia39XXX-660-117.png",document.getElementById("report").style.display="inline"),n)document.getElementById(t).innerText=n[t];i=e.traceid,e=i.slice(8,21);document.getElementById("traceid").innerText=i,document.getElementById("url").innerText=location.href.split("?")[0],document.getElementById("time").innerText=convertTimestampToString(e)}}</script><textarea id="renderData" style="display:none">{"traceid":"784e2c8f17264942895828839e0533","lang":"cn"}</textarea>: unexpected error

是已添加很久的存储。应该是今天出现的问题，昨天qnap-alist还能打开的，今天qnap和服务器都打不开。

### Reproduction / 复现链接

添加115存储，更新cookies.

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xxxx",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",                                                                                                                            
    "ssl_mode": "",                                                                                                                                  
    "dsn": ""                                                                                                                                        
  },                                                                                                                                                 
  "meilisearch": {                                                                                                                                   
    "host": "http://localhost:7700/",                                                                                                                 
    "api_key": "",                                                                                                                                   
    "index_prefix": ""                                                                                                                               
  },                                                                                                                                                 
  "scheme": {                                                                                                                                        
    "address": "0.0.0.0",                                                                                                                            
    "http_port": 5244,                                                                                                                               
    "https_port": -1,                                                                                                                                
    "force_https": false,                                                                                                                            
    "cert_file": "",                                                                                                                                 
    "key_file": "",                                                                                                                                  
    "unix_file": "",                                                                                                                                 
    "unix_file_perm": ""                                                                                                                             
  },                                                                                                                                                 
  "temp_dir": "data/temp",                                                                                                                           
  "bleve_dir": "data/bleve",                                                                                                                         
  "dist_dir": "",                                                                                                                                    
  "log": {                                                                                                                                           
    "enable": true,                                                                                                                                  
    "name": "data/log/log.log",                                                                                                                      
    "max_size": 50,                                                                                                                                  
    "max_backups": 30,                                                                                                                               
    "max_age": 28,                                                                                                                                   
    "compress": false                                                                                                                                
  },                                                                                                                                                 
  "delayed_start": 0,                                                                                                                                
  "max_connections": 0,                                                                                                                              
  "tls_insecure_skip_verify": true,                                                                                                                  
  "tasks": {                                                                                                                                         
    "download": {                                                                                                                                    
      "workers": 5,                                                                                                                                  
      "max_retry": 1,                                                                                                                                
      "task_persistant": true                                                                                                                        
    },                                                                                                                                               
    "transfer": {                                                                                                                                    
      "workers": 5,                                                                                                                                  
      "max_retry": 2,                                                                                                                                
      "task_persistant": true                                                                                                                        
    },                                                                                                                                               
    "upload": {                                                                                                                                      
      "workers": 5,                                                                                                                                  
      "max_retry": 0,                                                                                                                                
      "task_persistant": false                                                                                                                       
    },                                                                                                                                               
    "copy": {                                                                                                                                        
      "workers": 3,                                                                                                                                  
      "max_retry": 2,                                                                                                                                
      "task_persistant": true                                                                                                                        
    }                                                                                                                                                
  },                                                                                                                                                 
  "cors": {                                                                                                                                          
    "allow_origins": [                                                                                                                               
      "*"                                                                                                                                            
    ],                                                                                                                                               
    "allow_methods": [                                                                                                                               
      "*"                                                                                                                                            
    ],                                                                                                                                               
    "allow_headers": [                                                                                                                               
      "*"                                                                                                                                            
    ]                                                                                                                                                
  },                                                                                                                                                 
  "s3": {                                                                                                                                            
    "enable": false,                                                                                                                                 
    "port": 5246,                                                                                                                                    
    "ssl": false                                                                                                                                     
  }

**Comment by KNzzzzzzzzzz** [comment]
我也出现这个问题了

**Comment by ulovecode** [comment]
我也出现这个问题了

failed get objs: failed to list objs: invalid character 'a' looking for beginning of value

**Comment by 13760776822** [comment]
115紧急修复攻击后，就没法用令牌或者cookie登陆了

**Comment by duojiaqi123** [comment]
> 我也出现这个问题了
> 
> failed get objs: failed to list objs: invalid character 'a' looking for beginning of value

我也是

**Comment by lenhoo** [comment]
> 我也出现这个问题了
> 
> failed get objs: failed to list objs: invalid character 'a' looking for beginning of value

我也是同样的问题

**Comment by KeithW0726** [comment]
> > 我也出现这个问题了
> > failed get objs: failed to list objs: invalid character 'a' looking for beginning of value
> 
> 我也是

我也是

**Comment by Water-Oldbrother** [comment]
这115也是搞笑，改了代码就不能登了？ 坐等修复，辛苦老大了。

**Comment by luvjojo** [comment]
我也是！打不开了！app正常

**Comment by babylife** [comment]
一样的情况，难道今天的故障有关系？

**Comment by chenqs000** [comment]
> 一样的情况，难道今天的故障有关系？

据说是今天修复问题后，ua禁用了115desktop

**Comment by wao1201** [comment]
看的有说封 UA 了，需要作者适配了

**Comment by likevi9528** [comment]
+1, failed get objs: failed to list objs: invalid character 'a' looking for beginning of value

**Comment by lee1031** [comment]
+1

**Comment by Aiwan520** [comment]
这是今天下午出现的问题，目前115官网已经逐步恢复正常了。但是挂载到alist的无法读取到列表。出现：failed get objs: failed to list objs: invalid character 'a' looking for beginning of value的错误

**Comment by hw8408** [comment]
俺也一样。CD2也是一样的错误。。

**Comment by StYaphet** [comment]
+个 1

**Comment by jjjjjjava** [comment]
同样问题：
![image](https://github.com/user-attachments/assets/7b6a92fa-f9cc-4d4c-a212-d852c59e734e)

**Comment by 999k923** [comment]
> > > 我也出现这个问题了
> > > failed get objs: failed to list objs: invalid character 'a' looking for beginning of value
> > 
> > 
> > 我也是
> 
> 我也是

我也是

**Comment by sunrise1998** [comment]
me too

**Comment by Deepsea-CN** [comment]
同405了。应该是ua被封了，只能等作者适配了

**Comment by U8m2** [comment]
+1

**Comment by FECSky** [comment]
+1

**Comment by antoniosinclair** [comment]
> 这是今天下午出现的问题，目前115官网已经逐步恢复正常了。但是挂载到alist的无法读取到列表。出现：failed get objs: failed to list objs: invalid character 'a' looking for beginning of value的错误

俺也一样

**Comment by jherlock** [comment]
failed get objs: failed to list objs: invalid character 'a' looking for beginning of value的错误的可以试下挂载115分享自己文件的方式挂载，我这边成功挂载了

**Comment by bobokick** [comment]
刚才我也是出现了这个问题，打开115文件夹时提示：failed get objs: failed to list objs: invalid character 'a' looking for beginning of value

**Comment by gitcook** [comment]
坐等作者更新

**Comment by antoniosinclair** [comment]
> failed get objs: failed to list objs: invalid character 'a' looking for beginning of value的错误的可以试下挂载115分享自己文件的方式挂载，我这边成功挂载了

我尝试分享我的文件夹，读取前两层文件夹列表成功，但是读取详细目录（各个影音文件夹）的时候弹出了和发起issues的老哥一样的错误提示。

**Comment by Y-ASLant** [comment]
手动更新完3.37.2里面版本号显示不对，显示为3.37.1 beta
![image](https://github.com/user-attachments/assets/8d7d2500-8112-41f7-a09b-a56c7015c4f9)

**Comment by antoniosinclair** [comment]
> 手动更新完3.37.2里面版本号显示不对，显示为3.37.1 beta ![image](https://private-user-images.githubusercontent.com/77436463/367847845-8d7d2500-8112-41f7-a09b-a56c7015c4f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDU3ODgsIm5iZiI6MTcyNjUwNTQ4OCwicGF0aCI6Ii83NzQzNjQ2My8zNjc4NDc4NDUtOGQ3ZDI1MDAtODExMi00MWY3LWEwOWItYTU2YzcwMTVjNGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE2NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNzQ5OTliMTQ2NWQxZmU1ODc0NTk3MzY1M2M2MWI4NDNkZjYxMDgyNThmMjU3MTkwMDM3NDU4YTE0NDQ2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sBHglU9YemKbXNP6pjlTsuanF8hM50ZIgLcWGrLR2-Y)

版本号显示错误，在另一个issues里

**Comment by jherlock** [comment]
> > failed get objs: failed to list objs: invalid character 'a' looking for beginning of value的错误的可以试下挂载115分享自己文件的方式挂载，我这边成功挂载了
> 
> 
> 
> 我尝试分享我的文件夹，读取前两层文件夹列表成功，但是读取详细目录（各个影音文件夹）的时候弹出了和发起issues的老哥一样的错误提示。

我不会唉，我文件id直接填根目录的，跟分页大小和速率有没有关系？分页大小我填了1500，速率是20。我的层级读取到4层也没事

**Comment by Y-ASLant** [comment]
小幸运2 修复了115无法挂载 这个问题，但是那个alist不知道修改了什么内容。用这个修改版本 一切正常
![image](https://github.com/user-attachments/assets/8c2edca2-7d54-4fd8-89a8-6ac76c5569db)
![image](https://github.com/user-attachments/assets/dbcd7a45-a182-46ca-94b1-b48f64077eb1)

**Comment by antoniosinclair** [comment]
> > > failed get objs: failed to list objs: invalid character 'a' looking for beginning of value的错误的可以试下挂载115分享自己文件的方式挂载，我这边成功挂载了
> > 
> > 
> > 我尝试分享我的文件夹，读取前两层文件夹列表成功，但是读取详细目录（各个影音文件夹）的时候弹出了和发起issues的老哥一样的错误提示。
> 
> 我不会唉，我文件id直接填根目录的，跟分页大小和速率有没有关系？分页大小我填了1500，速率是20。我的层级读取到4层也没事

我还是等一等吧，我要分享的里面有太多违规文件了

**Comment by Logzhan** [comment]
我已经解决了：
<img width="1014" alt="a920d84ae6b7ef761f080d314d408d3" src="https://github.com/user-attachments/assets/566b1299-d7e6-4682-80ea-1288b45eb70b">
在driver/115/util.go下面，按照上面的修改，重新编译。搞定！

**Comment by sln162** [comment]
已经有人提Pull了，等作者更新，Linux也可以自己编译，但是Windows的咋弄，咋编译生成exe有人知道吗？
