### ISSUE TITLE
115网盘挂载成功但无法获取文件列表

### ISSUE THREAD

**Issue by Lost2049** [alist-org/alist#7216]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.37.3

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

之前用Alist挂载115网盘一直顺利使用，电脑环境、账号均无改变。
9.16日发现115网盘登录异常，官方有通知受到服务器攻击，当晚有修复；
再使用Alist挂载115网盘，按指导文档步骤更新获取二维码令牌，加载成功，但进入网盘文件夹时，页面空白反馈： failed get objs: failed to list objs: invalid character 'a' looking for beginning of value
已持续两天未恢复。

### Reproduction / 复现链接

![20240918 172449 21](https://github.com/user-attachments/assets/ced2974a-e58b-4b87-90d8-13012a9073fd)

### Config / 配置

……

**Comment by Ezalor** [comment]
3.37.3修复了啊，你的版本是3.37.3吗？

**Comment by clionertr** [comment]
V3.37.3修复了，另外你cookie露了

**Comment by li-peifeng** [comment]
升级3.37.3修复了，cookie不要露，很危险的

**Comment by flytutulee** [comment]
3.37.3/3.37.4 挂载115,都报同样的错. “failed get objs: failed to list objs: invalid character 'a' looking for beginning of value
”

**Comment by anwen-anyi** [comment]
> 3.37.3/3.37.4 挂载115,都报同样的错. “failed get objs: failed to list objs: invalid character 'a' looking for beginning of value ”

你估计没更新成功，我更新3.37.4之后 复制、秒传都没问题

**Comment by Lost2049** [comment]
感谢楼上朋友的提醒，已修正；仔细查看了下我用的版本是3.35，待重新安装最新版本再检测。

**Comment by flytutulee** [comment]
> > 3.37.3/3.37.4 挂载115,都报同样的错. “failed get objs: failed to list objs: invalid character 'a' looking for beginning of value ”
> 
> 你估计没更新成功，我更新3.37.4之后 复制、秒传都没问题

我的是mac amd64 版本的   你的是什么版本

**Comment by firimar** [comment]
> > > 3.37.3/3.37.4 挂载115,都报同样的错. “failed get objs: failed to list objs: invalid character 'a' looking for beginning of value ”3.37.3/3.37.4 挂载115,都报同样的错.“Failed Get OBJS： Failed to List OBJS： invalid character 'a' looking for beginning of value ”
> > 
> > 
> > 你估计没更新成功，我更新3.37.4之后 复制、秒传都没问题
> 
> 我的是mac amd64 版本的 你的是什么版本

可以到 http://localhost:5244/@manage/settings/site 设置-站点 检查一下版本 ，3.37.3就修复了

**Comment by Lost2049** [comment]
我重安装最新版Alist与重新配置后，已经恢复正常使用了。感谢大家的指点帮助！
