### ISSUE TITLE
115离线下载报错 

### ISSUE THREAD

**Issue by KleinerSource** [alist-org/alist#7218]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.3

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

离线下载添加磁力链接 前端提示成功 后端报错

failed to add offline download task: invalid character 'd' looking for beginning of value

### Reproduction / 复现链接

前端点击离线下载 115cloud 添加磁力链 确定 

### Config / 配置

![IMG_3807](https://github.com/user-attachments/assets/59d64e52-9284-489e-9da4-b2b2ff81667c)

**Comment by Deepsea-CN** [comment]
同，应该是前两天的问题后115做了变动导致的，等作者适配
我也是报错

failed to add offline download task: invalid character 'd' looking for beginning of value

**Comment by anwen-anyi** [comment]
更新v3.37.4
![image](https://github.com/user-attachments/assets/b8dbee20-de6f-4bb7-9813-e9ed932e209f)

**Comment by GodinGu** [comment]
目前使用的v3.38，还是提示了同样的错误，是设置不对吗？
![image](https://github.com/user-attachments/assets/feb30f4d-783c-4731-bd7e-682128477649)

**Comment by q15751261559** [comment]
我3.39.1也遇到这个问题， 看了下下载链接很明显前面多了个 download导致的报错。。 不知道啥情况

**Comment by GodlikeYang** [comment]
3.39依然有问题，报错 ：failed to add offline download task: invalid character 'd' looking for beginning of value

**Comment by Haooooo2021** [comment]
3.40也有相同问题

**Comment by JIUJIUs** [comment]
同样问题，希望作者可以关注到！
