### ISSUE TITLE
PC端用浏览器访问alist看视频，有些视频看不了

### ISSUE THREAD

**Issue by PHCSJC** [alist-org/alist#7224]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.4

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

重现步骤：下载链接里的这个视频到电脑，用任何播放器打开视频，可以正常播放，说明视频源正常，把这个视频上传到夸克网盘，alist挂载夸克，再用PC的chrome浏览器访问alist，播放此视频，会发现1秒都播放不了，问题重现成功

### Reproduction / 复现链接

https://we.tl/t-cpyfmuiadq

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xxxxxxxxxx",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1,
      "task_persistant": true
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    },
    "upload": {
      "workers": 5,
      "max_retry": 0,
      "task_persistant": false
    },
    "copy": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

**Comment by xhofe** [comment]
https://alist.nn.ci/zh/faq/why.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E8%83%BD%E9%A2%84%E8%A7%88%E8%A7%86%E9%A2%91%E6%88%96%E9%9F%B3%E9%A2%91%E6%96%87%E4%BB%B6

**Comment by PHCSJC** [comment]
@xhofe 明白你的意思，不过奇怪的的，我这个是电视剧，一共21集，只有2集不能正常播放，其他集都没问题

**Comment by a5412398** [comment]
我也出现这样的，用nplayer，webdav进入夸克网盘，可以播放这个电视剧，但是在chrome页面，进入夸克目录，在线无法播放，用potplayer也不行，不知道啥情况。。

**Comment by PHCSJC** [comment]
其实不止这个电视剧，我保存过的别的电视剧也有类似的情况，很奇怪会有那么1、2集播放不了，而如果下载下来又可以正常播放，视频的编码都是一样的
