### ISSUE TITLE
希望可以修改视图模式的逻辑

### ISSUE THREAD

**Issue by mxiaonian** [alist-org/alist#7234]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在设置完视图模式为 列表，或者网格视图，或者图片视图后，再次进入其它文件夹，视图模式又回到了默认的列表视图模式。目前每个文件夹的视图模式都是分开的，可各自设置的。并且开启图片模式之后，前端页面会非常卡~特别是图片比较多的情况下，卡到鼠标都不能动，希望优化图片视图模式，个人更喜欢瀑布流的那种展示方式，希望可以加入这个，现在的虽然也类似，但是单个图片缩放的太小了，展示效果不太好。

### Suggested solution / 实现思路

增加一个全局视图模式的设置按钮，启用全局视图模式修改后覆盖所有文件夹的视图模式为全局设置的模式。

**Comment by xhofe** [comment]
![image](https://github.com/user-attachments/assets/91012c48-03fa-4b51-bb6e-e7b5739d63f7)
