### ISSUE TITLE
115挂载可以读取目录但是无法读取或下载文件

### ISSUE THREAD

**Issue by claw2002** [alist-org/alist#7243]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.4

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

挂载115时可以正常读取目录以及文件属性
![image](https://github.com/user-attachments/assets/b22a9c9e-983f-4aa0-b7dd-153626885783)
但是当点击下载时会提示错误
![image](https://github.com/user-attachments/assets/db392c0c-a8b6-4915-85ca-aeb532f105b8)
最开始以为是cookie过期了，但是更换过后依旧没有解决问题
115的浏览器端是可以正常使用的，应该也不是账号问题
之前是可以正常使用的，大概是前几天出了问题之后就变成这样了
翻了翻issure没看到有类似问题的，不知道能否解答

### Reproduction / 复现链接

由于我是通过alist挂载到本地使用的所以可能无法提供可复现的链接
如果有办法请告知

### Config / 配置

![image](https://github.com/user-attachments/assets/4780a2d0-9b31-49ac-9ed7-08801df34891)
![image](https://github.com/user-attachments/assets/59842968-8fa9-4b66-abf3-5964a97f036c)

**Comment by raxtany** [comment]
the same problem

**Comment by claw2002** [comment]
> the same problem

刚才我经过了各种尝试解决了，下面是我的情况
因为我是从115手机客户端抓取的cookie，所以我一直以为它是没有问题的，或许确实没有问题，但实际上我使用重新登录之后再次抓取的cookie就可以正常使用了
希望能帮到你
I just tried various methods and managed to solve it. Here’s my situation:
Since I grabbed the cookie from the 115 mobile client, I always thought it was fine, and maybe it really was. However, after re-logging in and grabbing the cookie again, it worked properly.
I hope this can help you.

**Comment by dahangda** [comment]
遇到了相同情况

**Comment by dahangda** [comment]
从新加载重新cookie解决了

**Comment by raxtany** [comment]
谢谢你！我现在也能正常使用了。在 2024年9月22日，01:06，claw2002 ***@***.***> 写道：﻿

the same problem

刚才我经过了各种尝试解决了，下面是我的情况
因为我是从115手机客户端抓取的cookie，所以我一直以为它是没有问题的，或许确实没有问题，但实际上我使用重新登录之后再次抓取的cookie就可以正常使用了
希望能帮到你
I just tried various methods and managed to solve it. Here’s my situation:
Since I grabbed the cookie from the 115 mobile client, I always thought it was fine, and maybe it really was. However, after re-logging in and grabbing the cookie again, it worked properly.
I hope this can help you.
