### ISSUE TITLE
Crypt 加密后大文件上传失败

### ISSUE THREAD

**Issue by fmorz** [alist-org/alist#7248]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

本机存储 , Crypt

### Describe the bug / 问题描述

在使用**Crypt** 加密本地的挂载路劲后 ， 通过**webdav**上传**1.8g**左右的文件到加密文件夹 失败

### Reproduction / 复现链接

加密后上传1.8g文件必现

### Config / 配置

![image](https://github.com/user-attachments/assets/c06db810-eeae-44f5-a72a-1c1c9b8944a3)
![image](https://github.com/user-attachments/assets/e3473909-a2df-496d-bdbb-be511f5b9178)
![image](https://github.com/user-attachments/assets/f19bb955-41c1-41b0-8c96-3901d0498a51)
![image](https://github.com/user-attachments/assets/5e0efc26-b664-4dc0-b888-4ca63264948b)

### Logs / 日志

![image](https://github.com/user-attachments/assets/184b8313-226b-4848-bbfd-a8acee759cd4)

**Comment by baobolz** [comment]
还是找自己的原因吧

**Comment by fmorz** [comment]
> 还是找自己的理由吧

就是单纯的运行了alist 程序 ， 非加密文件上传是 ok 的

**Comment by fmorz** [comment]
解决了 ， 中转缓存问题
