### ISSUE TITLE
挂载115 网盘 打开目录 为空 无内容

### ISSUE THREAD

**Issue by zhouLife** [alist-org/alist#7266]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.4

### Driver used / 使用的存储驱动

115 网盘

### Describe the bug / 问题描述

挂载115 网盘 打开目录 为空 无内容 什么都没有 也没有报错信息

### Reproduction / 复现链接

全新安装 都是一样的 

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "em84a098uEPGwEv6",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1,
      "task_persistant": true
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    },
    "upload": {
      "workers": 5,
      "max_retry": 0,
      "task_persistant": false
    },
    "copy": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

### Logs / 日志

![HEy8Cj](https://github.com/user-attachments/assets/28417a0e-3e7b-40fe-8cc7-9ef0fd55d26f)
![tFMQ2n](https://github.com/user-attachments/assets/26b69f85-7845-4e38-9477-c13004ab23f5)
[log.log](https://github.com/user-attachments/files/17129706/log.log)

**Comment by zhouLife** [comment]
过了2天才出现 错误
failed get objs: failed to list objs: {"state":false,"error":"登录超时，请重新登录。","errNo":990001,"request":"\/files?aid=1&asc=1&cid=%2F&fc_mix=0&format=json&limit=56&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0"}: user not login

**Comment by rovexxx** [comment]
> 过了2天才出现 错误 failed get objs: failed to list objs: {"state":false,"error":"登录超时，请重新登录。","errNo":990001,"request":"/files?aid=1&asc=1&cid=%2F&fc_mix=0&format=json&limit=56&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0"}: user not login

今天遇到同样的问题，请问你是怎么解决的？

**Comment by wkABXY** [comment]
遇到了
