### ISSUE TITLE
v3.37.4版本-本地文件复制到115网盘报错: 请升级到最新版本: unexpected error

### ISSUE THREAD

**Issue by crtf1999** [alist-org/alist#7315]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.4

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

- 版本
```bash
# ./alist version
Built At: 2024-09-18 17:25:13 +0000
Go Version: go1.22.4 linux/amd64
Author: Xhofe <i@nn.ci>
Commit ID: 6106a2d4
Version: v3.37.4
WebVersion: 3.37.1
```

- 问题

2024-10-11 11:00:00 再次出现下面的问题

[v3.37.3版本-本地文件复制到115网盘报错: 请升级到最新版本: unexpected error](https://github.com/alist-org/alist/issues/7198)

### Reproduction / 复现链接

添加115存储，更新cookies.

### Config / 配置

```json
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "lk49e1hyMEoDNoBH",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1,
      "task_persistant": true
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    },
    "upload": {
      "workers": 5,
      "max_retry": 0,
      "task_persistant": false
    },
    "copy": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}
```

### Logs / 日志

```txt
^[[31mERRO^[[0m[2024-10-11 13:23:00] COPY /dav/local/live/biliup/upload/2024-10-11/小妤儿/小妤儿.2024-10-11 09_05_01.ing.flv unexpected error
github.com/SheltonZhu/115driver/pkg/driver.init
        <autogenerated>:1
runtime.doInit1
        /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/proc.go:7176
runtime.doInit
        /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/proc.go:7143
runtime.main
        /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/proc.go:253
runtime.goexit
        /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/asm_amd64.s:1695
请升级到最新版本
github.com/SheltonZhu/115driver/pkg/driver.GetErr
        /home/runner/go/pkg/mod/github.com/!shelton!zhu/115driver@v1.0.29/pkg/driver/error.go:143
github.com/SheltonZhu/115driver/pkg/driver.(*UploadInitResp).Err
        /home/runner/go/pkg/mod/github.com/!shelton!zhu/115driver@v1.0.29/pkg/driver/response.go:182
github.com/SheltonZhu/115driver/pkg/driver.CheckErr
        /home/runner/go/pkg/mod/github.com/!shelton!zhu/115driver@v1.0.29/pkg/driver/error.go:154
github.com/alist-org/alist/v3/drivers/115.(*Pan115).rapidUpload
        /home/runner/work/alist/alist/drivers/115/util.go:215
github.com/alist-org/alist/v3/drivers/115.(*Pan115).Put
        /home/runner/work/alist/alist/drivers/115/driver.go:167
github.com/alist-org/alist/v3/internal/op.Put
        /home/runner/work/alist/alist/internal/op/fs.go:561
github.com/alist-org/alist/v3/internal/fs._copy
        /home/runner/work/alist/alist/internal/fs/copy.go:91
github.com/alist-org/alist/v3/internal/fs.Copy
        /home/runner/work/alist/alist/internal/fs/fs.go:73
github.com/alist-org/alist/v3/server/webdav.copyFiles
        /home/runner/work/alist/alist/server/webdav/file.go:59
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleCopyMove
        /home/runner/work/alist/alist/server/webdav/webdav.go:477
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
        /home/runner/work/alist/alist/server/webdav/webdav.go:70
github.com/alist-org/alist/v3/server.ServeWebDAV
        /home/runner/work/alist/alist/server/webdav.go:46
...
```

**Comment by KeithW0726** [comment]
+1

**Comment by jiangtao-guo** [comment]
+1

**Comment by karasfjm** [comment]
+1，前几天还好的

**Comment by Y-ASLant** [comment]
Brown UA今天变了 改UA版本就可以
![image](https://github.com/user-attachments/assets/ead2a43b-69c5-4ad1-814b-86290f84821c)
之前是27.0.3.7

**Comment by fgr178707** [comment]
> Brown UA今天变了 改UA版本就可以 ![image](https://private-user-images.githubusercontent.com/77436463/375655509-ead2a43b-69c5-4ad1-814b-86290f84821c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzUwNDEsIm5iZiI6MTcyODYzNDc0MSwicGF0aCI6Ii83NzQzNjQ2My8zNzU2NTU1MDktZWFkMmE0M2ItNjljNS00YWQxLTgxNGItODYyOTBmODQ4MjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OTgzMGExYmI4NDVjMmRlNDFjNGVjOWQxMTBhYzQxZjRhMzJjMTU1ZGFlZjMwN2ZhMWZmYTg2M2ZiM2Y0NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1ZodhIY0Y1GLP4aZI-nr-jzAi6c_F3JptM-v047TFbw) 之前是27.0.3.7，现在是27.0.5.7

在哪儿改?  需要克隆重新编译?

**Comment by brainiac19** [comment]
+1，且我记得上次115driver更新添加了动态获取版本号的

**Comment by lee1031** [comment]
+1

**Comment by chenleidaye** [comment]
+1，昨天都还能用，刚才用阿里转到115就报错了

**Comment by tnanice** [comment]
能丢个编译好的支持的吗

**Comment by wixb50** [comment]
+1

**Comment by tlzwss** [comment]
+1

**Comment by gitcook** [comment]
+1

**Comment by Espen-Lee** [comment]
+1

**Comment by bilibili2077** [comment]
+1

**Comment by chivehao** [comment]
建议这个配置写到配置文件里或者能通过环境变量覆盖，老是这样也不是事啊

**Comment by gitcook** [comment]
115挂了

**Comment by karasfjm** [comment]
> 看了说明也不会改 在什么位置改 也没找到 老大 能尽快更新下吗 非常感谢

不用急了，115又挂了，估计恢复后ALIST也要更新

**Comment by cnpilot** [comment]
> 简单修复下，应该可以上传了 https://github.com/pongfcnkl/alist/actions/runs/11293555186

大佬  你好  我是deian 系统 用的官方一键安装的  应该怎么使用你发的这个

**Comment by 2450519347** [comment]
> > 简单修复下，应该可以上传了 https://github.com/pongfcnkl/alist/actions/runs/11293555186
> 
> 大佬 你好 我是deian 系统 用的官方一键安装的 应该怎么使用你发的这个

把附件下下来，解压出来把你对应架构的文件替换到你机器/opt/alist里面去

**Comment by xinxinenjoy** [comment]
如果能支持动态获取版本号最好，如果不能自动，是不是考虑增加个配置文件的参数来手动填？会方便一些

**Comment by xun188** [comment]
似乎新版本115cloud无法上传磁力

**Comment by Deepsea-CN** [comment]
> 似乎新版本115cloud无法上传磁力

同，离线任务无法添加了
