### ISSUE TITLE
配置Nginx打开主页后出现MIME类型错误

### ISSUE THREAD

**Issue by ArthurZhou** [alist-org/alist#7322]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.38.0

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

配置nginx后打开主页浏览器控制台报错`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

不使用Nginx直接访问时正常

![image](https://github.com/user-attachments/assets/0c139989-94bc-4cf5-922d-43e65057da8c)

### Reproduction / 复现链接

[临时链接](https://t3.entrycdn-1.us.eu.org/alist/)

### Config / 配置

alist相关配置:
```
{
  "site_url": "/alist",
  
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  
}
```
Nginx配置来自[文档](https://alist.nn.ci/faq/howto.html#how-to-reverse-proxy-with-sub-directory)

**Comment by Simonzhang8** [comment]
我这边打开你的链接 没看到你这个报错啊

**Comment by ArthurZhou** [comment]
重装nginx并清空浏览器缓存后解决了🤔，可能是之前配置的时候改坏了什么东西
