### ISSUE TITLE
failed get objs: failed to list objs, Onedrive的

### ISSUE THREAD

**Issue by myfisher** [alist-org/alist#7355]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

![微信图片_20241017145702](https://github.com/user-attachments/assets/afcfeea6-745b-4672-9dfc-ca8294a95ed6)

想问下，这是什么原因？怎么解决？ 谢谢

**Comment by Simonzhang8** [comment]
怎么配置的？

**Comment by ethuh** [comment]
我也出现了，failed get objs: failed to list objs: Either scp or roles claim need to be present in the token.

OneDrive储存没问题，昨天添加的OneDriveApp的储存就用不了，第一次试这个。
