### ISSUE TITLE
增加HSTS支持

### ISSUE THREAD

**Issue by pover0k** [alist-org/alist#7435]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

HTTP 严格传输安全 (HSTS, RFC 6797) 是一个标头，允许网站在客户端 Web 浏览器中指定并强制执行安全策略。强制执行此策略可以保护安全网站免受降级攻击、SSL 剥离和 Cookie 劫持。它允许 Web 服务器声明一个策略，即浏览器将仅使用安全 HTTPS 连接进行连接，并确保最终用户不会“点击”重要安全警告警示的内容。HSTS 是实现高安全性网站的一项重要安全机制。仅当通过 HTTPS 连接（而非 HTTP）提供服务时，才会遵守 HSTS 标头。

**Comment by yyyytawa** [comment]
请使用NGINX反代手动添加hsts的请求头
