### ISSUE TITLE
联通云盘使用webdav播放3G以上视频提示无法播放

### ISSUE THREAD

**Issue by rianjskis** [alist-org/alist#7627]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.40.0

### Driver used / 使用的存储驱动

联通云盘

### Describe the bug / 问题描述

能正常挂载浏览，电脑使用PotPlayer,webdav挂载播放提示:无法播放，服务器已关闭或地址错误，安卓使用nplayer播放提示：此文件不可播放：500

### Reproduction / 复现链接

我用Alist挂载在openwrt上内网播放，

### Config / 配置

config alist 'config'
        option enabled '1'
        option debug '0'
        option listen_addr '0.0.0.0'
        option listen_http_port '12405'
        option listen_https_port '12406'
        option listen_force_https '1'
        option listen_cert_file '/etc/uhttpd.crt'
        option listen_key_file '/etc/uhttpd.key'
        option site_login_expire '48'
        option site_max_connections '0'
        option db_type 'sqlite3'
        option db_port '0'
        option db_table_prefix 'x_'
        option log_max_size '0'
        option log_max_backups '0'

### Logs / 日志
[31mERRO[0m[2024-12-08 12:31:41] GET /dav/联通云盘/影视/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4 request failed with rsp_code: 130017,rep_desc: 下载的文件已超3.5G
failed get link
github.com/alist-org/alist/v3/internal/op.Link.func1
	/home/runner/work/alist/alist/internal/op/fs.go:260
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.Link
	/home/runner/work/alist/alist/internal/op/fs.go:276
github.com/alist-org/alist/v3/internal/fs.link
	/home/runner/work/alist/alist/internal/fs/link.go:19
github.com/alist-org/alist/v3/internal/fs.Link
	/home/runner/work/alist/alist/internal/fs/fs.go:48
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleGetHeadPost
	/home/runner/work/alist/alist/server/webdav/webdav.go:266
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	/home/runner/work/alist/alist/server/webdav/webdav.go:62
github.com/alist-org/alist/v3/server.ServeWebDAV
	/home/runner/work/alist/alist/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server.WebDAVAuth
	/home/runner/work/alist/alist/server/webdav.go:113
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/home/runner/work/alist/alist/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589
net/http.serverHandler.ServeHTTP
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/server.go:3137
net/http.(*conn).serve
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/server.go:2039
runtime.goexit
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/asm_arm64.s:1222
failed link 
[GIN] 2024/12/08 - 12:31:41 | 500 |  354.361453ms |    192.168.3.76 | GET      "/dav/联通云盘/影视/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4"
[33mWARN[0m[2024-12-08 12:31:41] failed get /��ͨ����/Ӱ��/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4: failed get storage: storage not found; rawPath: /��ͨ����/Ӱ��/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4 
[31mERRO[0m[2024-12-08 12:31:41] GET /dav/��ͨ����/Ӱ��/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4 storage not found; rawPath: /��ͨ����/Ӱ��/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4
failed get storage 
[GIN] 2024/12/08 - 12:31:41 | 404 |     532.592µs |    192.168.3.76 | GET      "/dav/\xc1\xaaͨ\xd4\xc6\xc5\xcc/Ӱ\xca\xd3/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4"
[33mWARN[0m[2024-12-08 12:31:41] failed get /��ͨ����/Ӱ��/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4: failed get storage: storage not found; rawPath: /��ͨ����/Ӱ��/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4 
[31mERRO[0m[2024-12-08 12:31:41] GET /dav/��ͨ����/Ӱ��/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4 storage not found; rawPath: /��ͨ����/Ӱ��/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4
failed get storage 
[GIN] 2024/12/08 - 12:31:41 | 404 |     529.967µs |    192.168.3.76 | GET      "/dav/\xc1\xaaͨ\xd4\xc6\xc5\xcc/Ӱ\xca\xd3/长安十二时辰 (2019)/The.Longest.Day.In.Chang'an.S01.2019.2160p.HQ.WEB-DL.H265.AAC/The.Longest.Day.In.Chang'an.S01E01.2019.2160p.HQ.WEB-DL.H265.AAC.mp4"

**Comment by openegg** [comment]
> 网页上只支持下载3.5G的大小 试试换手机的cookie

怎么换手机的cookie？

**Comment by openegg** [comment]
用手机app试了一下，打开视频时也会先报一个下载超过3.5G的错误，但是之后就开始播放视频了

**Comment by openegg** [comment]
> 使用v3.41.0联通云盘已经恢复可以播放3G以上视频，不知道是联通自己改了还是啥，关闭问题，

3.36版本也没问题了，看来是联通自己良心发现了
