### ISSUE TITLE
优化元信息相关设置

### ISSUE THREAD

**Issue by simpleandstupid** [alist-org/alist#767]
### Description of the feature / 需求描述

现有的目录加密/隐藏功能存在提升空间，
需要一条条的添加路径，
希望能在列表中选择文件夹设置加密，或者隐藏指定文件/文件夹，而不需要进入后台进行繁琐的填写工作

### Suggested solution / 实现思路

现有的选择/多选已经实现了重命名/移动等功能，可以在此菜单上添加加密/隐藏的按钮，自动生成元信息（在后台登录后）

**Comment by Xhofe** [comment]
本程序理念是尽量简化，此需求无限期搁置。

**Comment by Xhofe** [comment]
Available in [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
