### ISSUE TITLE
希望可以添加离线下载功能

### ISSUE THREAD

**Issue by zzy-ac** [alist-org/alist#880]
### Description of the feature / 需求描述

如题

### Suggested solution / 实现思路

用aria吧文件下到服务器，然后上传到alist挂载的这些网盘里

**Comment by senwzz** [comment]
+1

**Comment by x2nbit** [comment]
+1

**Comment by babiqqq** [comment]
+999999999999

**Comment by viqbgrg** [comment]
夸克,迅雷云盘也都支持离线下载,其它的不支持的可以用aria的方案下载

**Comment by Xhofe** [comment]
Available at [v3](https://github.com/alist-org/alist/releases/tag/v3.0.0-beta.0)
