### ISSUE TITLE
希望增加115网盘的支持

### ISSUE THREAD

**Issue by kokobk** [alist-org/alist#894]
### Description of the feature / 需求描述

官网 115.com

使用频率非常高的一个网盘 希望能增加支持

**Comment by 2830514940** [comment]
附议

**Comment by remiliyaScarlet** [comment]
雀食

**Comment by jackcsq** [comment]
附议，强烈恳求

**Comment by litterjim** [comment]
为了18X ?

**Comment by MvCraK** [comment]
+1

**Comment by SheltonZhu** [comment]
搞了一个115的driver，小文件已经可以了，但是找的lib半年没更新了，大文件的上传下载api已经失效了，需要抓包研究一下，或者哪位大佬能提供下api。另外鉴权是使用cookie中的cid，uid，seid实现的，这部分也要待我再研究下是否可以账号密码或者qrcode实现😂。

**Comment by tanpengsccd** [comment]
3.3.0能用了Cookie了,听说使用APP 的Cookie 时间会久一点
<img width="775" alt="image" src="https://user-images.githubusercontent.com/13959880/200172751-68cad88a-cf43-44e2-bf62-3228ea3b6ac6.png">
