### ISSUE TITLE
请求增加对OneDrive/Sharepoint的跨域公开分享链接的支持

### ISSUE THREAD

**Issue by pipixia244** [alist-org/alist#998]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望alist可以支持OneDrive/SharePoint的跨域公开分享链接。
由于官方公开分享链接冗长难记，并且不支持跨域转存，因此希望能支持公开分享链接以达到 简化分享链接/将官方分享链接转换为直链/挂载webdav转存分享 等目的。
该问题存在已久，且目前存在的几种方法均存在不同程度的限制，因此需求应该很广。

### Suggested solution / 实现思路

可参考[OneManager](https://github.com/qkqpttgf/OneManager-php)对于公开分享链接的实现（`sharelink`）
由于OneManager中可以实现`sharelink`的正常列目录与下载，因此推测该提议可行。

### Additional context / 附件

`sharelink.php` https://github.com/qkqpttgf/OneManager-php/blob/master/disk/Sharelink.php

**Comment by jiadelinlang** [comment]
@welcome[bot] 此功能目前已可使用，可挂载同域内分享链接。参考rclone以挂载WebDAV的方式挂载同域分享链接的教程：https://weinb.top/index.php/archives/131/

只要获得同域内其他账号分享的文件夹的访问权限，就可以挂载。更为简洁的描述：https://github.com/Xhofe/alist/issues/460

**Comment by pipixia244** [comment]
> @WELCOME[bot] 此功能目前已可使用，可挂载同域内分享链接。参考rclone以挂载WebDAV的方式挂载同域分享链接的教程：https://weinb.top/index.php/archives/131/
> 
> 只要获得同域内其他账号分享的文件夹的访问权限，就可以挂载。更为简洁的描述：#460

不好意思，我可能没有说清楚，是跨域的公开分享链接，而不是同域分享链接。
